### ISSUE TITLE
e-mail weitere Anlagen

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-org#100]
Wenn ich eine e-mail mit mehreren Anlagen fertig habe, möchte ich manchmal noch ein weiteres Dokument aus dem Ordner als Attachment ergänzen. Im Moment geht das nicht, weil man nur auf lokale Ordner über Anhang zugreifen kann, nicht aber auf die Dokumenten in dem J-Lawyer Dokumentordner. Also - e-mail neu erstellen der fehlende Anlage separat versenden. Eine Änderung wäre hier hilfreich...

**Comment by j-dimension** [comment]
Umgesetzt
