### ISSUE TITLE
[FEATURE] Platzhalter für Datum in der Form: TT. Monat JJJJ

### ISSUE THREAD

**Issue by iradraconis** [jlawyerorg/j-lawyer-org#1000]

**Comment by ReRo-G** [comment]
Ich glaube, dass das Thema schon existiert:
https://github.com/jlawyerorg/j-lawyer-org/issues/827

**Comment by j-dimension** [comment]
In der Tat, danke @ReRo-G

**Comment by j-dimension** [comment]
Verdammt, hätte Ticket #1000 nicht etwas total Spektakuläres sein können? :-)

Hätte mir so etwas wie "Button zum Ansteuern von IoT-fähigen Kaffeevollautomaten" gewünscht.
