### ISSUE TITLE
[BUG] [beA] Beim speichern in Akte werden Umlaute zerstört

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#1003]
**Describe the bug / Fehlerbeschreibung**
(todo: a description of the bug / eine Beschreibung des Fehlers)

**To Reproduce / Schritte zum Nachvollziehen**

(in diesem Fall) eine ausgehende beA-Nachricht per beA-web erstellt in j-l angeklickt und in Akte gespeichert.

Aus sauber in beA (in j-l) dargestellten Umlauten im Betreff und den Dateinamen werden "Sonderzeichen"

Der Dateiname der abgespeicherten bea-Datei hingegen hat korrekte Umlaute.

![image](https://user-images.githubusercontent.com/29924198/101228158-b6858800-369a-11eb-8547-cf2d3a6a3c0e.png)

**Environment / verwendete Umgebung:**
 - OS / Betriebssystem: Win 10 Pro 64
 - j-lawyer.org Version: 1.13.0.5

**Comment by j-dimension** [comment]
Der Server lief unter Linux, korrekt? Bitte dort mal

`echo $LANG`

ausführen und die Ausgabe hier posten.

**Comment by stm9x9** [comment]
ja Linux

```
debian@debian9:~$ echo $LANG
de_DE.UTF-8
```

**Comment by j-dimension** [comment]
Hast Du die Möglichkeit, die selbe - auf einem Windows-Client fehlerhaft angezeigte - Nachricht mal mit einem Linux-Client anzuzeigen?

**Comment by stm9x9** [comment]
ich habe leider keinen Linux-Client zur Verfügung :-(

**Comment by stm9x9** [comment]
da sind alle Umlaute ok

**Comment by j-dimension** [comment]
@stm9x9 sofern möglich, bitte mal eine solche Konstellation erstellen (bspw. Nachricht an Dich selbst, dann in Akte speichern) und mir dann die .bea aus der Akte heraus als Datei speichern und per E-mail senden. Danke!

**Comment by j-dimension** [comment]
siehe E-Mail @stm9x9 vom 30.10.

**Comment by j-dimension** [comment]
via bea wrapper issue 83
