### ISSUE TITLE
[BUG] [beA] in Akte speichern: Schließsymbol X geht nicht

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#1007]
Das X oben links ist funktionslos, nur Abbrechen geht zu Abbrechen. Sowohl beim Speichern beim Versand als auch bei einem nachträglichen aus dem Menü.

![image](https://user-images.githubusercontent.com/29924198/101284682-99a79c80-37e1-11eb-87fe-37d1125f425f.png)

**Comment by j-dimension** [comment]
Das ist beabsichtigt.
