### ISSUE TITLE
[BUG] [Scan] keine Dokumente zu sehen

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#1012]
**Describe the bug / Fehlerbeschreibung**
(todo: a description of the bug / eine Beschreibung des Fehlers)

Mein Scaneingang ist leer.

**To Reproduce / Schritte zum Nachvollziehen**

Ich habe in mein lokales Scan-Verzeichnis zwei Dateien gelegt. 

Dann habe ich auf dem Server /home/debian/j-l_scan angelegt:

![image](https://user-images.githubusercontent.com/29924198/101498568-883ecb80-396c-11eb-8eb6-ae6a8fc6fb4b.png)

Dann wurden auch die Dateien auf den Server übertragen und sind auch da:

![image](https://user-images.githubusercontent.com/29924198/101498240-254d3480-396c-11eb-8e32-05d1ee979c28.png)

aber in j-l bleibt das Fenster leer:

![image](https://user-images.githubusercontent.com/29924198/101498272-3007c980-396c-11eb-9e5c-3eefc096a405.png)

**Environment / verwendete Umgebung:**
 - OS / Betriebssystem: Win 10 Pro 64 / Server: Debian
 - j-lawyer.org Version: 1.13.0.5 / 1.13.0.20

**Comment by stm9x9** [comment]
OK, gelöst. Für alle, die dasselbe Problem haben:

Das obere Fenster ist auf Nullgröße zusammengeschrumpft, man muß den Trennbalken runterziehen:

![image](https://user-images.githubusercontent.com/29924198/101500033-34cd7d00-396e-11eb-9bfa-878d5fa7d52d.png)

Und dann auch den senkrechten Balken, damit die Vorschau wieder zu sehen ist.

**Comment by j-dimension** [comment]
Der Trenner für die Dateiliste ist einfach zu weit oben, einmal runterziehen, die Position wird gespeichert. Ich habe das in 1.14 schon behoben.
