### ISSUE TITLE
[FEATURE] Ordneransicht in Akte merken für nächsten Aufruf

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#1015]
**Is your feature request related to a problem? Please describe. / Welches Problem soll durch die Erweiterung / Verbesserung gelöst werden?**
Description / Beschreibung

Wenn ich mir in einer Akte passend zur aktuellen Prozeßsituation zb den Ordner Sozialgericht (und nur diesen Ordner) anzeigen lasse und später wieder in die Akte zurückgehe, werden wieder alle Ordner (bzw deren Inhalte) angezeigt.

**Describe the solution you'd like / Beschreibe die gewünschte Lösung**
Description / Beschreibung

j-l sollte sich (aktenbezogen und vermutlich sinnvollerweise nutzerbezogen) merken, welche Ordner zuletzt angezeigt wurden und diesen Zustand beim nächsten Öffnen der Akte wiederherstellen.

Das erleichtert das Weiterarbeiten in der Akte enorm.

**Comment by j-dimension** [comment]
Dup von #988
