### ISSUE TITLE
[BUG] Etikettenfilter in Akte nach Neueinstieg in Akte "halb-aktiv"

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#1020]
**To Reproduce / Schritte zum Nachvollziehen**

In einer Akte ein Etikett als Filter auswählen.
Akte verlassen.
Akte wieder reingehen, in Dokumente
die vorher rot gezeichneten Dokumente aus dem Filter sind nicht mehr rot.
es wird auch kein Treffer angezeigt
aber in der Liste ist die Etikette noch ausgewählt

und das Symbol ist auch noch grün

![image](https://user-images.githubusercontent.com/29924198/101682904-8c4e1480-3a64-11eb-9d23-0aea61b9bfa6.png)

**Environment / verwendete Umgebung:**
 - OS / Betriebssystem:
 - j-lawyer.org Version: 1.13.0.5

**Comment by j-dimension** [comment]
Filter beim Laden einer Akte zurücksetzen.
