### ISSUE TITLE
[BUG] Etikettenfilter und Ordneransicht - keine Aktualisierung bzw. an Ordner angepaßt

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#1021]
**Describe the bug / Fehlerbeschreibung**
(todo: a description of the bug / eine Beschreibung des Fehlers)

**To Reproduce / Schritte zum Nachvollziehen**

Akte mit zwei Ordnern A und B.

In A ist ein Dokument mit Etikett bezahlt.

Ich lasse nur Ordner B anzeigen.

Der Tooltip zeigt immer noch an "bezahlt (1)" obwohl in den angezeigten Ordnern kein Dokument mit diesem Etikett ist.

![image](https://user-images.githubusercontent.com/29924198/101681787-fe255e80-3a62-11eb-9103-98554768dac7.png)

Wenn ich den Ordner wieder anzeigen lasse, dann wird das Dokument nicht erneut markiert.

Umgekehrt wird - wenn ich bereits mit einem Etikett filtere - nichts aktualisiert, wenn ich ein weiteres Dokument mit dem Etikett belege. Weder die Zahl der Treffer oben noch wird das neu-etikettierte Dokument rot eingefärbt.

**Abhilfevorschlag**

immer wen ein Etikett oder eine Ordnersichtbarkeit verändert wird, muß der Etikettenfilter neu ausgeführt / aktualisiert werden.

**Environment / verwendete Umgebung:**
 - OS / Betriebssystem:
 - j-lawyer.org Version: 1.13.05

**Comment by j-dimension** [comment]
> Der Tooltip zeigt immer noch an "bezahlt (1)" obwohl in den angezeigten Ordnern kein Dokument mit diesem Etikett ist.

Das würde ich auch so lassen. Sonst müsste man immer alle Ordner selektieren, um die verwendeten Etiketten zu sehen.

**Comment by stm9x9** [comment]
> Das würde ich auch so lassen. Sonst müsste man immer alle Ordner selektieren, um die verwendeten Etiketten zu sehen.

aber will man das denn? Was habe ich denn davon zu sehen, daß in einem nicht angezeigten Ordner ein Dokument mit "bezahlt" ist?

Und ist man nicht eher irritiert wenn man dann nach "bezahlt" filtert und es wird nichts hervorgehoben?

**Comment by j-dimension** [comment]
> Was habe ich denn davon zu sehen, daß in einem nicht angezeigten Ordner ein Dokument mit "bezahlt" ist?

Was habe ich davon, wenn ich erst alle Ordner selektieren muss, um herauszufinden ob ich eine "Rechnung" oder was auch immer in der Akte habe?

**Comment by stm9x9** [comment]
Was habe ich davon zu wissen, daß eine Rechnung in der Akte ist, ich finde sie aber gar nicht, ohne alle Order selektieren zu müssen? 

Und wenn es um die Frage geht: Ist die Akte schon abgerechnet worden? dann ist das doch eine Eigenschaft der Akte und es sollte das Akten(!)etikett "Rechnung gestellt" gesetzt sein.

**Comment by j-dimension** [comment]
> Was habe ich davon zu wissen, daß eine Rechnung in der Akte ist, ich finde sie aber gar nicht, ohne alle Order selektieren zu müssen?

Ähmm... Du weißt dann, dass eine Rechnung in der Akte ist? Das ist doch ein Wert an sich, oder?

> Und wenn es um die Frage geht: Ist die Akte schon abgerechnet worden? dann ist das doch eine Eigenschaft der Akte und es sollte das Akten(!)etikett "Rechnung gestellt" gesetzt sein.

Es ging mir nicht um einen spezifischen Use Case. Es hat für mich einen Wert zu erkennen, dass ein mit Etikett x versehenes Dokument in der Akte ist.
