### ISSUE TITLE
[BUG] Dokumente: manchmal Fettschrift, manchmal nicht

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#1022]
**Describe the bug / Fehlerbeschreibung**
(todo: a description of the bug / eine Beschreibung des Fehlers)

Die Schriftauszeichnung ändert sich ganz komisch.

**To Reproduce / Schritte zum Nachvollziehen**

Einstieg in Dokumente - alles in Fettschrift

![image](https://user-images.githubusercontent.com/29924198/101683917-e9969580-3a65-11eb-9441-69413da2fc50.png)

Etikettenfilter angewandt, die passenden Dokumente werden rot und fett, die anderen bekommen Normalschrift

![image](https://user-images.githubusercontent.com/29924198/101684037-134fbc80-3a66-11eb-9ee3-911bad7d86dc.png)

Filter gelöscht, rote Markierung verschwindet, aber jetzt sind alle ohne Fettschrift

![image](https://user-images.githubusercontent.com/29924198/101684119-311d2180-3a66-11eb-83f6-3fbb48e85eaa.png)

jetzt nehme ich Ordner B weg und die restlichen aus A sind wieder fett.

![image](https://user-images.githubusercontent.com/29924198/101684264-6c1f5500-3a66-11eb-9d6b-e46e3ed57c20.png)

**Environment / verwendete Umgebung:**
 - OS / Betriebssystem: Win 10 Pro 64
 - j-lawyer.org Version: 1.13.05

**Comment by j-dimension** [comment]
Dup von #968
