### ISSUE TITLE
[FEATURE] Dokument-Kontextmenü: "als E-Mail senden" und Icon

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#1028]
**Is your feature request related to a problem? Please describe. / Welches Problem soll durch die Erweiterung / Verbesserung gelöst werden?**
Description / Beschreibung

![image](https://user-images.githubusercontent.com/29924198/101686079-d89b5380-3a68-11eb-89ff-bcba9cc0c689.png)

es wird nicht ganz klar, daß mit senden / als pdf senden eine E-Mail gemeint ist

**Describe the solution you'd like / Beschreibe die gewünschte Lösung**
Description / Beschreibung

umbenennen in "als E-Mail senden" / "als pdf mit E-Mail senden"
und statt des Pfeils ein @ oder so.

**Comment by j-dimension** [comment]
Werde nur das Icon anpassen.
