### ISSUE TITLE
[FEATURE] Dokumente: Etikettenfeld nicht größer als nöig

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#1030]
![image](https://user-images.githubusercontent.com/29924198/101686915-03d27280-3a6a-11eb-8dac-9fc467f31ddf.png)

da unten ist viel grauer Platz. Wenn das an die Etikettenzeilen angepaßt sein würde, hätte man oben mehr Platz für Dokumente und die Vorschau

**Comment by j-dimension** [comment]
Dup von bereits umgesetztem #991
