### ISSUE TITLE
doppelten Eintrag einer Person vermeiden[FEATURE]

### ISSUE THREAD

**Issue by RobertT01** [jlawyerorg/j-lawyer-org#1031]
**NOTE: Please search existing tickets to avoid duplicates **
**HINWEIS: Bitte vorab die Ticketsuche verwenden, um Doppeleinträge zu vermeiden **

habe keinen Eintrag gefunden

**Is your feature request related to a problem? Please describe. / Welches Problem soll durch die Erweiterung / Verbesserung gelöst werden?**
Description / Beschreibung
ES kommt vor, dass zu einer Person mehrere Stammdaten eingetragen werden. Diese können dann auch nur mit Umwegen gelöscht werden, falls jeder Eintrag einer Akte zugeordnet wird (was richtig ist).
**Describe the solution you'd like / Beschreibe die gewünschte Lösung**
Description / Beschreibung
Eine Hinweis wäre schön, wenn man eine Person mit einen Namen anlegt und dieser Name schon in der Datenbank vorhanden ist, so nach der Devise, willst Du die Person wirklich zweimal anlegen 
**Additional context / Sonstiges **
Sonstige Informationen / Screenshots / ...

**Comment by j-dimension** [comment]
Duplikat von #654
