### ISSUE TITLE
[FEATURE] bei Beteiligtem hinterlegte Verschlüsselung im Email-Versand-Dialog kenntlich machen

### ISSUE THREAD

**Issue by iradraconis** [jlawyerorg/j-lawyer-org#1034]
mir geht das manchmal durch, dass ein Mandant die Emails verschlüsselt haben möchte. Es sind tatsächlich nur wenige meiner Mandanten. Ich lasse mir das vorher immer bestätigen, aber darum geht es hier nicht :). 
Es wäre jedenfalls schön wenn im Email-Versand-Dialog entweder automatisch die Verschlüsselung aktiviert wird, wenn die Verschlüsselung bei einem Beteiligten aktiviert ist oder aber wenn in dem Dialog wenigstens neben einer EmailAdresse ein Icon erscheinen würde, wenn für denjenigen ein Kennwort hinterlegt ist. So wüsste der Anwender jedenfalls auf den ersten Blick, dass der verschlüsselte Versand auszuwählen ist.

**Comment by Maz111111** [comment]
Ist ein #504 Duplikat

**Comment by j-dimension** [comment]
danke, @Maz111111

**Comment by iradraconis** [comment]
> danke, @Maz111111

Ich hätte schwören können, dass es noch kein Ticket gibt! Ich mache das nicht absichtlich ;)

**Comment by j-dimension** [comment]
Naja, die Github-Suche ist nicht ganz so komfortabel wie bei den Suchmaschinen...

**Comment by iradraconis** [comment]
> Naja, die Github-Suche ist nicht ganz so komfortabel wie bei den Suchmaschinen...

werde zukünftig intensiver suchen ;)
