### ISSUE TITLE
[BUG] Notizen: Testumbruch ist falsch / vertikales Scrollen

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#1035]
**Describe the bug / Fehlerbeschreibung**
(todo: a description of the bug / eine Beschreibung des Fehlers)

In Notizen werden längere Zeilen nicht richtig umgebrochen, es kommt zu vertikalem Scrollbalken

**To Reproduce / Schritte zum Nachvollziehen**

1. neue Notiz mit langer Zeile bzw längerem Absatz

![image](https://user-images.githubusercontent.com/29924198/101940712-2fc73280-3be7-11eb-8184-f4db316aa453.png)

2. nach dem Speichern anschauen und Fenster breit ziehen:

![image](https://user-images.githubusercontent.com/29924198/101940780-4bcad400-3be7-11eb-920e-3d0674290f5d.png)

Es wird am Ende des Fensters umgebrochen. Egal wo das im Text ist. "Neue" ist dann zb noch auf der ersten Zeile. Weil Platz da ist. Das erscheint auch korrekt, da es in html ein Paragraph ist:

![image](https://user-images.githubusercontent.com/29924198/101940854-6c932980-3be7-11eb-87d3-2375db6827d3.png)

3. aber wenn man das Fenster wieder auf üblichere Breiten zurückstellt, dann verschwindet ein Teil des Textes rechts im Scrollbereich.

![image](https://user-images.githubusercontent.com/29924198/101941287-0c50b780-3be8-11eb-97ef-5257f7d9c929.png)

Das ist gerade für die Notizen unschön, die man ja schnell auf einmal lesen will.

**Environment / verwendete Umgebung:**
 - OS / Betriebssystem: Win 10
 - j-lawyer.org Version: 1.13.05

**Comment by j-dimension** [comment]
Die Drittkomponente verhält sich so wie erwartet, solange man die Breite des Elementes größer als die minimale Breite belässt, welche sich das Element beim Rendern "wünscht". Das ist hier die Breite der Toolbar plus etwas Aufschlag. 

Darunter kommt es zu dem von Dir beschriebenen Verhalten.

Ich müsste hier eine Änderung der Drittkomponenten vornehmen, was ich angesichts des Aufwand/Nutzen-Verhältnisses nicht tun werde.
