### ISSUE TITLE
[BUG] Gelöschter Unterordner taucht nach Löschen noch auf

### ISSUE THREAD

**Issue by socram70** [jlawyerorg/j-lawyer-org#1037]
**NOTE: Please search existing tickets to avoid duplicates **
**HINWEIS: Bitte vorab die Ticketsuche verwenden, um Doppeleinträge zu vermeiden **

**Describe the bug / Fehlerbeschreibung**
(todo: a description of the bug / eine Beschreibung des Fehlers)

**To Reproduce / Schritte zum Nachvollziehen**

1. Go to / Gehe zu '...'
Nach einem Löschen des Ordners und nach einem Klick auf das "Baumstruktur-Icon", um ein Dokument zu verschieben, taucht der zuvor gelöscht Ordner nach wie vor auf. Ein schließen und Neu-Öffnen der Akte behebt das Problem.
2. Klicke auf / Click on '....'
4. Error message / Fehlermeldung: '...'

**Expected behavior / Erwartetes Verhalten**
Eine Beschreibung des erwarteten Verhaltens.
Der gelöschte Ordner sollte nach dem Löschen nicht mehr auftauchen.

**Screenshots**
Falls relevant, Screenshot beifügen.
![grafik](https://user-images.githubusercontent.com/60073801/102006342-ce0ae380-3d20-11eb-94f3-2c6d0e6337c7.png)

**Environment / verwendete Umgebung:**
 - OS / Betriebssystem: Microsoft Windows [Version 10.0.18363.1256]
 - j-lawyer.org Version: 1.13.05 (Client) Ubuntu 18.04.5 mit Server 1.13.0.20 (Server - auch wenn das ziemlich sicher kein Serverproblem sein wird)

**Additional context / Sonstiges**

**Comment by j-dimension** [comment]
Duplikat von #1025
