### ISSUE TITLE
[FEATURE] Order-Handling optimieren: Nur diesen Ordner anzeigen

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#1039]
![image](https://user-images.githubusercontent.com/29924198/102229192-c8152e00-3eeb-11eb-9a50-84e7eea3672c.png)

weiteren Menüpunkt im Dreipunkt-Menü eines Ordners: Nur diesen Ordner anzeigen

Damit kann man schnell und ohne Umweg den Inhalt nur eines Ordners anzeigen lassen.

**Comment by j-dimension** [comment]
Hamburger-Menü, Kontextmenüeintrag = 2 Klicks

Nichts auswählen-Knopf, Ordner anklicken = 2 Klicks

Ich sehe den Effizienzvorteil nicht.

**Comment by stm9x9** [comment]
Lieber wäre mir auch einfach Rechtsklick = nur diesen Ordner anzeigen. Das dürfte aber vielleicht nicht selbsterklärend sein.

Aber auch sonst sehe ich einen Effizienzvorteil: Man macht diese beiden Klicks im Kontextmenü des Ordners, man ist also an einer Stelle. Und zwar bei dem Objekt, daß man benutzen will. Klick, eine Idee nach rechts und sofort wieder Klick.

Und rein "intellektuell" ist es nur ein "aktionsauslösender" Klick (nämlich der zweite), während nichts-auswählen bereits gedanklich Mehrarbeit erfordert: "also erstmal mit der Maus weg von dem gewünschten Ordner und ALLE deselektieren, obwohl ich ja gar nicht alle deselektieren will, sondern nur 'alle anderen'. Und dann wieder zurück und dann erst den gewünschten Ordner selektieren". Da kostet IMHO mehr (unbewußte) "Gedanken-Zyklen".

Und es ist auch schlicht mehr Mausstrecke zu bewältigen.

**Comment by j-dimension** [comment]
Okay, muss dann aber warten. Im Vergleich der Prioritäten ist das hart an der Grenze.

**Comment by Maz111111** [comment]
ob das mit dem Rechtsklick jetzt der Durchbruch ist, weiß ich zwar nicht ... aber ich muss @stm9x9 irgendwie Recht geben...

Nachdem ich die Geschichte mit den Buttons über den Ordnern verinnerlicht hatte, nutze ich sie auch ... aber intuitiv ist irgendwie anders...das ist allenfalls als konstruktive Kritik gemeint - wenn eventuell der konstruktive Anteil auch fehlt :-D

Es funktioniert ja extrem gut... wenn man weiß wie ... aber so ein Anwalt ist eben kein IT-FummelTyp ... Da muss es einfach und unkompliziert sein. Und am Besten eben so wie immer und in jedem anderen Programm auch.

Und genau da kommt dann die Gedankenarbeit ( "Gedanken-Zyklen") ins Spiel...ich verweise mal auf meinen Wunsch, die Datei nach Verschieben in einen ausgeblendeten Ordner sofort auszublenden. Ja es geht anders, Und wenn man erst mal mitbekommen hat wie, ist es auch irgendwie cool. Aber es ist eben ungewohnt...Und jedes mal wenn man aus seinem gewohnten "Was erwarte ich von der Software für ein Verhalten" - Muster (also aus der Komfort-Zone) raus muss, kostet das GedankenZyklen und damit Zeit. Es ist nicht nur der eine Moment, sondern eine sehr lange Lernarbeit, weil man einfach etwas anderes gewohnt ist und bei ein und der selben Aktion immer wieder neu überlegen muss: "ja, das geht irgendwie ... wie war das doch gleich..ach ja, so ging das". 

Und insofern mögen zwar die Anzahl der Klicks gleich sein. Aber die gewünschte Rechtsklick-Methode erscheint auch mir intuitiver. Ich würde eine solche Aktion auch eher im Kontextmenu erwarten und empfinde (im tatsächlichen Sinne eines reinen Empfindens) die von Dir beschriebene Methode eher als work-around. Das ist aber nur ein Gefühl...schwer zu beschreiben.

In der 2.0 ist es sicher ganz gut aufgehoben, weil es ja anders geht....

**Comment by j-dimension** [comment]
Dieses gesamte Ordnerfeature ist für mich eine Zeitsenke ohne Ende. 

Mein Learning an dieser Stelle ist, in Zukunft stärker auf mein Bauchgefühl zu hören und wenn mir etwas zu komplex vorkommt, es einfach nicht zu implementieren, auch wenn es Anwenderwunsch ist. Der Wunsch, mehrere Ordner gleichzeitig zu sehen, macht hier so viele Sonderszenarien auf und führt dazu, dass es nicht mehr intuitiv ist. 

Auch hier ist das Ordnerkonzept simpel gehalten, und diesen Stand hätte ich in j-lawyer.org wesentlich einfacher und schmerzfrei erreichen können: https://www.youtube.com/watch?v=7V8ohnVqEwo

**Comment by Maz111111** [comment]
Bitte nicht ganz so doll in die Tischkante beißen.

Das Feature Inhalte mehrerer Ordner gleichzeitig sichtbar und bearbeitbar zu haben, ist outstanding! 

Aus meiner Sicht ist dies das ganzen Tohuwabohu schon noch wert.

Also 1000 (in worten: Tausend) Dank noch mal für Deine Mühe und Geduld!

**Comment by Mucki526** [comment]
Habe die Ordner sehnlichst erwartet seit mehreren Versionen, bin von der Umsetzung begeistert und nutze sie schon jetzt wie kein andere Feature (bringt Ordnung in die elektronische Akte). Das ganze mit Drag&Drop (in Planung) zur Verteilung von Dokumente in den Ordner und Funktionen auf der Rechten Maustaste ist ein echter Quantensprung für uns.

**Comment by iradraconis** [comment]
Schließe mich den Vorrednern an!

**Comment by stm9x9** [comment]
Je öfter ich mit den Ordnern arbeite, um so mehr kommt mein "Fingergefühl" zu dem Schluß: Ein schneller Doppelklick auf einen Ordner sollte diesen alleine anzeigen. Nix mit extra in ein Untermenü wie ursprünglich vorgeschlagen. Sind dann rein zähltechnisch immer noch zwei Klicks, aber für Hand und Maus doch was ganz anderes :-)

**Comment by Dickmaulruessler** [comment]
> Dieses gesamte Ordnerfeature ist für mich eine Zeitsenke ohne Ende.
> 
Ich muss den Wert dieser Ordner auch noch einmal positiv hervorheben! Es ist wirklich wichtig, dass man da den Überblick hat und das gewährleistet deine hervorragende Umsetzung! Danke!

**Comment by Dickmaulruessler** [comment]
> > Dieses gesamte Ordnerfeature ist für mich eine Zeitsenke ohne Ende.
> 
> Ich muss den Wert dieser Ordner auch noch einmal positiv hervorheben! Es ist wirklich wichtig, dass man da den Überblick hat und das gewährleistet deine hervorragende Umsetzung! Danke!

Ich freue mich wirklich jedes Mal wieder über dieses schon jetzt sehr leistungsfähige Ordner-Feature (und kleine Verbesserungen sind auch toll)

**Comment by Dickmaulruessler** [comment]
ich wollte gerade gucken, wie der Diskussionsstand zu diesem Thema ist...
...und .... schwupps.... es ist schon erledigt! 
Vielen Dank, Jens!
