### ISSUE TITLE
Akte als PDF exportieren

### ISSUE THREAD

**Issue by j-dimension** [jlawyerorg/j-lawyer-org#104]
aus dem Community Meeting vom 11.03.2016: es wurde ein Export einer Akte inklusive aller Metadaten und Dokumente als EIN PDF-Dokument angeregt
Option: Aktendaten ja/nein
Option: alle Dokumente oder gewählte Dokumente

**Comment by Dickmaulruessler** [comment]
Angeregt durch dies
https://www.j-lawyer.org/?topic=gesamte-akte-drucken#post-5101
finde ich, dass man sich über dieses Feature noch einmal Gedanken machen könnte. 

Mögliche Anwendungsfälle würde ich hierin sehen:

– Dem Mandanten eine komplette digitale Aktenkopie übergeben.
– Selbst die Akte auf jedem belieben Gerät lesen zu können, wo dann nur ein PDF-Viewer benötigt würde. Ohne dass eine JL-Installation benötigt wird. Z.B. die Akte auf einem Stick mitnehmen und dann zu Hause oder im Urlaub an einem beliebigen PC lesen…

**Comment by Porfavorio** [comment]
Ich kann mir nur anschließen. Danach hatte ich auch gesucht. Angenommen man ist bei Gericht und möchte hier schnell einen digitalen Überblick haben oder man möchte z.B. einem Terminsvertreter Unterlagen zukommen lassen.

**Comment by stm9x9** [comment]
Bei einer Auswahl der Dokumente sollte man dann auch unbedingt orderweise hinzufügen oder weglassen können.

**Comment by stm9x9** [comment]
ich denke, gerade bei den obigen Ideen ist es sehr wichtig. Ein Terminsvertreter bekommt bitte nicht meine Kommunikation mit der RSV oder die Beratungshilfeunterlagen ...

**Comment by niciti** [comment]
Hallo,

wie ich sehe gibt es ja durchaus ein gewisses Interesse an dem Thema. Wir könnten uns auch vorstellen das Feature gemeinsam mit anderen zu finanzieren.

Würden sich noch mehr Personen/Kanzleien daran beteiligen? 

LG,

**Comment by j-dimension** [comment]
@niciti das Drucken ist abhängig von den Möglichkeiten von LibreOffice (was intern für den Direktdruck verwendet wird) oder von der Möglichkeit, ein Dokument in ein PDF konvertieren zu können. Es wird also Formate in der Akten geben können, die nicht gedruckt werden können. Ein Dialog könnte diese aber eindeutig benennen, sodass der Nutzer informiert ist. 

Allgemein wären folgende Arbeiten zu erledigen:

- [ ] Button für Gesamt-Export als PDF
- [ ] alle Dokumente auf deren Exportierbarkeit / PDF-Konvertierbarkeit prüfen
- [ ] nicht konvertierbare Dokumente ausgeben
- [ ] alle Dokumente nach PDF konvertieren
- [ ] Gesamt-PDF generieren
- [ ] Downloaddialog mit Auswahl des Zielverzeichnisses
- [ ] Fortschrittsanzeige (v.a. für umfangreiche Akten)

optional:

- [ ] Darstellung aller Dokumente als Auswahlliste (vor dem Konvertierungsvorgang), um einzelne Dokumente ausschließen zu können
- [ ] Generieren einer Inhaltsverzeichnisseite im Gesamt-PDF, über welche man schnell zu bestimmten Dokumenten springen kann
- [ ] PDF-Konvertierung für E-Mails ermöglichen
- [ ] PDF-Konvertierung für beA-Nachrichten ermöglichen

@niciti bitte mal drüberschauen und ergänzen / reduzieren, dann schaue ich mal was das für ein Aufwand wäre.

**Comment by Porfavorio** [comment]
> Hallo,
> 
> wie ich sehe gibt es ja durchaus ein gewisses Interesse an dem Thema. Wir könnten uns auch vorstellen das Feature gemeinsam mit anderen zu finanzieren.
> 
> Würden sich noch mehr Personen/Kanzleien daran beteiligen?
> 
> LG,

Einen kleinen Beitrag könnte ich mir auch vorstellen.

**Comment by Dickmaulruessler** [comment]
> 
> Allgemein wären folgende Arbeiten zu erledigen:
> 

@j-dimension könntest du bei Gelegenheit bitte den Zeitaufwand schon einmal auflisten, damit man die Kosten grob überblicken kann?

**Comment by niciti** [comment]
Wir würden gerne unseren Beitrag leisten, wenn es genauere Zahlen zu dem notwendigen Aufwand gibt.

**Comment by j-dimension** [comment]
@Dickmaulruessler @niciti ich habe Aufwandsschätzungen oben eingefügt. 50% würden auf mich gehen.

**Comment by Dickmaulruessler** [comment]
Sorry, ich wäre beim Sponsorn raus, da ich im letzten Jahr schon zwei Projekte gesponsort habe. 
Ich finde das hier aber interessant und würde es gerne mit Ideen (und Fragen) begleiten.

@j-dimension was wäre denn, wenn E-Mail und beA-Konvertierung nicht dabei wären? Gar nichts? Oder ein Platzhalter mit dem Betreff / Absender? Hmmmm... Könnte das Sinn machen, Mail/beA wegzulassen?
Und was wäre bei beA mit den ganzen "Müll-Dateien" (XML, HTML-Datein, dumme Informationsblätter vom Gericht), die immer mitgeschickt werden. Die könnte man dann manuell ausschließen, andernfalls wären auch die dabei, oder?

**Comment by j-dimension** [comment]
@Dickmaulruessler ich könnte mir vorstellen, beim optionalen Punkt _"Darstellung aller Dokumente als Auswahlliste (vor dem Konvertierungsvorgang), um einzelne Dokumente ausschließen zu können"_ die Dateien anhand Ihres Typs schnell an- und abwählbar zu gestalten, so kann man mit wenigen Klicks alle Signaturen, XML-Dateien etc. ausschließen. Bei Sekunde 65 siehst Du das hier ganz gut: https://youtu.be/cJSSjnrgGIk?t=65

Alles was nicht nach PDF konvertiert wird, würde ich im Original mit speichern, sodass man bspw. die E-Mails dann im Thunderbird anschauen könnte.

**Comment by Dickmaulruessler** [comment]
> 
> Alles was nicht nach PDF konvertiert wird, würde ich im Original mit speichern, sodass man bspw. die E-Mails dann im Thunderbird anschauen könnte.

beA bleibt dann aber komplett beA oder könnte man die darin enthaltenen PDFs auch ohne der optionalen PDF-Konvertierung sehen?

**Comment by j-dimension** [comment]
> beA bleibt dann aber komplett beA oder könnte man die darin enthaltenen PDFs auch ohne der optionalen PDF-Konvertierung sehen?

Alle Anlagen, die bereits PDF sind, oder wo es schon eine PDF-Konvertierung gibt, würden natürlich mit in das PDF aufgenommen werden. Aufwändig ist das PDFen der Nachricht an sich, des Journals, des Laufzettels, der Signaturprüfung, des VHN, ...

**Comment by iradraconis** [comment]
Da die Frage auch bei Facebook kam und ich auf dieses Ticket verwiesen habe, habe ich noch einmal hineingeschaut. Für uns wäre das auch ein tolles und wichtiges Feature.

**Comment by j-dimension** [comment]
Von @niciti gab es nach meiner Schätzung keine weitere Rückmeldung. Vielleicht ist das einfach untergegangen.

**Comment by iradraconis** [comment]
@j-dimension dann würde ich mich auch beteiligen, um die Sache und das Projekt voran zubringen. Die oben genannten Features finde ich alle gut, gerade auch die optionalen. Ich frage gerade auch einen Kollegen an, ob er sich beteiligt.

**Comment by Dickmaulruessler** [comment]
> Bei einer Auswahl der Dokumente sollte man dann auch unbedingt orderweise hinzufügen oder weglassen können.

Ich hatte das damals in meiner Antwort kritisch hinterfragt. Sorry, ich glaube ich möchte das wieder rückgängig machen. 
Diese Ordner (mit all seinen Funktionen) sind einfach wunderbar und ich nutze die **immer**!

Auch für den PDF-Export wäre die Ordnerfunktion glaube ich wirklich auch sehr praktisch. @j-dimension könntest du den optionalen Teil bitte oben zeitlich noch einmal einschätzen? 

Ich muss mich finanziell momentan etwas zurückhalten, wäre unter Vorbehalt anteilig aber wohl auch dabei.

**Comment by iradraconis** [comment]
Eine Ergänzung wäre sicherlich noch wünschenswert: ab einer bestimmten Dateigröße wird die Datei gesplittet.

**Comment by j-dimension** [comment]
Dann möchte ich alle, die sich beteiligten möchten, um eine kurze Mail an mich bitten (info@ ...). Danke!

**Comment by j-dimension** [comment]
Prototyp:


https://github.com/jlawyerorg/j-lawyer-org/assets/3729754/85a6e64e-7032-4e70-a24d-9fa8923382b9

**Comment by j-dimension** [comment]
Beispiel mit ca. 60 Dokumente, die zusammengefasst ca. 340 Seiten ergeben. Übersichtsseite, Inhaltsverzeichnis (jetzt in hübscher :-) ), Navigation, Seitenzahlen, Unterstützung von E-Mails und beA-Nachrichten. 

Fortschrittsanzeige etwas nützlicher gestaltet (es werden nur noch Fehler ausgegeben, da die Liste bei umfangreichen Akten sonst sehr lang wird). 

https://github.com/user-attachments/assets/47609354-009d-4142-b0f9-3199d773221a

**Comment by iradraconis** [comment]
Ausprobiert… Im 1. Test ist im Inhaltsverzeichnis etwas verkehrt. Die eine PDF taucht doppelt auf mit Seite 11. Ich teste die kommenden Tage noch weiter mit verschiedenen Dokumenten.

![grafik](https://github.com/user-attachments/assets/b03ad3e3-ff94-47d2-86df-d7f8ffdfa8db)

Eine Anregung hätte ich. Es wäre toll, wenn es hier noch einen Haken gäbe "PDF auch in Akte speichern". Oft erstellen wir Aktenauszüge und möchten die PDF dann per  Mail an den Mandanten schicken. 

![Bildschirmfoto vom 2024-07-23 07-37-37](https://github.com/user-attachments/assets/43fa8fe0-03df-48ed-9746-b934d305b87f)

Eine Frage: wird das Inhaltsverzeichnis auch verlinkt sein? Also dass direkt zur Seite gesprungen werden kann?

**Comment by Dickmaulruessler** [comment]
> 
> Eine Frage: wird das Inhaltsverzeichnis auch verlinkt sein? Also dass direkt zur Seite gesprungen werden kann?

Ja, das wäre gut!

**Comment by j-dimension** [comment]
> Eine Frage: wird das Inhaltsverzeichnis auch verlinkt sein? Also dass direkt zur Seite gesprungen werden kann?

Es gibt Lesezeichen zu jedem Dokument, sodass man direkt springen kann. Ist im Video links zu sehen, wenn das Dokument geöffnet ist.

**Comment by iradraconis** [comment]
Sorry ich hab mich falsch ausgedrückt. Lesezeichen sind drin, das stimmt. Das ist super so. Ich meinte, dass das Inhaltsverzeichnis, dass erstellt wird, Links enthält, eine Art Hyperlink, um innerhalb des Dokuments zu springen. Oder ist das technisch nicht umsetzbar.. Ist nur eine kleine Sache und wahrscheinlich eh überflüssig, durch die Lesezeichen im Dokument.

**Comment by Dickmaulruessler** [comment]
Je nachdem wie man es nutzt, wäre mal das eine mal das andere sinnvoll. Beim Betrachten im Hochformat auf einem relativ kleinen Tablet wäre der Platz eng und die Lesezeichen nicht praktisch. Auch glaube ich das "normale" Nutzer Lesezeichen in PDF eher nicht kennen, viele glaube ich sogar noch niemals genutzt haben. 
Wenn man das hingegen am großen Notebook betrachtet, sind die Lesezeichen natürlich sehr cool! 

Falls die echten Hyperlinks (parallel zu den Lesezeichen) mit vertretbarem Aufwand umsetzbar sind, würde ich auch sehr dafür plädieren.

**Comment by j-dimension** [comment]
Das ist ehrlich gesagt ziemlich komplex. Der Code fügt jetzt 
- 1 Dokument mit den Aktenkopfdaten
- 1 Dokument mit dem Inhaltsverzeichnis
- n Dokumente aus der Akte
zu einem PDF zusammen. Dabei können Lesezeichen bereits auf Seiten verweisen, die noch nicht existieren (zum Zeitpunkt der Erstellung des Inhaltsverzeichnisses gibt es im selben Dokument die anderen Inhalte noch nicht). 

Mit Hyperlinks geht das nicht und ich müsste
- Die Länge des Inhaltsverzeichnisses berechnen (Seitenanzahlen)
- ein Gesamtdokument mit Aktenkopfdaten, der richtigen Anzahl leerer Seiten für das Inhaltsverzeichnis), den Dokumenten aus der Akte erstellen
- dann die leeren Seiten bearbeiten und ein Inhaltsverzeichnis mit Hyperlinks einfügen

**Comment by iradraconis** [comment]
Also für mich angesichts des damit verbundenen Aufwands nicht erforderlich.

**Comment by j-dimension** [comment]
![grafik](https://github.com/user-attachments/assets/4f0be296-932c-413b-bf2c-f522e0a9d7aa)

Optionen zum lokalen Speichern / Speichern zur Akte. Einstellungen werden nutzerspezifisch gespeichert und wiederhergestellt.

**Comment by j-dimension** [comment]
TOC beginnt erst bei Seite 2 - nacharbeiten

**Comment by j-dimension** [comment]
war beim Testen nur verwirrt :-)

**Comment by Dickmaulruessler** [comment]
Cool!

**Comment by Dickmaulruessler** [comment]
Ich habe das getestet und finde es super! Merci!

Zwei Anmerkungen:

- im Dateinamen hielte ich eine textliche Ergänzung für sinnvoll z.b. "EXPORT" oder "PDF" oder ähnlich (So wie sich bei E-POST auch ein Hinweis darauf im Dateinamen befindet).

- Könnte auch ein Lesezeichen für die 1. Seite und auch für das Inhaltsverzeichnis erstellt werden? 
Aktuell beginnen die Lesezeichen erst danach und man kommt dort momentan nur durch Scrollen hin.
