### ISSUE TITLE
[BUG] Historie nur minutengenau?

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#1040]
![image](https://user-images.githubusercontent.com/29924198/102230438-2a226300-3eed-11eb-9c14-f8cdf1c7050c.png)

Die Änderungen an der Akte werden nur minutengenau angezeigt. Werden sie auch nur so abgespeichert?

Die drei Änderungen oben Eingang Protokoll habe ich vor aMdt zK gemacht, sie stehen aber jetzt da drüber.

oder hier:

![image](https://user-images.githubusercontent.com/29924198/102230774-90a78100-3eed-11eb-8e71-2fe7463c1c5f.png)

ich habe ENTWURF erst gesetzt und dann wieder entfernt, nicht andersrum

Können die sekundengenau abgespeichert und auch angezeigt werden? ggf aus Platzgründen nur per Tooltip?

**Comment by j-dimension** [comment]
Wir sekundengenau gespeichert. Hier wäre wohl die Sortierung anzupassen, schaut evtl. nur auf den dargestellten Wert anstelle des gespeicherten Wertes.

**Comment by j-dimension** [comment]
Anzeigegenauigkeit  erhöht, Wochentag aufgenommen

![grafik](https://user-images.githubusercontent.com/3729754/118555364-e7e2a380-b762-11eb-8f13-c9691758dc7f.png)
