### ISSUE TITLE
[FEATURE] Dokumente nach Erstellen automatisch öffnen (als Option)

### ISSUE THREAD

**Issue by iradraconis** [jlawyerorg/j-lawyer-org#1047]
(Ich glaube das gibt es noch nicht als Ticket.)

Es könnte eine client-seitige Option geben, die dafür sorgt, dass Dokumente nach deren Erstellen automatisch zur Bearbeitung geöffnet werden.

**Comment by j-dimension** [comment]
Duplikat von #1199
