### ISSUE TITLE
[FEATURE] [bea] alle Dokumente einer Nachricht auf einmal importieren

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#1048]
**Is your feature request related to a problem? Please describe. / Welches Problem soll durch die Erweiterung / Verbesserung gelöst werden?**

Wenn per bea eine Akteneinsicht kommt, dann sind da fünfzig, sechzig oder gar neunzig Dateien drin. Die müssen in die Akte für den Aktenviewer. Aktuell kann man die nur über die normalen Wege importieren, das heißt: bis zu 90mal den Namen abnicken bzw sogar verändern, weil das Datum vorne wieder weg muß, damit die Dateien mit dem SDS übereinstimmen.

**Describe the solution you'd like / Beschreibe die gewünschte Lösung**

Ich weiß noch nicht an welcher Stelle dies sinnvoll ist, aber wir brauchen eine Möglichkeit alle Dokumente aus einer Nachricht ohne Umbenennung in einem Rutsch in die Akte zu übernehmen. Damit auf jeden Fall verhindert wird, daß versehentlich 90 Nachrichten den Hauptordner zumüllen, sollte auch zwingend ein Unterordner ausgewählt werden müssen, mit der Option in in diesem Vorgang gleich zu erstellen.

**Comment by j-dimension** [comment]
Anhänge werden unverändert in die Akte übernommen. XJustiz-SDS wird mit Präfix versehen, da die Datei in jeder beA-Nachricht den selben Namen hat. beA-Nachricht kann wie bisher umbenannt werden. 


https://user-images.githubusercontent.com/3729754/113615322-00d04300-9654-11eb-985a-d0e5328b692f.mp4
