### ISSUE TITLE
[FEATURE] Unterschiedliche Sätze an Etikettenabos am Desktop, zentral am Nutzer speichern

### ISSUE THREAD

**Issue by Maz111111** [jlawyerorg/j-lawyer-org#1049]
Bisher wurden die Abos afaik (ausschließlich) für jeden Arbeitsplatz gespeichert.

Ich habe folgendes etabliert:

Bin ich im HomeOffice sehe ich u.a. die Etiketten "Posteingang" und "bearbeitetes Diktat". Ich korrigiere das Diktat oder bewerte den Posteingang und mache irgendwas damit. Dann vergebe ich elektronisch im jL eine neue WV.

Ich habe im HO aber meinen (afaik zwingend parallel zu führenden) physischen Kalender nicht dabei. Der liegt - wie auch der Aktendeckel mit dem darauf gehefteten Posteingang - weggeschlossen in der Kanzlei. Ich vergebe nach dem abarbeiten also das Etikett "alte WV streichen", "neue WV notieren". Oder z.B. auch das Etikett "archivieren" (bedeutet Aktendeckel oder ältere Papierakte ins Archiv hängen). Also jedenfalls Anweisungen an mich, die nur in der Kanzlei befolgt werden können. In der Kanzlei sehe ich dann nur die Etiketten, die dort sinnvoll abgearbeitet werden können.

Im HO will ich z.B das Etikett "WV streichen" nicht sehen - kann ich im HO ja ohnehin nicht.

Gäbe jetzt noch weitere Beispiele ist aber egal. Ich hatte die Änderung nicht mitbekommen und "neue WV notieren" im HO ausgeblendet. Dummmerweise war es damit auch im Büro ausgeblendet. Dort dachte ich aber, dass es einfach keine neuen WVs zu notieren gibt.

Das hätte mit großen Verwirrungen enden können. Habe es heute eher zufällig mitbekommen, weil ich ein anderes Etikett, an dessen Vergabe im HO ich mich erinnerte, im Büro nicht fand. Da habe ich dann die anderen dort wieder sichtbar gemacht und hatte ganz schön was nachzutragen im Kalender. Jetzt sitze ich gerade im HO und wundere mich über die vielen angezeigten Akten und habe die Abos kontrolliert.

Workaround wäre ein neuer HO Nutzer - ist das gewollt? So wie es vorher war, war es komfortabel - eben ohne neuen extraNutzer. Ich verstehe, dass man - aus welchem Grund auch immer - einen anderen Nutzer am eigenen Rechner arbeiten lässt (wer macht das?) und dieser dann seine eigenen Abos sehen soll. 

Wenn man dieses Feature des Nutzerwechsels am selben Arbeitsplatz unbedingt benötigt, fände ich es besser, wenn dann arbeitsplatz- und nutzabhängig gespeichert wird.

**Comment by j-dimension** [comment]
> Ich verstehe, dass man - aus welchem Grund auch immer - einen anderen Nutzer am eigenen Rechner arbeiten lässt (wer macht das?) und dieser dann seine eigenen Abos sehen soll.

Das ist nicht das angepeilte Szenario. Wenn man unterschiedliche Personen an einem Arbeitsplatz hat (bspw. verschiedene MA im Sekretariat, je nach Wochentag), dann sollten diese auch eigene Windows-/macOS-/Linux-Logins bekommen und hätten somit sowieso ihr eigenes Profil. 

Es geht mehr um das Nutzen verschiedener Geräte durch die selbe Person - im Büro am Desktop, unterwegs am Notebook. Dort musste bisher eine Änderung der Etiketten-Abos immer mehrfach gepflegt werden.

**Comment by Maz111111** [comment]
OK. Verstehe - macht natürlich Sinn, wenn man an jedem Arbeitsplatz die selben Abos haben will, was - wenn ich das so betrachte - auf den ersten Blick auch mir als der häufigste Anwendungsfall erscheint.

Also habe ich das (vielleicht) Sonderproblem, dass icvh für verschiedene Geräte verschiedene Abos benötige.

Ach, ach, ach ... der Anwender steht im Mittelpunkt ... und damit immer im Weg :-)

**Comment by j-dimension** [comment]
> der Anwender steht im Mittelpunkt ... und damit immer im Weg :-)

Ich denke schon dass die Wünsche der Anwender hier in diesem Projekt sehr stark berücksichtigt werden. Man zeige mir eine andere Kanzleisoftware, die auf eine so direkte Art und Weise die Anwender einbezieht.

Nur ist es eben so, dass unterschiedliche Anwender an unterschiedlichen Stellen im Raum stehen, und diese Konflikte muss ich auflösen. Dadurch ist eben nicht immer jeder gleich happy. Die "Konfliktlösungsstrategie" ist meistens das Identifzieren der größten Nutzergruppe, die von einer Umsetzungsvariante profitieren würde.

**Comment by Maz111111** [comment]
> Ich denke schon dass die Wünsche der Anwender hier in diesem Projekt sehr stark berücksichtigt werden.

auf jeden!!!!
> Ach, ach, ach ... der Anwender steht im Mittelpunkt ... und damit immer im Weg :-)

war als reiner Witz gedacht -- der Spruch geht normalerweise mit "Mandant" anstatt "Anwender"

**Comment by stm9x9** [comment]
> Das ist nicht das angepeilte Szenario. Wenn man unterschiedliche Personen an einem Arbeitsplatz hat (bspw. verschiedene MA im Sekretariat, je nach Wochentag), dann sollten diese auch eigene Windows-/macOS-/Linux-Logins bekommen und hätten somit sowieso ihr eigenes Profil.

das ist in kleineren Kanzleien zb am "Tresen"/"Empfangs"-PC nicht machbar.
 
> Es geht mehr um das Nutzen verschiedener Geräte durch die selbe Person - im Büro am Desktop, unterwegs am Notebook. Dort musste bisher eine Änderung der Etiketten-Abos immer mehrfach gepflegt werden.

Das finde ich auch gut so, verstehe aber das Problem von @Maz111111. Vielleicht läßt es sich so lösen und damit gleich noch eine andere Fliege erschlagen:

Der Nutzer erhält die Möglichkeit, individuelle Sets an Etiketten-Abos abzuspeichen. Dann könnte Maz sich ein Set "Home-Office" erstellen und eines "Büro". Aber man kann damit auch Arbeitsphasen abbilden.  

zb Set "Postausgang" mit 

![image](https://user-images.githubusercontent.com/29924198/102831418-0fb82000-43ec-11eb-93e9-2e8d494ca60e.png)

oder "Abrechnen" mit Abrechnen Ggn, Abrechnen Mdt, Abrechnen PKH ...

**Comment by Maz111111** [comment]
dann müsste aber auch arbeitsplatz- bzw. clientspezifisch abgespeichert werden, welches Set beim Start des jeweiligen Clients aktiv sein soll.

**Comment by j-dimension** [comment]
> das ist in kleineren Kanzleien zb am "Tresen"/"Empfangs"-PC nicht machbar.

Das kann man schon so machen, dann isses aber Kacke. 

Im Ernst: warum soll das nicht möglich sein? Ich kenne keinen Fall, in dem die Vorteile von Shared User Accounts die Nachteile überwiegen. DSGVO-konform ist es auch nicht, und im Problemfall wird sich die Betriebshaftpflicht freuen zu hören, dass man gar nicht weiß, wer wann was gemacht hat.

**Comment by j-dimension** [comment]
> Der Nutzer erhält die Möglichkeit, individuelle Sets an Etiketten-Abos abzuspeichen. Dann könnte Maz sich ein Set "Home-Office" erstellen und eines "Büro". Aber man kann damit auch Arbeitsphasen abbilden.

Technisch machbar, auch wenn es die Einstelloptionen weiter aufbläht. Wenn das Euer Konsens ist, formuliere ich das Ticket um. Muss dann im Verbund mit #981 betrachtet werden.

**Comment by Maz111111** [comment]
> dann müsste aber auch arbeitsplatz- bzw. clientspezifisch abgespeichert werden, welches Set beim Start des jeweiligen Clients aktiv sein soll.

wenn das eingebaut ist, dürfte die Set Lösung für die Allgemeinheit die nützlichere Variante sein.

Ansonsten wird es früher oder später jemanden geben, der am Lapi seine Abos ändert und dann genervt ist, weil er sie im Büro auch noch anpassen muss (was in meiner Welt und von mir aber als völlig erwartungsgemäßes Verhalten der KSW  wahrgenommen wird).

Ich hab da nochmal drüber nachgedacht: das hängt halt sehr vom Nutzer ab. Jemand der die nutzerbedingte Speicherung bevorzugt, wird wahrscheinlich z.B. auch seine Lesezeichen / Favoriten der Webbrowser synchronisieren lassen.

Das ist eine Sache die ich absolut hasse und immer als allererstes abschalte. Jeder Arbeitsplatz hat seinen Zweck und seinen Anwendungsbereich. Wenn ich Abends auf der Couch sitze, brauche ich völlig andere Lesezeichen im Browser als im Büro.

Das mit den Etiketten ist vergleichbar. Der eine mag es so und der andere eben so. Da aber auch jeder mir vertraute Browser so eine SyncFunktion anbietet, scheint meine Auffassung - das arbeitsplatzspezifisch ein jeweils separates look & feel besser ist - aber wohl tatsächlich die Minderheit darzustellen.

Jetzt beim Schreiben kommt mir aber glatt die Idee! Jeder mir vertraute Browser bietet ja auch die - von mir immer genutzte - Möglichkeit die Sync-Funktion abzuschalten.

Mach es doch also genauso, wie in den Browsern - lass den User entscheiden, ob er es syncen will oder nicht.

**Das ist meine favorisierte Lösung:

Wenn der Nutzer nichts macht, wird auf jedem seiner Clients in Bezug auf die EtikettenAbos alles gleich dargestellt (Nutzerabhängige Speicherung / Synchronisierung=an). Aber er hat die Möglichkeit, dieses in den Einstellungen zu unterbinden, so dass er an jedem Arbeitsplatz auch andere Etiketten abonnieren kann (Arbeitsplatzabhängige Speicherung / Synchronisierung = aus).**

**Comment by Maz111111** [comment]
Da kann man jetzt natürlich auch noch darüber nachdenken (da die Frage ja sowieso früher oder später kommen wird), ob man die Entscheidung ob synchronisiert wird oder nicht, nicht auch gleich clientabhängig speichern kann.

Ich nutze derzeit vier Rechner:
1. Büro (=Hauptarbeitsplatz)
2. Laptop (=Terminsarbeitsplatz für das Gericht)
3. Rechner 1 (=HO)
4. Rechner 2 (=HO)

Jetzt sollen zumindest 3. und 4. immer dieselben Etiketten Abos haben und 1.und 2 vielleicht...

**Comment by stm9x9** [comment]
> dann müsste aber auch arbeitsplatz- bzw. clientspezifisch abgespeichert werden, welches Set beim Start des jeweiligen Clients aktiv sein soll.

Das würde ich einfach nur nutzerspezifisch abspeichern. Das umstellen als erstem Schritt nach einer ersten Anmeldung an einem PC halte ich für recht unaufwändig und leicht zu memorieren.

**Comment by stm9x9** [comment]
> Da kann man jetzt natürlich auch noch darüber nachdenken (da die Frage ja sowieso früher oder später kommen wird), ob man die Entscheidung ob synchronisiert wird oder nicht, nicht auch gleich clientabhängig speichern kann.

scheint mir für den "Normalo"-Anwender eine Spur zu komplex. Dann lieber die Set-Lösung.

**Comment by stm9x9** [comment]
> Im Ernst: warum soll das nicht möglich sein? Ich kenne keinen Fall, in dem die Vorteile von Shared User Accounts die Nachteile überwiegen. DSGVO-konform ist es auch nicht, und im Problemfall wird sich die Betriebshaftpflicht freuen zu hören, dass man gar nicht weiß, wer wann was gemacht hat.

Weil da oft fliegender Wechsel ist.

**Comment by stm9x9** [comment]
not planned? Huch? Ich dachte, mit der Idee von individuellen Sets an Etiketten-Abos gab es einen Konsens?

**Comment by j-dimension** [comment]
Ich habe das Gefühl, dass das Feature der Etiketten-Sets bereits eine 120%-Lösung ist, und mit gerätespezifischer Speicherung eine 180%-Lösung. Wenn ich das gegen die anderen Features halte, weiß ich nicht wann das priorisiert werden kann. Lasse mich bei mehr Anwenderwunsch umstimmen.
