### ISSUE TITLE
[BUG] Dokumentenliste - Rechtsklick - unerwartetes Verhalten

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#1054]
**Describe the bug / Fehlerbeschreibung**
(todo: a description of the bug / eine Beschreibung des Fehlers)

**To Reproduce / Schritte zum Nachvollziehen**

1. Ein Dokument ist mit Linksklick ausgewählt.
2. Maus auf ein anderes Dokument schieben
3. Dort einen Rechtsklick machen und eine Aktion (zb Umbenennen) auswählen

Diese Aktion wird dann mit dem vorher per Linksklick ausgewählten Dokument gemacht.

**Expected behavior / Erwartetes Verhalten**
Eine Beschreibung des erwarteten Verhaltens.

Die Aktion wird mit dem Dokument gemacht, wo der Mauszeiger beim Rechtsklick war. Das entspricht zumindest dem, was man unter Windows gewohnt ist.

Im Falle einer vorherigen Mehrfachselektion ist es unter Win unterschiedlich:

Wenn man dann den Rechtsklick über einem der markierten Dateien macht, dann wird der Rechtsklick für alle markierten gemacht. Bewegt man die Maus auf eine andere, nicht selektierte Datei, dann wird die Mehrfachselektion aufgehoben und der Rechtsklick gilt für die neue Datei.

Ich weiß nicht, was die Nutzer unter Mac gewohnt sind, aber ich muß gerade ein paar Dateien umbenennen und ich falle jedes zweite Mal drauf rein, daß ich erst die neue Datei links markieren muß, bevor ich mit rechts eine Aktion auswählen kann.

**Screenshots**
Falls relevant, Screenshot beifügen.

![image](https://user-images.githubusercontent.com/29924198/103229669-cf98f600-4933-11eb-9e54-5409476fdfcb.png)

**Environment / verwendete Umgebung:**
 - OS / Betriebssystem: Win 10 Pro
 - j-lawyer.org Version: 1.13.0.5

**Additional context / Sonstiges**

**Comment by j-dimension** [comment]
Dup von #1141
