### ISSUE TITLE
[FEATURE] Suchen oder Filtern in der Historie

### ISSUE THREAD

**Issue by RA-crm** [jlawyerorg/j-lawyer-org#1060]
Die #1040 hat mich auch die Idee gebracht, dass man in der Historie auch filtern oder suchen können sollte. So eine Option besteht bisher nicht, oder?

So wäre es möglich auch weit in der Vergangenheit zurückliegende Vorgänge schnell zu filtern und gegebenenfalls Fehler aufzudecken um diese zukünftig zu verhindern.

**Comment by j-dimension** [comment]
Duplikat von #75
