### ISSUE TITLE
[BUG] Fehler bei Zugriff auf Dateien mit speziellen Unicode-Zeichen im Dateinamen

### ISSUE THREAD

**Issue by bjk00** [jlawyerorg/j-lawyer-org#1063]
Fehlerbeschreibung
Wird eine Email mit Anhang in einer Akte gespeichert und nachfolgend der Anhang separat in der Akte gespeichert, kann j_lawyer nicht mehr auf den Anhang zugreifen, wenn spezielle Unicode-Zeichen (U+0075U+0308) im Dateinamen enthalten sind.

Schritte zum Nachvollziehen
1. Emailpostfach->Posteingang
2. Markieren der Email
3. Rechtsklick->Kontextmenü->in Akte speichern
4. Akte auswählen, Dateinamen übernehmen, speichern
5. In die Akte wechseln, Reiter Dokumente, Email markieren, Emailinhalt erscheint rechts
6.  in der Email/Anhänge unten mit rechts auf den Anhang klicken->Speichern->in Akte wählen
7. Akte auswählen und übernehmen
8. gerade gespeichertes Dokument (hier war es ein PDF) zum Öffnen doppelt anklicken

Fehlermeldung erscheint "Fehler beim Laden des Dokuments: Dokument ... existiert nicht!

Nach einigen Versuchen habe ich rausgefunden, dass im Dateinamen der Umlaut ü (Unicode U+00FC) durch die Unicodezeichen  u + Umlautzeichen (Trema, Combining diaeresis) (Unicode U+0075U+0308) dargestellt waren. Sichtbare Unterschiede gibt es zwischen den beiden Varianten nicht. Windows und Linux behandeln die Datei problemlos (Kopieren, Umbenennen etc.) Öffenen lässt sich das PDF extern problemlos. 

**Environment / verwendete Umgebung:**
 - OS / Betriebssystem: Client Windows 10 pro 64bit / Server Linux Mint 19
 - j-lawyer.org Version: 1.13.0.5

**Comment by j-dimension** [comment]
Es geht um Anhänge einer Email (die in eine Akte übernommen wurden), nicht die Mail selbst, korrekt?

Kannst Du mir eine solche Email erstellen, samt Anhängen, und mir dann die .eml bereitstellen? (gezippt an meine Mailadresse)

@bjk00

**Comment by bjk00** [comment]
Hat die Email selbst diese unicode-Zeichen im eml-Dateinamen, erscheint die gleiche Fehlermeldung beim Versuch sie in j-lawyer zu öffnen. Ich kann gerne direkt eine Testmail mit einem entsprechend erstelltem Dokument im Anhang zusenden. Gezippt per eml natürlich auch.

**Comment by j-dimension** [comment]
Danke, habe die Testmail erhalten.

**Comment by j-dimension** [comment]
Kannst Du die .eml bitte nochmal gezippt senden? Thunderbird stellt die sonst "inline" dar, ich sehe gar nicht dass eine .eml gesendet wurde. Danke!

**Comment by j-dimension** [comment]
@bjk00 ich bekomme das nicht reproduziert. Folgende Konstellationen habe ich getestet:

- Server Windows, Client Windows - funktioniert
- Server Linux, Client Windows - funktioniert
- Server Linux, Client Linux - funktioniert

Ich habe die Testmail als .eml in die Dokumente aufgenommen und dann per Doppelklick das darin befindliche Attachment geöffnet.

Insofern bin ich erstmal nicht in der Lage, hieran zu arbeiten.

**Comment by bjk00** [comment]
Ich hatte dir auch ein PDF geschickt, mit besagtem Sonderzeichen im Dateinamen. Damit kann ich den Fehler auch durch ein einfaches Hinzufügen zu einer Akte reproduzieren:
1. Akte öffen
2. Karteireiter Dokumente
3. oben rechts Button " Hinzufügen" anklicken
4. Datei auswählen und auf Öffnen klicken -> Datei wird der Akte hinzugefügt
5. Doppelklick auf die gerade hinzugefügte Datei im der Dokumentenliste
-> Fehlermeldung: "Fehler beim Laden des Dokuments: Dokument ... existiert nicht!

Löschen kann ich das Dokument aus der Dokumentenliste aber wenn ich es nochmal hinzufügen möchte, bekomme ich die Fehlermeldung, dass der Dateiname schon existiert.

**Comment by bjk00** [comment]
Ich habe es gerade nochmal in den beiden Kombinationen ausprobiert:
Server Linux, Client Windows
Server Linux, Client Linux
Bei beiden das gleiche Verhalten und die gleiche Fehlermeldung.

**Comment by bjk00** [comment]
Kann es sein, dass vielleicht irgendeine Zeichensatz-Einstellung am mysql-Server nicht passt? Scheinbar wird das Dokument ja ordnungsgemäß im Dateisystem abgelegt aber beim Namen in der Datenbank scheint ein ? statt des ü zu stehen. Zumindest wird dieses "?" in der Fehlermeldung angezeigt.

**Comment by j-dimension** [comment]
> * Akte öffen
> * Karteireiter Dokumente
> * oben rechts Button " Hinzufügen" anklicken
> * Datei auswählen und auf Öffnen klicken -> Datei wird der Akte hinzugefügt
> * Doppelklick auf die gerade hinzugefügte Datei im der Dokumentenliste
>   -> Fehlermeldung: "Fehler beim Laden des Dokuments: Dokument ... existiert nicht!

@bjk00 auch das führt in meinen Testumgebungen zu keinerlei Fehler. 

Bitte mal das hier ausführen:


```
SELECT CCSA.character_set_name FROM information_schema.`TABLES` T,
       information_schema.`COLLATION_CHARACTER_SET_APPLICABILITY` CCSA
WHERE CCSA.collation_name = T.table_collation
  AND T.table_schema = "jlawyerdb"
  AND T.table_name = "case_documents";


SELECT character_set_name FROM information_schema.`COLUMNS` 
WHERE table_schema = "jlawyerdb"
  AND table_name = "case_documents"
  AND column_name = "name";
```

**Comment by bjk00** [comment]
In beiden Fällen ist die Ausgabe:
+--------------------+
| character_set_name |
+--------------------+
| utf8               |
+--------------------+
1 row in set (0.00 sec)

**Comment by j-dimension** [comment]
So wie es sein soll. 

Und was ist die Ausgabe von "sysprops" in der Administratorkonsole, Eintrag "file.encoding"?

**Comment by bjk00** [comment]
file.encoding = UTF-8
file.encoding.pkg = sun.io
file.separator = /

**Comment by j-dimension** [comment]
`echo $LANG` auf dem Server?

**Comment by bjk00** [comment]
de_DE.UTF-8

**Comment by j-dimension** [comment]
Sorry, da gehen mir jetzt echt die Ideen aus, alle "Schichten" nutzen das gleiche, und zwar korrekte, Encoding.

**Comment by bjk00** [comment]
Hmm, das war für mich der einzige Hinweis, dass die Datei im Dateiensystem korrekt mit dem Sonderzeichen angelegt wird, in der Dokumentenliste von j-lawyer aber mit "?" an Stelle des  Sonderzeichens steht. Wenn ich die Datei in der Dokumentenliste lösche, wird sie übrigens im Dateiensystem des Servers nicht gelöscht. Vermutlich gib es daher die Fehlermeldung, dass sie schon vorhanden ist, wenn ich sie nach dem Löschen nochmals hinzufügen will.
Ich hätte mit meinem Laienverständnis jetzt getippt, dass die Name in der Datenbank falsch hinterlegt ist, warum auch immer.

**Comment by j-dimension** [comment]
Ich könnte höchstens per Fernwartung draufschauen. Wenn das aber ein Einzelschicksal ist, wäre Aufwand/Nutzen für mich aber relativ hoch.

**Comment by bjk00** [comment]
Sieht ja ein wenig nach Einzelschicksal aus...
Zurzeit betrifft es nur einen Mandanten, der so komische Zeichen in seinen Dateien hat. Der Workaround ist alles umzubennen, was er sendet. Geht also erstmal.
Danke für die Zeit!

**Comment by j-dimension** [comment]
Dann schliesse ich hier erstmal. Kannst aber gern wieder öffnen, sobald sich neue Erkenntnisse ergeben oder das Problem sich in die Breite entwickelt.
