### ISSUE TITLE
[FEATURE] Native macOS M1 installer

### ISSUE THREAD

**Issue by j-dimension** [jlawyerorg/j-lawyer-org#1069]
Provide a native macOS M1 build and installer (ARM64)

https://www.ej-technologies.com/download/install4j/changelog.html

**Comment by j-dimension** [comment]
Depends on https://github.com/AdoptOpenJDK/openjdk-build/issues/1922 and LibericaJDK

**Comment by j-dimension** [comment]
@ingokegel when building, install4j was unable to find a JRE for the target platform / architecture. Under General - JRE bundles I am using Liberica JRE 8. 

Is there anything special to do (such as choosing a specific JRE provider) in order to build an installer for macOS ARM64?

Thanks!

**Comment by ingokegel** [comment]
Please see

https://www.ej-technologies.com/blog/2020/11/support-for-macos-on-arm-apple-m1/

**Comment by j-dimension** [comment]
Thanks for the very nice RTFM, @ingokegel :-)

**Comment by j-dimension** [comment]
@iradraconis habe einen Client-Installer für M1 / ARM64 erstellt (Download im "Vorschau"-Bereich). Kannst Du mal testen? Mir fehlt es schlicht an einer Testumgebung.

**Comment by j-dimension** [comment]
@iradraconis nach Installation bitte mal die Adminkonsole öffnen und die Ausgabe von 
`sysprops`
**per E-Mail** an mich. Danke!

**Comment by iradraconis** [comment]
Super!! Vielen Dank, Jens! Direkt installiert und ausprobiert. Soweit alles unauffällig, also keine Fehler oder dergleichen bemerkt. Gerade im Fernzugriff getestet und gefühlt "snappier". Ich werde den Client morgen noch auf 2 weiteren Geräten installieren. 
Meine Mitarbeiterin meinte heute noch, der neue iMac (m1) sei inzwischen auch schon langsamer geworden. Das würde ich mal ausschließen. Ich hoffe mit dem nativen arm basierten Client wird es besser. Melde mich dazu wieder.

**Comment by j-dimension** [comment]
```
apple.awt.application.name = j-lawyer.org
apple.laf.useScreenMenuBar = true
awt.toolkit = sun.lwawt.macosx.LWCToolkit
com.apple.mrj.application.apple.menu.about.name = j-lawyer.org
exe4j.moduleName = /Applications/j-lawyer.org (Client).app
file.encoding = UTF-8
file.separator = /
gopherProxySet = false
http.agent = j-lawyer Client v2.1.0.0
i4j.jreBundle = /Applications/j-lawyer.org (Client).app/Contents/PlugIns/jre.bundle
i4j.ownBundlePath = /Applications/j-lawyer.org (Client).app
install4j.appDir = /Applications/j-lawyer.org (Client).app/Contents/java/app/
install4j.exeDir = /Applications/
install4j.launcherId = 27
install4j.swt = false
java.awt.graphicsenv = sun.awt.CGraphicsEnvironment
java.class.version = 55.0
java.home = /Applications/j-lawyer.org (Client).app/Contents/PlugIns/jre.bundle/Contents/Home
java.io.tmpdir = /var/folders/q7/_qf3nmgs3yq564xt65v2fd580000gn/T/
java.library.path = /Users/max/Library/Java/Extensions:/Library/Java/Extensions:/Network/Library/Java/Extensions:/System/Library/Java/Extensions:/usr/lib/java:.
java.net.preferIPv4Stack = true
java.net.useSystemProxies = true
java.protocol.handler.pkgs = com.jdimension.jlawyer.client.editors.documents.viewer.html
java.runtime.name = OpenJDK Runtime Environment
java.runtime.version = 11.0.14.1+1-LTS
java.security.auth.login.config = auth.conf
java.specification.name = Java Platform API Specification
java.specification.vendor = Oracle Corporation
java.specification.version = 11
java.vendor = BellSoft
java.vendor.url = https://bell-sw.com/
java.vendor.url.bug = https://bell-sw.com/support
java.version = 11.0.14.1
java.version.date = 2022-02-08
java.vm.compressedOopsMode = Zero based
java.vm.info = mixed mode
java.vm.name = OpenJDK 64-Bit Server VM
java.vm.specification.name = Java Virtual Machine Specification
java.vm.specification.vendor = Oracle Corporation
java.vm.specification.version = 11
java.vm.vendor = BellSoft
java.vm.version = 11.0.14.1+1-LTS
javafx.runtime.version = 11.0.14+b01
javafx.version = 11.0.14
jdk.debug = release
os.arch = aarch64
os.name = Mac OS X
os.version = 12.3
path.separator = :
sun.arch.data.model = 64
sun.awt.enableExtraMouseButtons = true
sun.boot.library.path = /Applications/j-lawyer.org (Client).app/Contents/PlugIns/jre.bundle/Contents/Home/lib
sun.cpu.endian = little
sun.cpu.isalist = 
sun.font.fontmanager = sun.font.CFontManager
sun.io.unicode.encoding = UnicodeBig
sun.java.command = com.install4j.runtime.launcher.MacLauncher
sun.java.launcher = SUN_STANDARD
sun.jnu.encoding = UTF-8
sun.management.compiler = HotSpot 64-Bit Tiered Compilers
sun.nio.ch.bugLevel = 
sun.os.patch.level = unknown
user.country = DE
user.dir = /Applications/j-lawyer.org (Client).app/Contents/java/app
user.language = de
user.name = max
user.timezone = Europe/Berlin
webSocketSSL = true
```

**Comment by iradraconis** [comment]
Log: java.version = 11.0.14.1

installiert habe ich aber eine Version 17.
Der Client benutzt also eine mitgelieferte Runtime, richtig? 

![Bildschirmfoto 2022-03-29 um 23 07 33](https://user-images.githubusercontent.com/71747937/160707514-ca18577b-7619-4582-b181-a8dc28eafb28.png)

**Comment by j-dimension** [comment]
> Der Client benutzt also eine mitgelieferte Runtime, richtig?

Das ist richtig. Beim M1-Installer ist es aber nun eine ARM64-Runtime.

**Comment by iradraconis** [comment]
> > Der Client benutzt also eine mitgelieferte Runtime, richtig?
> 
> Das ist richtig. Beim M1-Installer ist es aber nun eine ARM64-Runtime.

Wenn es nicht Placebo ist, ist es wirklich schneller :) mal sehen, was die anderen M1 Nutzer sagen...

**Comment by Fn0rdmann** [comment]
Subjektiv würde auch ich sagen: deutlich mehr Schwuppdizität!
