### ISSUE TITLE
nextCloud-Anbindung

### ISSUE THREAD

**Issue by j-dimension** [jlawyerorg/j-lawyer-org#107]
https://github.com/a-schild/nextcloud-java-api

**Comment by j-dimension** [comment]
inkl. Chat via Nextcloud Talk. API existiert.

**Comment by j-dimension** [comment]
https://www.ionos.de/enterprise-cloud/nextcloud

**Comment by PBaumfalk** [comment]
Ja!!! Nextcloudanbindung wäre super!

Mit freundlichen Grüßen / Kindly Regards

Patrick Baumfalk
Rechtsanwalt / Lawyer


Mobil:    +49 1525 53 04 194
E-Mail:   patrick.baumfalk@kanzlei-baumfalk.de


Baumfalk - Rechtsanwaltskanzlei
Hauptstr. 195
50169 Kerpen

Tel.: +49 2273 40 68 504
Fax: +49 2273 59 03 565

E-Mail: info@kanzlei-baumfalk.de
Web: www.kanzlei-baumfalk.de

Sent by Mobile

**Comment by librelegal** [comment]
Nextcloud-Anbindung wäre wirklich hilfreich. Da gibt es sicher einiges an positiven Erfahrungen seit j-lawyer.cloud

**Comment by Maz111111** [comment]
Ich weiß zwar nicht, was dann über nextcloud realisiert werden soll.
Es wäre aber toll, wenn die Anwender nicht ausschließlich auf die cloudLösung verwiesen würden.
Es sollte gewährleistet sein, dass zusätzlich die gleichen Funktionen, die über die Cloud laufen, in der selben Art und Weise auch über einen (selbstverständlich selbst zu erstellenden) VPN Tunnel möglich sind.
Bsp:
Synology NAS. Synology bietet eine private Cloud (Synology Drive). Daten werden von überall auf der Welt automatisch auf das NAS geladen, wenn auf dem ClientGerät die Clientsoftwäre installiert ist.
Die Anbindung kann hier zum einen über die direkt von Synology bereitgestellte synology ID und damit über deren Server laufen oder aber über die schlichte Eingabe der IP des NAS, wenn eben ein aktiver VPNTunnel besteht.
Ich kann daher meine Daten völlig unabhängig von Synology und damit nicht über deren Server über meinen verschlüsselten VPN Tunnel abgleichen.
Ist nichts für jeden Anwender - daher sollte die ToGo Lösung über Nextcloud auch ent-/ bestehen. Es wäre aber eben gut, wenn man nicht zur Nutzung gezwungen wird, um alle Funktionen von jL nutzen zu können.

**Comment by j-dimension** [comment]
Das wird eine schrittweise Umsetzung. Langfristig möchte ich gern

- Kalendersynchronisation
- Bereitstellung on Dokumenten für Mandanten / externe Partner
- Übernahme von Dokumenten, die Mandanten / externe Partner bereitgestellt haben
- Organisieren von Telefon- / Videokonferenzen

Das sind Punkte, die ich nicht selbst entwickeln werde und die einen öffentlich erreichbaren Server voraussetzen. Ob man das dann intern im Kanzleinetzwerk betreibt oder auf einem öffentlichen Server ist zweitrangig. 

Jedoch werde ich mich auf EINE Anbindung konzentrieren, und dazu diejenige auswählen, die (1) leicht verfügbar / kostenfrei ist, (2) den höchstmöglichen Grad an fertig nutzbarer Funktionalität hat und (3) gut integrierbar ist. Daher meine Auswahl von Nextcloud.

**Comment by Maz111111** [comment]
Alles klaro.
Für den Austausch mit dem Mandanten macht der VPN Tunnel auch keinen Sinn. Die sollen ja gar keinen Zugang zu meinem Netzwerk erhalten.
Ich dachte es wird hier um irgendeinen Weg gehen, jL auf dem Tablet mit zum Termin nehmen zu können und dann dort die eigene Akte - anstatt der Papierakte - abrufen zu können.
Die TerminsApp sozusagen. Hierfür fänd ich eben die (zusätzliche) VPN Lösung gut.
Mein Fehler.

**Comment by j-dimension** [comment]
@Maz111111 dafür gibt es ein separates Ticket: #60 

Das wird dann auch ohne irgendeine "Cloud" möglich sein.

**Comment by j-dimension** [comment]
Ticket wird durch spezifischere Teiltickets ersetzt.
