### ISSUE TITLE
[BUG] Unlöschbare DREBIS Vorgänge, wenn Versicherer mit "Mandatsempfehlung" antwortet

### ISSUE THREAD

**Issue by PBaumfalk** [jlawyerorg/j-lawyer-org#1070]
**NOTE: Please search existing tickets to avoid duplicates **
**HINWEIS: Bitte vorab die Ticketsuche verwenden, um Doppeleinträge zu vermeiden **

Wenn kein Aktenzeichen und kein Kurzrubrum von der RSV vergeben ist, gibt es unlöschbare DREBIS-Vorgänge:

![image](https://user-images.githubusercontent.com/50404378/104497739-185ed900-55db-11eb-89a3-70b0894d2b49.png)

![image](https://user-images.githubusercontent.com/50404378/104497759-214faa80-55db-11eb-9dba-d434d0728b71.png)

**Describe the bug / Fehlerbeschreibung**
(todo: a description of the bug / eine Beschreibung des Fehlers)

**To Reproduce / Schritte zum Nachvollziehen**

1. Go to / Gehe zu '...'
2. Klicke auf / Click on '....'
4. Error message / Fehlermeldung: '...'

**Expected behavior / Erwartetes Verhalten**
Eine Beschreibung des erwarteten Verhaltens.

**Screenshots**
Falls relevant, Screenshot beifügen.

**Environment / verwendete Umgebung:**
 - OS / Betriebssystem:
 - j-lawyer.org Version:

**Additional context / Sonstiges**

**Comment by j-dimension** [comment]
Es darf gar keine Antwort von Drebis geben, die kein Aktenzeichen hat. Bitte mal das client.log und server.log per E-Mail bereitstellen.

**Comment by PBaumfalk** [comment]
> Es darf gar keine Antwort von Drebis geben, die kein Aktenzeichen hat. Bitte mal das client.log und server.log per E-Mail bereitstellen.

Erledigt.

**Comment by j-dimension** [comment]
Wenn Ihr Euch im Drebis-Portal einloggt - ist dort Eure Akte mit Aktenzeichen zu sehen?

**Comment by PBaumfalk** [comment]
Nein.

Mit freundlichen Grüßen / Kindly Regards

Patrick Baumfalk
Rechtsanwalt / Lawyer


Mobil:    +49 1525 53 04 194
E-Mail:   patrick.baumfalk@kanzlei-baumfalk.de

BAUMFALK - Rechtsanwaltskanzlei

Hauptkanzlei:
Hauptstr. 195
50169 Kerpen

Zweigstelle:
Berliner Str. 4
58452 Witten

Postanschrift:
Postfach 1233
50141 Kerpen

Tel.: +49 2273 40 68 504
Fax: +49 2273 59 03 565

E-Mail: info@kanzlei-baumfalk.de
Web: www.kanzlei-baumfalk.de

**Comment by j-dimension** [comment]
Ist sie nicht zu sehen oder hat sie kein Aktenzeichen?

**Comment by j-dimension** [comment]
nur für mich:

```
2021-01-14 07:16:14,310 ERROR [com.jdimension.jlawyer.client.drebis.DrebisInboxPanel] Error confirming drebis message
com.jdimension.jlawyer.drebis.DrebisException: Transaktionen konnten nicht bestÃ¤tigt werden
	at com.jdimension.jlawyer.drebis.DrebisAPI.confirm(DrebisAPI.java:1154)
```

**Comment by PBaumfalk** [comment]
Ist auch nicht im DREBIS Portal zu sehen.

Mit freundlichen Grüßen / Kindly Regards

Patrick Baumfalk
Rechtsanwalt / Lawyer


Mobil:    +49 1525 53 04 194
E-Mail:   patrick.baumfalk@kanzlei-baumfalk.de

BAUMFALK - Rechtsanwaltskanzlei

Hauptkanzlei:
Hauptstr. 195
50169 Kerpen

Zweigstelle:
Berliner Str. 4
58452 Witten

Postanschrift:
Postfach 1233
50141 Kerpen

Tel.: +49 2273 40 68 504
Fax: +49 2273 59 03 565

E-Mail: info@kanzlei-baumfalk.de
Web: www.kanzlei-baumfalk.de

**Comment by j-dimension** [comment]
Können wir das kommende Woche per Fernwartung anschauen?

**Comment by PBaumfalk** [comment]
Klar!

Mit freundlichen Grüßen / Kindly Regards

Patrick Baumfalk
Rechtsanwalt / Lawyer


Mobil:    +49 1525 53 04 194
E-Mail:   patrick.baumfalk@kanzlei-baumfalk.de


Baumfalk - Rechtsanwaltskanzlei
Hauptstr. 195
50169 Kerpen

Tel.: +49 2273 40 68 504
Fax: +49 2273 59 03 565

E-Mail: info@kanzlei-baumfalk.de
Web: www.kanzlei-baumfalk.de

Sent by Mobile

**Comment by j-dimension** [comment]
@PBaumfalk das Thema ist irgendwie völlig von meinem Radar verschwunden. Mea culpa!

Existiert dieses Problem noch?

**Comment by PBaumfalk** [comment]
Ja

Mit freundlichen Grüßen / Kindly Regards

Patrick Baumfalk
Rechtsanwalt / Lawyer


Mobil:    +49 1525 53 04 194
E-Mail:   ***@***.***


Baumfalk - Rechtsanwaltskanzlei
Hauptstr. 195
50169 Kerpen

Tel.: +49 2273 40 68 504
Fax: +49 2273 59 03 565

E-Mail: ***@***.***
Web: www.kanzlei-baumfalk.de

Sent by Mobile

**Comment by j-dimension** [comment]
Die Versicherung hat - im Gegensatz zu allen anderen mir bekannten - nicht mit einer Datenstruktur vom Typ "Freitext" geantwortet, sondern mit einer "Mandatsempfehlung". 

Ich habe diesbezüglich eine Erweiterung umgesetzt und werde sie mit 1.15 ausliefern. 

Die nicht löschbare Nachricht von Dir @PBaumfalk konnte ich mittels dieser Erweiterung bestätigen, sie sollte nicht mehr erscheinen.
