### ISSUE TITLE
[FEATURE] Skripte in Vorlagen, Wenn - Dann - Funktionalität

### ISSUE THREAD

**Issue by GuidoBo** [jlawyerorg/j-lawyer-org#1078]
**Is your feature request related to a problem? Please describe. / Welches Problem soll durch die Erweiterung / Verbesserung gelöst werden?**

Es fehlt aktuelle eine Möglichkeit, in einer Textvorlage Texte bedingt anzuzeichen. 
Datenbankfelder sollten sich auch in einem zu erstellenden Textdokument (über den bloßen Platzhalter hinaus) auswerten lassen.

**Describe the solution you'd like / Beschreibe die gewünschte Lösung**
Description / Beschreibung

Mit einer Wenn-Dann-Auswertung könnte z.B. ein geschlechtsabhängiger Text erstellt werden, der abhängig etwa von der hinterlegten Geschlechtsangabe der Mandatierenden Person (Männlich, Weiblich, Divers, Plural), einfügt 

z.B. („des Klägers“,“der Klägerin“,“der klagenden Person“,“der Kläger“)

---------------------------

Design / Tasks von @j-dimension 2021-08-28

- [x] script-Platzhalter in Vorlagen suchen - LibreOffice: 1h
- [x] script-Platzhalter in Vorlagen suchen (mehrzeilig via Shift+Enter) - LibreOffice: 1,5h
- [ ] script-Platzhalter in Vorlagen suchen (mehrzeilig mit Absätzen) - LibreOffice: 1,5h
- [x] Transformieren des Scriptes der Vorlage in ein Groovy-Script: 4h
- [x] Ersetzen der Platzhalter im Script: 1,5h   (aktuell muss Platzhalter mit {{}} außerhalb des Scriptes enthalten sein :-(
- [x] Anwenden von Funktionen: 1h
- [x] Funktion: WENNGLEICH: 0,5h
- [x] Funktion: WENNENTHÄLT: 0,5h
- [x] Funktion: WENNLEER (oder über WENNGLEICH mit Leerstring abbilden): 0,5h
- [x] zentrale Einstellung für "Übersetzungstabellen": logischer Name für Mappingtabelle (bspw. "Kläger"), Eingangswerte (bspw. "weiblich", "männlich", ...) und deren Ausgangswerte - Datenbankerweiterung, Services, Oberflächenerweiterungen: 12h
- [x] Funktion: VERWEIS o.ä. - schaut in Mappingtabelle und ermittelt passenden Wert: 2h
- [x] Funktion: GENDERN / MWDJU - ohne Mappingtabelle, mit fixen Werten (männlich, weiblich, divers, jur. Person, undefiniert ...): 1h
- [x] GENDERN-Tabelle über Migrationsskript automatisch erstellen
- [x] Funktion: WENNGRÖSSER: 0,5h
- [x] Funktion: TAGEDATUM ("Frist", s.u.): 0,75h
- [x] Funktion: TAGEBANKDATUM ("Banktag", s.u.): 1h
- [x] serverseitigen Groovy-Interpreter: 3h
- [x] Erweitern Service-Signaturen um Fehlermeldungen aus den Scripten an den Client zurückzugeben: 1,5h
- [x] Erweitern des Clients für die Anzeige serverseitiger Scriptfehler: 2h
- [x] Berechnen eines Ausgabestrings: 1h
- [x] Ersetzen des Scriptplatzhalters durch den Ausgabe String - LibreOffice: 0,5h
- [x] Test: 12h
- [x] Dokumentation: 6h
- [x] Beispielvorlage LO: 2h

**Comment by j-dimension** [comment]
Beispiel 1:

Heute hat mich [[MANDANT_GESCHLECHT=männlich;der Kläger]][[MANDANT_GESCHLECHT=weiblich;die Klägerin]] per Schreiben informiert

**Comment by j-dimension** [comment]
Ein Anwender:

> Wir nutzen bisher Advolux. Dort gibt es eine Reihe von Skripten, die man in die Textvorlage eintragen kann und die dann bei der Erstellung des Dokumentes ausgewertet werden. Die Dokumentation hierzu finden Sie hier:
> 
> https://media.haufe-group.com/ShopData/media/pegasus/attachments/2/Tec%20Dok%20scripte.pdf
> 
> Da ist vieles dabei, das wir niemals benutzt haben. Einiges aber benutzen wir immer und das hätten wir gern so ähnlich in J-Lawyer. Konkret:
> 
> Funktion gender()
> 
> Funktion WennDannText()
> 
> Funktion Frist()
> 
> Außerdem hätten wir gern eine Funktion, die Advolux mal in Aussicht gestellt, aber nie realisiert hat, nämlich eine 
> 
> Funktion frist_banktag(), siehe gleich:
> 
> 
> 
> ## Gendern
> 
> Funktion gender("MANDANT",männlich,weiblich,plural,divers,jp)
> 
> Die Nutzung stellen wir uns z.B. so vor:
> [[gendern("MANDANT","Der Mandant begehrt","Die Mandantin begehrt","Die Mandanten begehren","Die mandatierende Person begehrt","Die mandatierende juristische Person begehrt")]]
> Hier gendert die Funktion über die Person, die als MANDANT ausgewählt wurde und gibt denjenigen Text aus, der zu jeweiligen Gender gehört.
> 
> [[gendern("GEGNER","Der Beklagte betreibt","Die Beklagte begehrt","Die Beklagten betreiben","Die beklagte Partei betreibt","Die beklagte "{{GEGNER_RFORM}}" betreibt")]] mit Sitz in 
> {{GEGNER_PLZ}} {{GENER_ORT}} ein Handelsgewerbe.
> 
>     Wenn GEGNER_GESCHLECHT == "weiblich", wird daraus:
> 
>         Die Beklagte betreibt mit Sitz in 34117 Kassel ein Handelsgewerbe.
> 
>     Wenn GEGNER_GESCHLECHT == "männlich", wird daraus:
> 
>         Der Beklagte betreibt mit Sitz in 34117 Kassel ein Handelsgewerbe.
> 
>     Wenn GEGNER_GESCHLECHT == "juristische Person", wird daraus:
> 
>         Die beklagte GmbH betreibt mit Sitz in 34117 Kassel ein Handelsgewerbe.
> 
> 
> 
> 
> ## Wenn-Dann-Text
> 
> Beim Wenn-Dann-Text wird eine Variable verglichen und je nach dem Ergebnis des Vergleichs der DANN- oder der SONST-Teil ausgegeben. Die Nutzung stellen wir uns z.B. so vor:
> 
> Der folgende Aufruf
> 
> [[WennDannText(ARBR_BR=="nein","",[[gender("GEGNER","Beim Beklagten","Bei der Beklagten","Bei den Beklagten ist","Bei der beklagten Partei","Bei der beklagten Partei")]]+
> "ist ein Betriebsrat gebildet. Die ordnungsgemäße Anhörung des Betriebsrats wird (hilfsweise mit Nichtwissen) bestritten.")]]
> 
> gibt - in Kombination mit der Funktion gendern() - den SONST-Text aus, wenn die Variable {{ARBR_BR}} nicht "nein" ist. Ist die Variable aber "nein", dann erfolgt keine Textausgabe.
> 
> 2. Beispiel:
> 
> [[WennDannText(VRKHR_KENNZEICHEN=="","Das amtl. Kennzeichen ist nicht bekannt.","Das amtl. Kennzeichen lautete {{VRKHR_KENNZEICHEN}}.")]]
> 
> Wenn Kennzeichen leer ist, wird folgender Text ausgegeben:
> 
>     "Das amtl. Kennzeichen ist nicht bekannt."
> 
> Andernfalls wird zum Beispiel folgender Text ausgegeben:
> 
>     "Das amtl. Kennzeichen lautete GÖ-AB 1202."
> 
> ## Fristen-Berechnungen:
> 
> frist(DATUM;TAGE)
> Am 01.09.2021 gibt die Funktion [[frist({{KURZDATUM;15)]] folgendes Datum aus "16.09.2021"
> 
> frist_banktag(DATUM,TAGE) 
> Frist nach "Banktagen": Gibt das Datum aus, auf das der nächste Werktag "über" 15 Tage liegt; zählt im Kalender also 15 Tage zum Datum hinzu und - falls dieser Tag ein Samstag, Sonntag oder Feiertag ist, verschiebt er das Fristende solange um einen Tag nach hinten, bis es auf einen Werktag fällt. Die Bezeichnung als "Banktag" soll verdeutlichen, dass auch Samstage (die eigentlich Werktage sind) übersprungen werden sollen.

**Comment by stm9x9** [comment]
Wobei es da noch ein anderes Problem gibt, als nur dieses wenn-dann: die Unterscheidung zwischen singular und Plural. Möglicherweise müsste man hier das Modell aufweichen, nach der jeder Rolle für ein Dokument nur ein Beteiligter zugewiesen werden kann. Oder auf gut Deutsch: man muss mehr als ein Beteiligten zu Mandanten oder Gegner deklarieren können. Damit wäre es dann auch möglich, mit nur einer Vorlage, zum Beispiel Klagen für Einzelkläger und eine Klägergruppe, zu gestalten. Dann bräuchte es vielleicht einer Variable, die die Anzahl der als Mandanten deklarierten Beteiligten enthält, und dann eine Schleifenkonstruktion: Mandant eins mit Anschrift als Kläger zu 1), Mandant zwei mit Anschrift als Kläger zu 2) ...

**Comment by j-dimension** [comment]
https://user-images.githubusercontent.com/3729754/140826443-0a941e16-1070-4990-a382-bb92a3d36f57.mp4

**Comment by j-dimension** [comment]
Letztlich benötigt man für die GENDERN-Funktion sogar eine relativ umfangreiche Tabelle mit Fällen: 

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">

<html>
<head>
	
	
	<title></title>
	<meta name="generator" content="LibreOffice 6.4.7.2 (Linux)"/>
	<style type="text/css">
		body,div,table,thead,tbody,tfoot,tr,th,td,p { font-family:"Liberation Sans"; font-size:x-small }
		a.comment-indicator:hover + comment { background:#ffd; position:absolute; display:block; border:1px solid black; padding:0.5em;  } 
		a.comment-indicator { background:red; display:inline-block; border:1px solid black; width:0.5em; height:0.5em;  } 
		comment { display:none;  } 
	</style>
	
</head>

<body>


Tabelle | Key1 | Key2 | Value
-- | -- | -- | --
Kläger | weiblich | Nominativ | die Klägerin
Kläger | weiblich | Genitiv | der Klägerin
Kläger | weiblich | Dativ | der Klägerin
Kläger | weiblich | Akkusativ | die Klägerin
Kläger | männlich | Nominativ | der Kläger
Kläger | männlich | Genitiv | des Klägers
Kläger | männlich | Dativ | dem Kläger
Kläger | männlich | Akkusativ | den Kläger
Kläger | juristische Person |   |  
Kläger | divers |   |  
Kläger | undefiniert |   |  
Kläger |   |   |  
Kläger |   |   |  
Kläger |   |   |  
Kläger |   |   |  
Kläger |   |   |  
Kläger |   |   |  


</body>

</html>

**Comment by GuidoBo** [comment]
Nicht sicher, ob das stimmt bzw. ob ich das Problem verstanden habe, aber genügt nicht 
`MWDP("MANDANT_GESCHLECHT";"des Klägers";"der Klägerin";"der klagenden Person";"der Kläger (gemeinschaftlich)")`
Hier bestimmt sich der grammatikalische Fall doch nach den eingesetzten Texten uns ist der nutzenden Person überlassen, oder?

**Comment by j-dimension** [comment]
> Nicht sicher, ob das stimmt bzw. ob ich das Problem verstanden habe, aber genügt nicht
> MWDP("MANDANT_GESCHLECHT";"des Klägers";"der Klägerin";"der klagenden Person";"der Kläger (gemeinschaftlich)")
> Hier bestimmt sich der grammatikalische Fall doch nach den eingesetzten Texten uns ist der nutzenden Person überlassen, oder?

@GuidoBo  Ja, das würde auch gehen, vielleicht sollte man beide Varianten anbieten. 

Die Variante mit der Mappingtabelle spart ein wenig Tipparbeit und macht die Vorlagen kompakter. 

Aus 
`MWDP("MANDANT_GESCHLECHT";"des Klägers";"der Klägerin";"der klagenden Person";"der Kläger (gemeinschaftlich)")`
wird dann
`GENDERN("Kläger",MANDANT_GESCHLECHT,"Genitiv")`

**Comment by GuidoBo** [comment]
Ich bin nicht von dem Konzept eine Flexionstabelle überzeugt, denn gerade beim Gendern gibt es nicht immer einen einheitlichen Begriff 
m -> Kläger
w -> Klägerin
d -> Klagende Person
p -> Kläger
bzw.
m -> Rechtsanwalt
w -> Rechtsanwältin
d -> zur Rechtsanwaltschaft zugelassene Person
p -> zur Rechtsanwaltschaft zugelassene Personen

**Comment by j-dimension** [comment]
@GuidoBo die Flexionstabellen könnten ja genau das abbilden, man ist ja nicht beschränkt auf die tatsächliche Flexion eines bestimmten Wortes, sondern kann alles mögliche eintragen. 

Letztlich also keine Flexionstabelle, sondern eine Abbildungsvorschrift
vom generischen "Rechtsanwalt" die Variante "d" ergibt "zur Rechtsanwaltschaft zugelassene Person"

**Comment by GuidoBo** [comment]
Du hast sicherlich den viel bessern Einblick. Mir ist nicht klar, wie man das praktisch wird pflegen können (over engineering)?

**Comment by j-dimension** [comment]
Ich liefere ein paar Screenshots, wenn ich einen sinnvollen Zwischenstand erreicht habe.

**Comment by stm9x9** [comment]
so zb sieht das bei a-jur aus:
![image](https://user-images.githubusercontent.com/29924198/145116336-bd05c2d9-ce67-45b9-8c72-3cb4cd46fb19.png)

**Comment by j-dimension** [comment]
[j-lawyer-Scriptdemo-MANDANT.odt](https://github.com/jlawyerorg/j-lawyer-org/files/7680935/j-lawyer-Scriptdemo-MANDANT.odt)

**Comment by j-dimension** [comment]
Demovorlage mit Erläuterungen

**Comment by j-dimension** [comment]
Riesige Deklinationstabelle erarbeitet und für das Scripting bereitgestellt: 
![grafik](https://user-images.githubusercontent.com/3729754/151682757-13add8fb-490e-45e7-9a72-7b74729d426f.png)

**Comment by j-dimension** [comment]
Zu Dokumentationszwecken: Genderwörterbuch: https://www.scribbr.de/gendern/woerterbuch/

**Comment by j-dimension** [comment]
Ticket wird mit einem offenen Punkt (spätere Lieferung) abgeschlossen. 
https://github.com/jlawyerorg/j-lawyer-org/issues/1549

**Comment by stm9x9** [comment]
wobei mir gerade auffällt - vielleicht kann da ein Kollege was zu sagen? - daß die Zuordnung "juristische Person" -> weibliche Form (hier zu sehen als Auftraggeber -> die Auftraggeberin von den Gerichten auch anders gesehen wird. Bei mir ganz konkret im Sozialrecht: Das Jobcenter - unzweifelhaft keine natürliche Person - wird von den Gerichten immer als "der Beklagte" und nicht "die Beklagte" betitelt ...

Wäre es ggf. eine Option, diese Tabelle bei jedem im Adressbuch in einem Reiter mit diesem Standard oben vorbelegt anzuzeigen und dann die manuelle Änderung für diesen Kontakt individuell zu erlauben?

**Comment by j-dimension** [comment]
> Wäre es ggf. eine Option, diese Tabelle bei jedem im Adressbuch in einem Reiter mit diesem Standard oben vorbelegt anzuzeigen und dann die manuelle Änderung für diesen Kontakt individuell zu erlauben?

Die auszugsweise dargestellte Tabelle wird jeder nach eigenem Bedarf selbst ändern / ergänzen können. Sie darf jedoch nicht gelöscht werden, da die GENDERN-Funktion des Scriptings darauf zugreift.

**Comment by GuidoBo** [comment]
> wobei mir gerade auffällt - vielleicht kann da ein Kollege was zu sagen? - daß die Zuordnung "juristische Person" -> weibliche Form (hier zu sehen als Auftraggeber -> die Auftraggeberin) von den Gerichten auch anders gesehen wird. Bei mir ganz konkret im Sozialrecht: Das Jobcenter - unzweifelhaft keine natürliche Person - wird von den Gerichten immer als "der Beklagte" und nicht "die Beklagte" betitelt ...
> 
> Wäre es ggf. eine Option, diese Tabelle bei jedem im Adressbuch in einem Reiter mit diesem Standard oben vorbelegt anzuzeigen und dann die manuelle Änderung für diesen Kontakt individuell zu erlauben?

Nicht alle jur. Personen sind weiblich (der Verein). Im Verwaltungsrecht: Die Bundesrepublik Deutschland (eigentlich weiblich) wird (dankenswerter Weise) entsprechend der EuGH-Nomenklatura "der beklagte Staat". Das Bundesland Hessen ist "das beklagte Land", nicht aber Bayer ("der Freistaat").

**Comment by j-dimension** [comment]
> Nicht alle jur. Personen sind weiblich (der Verein).

Ja, das stimmt. Hier kann man selbst entsprechend ausdetaillieren / anpassen. Die Tabelle ist editierbar.

**Comment by GuidoBo** [comment]
Haben wir schon eine Dokumentation zur Nutzung der Tabelle?

**Comment by j-dimension** [comment]
> Haben wir schon eine Dokumentation zur Nutzung der Tabelle?

Ja, das wäre letztlich die GENDERN-Funktion, welche auf diese Tabelle zugreift. Hier zur Doku:
http://www.j-lawyer.org/downloads/documentation/j-lawyer.org-UserGuide-de.html#__RefHeading___Toc10728_150888202
(runterscrollen bis zur GENDERN-Funktion)
