### ISSUE TITLE
Terminkalender

### ISSUE THREAD

**Issue by j-dimension** [jlawyerorg/j-lawyer-org#108]
Kalender sollte Eintragungen zur Akte ermöglichen. Ggf. sollten auch Eintragungen ohne Akte möglich sein um Anfragen und neue Mandate aufnehmen zu können. Aktuelle Termine sollten auf Desktop/Startseite? ersichtlich sein. Termine sollten mit anderem Kalender (zB Thunderbrid Lightning) synchronisierbar sein.

**Comment by j-dimension** [comment]
https://github.com/theodorcostache/java-swing-calendar

https://sourceforge.net/p/javacaltools/news/2008/01/k5n-calendar-panel-updated/

https://sourceforge.net/projects/k5ndesktopcal/

http://timefinder.sourceforge.net/license.html

**Comment by PBaumfalk** [comment]
Nur weil ich dir so gerne auf den Keks gehe: Könnte man nicht relativ fix eine Dritte Kategorie in Wiedervorlagen & Fristen legen, die Termine heißt? So könnte man zumindest erstmal tageweise in J-Lawyer eintragen, dass dort ein "Verhandlungstermin" ist oder sowas. Im Aktenvorblatt könnte man das dann umbenennen in "Termine, WV und Fristen" und alles auflisten.

**Comment by PBaumfalk** [comment]
Also hier:

![image](https://user-images.githubusercontent.com/50404378/71959840-efe81600-31f3-11ea-9b7c-0e38d1a22422.png)

**Comment by j-dimension** [comment]
Das wäre sicher ein Einstieg und nicht so aufwändig wie die vollständig Lösung.

**Comment by RA-crm** [comment]
Wenn man den Urlaub einträgt, dann könnte man ggf auch Abwedensheiten eintragen. Ich nutze momentan die WV für Termine (in der Kanzlei / auswärts). Wenn ich aber zu einem Termin am anderen Ende der Republik muss, bin ich den ganzen Tag nicht da. Da wäre es schön, wenn man die WV auch nicht auf diesen Tag legt.

Wird dass dann schon wieder zu kompliziert?

**Comment by j-dimension** [comment]
https://github.com/mikeberger/borg_calendar

sync: 
https://github.com/mikeberger/borg_calendar/blob/master/BORGCalendar/model/src/main/java/net/sf/borg/model/ical/CalDav.java

**Comment by j-dimension** [comment]
https://sabre.io/dav/building-a-caldav-client/

**Comment by j-dimension** [comment]
Umsetzung via #955
