### ISSUE TITLE
Contact-Tabelle, Vertretende bzw. "Wirtschaftlich berechtigte Person" (erforderlich) [FEATURE]

### ISSUE THREAD

**Issue by GuidoBo** [jlawyerorg/j-lawyer-org#1082]
**Is your feature request related to a problem? Please describe. / Welches Problem soll durch die Erweiterung / Verbesserung gelöst werden?**

1. In der Tabelle "contact" kann nach meinem Verständnis exakt eine Person mit ihrer Rolle im Unternehmen gespeichert werden. Nach den Regeln des Geldwäschegesetzes muss aber (eigentlich bei fast jeder Mandatierung) ein Vertretungverhältnis abgefragt werden (handeln Sie im eigenen Namen oder (falls nicht) wer ist der "wirtschaftlich Berechtigte"). Das ist ein zwingende gesetzliche Vorgabe.
2. für die Kollisionsprüfung ist es ebenfalls erforderlich, den wirtschaftlich berechtiten "hinter" einem Unternehmen zu kennen.
3. Für ein korrektes Rubrum sind oft mehr als eine Person im Vertretungsverhältnis erforderlich. 
4. Bei rechtlichen Betreuungen und Insolvenzen gibt es ein besonderes Vertretungsverhältnis der Betreuerin/Insolvenzverwalterin

**Describe the solution you'd like / Beschreibe die gewünschte Lösung**

Eine Person (contact) sollte mehreren mit weiteren Personen (entweder vom Typ "wirtschaftlich Berechtigter" oder vom Typ "Vertreter" oder "Rechtsbeistand") zugeordnet werden können.

**Comment by j-dimension** [comment]
Ich sehe hier zwei Optionen:

1. eine Liste (in Form von Namen) von "Vertreter", "Rechtsbeistand", "wirtschaftlich Berechtigter" - d.h. keine weiteren Metadaten zu diesen Personen
2. eine vollständige Erfassung der oben genannten als eigenen Kontakt, in Kombination mit der Pflege von Relationen zwischen den Kontakten. Das wäre in Ticket #120 abgedeckt.

Ich tendiere zur zweiten Lösung.

Was meinst Du, @GuidoBo ?

**Comment by GuidoBo** [comment]
Die 2. Lösung erscheint mir auch besser.

**Comment by j-dimension** [comment]
Dann schließe ich hier als Duplikat.
