### ISSUE TITLE
Bug bei der Übernahme von Daten aus dem beA Verzeichnis 

### ISSUE THREAD

**Issue by RobertT01** [jlawyerorg/j-lawyer-org#1086]
bei der Übernahme von Daten des beA werden bei Rechtsanwälten die Straßennamen nicht übernommen
Im Feld des Straßennamen werden die Hausnummer/n eingetragen

Das Feld der Hausnummer bleibt leer.

Eine Übernahme von mehreren Hausnummern erfolgt nicht, Bsp.: 23 -26 wird nicht komplett übernommen nur 26

**Comment by j-dimension** [comment]
Erledigt. Danke für's Melden, @RobertT01
