### ISSUE TITLE
[BUG] DREBIS Nachrichten können nicht in Akte gespeichert werden.

### ISSUE THREAD

**Issue by PBaumfalk** [jlawyerorg/j-lawyer-org#1087]
**NOTE: Please search existing tickets to avoid duplicates **
**HINWEIS: Bitte vorab die Ticketsuche verwenden, um Doppeleinträge zu vermeiden **

Nachrichten in Derbys können nicht der Akte zugeordnet werden:

<img width="456" alt="image" src="https://user-images.githubusercontent.com/50404378/105318019-46d44980-5bc3-11eb-982e-b5501cb4f317.png">

Erweitertes Aktenzeichenschema. Akte wird nicht gefunden! Kann nur manuell eingespeichert werden.

**Describe the bug / Fehlerbeschreibung**
(todo: a description of the bug / eine Beschreibung des Fehlers)

**To Reproduce / Schritte zum Nachvollziehen**

1. Go to / Gehe zu '...'
2. Klicke auf / Click on '....'
4. Error message / Fehlermeldung: '...'

**Expected behavior / Erwartetes Verhalten**
Eine Beschreibung des erwarteten Verhaltens.

**Screenshots**
Falls relevant, Screenshot beifügen.

**Environment / verwendete Umgebung:**
 - OS / Betriebssystem:
 - j-lawyer.org Version:

**Additional context / Sonstiges**

**Comment by j-dimension** [comment]
@PBaumfalk und gibt es im System eine Akte FKFHZ/01/21-PBA-PBA im System, oder hat die Drebisnachricht das falsche Aktenzeichen?

**Comment by PBaumfalk** [comment]
Die Akte gibt es im System. Das passiert bei jeder Akte in DREBIS.

Mit freundlichen Grüßen / Kindly Regards

Patrick Baumfalk
Rechtsanwalt / Lawyer


Mobil:    +49 1525 53 04 194
E-Mail:   patrick.baumfalk@kanzlei-baumfalk.de


Baumfalk - Rechtsanwaltskanzlei
Hauptstr. 195
50169 Kerpen

Tel.: +49 2273 40 68 504
Fax: +49 2273 59 03 565

E-Mail: info@kanzlei-baumfalk.de
Web: www.kanzlei-baumfalk.de

Sent by Mobile

**Comment by j-dimension** [comment]
Bitte mal einen Screenshot der Einstellungen des Aktenzeichenschemas. Danke!

**Comment by j-dimension** [comment]
Ich habe eine Arbeitsthese: Du nutzt identische Trennzeichen zwischen AZ und Erweiterung und zwischen den einzelnen Angaben innerhalb der Erweiterung. Zumindest bekomme ich damit den Fehler reproduziert.

Ich habe - um wirklich alle Eventualitäten abzudecken - nun eine Aktensuche eingebaut, sollte die Akte nciht automatisch gefunden werden können. D.h. der Anwender kann in diesen Fällen manuell suchen.

**Comment by PBaumfalk** [comment]
Du bist der Beste!

Mit freundlichen Grüßen / Kindly Regards

Patrick Baumfalk
Rechtsanwalt / Lawyer


Mobil:    +49 1525 53 04 194
E-Mail:   patrick.baumfalk@kanzlei-baumfalk.de


Baumfalk - Rechtsanwaltskanzlei
Hauptstr. 195
50169 Kerpen

Tel.: +49 2273 40 68 504
Fax: +49 2273 59 03 565

E-Mail: info@kanzlei-baumfalk.de
Web: www.kanzlei-baumfalk.de

Sent by Mobile

**Comment by j-dimension** [comment]
@PBaumfalk kann ich dieses Ticket abhaken?
