### ISSUE TITLE
Drebis

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-org#109]
Ich habe mich bei Drebis angemeldet und die erste Deckungsanfrage versendet. Anmeldung hat geklappt, Versenden wohl auch??? Aber ich habe keine Kopie der versendeten Nachricht, weder im Dokumentenordner noch kann ich sie im Drebisbereich abrufen wie eine versendete mail???? Nur an der Timline sehe ich, dass ich eine Anfrage versendet habe...

**Comment by j-dimension** [comment]
Bitte bescheid geben wenn das noch auftritt.
