### ISSUE TITLE
[FEATURE] Sortierreihenfolge bei der Aktensuche

### ISSUE THREAD

**Issue by ReRo-G** [jlawyerorg/j-lawyer-org#1100]
**Is your feature request related to a problem? Please describe. / Welches Problem soll durch die Erweiterung / Verbesserung gelöst werden?**
Mir erscheint es übersichtlicher, wenn die Aktenübersicht (Aktensuche ausgelöst ohne Eingabe) nach Aktenzeichen sortiert wäre. Wonach sie derzeit sortiert ist, ist mir nicht klar.

**Describe the solution you'd like / Beschreibe die gewünschte Lösung**
Eine Vorsteinstellung in den Einstellungen, mit welcher das Verhalten eingestellt werden kann.
ODER
jl merkt sich, nach welcher Spalte zuletzt sortiert wurde.

**Comment by Maz111111** [comment]
siehe #596

**Comment by j-dimension** [comment]
In der Tat, @Maz111111 . Dann mache ich hier zu.
