### ISSUE TITLE
[FEATURE] Anzeige der ausgewählten Etiketten in der Desktop-Ansicht

### ISSUE THREAD

**Issue by ReRo-G** [jlawyerorg/j-lawyer-org#1101]
**Is your feature request related to a problem? Please describe. / Welches Problem soll durch die Erweiterung / Verbesserung gelöst werden?**
Rasche Erkennbarkeit darüber, welche Etiketten ausgewählt sind.

**Describe the solution you'd like / Beschreibe die gewünschte Lösung**
Rechts neben dem Wort Etikett könnte angezeigt werden, welche Etiketten gerade ausgewählt sind, z.B. in Klammern.
![Bildschirmfoto 2021-01-28 um 21 50 43](https://user-images.githubusercontent.com/68281026/106197661-420b2900-61b3-11eb-949d-d01cab0f4234.png)

**Comment by j-dimension** [comment]
Ich habe dieses Ticket in #981 verlinkt und schließe dieses hier als Duplikat

**Comment by ReRo-G** [comment]
Sorry, das ist mir in der Suche nicht aufgefallen. Danke!
