### ISSUE TITLE
[FEATURE] Auto Check ob Replikation erfolgreich + Mail bei Fehler

### ISSUE THREAD

**Issue by Maz111111** [jlawyerorg/j-lawyer-org#1103]
Meine Replikationsbox war unbemerkt über Tage nicht im Netzwerk. Insofern dürfte keine der täglichen Replikationen erfolgreich gewesen sein.

Es wäre gut, wenn jL dies zum einen prüft und zum anderen automatisch mit einer Mail auf den Fehler hinweist.

**Comment by j-dimension** [comment]
Bisschen was kann man da tun, aber "wasserdicht" wird das nicht. Geht schon bei trivialen Dingen wie Änderungen des Mailpasswortes für die Überwachung los. Und die Quellbox kann zwar prüfen ob die Daten rübergereicht werden können, aber ein korrekter Import ist schwer zu prüfen.

Ich transferiere das Ticket in ein anderes Repo.

**Comment by j-dimension** [comment]
Übernommen in https://github.com/j-dimension/j-lawyer-box/issues/52
