### ISSUE TITLE
[FEATURE] Schnittstelle zu Webakte

### ISSUE THREAD

**Issue by MarcoWolny** [jlawyerorg/j-lawyer-org#1104]
Schnittstelle zur Webakte von e.CONSULT AG möglich?

Unter Reiter "Dokumente" --> Kontextmenü --> Senden an Webakte

Via Webakte sind auch Schadensmeldungen mit Versicherungen austauschbar, Deckungsanfragen können abgesetzt werden - vielleicht lässt sich das auch implementieren?

Adressen aus J-Lawyer in Webakte exportieren, bestenfalls synchronisieren

**Comment by j-dimension** [comment]
Wird aus Kostengründen nicht umgesetzt. (Nutzung der API kostet)
