### ISSUE TITLE
[BUG] Login per SSH-Tunnel. Port-Angabe an falscher Stelle

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#1105]
**Describe the bug / Fehlerbeschreibung**
(todo: a description of the bug / eine Beschreibung des Fehlers)

Ich habe einen Server, den ich per ssh-Tunnel erreiche.

Auf dem Server selber ist j-l auf 8080 zu erreichen. Wenn ich den Server ohne Verschlüsselung kontaktiere, dann klappt das auch auf 8080.

Wenn ich den Tunnel verwende, dann steht dazu in der Doku (davon abgesehen, daß in Zukunft der erste Port dynamisch erzeugt wird):

_Weiterleitung: der erste Port kann beliebig gewählt werden. Es muss ein freier Netzwerkport auf dem Arbeitsplatz sein. Der zweite Port ist der Netzwerkport auf dem Server, auf welchem der j-lawyer.org Server lauscht – in der Regel 8080._

Das verstehe ich so, daß hier der zweite Port (grüner Kreis) das entscheidende ist und der Port oben (roter Kreis) nun egal ist.

so geht es aber nicht:

![image](https://user-images.githubusercontent.com/29924198/106809437-f56c9580-666b-11eb-8779-af38c39390fc.png)

Es scheint mir genau umgekehrt. Ich kann bei grün eingeben, was ich will, auch 1234, bei rot muß 8080 stehen. Mache ich rot 1234 und grün 8080 dann klappt die Verbindung nicht. Es scheint mir daher, der grüne Port ist nicht von Bedeutung und (da der Sourceport ja auch demnächst weg kommt) mann könnte die ganze Zeile einfach löschen und nur oben den Port eingeben lassen. Egal ob per Tunnel oder unverschlüsselt.

so geht es:
![image](https://user-images.githubusercontent.com/29924198/106809179-a7579200-666b-11eb-825f-60a09837d64c.png)

**Comment by j-dimension** [comment]
Der zweite Port bei Weiterleitung ist zwingend jener, auf welchem am Server der j-lawyer.org Serverdienst lauscht, idR 8080.

Der erste Port unter Weiterleitung muss in Version 1.13 zwingend mit dem "Port" unterhalb von "Server" übereinstimmen. 

Ich mache hier zu. Die Doku wird aktualisiert, wenn die 1.14 kommt, dann ist der SSH-Tunnel auch einfach zu nutzen. Sieht dann so aus:

![grafik](https://user-images.githubusercontent.com/3729754/106811577-d4f20a80-666e-11eb-9844-d5b502554faf.png)

**Comment by stm9x9** [comment]
> Der zweite Port bei Weiterleitung ist zwingend jener, auf welchem am Server der j-lawyer.org Serverdienst lauscht, idR 8080.

So hatte ich das verstanden. Aber so ist es nicht. Ich kann da auch 1234 oder 6789 eintragen. Es macht nichts aus.
 
> Der erste Port unter Weiterleitung muss in Version 1.13 zwingend mit dem "Port" unterhalb von "Server" übereinstimmen.

Das ist bei mir nicht so. Wie in meinem zweiten Bild gezeigt 8080/9091/1234 funktioniert wunderbar, wenn der Serverdienst intern auf 8080 lauscht.
 
> Ich mache hier zu. Die Doku wird aktualisiert, wenn die 1.14 kommt, dann ist der SSH-Tunnel auch einfacher zu nutzen. Sieht dann so aus:

Muß da unten wirklich überhaupt ein Port stehen? Wie gesagt, bei mir aktuell ist nur entscheidend was oben "unterhalb von Server" steht. Dann könnte man das IMHO auch unten weglassen. Dann würde man oben immer angeben, wo der Serverdienst lauscht (ob nun nach draußen oder nur intern auf dem Server - hier wäre dann in der Doku ein Hinweis gut, daß man in der Firewall diesen Port von draußen sperren sollte, damit keiner versehentlich unverschlüsselt zugreift!) und unten nur "ssh-Tunnel" auswählen und die ssh-Daten angeben.

**Comment by j-dimension** [comment]
@stm9x9 ich meine es gibt ein grundsätzliches Verständnisproblem. Die Doku sagt:

"[...] Anschließend verbindet man sich per Server und Port nicht zum Server selbst, sondern auf **localhost** zu dem ersten Port der Weiterleitungsangabe."

Ich gehe davon aus dass Du **nicht** zu localhost verbindest, sondern noch den richtigen Host drin stehen hast. Dann ist es natürlich völlig schnurz was bei den SSH-Tunnel-Angaben steht, denn dann tust Du folgendes: Du baust einen Tunnel auf, lässt ihn dann links liegen und verbindest Dich direkt.
