### ISSUE TITLE
[BUG] Doku: "Portkonflikte beheben" falsche Datei genannt

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#1106]
**Describe the bug / Fehlerbeschreibung**
(todo: a description of the bug / eine Beschreibung des Fehlers)

Da auf meinem Server die 8080 nicht (mehr) frei ist, mußte ich den Port verschieben und habe einen offset von 100 setzen wollen.

```
2021-02-03 22:11:28,992 ERROR [org.jboss.msc.service.fail] (MSC service thread 1-3) MSC000001: Failed to start service org.wildfly.undertow.listener.default: org.jboss.msc.service.StartException in service org.wildfly.undertow.listener.default: Die Adresse wird bereits verwendet /0.0.0.0:8080

2021-02-03 22:11:45,207 ERROR [org.jboss.as.controller.management-operation] (Controller Boot Thread) WFLYCTL0013: Operation ("add") failed - address: ([
    ("subsystem" => "undertow"),
    ("server" => "default-server"),
    ("http-listener" => "default")
]) - failure description: {"WFLYCTL0080: Failed services" => {"org.wildfly.undertow.listener.default" => "Die Adresse wird bereits verwendet /0.0.0.0:8080"}}
```

Laut Doku http://www.j-lawyer.org/downloads/documentation/j-lawyer.org-UserGuide-de.html#__RefHeading___Toc1752_579777149 soll ich in \wildfly-9.0.2.Final\standalone\configuration\ **standalone-full.xml** (abgesehen davon, daß der Pfad vorne bei mir keine Versionsnummer hat) 

`<socket-binding-group name="standard-sockets" default-interface="public" port-offset="${jboss.socket.binding.port-offset:100}">`

schreiben.

Das habe ich gemacht, aber der Fehler blieb. Erst eine Änderung in **standalone.xml** hat geholfen. Ich weiß nicht, warum da so viele ähnlich klingende Config-Dateien sind:

![image](https://user-images.githubusercontent.com/29924198/106811099-2057e900-666e-11eb-82f2-ab1e408ea79f.png)

**Comment by j-dimension** [comment]
Ja, die standalone.xml ist die richtige, die Information in der Doku ist veraltet. Kann direkt in der Doku angepasst werden. 

https://github.com/jlawyerorg/j-lawyer-documentation/raw/master/src/j-lawyer.org-UserGuide-de.fodt  mit LibreOffice bearbeiten und an mich emailen, dann lade ich das hoch.

**Comment by stm9x9** [comment]
done
