### ISSUE TITLE
Änderung eines Eintragsbei Wiedervorlagen

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-org#111]
Man kann jetzt einen Wiedervorlageneintrag editieren. Aber wenn man eine Frist versehentlich als Wiedervorlage eingetragen hat und editieren will, kann man nicht aus einer Wiedervorlage eine Frist machen. Also muss man alles neu anlegen....

**Comment by j-dimension** [comment]
Duplikat
