### ISSUE TITLE
[beA] steht bis alle alten Nachrichten geladen sind.

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-org#1115]
Während die Weboberfläche des BEA sich flott verwalten lässt, friert mir das BEA  regelmäßig ein, wenn ich den Client neu starte und aufs BEA gehe. Ich habe jetzt festgestellt, dass dass daran liegt, dass jedesmal im BEA vorhandene Dokumente wieder und wieder bei jedem Start komplett geladen werden (das verhält sich analog der bisher ungecacheten e-mail. Sobald alles bea-nachrichten abgehohlt wurden, geht es wieder, bis ich den Client beende. Dann geht es von vorne los....
Die Lösung wird sein (außer alles weglöschen) einfach abzuklären, welche e-mails bereits einmal geladen wurden und lokal daliegen und nur die neuen abzuholen bzw. gelöschte mails auch im Cache zu löschen.

**Comment by j-dimension** [comment]
Es wird ausschließlich der Posteingangsordner geladen. Ob das ein Problem ist oder nicht, hängt also davon ab wie man sein beA einsetzt. Mit großer Menge an Nachrichten im Posteingang dauert das intiale Laden. Hält man die Anzahl der Nachrichten in Posteingang klein (bspw. durch Verschieben in Unterordner), geht das Laden auch sehr schnell.

**Comment by Dickmaulruessler** [comment]
> wenn ich den Client neu starte

Nur aus Neugierde: Weshalb startest du so häufig neu? 

Bei mir läuft der den ganzen Tag durch.

**Comment by stm9x9** [comment]
Selbst mit großen Ordnern friert es bei mir eigentlich nur selten ein. Was aber immer wieder passiert (bei Nachrichten mit vielen Anhängen (so um die 50) immer, aber auch immer mal wieder bei ganz normalen Nachrichten): beim klicken auf eine Nachricht friert j-l für ein, zwei Minuten ein.

**Comment by Mucki526** [comment]
@Dickmaulruessler - Client läuft oft den ganzen Tag, aber es kommt immer wieder zu, dass ich ihn im Eifer des Gefechts beende und neu starten muss. Und das mit dem Einfrieren kenne ich auch. Ich habe auch ein Problem mit dem Foxit-Reader, der gerne einfriert, habe schon Arbeitsspeicher nachgerüstet, das System rauf und runter gepflegt (z.B. tweaking.com).

**Comment by j-dimension** [comment]
Bin offen und ehrlich gesagt unsicher, ob ich hier Zeit investiere, zumal auch andere Anwendungen einfrieren und es so ein umgebungsspezifisches Thema sein könnte.
