### ISSUE TITLE
dokumentenzähler BEA

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-org#1116]
Die API des BEA ist ja nicht in der Lage die Anzahl der noch nicht gelesenen Dokumente auszugeben (Wen in der Entwicklungsabteilung kann man da eigentlich höflich bitten, nötigen oder treten..., das doch endlich mal zu ändern)?. Aber über die Weboberfläche wird diese Information ja an den Browser gegeben. Was im Browser umgesetzt wird, steht ja dann als info zur Verfügung. Könnte man damit nicht evt. das Problem der unzulänglichen API umgehen im J-Lawyer Client oder ist das utopisch??

**Comment by j-dimension** [comment]
Nein, das ist leider nicht möglich. Was nicht über die offizielle API geht, kann ich nicht umsetzen. 

Die Weboberfläche nutzt interne APIs bzw. direkten Datenbankzugriff, was für externe Anwendungen ausgeschlossen ist.

**Comment by stm9x9** [comment]
da eine in j-l gelesene / geöffnete Nachricht eh nicht auf den gelesen-Status im beA-System auswirkt, ist das IMHO eh egal
