### ISSUE TITLE
Farbgebung linker Navigationsbereich

### ISSUE THREAD

**Issue by Dickmaulruessler** [jlawyerorg/j-lawyer-org#1117]
Vielleicht habe ich nicht mehr die besten Augen :-) aber jedenfalls mir ist die linke Menüleiste nicht kontrastreich genug. Mein Vorschlag wäre es, die oberen Gliederungspunkte "Akten", "Adressen", Wiedervorlagen", "Post", "Recherche"... mit deutlich dunklerem Hintergrund als die Unterpunkte darzustellen. Oder die Oberpunkte so hell zu belassen und den Hintergrund für die Unterpunkte dunkler zu machen. Das ist aber sicherlich Geschmackssache und daher gut, wenn sich auch noch andere Nutzer dazu äußern. 
![dsfdsafdf](https://user-images.githubusercontent.com/46451749/107358713-ff5f2000-6ad3-11eb-96cb-a1f9ac29e8fa.jpg)

**Comment by Dickmaulruessler** [comment]
(Das Label "enhancement" habe ich nicht bewusst gesetzt. Oder kommt das automatisch?)

**Comment by j-dimension** [comment]
Vielleicht so hier?

![grafik](https://user-images.githubusercontent.com/3729754/107434094-922aa980-6b2a-11eb-8c97-0ebf9a821e62.png)

**Comment by Dickmaulruessler** [comment]
Wunderbar! Danke!
