### ISSUE TITLE
Beteiligte in der Akte bereits auf dem ersten Reiter "Allgemeine Daten" nachrichtlich nennen

### ISSUE THREAD

**Issue by Dickmaulruessler** [jlawyerorg/j-lawyer-org#1119]
Ich würde mir wünschen, dass man bei dem ersten Klick auf die Akte bereits unter "Allgemeine Daten", dort unter "Aktenkopf" schon die Beteiligten lesen kann. Also nicht all das was im Reiter "Beteiligte" steht, sondern nur in einer Zeile die Namen - **rein nachrichtlich,** ohne Eingabemöglichkeit. Denn jedenfalls das Gericht steht nicht im Kurzrubrum mit drin, ist aber praktisch, wenn man das schon gleich auf der ersten Seite sieht. 

Die Beteiligten sind ja das Wichtigste am Ganzen und daher wäre es gut, das gleich auf den allerersten Blick zu sehen. 
![dköäkflösd](https://user-images.githubusercontent.com/46451749/109888134-4bd8ee00-7c83-11eb-978d-1160b78128e1.jpg)

Gleiches - nur die nachrichtliche Wiedergabe unter "Allgemeine Daten" - könnte ich mir auch für die "Eigenen Felder" vorstellen. Aber das mag möglicherweise nicht für jeden diese Bedeutung haben. 

Nur ganz Allgemein an dich Jens: 
Merci für Alles!

**Comment by j-dimension** [comment]
Wird in #1 fortgeführt.
