### ISSUE TITLE
[BUG] "Einstellungen" im linken Navigationsbereich

### ISSUE THREAD

**Issue by Dickmaulruessler** [jlawyerorg/j-lawyer-org#1120]
Die doppelten "Einstellungen" ganz unten im linken Navigationsbereich finde ich als Dopplung zu den "Einstellungen" ganz oben nicht so logisch... Wäre es nicht logischer, das oben zu integrieren?

**Comment by j-dimension** [comment]
Ich wollte hier eine Unterscheidung zwischen (1) eher fachlich orientierten Einstellungen, mit denen auch ein normaler Nutzer regelmäßig arbeitet. Diese werden dann auch im Hauptteil / Hauptfenster dargestellt. Und (2) eher technisch orientierten und zum Großteil nur von Nutzern mit Administrationsrechten zu bedienenden Einstellungen. Diese werden dann separat / in eigenen Dialogen dargestellt. 

Vielleicht gibt es Möglichkeiten, die beiden Kategorien klarer zu trennen. Evtl. hilft schon, die "Einstellungen" im linken Bereich anders zu benennen o.ä.

**Comment by Mucki526** [comment]
Z.B. links Einstellungen in "Vorlagen" umbenennen.

**Comment by Dickmaulruessler** [comment]
> 
> 
> Z.B. links Einstellungen in "Vorlagen" umbenennen.

Ja, finde ich verständlicher. 
Zu "Serienbriefe" passt das zwar nicht ganz. Aber doch besser als "Einstellungen". 

Wo wir gerade bei dem Vorlagen-Ordner sind. Wenn ich dort etwas bearbeite, tue ich das lieber von dort aus, wo ich es bearbeite (also im LibreOffice Writer oder Calc) und öffne es dort dann aus dem Ordner direkt **(C:\Program Files\j-lawyer-server\j-lawyer-data\templates).** Den Pfad hatte ich damals nur mit Jens´ Hilfe gefunden. Ich weiß nicht, ob andere das auch gerne wüssten und ob die Nennung des Pfades hier von Interesse wäre. Platz genug wäre ja in der linken Spalte.
![sdsaDASdsaDAA](https://user-images.githubusercontent.com/46451749/108418249-44502880-7231-11eb-9b4f-40753450f99e.jpg)
