### ISSUE TITLE
.odt automatisch x Zeilen nach unten scrollen

### ISSUE THREAD

**Issue by Dickmaulruessler** [jlawyerorg/j-lawyer-org#1123]
Ich finde die Vorschaufunktion von Dokumenten so hervorragend! Danke für diese cooole Tool!

Man kann sich mit den Text-Extraten sehr schnell durch einen Fülle an Dokumenten durchklicken und man weiß schon nach einem kurzen Blick sofort bescheid. 

Hierzu hätte ich kleine Optimierungswünsche:

1. Beim Textextrakt wird erst der gesamte Briefkopf gezeigt. Das sind (wegen Tabelle für Absender und Empfänger, wo jede Zelle in der Vorschau eine eigene Zeile erhält, komischerweise wird auch die Fußzeile komplett da oben dargestellt...) bei mir immerhin 50-52 Zeilen. Die muss man immer 50 Zeilen nach unten scrollen. 
> Kann es so eingestellt werden, dass bei der Vorschau **automatisch so ca. 50 Zeilen nach unten gescrollt** wird?

2. Ich würde die Sinnhaftigkeit des Screenshots hinterfragen. Generell finde ich die eigentlich sehr hipp! Aber außer der Anzahl der Absätze erkenne ich darin nichts, was für mich irgendneinen Informationswert hätte. Der Screenshot nimmt auch viel Platz weg, welches dem Vorschaufenster dann fehlt. Für mich ist der Screenshot ohne Wert. 
> Ich würde zur Diskussion stellen, die **Screenshots ganz zu entfernen.**

3. Die Breite des Vorschaufensters ist links durch die im Wege stehenden Buttons "Datum", "Name", "Favorit", "Größe", "Ordner" begrenzt. Man kann es nicht weiter nach links schieben und so dem Vorschaufenster rechts mehr Platz geben. Das ist durchaus relevant, da im Vorschaufenster keine automatischer Umbruch erfolgt. 
> Wäre das durch irgendeinen Weg änderbar, so dass man das **Vorschaufenster durch Verschieben nach links dieses vergrößern** kann? 

Z.B.:
- automatischer Umbruch der Buttons, wenn man die Trennung links rüber zieht oder
- generell zweizeilig?
- deutliche Verkleinerung der Buttons?
- Hochschieben der Buttons rechts neben die darüberliegende Suchzeile, wo noch Platz ist?
- Alle Buttons in ein Pulldown-Menü (das Datum ist mit Abstand das wichtigste Sortierkriterium)?

Vielen Dank!

**Comment by j-dimension** [comment]
> Kann es so eingestellt werden, dass bei der Vorschau **automatisch so ca. 50 Zeilen nach unten gescrollt** wird?

Das schaue ich mir an.

**Comment by j-dimension** [comment]
> Ich würde zur Diskussion stellen, die **Screenshots ganz zu entfernen.**

Das können wir gern zur Diskussion stellen. Ich habe auch schon einige positive Rückmeldungen dazu bekommen. Vielleicht können wir hier ein breiteres Meinungsbild einholen.

**Comment by j-dimension** [comment]
> Wäre das durch irgendeinen Weg änderbar, so dass man das **Vorschaufenster durch Verschieben nach links dieses vergrößern** kann?

Das ist bereits umgesetzt, kannst Du Dir gern im Demosystem anschauen: https://www.j-lawyer.org/?page_id=310

**Comment by Dickmaulruessler** [comment]
> 
> 
> > Wäre das durch irgendeinen Weg änderbar, so dass man das **Vorschaufenster durch Verschieben nach links dieses vergrößern** kann?
> 
> Das ist bereits umgesetzt, 
>
Genial gemacht mit dem Mix aus Icon und Wechsel zu Text! 
Links Verschieben funktioniert wunderbar. Merci!

**Comment by stm9x9** [comment]
> 1. Das ist durchaus relevant, da im Vorschaufenster keine automatischer Umbruch erfolgt.

wie sieht es denn damit aus? Kann man da was machen? Es gab ein ähnliches Ticket #1035 da lag es an einer Drittkomponente => #wontfix. Tut es das hier auch?

**Comment by j-dimension** [comment]
> > 1. Das ist durchaus relevant, da im Vorschaufenster keine automatischer Umbruch erfolgt.
> 
> wie sieht es denn damit aus? Kann man da was machen? Es gab ein ähnliches Ticket #1035 da lag es an einer Drittkomponente => #wontfix. Tut es das hier auch?

Nein, das ist keine Komponente mit Styling à la HTML. 

So hier?


https://user-images.githubusercontent.com/3729754/108128607-4a1d0100-70ad-11eb-85d1-e3644891f178.mp4

**Comment by j-dimension** [comment]
Hier noch das automatische Scrollen. Es ist jetzt eine gewisse "Intelligenz" umgesetzt, die versucht den relevantesten Textteil zu ermitteln. Wird nicht immer zuverlässig klappen, aber in den meisten Fällen. 


https://user-images.githubusercontent.com/3729754/108137447-290fdc80-70bc-11eb-8636-ea8697f06979.mp4

**Comment by j-dimension** [comment]
Ich würde dann hier zu machen, okay, @Dickmaulruessler ?

**Comment by Dickmaulruessler** [comment]
Hi Chef, 

danke, das haben Sie wirklich hervorragend gelöst!

Mit freundlichen Grüßen
Herr Dickmaulrüssler

**Comment by Dickmaulruessler** [comment]
(Nur aus reiner Neugierde: Das ist sicherlich eine Drittkomponente, oder? Wie kommt es, dass die Fußzeile nach oben gezogen wird? Macht das bei anderer Verwendung Sinn?)

**Comment by j-dimension** [comment]
> Wie kommt es, dass die Fußzeile in der Vorschau nach oben gezogen wird?

Das verstehe ich gerade nicht. Was genau meinst Du?

**Comment by Dickmaulruessler** [comment]
![fussnote](https://user-images.githubusercontent.com/46451749/108225385-2fde3400-713c-11eb-85ea-f66e61f67aa7.jpg)

**Comment by j-dimension** [comment]
Ah, jetzt! 

Die Textextraktion macht Apache Tika, ich habe keine Ahnung warum der Text dann dort oben erscheint... :-(
