### ISSUE TITLE
[MEINUNGSBILD] Soll der Dokumenten-Screenshot in der Dokumenten-Vorschau weg?

### ISSUE THREAD

**Issue by Dickmaulruessler** [jlawyerorg/j-lawyer-org#1124]
Mein Vorschlag wäre es, den Dokumenten-Screenshot ("Foto" der Seite / oben) zu entfernen, damit für die Dokumenten-Vorschau (Textextrakt / unten) mehr Platz ist.

Meine Argumente:

- der Screenshot hat keinen eigenen Wert, man erkennt nix (allenfalls, wieviele Absätze das Dokument hat und ob es sich um einen Schriftsatz oder um eine Rechnung handelt, das erkennt man aber schon aus dem Dateinamen)
- der Screenshot raubt der eigentlich tollen Dokumentenvorschau viel Platz
- würde man den Preview (durch gesondertes Laden) lesbar machen, bräuchte man dafür noch mehr Platz und der Vorteil des schnellen Durchklickens wäre dahin. 

Siehe auch hier: https://github.com/jlawyerorg/j-lawyer-org/issues/1123#issuecomment-778637601

Eure Meinung?

**Comment by j-dimension** [comment]
Ggf. parallel noch in der Mailingliste posten.

**Comment by ReRo-G** [comment]
Ich muss an dieser Stelle mal unwissen nachfragen: Ich sehe nur die Vorschau (die bei jedem Klick auf ein Dokument neu geladen wird). Eine Screenshot-Preview wird mir nicht angezeigt. Kann man diese vielleicht jetzt schon deaktivieren und ich habe das versehentlich getan (jl läuft bei mir auf macOS).

**Comment by j-dimension** [comment]
@ReRo-G ich meine der @Dickmaulruessler bezieht sich hier spezifisch auf .odt-Dateien. 

Du solltest auch auf macOS Vorschauen haben für .odt - ist das der Fall?

**Comment by Mucki526** [comment]
Ich finde, die odt-Vorschau sollte/könnte genauso aussehen wie jetzt die geniale PDF-Vorschau. Das schnelle Scrollen in den Dateien sollte dabei kein Problem sein. Das Nachladen des Dokuments erfolgt einfach, wenn man länger auf einem odt-Dokument stehen bleibt. Irgendwie wird das kleine preview ja auch erzeugt. Und Speicherplatz stellt doch heute eigentlich kein großes Problem mehr dar (im Vergleich zu früher). Wie wäre es mit Reitern in den Einstellungen, in welchem man sich aussuchen kann, welche Darstellung erfolgen soll oder nicht. Dann wäre fast jeder glücklich, außer vermutlich der Programmierer, der das umsetzen muss ;-).

**Comment by j-dimension** [comment]
> Ich finde, die odt-Vorschau sollte/könnte genauso aussehen wie jetzt die geniale PDF-Vorschau.

Das wäre mir auch am liebsten, ist aber technisch nicht möglich. 

Die kleinen Vorschaubilder werden von LibreOffice automatisch generiert und sie liegen dann "an einer bestimmten Stelle" in der .odt-Datei, von wo ich sie aktuell extrahiere. Eine Möglichkeit, die Auflösung zu vergrößern, gibt es leider nicht.

Auch ist es nicht möglich, LibreOffice eingebettet in j-lawyer anzuzeigen. Außerdem würde das die Zeit für das Aufbauen der Vorschau - je nach Hardware - auf mehrere Sekunden erhöhen.

Auch einen Umweg über PDF habe ich betrachtet: das Dokument zum Zweck der Vorschau in ein PDF umwandeln. Wartezeit wäre hier noch höher. 

Einzige Möglichkeit wäre mit jedem Speichern zusätzlich ein PDF zu generieren. Würde den Speichern-Vorgang in die Länge ziehen.

Wenn es eine gute Möglichkeit gäbe, hätte ich sie unabhängig vom Aufwand umgesetzt, da die Arbeit mit Dokumenten so essentiell ist.

**Comment by ReRo-G** [comment]
@j-dimension 
Danke für die Aufklärung. Ich habe keine .odt-Dateien, daher sehe ich wohl auch das kleine Bild nicht. Danke für die Erhellung.

Nur zur Info:
Der Workflow mit den derzeit integrierten PDF-Vorschau ist auf meinem System zu langsam, was natürlich an meinem vier Jahren alten Mac liegen kann. Im Ergebnis öffne ich die Dateien direkt als PDF, das ist zwar auch langsam, aber damit kann ich dann schneller blättern/scrollen). Wenn ich mich recht entsinne, hattest Du, Jens, für die 1.14 schon eine Option eingebaut, dass die PDF-Vorschau gar nicht mehr geladen wird.

**Comment by iradraconis** [comment]
Also ich finde die Vorschau von ODT Dateien als Screenshot sehr hilfreich. So kann ich auf einen Blick (bei einseitigen Dokumenten) sehen, ob ich schon eine Unterschrift gesetzt habe oder nicht. Das nur als Beispiel.

**Comment by j-dimension** [comment]
Ich belasse das Thumbnail also vorerst wie es ist.
