### ISSUE TITLE
Dokumentensuche

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-org#1127]
Die Dokumentensuche zeigt nur eine Fehlermeldung bei uns "searchindex 0". Und unter Einstellungen Dokumenten kommt die Fehlermeldung, dass die Dokumentenanzahl nicht ermittelbar ist. Ich habe gestern von einem Rechner aus den Neuaufbau des Index angestoßen, wiel es angeboten wurde, hat nichts geholfen... Search index not initialized.... :-(

**Comment by j-dimension** [comment]
Für solche Themen bitte das Forum nutzen, Github ist nicht für Support gedacht, nur für entwicklungsrelevante Themen. 

In diesem Fall wird wahrscheinlich ein Neustart des Dienstes, gefolgt von Neuaufbau des Indexes helfen.

Grüße!

**Comment by Mucki526** [comment]
Danke, geht wieder.... Viele Grüße
