### ISSUE TITLE
[adressen] Neue Felder für Initialen, akademische Grade, Geburtsname, Geburtsort und Beruf

### ISSUE THREAD

**Issue by j-dimension** [jlawyerorg/j-lawyer-org#113]
Es wäre schon, um Felder für Initialen und akademische Grade zu bekommen. In den Niederlanden ist es z.B. unüblich im Rechtsverkehr die Gegenseite mit Vornamen und ohne akademische Grade anzuschreiben, z.B. "Hans van der Donk". Richtig wäre "H.P.L. van der Donk, LLM". 
Das Feld "Vorname" sollte weiterhin bestehen bleiben, jedoch scheinen mir obige Felder als Zusatz sehr sinnvoll. Vor allem ein Feld für akademische Grade wäre sicherlich auch in Deutschland nützlich

**Comment by j-dimension** [comment]
neue Eingabefelder für "Geburtsname," "Geburtsort" und "Beruf" samt Platzhaltern

**Comment by librelegal** [comment]
Die Bezeichnung dieses issues sollte vereinheitlicht werden. Es geht um Adressen, deshalb "Adressen:" voranstellen. Außerdem war ein Tippfehler im Betreff.
Insgesamt wie nachstehend:
Adressen: Felder für Initialen, akademische Grade, Geburtsname, Geburtsort und Beruf
