### ISSUE TITLE
[FEATURE] Infobereich für Optionen im Rahmen der Dokumentensuche

### ISSUE THREAD

**Issue by Dickmaulruessler** [jlawyerorg/j-lawyer-org#1131]
Dies ist ein Unterpunkt von #1130, der mit diesem Ticket abgeschichtet umgesetzt werden könnte. 

Dort wurde vorgeschlagen, [dies ](http://www.j-lawyer.org/downloads/documentation/j-lawyer.org-UserGuide-de.html#__RefHeading__427_1146603382 )verkürzt entweder durch einen Info-Button oder ggf. dauerhaft anzuzeigen. 
Falls dauerhaft: Das Suchfeld könnte in der Breite verringert werden und dann wäre rechts neben "Dokumentensuche" viel Platz für kurze Hinweise.

Ggf. so:

**Felder:   text:    dateiname:    autor:    akte:   az:     Bsp: text:Kauf**
(Beschreibt "Felder" das für Anwälte verständlich? Oder anderes Wort denkbar? "Suchbereiche"? "Suchkriterien"? "Suchbefehle"?

**Suchoptien:       AND         OR      
                           "Wortgruppe mittels Anführungszeichen"**
                            ("Hochkommata", so in der Dokumentation, ist glaube ich [nicht korrekt](https://de.wikipedia.org/wiki/Anf%C3%BChrungszeichen))

**Wildcards:             " für ein Zeichen,            * für mehrere Zeichen.**

Evtl. ergänzender **Hilfetext** in Langtext-Form mit rotem "?" mit Tool-Tip, Info-Fenster oder direkten Link auf Unterseite der Dokumentation.

**Comment by Dickmaulruessler** [comment]
supi! Mit Tool-Tip!

**Comment by j-dimension** [comment]
Rechte obere Ecke hat ein ?-Icon mit Tooltip:

![grafik](https://user-images.githubusercontent.com/3729754/108761976-d452e280-754f-11eb-80cd-067ce7ad2c0f.png)

**Comment by Dickmaulruessler** [comment]
Danke! Super!

**Comment by stm9x9** [comment]
> **Felder: text: dateiname: autor: akte: az: Bsp: text:Kauf**
> (Beschreibt "Felder" das für Anwälte verständlich? Oder anderes Wort denkbar? "Suchbereiche"? "Suchkriterien"? "Suchbefehle"?

Suchbereich fände ich verständlicher.

**Comment by j-dimension** [comment]
Ausschluss über "-" noch mit aufnehmen
