### ISSUE TITLE
[FEATURE] Beteiligte Tooltip dauerhaft

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#1135]
Wenn ich auf einen Beteiligten gehe mit der Maus, dann kommt ein Tooltip mit den wichtigsten Daten. Leider verschwindet der tooltip nach wenigen Sekunden wieder und ich bin nicht schnell genug, zb eine Telefonnummer abzutippen im Handy. Obwohl ich die Maus nicht bewegt habe.

![image](https://user-images.githubusercontent.com/29924198/109026323-ea7fb080-76bf-11eb-8af5-6e2befd00200.png)

Wäre gut, wenn der tooltip so lange offen bleibt, wie die Maus auf der Stelle bleibt.

**Comment by j-dimension** [comment]
Dup von #957
