### ISSUE TITLE
[FEATURE] Datensicherung: Technisch vereinfachen und Dokumentation erweitern

### ISSUE THREAD

**Issue by Dickmaulruessler** [jlawyerorg/j-lawyer-org#1139]
Datensicherungen sind so enorm wichtig - aber ich könnte wetten, dass nur 1/3 oder weniger der j-lawyer Anwälte ein vernünftiges Backup auf einem **_externen_** Medium haben. Auch ich habe es leider noch nicht hinbekommen. Sünde! 
Ich habe nur das automatische Backup aktiviert, aber das ist ja eben nur auf derselben Platte. 

Die [Dokumentation ](http://www.j-lawyer.org/downloads/documentation/j-lawyer.org-UserGuide-de.html#__RefHeading__433_1146603382) finde ich - für Anwälte - zu knapp. Ich (immerhin technisch nicht gaaaanz "doof"...) verstehe es leider nicht. 
Gerade in diesem Punkt sollte es glaube ich wirklich eine gute Schritt-für-Schritt-Anleitung mit Screenshots "für Doofe" sein, da das wirklich **_jeder_** unbedingt einrichten sollte. 

Insbesondere bei dem wichtigen Unterpunkt "Synchronisation" bin ich heillos überfordert, was die unterschiedlichen Optionen unterscheidet. Technisch überfordert mich auch die Auswahl des Zielordners, da das hier nicht "wie immer" geht. Kann dieser Punkt vereinfacht (direkte Auswahl des Ordners) oder aber in der Doku detailliert erläutert werden?

Da das ganze Thema so enorm wichtig ist: Wäre evtl. auch ein Video dazu sinnvoll? (Anm.: Videos mit sprachlicher Erläuterung finde ich wesentlich verständlicher, als ohne ebensolche)

Ist die Synchronisation zeitlich an das automatische Backup gekoppelt oder erfolgt die nur manuell?

**Comment by j-dimension** [comment]
> Insbesondere bei dem wichtigen Unterpunkt "Synchronisation" bin ich heillos überfordert, was die unterschiedlichen Optionen unterscheidet. Technisch überfordert mich auch die Auswahl des Zielordners, da das hier nicht "wie immer" geht. Kann dieser Punkt vereinfacht (direkte Auswahl des Ordners) oder aber in der Doku detailliert erläutert werden?

Ich könnte beispielhafte Einstellungen für Windowsfreigaben und SSH/SFTP aufnehmen, jedoch ohne Schritt-für-Schritt-Anleitung zum Erstellen dieser Freigaben. Das ist zum Einen keine Spezifik der Kanzleisoftware, und zum Anderen auch schlicht stark unterschiedlich zwischen Betriebssystemen und Betriebssystemversionen.

Eine direkte Auswahl des Zielordners ist nicht möglich, da der Orner sich nicht am Arbeitsplatz befindet, sondern am Server, und eben nur über bestimmte Protokolle erreichbar ist, die von keinem Datei-/Ordnerauswahldialog unterstützt werden. Sie werden bei Bestätigung aber geprüft.

**Comment by j-dimension** [comment]
> Ist die Synchronisation zeitlich an das automatische Backup gekoppelt oder erfolgt die nur manuell?

Die Dokumentation meint dazu: "Das System wird stündlich eine Synchronisation probieren." 
Es wird direkt nach Erstellung der Sicherung eine Synchronisation durchgeführt, aber eben zusätzlich stündlich neu probiert, falls das Zielgerät nicht verfügbar war.

**Comment by Dickmaulruessler** [comment]
ok

**Comment by j-dimension** [comment]
Bin mir gerade nicht sicher, für das das "ok" gilt :-)  für die Beispiele, wie man die Synchronisation konfiguriert?

**Comment by Dickmaulruessler** [comment]
> 
> 
> Bin mir gerade nicht sicher, für das das "ok" gilt :-) für die Beispiele, wie man die Synchronisation konfiguriert?

"Ok" für deinen Verfahrensvorschlag. Ich warte erst einmal ab und gedulde mich noch.

**Comment by j-dimension** [comment]
Dokumentation erweitert.
