### ISSUE TITLE
Client Installer Win64 with 64Bit LibreOffice

### ISSUE THREAD

**Issue by j-dimension** [jlawyerorg/j-lawyer-org#114]
When working on the client installer, I realized that unoconv is currently not working with LibreOffice? 64Bit (LO 5 is the first version with 64Bit binaries). 
reverted the j-lawyer.org Client Installer (Win 64Bit) to install LO 5 32Bit
updated unoconv despite the known issue
todo:
upgrade to latest unoconv if this has been fixed: ​https://github.com/dagwieers/unoconv/issues/57, download via ​https://github.com/dagwieers/unoconv
update installer to install 64 Bit: (1) compiler variable (2) "Validation Expression" in install4j Configurable Form for LO and (3) install .bat -script that is downloaded together with the LO MSI installer
testing on Windows 64 Bit with 64 Bit client installer
Note: After installing 32 Bit LO, python.exe wasn't working, I had to enable compatibility mode for this exe, and it started working.

**Comment by j-dimension** [comment]
LO 6 mit macOS - siehe Kommentare hier: https://github.com/unoconv/unoconv/issues/391#issuecomment-503053330

**Comment by PBaumfalk** [comment]
LO 6 mit macOS klappt wohl immer noch nicht:
https://github.com/unoconv/unoconv/issues/478

**Comment by j-dimension** [comment]
Angeblich soll es gehen wenn man statt unoconv aufzurufen die Python-Runtime von LO ruft und unoconv "übergibt". Muss ich mal testen.

**Comment by librelegal** [comment]
Eventuell ist mit dem geschlossenen issue #679 auch für dieses issue eine Vorbedingung erfüllt? Sieht so aus, als wäre zumindest bei MacOS die neue unoconv implementiert.

**Comment by j-dimension** [comment]
Das ist in der Tat komplett via #679 umgesetzt.
