### ISSUE TITLE
[TASK] Hilfetext "NOTIZTEXT" unter Notizen entfernen

### ISSUE THREAD

**Issue by Dickmaulruessler** [jlawyerorg/j-lawyer-org#1140]
In der Akte unter Dokumente / "große" (formatierbare) Notizfunktion steht der Hilfetext "NOTIZTEXT". Für den allerersten Nutzer mag das hilfreich sein - aber eigentlich ist es schon selbsterklärend, dass man an der Stelle den Text hereinschreiben muss. 
Wenn man das regelmäßig nutzt, ist es nervig, wenn man das Wort "NOTIZTEXT" immer erst entfernen muss. 

Kann man stattdessen den Fokus in das Feld setzen?

**Comment by j-dimension** [comment]
Text angepasst. Fokus kann ich nicht steuern, da es sich um eine Drittkomponenten handelt (für die Bearbeitung formatierter Texte). Ich kann nur der Gesamtkomponente sagen "bitte Fokus auf Dich", habe dann aber nicht ausreichend Kontrolle darüber, ob die Toolbar oder der Textinhalte fokussiert wird.
