### ISSUE TITLE
Rechtsklick auf Dokument sollte dieses markieren und alle anderen ggf. demarkieren

### ISSUE THREAD

**Issue by Maz111111** [jlawyerorg/j-lawyer-org#1141]
Problem:
Es ist ein Dokument markiert.

Man will ein anderes löschen. Unter Win führt der Rechtsklick auf eine Datei dazu, dass sich ein Kontextmenü öffnet und die gewählte Aktion sich auf die Datei bezieht, auf der beim Rechtsklick der Mauszeiger lag. Diese Datei wird mit dem Rechtsklick markiert.

Ich weiß nicht, wie das bei anderen Betriebssystemen ist.

Als Windowsnutzer ist es aber mehr als ungewohnt, das dies in jL nicht so ist. So kam es eben mal wieder, dass ich etwas löschen wollte und die weiter unten markierte Datei löschte - nicht aber die, auf die ich den Rechtsklick gesetzt hatte.

Intuitiver wäre es m.E., wenn sich die Clientversion hinsichtlich solcher Features an die Vorgaben des jeweiligen Betriebssystems halten würde. Vielleicht ist es ja auch in jedem System so, dass der Rechtsklick zur Markierung führt.

**Comment by j-dimension** [comment]
Bei Mehrfachselektion ist dann jetzt nur noch per Shift / Ctrl ein Popup zu öffnen.
