### ISSUE TITLE
[FEATURE] Aus einer Akte heraus direkt in eine beliebige andere Akte des Mandanten springen können

### ISSUE THREAD

**Issue by Maz111111** [jlawyerorg/j-lawyer-org#1142]
Oft haben Mandanten mehrere Mandate übergeben. Diese hängen oft auch zumindest so miteinander zusammen, dass zumindest die Unterlagen des Mandanten mal hier und mal dort gebraucht werden. Manchmal auch nur um nochmal etwas nachzusehen - ohne dass die Unterlage tatsächlich in allen Akten als Kopie benötigt wird.

Dann fände ich es gut, wenn man in einer Akte eine Liste der anderen Mandate des Mandanten aufklicken könnte (z.B. im Reiter Beteiligte) und dann direkt in die andere Akte springen könnte.

Viele Grüße
Martin

**Comment by j-dimension** [comment]
Wäre es nicht zielführender, Dokumente direkt an der Person hinterlegen zu können?

https://github.com/jlawyerorg/j-lawyer-org/issues/281

**Comment by Maz111111** [comment]
Das ist nicht das, was ich meine. Allerdings träfe mein Beispiel den von Dir beschriebenen Fall.

Es geht darum, schnell den Verlauf eines anderen Verfahrens überschauen zu können. Oder auch WVs abgleichen zu können.

Bsp: Scheidung - VKH beantragt. Gericht verweist mich darauf, beim GG zunächst einen Verfahrenskostenvorschuss geltend zu machen. Das ist ein anderes Mandat. Beide sind aber irgendwie miteinander verbunden. Wenn ich das nächste Mal in die Scheidungssache schaue, werde ich mich fragen, wie weit die Sache mit dem VKV ist. 

Sowas und ähnliches meine ich.

Verschiedene Dokumente an bestimmte Personen zu hängen, trifft das nicht exakt.

**Comment by j-dimension** [comment]
Verstehe, danke.

**Comment by stm9x9** [comment]
Der Weg, den Mandanten zu öffnen und da dann aus dem Reiter Akten die Akte auszuwählen, ist "zu weit" in dem Szenario? Oder geht es mehr um die Möglichkeit, noch eine andere Akte zum Reinschauen mal schnell öffnen zu können? Das wäre dann #402 oder #837 ?

**Comment by Maz111111** [comment]
Dies Funktionalität war mit nicht bekannt.

Reicht mir! Dankeschön!
