### ISSUE TITLE
[BUG] Fehler beim Speichern. Failed to read response bei zu langem Text in einer Betreffzeile eines Beteiligten

### ISSUE THREAD

**Issue by Maz111111** [jlawyerorg/j-lawyer-org#1144]
**Describe the bug / Fehlerbeschreibung**
Offenbar scheitert das Speichern einer Akte, wenn in einer Betreffzeile zu einem Beteiligten eine zu hohe Anzahl an Zeichen eingegeben wird. Fehlermeldung "Fehler beim Speichern. Failed to read response."

**To Reproduce / Schritte zum Nachvollziehen**

es wurde ein 5. Beteiligter angelegt und in der Betreffzeile 2 was folgt eingegeben "betreffend die Ersetzung der Einwilligung in eine genetische Abstammungsuntersuchung und die Duldung der Entnahme einer für die Untersuchung geeigneten genetischen Probe (§ 1598a Abs. 2 BGB) zur Klärung der leiblichen Abstammung des minderjährigen Kindes "

**Expected behavior / Erwartetes Verhalten**
normales Abspeichern

**Environment / verwendete Umgebung:**
 - OS / Betriebssystem: Win10
 - j-lawyer.org Version: 1.13.0.5

**Comment by j-dimension** [comment]
Was ist mit "Betreffzeile" gemeint? Eines der eigenen Felder?

**Comment by Maz111111** [comment]
Im Reiter Beteiligte kann ich mit den zwei nach unten gerichteten Pfeilen bei jedem Beteiligten weitere Felder aufklappen.
"Ansprechpartner", "Betreff Zeile1", "Betreff Zeile2" und "Betreff Zeile3".

Diese Betreffzeile meine ich.

Ich habe es auch nochmal in einer anderen Akte versucht. Auch da kam es zu der Fehlermeldung.

**Comment by j-dimension** [comment]
Okay, jetzt weiß ich was gemeint ist. Die hast Du so benannt, daher musste ich nachfragen. 

Schaue ich mir an.

**Comment by Maz111111** [comment]
> Die hast Du so benannt,

Sorry, das habe ich nicht mehr gewusst - aber gut zu wissen .-)
