### ISSUE TITLE
[BUG] Button zum Hinzufügen von Beteiligten linksbündig

### ISSUE THREAD

**Issue by Dickmaulruessler** [jlawyerorg/j-lawyer-org#1146]
In der Akten-Ansicht beginnt alles auf der linken Seite. 
Allein der **"+"-Button zum Hinzufügen der Beteiligten** steht ganz rechts. Bei meinem großen Bildschirm _sehr_ weit rechts. 
Hat das einen Grund?

Mein Vorschlag wäre es, diesen Button linksbündig zu setzen. 
Auch in dem darauf folgenden Such-Fenster ist der Button linksbündig. 

(ja, Jens, das ist eine pingelige Kleinigkeit, aber daran sieht man nur einmal wie perfekt das Programm sonst schon ist! Danke!)

**Comment by j-dimension** [comment]
Das ist bereits geändert worden, in der Onlinedemo kann man das schon betracht :-)
