### ISSUE TITLE
BUG: Straße verschwindet bei Verfeinerung einer Adresse und Import aus beA Datenbank

### ISSUE THREAD

**Issue by iradraconis** [jlawyerorg/j-lawyer-org#1148]
Beispiel: ich lege einen Kollegen unter Adressen an. Ich möchte anschließend seine kompletten Daten inklusive beA-Adresse erfassen. Das mache ich über die Adresseingabe (nicht Schnelleingabe). Über die Bea-Suche finde ich ihn, füge ihn hinzu. Unter Straße erscheint dann nur die Hausnummer und die Straße selbst ist nicht vorhanden. 

Bei Behörden kommt es dann mal vor, dass die PLZ und Stadt hinter dem Namen gespeichert wird. 

Ich weiß nicht, ob das ein generelles Problem ist, mir ist es jedenfalls schon etliche Male passiert.

**Comment by j-dimension** [comment]
Die Übernahme der Daten aus dem BRAK-Verzeichnis hat keine Logik i.S.v.

"wenn bereits eine Strasse erfasst ist, überschreibe nicht, ansonsten nimm die Daten von der BRAK". 

Es werden schlicht die Informationen der BRAK übernommen. Ist dort die Strasse leer, so wird eine evtl. händisch eingegebene Strasse entfernt.

**Comment by iradraconis** [comment]
Ok, in meinem Beispiel hatte ich keine Straße eingegeben und dann wurde bei Straße lediglich die Hausnummer eingetragen. Ich "meine" das war in 1.12 noch nicht so. Da hatte ich Adressen auch so verfeinert und das klappte prima.

**Comment by j-dimension** [comment]
Ach sehe gerade dass das wahrscheinlich ein Duplikat von https://github.com/jlawyerorg/j-lawyer-org/issues/1086 ist. Ist bereits bearbeitet.
