### ISSUE TITLE
[BUG] lauter Fehlermeldungen (beA?) nach Rechner-Standby

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#1150]
Wenn ich j-l geöffnet habe und in beA eingeloggt bin und dann den Rechner in den Standby schicke, dann bekomme ich nach dem Aufwecken (nach längerer Zeit) zig (keine Ahnung, 10 oder mehr) identische Fehlermeldungen angezeigt, die ich alle wegklicken muß.

![image](https://user-images.githubusercontent.com/29924198/110021846-88602480-7d2b-11eb-8635-93713571aae1.png)

Ich vermute, daß eine nicht mehr bestehende Verbindung zu beA dahinter steckt und schlicht tatsächlich ein Fehler vorliegt und zu Recht gemeldet wird. Aber ein unbedarfterer Nutzer, eine nicht so technisch affine Refa, der wird a) Panik bekommen wegen der Anzahl und b) nicht verstehen, was das System da von ihm will. Beides wirkt sich schlecht auf die User-experience aus :-) Und kein Anwalt will, daß sein Personal über die Technik schimpft! :-D 

Kann man a) den Fehlertext etwas "anwalts/refafreundlicher" machen und b) die zig Meldungen abfangen? Oder sowas wie: 

"Die Verbindung zum beA-Server ist unterbrochen. Soll versucht werden, die Verbindung wiederherzustellen? Ja/Nein."
Und dann halt entweder richtig ausloggen (so wie wenn man auf den Button dafür oben links klickt) oder halt Ausloggen und Neuverbindung probieren.

**Comment by j-dimension** [comment]
Duplikat von #1094
