### ISSUE TITLE
Präfix für Datensicherungsmail

### ISSUE THREAD

**Issue by Dickmaulruessler** [jlawyerorg/j-lawyer-org#1154]
Bei erfolgreicher Datenbanksicherung lautet der Betreff in der E-Mail
![fdsddsf](https://user-images.githubusercontent.com/46451749/110174073-d6def300-7dff-11eb-9930-3d7ae1522755.jpg)

bei einem Fehler
![jkdlsföaf](https://user-images.githubusercontent.com/46451749/110174103-e8c09600-7dff-11eb-88bd-1a4604b50322.jpg)

Falls man seine Mails nach dem Betreff mit der Regel "enthält" den Betreff "j-lawyer.org Datensicherung vom" sortiert, landen auch die mit "Fehlgeschlagen" darin. 

Daher zusätzlicher Präfix für "erfolgreich"?

Und damit jeder das sinnvolle Sortierkriterium sofort erkennt, den Präfix evtl. in eckige Klammern [j-lawyer backup Erfolg] und [j-lawyer backup Fehler]?

Und in der Mail vielleicht ein Tipp "Bei Regelerstellung wird empfohlen, nach [j-lawyer backup Erfolg] bzw. [j-lawyer backup Fehler]
zu sortieren? 

Welche Meldung gibt es für "Warten", also wenn der externe Speicher gerade nicht verfügbar ist? (keine, oder? Sollte es nach X Tagen doch eine Meldung mit "Fehlgeschlagen" geben?)

**Comment by Maz111111** [comment]
Ich häng mich hier mal dran.

Wäre es vielleicht auch eine mögliche Lösung in der KSW angeben zu können, dass eine Benachrichtigungsmail nur bei Fehlern gesendet wird.

**Comment by j-dimension** [comment]
> Wäre es vielleicht auch eine mögliche Lösung in der KSW angeben zu können, dass eine Benachrichtigungsmail nur bei Fehlern gesendet wird.

Schon fertig: https://github.com/jlawyerorg/j-lawyer-org/issues/1091

**Comment by j-dimension** [comment]
Die eckigen Klammern finde ich fast etwas zu technisch für den Normalverbraucher. Es wird nun aber ein "Erfolgreich:" vorn angestellt.

**Comment by j-dimension** [comment]
noch zu dokumentieren: Hinweise zur Regelerstellung in Mailprogrammen
