### ISSUE TITLE
[FEATURE] Etiketten auf Ebene Dokumente sichbar

### ISSUE THREAD

**Issue by RA-crm** [jlawyerorg/j-lawyer-org#1157]
Bis zu 1.12 waren die Etiketten in den Dokumenten unter der Suchzeile zu finden. Man konnte also erkennen, ob und wie viele Etiktten etwa mit "Posteingang" oder "ToDo" in der Akte vorhanden sind. Das ist in der 1.13 nicht mehr der Fall, oder? Jedenfalls finde ich diese Angaben nicht mehr. Ich muss jetzt jedesmal die Etiketten filtern, ohne zu wissen, nach was ich eigentlich suchen muss.
Wenn diese Anzeige wirklich weg ist, hätte ich diese gerne wieder.

**Comment by j-dimension** [comment]
Die Information gibt es noch, als Tooltip / Mouseover am Dokumentetiketten-Filterknopf. 

Ansonsten ist dieses Ticket ein Duplikat von #1064
