### ISSUE TITLE
[BUG] Keine Darstellung von Bildern bei Mails von iPhones

### ISSUE THREAD

**Issue by RA-crm** [jlawyerorg/j-lawyer-org#1159]
Bei E-Mails von Apple Produkten (iPhone) kommt es vor, dass die in der E-Mail eingefügten Fotos nicht angezeigt werden können. Sie werden auch ich als Anlage zu E-Mail angezeigt. 

Bisher sind die Bilder dann stets über den externen E-Mail-Client herunterzuladen und separat in die Akte zu speichern. 

Meines Erachtens ist das ein Bug.

**Comment by j-dimension** [comment]
Duplikat von bereit gelöstem Ticket #1125
