### ISSUE TITLE
Backupziel "Datenträgernamen statt Laufwerksbuchstaben"

### ISSUE THREAD

**Issue by Dickmaulruessler** [jlawyerorg/j-lawyer-org#1161]
Ich sichere die Datenbank auf mehreren wechselnden USB-Sticks (alle die selbe Marke, dasselbe Modell, alle mit "J-Lawyer" benannt".

Wegen des Wechsels ist ein Stick mal eingelegt, mal aber auch (noch) nicht.

Wenn ich dann an den USB-Port etwas anderes anschließe - passiert häufiger mal - (Webcam, anderer Stick, externe Backup-Platte..) stimmt die Zuordnung der Laufwerksbuchstaben für die j-jawyer-Datensicherung nicht mehr. 

In meinem Backup-Programm (Personal-Backup) gibt es die Möglichkeit "Datenträgernamen statt Laufwerksbuchstaben" zu verwenden.

> [Volume Namen von Wechseldatenträgern](https://personal-backup.rathlev-home.de/help-6-de/pb-task.html#vol)
> 
> Bei USB-Sticks oder externen Laufwerken kann es vorkommen, dass das System ihnen nicht immer den gleichen Laufwerksbuchstaben zuordnet. Soll ein solches Medium als Ziel für ein Backup verwendet werden, besteht die Möglichkeit, durch Klick auf diese Schaltfläche den Laufwerksbuchstaben im Zielpfad durch den Namen des eingelegten Wechseldatenträgers :<volumename>: zu ersetzen.
> Bsp.: statt K:\Backup schreibt man :Backup-1:\Backup
> Beim Backup wird dann geprüft, ob ein Datenträger mit diesem Namen (egal unter welchem Laufwerksbuchstaben) angeschlossen ist. Wenn nicht, wird der Benutzer aufgefordert, diesen einzulegen. 

Ginge das auch für die Synchronisations-Einstellungen unter j-lawyer?

**Comment by j-dimension** [comment]
Grundsätzlich geht das wahrscheinlich (bis auf den Punkt "Wenn nicht, wird der Benutzer aufgefordert, diesen einzulegen.", da die Synchronisation im Hintergrund läuft), es wäre eine windowsspezifische Umsetzung.

**Comment by Dickmaulruessler** [comment]
Möglicherweise kann man das schon jetzt manuell (meine Datenträgerbezeichnung: J-Lawyer)?
:J-Lawyer:\Backup

Soll ich das mal probieren?

**Comment by j-dimension** [comment]
Nein, das wird nicht gehen. Letzlich muss die Synchronisation auf einen gültigen Pfad schreiben, und die Datenträgerbezeichnungen sind keine. 
Es müsste vor jedem Synchronisationslauf automatisch das Laufwerk mit diesem Datenträger ermittelt, und der Pfad dann dynamisch angepasst werden.

**Comment by Dickmaulruessler** [comment]
> 
> 
es wäre eine windowsspezifische Umsetzung.

Ich vermute, dass Lösungen nur für einzelne Betriebssysteme in j-lawyer nach Möglichkeit vermieden werden sollen. 

Ich habe für mich (als Windows-Nutzer) jetzt eine Alternative gefunden: 
Ich habe unter 

"Rechte Maustaste auf die Start-Taste / Computerverwaltung / Datenspeicher / Datenträgerverwaltung / eingesteckten USB-Stick auswählen / rechte Maustaste "Laufwerksbuchstaben und -pfade ändern" / erneut auf "Ändern" klicken / "Folgenden Laufwerksbuchstaben zuweisen"

dem USB-Stick für die j-lawyer-Datensicherung den festen Laufwerksbuchstaben "Z" zugewiesen. Dieser Laufwerksbuchstabe verändert sich dann nicht mehr.

**Comment by j-dimension** [comment]
Klasse Lösung. Das wäre etwas für die Doku. Ich nehme das mit auf.

**Comment by j-dimension** [comment]
hinzugefügt
