### ISSUE TITLE
[FEATURE] Etiketten - zweiter Filter auf Desktop

### ISSUE THREAD

**Issue by Maz111111** [jlawyerorg/j-lawyer-org#1162]
**NOTE: Please search existing tickets to avoid duplicates **
**HINWEIS: Bitte vorab die Ticketsuche verwenden, um Doppeleinträge zu vermeiden **
Hab nichts direkt passendes gefunden

Description / Beschreibung
Ich habe auf meinem Desktop verschiedene Etiketten angewählt und lass mir dementsprechend diese Akten anzeigen. Es handelt sich unter anderem um "Posteingang" "neue WV eintragen" u.s.w.

Ich benötige faktisch alle der gewählten Etiketten und generell ist es auch in Ordnung, dass alle angezeigt werden.

Manchmal will ich aber nur den Posteingang sehen, um zu vermeiden, dass davon etwas unter den anderen angezeigten Etiketten untergeht. Soweit ich das sehe, bekomme ich das nur hin, indem ich alle anderen Etiketten abwähle und dann (hoffentlich) daran denke, sie nach Abarbeitung der Posteingänge wieder anzuwählen. Ach so mein Posteingang ist im HomeOffice rein digital - ich bin also auf die richtige Etikettierung durch meine MA im Büro (die das alles einscant und digital zuordnet) angewiesen. Vor allem habe ich nicht zusätzlich eine haptische Akte mit aufgeheftetem Posteingang vor mir liegen, so dass ich daran "feinsortieren" könnte.

Das ist alles umständlich und vor allem fehleranfällig (Maschine Mensch).

**Describe the solution you'd like / Beschreibe die gewünschte Lösung**

Jetzt wäre es gut, wenn man mit einem weiteren Filter nochmals "feinfiltern" könnte. Nach dem Motto: "Zeige von den gewählten Etiketten nur die folgende(n)"

**Comment by j-dimension** [comment]
Das wäre ein Duplikat von #981

**Comment by Maz111111** [comment]
Das ist misslich - aber ich versuche es mir zu merken...

Ich habe leider nur nach noch offenen Issues mit dem Stichwort "etiketten" gesucht, weil die Suchroutine das so vorgibt.

Bin nicht darauf gekommen, auch nach geschlossenen Tickets zu suchen.

Sorry!

**Comment by j-dimension** [comment]
Gar kein Problem, die Github-Suche ist nicht so intuitiv wie die große Suchmaschine 🙂

**Comment by j-dimension** [comment]
Die #981 ist im Übrigen noch offen und für 1.15 geplant.

**Comment by Maz111111** [comment]
Da hast Du schon wieder recht - d'oh - dann habe ich es einfach übersehen...Aber ich habe vorher gesucht...isch schwöre ;-)
