### ISSUE TITLE
verschlüsseltes Backup offenbart Dateinamen

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#1163]
Hallo!

Ich weiß ja nicht, ob das an verschlüsselten zips als solchen liegt, aber man kann in dem verschlüsselten Backup zumindest die Dateinamen der Dokumente ohne Schlüssel auslesen? Soll das so sein?

![image](https://user-images.githubusercontent.com/29924198/111042657-bd146000-843e-11eb-9175-8e805e3f94ec.png)

Ist sicher nicht so tragisch wie Zugriff auf den Inhalt, aber ggf. kann ein Angreifer auch daraus Schlüsse ziehen.

**Comment by j-dimension** [comment]
Das Backup nutzt verschlüsselte ZIP-Dateien - seit es das Feature gibt. Als "Bug" stufe ich das daher nicht ein.

**Comment by stm9x9** [comment]
je nachdem, wie beschreibend der Anwalt die Dateinamen benennt,. kann man aber leider aus deren Namen heraus bereits Rückschlüsse ziehen, die das Anwaltsgeheimnis verletzen.

Muß es denn aus Kompatibilitätsgründen unbedingt zip sein? Würde  7z möglich sein?

`7z a -p -mhe=on archivname quelldateien`

macht das gewünschte und verschlüsselt auch die Dateinamen. Habe ich gelesen.

Oder erst ein zip erstellen und daß dann in ein verschlüsseltes zip einpacken.

**Comment by j-dimension** [comment]
> Rückschlüsse ziehen, die das Anwaltsgeheimnis verletzen.

D.h. jede am Markt befindliche Anwaltssoftware nutzt verschlüsselte Backups? Kann ich nicht glauben. Oder Anwälte, die das Datenverzeichnis ihrer KSW auf USB mit sich herumtragen. Oder Anwälte die ihre KSW auf einem Terminalserver im RZ betreiben lassen wo die Daten wiederum unverschlüsselt rumliegen?

Ich verstehe Deine Motivation, aber ob "Anwaltsgeheimnis" hier als Argument herangezogen werden kann?

**Comment by stm9x9** [comment]
Dann können wir aber das Verschlüsseln gleich wieder abschaffen. Ich denke in erster Linie, es wiegt einen in falscher Sicherheit. 

Und im Zweifel traue ich (und darf das auch) meinem Hoster/RZ, mit dem ich eine Auftragsdatenverarbeitungsvereinbarung unterzeichnet habe mehr, als zb dem Cloud-Server, der Dropbox oder sonst wo ich ein verschlüsseltes Backup hinspielen will zur Ausfallsicherheit.

Rechtlich geht es um § 203 StGB und § 43e BRAO

Inanspruchnahme von Dienstleistungen
(1) 1Der Rechtsanwalt darf Dienstleistern den Zugang zu Tatsachen eröffnen, auf die sich die Verpflichtung zur Verschwiegenheit gemäß § 43a Absatz 2 Satz 1 bezieht, soweit dies für die Inanspruchnahme der Dienstleistung erforderlich ist. 2Dienstleister ist eine andere Person oder Stelle, die vom Rechtsanwalt im Rahmen seiner Berufsausübung mit Dienstleistungen beauftragt wird.

Daher - wenn auf dem Server mit den Daten gearbeitet werden muß - dann können die da unverschlüsselt gespeichert werden (das heißt jetzt nicht, die Vision einer verschlüsselten Ablage auch auf dem Server zu verwerfen :-D). Aber das Backup auf dem Backup-Server muß nicht bearbeitet werden. Daher wäre ein unverschlüsseltes Speichern dort nach strenger Ansicht ein unbefungtes Offenbaren nach 203. Denn es ist nicht nach 43a erforderlich.

**Comment by j-dimension** [comment]
> Dann können wir aber das Verschlüsseln gleich wieder abschaffen. Ich denke in erster Linie, es wiegt einen in falscher Sicherheit.

Sorry, das wird mir zu unsachlich. Du forderst im Ernst die Verschlüsselung von Inhalten abzuschafen, weil Dateinamen einsehbar sind? Die Anwendung bietet an dieser Stelle wahrscheinlich mehr als die meisten Anwendungen dieser fachlichen Domain.

Der "Zielspeicher" ist doch üblicherweise wiederum zugangsgesichert, d.h. diese Barriere wäre als erstes mal zu umgehen. 

Im Vergleich zu anderen offenen Erweiterungen sehe ich hier einfach keine zeitnahe Änderung meinerseits. Das kann jemand beisteuern oder sponsorn, aber ich habe das Gefühl dass hier Dinge von einer freien Anwendung gefordert werden, die kaum ein kommerzieller Anbieter implementiert hat. 

Ein höheres Sicherheitsniveau in Anwenderverantwortung wäre ebenfalls möglich - einfach das Backup selbst nochmal "nachbearbeiten" bevor es irgendwo eingelagert wird.

**Comment by stm9x9** [comment]
> Sorry, das wird mir zu unsachlich. Du forderst im Ernst die Verschlüsselung von Inhalten abzuschafen, weil Dateinamen einsehbar sind? Die Anwendung bietet an dieser Stelle wahrscheinlich mehr als die meisten Anwendungen dieser fachlichen Domain.

Erstmal fordere ich gar nichts. Würde ich nie tun. Weil ich weiß, was wir an der Software und an Deinem Engagement haben! Allerdings möchte ich auch nicht, daß Anwender hinterher ggf mal Probleme bekommen, weil sie ja dachten, es wäre doch verschlüsselt.

> Ein höheres Sicherheitsniveau in Anwenderverantwortung wäre ebenfalls möglich - einfach das Backup selbst nochmal "nachbearbeiten" bevor es irgendwo eingelagert wird.

Insofern ist natürlich auch das ein gangbarer Weg. Nur braucht es dann das Wissen des Anwenders, daß dies ggf nötig ist.

> Der "Zielspeicher" ist doch üblicherweise wiederum zugangsgesichert, d.h. diese Barriere wäre als erstes mal zu umgehen.

Was dann wieder zu meiner - zugegeben provokanten - Nachfrage von oben führt. Entweder man empfindet bereits diese Barriere als ausreichend oder eben nicht.
 
> Im Vergleich zu anderen offenen Erweiterungen sehe ich hier einfach keine zeitnahe Änderung meinerseits. Das kann jemand beisteuern oder sponsorn, aber ich habe das Gefühl dass hier Dinge von einer freien Anwendung gefordert werden, die kaum ein kommerzieller Anbieter implementiert hat.

Da fehlt mir die Übersicht, auf Anhieb finde ich nur https://onlinehilfen.ra-micro.de/index.php/Kanzleidaten_Sicherung wo auch nicht genau hervorgeht, wie / was verschlüsselt wird.
