### ISSUE TITLE
[BUG] backup-manager ohne Verschlüsselung geht nicht

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#1164]
ich habe ein Backup ohne(!) Verschlüsselung angelegt.

Wenn ich das wieder einspielen will, werde ich nach dem Paßwort der Verschlüsselung gefragt. Ich drücke Enter, weil ich keines habe. Dann geht der Prozeß nicht mehr weiter:

![image](https://user-images.githubusercontent.com/29924198/111042809-7a9f5300-843f-11eb-9707-3bad099f5209.png)

Wenn ich aber eines angebe, dann bricht es wegen eines Fehlers ab (es gibt ja schließlich auch keine Verschlüsselung.

![image](https://user-images.githubusercontent.com/29924198/111042817-81c66100-843f-11eb-93ad-04850b958faf.png)

Abhilfe: Das Skript sollte ein leeres Enter akzeptieren und ohne Verschlüsselungsprüfung weitermachen.

**Comment by j-dimension** [comment]
Wenn Du an der Stelle

***empty***

eingibst, läuft der Backupmanager weiter. Ich werde das ein wenig anpassen.
