### ISSUE TITLE
[BUG] Adhoc Backup (und ggf alle API-Aufrufe?) gehen nicht, wenn Server hinter nginx / ssl

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#1165]
mein Server ist von außen nur per ssl erreichbar, mittels nginx.

Wenn ich im Frontend das adhoc-Backup auslösen will, bekomme ich diesen Fehler:

![image](https://user-images.githubusercontent.com/29924198/111043210-9f94c580-8441-11eb-8368-a8cace91fbd4.png)

Denn es wird versucht, eine http statt https-URL aufzurufen.

**Comment by j-dimension** [comment]
Bereits behoben in #1053
