### ISSUE TITLE
[BUG] nach Backup-Einspielen Dateieigentümer falsch - diverse Folgeprobleme

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#1166]
Ich habe meine Installation auf einen anderen Server mittels Backup / Restore umgezogen. Soweit so gut.

Ich bekam aber keine Dateivorschauen mehr angezeigt und konnte keine neuen Dateien anlegen!

![image](https://user-images.githubusercontent.com/29924198/111043947-e2589c80-8445-11eb-989f-4e1cba981695.png)

Ein Blick unter die Haube zeigte:

Wo bislang alle Dateien und Ordner j-lawyer-server gehörten, waren sie jetzt root:root

![image](https://user-images.githubusercontent.com/29924198/111044004-3bc0cb80-8446-11eb-91d8-8545e55acbf0.png)

![image](https://user-images.githubusercontent.com/29924198/111044012-47ac8d80-8446-11eb-9134-1276026c2294.png)

Abhilfe schaffte dann ein

` :/usr/local/j-lawyer-server$ sudo chown -R j-lawyer-server:j-lawyer-server j-lawyer-data/`

Vorschlag: kann das der Backupmanager nicht übernehmen?

**Comment by j-dimension** [comment]
Das sind Betriebssystemthemen. Wenn Du den Backupmanager mit einem Nutzer ausführst, der später drauf zugreift, brauchst Du den extra Schritt nicht. Unter Windows spielt das alles keine Rolle, auf unixoiden (Linux, macOS) schon. 

Der Backupmanager weiß nicht, unter welchem Nutzer der j-lawyer.org Server läuft, kann also auch nicht entscheiden wem die Daten zu "übereignen" sind. 

Ich kann hierfür einen Satz in der Doku aufnehmen, Codeänderungen sehe ich nicht.

**Comment by j-dimension** [comment]
Kommentar in der Doku:

https://github.com/jlawyerorg/j-lawyer-documentation/commit/80b638f696bfd14850817b3a8675f9b08d7d9e51

**Comment by stm9x9** [comment]
> Der Backupmanager weiß nicht, unter welchem Nutzer der j-lawyer.org Server läuft, kann also auch nicht entscheiden wem die Daten zu "übereignen" sind.

Kann er nicht den Eigentümer des Datenverzeichnisses (hier j-lawyer-data/) auslesen? Die Einstellungen dieses Oberverzeichnisses, die stimmen ja.

**Comment by j-dimension** [comment]
Nochmal: es ergibt keinen Sinn, Mittel des Betriebssystems in den Backupmanager zu überführen, weil das schlicht nicht zuverlässig funktionieren wird. Die Varianten, in denen der Server betrieben wird, sind schlicht zu vielfältig. Außerdem fange ich dann an dieser Stelle wieder an, verschiedene Codevarianten je nach Betriebssystem umzusetzen und zu testen, für ein Feature das die meisten Anwender niemals nutzen. 

Daher: Doku lesen, selber machen.
