### ISSUE TITLE
Unterstützung für mehrere Beteiligte des selben Typs

### ISSUE THREAD

**Issue by j-dimension** [jlawyerorg/j-lawyer-org#117]
Unterstützung für mehrere Beteiligte des selben Typs innerhalb des selben Dokuments/der selben Vorlage
bspw. unterschiedliche "Dritte" oder 1 Gegner und 1 Gegnervertreter, die beide als "Gegner" erfasst sind.

**Comment by stm9x9** [comment]
ist mir nicht so ganz klar, ob das hier schon so richtig mit erfaßt ist: 

Die Möglichkeit, mehr als einen Mandanten oder Gegner in eine Vorlage zu übernehmen. Ganz klassisch zb bei einer Klagevorlage:

Klage

1) der Frau XY, Musterweg
2) des Herrn AY Musterweg
3) des Herrn ZY, Musterweg – minderjährig – ………………………………….. – Kläger –

gegen

blablub …

Auf Ebene der Beteiligtenauswahl könnte das bei der Dokumentenerstellung zb über eine Mehrfachselektion im Auswahlfenster geschehen.

**Comment by j-dimension** [comment]
Ja, genau darum geht es in diesem Ticket.

**Comment by stm9x9** [comment]
In der Vorlage zb mittels Schleifen, wenn das überhaupt geht.

**Comment by stm9x9** [comment]
Alternativ wenn Schleifen nicht gehen:
Eine Vorlage für Einzelklage, eine für Mehrpersonenklagen. Und dann bei Einzelklagen:

Klages des 

{{MANDANT}}

und in den anderen:

Klage des

{{MANDANT1}}
{{MANDANT2}}
{{MANDANT3}}
...
{{MANDANT10}}

in der Hoffnung, es gibt nicht mehr als 10 :-) Und dann manuell die überflüssigen löschen im Dokument.

siehe auch #401
