### ISSUE TITLE
[FEATURE] Dokumente direkt zu pdf erstellen

### ISSUE THREAD

**Issue by Maz111111** [jlawyerorg/j-lawyer-org#1177]
Description / Beschreibung
Es gibt Vorlagen, die keiner Modifikation bedürfen. Diese werden zuerst als .odt erstellt und dann über das Kontextmenü unmittelbar für den beA Versand in pdf umgewandelt.

**Describe the solution you'd like / Beschreibe die gewünschte Lösung**
Es wäre schneller, wenn im "Erstellen" Dialog die Möglichkeit angeboten würde, aus der Vorlage direkt ein pdf-Dokument zu erstellen.

**Comment by iradraconis** [comment]
ist in 2.4 umgesetzt. Ticket könnte geschlossen werden, oder?

**Comment by j-dimension** [comment]
Dup von #1739
