### ISSUE TITLE
Unterschiedliche Icons für WV und Frist

### ISSUE THREAD

**Issue by j-dimension** [jlawyerorg/j-lawyer-org#1178]
Aktuell wird für Wiedervorlagen und Fristen das selbe Icon verwendet, nur in unterschiedlicher Farbe (rot für Frist, grün für WV). 

Für Anwender mit rot/grün-Schwäche ist das nicht optimal.

**Comment by j-dimension** [comment]
Es gibt nun nur noch zwei unterschiedliche Icons: WV und Frist. Das separate Icon für WV/Frist für die man selbst verantwortlich ist, entfällt.

**Comment by j-dimension** [comment]
WV: blau
Frist: rot mit Ausrufezeichen in der Mitte. Hoffe das ist gut genug zu erkennen / unterscheiden.

**Comment by stm9x9** [comment]
> Hoffe das ist gut genug zu erkennen / unterscheiden.

kannst du mal einen Screenshot von den neuen Icons zeigen?

> Das separate Icon für WV/Frist für die man selbst verantwortlich ist, entfällt.

ist mir gar nicht aufgefallen, wie sah das denn aus?

**Comment by j-dimension** [comment]
![grafik](https://user-images.githubusercontent.com/3729754/119413225-82a42a80-bced-11eb-9e45-c53bc658a655.png)

**Comment by j-dimension** [comment]
> > Das separate Icon für WV/Frist für die man selbst verantwortlich ist, entfällt.
> 
> ist mir gar nicht aufgefallen, wie sah das denn aus?

Frist rot, WV blau, eigene WV oder Frist grün

**Comment by stm9x9** [comment]
ah das meinst du. Man könnte stattdessen den Nutzernamen rechts grün machen, wenn es eine eigene Frist/WV ist? Und blau bei fremden.

**Comment by j-dimension** [comment]
> Man könnte stattdessen den Nutzernamen rechts grün machen, wenn es eine eigene Frist/WV ist?

Hab das mal probiert, das hat an der Stelle zu wenig Kontrast, wenn ich die Standardfarbe nehme (die im Logo enthalten ist und querbeet in der Anwendung verwendet wird). Das Rot würde gehen.
