### ISSUE TITLE
[FEATURE] Aktennotizen - Automatischer Datums-, Zeit und Benutzerstempel bei neuer Eingabe

### ISSUE THREAD

**Issue by Utzi81** [jlawyerorg/j-lawyer-org#1179]
Ich nutze das Notizenfenster auf dem ersten Tab für eine Chronologie der Akte. Alle wesentlichen Bearbeitungsschritte werden dort kurz beschrieben. Wäre es möglich, bei einer neuen Eingabe immer automatisiert einen Zeitstempel und den Bearbeiter in eckigen Klammern voranzustellen? 

Beispiel:
[08.02.2021, 10:57h, Mustermann.Max]: Hier kommt dann der Text.

Schön wäre darüber hinaus, wenn man das Notizenfeld mit verschiedenen Berechtigungen versehen könnte. Also z.B. admin darf alles ändern, normaler Benutzer dagegen nur neue Notizen hinzufügen, aber keine alten mehr verändern.

**Comment by j-dimension** [comment]
https://www.javacodegeeks.com/2012/08/chat-bubble-in-java-swing.html

https://stackoverflow.com/questions/19037698/jtextfield-bubble-text

**Comment by j-dimension** [comment]
Bitte mal prüfen ob das seit Version 2.5 verfügbare Messaging diese Funktionalität abdeckt. Dort können aktenbezogen auf dem ersten Tab Nachrichten hinterlassen werden, die automatisch Zeistempel und Verfasser haben und in der Menge nicht beschränkt sind.

**Comment by Utzi81** [comment]
Hallo, das tut die Funktion in der Tat. Bin total begeistert von dem neuen Feature Messaging, ganz lieben Dank dafür! Damit kann dieses Ticket auf erledigt gesetzt werden.

Wichtig wäre mir nur, dass die gesendeten Nachrichten auch künftig nachträglich nicht verändert werden können. Dann hätte sich sogar auch mein Historienthema dauerhaft erledigt.

Viele Grüße
Christopher
Am 29. Okt. 2023, 19:06 +0100 schrieb Jens Kutschke ***@***.***>:

**Comment by j-dimension** [comment]
> Wichtig wäre mir nur, dass die gesendeten Nachrichten auch künftig nachträglich nicht verändert werden können. Dann hätte sich sogar auch mein Historienthema dauerhaft erledigt.

Ändern wird nicht möglich sein, aber Nutzer(-innen) wünschen sich eine Löschfunktion: https://github.com/jlawyerorg/j-lawyer-org/issues/2148
Das müsste so umgesetzt werden, dass man nur seine eigenen Nachrichten löschen darf.

**Comment by Utzi81** [comment]
Wäre er möglich, das Löschrecht gesondert im Benutzerprofil zu vegeben? Das wäre für mich wichtig - auch für selbst gesendete Nachrichten. Denn ich würde den Chat dann gerne als inkrementelle Dokumentation nutzen, bei der keine Informationen verloren gehen können. Der admin hätte dann das Löschrecht in meinem Fall, die Standarduser aber nicht.

Lg aus München!
Am 29. Okt. 2023, 22:47 +0100 schrieb Jens Kutschke ***@***.***>:
