### ISSUE TITLE
[adressen] Neue Felder "Funktion" und "Adresszusatz" 

### ISSUE THREAD

**Issue by j-dimension** [jlawyerorg/j-lawyer-org#118]
Mit den „Funktionen“ meine ich nicht (akademische) „Titel“. Vielmehr der ausgeübte Beruf (z. B. Sachvertändiger, Schadenregulierer, Geschäftsführer, etc.) oder eine ehrenamtliche Tätigkeit (z. B. bei Vereinen, also 1. Vorsitzender, etc.).
Adresszusatz: Abteilung, Ansprechpartner, ...

**Comment by librelegal** [comment]
Die Bezeichnung dieses issues sollte vereinheitlicht werden. Es geht um Adressen, deshalb "Adressen:" voranstellen. Außerdem war ein Tippfehler im Betreff.
Insgesamt wie nachstehend:
Adressen: Felder "Funktion" und "Adresszusatz"
