### ISSUE TITLE
[FEATURE] Desktop - dritte Zeile bei Fälligkeiten mit Aktenbezeichnung

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#1182]
Ich habe sehr oft dieselben Mandanten gegen denselben Gegner.

Das heißt die zweite Zeile unterscheidet sich nur im Aktenzeichen und anhand dessen weiß ich nicht wirklich direkt, welche der vielen Akten es ist.

Da dort eh Platz für eine dritte Zeile ist durch das Icon vorne und den Bearbeiter hinten, könnte man diese nutzen, um noch den Aktenbetreff (das "wegen") anzuzeigen:

![image](https://user-images.githubusercontent.com/29924198/114239267-24fa8f80-9986-11eb-80f9-4fd0786acd08.png)

**Comment by j-dimension** [comment]
Es sind vier Zeilen, wegen der Etiketten. 

![grafik](https://user-images.githubusercontent.com/3729754/120541617-62a9f080-c3ea-11eb-917f-14b7d95be532.png)

**Comment by stm9x9** [comment]
oh sind die neu? Welche Etiketten sind das? Die der Akte?

**Comment by j-dimension** [comment]
Die gibt es schon seit sonstewann. Ja, sind Aktenetiketten.

**Comment by stm9x9** [comment]
Ah. die nutze ich im Moment fast nicht, daher hab ich das nicht gesehen.
