### ISSUE TITLE
Drucken von e-mail

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-org#1188]
Drucken von e-mail geht nicht direkt, nur über den Aufruf des installierten externen mailprogramms (Datei im externen mailprogramm öffnen). Könnte man nicht einfach vorsehen, dass beim Aufruf des normalen Druckbefehls bei einer e-mail (.eml) Datei gleich automatisch das externe mailprogramm und seine Druckfunktion aufgerufen wird (evt. mit Auswahl Druckfenster vorher anzeigen oder nicht). Ich muss jede e-mail ausdrucken für die Akte, da wären drei oder vier ersparte Clicks bei 1000enden e-mails im Jahr einfach nur komfortabel.

**Comment by j-dimension** [comment]
Duplikat von #642 und #112
