### ISSUE TITLE
[FEATURE] neue beA-Anforderungen an Dateinamen umsetzen

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#1190]
Folgendes las ich gerade:

> Mit der beA-Version 3.4 werden Dateinamen vor dem Hinzufügen von Anhängen zu Nachrichtenentwürfen in der beA-Webanwendung automatisch geprüft. Grundlage dafür sind erweiterte Regelungen, die die Justiz für den elektronischen Rechtsverkehr veröffentlicht hat.
> „Die Länge von Dateinamen darf zukünftig grundsätzlich maximal 84 Zeichen einschließlich der Dateiendungen betragen. Für Signaturdateien ist die Länge auf 90 Zeichen einschließlich der Dateiendungen beschränkt. In Dateinamen dürfen grundsätzlich alle Buchstaben des deutschen Alphabetes inklusive der Umlaute Ä, ä, Ö, ö, Ü, ü sowie ß genutzt werden. Zudem dürfen alle Ziffern und die Zeichen „Unterstrich“ und „Minus“ genutzt werden. Wichtig: Leerzeichen sind nicht erlaubt. Es bietet sich an, Unterstriche anstelle von Leerzeichen zu nutzen. Punkte sind nur als Trennzeichen zwischen dem Dateinamen und der Dateinamensendung zulässig. Nur bei konkatenierten Dateinamensendungen, z.B. bei abgesetzten Signaturdateien, dürfen Punkte auch im Dateinamen genutzt werden (z. B. Dokument1.pdf.pkcs7).“
>

Ich weiß ja nicht, wie die Kollegen das so machen, aber bei mir haben die Dateien in j-l sprechende Namen mit Leerzeichen (sind einfach besser zu lesen als _) zb:

2020-07-17 - an SG - Begründung und PKH.pdf

Diese müßten dann von j-l vor dem Versenden beA-konform gemacht werden. Und da die Gerichte - sofern sie eine eAkte nutzen - auch lieber lesbare Namen mit Leerzeichen haben (so jedenfalls in allen Präsentationen zb von EUREKA fach), wäre es damit IMHO dringend, daß sich auch j-l an die Unterscheidung Dateiname (den ganzen Anforderungen entsprechend, ohne Leerzeichen, doppelte Punkte etc und auch ergänzt um eine Numerierung und Schriftsatz/Anlage vorne für die Internet-Ausdrucker-Gerichte) und Anzeigenamen macht. 

Der Dateiname würde dann vollkommen in den (nur noch technischen) Hintergrund wandern und der frei gestaltbare Anzeigenamen müßte im Vordergrund stehen. Der Anzeigenamen könnte dann sogar (ggf optional) komplett ohne Dateiendung auskommen und die Art der Datei nur noch im technischen Dateinamen hinterlegen und für den Anwender durch das Dokumentensymbol vorne anzeigen. Und der Dateiname könnte dann (nur verkleinert oder gar nicht in unserer Dokumentenansicht angezeigt) einfach aus dem Anzeigenamen generiert werden, wobei dann halt Leerzeichen oder doppelte Punkte durch _ ersetzt werden.

**Comment by stm9x9** [comment]
steht mit folgenden Issues in Verbindung:

https://github.com/jlawyerorg/j-lawyer-org/issues/628
https://github.com/jlawyerorg/j-lawyer-org/issues/373
https://github.com/jlawyerorg/j-lawyer-org/issues/761
https://github.com/jlawyerorg/j-lawyer-org/issues/762
https://github.com/jlawyerorg/j-lawyer-org/issues/663
https://github.com/jlawyerorg/j-lawyer-org/issues/757

**Comment by j-dimension** [comment]
@stm9x9 Ich beschränke dieses Ticket hier auf die Konformität der Dateinamen. Der Rest ist mehr Arbeit und weniger dringend. Bitte bei Bedarf separates Ticket stellen.

**Comment by j-dimension** [comment]
behoben via bea wrapper
