### ISSUE TITLE
Versteckte Dateien im Vorlagen-Ordner ausblenden

### ISSUE THREAD

**Issue by Dickmaulruessler** [jlawyerorg/j-lawyer-org#1191]
In dem Dokument-Vorlagen-Ordner gibt es eine Datei namens

**.directory**

mit dem Inhalt:

_[Dolphin]
Timestamp=2016,12,15,22,4,4
Version=3
ViewMode=1_

Muss ich die Datei sehen? Kann die ausgeblendet werden?
Nur aus Neugierde: Was bedeutet der Inhalt mit dem "Timestamp"?

Merci!

**Comment by j-dimension** [comment]
Du kannst die Datei gefahrlos löschen. 

Ich formuliere das Ticket um.
