### ISSUE TITLE
[MEINUNGSBILD] Statistik-Statusleiste entfernen?

### ISSUE THREAD

**Issue by Dickmaulruessler** [jlawyerorg/j-lawyer-org#1192]
Auf dem Desktop befinden sich in der Statusleiste statistische Angaben zur Anzahl der Akten, davon im Archiv, Adressen, Dokumente, Kosten.

![jhfklöjfklasdöjlfkdös](https://user-images.githubusercontent.com/46451749/115869745-9f271b80-a43e-11eb-916f-1c58d482ed87.jpg)

Hat das wirklich Informationswert, dass man das auf dem Desktop immer unten sehen muss?

Ich halte es für entbehrlich, es lenkt ab, kostet unnötig eine wertvolle Zeile Platz 
(...aber irgendwie auch ganz witzig: Ich würde es irgendwo in der Menüleiste bei "?" unterbringen.)

Oder erkennt jemand einen wirklichen Mehrwert in diesen auf dem Desktop ständig sichtbaren Angaben?

**Comment by PBaumfalk** [comment]
Ich habe da einen Mehrwert von. Ich fände eine umfassende Reportingansicht sogar gut!

Mit freundlichen Grüßen / Kindly Regards

Patrick Baumfalk
Rechtsanwalt / Lawyer


Mobil:    +49 1525 53 04 194
E-Mail:   ***@***.***


Baumfalk - Rechtsanwaltskanzlei
Hauptstr. 195
50169 Kerpen

Tel.: +49 2273 40 68 504
Fax: +49 2273 59 03 565

E-Mail: ***@***.***
Web: www.kanzlei-baumfalk.de

Sent by Mobile

**Comment by Dickmaulruessler** [comment]
Welchen konkreten Mehrwert?
Wieso unbedingt da unten und nicht zwei Klicks weiter?

**Comment by j-dimension** [comment]
> Ich fände eine umfassende Reportingansicht sogar gut!

Fände ich auch sehr cool! Ich hatte da vor Zeiten mal ein Ticket angelegt, findet aber keine Beachtung :-)

https://github.com/jlawyerorg/j-lawyer-org/issues/85

Konkrete Ideen gern dort rein.

**Comment by stm9x9** [comment]
ich find es ganz angenehm die Info da unten zu haben - stört jedenfalls nicht

**Comment by Linkki2021** [comment]
Finde die Auswertung an sich gut, muss aber nicht permanent im Fokus stehen. Bin da bei Dickmaulruessler, kann irgendwo "aufgeräumt" werden.

**Comment by stm9x9** [comment]
> > Ich fände eine umfassende Reportingansicht sogar gut!
> 
> Fände ich auch sehr cool! Ich hatte da vor Zeiten mal ein Ticket angelegt, findet aber keine Beachtung :-)
> 
> #85
> 
> Konkrete Ideen gern dort rein.

Ich weiß nicht, wie viele Anwender hier regelmäßig nach neuen Tickets gucken (so wie ich :-)). Verweis doch mal in der Liste auf dieses Ticket, daß du da dich über Beachtung freuen würdest!
