### ISSUE TITLE
[BUG] Sternchen "Dokument-Favoriten" entfernen?

### ISSUE THREAD

**Issue by Dickmaulruessler** [jlawyerorg/j-lawyer-org#1193]
In der Akten-Ansicht gibt es oben rechts ein ständig sichtbares gelbes Sternchen "Dokument-Favoriten" anzeigen. 
![dsafkljödsakf](https://user-images.githubusercontent.com/46451749/115873212-f5965900-a442-11eb-9caf-312383e6249b.jpg)
.
.
.
Macht das (an der Stelle) Sinn, wo es doch die super Sortierfunktion auch nach Favoriten in den Ordnern gibt?
.
.
.
![dsfklöasd](https://user-images.githubusercontent.com/46451749/115873258-01821b00-a443-11eb-8203-babf0d6d0e5d.jpg)

**Comment by j-dimension** [comment]
Ja, das ergibt definitiv Sinn. Daher erlaube ich mir das Ticket zu schliessen :-)

Im Ernst: es geht darum einen möglichst schnellen Zugriff zu ermöglichen. Akte auf - Sternchen - Dokument offen. 

In dem Sortierszenario bedeutet es: Akte auf - Dokumente-Tab - Sortieren - merken "Mist, Ordner ist ja ausgeblendet" - alle Ordner einblenden - Sortieren - Dokument öffnen. Dann ist aber die Ordnereinblendung verändert, also nochmal anpassen.

**Comment by Dickmaulruessler** [comment]
Ah, ja, das ist wirklich praktisch und sollte da bleiben!

Noch folgender Hinweis: 
Ich erstelle bisher keine Favoriten.-Dokumente. 
Das gelbe Sternchen fand ich so auffällig. Ich wollte schon mehrfach wissen, was es für eine Funktion hat. Es sah mir nach einem Button aus (wie der Button "Notizen" rechts daneben). Deshalb hatte da drauf geklickt und nichts tat sich. 
Als Tooltip kommt die Erklärung. Wenn man aber zu ungeduldig ist und klickt statt zu warten, kommt kein Tooltip und (wenn man keine Favoriten definiert hat) tut sich gar nichts. 

Danke, Jens, jetzt weiß ich bescheid. 
Ob sich auch andere so dumm anstellen wie ich? Dann könnte man evtl. fürs Klicken eine Funktion einrichten, welche dem Tooltip entspricht...

**Comment by j-dimension** [comment]
> fürs (nur erfolglose) Klicken eine Funktion einrichten, welche dem Tooltip entspricht...

Das verstehe ich nicht. Was soll da passieren?

**Comment by Dickmaulruessler** [comment]
Dasselbe beim Klicken wie beim Tooltip. Nur eine Info. 

Man könnte aber auch gerne der Ansicht sein, dass der Nutzer sich einfach in der Doku informiert sollte oder der Nutzer unwissend bleibt und das Sternchen eben einfach ignoriert. 
Das Sternchen verleitet aber nur dazu, dass man neugierig ist und es unbedingt wissen will :-)

Beende das Thema aber sonst gerne.

**Comment by Dickmaulruessler** [comment]
Probiere es vielleicht mal in einer Akte aus, in der es keine Favoriten gibt und du schnell auf das Sternchen klickst....

Aber jetzt kommt der Tooltip ja auch schneller (du hast die Zeit ja angepasst).

**Comment by j-dimension** [comment]
Da möchte ich den Aufwand lieber an anderer Stelle investieren. 

Soviel möchte ich dem Anwender zumuten: Wenn ein Knopf nicht "verstanden" wird, dann nach Tooltip schauen. Alles weitere wäre dann Overengineering :-)

**Comment by Dickmaulruessler** [comment]
jo!

Merci!
