### ISSUE TITLE
[FEATURE] Aktenvorauswahl im Berechnungs-Plugin und Anzeigeakte nach Erstellen des Dok

### ISSUE THREAD

**Issue by Maz111111** [jlawyerorg/j-lawyer-org#1198]
Sorry für die lange Überschrift -- ggf. anpassen  mir fiel nichts prägnanteres ein

Wenn man aktuell in einer Akte arbeitet und eine Rechnung über das Plugin und eine Vorlage erstellt, sollte bei der Frage nach der Akte, die aktuelle Akte oben stehen und ggf. vorausgewählt sein.

Nach Erstellen des Dokumentes, sollte die KSW dann (soweit die Rechnung in der aktuellen Akte erstellt wurde) in dem aktuellen Reiter der aktuellen Akte verbleiben oder (wenn die Rechnung für eine andere als die aktuelle erstellt wurde) direkt in den Reiter Dokumente für diese Akte springen (derzeit springt sie in den Reiter "allgemeine Daten").

Ggf. sollte die frisch erstellte Rechnung zur weiteren Bearbeitung auch direkt geöffnet werden (dies mal zur Diskussion - würde jedenfalls meinem regelmäßigem Arbeitsablauf entsprechen)

**Comment by j-dimension** [comment]
Du kannst die Berechnung einfach über den Tab "Berechnung" der Akte starten, dann ist der Aktenbezug vorhanden.

**Comment by Maz111111** [comment]
OK, das hab ich nicht gewusst.

Macht aber Sinn... 😀
Danke
