### ISSUE TITLE
[FEATURE] Datei ersetzen können

### ISSUE THREAD

**Issue by Maz111111** [jlawyerorg/j-lawyer-org#1203]
Wenn man ein Dok in ein pdf umwandelt, kommt es häufig vor, dass man dann doch noch etwas am Dok ändert und dies erneut in ein pdf umwandelt. Beim umwandeln übernehme ich immer den vorgeschlagenen Namen.

Wenn man dann erneut umwandelt, wird darauf hingewiesen, dass es ein File mit diesem Namen bereits gibt und ein anderer Name vergeben werden soll.
Das ist so noch vorhersehbar.

Wenn man in weiser Voraussicht aber vorher das pdf schon löscht und erst dann erneut umwandelt, kommt die gleiche Fehlermeldung, weil ein File mit diesem Namen im Papierkorb dieser Akte liegt.

Zumindest für letzteren Fall halte ich es für anwenderfreundlich, die Option "soll Datei ersetzt werden?" anzubieten.

**Comment by iradraconis** [comment]
Absolut!! Mich hat das auch die Tage irritiert!

**Comment by stm9x9** [comment]
Das hat vermutlich auch damit zu tun, daß man einen Dateinamen - auch wenn er in unterschiedlichen Ordnern vorkommen soll - nur einmal in der Akte haben darf. Vielleicht wäre das der umfassendere Ansatz, um das Problem anzugehen?

Zb hatte ich die Tage in einem Klageverfahren wegen einer Rückforderung Jobcenter den Fall, daß zeitgleich gegen beide Betroffene trotz laufendem Verfahren die Vollstreckung versucht wurde. Da gab es dann zwei neue Unterordner: Eilverfahren x und Eilverfahren y. In beiden dann die Datei: yymmdd-an_SG-Antrag auf Eilschutz.odt - bzw genauer: es sollte diese beiden Dateien geben. Aber j-l meckerte an, die Datei gibt es ja schon.

**Comment by Bentipa** [comment]
@j-dimension closed via #1521?

**Comment by j-dimension** [comment]
@Bentipa ja, in der Tat!
