### ISSUE TITLE
[FEATURE] Mehr "eigene Felder" für Akten

### ISSUE THREAD

**Issue by SaraSiakala** [jlawyerorg/j-lawyer-org#1206]
Drei "eigene Felder" für Akten sind schön, aber mehr (bspw. neun) wären super. Das wäre für uns eine hilfreiche Erweiterung, über die wir uns sehr freuen würden.

PS: Wurde bereits von einem anderen User gewünscht, aber soweit ich sehen konnte noch kein Ticket dazu erstellt.

**Comment by j-dimension** [comment]
@SaraSiakala welche Eingaben würden dort getätigt werden? Evtl. ist es sinnvoller das als "richtige" Felder aufzunehmen, oder in Form eines Falldatenblattes.
