### ISSUE TITLE
Beteiligte generisch modellieren mit "Beteiligtentyp", der konfigurierbar ist?

### ISSUE THREAD

**Issue by j-dimension** [jlawyerorg/j-lawyer-org#121]
bspw. weitere für Gericht o.ä.

Hinweise eines Anwenders vom 05.07.2015:
im Aktenmodul gibt es unter dem Reiter "Beteiligte" die Kategorien 
"Mandanten," "Gegner" und "Dritte." Um an all diese Beteiligten jeweils einen 
Brief zu schreiben, muss man drei verschiedene Vorlagen haben, nämlich bspw. 
"Brief an M," "Brief an G" und "Brief an D" mit den jeweiligen Platzhaltern im 
Adressfeld.
Wäre es nicht eine Erleichterung, die Aufteilung der Beteiligten in die drei 
genannten Kategorien aufzugeben und sämtliche Aktenbeteiligten nur noch unter 
"Beteiligte" zu speichern und anzuzeigen? Dann bräuchte man nur noch eine 
Vorlage "Brief" mit allgemeinen Platzhaltern für "Name," "Vorname" usw für 
Schreiben an jeden beliebigen Beteiligten. Die korrekte Ausfüllung der 
Platzhalter erfolgt dann durch Anklicken des entsprechenden Beteiligten, so 
wie dies ja jetzt schon funktioniert, wenn es bspw. mehrere Mandanten oder 
mehrere Gegner gibt.
Wenn alle Beteiligten nur noch in einer Kategorie zusammengefasst sind, wäre 
es natürlich nützlich, wenn man zu den jeweiligen Beteilgten eingeben könnte, 
welche Funktion innerhalb der Akte er hat, also bspw. Mandant, Gegner, Gericht 
Instanz, Gericht 2. Instanz, Rechtsschutzversicherung usw., vielleicht
sogar vom Benutzer frei definierbar.

**Comment by Maz111111** [comment]
Also der Hinweis ist ja - wenn ich das richtig verstehe - nur für die Fälle relevant, in denen ein Anwender vollständig leere Vorlagen erstellt, die nur das Adressfeld befüllen und ggf. die eigenen aktenbezogenen Daten.
Das dürfte aber nicht der regelmäßige Anwendungsfall sein. Die Vorlagen dürften in der Regel ja bereits mit Textbausteinen befüllt sein, die auch nur für den einen jeweiligen Beteiligten zutreffen.
Wenn man tatsächlich einmal an alle Beteiligte identische Briefe senden will, sollte der Serienbrief ausreichend sein.
Wenn ich die Konsequenz richtig sehe, würde durch die in Betracht gezogene Änderung ein über Jahre etabliertes Vorlagen- und Beteiligten-System geändert (und nicht nur ergänzt) werden. Die Arbeitsabläufe des Anwenders müssten sich ändern und die bestehenden Vorlagen könnten eventuell auch nicht mehr genutzt werden, bzw. müsste irgendeine Abwärtskompatibilität eingebaut werden.
Großer Aufwand für "überschaubaren" Nutzen. Selbst wenn man dies nur als "Erweiterung" einbauen würde.
Darüber sollte man vielleicht noch mal nachdenken. Never touch an running System … und so...

**Comment by stm9x9** [comment]
Zumindestens gibt es diverse Vorlagen, die zb sowohl für das Gericht I. als auch II. Instanz sind. 

Ganz universal ist zb bei mir die Vorlage Telefonvermerk.

**Comment by j-dimension** [comment]
Gelöst in #117
