### ISSUE TITLE
[BUG] Anmeldung nach Update nicht mehr möglich

### ISSUE THREAD

**Issue by MarcoWolny** [jlawyerorg/j-lawyer-org#1217]
Betriebssystem: MacOS 11.2.3
Software-Version 1_14_0_2

Nach dem Update auf die Version 1.14.0.2 kann ich mich (und auch kein anderer Benutzer) nicht mehr bei j-lawyer anmelden.

Update auf der Box erfolgreich durchgeführt.

Client erfolgreich upgedated.

Oberfläche des Clients zeigt grün bei "j-lawyer.BOX", Prüfung der Erreichbarkeit liefert "Erreichbar, Service läuft".

Login mit Benutzer und Passwort führt zur Fehlermeldung "Anmeldedaten oder Verbindungsparameter falsch" (und ja, die Eingabe ist korrekt).

Management Konsole kann nicht geöffnet werden, der Browser öffnet sich und fordert die Eingabe von Benutzername und Passwort, nach Eingabe dieser bleibt der Benutzer "stehen", das Feld "Passwort" ist wieder leer. Die Seite lädt nicht. Am Ende kommt die Fehlermeldung "Unauthorized".

Rücksetzung der Box mittels Datenrücksicherung hat hieran nichts geändert. 

Über den Finder erreiche ich die Verzeichnisse "backup", "share" und "vorlagen" problemlos. 

Auch ein Downgrade des Clients hat hieran nichts geändert.

Ich fahre jetzt das Update auf BigSur 11.3.1 – aber ich glaube kaum, dass es daran liegt…

Wie komme ich denn jetzt wieder in die Software? Was mache ich denn jetzt mal Schlaues?

**Comment by j-dimension** [comment]
Bitte mal Telefonnr. per E-mail senden und AnyDesk installieren
