### ISSUE TITLE
Ordnerstruktur für Dokumente

### ISSUE THREAD

**Issue by j-dimension** [jlawyerorg/j-lawyer-org#122]
Anwenderwunsch:
"Gibt es die Möglichkeit, Unterordner anzulegen und frei zu benennen, um hierüber eine bessere Übersichtlichkeit der Dokumente in den Akten zu erhalten? (Z.B. Unterteilung in Mandantenteil, Gericht-/Amtsteil,...)
Eine entsprechende Umsetzung einer Unterordnerstruktur (Idealerweise mit der Möglichkeit, diese frei und individuell zu benennen) wäre sehr wünschenswert um bei größeren Verfahren oder mehreren Beteiligten nicht den Überblick zu verlieren."
mögliche Umsetzung:
Aktentypen, jeder Typ hat eine vorgefertigte Ordnerstruktur
Struktur kann zusätzlich manuell je Akte geändert werden

Akte:
- [x] Akte erhält eine Ordnerstruktur
- [x] Akte 1 : n Ordner vs. Akte 1 : 1 Referenz auf Ordnerstrukturtemplate (dann würden auch bei Änderung des Templates alle vorhandenen Akten automatisch angepasst - mit Referenz auf Template könnte man allerdings in der Akte keine leeren Ordner anlegen)
- [x] jeder Ordner wird als voller Pfad gespeichert, also keine Baumabbildung im Modell - das wird dynamisch zur Laufzeit erledigt (Nachteil: bei Umbenennen eines übergelagerten Ordners müssen alle Subordnerpfade angepasst werden)

Dokument(e):
- [x] Dokument bekommt ein Attribut für den aktuellen Ordner, dort wird der vollständige Pfad gespeichert
- [x] ein Dokument kann nur in einem Ordner sein
- [x] ggf. eigener Renderer für Dokumentzeilen im Baum, inklusive Tags und Metadaten

Aktendarstellung beim Laden:
- [x] zuerst Ordnerstruktur lt. Aktenordnern aufbauen
- [x] dann Dokumente "einsortieren", ggf. fehlende Ordner hinzufügen

REST API
- [x] neues API-Level
- [x] Minimalumfang: Services die Dokumente mit Ordnern abspeichern können
- [x] besser: kompletter Funktionsumfang per API

Visualisierung:
- [x] eine Baumstruktur, die Ordner UND Dokumente darstellt - oder Baum und Dokumentliste, plus zusätzlichen Tab mit flacher Darstellung
- [x] Dokumente nicht mehr als Tabelle, sondern mit eigenem Renderer, um in der Horizontalen Platz zu sparen. Jedoch dadurch Problem der Sortierbarkeit, daher:
- [x] Sortierbuttons für jede relevante Spalte (siehe SortButton)
- [x] PROBLEM: in einem Table Cell Renderer sind die Elemente nicht klickbar. Brauche aber die Multiselektfunktion etc. einer Tabelle...
- [x] Baumstruktur ist initial komplett aufgeklappt
- [x] Tags direkt am Dokument, nicht unterhalb und separat
- [x] Tag-Refresh je nach Selektion der Dokumente passt nicht (bspw. Mehrfachselektion und dann zurück auf Einfachselektion)
- [x] Anzeige Dokumentanzahl am Ordner --> später

Aktionen:
- [x] Ordnerstruktur aus Templatestruktur übernehmen - es werden ausschließlich Aktenordner ersetzt, die Angaben an den Dokumenten bleiben erhalten. D.h. nicht leere Ordner werden nicht entfernt, da sie als Attribut an den Dokumenten hängen
- [x] Dokument in Ordner verschieben
- [x] Dokument in Ordner kopieren
- [x] Ordner löschen (leer vs. nicht leer)
- [x] Ordner anlegen
- [x] Ordner umbenennen
- [x] optional: Ordner in anderen Elternordner verschieben (ggf. abbildbar durch Neuanlage Ordner, Verschieben der Dokumente, Löschen Altordner) --> später
- [x] HTML-Export: Dokumente nach Ordner und Name sortiert in der HTML-Datei

Einstellungen:
- [x] CRUD für Ordnertemplates
- [x] CRUD für Ordner eines Ordnertemplates
- [x] Klonen von Ordnertemplates
- [x] Beispielstruktur(en) via Flyway ausliefern

unklar:
- [x] Bäume auch in anderen Dialogen, die auf Dokumente zugreifen? (Anhang auswählen beA / E-Mail, Drebis, ...) --> erstmal nicht, da die Ordnerstruktur in jeder Akte anders ist, das würde viele Klicks erfordern
- [x] unterschiedliche Icons für Ordner ermöglichen? --> erstmal nicht

out of scope:
- [x] Abbildung Ordnerstruktur im Dateisystem - die Struktur gibt es nur in der Datenbank, nicht im Datenverzeichnis - daher kein Aufwand bzgl. Backup / Restore

**Comment by j-dimension** [comment]
https://www.j-lawyer.org/?topic=unterordner-dokumente/#post-2837

> Im Übrigen bin ich mittlerweile der Meinung dass man für die Akte selbst gar keine Ordner nutzen sollte, sondern ausschliesslich mit den Tags arbeitet. Ein Dokument kann dann auch einfach in mehreren Ordnern (sprich: unterhalb mehrerer Tags) angezeigt werden.
> Eine solche „Ordneransicht“ auf Basis der Tags wird es aber mit der 1.10 noch nicht geben. Wohl aber eine einfache Auffindbarkeit von Dokumenten anhand der Tags, sowie eine Übersicht der aktiven Tags mit Anzahlen der Dokumente.

**Comment by j-dimension** [comment]
@stm9x9

**Comment by stm9x9** [comment]
ich fände es übersichtlicher wenn man (notfalls optional) nicht wie bei den Vorlagen-Ordnern immer nur in einen (Unter)Ordner reingucken kann sondern – sofern aufgeklappt – in alle.

Man braucht meiner Erfahrung nach oft einen schnellen Überblick, was man an Dokumente im Gerichtsordner hat, was im Mandantenordner etc.

Im übrigen wäre es nett, wenn zb farblich gekennzeichnet ist, ob ein Ordner leer ist. zb könnte der Aufklapppfeil eine andere Farbe haben.

Und eine Idee wie das optisch aussehen könnte, was woanders schonmal angesprochen wurde: in der Liste per Farbklecks anzeigen welche Etiketten vergeben wurden und bei den Ordnern auch mit der Anzahl.

**Comment by stm9x9** [comment]
1

![](https://i.ibb.co/qdXwDWw/image.png)

**Comment by stm9x9** [comment]
> https://www.j-lawyer.org/?topic=unterordner-dokumente/#post-2837
> 
> > Im Übrigen bin ich mittlerweile der Meinung dass man für die Akte selbst gar keine Ordner nutzen sollte, sondern ausschliesslich mit den Tags arbeitet. Ein Dokument kann dann auch einfach in mehreren Ordnern (sprich: unterhalb mehrerer Tags) angezeigt werden.
> > Eine solche „Ordneransicht“ auf Basis der Tags wird es aber mit der 1.10 noch nicht geben. Wohl aber eine einfache Auffindbarkeit von Dokumenten anhand der Tags, sowie eine Übersicht der aktiven Tags mit Anzahlen der Dokumente.

Ich halte aus meiner täglichen Arbeit heraus Ordner für unabdingbar als Ordnungsinstrument.

Zum einen sind sie flexibler: Es gibt je nach Rechtsgebiet zwar Standardordner aber manchmal muß ich sehr aktenspezifische Ordner anlegen, die ich fast kein zweites Mal in der Art benötige. Dafür jetzt die Menge der Tags mit solchen Spezialsachen vollzumüllen halte ich für ungünstig.

Zum anderen hilft es bei der Übersicht – gerade wenn man wie oben vorgeschlagen, mehr als den Inhalt eines Ordners parallel zu sehen bekommt – daß die Inhalte nach Ordnern getrennt gelistet sind. Bei Tags dürfte es einigen programmtechnischen und dann Anwenderaufwands bedeuteten so zu gruppieren.

Und letztlich zeigt meine Erfahrung, daß Dokumente, die vermeintlich in mehr als einem Order stecken, dann doch inhaltlich ihre eigenen Wege gehen und deswegen nicht nur einmal mit mehreren Order-Tags angelegt werden sollten, sondern als echte Duplikate. Beispiel: Alle Kto-Auszüge sammle ich in „Mandantenunterlagen“. Die passenden kopiere ich mir zu den PKH-Unterlagen in den Gerichtsordner. Und dann fummle ich an diesen Dateien rum. Vielleicht muß noch was geschwärzt werden, ich brauche einen Teilzeitraum doch nicht, … Wenn so eine Änderung dann auf das „Original“ im Mandantenordner durchschlagen würde, wäre das tödlich.

Aber das erster Argument ist mir das mir wichtigste: Ich kann und darf die Tag-Wolke nicht derart groß werden lassen, wie ich es müßte, wenn ich alle möglichen Ordner als Tags abbilden müßte

**Comment by stm9x9** [comment]
**heul** 

gibt es ein geplantes Zieldatum für 2.0? Weil ohne Order kann ich nicht umsteigen. Und ich muß wirklich schnellstmöglichst umsteigen, alleine schon weil beAweb derart viel Zeit frißt.  Das und das rollenbasierte Beteiligtensystem.

**Comment by j-dimension** [comment]
> das rollenbasierte Beteiligtensystem

Daran arbeite ich gerade, und da bleibt kein Bit auf dem anderen - Vorlagensystem, Stammdaten für Akte und Adresse, sehr viele Dialoge, das zieht sich überall durch. Und die 1.12 ist schon wieder saugross geworden: https://github.com/orgs/jlawyerorg/projects/6
Ich muss irgendwo Einschnitte machen, oder die Anwender monatelang warten lassen.

**Comment by stm9x9** [comment]
> Daran arbeite ich gerade, und da bleibt kein Bit auf dem anderen

Ick seh es jerade und freu mir so! Und ick bin sowat von jespannt! Wie en Flitzebogen!

**Comment by j-dimension** [comment]
Bin mittlerweile fast fertig, evtl. schicke ich morgen schonmal ein "Preview" als Blogartikel.

Das letzte Kopfzerbrechen das ich habe ist die Prüfung auf Interessenkonflikte. Da mit dem neuen Konzept die Beteiligtentypen frei konfigurierbar sind, kann ich nicht wissen welche Konstellationen nicht auftreten dürfen. Das müsste ebenfalls konfiguriert werden. 

Mal sehen.

**Comment by stm9x9** [comment]
Da habe ich einen Vorschlag für in der Mailingliste gelesen: 

ach und könnte es noch irgendwie eine Gruppierungsfunktion für die selbst erstellten Rollen geben? Letztlich bleibt es ja dabei, es gibt immer drei Lager: meins, der Gegner und Unabhängige/Dritte. Es wäre schön, wenn diese in der Beteiligenübersicht auch so gruppiert werden können. Dafür müßte zb noch für jede Rolle neben Namen und Farbe eben dieses Lager auswählbar sein. Letztlich dürfte es das doch auch für die Prüfung von Interessenskollisionen notwendig sein!?

**Comment by j-dimension** [comment]
Das gehört thematisch nicht zu diesem Ticket hier. 

Eine Gruppierung könnte auch einfach eine Sortierung nach Rolle sein. Die Prüfung auf Interessenkonflikte ist jetzt erstmal so gemacht, dass man einen Überblick über alle "Beteiligungen" beklommt, wenn man eine Adresse zuordnet oder die Rolle ändert. Die Entscheidung liegt dann letztlich beim Anwender.

**Comment by j-dimension** [comment]
Akte:
- [ ] Akte erhält eine Ordnerstruktur
- [ ] Akte 1 : n Ordner
- [ ] jeder Ordner wird als voller Pfad gespeichert, also keine Baumabbildung im Modell - das wird dynamisch zur Laufzeit erledigt

Dokument(e):
- [ ] Dokument bekommt ein Attribut für den aktuellen Ordner, dort wird der vollständige Pfad gespeichert
- [ ] ein Dokument kann nur in einem Ordner sein
- [ ] ggf. eigener Renderer für Dokumentzeilen im Baum, inklusive Tags und Metadaten

Aktendarstellung beim Laden:
- [ ] zuerst Ordnerstruktur lt. Aktenordnern aufbauen
- [ ] dann Dokumente "einsortieren", ggf. fehlende Ordner hinzufügen

Visualisierung:
- [ ] eine Baumstruktur, die Ordner UND Dokumente darstellt - spart Platz
- [ ] Baumstruktur ist initial komplett aufgeklappt

Aktionen:
- [ ] Ordnerstruktur aus Templatestruktur übernehmen - es werden ausschließlich Aktenordner ersetzt, die Angaben an den Dokumenten bleiben erhalten. D.h. nicht leere Ordner werden nicht entfernt, da sie als Attribut an den Dokumenten hängen
- [ ] Dokument in Ordner verschieben
- [ ] Ordner löschen (leer vs. nicht leer)
- [ ] Ordner anlegen
- [ ] Ordner umbenennen
- [ ] optional: Ordner in anderen Elternordner verschieben (ggf. abbildbar durch Neuanlage Ordner, Verschieben der Dokumente, Löschen Altordner)

Einstellungen:
- [ ] Möglichkeit, Ordnerstrukturen als Templates / Blaupause zu definieren und zu manipulieren

unklar:
- [ ] Bäume auch in anderen Dialogen, die auf Dokumente zugreifen? (Anhang auswählen beA / E-Mail, Drebis, ...)

**Comment by Maz111111** [comment]
Das klingt alles sehr gut und spannend. Das wird ein großer Fortschritt und eine Erleichterung.

Wäre es denkbar und möglich und nicht zu aufwendig, wenn man in der Akte im Reiter Dokumente über dem Dokumentenfenster weitere Reiter hätte (nach links und rechts mit kleinen Pfeilen scrollbar, wenn der Platz über dem Fenster nicht reicht), wobei der erste Reiter immer die komplette (bei Bedarf aufklappbare) Baumstruktur beinhaltet und die restlichen den Inhalt der einzelnen angelegten Ordner, so dass man sich (ohne Baumstruktur) den Inhalt eines einzigen Ordners anzeigen lassen kann, wobei das Dokumenten-Fenster dann wie gewohnt mit Datum, Favoriten etc. aussieht.
Nur eine Idee.
Viele Grüße
Martin

**Comment by j-dimension** [comment]
@Maz111111 technisch möglich ist das (Notiz an mich selbst bzgl. scrollbarer Tabs: https://docs.oracle.com/javase/8/docs/technotes/guides/swing/1.4/tabbedPane.html), der Aufwand aber schon recht hoch. Bei Änderungen müssten die Tabs immer mit dem ersten "Gesamttab" synchronisiert werden. Ich schaue mir das bald genauer an.

**Comment by stm9x9** [comment]
> Akte:
> 
> * [ ]  Akte erhält eine Ordnerstruktur
> * [ ]  Akte 1 : n Ordner vs. Akte 1 : 1 Referenz auf Ordnerstrukturtemplate (dann würden auch bei Änderung des Templates alle vorhandenen Akten automatisch angepasst - mit Referenz auf Template könnte man allerdings in der Akte keine leeren Ordner anlegen)

Versteh ich zwar nicht, würde aber gerne nochmal an die Idee erinnern, auch mandantenbezogene Ordner zu haben, um zb aktenübergreifende Sachen wie Kontoauszüge, Mietverträge etc unterzubringen

> * [ ]  ggf. eigener Renderer für Dokumentzeilen im Baum, inklusive Tags und Metadaten

siehe mein bebilderter Vorschlag weiter unten
 
> * [ ]  Baumstruktur ist initial komplett aufgeklappt

dann bitte einen Button oder so: alles einklappen / ausklappen dazu
 
> Aktionen:
> 
> * [ ]  Ordnerstruktur aus Templatestruktur übernehmen 

dies sollte dann an dem Akten-Sachgebiet hängen. offene Frage: automatische Übernahme bei nachträglichem Sachgebietswechsel? (zb weil man es schlicht fehlerhaft beim Anlegen ausgewählt hat)

> unklar:
> 
> * [ ]  Bäume auch in anderen Dialogen, die auf Dokumente zugreifen? (Anhang auswählen beA / E-Mail, Drebis, ...)

sehr sinnvoll, damit man die Dokumente zielgerecht findet und ähnlich / gleich benannte in verschiedenen Ordnern unterscheiden kann Sofern hier multiselection möglich sein sollte, wäre die kombinierte Ordner/Dokumente-Übersicht angebracht. Wenn nur ein Dokument selektiert werden kann, dann kann es eine "eindimensionale" Darstellung sein, wo man immer nur einen Ordner auf einmal sieht

> * [ ]  Auswirkung auf HTML-Export

Verzeichnis-Ordner anlegen?

> * [ ]  unterschiedliche Icons für Ordner ermöglichen?

love this! Aber die Anzeigen (leer/nicht leer, ggf welche Etiketten sind im Ordner ...) siehe mein buntes Beispiel unten scheinen mir wichtiger als unterschiedliche Icons, falls sich das beißen sollte
 
> out of scope:
> 
> * [ ]  Abbildung Ordnerstruktur im Dateisystem - die Struktur gibt es nur in der Datenbank, nicht im Datenverzeichnis - daher kein Aufwand bzgl. Backup / Restore

klingt selbst für mich vernünftig :-) Die Infos stecken ja offenbar in den Metadaten der Datei

alles in allem: LOVE THIS!

**Comment by j-dimension** [comment]
![grafik](https://user-images.githubusercontent.com/3729754/87345046-bc45ca00-c54f-11ea-8ff4-e23bfdee3e67.png)

**Comment by stm9x9** [comment]
Gibt es schon ein Bild, wie sie da die Dokumente optisch einfügen?

**Comment by j-dimension** [comment]
Noch nicht, bin dran!

**Comment by j-dimension** [comment]
@stm9x9 hast Du Input für eine möglichst allgemeingültige "Standardstruktur" die ich direkt mit ausliefern kann? Würde das dann direkt in den Installer aufnehmen.

**Comment by stm9x9** [comment]
Meinst Du eine Vorgabe, unabhängig von nutzer/sachgebietsspezifischen Ordnern? Oder meinst Du Mustervorlagen für einige Sachgebiete und ein allgemeines Muster, was sich jeder zum Aufbau eigener Struktur-Vorlagen vornehmen kann?

Ich glaube, ein Standard, den jeder vorgesetzt bekommt und den er nicht ändern kann, das paßt nicht für jeden. Und sei es nur, daß er es anders benamst haben will.
 
Ich persönlich würde ja meinen:

Mandant Korrespondenz
Mandant Unterlagen
Kanzlei Dokumente

aber das halte ich nicht für 100% verallgemeinerungsfähig.

Ich würde eher ein paar Musterstruktur-Vorlagen anbieten und für individuelles dann die Möglichkeit, in einem Fenster die vorhandenen Vorlagen zu bearbeiten und vor allem auch zu klonen. Dann kann sich jeder selber seine Minimalvorlage bauen, die dann klonen und um sachgebietsspezifische Ordner ergänzen und so seine eigene Bibliothek an Ordnerstrukturen aufbauen.

Wenn ich Dir so ein paar Ordner-Vorlagen für Sachgebiete als Mustervorlage für die Nutzer machen soll, gerne.

**Comment by stm9x9** [comment]
Was mir gerade noch einfällt:

Die Dokumente sind und sollen ja weiterhin nach Name, Datum etc sortierbar sein. Die Ordner würde ich davon unberührt lassen. Also die sollten immer alphabetisch sortiert sein und sich nicht umsortieren. Das führt sonst zu Chaos und ich sehe keinen Nutzen in so einer Sortierung, der das rechtfertigen würde.

**Comment by j-dimension** [comment]
> Oder meinst Du Mustervorlagen für einige Sachgebiete und ein allgemeines Muster, was sich jeder zum Aufbau eigener Struktur-Vorlagen vornehmen kann?

Genau das.

**Comment by Maz111111** [comment]
Ich hatte gedacht, dass man über das Kontextmenü der rechten Maustaste einen "neuen Ordner erstellen" und diesen dann über "umbenennen" umbenennen kann.
Und das beliebig oft und auch in jedem Ordner als Unterordner (hier ggf. von Haus aus auf 3-5 Unterebenen begrenzt).
Dann bräuchte es keine Vorlagen.

**Comment by j-dimension** [comment]
@Maz111111 das schon, aber man möchte wahrscheinlich nicht für jede neue Akte bei "Null" anfangen und ggf. größere Standardstrukturen immer wieder händisch erstellen.

**Comment by Maz111111** [comment]
Das könnte aber genauso, wie unter "Einstellungen - Adressen - Beteiligtentypen" geregelt werden. 
So dass sich jeder Anwender seine Grundstruktur, die er in jeder Akte haben will, erst mal selbst erstellen kann. In der jeweiligen Akte selbst sollten dann manuelle Änderungen möglich sein - also auch Abweichungen von der als Grundsatz in den Einstellungen vorgegebenen Ordnerstruktur (Bsp. eingestellt ist immer ein Ordner "Mandantenverkehr" - der muss in der einzelnen Akte auch wieder gelöscht bzw. umbenannt werden können, ohne das damit die Grundsatzeinstellung verändert wird).
Ich denke nicht, dass es den "Service" braucht, für den Anwender eine mögliche Grundstruktur vorzubereiten. Zumal die Wahrscheinlichkeit, damit den Geschmack der Mehrheit zu treffen, m.E. gegen null tendiert.

**Comment by j-dimension** [comment]
Standardstruktur ausliefern: 

0 Abrechnung
0 Beratungshilfe
0 Mandant Korrespondenz
0 Mandant Unterlagen
0 Kanzlei Dokumente

**Comment by Maz111111** [comment]
Nachfrage / Hinweis:

ich habe gerade in der Rundmail die erste Vorschau auf die Ordnerstruktur gesehen...KLASSE!

Dabei ist mir aufgefallen, dass in dem Beispiel ein Unterordner Vollmacht vorhanden war. Dies brachte mich auf folgenden - von dem konkreten Beispiel unabhängigen - Gedanken:

Wenn ich etwas per beA oder sonst elektronisch versende, sende ich regelmäßig einen Schriftsatz und die Vollmacht mit. dies wäre im Beispiel in zwei unterschiedlichen (Unter-) Ordnern gelagert.

Je nach persönlicher Vorliebe wird es öfter so sein, dass Dokumente in verschiedene Unterordner einsortiert sind, aber gemeinsam verschickt werden sollen.

Es muss also möglich sein, mehrere Dokumente aus unterschiedlichen Unterordnern zu markieren und gemeinsam zu versenden.

Nur falls das noch nicht auf dem Schirm war.

**Comment by j-dimension** [comment]
> Es muss also möglich sein, mehrere Dokumente aus unterschiedlichen Unterordnern zu markieren und gemeinsam zu versenden.

Ja, das wird möglich sein.

**Comment by iradraconis** [comment]
Ich freue mich sehr auf das Update. Ordner sind ein tolles Feature. Auch die Implementation sieht sehr gelungen aus.

**Comment by j-dimension** [comment]
finalisierte Oberfläche:

![grafik](https://user-images.githubusercontent.com/3729754/98422577-5647fa00-208c-11eb-90d1-fcaad58e1ee5.png)
