### ISSUE TITLE
[BUG] Datei speichern in Akte speichert nicht in gewählten Ordner (nur innerhalb einer Akte)

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#1220]
Ich habe eine Mail oder eine beA-Nachricht bereits in einer Akte. Ich nehme einen Anhang daraus per Rechtsklick: Speichern in Akte.

Es kommt das neue Fenster zum Abspeichern:

![image](https://user-images.githubusercontent.com/29924198/117160274-456d0c80-adc1-11eb-90b8-0e5be532575d.png)

Ich wähle die aktuelle Akte und einen Ordner. Dann bestätige ich noch den Namen.

Die Datei wird dann dennoch im Standardordner abgelegt statt im ausgewählten Unterordner.

wenn ich es in eine andere Akte speichere, dann wird in den korrekten Ordner abgespeichert. 
wenn ich es aus dem Mailbereich von j-l mache, dann wird in den korrekten Ordner abgespeichert.

**Comment by j-dimension** [comment]
Tatsächlich wird das Dokument in den Unterordner gelegt, nur die Anzeige täuscht vor, dass es in der Wurzel liegt.
