### ISSUE TITLE
Ausrufungszeichen im News-Button entfernen

### ISSUE THREAD

**Issue by Dickmaulruessler** [jlawyerorg/j-lawyer-org#1222]
Das Ausrufungszeichen im News-Butten ist zu viel des Guten ...
... so jedenfalls meine Wahrnehmung. 

![fsdafsdaf](https://user-images.githubusercontent.com/46451749/117667014-bc7d1900-b1a4-11eb-89f7-b2a33772a525.jpg)

Ich würde alles so lassen wie es ist, nur das Ausrufungszeichen entfernen.

**Comment by j-dimension** [comment]
So ist das in der Tat. Sobald man draufklickt, gilt die News als gelesen und erscheint dann nicht nochmal. 

Ticket schließen?

**Comment by Dickmaulruessler** [comment]
> 
> Ticket schließen?

Ja, danke!
