### ISSUE TITLE
[TASK] [beA] [e-mail] Massen-Abspeichern von Anhängen (beA und Mail) neu gestalten

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#1225]
Nachdem seit 1.14 beim Abspeichern aller Anhänge einer Nachricht (damit zb Akteneinsichten die Originalnamen behalten und wegen der Menge an Dateien bei einer Akteneinsicht) nicht mehr wegen einer Umbenennung gefragt wird, kam es  Problemen bei Anwendern, die keine Akteneinsichten bekommen:

> Hauptsächlich kommen über das beA Nachrichten von Kollegen. Regelmäßig wie folgt:  2013_21Datei.pdf. Egal wie oft mir die Kollegin per beA schreibt. Die Datei heißt immer so. Häufig hängt dann auch noch die digitale Signatur als Anhang mit dran.
> 
> Dann klickt man auf die Büroklammer, geht dann in die Akte, benennt um und löscht die Signaturdatei. Der praktische Datumspräfix muss von Hand erstellt werden. Wenn zeitnah eine weitere Nachricht des Kollegen kommt, kann es sein, dass die der Akte über die Büroklammer gar nicht zugeordnet werden kann, weil man noch nicht umbenannt hat oder ggf. eine Datei mit diesem Namen im Papierkorb der Akte liegt.
> 
> Der Weg über Rechtsklick und zur Akte hinzufügen löst weder die automatisierte Etikettenvergabe noch das Verschieben der Nachricht in den Zugeordnet-Ordner aus. Deswegen stellt dies keine Alternative dar. Das Risiko, dass man mangels Etikettenvergabe die Akte nebst Nachricht vergisst, halte ich für zu hoch. 

Dafür folgender Vorschlag:

Die Änderung aus 1.14 wieder zurücknehmen. Aber beim Umbenenn-Dialog ein Anklick-Kästchen machen, mit dem bereits die aktuelle Datei nicht umbenannt wird und für alle weiteren Dateien bei diesem Abspeichervorgang wird der Dialog gleich umgangen und die Dateien, wie sie sind, abgespeichert. 

![image](https://user-images.githubusercontent.com/29924198/117743145-7d7faf80-b206-11eb-962d-2eb211fd577b.png)

Damit kann man - wenn man wie ich die bea-Nachricht auch abspeichert,

![image](https://user-images.githubusercontent.com/29924198/117743162-87a1ae00-b206-11eb-9fc3-4726d81a5b62.png)

diese noch umbenennen, aber dann bei den Anhängen entscheiden, ob man sie umbenennt (das mache ich bei normalen Anhängen ja auch, damit da das Datum aus dem Schreiben steht zb) oder aber darauf verzichten will bei Akteneinsichten.

**Comment by GuidoBo** [comment]
Hier ein Beispiel für die Fehlermeldung zu  #ticket:1517 <img width="551" alt="Bildschirmfoto 2022-01-04 um 12 06 31" src="https://user-images.githubusercontent.com/56734761/148050361-b6da9cfe-4b20-45bc-ab0c-a7dc220cad4b.png">

**Comment by Maz111111** [comment]
Ich wollte noch mal was dazu sagen.
Derzeit ist mein Workflow so, dass ich die gesamte beA Nachricht in die Akte übernehme und dann dort die Anhänge, die ich tatsächlich verfügbar haben will (in der Regel nur der relevante Schriftsatz ohne Signatur und allen anderes), nebst Umbenennen in die Akte speichere.
Dann blende ich die eigentliche beA Nachricht über die Ordnerstruktur aus.
Ursprünglich wollte ich das über das Klammerbutton direkt aus dem beA Fenster machen. Da das aus den in diesem Ticket beschriebenen Gründen nicht so richtig ging (kein Umbenennen möglich), musste ich erstmal ein "workaround" finden und mache es jetzt so wie beschrieben.
Warum schreibe ich das?
Weil ich meine Arbeitsweise nicht mehr als "workaround" betrachte. Sondern als den einzigen Weg, wie sinnvoll vorgegangen werden sollte.
Mit der gewünschten Änderung ist es nicht möglich, die gesamte beA Nachricht zur Akte zu nehmen und ein Kopie(!) einzelner Anhänge direkt zur Akte zu nehmen. Das muss man dann ohnehin wie eben beschrieben in der Akte vornehmen.
Dies ist aber m.E. der einzig richtige Weg. Im Zweifelsfall sollte man - insbesondere nachdem beA die Nachricht auf dem Server automatisiert gelöscht hat - die gesamte original Nachricht mit allen(!) Anhängen verfügbar haben. Die Kopie der jeweils gewünschten Anänge in der Akte dient nur der schnelleren Auffindbarkeit.
Aus meiner Sicht kann dieses Ticket daher gelöscht werden.
Allenfalls sollte der SpeicherDialog im beA Fenster dahingehend geändert werden, dass es nur noch einen Button gibt - nämlich "Nachricht zur Akte nehmen und in importiert verschieben".
Wenn man es übertreiben will, könnte man dann gleich noch einen Dialog aufmachen: "Welche der Anhänge sollen als Kopie direkt zur Akte genommen werden?" mit einem folgenden Dialog, der die (um-) Benennung ermöglicht.
Ist aus meiner Sicht aber nur Luxus. Wie gesagt reicht es m.E. die Buttons auf einen zu dezimieren um Missverständnisse auszuschließen.
Vielleicht finden sich ja Befürworter meiner Auffassung. 
Dann hätte sich dieses Ticket erledigt.
Ich werde meinen Workflow jedenfalls nicht erneut ändern und brauch das Ticket daher im ursprünglichen Sinne nicht mehr.

**Comment by j-dimension** [comment]
@stm9x9 @Maz111111 mit dem neuen Speichern-Dialog (siehe https://www.youtube.com/watch?v=cJSSjnrgGIk) werden nun auch automatisch die geänderten Dateinamen im XJustiz-Datensatz ausgetauscht. Somit besteht völlige Freiheit beim Benennen der Dokumente.
