### ISSUE TITLE
[FEATURE] Drebis - Textbausteine für Freitext hinterlegen

### ISSUE THREAD

**Issue by Linkki2021** [jlawyerorg/j-lawyer-org#1228]
Im Drebis-Dialog Freitext wäre es hilfreich vorbereitete Textbausteine oder -vorlagen verwenden zu können. Dies könnte analog der Mail-Vorlagen gestaltet sein.

Damit könnte man den Zeitaufwand reduzieren, da man oft das gleiche schreibt ("Sehr geehrte Damen und Herren, beigefügte Dokumente zu Ihrer Kenntnis. Mit freundlichen Grüßen" etc.)

**Comment by Linkki2021** [comment]
Auch toll wäre es, wenn hier die Platzhalter analog der sonstigen Logik angewendet werden könnten

**Comment by j-dimension** [comment]
- Vorlagenauswahl und Beteiligtenmatrix aufgenommen
- Filter auf reine Textvorlagen (Drebis unterstützt keine HTML-formatierten Nachrichten)
- Platzhalterauflösung umgesetzt, inklusive der Unterstützung für Platzhalter aus Falldatenblättern
- zuletzt ausgewählte Vorlage ist beim nächsten Vorgang automatisch ausgewählt

Was noch nicht geht, ist dass der in einem früheren Wizardschritt ausgewählte Kontakt in der Beteiligtenmatrix automatisch ausgewählt ist. Das unterstützt diese Komponente noch nicht. Wäre aber auch nur ein Problem, wenn mehrere Mandanten geführt werden. Macht Euch dazu gern Gedanken und kommentiert dieses Ticket, oder erstellt ein neues.

**Comment by j-dimension** [comment]
Video dazu:

https://github.com/jlawyerorg/j-lawyer-org/assets/3729754/7efb625a-f928-4340-ac6c-a6f1eef5d81c
