### ISSUE TITLE
[FEATURE] Drebis-Dialog Mandant(en) Vorauswahl

### ISSUE THREAD

**Issue by Linkki2021** [jlawyerorg/j-lawyer-org#1229]
Im Dialog sind immer alle Aktenbeteiligten via Checkbox bei "übertragen" vorausgewählt.

Hier würde es Sinn machen nur den Aktenbeteiligten "Mandant" vorauszuwählen, genau darum geht es ja in diesem Dialog.

**Comment by j-dimension** [comment]
@Linkki2021 bitte um kurzen Input:

Dass es immer eine Rolle "Mandant" gibt, ist nicht zwingend der Fall - sie könnte umbenannt oder spezifischer konfiguriert sein ("Versicherungsnehmern" o.ä.). 

Was ich tun könnte (vorbehaltlich genauerer Prüfung):
- Sind alle im Dialog ausgewählten Kontakte in der selben Beteiligtenrolle, so speichere diese Rolle
- beim nächsten Aufruf: sofern eine Rolle gespeichert, selektiere alle Kontakte, die sich in dieser Rolle befinden. 

Wäre das eine Lösung?
