### ISSUE TITLE
[bea] Trennbalken blendet Anhänge vollständig aus

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#1233]
Der Trennbalken, der die Anhänge abtrennt, ist nach jedem Neustart wieder ganz unten und man sieht keine Anhänge.

![image](https://user-images.githubusercontent.com/29924198/118502293-dd57e800-b729-11eb-8dfd-59c880b6defd.png)

Auch wenn ich es hochziehe

![image](https://user-images.githubusercontent.com/29924198/118502336-e5b02300-b729-11eb-94e4-cd85faa161e0.png)

beim nächsten Start ist es wieder ganz unten.

Zusatzvorschlag: Das Feld unten sollte nie so klein gemacht werden können, daß nicht zumindest eine Zeile mit dem Wort Anhänge zu sehen ist.

**Comment by j-dimension** [comment]
@stm9x9 dass der untere Teil komplett verschwindet bekomme ich hier nicht reproduziert. Sobald ein Anhang drin ist, bekommt der untere Teil dann auch Scrollbalken, und diese werden nicht ausgeblendet / vom Trenner in den unsichtbaren Bereich verschoben.

Wie bekomme ich diesen Zustand, dass der Teil unten komplett weg ist, obwohl er Anhänge enthält?

**Comment by stm9x9** [comment]
wenn ich beA starte, sieht das immer so bei mir aus, schon ohne eine ausgewählte Nachricht:

![image](https://user-images.githubusercontent.com/29924198/119279945-00edc780-bc2f-11eb-86e3-07fe656e8bf7.png)


und daran ändert sich nichts, wenn ich eine Nachricht markiere.

**Comment by j-dimension** [comment]
Client stellt nun sicher, dass sich der Trenner nur im Bereich 10% .. 90% befindet.
