### ISSUE TITLE
Bessere Fehlermeldung, wenn Ordnervorlage bereits existiert

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-org#1238]
Wenn man eine Vorlage für eine Dokumentenordnerstruktur anlegt, z.B. Standard, erscheint diese als neue Vorlage mit dem Grundordner Dokumente. Soweit sogut. Wenn man dann den Grundordner Dokumente markiert und die linke Maustaste nimmt, kann man dort weitere Unterordner anlegen. Auch gut. Wenn man aber den Grundordner Dokument markiert und dann rechts das + drückt, um einen Unterordner zu erzeugen (so habe ich das erwartet), dann erscheint folgender Fehler:

![grafik](https://user-images.githubusercontent.com/37142896/118951550-77eb3d80-b95b-11eb-84f9-c92805a5ccf8.png)

Wenn man den Dokumentordner, der markiert ist umbenennen will, wird die Vorlage umbenannt. 

Da stimmt was nicht....

**Comment by j-dimension** [comment]
Zunächst zum Konzept:  Über das + rechts kannst Du eine komplett neue Ordnerstruktur anlegen. Es muss ein Name angegeben werden, dann erscheint dieser in dem Dropdown (wo in Deinem Screenshot "Standard" steht). Die Editierung der Ordner geht einzig im unteren Bereich per Markierung und Rechtsklicks / Kontextmenü.

**Comment by stm9x9** [comment]
Bei mir kommt bei dem + ja erstmal eine Abfrage, die erläutert, daß es hier um eine neue Ordnerstruktur geht?

![image](https://user-images.githubusercontent.com/29924198/119232196-95b7ce80-bb24-11eb-8818-fcd6be0fda58.png)

Allerdings hätte ich zwei Vorschläge, um das deutlicher zu machen

1) Das + bezieht sich ja wie der Papierkorb und die anderen Dinge auf die Ebene Ordnerstruktur. Ich würde die daher auch alle in einem Block anordnen statt das + so weit rechts.
2) von den Buttons hat nur Duplizieren ein Tooltip, das die Funktion erläutert. Wäre für die anderen auch hilfreich. U.a. für + = Neue Ordnerstruktur

**Comment by stm9x9** [comment]
ggf wäre es auch hilfreich, wenn man die Aktionsbuttons für die Ordner nicht in ein Kontextmenü "versteckt" sondern direkt in der Liste. Dann sieht man gleich: ah, für das Bearbeiten der Order sind diese Buttons.

![image](https://user-images.githubusercontent.com/29924198/119232506-c9dfbf00-bb25-11eb-8a2c-f1ae9c7b73cb.png)


Bei der Gelegenheit könnte man auch das Umbenennen von Ordnern ermöglichen.

**Comment by j-dimension** [comment]
>     1. Das + bezieht sich ja wie der Papierkorb und die anderen Dinge auf die Ebene Ordnerstruktur. Ich würde die daher auch alle in einem Block anordnen statt das + so weit rechts.

Löschen, Bearbeiten und Duplizieren beziehen sich auf die gewählte Ordnervorlage, das Hinzufügen benötigt keinen Kontext.
