### ISSUE TITLE
[BUG] Export von Bea-Anlagen in Akte scheitert, weil Name schon vorhanden

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-org#1241]
Ich bekamheute vom Gericht vier BEA-Nachrichten mit Dokumenten. Ich wollte die Dateien einfach in die Akte kopieren mit Nachrich tund Datei einzeln. Ging nicht, weil einige der Anhänge der verschiedenen Nachrichten den gleichen Namen wie bereits im Dateiordner vorhandene hatten. Da müsste eigentlich die Möglichkeit zur Umbenennung des Anfangs bestehen oder einfach automatisch ggf. nach Hinweismeldung beim Export ein (1) hinter den Dateinamen gesetzt werden, damit der Export erfolgen kann. 

**NOTE: Please search existing tickets to avoid duplicates **
**HINWEIS: Bitte vorab die Ticketsuche verwenden, um Doppeleinträge zu vermeiden **

**Describe the bug / Fehlerbeschreibung**
(todo: a description of the bug / eine Beschreibung des Fehlers)

**To Reproduce / Schritte zum Nachvollziehen**

1. Go to / Gehe zu '...'
2. Klicke auf / Click on '....'
4. Error message / Fehlermeldung: '...'

**Expected behavior / Erwartetes Verhalten**
Eine Beschreibung des erwarteten Verhaltens.

**Screenshots**
Falls relevant, Screenshot beifügen.

**Environment / verwendete Umgebung:**
 - OS / Betriebssystem:
 - j-lawyer.org Version:

**Additional context / Sonstiges**

**Comment by j-dimension** [comment]
Duplikat von #1225
