### ISSUE TITLE
Symbol für minderjähriges Kind - Geburtstag

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-org#1244]
Das Symbol für minderjähriges Kind ist gut. Es wäre schön, wenn daneben direkt das Geburtsdatum sichtbar wäre,

**NOTE: Please search existing tickets to avoid duplicates **
**HINWEIS: Bitte vorab die Ticketsuche verwenden, um Doppeleinträge zu vermeiden **

**Describe the tasks / Aufgabenbeschreibung**
(todo: a description of the task / eine Beschreibung der Aufgabe)

**Screenshots**
Falls relevant, Screenshot beifügen.

**Additional context / Sonstiges**

**Comment by stm9x9** [comment]
an welcher Stelle konkret? Vielleicht einen Screenshot machen und da die gewünschte Stelle markieren?

**Comment by Mucki526** [comment]
![grafik](https://user-images.githubusercontent.com/37142896/119269683-32e43700-bbf9-11eb-84c9-b931fffefcdb.png)
Zwischen 18 und Zeichenzeile (die sehr lang ist). Zeichenzeile etwas nach Rechts, Geburtsdatum zwischen U18 Grafik und Zeichen...

**Comment by stm9x9** [comment]
Welchen spezifischen Vorteil hat das denn bei Minderjährigen? Ggf würde ich es eher in den Tooltip beim Namen mit aufnehmen. Aber so richtig sehe ich den Mehrwert noch nicht. Braucht man das Datum so oft gleich auf die Schnelle in der Übersicht?

**Comment by j-dimension** [comment]
Die Prio ist aus meiner Sicht nicht so hoch, dass das Thema umgesetzt werden würde (i.Vgl. zu anderen Tickets). Ich schließe.
