### ISSUE TITLE
[adressen] mehrere Betreff-Felder zur Adresse

### ISSUE THREAD

**Issue by j-dimension** [jlawyerorg/j-lawyer-org#125]
mehrere Betrefffelder zur Adresse wären schön:
z.B.
Glasschaden = Feld 1
Ihre Schadennr.: 123456 = Feld 2
Schadenfall vom ...... = Feld 3

**Comment by librelegal** [comment]
Die Bezeichnung dieses issues sollte vereinheitlicht werden. Es geht um Adressen, deshalb "Adressen:" voranstellen. Außerdem war ein Tippfehler im Betreff.
Insgesamt wie nachstehend:
Adressen: mehrere Betreff-Felder zur Adresse
