### ISSUE TITLE
[BUG] Volltextsuche mag keine Schrägstriche ("/")

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#1250]
![image](https://user-images.githubusercontent.com/29924198/119674681-b0e45000-be3c-11eb-8b82-ca6b4a2f2f57.png)

ich wollte nach einem Aktenzeichen suchen, das in einer Akte in einem Text benannt worden sein müßte.  Bekam dann diese Fehlermeldung mit lexical error und EOF ...

**Comment by stm9x9** [comment]
kann das / nicht grundsätzlich nach Eingabe "maskiert" werden? Es muß ja nicht unbedingt ein Aktenzeichen sein, wonach man sucht (und dann auch nicht unbedingt eines im Format von jl sondern kann auch ein fremdes sein) sondern zb wenn ich weiß, in einer Akte hat ein Gegner ein Datum so geschrieben: 07/05/2020 oder ich suche nach "Kosten zu 2/3"

**Comment by j-dimension** [comment]
Maskieren geht an dieser Stelle m.W. nicht, ich muss das in Quotes nehmen. Nur kann der Code nicht wissen, ob nach
"Kosten zu 2/3"
oder
Kosten zu "2/3"
gesucht werden soll.

**Comment by stm9x9** [comment]
im Zweifelsfall nur die kleinste lexigraphische Einheit, also zwischen den nächstgelegenen Leerzeichen, in Quotes nehmen? wer tatsächlich nach genau der Phrase "Kosten zu 2/3" suchen will, der wird das dann auch so machen.
