### ISSUE TITLE
[beA] Adressen von nicht-beA-Teilnehmern im ERV werden nicht ausgegeben

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#1252]
Wenn ich im ERV-Adressbuch via beA-Schnittstelle suche, zb nach Agentur für Arbeit, dann wird diese zwar gefunden, aber die Adressfelder sind leer. 

![image](https://user-images.githubusercontent.com/29924198/119711039-57414d00-be5f-11eb-8e4a-d3ab56795d7d.png)

Wenn ich dasselbe in beA-web mache, dann sind da Daten:

![image](https://user-images.githubusercontent.com/29924198/119711052-5c9e9780-be5f-11eb-8551-71d995722b63.png)

Ich weiß natürlich nicht, ob jl hier die Daten nicht auswertet oder ob die KSW-Schnittstelle die Daten nicht liefert. 

teilweise werden auch Daten für Gerichte geliefert, teils nicht. 

![image](https://user-images.githubusercontent.com/29924198/119712042-79879a80-be60-11eb-902f-b05db501f7a7.png)

2 min später bei derselben Abfrage hat der Verwaltungsgerichtshof seine Daten verloren und das Bayrischer aus dem Vorname ist in den Nachnamen gerutscht!?

![image](https://user-images.githubusercontent.com/29924198/119712312-bf446300-be60-11eb-87ac-f3a7bb6dcefc.png)

**Comment by j-dimension** [comment]
Die Suche reicht die Daten aus der Schnittstelle 1:1 durch. Mal schauen ob ich ein System erkennen kann.

**Comment by j-dimension** [comment]
Ich hatte an der Stelle einen Workaround für einen Bug der Schnittstelle eingebaut. Und zwar gibt es verschiedene Wege an die Identitäten zu kommen, aber die unterschiedlichen Varianten liefern unterschiedliche Attribute, bspw. liefert die eine keine Emailadresse, die andere aber doch.

Der Wokaround geht nicht mehr, ich lasse mir ewas anderes einfallen.
