### ISSUE TITLE
Feature: HTML-Export mit Abbildung der Ordnerstruktur (entweder in der Index oder im eigentlichen Ordner "documents"

### ISSUE THREAD

**Issue by iradraconis** [jlawyerorg/j-lawyer-org#1253]
Es wäre toll, wenn die in der Akte angelegten Ordner ebenfalls exportiert würden, bzw. deren Inhalt sich nach dem Export in einem jeweiligen Unterordner wiederfindet. So lassen sich bei sehr umfangreichen Akten mit sehr vielen Unterordnern Dokumente viel leichter finden. So sortiere ich zum Beispiel in Strafsachen mit mehreren Verfahren die einzelnen Dokumente immer in Ordner zu ihrem jeweiligen Aktenzeichen. 
Wenn hingegen alles in einem Ordner gespeichert wird, macht es das Auffinden der Dateien schwieriger. Die HTML Index hilft da leider mir zumindest aktuell nicht viel weiter. Die ist viel zu unübersichtlich. Vielleicht kann auch dort die Darstellung etwas verbessert werden, das würde vielleicht schon etwas bringen. Im besten Fall kann der Nutzer vor dem Export die HTML mit einfachen Optionen anpassen. Ich zum Beispiel brauche nie das Feld "Schäden". Das könnte ja ausgeblendet werden. Nur so als Beispiel.

**Comment by Thorsten-Nutzer** [comment]
Ja, das unterstütze ich auch total, dabei habe ich folgenden Gedanken:

Wenn ich nur ein, zwei Akten mit in die Verhandlung nehmen will, müssen die irgendwie auf mein schlankes Notebook kommen. Der Weg über die Mobil-App wäre theoretisch machbar. Dann müßte ich aber ein Android-Emulator auf dem Notebook installieren. Das ist natürlich extrem umständlich gedacht. Einfacher wäre eine Art "Viewer" für einzelne exportierte Akten, vielleicht als Java-App, Plattformübergreifend.

Momentan liegen die exportierten Dateien ja ohne Struktur in einem Verzeichnis. Das ist natürlich auch schon ganz prima. Aber in der Nervosität der Verhandlung finde ich bei umfangreichen Akten da nichts mehr.

Zur Vorbereitung der Verhandlung könnte ich mir natürlich händisch einzelne Dateien in Ordner zusammenkopieren, aber das ist ja eine Arbeit, die es gerade zu vermeiden gilt.

Am einfachsten wäre tatsächlich, die Ordnerstruktur beim Export mit abzubilden. Dann kann ich offline mit meinem normalen Linux (oder jedem Browser) in der Verhandlung glänzen.

Liebe Grüße,
Thorsten

**Comment by Dickmaulruessler** [comment]
Export-Funktionen sind für uns generell von großem Interesse, sei es um die Akte selbst einmal (z.B. auf einem USB-Stick) mitzunehmen und unkompliziert auf einem beliebigen Gerät anzusehen oder um sie dem Mandanten übergeben zu können. 

Beide Varianten (HTML und PDF) haben ihre eigenen Vor- und Nachteile und werden wohl beide von Fall zu Fall benötigt. 

Je nach Aufwand wäre aber wohl eine Priorisierung nötig, oder @j-dimension ?
Ich persönlich würde jedenfalls der PDF-Verison aus #104 eindeutigem Vorrang geben wollen, welche auch einige optionale "Komfort-Funktionen" ermöglicht.
