### ISSUE TITLE
[adressen] Notizfeld zu einer Adresse

### ISSUE THREAD

**Issue by j-dimension** [jlawyerorg/j-lawyer-org#126]
Ebenfalls wäre ein Notizfeld zu einer Adresse schön, dass dann jedoch generell zu der Adresse verfügbar sein sollte.

**Comment by librelegal** [comment]
Die Bezeichnung dieses issues sollte vereinheitlicht werden. Es geht um Adressen, deshalb "Adressen:" voranstellen.
Insgesamt wie nachstehend:
Adressen: Notizfeld zu einer Adresse
