### ISSUE TITLE
[FEATURE] Wenn-/Dann-Funktion für Vorlagen (z. B. variable Bezeichnungen bei verschiedenen Geschlechtern)

### ISSUE THREAD

**Issue by socram70** [jlawyerorg/j-lawyer-org#1268]
Entsprechend diesen Foren-Posts wurde einmal von Jens darum gebeten, ein Ticket aufzumachen:
https://www.j-lawyer.org/?topic=bedingungen-wenn-dann-und-geschlechtsabhaengiger-text
Ich habe nach dem Ticket gesucht, aber nicht gefunden, finde das Feature aber ebenfalls sehr sinnvoll.

Somit hole ich hiermit das Ticket nach:

Folgendes ist gewünscht:
Abhängig vom Geschlecht, das beim Mandanten (oder sonstigen Beteiligten) in der Adressverwaltung ausgewählt ist, soll sich die Bezeichnung im Dokument ändern. Handelt es sich beispielsweise um eine weibliche Klägerin, so soll dort "Klägerin" im Rubrum und an sonstigen Stellen im Dokument auftauchen. Beim Männlichen Kläger "Kläger" usw.

**Comment by j-dimension** [comment]
Duplikat von #1078 - Kommentare gern dort rein.
