### ISSUE TITLE
Ablegen als PDF bei JPEG Dateien nicht möglich

### ISSUE THREAD

**Issue by iradraconis** [jlawyerorg/j-lawyer-org#1269]
Siehe Titel. Mandanten schicken Vollmacht etc. als Foto im Jpg Format. Das Foto wird dann gedreht abgespeichert bzw. dargestellt. Meine momentane Lösung: Öffnen in LibreOffice Draw, drehen, speichern als PDF, importieren in Akte (umständlich).

JPG Dateien lassen sich leider nicht als PDF ablegen. Dann kommt eine Fehlermeldung

**Comment by j-dimension** [comment]
> Das Foto wird dann gedreht abgespeichert bzw. dargestellt.

Das Foto wird original dargestellt. Es hat wahrscheinlich Metadaten, die die Ausrichtung überschreiben. Der Client wertet solche Metadaten aktuell nicht aus. Müsste hinzugefügt werden, bspw. wie hier (https://stackoverflow.com/questions/5905868/how-to-rotate-jpeg-images-based-on-the-orientation-metadata) beschrieben.

**Comment by j-dimension** [comment]
> JPG Dateien lassen sich leider nicht als PDF ablegen. Dann kommt eine Fehlermeldung

Funktioniert in meinen Testumgebungen. Wie lautet denn die Fehlermeldung?

**Comment by iradraconis** [comment]
> > JPG Dateien lassen sich leider nicht als PDF ablegen. Dann kommt eine Fehlermeldung
> 
> Funktioniert in meinen Testumgebungen. Wie lautet denn die Fehlermeldung?

Sorry, das betrifft nicht jpg-Dateien sondern jpeg Dateien. Manche Mandanten schicken Dateien mit dieser Dateiendung.

**Comment by j-dimension** [comment]
automatisches Drehen via separatem Ticket #1270

**Comment by stm9x9** [comment]
dieses Problem betrifft btw alle Aktionen wie Ablegen als ...
