### ISSUE TITLE
[BUG] Eingegebene Verkehrsunfalldaten werden nicht gespeichert

### ISSUE THREAD

**Issue by Linkki2021** [jlawyerorg/j-lawyer-org#1273]
Wir haben häufiger den Umstand, dass eingegebene Daten nicht gespeichert werden. Trotz Bestätigung über das Disketten-Symbol.

"Leider" (aus Problemeingrenzungssicht) passiert das nicht immer, weitere Einflussfaktoren konnten wir bislang nicht identifizieren.

Der Datenverlust tritt bei den Falldaten gehäuft auf, vereinzelt auch bei den Notizen in den allgemeinen Daten.

Gibt es dazu Ideen? Werden ggf. weitere Infos benötigt, die wir liefern können?

Vielen Dank.

**Comment by j-dimension** [comment]
Am besten mal ein client.log per E-Mail bereitstellen. 

https://www.j-lawyer.org/?topic=wo-findet-man-die-fehlerprotokolle-des-j-lawyer-org-servers-und-clients

**Comment by j-dimension** [comment]
Falls das Thema noch relevant ist, bitte ein client.log senden und das Ticket wieder öffnen - Danke!
