### ISSUE TITLE
[FEATURE] Urlaub eintragen können, auf den bei der Anlage von WV und/oder Frist hingewiesen wird

### ISSUE THREAD

**Issue by Maz111111** [jlawyerorg/j-lawyer-org#1274]
Es wäre ein nette Funktion, wenn man seinen Urlaub in jL hinterlegen könnte und jL auf diesen dann bei Anlegen einer Frist oder WV hinweist - wie er es auch bei den Feiertagen macht.

-------------------------------------------------------------------------
@j-dimension 2022-06-24

**Option 1**: alle überlappenden Termine mit dem selben Verantwortlichen anzeigen, Nutzer entscheiden lassen.
Bei Erstellung oder Änderung eines Kalendereintrages werden alle zeitlich überlappenden Einträge ermittelt und dem Anwender angezeigt. Rückfrage, ob trotzdem gespeichert werden soll oder nicht.

Pro: einfach umzusetzen
Con: evtl. viele sinnlose Rückfragen, bspw. wenn man sich für bestimmte Tage "Heimarbeit" ganztägig in den Kalender packt, darf dort ja trotzdem noch ein Telefonat terminiert werden. 

- [x] neuer Service zum Laden aller Kalendereinträge eines Verantwortlichen in einem bestimmten Zeitraum: 1,5h
- [x] neuer Dialog zur Anzeige der Kalendereinträge und Aufnahme von Nutzerinput ("trotzdem speichern?") mit Ergebnis ja/nein, Darstellung als Liste: 2,5h
- [x] Integrieren des neuen Dialogs - überall wo Termine **erstellt** werden (Versand beA-Nachricht, Versand E-Mail, Dokumenterstellung, Notizerstellung, in Akte, Duplizieren von Kalendereinträgen, Kalenderblatt): 2,25h
- [x] Integrieren des neuen Dialogs - überall wo Termine **bearbeitet** werden (Desktop, in Akte, Kalenderblatt): 0,5h
- [x] Tests: 0,75h
**gesamt: 7,5h**

**Comment by j-dimension** [comment]
Füge @ms00st als Beobachter hinzu

**Comment by j-dimension** [comment]
Alternative:
**Option 2**: Einführen von Kategorien. Alle überlappenden Termine mit dem selben Verantwortlichen anzeigen, Nutzer entscheiden lassen, wenn überlappende Termine involviert sind, die in Kategorien stecken, die keine Überlappung zulassen. 
Hier könnte man sich also Kategorien ("Urlaub", "Heimarbeit", "Telefonat", ...) konfigurieren und bei Erstellung / Änderung vergeben. Zusätzlich ließe sich konfigurieren, welche Kategorien keine Überlappung zulassen sollten.

Pro: weniger Rückfragen an den Nutzer
Con: relativ hoher Aufwand

- [ ] Datenmodellerweiterung: neue Datenbanktabelle für Kategorien von Kalendereinträgen (ID, Name, Anzeigefarbe, darf überlappen ja/nein): 1h
- [ ] Datenmodellerweiterung: Kategorie an Kalendereintrag: 0,75h
- [ ] neue Services zur Konfiguration der Kategorien: lesen, editieren, erstellen, löschen (mit Konfliktauflösung): 3,5h
- [ ] neuer Dialog zur Verwaltung der Kategorien: 3h
- [ ] Erweiterung der Anzeige: überall wo Kalendereinträge angezeigt werden, muss die Kategorie aufgenommen werden: 2,5h
- [ ] Sonderfall: Kategoriewechsel eines Kalendereintrages - kann dazu führen, dass ein Überlappen nicht mehr zulässig ist: 1,5h
- [ ] neuer Service zum Laden aller Kalendereinträge eines Verantwortlichen in einem bestimmten Zeitraum: 1,5h
- [ ] neuer Dialog zur Anzeige der Kalendereinträge und Aufnahme von Nutzerinput ("trotzdem speichern?") mit Ergebnis ja/nein, Berücksichtigung der (Un-)Zulässigkeit von Überlappungen je nach Kategorie, Darstellung als Liste: 3h
- [ ] Integrieren des neuen Dialogs - überall wo Termine **erstellt** werden (Versand beA-Nachricht, Versand E-Mail, Dokumenterstellung, Notizerstellung, in Akte, Duplizieren von Kalendereinträgen, Kalenderblatt): 2,25h
- [ ] Integrieren des neuen Dialogs - überall wo Termine **bearbeitet** werden (Desktop, in Akte, Kalenderblatt): 0,5h
- [ ] Tests: 2h
**gesamt: 21,5h**

**Comment by j-dimension** [comment]
@ms00st @Maz111111 ein paar Hinweise / Fragen bzgl. der Wertung als "Konflikt":

a) WV eintragen: wenn neue WV überlappt mit bestehender WV oder Frist = kein Problem
b) Frist eintragen: wenn neue Frist überlappt mit bestehender WV oder Frist = kein Problem
c) Termin eintragen: wenn neuer Termin überlappt mit bestehendem Termin = möglicherweise ein Problem --> anzeigen
d) Termin eintragen: wenn neuer Termin überlappt mit bestehender WV oder Frist = möglicherweise ein Problem --> anzeigen
e) WV eintragen: wenn neue WV überlappt mit bestehendem Termin = möglicherweise ein Problem --> anzeigen
f) Frist eintragen: wenn neue Frist überlappt mit bestehendem Termin = möglicherweise ein Problem --> anzeigen

d) und e) und f) könnte möglicherweise zu vielen ungewollten Konfliktanzeigen führen, wenn man einfach eine Mandantenbesprechung (Termin) an einem Tag einträgen möchte, wo es eine WV oder Frist gibt. Muss aber so gehandhabt werden, denn wenn es keine Mandantenbesprechung sondern ein Urlaub ist, dann muss es als Konflikt gewertet werden. Man könnte soetwas wie eine Logik einbauen wie "wenn Termin länger als 4h? dauert und mit WV oder Frist überlappt --> anzeigen". Das sollte die Anzahl der angezeigten Konflikte zumindest reduzieren.

Was meint Ihr?

**Comment by Dickmaulruessler** [comment]
> Man könnte soetwas wie eine Logik einbauen wie "wenn Termin länger als 4h? dauert und mit WV oder Frist überlappt --> anzeigen".

Wow, sehr pfiffig!

**Comment by ms00st** [comment]
Die Nutzung einer solchen Logik halte ich ebenfalls für sinnvoll.

**Comment by Maz111111** [comment]
In der Regel wird ein solcher Konflikt nur bei ganztägigen "Terminen" anzuzeigen sein.

Ich schlage vor, bei der Terminseintragung die Option ganztägig anzubieten mit dem Hinweis, dass nur dies zu Warnungen bzgl. WVs und Fristen führt.

Die angedachte Logik erscheint zweifelhaft. Termin länger als 4h ist ein Auswärtstermin, der in der Regel die Bearbeitung von Fristen und WVs an diesem Tag nicht hindern sollte.

Ist zumindest bei mir so.

Darüber hinaus ging es bei meinem Gedanken tatsächlich auch nur um Urlaubstage / Tage an denen man tatsächlich nicht arbeiten will. Insofern könnt e an auch schlicht den Kalendereintrag Urlaub / freier Tag zur Verfügung stellen. Wenn dies für einen Tag vom Nutzer eingestellt ist, werden für diesen Tag Warnungen angezeigt, die ggf. auch ignoriert werden können.

Ich glaube, Du machst es zu kompliziert.

Liebe Grüße

**Comment by j-dimension** [comment]
https://user-images.githubusercontent.com/3729754/180877259-b11a8a0e-7356-4396-92b9-df654f1aeb22.mp4

**Comment by j-dimension** [comment]
@ms00st @Maz111111 hab ein Video hinzugefügt. Bei Hinzufügen oder Ändern eines Termins - egal wo in der Anwendung - wird die Konfliktprüfung ausgeführt und bei möglichen Terminkonflikten ein grafisches Kalenderblatt angezeigt: die bestehenden Termine semitransparent, also weniger im Fokus, die Änderung (neuer oder geänderter Termin) nicht transparent. 

Nutzer kann sich entscheiden trotzdem zu speichern, da es durchaus vorkommen wird, dass die Konfliktprüfung zu pessimistisch ist :-)

**Comment by Maz111111** [comment]
Zunächst
Vielen Dank, lieber Jens für Deine Mühe und die Arbeit!!

In der Sache glaube ich aber, dass der von mir angeschobene Feature Wunsch nicht umgesetzt wurde. Ich weiß, dass es darauf nicht ankommt.
Wenn ich das richtig verstehe, muss der "Urlaub" aktenbezogen in  den Kalender eingetragen werden. Muss ich dann in jeder Akte, in der ich einen Hinweis erhalten möchte, "Urlaub" eintragen? Die Hinweise auf Sonn- und Feiertage haben Ihre Grundlage doch auch nicht in einem aktenbezogenen Kalender. Möglicherweise verweist Du jetzt auf eine OrgaAkte, die dann nebenbei gepflegt werden muss. Das fühlt sich für mich nach wie vor extrem unnatürlich an. Mein Urlaub ist kanzlei- und nicht aktenbezogen.
Ich konnte im Video jetzt nicht erkennen, was passiert, wenn in einer anderen Akte eine WV auf einen der Urlaubstage gelegt wird.
Ich hatte gemeint, dass man irgendwo in jL (nicht zwingend in einem Kalender) angeben kann, dass man von Tag, Uhrzeit bis Tag, Uhrzeit im Urlaub ist und jL dann beim Anlegen einer WV oder Frist in jeder Akte darauf hinweist (we bei den Feiertagen).

**Comment by j-dimension** [comment]
> Vielen Dank, lieber Jens für Deine Mühe und die Arbeit!!

Der konstruktive Einstieg verdient Anerkennung :-)

> In der Sache glaube ich aber, dass der von mir angeschobene Feature Wunsch nicht umgesetzt wurde. 

Warum? Die Urlaubswarnungen sind nun verfügbar, und darüber hinaus noch viel mehr, nämlich eine echte Terminkonfliktprüfung.

> Wenn ich das richtig verstehe, muss der "Urlaub" aktenbezogen in den Kalender eingetragen werden. Muss ich dann in jeder Akte, in der ich einen Hinweis erhalten möchte, "Urlaub" eintragen?

Nein, nur exakt einmal in einem Kalender.

> Die Hinweise auf Sonn- und Feiertage haben Ihre Grundlage doch auch nicht in einem aktenbezogenen Kalender.

Kein guter Vergleich. Sonn- und Feiertage haben alle Nutzer, Urlaub nur einer.

> Möglicherweise verweist Du jetzt auf eine OrgaAkte, die dann nebenbei gepflegt werden muss. Das fühlt sich für mich nach wie vor extrem unnatürlich an.

Rein rationale Entscheidung. Es gibt Kalenderfunktionalität. Wenn ich die jetzt an anderer Stelle nochmal entwickle, heisst das (1) Datenkbank erweitern, (2) Serveranwendung erweitern, um die Tabellen befüllen / bearbeiten zu können und (3) neue Dialoge und Einstellungen im Client. Alles für den sehr geringen Nutzen, keine Orga-Akte zu nutzen? Sorry, dafür ist mir meine Freizeit zu wertvoll.
Wie so oft gibt es für 20% des Aufwands eine 80%-Lösung, die restlichen 20% Funktionalität kosten 80% des Aufwands. 

> Mein Urlaub ist kanzlei- und nicht aktenbezogen.

Keineswegs. Der Urlaub ist nutzerbezogen. Warum sollte man das "global" hinterlegen, bspw. bei einer Bürogemeinschaft, wo sich der Kollege mal so gar nicht für den eigenen Urlaub interessiert? Mit der jetzigen Lösung hat jeder einen eigenen Kalender und die Zugriffe werden über Berechtigungen gepflegt. Die Terminkonfliktprüfung nutzt dann nur die Kalender, auf welche man auch Zugriff hat.

> Ich konnte im Video jetzt nicht erkennen, was passiert, wenn in einer anderen Akte eine WV auf einen der Urlaubstage gelegt wird.

Es erscheint ein Hinweis. Die Prüfung ist nicht auf einzelne Akten beschränkt.

> Ich hatte gemeint, dass man irgendwo in jL (nicht zwingend in einem Kalender) angeben kann, dass man von Tag, Uhrzeit bis Tag, Uhrzeit im Urlaub ist und jL dann beim Anlegen einer WV oder Frist in jeder Akte darauf hinweist (we bei den Feiertagen).

Das ist aber nicht zielführend (s.o.). Meine Aufgabe und Bestreben bestehen darin, Wünsche der Anwenderschaft so zu verallgemeinern dass ich mit einem bestmöglichen Kosten/Nutzen-Verhältnis eine Erweiterung für die größtmögliche Anwendergruppe bereitstellen kann. Genau das habe ich getan.

**Comment by Dickmaulruessler** [comment]
Merci Jens!

**Comment by Maz111111** [comment]
Nun gut.
Also muss jeder Nutzer seine eigene OrgaAkte anlegen und führen (oder verschiedene Funktionalitäten eben nicht nutzen).

Ok, message received. Werde ich mir überlegen.

Allein wäre noch die Frage, ob die Logik jetzt eingebaut ist oder nicht.

Im Video hast Du auf den 28. einen 2 Stunden Gerichtstermin angelegt und es poppte beim Versuch etwas auf den 28. zu verschieben die Konfliktwarnung auf. Das würde dannja auch bei jeder WV und Frist passieren, die ich auf den 28. lege.

Wie ich oben bereits schrieb hindert ein zwei Stunden Termin m.E. aber keine WV. 

Habe ich was missverstanden?

**Comment by iradraconis** [comment]
> Nun gut. Also muss jeder Nutzer seine eigene OrgaAkte anlegen und führen (oder verschiedene Funktionalitäten eben nicht nutzen).

Warum nicht eine Orga Akte für die gesamte Kanzlei? Dann sind alle Urlaube zentral einsehbar. Wer Urlaub hat, ist im Kalender anhand des "Verantwortlichen" zu sehen? Kann das Unbehagen hinsichtlich der durch Jens umgesetzten Implementierung nicht ganz nachvollziehen. Die Idee, Urlaub außerhalb eines Kalenders zu notieren, ist aus meiner Sicht "extrem unnatürlich".

**Comment by Maz111111** [comment]
> Warum nicht eine Orga Akte für die gesamte Kanzlei? Dann sind alle Urlaube zentral einsehbar. Wer Urlaub hat, ist im Kalender anhand des "Verantwortlichen" zu sehen? Kann das Unbehagen hinsichtlich der durch Jens umgesetzten Implementierung nicht ganz nachvollziehen. Die Idee, Urlaub außerhalb eines Kalenders zu notieren, ist aus meiner Sicht "extrem unnatürlich".

Dann dürfte aber bei jeder WV oder Frist, die irgendein Nutzer einträgt, eine Konfliktwarnung (um die es bei dem Ticket ja ursprünglich ging) erscheinen, die den Fristverantwortlichen gar nicht interessiert, weil es gar nicht sein Urlaub ist, auf den hingewiesen wird. 

Zumindest verstehe ich die Implementierung so. 

Ich habe meinen Post oben nochmal editiert.
