### ISSUE TITLE
Geburtstagseingabe

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-org#1276]
Wenn man den Geburtstag einer Person mit z.B. 21.01.21 (statt 2021) eingibt, wird von J-Lawyer völlig entspannt und ohne Warnung ein recht hohes Alter der Person mit 2000 Jahren angegeben. Besser wäre einfach, man könnte die Eingabe nicht abschließen, bis das Geburtsjahr vierstellig ist.

**Comment by j-dimension** [comment]
@Mucki526 , das ist ein Duplikat Deines eigenen(!) Tickets #1169 vom 16. März. Bitte nutzt vorab die Suche.
