### ISSUE TITLE
[FEATURE] Schnittstelle zur e.Consult RECHTSSCHUTZABWICKLUNG

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#1277]
Drebis hat leider bei weitem nicht alle Rechtsschutzversicherer in seinem System, so daß ich zusätzlich die kostenfreie https://www.e-consult.de/produkte/rechtsschutzabwicklung/ verwenden muß. Dort steht, daß sie auch eine Schnittstelle für KSW anbieten. Wäre als Ergänzung zu Drebis toll.

**Comment by stm9x9** [comment]
PS: ist nicht ganz so weitgehend wie #1104  - da geht es um eine komplette Integration der Webakte als Online-Akte in "Konkurrenz" zu der nextcloud-Integration

**Comment by j-dimension** [comment]
Das letzte mal als ich mit denen Kontakt hatte, war die Schnittstelle "Windows only". Vielleicht hat sich inzwischen etwas getan.

**Comment by stm9x9** [comment]
Ich bin am Nachfühlen.

**Comment by j-dimension** [comment]
ich warte noch auf das NDA, erst dann bekomme ich Details.

**Comment by j-dimension** [comment]
Wird aus Kostengründen nicht umgesetzt. (Nutzung der API kostet)
