### ISSUE TITLE
SIPGATE-Einstellungen für Easybell

### ISSUE THREAD

**Issue by MarcoWolny** [jlawyerorg/j-lawyer-org#1290]
Ich bin offensichtlich nicht in der Lage, meinen VoIP-Anbieter Easybell (https://www.easybell.de) in J-Lawyer einzubetten. 
Liegt das an mir, oder ist das nicht kompatibel?
Falls doch: Wo finden sich die entsprechenden Angaben, die ich bei J-Lawyer machen muss? Auf der Seite von Easybell finde ich nichts zu API-Endpunkt, SIP-Präfix oder SIP-Suffix pp.

**Comment by j-dimension** [comment]
Easybell hat/hatte keine Schnittstelle. Man kann es aber über ein sogenanntes Softphone einbinden:

http://www.j-lawyer.org/downloads/documentation/j-lawyer.org-UserGuide-de.html#__RefHeading___Toc7210_891333620

Am Nutzer dürfen dann KEINE Sipgate-Zugangsdaten eingetragen sein.
