### ISSUE TITLE
[BUG] Ladezeit in Aktensuche nach Etiketten sehr lang, wenn Berechtigungskonzept für viele Akten aktiv ist

### ISSUE THREAD

**Issue by iradraconis** [jlawyerorg/j-lawyer-org#1295]
Ich habe im System aktuell 732 Akten, 351 im Archiv, 7754 Adressen, 24.333 Dokumente. Also überschaubar meine ich. 

Wenn ich einschließlich der archivierten Dateien alle Dateien anzeigen lassen möchte, die das Etikett "HAFT" (egal welches) tragen, benötigt die Suche bei meinem letzten Versuch exakt 4:00 Minuten. Ohne die Einbeziehung der Archivierten sind es immerhin noch 2:52 Min. 

Das Suchen nach Akten mit bestimmtem Etikett ist so zumindest sehr zeitraubend. 

Der Server ist ein MacBook Pro aus 2018. 

Client Log schicke ich per Mail.

**Comment by j-dimension** [comment]
@iradraconis das ist mit großer Wahrscheinlichkeit kein Bug, sondern ein MySQL-Konfigurationsthema. 

Bitte mal im Terminal ausführen (Datenbankpasswort wird benötigt):

`/usr/local/mysql/bin/mysql -u root -p -e "show variables where variable_name like '%buffer%'"`

Ausgabe hier posten.

**Comment by iradraconis** [comment]
+-------------------------------------+----------------+
| Variable_name                       | Value          |
+-------------------------------------+----------------+
| bulk_insert_buffer_size             | 8388608        |
| innodb_buffer_pool_chunk_size       | 134217728      |
| innodb_buffer_pool_dump_at_shutdown | ON             |
| innodb_buffer_pool_dump_now         | OFF            |
| innodb_buffer_pool_dump_pct         | 25             |
| innodb_buffer_pool_filename         | ib_buffer_pool |
| innodb_buffer_pool_instances        | 1              |
| innodb_buffer_pool_load_abort       | OFF            |
| innodb_buffer_pool_load_at_startup  | ON             |
| innodb_buffer_pool_load_now         | OFF            |
| innodb_buffer_pool_size             | 134217728      |
| innodb_change_buffer_max_size       | 25             |
| innodb_change_buffering             | all            |
| innodb_log_buffer_size              | 16777216       |
| innodb_sort_buffer_size             | 1048576        |
| join_buffer_size                    | 262144         |
| key_buffer_size                     | 8388608        |
| myisam_sort_buffer_size             | 8388608        |
| net_buffer_length                   | 16384          |
| preload_buffer_size                 | 32768          |
| read_buffer_size                    | 131072         |
| read_rnd_buffer_size                | 262144         |
| sort_buffer_size                    | 262144         |
| sql_buffer_result                   | OFF            |
+-------------------------------------+----------------+

**Comment by j-dimension** [comment]
Dann bitte testweise

/usr/local/mysql/bin/mysql -u root -p -e "SET GLOBAL innodb_buffer_pool_size=268435456"

und erneut prüfen. Wenn das nicht hilft, muss auf die Indexe geschaut werden.

**Comment by iradraconis** [comment]
Hab ich gemacht. Die Suche dauert nun teilweise länger und mein Server (MacBook) ist während der Suche in den "Düsenbetrieb" übergegangen, was es vorher nicht gemacht hat.

**Comment by j-dimension** [comment]
teilweise länger = nicht besser, oder nur machmal länger?

Wieviel RAM hat das Gerät, und wie stark ist der ausgelastet?

**Comment by iradraconis** [comment]
Ich hatte die Stoppuhr mitlaufen lassen. Statt 2 Min. ohne Archivsuche waren es 3 Minuten. Die Suche mit Archiv dauerte auch 4 Minuten so wie vorher. Weitere Messungen habe ich nicht unternommen, weil mir das schlicht zu lange dauert :) 
Auf dem Server MacBook sind 8 GB Ram verbaut. Außer Anydesk sind dort keine Programme geöffnet. Auslastung gerade nachgeschaut: 
<img width="579" alt="Bildschirmfoto 2021-07-14 um 16 56 36" src="https://user-images.githubusercontent.com/71747937/125644556-72fb9304-006f-4b37-972b-cb614a8339ee.png">

**Comment by j-dimension** [comment]
Dann bitte das hier: 

`/usr/local/mysql/bin/mysql -u root -p -e "select distinct table_name, index_name from information_schema.statistics where table_schema='jlawyerdb'"`

**Comment by iradraconis** [comment]
Das Kommando hat die Zeit von 3 Minuten auf 2:45 reduziert. Meinst du es liegt an dem "schwachen" Server? Braucht der mehr RAM?

**Comment by j-dimension** [comment]
@iradraconis weiß ich noch nicht. Kann ich die Ausgabe von meinem letzten Kommentar (dem Befehl darin) haben?

**Comment by iradraconis** [comment]
ich habe das leider nicht gespeichert -.- und wenn ich den Befehl jetzt noch einmal ausführe, wird die Ausgabe nicht mehr angezeigt..

**Comment by iradraconis** [comment]
+----------------------------+-----------------------------------------+
| table_name                 | index_name                              |
+----------------------------+-----------------------------------------+
| campaign_contacts          | PRIMARY                                 |
| campaign_contacts          | IDX_CAMPAIGNADDRESSES_CAMPAIGNKEY       |
| campaign_contacts          | IDX_CAMPAIGNADDRESSES_ADDRESSKEY        |
| campaigns                  | PRIMARY                                 |
| case_contacts              | PRIMARY                                 |
| case_contacts              | IDX_ARCHIVEFILEKEY                      |
| case_contacts              | case_contacts_ibfk_2                    |
| case_contacts              | IDX_ARCHIVEFILEKEY_REFERENCETYPE        |
| case_contacts              | fk_reference_type                       |
| case_documents             | PRIMARY                                 |
| case_documents             | IDX_ARCHIVEFILEKEY                      |
| case_documents             | fk_case_documents_folder                |
| case_documents             | idx_case_documents_deleted              |
| case_folder_settings       | PRIMARY                                 |
| case_folder_settings       | idx_principal_folder_casefoldersettings |
| case_folder_settings       | folder                                  |
| case_folders               | PRIMARY                                 |
| case_folders               | idx_name_parentid_casefolders           |
| case_folders               | parent_id                               |
| case_followups             | PRIMARY                                 |
| case_followups             | IDX_DONE                                |
| case_followups             | IDX_REVDATE                             |
| case_followups             | IDX_ARCHIVEFILEKEY                      |
| case_followups             | IDX_REVTYPE                             |
| case_followups             | IDX_REVDATE_DONE                        |
| case_forms                 | PRIMARY                                 |
| case_forms                 | formtype                                |
| case_forms                 | case_id                                 |
| case_forms_entries         | PRIMARY                                 |
| case_forms_entries         | form_id                                 |
| case_forms_entries         | case_id                                 |
| case_groups                | PRIMARY                                 |
| case_groups                | group_id                                |
| case_groups                | case_id                                 |
| case_history               | PRIMARY                                 |
| case_history               | IDX_ARCHIVEFILEKEY                      |
| case_history               | IDX_PRINCIPAL                           |
| case_history               | IDX_CHANGEDATE                          |
| case_tags                  | PRIMARY                                 |
| case_tags                  | IDX_ARCHIVEFILEKEY_TAGNAME_UQ           |
| case_tags                  | IDX_TAGNAME                             |
| case_tags                  | IDX_ARCHIVEFILEKEY                      |
| case_tags                  | IDX_ARCHIVEFILEKEY_TAGNAME              |
| cases                      | PRIMARY                                 |
| cases                      | root_folder                             |
| cases                      | IDX_FILENUMBER                          |
| cases                      | IDX_NAME                                |
| cases                      | IDX_ARCHIVED                            |
| cases                      | IDX_REASON                              |
| cases                      | IDX_CASE_CUSTOM1                        |
| cases                      | IDX_CASE_CUSTOM2                        |
| cases                      | IDX_CASE_CUSTOM3                        |
| cases                      | IDX_ARCHIVEFILEBEAN_SUBJECTFIELD        |
| cases                      | fk_group                                |
| cases                      | IDX_CASES_FILENUMBEREXT                 |
| cases                      | fk_root_folder                          |
| communication_fax          | PRIMARY                                 |
| communication_fax          | IDX_ARCHIVEFILEKEY                      |
| communication_fax          | IDX_LASTSTATUS                          |
| contact_tags               | PRIMARY                                 |
| contact_tags               | IDX_ADDRESSKEY_TAGNAME_UQ               |
| contact_tags               | IDX_TAGNAME                             |
| contact_tags               | IDX_ADDRESSKEY                          |
| contact_tags               | IDX_ADDRESSKEY_TAGNAME                  |
| contacts                   | PRIMARY                                 |
| contacts                   | IDX_FIRSTNAME                           |
| contacts                   | IDX_NAME                                |
| contacts                   | IDX_COMPANY                             |
| contacts                   | IDX_ADDRESS_CUSTOM1                     |
| contacts                   | IDX_ADDRESS_CUSTOM2                     |
| contacts                   | IDX_ADDRESS_CUSTOM3                     |
| contacts                   | IDX_EMAIL                               |
| contacts                   | IDX_PHONE                               |
| contacts                   | IDX_MOBILE                              |
| contacts                   | IDX_BEASAFEID                           |
| contacts                   | IDX_CONTACTS_DEPARTMENT                 |
| contacts                   | IDX_CONTACTS_DISTRICT                   |
| contacts                   | IDX_CONTACTS_BIRTHNAME                  |
| contacts                   | IDX_CONTACTS_ZIPCODE                    |
| directory_banks            | PRIMARY                                 |
| directory_banks            | IDX_NAME                                |
| directory_banks            | IDX_BANKCODE                            |
| directory_cities           | PRIMARY                                 |
| directory_cities           | IDX_CITY                                |
| directory_cities           | IDX_ZIPCODE                             |
| document_folder_tpls       | PRIMARY                                 |
| document_folder_tpls       | name                                    |
| document_folder_tpls       | root_folder                             |
| document_folders           | PRIMARY                                 |
| document_folders           | idx_name_parentid_documentfolders       |
| document_folders           | parent_id                               |
| document_tags              | PRIMARY                                 |
| document_tags              | IDX_DOCUMENTKEY_TAGNAME_UQ              |
| document_tags              | IDX_TAGNAME                             |
| document_tags              | IDX_DOCUMENTKEY                         |
| document_tags              | IDX_DOCUMENTKEY_TAGNAME                 |
| flyway_schema_history      | PRIMARY                                 |
| flyway_schema_history      | flyway_schema_history_s_idx             |
| form_types                 | PRIMARY                                 |
| form_types                 | name                                    |
| form_types                 | placeholder                             |
| form_types_artefacts       | PRIMARY                                 |
| form_types_artefacts       | formtype                                |
| party_types                | PRIMARY                                 |
| party_types                | name                                    |
| security_group_memberships | PRIMARY                                 |
| security_group_memberships | principal_id                            |
| security_group_memberships | group_id                                |
| security_groups            | PRIMARY                                 |
| security_groups            | name                                    |
| security_groups            | abbreviation                            |
| security_roles             | PRIMARY                                 |
| security_users             | PRIMARY                                 |
| security_users             | fk_primary_group                        |
| server_options             | PRIMARY                                 |
| server_options             | IDX_OPTIONGROUP                         |
| server_settings            | PRIMARY                                 |
+----------------------------+-----------------------------------------+

**Comment by j-dimension** [comment]
Da fehlt ein Index. Nutzt Ihr das Berechtigungssystem? (Akten haben Eigentümer und - optional - Berechtigte)

**Comment by iradraconis** [comment]
Ja wir nutzen das System mit Berechtigungen. Bei jeder Akte ist ein Eigentümer, und auch eine Gruppe gesetzt.

**Comment by j-dimension** [comment]
Okay, dann habe ich einen Ansatz. Ich habe in einer Instanz mit 

465 Akten
10 650 Dokumenten

Antwortzeiten von ca. 12  Sekunden, wenn ich für alle Akten Berechtigungen hinterlege. Der Unterschied zu Deiner Installation erscheint mir zu groß, wahrscheinlich spielen da noch andere Faktoren mit rein. 

Ich werde aber in der 1.15 die Prüfung der Berechtigungen anders umsetzen.
