### ISSUE TITLE
[BUG] Berechnung Anwaltskosten Verkehrsunfalldaten fehlerhaft

### ISSUE THREAD

**Issue by Linkki2021** [jlawyerorg/j-lawyer-org#1296]
Hier scheint es einen Berechnungsfehler zu geben. Für die unterste RVG-Stufe (bis 500€ Gegenstandswert) werden mE nicht 12,74€ Auslagen VV7002 hinzugerechnet, sondern 20€ (was ab 501€ gilt). Dadurch bleibt immer ein Saldo, siehe Screenshot. Ggf. kann das mal geprüft werden, auch ob es noch andere Falldaten betrifft.

Im RVG-Plugin-Rechner passt alles.

![image](https://user-images.githubusercontent.com/77149788/125613833-6fc59adc-c41a-4f73-8b45-9ab2bbeee817.png)

**Comment by j-dimension** [comment]
Hallo @Linkki2021 , das ist ein Duplikat von https://github.com/jlawyerorg/j-lawyer-forms/issues/65

Dieses Ticket habe ich bereits eingeplant.

**Comment by Linkki2021** [comment]
Sorry, mein Fehler. Ich dachte auch, dass ich es bereits gemeldet hatte, habe es aber nicht gefunden und dachte dann, dass ich es vertrödelt habe... Kommt (hoffentlich) nicht wieder vor ;)
