### ISSUE TITLE
[e-mail] Antwort / Weiterleitung: Ordner für gesendete Nachricht beibehalten 

### ISSUE THREAD

**Issue by j-dimension** [jlawyerorg/j-lawyer-org#1297]
Wird eine E-Mail aus einem Unterordner weitergeleitet oder beantwortet, so sollte die gesendete Nachricht (sofern sie gespeichert wird) ebenfalls in diesem Ordner landen.

**Comment by stm9x9** [comment]
dann scheint mir das beim Beantworten sinnvoll, aber nicht zwingend beim Weiterleiten? Man leitet ja normalerweise an wen anders weiter. Also wenn ich zb eine Mail im Aktenordner "Korrespondenz Gegner" an meinen Mandanten weiterleite, dann gehört diese Weiterleitung ja nicht in "Korrespondenz Gegner" sondern  "Korrespondenz Mdt"

**Comment by j-dimension** [comment]
Dup von #1487
