### ISSUE TITLE
[FEATURE] automatisches Reconnect des SSH-Tunnels

### ISSUE THREAD

**Issue by j-dimension** [jlawyerorg/j-lawyer-org#1300]
bspw. nach Standby des Laptops

**Comment by PBaumfalk** [comment]
Das ist ganz wichtig. Jedes Mal bei Gericht eine Katastrophe :-(

Mit freundlichen Grüßen / Kindly Regards

Patrick Baumfalk
Rechtsanwalt / Lawyer


Mobil:    +49 1525 53 04 194
E-Mail:   ***@***.***


Baumfalk - Rechtsanwaltskanzlei
Hauptstr. 195
50169 Kerpen

Tel.: +49 2273 40 68 504
Fax: +49 2273 59 03 565

E-Mail: ***@***.***
Web: www.kanzlei-baumfalk.de

Sent by Mobile

**Comment by j-dimension** [comment]
session#isConnected prüfen?
