### ISSUE TITLE
[FEATURE] Etiketten mit individuellen Farben (oder Farbgruppen) versehen

### ISSUE THREAD

**Issue by ReRo-G** [jlawyerorg/j-lawyer-org#1308]
**Welches Problem soll durch die Erweiterung / Verbesserung gelöst werden?**
Unübersichtliche Lage bei vielen Etiketten.
Ich nutze die Etiketten nach Gruppen, welche sich durch die erste Zahl unterscheiden, wie es ein anderer Nutzer mal vorschlug. Bsp.: Gruppe 1: Abrechnung --> 1.1 OPOS, 1.2 RVG, 1.3 Vergütungsvereinbarung ... etc.

**Beschreibe die gewünschte Lösung**
Es wäre klasse, wenn man den Etiketten der jeweiligen Gruppen unterschiedliche Farben zuordnen könnte (Etikett x hätte dann global immer die selbe Farbe).

**Comment by j-dimension** [comment]
Duplikat von #69
