### ISSUE TITLE
[BUG] Volltextsuche findet nicht (mehr) existente Darei

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#1316]
ich habe nach was gesucht und wollte eine der gefundenen Dateien öffnen. Ging nicht:

![image](https://user-images.githubusercontent.com/29924198/130154599-3d9f3a87-da4a-4235-9b28-d715d0b3b1c3.png)

In der Akte nachgeguckt: gibt es wirklich nicht (ggf mehr). Auch im Papierkorb war nichts.

kein Eintrag im client.log

**Comment by j-dimension** [comment]
Über die Einstellungen mal den Index neu erfassen.

**Comment by stm9x9** [comment]
> Über die Einstellungen mal den Index neu erfassen.

Hat geholfen! :-)

Muß man das denn regelmäßig machen?

Und ist es normal, daß nicht alle Dateien indiziert werden?

![image](https://user-images.githubusercontent.com/29924198/130472612-2e9cf075-6c2a-4e0b-9c0b-d2772a857d29.png)

**Comment by j-dimension** [comment]
Eigentlich nur in Ausnahmefällen notwendig, bspw. wenn der Serverdienst mal nicht sauber beendet wurde.

Indexiert werden nur Dokumente, die textuelle Informationen haben.

**Comment by Dickmaulruessler** [comment]
Bei mir (noch kleine Datenbank) war das auch einmal erforderlich. Problem: Bis man den Fehler analysiert hat, erhält man nicht korrekte oder lückenhafte Suchergebnisse. 
Macht es evtl. Sinn, dass der Index im Hintergrund oder in Zeiten der Nicht-Nutzung ab und an automatisch überprüft wird? Evtl. planbar einmal pro Monat für die Nacht? 
Ich weiß nicht, wieviel Ressourcen der Neuaufbau den Indexes benötigt.

Eine gute Volltextsuche ist jedenfalls sehr sehr wichtig... Ich suche häufig irgendetwas. Häufig ist mir der Aktenname dann nicht mehr bekannt, sondern z.B. nur ein Stichwort zu einem rechtlichen Problem...

**Comment by j-dimension** [comment]
Letzlich sollte das nur in Ausnahmefällen notwendig sein. 

> Ich weiß nicht, wieviel Ressourcen der Neuaufbau des Indexes benötigt.

Das ist stark abhängig von der kumulierten Größe der Dokumente. Insbesondere im Strafrecht mit den riesigen PDFs kann das sehr lange dauern und den Server stressen. Bei einer Installation mit ca. 100GB an Dokumenten kann das locker auch 4-5 Stunden dauern.
