### ISSUE TITLE
REST API: Contact-Anlage nicht alle Felder unterstützt?

### ISSUE THREAD

**Issue by LazyGuy21No** [jlawyerorg/j-lawyer-org#1320]
Wenn wir über die API einen Contact anlegen, können wir anscheinend nicht alle Felder befüllen:
`/v1/contacts/create
`
scheint z.B. kein Feld "gender" zu haben. Ein anschließendes Update mittels
`/v2/contacts/update
`
funktioniert. Soll das so oder sind wir einfach zu blöd?

**Comment by GuidoBo** [comment]
Hier fehlte z.B. die Info zu /v2/contacts/create

**Comment by j-dimension** [comment]
Die /v2/contacts/create ist ja auch in der Swagger UI zu finden. Grundsätzlich kann man wie folgt vorgehen: man nutzt die höchste Version der API, also bspw. /v2/...
Vermisst man dort einen Endpunkt, schaut man in der Vorgängerversion etc.

**Comment by j-dimension** [comment]
> Stimmt das, oder habe ich das übersehen?

Das stimmt.

**Comment by iradraconis** [comment]
ok, danke! :)
