### ISSUE TITLE
[FEATURE] Button: Adresse als Block kopieren und Link zu OSM anzeigen

### ISSUE THREAD

**Issue by GuidoBo** [jlawyerorg/j-lawyer-org#1326]
Wenn mal ganz viel Zeit ist: 

In der Personenansicht, Reiter Adresse: Es wäre total toll, wenn wir eine Möglichkeit hätten

1. Die Adresse einer Person im Format
Prof. Dr. Steffanie Maier, LL.M., M.B.A
Beispielstraße 27, 10012 Beispielstadt

(evtl. per Button/Dropdown) in die Zwischenablage zu kopieren (z.B. f. Zeugen) und

2. wenn wir einen Button in der Personenansicht hätten, die entsprechende Adresse auf Googlemaps/Open Street Map nachzuschlagen.

**Comment by j-dimension** [comment]
Zu (1) - es gibt den Button hinter der Hausnummer - ist das bereits die gewünschte Funktionalität?

(2) ist ein Duplikat von https://github.com/jlawyerorg/j-lawyer-org/issues/902

**Comment by GuidoBo** [comment]
Ja, tut es; vielen Dank!
