### ISSUE TITLE
[BUG] Änderungen an Notiz-Dokumenten gehen verloren

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#1328]
Ich hatte gestern eine Notiz erstellt. Die habe ich dann Stunden später direkt im Fenster rechts ergänzt. Dann bin ich raus aus der Akte. jl fragt mich noch ab es Änderungen speichern solle. (OK das fragt jl ja aktuell immer, egal ob was zu speichern ist. Aber das ist ja ein anderes Ticket). Ich klickte ja. Als ich in die Akte zurückging: Alle Änderungen an der Notiz waren weg! 8-o Da entdeckte ich dann das kleine Disketten-Icon oben links ...

![image](https://user-images.githubusercontent.com/29924198/132713587-e6a324dd-46dd-4135-a881-10a70246f0d5.png)

Es zeigte sich dann, daß Änderungen auch dann verloren sind, wenn man in der Akte bleibt, aber ein anderes Dokument öffnet.

Vorschlag: 1) Die Speicher-Abfrage beim Verlassen der Akte sollte eine Notiz auch mitspeichern, wenn man auf ja klickt.
sowie 2) Wenn man aus einer veränderten Notiz raus geht, anderer Tab, anderes Dokument ... dann sollte auch eine Sicherheitsabfrage kommen, ob man die Änderungen an der Notiz speichern will.

Jedenfalls ist es gefährlich, sich darauf zu verlassen, daß der Nutzer schon das Save-Icon klicken wird und ansonsten kommentarlos jede Änderung einfach zu verwerfen.

**Comment by j-dimension** [comment]
Duplikat von #783
