### ISSUE TITLE
[BUG] bea-lock-Datei und verwaiste jl-Instanz (Windows)

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#1329]
Ist mir jetzt ein paar Mal passiert:

Windows-Rechner aus Ruhezustand geweckt. jl neu gestartet. Jetzt komme ich nicht ins beA rein, da beA laut lock-Datei von einer anderen Instanz benutzt wird. Aktuelle jl-Instanz geschlossen. Dennoch kann ich die lock-Datei nicht löschen:

![image](https://user-images.githubusercontent.com/29924198/133121941-e3a98205-a780-4a49-9014-34c5cd40ae01.png)

Im Taskmanager finde ich dann noch eine verwaiste jl-Instanz. Nach dem Abschießen kann ich auch die lock-Datei löschen.

Merkwürdigerweise ist die lock-Datei sogar vom 10.9. Ich kann nicht mit Sicherheit sagen, ob ich am Wochenende in beA drin war.

**Comment by j-dimension** [comment]
Duplikat von #1239
