### ISSUE TITLE
[FEATURE] Dateien auch wahlweise mit alternativen Programmen öffnen können

### ISSUE THREAD

**Issue by iradraconis** [jlawyerorg/j-lawyer-org#1345]
Momentan gilt, dass Dateien entweder mit dem systemeigenen Standard Programm geöffnet werden, mit einem für die Dateiendung eigens durch den Nutzer benannten Programm oder aber durch Word/Libreoffice.

Gerade bei PDF Dateien würde ich mir eine zusätzliche Option wünschen, die aber nicht generell für PDF gelten muss, sondern einfach eine nutzerspezifische Programmauswahl ermöglichen sollte.

Beispiel: PDF Dateien lesen standardmäßig durch PDF Reader, aber PDF Dateien bearbeiten durch spezialisierte Programme (Linux: PDF Arranger oder PDF Slicer). Ich weiß, dass PDF Dateien auch mit Libreoffice Draw geöffnet und bearbeitet werden können, ABER dabei geht manchmal die Formatierung verloren, wenn Draw eine Textelemente versucht, als Text darzustellen.

**Comment by Thorsten-usr** [comment]
Ja, ich unterstütze diese Bitte, weil ich das auch so brauche. Ein schnelles Re-Arrangieren von Pdfs geht sehr gut mit Pdf-Arranger, zum lesen taugt der aber nicht. 
Danke!

**Comment by iradraconis** [comment]
Und mit diesem Feature könnte man auch pdf Dateien mit einem ocr Tool öffnen und lesbar machen. :) ich weiß, dass es ein eigenes Ticket zu ocr gibt aber mit diesem hier wären mehrere Fliegen mit einer Klappe und so ;)

**Comment by j-dimension** [comment]
@iradraconis das sollte mit 2.1 abgedeckt sein. Wenn Du noch etwas vermisst, bitte wieder aufmachen.

**Comment by j-dimension** [comment]
siehe #1568
