### ISSUE TITLE
[BUG] an Client 1 gespeicherte Emails führen zu "Teilabsturz" bei Client 2 

### ISSUE THREAD

**Issue by iradraconis** [jlawyerorg/j-lawyer-org#1347]
Hintergrund:
Ich speichere an meinem Rechner eine Email in eine Akte. Meine Mitarbeiterin am anderen Client kann die Datei aber nicht löschen oder sonst was mit ihr machen. Sobald sie mit rechter Maustaste die Datei anklickt, öffnet sich für einen Bruchteil einer Sekunde das Kontextmenü und verschwindet dann sofort wieder. Ist das ein Rechteproblem? Auf meinem Client kann ich die Datei wie gewohnt benutzen. 

Mein Client ist Linux, der Client meiner Mitarbeiterin MacOS. 

Client: 1.14.1.0

**Comment by j-dimension** [comment]
> Ich speichere an meinem Rechner eine Email in eine Akte. 

Wird sie dabei aus dem Posteingang gelöscht?

> Meine Mitarbeiterin am anderen Client kann die Datei aber nicht löschen oder sonst was mit ihr machen. Sobald sie mit rechter Maustaste die Datei anklickt, öffnet sich für einen Bruchteil einer Sekunde das Kontextmenü und verschwindet dann sofort wieder.

Bezieht sich das auf Aktionen innerhalb des Posteingangs der der Akte?

**Comment by iradraconis** [comment]
> > Ich speichere an meinem Rechner eine Email in eine Akte.
> 
> Wird sie dabei aus dem Posteingang gelöscht?
=> nein

> > Meine Mitarbeiterin am anderen Client kann die Datei aber nicht löschen oder sonst was mit ihr machen. Sobald sie mit rechter Maustaste die Datei anklickt, öffnet sich für einen Bruchteil einer Sekunde das Kontextmenü und verschwindet dann sofort wieder.
> 
> Bezieht sich das auf Aktionen innerhalb des Posteingangs der der Akte?
=> ja

**Comment by j-dimension** [comment]
Ist das konsistent reproduzierbar oder ggf. nur eine zeitliche Koinzidenz?

Kann ich das client.log der Main und eine Zeit haben, zu welcher das aufgetreten ist?

**Comment by j-dimension** [comment]
Ah, hab das Log.

**Comment by j-dimension** [comment]
Bekomme das nicht reproduziert.

@stm9x9 @GuidoBo habt Ihr das schon mal beobachtet?

@iradraconis ggf. auch mal in der Mailingliste posten.

**Comment by GuidoBo** [comment]
Gelegentlich ist der Mail-Client wohl mal sehr laaaaaangsam, aber das kennen wir so nicht.
