### ISSUE TITLE
[TASK] [adressen] Struktur der beiden ersten Reiter unter "Adresse" überdenken

### ISSUE THREAD

**Issue by Dickmaulruessler** [jlawyerorg/j-lawyer-org#1348]
Ich möchte zur Diskussion stellen, ob die beiden Reiter "Grunddaten" und "Kontakt" neu strukturiert werden sollten. 

Nach meinem Dafürhalten müssen Name, Adresse, Tel, Fax und E-Mail und ein Notizfeld zusammen und auf dem ersten Reiter sein, **da sie immer und von jedem benötigt werden.** 
Dass die Kontaktangaben erst auf dem zweiten Reiter sind - und damit auch nicht mit dem ersten Klick - empfinde ich als unglücklich. 

Derzeit befinden sich auf dem ersten Reiter unzählig viele Details (alles unter dem Vornmanen) die mancher möglicherweise braucht, die Masse aber sicherlich nicht. Das könnte auf den zweiten Reiter. 

_(Anlass dieser Anregung ist Folgendes: Ich kopiere sehr häufig Adressen aus dem Internet und füge diesen dann als Kontakt ein (in meinem Fall Pflegeheime, Pflegedienste, Soziale Dienste, Krankenhäuser...). Unter Outlook hatte ich das immer in das Notizfeld eingefügt und dann mit copy&paste in die entsprechenden Spalten Straße, Ort, Tel.... geschoben. Das geht hier nicht, da Notizfeld und Kontaktdaten sich auf verschiedenen Reitern befinden und bei Kontaktdaten auch nicht ein einziges vierzeiliges Feld vorhanden ist, wo man das provisorisch für diesen Zweck hinschieben könnte. 
In der "Schnellerfassung" unter "Beteiligte" ist all dies auch zusammen in einem Fenster. Dort fehlt aber ein (kleines) mind. 4 zeiliges Notizfeld.
**Wie fügen andere Kollegen Kontaktdaten ein, die sie aus dem Netz kopiert haben? Oder Jens, hast du einen Tipp für dieses Anliegen?** Einzeln rüberkopieren ist nervig, Abtippen ebenso...
Meine obige Anregung für die Neustrukturierung würde dieses Problem mit dem Copy&Paste lösen. Ich würde die Neustrukturierung aber auch losgelöst davon anregen wollen, da es dann irgendwie "logischer" wäre und das Wichtigste einen Reiter weiter nach Vorne kommen würde)_

**Comment by j-dimension** [comment]
Layoutänderung schaue ich mir an.

Das Einfügen wäre irgendwie am besten wenn man einfach etwas aus der Zwischenablage in die Anwendung einfügen könnte und diese das dann irgendwie intelligtent auseinandernimmt und auf die Fehler verteilt.

**Comment by iradraconis** [comment]
> Ich möchte zur Diskussion stellen, ob die beiden Reiter "Grunddaten" und "Kontakt" neu strukturiert werden sollten.
> 
> Nach meinem Dafürhalten müssen Name, Adresse, Tel, Fax und E-Mail und ein Notizfeld zusammen und auf dem ersten Reiter sein, **da sie immer und von jedem benötigt werden.** Dass die Kontaktangaben erst auf dem zweiten Reiter sind - und damit auch nicht mit dem ersten Klick - empfinde ich als unglücklich.
> 
> Derzeit befinden sich auf dem ersten Reiter unzählig viele Details (alles unter dem Vornmanen) die mancher möglicherweise braucht, die Masse aber sicherlich nicht. Das könnte auf den zweiten Reiter.
> 
> _(Anlass dieser Anregung ist Folgendes: Ich kopiere sehr häufig Adressen aus dem Internet und füge diesen dann als Kontakt ein (in meinem Fall Pflegeheime, Pflegedienste, Soziale Dienste, Krankenhäuser...). Unter Outlook hatte ich das immer in das Notizfeld eingefügt und dann mit copy&paste in die entsprechenden Spalten Straße, Ort, Tel.... geschoben. Das geht hier nicht, da Notizfeld und Kontaktdaten sich auf verschiedenen Reitern befinden und bei Kontaktdaten auch nicht ein einziges vierzeiliges Feld vorhanden ist, wo man das provisorisch für diesen Zweck hinschieben könnte. In der "Schnellerfassung" unter "Beteiligte" ist all dies auch zusammen in einem Fenster. Dort fehlt aber ein (kleines) mind. 4 zeiliges Notizfeld. **Wie fügen andere Kollegen Kontaktdaten ein, die sie aus dem Netz kopiert haben? Oder Jens, hast du einen Tipp für dieses Anliegen?** Einzeln rüberkopieren ist nervig, Abtippen ebenso... Meine obige Anregung für die Neustrukturierung würde dieses Problem mit dem Copy&Paste lösen. Ich würde die Neustrukturierung aber auch losgelöst davon anregen wollen, da es dann irgendwie "logischer" wäre und das Wichtigste einen Reiter weiter nach Vorne kommen würde)_

Ich möchte mich dem Wunsch nach einer Layoutänderung anschließen. Ich empfinde das momentan auch als umständlich bzw. die am häufigsten benötigten Informationen sind unnötig weit verteilt.

**Comment by stm9x9** [comment]
mir scheint, selbst wenn ich das Programmfenster recht klein ziehe, dann sind die ganzen Eingabefelder einfach wahnsinnig lang.
Mir scheint, man könnte eigentlich alles aus dem Reiter Kontakt auf den ersten Reiter ziehen.

![image](https://user-images.githubusercontent.com/29924198/135670514-73a1d856-c5f3-4ba3-96d8-4e8ea0d35293.png)

Alles aus Adresse dann rechts in den roten Kasten und alles aus Kontakt unterhalb von juristische Person.

**Comment by j-dimension** [comment]
Das Video zeigt die Layoutänderungen sowie das geführte Erstellen von Daten aus der Zwischenablage (bspw. Signatur oder Impressum).

**Comment by Dickmaulruessler** [comment]
cooles feature! Gute neue Struktur!
