### ISSUE TITLE
[BUG] Fehlermeldung Installation 2.0.0.3

### ISSUE THREAD

**Issue by Dickmaulruessler** [jlawyerorg/j-lawyer-org#1350]
Client fehlerfrei
Server unten stehende Fehlermeldung. Nach "OK" läuft dann alles problemlos durch. Ein tatsächlich Netzwerkproblem gab es soweit ersichtlich nicht. 
Win x64
![jl](https://user-images.githubusercontent.com/46451749/135731847-0972c0a9-9cee-439f-beb2-ca4e6ecae050.jpg)

**Comment by j-dimension** [comment]
Keine weiteren Rückmeldungen hierzu, und ich kann es nicht reproduzieren :-(

Schließe erstmal.

**Comment by Dickmaulruessler** [comment]
Der Fehler trat nur in meiner Testumgebung zu Hause auf. Das war die Installation, die schon "irgendwie komisch" war, da ich dort in der Vergangenheit etwas wild heruminstalliert hatte und an der du deshalb später auch schon einmal mit Fernwartung dran warst....

In der Kanzlei lief alles schnell und fehlerfrei ab.
