### ISSUE TITLE
[FEATURE] Platzhalter aus Falldaten in Mails verwenden

### ISSUE THREAD

**Issue by Linkki2021** [jlawyerorg/j-lawyer-org#1354]
Ist mE derzeit nicht möglich, zumindest funktioniert es bei mir nicht.

Könnte hilfreiche sein.

**Comment by j-dimension** [comment]
In der Tat aktuell nicht unterstützt.

**Comment by Linkki2021** [comment]
Stehe ich gerade auf dem Schlauch, oder gibt es das nicht seit der 2.2? :)

**Comment by j-dimension** [comment]
Ähmmm. Da ist mir ein Duplikat durchgegangen. Du hast völlig recht. 

Geliefert mit #1758
