### ISSUE TITLE
[TASK] in Akte speichern - Sortierung der Ordner

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#1356]
![image](https://user-images.githubusercontent.com/29924198/136280659-5388dbd4-09f0-4dd2-8bb2-30ab11870f97.png)

mir fiel gerade auf, daß die Ordner nicht - wie in der Akte - alphanummerisch sortiert sind sondern ... irgendwie anders. Es erleichtert den Arbeitsfluß, wenn das auch hier wie üblich sortiert werden würde

**Comment by j-dimension** [comment]
Bereits behoben - schließe Ticket.
