### ISSUE TITLE
[FEATURE] [kalender] Termin im Kalenderblatt eintragen

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#1357]
Wenn man einen Termin vergeben will für einen Mandanten und dafür im Kalenderblatt guckt, wann was frei ist: Da wäre es toll, wenn man dort direkt einen Termin eingeben könnte.

Ich stelle mir das so vor: man klickt auf einen Zeitpunkt im Kalender oder auf ein + Symbol. Dann kommt das bekannte Fristen/Termine-Fenster, wo aber nur Termine ausgewählt werden kann. Dafür gibt es zusätzlich oder vorher eine Aktensuche, so daß man den Termin einer Akte zuordnet und dort einträgt.

**Comment by iradraconis** [comment]
Ist die Planung für 2.1 unumstößlich? 😀 das wäre noch ein Killerfeature für die 2.0 um nicht zu sagen, das Schließen einer funktionalen Lücke.

**Comment by j-dimension** [comment]
Leider absolut ausgeschlossen, die 2.0 zu erweitern. Ich hab so schon Bammel das alles bis kurz vor Ende Oktober fertig zu bekommen.

**Comment by mmellenthin** [comment]
Bitte in der 2.1 auch Termine ohne Aktenzuordnung ermöglichen. 
Dies wird benötigt für Wiedervorlagen und Fristen des Altbestandes sowie Neumandate.

**Comment by j-dimension** [comment]
> Bitte in der 2.1 auch Termine ohne Aktenzuordnung ermöglichen.

Die konkrete Planung liegt bei mir, es sei denn man sponsort ein Feature. Ich versuche die Prioritäten der Anwender aber natürlich immer zu treffen. 

Zum Jahreswechsel steht ein RIESEN-Update im ERV an, ich bin nicht sich ob dieses Feature hier in die 2.1 reinpasst. 

Außerdem muss unterschieden werden zwischen diesem Ticket (Eingabe über Kalenderblatt, aber mit Aktenbezug - überschaubarer Aufwand) und dem Wunsch, Termine ohne Aktenbezug eingeben zu können (wäre neues Ticket, großer Aufwand). Letzteres lässt sich auch einfach mit einer jahresweise genutzten Orga-Akte für die ganze Kanzlei abbilden.

**Comment by Dickmaulruessler** [comment]
> 
> Die konkrete Planung liegt bei mir
> 

Jo!

> 
> Letzteres lässt sich auch einfach mit einer jahresweise genutzten Orga-Akte für die ganze Kanzlei abbilden.

Ich benötige diese Funktion nicht. Aber für all diejenigen, die das vermissen, vielleicht eine ausführlichere Erklärung:

Du legst eine Akte an (die z.B. "Orga-Akte" oder "WV Altbestand" "Fristen Altbestand" heißt) und die allein den Zweck erfüllt über diese ALLE anderen Termine ohne tatsächlichem Aktenbezug einzutragen. Das ist ungewöhnlich, funktioniert aber gut. 

Für Neumandate kann dann gleich eine neue Akte angelegt werden aus der heraus du dann Termine einträgst. Falls du Neumandate aus irgendwelchen Gründen anders als schon länger laufende Mandate handhaben möchtest, kannst du ein entsprechendes Ettikett "Neumandat" vergeben. 

@mmellenthin probiere es doch einmal aus :-)

**Comment by iradraconis** [comment]
Einen Termin in der Ansicht Kalender Chronologisch eintragen zu können wird hier schmerzlich vermisst. Ich muss mir jeden Tag anhören, wie aufwendig es ist, erst in der Übersicht zu schauen und dann in die jeweilige Akte zu gehen und dort einen Termin einzutragen. Wir hoffen sehr auf dieses Feature in der 2.1 :)

**Comment by j-dimension** [comment]
https://user-images.githubusercontent.com/3729754/153083501-a849a864-ef08-4564-bc5f-49f22be15126.mp4

**Comment by j-dimension** [comment]
@iradraconis siehe Video. Nicht ganz optimal, da zwei Fenster nacheinander dargestellt werden, funktioniert aber erstmal und ich konnte durch Nachnutzung vorhandener Dialoge etwas schneller zum Ziel kommen. 

So, bekomme ich nun als Gegenleistung einen Termin bei Dir bzgl. der Umlautethematik?

**Comment by iradraconis** [comment]
> @iradraconis siehe Video. Nicht ganz optimal, da zwei Fenster nacheinander dargestellt werden, funktioniert aber erstmal und ich konnte durch Nachnutzung vorhandener Dialoge etwas schneller zum Ziel kommen.
> 
> So, bekomme ich nun als Gegenleistung einen Termin bei Dir bzgl. der Umlautethematik?

Bin begeistert UND WILL DAS RELEASE SOFORT! ;)  :) ....

Wegen der Umlautthematik musste ich erst sehen, wie ich es reproduziert bekomme. Ich schreibe dazu in dem anderen Ticket. Wegen Termin melde ich mich.

**Comment by iradraconis** [comment]
Ich vermute, dass hier beobachtete Verhalten hängt mit diesem Feature zusammen: 
- Kalenderblatt: Wochenansicht: Teiler zwischen Terminen und Fristen/WV bei Neustart des Clients immer wieder nach oben gerutscht, muss manuell nach unten gezogen werden, um Termine sichtbar zu machen


M1 Mac - MacOs 12.3

**Comment by j-dimension** [comment]
Danke, wird korrigiert.

**Comment by librelegal** [comment]
In Vorschau Version 2.1 scheint das zu funktionieren, aber der Kalender ist etwas verrutscht. Falls ich dafür lieber ein neues issue anlegen soll, bitte Bescheid sagen
![image](https://user-images.githubusercontent.com/37673969/160990456-e7d8153a-e84e-448f-b445-a039820cf672.png)

**Comment by j-dimension** [comment]
> In Vorschau Version 2.1 scheint das zu funktionieren, aber der Kalender ist etwas verrutscht. Falls ich dafür lieber ein neues issue anlegen soll, bitte Bescheid sagen

Das wäre sehr hilfreich, da anderer Fokus / Inhalt - danke!
