### ISSUE TITLE
[FEATURE] Klick auf Eintrag im Kalenderblatt führt in die Akte

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#1358]
so wie in der chronologischen Liste sollte auch im Kalenderblatt die Möglichkeit bestehen, mit einem Klick auf Termin/Frist zu der Akte zu springen. Dort dann direkt zu dem Fristen-Reiter.

**Comment by j-dimension** [comment]
> Geht bei mir übrigens nur für Termine nicht aber Fristen/etc

@stm9x9 was heißt das genau? Kann ich nicht nachvollziehen.

**Comment by j-dimension** [comment]
Schließe mangels Feedback.
