### ISSUE TITLE
[BUG] mehrtägige Termine werden in Kalenderansicht nur am Starttermin angezeigt.

### ISSUE THREAD

**Issue by iradraconis** [jlawyerorg/j-lawyer-org#1368]
So ist ein Abgleich von Terminen mit dem Urlaub eines Sachbearbeiters ein großes Risiko.

**Comment by j-dimension** [comment]
![grafik](https://user-images.githubusercontent.com/3729754/162533194-d91020d0-9770-4374-80f1-fc14bc30918e.png)

**Comment by j-dimension** [comment]
![grafik](https://user-images.githubusercontent.com/3729754/162533468-0671d38b-04e3-4f81-b135-412180b4e825.png)
