### ISSUE TITLE
[FEATURE] [kalender] einzelne Kalender in Übersicht ausblenden können

### ISSUE THREAD

**Issue by iradraconis** [jlawyerorg/j-lawyer-org#1369]
Rückmeldung von meinem Team. Die Übersicht leidet stark bei vielen Wiedervorlagen und Fristen, wenn ein Termin gefunden werden soll, vor allem in der Monatsansicht.

**Comment by stm9x9** [comment]
Ich würde vorschlagen, die Legende da oben einfach zu Buttons umzubauen.

![image](https://user-images.githubusercontent.com/29924198/136613910-580e9290-85a7-462e-a285-783748a57819.png)

**Comment by j-dimension** [comment]
Ein Scrollen innerhalb eines Tages in der Monatsansicht ist nicht trivial umsetzbar, da ich dafür eine externe Bibliothek anpassen müsste. Ich habe jetzt das Ein -und Ausblenden umgesetzt.

**Comment by j-dimension** [comment]
https://user-images.githubusercontent.com/3729754/160722496-32b02b8e-0ae2-4dd3-83a1-a6d5360e1cc3.mp4

**Comment by iradraconis** [comment]
Der Kalender ist mit der 2.1 richtig stark geworden! Danke Jens!
