### ISSUE TITLE
[FEATURE] [kalender] -Synchro: Aktenzeichen in den Titel

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#1377]
Es wäre hilfreich, wenn man - so wie ja auch in jl direkt - ein paar mehr Infos als nur den Grund im Terminstitel in nextcloud sähe.

zb: Aktenzeichen - Reaktion Gegner? 
oder Aktenzeichen - Kurzrubrum - Reaktion Gegner? 

Das wird dann zwar möglicherweise recht lang, aber wenn der Anwender es optional einstellen kann, ist das ja dann seine Entscheidung. zb in einer Tagesansicht des Kalenders paßt das ja alles hin. Aber wenigstens mit dem AKz die Frist überhaupt irgendwie zuordnen zu können, wäre schon nötig.

**Comment by j-dimension** [comment]
AZ okay

**Comment by j-dimension** [comment]
@stm9x9 @ReRo-G ich bin etwas hin- und hergerissen. Ich verstehe dass - wenn man bspw. mehrere gleichnamige WV am selben Tag hat - nicht direkt erkennbar ist, um welche Akte es geht. Die Informationen sind verfügbar, aber eben nur in den Details des Termins. 

Aber: Mandant aufnehmen hat die Herausforderung, dass es mehrere geben kann. AZ aufnehmen hätte für mich persönlich keinen Wert, ich kann anhand des Zeichens nicht ablesen, um welche Akte es geht, da bin ich zu wenig inselbegabt :-)

Würde das Rubrum - ans Ende der WV/Fristen/Terminbezeichnung gestellt - Eure Anforderungen adressieren?

**Comment by ReRo-G** [comment]
Ich für meinen Teil muss etwas auf die Bremse treten und entschuldige mich dafür, dass ich das spät mache:

Ich bin nach einigen Tagen der Nutzung zunächst wieder auf meine Bisherige Kalenderlösung umgestiegen und nutze für alle Termine etc. derzeit nicht jl. Der Grund dafür: Das anlegen geht so deutlich schneller und die Übersicht ist besser. Jl nutze ich daher momentan wie in der Basisversion und trage dort nur WVen und Fristen ein. Für mich funktioniert das gut - eine neue Stufe der Komplexität wird es ggf. künftig mit mehr Personal geben.

**Comment by stm9x9** [comment]
> Aber: Mandant aufnehmen hat die Herausforderung, dass es mehrere geben kann. AZ aufnehmen hätte für mich persönlich keinen Wert, ich kann anhand des Zeichens nicht ablesen, um welche Akte es geht, da bin ich zu wenig inselbegabt :-)

Ja, nur Mandant wäre zu wenig. Aber um am Az das Mandat zu erkennen, dazu muß man vielleicht Anwalt sein :-D 

Aber das ist sicher auch sehr kanzleispezifisch:

Der Sozialrechtsanwalt hat oft Mandanten mehrfach und immer gegen diesselbe Behörde.

> Würde das Rubrum - ans Ende der WV/Fristen/Terminbezeichnung gestellt - Eure Anforderungen adressieren?

Das ist dann Maier ./. Jobcenter Pusemuckl nicht hilfreich, um die Akte zu erkennen. Gibt einfach zuviele davon.

Wer Zivilrecht macht, der hat eher ständig wechselnde Mandanten und Gegner, da fällt bei Markmann ./. Günter wohl sofort der Groschen.

Also sage ich das, was Du immer am liebsten hörst ;-D ideal wäre konfigurierbar  

oder aber Mandant - Akz als Kompromiß. Das scheint mir in vielen Fällen auch kürzer zu sein als das Rubrum. Und zb im Strafrecht lautet das Rubrum oft "Strafsache Mustermann". Da ist dann mit "Strafsache" ganz viel für die schnelle Kalendersicht uninteressantes drin.

**Comment by j-dimension** [comment]
> oder aber Mandant - Akz als Kompromiß

Wie bereits erwähnt, das funktioniert nicht gut, wenn es mehrere Mandanten gibt.

**Comment by stm9x9** [comment]
Hm, hatte ich überlesen. Dann bleibt wohl nur "Rubrum - Akz".

**Comment by j-dimension** [comment]
vielleicht doch noch Rubrum

**Comment by stm9x9** [comment]
wirkt das eigentlich nur auf mit der 2.1 neu erstellte Fristen oder auch schon auf vorher erstellte?

**Comment by j-dimension** [comment]
> wirkt das eigentlich nur auf mit der 2.1 neu erstellte Fristen oder auch schon auf vorher erstellte?

auf ab dem Update erstellte oder bearbeitete

einfach ausprobieren?

**Comment by stm9x9** [comment]
dann wüßte ich ja immer noch nicht, ob das beobachtete dann works as intended :-)

**Comment by j-dimension** [comment]
Du kannst ja einen Termin ändern oder erstellen?

**Comment by j-dimension** [comment]
Oder meinst du ich möge das erwartete Verhalten hier nochmal beschreiben?

**Comment by stm9x9** [comment]
> Oder meinst du ich möge das erwartete Verhalten hier nochmal beschreiben?

ich nehme an, das hast du mit "auf ab dem Update erstellte oder bearbeitete" schon getan?

Ich wunderte mich nur über ein Nebeneinander von Einträgen mit und ohne Zusatzinformationen. Weil ich dachte, die werden alle bei jeder Synchro neu erzeugt oder so. Aber da dem wohl so nicht ist, muß ich mir jetzt überlegen, ob ich da ein Feature-Ticket aufmache oder ob es den Aufwand wohl nicht wert ist (also Deinen Aufwand, nicht meinen, ein Ticket zu erstellen). Ein Fehler-Ticket ist es ja demnach jedenfalls nicht. :-)
