### ISSUE TITLE
Kalender: neuer Kalender wird nicht angezeigt bei Neuanlage

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#1379]
Ich habe neue Kalender eingefügt und einen bestehenden umbenannt "Terminexy"

![image](https://user-images.githubusercontent.com/29924198/136626450-81f2cf20-055a-4f9d-9684-7fedd1bda4b0.png)

Ich bekomme aber nur den veränderten bei der Neuanlage angezeigt:

![image](https://user-images.githubusercontent.com/29924198/136626514-8c0268f8-7c9e-410b-86f3-d3d25c2e83db.png)

**Comment by j-dimension** [comment]
Hast Du in der Nutzerverwaltung Rechte für den neuen Kalender vergeben?

**Comment by stm9x9** [comment]
Aaaa ich muß den dann wiederum noch in der Nutzerverwaltung freigeben. Problem als solches gelöst. Bleibt nur die Frage, ob man das irgendwie intuitiver für den Admin machen kann oder einen Hinweis da irgendwo hinschreibt.

**Comment by j-dimension** [comment]
Doku-Thema, ja. Gibt's noch nicht. Zeitplan zu tough.
