### ISSUE TITLE
[TASK] Anforderungen - Teilnahme von Drittanwendungen am OSCI-gestützten elektronischen Rechtsverkehr

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#1380]
Ich nehme mal zwar an, daß das schon bekannt ist, aber zur Sicherheit und weil ich ein paar Punkte herausstellen will:

https://egvp.justiz.de/Drittprodukte/EGVP_Infrastruktur_Anforderungen_Teilnahme_von_Drittanwendungen.pdf

Ich versteh nur Bahnhof:
![image](https://user-images.githubusercontent.com/29924198/136637256-e41278cb-f2a4-4079-a1b2-db474ae23cf7.png)

Das dürfte das große Textfeld sein. Mein Vorschlag: rausnehmen, sobals möglich. Gewinnt auch gleich Platz im Fenster.
![image](https://user-images.githubusercontent.com/29924198/136637287-8e1d0dbc-12ab-4f82-951c-a2c832c54168.png)

laut BRAK werden damit auch endlich die Anhänge vom Empfänger quittiert, da bin ich mir aber nicht sicher
![image](https://user-images.githubusercontent.com/29924198/136637392-ef1941aa-f733-4493-afa0-97f7fd45ef74.png)

Gibt es denn inzwischen die nötigen Informationen, um einen Strukturdatensatz korrekt für was anderes als Gerichte, also zb Behörden oder StAs zu erzeugen? Bislang tauchen die ja in den Listen nicht auf.
![image](https://user-images.githubusercontent.com/29924198/136637470-8e4802fc-4c28-4bbe-843a-b71babe2f5cb.png)

Für das Aktenzeichen ggf. die Werte neu und unbekannt als weiteren Vorschlag in das dropdown-Menü aufnehmen?
![image](https://user-images.githubusercontent.com/29924198/136637564-994ae3f3-32cb-4fb5-be87-1a27e346430f.png)

Verstehe ich das richtig? Hier werden zwingende(?) Vorgaben für den Betreff gemacht? Was soll das denn überhaupt sein? Sachgebiet? Ereignis?
![image](https://user-images.githubusercontent.com/29924198/136637610-f85d56b3-c6d1-42ba-b636-771ce5678e9d.png)

Und BTW, das alles muß bis zum 1.11.21 umgesetzt sein!

Gab es nicht das Problem, daß eine KSW den Laufzettel nur einmal abholen kann oder so? Wie soll denn dann später nochmal der Laufzettel mit der Abholbestätigung geholt werden? Und es muß eine Visualisierung dieser Bestätigung erstellt/entwickelt werden.
![image](https://user-images.githubusercontent.com/29924198/136637702-570e9541-7fd3-43b1-97f2-bb1dc666e796.png)

Prüfvermerk?
![image](https://user-images.githubusercontent.com/29924198/136637723-e0171f07-db96-48b6-9e1b-03cc48fb2da1.png)

**Comment by stm9x9** [comment]
> Verstehe ich das richtig? Hier werden zwingende(?) Vorgaben für den Betreff gemacht? Was soll das denn überhaupt sein? Sachgebiet? Ereignis?

wobei auch der Betreff zum 1.11.21 wegfallen soll?

![image](https://user-images.githubusercontent.com/29924198/136638004-98fe6629-5d43-4f8a-88f1-bdce770f5233.png)

**Comment by stm9x9** [comment]
> Prüfvermerk?

ah, weitere Infos ab S. 13 - den muß eine KSW dann wohl erstellen können müssen?

**Comment by stm9x9** [comment]
ich glaube, die zitierten Punkte dürfte den Handlungsbedarf gut umreißen, aber ich gucke das Dokument nochmal durch. An etlichen Stellen allerdings fürchte ich, fehlen mir tiefere Kenntnisse über die konkrete beA-Anbindung von jl.

**Comment by j-dimension** [comment]
via bea wrapper und upgrade auf V6 der Schnittstelle der BRAK
