### ISSUE TITLE
[BUG] Sipgate Einstellungen auf MacOS lassen sich nicht öffnen

### ISSUE THREAD

**Issue by PBaumfalk** [jlawyerorg/j-lawyer-org#1381]
In Einstellungen lässt sich die Sipgate-Einstellung nicht öffnen auf macOS.

Telefonie/Fax - Sipgate öffnet sich nach Klick nicht.

**Comment by j-dimension** [comment]
Schau ich mir an.

Brauchst Du aber wahrscheinlich nicht. Die Zugangsdaten hängen am Nutzer.

Musst einen Token erstellen.

Tokenerstellung:

bei Sipgate einloggen

links auf "Mein Account"

weit unten "Personal Access Tokens"

dort einen Token erstellen, Wert in die Zwischenablage kopieren

Token-ID und Wert in j-lawyer.org am Nutzer hinterlegen

**Comment by PBaumfalk** [comment]
Okay. Ich habe auch gerade meine Nextcloud-Probleme gelöst. Heute habe ich mal Family-Frei und Zeit und richtig hart Bock.

Mit freundlichen Grüßen / Kindly Regards

Patrick Baumfalk
Rechtsanwalt / Lawyer


Mobil:    +49 1525 53 04 194
E-Mail:   ***@***.***

BAUMFALK - Rechtsanwaltskanzlei

Hauptkanzlei:
Hauptstr. 195
50169 Kerpen

Zweigstelle:
Berliner Str. 4
58452 Witten

Postanschrift:
Postfach 1233
50141 Kerpen

Tel.: +49 2273 40 68 504
Fax: +49 2273 59 03 565

E-Mail: ***@***.***
Web: www.kanzlei-baumfalk.de
