### ISSUE TITLE
Maximale Kontakte in Nextcloud? 

### ISSUE THREAD

**Issue by PBaumfalk** [jlawyerorg/j-lawyer-org#1382]
Bei der Syncro fällt mir auf, dass nur ca. 400 Kontakte übertragen wurden. Liegt das an J-Lawyer oder an der NC?

**Comment by j-dimension** [comment]
Es gibt kein explizites Limit. Kannst Du ein Server.log per Mail schicken?

**Comment by PBaumfalk** [comment]
Es ist Erledigung eingetreten.
Durch Update der Nextcloud wurden auch alle Beschränkungen aufgehoben.

Mit freundlichen Grüßen / Kindly Regards

Patrick Baumfalk
Rechtsanwalt / Lawyer


Mobil:    +49 1525 53 04 194
E-Mail:   ***@***.***

BAUMFALK - Rechtsanwaltskanzlei

Hauptkanzlei:
Hauptstr. 195
50169 Kerpen

Zweigstelle:
Berliner Str. 4
58452 Witten

Postanschrift:
Postfach 1233
50141 Kerpen

Tel.: +49 2273 40 68 504
Fax: +49 2273 59 03 565

E-Mail: ***@***.***
Web: www.kanzlei-baumfalk.de
