### ISSUE TITLE
[TASK] Xjustiz Aktenviewer entfernen

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#1384]
Mit dem Menüpunkt wird aktuell eine exe runtergeladen.  Diese gibt den Fehler:

![image](https://user-images.githubusercontent.com/29924198/136671815-cca646b5-df5c-4507-8094-aab46d70515d.png)

In zip unbenannt, ist da eine viewer.exe drin, die aber nicht mit der neuesten übereinstimmt, die seit kurzem angeboten wird: https://www.facebook.com/groups/beasupport/posts/2631449863817723/

**Comment by j-dimension** [comment]
Bitte vorerst direkt den Autor der Anwendung ansprechen. 

Werde ihn parallel kontaktieren.

**Comment by librelegal** [comment]
Besser als die Reparatur dieses bugs wäre wohl der Einbau des plattforumunabhängigen XJustiz-Viewers #1200 mit dem interessanten projekt https://openxjv.de/
