### ISSUE TITLE
nextcloud / Kontakte: nur Kontakte mit Hausnummer werden übertragen?

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#1385]
Mir fiel gerade bei den Gerichten in meiner Adressdatenbank auf, daß nur Kontakte synchronisiert werden, die einen Eintrag in der Hausnummer haben. (wobei das dann in nextcloud gar nicht nach Straße und Nummer aufgeteilt wird). Daher sind fast alle Gerichte nicht übertragen worden, weil die Hausnummer im Feld Straße über beA übernommen wurde. Immer wenn ich in jl die Nummer in das Feld Hausnummer übertrage, dann erscheint auch der Kontakt in der nextcloud.

**Comment by stm9x9** [comment]
Korrektur: es reicht offenbar aus, den Kontakt ohne jede Veränderung in jl einfach nochmal abzuspeichern. Und schon wird das Gericht übertragen. Aber es bleibt dabei: Ohne daß ich einen Kontakt neu abspeichere wurden nur die alten Kontakte übertragen, die was im Feld Hausnummer stehen hatten.

**Comment by j-dimension** [comment]
Kann ich nicht nachvollziehen, weder durch Ausprobieren, noch finde ich einen plausiblen Grund wenn ich den Code anschaue. 

Brauche das server.log.

**Comment by stm9x9** [comment]
was heißt standardmäßig? Ich habe jetzt zb das AG Zwickau in nextcloud. Nicht weil es Beteiligter irgendwo ist, sondern nur, weil ich im Kontakt in jl einmal auf speichern gedrückt habe. Löst dieses Speichern eine Synchronisation aus? Dann wäre das mit der Hausnummer nur eine Koexidenz.

**Comment by stm9x9** [comment]
dann kann das wohl geschlossen werden
