### ISSUE TITLE
[BUG] Desktop - schwarze Striche zwischen Einträgen

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#1386]
eine kleine vermutlich nur optische Irritation.

![image](https://user-images.githubusercontent.com/29924198/136673950-2243cd45-464e-4625-aa7f-d3030edaa2c6.png)

**Comment by j-dimension** [comment]
Ich sehe das auf keiner meiner Testumgebungen. Windows? Welche Auflösung?

**Comment by stm9x9** [comment]
Windows 10 64bit
1680x1050
Benutzerdefinierte Skalierung 105%
Textgröße 1 (mit 0 kann ich es aktuell nicht probieren, da ich nach einer Trennen/neu verbinden-Kaskade und einem reboot gerade gar nicht auf meinen Testserver zugreifen kann :-/) Aber die 1.14 zeigt mit Größe 0 und 1 nicht dieses Streifen.

**Comment by stm9x9** [comment]
So, nach einem Update auch des Servers geht wieder alles. Also auch bei Größe 0 sind die Striche da.

BTW, die Schriftgröße wird irgendwo so zentral gespeichert, daß die Veränderung in einer Installation (2.0) sie auch in der Parallelinstallation (1.4) ändert.

**Comment by j-dimension** [comment]
> BTW, die Schriftgröße wird irgendwo so zentral gespeichert, daß die Veränderung in einer Installation (2.0) sie auch in der Parallelinstallation (1.4) ändert.

Ja, auf dem Gerät. Diese Einstellung will man idR nicht "mitnehmen" auf ein anderes Gerät.

**Comment by j-dimension** [comment]
> So, nach einem Update auch des Servers geht wieder alles.

Ist das "Tag -1"-Thema also erledigt?

**Comment by j-dimension** [comment]
auch nach Monaten auf keiner Kundeninstallation gesehen.
