### ISSUE TITLE
[FEATURE] Benachrichtigungen an Dritt-Software aus JLawyer via Webhooks

### ISSUE THREAD

**Issue by Linkki2021** [jlawyerorg/j-lawyer-org#1392]
Um über Änderungen an Daten, Dokumente, Informationen aus jlawyer in einer dritten Software benachrichtigt zu werden benötigt es die Möglichkeit dies in JLawyer zu konfigurieren.

Als Sinnvolle Lösung sehen wir Webhooks mit minimaler Payload.

Aktuell sehen wir folgende Use-Cases bei der das Ausführen eines Webhooks sinnvoll sind:
-	Eingabe in Falldaten
-	Erstellung Dokument bzw. neues Dokument in Akte
-	Vergabe Etiketten (Dokument oder Akte)
-	Änderung Adressdaten
-	Erstellung/Änderung Wiedervorlage

**2021-11-22 per E-Mail: 
am wichtigsten: 
Vergabe der Etiketten (document & case) sowie die Dokumenterstellung**

- [x] Basics: Events und custom hooks samt Observer
- [x] HTTP POST Request-Generator
- [x] Datenmodell erweitern: Hook-Konfiguration
- [ ] GUI erweitern: Hooks pflegen
- [x] Hook: neues Dokument
- [x] Hook: geändertes Dokument
- [x] Hook: gelöschtes Dokument
- [x] Hook: neue Adresse
- [x] Hook: geänderte Adresse
- [x] Hook: gelöschte Adresse
- [x] Hook: neue Akte
- [x] Hook: geänderte Akte
- [x] Hook: gelöschte Akte
- [x] Hook: Etikett Akte an
- [x] Hook: Etikett Akte aus
- [x] Hook: Etikett Adresse an
- [x] Hook: Etikett Adresse aus
- [x] Hook: Etikett Dokument an
- [x] Hook: Etikett Dokument aus
- [ ] Hook: Falldaten geändert

**Comment by j-dimension** [comment]
Ticketbeschreibung erweitert (Prioritäten)

**Comment by j-dimension** [comment]
@Linkki2021 was heisst "Eingabe in Falldaten" - die Erstellung eines Falldatenblattes in einer Akte?

**Comment by Linkki2021** [comment]
Hallo Jens, "Eingabe in Falldaten" soll heißen es gibt ein bestehendes Falldatenblatt, in unserem Fall Verkehrsunfalldaten, und dort werden Daten eingegeben.

**Comment by j-dimension** [comment]
> soll heißen es gibt ein bestehendes Falldatenblatt, in unserem Fall Verkehrsunfalldaten, und dort werden Daten eingegeben.

@Linkki2021 
Das kann ich nicht unaufwändig umsetzen, müsste dann jeden einzelnen Eintrag vergleichen. Würde es reichen mitzubekommen, wenn eine Akte mit einem Falldatenblatt eines bestimmten Typs gespeichert wird?

**Comment by j-dimension** [comment]
POST-Requests:
```
{
  "hookType": "ADDRESS_CREATED",
  "addressId": "21f3f7b07f0001012cdc167fafd982c3"
}

{
  "hookType": "ADDRESS_UPDATED",
  "addressId": "21f3f7b07f0001012cdc167fafd982c3"
}

{
  "active": true,
  "tagName": "abweisen",
  "hookType": "ADDRESSTAG_CHANGED",
  "addressId": "21f3f7b07f0001012cdc167fafd982c3"
}

{
  "active": false,
  "tagName": "abweisen",
  "hookType": "ADDRESSTAG_CHANGED",
  "addressId": "21f3f7b07f0001012cdc167fafd982c3"
}

{
  "hookType": "ADDRESS_REMOVED",
  "addressId": "21f3f7b07f0001012cdc167fafd982c3"
}

```

**Comment by j-dimension** [comment]
https://user-images.githubusercontent.com/3729754/148139351-af9087c2-6b30-4450-92ec-2f8b81f40f90.mp4

**Comment by j-dimension** [comment]
zusätzlicher Webhook für geänderte Falldaten:
```

{
  "formId": "369161647f00010160fa4bb8450ccbb3",
  "caseId": "6a7bd5367f000101364966678df1572d",
  "hookType": "CASE_FORM_UPDATED"
}
```
