### ISSUE TITLE
[BUG] Rechtsklick Kontextmenü auf ZIP Datei führt zu Einfrieren des Systems, langer Reaktionszeit

### ISSUE THREAD

**Issue by iradraconis** [jlawyerorg/j-lawyer-org#1394]
**Describe the bug / Fehlerbeschreibung**
(todo: a description of the bug / eine Beschreibung des Fehlers)
Szenario: etwa 20 MB große ZIP Datei befindet sich im Dokumentenordner. Die Datei soll lokal gespeichert werden. Bei Rechtsklick auf die Datei ist das Kontextmenü aber erst verfügbar, wenn J-Lawyer eine "Vorschau" der Datei generiert hat. Das funktioniert bei Zip Dateien nun nicht mal so prima. Mein komplettes System ist währenddessen für knapp eine Minute eingefroren. So unter Linux und auch MacOS. Das passiert (gut so!) bei großen PDF Dateien nicht. 

**Expected behavior / Erwartetes Verhalten**
Die Datei sollte auch ohne Vorschau mittels Kontextmenü "bearbeitet" werden können.

**Comment by j-dimension** [comment]
@iradraconis Wenn die selbe Datei ein zweites mal angeklickt wird, geht es dann schnell?

**Comment by j-dimension** [comment]
@iradraconis über das Limitieren der Vorschaugröße sollte hier Abhilfe möglich sein. Kann ich das Ticket schließen?

**Comment by iradraconis** [comment]
> @iradraconis über das Limitieren der Vorschaugröße sollte hier Abhilfe möglich sein. Kann ich das Ticket schließen?

denke ja
