### ISSUE TITLE
Kalenderbutton für Geburtstag

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#14]
Bei der Eintragung von Fristen etc kommt ein Kalender, wo man ein Datum per Klick auswählen kann. Dasselbe für den Geburtstag eines Beteiligten wäre nett.

**Comment by bjk00** [comment]
Ich gehe davon aus, dass diese Änderung auch in der Workaround-Version 1.9.1 zum Issue#232 enthalten ist. 
Der Kalender wird dort nach dem Öffnen in fester Relation zum rechten Rand des j-lawyer-Programmfensters positioniert. Ist das Programmfenster maximiert bzw. sehr groß so wird der Kalender nicht vollständig angezeigt und eine Auswahl ist nur eingeschränkt möglich. Der Kalender lässt sich auch nicht verschieben. 
Um ihn vollständig angezeigt zu bekommen, muss das jlawyer-Programmfenster relativ klein sein und außerdem weit nach links auf dem Desktop verschoben.
Windows 10, Client 1.9.1 mit Workaround zu Issue#232, Bildschirmauflösung 2560x1440

**Comment by j-dimension** [comment]
@bjk00 hast Du einen Screenshot?

**Comment by bjk00** [comment]
![screenshot](https://user-images.githubusercontent.com/46385750/52370155-80513000-2a52-11e9-8242-4ec25dba31ae.jpg)

**Comment by j-dimension** [comment]
Ist das ein Dualmonitor-System? Ich kann das hier gerade nicht reproduzieren?

**Comment by bjk00** [comment]
Nein, kein Dualmonitor. Ein Bildschirm mit oben genannter Auflösung. Ich mach gleich noch einen Screenshot mit verkleinertem Programmfenster. Vielleicht hilft das...

**Comment by bjk00** [comment]
![screenshot2](https://user-images.githubusercontent.com/46385750/52370785-146fc700-2a54-11e9-94f6-9292bbb51169.jpg)
Wenn die Breite des Programmfensters reduziert wird, wird der Kalender auf voll dargestellt.
Der Screenshot ist über die volle Bildschirmbreite

**Comment by bjk00** [comment]
Der Kalender wird scheinbar fix zum rechten Rand des Programmfensters positioniert, unabhängig wo der Rand ist.

**Comment by j-dimension** [comment]
@bjk00 Danke, ich mache das Ticket nochmal auf, auch wenn ich im Moment noch nicht weiß wie ich es reproduziere.

**Comment by j-dimension** [comment]
Die Koordinatenberechnung ist fehlerhaft. Unter Linux und macOS entscheidet das Betriebssystem, das Fenster statt an der angeforderten Position zu rendern, eine Position zu nehmen die eine vollständige Darstellung sicherstellt. 

Windows hat eine solche Logik nicht. Benötigt daher einen Fix.
