### ISSUE TITLE
beAToolkit Temp-Ordner wird nicht gelöscht und verlangsamt beA extrem

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#1406]
Win10 64bit, client 64bit

Der Ordner C:\Users\User\AppData\Local\Temp\beaToolkit wird nach einem Logout nicht gelöscht und damit sammeln sich dort im Laufe der Zeit zig ... zigtausende Ordner und Dateien an und bewirken, daß jl ab dem beA-Login extrem ausgebremst wird, die CPU-Last dauerhaft (bis zum beA-Logout) in die Höhe schnellt, der beA-Login über eine Minute dauert und das Öffnen einer Nachricht bis zu 2-3 min.

![image](https://user-images.githubusercontent.com/29924198/137798838-c55537db-6d1b-43b7-87db-de74f68d801b.png)

Mit dem Processmonitor konntei ich feststellen, daß jl nach dem bea-Login nur noch am Öffnen und Lesen dieser Ordner ist, während beA läuft.

Nachden ich den Ordner manuell gelöscht habe, rennt beA wieder wie in allen anderen Installationen, die ich testweise u.a. in einer virtuellen Umgebung installiert hatte.

**Comment by j-dimension** [comment]
Das scheint in deren Bibliotheken verbacken zu sein. 

(1) Ordner gelöscht, j-lawyer Client gestartet und beA benutzt --> Ordner ensteht wieder, samt Daten
(2) Ordner gelöscht, beA über die Weboberfläche benutzt --> Ordner ensteht wieder, samt Daten

Magst Du mal den Support kontaktieren und fragen, wie dieser Ordner "bereinigt" wird?

**Comment by stm9x9** [comment]
> Magst Du mal den Support kontaktieren und fragen, wie dieser Ordner "bereinigt" wird?

komme ich an den Support für die bea-KSW-Schnittstelle ran? Ist ja nicht das normale beaSecurity-Enduser-Programm?

**Comment by stm9x9** [comment]
man empfahl mir als wörtlich Workaround in den Windows-Einstellungen die Speicheroptimierung zu aktivieren und zu konfigurieren, zb daß alle Temp-Dateien nach 1 Woche oder nach 1 Monat gelöscht werden

**Comment by j-dimension** [comment]
Nun ja, was machen wir jetzt damit?

**Comment by j-dimension** [comment]
Erstmal nur Warnung, da das Finden des temporären Ordners nicht trivial ist und ich keine Daten des Anwenders leichtfertig lösche.

![grafik](https://user-images.githubusercontent.com/3729754/144524342-763a0931-b726-4174-a597-e22ab502b258.png)

**Comment by stm9x9** [comment]
ab wieviel Ordnern willst du denn warnen? Ich würde so roundabout 100 vorschlagen. Und kann der Verzeichnis-String anklickbar sein und den Explorer da öffnen?

Und ich würde den Grund noch ergänzen: ... werden, da diese die beA-Komponente ausbremsen können.

**Comment by j-dimension** [comment]
Ab 500 Ordnern, konfigurierbar. Ja, Navigation durch Klick gerade hinzugefügt. Grund war schon vorher drin (aber nicht im Screenshot).

**Comment by stm9x9** [comment]
bezieht sich die 500 auf Ordner- und Unterordner oder nur im Hauptverzeichnis? Im ersteren Fall dürfte das ausreichen. Bei 500 Hauptordnern dürfte das System schon lange massiv ausgebremst sein, ohne das der Nutzer den Hinweis bekommt, warum. Da würde ich für den nicht-wissenden Nutzer eher 100 vorsehen.

**Comment by j-dimension** [comment]
bezieht sich auf die gesamte Struktur
