### ISSUE TITLE
[TASK] EB-Symbol anders anordnen

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#1407]
Das EB-Symbol ist jetzt vor das Aktenzeichen gerutscht. IMHO paßt es dort systematisch nicht hin. Und auch nicht optisch. Oben ist aber durch das pdf-Symbol eh eine Zeile, die kann rechts genutzt werden. Und damit könnte das EB-Symbol auch größer und damit sichtbarer werden. Halt so groß wie das pdf-Symbol.

![image](https://user-images.githubusercontent.com/29924198/137814603-779a965b-3a1d-4c00-92c0-9e1444c02eb8.png)

**Comment by stm9x9** [comment]
> Eigentlich will ich diese Zeile mit dem PDF-Export loswerden. Zu viel leerer Platz.

jetzt scheint da ja noch das Signaturprüf-Icon hinzukommen: #1485 
Kann dann auch das EB-Icon da hoch?

**Comment by j-dimension** [comment]
Ja, ist jetzt auch da oben. 
![grafik](https://user-images.githubusercontent.com/3729754/144936713-4450616d-17f1-402c-aaf7-bbe8da256457.png)


Das Textfeld fällt übrigens nicht weg.

**Comment by stm9x9** [comment]
> Das Textfeld fällt übrigens nicht weg.

DAFUQ? Das wollten die vom "EGVP-Konsortium" doch unbedingt endlich weg haben?

**Comment by j-dimension** [comment]
> DAFUQ? Das wollten die vom "EGVP-Konsortium" doch unbedingt endlich weg haben? Oder hat das was damit zu tun, daß auch das neue beA-Web-Design von heute auf morgen abgekündigt ... äh ... verschoben wurde?

Nichts Genaues weiß man nicht. Ich kann in der Testumgebung immer noch mit Text senden, und in meinem Testgericht EGVP-kommt der Text auch an. 
Evtl. fällt das erst mit Einführung VHN2 weg, das kann ich nicht testen, da es dafür noch keine Testumgebung gibt. Soll aber Ende des Jahres bereits genutzt werden. Ich implementiere dann VHN2 am 25. / 26.  Dezember oder so.

Ich habe von einem Automatismus gelesen, der dann den Nachrichtentext in ein PDF wandelt und als Anhang zustellt. Nur bekommt die KSW davon nichts mit. Da hat man dann eine gesendete Nachricht in der Akte, die von dem abweicht, was das Gericht empfängt. Wenn die sich über das PDF beschweren, weiß man nicht mal was passiert sein könnte, da man die Datei nicht hat.

Und Nachrichten von Anwalt zu Anwalt werden m.E. auch weiterhin mit Text gesendet werden können. Ist aber alles irgendwie noch im Fluss (also alles bis auf die Informationen).

**Comment by stm9x9** [comment]
;-( und 

```
                ___                  ____                  ___
           ____(   \              .-'    `-.              /   )____
          (____     \_____       /  (O  O)  \       _____/     ____)
         (____            `-----(      )     )-----'            ____)
          (____     _____________\  .____.  /_____________     ____)
            (______/              `-.____.-'              \______)

            *Hug*     *Hug*    *Hug*     *Hug*          *Hug*
            *Hug*     *Hug*    *Hug*     *Hug*       *Hug* *Hug*
            *Hug*     *Hug*    *Hug*     *Hug*      *Hug*   *Hug*
            *Hug*     *Hug*    *Hug*     *Hug*     *Hug*
            *Hug**Hug**Hug*    *Hug*     *Hug*    *Hug*
            *Hug**Hug**Hug*    *Hug*     *Hug*    *Hug*    *Hug**Hug*
            *Hug*     *Hug*    *Hug*     *Hug*     *Hug*     *Hug*
            *Hug*     *Hug*     *Hug*   *Hug*       *Hug*   *Hug*
            *Hug*     *Hug*      *Hug* *Hug*         *Hug* *Hug*
            *Hug*     *Hug*         *Hug*               *Hug*
```
