### ISSUE TITLE
[FEATURE] Aktensuche - Fokus ins Suchfeld und auch SelectAll

### ISSUE THREAD

**Issue by iradraconis** [jlawyerorg/j-lawyer-org#1408]
plus nach erfolgter Suche wieder Fokus UND SelectAll im Suchfeld.
Das spart nur ein paar Klicks und Mauswege. Reine Usebality.

**Comment by j-dimension** [comment]
wann immer man zur akten- oder adresssuche navigiert, ist der Fokus nun im Suchfeld und ggf. ein bereits enthaltener Suchbegriff vollständig selektiert. 

Den Fokus nach Suche ins Suchfeld setzen möchte ich nicht, der ist nach der Suche in der Tabelle, sodass man mit den Pfeiltasten navigieren und per Enter öffnen kann.
