### ISSUE TITLE
[FEATURE] Rechnungserstellung mit GiroCode

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#1412]
Um Überweisungen zu erleichtern, gibt es eine Sonderform des QR-Codes, der SEPA-Informationen enthält. Die kann man einfach mit der Banking-App scannen und alle Daten sind ohne Abtippfehler und Arbeit in der Überweisungsmaske.

siehe zb https://www.youtube.com/watch?v=VPx0pCauW64

Da Name und Kontoverbindung ja schon in jl hinterlegt sind, könnte man beim Erzeugen einer Rechnung auch so einen Code erzeugen lassen.

Dafür gibt es mehrere Moglichkeiten:

- über eine API den Code erzeugen lassen. zb https://qrcode.tec-it.com/de/SEPA - damit wäre man aber von Dritten abhängig
- es gibt für Word eine Anleitung für die interne Funktion https://www.defrent.de/2021/04/eqc-qr-codes-in-ms-word/, aber die scheint bei LibreOffice nicht zu gehen - da gibt es zwar auch eine QR-Funktion https://help.libreoffice.org/latest/de/text/shared/guide/qrcode.html, aber da bekomme ich die notwendigen Line Feed Sonderzeichen nicht rein
- selber erstellen. zb: https://techblogstation.com/java/generate-qr-code-in-java/ - Die Infos über die notwendigen Daten im "Text"-Feld gibt es in dem Word-Link

@j-dimension 2024-02-08 ------------------------------------

- [x] neue Platzhalterart für Bilddaten: 4h
- [x] neuer Platzhalter BEL_QR: 0,5h
- [x] bei Dokumenterstellung: prüfen auf QR-Platzhalter, wenn vorhanden: prüfen auf vollständige Zahlungsinformationen im Kanzleiprofil, ggf. Warnung: 1,5h
- [x] Dokumenterstellung: QR-Code aus Bankinformationen im Kanzleiprofil generieren: 0,75h
- [x] Test MS Office: 1,5h
- [x] Test LibreOffice: 1,5h
- [ ] Doku: 0,5h

10,25h

zukünftig könnte es auch sinnvoll sein, die Kontoinformationen nicht aus dem Kanzleiprofil zu nehmen, sondern die Bankverbindung am Nutzer zu hinterlegen (Bürogemeinschaften).

**Comment by stm9x9** [comment]
noch eine API: https://zahlen-mit-code.com/#api

Paßt ja zur aktuellen Rechnungs-Offensive! :-D

**Comment by stm9x9** [comment]
noch was zum Dateninhalt: https://de.wikipedia.org/wiki/EPC-QR-Code#Dateninhalt

**Comment by j-dimension** [comment]
```
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Base64;

import javax.imageio.ImageIO;

import com.google.zxing.BarcodeFormat;
import com.google.zxing.EncodeHintType;
import com.google.zxing.WriterException;
import com.google.zxing.client.j2se.MatrixToImageWriter;
import com.google.zxing.common.BitMatrix;
import com.google.zxing.qrcode.QRCodeWriter;
import com.google.zxing.qrcode.decoder.ErrorCorrectionLevel;

public class GirocodeGenerator {

    public static void main(String[] args) throws WriterException, IOException {
        // Define invoice data
        String iban = "DE89370400440532013000";
        String bic = "COBADEFFXXX";
        String name = "John Doe";
        String amount = "10.50";
        String purpose = "Invoice 12345";
        
        // Encode invoice data as a Girocode string
        String girocodeData = String.format("BCD\n001\n1\nSCT\n%s\n%s\n%s\nEUR%s\n\n\n%s\n\n\n\n", iban, bic, name, amount, purpose);
        byte[] girocodeBytes = girocodeData.getBytes("ISO-8859-1");
        String girocodeBase64 = Base64.getEncoder().encodeToString(girocodeBytes);
        
        // Generate QR code from Girocode string
        QRCodeWriter qrWriter = new QRCodeWriter();
        BitMatrix matrix = qrWriter.encode(girocodeBase64, BarcodeFormat.QR_CODE, 300, 300, getHints());
        
        // Write QR code to file
        File qrFile = new File("girocode.png");
        Path qrPath = qrFile.toPath();
        MatrixToImageWriter.writeToPath(matrix, "PNG", qrPath);
        
        // Read QR code file as base64 string
        byte[] qrBytes = Files.readAllBytes(qrPath);
        String qrBase64 = Base64.getEncoder().encodeToString(qrBytes);
        
        System.out.println("Girocode data: " + girocodeData);
        System.out.println("Girocode base64: " + girocodeBase64);
        System.out.println("QR code base64: " + qrBase64);
    }
    
    private static java.util.Map<EncodeHintType,Object> getHints() {
        java.util.Map<EncodeHintType,Object> hints = new java.util.EnumMap<EncodeHintType,Object>(EncodeHintType.class);
        hints.put(EncodeHintType.ERROR_CORRECTION, ErrorCorrectionLevel.L);
        hints.put(EncodeHintType.CHARACTER_SET, "ISO-8859-1");
        return hints;
    }
}

```

**Comment by j-dimension** [comment]
benötigt Startup-Parameter

`--add-exports=java.base/sun.security.action=ALL-UNNAMED --add-exports=java.desktop/com.sun.imageio.plugins.jpeg=ALL-UNNAMED --add-exports=java.desktop/com.sun.imageio.spi=ALL-UNNAMED`

**Comment by j-dimension** [comment]
![grafik](https://github.com/jlawyerorg/j-lawyer-org/assets/3729754/15be5292-c7b1-40a5-8e8d-26c2251ecef6)

**Comment by j-dimension** [comment]
https://github.com/jlawyerorg/j-lawyer-org/assets/3729754/c7583c6a-4d9d-48e1-a464-070f1d8a8d02

**Comment by j-dimension** [comment]
`{{BEL_GIROCODE}}`

**Comment by socram70** [comment]
Auch wenn es für die Produktivversion vermutlich nicht mehr benötigt werden wird, wäre es vermutlich noch hilfreich darauf hinzuweisen, wo man die Parameter einfügen muss. Ich würde es in der /etc/init.d/j-lawyer-server ab Zeile 167 unterbringen, korrekt? Hier ab Zeile 166:

`
 if [ "$JBOSS_MODE" = "standalone" ]; then
                        start-stop-daemon --start --user "$JBOSS_USER" \
                        --chuid "$JBOSS_USER" --chdir "$JBOSS_HOME" --pidfile "$JBOSS_PIDFILE" \
                        --exec "$JBOSS_SCRIPT" -- -c $JBOSS_CONFIG $JBOSS_OPTS >> "$JBOSS_CONSOLE_LOG" 2>&1 &`
