### ISSUE TITLE
[FEATURE] Dokumente in Zwischenablage übernehmen

### ISSUE THREAD

**Issue by Linkki2021** [jlawyerorg/j-lawyer-org#1419]
Es wäre wünschenswert, wenn Dokumente aus einer Akte über das Rechtsklick-Kontextmenü in die Zwischenablage übernommen werden könnten, um sich für bestimmte Schritte das lokale zwischenspeichern zu sparen.

---------------- @j-dimension 2023-09-29 ---------------------------

- [x] Implementierung
- [x] Test Linux
- [ ] Test Windows
- [ ] Test macOS

**Comment by Dickmaulruessler** [comment]
praktisches kleines Feature!

**Comment by librelegal** [comment]
dieser issue ist bereits in Testing, obwohl 2 der vier Punkte in https://github.com/jlawyerorg/j-lawyer-org/issues/1419#issue-1038387211 noch nicht erledigt sind. Ich frage nur nach, damit das nicht versehentlich vergessen wird ...

**Comment by j-dimension** [comment]
@librelegal fertig entwickelt, zwei Tests offen, bzgl. welcher ich in der Mailingliste um Hilfe gebeten habe. Passt so.

**Comment by librelegal** [comment]
Funktioniert unter Windows 10, tolles feature!
