### ISSUE TITLE
[FEATURE] Mailkonten-Reihenfolge für Versand definieren

### ISSUE THREAD

**Issue by Linkki2021** [jlawyerorg/j-lawyer-org#1421]
Das neue Feature, mehrere Mailkonten einzubinden ist prima.

Eine Anregung hierzu: es sollte ein Preset geben, welches Mailkonto beim Versand vorausgewählt ist.

Ich habe zwei Postfächer: A & B

Wenn ich eine neue Mail verfasse ist bei mir automatisch B ausgewählt. Ich würde dort aber gerne A haben (weil ich es deutlich häufiger verwende). Momentan sehe ich keine Möglichkeit, das zu beeinflussen - außer evtl. den noch nicht getesteten Workaround, A zu löschen und neu anzulegen, damit es danach vll. das neue B und damit die Vorauswahl ist.

Umsetzungsvarianten wären mE zB
a) Reihenfolge in den Einstellungen=Reihenfolge im SchreibenVon-Dropdown. Dazu müsste man die Möglichkeit schaffen, die Einträge in den Einstellungen zu sortieren. Oder man gibt ihnen zusätzlich Werte wie 1,2,3, um die Reihenfolge zu bestimmen.
b) Es gibt in Einstellungen der Postfächer eine Checkbox "Standard-Konto für Versand". Dieses erscheint dann immer oben in den Liste. Wobei dann die nachrangige Sortierung immer noch offen wäre, sofern es mehr als 2 Postfächer sind.

**Comment by j-dimension** [comment]
Lösung sollte auch die Reihenfolge der Postfächer im Posteingang konfigurierbar machen.

**Comment by j-dimension** [comment]
@Linkki2021 es gibt hier bereits eine Automatik, die dafür sorgt dass bei einem Versand, der nicht Antwort oder Weiterleitung ist, das zuletzte verwendete Mailkonto vorselektiert ist. Das erscheint mir auch relativ sinnvoll. 

Szenario Bürogemeinschaft mit geteiltem Sekretariat: Dort würde - mit der aktuellen Automatik - die Bürokraft nacheinander für Anwalt A und dann für Anwalt B mailen können, ohne immer das Konto auswählen zu müssen. 

Wenn es jetzt ein Standardkonto gäbe, müsste man sich entscheiden ob jenes von A oder jenes von B der Standard wäre. Ist A Standard, muss bei Versand für B **IMMER** eine Auswahl des Versandkontos stattfinden. 

Ich denke da nochmal drüber nach, und bitte Euch das ebenfalls zu tun :-)
