### ISSUE TITLE
[BUG] Akte verlassen ohne WV => keine Meldung

### ISSUE THREAD

**Issue by iradraconis** [jlawyerorg/j-lawyer-org#1425]
Ich bekomme seit einiger Zeit beim Verlassen mancher Akten, in denen keine WV oder Frist oder sonst was offen ist, keine Warnung mehr, dass keine WV eingetragen ist. Soll das so? Ich bin mir grad nur nicht sicher, ob das schon immer so war :)

Antwort Jens: Konnte ich gerade reproduzieren. Vielleicht irgendein Seiteneffekt der
umfangreichen Kalenderarbeiten. Kannst Du ein Ticket dafür erstellen?

Danke!

=> Gerne!

**Comment by j-dimension** [comment]
Bug bestand seit geraumer Zeit, immer wenn an der Akte nichts geändert wurde, fehlte die Prüfung. Wurde irgendetwas in der Akte geändert, so wurde auch der Check ausgeführt.
