### ISSUE TITLE
[BUG] Datei in Akte importieren - Abbrechen bei doppeltem Namen 

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#1431]
ähnlich wie #912 

wenn ich mehrere lokale Dateien in die Akte ziehe und da ist schon eine Datei mit dem Namen, dann werde ich gefragt, ob ich sie umbenennen will.

![image](https://user-images.githubusercontent.com/29924198/139720138-66e70e40-4374-47bc-a8ea-500bf0310c14.png)

Zum einen sollte hier dem Nutzer erklärt werden warum, also was in der Art "Datei(name) schon vorhanden", zum anderen, deshalb Bug: Nimmt man Abbrechen, weil man die Datei für doppelt hält und nicht umbenannt in die Akte haben will, dann bricht der gesamte Vorgang ab, alle weiteren Dateien werden nicht in die Akte genommen. Hier wäre ein Button "Datei überspringen" hilfreich. Abbrechen könnte dann weiterhin komplett abbrechen.

**Comment by j-dimension** [comment]
Wird über #1225 gelöst
