### ISSUE TITLE
[BUG] Drebis-Nachricht verschwindet bei Abbruch während Dokumentbenennung

### ISSUE THREAD

**Issue by Linkki2021** [jlawyerorg/j-lawyer-org#1432]
Ich hatte gerade folgendes:
Aufruf drebis - Abholen Nachrichten - Speichern & Bestätigen einer neuen Meldung - Im dann aufgehenden Dialog zur Dokumentbenennung habe ich auf Abbrechen geklickt - Danach hat sich das Fenster aktualisiert und die Nachricht samt Anhang war weg. Im Drebis-Online-Portal kommt man auch nicht mehr ran, da die Nachricht dort auf "von Kanzleisoftware abgeholt" steht.
@j-dimension Unabhängig von der Fehlerbehebung, kommt man irgendwie noch an die Nachricht/Datei ran?

**Comment by j-dimension** [comment]
@Linkki2021 keine offensichtliche. Ich fürchte dass da nur ein Ticket an den Drebis-Support Klarheit schaffen kann... :-(

**Comment by j-dimension** [comment]
Behoben.
