### ISSUE TITLE
[BUG] Schriftgröße anpassen wirkt sich nicht auf alles aus

### ISSUE THREAD

**Issue by Dickmaulruessler** [jlawyerorg/j-lawyer-org#1436]
Die Anpassung der Schriftgröße unter "Ansicht" wirkt sich auf fast alles aus, ausgenommen aber die Beteiligtennamen und die Dokumentnamen. 

Hier am Beispiel "sehr klein" (-5), bleiben ebendiese groß. 
Gleiches wenn man auf "sehr groß" stellt, werden die Beteiligtennamen und Dokumentnamen nicht größer. 

![fafdsdasfdsfdsasdf](https://user-images.githubusercontent.com/46451749/140176325-4f65b2c2-c704-4b08-95c6-5d24de2727b1.jpg)

![dfsdafasdfdssfdfsafsd](https://user-images.githubusercontent.com/46451749/140176327-689fd783-b988-4a79-9501-63be9464d084.jpg)
 
Ich benötige diese Funktion _(noch)_ nicht, könnte mir aber vorstellen, dass die Vergrößerungsoption für manche mit Sehschwäche eine ganz hervorragende Sache ist (so wie auch das Detail damals mit der rot/grün-Schwäche). Und dann sind ebendiese Angaben zu Beteiligten- und Dokumentnamen auch besonders wichtig. 

--------------------------------------

(Und ich glaube die Vorschau-Funktion funktioniert nicht richtig. Irgendetwas tut sich da, zeigt aber glaube ich nicht die tatsächliche Größenveränderung. Das ist ein toller Service - muss aber auch nicht sein. Man kann auch ausprobieren. 

Falls das also nicht ohne Weiteres fehlerfrei zum Laufen bekommen werden kann, könnte die Vorschau meiner Meinung nach  auch entfallen.)
![fdsafsadfsadfsdasdfadsfas](https://user-images.githubusercontent.com/46451749/140177680-a94a9e19-6634-4792-a08f-f82560c8f3b8.jpg)

**Comment by j-dimension** [comment]
behoben via #556
