### ISSUE TITLE
Termin eintragen geht nicht

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-org#1438]
Ich sage erst einmal Danke für die neue J-lawyer-Version. Das Kalenderblatt ist ein super feature. Ich kann aber keinen Termin eintragen. Es kommt immer "Ungültiges Beginndatum / Zeit". Ist aber nichts ungültiges zu erkennen, ich wähle das Datum aus dem Kalender und dann die Beginn und Endezeit aus. Geht nicht. Ist hoffentlich keine Dublette, ich habe nichts vergleichbares finden können.

**Comment by j-dimension** [comment]
Bitte einen Screenshot hinzufügen. Danke

**Comment by Mucki526** [comment]
lässt sich heute Abend nach einem Neustart nicht reproduzieren. Wenn es wieder auftritt mache ich gleich einen screenshot.
