### ISSUE TITLE
[BUG] beA: Nachrichtenjournal im pdf gekürzt

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#1441]
ich habe eine bea-Nachricht an mich. Im Reiter Journal sieht das so aus:

![image](https://user-images.githubusercontent.com/29924198/140422185-236bf2b6-43fe-4f49-a9c3-eb8014c56861.png)

wenn ich aber ein pdf der Nachricht erstelle, dann hat das Journal nur noch einen Eintrag:

![image](https://user-images.githubusercontent.com/29924198/140422238-a23f9d07-1bea-4fd5-8701-ddb3a132576b.png)

**Comment by j-dimension** [comment]
Einträge des Typs MESSAGE_ABHOLEN_DER_NACHRICHT_KSW werden beim Generieren des PDFs entfernt. Wenn man Nachrichten längere Zeit im Posteingang belässt, gibt es bei jedem Abruf einen Journaleintrag. 

Die Einträge dieses Typs haben - im Gegensatz zu den anderen - keine wirklich hohe Aussagekraft.
