### ISSUE TITLE
[BUG] bea: Strukturdatensatz / EB mit fehlerhaften Umlauten

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#1442]
so sehen Strukturdatensatz / EB aktuell bei mir aus:

![image](https://user-images.githubusercontent.com/29924198/140423037-0e403427-abd7-406e-9999-1d8b6eafd6d1.png)

**Comment by j-dimension** [comment]
behoben via beA wrapper
