### ISSUE TITLE
[kalender] nicht vollständige Datumsangabe 

### ISSUE THREAD

**Issue by RobertT01** [jlawyerorg/j-lawyer-org#1445]
Die Anzeige des Datums bei Anlegen oder duplizieren einer Wiedervorlage erfolgt beim Tag nicht vollständig, wenn das Ausgangsdatum nur einstellig ist. 
![Wiedervorlage Ausgangsatum 8 11 2021](https://user-images.githubusercontent.com/36947879/140747303-8174de78-3139-4114-b72e-cd25fe06ffad.JPG)
![Wiedervorlage Ausgangsatum 8 11 2021 um 2 Wochen auf 22 11 2021 geändert](https://user-images.githubusercontent.com/36947879/140747314-a81d8301-88d9-4b5a-969b-51896ec5db95.JPG)

Beim Wiedervorlagedatum dem 22.11.2021 fehlen die Zehner des Tages.

**Comment by j-dimension** [comment]
Das kann ich spontan nicht reproduzieren: 

![grafik](https://user-images.githubusercontent.com/3729754/140813686-67255aba-8eca-4fa4-b066-9b3578e431df.png)

- Hat das System über die Windows-Einstellungen einen Skalierungsfaktor eingestellt, sowas wie 125%?
- auf welchem Wert steht die Skalierung im j-lawyer.org Client (Ansicht - Schriftgrössen)?

**Comment by papiertiger960ff** [comment]
ICh bekomme beim VErsuch, das Problem zu reproduzieren, das gleiche Ergebnis wie Jens.
Allerdings fällt mir in den Screenshots ein deutlicher Unterschied auf:

Sowohl bei Jens als auch bei mir scheint ein Datumsformat eingestellt zu sein, bei dem Tag und Monat stets zweistellig angezeigt werden (siehe Screenshot Nr. 3, dort steht „30.**0**1.2022“). Der THreadersteller hat hingegen ein Datumsformat, bei dem Tag und Monat ohne führende Null dargestellt werden (siehe Screenshot Nr. 1, dort steht im ersten Datumsfeld **2**.11.2021). Das abweichende Datumsformat dürfte dafür ursächlich sein, dass sich das Problem nicht reproduzieren lässt, weil die führenden Nullen dazu führen, dass alle Daten gleichlang sind.

Dazu kommt, dass im ersten Screenshot das zweite Datumsfeld leer ist. Das kriege ich bei mir auch nicht reproduziert. Wenn ich einen Termin ohne Enddatum anlege und dann den Dialog aufmache, steht dort immer ein automatisch ergänztes Enddatum drin. Dieses Enddatum dürfte in Konstellationen, wo die beiden Felder mit unterschiedlich langen Daten befüllt sind, ebenfalls dafür sorgen, dass das Problem nicht auftritt.

Was mir aber auch auffällt, ist, dass bei mir (anders als bei Jens) am Ende der beiden Datumsfelder noch ziemlich viel Platz ist. Ich könnte dort problemlos ein Datum mit zweistelligem Monat, zweistelligem Tag und sechsstelliger Jahreszahl unterbringen, womit j-lawyer auch in 100000 (hunderttausend) Jahren noch nutzbar wäre
![temp_Screenshot_20211213_215728](https://user-images.githubusercontent.com/85453166/145897915-536d6874-e1f1-40d8-8672-bd21e4bd58fc.png)
.

**Comment by j-dimension** [comment]
@papiertiger960ff ich glaube das Format ist beim Ticketersteller das gleiche, der 2.11.2012 also eigentlich der 12.11.2021.

Ohne Antworten von @RobertT01 auf die Fragen kommen wir hier nicht weiter:

- Hat das System über die Windows-Einstellungen einen Skalierungsfaktor eingestellt, sowas wie 125%?
- auf welchem Wert steht die Skalierung im j-lawyer.org Client (Ansicht - Schriftgrössen)?
- Bilschirmauflösung?

**Comment by papiertiger960ff** [comment]
Ich bitte um Enschuldigung, ich muss aufgrund eines Büroversehens die beiden Screenshots verwechselt haben. Nochmal langsam: So wie ich den Ticketersteller verstehe, steht im ersten Screenshot der **8**.11.2021, dann hat der TE auf „**2 Wochen**“ geklickt und den **22**.11.2021 bekommen, der nun als **2**.11.2021 falsch dargestellt wird. Das macht eigentlich Sinn, weil 8+14 zumindest nach der Mathematik, die ich in der Grundschule gelernt habe, 22 ergibt und weil es da steht (ganz am Ende unter dem 2. Screenshot). Aber vielleicht liege ich ja auch falsch. (Ich bin mit der juristischen Mathematik, falls es sowas gibt, und dem Grundsatz „Iudex non calculat“ (lat.: Richter können nicht rechnen) nicht sonderlich vertraut, daher könnte es dort Aspekte geben, die mir bisher entgangen sind.)

**Comment by j-dimension** [comment]
Ja, wenn ICH das jetzt nochmal in Ruhe anschaue: Sie haben völlig recht :-)

**Comment by RobertT01** [comment]
Hallo an die Beteiligten,

ich hoffe, ich antworte in der richtigen Runde.

Skalierung bei Windows ist auf 100 %.
Skalierung beim j-lawyer bei Maximum, d.h. 5
Bildschirmauflösung ist bei Full-HD, d.h. 1920 x 1080

Diese Daten werden angewandt bei Nutzung jeweils eines 27`und eines
24´Monitors.
Bei der Nutzung eines 30`und 24` Monitors ändert sich die
Windows-Skalierung auf 150 %.



Am 13.12.2021 um 23:23 schrieb Jens Kutschke:

**Comment by RobertT01** [comment]
hier noch die zugehörigen screenshots

Am 13.12.2021 um 23:23 schrieb Jens Kutschke:

**Comment by j-dimension** [comment]
An alle: tritt das mit der 2.1 noch auf?
