### ISSUE TITLE
[BUG] Verzögerte Anmeldung

### ISSUE THREAD

**Issue by Linkki2021** [jlawyerorg/j-lawyer-org#1446]
Ich bin mir nicht sicher, inwiefern es sich tatsächlich um einen Bug handelt. Seit dem Update auf 2.0 hänge ich beim Login immer wieder an der gleichen Stelle (siehe Screenshot) - mal kürzer, mal länger (bis zu ca. 45 Sekunden, das aber bislang nur einmal).

Das ist jetzt nicht direkt schlimm, aber in jedem Fall anders als zuvor. 

![image](https://user-images.githubusercontent.com/77149788/140774525-45041aea-4f89-4053-a784-8e7a704526c6.png)

**Comment by j-dimension** [comment]
In Version zwei habe ich von Java 8 auf 11 aktualisiert, und dort gibt es scheinbar Probleme beim Darstellen von Baumstrukturen. Es gibt bereits ein entsprechendes Ticket: https://github.com/jlawyerorg/j-lawyer-org/issues/1416

Ich habe diesbezüglich in Version 2.0.1 Änderungen vorgenommen, die das zumindest etwas entschärfen. Habt Ihr die bereits installiert? 

Man kann die Wartezeit auch verringern wenn man nicht benötigte Ordner im E-Mail-Posteingang ausblendet (das wird seit Version 2 auch gespeichert und wiederhergestellt). DAs verringert die Größe der Ordnerhierarchie und hilft ebenfalls.
