### ISSUE TITLE
Bug: Client 2.0.1 - E-Mail - Postfachordner werden nicht vollständig geladen

### ISSUE THREAD

**Issue by iradraconis** [jlawyerorg/j-lawyer-org#1449]
Seit der aktuellen Version werden bei mir die Ordner im E-Mail Postfach nicht mehr richtig angezeigt, wenn ich nach dem Start des Clients in den E-Mail Bereich gehe. Ich muss dann oben auf neu laden klicken, damit überhaupt der Posteingang angezeigt wird. Ich nutze Mailbox.org und habe aktuell zwei E-Mail Postfächer unter meinem Nutzer eingerichtet. Das Problem besteht tatsächlich erst seit dem letzten Update.

**Comment by j-dimension** [comment]
Heute Rückmeldung von einem weiteren Nutzer mit mailbox.org - Konto und gleichem Problem. Seltsam.

@iradraconis funktioniert denn der Versand? Es geht nur um das Laden der Ordner, oder?

**Comment by iradraconis** [comment]
Es funktioniert alles so wie es soll, bis auf das Laden der Ordner. Das aber auch nur beim Start des Clients. Danach funktioniert es in der Regel.

**Comment by iradraconis** [comment]
> Es funktioniert alles so wie es soll, bis auf das Laden der Ordner. Das aber auch nur beim Start des Clients. Danach funktioniert es in der Regel.

Korrektur: während der Benutzung des Clients, taucht das Problem auch wieder auf, trotz dass vorher mal neu geladen war

**Comment by j-dimension** [comment]
@iradraconis kannst Du mal diese Datei austauschen und rückmelden ob es das Problem behebt?

https://cloud.j-dimension.com/index.php/s/wscJLx3KDCKoEWm?path=%2FVorschau%2FClient

Danke!

**Comment by iradraconis** [comment]
Ich muss das kommende Woche an meinem Arbeitsplatz probieren. Über Fernzugriff per VPN und unter MacOS funktioniert es nämlich gerade ohne diese Datei.

**Comment by iradraconis** [comment]
Problem scheint mit der neuen .jar behoben. Werde berichten, falls nicht.

**Comment by j-dimension** [comment]
Vielen Dank, @iradraconis !

**Comment by Mucki526** [comment]
Also, bei mir ist gerade folgendes passiert. Ich habe zwei e-mail accounts eingerichtet. Auf der E-mail Seite erschienen Ordner nicht beim ersten angezeigten e-mail account (z.B. Empfangsordner), Ein Test funktionierte aber für die e-mailadresse. Nur das Ein und Ausklappen aller Ordner funktionierte nicht, nur für den zweiten unteren Account.. Aktuallisieren brachte auch nichts. Erst nach dem Schließen beider Ordnernsichten für beide e-mail accounts konnte die Ordneransicht für den oberen ersten e-mail account wieder vollständig ausgeklappt werden.

**Comment by Mucki526** [comment]
Ist Reproduzierbar
![grafik](https://user-images.githubusercontent.com/37142896/143560177-1c233be1-e1f1-447d-bb08-6750f584d194.png)

**Comment by j-dimension** [comment]
@Mucki526 das Ticket ist bereits geschlossen und ein neues Release verfügbar. Wenn Du vor dem 16.11. installiert hast, lass bitte nochmal den Client-Installer laufen: https://www.j-lawyer.org/?page_id=17
