### ISSUE TITLE
[BUG] Buttons von Kontakt-Schnellerfassung verschwinden bei Veränderung der Fenstergröße

### ISSUE THREAD

**Issue by Dickmaulruessler** [jlawyerorg/j-lawyer-org#1450]
Das Fenster für die Kontakt-Schnellerfassung lässt sich in der Größe verändern, so dass dann auch die Buttons "Übernehmen" und "Schließen" verschwinden. Ein Scrollbalken aktiviert sich nicht automatisch. 

Sollte die Möglichkeit zur Größenveränderung deaktiviert oder jedenfalls ein automatischer Scrollbalken aktiviert werden?

![jkljsdkljfklsjfklajdslöjasfasa](https://user-images.githubusercontent.com/46451749/141304857-0fcdedbd-aded-484d-9fdc-2021b5e33091.jpg)

**Comment by j-dimension** [comment]
Ich habe das angeschaut. Scrollverhalten habe ich grundsätzlich überall dort, wo man nicht weiß wieviele Daten dargestellt werden könnten. Das ist ein einem reinen Eingabedialog nicht der Fall. Der muss bei initialer Darstellung vollständig sein. Wenn er dann kleiner gezogen wird, habe ich ja aber keine Möglichkeit, irgendwelche Felder "rauszunehmen". Aber zumindest weiß der Nutzer ja, dass dort Buttons sind, er hat sie ja explizit "versteckt". 

Alle Dialog scrollfähig zu machen ist mir zu viel Aufwand. 

Okay?

**Comment by Dickmaulruessler** [comment]
Jo, ich kann damit gut leben. Danke fürs prüfen!
