### ISSUE TITLE
[beA] Nachricht vom Gericht doppelt?

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-org#1451]
Ich habe eine BEA Nachricht (Ladung) vom Gericht gerade scheinbar doppelt erhalten, also zweimal, in der Weboberfläche des BEA ist die Nachricht aber ganz normal nur einmal eingegangen....

**Comment by j-dimension** [comment]
Auch nach einem Neuladen des Ordners?

**Comment by Mucki526** [comment]
Ist nochmals aufgetreten für alle Nachrichten im Ordner gleichzeitig, nach einem Neuladen der Nachrichten wars wieder o.k.. Es waren ca. 11 Nachrichten im BEA, das sind eigentlich 7-8 zuviel, da die jedesmal neu geladen werden, wenn man sich mit dem BEA neu verbinden muss. Das Laden (nachladen) von Nachrichten dauert unfassbar lange, (wie damals zu Modemzeiten) blockiert dabei das BEA und teilweise auch j-lawyer.

**Comment by j-dimension** [comment]
> Das Laden (nachladen) von Nachrichten dauert unfassbar lange, (wie damals zu Modemzeiten) blockiert dabei das BEA und teilweise auch j-lawyer.

@Mucki526 

Das ist ein Fehler in einer Bibliothek der BRAK, siehe #1406.

Du kannst testweise mal den Ordner C:\Benutzer\NUTZERNAME\AppData\Local\Temp\beaToolkit löschen, das sollte eine spürbare Verbesserung bringen.

**Comment by Mucki526** [comment]
Wenn morgen Weihnachten wäre, wünschte ich mir ein Forum, in dem man seinen BEA-Frust der zuständigen Crew mitteilen könnte, damit die was ändern, aber die ganze Erstellung des BEA durch die BRAK ist derart unnahbar. Die sollten sich an J-lawyer ein Beispiel nehmen. Sonst wird da nix besser. Und wie die Geschwindigkeit / Bandbreite reichen soll, wenn ein ein paar Jahren auch die Gerichte mitfunken und alle BEA machen müssen, ist mir zumindest im Moment schleierhaft. Danke für den Tipp mit dem Ordner, den probiere ich gleich aus, Sollte sich als Temp-Ordner doch eigentlich alleine löschen??

**Comment by Mucki526** [comment]
knapp 30.000 Dateien gelöscht in dem Temp-Ordner.....!!! Es scheint schneller. Mal sehen, wie schnell der Ordner wieder vollläuft....

**Comment by Mucki526** [comment]
Ich lösche diesen Ordner (die tmp-Dateien) jetzt einfach automatisch alle 14 Tage.....

**Comment by j-dimension** [comment]
@Mucki526 ist dieses doppelte Erscheinen einer Nachricht nochmal aufgetreten?
