### ISSUE TITLE
[BUG] Neues Mailpostfach nach Erstellung automatisch selektieren

### ISSUE THREAD

**Issue by Dickmaulruessler** [jlawyerorg/j-lawyer-org#1452]
(Hmmmmm... weiß nicht, ob ich mich zu doof anstelle - ´halte ich nicht für ganz ausgeschlossen - ´glaube ich aber eher nicht...)

Also: Ich wollte erstmals über Einstellungen / E-Mail-Postfächer meine E-Mailkonfiguration erstellen. Das habe ich auch alles getan (IMAP). Der Test verlief erfolgreich. Auf meinem PC traf unter Outlook "Wenn Sie diese Nachricht erhalten, funktioniert der Versand von E-Mails." ein. 
Ich habe in der JL-E-Mail-Konfiguration auf "übernehmen" und "schließen" geklickt. 

Danach war das Postfach aber nicht gespeichert....

Das ganze habe ich sicherheitshalber wiederholt, dabei hatte ich also sicher auf "übernehmen" und "schließen" geklickt. 
Das Postfach ist aber immer noch nicht da. Auch nicht nach einem Client-Neustart.

**Comment by Dickmaulruessler** [comment]
(Nur am Rande: Die Buttons verschwinden auch hier bei kleiner Fenstergröße, siehe auch #1450)

**Comment by j-dimension** [comment]
Man muss nach Anlage des Postfaches nochmal links in der Tabelle draufklicken, dann die Konfiguration ändern und speichern. 

Ich mache das so, dass nach Neuanlage die Zeile / das Postfach automatisch selektiert wird.

**Comment by Dickmaulruessler** [comment]
ja, unter "Einstellungen" ist das Postfach dann vorhanden. 

Eine Mail kann ich dann jedoch noch nicht versenden. 

Und zwar weder direkt im linken E-Mail-Menü ("neue E-Mail schreiben" funktioniert nicht) ....

...noch direkt aus der Akte heraus über den rechten Mausklick "senden" (Fehlermeldung: "E-Mail ist für diesen Nutzer nicht konfiguriert"). Nach Klick auf "OK" kommt das Fenster "neue E-Mail", in welchem im Pulldown "Von" gar kein Eintrag vorhanden ist.

**Comment by j-dimension** [comment]
Dann fehlen dem Nutzer noch die Rechte:

http://www.j-lawyer.org/downloads/documentation/j-lawyer.org-UserGuide-de.html#__RefHeading__114_1146603382

**Comment by Dickmaulruessler** [comment]
> 
> 
> Dann fehlen dem Nutzer noch die Rechte:
> 

Jep, funktioniert! Danke!
