### ISSUE TITLE
Frage: JAVA auf M1 Macs. Performance nutzen?

### ISSUE THREAD

**Issue by iradraconis** [jlawyerorg/j-lawyer-org#1454]
Da ich über die technischen Hintergründe nur wenig weiß, stelle ich einmal hier die Frage: 

Vorab: solange Java über Rosetta läuft, dürfte es ja insgesamt langsamer sein als eine native Java Runtime. 

Ich habe heute eine native Java Runtime (Liberica) auf meinem MacBook installiert. Parallel ist auch noch die Standard x86 Java Runtime installiert. Möglicherweise auch die, die J-Lawyer beim Installieren mitinstalliert hat.

Kann irgendwie eingestellt werden, welche Runtime der Client nutzt? Die längere Akkulaufzeit und die bessere Performance bei nativer Nutzung würden mich interessieren.

Macht es performancemäßig mehr Sinn, auch den Server auf M1 laufen zu lassen? Insgesamt meine ich, dass die Performance außerhalb von Linux etwas verbesserungsfähig ist :)

**Comment by j-dimension** [comment]
Thema ist bereits erfasst als #1069.

Manuell würde ich da als Anwender nicht experimentieren, möglich ist es aber.
