### ISSUE TITLE
[BUG] Einträge im Akten-Kalender werden nicht sofort sortiert

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#1458]
Ich verschiebe eine Frist im Kalender, aber die Frist wird nicht dem neuen Datum entsprechend einsortiert. Auch wenn ich die Reiter wechsle und zurück zum Kalender gehe, bleibt es. Erst ein Schließen und neuöffnen der Akte macht die richtige Sortierung:

![image](https://user-images.githubusercontent.com/29924198/141850370-fcb55eff-bd7b-4ea6-97da-e48ae779141e.png)

**Comment by j-dimension** [comment]
Dann würden bei vielen Einträgen der editierte Eintrag evtl. komplett aus dem sichtbaren Bereich verschwinden, das wäre keine "UI best practice". 

Du kannst auf den Spaltenheader klicken und so eine Neusortierung erzwingen.
