### ISSUE TITLE
[TASK] Verbindungsprofil -  aus Zwischenablage importieren - aber wie exportieren?

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#1459]
Wofür ist eigentlich dieses importieren des Verbindungsprofils aus Zwischenablage? Und bräuchte es dann nicht auch einer Exportfunktion? Ich wüßte gar nicht, wie so ein Profil als plain text aussehen müßte, damit es importiert werden kann!?

**Comment by j-dimension** [comment]
> Wofür ist eigentlich dieses importieren des Verbindungsprofils aus Zwischenablage?

Gedacht für Fälle in denen man Nutzern das Ausfüllen der vielen Verbindungsparameter ersparen will.



> Ich wüßte gar nicht, wie so ein Profil als plain text aussehen müßte, damit es importiert werden kann!?

<NUTZERVERZEICHNIS>\.j-lawyer-client\connections

Dort findest du die Profile, sie lassen sich mit einem Texteditor öffnen.
