### ISSUE TITLE
[TASK] Platzhalter/Template Engine

### ISSUE THREAD

**Issue by Linkki2021** [jlawyerorg/j-lawyer-org#1461]
Derzeit ist bei den Platzhaltern ja die Möglichkeit gegeben, einen jeweilig definierten Wert in eine Vorlage zu übernehmen.

Welche Template Engine findet denn bei jlawyer Anwendung? Gibt es ggf. über die Engine auch die Möglichkeit, komplexere Vorgänge (if/else) zu gestallten?

Also beispielsweise wenn {{xyz}}=ja dann setze ein "ABC".

Danke fürs Feedback

**Comment by j-dimension** [comment]
@Linkki2021 bereits in Arbeit: https://github.com/jlawyerorg/j-lawyer-org/issues/1078

Es gibt dort auch bereits ein Video (runterscrollen)

**Comment by Linkki2021** [comment]
Cool, danke, hatte das Issue beim Suchen nicht gefunden.
