### ISSUE TITLE
[BUG] [beA] eEB zeigt falsches Datum und keinen Inhalt 

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#1465]
Ich habe ein eEB mit jl abgegeben.

Wenn ich die eEB-ERV-Nachricht anklicke und da mir das eEB / Strukturdatensatz anzeigen lasse, dann ist da a) kein Dokument aufgelistet und b) mit dem 27.9.2021 ein Abgabe-Datum angezeigt, was überhaupt nicht paßt und auch in der xml-Rohdatei nicht auftaucht. in beA-Web wird alles sauber angezeigt.

![image](https://user-images.githubusercontent.com/29924198/142778523-21b20ade-89b9-408b-b27e-7d95e89e64b1.png)

`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><ns2:nachricht.eeb.zuruecklaufend.2200007     xmlns:ns2="http://www.xjustiz.de"     xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"     xsi:schemaLocation="http://www.xjustiz.de xjustiz_2200_eeb_3_0.xsd">    <ns2:nachrichtenkopf xjustizVersion="3.2.1">        <ns2:aktenzeichen.absender>xxx</ns2:aktenzeichen.absender>        <ns2:aktenzeichen.empfaenger>S xxxx/21</ns2:aktenzeichen.empfaenger>        <ns2:erstellungszeitpunkt>2021-11-21T21:36:15</ns2:erstellungszeitpunkt>        <ns2:auswahl_absender>            <ns2:absender.sonstige>DE.BRAKxxx</ns2:absender.sonstige>        </ns2:auswahl_absender>        <ns2:auswahl_empfaenger>            <ns2:empfaenger.sonstige>govello-12xxxx</ns2:empfaenger.sonstige>        </ns2:auswahl_empfaenger>        <ns2:eigeneNachrichtenID>0xxxxx8d9f7e28a</ns2:eigeneNachrichtenID>        <ns2:fremdeNachrichtenID>54Axxxx41E82EC</ns2:fremdeNachrichtenID>    </ns2:nachrichtenkopf>    <ns2:fachdaten>        <ns2:empfangsbestaetigung>2021-11-15</ns2:empfangsbestaetigung>    </ns2:fachdaten></ns2:nachricht.eeb.zuruecklaufend.2200007>`

**Comment by librelegal** [comment]
Ergänzend noch folgende Beobachtung (bei Nutzung der Entwickler-Version 2.1, aber wohl auch bei der 2.0.1): Die Beobachtung von stm9x9 trifft zu, bei Anzeige der Naxchricht als pdf wird das seltsame Datum 27.9. nicht angezeigt. 
In beiden Darstellungen wäre die Anzeige der Nachrichten-ID hilfreich, um sicher zu sein, worauf sich das eEB überhaupt bezieht.

**Comment by j-dimension** [comment]
Die fehlende Dokumentenliste ist in #917 erfasst. Die falsche Datumsangabe wird mit diesem Ticket hier korrigiert.
