### ISSUE TITLE
[QUESTION] Dokument-Verschiebe-Modus?

### ISSUE THREAD

**Issue by Dickmaulruessler** [jlawyerorg/j-lawyer-org#1469]
In der Dokumentansicht wechselt der Mauszeiger beim Mouseover vom Zeige- in den Verschiebemodus (Screenshot ist davon nicht möglich). 

Ist das gewollt und wenn ja wofür? Soweit ersichtlich kann ich nichts verschieben.

![dsdfsdafdfdasasdfsdf](https://user-images.githubusercontent.com/46451749/143467112-04500479-2421-40da-9294-81da701c4667.jpg)

![dskflösad](https://user-images.githubusercontent.com/46451749/143467262-0c15fb18-51cb-4f37-859a-fe6364fa39ac.jpg)

**Comment by j-dimension** [comment]
Interessant. Das scheint nur unter Windows und nur über dem Icon so zu sein.

**Comment by Dickmaulruessler** [comment]
ja, nur über dem einen Icon.

**Comment by j-dimension** [comment]
Ich glaube ursprünglich wollte ich die Ordnerzuordnung per Drag&Drop nur über das Icon zulassen, habe das aber später revidiert. Ich passe den Cursor an.
