### ISSUE TITLE
Nutzer-/Gruppenverwaltung in Menü "Administration" verschieben

### ISSUE THREAD

**Issue by Dickmaulruessler** [jlawyerorg/j-lawyer-org#1471]
Sorry, ich immer mit meinen pingeligen Mini-Kleinigkeiten.... :-)

Die Nutzer-**_verwaltung_** heißt im Menü unter "Einstellungen" nur "Nutzer". Mit der Ergänzung "verwaltung" ist dieser - obendrein wichtige - Punkt glaube ich besser beschrieben. Tatsächlich heißt es dort auch so.

![fkldsjfklösdajklföjjsdfjklfasö](https://user-images.githubusercontent.com/46451749/143481325-d71bf6f6-2bfc-45c3-9073-19d8d3e9cce5.jpg)

![jkldfsöjfklöjklsdaa](https://user-images.githubusercontent.com/46451749/143481298-a6d9761c-dd44-4352-8229-692fbd8002b0.jpg)

**Comment by j-dimension** [comment]
So war das früher gar mal benannt. 

Mit der Einführung der Gruppen habe ich es in "Nutzer" umbenannt, weil ich nicht "Gruppenverwaltung" nutzen wollte, das aber sonst inkonsistent gewesen wäre. Hatte ich da an anderen Softwareprodukten orientiert.

**Comment by Dickmaulruessler** [comment]
Ja, das ist nicht einfach. "Nutzerprofil" und zwei darunter "Nutzer" in den Einstellungen ist auch irgendwie inkonsistent. Naja, die Bezeichnung ist aber natürlich nur unwichtige Erbsenzählerei.... (Ich kam darauf, da heute über die Mailingliste eine Frage kam, die von dir dann an die Nutzerverwaltung verwies und mir dann auffiel, dass dieser wichtige Punkt ein klein wenig zu versteckt ist...)

**Comment by j-dimension** [comment]
Mit der 2.1 gibt es ja ein neues Menü "Administration" - vielleicht könnte man "Nutzer" auch einfach dorthin verschieben, da es nicht wirklich eine Einstellung ist.

**Comment by j-dimension** [comment]
Vielen Dank, @Bentipa !

**Comment by stm9x9** [comment]
ggf überhaupt Einstellungen, die nur der Admin vornehmen kann, gesondert lokalisieren? Ebne zb in Administration.

**Comment by j-dimension** [comment]
> ggf überhaupt Einstellungen, die nur der Admin vornehmen kann, gesondert lokalisieren? Ebne zb in Administration.

Dafür gibt es in der Tat ein Ticket, das darauf abzielt zwischen einem fachlichen und einem technischen Admin zu unterscheiden.
