### ISSUE TITLE
[BUG] Fehler beim Holen der beA-Nachricht

### ISSUE THREAD

**Issue by socram70** [jlawyerorg/j-lawyer-org#1476]
1. Öffnen der beA-Nachricht

**NOTE: Please search existing tickets to avoid duplicates **
**HINWEIS: Bitte vorab die Ticketsuche verwenden, um Doppeleinträge zu vermeiden **

**Describe the bug / Fehlerbeschreibung**
(todo: a description of the bug / eine Beschreibung des Fehlers)

**To Reproduce / Schritte zum Nachvollziehen**

1. Go to / Gehe zu: Öffnen der beA-Nachricht
2. Klicke auf / Click on: Klicken oder Doppelklicken auf die Nachricht
4. Error message / Fehlermeldung: Fehler beim Holen der beA-Nachricht: org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Content ist nicht zulässig in Prolog.

**Expected behavior / Erwartetes Verhalten**
Eine Beschreibung des erwarteten Verhaltens.
Zu erwarten wäre das Öffnen der Nachricht. Die Nachricht lässt sich in der Weboberfläche des beA öffnen.

**Screenshots**
Falls relevant, Screenshot beifügen.
![grafik](https://user-images.githubusercontent.com/60073801/144271587-466270d3-622f-4924-91de-f64b3f246905.png)

**Environment / verwendete Umgebung:**
 - OS / Betriebssystem: Windows 10 x64 - 
 - j-lawyer.org Version: Server: 2.0.1.0; Client: 2.0.1.0; beA-Wrapper-Version: 3.7.0.0

**Additional context / Sonstiges**

**Comment by j-dimension** [comment]
Duplikat von #1457 

Da es verschiedene Varianten gibt, bitte client.log bereitstellen.
