### ISSUE TITLE
Anzeige e-mail Konten

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-org#1482]
Trotz Installation des aktuellesten Release des clients, wie mir geraten wurde, sind immer wieder bei zwei e-mail accounts, die ich angemeldet habe, nicht alle Einträge sichtbar. Abhilfe und Neuaufbau der vollständigen Ansicht ist dann nur dadurch möglich, dass man die Ansichten (Auflistung) beider Konten schließt und eine Aktualisierung macht. Dann geht´s wieder....

**Comment by j-dimension** [comment]
Duplikat von #1449 
Bitte keine neuen Tickets für existierende Themen. 

In #1449 bitte das Änderungsdatum der j-lawyer-client.jar im Installationsverzeichnis mitteilen. Danke
