### ISSUE TITLE
[FEATURE] beA Anzeige Versandstatus

### ISSUE THREAD

**Issue by j-dimension** [jlawyerorg/j-lawyer-org#1488]
Nachrichtenansicht - verschiedene Icons:

1. empfangene Nachricht: neutral
2. versendete Nachricht mit "gutem" Journal an Nicht-EGVP: grün
3. versendete Nachricht mit "schlechtem" Journal an Nicht-EGVP: rot
4. versendete Nachricht mit "gutem" Journal und gutem Laufzettel an EGVP: grün
5. versendete Nachricht mit "gutem" Journal und fehlendem Laufzettel an EGVP: orange
6. versendete Nachricht mit "schlechtem" Journal oder schlechtem Laufzettel an EGVP: rot

**Comment by Dickmaulruessler** [comment]
Das wird ein sehr wertvolles neues Feature sein! 

Danke dir!

**Comment by j-dimension** [comment]
Doku: 
- nicht zuverlässig im "Gesendet"-Ordner, aber für alle Nachrichten die nach dem Versand automatisch einer Akte zugeordnet worden sind (Ursache: EGVP-Laufzettel kann nur einmal abgerufen werden)
- keine Haftung für falsche Anzeige - bisher nur Rohdatenanzeige (Journal, Laufzettel), jetzt Interpretation der Rohdaten. Die ist nicht immer 100%ig richtig, da das beA z.B. keine MÖglichkeit bietet zu erkennen, ob es sich um ein EGVP handelt oder nicht.

**Comment by stm9x9** [comment]
> * ob es sich um ein EGVP handelt oder nicht.

was heißt in dem Kontext EGVP? Gericht? Behörde? Im Gegensatz zu beA-intern? oder was ist zb ein beN in dem System?

**Comment by j-dimension** [comment]
> was heißt in dem Kontext EGVP? Gericht? Behörde? Im Gegensatz zu beA-intern? oder was ist zb ein beN in dem System?

Gericht auf alle Fälle. Den Rest kann ich Dir nicht beantworten, müsste recherchiert werden wie diese angebunden sind (über die Intermediäre der Länder? Anderswie?)

**Comment by stm9x9** [comment]
andersrum gefragt: was genau meinst du mit dieser Unterscheidung? Geht es dir darum, ob ein Laufzettel generiert und zurückgeliefert wird bzw. daraus der 0800er-Code erzeugt wird?

Da denke ich mal, müßte alles, was das beA-System verläßt, mit uns "EGVP sprechen". Denn das ist ja die Schnittstelle, die gemeinsame Sprache aller System da dran. Nur beA-intern von Anwalt zu Anwalt braucht sich beA nicht daran zu halten und macht sowas wie Laufzettel nicht. Hier bleibt ja alles auf einem Server, so daß der Eingang direkt bestätigt werden kann.

**Comment by j-dimension** [comment]
> was genau meinst du mit dieser Unterscheidung?

Unterscheidung zwischen EGVP und Journal meinst Du? Das sind ja letztlich zwei gleiche Konzepte mit den gleichen Informationen. Mir ist nicht klar, ob und wann beide voneinander abweichen können, und dokumentiert ist das auch nicht. Wenn beides da ist, prüfe ich beides. Ich kann mich aber auch nicht auf das Vorhandensein verlassen, daher muss ich prüfen i.S.v. "wenn EGVP aber kein Laufzettel" = böse
