### ISSUE TITLE
Zeichenbeschränkungen bei Aktennotizen

### ISSUE THREAD

**Issue by ms00st** [jlawyerorg/j-lawyer-org#1489]
In den Aktennotizen ist es nicht möglich mehr als 299 Wörter einzugeben. 

Kann man diese Beschränkung aufheben?

**Comment by j-dimension** [comment]
@ms00st aktuell nicht. Bitte mal hier reinlesen: https://github.com/jlawyerorg/j-lawyer-org/issues/938

Grüße!

**Comment by Dickmaulruessler** [comment]
@ms00st in obigem Nr.938 mit [Alternative](https://github.com/jlawyerorg/j-lawyer-org/issues/938#issuecomment-776896357):
