### ISSUE TITLE
[FEATURE] durchgängig gleiche Dateisymbole, um auch unter Windows eines für beA-Nachrichten zu haben

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#1490]
Aktuell haben gespeicherte .bea-Dateien ein leeres / weißes Dokument als Symbol:

![image](https://user-images.githubusercontent.com/29924198/145114863-d7fe1577-8a5e-4c41-8ba2-cd60086d22fa.png)

Schön wäre es, wenn sie - wie Word oder pdf-Dateien - ein eigenes Symbol erhielten. Zb der beA-Schriftzug. Und in Kombination mit #1488 könnte die Farbe auch gleich den Status anzeigen:

![image](https://user-images.githubusercontent.com/29924198/145114750-f70d9457-5a83-497b-bbdf-ff1d0a68986c.png)

**Comment by j-dimension** [comment]
> Schön wäre es, wenn sie - wie Word oder pdf-Dateien - ein eigenes Symbol erhielten.

Das haben Sie, allerdings nur auf Mac und Linux. Sieht dann so aus:

![grafik](https://user-images.githubusercontent.com/3729754/145115744-da407afd-93b3-449e-8c8c-025c962a8474.png)

Hintergrund: unter Windows gibt es eine API, die die Icons des Systems zurückliefert. ein PDF bekommt dann bei einem Nutzer von Acrobat eben Icon A, bei einem Nutzer von Foxit Icon B. Für .bea hat Windows dann aber kein Icon, daher ein "Standardicon".

Auf Mac / Linux gibt es die API nicht, daher rendere ich dort immer eigene Icons.

**Comment by j-dimension** [comment]
> Und in Kombination mit #1488 könnte die Farbe auch gleich den Status anzeigen:

Eher nicht. Für das Anzeigen der Liste fragt der Client nur die Metadaten der Dokumente ab. Der Versandstatus steckt aber in den Dokumenten selbst, die müssten dann alle (alle .beA) ausgewertet werden, was bei großen Akten zu teuer ist. 

Ließe sich nur lösen, indem man den Versandstatus als extra Metadatenattribut separat speichert.

**Comment by stm9x9** [comment]
> Auf Mac / Linux gibt es die API nicht, daher rendere ich dort immer eigene Icons.

könntest du die API dann im Falle einer .bea-Datei auf Windows umgehen?

**Comment by j-dimension** [comment]
Theoretisch schon, nur versuche ich das - wann immer möglich - zu vermeiden. Plattformspezifischer Code bedeutet leider auch den Testaufwand zu multiplizieren.

**Comment by stm9x9** [comment]
> Ließe sich nur lösen, indem man den Versandstatus als extra Metadatenattribut separat speichert.

hätte ggf den Vorteil, daß du den Versandstatus nicht auch beim Öffnen einer bea-Datei jedesmal neu herausfinden müßtest. Der Status ist ja eher statisch und müßte bei einem extra Attribut nicht laufend überprüft werden, oder?

**Comment by stm9x9** [comment]
> Theoretisch schon, nur versuche ich das - wann immer möglich - zu vermeiden. Plattformspezifischer Code bedeutet leider auch den Testaufwand zu multiplizieren.

Dann schmeiß den Sonder-Code für Windows raus und rendere die Icons überall selber :-D

**Comment by j-dimension** [comment]
> > Ließe sich nur lösen, indem man den Versandstatus als extra Metadatenattribut separat speichert.
> 
> hätte ggf den Vorteil, daß du den Versandstatus nicht auch beim Öffnen einer bea-Datei jedesmal neu herausfinden müßtest. Der Status ist ja eher statisch und müßte bei einem extra Attribut nicht laufend überprüft werden, oder?

und den Nachteil dass das Metadatenmodell auf einmal dateitypspezifisch wird.

**Comment by j-dimension** [comment]
> > Theoretisch schon, nur versuche ich das - wann immer möglich - zu vermeiden. Plattformspezifischer Code bedeutet leider auch den Testaufwand zu multiplizieren.
> 
> Dann schmeiß den Sonder-Code für Windows raus und rendere die Icons überall selber :-D

Damit könnte ich in der Tat gut leben! Finde die j-lawyer-eigenen größeren Icons auch viel hübscher als die kleinen :-)

**Comment by Dickmaulruessler** [comment]
Das technische oben habe ich nicht verstanden, aber ein beA-Icon würde ich auch schön - und wirklich hilfreich! - finden.

**Comment by j-dimension** [comment]
Es werden nun überall die j-lawyer-eigenen Symbole benutzt. Das führt dazu dass (a) sich Windows-Anwender erst neu dran gewöhnen müssen und (b) einige andere Dateien evtl. kein Symbol mehr haben (bspw. irgendwelche exotischen Dateitypen). 
Die muss ich dann nach und nach nachpflegen / Icons erstellen.
