### ISSUE TITLE
[FEATURE] Honorarstufen für Mitarbeiter

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#1492]
Die Kanzleien, die mit Zeithonoraren arbeiten, haben oft je nach Mitarbeiterstatus unterschiedliche Stundensätze. Die könnte man beim Mitarbeiter hinterlegen, um die Rechnungsstellung zu vereinfachen.

Anschauungsbeispiel: https://www.a-jur.de/zeiterfassung.htm#Stufe

**Comment by j-dimension** [comment]
ist in #58 als Anforderung erfasst.
