### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#1494]
ich war mir sicher, es schon mal reportet zu haben, aber ich finde es nicht:

Wenn ich eine Datei mit "ablegen als pdf" konvertiere, dann wird im Dateinamen jedes Leerzeichen gegen einen Bindestrich ausgetauscht. Ist nervig, das jedesmal händisch korrigieren zu müssen.

![image](https://user-images.githubusercontent.com/29924198/145238624-13ed4938-7647-4868-a427-e44955173a09.png)

**Comment by j-dimension** [comment]
Duplikat von #1235
