### ISSUE TITLE
Mehrere Anwälte - Aktennummerbereiche

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-org#150]
Ich habe die fortlaufenden Aktennummern unterschiedlich eingeteilt (z.B. 8000 ff. Schweizer-Büro), 20000 ff. Private Dinge. Dabei stelle ich bei Anlage einer neuen Akte für den jeweiligen Bereich den Beginn der Nummerierung manuell aus dem jeweiligen Nummernbereich ein. Das Programm legt dann problemlos die nächste mögliche Aktennummer in dem Bereich an. Danach stelle ich manuell auf die Nummerierung ab 1 ff. zurück. Vorschlag - um eine Trennung der Zählbereiche zu erleichtern, könnte man ein Pull-down-Menü einrichten, aus dem der Anwalt / Nummernbereich ausgewählt werden kann, bzw. ein neuer Nummernbereich definiert werden kann.. Die nächste Akte in diesem Bereich wird dann dort angelegt und die Nummerierung danach automatisch wieder auf den Standard gesetzt (Nummerierung ab 1).

**Comment by j-dimension** [comment]
Duplikat von #241
