### ISSUE TITLE
Frage! Platzhalter Anrede1 führt zu Doppelnennung

### ISSUE THREAD

**Issue by iradraconis** [jlawyerorg/j-lawyer-org#1502]
Ich habe dazu noch nichts gefunden, weiß also nicht, ob das hier ein Doppeleintrag ist. Sorry vorab. Ich habe in meiner  Briefvorlage die folgenden Platzhalter im Adressfeld.

Per eMail: {{DRITTE_EMAIL}}
Per Fax: {{DRITTE_FAX}}
Per beA
{{DRITTE_UNTERNEHMEN}}
{{DRITTE_ANREDE1}}{{DRITTE_TITEL}}
{{DRITTE_VORNAME}}{{DRITTE_NAME}}
{{DRITTE_ABTLG}}
{{DRITTE_STRASSE}}{{DRITTE_HAUSNR}}

{{DRITTE_PLZ}}{{DRITTE_ORT}}

Wenn ich beim Beteiligten in der Adressmaske unter Anrede "Herr" auswähle, erscheint im Briefkopf "Herr Herr".  

Soll das so? 

Könnte vielleicht jemand mal erläutern, wie man am besten die Anrede1, Anrede2 und Begruessung richtig verwendet? Ich tue mich da etwas schwer.

Das Verhalten beobachte ich schon lange, und habe es in anderen Vorlagen zum Anlass genommen, die Anrede rauszunehmen.

**Comment by j-dimension** [comment]
Ich trage unter "Anrede" den Wert "Herr" ein, unter "Anrede Briefkopf" den Wert "Herrn", und nutze dann im Kuvertfenster Folgendes

{{DRITTE_UNTERNEHMEN}}
{{DRITTE_ANREDE2}}{{DRITTE_TITEL}}
{{DRITTE_VORNAME}}{{DRITTE_NAME}}
{{DRITTE_ABTLG}}
{{DRITTE_STRASSE}}{{DRITTE_HAUSNR}}

{{DRITTE_PLZ}}{{DRITTE_ORT}}

Hilft das?
