### ISSUE TITLE
[FEATURE] umwandeln statt ablegen

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#1505]
Ich weiß nicht, wie es den anderen geht, aber ich muß hier gedanklich immer eine Hürde überwinden:

![image](https://user-images.githubusercontent.com/29924198/146604191-770a93fd-3001-4b36-9dd0-89d67904850b.png)

ablegen lese ich irgendwie mehr als lokal ablegen. Wäre umwandeln (in pdf) eine intuitivere Benennung?

**Comment by iradraconis** [comment]
Also ich muss da keine Hürde überwinden. Finde es gut wie es ist.

**Comment by GuidoBo** [comment]
Geht mir exakt genau so, wie @stm9x9. Jedes mal, denke ich, dass nach "ablegen" die Datei weg ist

**Comment by j-dimension** [comment]
Umwandeln hört sich für mich allerdings so an, als mache man aus einem ODT ein PDF und das ODT ist dann nicht mehr da (es wurde "umgewandelt"). Das ODT verbleibt ja aber.
Ich mache das Ticket zu. Wenn jemand einen besseren Vorschlag hat, dann gern kommentieren und ich öffne es wieder.
