### ISSUE TITLE
[FEATURE] lokal statt als Datei speichern

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#1506]
Auch hier stolpere ich immer gedanklich. Als Datei will ich es ja auch in der Akte speichern.

![image](https://user-images.githubusercontent.com/29924198/146604475-48489712-7874-472a-9312-1dcd9ca2d892.png)

Wäre es möglich, hier die beiden Menüeintrage beide mit dem Speicherort zu beschriften?

also 

Speichern
- in Akte
- lokal

Hier heißt es ja auch lokal speichern:
![image](https://user-images.githubusercontent.com/29924198/146604433-7e01fb23-f245-4785-9bd3-343baec01205.png)

**Comment by GuidoBo** [comment]
+1
