### ISSUE TITLE
beA - Typ: "Schriftsatz" wird immer zu Typ: "Anlage" im Webclient

### ISSUE THREAD

**Issue by GuidoBo** [jlawyerorg/j-lawyer-org#1509]
Beim erstellen einer neuen beA-Nachricht kann unterhalb des Nachrichtentextes in der Tabelle gewählt werden, ob es sich um einen Schriftsatz oder eine Anlage handelt. 

Beim Speichern in **"Entwürfe"** und späterem Versand über den beA-Webclient wird hieraus (im Webclient) immer "**Anlage**", auch wenn es als "**Schriftsatz**" markiert war. Das kann dort mE auch nicht mehr geändert werden.

**Comment by j-dimension** [comment]
Behoben mit API V6 der BRAK.
