### ISSUE TITLE
Drebis

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-org#151]
Jetzt habe ich es geschafft, beim Refresh die Drebis Dokumente zu sehen in Drebis. Eine Zuordnung zur Akte ist aber nicht möglich. Das Aktenzeichen von Drebis ist 320-17, meine Akte hat 00320-17, Drebis behauptet beim Abspeichern und bestätigen (nur abspeichern gibt´s nicht oder einer Akte zuordnen..). Das keine Akte gefunden wird....

**Comment by Mucki526** [comment]
Vermutlich nicht, sondern über die Webseite drebis.... Ich weiss aber zuwenig über Drebis und frage mich warum es nur die in Akte sortieren und bestätigen oder nur bestätigen Möglichkeit gibt und nicht wie im scanordner die Möglichkeit, eine Akte auszuwählen, dadurch ist es mir ja erst aufgefallen, dass es nicht geht, weil zwei Nullen im Aktenzeichen fehlen...

**Comment by j-dimension** [comment]
> frage mich warum es nur die in Akte sortieren und bestätigen oder nur bestätigen Möglichkeit gibt und nicht wie im scanordner die Möglichkeit, eine Akte auszuwählen


Weil es im Fall von Scans nicht 100%ig klar ist, in welche Akte sie denn gehören. Bei eingehenden Drebisnachrichten hat man zwangsweise immer einen Aktenbezug, der von der Drebisschnittstelle zu einer Nachricht geliefert wird.

**Comment by Mucki526** [comment]
Einen wunderschönen guten Morgen. Das verstehe ich, aber wie bekomme ich die Nachricht mit dem "falschen" Aktenzeichen weil ich die Nachricht über die Webseite gesendet habe von Debris in die Akte, wen das Aktenzeichen wie hier 2 Nullen zu wenig hat? Ich kann es im Moment natürlich öffnen, in den Scanordner speichern, von dort der Akte zuordnen....  Wenn ich sie nur bestätige ist sie ja weg, bzw. wird bei Drebis nicht mehr abgeholt beim Refresh.... Ich mag Automatik, solange ich ihr Herr bin.... :-)

**Comment by j-dimension** [comment]
Du kannst entweder die Dokumente direkt im Drebiseingang öffnen und dann speichern und in die Akte ziehen, oder Du loggst Dich direkt im Drebisportal ein und holst Dir dort die Dokumente.
