### ISSUE TITLE
[FEATURE] pdfs durchsuchbar machen

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#1514]
![image](https://user-images.githubusercontent.com/29924198/147791401-6b442151-1206-4cbc-ae49-4cb18cd70269.png)

angeregt von der Konkurrenz :-) wenn man ein pdf vom Mandanten bekommt, ist das meist nicht durchsuchbar. Ist zwar nicht mehr zwingend, aber immer noch eine Soll-Vorschrift für Gerichtsdokumente und auch sinnvoll.

Könnte entweder auf dem Server passieren oder lokal. Ich weiß nicht, wie gut tesseract inzwischen ist.

**Comment by j-dimension** [comment]
Duplikat von #74
