### ISSUE TITLE
Layout / Schriften / Fonts für Dokumentenverzeichnis in der Akte

### ISSUE THREAD

**Issue by Thorsten-usr** [jlawyerorg/j-lawyer-org#1515]
Hallo
für die Darstellung der Dokumentenablage / Verzeichnisbaum in der Akte wird eine gleichermaßen raumgreifende wie nicht optimal lesbare Schrift verwendet. Sobald man ein paar mehr Dokumente hat, wird das ganze unübersichtlich. Hilfreich wäre, wenn die Darstellung grundsätzlich einzeilig wäre und eine kompaktere Schrift verwendet würde, die klar und deutlich lesbar ist (also ganz schnöde Arial, FreeSans o. dgl. Im Prinzip wie in einem normalen Dateimanager.
Danke im Voraus!

**Comment by j-dimension** [comment]
Bitte einen Screenshot beifügen, ich kann mit der Beschreibung relativ wenig anfangen.

Geht es um die Ordner oder die Dokumente an sich? Was heißt "nicht optimal lesbar"? Inwiefern "unübersichtlich"?

**Comment by Thorsten-usr** [comment]
Ja, es geht hier um die Darstellung der Ordnernamen (das wäre aber noch in Ordnung) und die Darstellung der Dateinamen der Dokumente mit Metadaten (zweizeilig).
Hier mal ein Screenshot von meinem Bildschirm:
![Bildschirmfoto-Dokumentenverwaltung](https://user-images.githubusercontent.com/96954359/147858469-438d4206-a1cd-441b-848e-07059a2b01ac.png)
Auf meinem Bilschirm habe ich da Platz für ca. 10 Dokumente ohne zu scrollen. Die Dateinamen laufen "relativ" weit auseinander, weil es so ein breiter Schriftfont ist. Die kleinen Metadaten sind in dieser Darstellung überhaupt nicht gut zu überblicken. Vielleicht liegt das ja auch an meiner Installation - glaube ich aber nicht wirklich.

**Comment by j-dimension** [comment]
Was ist das für ein Betriebssystem, welche Auflösung und Skalierung?

**Comment by Thorsten-usr** [comment]
Ja, hier mal die Daten:

System:    Kernel: 5.4.0-91-generic x86_64 bits: 64 Desktop: Xfce 4.14.2 Distro: Linux Mint 20.1 Ulyssa 

Graphics:  Device-1: Intel Core Processor Integrated Graphics driver: i915 v: kernel 
                 Display: x11 server: X.Org 1.20.13 driver: modesetting unloaded: fbdev,vesa resolution: 1920x1080~60Hz 
                 OpenGL: renderer: Mesa DRI Intel HD Graphics (ILK) v: 2.1 Mesa 21.0.3

**Comment by j-dimension** [comment]
Dann sind die Default-Schriften unter Mint einfach schräg. Ich frage die vom System ab und nutze keine "fixen" Schriften. So sieht die Anwendung dann bspw. auf Mac auch nach Mac aus. 

Hier ein Beispiel mit (K)Ubuntu: 
![grafik](https://user-images.githubusercontent.com/3729754/147858799-8bc4949b-7ae6-4823-af06-aa582d2c9fd3.png)

**Comment by Thorsten-usr** [comment]
Na, dann werde ich mal versuchen, an meinen Systemschriftarten zu schrauben - was natürlich weitreichende Auswirkungen haben kann.

**Comment by j-dimension** [comment]
> Na, dann werde ich mal versuchen, an meinen Systemschriftarten zu schrauben - was natürlich weitreichende Auswirkungen haben kann.

Bin mir nicht sicher ob das helfen wird - hört sich eher nach einem Mint / Xfce-Bug an.

**Comment by Thorsten-usr** [comment]
Ja, habe etwas rumgesucht und denke jetzt, daß es sich um eine Java-Problematik handelt. Habe den Client hier unter OpenJDK-11 installiert. Ab Version 11 werden wohl die Schriften nicht mehr mitgeliefert, sondern irgendwo vom System gezogen. Unter Linux hat man da angeblich wenig Einflußmöglichkeiten. Habe jetzt zum Vergleich mal OpenJDK-8 installiert und aktiviert. Ich meine, daß die Schriften jetzt etwas kompakter sind:
![Dokumentenbaum](https://user-images.githubusercontent.com/96954359/147888503-88c1832a-d4d6-4839-a7ed-468f3b1ed957.png)
Zusätzlich habe ich auch diese Anleitung zum Antialiasing durchgeführt:
https://wiki.archlinux.org/title/Java_Runtime_Environment_fonts
Mit der Lupe habe ich jetzt nicht nachgesehen, aber ich glaube, das hat sich auch positiv auf die Schriftdarstellung im E-Mail-Fenster ausgewirkt.
Ich finde ja, daß die Schrift in den Reitern des Dokumenten-Fensters schon gut ist. Vielleicht würde es schon helfen, wenn die Dateinamen in der Liste nicht mehr "fett" dargestellt werden müßten. Kann man das irgendwo einstellen/konfigurieren? Denn wie es aussieht, bekommt dem Schriftfont das Fett-Rendern nicht besonders gut.
Was mich noch stutzig macht: Beim Start der Anwendung wird in der Konsole an mehrern Stellen ausgegeben, daß Java 11 im Spiel sei, obwohl ich ja jetzt Java 8 als Priorität gesetzt habe. Ist das, weil der Client in Java 11 geschrieben ist?

Grüße

P.S: Habe noch einmal mit dem Lineal nachgemessen: Die Laufweite der Schriften scheint gleich geblieben zu sein. Also alles nur eine Selbsttäuschung? Oder ignoriert die Anwendung das Umschalten auf Java 8 und benutzt stur Java 11?

**Comment by j-dimension** [comment]
Selbsttäuschung. Der normale Client-Installer bringt ein eigenes Java mit. 

Du kannst versuchen den Client mit dem auf dem System installierten Java zu starten

(voller Pfad zum Java)/java -jar j-lawyer-client.jar

Es muss zwingend ein Java 11 sein.

**Comment by Thorsten-usr** [comment]
Ok, sehe gerade, daß J-Lawyer sein eigenes Java mitbringt. Warum muß man dann vorher auf dem Rechner eine Java-Version installieren? Die mitgebrachte Version ist ja eine 11er Version mit den geänderten Schriftregelungen. Da nützt das ja nix, wenn ich hier eine alte Java-Version installiere.
Es müßte dann ja einfach reichen, wenn die Dateinamen in der Dokumentenverwaltung die gleiche Schrift-Klasse zugewiesen bekäme, wie die Reiter in dem Fenster. Vorteil wäre dann ja auch, daß sich die Dateinamen auch in der Größe mitskalieren würden, wenn man unter "Ansicht" die Schriftgröße verändert.

**Comment by j-dimension** [comment]
> Es müßte dann ja einfach reichen, wenn die Dateinamen in der Dokumentenverwaltung die gleiche Schrift-Klasse zugewiesen bekäme, wie die Reiter in dem Fenster.

Auch die Tab-Beschriftungen haben bei Dir die falsche Schrift. Wie gesagt wird die bereits dynamisch ermittelt, und ich mache keine Logik a la "wenn Mint / Xfce, dann verhalte Dich so, anderenfalls so".

**Comment by Thorsten-usr** [comment]
Ja genau, dann könnte man das in der Installationsanleitung mal anpassen "zwingend Java-11", falls das wichtig ist.

**Comment by j-dimension** [comment]
> Ja genau, dann könnte man das in der Installationsanleitung mal anpassen "zwingend Java-11", falls das wichtig ist.

Habe in der Installationsanleitung für Linux den kompletten Abschnitt "Java installieren" für den Client entfernt, da nicht mehr notwendig.

**Comment by Thorsten-usr** [comment]
Ja, verstehe...
aber die Dateinamen könnten ja die gleiche "falsche" Schrift bekommen, wie die Reiter.
(Nur eine Vorschlag)
Ah, guter Hinweis. Wenn ich jetzt den Client noch auf meinen anderen Rechnern installiere, brauche ich das Java nicht mehr. Der Server braucht dann aber noch eine Java-Installation?

**Comment by j-dimension** [comment]
> aber die Dateinamen könnten ja die gleiche "falsche" Schrift bekommen, wie die Reiter.

Das ist aus Perspektive des Codes keine andere Schrift, nur die Formatierungen (Styles) unterscheiden sich.



> Der Server braucht dann aber noch eine Java-Installation?

Unter Linux ja, ansonsten nicht.

**Comment by Thorsten-usr** [comment]
Ja, zuviele unterschiedliche Schriften sieht ja auch nicht gut aus und wenn die sowieso dynamisch der Klasse "Sans" zugeordnet wird, dann ist das so. 
Die Formatierung als "bold" kann man ja mal überdenken.
Die Beobachtung, daß sich die Dateinamen bei der Dokumentenverwaltung der Skalierung entziehen - auch wenn es dieselbe Schrift ist - bleibt aber. Das wurde aber schon unter einem anderen Ticket angesprochen.

Grundsätzlich kann man mit der Darstellung brauchbar arbeiten. Ich werde an dem Thema Java und Fonts noch etwas dranbleiben.

**Comment by stm9x9** [comment]
ich muß gestehen, so richtig zufrieden bin ich mit der Darstellung auch nicht. Allerdings fällt es mir schwer, das in Worte zu fassen. Irgendwie strengt es an, dort zu lesen.

![image](https://user-images.githubusercontent.com/29924198/148265253-f9ea769f-2af6-4462-bfd7-53e7946547fa.png)

Win10, 64bit
1680x1050
Skalierung 1

**Comment by Thorsten-usr** [comment]
Ja, das muß irgenwie anders - überlege aber noch wie. Die Angabe des Dateierstellungsdatum ist nur sekundär interessant, auch die Größe und der aktuelle Ablageordner (also die ganze zweite Zeile). Die Infos könnte man auch einblenden, wenn man auf das Datei-Icon geht. Dann hätte man die Ansicht schon etwas entschlackt. Dann braucht man auch den Farbwechsel der Doppelzeilen nicht.
Das Datum ist immer sehr prominent in der Ansicht. Ich nutze immer nur eine kompakte Form "211023", also yymmtt. Dadurch werden die Dateien sauber sortiert ohne daß das Datum zu breit ist.
Vielleicht kann man dereinst zwischen der Standard- und einer reduzierten Ansicht wählen.
Ich würde es mir wünschen.
Grüße!

**Comment by j-dimension** [comment]
Das Kommende nicht falsch verstehen: ohne breitere Debatte in der Anwenderschaft und eine Art "Konsens" werde ich hier nichts anpassen. Zu oft habe ich den Fehler gemacht, Änderungen auf Basis der Wünsche Einzelner umzusetzen, die dann von der Masse abgelehnt oder nicht verstanden wurden. 

Vor einer Weile WAR die Dokumentenansicht eine schlichte Tabelle, mit damit verbundenen Beschwerden, dass für die Metadaten immer horizontal gescrollt werden müsse. Daher der Umbau. 

Ich persönlich habe auch tatsächlich Bedarf, die Metadaten im Blick zu haben: die Ordner, um schnell zu sehen ob ich noch etwas verschieben muss, die Größen um zu sehen ob etwas noch in eine beA-Nachricht reinpasst und ob man statt per E-Mail zu senden lieber eine Freigabe nutzt.

Ich lasse das Ticket offen, gern die Mailingliste nutzen, und am besten an Hand von UI Sketches diskutieren.

**Comment by Thorsten-usr** [comment]
Ja gut, hier schon mal zur Diskussion die Dokumentenansicht des Platzhirschen:
![RA-Micro-Dokumentenansicht](https://user-images.githubusercontent.com/96954359/148273542-dec95ebf-9ebe-4cd4-942f-49863564a36f.png)
Übersichtlich ist das ja auf jeden Fall.
Ein Feature der Darstellung von J-Lawyer ist ja die Sortierung der Dateien über Ordnerebenen hinweg. Allerdings weiß ich jetzt noch nicht, ob ich das auch nutzen werde, oder ob das auch so geht.
Ich glaube auch nicht an die große Diskussion, an deren Ende eine Entscheidung stehen wird. Deswegen hoffe ich auf eine umschaltbare Ansicht einzeilig/zweizeilig. Dann kann sich jeder nach seinen Bedürfnissen etwas aussuchen.
Beim Stöbern habe ich mal die "alte" Dokumentenansicht von J-Lawyer gesehen - die war schon kompakt.
