### ISSUE TITLE
[BUG] beA-Import - Import bricht ab bei gleichlautende Dateinamen der Dokumente des Gerichts

### ISSUE THREAD

**Issue by GuidoBo** [jlawyerorg/j-lawyer-org#1517]
Verschickt das Gericht mehrmals Anhänge mit demselben Dateinamen im Anhang (z.B. Anschreiben_formlos.pdf) bricht der Import mit der Fehlermeldung ab, dass diese Datei bereits in der Akte vorhanden ist.

Vorschlag: Beim Import umbenennen und Datum oder MessageID in den Dateinamen übernehmen (möglichst unmittelbar vor der Dateiendung, nicht am Anfang des Dateinamens).

**Comment by j-dimension** [comment]
Ist nicht ohne weiteres möglich / sinnvoll, da dann der Strukturdatensatz nicht mehr zu den Dateien passt, es müsste also auch der SDS angepasst werden.

**Comment by j-dimension** [comment]
Thema wird über bereits vorhandenes Ticket #1225 bearbeitet.
