### ISSUE TITLE
Filtern nach Tags

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-org#152]
Erst mal Gratulation zu 1.9.1. Läuft prima und bring tolle Verbesserungen. Dank Jens für die viele Arbeit und dass der Programmcode öffentlich gemacht worden ist. 
Ich habe folgendes gerade in 1.9.1 bemerkt. Wenn man Akten filtert nach Tags und man zwei Tags auswählt, die ggf. in einer Akte beide gesetzt sind, wird die Akte in der Trefferliste zweimal ausgeben. Einmal wäre m.E. sinnvoller - nach dem update ist vor dem update :-).

**Comment by j-dimension** [comment]
Erledigt.
