### ISSUE TITLE
[TASK] Überschreiben einer früheren PDF-Datei

### ISSUE THREAD

**Issue by ms00st** [jlawyerorg/j-lawyer-org#1521]
Wahrscheinlich ähnlich / identisch zu #862.

Wenn ich ein Dokument (.odt) im Programm als PDF ablegen (umwandeln) möchte und die Datei schon existiert, muss ich einen neuen Dateinamen eingeben. Hier fehlt die Möglichkeit, die alte Datei zu überschreiben.

Insbesondere ist dies umständlich, da ich die vorherige PDF-Datei erst umbenennen und dann löschen muss, bevor ich die neue Datei unter dem alten Namen speichern kann. Wenn ich die alte Datei vor dem Löschen nicht umnenne, kann ich den ursprünglichen Dateinamen ebenfalls nicht benutzen. Hier scheint die Papierkorbfunktion die Nutzung des Dateinamens zu verhindern.

**Comment by j-dimension** [comment]
@Bentipa vielen Dank, ich hab den PR gemerged!
