### ISSUE TITLE
[FEATURE] Nutzerkürzel als Platzhalter

### ISSUE THREAD

**Issue by MarcoWolny** [jlawyerorg/j-lawyer-org#1525]
Für die Zuordnung der Dokumente am Drucker wäre es hilfreich, wenn auf dem Ausdruck der Nutzer vermerkt wäre, der das Dokument erstellt hat.

Dies könnte durch einen Platzhalter für das Nutzerkürzel aus der Nutzerverwaltung realisiert werden.

**Comment by j-dimension** [comment]
@MarcoWolny Ihr könntet bspw. {{AUTOR_AN}} nutzen, das ist der in der Nutzerverwaltung hinterlegte "Anzeigename" des Nutzers.

**Comment by MarcoWolny** [comment]
Hm, dachte ich auch erst, aber der PH bleibt bei mir leer... Muss ich dafür noch irgendwo in der Software etwas einstellen?
![Bildschirmfoto 2022-01-06 um 14 37 46](https://user-images.githubusercontent.com/74820386/148391263-0431e508-26a2-4140-a970-9bb04de6b1a3.png)

**Comment by j-dimension** [comment]
In der Nutzerverwaltung ("Einstellungen" - "Nutzer") auf den gewünschten Nutzer klicken und dann gleich auf dem ersten Tab unter "Anzeigename" einen Wert eintragen.

**Comment by MarcoWolny** [comment]
Ah, super. Danke, damit ist dieser Punkt geklärt.
Perfekt!
