### ISSUE TITLE
E-Mail - für .eml Dateien kann kein externes Programm konfiguriert werden

### ISSUE THREAD

**Issue by Thorsten-usr** [jlawyerorg/j-lawyer-org#1526]
Nachdem ich bei einigen E-Mail-Dateien Probleme mit dem Öffnen bzw. Darstellen bekommen habe, würde ich gerne diese E-Mails mit Thunderbird öffnen. Meine Bemühungen unter Einstellungen/Dokumente für .eml Dateien ein externes Programm festzulegen führen aber zu nichts. J-Lawyer versucht trotzdem die E-Mail-Datei mit dem internen Viewer zu öffnen - was nicht klappt.

Linux Mint 20.1 xfce, Thunderbird ist Standard-Client und direkt von überall aufrufbar.

Grüße.

**Comment by j-dimension** [comment]
Man kann Mails sowohl aus dem Posteingang als auch aus der Akte heraus mit dem Standardmailer des Systems öffnen: Rechtsklick, "im externen Mailprogramm öffnen".

**Comment by j-dimension** [comment]
Was bedeutet "Probleme mit dem Öffnen" genau? Fehlermeldung?

**Comment by Thorsten-usr** [comment]
Ah, ok, ich dachte für die Standartprogramme muß man immer Doppelklicken und - falls vom Standard abweichend - vorher ein externes Programm konfiguriert haben. 
Bei der E-Mail ist es jetzt wie folgt: Die Einstellung eines externen Programms blockiert den Aufruf des Standardprogramms, liefert dann aber euch kein Ergebnis. Wenn ich kein externes Programm definiert habe öffnet sich bei Doppelklick der interne Betrachter von J-Lawyer und bei Rechtsklick dann das Standardprogramm des Systems.
Also, mein Problem war der eigene - blockierende - Eintrag eines Programms bei den Einstellungen.

**Comment by j-dimension** [comment]
Okay, dann kann ich hier schließen?

**Comment by Thorsten-usr** [comment]
Noch zu dem Fehler beim Öffnen einiger E-Mails:
Die Meldung lautet: failed to parse
Hier wird im internen Betrachter also nichts angezeigt (Fehler beim Laden).
Wenn ich die Mail dann umleite über einen anderen Account und dann nocheinmal öffne, kann sie nun doch geöffnet werden, hat aber diesen Html Block am Anfang:
![Mail-mit-html-Block-2](https://user-images.githubusercontent.com/96954359/148644785-296c251e-d6ed-417e-b9ce-270273c836a6.png)
Bei einer anderen Mail war auch so ein Block, diese Mail ließ sich aber direkt intern öffnen:
![Mail-mit-html-Block](https://user-images.githubusercontent.com/96954359/148644809-91390221-3179-4dcc-90b5-62d2c369e212.png)
Mit externem Programm werden diese Blöcke nicht angezeigt. Sieht aus, als ob es hier irgendwelche Inkompatibilitäten gibt.
Grüße.

**Comment by j-dimension** [comment]
@Thorsten-usr okay, ich habe dafür ein neues Ticket erstellt und schließe dieses hier.
