### ISSUE TITLE
Tastenkombination option + backspace funktioniert nicht unter MacOS Monterey

### ISSUE THREAD

**Issue by iradraconis** [jlawyerorg/j-lawyer-org#1529]
MacOs Monterey

im Client funktioniert weder in Emails, noch in Notizen, noch im Kalender das wortweise "Löschen" mit option + backspace.

**Comment by Fn0rdmann** [comment]
Unter MacOS ist die Tastenlogik eine andere. Mit Alt + Backspace klappt es bei mir.
Am 10. Jan. 2022, 12:15 +0100 schrieb iradraconis ***@***.***>:

**Comment by j-dimension** [comment]
In der Tat, vielen Dank @Fn0rdmann !
@iradraconis , ist das für Dich ausreichend?

**Comment by iradraconis** [comment]
Auf meiner Macbook Tastatur gibt es kein Alt sondern eben nur "option". Und es funktioniert nicht. Weder mit Option, noch mit Ctrl. noch mit cmd.

**Comment by iradraconis** [comment]
> Was ist das für ein Mac-Modell? Command (or Cmd) ⌘ Option (or Alt) ⌥ Control (or Ctrl) ⌃ Hier funktioniert Option/Alt mit interner und externer Tastatur A1314 unter MacOS 12.1 einwandfrei. Am 10. Jan. 2022, 16:39 +0100 schrieb iradraconis ***@***.***>:
> […](#)

Macbook Pro M1 Pro, 16 Zoll mit OSX Monterey 12.1. 
Die Tastenkombination funktioniert bei mir überall in OSX, nur halt nicht im J-Lawyer Client.

**Comment by iradraconis** [comment]
Nur ergänzend der Hinweis, dass ich OSX nicht erst seit heute benutze, sondern schon Jahre! Dass die Tastenlogik eine andere ist, als unter Windows, ist mir bewusst. Ich habe das Ticket eröffnet, weil es eben im client nicht geht und nicht unter MacOs im Allgemeinen.

**Comment by Fn0rdmann** [comment]
Mein Hinweis bezog sich auf die Logik unter Linux, aber gleichviel. Wenn es sonst funktioniert, liegt es wohl auch nicht am Mapping. Dann muss Jens wohl doch mal unter die Haube schauen. Bei mir ist die Funktionalität auf einer kleineren M1-Maschine mit Alt/Option wie erwartet.
Am 10. Jan. 2022, 17:18 +0100 schrieb iradraconis ***@***.***>:

**Comment by j-dimension** [comment]
Ich habe hier zwar einen Mac als Testumgebung, der hat allerdings eine Alt-Taste. Bin noch im Unklaren wie ich das angehen soll.

**Comment by iradraconis** [comment]
ich glaube, Jens, du kannst hier vorerst schließen. Nach einem Neustart des Macbooks funktioniert es hier wieder. durch die lange Akkulaufzeit der neuen M1 Modelle, lag mein letzter Neustart einige Zeit zurück. Was auch immer das war, es scheint ein vorübergehendes und nicht gravierendes Problem zu sein. Falls es wieder auftritt, darf ich mich bestimmt wieder melden :)

**Comment by iradraconis** [comment]
Der Fehler taucht beinahe täglich auf. Nach einige Nutzung des Clients (M1 Macbook Pro) funktioniert die Tastenkombination nicht mehr. Ein Neustart des Clients schafft Abhilfe.

**Comment by j-dimension** [comment]
Dann mach ich den Bug wieder auf, nur helfen kann ich nicht. Eine Recherche hat nichts ergeben, und auf meinem Mac (kein M1) kann ich das nicht nachvollziehen.

**Comment by Fn0rdmann** [comment]
Ich kann das hier nicht nachvollziehen, weder mit der internen, noch mit einer externen Tastatur (A1314). Hier passiert folgendes:

Option (or Alt) ⌥ + Backspace ⌫ - wortweises Löschen nach links
fn + Option (or Alt) ⌥ + Backspace ⌫ - wortweises Löschen nach rechts
Fn + Backspace ⌫ - zeichenweises Löschen nach rechts

Umgebung: MacBook Pro (13 Zoll, M1, 2020), Mac OS 12.1
Am 24. Jan. 2022, 09:17 +0100 schrieb Jens Kutschke ***@***.***>:
