### ISSUE TITLE
[FEATURE] Dokumentvorschau nur bis zu einer bestimmten Dokumentengröße

### ISSUE THREAD

**Issue by j-dimension** [jlawyerorg/j-lawyer-org#1533]
Aktuell wird zum Generieren einer Vorschau immer das Dokument vom Server geladen. Für schmalbandig angebundene Clients ist das nicht optimal. 

Größe, bis zu welcher ein Dokument zum Zweck der Vorschau vom Server geladen wird, konfigurierbar machen.

**Comment by j-dimension** [comment]
Standardwert 2MB

**Comment by j-dimension** [comment]
![grafik](https://user-images.githubusercontent.com/3729754/149642196-bb342848-ee17-4429-9805-e66f508b0608.png)

**Comment by j-dimension** [comment]
![grafik](https://user-images.githubusercontent.com/3729754/149642214-214af4c3-e39b-4f0d-9dfe-56d97ce862df.png)

**Comment by Dickmaulruessler** [comment]
Kannst du den praktischen Anwendungsfall bitte noch näher erläutern? Für die ganz überwiegende Anzahl an Nutzern, namentlich alle lokale Installationen und für (Kanzlei-) Netzwerke ist das wohl irrelevant, oder?
Danke schon einmal!

**Comment by j-dimension** [comment]
Ja, in lokalen Netzen irrelevant, höchstens wenn man so ein ominöses D-LAN nutzt.

Für die Vorschau wird das Dokument vom Server geladen. Hat man wenig Bandbreite, dann dauert das. Dann könnte man ein Limit einstellen und so Bandbreite (und Zeit) sparen. So bekommt man dann Vorschauen für kleine Dokumente / Mails, aber die 60MB Ermittlungsakte (PDF) wird dann nicht geladen, nur wenn man sie per Doppelklick öffnet.

**Comment by Dickmaulruessler** [comment]
Ok. Kann man das global auf "unbegrenzt" stellen oder ist die Einstellung Akten- oder Dokumentbezogen?

**Comment by j-dimension** [comment]
Ja, global auf unbegrenzt geht.

**Comment by stm9x9** [comment]
> Kannst du den praktischen Anwendungsfall bitte noch näher erläutern? Für die ganz überwiegende Anzahl an Nutzern, namentlich alle lokale Installationen und für (Kanzlei-) Netzwerke ist das wohl irrelevant, oder? Danke schon einmal!

zum einen kann man den Server ja auch auf einem dezidierten Server laufen haben, zum anderen greift auch der Anwalt mit lokalem Server ja vielleicht mal mobil vom Gericht aus auf die Dokumente zu.

**Comment by iradraconis** [comment]
PDF ist 25 MB groß, Einstellung auf unbegrenzt,
<img width="446" alt="Bildschirmfoto 2022-03-22 um 13 56 14" src="https://user-images.githubusercontent.com/71747937/159486892-71fab1be-3fbe-46e9-bc75-53fc5099cd03.png">
