### ISSUE TITLE
[kalender] Langfristige Wiedervorlagen

### ISSUE THREAD

**Issue by LinoPeters** [jlawyerorg/j-lawyer-org#1534]
Großartig wären, über die standardisierten Widervolagefristen hinaus, WV v 3 M, 6 M und eventuell auch 12 M. Vielen Dank

**Comment by Fn0rdmann** [comment]
+1

--
Bernd M. Schraeder
+49 2594 7928398 | +49 1512 7075059 | ***@***.***
Am 16. Jan. 2022, 10:02 +0100 schrieb LinoPeters ***@***.***>:

**Comment by Dickmaulruessler** [comment]
Ja, auch ich hätte häufig Fälle für langfristige WV. 

Insgesamt ist deren gewünschte Dauer je nach Rechtsgebiet und Arbeitsweise sehr individuell und da man diese Frage täglich viele Male in der Akte entscheiden muss auch etwas mit hoher praktischer Relevanz für jeden (ich mag es nicht sagen, Jens, aber - nur falls all die hier gewünschten Zeiträume insgesamt zu viel werden - evtl. "einstellbar"?)

**Comment by j-dimension** [comment]
![grafik](https://user-images.githubusercontent.com/3729754/150581808-d8884988-ed62-440c-b1ef-9c780d8c30fd.png)

**Comment by Dickmaulruessler** [comment]
Cool!

**Comment by LinoPeters** [comment]
Super! Vielen Dank Herr Kutschke!

**Comment by stm9x9** [comment]
aus #1478 1 Monat als DIE Standardrechtsmittelfrist wäre noch spitze!
