### ISSUE TITLE
[beA] Teilnehmersuche - nicht mehr zwei Suchparameter nötig?

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#1536]
![image](https://user-images.githubusercontent.com/29924198/149673869-2c77e3d3-2022-4b05-9bee-9caf5f064884.png)

Aktuell bekommen wir in jl - wie bislang auch in beA-web - den Fehler "mindestens zwei Suchparameter!", wenn wir zb nur den Ort eingeben.

Wie ich gerade feststellen konnte, in beA-web genügt inzwischen ein Parameter, exemplarisch hier ein Ort. Ist das in der Schnittstelle auch geändert worden? Kann jl entsprechend angepaßt werden? (Was ich jetzt nicht geprüft hatte: braucht es noch mehr als zwei Zeichen?)

**Comment by j-dimension** [comment]
ich finde keinen änderungseintrag in der schnittstellendoku. kann das trotzdem prüfen.

**Comment by j-dimension** [comment]
Die Schnittstelle liefert nach wie vor

`0206 - The given search parameter are insufficient. Please provide at least 2 parameters with at least 2 characters (if the value is a string) or 1 type (if the value is a type)!`
