### ISSUE TITLE
[BUG] macOS: Klickereignisse werden teilweise nicht erkannt

### ISSUE THREAD

**Issue by j-dimension** [jlawyerorg/j-lawyer-org#1537]
Scheinbar primär unter macOS werden Klickaktionen teilweise nicht verarbeitet / kommen gar nicht in der Anwendung an. Ursache unklar. Es scheint sich auf bestimmte Oberflächenelemente zu beschränken, d.h. es gibt andere Buttons / Elemente, bei denen dieses Problematik nie auftritt.

Bitte hier sammeln, bei welchen Elementen das zu beobachten ist. 

Bekannt:
- Dokumentenliste in der Akte

**Comment by j-dimension** [comment]
Füge @PBaumfalk als Beobachter hinzu

**Comment by RA-Heil** [comment]
Mir aufgefallen in folgenden Elementen:

-Sporadisch bei Klick auf einzelne Akten im Startbildschirm
- Sporadisch bei Klick auf Daten in der Dokumentenvorschau nach öffnen einer einzelnen Akte
- insbesondere die Reiter „Email“, „bea“, „Scan“ sind bei mir betroffen 
- Innerhalb der oben erwähnten Reiter bei Klick auf einzelne Elemente. Besonder markant im Bereich Scan und dem Versuch diese in der Vorschau anzeigen zu lassen. Das führt dazu dass es teils unmöglich ist Scans zuzuordnen oder dass diese falsch zugeordnet werden

**Comment by GuidoBo** [comment]
- An- und Wegklicken von Ordnern (oft)
- beA-Vorschau (oft)

**Comment by Fn0rdmann** [comment]
•  Menüeinträge in der Seitenleiste

Am 18. Jan. 2022, 20:15 +0100 schrieb GuidoBo ***@***.***>:

**Comment by j-dimension** [comment]
> Menüeinträge in der Seitenleiste

@Fn0rdmann Du meinst die Hauptnavigation links? Gibt es dort bestimmte Menüeinträge wo das zu beobachten ist? Oder auch interessant: Gibt es Menüeinträge wo das überhaupt nicht auftritt?

**Comment by GuidoBo** [comment]
Schwer mit Gewissheit zu sagen, aber vielleicht die Schaltflächen oben auf dem Desktop: News und das Benutzerprofil (rechts)
![image](https://user-images.githubusercontent.com/56734761/150076071-3aa030d1-db38-4538-ac83-cb88a4131bcc.png)

**Comment by Fn0rdmann** [comment]
Richtig. Unter MacOS ist das die Seitenleiste ;-)

Meine Wahrnehmung: Klicks auf Text funktionieren häufig nicht. Klicks auf die Symbole/Icons klappen deutlich besser.
Am 18. Jan. 2022, 23:04 +0100 schrieb Jens Kutschke ***@***.***>:

**Comment by j-dimension** [comment]
An alle, ich habe eine Gemeinsamkeit der hier genannten "Problem-Oberflächenelemente" ausmachen können. Da ich das in keiner meiner Testumgebungen nachvollziehen konnte, werde ich Hilfe beim Testen benötigen. Melde mich, wenn die Pilotphase für die 2.1 eingeläutet wird.

**Comment by iradraconis** [comment]
Ich melde mich dann auch mal als Betroffener.
