### ISSUE TITLE
[FEATURE] PDFs im Scaneingang splitten

### ISSUE THREAD

**Issue by j-dimension** [jlawyerorg/j-lawyer-org#1538]
Eine Art Mehrseitenanzeige, in welcher man Schnittmarken setzen kann und das PDF auf Knopfdruck gesplittet wird.

Use Case: Stapelscan gesamter Papierpost und spätere Aufteilung.

**Comment by j-dimension** [comment]
Erweiterung: Split anhand eines Textes auf einer Trennseite, oder anhand leerer Seiten.

**Comment by j-dimension** [comment]
https://stackoverflow.com/questions/16358002/split-pdf-into-separate-files-based-on-text

**Comment by j-dimension** [comment]
https://stackoverflow.com/questions/23738652/how-to-find-blank-pages-inside-a-pdf-using-pdfbox

**Comment by j-dimension** [comment]
umgesetzt: 
- Splitten von PDFs an leeren Seiten (bspw. zum Trennen von Eingangspost)
- Splitten von PDF in gleichmäßig große Seitenzahlenpakete (bspw. bei sehr großen PDFs) 

ohne grafische Splitanzeige

**Comment by Dickmaulruessler** [comment]
Kann man diese coole Funktion an und ausstellen, falls man damit trotz allem nicht klarkommen sollte?

**Comment by j-dimension** [comment]
> Kann man diese coole Funktion an und ausstellen, falls man damit trotz allem nicht klarkommen sollte?

Das ist völlig optional. Es gibt im Scaneingang einfach eine Split-Funktion, welche die Dokumente noch innerhalb des Eingangs splittet.

**Comment by Dickmaulruessler** [comment]
Super! Schönes Feature!

**Comment by j-dimension** [comment]
Hier mal ein Video:


https://user-images.githubusercontent.com/3729754/194729318-1508e330-ee06-480d-a0fe-2662a3594269.mp4

**Comment by iradraconis** [comment]
Das sieht nach einem tollen Feature aus. Wirklich gut!
Vielleicht gibt es ja in zukünftigen Updates die Möglichkeit, die Funktion auch innerhalb einer Akte auf Dokumente anzuwenden

**Comment by Maz111111** [comment]
Nur ein Hinweis:
Grundsätzlich eine tolle Sache mit der Trennung nach /bei leeren Seiten.
Das wird aber nur funktionieren, wenn man beim Einscannen nur einseitig scannt (Rückseiten sind meistens leer und würden dann als Trennblatt wirken) und die Funktion leere Seite automatisch entfernen ausgeschaltet hat (sonst fehlen im fertigen Scan die Trennblätter).
Du hattest oben in den Raum geworfen, die Trennung anhand eines bestimmten Textes vorzunehmen. 
Das würde das beschriebene Problem mehr oder weniger umgehen. Wenn man den Text "Trennblatt" auf das Trennblatt schreibt, ist die Wahrscheinlichkeit, dass das Wort "Trennblatt" in irgendeinem einzuscannenden Schriftsatz auftaucht sehr gering.
Ich finde die Option für den Arbeitsablauf aber extrem gewinnbringend - da zeitsparend. Richtig gut!
