### ISSUE TITLE
scanordner Rücksprung nach Zuordnung

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-org#154]
Wenn man mehrere Dateien im Scanordner hat und die neueste (unterste) einer Akte zuordnet, springt der Fokus danach auf die älteste (oberste) Datei im scanordner. Besser wäre auf die jetzt neueste (unterste). Eine geänderte Sortierreihenfolge wird zudem nicht gespeichert.

**Comment by j-dimension** [comment]
#163
