### ISSUE TITLE
[FEATURE] (Soft-)Gendering im Userinterface

### ISSUE THREAD

**Issue by LazyGuy21No** [jlawyerorg/j-lawyer-org#1543]
Wir würden uns wünschen, dass es ein Soft-Gendering im Userinterface gibt (ähnlich dem, das Apple mittlerweile verwendet: "Nutzer:in"). Evtl. auch unter Verwendung des Gerundiums ("Nutzende Person", "Studierende Person"), da dies wohl eine höhere allgemeine Akzeptanz zu haben scheint.

**Comment by j-dimension** [comment]
Von mir aus gern, jedoch nicht ohne eine breitere Debatte in der Anwenderschaft. Wie bei so vielen Themen heutzutage, scheint es da eine "Spaltung" zu geben.

**Comment by Dickmaulruessler** [comment]
> Wir würden uns wünschen, dass es ein Soft-Gendering im Userinterface gibt

Wo konkret würdest du dir das den vorstellen? 
Der Umfang der gewünschten Änderungen wäre für die notwendig breitere Debatte sicherlich von Interesse.

**Comment by GuidoBo** [comment]
![image](https://user-images.githubusercontent.com/56734761/151213543-726d3672-8578-4aca-a602-612af0c49c2b.png)
z.B. Nutzer:innenprofil / Nutzer:in; so wie hier ...
<img width="110" alt="Bildschirmfoto 2022-01-26 um 18 22 13" src="https://user-images.githubusercontent.com/56734761/151214264-097edccd-6be5-4b46-a7a8-e92c22dded53.png">

**Comment by PBaumfalk** [comment]
Muss das tatsächlich sein? Bringt das einen tatsächlichen Mehrwert?

**Comment by GuidoBo** [comment]
Dafür gibt es vermutlich keinen einziges Euro von irgendwem mehr und es *muss* sicher auch nicht sein.

Allerdings arbeiten mit mir Menschen, die die Bedingungen ihrer Arbeit (und ihres übrigen Lebens) weit weniger bestimmen können als ich. Diesen Menschen möchte ich nach in ihrem Arbeitsumfeld nach Möglichkeit einen Safe-Space bieten. Das geht oft nicht, etwa im Kontakt mit den Menschen, die uns mandatieren oder mit Gegenseiten. Darauf habe ich keinen Einfluss.

Aber dort, wo ich Einfluss habe, möchte ich auf ein respektvolles Umfeld hinwirken. Und: schlechter wird das System dadurch sicher auch nicht.

**Comment by GuidoBo** [comment]
![image](https://user-images.githubusercontent.com/56734761/151300888-ac5e95af-31ce-46de-a882-4908a36fb7ca.png)
**Sachbearbeitung** statt Sachbearbeiter

**Comment by GuidoBo** [comment]
![image](https://user-images.githubusercontent.com/56734761/151304731-bb90a260-0663-475c-83a0-d885a06420cb.png)
**Zur Anwaltschaft zugelassene Person** statt Anwalt

**Comment by GuidoBo** [comment]
![image](https://user-images.githubusercontent.com/56734761/151305057-0f652652-bb02-4725-b1ed-d67976b23b19.png)
**... Nutzer:in ist Rechtsanwältin/Rechtsanwalt** oder **... ist zur Anwaltschaft zugelassene Person**  oder **... übernimmt anwaltschaftliche Funktion**

**Comment by Fn0rdmann** [comment]
Die letzten Beispiele zeigen m. E. sehr schön, dass das Gendering im Userinterface zu sehr unübersichtlichen Beschreibungen führte.

Ich persönlich halte die Gleichsetzung von biologischem und grammatischem Geschlecht für ein großes Missverständnis.

M. E. sollte das UI bleiben, wie es ist.

**Comment by iradraconis** [comment]
> Die letzten Beispiele zeigen m. E. sehr schön, dass das Gendering im Userinterface zu sehr unübersichtlichen Beschreibungen führte. Ich persönlich halte die Gleichsetzung von biologischem und grammatischem Geschlecht für ein großes Missverständnis. M. E. sollte das UI bleiben, wie es ist.

Das würde ich so unterschreiben.

**Comment by GuidoBo** [comment]
Ich denke nicht, dass es deswegen zur Unübersichtlichkeit kommt. In iOS gibt es damit jedenfalls keine Probleme: https://t3n.de/news/ios-15-apple-gendern-1386010/

**Comment by GuidoBo** [comment]
> > Die letzten Beispiele zeigen m. E. sehr schön, dass das Gendering im Userinterface zu sehr unübersichtlichen Beschreibungen führte. Ich persönlich halte die Gleichsetzung von biologischem und grammatischem Geschlecht für ein großes Missverständnis. M. E. sollte das UI bleiben, wie es ist.
> 
> Das würde ich so unterschreiben.

Es geht letztlich m.E. nur um eine handvoll Änderungen (vielleicht zwei Hände voll). Wäre es akzeptabel, wenn wir uns auf einzelne Änderungen verständigen können, statt es in Bausch und Bogen abzulehnen? Zu "Sachbearbeitung" statt "Sachbearbeiter" sollte z.B. ein Konsens möglich sein.

**Comment by j-dimension** [comment]
> Zu "Sachbearbeitung" statt "Sachbearbeiter" sollte z.B. ein Konsens möglich sein.

Das hätte keine Nachteile bzgl. des UI-Layouts, würde jedoch zu einer Diskrepanz zwischen Benennung in der Oberfläche und dem Namen des Platzhalters führen.

**Comment by Dickmaulruessler** [comment]
Ich tue mich auch schwer damit. Und besonders bei ein oder zwei Vorschlägen bekam ich Augenrollen. 

Wenn ich mir aber den umgekehrten Fall vorstelle (Ich als Mann würde durchgehend als "Nutzerin" und "Sachbearbeiterin" angesprochen werden) würde ich auch eindeutig Handlungsbedarf sehen. 

Ich finde aber, dass man die relevanten Punkte erst einmal entspannt in aller Ruhe komplett sammeln sollte.

Ein Formilulierungsvorschlag muss meiner Meinung dann noch nicht dabei sein - da gibt es ja immer mehrere gute und schlechte Optionen.

Ich würde daher bitten, dass wir hier nicht vorschnell zu einer Bewertung kommen und die Sammlung noch sachlich und geduldig fortführen.

**Comment by Dickmaulruessler** [comment]
> ![image](https://user-images.githubusercontent.com/56734761/151305057-0f652652-bb02-4725-b1ed-d67976b23b19.png) 

Welche praktische Bedeutung hat diese Einstellung? 
In der Doku findet sich dazu nichts. 
Im Forum fand ich diesen Hinweis: "Die Angabe „Nutzer ist Anwalt“ wird primär dazu genutzt, die Auswahlboxen zu füllen – bspw. im Abschnitt „Eigentümer“ einer Akte".
Verstehe ich das richtig, die Box nimmt die Differenzierung vor, ob jemand "Anwalt" oder "Sachbearbeiter" ist? Haken nicht gesetzt = Sachbearbeiter?

**Comment by j-dimension** [comment]
> Haken nicht gesetzt = Sachbearbeiter?

Haken nicht gesetzt = kann nicht als Anwalt/Anwältin ausgewählt werden. Haken gesetzt = Nutzer kann sowohl Anwalt / Anwältin als auch Sachbearbeiter / Sachbearbeiterin sein.

**Comment by Dickmaulruessler** [comment]
Ist das Thema evtl. in den Falldatenblättern relevant?
Ich habe darüber keinen Überblick.

**Comment by GuidoBo** [comment]
> Ist das Thema evtl. in den Falldatenblättern relevant? Ich habe darüber keinen Überblick.
m.E. nein

**Comment by stm9x9** [comment]
Ich bitte dringend darum, davon Abstand zu nehmen. Nicht nur, daß es inhaltlich / grammatikalisch falsch ist (einschließlich des Gerundiums) und es auch genügend gerade Frauen gibt, die nicht unterschiedlich bezeichnet werden wollen, sind da auch noch blinde und sehbehinderte Menschen, für die diese :/*-Lösungen problematisch sind.

Einen Safe-Space schaffe ich für meine Mitarbeiter (m/w/d) indem ich sie gut behandle, sie als Menschen akzeptiere, eine freundliche Atmosphäre schaffe ...

**Comment by stm9x9** [comment]
Ich bitte dringend darum, davon Abstand zu nehmen. Nicht nur, daß es inhaltlich / grammatikalisch falsch ist (einschließlich des Gerundiums) und es auch genügend gerade Frauen gibt, die nicht unterschiedlich bezeichnet werden wollen, sind da auch noch blinde und sehbehinderte Menschen, für die diese :/*-Lösungen problematisch sind.

Einen Safe-Space schaffe ich für meine Mitarbeiter (m/w/d) indem ich sie gut behandle, sie als Menschen akzeptiere, eine freundliche Atmosphäre schaffe ...

**Comment by stm9x9** [comment]
> Wenn ich mir aber den umgekehrten Fall vorstelle (Ich als Mann würde durchgehend als "Nutzerin" und "Sachbearbeiterin" angesprochen werden) würde ich auch eindeutig Handlungsbedarf sehen.

Was schlicht daran liegt, daß die movierte, feminine Form nach unserer Grammatik den ausdrücklichen Hinweis enthält: Person ist weiblich. Während die Grundform eben neutral ist und keinen Hinweis zum Geschlecht übermittelt. Gibt es auch umgekehrt: Die Geisel ist feminin, kann aber männlich wie weiblich sein. Oder die Katze ist feminin, aber es gibt männliche und weibliche Katzen. Erstere kann auch Kater genannt werden. Da wäre jeder Katzenhalter irritiert, wenn man seine weibliche Katze einen Kater nannte ... Der Halter eines Katers aber kauft ohne auch nur drüber nachzudenken einen Kratzbaum für Katzen.

Daß sich etliche nicht mehr durch das genderneutrale (erstmal nur grammatikalisch maskuline (es hilft auch sehr, beim Geschlecht des Wortes von maskulin/feminin/neutrum zu sprechen und bei dem Geschlecht von Personen von männlich/weiblich)) Grundwort angesprochen fühlen, ist IMHO auch ein "Erfolg" gerade der "gegenderten" Sprache, die als erste Maxime lehrt: "Fühle dich als weibliche Person nicht von maskulinen Bezeichnungen angesprochen!" Eine selbst-erfüllende Prophezeiung quasi.

**Comment by GuidoBo** [comment]
> sind da auch noch blinde und sehbehinderte Menschen, für die diese :/*-Lösungen problematisch sind.
Kennst Du konkret jemanden, der damit Probleme hat?

**Comment by j-dimension** [comment]
> > sind da auch noch blinde und sehbehinderte Menschen, für die diese :/*-Lösungen problematisch sind.
> 
> Kennst Du konkret jemanden, der damit konkret Probleme hat?

Vermutlich meint @stm9x9 Anwender, die Tools einsetzen welche den Bildschirminhalt "vorlesen", wenn man mit der Maus drüberfährt.

**Comment by GuidoBo** [comment]
> Vermutlich meint @stm9x9 Anwender, die Tools einsetzen welche den Bildschirminhalt "vorlesen", wenn man mit der Maus drüberfährt.

Ja, vermutlich waren diese Leute gemeint. Die Aussage hat mich ehrlich gesagt mega getriggert, mein Vater gehört nämlich dazu, denn er ist blind (nicht nur "sehbehindert", sondern blind mit Assistenz-Hund und allem Pipapo).

Die Erzählung, dass gendersensitive Schreibung zu Problemen mit Screenreadern führt, kommt immer wieder. Sie geht wohl auf eine innerhalb der Community extrem umstrittene [Publikation des dbsv](https://www.dbsv.org/gendern.html#barrierefreiheit) zurück. Die Erzählung, die oft als Alibi genutzt wird, ist besonders ärgerlich, weil sie den Anschein erweckt, es komme wegen technischer Aspekte zu Problemen beim Verstehen von Texten. Das ist aber nicht so. Tatsächlich orientiert sich der Text - so eine Legitimation - maßgeblich an den Duden-Empfehlungen. Beim aufmerksamen Lesen des Textes wird klar: es geht maßgeblich darum, dass die Vorlesepraxis stark variiert. Das "Problem" liegt also an der Vielzahl der Lese-Variationen. Seit sich der Glottisschlag etabliert hat, ist das Thema weitgehend aus der Welt. Evidenz dafür, dass das Lesen mit Glottisschlag tatsächlich zu Problemen führt gibt es m.W. nicht. Eher ist m.E. das Gegenteil der Fall: 

Menschen, die blind oder sehbehindert sind, [feiern gerade Apple-Produkte total, hier: Peer aus Kassel](https://www.youtube.com/watch?v=dgk_Jawzdwk), weil sie auch ohne visuelles Feedback extrem gut benutzbar sind. Die Sprachsynthese dort funktioniert seit vielen Jahren sehr, sehr gut und imitiert seit längerem auch einen Glottisschlag an exakt der richtigen Stelle (am Doppelpunkt). Unter Windows ist die "Cortana-Sprachsynthese" seit etwa drei Jahren wohl entsprechend angepasst.

Ich bin sehr für Verständlichkeit von Texten. Leichte Sprache und Gendersensitivität sind da auch überhaupt kein Widerspruch (Gendersensitive Sprache und Gebärdensprache übrigens oft schon; sprecht mit der Gebärden-Dolmetschperson eures Vertrauens mal über den Unterschied zwischen den Gebärden für Geschlechtsverkehr und Vergewaltigung). Gerade unter Jurist:innen wundere ich mich aber schon, dass es bei "Nutzer:innen" einen Aufschrei gibt, während "Grundstücksverkehrsgenehmigungszuständigkeitsübertragungsverordnung" irgendwie mit einem gewissen Stolz daher kommt. Abgesehen hiervon legt die Verwendung des "ja, aber die blinenden Menschen"-Arguments immer die Vermutung nahe, es würde eine marginalisierte Gruppe gegen eine andere ausgespielt.

Ich wünsche mir in diesem Kontext letztlich nicht mehr (aber auch nicht weniger), als dass diejenigen Menschen, die gendersensitiver Sprache Unverständlichkeit vorwerfen, sich auch in allen anderen Bereichen des Lebens mit demselben Eifer um Textverständlichkeit bemühen. Meine Erfahrung ist aber, dass diese Schnittmenge extrem klein ist. 

Was übrigens wirklich hart für Screenreader ist, sind Fachtexte (insbesondere juristische). Wer sich davon einen Eindruck verschaffen möchte kann die eigenen Schriftsätze (oder besser: die der Gegenseite) unter MacOS gern mal vorlesen lassen (option + esc).

**Comment by stm9x9** [comment]
> Beim aufmerksamen Lesen des Textes wird klar: es geht maßgeblich darum, dass die Vorlesepraxis stark variiert. Das "Problem" liegt also an der Vielzahl der Lese-Variationen. Seit sich der Glottisschlag etabliert hat, ist das Thema weitgehend aus der Welt. Evidenz dafür, dass das Lesen mit Glottisschlag tatsächlich zu Problemen führt gibt es m.W. nicht. Eher ist m.E. das Gegenteil der Fall:

ich lese da wesentlich mehr Probleme als nur Variationen:

> Auch Computersysteme können Texte vorlesen. Dabei gibt es unterschiedliche Optionen, wie Satz- und Sonderzeichen behandelt werden – je nachdem welche Software, also welcher Screenreader, verwendet wird. Gelingt es, das Vorlesen bestimmter Zeichen gezielt zu verhindern, werden diese immer unterdrückt – beispielsweise wird ein Stern, der in einem Formular ein Pflichtfeld markiert, dann ebenfalls nicht vorgelesen.  
> ...
> In Bezug auf Barrierefreiheit müssen neben dem zentralen Aspekt des Vorlesens weitere Aspekte bedacht werden, wie die Sprachausgabe, die je nach Nutzergruppe sehr unterschiedlich eingestellt wird, und die Ausgabe der Sonderzeichen auf dem Blindenschrift-Display, mit dem digitale Inhalte für blinde Menschen dargestellt werden. Bei Texten in Brailleschrift – auch in Papierform – müssen Sonderzeichen durch spezielle Ankündigungszeichen als solche gekennzeichnet werden, was den Lesefluss behindert. Erschwerend kommt hinzu, dass es aktuell keine einheitliche Gendervariante gibt, auf die sich Personen, die vorlesen, und die Hersteller von Computerprogrammen einstellen könnten.
> 
> Der Genderdoppelpunkt
> Der Doppelpunkt steht auf einer Liste nicht empfohlener Gender-Kurzformen des Deutschen Blinden- und Sehbehindertenverbandes. Gründe sind Probleme beim Vorlesen – sei es durch einen Computer oder durch eine Person – und bei der Darstellung in Blindenschrift. Trotzdem wird der Doppelpunkt zunehmend als eine besonders blinden- und sehbehindertenfreundliche Form des Genderns dargestellt. Grund ist vermutlich die Annahme, dass der Doppelpunkt von Screenreadern standardmäßig nicht vorgelesen werde, weil er im Gegensatz zu Stern und Unterstrich kein Sonderzeichen, sondern ein Interpunktionszeichen ist. Abgesehen davon, dass dies von den Screenreadern unterschiedlich gehandhabt wird, hat der Doppelpunkt jedoch wichtige Funktionen, weshalb viele blinde und sehbehinderte Menschen ihn sich vorlesen lassen. Das Unterdrücken des Doppelpunktes führt zudem zu einer längeren Pause als das Unterdrücken anderer Zeichen. So kann der Eindruck entstehen, der Satz sei zu Ende.
>

**Comment by stm9x9** [comment]
> Ich bin sehr für Verständlichkeit von Texten. Leichte Sprache und Gendersensitivität sind da auch überhaupt kein Widerspruch 

Ich habe nur die ersten Treffer aus google genommen. Alle sehen Probleme:

https://geschicktgendern.de/gendern-und-leichte-sprache/
https://www.genderleicht.de/gendern-in-leichter-sprache-anleitung/
https://cotelangues.com/de/wie-gendert-man-in-leichter-bzw-einfacher-sprache/

> Gerade unter Jurist:innen wundere ich mich aber schon, dass es bei "Nutzer:innen" einen Aufschrei gibt, während "Grundstücksverkehrsgenehmigungszuständigkeitsübertragungsverordnung" irgendwie mit einem gewissen Stolz daher kommt.

Das mag zum einen daran liegen, daß die Sprache das Handwerkszeug des Juristen ist und wir daher in der Regel ein besonderes Gespür dafür haben, wie Sprache funktioniert und wie nicht. Zum anderen, auf Grundstücksverkehrsgenehmigungszuständigkeitsübertragungsverordnung ist man allenfalls in selbstironisierender Weise stolz.

**Comment by stm9x9** [comment]
bitte allenfalls als Option
