### ISSUE TITLE
[BUG] Termin in Handakte nicht sichtbar

### ISSUE THREAD

**Issue by Bentipa** [jlawyerorg/j-lawyer-org#1544]
**Describe the bug / Fehlerbeschreibung**
Wenn ich in einer Akte einen Termin anlege wird dieser in der generierten Handakten nicht angezeigt.
Nur Fristen / Wiedervorlagen werden angezeigt.

**To Reproduce / Schritte zum Nachvollziehen**

1. Akte öffnen
2. Termin hinzufügen
3. Handakte öffnen

**Expected behavior / Erwartetes Verhalten**
Termin sollte unter "Termine" gelistet werden.

**Screenshots**
![image](https://user-images.githubusercontent.com/11789478/151153771-bdcc3b07-886a-4ef3-9dca-822fc1084e48.png)
![image](https://user-images.githubusercontent.com/11789478/151153714-049411ff-3caa-47f7-b836-e51c946fff35.png)

**Environment / verwendete Umgebung:**
 - OS / Betriebssystem: Linux Mint und Windows (Clients, beides getestet), Linux / Ubuntu (Server)
 - j-lawyer.org Version: 2.0.1.0 (Server+Client)

**Comment by j-dimension** [comment]
Reports-Definitionen in https://github.com/jlawyerorg/j-lawyer-org/tree/master/j-lawyer-client/src/reports, insbesondere reviews und review_details

Reportaufruf ist in Methode tabPaneArchiveFileStateChanged der Klasse https://github.com/jlawyerorg/j-lawyer-org/blob/master/j-lawyer-client/src/com/jdimension/jlawyer/client/editors/files/ArchiveFilePanel.java

**Comment by j-dimension** [comment]
https://www.j-lawyer.org/?topic=termine-nicht-in-handakte#post-4760
