### ISSUE TITLE
[FEATURE] mehrzeilige Script-Ergebniswerte unterstützen

### ISSUE THREAD

**Issue by j-dimension** [jlawyerorg/j-lawyer-org#1549]

**Comment by GuidoBo** [comment]
Sollten es nicht "mehrere Absätze" (Statt "mehrere Zeilen") sein?

**Comment by LazyGuy21No** [comment]
Alternativ: Ein Platzhalter für "Zeilenumbruch", ein Platzhalter für "Absatz" und ein Absatz für "Tabulator", die auch innerhalb eines Skripts verwendet werden können.

**Comment by j-dimension** [comment]
@LazyGuy21No ich habe mir das gerade mal i.V. mit LibreOffice angeschaut. Ihr könnt in einem Script bereits jetzt

\n für neue Zeile
\t für Tabulator

aufnehmen.

Aus 

`Hallo hier folgt eine neue Zeile\nund das folgende Wort ist eingerückt:\teingerückt`

wird dann

```
Hallo hier folgt eine neue Zeile
und das folgende Wort ist eingerückt:                    eingerückt
```

Hilft Euch das weiter? Dann würde ich dieses Ticket schließen und dieses Verhalten vor Veröffentlichung lediglich in die Doku aufnehmen.

**Comment by LazyGuy21No** [comment]
Der echte Absatz wäre schon eher wichtig. Meine Vorlagen unterscheiden immer zwischen Absatz (mit Abstand darüber/-runter) und LineBreak (nur Notlösung).

**Comment by stm9x9** [comment]
sowas wie \p für paragraph gibt es wohl nicht, oder?
