### ISSUE TITLE
Festpinnen Favourit

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-org#155]
Favouritenherzchen ist praktisch. Praktischer wäre, wenn man das Herz an seiner Position nach dem Umsortieren oben oder unten festpinnen könnte (oder eben an seiner aktuellen Position) und es dort bleibt, wenn man die Dateien umsortiert oder in den Ordner ein oder aussteigt.

**Comment by Mucki526** [comment]
Ganz einfach, Ich habe z.B.: Zeiterfassung, Kontenblatt und an den Mandaten bereits gestellten Kostennoten und besondere Honorarvereinbarungen auf einen Blick ganz oben, wenn ich in den Ordner gehe. Im Papierordner habe ich die Kostennoten, Kostenblätter und Vollmachten, Honorarvereinbarungen, Berechnungen etc. auch in separaten Ordnern und ganz oben oder unten in der Akte.  Als Pin hätten alle diese Dokumente dann ein Favouritenherzchen (nett) mit Pfeil durch, weil sie ja oben festgepinnt sind ;-)). Derartige Pinnadeln gibt es z.B. bei Microsoft in neueren Wordversionen. Sonst muss ich erst immer alle Herzchen sortieren und dann für die Übersicht wieder die Dokumente z.B. nach Datum umsortieren. Man könnte alternativ auch Ordner Im Dokumentenordner anlegen können (Vollmachten, Kostennote, Zeiterfassung, Unterlagen Mandant) wie jetzt sinnvoll bei den Vorlagen, aber da muss man halt jedesmal in den Ordnerbaum einsteigen. Bei den festgepinnten Favouriten habe ich wichtige Dokumente aus dem Dokumentenordner (oder was ich für wichtig halte) aber sofort beim Einstieg im Blickfeld. Bei 200 Dokumenten in einem großen Mandant ist mir das lieber als alle Herzchen jedesmal nach oben zu sortieren, dann habe ich auch evt. die Kostennoten nicht alle beieinander, wenn ein anderer Favourit dazwischen ist. Alternativ oder ergänzend könnte man ja vielleicht oberhalb der Dokumente ein Fenster einbauen, in dem ich die Dokumente oder Favouriten ziehe, die immer oben sind, solange sie dort liegen, quasi als "gläserner Ablageschale".

**Comment by j-dimension** [comment]
> Sonst muss ich erst immer alle Herzchen sortieren und dann für die Übersicht wieder die Dokumente z.B. nach Datum umsortieren.

Nein, Du würdest einfach die Akte öffnen und musst nichtmal in den Dokumente-Reiter wechseln, sondern hast ganz oben rechts den Favoritenknopf, wo Du alle Favoritendokumente sofort parat hast. Oder?

**Comment by Mucki526** [comment]
O.k. das ist natürlich ein Argument, ich dachte der Knopf sortiert nur die Favouriten nach oben in den Dokumenten, aber der kann ja mehr. Cool... - Wenn ich jetzt diese Favouriten noch irgendwie frei sortieren könnte, dann wäre das perfekt und besser als ein Festpinnen und ein gläserner Ordner, der nur bei Bedarf aufgeht....

**Comment by Mucki526** [comment]
z.B. mit linker Tast im sich öffnenden Herzfenster greifen und dauerhaft hoch oder runtersortieren...
