### ISSUE TITLE
[kalender] Ansicht: "Kalender suchen" - Suche nach Aktenzeichen

### ISSUE THREAD

**Issue by iradraconis** [jlawyerorg/j-lawyer-org#1551]
Unter "Kalender suchen" kann der Nutzer die Einträge filtern. Dort erscheinen auch erledigte Einträge bzw. Termine. 
Eine Suche/Sortierung nach Aktenzeichen wäre toll. So könnte man alle Termine aus einer Akte sehen.

**Comment by j-dimension** [comment]
@iradraconis Du meinst "suchen", nicht "fehlende", oder?

**Comment by iradraconis** [comment]
Ja, sorry. War für einen Freund :) ich ändere das eben...

**Comment by j-dimension** [comment]
Okay, aber dort gibt es doch eine Sortierung.

**Comment by iradraconis** [comment]
Richtig, ohne eine vorherige Suche nach Az. muss aber dann innerhalb der sortierten Ergebnisse nach dem eigentlichen Az gesucht werden. Der Schwerpunkt des Tickets liegt tatsächlich auf der Suche nach dem Az. Ich entschuldige mich für die missverständliche Bezeichnung.

**Comment by j-dimension** [comment]
Works like a charm. Danke, @Bentipa !
