### ISSUE TITLE
[BUG] [beA] Speichern von Anhängen fehlerhaft bei button-Nutzung 

### ISSUE THREAD

**Issue by librelegal** [jlawyerorg/j-lawyer-org#1554]
Das Speichern der Anhänge einer beA - Nachricht kann auf zwei Wegen erfolgen. 
Erstens kann man alle Anhänge markieren und dann einen Rechtsklick in Akte Speichern wählen. Es werden Dateinamen vorgeschlagen, bei denen das aktuelle Speicherdatum und -zeitpunkt vorangestellt werden. Dies bestätigt man mit OK. Will man auch die Nachricht speichern, bedarf dies eines weiteren Vorgangs.

Bei der zweiten Möglichkeit tritt ein Fehler auf. Man kann den button rechts "Nachrichten und Anhänge werden beide separat in die Akte übernommen" nutzen. Bei einer Nachricht mit 13 Anhängen wurden jedoch nur 5 Anhänge in der Akte gespeichert.

Es erfolgt nachstehende Meldung, wonach ein bestimmtes Dokument (das fünfte Dokument) ""Authentizitätsnachweis.pdf" nicht gespeichert werden konnte, weil es bereits vorhanden sei. Ein neuer Dateiname bestehend aus Speicherdatum und -zeitpunkt wird nicht vorgeschlagen.
![image](https://user-images.githubusercontent.com/37673969/152334822-a567bd08-eaa3-4b5c-b1f9-1f6c83a352bd.png)

Tatsächlich findet sich ein solches Dokument bereits digital in der Akte. Es wird allerdings immer wieder so sein, da das Gericht diese immer übersendet, also diese Datei typischerweise bereits vorhanden ist. Eine automatische Umbenennung oder wenigstens ein Vorschlag mit z.B. aktuellem Datum würde Sinn machen. 
Unbedingt aber muss die Speicherung der nachfolgenden Dateien fortgesetzt werden, was nicht der Fall ist. An dieser Stelle wird abgebrochen, ohne dass ein Hinweis auf die nur teilweise Speicherung erfolgt.

**Environment / verwendete Umgebung:**
 - OS / Betriebssystem: Debian 10
 - j-lawyer.org Version: 2.0.1.0

**Comment by Maz111111** [comment]
siehe #1225
das dürfte die gleiche Problematik sein

**Comment by Maz111111** [comment]
Ich löse die Angelegenheit zwischenzeitlich so, dass ich die gesamte beA Nachricht in die Akte übernehme und dann innerhalb der Akte den Anhang den ich will über Rechtsklick -> in Akte speichern zuordne . Dann kommt nämlich ein Ubenennendialog und ich kann den Namen anpassen.
Ist wahrscheinlich auch der elegantere Weg, da man damit die gesamte beA Nachricht in der Akte hat. Die Anhänge fressen dann zwar doppelt Speicherplatz - aber was solls.
Die gesamte beA Nachricht selbst verschiebe ich dann in einen ausgeblendeten Ordner. Ergebnis ist das gleiche - nur mit dem Unterschied, dass ich die Anhänge der beA Nachricht, die ich faktisch zum Arbeiten nicht brauche, trotzdem in der beA Nachricht und damit in der Akte gesichert habe.

**Comment by Maz111111** [comment]
Nun habe ich das Problem, dass mir das Gericht sogar gleichlautende beA Nachrichten sendet.

Die oben beschriebene Vorgehensweise läuft dann auch ins Leere.

Ich habe jetzt eine beA Nachricht im Posteingang und habe gerade keine Vorstellung, wie ich die in die Akte bekomme. Die Anhänge haben zum Teil bereits vom Gericht vergebene Namen und die beA Nachricht existiert mit diesem Namen auch schon.

Es kommt immer die Fehlermeldung, dass ich einen anderen Namen vergeben soll. Allein gibt mir jL keine Möglichkeit dazu.

**Comment by librelegal** [comment]
Die vorgeschlagene Automatisierung des Vorgangs klingt sinnvoll

**Comment by j-dimension** [comment]
wird über #1225 gelöst
