### ISSUE TITLE
[FEATURE] Implementierung XJustiz 3.3.1 (gültig ab 31.10.2022)

### ISSUE THREAD

**Issue by j-dimension** [jlawyerorg/j-lawyer-org#1555]
https://xjustiz.justiz.de/xjustiz_3_3_1/index.php

**Comment by librelegal** [comment]
Dieser bug ist Milestone 2.3 vorgesehen. Falls Xjustiz aber vorher gültig wird, könnte es Probleme geben. Evtl. sollte erwogen werden, diesen bug noch in milestone 2.2 aufzunehmen?

**Comment by j-dimension** [comment]
Sehr aufmerksam - ja, sollte vorgezogen werden.

**Comment by j-dimension** [comment]
Gelöst via bea Wrapper Ticket 77

Testdatensatz an BRAK gesendet
