### ISSUE TITLE
[BUG] Dateien lassen sich nicht per Drag n Drop in Ordner verschieben. Drag n Drop von Emails in Unterordner funktioniert nicht

### ISSUE THREAD

**Issue by iradraconis** [jlawyerorg/j-lawyer-org#1557]
Meine Mitarbeiter nutzen einen M1 iMac mit MacOS Monterey in Version 12.2. Gestern hieß es, dass Drag n Drop von Dokumenten in Unterordner nicht funktioniere und auch Emails sich nicht verschieben lassen. Ich konnte das erst nicht nachvollziehen, da ich auf meinen M1 Macbooks (13 Zoll MB Pro und 16 Zoll MB Pro, diesselbe MacOS Version) das Problem noch nicht bemerkt habe und ich würde mich als VIELNutzer bezeichnen ;)  Nachdem ich also erst dachte, das Problem sitzt vor dem Monitor, habe ich festgestellt, dass der Fehler tatsächlich so auftritt, wie beschrieben. Ein sporadischer Neustart des Clients helfe gelegentlich. Jetzt ist eine Sache noch auffällig: Die Mitarbeiterin, die deutlich häufiger da ist, beobachtet das Problem seltener. Die Mitarbeiterin, die nur 8 Stunden die Woche da ist, beobachtet das Problem häufiger. Ich, der am meisten da ist, beobachtet das Problem gar nicht. 

WAS ich hingegen häufig erlebe, ist, dass Klicks nicht registriert werden, aber da gibt es bereits in Ticket. 

Ich kann mir vorstellen, dass das extrem schwer nachzuvollziehen ist. Ggfs. könntest du, Jens, mal in einer ruhigen Minute per Fernwartung draufschauen, sofern du das für erforderlich hälst. 

Vielleicht passt dieser Bug auch zu #1529

**Comment by j-dimension** [comment]
@iradraconis mir wäre sehr an einer Fernwartung zu #1312 gelegen, da ich hier gern in 2.1 noch Hand anlegen möchte. Vielleicht lässt sich das verbinden.

**Comment by j-dimension** [comment]
@iradraconis besteht dieses Problem noch? Ich kriege es nicht reproduziert.

**Comment by iradraconis** [comment]
Da muss ich meine MAin drauf ansetzen, da das an meinem Arbeitsplatz nie passiert war. Ich melde mich dazu.
