### ISSUE TITLE
Einstellungen für externe Programme werden nicht benutzt - Bilder öffnen mit Draw

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#1566]
Ich kann gar nicht genau sagen seit wann, aber vor ein paar Tagen bemerkte ich, daß sämtliche Einstellungen für externe Programme weg waren. Ich habe sie für jpg und jpeg neu erstellt, aber es wird dennoch immer mit LibreDraw geöffnet.

![image](https://user-images.githubusercontent.com/29924198/153916246-199c5729-38fb-4ffc-9ca6-cfd2c0606372.png)

![image](https://user-images.githubusercontent.com/29924198/153916286-02da711b-e784-4c69-8d86-739d213c4273.png)

**Comment by j-dimension** [comment]
"Öffnen mit" hat noch nie die externen Programme angezeigt. Die kommen direkt bei Doppelklick auf das Dokument zum Tragen.

**Comment by j-dimension** [comment]
Die Einstellungen liegen im Nutzerprofil des Arbeitsplatzes, da es bspw nicht sinnvoll ist, diese Einstellungen mitzunehmen, wenn man von einem Windows-Arbeitsplatz zu einem mit Linux wechselt.

Anderer Arbeitsplatz oder neues Nutzerprofil - - > Einstellungen zu externen Programmen neu erstellen.

**Comment by stm9x9** [comment]
Auch auf Doppelklick wird mit Draw geöffnet.

und sie verschwanden auf ein und demselben Arbeitsplatz - aber das ist ja nicht mein Hauptproblem. Aber neues Nutzerprofil? Die Einstellungen sind doch dem Admin vorbehalten für alle Nutzer an einem Rechner?

**Comment by j-dimension** [comment]
> Auch auf Doppelklick wird mit Draw geöffnet.

Dann bitte client.log sichten / senden.

**Comment by j-dimension** [comment]
> Die Einstellungen sind doch dem Admin vorbehalten für alle Nutzer an einem Rechner?
Die Einstellungen liegen im Profil des Betriebssystemnutzers. Da spielt es also keine Rolle, wie man sich an der KSW anmeldet, aber ein zweiter OS-Nutzer hat diese Einstellungen nicht.
