### ISSUE TITLE
[FEATURE] mehrere externe Programme pro Dateityp

### ISSUE THREAD

**Issue by j-dimension** [jlawyerorg/j-lawyer-org#1568]
- [x] externe Programme im Kontextmenü anzeigen: bei jedem Öffnen das Kontextmenü zurücksetzen: 0,25h
- [x] externe Programme im Kontextmenü anzeigen: bei jedem Öffnen den Dateityp ermitteln und das Kontextmenü entsprechend Konfiguration erweitern: 0,75h
- [x] externe Programme im Kontextmenü anzeigen: wenn unterschiedliche Dateitypen markiert sind, werden keine externen Programme angeboten: 0,25h
- [x] mehrere Programme pro Dateityp ermöglichen: Oberfläche und Aktionen: 1,5h
- [x] mehrere Programme pro Dateityp ermöglichen: neues Format für das Speichern der Konfiguration (da aktuell der Dateityp als Schlüssel verwendet wird, und der ist dann nicht mehr eindeutig): 2h
- [x] zusätzliche Konfiguration: "als Standard nutzen" (für Doppelklickaktion) - sind zwei externe Programme für den selben Dateityp konfiguriert, muss ein "Standard" auswählbar sein. Ist kein Standard konfiguriert, wird ein beliebiges konfiguriertes Programm genutzt: 0,5h
- [x] automatische Migration von altem Konfigurationsformat auf neues Format: 1,5h
- [x] Doku anpassen: 0,5h

**gesamt: 7,25h**

**Comment by j-dimension** [comment]
Erste Anwendung, die für PDF konfiguriert ist. Sie ist als Standardanwendung definiert, wird also auch bei Doppelklick auf das Dokument benutzt:
![image](https://user-images.githubusercontent.com/3729754/157977609-deaaebde-96fc-4777-bfd5-091a60f70c85.png)

**Comment by j-dimension** [comment]
Zweite Anwendung, ebenfalls PDF, aber kein Standardprogramm. Sie kann nur per Kontextmenü aufgerufen werden.

![image](https://user-images.githubusercontent.com/3729754/157977858-bb109616-b090-4c83-9b59-c9072152e570.png)

**Comment by j-dimension** [comment]
Kontextmenü "öffnen mit" bietet nun Zugriff auf alle externe Programme, die für den Dateityp konfiguriert sind:

![image](https://user-images.githubusercontent.com/3729754/157978229-a64d3737-aff2-4fc0-8738-52345f0b0004.png)

**Comment by j-dimension** [comment]
@iradraconis siehe Screenshots

**Comment by iradraconis** [comment]
> @iradraconis siehe Screenshots

perfekt!! 👍🏻

**Comment by j-dimension** [comment]
bug: doppelte Anwendungsnamen verhindern

**Comment by iradraconis** [comment]
kurzes vorab-Feedback, probiere morgen noch mal genauer: 
In der Preview von heute funktioniert das bei mir noch nicht. Getestet mit pdf- und html - Dateien. Wenn die Programme angelegt sind, tut sich nichts, bei Auswahl des Programms. 

MacOs Monterey 12.3

**Comment by iradraconis** [comment]
client.log

2022-03-25 07:25:07,377 ERROR [com.jdimension.jlawyer.client.launcher.CustomLauncher] error in custom launcher for pdf
java.io.IOException: Cannot run program "/Applications/PDFScanner.app/PDFScanner.app": error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1128) ~[?:?]
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1071) ~[?:?]
	at com.jdimension.jlawyer.client.launcher.CustomLauncher.lambda$launch$1(CustomLauncher.java:799) ~[j-lawyer-client.jar:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.ProcessImpl.forkAndExec(Native Method) ~[?:?]
	at java.lang.ProcessImpl.<init>(ProcessImpl.java:340) ~[?:?]
	at java.lang.ProcessImpl.start(ProcessImpl.java:271) ~[?:?]
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1107) ~[?:?]
	... 3 more

**Comment by iradraconis** [comment]
wenn im Client unter MacOs ein Programm, also zum beispiel "Preview.app" ausgewählt wird, wird diese Datei wie ein Ordner geöffnet. Die "Preview.app" oder in meinem Fall PDFScanner.app, kann nicht direkt als "Datei"/"Programm" ausgewählt werden. Was genau muss denn ausgewählt werden, damit das funktioniert?

**Comment by iradraconis** [comment]
Der Versuch, die Preview.app zum Standard zu machen, nachdem J-Lawyer diese nicht mehr standardmäßig nutzt führt zu folgendem Fehler: 

Client.log
"Die Datei „2021-10-26_3366-21 AG Aktenuebersendung.pdf“ konnte nicht geöffnet werden, da du nicht die Zugriffsrechte hast, um sie anzuzeigen." UserInfo={NSFilePath=/Users/maximiliansteinert/.j-lawyer-client/tmp-documents/1648795441040_bfd15390c0a808842cc3018b5edbd9ee/2021-10-26_3366-21 AG Aktenuebersendung.pdf, NSUnderlyingError=0x60000245dc50 {Error Domain=NSPOSIXErrorDomain Code=1 "Operation not permitted"}}

**Comment by j-dimension** [comment]
@iradraconis wenn es unter Monterey Zugriffsfehler gibt, nutze bitte den Standardöffner "open" wie folgt:
<img width="609" alt="Bildschirmfoto 2022-03-25 um 10 15 21" src="https://user-images.githubusercontent.com/3729754/160091857-70f571da-cbb8-4401-b6c5-111f57219730.png">

**Comment by j-dimension** [comment]
"open" hat einen Parameter -a, über den kann der Anwendungsname angegeben werden.

**Comment by j-dimension** [comment]
> 2022-03-25 07:25:07,377 ERROR [com.jdimension.jlawyer.client.launcher.CustomLauncher] error in custom launcher for pdf java.io.IOException: Cannot run program "/Applications/PDFScanner.app/PDFScanner.app": error=2, No such file or directory 

Da hast Du wahrscheinlich den Ordner der Anwendung angegeben. Die ausführbare Datei liegt meist in einem Unterverzeichnis namens "Contents/MacOS", für Preview/Vorschau wäre die vollständige Angabe

/System/Applications/Preview.app/Contents/MacOS/Preview

**Comment by iradraconis** [comment]
Jetzt klappt alles wie es soll!! DANKE! Da wäre ich nie von selbst drauf gekommen!

**Comment by j-dimension** [comment]
@iradraconis ja, das ist unter macOS etwas seltsam zu konfigurieren. Aber zumindest auch in der Doku beschrieben
http://www.j-lawyer.org/downloads/documentation/j-lawyer.org-UserGuide-de.html#__RefHeading__429_1146603382

**Comment by iradraconis** [comment]
> @iradraconis ja, das ist unter macOS etwas seltsam zu konfigurieren. Aber zumindest auch in der Doku beschrieben
> http://www.j-lawyer.org/downloads/documentation/j-lawyer.org-UserGuide-de.html#__RefHeading__429_1146603382

ok, ich war wieder zu ungeduldig ;) hab den Wink verstanden!
