### ISSUE TITLE
[FEATURE] Längeres Passwort für Nextcloudanbindung zulassen "Data too long for column"

### ISSUE THREAD

**Issue by niciti** [jlawyerorg/j-lawyer-org#1575]
Hi,

da es bisher anscheinend noch niemand getan hat, eröffne ich mal meinen ersten Verbesserungsvorschlag.

Wenn man ein langes Nextcloudpasswort verwendet, kann der Kalender nicht in die Nextcloud eingebunden werden.

Beim Klicken auf „Übernehmen“ kommt die Fehlermeldung „Failed to read response“ und die Daten werden nicht gespeichert

und im Log steht:

Caused by: com.mysql.cj.jdbc.exceptions.MysqlDataTruncation: Data truncation: Data too long for column ‚cloudPassword‘ at row 1

Also würde ich bitten die Zeichenbeschränkung aufzuheben bzw. deutlich zu erweitern.

LG,
niciti

**Comment by j-dimension** [comment]
Danke für das Ticket. Ist bereits zuvor gemeldet worden und im aktuellen Entwicklungsstand bereits umgesetzt. Wird mit der Version 2.1 geliefert.

https://github.com/jlawyerorg/j-lawyer-org/issues/1550
