### ISSUE TITLE
[BUG] E-Mail-Empfänger wird mit Komma angezeigt

### ISSUE THREAD

**Issue by Dickmaulruessler** [jlawyerorg/j-lawyer-org#1577]
Wenn ich eine E-Mail versende und den Empfänger über die Lupe aus den dann dort vorgeschlagenen Beteiligten übernehme, steht vor der E-Mail immer ein Komma, auch bei nur einer einzigen E-Mailadresse.

![jfkldöjafkldösaf](https://user-images.githubusercontent.com/46451749/157508700-288e0c78-983c-450a-be67-2a83df20e4f3.jpg)

**Comment by j-dimension** [comment]
Danke. Das hat - bis auf die Optik - keinerlei negative Auswirkungen. Werde es im Rahmen der 2.2 anschauen.
