### ISSUE TITLE
[BUG] beA Anhang darf nur 84 Zeichen inkl Erweiterung und nur bestimmte Sonderzeichen haben

### ISSUE THREAD

**Issue by Maz111111** [jlawyerorg/j-lawyer-org#1578]
Ich habe gestern eine beA Nachricht mit j-lawyer versendet.
Einer der Anhänge war wie folgt benannt:
2022-03-10_Schreiben-an-Amtsgericht-Halle-(Saale)-per-beA-vorab-Fax--Verteidigungsanzeige-mit-Abweisungsantrag.pdf
Sowohl in jL as auch in der beA Weboberfläche wurde die Nachricht als erfolgreich versendet dargestellt (der Anhang auch).

Der Anhang wurde mit dem oben dargestellten Namen von jL übermittelt und wird im Web in beA auch exakt so als Anhang angezeigt (Dateiname und Bezeichnung).

Heute rief mich das Gericht an und teite mit, dass nur die Vollmacht angekommen sei. Daraufhin versendete ich die Nachricht erneut. Abermals meldete jL "erfolgreich" und auch in der Weboberfläche stand "erfolgreich"

Ich erhielt nun eine beA Nachricht von der Poststelle, in wecher mir diese mitteilte, dass der Anhang "Schreiben an Amtsgericht" fehlen würde.

Dann habe ich versucht, die Nachricht direkt über die Weboberfläche zu senden. Dort erhielt ich beim Hochladen dann die Meldung, dass der Anhang entfernt worden sei und dass der Name nur 84 Zeichen lang sein und nur "-" und "_" verwendet werden dürfen.

Erst nachdem ich den Namen der Datei in "2022-03-10_Schreiben-an-Amtsgericht-per-beA.pdf" geändert hatte, konnte ich senden.

jL sollte das prüfen und die Namen anpassen. Ich weiß, dass das eigentlich so bereits programmiert ist und von allein klappen sollte. Hier hat es aber mehrfach nicht geklappt.

Außerdem sollte man prüfen, warum beA - wenn es von jL "gefüttert" wird - die Fehlermeldung nicht bringt und sogar einen erfolgreichen Versand (inkl. der angehängten Nachricht) meldet.

**Comment by Maz111111** [comment]
Aso ich habe jetzt nochmal meine anderen Verfahren durchgesehen. Die "( )" scheinen zumindest bei der Zustellung an einen Anwalt kein Probem zu machen.

Bin mir aber nicht sicher.

Aerdings ist nicht jedes Gericht so nett und blickich. AG Köthen druckt offenbar einfach nur aus und versendet an den GG. Dort wurd emir ein Schreiben des GG zugestellt, in welchem dieser beklagt, nur meine Vollmacht erhalten zu haben und anfragt, ob nicht etwas fehlt. Ich habe kontrolliert und hier war überall ein vollständig erfolgreicher Versandt vermerkt und dachte, das Gericht habe einen Fehler gemacht.

Jetzt wird mir klar, dass das Gericht gar nicht gemerkt hat, dass ein Anhang fehlt.

Insofern halte ich die Sache für ein akutes Problem.

**Comment by j-dimension** [comment]
Ich habe das neue Regelwerk bzgl. Dateinamen bereits umgesetzt und liefer das mit der kommenden 2.1
https://github.com/jlawyerorg/j-lawyer-org/issues/1190

Dass das beA über die externen Schnittstellen alles völlig lautlos akzeptiert, ist natürlich Mist.

**Comment by librelegal** [comment]
Bei der Benennung scheint es noch Rest-Probleme zu geben. Ich habe die Hoffnung, dass sich die noch vor der Version 2.1 lösen lassen.  

Die Anforderungen habe ich mit einer bewusst fehlerhaften Beispiel-Datei aus der beA- Weboberfläche entnommen:

![image](https://user-images.githubusercontent.com/37673969/161328418-d4f06be9-4de8-4250-825e-4b534c48bce7.png)

Diese weichen ggf. etwas von der Beschreibung der Kanzlei-Software-Schnittstelle ab, deren Anforderungen bereits eingehalten werden. Die DATEV war offenbar von 90 statt nur 84 Zeichen ausgegangen. 

Ein Kollege auf der mailing -Liste hatte am 1.4. Probleme mit dem beA, das aber wohl zudem am 1.4. als Aprilscherz ein problematisches Update erhalten hat (https://bea-abc.de/blog/es-ruckelt-beim-bea-neuigkeiten-zum-update-3-11/), die spärlichen release Informationen erklären dies nicht (https://portal.beasupport.de/release-information#c56). Für die Entwicklung ist es deshalb sicher noch schwieriger Tests durchzuführen. 

Die Dokumentation zum beA Web listet die Anforderungen aktuell so auf:
https://wiki.bea-brak.de/xwiki/bin/view/BRAK/%2300077

**Comment by librelegal** [comment]
bitte beim Testen die aktualisierte Version vom 1.4. nutzen, https://cloud.j-dimension.com/index.php/s/wscJLx3KDCKoEWm?path=%2FVorschau%2FClient
