### ISSUE TITLE
Optional verschlüsselbares Datenverzeichnis, damit die Dokumente nicht unverschlüsselt auf dem Rechner liegen.

### ISSUE THREAD

**Issue by nullproblemo** [jlawyerorg/j-lawyer-org#158]
Gefahrenlage: Abhandenkommen des Rechners (Notebooks), § 243 StGB Besonders schwerer Fall des Diebstahls, Durchsuchungsbeschluss der Staatsanwaltschaft ;)

**Comment by j-dimension** [comment]
Duplikat von #200
