### ISSUE TITLE
[BUG] E-Mail-Einstellungen und Problem bei Test-Email

### ISSUE THREAD

**Issue by socram70** [jlawyerorg/j-lawyer-org#1583]
**Describe the bug / Fehlerbeschreibung**
(todo: a description of the bug / eine Beschreibung des Fehlers)
Falsche Darstellung des E-Mail-Kontos

**To Reproduce / Schritte zum Nachvollziehen**

Eine Änderung der Einstellungen des E-Mail-Kontos, ohne ein neues Konto anzulegen, führt dazu, dass beim Klick auf E-Mail im Menü links nach wie vor die alte Adresse angezeigt wird. Der Versand erfolgt dennoch mit den geänderten Einstellungen und nach dem Neustart des Clients ist alles in Ordnung.

Ein weiterer Bug (1blu ist der Hoster) tritt beim Testen des E-Mail-Kontos auf (der Fehler mit Sender must contain a domain ist wohl selbsterklärend). Das beschränkt sich allerdings auf die Testmail und sonst funktioniert das Konto einwandfrei.

![grafik](https://user-images.githubusercontent.com/60073801/159039846-3aa1d4a8-4df4-480f-81c9-cc5a9dcae4ed.png)

**Expected behavior / Erwartetes Verhalten**
Die Testmail sollte funktionieren und die Änderung in der Darstellung vor dem Neustart wirksam werden.

**Environment / verwendete Umgebung:**
 - OS / Betriebssystem: Windows 10
 - j-lawyer.org Version: 2.0.1.0

**Comment by j-dimension** [comment]
> Eine Änderung der Einstellungen des E-Mail-Kontos, ohne ein neues Konto anzulegen, führt dazu, dass beim Klick auf E-Mail im Menü links nach wie vor die alte Adresse angezeigt wird.

Auch wenn im Posteingang der Aktualisieren-Knopf genutzt wird?

**Comment by j-dimension** [comment]
> Ein weiterer Bug (1blu ist der Hoster) tritt beim Testen des E-Mail-Kontos auf (der Fehler mit Sender must contain a domain ist wohl selbsterklärend). Das beschränkt sich allerdings auf die Testmail und sonst funktioniert das Konto einwandfrei.

Sehr wahrscheinlich behoben via #1504

**Comment by socram70** [comment]
Das habe ich gerade noch einmal gestetet, der Aktualisieren-Button führt zum Erfolg.
Den #1504 teste ich gerne sobald die Beta da ist und update das Ticket hier.

**Comment by j-dimension** [comment]
@socram70 ich schließe hier. Gern kommentieren, sollte das nochmal auftreten.
