### ISSUE TITLE
[BUG] Login: Verbindungswechsel löscht nicht Passwort

### ISSUE THREAD

**Issue by GuidoBo** [jlawyerorg/j-lawyer-org#1588]
Wechsel der Verbindung (dropdown oben) löscht einen bereits eingegebenen Name, aber nicht ein bereits eingegebenes Passwort. Sollte es aber

**Comment by j-dimension** [comment]
@GuidoBo der Name wird durch jenen des ausgewählten Profils ersetzt. Ist dort kein Nutzername gespeichert, wird der Nutzername geleert. 

Das Passwort ist nicht Teil des Profils, bleibt daher unverändert.

Die Usability ist hier wahrscheinlich nicht optimal. Die Profilverwaltung hat einen eigenen Tab, da ist nicht ganz offensichtlich dass der Nutzername dazu gehört. Den Nutzernamen auf den Profiltab verschieben möchte ich aber auch nicht.

**Comment by j-dimension** [comment]
Nutzername wird bei erfolgreichem Login nun automatisch im Profil gespeichert.
