### ISSUE TITLE
[FEATURE] [kalender] Sortierung der WV, Fristen und Termine in der Monatsansicht 

### ISSUE THREAD

**Issue by iradraconis** [jlawyerorg/j-lawyer-org#1589]
derzeitige Sortierung/Darstellung
WV, 
Fristen
Termine, 

oder WV,
Fristen
Termine
(uneinheitlich)

Wunsch: Termine, Fristen, WV

Zweck: die Monatansicht sollte die Verfügbarkeit des Sachbearbeiters auf einen Blick beantworten können. Das geht aktuell nicht, wenn viele WVen und Fristen die Darstellung der Termine verhindern

**Comment by j-dimension** [comment]
@Bentipa thanks again!
