### ISSUE TITLE
Aktennummer (unter Umständen editieren)

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-org#159]
Es soll nach der Änderungsliste zu 1.9.1 möglich sein Aktenzeichen zu ändern (in gewissen Grenzen). Ich finde diese Möglichkeit nicht im Programm. Wie geht das? Konkret möchte ich bei den angelegten Akten die Jahreszahl der Anlage korrigieren können, damit bei einer Akte aus 16 auch 16 und bei einer Akte aus 17 auch 17 steht. Wenn man diese Altakten in 18 ins Programm eingepflegt hat, kann man zwar über eine Trick die alte Aktennummerierung ins System bringen (indem man bei der von uns verwendeten Nummerierungsart 12345-JJ die Startnummer der Aktennummerierung verändert), aber nicht das Jahr.... Wir pflegen nach und nach die alten Akten ins System ein...

**Comment by j-dimension** [comment]
Da das eher nur im Ausnahmefall gemacht werden sollte, ist das nicht in die Oberfläche integriert, sondern wird über Einstellungen - Administratorkonsole aufgerufen. Bitte die Dokumentation konsultieren:
http://www.j-lawyer.org/downloads/documentation/j-lawyer.org-UserGuide-de.html#__RefHeading___Toc3502_2028972031

Es werden bspw. keine Dokumente angepasst, d.h. dort hat man dann noch das alte Aktenzeichen drin.

**Comment by Mucki526** [comment]
Danke!
