### ISSUE TITLE
[BUG] [Feature] [kalender] Eintrag Termin in Monatsansicht Zeiten krumm => ggfs. Mouseover für Zeit unter dem Cursor?

### ISSUE THREAD

**Issue by iradraconis** [jlawyerorg/j-lawyer-org#1590]
erwartetes Verhalten ist: halbstündige Anlage, d.h. zu :00 oder :30 
hier: Macbook pro 16 Zoll, Retina Display. Aber auch mit externem Display Widescreen beobachtet 

Vielleicht könnte es ja auch bei dem Verhalten bleiben und zur Hilfe/Unterstützung wird ein Mouseover eingeblendet, mit der Zeit unter dem Mauszeiger. Das das wäre der Königsweg! Denn so können minutengenaue Termine angelegt werden, ohne dies manuell eingeben zu müssen.

**Comment by j-dimension** [comment]
@Bentipa aufwandstechnisch sollte das sehr überschaubar sein, aber man bekommt das wahrscheinlich nur mit Auflösungen horizontal > 2500 überhaupt reproduziert.

**Comment by j-dimension** [comment]
Herzlichen Dank für den PR, @Bentipa !
