### ISSUE TITLE
[FEATURE] Benachrichtigungen per Signal Messenger

### ISSUE THREAD

**Issue by GuidoBo** [jlawyerorg/j-lawyer-org#1598]
… statt nur SMS oder Email oder Post. 

Es gibt für Signal eine API. 
https://signal.org/docs/

Es müsste auch funktionieren, dass Mediendateien (PDFs) verschickt werden.

In den Personendaten müsste dann vermerkt sein, welcher Kontaktweg bevorzugt wird.

Mal Hand aufs Herz: datenschutzrechtlich ist alles andere (ausgenommen Papier) doch schon lange "angezählt".

Evtl. (zusätzlich) auch Vergleichbares für Telegram und WhatsApp. 😫

**Comment by librelegal** [comment]
ich wäre sehr für Signal - und nicht für die anderen

**Comment by GuidoBo** [comment]
oh, ich eigentlich auch, aber: was wollen wir wirklich: das Mandantierende unsere Nachrichten Ende-zu-Ende-Verschlüsselt bekommen, oder? Und gegenüber E-Mail ist das doch alles ein Fortschritt, oder?

**Comment by j-dimension** [comment]
Duplikat des antiken Tickets #89

**Comment by GuidoBo** [comment]
Ich habe in der Dokumentation nichts dazu gefunden. Kannst Du kurz was zu der Implementierung sagen?

**Comment by j-dimension** [comment]
@GuidoBo ich habe das Ticket als Duplikat geschlossen. Das vorhandene Ticket #89 ist noch offen und unbearbeitet.
