### ISSUE TITLE
Neuer Handaktenbogen - Fehler

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-org#160]
Kleiner Fehler im neuen Handaktenbogen bei Wiedervorlagen und Fristen ist der Strich in der Mitte unterbrochen und kräftig (1 cm) verschoben (1 Wiedervorlage eingetragen).

**Comment by j-dimension** [comment]
Das kann ich so nicht reproduzieren. Besteht die Möglichkeit, ein Beispiel per Email zu bekommen?

**Comment by Mucki526** [comment]
Du hast e-mail mit Anlage....

**Comment by j-dimension** [comment]
Notiz: Email Mucki526 vom 09.11.2018
