### ISSUE TITLE
[BUG] [e-mail] E-Mail-Subsystem reagiert sehr träge, einzelne Nachrichten werden nicht dargestellt

### ISSUE THREAD

**Issue by Fn0rdmann** [jlawyerorg/j-lawyer-org#1600]
Das E-Mail-Subsystem ist hier unter jl 2.1.0 RC sehr zäh. Beim ersten Aufruf nach Update-Installation des M1-Clients dauert es mehrere Sekunden, bis der Client wieder auf Mausklicks reagiert. Anzeige eines Newsletters der RAK Hamm führt zur Fehlermeldung:

javax.mail.util.SharedByteArrayInputStream@27d91560
oder
Fehler beim Laden der Nachricht: G71 BAD Error in IMAP command FETCH: Invalid messageset (0.000 + 0.000 secs).

Unter Linux Mint taucht nur die erste Fehlermeldung auf, die Reaktionszeit ist deutlich schneller. Im externen E-Mail-Programm lässt sich die Nachricht ohne weiteres darstellen.

Serverversion: 2.1.0.12 (Linux)
Clientversion: 2.1.0.0 (M1 unter MacOS 12.3) und 2.1.0.0 (unter Linux Mint 20.3)

**Comment by j-dimension** [comment]
@Fn0rdmann es gibt ein Problem in einer externen Bibliothek. Kannst Du mal testweise die Ordner des Postfaches "zuklappen" und den Client neustarten? Geht es dann schneller?

**Comment by Fn0rdmann** [comment]
Ja, in der Tat. Auf dem Client, an dem ich gerade sitze, geht es jetzt (wieder) schneller. Die Fehlermeldung bleibt aber bestehen, allerdings nur bei Nachrichten der RAK Hamm. Die übrigen Mails werden dargestellt.

**Comment by j-dimension** [comment]
@Fn0rdmann kann ich dazu noch ein client.log bekommen, oder - falls nicht vertraulich - die E-Mail der RAK Hamm (nicht als Weiterleitung, sondern die .eml-Datei)?

**Comment by j-dimension** [comment]
@Fn0rdmann danke, haben den Fehler gefunden und korrigiert.
