### ISSUE TITLE
[BUG] Recherche mit U&G wirft Java-Fehler

### ISSUE THREAD

**Issue by Fn0rdmann** [jlawyerorg/j-lawyer-org#1601]
Eine Suche unter Recherche / U&G führt zur Fehlermeldung

    Fehler bei der Suche: java.ws.rs.ProcessingException: Error loading key store
    from file "ks.jpg".

Serverversion: 2.1.0.12
Clientversion: 2.1.0.0

**Comment by librelegal** [comment]
Mit debian 11 bullseye KDE, funktioniert das ohne Fehler, gleiche Version, Stand 2.4.

**Comment by librelegal** [comment]
Welches Betriebsystem usw. nutzt Du?

**Comment by Fn0rdmann** [comment]
Server ist Ubuntu 18.04.6 LTS (virtualisiert unter Proxmox VE 7.1)
Client 1 getestet unter Mac OS 12.3 und 12.3.1
Client 2 getestet unter Linux Mint 20.3

**Comment by j-dimension** [comment]
@Fn0rdmann tritt der gleiche Fehler unter Linux auf?
Ist der Client unter Linux als root oder als Nutzer installiert?

**Comment by Fn0rdmann** [comment]
Ja, der Fehler tritt auch unter Linux auf. Der Client ist jeweils in der jüngsten RC-Version auf verschiedenen Rechnern jeweils als Nutzer installiert. Alle Linux Clients laufen unter Linux Mint 20.3.

**Comment by j-dimension** [comment]
Dann bitte mal eine U&G-Suche ausführen und anschließend das Client.log per Mail schicken. Danke!

**Comment by PBaumfalk** [comment]
Müssen wir wirklich viel Zeit auf U&G verwenden? Das letzte BGH-Urteil wurde 2019 eingepflegt…


Mit freundlichen Grüßen / Kindly Regards

Patrick Baumfalk
Rechtsanwalt / Lawyer


E-Mail:   ***@***.***


Baumfalk - Rechtsanwaltskanzlei
Hauptstr. 195
50169 Kerpen

Tel.: +49 2273 40 68 504
Fax: +49 2273 59 03 565

E-Mail: ***@***.***
Web: www.kanzlei-baumfalk.de

Sent by Mobile

**Comment by iradraconis** [comment]
Ich meine auch, dass das tot ist…

**Comment by j-dimension** [comment]
Kennt jemand eine Alternative mit einer API?

**Comment by PBaumfalk** [comment]
Hier ist die JAVA API:
https://github.com/openlegaldata/oldp-sdk-java

Mit freundlichen Grüßen / Kindly Regards

Patrick Baumfalk
Rechtsanwalt / Lawyer


Mobil:    +49 1525 53 04 194
E-Mail:   ***@***.***


Baumfalk - Rechtsanwaltskanzlei
Hauptstr. 195
50169 Kerpen

Tel.: +49 2273 40 68 504
Fax: +49 2273 59 03 565

E-Mail: ***@***.***
Web: www.kanzlei-baumfalk.de

Sent by Mobile

**Comment by PBaumfalk** [comment]
https://de.openlegaldata.io/

2022 und sogar 2027 und 2029

Mit freundlichen Grüßen / Kindly Regards

Patrick Baumfalk
Rechtsanwalt / Lawyer


Mobil:    +49 1525 53 04 194
E-Mail:   ***@***.***


Baumfalk - Rechtsanwaltskanzlei
Hauptstr. 195
50169 Kerpen

Tel.: +49 2273 40 68 504
Fax: +49 2273 59 03 565

E-Mail: ***@***.***
Web: www.kanzlei-baumfalk.de

Sent by Mobile

**Comment by Dickmaulruessler** [comment]
Ich habe U&G noch nie genutzt. Eine solche Datenbank muss nach meinem Dafürhalten auch nicht Teil einer Kanzleisoftware sein.

Eine solche Datenbank ist aus meiner Sicht nur sinnvoll, wenn sie SEHR gut gepflegt wird: Unfangreich und aktuell. Und auch das genügt noch nicht: Es muss auch das Rechtsgebiet des Nutzers gut abdecken.

**Comment by PBaumfalk** [comment]
Ersatzlos streichen?

Mit freundlichen Grüßen / Kindly Regards

Patrick Baumfalk
Rechtsanwalt / Lawyer

E-Mail:   ***@***.***

BAUMFALK - Rechtsanwaltskanzlei

Hauptkanzlei:
Hauptstr. 195
50169 Kerpen

Zweigstelle:
Berliner Str. 4
58452 Witten

Postanschrift:
Postfach 1233
50141 Kerpen

Tel.: +49 2273 40 68 504
Fax: +49 2273 59 03 565

E-Mail: ***@***.***
Web: www.kanzlei-baumfalk.de

**Comment by j-dimension** [comment]
@Fn0rdmann ich habe das in den vergangenen Tagen bei jeweils bei Anwendern getestet, wo ein ein Update installiert habe, und konnte es nicht reproduzieren. ist es okay für Dich, wenn ich hier erstmal schließe?

Wenn Du die Funktionalität benötigst, würde ich gern per Fernwartung draufschauen.

**Comment by Mucki526** [comment]
Ich nutze U&G selten, habe aber das gleiche Problem. Geht nicht mehr... nutzen alternativ regelmäßig Openjur..
![grafik](https://user-images.githubusercontent.com/37142896/164643189-4b6bcdeb-7330-4f66-b4df-60c84f803326.png)

**Comment by j-dimension** [comment]
Ich schließe das hier und werde #250 weiter verfolgen.
