### ISSUE TITLE
[FEATURE] zufälligen Desktop-Hintergrund ohne Neustart des Clients 

### ISSUE THREAD

**Issue by iradraconis** [jlawyerorg/j-lawyer-org#1602]
Aktuell wird bei jedem Neustart des Clients ein anderes Wallpaper gewählt. Es wäre schön, wenn "zur Laufzeit" der ein anderes Wallpaper, meinetwegen auch zufällig, gewählt werden könnte. 

(Ich habe ein Python Skript geschrieben, was eigene Wallpaper aus einem selbstgewählten Ordner in den Client integriert. Kann ich gern zur Verfügung stellen, sofern jemand Bedarf hat)

**Comment by j-dimension** [comment]
Ich muss nachfragen: geht es darum den notwendigen Neustart zu eliminieren, wenn man das Feature aktiviert, oder geht es um eine automatische Änderung des Hintergrundes in Intervallen?

**Comment by iradraconis** [comment]
Darum, den Neustart zu vermeiden.

**Comment by j-dimension** [comment]
Ich mache das hier zu, wenn Ihr erlaubt. Die Priorität erscheint mir gering.
