### ISSUE TITLE
Gravityforms/Falldatenblatt Erweiterung Adressübername in Jlawyer Datenbank

### ISSUE THREAD

**Issue by SaschaKarcher01** [jlawyerorg/j-lawyer-org#1606]
Im Falldatenblatt von Gravityforms sollte noch die Möglichkeit gegeben werden, dass
die Adressdaten des Neumandanten per klick in die die Adressdatenbank von Jlawyer übertragen werden.

Zur Umsetzung könnten hierfür etwa die in Gravityforms angebenenen "erweiterten Felder" Name, Anschrift ,Email,Telefon verwendet werden, oder falls es einfacher ist, Admin Feld Etiketten vorgegeben werden, bei welchem dann das Falldatenblatt diese erkennt und in das Adressbuch von J-lawyer bzw. die angebundene mysql schreibt.

**Comment by GuidoBo** [comment]
Ist es eine gute Idee, wenn eine Wordpressisnstallation schreibend auf die JL-Datenbank zugreift?

**Comment by j-dimension** [comment]
> Ist es eine gute Idee, wenn eine Wordpressisnstallation schreibend auf die JL-Datenbank zugreift?

Das ist nicht der Fall und würde aus Sicherheitsgründen auch nicht meine Zustimmung finden. Bitte mal den Vortrag am kommenden Montag anschauen, da erkläre ich die Funktionsweise.

**Comment by librelegal** [comment]
Jens meint diese Veranstaltung: https://www.j-lawyer.org/?p=4887

**Comment by j-dimension** [comment]
Ist jetzt verfügbar. Das Falldatenblatt versucht die Felder intelligent zu erkennen, und optional können für die Admin-Feld-Etiketten die Standard-Platzhalternamen verwendet werden - diese werden ebenfalls ausgewertet.

**Comment by librelegal** [comment]
> > Ist es eine gute Idee, wenn eine Wordpressisnstallation schreibend auf die JL-Datenbank zugreift?
> 
> Das ist nicht der Fall und würde aus Sicherheitsgründen auch nicht meine Zustimmung finden. Bitte mal den Vortrag am kommenden Montag anschauen, da erkläre ich die Funktionsweise.

Prima, dass der issue geschlossen werden konnte. Wenn also kein schreibender Zugriff von extern stattfindet, wie kommt die Adresse dann in den Gesamtbestand rein? Ist eine derart imporierte Adresse als eine solche erkennbar / sinnvoll? Eine Bestätigung je Adresse scheint mir sinnvoll

**Comment by j-dimension** [comment]
Der Import wird im Client angestoßen, die Daten werden also aus Wordpress "abgeholt" und nicht von Wordpress gepusht.
