### ISSUE TITLE
[BUG] [beA] eingehende Nachricht - Betreff Sonderzeichen kapuut

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#1608]
gerade mit der neuen Version getestet, aktuelle Nachricht vom Gericht sieht im Betreff so aus, das ß ist kaputt:

![image](https://user-images.githubusercontent.com/29924198/162590153-add2ce4a-bfed-48c1-8c01-1906e7befd4b.png)

**Comment by stm9x9** [comment]
in der Liste ist das ß aber korrekt:

![image](https://user-images.githubusercontent.com/29924198/162590258-dfe13b05-9211-464f-ade1-d295c64c6a14.png)

**Comment by j-dimension** [comment]
Duplikat von #1003

**Comment by stm9x9** [comment]
> Duplikat von #1003

ja? Soweit ich mein Ticket noch nachvollziehen kann, ging es da um das Abspeichern?

> Aus sauber in beA (in j-l) dargestellten Umlauten im Betreff und den Dateinamen werden "Sonderzeichen"

hier ist es bereits im beA-Eingang. Was beim Speichern aktuell passiert, müßte ich erstmal prüfen.
