### ISSUE TITLE
[FEATURE] Mehr Bedienkomfort beim Scan-Workflow (Buttons und Kontextmenü)

### ISSUE THREAD

**Issue by Dickmaulruessler** [jlawyerorg/j-lawyer-org#1613]
Ich würde mir mehr Bedienkomfort bei der Ablage von gescannten Dokumenten wünschen. 
Ich finde, dass das eine ganz schöne Frimelei ist mit diesen beiden schmalen Zeilen:
![jklföjdsjlkfösadsflöjkdsföasdfdsfdsf](https://user-images.githubusercontent.com/46451749/163009466-51f1bb81-07b7-4c73-bfb7-5d4c5e78e60c.jpg)

Ich würde es begrüßen, wenn es direkt im ganz **oberen (!)** Fenster folgende Möglichkeiten gäbe:

- **Kontextmenü** (das würde ich am liebsten nutzen)
- ganz oben oder oben rechts: Etwas **größere** **Buttons**, ohne das man (wie jetzt) dabei in Sorge sein muss, schon gleich eine Akte anzuklicken oder - noch viel schlimmer - das Scandokument aus Versehen zu löschen. 

und dies für die Befehle:

- **Akte suchen**
- **umbenennen** (das sollte schon hier möglich sein und nicht nur im darauffolgenden Schritt der Aktenablage. Ich würde die Umbennung gerne als aller erstes erledigen, zum einen weil ich nur in dieser ersten Ansicht durch alle Seiten des Dokuments klicken kann und um über eine Priorisierung - welchen Scaneingang bearbeite ich zuerst? - entscheiden zu können)
- **löschen**
- (ob die Etikettenvergabe auch in das Kontextmenü sollte weiß ich nicht. Wenn es kein wesentlich größerer Aufwand wäre, würde aber auch das wohl Sinn machen. Andernfalls könnte man darauf evtl. verzichten). 

---------------------------------- @j-dimension 2022-07-11 ------------------------------

- [x] Layout: Standard-Seitenleiste analog beA / E-Mail: 1,5h
- [x] Aktionslogiken (zuweisen, suchen & zuweisen, löschen) separat bereitstellen, damit sie von mehreren Stellen gerufen werden können (aus Seitenleiste und Kontextmenü): 1h
- [x] neue Aktion: umbenennen - neue Serverfunktionalität implementieren: 0,5h
- [x] neue Aktion: umbenennen - neuen Service in Client einbauen: 0,5h
- [x] Kontextmenü mit allen Aktionen der Seitenleiste: 0,75h

**Comment by j-dimension** [comment]
@Dickmaulruessler was hältst Du davon wenn der Scaneingang analog der anderen Posteingänge mit einer Seitenleiste rechts versehen wird? Das Kontextmenü könnte es zusätzlich geben, ist bei den anderen ja auch da.

**Comment by Dickmaulruessler** [comment]
> wenn der Scaneingang analog der anderen Posteingänge mit einer Seitenleiste rechts versehen wird? 

Nett, dass du fragst, aber das wirst du - wie immer - schon gut machen!

Nur rein informatorisch möchte ich nur auf eine besonders schöne Eigenschaft des derzeitigen Scaneingangs hinweisen: Das Vorschaufenster rechts, welches ja das DINA4-Seitenverhältnis verlangt, wird derzeitig nicht durch weitere Fensterbereiche zwangsweise verkleinert. Man kann die Dokumente (jedenfalls bei meiner Bildschirmgröße und Auflösung) in der Vorschau also immer direkt lesen (anders als z.b. in der Akte im Reiter "Dokumente") Das finde ich gerade im Scaneingang, wo man die Tagespost sichtet, besonders wertvoll und es wäre schön, wenn der Vorschaubereich durch die neuen Buttons nicht wesentlich verkleinert wird (bei mir persönlich würde das sicherlich stets passen, aber bei anderen Bildschirmauflösungen könnte es evtl. eng werden, wenn rechts noch etwas hinkäme). 

![djsklsfödsjklöflasjdsfasfdsdfff](https://user-images.githubusercontent.com/46451749/178250296-45febeb8-7535-4b4f-85e4-25ddbdc95197.jpg)


Evtl. könnten die Buttons auch oben hin...

![dlöjfaklösdf](https://user-images.githubusercontent.com/46451749/178248920-21cb0cb6-15a4-4259-a69f-1a3b8e7d4da1.jpg)
.
.
.
.
> Das Kontextmenü könnte es zusätzlich geben, ist bei den anderen ja auch da.

Ja, das werde ich sicherlich am meisten nutzen und freue mich besonders auf dieses neue Feature!

**Comment by j-dimension** [comment]
Alles noch im Fluss, aber hier mal eine Vorschau:

- Optionen bzgl. der Etiketten und des Löschens sind in den Kopfbereich gerutscht - so ist es konsistent mit den anderen Posteingängen
- die Standard-Seitenleiste ist hinzugefügt. Ich hatte die erst wie sonst auch ganz rechts, bei großen Bildschirmen bedeutet das aber recht lange Mauswege, da man immer zwischen der Tabelle links und der Seitenleiste rechts wechseln muss - also einmal über den ganzen Bildschirm. Alternative wäre, auch die Tabelle noch nach rechts zu schieben. **Was meint Ihr?**
- Tabelle mit den Aktionen entfällt
- Kontextmenü (hier nicht sichtbar)

![grafik](https://user-images.githubusercontent.com/3729754/182045865-46dddfbc-4fd0-4ed2-9690-2a80b18224f4.png)

**Comment by Dickmaulruessler** [comment]
Ich finde es so wunderbar! 
Und ja, die Aktenzuordnungs-Seitenleiste wäre wegen der langen Mauswege ganz rechts in der Tat blöd. 

Für mich würde das so sehr gut passen! 
Falls andere aber einen kleinen Bildschirm haben oder die Scandocumente lange Dateinamen aufweisen oder die Aktenbezeichnung länger ist: Kann mann die Fenster manuell nach links und rechts schieben? Und bleibt die Fensterposition gespeichert?

**Comment by j-dimension** [comment]
> Kann mann die Fenster manuell nach links und rechts schieben? Und bleibt die Fensterposition gespeichert?

Ja und ja :-)

**Comment by stm9x9** [comment]
> Nur rein informatorisch möchte ich nur auf eine besonders schöne Eigenschaft des derzeitigen Scaneingangs hinweisen: Das Vorschaufenster rechts, welches ja das DINA4-Seitenverhältnis verlangt, wird derzeitig nicht durch weitere Fensterbereiche zwangsweise verkleinert

Das möchte ich auch gerne unterstreichen! So in den Dokumenten würde sehr helfen!

**Comment by j-dimension** [comment]
Video vom überarbeiteten Scaneingang:

https://user-images.githubusercontent.com/3729754/191363221-a1eb5ef5-d214-40be-8552-bac0c5b9a94c.mp4

**Comment by Dickmaulruessler** [comment]
Wunderbar! Vielen Dank!

Was wenn man im Kontaktemenü aus Versehen "aus dem Scaneingang löschen" klickt... Kann man es einfach wiederherstellen?

**Comment by j-dimension** [comment]
Ich könnte eine Sicherheitsabfrage einbauen.

**Comment by Dickmaulruessler** [comment]
> Sicherheitsabfrage

Ja, (auch wenn mich Sicherheitsabfragen in anderen Fällen manchmal nerven) hier erscheint mir das nicht nur sinnvoll, sondern wirklich unbedingt erforderlich.

Merci!
