### ISSUE TITLE
[BUG] Akte - Dokumentenordner-Panel mit Scrollbalken unten

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#1614]
ist mir jetzt erstmals mit der neuen 2.1.0.0 aufgefallen:

![image](https://user-images.githubusercontent.com/29924198/163053460-06cc41f3-2257-4400-944f-83013889fbe3.png)

Das linke Panel hat jetzt immer einen Scrollbalken unten und läßt sich auch nicht zu passender Größe aufziehen.

**Comment by j-dimension** [comment]
@stm9x9 ist das aktuell noch ein Thema?
