### ISSUE TITLE
[BUG] [e-mail] Schrift ganz komisch

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#1615]
![image](https://user-images.githubusercontent.com/29924198/163054949-de65ae3a-7030-4dfc-bc73-53ec4409357e.png)

Seit der 2.1.0.0 sieht die Schrift im Haupttext einer gespeicherten Mail (aber nur der, nicht die Schrift oben oder unten bei den Anhängen) wie "Geisterschrift" aus.

**Comment by j-dimension** [comment]
Was ist denn eine Geisterschrift?

Die Mails werden jetzt über einen eingebetteten Browser dargestellt, um die teils fehlerhafte HTML-Darstellung zu fixen. Das oben sieht mir wie eine reine Textmail aus, und die Schrift scheint eine Art Standarschrift des Betriebssystems zu sein.

**Comment by stm9x9** [comment]
naja halt so ghosty :-) Also etwas durchscheinend, bleich, verschwommen, unscharf ... 

![image](https://user-images.githubusercontent.com/29924198/163277646-0a647cff-85cf-4c63-aad7-44053be71fd0.png)

halt ganz anders als die klaren, schwarzen, kräftigen, kontrastreichen Buchstaben oben ( CC, BCC) oder unten "Anhänge". Oder anders formuliert: einfach schlecht lesbar

**Comment by j-dimension** [comment]
Ist das auch auf anderen Arbeitsplätzen so? Ich hab das so noch nicht gesehen.

**Comment by j-dimension** [comment]
Irgendjemand anderes der das beobachtet hat?

**Comment by stm9x9** [comment]
> Ist das auch auf anderen Arbeitsplätzen so? Ich hab das so noch nicht gesehen.

(leider) bislang nicht
