### ISSUE TITLE
[FEATURE] Falldatenblatt/Skript: Funktion, die prüft, ob Platzhalter vorhanden (oder: Funktion, die Fehler unterdrücken) 

### ISSUE THREAD

**Issue by GuidoBo** [jlawyerorg/j-lawyer-org#1618]
Eine Funktion, die prüft, ob ein Platzhalter definiert wurde bzw. existiert (Falldatenblatt)
WENNUNDEFINIERT(Platzhalter, "dann...","sonst...")

Alternativ:
Funktion die Fehlermeldungen unterdrückt
[[SCRIPT:SILENT(Hier stehen die Funktionen, deren Fehler unterdrückt werden.)]]

Grund:
Falldatenblätter: wird versucht auf einen nicht-existieren Platzhalter zugegriffen, liefert JL einen unschöne Fehler zurück. Das ist eigentlich richtig, sollte sich aber umgehen lassen in Fällen, sich nicht ex ante sagen lässt, ob das Falldatenblatt einen Wert enthalten wird/existiert.

**Comment by j-dimension** [comment]
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<html>
<head>
	
	<title></title>
	<meta name="generator" content="LibreOffice 6.4.7.2 (Linux)"/>
	<style type="text/css">
		@page { size: 21cm 29.7cm; margin: 2cm }
		td p { background: transparent }
		td p.western { font-family: "Liberation Sans", sans-serif }
		td p.cjk { font-size: 10pt }
		p { margin-bottom: 0.21cm; background: transparent; page-break-before: auto }
		p.western { font-family: "Liberation Sans", sans-serif; so-language: de-DE }
		p.cjk { font-size: 10pt }
		a:visited { color: #800000; so-language: zxx; text-decoration: underline }
		a:link { color: #000080; so-language: zxx; text-decoration: underline }
	</style>
</head>
<body lang="en-GB" link="#000080" vlink="#800000" dir="ltr"><p class="western" align="justify" style="margin-bottom: 0.5cm">
<font face="Verdana, sans-serif"><span lang="de-DE"><b>Text: </b></span></font><font face="Verdana, sans-serif"><span lang="de-DE"><b>F</b></span></font><font face="Verdana, sans-serif"><span lang="de-DE"><b>unktion
</b></span></font><font face="Verdana, sans-serif"><span lang="de-DE"><b>WENNFALLDATEN</b></span></font></p>
<p class="western" align="justify" style="margin-bottom: 0.5cm; page-break-before: auto"><a name="__DdeLink__13635_2761556120"></a>
<font face="Verdana, sans-serif"><span lang="de-DE"><span style="font-weight: normal">Gibt
einen Text aus, wenn ein </span></span></font><font face="Verdana, sans-serif"><span lang="de-DE"><span style="font-weight: normal">Falldatenblatt
in der betroffenen Akte vorhanden </span></span></font><font face="Verdana, sans-serif"><span lang="de-DE"><span style="font-weight: normal">ist,
oder optional einen anderen Wert, wenn d</span></span></font><font face="Verdana, sans-serif"><span lang="de-DE"><span style="font-weight: normal">as</span></span></font><font face="Verdana, sans-serif"><span lang="de-DE"><span style="font-weight: normal">
</span></span></font><font face="Verdana, sans-serif"><span lang="de-DE"><span style="font-weight: normal">Falldatenblatt</span></span></font><font face="Verdana, sans-serif"><span lang="de-DE"><span style="font-weight: normal">
nicht </span></span></font><font face="Verdana, sans-serif"><span lang="de-DE"><span style="font-weight: normal">existiert</span></span></font><font face="Verdana, sans-serif"><span lang="de-DE"><span style="font-weight: normal">.</span></span></font></p>


Signatur | WENNFALLDATEN(Präfix, 			WennVorhanden) 			 			WENNFALLDATEN(Präfix, 			WennVorhanden, 			WennNichtVorhanden)
-- | --
Parameter: Präfix | Platzhalterpräfix 			des Falldatenblattes. | FAMR
Parameter:  			   WennVorhanden | Text, 			welcher ausgegeben wird wenn ein 			Falldatenblatt mit diesem Präfix in der Akte vorhanden ist. |  
Parameter:  			   			WennNichtVorhanden | Optional. 			Text, 			welcher ausgegeben wird wenn das 			Falldatenblatt nicht vorhanden 			ist. |  
Rückgabewert: | Der 			Wert von WennVorhanden 			oder WennNichtVorhanden 			als Text. |  


<p lang="de-DE" class="western" align="justify" style="margin-bottom: 0.5cm; page-break-before: auto">
<br/>
<br/>

</p>
<p lang="de-DE" class="western" align="justify" style="margin-bottom: 0.5cm; page-break-before: auto">
<font face="Verdana, sans-serif"><b>Hinweis: Im Gegensatz zu den
anderen Funktionsaufrufen wird der Präfix-Parameter hier in
Hochkommata angegeben.</b></font></p>
<p lang="de-DE" class="western" align="justify" style="margin-bottom: 0.5cm; page-break-before: auto">
<font face="Verdana, sans-serif">Beispiel</font></p>
<p lang="de-DE" class="western" align="justify" style="margin-bottom: 0.5cm; page-break-before: auto">
<font face="Verdana, sans-serif"><font size="2" style="font-size: 9pt">[[SCRIPT:WENNFALLDATEN(&quot;UKBEA&quot;,
&quot;Falldaten UKBEA vorhanden&quot;, &quot;Falldaten UKBEA nicht
vorhanden&quot;);]]</font></font></p>
</body>
</html>
