### ISSUE TITLE
Editieren von Tags

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-org#162]
Es wäre sinnvoll, wenn man die Tags editieren könnte, nicht nur löschen. Wenn man sie löscht verschwinden sie ja vermutlich aus den Akten, wo sie gesetzt sind. Es könnte sich bei einer Änderung aber einfach der geänderte Tag in allen Akten ändern....

**Comment by j-dimension** [comment]
Ist umgesetzt.
