### ISSUE TITLE
[FEATURE] Aktentyp, Aktendeckelfarbe, Ablageort/Archiv

### ISSUE THREAD

**Issue by LazyGuy21No** [jlawyerorg/j-lawyer-org#1621]
Für eine Akte sollte ein Ablageort und "Metadaten" der Akte hinterlegt werden können.

Farbe: Orange
Aktenart: Papier führt/Digital führt/eAkte
Archiviert: ja/nein/für Archivierung markiert
Örtlichkeit: Büro Musterstadt 
Umfassung: Schrank A
Fach/Abteilung: Kiste 4

Dafür könnte der Reiter "Handakte" (den ich nie wirklich verstanden habe) entfallen oder das Notiz-Feld unter allgemeine Daten könnte horizontal halbiert  werden.

**Comment by j-dimension** [comment]
Duplikat von #44

**Comment by stm9x9** [comment]
mit dem Duplikat bin ich mir nicht so sicher. #44 scheint sich mir auf den Zeitpunkt nach Archivierung zu beziehen. Das hier aber möchte Infos zur "lebenden" Akte in jl hinterlegen.

**Comment by j-dimension** [comment]
> mit dem Duplikat bin ich mir nicht so sicher. #44 scheint sich mir auf den Zeitpunkt nach Archivierung zu beziehen. Das hier aber möchte Infos zur "lebenden" Akte in jl hinterlegen.

Ablageort / Archiv ist im verlinkten Ticket enthalten. 

Aktenart: sehe hier keinen breiten Bedarf, der über einen Vermerk im Notizfeld hinausgeht

Örtlichkeit: wäre das nicht über Gruppen / Dezernate lösbar? Dann könnte man es gar im Aktenzeichen reflektieren.

Farbe: mir ist nicht klar was hier genau gewünscht ist. Ggf. kann @LazyGuy21No hierzu ein separates Ticket machen und das gewünschte Verhalten genauer beschreiben.

**Comment by stm9x9** [comment]
Das mit der Farbe kapiere ich auch nicht so ganz, vielleicht sind bei dem Kollegen die Ordner mit Farben markiert?

> Aktenart: sehe hier keinen breiten Bedarf, der über einen Vermerk im Notizfeld hinausgeht

Letztlich kann man alles im Notizfeld vemerken :-D Aber wenn es hier keinen breiten Bedarf für gibt, dann böte sich auch "Eigenes Feld xxx" an.
 
> Örtlichkeit: wäre das nicht über Gruppen / Dezernate lösbar? Dann könnte man es gar im Aktenzeichen reflektieren.

Bei einer führenden eAkte kann ich mir vorstellen, daß es da nicht unbedingt eine Korrelation geben muß. Und wenn man Akten mal rumräumt, müßte man Aktenzeichen ändern.

und 

Umfassung: Schrank A
Fach/Abteilung: Kiste 4
wäre wohl auf jeden Fall ein Überfrachten des Akz-Systems.

Ob es aber sowas allgemein braucht, weiß ich nicht. Vielleicht wenn man eine größere Kanzlei hat als ich ...?

Auch hier die Frage an @LazyGuy21No: Über die Variablen Eigenes Feld lösbar?

**Comment by LazyGuy21No** [comment]
Es geht darum, dass körperliche Akten schwerer zu finden sind als Akten im Rechner.

"Farbe" soll beim Finden der Papier-Akte helfen. Viele Büros verwenden eine Farbcodierung für die Sachgebiete. Zum Beispiel: Rot für Strafrecht, Blau für Zivilrecht, Grün für Verkehrsrecht. Die Farbe der Papierakte sollte sich in der Virtuelle. Repräsentanz widerspiegeln. Also sollte die Farbe (zB) Orange in der Aktenansicht auftauchen.

Die Daten zum Ablageort können sowohl Abgelegte als auch lebende Akten betreffen. Wenn ich zB sehe, dass die Akte in einem anderen Standort ist, brauche ich nicht hier suchen, sondern rufe an. Ich hatte Gruppe immer personell aufgefasst, nicht örtlich. 

Umfassung und Ort betreffen insbesondere die Ablage. Wir legen zB nach Schränken und Kisten ab. Das heißt: die Akte kommt in einen Umschlag, der Umschlag bekommt den Ablagezettel auf die Front geklebt und landet in einer Kiste/Fach (2022-4) in Schrank B. Damit beschränkt sich die Suche auf wenige Akten, die gemeinsam in dieser Kiste liegen. 

Das wäre aber wirklich auch über die Notiz machbar
