### ISSUE TITLE
[FEATURE] Aktenhistorie: Mitarbeiter-Report

### ISSUE THREAD

**Issue by j-dimension** [jlawyerorg/j-lawyer-org#1625]
Aktenübergreifend einen Report bereitstellen:
- für bestimmte MAin 
- für gewählten Zeitraum
- ohne exakte Angabe von Zeiten (da arbeitsrechtlich u.U. bedenklich), aber gruppiert nach Kalendertagen

**Comment by j-dimension** [comment]
@vaelv wäre hier vielleicht gar die vorhandene Aktenhistorie (unter "Recherche") ausreichend, wenn man dort ein Filter-Dropdown mit den Mitarbeitern hätte?

**Comment by vaelv** [comment]
> @vaelv wäre hier vielleicht gar die vorhandene Aktenhistorie (unter "Recherche") ausreichend, wenn man dort ein Filter-Dropdown mit den Mitarbeitern hätte?

Ideal wäre schon ein grober aktenübergreifender Überblick. Aber ein Filter in der Historie wäre natürlich besser als nichts... Android hat Priorität 🙂

**Comment by j-dimension** [comment]
![grafik](https://user-images.githubusercontent.com/3729754/215225804-7275f5a9-9a90-4f96-b994-73a1076ae9d5.png)
