### ISSUE TITLE
Sortierung im Scanordner

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-org#163]
Wenn ein scan in den Scanordner erfolgt und ein Refresh ausgelöst wird, um ihn zu sehen (könnte eigentlich immer automatisch beim Öffnen des Ordners erfolgen), dann wird der neue scan ganz nach unten sortiert. Wenn im Scanordner viele Dokumente sind, ist er dann unter dem unteren Rand und man muss erst umsortieren, bzw. scrollen. Sinnvoller wäre m.E. dass das die neue Datei oben liegt... Aber die Sortierung kann man nicht vorwählen...

**Comment by j-dimension** [comment]
neue Standardsortierung: nach Änderungsdatum absteigend
