### ISSUE TITLE
[BUG] jl startet immer verkleinert

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#1631]
Egal ob ich beim Beenden von jl im Vollbild war oder das Fenster auch ganz klein habe, beim nächsten Start sieht jl immer so aus: nicht im Vollbild und rechts ne Menge Platz frei.

![image](https://user-images.githubusercontent.com/29924198/166157568-f218eee1-7a0a-484e-9cc2-21132c48e9a7.png)

**Comment by j-dimension** [comment]
Duplikat von #1480
