### ISSUE TITLE
e-mail - Fehlermeldung

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-org#1636]
Folgendes passierte:

neue BEA-Securitiy wurde von Avira immer in quarantäne geschoben. 
Avira deinstalliert
BEA-Securitiy neu installiert (geht jetzt)
Java-runtime wollte ein update - wurde gemacht.

J-lawyer hat folgendes Problem, dass trotz Neuinstallation bleibt:

![grafik](https://user-images.githubusercontent.com/37142896/166679442-c455dd12-eb73-4412-9abf-9e4a00d68659.png)

Die Konteneinrichtigung in J-Lawyer läuft, der Testversand klappt, aber der e-mailbereich geht nicht. Man bekommt die Konten nicht zu sehen, nur die Fehlermeldung..

Bin einigermaßen ratlos.

**NOTE: Please search existing tickets to avoid duplicates **
**HINWEIS: Bitte vorab die Ticketsuche verwenden, um Doppeleinträge zu vermeiden **

**Describe the bug / Fehlerbeschreibung**
(todo: a description of the bug / eine Beschreibung des Fehlers)

**To Reproduce / Schritte zum Nachvollziehen**

1. Go to / Gehe zu '...'
2. Klicke auf / Click on '....'
4. Error message / Fehlermeldung: '...'

**Expected behavior / Erwartetes Verhalten**
Eine Beschreibung des erwarteten Verhaltens.

**Screenshots**
Falls relevant, Screenshot beifügen.

**Environment / verwendete Umgebung:**
 - OS / Betriebssystem:
 - j-lawyer.org Version:

**Additional context / Sonstiges**

**Comment by j-dimension** [comment]
Das passiert, wenn jemand die SSL-verschlüsselte Verbindung zum Mailserver "aufbricht" und ein eigenes Zertifikat unterjubelt. Dem vertraut der j-lawyer dann nicht und es kommt zur dargestellten Fehlermeldung. 

Du schriebst "Avira deinstalliert" - ist es denn wieder installiert? Es scheint als hättest Du vorher eine Ausnahme in Avira definiert, die jetzt nicht mehr aktiv ist. 

Wie auch immer - die Lösung liegt in der Konfiguration der verwendeten Sicherheits-/Virensoftware.
