### ISSUE TITLE
[FEATURE] PDF-Vorschau zoombar machen.

### ISSUE THREAD

**Issue by j-dimension** [jlawyerorg/j-lawyer-org#1639]
- [x] zoom per Slider
- [x] zuletzt gewählte Zoomstufe nutzer- und gerätespezifisch speichern und bei erneutem Aufruf einer PDF-Vorschau wiederherstellen
- [x] in Seite einpassen per Button
- [x] Zoom per Mausrad

https://github.com/jlawyerorg/j-lawyer-org/assets/3729754/0821c17b-a237-4764-b3eb-e2042b5d6199

**Comment by Dickmaulruessler** [comment]
Schöne Sache! (mit Mausrad scrollbar?)

**Comment by j-dimension** [comment]
> Schöne Sache! (mit Mausrad scrollbar?)

Kann ich noch nicht sagen, mal sehen was die Bibliotheken hergeben :-)

**Comment by LazyGuy21No** [comment]
Andere Software erstellt übrigens eine Vorschau als jpeg-Dateien der ersten x Seiten und stellt sie beim Anklicken dar.

**Comment by stm9x9** [comment]
wobei zoombar machen das eine ist, überhaupt den vorhandenen Platz ausnutzen, damit möglichst viel möglichst lesbar dargestellt werden kann, scheint mir nicht unwichtiger zu sein. Sprich, die Etiketten unter der Vorschau weg.

**Comment by stm9x9** [comment]
Ist Zoom per Mausrad wirklich ein usability-Gewinn? Ich glaube ich würde mir da eher ein Scrollen durch das Dokument per Mausrad wünschen. (parallel zu dem andernorts angesprochene Blättern per Pfeiltaste, wenn man lieber an der Tastatur arbeitet)

**Comment by Dickmaulruessler** [comment]
> Ist Zoom per Mausrad wirklich ein usability-Gewinn? Ich glaube ich würde mir da eher ein Scrollen durch das Dokument per Mausrad wünschen. (parallel zu dem andernorts angesprochene Blättern per Pfeiltaste, wenn man lieber an der Tastatur arbeitet)

Hmmm, an den Einwänden ist definitiv etwas dran....

**Comment by LazyGuy21No** [comment]
Also, der Finder in MacOS macht das bei PDFs so:

Die Vorschau (rechts) passt sich automatisch an die Fensterbreite (!) an. Das „Mausrad“ scrolls durch die Seiten.
