### ISSUE TITLE
Installationsanleitung für Linux noch aktuell (Stand 2022-02-07)?

### ISSUE THREAD

**Issue by r4dh4l** [jlawyerorg/j-lawyer-org#1640]
Hallo,

ich habe heute versucht, j-lawyer nach der offiziellen Anleitung von http://www.j-lawyer.org/?page_id=93#install-server unter Debian 11/Bullseye zu installieren.

Dabei sind mir drei Probleme aufgefallen:

## 1. `update user set plugin='' where User='root';` -> `ERROR 1356 (HY000)`

Dieser Schritt endet bei mir in der Fehlermeldung:

```
MariaDB [mysql]> update user set plugin='' where User='root';
#ERROR 1356 (HY000): View 'mysql.user' references invalid table(s) or column(s) or function(s) or definer/invoker of view lack rights to use them
MariaDB [mysql]> 
```

Der gesamte Abschnitt zum Setzen des root-Passworts für mariadb lässt sich aber mit dem nach der mariadb-Installation bereits vorhandenen Paket `mysql_secure_installation` umgehen. Es setzt nach Start unter `root` alle empfohlenen Einstellungen bzw. fragt diese ab.

## 2. `Unable to locate package openjdk-8-jre`

Das Paket `openjdk-8-jre` gibt es unter Debian 11 nicht mehr:

```
root@jlawyer:~# apt install openjdk-8-jre openjfx
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
#E: Unable to locate package openjdk-8-jre
root@jlawyer:~#
```

Im 11/Bullseye-Repo werden v11 und v17 angeboten. Es fehlt hier also eine Empfehlung, welche Version genommen werden soll.

# 3. "(3) j-lawyer.org Server-Installer ausführen" -> Hinweis auf Bezugsquelle fehlt?

Entweder ich war heute sehr blind, oder es gibt tatsächlcih keinen Hinweis darauf, wo man das Skript für die Schritte

```
chmod a+x j-lawyer-server_unix_1_9.sh
sudo ./j-lawyer-server_unix_1_9.sh
```

beziehen soll. Nach ein bisschen Gesuche schien mir https://github.com/jlawyerorg/j-lawyer-server-installer naheliegend, die Skripte dort heißen aber nicht eindeutig genug so wie in der Anleitung, also habe ich an dieser Stelle abgebrochen.

Desweiteren vermisse ich irgendeine Empfehlung, ob man für das Skript vorab einen unprivilegierten User erstellen soll. `sudo ./j-lawyer-server_unix_1_9.sh` impliziert, dass man das Skript nicht unter dem eigentlich root-User starten soll, sondern wenn dann unter einem, der sich zu `root` machen kann, also beispielsweise einegrichteten Standard-User neben `root`. Empfiehlt es sich dennoch einen User spziell für j-lawyer zu erstellen, beispielsweise mit `useradd -m -d /home/jlawyer -s /bin/false jlawyer`?

**Comment by j-dimension** [comment]
Kann mysql_secure_installation auch die Anmeldung per TCP aktivieren (statt nur Unix Sockets)?

Wenn JDK8 nicht verfügbar ist, dann bitte 11 nutzen. Damit funktioniert der j-lawyer-server problemlos.

Die Installer (j-lawyer-server_unix_x_x.sh) gibt es unter den Downloads auf der Website. Diese müssen dann auf das Zielsystem kopiert werden.

Es muss kein separater Nutzer angelegt werden, das machen die Installer automatisch. Sie erstellen einen neuen Nutzer "j-lawyer-server" (ohne ein home-Directory), unter welchem der Dienst dann ausgeführt wird. Die Installation selbst muss aber mit root-Rechten ausgeführt werden, daher per sudo oder direkt als root.

**Comment by r4dh4l** [comment]
> Kann mysql_secure_installation auch die Anmeldung per TCP aktivieren (statt nur Unix Sockets)?

Das weiß ich leider nicht. Allerdings sehe ich gerade, dass der Befehl in http://www.j-lawyer.org/?page_id=93#install-server im Block

```
sudo mysql -u root
use mysql;
update user set plugin='' where User='root';
flush privileges;
quit;
sudo systemctl restart mariadb.service
sudo mysql_secure_installation
```

durchaus erwähnt wird. Fiel mir vorhin nicht auf, weil ich wie gesagt bei `update user set plugin='' where User='root';` schon hängen blieb.

Insgesamt wurde bei meinem Versuch aber alles abgefragt, was laut http://www.j-lawyer.org/?page_id=93#install-server abgefragt werden soll, also:

```
Enter current password for root (enter for none): Enter
Set root password? [Y/n]: Y
New password: geheimesPasswort
Re-enter new password: geheimesPasswort
Remove anonymous users? [Y/n]: Y
Disallow root login remotely? [Y/n]: Y
Remove test database and access to it? [Y/n]: Y
Reload privilege tables now? [Y/n]: Y
```

> Wenn JDK8 nicht verfügbar ist, dann bitte 11 nutzen. Damit funktioniert der j-lawyer-server problemlos.

Danke, das sollte unbedingt in die Doku.

> Die Installer (j-lawyer-server_unix_x_x.sh) gibt es unter den Downloads auf der Website. Diese müssen dann auf das Zielsystem kopiert werden.

Gut, mein Fehler :facepalm: – ein Link zum Download-Bereich dazu in der Doku wäre aber nicht verkehrt. Ist schon ziemlich klicklastig, bis man bei https://cloud.j-dimension.com/index.php/s/wscJLx3KDCKoEWm?path=%2F2.1.0%2FLinux%20Installer landet.

> Es muss kein separater Nutzer angelegt werden, das machen die Installer automatisch. Sie erstellen einen neuen Nutzer "j-lawyer-server" (ohne ein home-Directory), unter welchem der Dienst dann ausgeführt wird. Die Installation selbst muss aber mit root-Rechten ausgeführt werden, daher per sudo oder direkt als root.

Danke, genau diese Erklärung wäre analog zu den in der Anleitung vorangehenden auch hilfreich.

**Comment by j-dimension** [comment]
Anleitung aktualisiert.

**Comment by j-dimension** [comment]
Weder veraltete, noch doppelte Versionen. Client und Server sind separat versioniert. Die Install-Anleitung erwähnt, dass der Server einmal im Netzwerk und der Client auf jedem Arbeitsplatz installiert werden muss.

Die Clientversion verwende ich als "führende", weil es die Version ist, die Anwender/-innen unmittelbar zu Augen bekommen.

**Comment by r4dh4l** [comment]
> Weder veraltete, noch doppelte Versionen. Client und Server sind separat versioniert. Die Install-Anleitung erwähnt, dass der Server einmal im Netzwerk und der Client auf jedem Arbeitsplatz installiert werden muss.

Das habe ich durchaus so verstanden, mich dann allerdings gefragt, ob ich für die Server-Installation `2.1.0.15` oder `2.1.0.0` nehmen soll. Angeboten werden unter https://cloud.j-dimension.com/index.php/s/wscJLx3KDCKoEWm?path=%2F2.1.0%2FLinux%20Installer ja beide.

Was mir noch während des Skripts aufgefallen ist:

1. Ein Schritt fragt

> Create symlinks?

Was damit gemeint ist ergab sich erst durch Bejahung mit der Frage

> Select the folder where you would like j-lawyer.org (Server) to create symlinks, then click Next.

Vielleicht lässt sich die Frage "Create symlinks?" noch etwas spezifizieren (Symlinks wofür).

2. Der Abschnitt 

```
Folgende Standardnutzer werden bei Neuinstallationen automatisch angelegt:

Nutzername

Passwort

admin a Nutzer mit administrativen Berechtigungen  
user u Nutzer mit eingeschränkten Berechtigungen, bspw. für Mitarbeiter  
Weitere Nutzer können über die Nutzerverwaltung (Menü "Einstellungen")
erstellt werden.
```

ist etwas "kryptisch" formatiert. Was damit gemeint ist erschloss sich erst durch http://www.j-lawyer.org/?page_id=93#install-server:

> Administrator mit Nutzername „admin“ und Passwort „a“
> Nutzer mit Nutzername „user“ und Passwort „u“

3. Die ANleitung schweigt sich darüber aus, welche Ports freigegeben werden müssen. Der Hinweis zur Client-Installation am Ende lässt natürlich darauf schließen, dass über `8080` kommuniziert wird, aber der Server lauscht ja auch auf `8443` mit einem selbstsignierten Zertifikat. Das wäre ja zunächst die sicherere Variante, oder?

**Comment by j-dimension** [comment]
> Das habe ich durchaus so verstanden, mich dann allerdings gefragt, ob ich für die Server-Installation `2.1.0.15` oder `2.1.0.0` nehmen soll. Angeboten werden unter https://cloud.j-dimension.com/index.php/s/wscJLx3KDCKoEWm?path=%2F2.1.0%2FLinux%20Installer ja beide.

Ich versteh's immer noch nicht. Es gibt dort nur einen Server-Installer. Die anderen Dateien sind mit "client" im Namen.

**Comment by j-dimension** [comment]
> 3\. Die Anleitung sagt nicht wirklich, welche Ports freigegeben werden müssen. Der Hinweis zur Client-Installation am Ende lässt natürlich darauf schließen, dass über `8080` kommuniziert wird, aber der Server lauscht laut `netstat` ja auch auf `8443` mit einem selbstsignierten Zertifikat. Das wäre ja zunächst die sicherere Variante, oder?

In einem vertrauenswürdigen Netzwerk kann man über 8080 gehen. Ansonsten wäre der SSH-Tunnel meine Präferenz, wenn man den Server auf Linux betreibt. Dann benötigt man außer dem SSH-Port gar keine Ports nach außen.

**Comment by r4dh4l** [comment]
> Ich versteh's immer noch nicht. Es gibt dort nur einen Server-Installer. Die anderen Dateien sind mit "client" im Namen.

Entschuldige, da muss ich mich völlig verguckt (bzw. in Erwartungshaltung auf Server-Installer nur auf die Versionsnummern geschaut) haben, Du hast völlig Recht.

> In einem vertrauenswürdigen Netzwerk kann man über 8080 gehen. Ansonsten wäre der SSH-Tunnel meine Präferenz, wenn man den Server auf Linux betreibt. Dann benötigt man außer dem SSH-Port gar keine Ports nach außen.

Für technisch versiertere Mitarbeiter einer Kanzler wäre das sicher eine Lösung, aber das ist ja nicht unbedingt der Fall. Demnach ist es nicht empfohlen, sich verschlüsselt über `8443` zu verbinden?

**Comment by j-dimension** [comment]
Ich hab das ehrlich gesagt noch nie genutzt / probiert, es wäre ja auch nur ein selbstsigniertes Zertifikat. Da, wo der Server öffentlich gehostet wird, habe ich jeweils einen NGINX davorgestellt oder empfohlen das zu tun, wenn kein SSH-Tunnel genutzt werden soll.

**Comment by j-dimension** [comment]
> Für technisch versiertere Mitarbeiter einer Kanzler wäre das sicher eine Lösung, aber das ist ja nicht unbedingt der Fall.

Ähm, wenn Expertise da ist, einen Linuxserver zu betreiben, dann kann es doch daran nicht scheitern? Wie gesagt, die SSH-Tunnelfunktionalität ist ja direkt in den Client eingebaut, man füllt dort nur drei Felder in den Profileinstellungen und fertig?

**Comment by r4dh4l** [comment]
> Ähm, wenn Expertise da ist, einen Linuxserver zu betreiben, dann kann es doch daran nicht scheitern? 

Nur, wenn die Person, die den Server administriert, auch die Person ist, die die Clients betreut/nutzt.

> Wie gesagt, die SSH-Tunnelfunktionalität ist ja direkt in den Client eingebaut, man füllt dort nur drei Felder in den Profileinstellungen und fertig?

Ahja, gut zu wissen. Ich habe mir die Clients bisher nicht angeschaut, weil ich nur gebeten wurde, für einen Bekannten mal den Server auf einer NAS zu installieren.

Danke jedenfalls für Deine Antworten, die meine Fragen soweit geklärt habe.
