### ISSUE TITLE
MySQL bereits installiert - Installationsfrage

### ISSUE THREAD

**Issue by MarkusJost** [jlawyerorg/j-lawyer-org#1645]
My Qsl bereits installiert und durch anderweitiges Programm genutzt. Daher klappt die Anmeldung nicht. Wie kann ich j Lawyer trotzdem installieren?

**Comment by j-dimension** [comment]
Unter Windows fragt der Installer des j-lawyer.org Servers explizit, ob ein MySQL installiert werden soll oder eine vorhandene Installation mit genutzt werden soll. Im letzteren Fall fragt er nach dem aktuellen Passwort.

Grundsätzlich also kein Problem.

**Comment by MarkusJost** [comment]
Leider erhalte ich da die M
eldung " MySQL kann im angegebenen Verzeichnis nicht gefunden werden". (Pfad (C:\Prgram File\
MySQL

**Comment by MarkusJost** [comment]
Das hat soweit geklappt, allerdings kommt nach wie vor bei der Anmeldung von "admin" und "a" die Meldung "Anmeldedaten oder Verbindungsparameter falsch"... auf einem weiteren Laptop (auf dem MySQL) nicht installiert war, klappt alles.

**Comment by j-dimension** [comment]
Dann ggf. das server.log (Fehlerprotokoll des Servers) auf Fehler prüfen oder per E-Mail senden.
https://www.j-lawyer.org/?topic=wo-findet-man-die-fehlerprotokolle-des-j-lawyer-org-servers-und-clients

**Comment by j-dimension** [comment]
PS: der j-lawyer.org Server wird nur einmal im Netzwerk installiert, der Client auf jeden Arbeitsplatz.

**Comment by MarkusJost** [comment]
Dankeschön, ich habe Ihnen die Dateien per E-Mail übersandt. Vielleicht kann man daraus was erkennen.

**Comment by j-dimension** [comment]
`java.sql.SQLException: Access denied for user 'root'@'localhost' (using password: YES)`

Das Passwort für die Datenbank ist falsch oder wird aus anderen Gründen (Konfiguration) abgelehnt. Aus der Ferne kann ich hier kaum noch helfen, da ich nicht weiß wie (für die andere(n) Anwendung(en)) die Datenbank aufgesetzt wurde.

**Comment by j-dimension** [comment]
Gern melden, wenn hier noch Hilfe benötigt wird.

**Comment by MarkusJost** [comment]
Hallo Herr Kutschke,

hier die beiden Dateien. 

Die einmalige Installation als Server ist schon klar. Ich hatte es nur auf einem anderweitigen Laptop getestet. Da geht es. Leider auf meinem Arbeitsrechner nicht ;-(

 

Ich dachte, dass es an My SQL liegt.

 

Schön Grüße aus Bad Brückenau

 

Markus 

Von: Jens Kutschke <> 
Gesendet: Dienstag, 10. Mai 2022 14:56
An: jlawyerorg/j-lawyer-org ***@***.***>
Cc: MarkusJost ***@***.***>; Author ***@***.***>
Betreff: Re: [jlawyerorg/j-lawyer-org] MySQL bereits installiert - Installationsfrage (Issue #1645)

 

PS: der j-lawyer.org Server wird nur einmal im Netzwerk installiert, der Client auf jeden Arbeitsplatz.

**Comment by j-dimension** [comment]
Ich finde hier keine Anhänge. Bitte eine Mail direkt an info@
