### ISSUE TITLE
[FEATURE] Aktensuche: Eigenschaft für synchronisierte Akte  - suchbar - 

### ISSUE THREAD

**Issue by iradraconis** [jlawyerorg/j-lawyer-org#1660]
Es sollte eine Möglichkeit geben, in der Aktensuche alle Akten aufzulisten, die für die Synchronisation aktiviert sind. Möglicherweise über einen Checkbutten neben "archiviert". So kann der Nutzer dann in der Aktensuche schnell die Synchronisation für viele Akten deaktivieren.

**Comment by j-dimension** [comment]
Es gibt in der Ergebnisliste einer Aktensuche nun eine separate Spalte mit dem Sync-Status. Sie lässt sich auch für die Sortierung nutzen.
