### ISSUE TITLE
[FEATURE] Show most important fields directly in Partys-Tab 

### ISSUE THREAD

**Issue by Bentipa** [jlawyerorg/j-lawyer-org#1662]
Description / Beschreibung:
Allow the preview of certain information directly in the Partys Tab for faster access.
This could include for example phone numbers, email and address. 
At the moment, you can directly call a certain party, but you can not simply view the information.
For that, you would need to open the party and then view the information.

It could look similar to this:
![image](https://user-images.githubusercontent.com/11789478/170078641-40b60e1d-0100-4f16-af15-68aa33bc13e3.png)

**Comment by j-dimension** [comment]
Vielen Dank, @Bentipa !
