### ISSUE TITLE
[FEATURE] Desktop - Etiketten-Reiter-Reihenfolge alphabetisieren

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#1666]
Unten links auf dem Desktop, im Fenster "nach Etikett" die Reiter unten, deren Reihenfolge ist mal so mal so. Ich fände es übersichtlicher, wenn sie alphabetisch sortiert würden.

![image](https://user-images.githubusercontent.com/29924198/171025773-17751ef9-b5ef-48b8-a774-b3ea76201f66.png)

**Comment by j-dimension** [comment]
@Bentipa auch hierfür herzlichen Dank!
