### ISSUE TITLE
[BUG] Email: Absender als "vertrauenswürdig" wird nicht gespeichert

### ISSUE THREAD

**Issue by iradraconis** [jlawyerorg/j-lawyer-org#1669]
Ich muss bei vielen Absendern, immer wieder anklicken, dass diese vertrauenswürdig sind. Ich weiß nicht wie oft ich das schon gemacht habe. Manchmal merkt sich jL dies, manchmal nicht. Aber es ist definitiv so, dass ich bspw. die Mail Adresse der LVM oder die von Bestandsmandanten schon zig mal "authorisiert" habe.

**Comment by iradraconis** [comment]
Scheint keinen Unterschied zu machen, wie ich den Client schließe. ich habe im Posteingang mehrere Emails desselben Absenders. ich klicke auf "vertrauenswürdig", schließe den Client. Öffne den Client. Die betreffende Mail ist dann lesbar (egal wie Client geschlossen wurde). Andere Mails des Absenders, bei denen ich da zumindest heute noch nicht drauf geklickt habe, zeigen die Warnung wieder an.

**Comment by j-dimension** [comment]
Ausschlaggebend ist der Anzeigename UND die Absenderadresse. Weichen die voneinander ab, werden sie als unterschiedliche Absender gewertet. Kann es sein dass irgendein dynamisch veränderter Teil in einer der beiden Angaben enthalten ist? Manchmal wird da so etwas wie eine Ticketnummer untergebracht.

**Comment by j-dimension** [comment]
Danke für die Mail. 

Zu dem Vorkommen unterschiedlicher Absendernamen für die selbe Absenderadresse: Das ist damals bewusst so von mir umgesetzt worden. Oftmals werden Spammails mit einer falschen Adresse und einem Fake-Namen versendet, bspw. dann eben "John Doe" mit der Adresse "vertrauenswürdige Mailadresse". Das möchte ich eigentlich nicht aufweichen. 

Wenn Absendername und -adresse zwischen zwei Mails übereinstimmen, dann bitte mal schauen ob diese Adresse in clientsettings.properties im Verzeichnis ".j-lawyer-client" des Arbeitsplatzes enthalten ist.

**Comment by iradraconis** [comment]
ok, dass das Client-basiert gespeichert wird, wusste ich nicht. Das könnte erklären, dass ich "gefühlt" mehrfach denselben Klick machen muss, da ich mindestens 2 Clients im ständigen Einsatz habe.

**Comment by iradraconis** [comment]
Ich habe das heute wieder in einer Akte gehabt, dass ich den Absender (Mandant) als vertrauenswürdig einstufe. Die Mail wird angezeigt. Ich wähle ein anderes Dokument und gehe dann wieder auf die Mail. Ich muss wieder bestätigen. Ich konnte auch durch Speichern der Akte, Verlassen der Akte etc. den Client nicht dazu bewegen, mir die Mail direkt anzuzeigen. Kann ich das irgendwo ausstellen? -.-

**Comment by j-dimension** [comment]
Sende bitte mal die clientsettings.properties per E-Mail, und nenne welchen Absender Du als vertrauenswürdig markiert hast.

**Comment by iradraconis** [comment]
Ich weiß nicht mehr, welcher das war :( 
ich klicke mich den ganzen Tag durch so viele Akten. Ich habe versucht, hier reinzukommentieren, so schnell es ging, damit ich es nicht vergesse. Wenn ich das Verhalten noch mal sehe, achte ich darauf. Wenn es eine Möglichkeit gäbe, diese Funktion ganz abzuschalten, wäre ich dennoch dankbar.
