### ISSUE TITLE
[FEATURE] Faxbericht - Dialog zur Dateiumbenennung

### ISSUE THREAD

**Issue by ms00st** [jlawyerorg/j-lawyer-org#1670]
Beim Abspeichern eines Faxberichtes sollte ebenfalls ein Dialog zum Ändern des Dateinamens erscheinen.

**Comment by j-dimension** [comment]
@ms00st aktuell wird die Sipgate-Session-ID, eine Art eindeutige Transaktionsnummer für den Versandvorgang, als Teil des Dateinamens verwendet. Für eine spätere weitere Recherche (bspw. Erhalt wird vom Empfänger bestritten) ist diese Session-ID sehr hilfreich, man kann über diese ID im Sipgate-Portal selbst nochmals prüfen oder die ID an den Sipgate-Support weitergeben.

Was ist die Motivation zu diesem Ticket? Bei Versand mehrerer Faxe im Kontext der selben Akte eine Art sprechende Bezeichnung "Faxversand Schriftstück ABC" hinzufügen zu können?

**Comment by ms00st** [comment]
> Was ist die Motivation zu diesem Ticket? Bei Versand mehrerer Faxe im Kontext der selben Akte eine Art sprechende Bezeichnung "Faxversand Schriftstück ABC" hinzufügen zu können?

Genau ;-)

Die Sipgate-Session-ID war mir bislang unbekannt. Mit diesem Hintergrund macht es natürlich Sinn, diese zu vermerken. 

Persönlich gehe ich davon aus, insbesondere da das Datum mit Sekundenangabe auf der Faxbestätigung vermerkt ist, diese im Zweifel über die Sipgate Weboberfläche wiederzufinden oder dem Support ausreichend Informationen zu geben, damit mir die Bestätigung übersandt werden kann. 

Daher tendiere ich dennoch dazu, aufgefordert zu werden, den Dateinamen selbst anzupassen.

**Comment by j-dimension** [comment]
Ja, ergibt Sinn. Ich überlege mir was.
