### ISSUE TITLE
Wiedervorlagen in Nextcloud einen Tag zu früh + Vortragen von Überfälligen

### ISSUE THREAD

**Issue by hackvokat** [jlawyerorg/j-lawyer-org#1672]
1. Wiedervorlagen werden in Nextcloud-Kalendern immer schon einen Tag vor Fälligkeit angezeigt. Es wäre doch besser, wenn die WVs erst am Tag der Fälligkeit auch im Kalender als "Aufgabe" für diesen Tag erscheinen. Ist das kein Konfigurationsfehler von mir oder steckt eine Logik dahinter?

2. Nicht-erledigte WVs bleiben im Kalender auch nach Überfälligkeit an dem ursprünglichen (Vor-)Tag stehen. Wenn man mal an einem Tag unterwegs ist und nicht in j-lawyer reinsieht, kann man etwas Überfälliges leicht übersehen.

Beispiel: WV war für den 1.6. eingetragen, steht also am 31.5. im Kalender. Ich schaue mal nicht in j-lawyer, sondern nur in den Kalender und sehe ab dem 1.6. (wo die WV eigentlich fällig wäre) nichts Offenes mehr.

Vorschlag: Unerledigte WV werden in der Kalendersynchronisation "vorgetragen", d.h. wenn ich am 1.6. keinen Haken setze, taucht die WV bis zur Erledigung am jeweils aktuellen Tag auf. So kann man sichergehen, nichts zu übersehen.

**Comment by j-dimension** [comment]
> 1. Wiedervorlagen werden in Nextcloud-Kalendern immer schon einen Tag vor Fälligkeit angezeigt. Es wäre doch besser, wenn die WVs erst am Tag der Fälligkeit auch im Kalender als "Aufgabe" für diesen Tag erscheinen. Ist das kein Konfigurationsfehler von mir oder steckt eine Logik dahinter?

Hab ich noch nie beobachtet. Sind die Server, auf denen j-lawyer und Nextcloud laufen, für die selbe Zeitzone konfiguriert?

**Comment by j-dimension** [comment]
> Vorschlag: Unerledigte WV werden in der Kalendersynchronisation "vorgetragen", d.h. wenn ich am 1.6. keinen Haken setze, taucht die WV bis zur Erledigung am jeweils aktuellen Tag auf. So kann man sichergehen, nichts zu übersehen.

Werde ich eher nicht umsetzen. Eine WV (und noch viel stärker eine Frist) hat ein definiertes Fälligkeitsdatum. Es sollte keinen Automatismus geben, der diese anpasst. Im j-lawyer auf dem Desktop erscheinen sie dann als überfällig, sie verschwinden also nicht aus dem Blick.

**Comment by hackvokat** [comment]
> > Vorschlag: Unerledigte WV werden in der Kalendersynchronisation "vorgetragen", d.h. wenn ich am 1.6. keinen Haken setze, taucht die WV bis zur Erledigung am jeweils aktuellen Tag auf. So kann man sichergehen, nichts zu übersehen.
> 
> Werde ich eher nicht umsetzen. Eine WV (und noch viel stärker eine Frist) hat ein definiertes Fälligkeitsdatum. Es sollte keinen Automatismus geben, der diese anpasst. Im j-lawyer auf dem Desktop erscheinen sie dann als überfällig, sie verschwinden also nicht aus dem Blick.

![Bildschirmfoto 2022-06-02 um 13 22 04](https://user-images.githubusercontent.com/98764663/171619035-fb007635-8fb4-4145-94fc-93c061c1b884.png)
Sieht so aus, ja. Termine/Fristen sind korrekt. Nur Wiedervorlagen tauchen einen Tag früher auf.

Im Kalenderblatt in j-lawyer werden nur Termine angezeigt, Wiedervorlagen und Fristen nicht (trotz Aktivierung oben). Falls das damit zusammenhängen könnte.

**Comment by j-dimension** [comment]
"Gebietsschema" bezieht sich m.W. nur auf die Oberflächendarstellung / Sprache. Ausschlaggebend sind die Einstellungen betriebssystemseitig.

**Comment by j-dimension** [comment]
> Im Kalenderblatt in j-lawyer werden nur Termine angezeigt, Wiedervorlagen und Fristen nicht (trotz Aktivierung oben). Falls das damit zusammenhängen könnte.

Vielleicht ist nur der Trenner nicht entsprechend nach oben gezogen? Egal ob Tages-/Wochen-/Monatsansicht: WV/Fristen werden immer angezeigt, wenn man berechtigt ist, den Kalender einzusehen.

**Comment by hackvokat** [comment]
Zeitzone auf dem j-lawyer-Server auf UTC gestellt. Korrigiert und gelöst - vielen Dank!

(Und es war der Trenner, den hat man in der Standardansicht nicht gesehen).

**Comment by j-dimension** [comment]
@hackvokat dann kann ich das Ticket schließen?

**Comment by hackvokat** [comment]
Ja, danke!
