### ISSUE TITLE
[BUG] Leerzeichen werden zu Bindestriche beim Kopieren von Dokumentenvorlagen

### ISSUE THREAD

**Issue by ms00st** [jlawyerorg/j-lawyer-org#1676]
Der Fehler aus dem behobenen #1494 tritt ebenfalls auf, wenn Dokumentenvorlagen kopiert und umbenannt werden.

**Comment by j-dimension** [comment]
Ist im Entwicklungsstand bereits via #1235 behoben.

**Comment by ms00st** [comment]
Danke. Hatte das Issue #1235 übersehen.
