### ISSUE TITLE
[FEATURE] Dokumenterstellung aus Vorlage, via API

### ISSUE THREAD

**Issue by iradraconis** [jlawyerorg/j-lawyer-org#1677]
siehe Titel:

Funktionen:
- Termine/WV/Fristen anlegen
- Dokumente anlegen unter Auswahl der auf dem Server hinterlegten Vorlagen und Zuordnung der Platzhalter
- ggfs. noch weitere Funktionen, die hilfreich sind für weitestgehende Automation der Aktenbearbeitung/Erstellung etc. 

-------------------------- @j-dimension 2022-07-18 ----------------------------------------
Die Vorlagen liegen aktuell nicht in der Datenbank, werden ausschließlich in einem bestimmten Unterverzeichnis des Datenverzeichnisses vorgehalten. Diese mit einer ID zu versehen, würde bedeuten eine neue Tabelle in der Datenbank aufzubauen und darauf REST-APIs zu entwickeln. Da sind wir locker bei 8h+.

Wenn der Vorlagenbezug über den Namen hergestellt wird (also am aktuellen Ansatz für die Vorlagen nichts geändert wird), dann wäre Folgendes zu tun:

optional (sehr flexibel, alternativ könnte aber auch ein fester Vorlagenname zur Dokumenterstellung vom Aufrufer angegeben werden):
- [x] API: Unterordner eines bestimmten Vorlagenordners auflisten (oder den gesamten Baum in einem Aufruf liefern): 2h
- [x] API: Vorlagen in einem bestimmten Ordner auflisten: 0,75h

zwingend nötig:
- [x] API: Platzhalter einer bestimmten Vorlage auflisten (hier ist es - ohne die Templates in die Datenbank umzuziehen - eine Herausforderung die Vorlage anzugeben, da diese nur mit Dateiname  + Ordner eindeutig ist): 3,5h
- [x] API: Dokument aus Vorlage erstellen (hier gleiche Herausforderung zur Angabe der Vorlage): 1,5h
- [x] Test mit LibreOffice + MS Office, Test mit Platzhalterwerten aus Falldatenblättern: 1h

**Comment by j-dimension** [comment]
> * Termine/WV/Fristen anlegen
> 

Bereits umgesetzt via #1603 

> * Dokumente anlegen unter Auswahl der auf dem Server hinterlegten Vorlagen und Zuordnung der Platzhalter
> 

Kennt der Client dann die Platzhalter in der Vorlage, oder braucht es noch einen Service "gib mir alle Platzhalter in Vorlage x"?

> * ggfs. noch weitere Funktionen, die hilfreich sind für weitestgehende Automation der Aktenbearbeitung/Erstellung etc.

Zu unscharf :-)

**Comment by iradraconis** [comment]
> > * Termine/WV/Fristen anlegen
> 
> Bereits umgesetzt via #1603

=> nicht gesehen, super!

> > * Dokumente anlegen unter Auswahl der auf dem Server hinterlegten Vorlagen und Zuordnung der Platzhalter
> Kennt der Client dann die Platzhalter in der Vorlage, oder braucht es noch einen Service "gib mir alle Platzhalter in Vorlage x"?

=> puh, ohne das vorher umgesetzt zu haben, weiß ich gar nicht, ob es das braucht. Flexibler wäre es, wenn es den zusätzlichen Service gäbe, sonst müsste der Client bei Hinzukommen von Platzhaltern angepasst werden. 
 
> > * ggfs. noch weitere Funktionen, die hilfreich sind für weitestgehende Automation der Aktenbearbeitung/Erstellung etc.
> 
> Zu unscharf :-)

=> mit diesem Einwand habe ich gerechnet, ich wollte das offen lassen, falls noch andere Nutzer etwas "hinzufügen" möchten. Ich überlege mal weiter..

**Comment by LazyGuy21No** [comment]
aus meiner Perspektive wären eine Funktion, die

- case_no und 
- template_id

übergeben bekommt und daraus ein Dokument unter Nutzung der Standard-Personen-Rollen-Beziehung der Akte erstellt toll. 

Eine Funktion "welche Vorlagen hast Du?" wäre mE entbehrlich, wenn der Client in der Vorlagenverwaltung die Vorlagen_ID der angeklickten Vorlagen anzeigen würde.

**Comment by iradraconis** [comment]
> aus meiner Perspektive wären eine Funktion, die
> 
> * case_no und
> * template_id
> 
> übergeben bekommt und daraus ein Dokument unter Nutzung der Standard-Personen-Rollen-Beziehung der Akte erstellt toll.
> 
> Eine Funktion "welche Vorlagen hast Du?" wäre mE entbehrlich, wenn der Client in der Vorlagenverwaltung die Vorlagen_ID der angeklickten Vorlagen anzeigen würde.

Interesse an Co-Sponsoring? Gerade der Teilaspekt „eigene Vorlagen ID“ wäre dann ggfs. umsetzbar. Wären rund 350 netto pro Kopf (bei uns beiden).

**Comment by LazyGuy21No** [comment]
bin dabei

**Comment by j-dimension** [comment]
Umgesetzt ohne den Umzug der Vorlagen in die Datenbank - voller Funktionsumfang trotzdem gegeben.

**Comment by j-dimension** [comment]
@LazyGuy21No @iradraconis hier noch ein paar Hinweise wie Ihr das testen / integrieren könnt:

Alle Vorlagenordner holen: /v6/templates/documents/folders
```
[
  "/",
  "/andere Formate",
  "/andere Formate/andere 2",
  "/CE",
  "/Falldaten-Training",
  "/FB",
  "/PKH",
  "/Smart Templates",
  "/test1",
  "/xyz"
]
```

Für einen der angegebenen Ordner die Vorlagen auflisten:
```
[
  "Fluggastrechte-Kopie.odt",
  "Fluggastrechte.odt",
  "j-lawyer-Scriptdemo-MANDANT.docx",
  "j-lawyer-Scriptdemo-MANDANT.odt",
  "script-bugtest.odt",
  "script-wennvorhanden.odt",
  "Scripttest-uksc7einlassg.odt",
  "Test-GAG-an-GA.odt",
  "V_Test_Anrede_Vollmacht.odt",
  "Verkehrsunfall-mit-Fehler.odt",
  "Verkehrsunfall.odt"
]
```

Die Platzhalter einer Vorlage ermitteln: /v6/templates/documents/{folder}/{template}/{caseId}

```
[
  "{{AKTE_ZEICHEN}}",
  "{{UKSC_7EINLASSGAM}}",
  "{{UKSC_7EINLASSGINH}}",
  "{{UKSC_7EINLASSGJANEIN}}"
]
```

Dokument erstellen per: /v6/templates/documents/{folder}/{template}/{caseId}/{fileName}
```

{
  "creationDate": "2022-10-31T20:02:57.344Z[UTC]",
  "favorite": false,
  "folderId": "85c9a8007f00010126e0aed5d93e2c05",
  "id": "2fa3d5717f000101059e3cc59671a99b",
  "name": "schnuff123ds.odt",
  "size": 12892
}
```

**Comment by iradraconis** [comment]
Werde das morgen direkt ausprobieren. Das ist der Hammer! :)
