### ISSUE TITLE
[BUG] Fehlerhafte Rundung der USt 

### ISSUE THREAD

**Issue by RA-crm** [jlawyerorg/j-lawyer-org#1679]
Bei der (kaufmännischen) Rundung der Umsatzsteuer im RVG Modul kommt es zu einem Fehler:
Beispiel:
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<html>
<head>
	
	<title></title>
	<meta name="generator" content="LibreOffice 6.0.7.3 (Linux)"/>
	<style type="text/css">
		@page { margin: 2cm }
		td p { margin-bottom: 0cm }
		p { margin-bottom: 0.25cm; line-height: 115% }
	</style>
</head>
<body lang="de-DE" dir="ltr">
<p>&nbsp;</p>
<p>&nbsp;</p>

  | Position | Betrag
-- | -- | --
1,3 | Verfahrensgebühr 			Nr. 3100 VV RVG - 79,41 € | 63,70 			€
1,2 | Terminsgebühr 			Nr. 3104 VV RVG - 79,41 € | 58,80 			€
  | Auslagen 			Nr. 7002 VV RVG | 20,00 			€
  | Zwischensumme | 142,50 			€
19 			% | Umsatzsteuer 			Nr. 7008 VV RVG | 27,07 			€
  | Zahlbetrag | 169,57 			€

Zwieschensumme142,50 * 0,19 = 27,075; kaufmännische Rundung: 27,08!

**Comment by j-dimension** [comment]
@RA-crm Aus mir noch nicht ersichtlichen Gründen ist der Wert vor dem Runden 

 27.0749996602535

Und dann tut das kaufmännische Runden genau das was es soll. Ich fürchte ich muss das komplette Plugin durchgehen.

**Comment by j-dimension** [comment]
Muss durchgehend BigDecimal verwenden, siehe https://github.com/jlawyerorg/j-lawyer-forms/pull/111

https://medium.com/nerd-for-tech/java-floating-representation-and-solution-floating-point-round-off-error-930e1a4060b5

**Comment by an-mus** [comment]
Bug behoben: https://github.com/jlawyerorg/j-lawyer-calculations/commit/ccbf4e7f4f84220e31d59b4f2f3da8657da1e6eb

**Comment by j-dimension** [comment]
Vielen Dank @an-mus !
