### ISSUE TITLE
[FEATURE] Ordnerstrukturen per Drag&Drop importieren 

### ISSUE THREAD

**Issue by Freshwaters-Graf** [jlawyerorg/j-lawyer-org#1683]
Das ist kein Feature sondern ein Bug! Das muss unbedingt gehen. File Ordner müssen genauso darein importierbar sein. Man bekommt öfter von den Mandanten größere Verzeichnisse, die genau so da rein müssen! Nicht gezippt, sondern genau so, wie sie sind!

**Comment by Bentipa** [comment]
> Das ist kein Feature sondern ein Bug! Das muss unbedingt gehen. File Ordner müssen genauso darein importierbar sein. Man bekommt öfter von den Mandanten größere Verzeichnisse, die genau so da rein müssen! Nicht gezippt, sondern genau so, wie sie sind!

Option 3: selbst implementieren, wenn man es so wichtig findet... ;)

**Comment by Dickmaulruessler** [comment]
> Das ist kein Feature sondern ein Bug! Das muss unbedingt gehen. File Ordner müssen genauso darein importierbar sein. Man bekommt öfter von den Mandanten größere Verzeichnisse, die genau so da rein müssen! Nicht gezippt, sondern genau so, wie sie sind!

@Powergrafschaft Hast du verinnerlicht, dass du nächstes Mal bitte freundlichster schreibst?

**Comment by j-dimension** [comment]
Drag & Drop für Ordnerstrukturen implementiert - Fallenlassen auf Dokumentliste oder einem bestimmten Ordner möglich.

**Comment by j-dimension** [comment]
https://github.com/user-attachments/assets/386abdfb-4e1a-479f-b450-eacdedb486a6

**Comment by Dickmaulruessler** [comment]
Ich werde es nicht brauchen, 
für viele aber sicherlich ein tolles Feature!

**Comment by iradraconis** [comment]
Absolut tolles Feature!! Gerade wenn Mdt. über die Nextcloud Ordner und Dateien beibringen, lassen sich diese einfach übertragen. Danke Jens!
