### ISSUE TITLE
Kürzeltabelle - Neues Merkmal "Zeichen" bei den Beteiligten in den Akten

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-org#169]
Ich finde in der J-lawyer-Kürzeltabelle kein Kürzel für die Nutzung des neu in der Akte bei den Beteiligten eingeführten Zeile "Zeichen". Ich nehme an, dieses ist aktenbezogen. Kann man das in einer Vorlage nutzen (also dass das aktenbezogene Zeichen automatisch eingesetzt wird und wenn ja, mit welchem Kürzel?).

**Comment by j-dimension** [comment]
Ja, es gibt dafür neue Platzhalter. Die Dokumentation gibt dazu Auskunft: http://www.j-lawyer.org/downloads/documentation/j-lawyer.org-UserGuide-de.html#__RefHeading__273_1146603382
