### ISSUE TITLE
[bea] [FEATURE] abgegebene EBs in Akte speichern / Laufzettel 

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#1691]
Aktuell gibt es beim Versenden von eEBs keinerlei Nachricht, daß es erfolgreich war. Man findet nur die EB-OSCII-Nachricht in dem gesendet-Ordner. Da ist es dann aber auch zu spät, den Laufzettel abzuholen.

Vorschlag: Nach dem Versenden eines eEBs wie bei jeder anderen Nachricht auch die Möglichkeit bieten, diese zusammen mit dem Laufzettel direkt in eine Akte zu speichern.

**Comment by j-dimension** [comment]
Ich schliesse dieses Ticket als Duplikat von #1719. 

Die Laufzettel sind mit der neuen API der BRAK (V8) nun jederzeit abrufbar, und nicht postfach- sondern nachrichtenbezogen. Ich habe die V8 in den letzten Tagen implementiert - ein paar Punkte sind noch offen, aber das Thema "Laufzettel" ist bereits wesentlich entspannt.
