### ISSUE TITLE
Dateivorschau vergrößern mittels Tastendruck

### ISSUE THREAD

**Issue by ms00st** [jlawyerorg/j-lawyer-org#1697]
Eine Funktion, die ich beim Mac sehr zu schätzen weiß, ist das öffnen und schließen einer Dateivorschau mit Druck auf die Leertaste. Diese Funktion würde ich mir in j-lawyer ebenfalls wünschen, da die eingebettete Dateivorschau oftmals zu klein ist, um Details aus einem PDF zu erkennen. Den externen PDF-Viewer zu öffnen, dauert immer einige Sekunden und stört daher im Arbeitsablauf.

**Comment by iradraconis** [comment]
> ...Den externen PDF-Viewer zu öffnen, dauert immer einige Sekunden und stört daher im Arbeitsablauf.

=> bei mir geht die PDF Datei mit einem Doppelklick sofort auf. Wenn es mehrere Sekunden dauert, möglicherweise bei größeren Dateien, hat es bei mir geholfen, die Netzwerkgeschwindigkeit mal zu überprüfen. Wenn der Server entsprechend schnell angebunden ist und dann auch der Client mit entweder schnellem WLAN oder auch direkt per guter Kabelverbindung, ist ein unmittelbares Öffnen der Datei möglich.

Wenn es zu lange dauert, den PDF Viewer zu öffnen, ist der Client Rechner zu langsam :) eine gute SSD hilft!

**Comment by j-dimension** [comment]
Ist die "Vorschau"-App gemeint? Die könnte man sich als externes Programm für PDFs konfigurieren und dann per Doppelklick oder Enter öffnen. 

Die Einrichtung ist hier beschrieben: https://www.j-lawyer.org/downloads/documentation/j-lawyer.org-UserGuide-de.html#__RefHeading__429_1146603382

**Comment by ms00st** [comment]
Danke für die Hinweise. In der Tat öffnen sich die PDFs bei Verwendung der Vorschau-App von Apple schneller als in meinem verwendeten Acrobat Reader. Da ich jedoch den Acrobat Reader gerne standardmäßig nutze um pdfs zu signieren, zudem das Programm noch weitere Vorteile hat. Daher möchte ich hier keine Änderung vornehmen.

Ich halte eine kurze Vergrößerung der PDFs mit einmaligen Betätigen der Leertaste weiterhin für sinnvoll, da sich ein externes Programm auch immer in den Vordergrund schiebt und ich zwischen den Fenstern wechseln muss. Zudem muss ich das Programm anschließend wieder schließen, wenn ich nicht zu viel im Hintergrund offen haben möchte. Aus diesem denke ich, dass es eine sinnvolle Verbesserung wäre, wenn j-lawyer selbst eine Vergrößerung von Dokumenten mittels Kurzvorschau ermöglicht.

**Comment by ms00st** [comment]
Richtig ;-)
Leider nicht bei der Vorabsuche gesehen.

**Comment by j-dimension** [comment]
Okay, dann schließe ich hier :-)

PS: Dank @iradraconis ist es möglich, für einen Dateityp mehrere externe Programme zu definieren. Man könnte also "Vorschau" als Standardanwendung definieren und so schnell öffnende PDFs haben, und per Kontextmenü dann den Acrobat öffnen, wann immer das notwendig ist.
