### ISSUE TITLE
[FEATURE] Emails mit externen Programmen erstellen

### ISSUE THREAD

**Issue by Freshwaters-Graf** [jlawyerorg/j-lawyer-org#1699]
Sorry, aber das interne Mail Programm macht mich einfach nicht glücklich! Ich weiß, dass ist ne große Leistung, sowas zu schreiben! Es wäre sehr schön, wenn man rechts in dem Dropdown bei den Beteiligungen neben Email auch nen Punkt Email Extern hätte, wo dann das aktuelle Mail Programm aufgeht! Aktuell muss ich die Mail Adresse kompliziert da raus kopieren und extern ne Mail generieren. Wäre toll, wenn das ginge! Danke!

**Comment by Freshwaters-Graf** [comment]
Bitte in den Adressen die wichtigsten Sachen als Liste darstellen, also Name (Firma), Strasse-Nr, PLZ, Ort; Fon, Mobil, 
Fax , Email!
Bitte bei Email die Möglichkeit schaffen, auch extern Emails zu verfassen! Also: Wähle ich das aus, geht Thunderbird oder Outlook auf!
Ausserdem sollte das generell anklickbar sein! Also klickt man auf die Adresse: Brief. Klickt man auf die Mail: Email Intern oder Extern (bitte auswählen). Es wäre gut, wenn man sich das aussuchen könnte. Ich werde sicher nie das interne E-Mail Programm benutzen! Aber da ist jeder anders!
Generell: War früher selber Programmierer (C++, PHP, kein Java). Bitte versucht immer mit möglichst wenigen Schritten zum Ergebnis zu kommen. 
Also: Sucht man nach einer Akte, bitte gleich alle Grundinfos des Mandanten anzeigen.
So ist das leider oft zu umständlich!
Liebe Grüße!

**Comment by j-dimension** [comment]
> Sorry, aber das interne Mail Programm macht mich einfach nicht glücklich! Ich weiß, dass ist ne große Leistung, sowas zu schreiben! Es wäre sehr schön, wenn man rechts in dem Dropdown bei den Beteiligungen neben Email auch nen Punkt Email Extern hätte, wo dann das aktuelle Mail Programm aufgeht! Aktuell muss ich die Mail Adresse kompliziert da raus kopieren und extern ne Mail generieren.

Dann verliert man aber die Funktionen: E-Mail-Vorlage nutzen, direktes Speichern der ausgehenden Mail zur Akte, optionales Anlegen einer WV, Verschlüsselung von Anhängen. 

Was sind die konkreten Kritikpunkte an der E-Mail-Integration? Vielleicht dann eher dort ansetzen und Verbesserungen implementieren.

**Comment by j-dimension** [comment]
> Bitte in den Adressen die wichtigsten Sachen als Liste darstellen, also Name (Firma), Strasse-Nr, PLZ, Ort; Fon, Mobil,
> Fax , Email!

Tickets sollten thematisch sauber getrennt sein, dafür ggf. ein eigenes Ticket machen.

**Comment by j-dimension** [comment]
> Also: Sucht man nach einer Akte, bitte gleich alle Grundinfos des Mandanten anzeigen.

Wo genau? 
Was, wenn es in der Akte 5 Mandanten gibt? 
Und auch hier: wäre neues Ticket, hat nichts mit E-Mails zu tun.

**Comment by j-dimension** [comment]
> Bitte in den Adressen die wichtigsten Sachen als Liste darstellen, also Name (Firma), Strasse-Nr, PLZ, Ort; Fon, Mobil,
> Fax , Email!

Wirklich in der Adressverwaltung, oder im Beteiligten-Tab einer Akte? Letzteres ist bereits umgesetzt, kommt mit der nächsten Version. Screenshots hier: https://github.com/jlawyerorg/j-lawyer-org/pull/1663

**Comment by j-dimension** [comment]
Ich schließe hier, mangels Feedback. Einige Aspekte sind mittlerweile umgesetzt, die externe Mailabarbeitung an sich wird in #1869 fortgeführt.
