### ISSUE TITLE
[FEATURE] Umbenennen von Ordnern in Ordnervorlagen

### ISSUE THREAD

**Issue by Dickmaulruessler** [jlawyerorg/j-lawyer-org#1704]
Der Bedienkomfort für die unter Menü “Einstellungen” - “Modul ‘Akten’” - “Dokumentordner” erstellbaren Ordnervorlagen könnte verbessert werden: 

Insbesondere das **Umbenennen** ist derzeit nur für die höchste Ebene, nicht aber für die **darunterliegenden** Ebenen möglich. 

Wenn man diese Ebene ändern möchte, muss man sie derzeitig Löschen und (zumeist komplett) neu erstellen. Ja, kann man machen, da man es nun nicht häufig ändert, aber wenn es einfacher ginge, wäre das schön. **Insbesondere wenn man am Anfang mit einer individuellen Ordnerstruktur experimentiert, ändert man aber häufig noch etwas.** Danke!

(Bei Anlage einer neuen Ordnerstruktur wird automatisch die Ebene "Dokumente" erstellt. Ist das nötig, dass dies als eigene _Ebene_ dargestellt wird? Eigentlich ist das doch schon klar. Immerhin befinden wir uns ja in dem Reiter "Dokumente".)

Verwandte Themen:
https://github.com/jlawyerorg/j-lawyer-org/issues/1245

**Comment by Dickmaulruessler** [comment]
Ich passe meine Dokumentenstruktur bzw. -bezeichnung im laufenden Betrieb immer noch recht häufig an. 

Wie macht ihr anderen das?

**Comment by stm9x9** [comment]
regulär eigentlich nicht. Ich habe je nach Sachgebiet ein paar Spezial-Ordner-Vorlagen und das paßt dann meistens.

**Comment by steboe1** [comment]
Wie ist hier der Sachstand, eine nachträgliche Umbenennung der Ordnerstruktur ist aus meiner Sicht notwendig um Anpassungen einfach vornehmen zu können

**Comment by j-dimension** [comment]
Unverändert und aktuell nicht priorisiert.

**Comment by steboe1** [comment]
danke für die schnelle Rückmeldung, schade

**Comment by Dickmaulruessler** [comment]
Merci @j-dimension.
Ich ändere weiterhin immer noch Kleinigkeiten an der Ordnerstruktur und ich empfinde das so jedes Mal als störend.
