### ISSUE TITLE
[BUG] Ersetzung Script-Platzhalter

### ISSUE THREAD

**Issue by j-dimension** [jlawyerorg/j-lawyer-org#1708]
Platzhalternamen nach Namenslänge absteigend sortieren vor Ersetzung, sonst funktionieren Konstellationen wie

KEYBLABLA = xyz
KEYBLABLA123 = abc

nicht, da nach Ersetzung von KEYBLABLA an Stelle des zweiten Platzhalters dann xyz123 steht.

**Comment by clvnsch** [comment]
wird das mit der kommenden Version bei allen dieser Konstellationen funktionieren, bei einigen meiner Vorlagen funktioniert das jetzt noch nicht, was ja klar ist. Oder werden dabei einzelne Platzhalter z.B. OrtsTeil "bevorzugt"?

Aufgefallen war mir dieses Verhalten bei "XX_ORTSTEIL", "XX_GEBORT", "XX_GEBNAME", "XX_AKTE_ZEICHEN". Bei weiteren ist es mir nicht aufgefallen, da ich diese bilnag nicht nutze.

**Comment by j-dimension** [comment]
> wird das mit der kommenden Version bei allen dieser Konstellationen funktionieren

Momentan ist es noch offen, aber ich versuche es noch in die 2.2 zu bringen. Die muss allerdings wg. einer Umstellung der BRAK bis Ende Oktober veröffentlicht werden. Wird ganz schön tough.

**Comment by j-dimension** [comment]
@clvnsch gibt es bei Dir eine bestimmte Vorlage, die mir helfen könnte das Problem nachzuvollziehen?

**Comment by clvnsch** [comment]
ja, ich habe das mal in einer neuen Vorlage mit den "Standart" Beteiligtentypen nachgestellt. 
Vorlage:
[V_Test_Anrede_Vollmacht.odt](https://github.com/jlawyerorg/j-lawyer-org/files/9853675/V_Test_Anrede_Vollmacht.odt)

Dokument, was erstellt wird, mit der selben Bevollmächtigten Musterperson):

[2022-10-24_Test_Anrede_Vollmacht2.odt](https://github.com/jlawyerorg/j-lawyer-org/files/9853683/2022-10-24_Test_Anrede_Vollmacht2.odt)

Hier ist es dann so, dass bei den ersten Beiden alles "richtig" ersetzt wird aber bei dem Dritten mal schlägt das dann fehl. (Sind allerdings immer die gleichen Funktionen, aber mit anderen Beteiligtentypen)

**Comment by j-dimension** [comment]
@clvnsch wow, danke für die Arbeit! Das war sehr hilfreich. Ich habe das Problem behoben und werde es mit der finalen 2.2 ausrollen.
