### ISSUE TITLE
Nextcloud Calendar Sync - Nextcloud wirft 404

### ISSUE THREAD

**Issue by hackvokat** [jlawyerorg/j-lawyer-org#1711]
Bei mir macht die Kalender-Synchronisation Probleme:

Teilweise bleiben erledigte oder ganz gelöschte Einträge in Nextcloud stehen.

Über das Menü "Synchronisation durchführen" hilft da auch nicht weiter. Testweise habe ich auch mal einen Termin in der Zukunft aus Nextcloud gelöscht. Dieser wird dann auch nicht neu von j-lawyer angelegt.

Gibt es eine Möglichkeit den Kalender ganz neu aufzubauen? Also z.B. alle Termine aus Nextcloud zu löschen und komplett zu synchronisieren?

server.log für den Sync habe ich angehängt.

Jemand einen Tipp?

[server.log.txt](https://github.com/jlawyerorg/j-lawyer-org/files/9110131/server.log.txt)

**Comment by j-dimension** [comment]
Die Nextcloud meldet einen 404:

```
2022-07-14 10:13:19,070 INFO  [stdout] (EJB default - 1) 10:13:19.066 [EJB default - 1] ERROR org.jlawyer.cloud.NextcloudCalendarConnector - unable to get etag for /remote.php/dav/calendars/XXX/termine/
2022-07-14 10:13:19,070 INFO  [stdout] (EJB default - 1) org.apache.jackrabbit.webdav.DavException: Not Found
2022-07-14 10:13:19,070 INFO  [stdout] (EJB default - 1) 	at org.apache.jackrabbit.webdav.client.methods.DavMethodBase.getResponseException(DavMethodBase.java:162) ~[j-lawyer-cloud.jar:?]
```
Was für eine Nextcloudversion ist das denn? 

Neuaufbau: alle Termine in Nextcloud löschen, neu synchronisieren. Oder: kompletten Kalender in Nextcloud löschen, neuen anlegen und im j-lawyer konfigurieren, synchronisieren. Glaube aber nicht dass das hier hilft.

**Comment by hackvokat** [comment]
Nextcloud ist 24.0.1

Ich habe einen neuen Kalender in Nextcloud angelegt und die Synchronisation neu gestartet. Die Termine tauchen nun in dem neuen Kalender auf, aber im serverlog steht trotzdem:

```
2022-07-14 11:04:53,571 INFO  [stdout] (EJB default - 4) 11:04:53.564 [EJB default - 4] ERROR org.jlawyer.cloud.NextcloudCalendarConnector - unable to get etag for /remote.php/dav/calendars/XXX/termine2/
2022-07-14 11:04:53,572 INFO  [stdout] (EJB default - 4) org.apache.jackrabbit.webdav.DavException: Not Found
```

**Comment by j-dimension** [comment]
Dann bitte das Log des Webservers der Nextcloud prüfen.

**Comment by hackvokat** [comment]
Da komme ich leider nicht dran (managed Nextcloud von Hetzner).

Synchronisation klappt jetzt wieder, nachdem ich den Kalender neu angelegt habe. Fehler taucht aber weiterhin im serverlog auf.

**Comment by j-dimension** [comment]
> Da komme ich leider nicht dran (managed Nextcloud von Hetzner).

Ich werde da nicht wirklich helfen können. An besagter Codestelle wird der sogenannte ETAG ermittelt, das ist eine wichtige Angabe für die Synchronisation. Ich kann mir gerade nicht vorstellen, dass Nextcloud dort mit Version 24 Änderungen vorgenommen hat, davon wären sehr viele CalDAV-Clients betroffen. Vielleicht ist das einfach eine .htaccess o.ä. Einstellung bei Hetzner. 

Ich schließe das Ticket und werde es vor dem Release der neuen j-lawyer Version nochmal testen. Die von mir genutzten Nextcloud-Installation sind alle noch auf Version 23.0.6.

**Comment by hackvokat** [comment]
Ich habe von Hetzner jetzt die Logs zu einem Zeitpunkt, bei dem j-lawyer den Error für das etag gebracht hat, bekommen:


```
Jul 22 07:53:41 storage nginx[2338841]: nginx: 88.198.175.144 - XXX [22/Jul/2022:07:53:41 +0200] "nextcloud.domain" "REPORT /remote.php/dav/calendars/XXX/wiedervorlagen/f2ce29017f0001014f1f5e65a40d7da0.ics HTTP/1.1" 404 1440 "-" "Jakarta Commons-HttpClient/3.0" "-"
Jul 22 07:53:44 storage nginx[2338841]: nginx: 88.198.175.144 - XXX [22/Jul/2022:07:53:44 +0200] "nextcloud.domain" "PUT /remote.php/dav/calendars/XXX/wiedervorlagen/f2ce29017f0001014f1f5e65a40d7da0.ics HTTP/1.1" 400 1491 "-" "Jakarta Commons-HttpClient/3.0" "-"
Jul 22 07:53:47 storage nginx[2338841]: nginx: 88.198.175.144 - XXX [22/Jul/2022:07:53:47 +0200] "nextcloud.domain" "REPORT /remote.php/dav/calendars/XXX/wiedervorlagen/f6bcaabb7f000101773065c7928672b4.ics HTTP/1.1" 207 4455 "-" "Jakarta Commons-HttpClient/3.0" "-"
Jul 22 07:53:51 storage nginx[2338841]: nginx: 88.198.175.144 - XXX [22/Jul/2022:07:53:51 +0200] "nextcloud.domain" "PUT /remote.php/dav/calendars/XXX/wiedervorlagen/f6bcaabb7f000101773065c7928672b4.ics HTTP/1.1" 204 1399 "-" "Jakarta Commons-HttpClient/3.0" "-"
Jul 22 07:53:54 storage nginx[2338841]: nginx: 88.198.175.144 - XXX [22/Jul/2022:07:53:54 +0200] "nextcloud.domain" "REPORT /remote.php/dav/calendars/XXX/wiedervorlagen/fbd286f97f0001014e9e5d5e1840e572.ics HTTP/1.1" 207 4428 "-" "Jakarta Commons-HttpClient/3.0" "-"
Jul 22 07:53:58 storage nginx[2338841]: nginx: 88.198.175.144 - XXX [22/Jul/2022:07:53:58 +0200] "nextcloud.domain" "PUT /remote.php/dav/calendars/XXX/wiedervorlagen/fbd286f97f0001014e9e5d5e1840e572.ics HTTP/1.1" 204 1401 "-" "Jakarta Commons-HttpClient/3.0" "-"
```


j-lawyer-log zu diesem Zeitpunkt:
```
2022-07-22 07:53:41,149 INFO  [stdout] (EJB default - 10) 07:53:41.142 [EJB
default - 10] ERROR org.jlawyer.cloud.NextcloudCalendarConnector - unable
to get etag for /remote.php/dav/calendars/XXX/wiedervorlagen/
2022-07-22 07:53:41,149 INFO  [stdout] (EJB default - 10)
org.apache.jackrabbit.webdav.DavException: Not Found
```

**Comment by j-dimension** [comment]
Vielleicht wurde ein Termin an j-lawyer vorbei gelöscht? Im Moment gibt es noch keine Zwei-Wege-Synchronisation.
