### ISSUE TITLE
[FEATURE] Beteiligte Ansicht

### ISSUE THREAD

**Issue by Freshwaters-Graf** [jlawyerorg/j-lawyer-org#1712]
Wenn man auf Beteiligte geht sieht man nur den Beteiligten, aber nicht seine Daten.
Wenn man auf Details klickt, bekommt man Felder, mit denen ich spontan nichts anfangen kann.
Wie wäre es, wenn man das anders aufteilt:
Klickt man auf Details:
Links:
- Name, Adresse (Wenn man drauf klickt Brief)
Mitte: 
- Telefon, Fax, Mail (wenn man drauf klickt Anruf, Fax oder Mail) Mail bitte mit externen Programm möglich machen!
- Mail bitte zum anklicken zum externen Programm. Bitte als Betreff Aktenbezeichnung und Aktenzeichen übernehmen.
Rechts:
- Wie aktuell
Das wäre echt total super!
Danke & Liebe Grüße!
Graf

**Comment by j-dimension** [comment]
Detailanzeige ist Duplikat von #1662 

externes Mailprogramm ist Duplikat von #1699 

Für die Mails gibt es bereits Vorlagen, die Betreff und Inhalt automatisch befüllen können.
