### ISSUE TITLE
[FEATURE] Daten Verzeichnis öffnen / verändern

### ISSUE THREAD

**Issue by Freshwaters-Graf** [jlawyerorg/j-lawyer-org#1713]
Derzeit kann man ja die Akte über die Nextcloud freigeben und öffnen.
- Schön wäre, wenn man das Verzeichnis generell gleich öffnen könnte. Zur Aktensicht ist das extrem wichtig (Vorschau ist da leider nicht ausreichend)
- Noch toller wäre es, wenn man in das geöffnete Nextcloud Verzeichnis auch Sachen rein und raus kopieren könnte und Jlawyer das gleich in die Database schreibt und die Veränderung registriert!
- Auch müssten so ganze Ordner da rein kopierbar sein!

Aktuell muss ich die Datei lokal speichern (Sorry, super nervig). Nicht alles ist mit internen Mitteln zu machen!

Generell: Es gibt in der Informatik bekanntlich Regeln, mit wie vielen Schritten man zum Ergebnis kommt! In dem Fall sind es zuviele Schritte!

Würde mich sehr freuen, wenn das ginge!

Grüße!
Mathias Graf

**Comment by j-dimension** [comment]
Duplikat von #1604
