### ISSUE TITLE
Datum externer e-mails im Dokumentenordner

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-org#1720]
Wenn man e-mails aus externem e-mail programm in den dokumentenordner verschiebt, dann sieht man zwar das Datum und die Uhrzeit der e-mail, einsortiert wird sie aber nach dem Namen, d.h. dem Datum der Verschiebung. Wichtig für die elektronische Aktenführung wäre die chronologische Einsortierung nach dem Zeitpunkt des Eingangs bzw. bei einer ausgehenden mail die Versendung. Sonst stehen diese e-mails an der falschen Stelle und man muss immer erst manuell das Datum und die Uhrzeit ändern, damit die Sortierreihenfolge stimmt.

**Is your feature request related to a problem? Please describe. / Welches Problem soll durch die Erweiterung / Verbesserung gelöst werden?**
Description / Beschreibung

**Describe the solution you'd like / Beschreibe die gewünschte Lösung**
Description / Beschreibung

**Additional context / Sonstiges **
Sonstige Informationen / Screenshots / ...

**Comment by j-dimension** [comment]
Das ist Aufgabe des E-Mail-Posteingangs (der handhabt das auch so). Per Drag&Drop werden die Dokumente nicht weiter ausgewertet. Sonst müsste man konsequenterweise auch das Änderungsdatum aus Microsoft Word oder LibreOffice-Dokumenten auslesen usw. usf.
