### ISSUE TITLE
Email Modul funktioniert unter aarch64 Build (Linux) nicht 

### ISSUE THREAD

**Issue by iradraconis** [jlawyerorg/j-lawyer-org#1722]
![eMail Fehler](https://user-images.githubusercontent.com/71747937/182213341-6493c312-10aa-4186-b453-03b2c5281193.jpg)

client.log per Mail

**Comment by j-dimension** [comment]
Der ARM64-Installer für Linux bringt kein eigenes Java mit, d.h. das muss selbst installiert werden. 

Möglichkeiten:
https://download.bell-sw.com/java/11.0.16+8/bellsoft-jdk11.0.16+8-linux-aarch64-full.deb
https://download.bell-sw.com/java/11.0.16+8/bellsoft-jdk11.0.16+8-linux-aarch64-full.rpm
https://download.bell-sw.com/java/11.0.16+8/bellsoft-jdk11.0.16+8-linux-aarch64-full.tar.gz

**Comment by iradraconis** [comment]
Liberica JDK für Arm ist installiert

**Comment by j-dimension** [comment]
Ja, aber nicht das richtige. Es gibt eine ganze Reihe an Varianten, benötigt wird die "Full JRE" oder "Full JDK", da der Email-Client JavaFX benötigt, was bei der "full" enthalten ist.

**Comment by iradraconis** [comment]
Ok, Installation der "Full" Variante nachgeholt. Funktioniert jetzt wie es soll :)
