### ISSUE TITLE
[BUG] Fehlende security section in swagger.json

### ISSUE THREAD

**Issue by timo0** [jlawyerorg/j-lawyer-org#1725]
Ich habe mit swagger-codegen eine Java Client Lib generieren lassen. 

Ich musste der swagger.json folgende Zeilen hinzufügen um mich einloggen zu können:
```
"securityDefinitions": {
    "basicAuth": {
      "type": "basic"
    }
  },
  "security": [
    {
      "basicAuth": []
    }
  ],
```

Wäre das möglich, dass das beim generieren schon reinkommt?

**Comment by j-dimension** [comment]
@timo0 schaue ich mir an.
