### ISSUE TITLE
Darstellungsproblem profil

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-org#1726]
Ich habe einen neuen Laptop aufgesetzt und wollte mir ein Profil anlegen. Ich war erst im J-Lawyer und habe die Ansicht Buchstabengröße auf die größte Stufe 5 gesetzt, damit ich das auf dem 14" Laptop mit 1920 x ... Bildpunkt gut lesen kann. (Anm: Der Lenovo schreibt selbt für windows 11 (windows 10 das gleiche) eine Ansict der Buchstaben von 150% vor, ist aber hier nicht das Problem). Nach dem Neustart von J-Lawyer ist dann der Button "sichern" des Profils. Nicht mehr zu sehen - man kann nicht sichern.... .

**Comment by j-dimension** [comment]
Duplikat von bereits bearbeitetem https://github.com/jlawyerorg/j-lawyer-org/issues/556

Kann aktuell auch manuell behoben werden, indem eine bestimmte Datei im Clientverzeichnis bearbeitet wird. Ggf. melden wenn ich ein Beispiel senden soll.
