### ISSUE TITLE
Profilanlage

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-org#1728]
Wenn ich ein neues Profil anlege für J-Lawyer wird bei meinem neuen Laptop (Windows 11) beim Neustart des Profils zwar die IP und Einstellungen übernommen, aber es erscheint nicht der Benutzername vom letzten Start, wie ich das gewohnt bin, sondern ich muss jedesmal den Nutzer und das Passwort neu eingeben. Übersehe ich da eine Einstellung oder ist das ein Fehler? 

**NOTE: Please search existing tickets to avoid duplicates **
**HINWEIS: Bitte vorab die Ticketsuche verwenden, um Doppeleinträge zu vermeiden **

**Describe the bug / Fehlerbeschreibung**
(todo: a description of the bug / eine Beschreibung des Fehlers)

**To Reproduce / Schritte zum Nachvollziehen**

1. Go to / Gehe zu '...'
2. Klicke auf / Click on '....'
4. Error message / Fehlermeldung: '...'

**Expected behavior / Erwartetes Verhalten**
Eine Beschreibung des erwarteten Verhaltens.

**Screenshots**
Falls relevant, Screenshot beifügen.

**Environment / verwendete Umgebung:**
 - OS / Betriebssystem:
 - j-lawyer.org Version:

**Additional context / Sonstiges**

**Comment by j-dimension** [comment]
Nutzername eintragen, Profil speichern --> Nutzername ist Teil des Profils.
