### ISSUE TITLE
.eml -Emails zu PDF

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-org#1729]
Da wir ja seit dem 01.01.2022 Klagen und Schriftsätze und Anlage per BEA bei Gericht einreichen müssen, fehlt mit inzwischen täglich mehrfach bei Erstellung der Anlagen, die wir regelmäßig als PDF einreichen, eine Konvertierungsfunktion, die vorhandenen e-mails, die ich als Anlage zum Schriftsatz einreichen will,  in PDF zu konvertieren. Man muss sie aufwändig entweder ausdrucken und scannen oder mit externem Mailprogramm aufrufen, dann in den Scanordner als PDF ausdrucken (z.B. mit PDF24) und dann in die Akte importieren. ...

**Comment by j-dimension** [comment]
Duplikat von #146
