### ISSUE TITLE
Antwort auf e-mail, die in Akte ist.

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-org#1731]
Oft beantwortet man eine e-mail nicht sofort, sondern speichert sie erst in die Akte. Aber dann kann man in der Akte auf die e-mail nicht mehr direkt antworten und z.B. konkret dem Mandanten seine eigenen mail/ Fragen auf die man Bezug nimmt mitsenden oder seine Fragen direkt in dessen mail nochmals lesen beim Bearbeiten). Da wir zukünftig versuchen nur noch mit der elektronischen Akte zu arbeiten und 99,9% der Korrespondenz über e-mail läuft, fehtl diese Funktion. Da die Funktion auf e-mail antworten im e-mail von J-lawyer ja schon vorhanden ist, sollte sie nach meinem Verständnis doch auch im Dokumentenordner relativ problemlos verfügbar gemacht werden können.

**Comment by j-dimension** [comment]
E-Mail per Doppelklick öffnen, antworten.

**Comment by Mucki526** [comment]
O.k.,- Error by user...
