### ISSUE TITLE
[FEATURE] [kalender] letzte Ansicht auch nach Neustart merken

### ISSUE THREAD

**Issue by Maz111111** [jlawyerorg/j-lawyer-org#1732]
Es wäre schön, wenn sich der Kalender unter chronologisch auch nach einem Neustart von jL merken würde, welche Ansicht (Liste oder Kalenderblatt) man beim letzten Mal gewählt hatte.

Aktuell wird die Ansicht nach einem Neustart von jL immer auf Liste gesetzt.

**Comment by iradraconis** [comment]
Ich kann den Featurewunsch nur noch einmal unterstreichen! Das wäre eine große Hilfe. Der Kalender ist zu einem unverzichtbaren Tool geworden. Ein Zugriff sollte so schnell wie möglich erfolgen können.
