### ISSUE TITLE
[BUG] [beA] Dateinamenerweiterung .bea automatisch erkennen.

### ISSUE THREAD

**Issue by Dickmaulruessler** [jlawyerorg/j-lawyer-org#1733]
Wenn man in der Akte unter "Dokumente" den Dateinamen umbenennt und dies im Eifer sehr schnell tut und dabei auch die Dateiendung überschreibt, so ist dies bei (fast) allen Dateiformaten unschädlich: Bei Löschen der Dateiendungen **.odt, .pdf, .eml** werden diese vom System automatisch wieder ergänzt. 

Nur wenn man bei beA-Nachrichten die Dateiendung .bea aus Versehen entfernt, wird die Nachricht praktisch unbrauchbar. Man kann es zwar korrigieren und dann ist alles wieder OK. Also kein Drama.... Geht es aber vielleicht auch mit "automatischer" Erkennung so wie bei obigen Dateiendungen?

**Comment by j-dimension** [comment]
Das kriege ich nicht (mehr) nachgestellt. Falls das noch auftritt, dann bitte genaue Bediensequenz nennen.

**Comment by Dickmaulruessler** [comment]
ja, das Problem tritt tatsächlich nicht mehr auf.
