### ISSUE TITLE
[BUG] Abbruch des Speicherns einer beA Nachricht führt trotzdem zu Verschieben in "importiert"

### ISSUE THREAD

**Issue by iradraconis** [jlawyerorg/j-lawyer-org#1734]
BeA Fenster: Möchte ich eine Bea-Nachricht komplett in eine Akte importieren, und schließe dann aber das Aktenauswahlfenster, weil ich es mir anders überlege, oder die Nachricht und die Anhänge getrennt speichern möchte, verschwindet die Nachricht trotzdem aus dem Posteingang und wird direkt in den Unterordner "importiert" verschoben. Wenn ich das Importieren abbreche, sollte der Import auch nicht erfolgen.

**Comment by j-dimension** [comment]
Dup vom bereits bearbeiteten #1572
