### ISSUE TITLE
Anlagedatum, Ablagedatum, letzte Bearbeitung

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-org#1736]
Ich habe gerade eine Akte gesucht. wenn mir der Name des Mandanten gerade nicht einfällt, dann suche ich manchmal lange in der Liste. Da wäre es evt. hilfreich, wenn im Suchergebnis Zusatzinfos eingeblendet werden könnte (Häckchen für Anlagedatum, Ablagedatum, letzte Bearbeitung), oder evt. als Filter gesetzt werden könnten.

**NOTE: Please search existing tickets to avoid duplicates **
**HINWEIS: Bitte vorab die Ticketsuche verwenden, um Doppeleinträge zu vermeiden **

**Is your feature request related to a problem? Please describe. / Welches Problem soll durch die Erweiterung / Verbesserung gelöst werden?**
Description / Beschreibung

**Describe the solution you'd like / Beschreibe die gewünschte Lösung**
Description / Beschreibung

**Additional context / Sonstiges **
Sonstige Informationen / Screenshots / ...

**Comment by j-dimension** [comment]
Duplikat von #920 
@Mucki526 , bitte vorab einmal kurz die Suche nutzen!

**Comment by stm9x9** [comment]
> **NOTE: Please search existing tickets to avoid duplicates **

@Mucki526 und die Bitte, den Vorlagetext "**NOTE: Please search existing tickets to avoid duplicates **" usw. zu löschen, wenn er nicht benutzt wird. Danke!
