### ISSUE TITLE
[BUG] Farbe Rahmen Akte ändert sich wenn man aus der Aktenhistorie in die Akte geht.

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-org#1737]
Wenn ich aus der Aktenhistorei die letzte Akte aufrufe, gelange ich in die Akte, der Rahmen der Akte (normal blau) behält dann aber die Farbe der Aktenhistorie (bei mir lila)

**NOTE: Please search existing tickets to avoid duplicates **
**HINWEIS: Bitte vorab die Ticketsuche verwenden, um Doppeleinträge zu vermeiden **

**Describe the bug / Fehlerbeschreibung**
(todo: a description of the bug / eine Beschreibung des Fehlers)

**To Reproduce / Schritte zum Nachvollziehen**

1. Go to / Gehe zu '...'
2. Klicke auf / Click on '....'
4. Error message / Fehlermeldung: '...'

**Expected behavior / Erwartetes Verhalten**
Eine Beschreibung des erwarteten Verhaltens.

**Screenshots**
Falls relevant, Screenshot beifügen.

**Environment / verwendete Umgebung:**
 - OS / Betriebssystem:
 - j-lawyer.org Version:

**Additional context / Sonstiges**

**Comment by j-dimension** [comment]
Das ist exakt so gewünscht und bspw. auch bei der Volltextsuche, dem beA, E-Mail, ... so. Die Farbe hilft zu erkennen, wohin der "zurück"-Button im Aktenkopf hinnavigieren wird.

**Comment by stm9x9** [comment]
> Das ist exakt so gewünscht und bspw. auch bei der Volltextsuche, dem beA, E-Mail, ... so. Die Farbe hilft zu erkennen, wohin der "zurück"-Button im Aktenkopf hinnavigieren wird.

Öööh. Da wären wir wieder mal beim Punkt "geniale Idee vom Chefprogrammierer" aber "kein Anwender weiß davon" :-/  Gibt es noch mehr solcher "hidden Features"? Ich hatte ja ewig und drei Tag nicht gewußt, daß man direkt auf dem Desktop einen Termin verschieben kann. Hat irgendwer eine Idee, wie man solche Sachen bekannter machen kann?
