### ISSUE TITLE
Nextcloud: Fehlermeldung bei Upload der Freigabe-Datei

### ISSUE THREAD

**Issue by LazyGuy21No** [jlawyerorg/j-lawyer-org#1738]
Synchronisierung zur Nextcloud-Instanz funktioniert (eigentlich). Der letzte Schritt (Upload) scheitert leider mit folgender Fehlermeldung. Ordner-Anlegen etc. kein Problem. 

<img width="718" alt="Bildschirmfoto 2022-08-14 um 14 52 01" src="https://user-images.githubusercontent.com/56734761/184537845-2a49e7c1-427f-40d9-985c-42bf41fa32f7.png">

**Comment by j-dimension** [comment]
503 ist ein "internal server error". Hier wäre das Log des Nextcloud-Webservers zu prüfen. Evtl. hat die PHP-Runtime zu wenig Speicher o.ä.

**Comment by j-dimension** [comment]
Gern wieder öffnen, wenn es neue Informationen gibt.

**Comment by LazyGuy21No** [comment]
post_max_size = 20G
memory_limit = 3072M
upload_max_filesize = 20G

**Comment by LazyGuy21No** [comment]
Hast Du eine Idee, wo ich gucken könnte?
