### ISSUE TITLE
[FEATURE] PDF-Umwandlung bei Dokumenterstellung

### ISSUE THREAD

**Issue by Linkki2021** [jlawyerorg/j-lawyer-org#1739]
Wir arbeiten derzeit sehr stark daran, erstellte Schriftsätze nicht mehr anfassen zu müssen.

Dazu wäre es tolll, wenn es eine Erweiterung der Erstellungsmöglichkeiten gäbe, die ein erstelltes Dokument ohne Umweg gleich in ein PDF umwandelt. Quasi als weitere Alternative zu "Erstellen und öffnen" oder "Erstellen".

![image](https://user-images.githubusercontent.com/77149788/184891052-bc25759d-f675-4e39-923b-08b6537b5c28.png)

**Comment by j-dimension** [comment]
Das wäre doch nur dann sinnvoll, wenn das Dokument *gar nicht* nachbearbeitet werden müsste. Ist das nicht relativ selten?

**Comment by Linkki2021** [comment]
Wir arbeiten daran, dass es nicht mehr so selten ist :) U.a. die Skripte und die Falldatenblätter machen es möglich.

Sicher auch eine Frage des Fachgebiets.

**Comment by stm9x9** [comment]
und in so einem Dokument ist dann wirklich alles bis aufs i-Tüpfelchen mit den Skripten etc. beim Erstellen versandreif? Ich staune und bin zutiefst beeindruckt. Da würde ich mich ja mal sehr auf ein kleines Webinar oder so zu freuen!

**Comment by j-dimension** [comment]
Werde hier das originale Dokument (docx, odt, ...) in der Akte belassen, aber direkt eine PDF-Konvertierung anstoßen.

**Comment by j-dimension** [comment]
Im Dialog zur Erstellung von Dokumenten gibt es nun eine neue Option für die automatische PDF-Erstellung. Die Einstellung wird für jede Vorlage "gemerkt", da davon auszugehen ist, dass man diese Automatik für bestimmte Vorlagen haben möchte, für andere nicht. 

![grafik](https://github.com/jlawyerorg/j-lawyer-org/assets/3729754/7b7e7155-7931-48c3-8be7-818a2c7f2c03)

**Comment by Dickmaulruessler** [comment]
Das finde ich sehr praktisch!

Wie ist das Verhalten, falls man eine odt-Datei doch einmal ändert? Irgendein automatisches Suffix in der neuen PDF?

**Comment by j-dimension** [comment]
Die PDF-Erstellung kommt nur bei Erstellung des Dokuments zum Tragen. Wird das Original dann verändert, greift die Automatik nicht.
