### ISSUE TITLE
[e-mail] Automatische Betreffzeile

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-org#174]
Es wäre erleichternd, wenn im e-mail-Sendefenster automatisch Kurzzeichen eingeblendet werden könnten (Aktenzeichen, Bezeichnung der Akte aus der man gerade sendet). Man kann im Nachrichtenfenster unter user / e-mail eine Zeichensignatur vorgeben, aber nichts für die Betreffzeile, die ist nur jedesmal manuell oder über eine anzulegende Vorlage erreichbar.

**Comment by j-dimension** [comment]
Diese Informationen sind über eine Emailvorlage bereits automatisch eintragbar, auch in die Betreffzeile. Oder soll es über eine Art Tastenkürzel oder Klick auf einen Button übernommen werden können?

**Comment by Mucki526** [comment]
Es wäre eine Sache, wenn man einfach bei Aufruf der e-mail aus einer Akte automatisch gewisse Vorgaben in der Betreffzeile haben könnte wie Aktenzeichen, Name der Akte, wegen. Ich habe mir so eine Vorlage gemacht. aber wenn ich vergesse sie anzuklicken und erst meine mail schreibe und dann auf die Vorlage gehe ist die mail weg oder ich muss vorher den Text kopieren oder von Hand Aktenzeichen und Partei bezeichnung in die Betreffzeile einfügen. Kurz - es fehlt eine Möglichkeit dem Programm eine automatische Standardgrundeinstellung für die Betreffzeil vorzugeben, sinnvollerweise zumindest Aktenzeichen, Name der Akte und ggf. "Ihr Zeichen".

**Comment by j-dimension** [comment]
Es ist unwahrscheinlich dass dieser Task umgesetzt wird - im Vergleich mit anderen wird er immer wieder depriorisiert werden. Zwecks Transparenz und Tickethygiene schliesse ich.
