### ISSUE TITLE
[FEATURE] API Endpoint `cases/create` liefert keine ID

### ISSUE THREAD

**Issue by timo0** [jlawyerorg/j-lawyer-org#1740]
Wenn man per API einen Fall erstellt, dann muss ich mir immer die ID per `cases/list` holen.

Das ist natürlich nur eine "best bet" und kann, wenn jemand anderes auch einen Fall anlegt, schlief gehen. Könnte man die ID als Result zurückliefen?

**Comment by LazyGuy21No** [comment]
ich möchte dieses Ticket sponsern. Vielleicht kann es schon in die Version 2.3?

**Comment by j-dimension** [comment]
@timo0 @LazyGuy21No ich habe gerade mal geschaut, die /v2/cases/create gibt doch die ID direkt zurück. Hier ist eine Response des Endpunktes:

```
{
  "archived": 0,
  "assistant": "admin",
  "claimNumber": "",
  "claimValue": 0,
  "custom1": "c1",
  "custom2": "c2",
  "custom3": "c3",
  "fileNumber": "003/22",
  "id": "254c3b577f0001012976a9c04985f191",
  "lawyer": "admin",
  "name": "api-case",
  "notice": "",
  "reason": "",
  "subjectField": "api-tests"
}
```

**Comment by j-dimension** [comment]
Übersehe ich etwas?

**Comment by iradraconis** [comment]
Bei mir kommt die ID auch direkt zurück beim Erstellen eines Cases. Anders könnte ich weitere Aktionen auf die Akte gar nicht laufen lassen. Läuft so wie es soll.

**Comment by j-dimension** [comment]
Dann mach ich hier zu. Gern kommentieren, wenn etwas fehlt.

**Comment by timo0** [comment]
Danke für die Test. Der generierte Swagger Client liefert da nichts zurück. Dann muss ich da nochmal in die Generierung und der swagger.json schauen
