### ISSUE TITLE
Erweiterung des Ordnersystems - Link auf andere Akte

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-org#1741]
Wir sind dabei alles auf Elektronische Akte umzustellen. Das Ordnersystem hilft dabei sehr. Jetzt haben wir aber oft im Familienrecht - eine Ehescheidung - dann irgendwann eine eigene Akte Unterhalt oder Umgang. Die möchten wir auch als eigene Akte führen und nicht mit Unterordner arbeiten. Aber wir müssen im Auge behalten, welche Akten zusammen für den Mandanten geführt werden. Da wäre es hilfreich, wenn man im Ordnersystem einen Link zum Dokumentenordner anderer Akten des Mandanten anlegen könnte, um faktisch von einer Akte zur anderen Akte zu springen. Also faktisch ein Link als Unterordner.

**Comment by PBaumfalk** [comment]
+1

Mit freundlichen Grüßen / Kindly Regards

Patrick Baumfalk
Rechtsanwalt / Lawyer

E-Mail:   ***@***.***

BAUMFALK - Rechtsanwaltskanzlei

Hauptkanzlei:
Hauptstr. 195
50169 Kerpen

Zweigstelle:
Berliner Str. 4
58452 Witten

Postanschrift:
Postfach 1233
50141 Kerpen

Tel.: +49 2273 40 68 504
Fax: +49 2273 59 03 565

E-Mail: ***@***.***
Web: www.kanzlei-baumfalk.de

**Comment by iradraconis** [comment]
Etwas ähnliches ist ja schon umgesetzt unter den Beteiligten. Dort findet sich ein Reiter, wo alle Akten mit dem Beteiligten angezeigt werden. Drauf klicken und man landet dort.

**Comment by j-dimension** [comment]
Duplikat von #41
