### ISSUE TITLE
[bea] [BUG] Betreff und Aktenzeichen werden nicht angezeigt, wenn nicht vorher online entschlüsselt / gelesen

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#1744]
ich habe mal wieder mehrere Fälle von beA-Nachrichten, die in j-l den Betreff und Aktenzeichen nicht anzeigt bekommen. Anbei ist das client-log. Die beiden entscheidenden Nachrichten sind mit der ID 168083152 und 168083201. 

Nachdem ich die Nachricht in beA-web geöffnet hatte, waren die Angaben dann auch in j-l zu sehen. Und so sieht der maßgebliche Teil dann im Log aus:

`2022-08-16 15:47:54,658 INFO [de.governikus.bea.beaToolkit.converter.attachments.AttachmentDtoToFile] Starting attachment export to C:\Users\USER\AppData\Local\Temp\beaToolkit\161841408\16290352793264844980\13961602682728060973.xml
2022-08-16 15:47:54,660 INFO [de.governikus.bea.beaToolkit.converter.attachments.AttachmentDtoToFile] Attachment export finished, hashes match
2022-08-16 15:47:54,663 INFO [org.jlawyer.bea.xjustiz.XJustizUtil] Parsing XJustiz record - first 10 bytes: 60 63 120 109 108 32 118 101 114 115
2022-08-16 15:47:54,988 WARN [org.ehcache.impl.internal.store.heap.OnHeapStore] Max Object Graph Size reached for the object : [B@1cc1f3fa
2022-08-16 15:47:55,340 WARN [de.brak.bea.osci.vhn.CoCoHtmlConverter] nachricht: xml or xsl is null
2022-08-16 15:47:57,463 INFO [de.governikus.bea.beaToolkit.converter.attachments.AttachmentDtoToFile] Starting attachment export to C:\Users\USER\AppData\Local\Temp\beaToolkit\168083201\10079745266649259340\17422073328329119410.pdf
2022-08-16 15:47:57,486 INFO [de.governikus.bea.beaToolkit.converter.attachments.AttachmentDtoToFile] Attachment export finished, hashes match
2022-08-16 15:47:59,408 INFO [de.governikus.bea.beaToolkit.converter.attachments.AttachmentDtoToFile] Starting attachment export to C:\Users\USER\AppData\Local\Temp\beaToolkit\168083201\15956001073447003893\13098685134278916467.pdf
2022-08-16 15:47:59,420 INFO [de.governikus.bea.beaToolkit.converter.attachments.AttachmentDtoToFile] Attachment export finished, hashes match
2022-08-16 15:48:01,352 INFO [de.governikus.bea.beaToolkit.converter.attachments.AttachmentDtoToFile] Starting attachment export to C:\Users\USER\AppData\Local\Temp\beaToolkit\168083201\14835687533988904622\12546310053110233644.xml
2022-08-16 15:48:01,359 INFO [de.governikus.bea.beaToolkit.converter.attachments.AttachmentDtoToFile] Attachment export finished, hashes match
2022-08-16 15:48:01,379 INFO [org.jlawyer.bea.xjustiz.XJustizUtil] Parsing XJustiz record - first 10 bytes: -61 -81 -62 -69 -62 -65 60 63 120 109
2022-08-16 15:48:01,380 INFO [org.jlawyer.bea.xjustiz.XJustizUtil] Stripping 6 bytes XML BOM
2022-08-16 15:48:03,758 WARN [org.ehcache.impl.internal.store.heap.OnHeapStore] Max Object Graph Size reached for the object : [B@1685e015
2022-08-16 15:48:04,000 WARN [de.brak.bea.osci.vhn.CoCoHtmlConverter] nachricht: xml or xsl is null
2022-08-16 15:48:05,936 INFO [de.governikus.bea.beaToolkit.converter.attachments.AttachmentDtoToFile] Starting attachment export to C:\Users\USER\AppData\Local\Temp\beaToolkit\106174222\10652561634618447169\7937158003875492160.pdf`

**Comment by stm9x9** [comment]
Da das jetzt alle neuen Nachrichten zu betreffen scheint, vermute ich einen Zusammenhang mit der Umstellung auf VHN2. siehe auch #1743

**Comment by stm9x9** [comment]
Ach ja: Anzeigenamen und Betreff bekomme ich ohne Entschlüsseln in beA-web bei einer Nachricht der BRAK, also intern im beA-System, sofort angezeigt.

**Comment by stm9x9** [comment]
heute mal wieder eine Nachricht "meines" Sozialgerichts. Diesmal werden alle Angaben direkt in j-l angezeigt, ohne das ich bisher in beA-Web war. Ich werde weiter beobachten und berichten.

**Comment by stm9x9** [comment]
jetzt habe ich wieder eine Nachricht, wo die Angaben erst in j-l zu sehen sind, wenn ich die Nachricht in beaWeb geöffnet hatte. Keine Regemäßigkeit zu erkennen.

**Comment by j-dimension** [comment]
BRAK-Support: 

> "Es kann vielleicht dran liegen, dass Sie die Nachricht erst Entschlüsseln müssen, im Web, bevor Sie das Aktenzeichen und Betreff abrufen können."

Oh. Kay.

**Comment by stm9x9** [comment]
Diese Antwort scheint mir auf so vielen Ebenen "verkehrt"!?!?

- "es kann vielleicht ..." Kennen die ihre Software nicht?
- Es kann eigentlich nicht, weil ich ja durchaus Gerichtspost bekomme, wo eben alles sofort angezeigt wird
- Es kann doch nicht ernsthaft sein, daß erstmal ein Besuchen von beA-web nötig ist, wenn man doch eigentlich gerade eine KSW benutzt, weil man nicht ins Web will!?

Hast du von irgend einem anderen KSW-Hersteller solche Probleme gehört?

**Comment by j-dimension** [comment]
Ich habe meine Verwunderung gleichermaßen zum Ausdruck gebracht. Daraufhin:

> "Ich werde mich mit meinen Kollegen drüber unterhalten und Sie bekommen am Montag dann von uns eine Antwort.

Let's see.

**Comment by j-dimension** [comment]
BRAK: 

> Mit dem Update vom 31.3.2022 ist eine Änderung beim Nachrichtenversandt umgesetzt worden, bei der das Aktenzeichen des Empfängers nicht mehr in der optionalen nachrichten.xml übermittelt wird. Das Aktenzeichen wird weiterhin im xjustiz_nachricht.xml Strukturdatensatz angegeben und muss aus diesem ausgelesen werden.
> 
> Diese Umstellung wurde von den Gerichten nur Stufenweise umgesetzt, es kann sein, dass seit dem 27.10. vermehrt gerichte auf die Nachrichten.xml verzichten.

**Comment by j-dimension** [comment]
BRAK: 

> das haben Sie korrekt verstanden. Auch in der Webanwendung werden die Aktenzeichen von externen Nachrichten erst nach dem entschlüsseln/öffnen der Nachricht in der Übersicht angezeigt.

**Comment by j-dimension** [comment]
Meine Erwartungen werden konsistent erfüllt.

**Comment by j-dimension** [comment]
@stm9x9 kannst Du helfen und mir Folgendes bereitstellen:

- XJustiz-XML einer betroffenen Nachricht
- Angabe, welcher Wert im beA Web als Betreff angezeigt wird?

Danke!

**Comment by j-dimension** [comment]
https://github.com/j-dimension/j-lawyer-bea-wrapper/issues/81

**Comment by j-dimension** [comment]
Die Lösung, die ich gewählt habe, ist ein Tradeoff zwischen Performance und Handhabung. Im Posteingang (Nachrichtenliste) werden die fehlenden Werte weiterhin nicht angezeigt. Sobald man draufklickt, sind aber in der Detailansicht alle Infos vorhanden. Auch die Nachricht, welche man zur Akte speichert, ist vollständig.

**Comment by stm9x9** [comment]
> @stm9x9 kannst Du helfen und mir Folgendes bereitstellen:
> 
> * XJustiz-XML einer betroffenen Nachricht
> * Angabe, welcher Wert im beA Web als Betreff angezeigt wird?
> 
> Danke!

brauchst du das noch?

Ich kann jedenfalls mitteilen, mit der neuen Version wird es in der Detailansicht angezeigt. Allerdings wieder mit Umlautfehler.

aus:

`<?xml version="1.0" encoding="UTF-8"?>...<tns:verfahrensgegenstand><tns:gegenstand>AS  xxx Bescheid 10.2.22 höheren Mehrbedarf</tns:gegenstand>`

wird:

![image](https://user-images.githubusercontent.com/29924198/202752653-44b9ba23-48a5-4ca6-a7f0-eadce1632441.png)

**Comment by j-dimension** [comment]
Brauche ich nicht mehr.

**Comment by stm9x9** [comment]
ich habe jetzt allerdings das umgekehrte Problem, bei Nachrichten ohne das neue Format:

In der Liste werden Betreff und Aktenzeichen angezeigt, in der Detailansicht nicht:

![image](https://user-images.githubusercontent.com/29924198/202792530-414ebd90-6819-48d9-b40d-ac0a0aa0e063.png)

**Comment by stm9x9** [comment]
> BRAK:
> 
> > das haben Sie korrekt verstanden. Auch in der Webanwendung werden die Aktenzeichen von externen Nachrichten erst nach dem entschlüsseln/öffnen der Nachricht in der Übersicht angezeigt.

Dann werden sie aber permanent dort angezeigt, weil beA-web diese Daten dann hinterlegt. j-l hingegen lädt jedesmal die Übersicht neu und merkt sich solche Daten nicht, korrekt? Kann es sein, daß BRAK meint, die KSW speichern solche Informationen auch session-übergreifend ab? Mir scheint fast so, andere KSW machen das? Weil ich bislang noch sonst nirgends von solchen Problemen gelesen habe. Weißt Du wie RAM etc das machen?

**Comment by j-dimension** [comment]
> j-l hingegen lädt jedesmal die Übersicht neu und merkt sich solche Daten nicht, korrekt?

korrekt

**Comment by j-dimension** [comment]
> ich habe jetzt allerdings das umgekehrte Problem, bei Nachrichten ohne das neue Format:
> 
> In der Liste werden Betreff und Aktenzeichen angezeigt, in der Detailansicht nicht:
> 
> ![image](https://user-images.githubusercontent.com/29924198/202792530-414ebd90-6819-48d9-b40d-ac0a0aa0e063.png)

grundsätzlich?

**Comment by stm9x9** [comment]
teils teils. Aber in den Nachrichten mit unbekannt steht in der xjustiz_nachricht.xml eigentlich alles richtig drin:

```
<tns:nachricht.gds.uebermittlungSchriftgutobjekte.0005005 xmlns:tns="http://www.xjustiz.de" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.xjustiz.de xjustiz_0005_nachrichten_3_0.xsd">
<tns:nachrichtenkopf xjustizVersion="3.2.1">
<tns:aktenzeichen.absender>xxxxx</tns:aktenzeichen.absender>
<tns:aktenzeichen.empfaenger>xxxx</tns:aktenzeichen.empfaenger>
<tns:erstellungszeitpunkt>2022-10-17T13:06:15.01</tns:erstellungszeitpunkt>
```

**Comment by j-dimension** [comment]
XJustiz 3.2.1 ist nicht mehr zulässig. 3.3.1 ist die aktuelle Version.

**Comment by stm9x9** [comment]
Aber das heißt doch nicht, daß das lesend nicht mehr unterstützt werden sollte? Alte Nachrichten ändern ja ihre XJustiz-Version nicht.

**Comment by j-dimension** [comment]
Ich habe den Workaround aber nur für 3.3.1 entwickelt. Alte Nachrichten sollten idR bereits veraktet sein.

**Comment by j-dimension** [comment]
Lesend unterstützt sind die alten XJustiz-Implementierungen ja weiterhin, aber ich werde dafür keine Bug Fixes mehr machen. Aufwand/Nutzen in schlechtem Verhältnis.

**Comment by stm9x9** [comment]
> Lesend unterstützt sind die alten XJustiz-Implementierung

aber warum kann er denn dann da die Angaben nicht auslesen?

**Comment by j-dimension** [comment]
Die Darstellung der alten XJustiz-SDS ist vorhanden, das gezielte Herausparsen bestimmter Attribute muss versionsabhängig implementiert werden.

**Comment by stm9x9** [comment]
Ich habe jetzt neben den Altfällen auch aktuelle Fälle, wo in der Liste die Akz angezeigt werden, aber nicht in der Nachrichtenansicht. Ein Betreff ist in der xml nicht vorhanden. Es handelt sich allerdings um Nachrichten einer Behörde und kein Gericht. 

```
<ns0:nachricht.gds.uebermittlungSchriftgutobjekte.0005005 xmlns:ns0="http://www.xjustiz.de" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.xjustiz.de xjustiz_0005_nachrichten_3_0.xsd">
<ns0:nachrichtenkopf xjustizVersion="3.3.1">
<ns0:aktenzeichen.absender>W-xxx</ns0:aktenzeichen.absender>
<ns0:aktenzeichen.empfaenger>xxxx</ns0:aktenzeichen.empfaenger>
<ns0:erstellungszeitpunkt>2023-01-10T12:05:29</ns0:erstellungszeitpunkt>
<ns0:herstellerinformation>
<ns0:nameDesProdukts>E-JUSTIZ-BA</ns0:nameDesProdukts>
<ns0:herstellerDesProdukts>Bundesagentur für Arbeit</ns0:herstellerDesProdukts>
<ns0:version>22.03.011</ns0:version>
</ns0:herstellerinformation>
```
