### ISSUE TITLE
Name der Notiz beim Abspeichern

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-org#1749]
Es wäre hilfreich, wenn beim Abspeichern einer Notiz mit Popupfenster abgefragt wird, ggf. optional einstellbar, welchen Dateinamen die Notiz haben soll. Dann erspart man sich das nachträgliche Umbenennen im Workflow. 

**NOTE: Please search existing tickets to avoid duplicates **
**HINWEIS: Bitte vorab die Ticketsuche verwenden, um Doppeleinträge zu vermeiden **

**Is your feature request related to a problem? Please describe. / Welches Problem soll durch die Erweiterung / Verbesserung gelöst werden?**
Description / Beschreibung

**Describe the solution you'd like / Beschreibe die gewünschte Lösung**
Description / Beschreibung

**Additional context / Sonstiges **
Sonstige Informationen / Screenshots / ...

**Comment by j-dimension** [comment]
Der Dateiname ist oben im Freitext innerhalb der Notiz direkt editierbar.

**Comment by Dickmaulruessler** [comment]
Bevor ich dazu ein gesondertes Ticket aufmache, frage ich hier erst einmal: 
Wenn man die Notiz erstellt, ist man eigentlich immer in Eile und man möchte sofort drauflosschreiben. Also klicke ich mit der Maus auf Notiz und schreibe dann sofort los. Dabei verschwindet das - mir aus jeder Hinsicht sinnvoll erscheinende - Präfix mit Datum und dem Zusatz Notiz. Es ist damit inkonsistent zu den anderen Dokumenten. Bei einer späteren Sortieroption nach "Dateiname" wird anderes als alle anderen Dateien sortiert. 

Wie ließe sich das lösen? Fokus ändern? Präfix für Notiz fest einstellen?

**Comment by j-dimension** [comment]
> Wie ließe sich das lösen? Fokus ändern? Präfix für Notiz fest einstellen und unlöschbar (nur manuell umbenennbar) machen?

Den Fokus zu ändern wäre sehr einfach.
