### ISSUE TITLE
Password should not be stored as plain text

### ISSUE THREAD

**Issue by malteos** [jlawyerorg/j-lawyer-org#175]
Currently passwords are stored as plain text in the database. That might lead to some security issues and is not really best practice.

There seems to be already an existing ticket ( https://github.com/jlawyerorg/j-lawyer-org/issues/139 ). However, I cannot open it (GitHub server error).

added by j-dimension:

- [x] j-lawyer.BOX rest client needs to get credentials from Authorization header
- [x] update database structure (password column length) for storing hashes
- [x] migration script to replace plain text pw by hash with server version update
- [ ] installer needs to replace the configuration as below (existing installations)
- [x] configuration needs to be updated (new installations), see below
- [x] user admin dialog and password reset dialog need to be reworked to make sure the password is not hashed twice
- [x] server services for updating user information must not update passwords --> move to a dedicated service
- [x] update database initialization scripts to store hashes of the initial passwords
- [ ] roll out j-lawyer.BOX management UI **before** j-lawyer.org 1.4 is released
- [x] test user creation
- [x] test user updates
- [x] test password reset
- [ ] j-lawyer.BOX installer

replace 

`                            <module-option name="unauthenticatedIdentity" value="anonymous"/>`

by 

```
                            <module-option name="unauthenticatedIdentity" value="anonymous"/>
                            <module-option name="hashAlgorithm" value="SHA-256"/> 
                            <module-option name="hashEncoding" value="base64"/>
                            <module-option name="hashUserPassword" value="true"/>
                            <module-option name="hashStorePassword" value="false"/>
```

**Comment by j-dimension** [comment]
I have been using a Github Beta feature for migrating issues from one repo to another, and some tickets are affected by a bug now :-(   GitHub does not care about my feedback to them.

So: moving some information from #139 and #115 to this ticket and closing the old ones. This is on the roadmap anyways.

**Comment by j-dimension** [comment]
​http://www.mkyong.com/java/java-sha-hashing-example/ []

​http://www.jasypt.org/howtoencryptuserpasswords.html []

String hash = org.apache.commons.codec.digest.DigestUtils?.sha256Hex(password +"salt");

**Comment by j-dimension** [comment]
Might consider using a "salt derivation" algorithm to derive the salt from the user name and avoid storing the salt. Would require efforts when renaming users. 

Need to check impact on REST API authentication and j-lawyer.BOX.

**Comment by j-dimension** [comment]
- [ ] j-lawyer.BOX rest client needs to get credentials from Authorization header
- [ ] update database structure (password column length) for storing hashes
- [ ] migration script to replace plain text pw by hash with server version update
- [ ] installer needs to replace the configuration as below (existing installations)
- [ ] configuration needs to be updated (new installations), see below
- [ ] user admin dialog and password reset dialog need to be reworked to make sure the password is not hashed twice
- [ ] server services for updating user information must not update passwords --> move to a dedicated service
- [ ] update database initialization scripts to store hashes of the initial passwords
- [ ] roll out j-lawyer.BOX management UI **before** j-lawyer.org 1.4 is released


replace 

`                            <module-option name="unauthenticatedIdentity" value="anonymous"/>`

by 

```
                            <module-option name="unauthenticatedIdentity" value="anonymous"/>
                            <module-option name="hashAlgorithm" value="SHA-256"/> 
                            <module-option name="hashEncoding" value="base64"/>
                            <module-option name="hashUserPassword" value="true"/>
                            <module-option name="hashStorePassword" value="false"/>
```

**Comment by j-dimension** [comment]
@timo0 I added the hashing configuration to the standalone.xml used by the docker image(s).
