### ISSUE TITLE
[TASK] Fokus bei Notiz-Freifeld/Titel ans Ende setzen, damit Datum und Wort "Notiz" stehen bleiben

### ISSUE THREAD

**Issue by Dickmaulruessler** [jlawyerorg/j-lawyer-org#1750]
(Übertrag aus #1749):

Wenn man die Notiz erstellt, ist man eigentlich immer in Eile und man möchte sofort drauflosschreiben. Also klicke ich mit der Maus auf Notiz und schreibe dann sofort los. Dabei verschwindet das - mir in jeder Hinsicht sinnvoll erscheinende - Präfix mit Datum und dem Zusatz Notiz. Es ist damit inkonsistent zu den anderen Dokumenten. Bei einer späteren Sortieroption nach "Dateiname" wird anderes als alle anderen Dateien sortiert.

Wie ließe sich das lösen? Fokus ändern? Präfix für Notiz fest einstellen und unlöschbar (nur manuell umbenennbar) machen?

Von @j-dimension vorgeschlagene [Lösung](https://github.com/jlawyerorg/j-lawyer-org/issues/1749#issuecomment-1235325101)

_Den Fokus zu ändern wäre sehr einfach._

**Comment by j-dimension** [comment]
Doch nicht so einfach wie ich das dachte. Die Komponente lässt mich die Cursorposition anhand des dargestellten Textes setzen, sagt mir aber nur die maximale Position auf Basis des HTML-Inhaltes... ich schiebe in die 2.3.

**Comment by j-dimension** [comment]
Finde hier leider keine Lösung...
