### ISSUE TITLE
[FEATURE] Aktenzeichen bei beA-Versand automatisch vom Beteiligten übernehmen

### ISSUE THREAD

**Issue by ReRo-G** [jlawyerorg/j-lawyer-org#1753]
**Is your feature request related to a problem? Please describe. / Welches Problem soll durch die Erweiterung / Verbesserung gelöst werden?**
Im beA-Versanddialog muss das Aktenzeichen aus der Liste aller Aktenzeichen der Beteiligten der Akte ausgewählt werden.

**Describe the solution you'd like / Beschreibe die gewünschte Lösung**
Das Aktenzeichen des Beteiligten, welcher als Empfänger der Nachricht ausgewählt wurde, sollte direkt übernommen werden.

**Comment by LazyGuy21No** [comment]
Biiiiite!

**Comment by stm9x9** [comment]
das scheint mir ein Duplikat von wahlweise #984 oder #1027

**Comment by j-dimension** [comment]
#1027 -  danke für den Hinweis.
