### ISSUE TITLE
[FEATURE] Dokumente nach Dateityp sortieren

### ISSUE THREAD

**Issue by Dickmaulruessler** [jlawyerorg/j-lawyer-org#1759]
Ich finde es sehr wichtig, das im Bereich des Akten-Reiters "Dokumente" soviel Komfort wie möglich besteht. Das ist im alltäglichen Gebrauch der wichtigste Bereich überhaupt. 

Ich würde mir dort eine Sortiermöglichkeit nach Dateityp wünschen. Ebenso wie die Sortieroption "Größe" ist das - im Gegensatz zu "Datum", "Name", "Favoriten" - nichts was man ständig benöigt (evtl. könnte man beides zusammenfassen oder mit Untermenü?), aber ab und an wäre die Sortieroption "Dateityp" wirklich sehr hilfreich. 

Ich habe sie jetzt vermisst, um eine ältere Akte, in welcher noch nicht alle Dokumente Ordnern zugewiesen waren, aufzuräumen. Mit Dateityp kann man da etwas systematischer herangehen. 
Auch wenn man z.B. eine spezielle **E-Mail** oder eine **jpeg**.-Datei oder Aktenteile (.**pdf**) sucht, wäre dies hilfreich. 

-------------------------------------------
@j-dimension 2023-05-26:

- [x] Icon (aktiv) erstellen
- [x] Icon (inaktiv) erstellen
- [x] Button implementieren: Statuswechsel, samt Anpassung der Statuus der anderen Buttons
- [x] Sortierlogik

**Comment by Dickmaulruessler** [comment]
Im Reiter "Dokumente" nutze ich die Notizen gerne. Ich habe auch häufiger den Wunsch, nur alle Notizen zu lesen. Insofern wäre auch hier eine Sortiermöglichkeit eine tolle Sache. (ja, hilfsweise könnte man die Suchfunktion nach .html suchen lassen).

**Comment by Dickmaulruessler** [comment]
Wäre die Sortiermöglichkeit nach Dateityp und nach Notizen etwas, was ich sponsorn könnte? 
Möchtest du @j-dimension den Zeitaufwand einmal checken?

**Comment by iradraconis** [comment]
In der Zwischenzeit vielleicht auch eine Idee: Wir haben einen Unterordner für Notizen. Dieser Ordner wird standardmäßig bei jeder Akte angelegt. Den Ordner allein einblenden gibt den Blick frei für alle Notizen. 

Schneller ginge es noch wenn durch Rechtsklick auf einen Ordner nur dieser eingeblendet werden könnte. Ich glaub dafür mach ich mal ein Ticket auf :)

**Comment by j-dimension** [comment]
> Schneller ginge es noch wenn durch Rechtsklick auf einen Ordner nur dieser eingeblendet werden könnte. Ich glaub dafür mach ich mal ein Ticket auf :)

Diese Funktion habe ich auch schon ab und an vermisst :-)  Evtl. würde Dir diese Variante auch weiterhelfen, @Dickmaulruessler ?

**Comment by Dickmaulruessler** [comment]
Ja, das würde ich auch sehr praktisch finden, stellt aber keine Alternative für Dateityp-Sortieroptionen dar, oder?

**Comment by j-dimension** [comment]
> Wäre die Sortiermöglichkeit nach Dateityp und nach Notizen etwas, was ich sponsorn könnte? Möchtest du @j-dimension den Zeitaufwand einmal checken?

Das wären

- [ ] Icon (aktiv) erstellen
- [ ] Icon (inaktiv) erstellen
- [ ] Button implementieren: Statuswechsel, samt Anpassung der Statuus der anderen Buttons
- [ ] Sortierlogik

Schätze so ca. 45min.

**Comment by Dickmaulruessler** [comment]
Wäre es möglich, "Notizen" als gesonderten Fall neben "HTML" zu implementieren?

**Comment by j-dimension** [comment]
Praktisch würde man - der Logik von oben folgende - gar nicht bewusst eine Auswahl treffen. Wie bei den anderen Sortier-Buttons auch, würde einfach eine Sortierung nach dem gewählten Kriterium stattfinden, in dem Fall dem Dateityp. 

Was soll die Sortierung "nach Notizen" machen? Wäre das eher ein Filter statt einer Sortierung?

**Comment by Dickmaulruessler** [comment]
Sinn und Zweck: Dass man alle Datentypen und Notizen direkt untereinander sieht und komfortabel mit den Pfeiltasten durchklicken kann.

Also nicht wie bei der Suchfunktion, dass sie nur farblich gekennzeichnet sind. Dann kann man mit den Pfeiltasten nicht "durchwandern" und auch nicht - in einem Block - alle in einen Ordner verschieben. (Sondern praktisch ein Verhalten wie im Windows Datei-Explorer.) 

Beide o.g. Anwendungsfälle stelle ich mir sehr praktisch vor.

Kannst du diesen Nutzen nachvollziehen?

**Comment by j-dimension** [comment]
Ja, den Nutzen kann ich natürlich gut nachvollziehen. Ich wollte nur darauf hinweisen, dass eine Sortierung nicht die Menge der Einträge verringert. D.h. nach Anwenden des Dateitypen-Sortierknopfes würde man zu den HTML-Dokumenten scrollen und kann von dort dann per Pfeiltasten durchnavigieren. Es sind aber alle anderen Dokumente noch sichtbar - nur wären dann eben alle HTML-Dokumente in einem Block dargestellt.

**Comment by Dickmaulruessler** [comment]
Ja, fände ich ok. Es ist dann etwas Scrollen nötig. Das wäre für mich ein "normales" Verhalten. Möglicherweise gerade auch sinnvoll, da man in einem Schritt mehrere Dateitypen verschieben möchte.

**Comment by Dickmaulruessler** [comment]
Und wäre irgendeine Trennung von normalen HTML und Notizen möglich? Gerade das einfache Durchwandern (nur) durch die Notizen ist besonders interessant.

**Comment by j-dimension** [comment]
> Und wäre irgendeine Trennung von normalen HTML und Notizen möglich? Gerade das einfache Durchwandern (nur) durch die Notizen ist besonders interessant.

Das wäre mit der oben genannten Lösung nicht möglich, da für die Sortierung ausschließlich auf die Dateiendung geschaut würde. 
Man bräuchte dafür eine echte Typisierung der Dokumente, und der Nutzer müsste dann bei Dokumenterstellung / Hinzufügen zur Akte immer einen Typ mit geben.

**Comment by Dickmaulruessler** [comment]
Ok. Wäre gegenüber der jetzigen Handhabung aber auch schon eine deutliche Erleichterung. Fände ich so ausreichend. (habe keine Ahnung, nur dumme Frage: mit hilfsweiser Klassifizierung der einen als HTM (Notizen) und alle anderen als HTML geht das nicht, oder?)

**Comment by j-dimension** [comment]
> mit hilfsweiser Klassifizierung der einen als HTM (Notizen) und alle anderen als HTML geht das nicht, oder?)

Wenn es HTML und HTM-Dokumente in der Akte gibt, würden diese jeweils blockweise dargestellt.

**Comment by stm9x9** [comment]
> > Schneller ginge es noch wenn durch Rechtsklick auf einen Ordner nur dieser eingeblendet werden könnte. Ich glaub dafür mach ich mal ein Ticket auf :)
> 
> Diese Funktion habe ich auch schon ab und an vermisst :-) Evtl. würde Dir diese Variante auch weiterhelfen, @Dickmaulruessler ?

*räusper* #1039 :-D

**Comment by Dickmaulruessler** [comment]
> > mit hilfsweiser Klassifizierung der einen als HTM (Notizen) und alle anderen als HTML geht das nicht, oder?)
> 
> Wenn es HTML und HTM-Dokumente in der Akte gibt, würden diese jeweils blockweise dargestellt.

Ich würde das dann gerne sponsern.

(könnten die Notizen dann zu. HTM werden? Mein Sponsorn ist aber unabhängig von dieser Realisierbarkeit)

**Comment by j-dimension** [comment]
> könnten die Notizen dann zu. HTM werden?

Kannst Du etwas zur Motivation sagen? HTM ist die veraltete Variante aus Zeiten, wo Dateisysteme / Betriebssysteme nicht mehr als 3 Buchstaben in der Dateiendung unterstützten. 

Auch befürchte ich, dass sich einige Nutzer wundern werden, die sich für HTML eine bestimmte Anwendung konfiguriert haben.

**Comment by Dickmaulruessler** [comment]
> 
> Wenn es HTML und HTM-Dokumente in der Akte gibt, würden diese jeweils blockweise dargestellt.

Motivation für "htm-für-Notizen" wäre (da es wohl keinen anderen Weg gibt, Notizen gesondert herauszusortieren), dass bei der Sortierung die Notizen dann von den übrigen anderen HTML Dateien blockweise getrennt wären.

**Comment by j-dimension** [comment]
@Dickmaulruessler ich konnte das noch in die 2.6 aufnehmen.

**Comment by Dickmaulruessler** [comment]
Ah, schön! Vielen Dank!
