### ISSUE TITLE
[beA] Wartezeit bei fehlerhafter Übertragung beA

### ISSUE THREAD

**Issue by Maz111111** [jlawyerorg/j-lawyer-org#1763]
Wenn eine beA Übertragung scheitert, ist die KSW für Minuten gesperrt.

Erst erscheint die Meldung "Sende", dann "Warten auf EGVP-Laufzettel" und dann "speichern in Akte"

Für die gesamte Prozedur ist die KSW für gefühlt 3- 5 Minuten gesperrt und kann nicht anderweitig genutzt werden,

Das kann im allgemeinen Arbeitsalltagsstress extrem nervig sein.

Vielleicht könnte man die Meldungen zumindest so gestalten, dass ein Arbeiten in der KSW weiterhin möglich ist - diese also in den Hintergrund gerückt werden können.

**Comment by iradraconis** [comment]
Passiert bei mir jeden Tag, und frustriert extrem! Meine momentane Lösung: währenddessen an anderen Computer und dort weiter arbeiten. Der hier angeregte Vorschlag ist da deutlich besser :)

**Comment by j-dimension** [comment]
Duplikat von #566 

Dort könnt ihr auch sehen, dass das Thema nicht mal so eben nebenbei gemacht ist.

Problematisch ist das insbesondere für Mac-Nutzer, die mit Bordmitteln keine zweite Instanz der Anwendung starten können.

**Comment by j-dimension** [comment]
> Passiert bei mir jeden Tag, und frustriert extrem! Meine momentane Lösung: währenddessen an anderen Computer und dort weiter arbeiten. Der hier angeregte Vorschlag ist da deutlich besser :)

Optionen für Mac-Nutzer: Skript erstellen, über welches man die Anwendung mehrfach öffnen kann, oder Client zwei mal in verschiedenen Verzeichnissen installieren.

**Comment by iradraconis** [comment]
Wow 30 Stunden. Das hätte ich jetzt nicht gedacht. Alternativ vielleicht auch schauen warum der bea Versand so häufig scheitert? dass der eigentliche Versand bei großen Dateien dauert, ist ja eine Sache der Bandbreite.

**Comment by j-dimension** [comment]
Bandbreite ist fast nie das Problem des beA, sehr wohl aber das zuverlässige Funktionieren. 

Gerade jetzt in diesem Moment: 90% der Transaktionen über die API schlagen fehl:

<img width="647" alt="image" src="https://user-images.githubusercontent.com/3729754/190082639-486b6472-a659-442d-8b47-724bfac215c0.png">

Und die Anwenderfragen schlagen alle hier auf, nicht beim beA. Diese "Schnittstelle" treibt mich in den Wahnsinn!

**Comment by j-dimension** [comment]
> Alternativ vielleicht auch schauen warum der bea Versand so häufig scheitert?

Sehr gerne, sollte die BRAK endlich mal tun!

**Comment by iradraconis** [comment]
Ich merk schon 😀 🤐
