### ISSUE TITLE
[FEATURE] Farbliche Markierung von Dokumenten

### ISSUE THREAD

**Issue by Dickmaulruessler** [jlawyerorg/j-lawyer-org#1764]
Ich habe wieder einen kleinen Wunsch für den Komfort im wichtigen Reiter Dokumente. 

Ich würde einzelne Dokumente gerne - **super** **auffällig** - markieren können, so dass ich ich sie mir auch für abgelenkte Situation (während eines Telefonats, während eines Mandantengesprächs, während eines gerichtlichen Termins) sofort auf den ersten Blick finde. Ich meine das optisch ungefährt so:

![jfdklöajsklfjksladjfklsjadfklöjdsklöfasd](https://user-images.githubusercontent.com/46451749/190116113-ec9f6d44-cfe5-4e80-bd43-390e0e540886.jpg)

(aktuell werden die Dokumenten-Suchergebnisse farblich so markiert)

Ich würde mir mit einer solchen Funktion ein oder zwei Dokumente markieren, welche ich in der Terminsituation als besonders wichtig erachte und ohne Lesebrille :-) und auch mit nur einem Auge sofort finden kann. 

Ja, es gibt die Favoriten. Die sind super und haben wegen des Schnellzugangs oben rechts mit dem gelben Sternchen eine tolle Funktion. Das Ganze ist aber ganz schön klein und friemelig und für eine Stresssituation nur bedingt geeignet. Das Sternchen ist dafür einfach sehr klein (nun die Hervorhebung der Favoriten zu ändern, wäre auch keine Option, die sind für diesen Zweck schon so richtig und bedürfen ansonsten keiner Veränderung).

Ich könnte es mir auch später für die App gut vorstellen. Ich weiß zwar noch nicht wie die aussieht, aber es wird jedenfalls alles sehr viel kleiner (Lesebrillen-Träger....!) lund farbliche Hervorhebungen damit ums so wichtiger werden, damit man unterwegs die Übersicht behält. 

Es gibt parallel #1748 für farbliche **Ordner**-Markierungen, wöfür ich persönlich nicht so das Bedürfnis hätte. 
Aber farbliche Markierungen sind generell schon toll, um den Überblic,k zu behalten. 

--------------------------------------------------------------------
@j-dimension 2022-11-05

- [x] Erweiterung Datenmodell: 2 Farbwerte am Dokument: 0,5h
- [x] Erweiterung (interne) API: Farbe(n) setzen: 0,5h
- [x] Definition einer Farbpalette, die sich in das Anwendungsdesign einfügt: 0,15h
- [x] Dokumentenliste: Farbauswahl-Schalter: 0,5h
- [x] Darstellung in Dokumentenliste: 0,25h
- [x] Darstellung in Dokumentenliste, wenn aktuell eine Hervorhebung nach Suche aktiv ist: 0,25h
- [x] Farben über REST-API abrufbar machen / als Dokumentmetadaten rausreichen: 0,75h
- [x] Doku(?), Test: 0,25h

= 2,4h

nicht enthalten: Filterung / Sortierung nach farblich markierten, Konfiguration einer eigenen Farbpalette, Konfiguration von Kateogorie-Beschreibung zu einer Farbe, Erweiterung der mobilen App

**Comment by j-dimension** [comment]
Konversation mit Anwender:

    Da muss ich noch ein paar Fragen stellen:

     

    - Muss ein Satz Farben konfigurierbar sein? 

Nein, ich finde, das macht es sogar noch komplizierter.

    Oder immer per Farbauswahl aus einer Palette von x Farben auswählen lassen?

Eine kleine Farbpalette wäre fein. Der eine hasst rot, der andere liebt blau... Aber vom Prinzip ginge es auch mit einer einzigen Farbe. Jetzt gibst du ja auch nur das eine Grün vor und es gibt keine andere Auswahl (Leise Anm.: Ich mag das grün aber tatsächlich nicht... Farben sind immer so eine Sache... und wenn du dann noch eine Frau fragst, wird es noch viel komplizierter.... :-)))) Von daher: Die Farbdefinition wäre schön, aber eindeutig kein Muss.

    - Muss Filterung möglich sein? (zeige alle rot markierten o.ä.)

Nein, ich finde die farbliche Hervorhebung ist für das rein Optische, wenn man irgendetwas "einordnen" möchte, kann man das über die Ordner oder über Etiketten tun.

    - Markierungen liegen am Dokument selbst, sind nicht nutzerspezifisch? Oder darf jeder Nutzer seine eigene Farbmarkierung am Dokument definieren?

Ich kann das nicht beurteilen, da Einzelanwalt.

     

    - Darstellung: Hintergrundfarbe des Dokumentes in der Akte. Noch irgendwo anders?

"des Dokuments"? Verstehe ich nicht... Ich meine ja die Dokumenten-Liste...

Was evtl. interessant sein könnte - und was alle Outlook-User von den "Kategorien" her kennen - wäre es, wenn man dem Dokument in der Dokumentenliste aus einer Auswahl von ca. 10 Farben eine Hintergrundfarbe zuweisen kann und dieser auch gleichzeitig eine textliche Erläuterung hinzufügen kann. Also z.B. "rot" für Schreiben ans Gericht, "blau" Schreiben an Mandanten - und dies an der Farbe dann auch (vom Nutzer vorgegeben) "dransteht". Oder eben andere Kategorisierungen....

Ich vermute aber, dass das die Sache für dich sehr viel komplizierter macht. Ich brauche das nicht. Wenn man das tatsächlich mehrfarbig nutzt, wird das auch schnell ein ganz schön unansehnlicher bunter Kram... Je länger ich darüber nachdenke: Zu viel Spielkram!

 

Wo würdest du die Farbauswahl anbringen? (Noch mehr?) im Kontextmenü? oder evtl. Button rechtsbündig? Nee, dann müsste der ja immer da sein. Das geht ja nicht. Oder evtl. doch, wenn kleiner als bei mir? Aber wohl doch Kontextmenü, oder? Ich wäre noch unentschlossen...

**Comment by Dickmaulruessler** [comment]
> 
> Wenn man das tatsächlich **mehrfarbig** nutzt, wird das auch schnell ein ganz schön unansehnlicher bunter Kram... Je länger ich darüber nachdenke: Zu viel Spielkram!
> 

Dann und wann denke ich in der Praxis doch, dass man zumindest statt nur einer einzigen d**och zwei oder drei unterschiedliche Farbmarkierungen** benötigen könnte. Und wenn es nun blau und rot markiert wird, wäre das auch nicht "unansehnlicher bunter Kram". 

Ich überlasse es mal dem Entwickler, ob jeder Nutzer über "bunten Kram" selbst entscheiden sollte und ob **mehrfarbige** Markierungen überhaupt in einem angemessenen Aufwand/Nutzen-Verhältnis stehen oder ob es keinen Unterschied macht, ob man nun nur einfarbig oder mehrfarbig markieren kann (jedenfalls das mit den Kategorisierungen muss aber wirklich nicht sein. Zwei oder drei Farben, deren Bedeutung jeder Nutzer stets selbst im Kopf behalten muss, wären schon gut).

**Comment by j-dimension** [comment]
Farbpalette:
![grafik](https://user-images.githubusercontent.com/3729754/205465079-442f2476-c1f6-47b2-9846-90dfe38cdf9b.png)

Feedback willkommen - ich orientiere mich an Farblehre-Tools wie 
https://www.sessions.edu/color-calculator/
https://www.canva.com/colors/color-wheel/

**Comment by Dickmaulruessler** [comment]
Gefällt mir gut!
Auf keinen Fall mehr Farben (falls die Anzahl überhaupt eine Frage ist, dann eher weniger).

**Comment by j-dimension** [comment]
https://user-images.githubusercontent.com/3729754/206033670-ec9227b9-efd8-4c6d-a8ca-1eea8fbe8c4c.mp4

**Comment by Dickmaulruessler** [comment]
Das finde ich in der Funktion ganz hervorragend umgesetzt! Auch die beiden verschieden Möglichkeiten (links einzeln und rechts mehrere) sind sehr praktisch!

Ganz herzlichen Dank!

Ich würde zur **Farbpalette** aber vielleicht doch noch einmal eine Anmerkung machen, was ich bei obigem Kommentar übersehen hatte. Ich weiß nicht, wie kompliziert es ist, das jetzt noch zu ändern. 

Wenn die farbliche Markierung erfolgt ist, sieht man die verschiedenen Farben nicht mehr nebeneinander im direkten Vergleich - sondern praktisch nur in der Dokumentenliste "aus der eigenen Erinnerung". Den Unterschied zwischen den hier markierten Farben

![Farbpalette](https://user-images.githubusercontent.com/46451749/206161212-663c995e-85ae-4e13-ad59-a2b0554543f1.jpg)

wird man daher nicht kennen. Die Farben sind sich zu ähnlich. Nach meinem Dafürhalten sind es auch zu viele. Man benötigt keine Auswahl zwischen hell und dunkel - Pink. Auch nicht für drei verschiedene Grün-Töne. Das verwirrt nur und macht es zu kompliziert. 

Auch hat jeder für sich für Farben eine gewisse Assoziation. Insbesondere für Rot (sehr wichtig), **orange (!)** (weniger wichtig), "Ampel", **gelb (!)** grün ("geklärt") und blau. Einige wichtige "klassische" Farben fehlen teilweise.

Ich würde daher anregen, doch noch einmal über eine ganz klassische Farbtabelle nachzudenken. Nach meinem Dafürhalten reichen 8 Farben (plus das Löschen-Feld). Also meine Idee wäre: Ganz **klassische** (ohne pastell oder so einen "Spielkram"): Rot, orange, gelb, grün, blau, (irgendeine weitere Farbe). Dazu dann noch weiß (müsste wohl umrandet (!?) sein, da man es sonst auf dem teilweise weißen Spalten-Hintergrund nicht sieht, oder?), schwarz. Nur als Beispiel: 

![6-Farben](https://user-images.githubusercontent.com/46451749/206164125-d3f67b38-bf60-478d-b90d-46c4f46067d5.jpg)

**Comment by j-dimension** [comment]
@Dickmaulruessler danke für das Feedback. Die Farben werde ich noch ein wenig nachschärfen.

**Comment by Dickmaulruessler** [comment]
Merci!

**Comment by Dickmaulruessler** [comment]
Freue mich sehr auf dieses Feature!
