### ISSUE TITLE
Layoutanpassung Dokumenten-Tab in der Akte

### ISSUE THREAD

**Issue by j-dimension** [jlawyerorg/j-lawyer-org#1766]
> Nur rein informatorisch möchte ich nur auf eine besonders schöne Eigenschaft des derzeitigen Scaneingangs hinweisen: Das Vorschaufenster rechts, welches ja das DINA4-Seitenverhältnis verlangt, wird derzeitig nicht durch weitere Fensterbereiche zwangsweise verkleinert

Das möchte ich auch gerne unterstreichen! So in den Dokumenten würde sehr helfen!

_Originally posted by @stm9x9 in https://github.com/jlawyerorg/j-lawyer-org/issues/1613#issuecomment-1228787517_

**Comment by j-dimension** [comment]
@Dickmaulruessler

**Comment by j-dimension** [comment]
Sieht jetzt so aus:

![grafik](https://user-images.githubusercontent.com/3729754/191116603-6d67f631-7782-4dbd-8cda-7564348269fc.png)

**Comment by Dickmaulruessler** [comment]
Ich musste etwas länger suchen...

Aber ja, wunderbar! 
Kleine Änderung (unten Etiketten) - große Wirkung (rechts Vorschau)!

Danke!

Könnte das

![dflöasdlkföjlasdasfdasd](https://user-images.githubusercontent.com/46451749/191120543-e284c589-09e7-44e2-a4ea-4e06534b10ca.jpg)

möglicherweise gar auch noch linksbündig (das Suchfeld links könnte etwas verkleinert werden) und dann das Vorschaufenster weiter hochziehen? 
Würde auch den Mausweg verkürzen...
Gesondertes Ticket?
