### ISSUE TITLE
[BUG] E-Mail löschen löscht endgültig statt in den Papierkorb verschieben

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#1767]
Ich habe eben eine Mail verloren.

Ich weiß nicht genau, vielleicht hab ich doppelt auf Löschen gedrückt und nicht nur wie gewünscht, die Spam-Nachricht gelöscht sondern auch die legitime Mail. Oder es ist sonstwas passiert; denn die Mail war erst noch da, aber im Inhaltsfenster war eine kryptische Fehlermeldung. Erst nach einem Reload war sie komplett weg.

Aber was mir dabei auffiel: gelöschte Mails werden nicht wie sonst überall üblich in den Papierkorb-Ordner verschoben, sondern wirklich gleich endgültig gelöscht. Ich würde es zur Fehlervermeidung sehr begrüßen, wenn Löschen nur in den Papierkorb verschieben würde.

**Comment by j-dimension** [comment]
> Ich weiß nicht genau, vielleicht hab ich doppelt auf Löschen gedrückt und nicht nur wie gewünscht, die Spam-Nachricht gelöscht sondern auch die legitime Mail. Oder es ist sonstwas passiert; denn die Mail war erst noch da, aber im Inhaltsfenster war eine kryptische Fehlermeldung. Erst nach einem Reload war sie komplett weg.

Dazu bräuchte ich eine genaue Aktionsabfolge, sonst kann ich nicht helfen.

**Comment by j-dimension** [comment]
> Aber was mir dabei auffiel: gelöschte Mails werden nicht wie sonst überall üblich in den Papierkorb-Ordner verschoben, sondern wirklich gleich endgültig gelöscht.

Das kann passieren, wenn der Mailserver keinen Papierkorb-Ordner mitteilt. Was ist das für ein Mailserver?

**Comment by stm9x9** [comment]
Ich kann leider keine Aktionsabfolge liefern, weil mich das ja auch überrascht hat und ich nicht darauf geachtet hatte. :-(

> Das kann passieren, wenn der Mailserver keinen Papierkorb-Ordner mitteilt. Was ist das für ein Mailserver?

Ein ganz normaler IMAP-Server denke ich. In Thunderbird geht das auch wunderbar.

**Comment by j-dimension** [comment]
> Ein ganz normaler IMAP-Server denke ich. In Thunderbird geht das auch wunderbar.

In Thunderbird bitte mal Rechtsklick auf den Papierkorb, dann Eigenschaften. Bitte die Adresse hier posten (eigene Domain kann entfernt werden, ich brauche nur den Pfad hinten).

**Comment by stm9x9** [comment]
imap://anwalt%40xxx.de@imap.xxx.de/Trash

**Comment by j-dimension** [comment]
@stm9x9 danke. Kannst Du mal einen Ordner "Papierkorb", "Trash" oder "Gelöscht" unterhalb des Posteingang-Ordners erstellen und schauen ob die gelöschten dann dort einlaufen?

**Comment by librelegal** [comment]
> imap://anwalt%[40xxx.de@imap.xxx.de](mailto:40xxx.de@imap.xxx.de)/Trash

@stm9x9 ist das Problem gelöst?

**Comment by stm9x9** [comment]
ja, ist gelöst
