### ISSUE TITLE
[BUG] beA Fehler beiim Holen der beA Nachricht

### ISSUE THREAD

**Issue by iradraconis** [jlawyerorg/j-lawyer-org#1768]
siehe Fehlermeldung. Fehler erscheint bei einigen (nicht allen) Nachrichten seit der kürzlichen Umstellung auf eine neue beA Karte. Ich nutze in jLawyer mit einem Softwarezertifikat. Ich musste aber beides, Karte und Softwarezertifikat, neu freischalten im WebBea. Das habe ich letzte Woche gemacht und seither habe ich ein paar Eingänge, die eine solche Fehlermeldung auswerfen. Abruf in WebBea funktioniert.

Ich weiß, dass das auch an beA liegen kann und nicht zwingend an jLawyer, das issue ist dann ggfs. nur "informatorisch".

![Bildschirmfoto 2022-09-28 um 14 28 51](https://user-images.githubusercontent.com/71747937/192779008-54c56a1a-ffa0-45d8-bddc-af014a99fa47.png)

**Comment by j-dimension** [comment]
```
2022-09-28 14:32:59,445 INFO  [org.jlawyer.bea.xjustiz.XJustizUtil] Parsing XJustiz record - first 10 bytes: -17 -69 -65 60 63 120 109 108 32 118 
2022-09-28 14:32:59,445 INFO  [org.jlawyer.bea.xjustiz.XJustizUtil] Stripping 3 bytes XML BOM
```

**Comment by j-dimension** [comment]
@iradraconis kann ich mal den XJustiz-Strukturdatensatz der Nachricht per Mail bekommen?

**Comment by iradraconis** [comment]
> @iradraconis kann ich mal den XJustiz-Strukturdatensatz der Nachricht per Mail bekommen?

siehe Mail.

**Comment by j-dimension** [comment]
Mit dem letzten Stand der beA-Integration kann ich den Fehler nicht reproduzieren, bin also guter Dinge dass es mit dem Stand der 2.2 bereits gefixt ist. Ansonsten müsste das Ticket nochmal neu aufgemacht werden.
