### ISSUE TITLE
[BUG] [beA] rechts Panel (Speicher-Optionen) zu klein bei langem Betreff

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#1769]
Ich habe gerade eine beA-Nachricht geöffnet, wo das rechte Panel mit den Speicher-Optionen seeehr klein ist und sich auch nicht vergrößern läßt:

![image](https://user-images.githubusercontent.com/29924198/192900141-42ed7f3d-7f0d-4eb4-a106-8af10aa9a01f.png)

Ich vermute es liegt am langen Betreff?

**Comment by j-dimension** [comment]
Das ist möglich, ja. (Betreff als Ursache)

Was ist das für eine Auflösung?

**Comment by stm9x9** [comment]
1680x1050
