### ISSUE TITLE
Gerichtsadressen / Gerichtsorte

### ISSUE THREAD

**Issue by j-dimension** [jlawyerorg/j-lawyer-org#177]
https://de.openlegaldata.io/pages/api/?

**Comment by PBaumfalk** [comment]
Wir haben darüber am Sonntag mal gesprochen. Wenn Zeit da ist, könnten wir eine Telko diesen Freitag machen, mein Bekannter ist dann hier in der Kanzlei zugegen...Projekt: http://justizadressen.info/

**Comment by j-dimension** [comment]
https://justiz.de/index.php

**Comment by j-dimension** [comment]
Wird nun aus dem beA geladen.

**Comment by PBaumfalk** [comment]
Habe ich gesehen. Super!

Mit freundlichen Grüßen / Kindly Regards

Patrick Baumfalk
Rechtsanwalt / Lawyer


Mobil:    +49 1525 53 04 194
E-Mail:   patrick.baumfalk@kanzlei-baumfalk.de


Baumfalk - Rechtsanwaltskanzlei
Hauptstr. 195
50169 Kerpen

Tel.: +49 2273 40 68 504
Fax: +49 2273 59 03 565

E-Mail: info@kanzlei-baumfalk.de
Web: www.kanzlei-baumfalk.de

Sent by Mobile
