### ISSUE TITLE
[BUG] Kalender, Termin wird immer um 10 Uhr angelegt auch wenn andere Zeit gewählt/angeklickt

### ISSUE THREAD

**Issue by iradraconis** [jlawyerorg/j-lawyer-org#1773]
(Bitte nicht steinigen, falls es das Ticket schon gibt, ich habe es jedenfalls nicht gefunden)

Siehe Screenshots. Möchte man einen Termin eintragen, springt die Eingabemaske direkt auf eine Wiedervorlage, und übernimmt direkt die angeklickte Uhrzeit. Wähle ich dann aber Termin aus, wird immer 10 Uhr als Startzeit gewählt. Es wäre toll, wenn direkt ein Bereich (halbe Stunde bei einfachem Klick oder beim Ziehen eines Termins) wie ausgewählt als Terminszeit vormarkiert wäre. Beispiel: ich ziehe Termin von 10 bis 12 und diese Zeiten werden dann übernommen.

EDIT: ich wollte im LiveSystem schauen, ob es dort noch so ist, da gelingt die Anmeldung leider nicht. Da kommt eine Fehlermeldung.

![Bildschirmfoto 2022-10-04 um 14 59 06](https://user-images.githubusercontent.com/71747937/193825611-e59514e9-559e-48b4-9ca7-2d2a58e3825c.png)
![Bildschirmfoto 2022-10-04 um 14 59 14](https://user-images.githubusercontent.com/71747937/193825622-75af4e02-6c23-4bd4-ba26-2be8c69b0e2e.png)
![Bildschirmfoto 2022-10-04 um 14 59 19](https://user-images.githubusercontent.com/71747937/193825628-6d40c870-a396-4500-9bb1-8977ece5ead4.png)

**Comment by iradraconis** [comment]
> Wenn man mit der Maus "zieht" ist "Termin" voreingestellt, mit der ausgewählten Zeit.
> 
> Die einzige "Lücke" die ich sehe: will man einen <=30min-Termin, so wird das als WV gewertet, der Dialog öffnet mit WV als Voreinstellung, aber mit der geklickten Zeit. Wechselt man dann auf Termin, werden die Zeiten zurückgesetzt. Ist es das was Du meinst?

ähm, ja genau :)

**Comment by j-dimension** [comment]
Livesystem ist repariert.

**Comment by j-dimension** [comment]
In der Tat ein Duplikat von #1623
