### ISSUE TITLE
[TASK] Microsoft Exchance Basic Authentication eingestellt

### ISSUE THREAD

**Issue by Linkki2021** [jlawyerorg/j-lawyer-org#1776]
Microsoft hat zu Oktober die reguläre Basic Authentication eingestellt. Das betrifft ebenfalls IMAP, Zusatzinfos untenstehend.

Gibt es hier Implikationen für j-lawyer?

"https://learn.microsoft.com/de-de/exchange/troubleshoot/administration/cannot-connect-mailbox-pop-imap-outlook

Gemäß der Aussage von Microsoft ist es in Outlook nicht mehr möglich eine Verbindung via POP3 / IMAP aufzubauen:

"Es ist nicht geplant, dass Outlook-Clients OAuth für POP und IMAP unterstützen, aber Outlook kann sich über MAPI/HTTP (Windows-Clients) und EWS (Outlook für Mac) verbinden."

Bei dem Konto handelt es sich um ein vollwertiges Exchange Konto, sodass Sie hier eine Verbindung via Mapi aufbauen können. 
Sofern Sie weiterhin Imap verwenden möchten, wäre es notwendig, auf ein anderes Programm auszuweichen und dieses gemäß folgenden Microsoft Artikels in Betrieb zu nehmen:

https://learn.microsoft.com/de-de/exchange/client-developer/legacy-protocols/how-to-authenticate-an-imap-pop-smtp-application-by-using-oauth"

**Comment by j-dimension** [comment]
Das ist leider ein richtig dickes Brett, und das völlig ohne Not. IMAP und SMTP sind praktisch Standards, und eine Basic Auth mit Verschlüsselung ist sicher. Das Thema ist bereits unter #1470 erfasst.
