### ISSUE TITLE
[FEATURE] alternativer XJustiz-Viewer

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#1777]
Ich weiß ja nicht, wie es mit der Kooperation mit dem XJustiz-Viewer von Uwe Möller nach dieser Ankündigung https://ervjustiz.de/neue-version-4-des-xjustiz-aktenviewers weitergeht, aber hier mal eine Alternative, die man sich mal angucken könnte. Das Abspeichern als Komplett-pdf scheint es (noch) nicht zu haben:

https://openxjv.de/

**Comment by j-dimension** [comment]
Dup von #1200
