### ISSUE TITLE
Vergangene Termine ansehen

### ISSUE THREAD

**Issue by hackvokat** [jlawyerorg/j-lawyer-org#1778]
Hallo,

gibt es eine Möglichkeit, um vergangene Termine anzusehen?
Aus dem Kalender in j-lawyer und nextcloud fliegen die Termine nach Erledigung raus.

Kann ich irgendwie die Termine letzter Woche ansehen?

Danke.

**Comment by iradraconis** [comment]
in der tabellarischen Ansicht sollte das gehen

**Comment by hackvokat** [comment]
> in der tabellarischen Ansicht sollte das gehen

Da werden auch nur die zukünftigen angezeigt.

**Comment by iradraconis** [comment]
auf Kalender SUCHE und da entsprechend filtern

**Comment by j-dimension** [comment]
Via #1655 wird man in Kürze die erledigten Kalendereinträge auch in Nextcloud belassen können. 

Danke @iradraconis  für die Unterstützung hier im Ticketsystem :-)
