### ISSUE TITLE
Run server as non-root

### ISSUE THREAD

**Issue by malteos** [jlawyerorg/j-lawyer-org#178]
Um j-lawyer nicht nur auf einem abgetrennten Server nutzen zu können, sollte es auch möglich sein ihn als non-root laufen zu lassen.

Insbesondere hätte ich große Sicherheitsbedenken ein +100MB Install Script als root auszuführen, wenn noch andere wichtige Dinge auf dem Server laufen. Gleiches gilt für den MySQL Rootzugang.

**Comment by j-dimension** [comment]
Der Installer muss als root laufen, nicht aber der installierte Dienst. Wenn man bei Installation für "automatischen Start als Dienst" wählt, wird ein eigener Nutzer j-lawyer-server angelegt, unter welchem der Dienst läuft. 

Wenn man manuell starten möchte, dann kann und sollte man trotzdem einen dedizierten Nutzer nehmen, das ist in der Installationsanleitung beschrieben:
https://www.j-lawyer.org/?page_id=93

```
sudo mkdir -p /var/log/j-lawyer-server
sudo useradd --system j-lawyer-server
sudo chown -R j-lawyer-server:j-lawyer-server /opt/j-lawyer-server
sudo chown -R j-lawyer-server:j-lawyer-server /var/log/j-lawyer-server
```

Anschliessend „sudo -u j-lawyer-server sh start-server.sh“ im Verzeichnis /opt/j-lawyer-server (oder anderes bei der Installation gewähltes Verzeichnis) ausführen, Herunterfahren durch Abbrechen des Prozesses mit Strg+C.

**Comment by j-dimension** [comment]
Gern wieder öffnen, wenn es noch Fragen gibt.
