### ISSUE TITLE
[BUG] macOS: Client friert ein bei PDF-Konversion mit LibreOffice 7.4ff

### ISSUE THREAD

**Issue by LazyGuy21No** [jlawyerorg/j-lawyer-org#1783]
~~LibreOffie 7.0 geht~~
Downgrade funktioniert ~~nicht~~ erst nach einem Neustart des Systems (?)

------------------------------------ @j-dimension 2024-06-05 -----------------------------

- [x] Test Intel
- [ ] Test Apple Silicon

**Comment by j-dimension** [comment]
Betrifft lt. User macOS.

**Comment by PBaumfalk** [comment]
Sachstand: 7.4 führt zum Einfrieren des Clients. Downgrade auf 7.3. funktioniert nicht. Beide Versionen ausprobiert. Sowohl Intel als auch die M-Variante von LibreOffice. Der Client friert vollständig ein.

**Comment by j-dimension** [comment]
@PBaumfalk geht die vom Client automatisch heruntergeladene Variante?

**Comment by j-dimension** [comment]
https://www.j-lawyer.org/downloads/installer-3rdparty/LibreOffice_7.1.2_MacOS_x86-64.dmg
https://www.j-lawyer.org/downloads/installer-3rdparty/LibreOffice_7.1.2_MacOS_x86-64_langpack_de.dmg

**Comment by PBaumfalk** [comment]
Ich probiere nochmal 7.12

**Comment by PBaumfalk** [comment]
> https://www.j-lawyer.org/downloads/installer-3rdparty/LibreOffice_7.1.2_MacOS_x86-64.dmg
> https://www.j-lawyer.org/downloads/installer-3rdparty/LibreOffice_7.1.2_MacOS_x86-64_langpack_de.dmg

Mit 7.1.2 funktioniert es augenscheinlich.

**Comment by j-dimension** [comment]
Okay, werde schauen was danach im LibreOffice-Code geändert wurde (bzgl. der Konvertierung).

**Comment by LazyGuy21No** [comment]
7.0.6.2. geht aktuell auch

**Comment by LazyGuy21No** [comment]
Jetzt geht auch 7.4; keine Ahnung, was das war. Ticket kann geschlossen werden.

**Comment by j-dimension** [comment]
`/Applications/LibreOffice.app/Contents/MacOS/soffice --headless --convert-to pdf:"writer_pdf_Export:SelectPdfVersion=1" /Users/jens/Downloads/2022-11-15_j-lawyer.odt`

--outdir (optional)

**Comment by j-dimension** [comment]
Ich habe bisher LO 7.2.7.2 verwendet auf Intel-Mac, das lief ohne Probleme. 

Mit LO 7.4.2.3 hängt ca. jede vierte PDF-Konvertierung. Schließt man LO dann manuell ("Sofort beenden"), kann man auch im j-lawyer Client weiterarbeiten. 

Es gibt in 7.4 einige Änderungen an der Kommandozeilen-API von LibreOffice, ich werde das mal ausprobieren. Interessanterweise kann man darüber jetzt auch stempeln.

**Comment by LazyGuy21No** [comment]
Ich habe es jetzt noch mal 2 Tage probiert und erhalte ein ähnliches Bild wie @j-dimension: etwa jedes 4. oder 5. mal hängt sich LO auf

**Comment by librelegal** [comment]
besteht das Problem noch mit der aktuellen Version 7.4.4? https://blog.documentfoundation.org/blog/2023/01/12/libreoffice-7-4-4-community/

**Comment by j-dimension** [comment]
Schon jemand Erfahrungen mit LO 7.5 auf'm Mac?

**Comment by librelegal** [comment]
besteht das Problem noch mit der aktuellen Version  7.6?
https://blog.documentfoundation.org/blog/2023/09/14/libreoffice-7-6-1/

**Comment by LazyGuy21No** [comment]
Ja, das Problem besteht noch

**Comment by j-dimension** [comment]
Konvertierung auf macOS nun mittels direktem CLI-Call ohne unoconv. Test Intel erfolgreich, Test Apple Silicon steht noch aus.

**Comment by librelegal** [comment]
Wunderbar, dass der issue offenbar gefixt wurde. Ich weiß, dass dies zunächst nur Intel betrifft und Apple Silicon noch aussteht, aber konnten schon erfolgreiche Tests mit der aktuellen Version 24.2.4 von LibreOffice [https://www.libreoffice.org/download/download-libreoffice/](url) durchgeführt werden? Auch vom bug reporter?

**Comment by LazyGuy21No** [comment]
Teste es gern auf Silicone (bin mir aber quasi sicher, dass der cli-Aufruf dort exakt genauso funktionieren wird)
