### ISSUE TITLE
[FEATURE] Log-Report erstellen über Hauptmenü

### ISSUE THREAD

**Issue by LazyGuy21No** [jlawyerorg/j-lawyer-org#1784]
Über Administration -> Administrator-Konsole Dateien erstellen können mit den Logs des Servers bzw. des Clients, um sie an den Support schicken zu können.

**Comment by Linkki2021** [comment]
Für uns ist das auch interessant. Ebenso wäre ein Live-View der Server Log im Client spannend.

**Comment by j-dimension** [comment]
![grafik](https://github.com/jlawyerorg/j-lawyer-org/assets/3729754/a9e36750-a487-4afa-a8f1-ef3f7fb6b8c9)

**Comment by j-dimension** [comment]
![grafik](https://github.com/jlawyerorg/j-lawyer-org/assets/3729754/6e1aa412-085f-42a5-8992-70d3c634627e)

**Comment by j-dimension** [comment]
Funktionsumfang:

- Systeminformationen Client und Server anzeigen
- Log des Servers anzeigen
- Log des Clients anzeigen
- Logs des Servers live "durchlaufen" lassen
- Logs des Clients live "durchlaufen" lassen
- Bericht lokal speichern (als ZIP)
- Bericht per E-Mail versenden (sofern der aufrufende Nutzer ein Mailkonto konfiguriert hat)

**Comment by Dickmaulruessler** [comment]
Wenn man es sich selbst angucken möchte: Kann man nach dem "Durchlaufen" nach oben scrollen oder empfiehlt sich dann die gespeicherte Datei zu entpacken und dann zu betrachten?

**Comment by j-dimension** [comment]
Man kann und darf gern nach oben scrollen :-)

Die Anzahl der Zeilen lässt sich ebenfalls einstellen.

**Comment by LazyGuy21No** [comment]
Loving it already!
