### ISSUE TITLE
[e-mail] Datei aus Thunderbird droppen führt zu Client-Freeze

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-org#1786]
Wenn ich eine Datei per Drag and Drop (Konkret eine e-mail aus Thunderbird) in den Dokumentenordner verschieben will und die Datei versehentlich nicht im geöffneten Dokumentenbereich einer Akte droppe, friert der Client ein., dann hilft nur den Task abzuschießen und J-lawyer neu zu starten. Besser wäre, es geschähe einfach nichts. 

**NOTE: Please search existing tickets to avoid duplicates **
**HINWEIS: Bitte vorab die Ticketsuche verwenden, um Doppeleinträge zu vermeiden **

**Describe the bug / Fehlerbeschreibung**
(todo: a description of the bug / eine Beschreibung des Fehlers)

**To Reproduce / Schritte zum Nachvollziehen**

1. Go to / Gehe zu '...'
2. Klicke auf / Click on '....'
4. Error message / Fehlermeldung: '...'

**Expected behavior / Erwartetes Verhalten**
Eine Beschreibung des erwarteten Verhaltens.

**Screenshots**
Falls relevant, Screenshot beifügen.

**Environment / verwendete Umgebung:**
 - OS / Betriebssystem:
 - j-lawyer.org Version:

**Additional context / Sonstiges**

**Comment by j-dimension** [comment]
@Mucki526 was heißt "versehentlich nicht im geöffneten Dokumentenbereich einer Akte droppe"
Wo wird denn gedroppt? 

Und welches Betriebssystem wird genutzt?

**Comment by Mucki526** [comment]
Das bin ich noch am reproduzieren. was ich heute zum zweiten Mal gemerkt habe - Wenn ich eine Thunderbird-mail mit mehreren Anlagen ins J-lawyer kopiere und die Anlagen nicht einzeln sondern mehrere im Block aus der mail extrahiere (einfach speichern aus der Vorschau), dann funktioniert das scheinbar, die Vorschau des extrahierten PDF wird angezeigt, aber beim Öffnen gibt es einen Fehler. Das ist kurios. Ich versuche das zu reproduzieren.
