### ISSUE TITLE
[BUG] Kopieren bei RVG-Rechner ignoriert Tabellenformatierung

### ISSUE THREAD

**Issue by socram70** [jlawyerorg/j-lawyer-org#1790]
**NOTE: Please search existing tickets to avoid duplicates **
**HINWEIS: Bitte vorab die Ticketsuche verwenden, um Doppeleinträge zu vermeiden **

**Describe the bug / Fehlerbeschreibung**
(todo: a description of the bug / eine Beschreibung des Fehlers)

**To Reproduce / Schritte zum Nachvollziehen**
Beim Klick auf "Kopieren" beim RVG-Rechner werden die Tabelleneinstellungen ignoriert und es wird immer 7pt als Schriftgröße gewählt. Anders als bei dem Klick auf "Dokument erstellen" wird hier die Tabelle auch nicht über die gesamte Breite (z. B. bei Blocksatz sieht das m. M. n. besser aus) erstellt.

**Expected behavior / Erwartetes Verhalten**
Die Formatierung wird aus den Einstellungen übernommen - insbesondere die Schriftgröße.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/60073801/199040320-7cee501e-f631-4569-8dee-46ac5d67f6b0.png)

**Environment / verwendete Umgebung:**
 - OS / Betriebssystem: Windows 10 und 11 x64
 - j-lawyer.org Version: 2.2.0.0 (Client)

**Additional context / Sonstiges**

**Comment by j-dimension** [comment]
Duplikat von https://github.com/jlawyerorg/j-lawyer-calculations/issues/151
