### ISSUE TITLE
Scan - Akte suchen und Zuordnen (nicht nur Büroklammer)

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-org#1791]
Erst mal danke für die neue Version und die ganze Arbeit. Ich bin noch am erkunden... Die Scanfunktionalität ist stark verbessert. Eine kleine Verbesserung als Vorschlag: Wenn man den Button anklickt "Akte suchen und Zuornen" funktioniert das nur beim Klick auf die Büroklammern, nicht auf das Textfeld darüber. Wenn man hingegen eine angezeigte vorgeschlagene Akte auswählt funktioniert das sowohl mit der Büroklammer als auch mit dem Textfeld darüber. Das fühte bei meiner Frau zur irrigen Meinung, dass der obere Button (Ordner auswählen und zuordnen) nicht funktioniert. (doch, aber nur über die Büroklammer)

**Comment by j-dimension** [comment]
> Wenn man hingegen eine angezeigte vorgeschlagene Akte auswählt funktioniert das sowohl mit der Büroklammer als auch mit dem Textfeld darüber.

Nein, das tut es nicht. Hast Du es mal geklickt? Es navigiert zur Akte, ordnet aber gar nichts zu.

Oder verstehe ich Dich falsch?

**Comment by Mucki526** [comment]
Richtig, das habe ich dann gemerkt. Dann wäre mein Vorschlag, dass "Ordner suchen und zuordnen" die gleiche Funktonalität hat wie seine Büroklammer.... . Kann man sicher kontrovers denken. Für den "DAU" ists vermutlich sicherer, wenn es egal ist worauf er klickt ob auf Ordner suchen... oder Büroklammer.

**Comment by Dickmaulruessler** [comment]
> Dann wäre mein Vorschlag, dass "Ordner suchen und zuordnen" die gleiche Funktonalität hat wie seine Büroklammer....

Das würed ich auch so sehen. Zumal der Text "Ordner suchen und zuordnen" beim Hoovern zu Blau wechselt, also eigentlich eine Funktion signalisiert.

Ich Pingel erlaube mir dann noch die folgende Anmerkung: Im Kontextmenü heißt es "zur Akte speichern", in der rechten Spalte aber eben "Ordner suchen und zuordnen". Ich finde letzteres besser.
