### ISSUE TITLE
PDF an vom Nutzer bestimmten Stellen aufteilen

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-org#1792]
Die PDF-Funktionalität Aufteilen ist ein guter Einstieg in die Sache die für die elektronische Akte lebensnotwendig ist, aber noch etwas "sperrig" zu handhaben.  Wie wäre es, wenn man das gescannte Dokument über die Vorschau durchblättern kann und - wenn man an einer Stelle eine Trennung will, einen Button hat, der vor der in der Vorschau angezeigten Seite den "Cut" macht und zwei PDF-Dateien aus einer erzeugt.  Die automatische Aufteilung des Dokuments einfach in Stücke von x identischen Seiten wird man so gut wie nie brauchen. Die Aufteilung über eine leere Seite funktioniert z.B. nicht, wenn der Scanner wie bei uns beim Duplexscannen automatisch die weißen Seiten löscht. Die Markierung mit einem Kennwort auf einer leeren Seite (OCR) setzt voraus, dass man eine entsprechende Seite einfügt (ist bei großen Stapeln mühseelig).

**Comment by j-dimension** [comment]
> Die automatische Aufteilung des Dokuments einfach in Stücke von x identischen Seiten wird man so gut wie nie brauchen.

Doch. Große PDFs können so handhabbar gemacht werden.

**Comment by j-dimension** [comment]
> Die Aufteilung über eine leere Seite funktioniert z.B. nicht, wenn der Scanner wie bei uns beim Duplexscannen automatisch die weißen Seiten löscht.

Drucker anders einstellen?

**Comment by j-dimension** [comment]
> Die Markierung mit einem Kennwort auf einer leeren Seite (OCR) setzt voraus, dass man eine entsprechende Seite einfügt

Primärer Anwendungsfall ist hier das Scannen der Eingangspost.
