### ISSUE TITLE
PDF splitten / zusammenführen in der Akte

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-org#1794]
Die im Scaneingang Einzug haltende Scan-Trenn-Funktionalität wäre auch im Dokumentenordner sinnvoll (Aufteilen des PDF im Dokumentenordner. Die Mandanten schicken gerne ein 10-seitige Dokument in 10 jpg oder 10 einzelnen PDF (und zeigen sich da beratungsresistent oder hilflos es mit einer App anders zu machen)

**Is your feature request related to a problem? Please describe. / Welches Problem soll durch die Erweiterung / Verbesserung gelöst werden?**
Description / Beschreibung

**Describe the solution you'd like / Beschreibe die gewünschte Lösung**
Description / Beschreibung

**Additional context / Sonstiges **
Sonstige Informationen / Screenshots / ...

**Comment by LazyGuy21No** [comment]
Dazu könnten die Issues #74 und #1338 (nachträgliches OCR mit tesseract) passen?

**Comment by iradraconis** [comment]
Kann mich dem Wunsch nach dieser Erweiterung nur anschließen. 
Der bisherige Umweg läuft über einen Export aus der Akte, zusammenführen der PDF und anschließenden Import.
