### ISSUE TITLE
[FEATURE] [beA] Sendungspriorität einstellen

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#1796]
Mit der aktuellen beA-Version können Nachrichten in der beA-Webanwendung an beA-externe Nachrichtenempfänger (z.B. an Gerichte und Staatsanwaltschaften) mit einer Sendungspriorität übermittelt werden.

In dem Datenfeld Sendungspriorität kann entweder ein Bereitschaftsdienst der Justiz oder allgemein „Eilt“ angegeben werden.

siehe auch https://newsletter.brak.de/mailing/186/5936165/0/e251c4f243/index.html

Da es in der Schnittstelle von RA Micro schon umgesetzt sein soll, scheint die BRAK hier ausnahmsweise mal die KSW-API nicht benachteiligt zu haben.

**Comment by LazyGuy21No** [comment]
Tolles Ticket!

**Comment by j-dimension** [comment]
@stm9x9 das scheint einfach ein Feld im XJustiz-SDS zu sein. Ich habe recherchiert und konnte diese Werteliste finden:

https://www.xrepository.de/api/xrepository/urn:xoev-de:xjustiz:codeliste:gds.sendungsprioritaet_1.1:technischerBestandteilGenericode

Kannst Du im beA (produktiv) schauen ob Du diese Werte dort wiederfindest?

**Comment by stm9x9** [comment]
ja, sieht so aus wie im Dropdownfenster

**Comment by stm9x9** [comment]
So sieht das übrigens im Web aus:

![image](https://github.com/jlawyerorg/j-lawyer-org/assets/29924198/009356df-a6e6-4ba4-9e51-b35aa9e18554)

**Comment by j-dimension** [comment]
@LazyGuy21No @stm9x9 wie wichtig ist dieses Ticket? Hat die Auswahl denn irgendeine konkrete Auswirkung auf den Posteingangsprozess in der Justiz?

**Comment by stm9x9** [comment]
Soweit mir bekannt, wird damit - zumindest bei den forschrittlicheren Gerichten - eben die Bearbeitung durch Poststelle und Geschäftsstelle beschleunigt bei Eilanträgen etc. Oder wenn ich am Abend vor einem Gerichtstermin noch was einreiche oder wegen Krankheit um Abladung bitte und so. Also IMHO wichtig.

**Comment by iradraconis** [comment]
Sehr wichtiges Ticket!! Bei normalem Versand kann es passieren, dass das per beA versandte Schreiben der zuständigen Stelle erst einige Tage später "vorgelegt" (weil gedruckt) wird. Wenn der Bereitschaftsdienst direkt erreichbar ist, gleicht das einer "Fax-Durchwahl".

**Comment by j-dimension** [comment]
<!DOCTYPE html>

<html>
<head>
	
	
	<title></title>
	<meta name="generator" content="LibreOffice 7.3.7.2 (Linux)"/>
	<style type="text/css">
		body,div,table,thead,tbody,tfoot,tr,th,td,p { font-family:"Liberation Sans"; font-size:x-small }
		a.comment-indicator:hover + comment { background:#ffd; position:absolute; display:block; border:1px solid black; padding:0.5em;  } 
		a.comment-indicator { background:red; display:inline-block; border:1px solid black; width:0.5em; height:0.5em;  } 
		comment { display:none;  } 
	</style>
	
</head>

<body>

Spaltenname (lang) | Schlüssel | Wert
-- | -- | --
Spaltenname (technisch) | code | wert
Datentyp | string | string
Codespalte | true | false
Verwendung | required | required
Empfohlene Code-Spalte | true | false
Sprache |   |  
Daten |   |  
  | 001 | Eilt
  | 100 | Gerichtlicher Bereitschaftsdienst Betreuungssachen
  | 101 | Gerichtlicher Bereitschaftsdienst Familiensachen
  | 102 | Gerichtlicher Bereitschaftsdienst Insolvenzsachen
  | 103 | Gerichtlicher Bereitschaftsdienst Nachlasssachen
  | 104 | Gerichtlicher Bereitschaftsdienst Unterbringungssachen (zivilrechtlich)
  | 105 | Gerichtlicher Bereitschaftsdienst Wohnungseigentumssachen
  | 106 | Gerichtlicher Bereitschaftsdienst Zwangsvollstreckungssachen
  | 125 | Gerichtlicher Bereitschaftsdienst sonstige Zivilsachen
  | 126 | Gerichtlicher Bereitschaftsdienst Haftsachen (Abschiebung/Auslieferung)
  | 127 | Gerichtlicher Bereitschaftsdienst Gefahrenabwehr (Polizei- und Sicherheitsrecht)
  | 128 | Gerichtlicher Bereitschaftsdienst Unterbringungs-/Freiheitsentziehungssachen (öffentlich-rechtlich)
  | 129 | Gerichtlicher Bereitschaftsdienst Fixierungen (öffentlich-rechtlich)
  | 151 | Gerichtlicher Bereitschaftsdienst Ermittlungsrichterliche Maßnahmen (Erwachsene)
  | 152 | Gerichtlicher Bereitschaftsdienst Ermittlungsrichterliche Maßnahmen (Jugendliche und Heranwachsende)
  | 153 | Gerichtlicher Bereitschaftsdienst Haftrichterliche Maßnahmen (Erwachsene)
  | 154 | Gerichtlicher Bereitschaftsdienst Haftrichterliche Maßnahmen (Jugendliche und Heranwachsende)
  | 155 | Gerichtlicher Bereitschaftsdienst Jugendstrafsachen
  | 175 | Gerichtlicher Bereitschaftsdienst sonstige Strafsachen
  | 199 | allgemeiner gerichtlicher Bereitschaftsdienst
  | 200 | Staatsanwaltschaftlicher Bereitschaftsdienst Fußballsachen
  | 201 | Staatsanwaltschaftlicher Bereitschaftsdienst Haftsachen
  | 202 | Staatsanwaltschaftlicher Bereitschaftsdienst Internetkriminalität
  | 203 | Staatsanwaltschaftlicher Bereitschaftsdienst Kapitalsachen
  | 204 | Staatsanwaltschaftlicher Bereitschaftsdienst organisierte Kriminalität
  | 205 | Staatsanwaltschaftlicher Bereitschaftsdienst Pressebereitschaftsdienst
  | 206 | Staatsanwaltschaftlicher Bereitschaftsdienst Rotlichtkriminalität
  | 207 | Staatsanwaltschaftlicher Bereitschaftsdienst Staatsschutz- und sonstige politisch motivierte Strafsachen
  | 208 | Staatsanwaltschaftlicher Bereitschaftsdienst Verkehrssachen
  | 209 | Staatsanwaltschaftlicher Bereitschaftsdienst Vorführbereitschaftsdienst
  | 297 | allgemeiner staatsanwaltschaftlicher Bereitschaftsdienst
  | 298 | allgemeiner amtsanwaltschaftlicher Bereitschaftsdienst
  | 299 | allgemeiner Rechtspflegerbereitschaftsdienst


</body>

</html>

**Comment by j-dimension** [comment]
Sehr merkwürdig! Wählt man im Browser-beA "Eilt" als Priorität, so passiert rein gar nichts! Die Nachricht sieht exakt so aus, als würde sie ohne Prioritätsangabe verschickt. Nur wenn man einen der anderen Werte wählt, entsteht eine zusätzliche Zeile im XJustiz-SDS.

Frage mich, wieviele User hier eifrig "Eilt" nutzen und dann denken, das würde irgendetwas bewirken.

**Comment by j-dimension** [comment]
![grafik](https://github.com/jlawyerorg/j-lawyer-org/assets/3729754/bc1e1f03-fb75-4be4-957d-cf50c3944599)

**Comment by stm9x9** [comment]
> Sehr merkwürdig! Wählt man im Browser-beA "Eilt" als Priorität, so passiert rein gar nichts! Die Nachricht sieht exakt so aus, als würde sie ohne Prioritätsangabe verschickt. Nur wenn man einen der anderen Werte wählt, entsteht eine zusätzliche Zeile im XJustiz-SDS.
> 
> Frage mich, wieviele User hier eifrig "Eilt" nutzen und dann denken, das würde irgendetwas bewirken.

hm ... 
![image](https://github.com/jlawyerorg/j-lawyer-org/assets/29924198/4e3be4a8-1a76-44c9-afd4-c949edc555fc)

**Comment by LazyGuy21No** [comment]
Für "meine" eilt Sachen, ist da aktuell eh nix dabei.

**Comment by stm9x9** [comment]
> Für "meine" eilt Sachen, ist da aktuell eh nix dabei.

naja, außer halt "eilt" :)

**Comment by j-dimension** [comment]
Das vermute ich auch. Code 001 ist an der Stelle richtig.
