### ISSUE TITLE
[FEATURE] lokal speichern als PDF: PDFs einfach kopieren, nicht konvertierbare als Hinweis ausgeben und im Original speichern

### ISSUE THREAD

**Issue by LazyGuy21No** [jlawyerorg/j-lawyer-org#1799]
Ich finde die Funktion Schnelldruck extrem handlich. Ich stelle so z.B. meine Papierakten zusammen, wenn ich um Termin gehe. Blöd allerdings ist, dass ich nicht wirklich einen Einfluss darauf habe, auf welchem System (und mit welchen Druck-Optionen) gedruckt wird.

Wir wünschen uns dafür ein Batch-Print-System, bei dem die zu druckenden Datei lediglich als PDFs in ein vorher gewähltes Ziel-Verzeichnis abgelegt werden. Um alles weitere kümmert sich dann ein Shell-Skript. 

Toll wäre, wenn sich über **Einstellungen** (also auf Nutzer:innen-Ebene) eine Möglichkeit gäbe, festzulegen, was passiert, wenn die Nutzerin Schnelldruck ("drucken (Standarddrucker)") wählt:

"Auf Standarddrucker ausgeben via PDFBox"
"Batch-Print (Ablegen als Datei in ein überwachtes Verzeichnis)"

Bei Batch-Print kann dann noch der Verzeichnis-Pfad ausgewählt werden.

Der Schnell-Druck selbst erfolgt dann wie bisher über das Kontext-Menü für eine oder mehrere Dateien.

**Comment by j-dimension** [comment]
@LazyGuy21No wäre das aber nicht schon ganz nah an der vorhandenen Option "lokal speichern als PDF"? Das einzige was dort noch fehlt, wäre eine Intelligenz iSv "oh, ist ja schon ein PDF, dann kopiere ich nur".

**Comment by LazyGuy21No** [comment]
stimmt! Daran hatte ich nicht gedacht

**Comment by iradraconis** [comment]
Ich glaube für Emails funktioniert das Ablegen als pdf leider bisher nicht, oder?

**Comment by j-dimension** [comment]
> Ich glaube für Emails funktioniert das Ablegen als pdf leider bisher nicht, oder?

Nein, das wäre #146 . Hab das jetzt mal in die 2.3 gezogen, ohne einschätzen zu können wieviel Aufwand das ist.

**Comment by j-dimension** [comment]
> stimmt! Daran hatte ich nicht gedacht

Okay, dann würde ich den Titel dieses Ticket hier etwas schärfen.
