### ISSUE TITLE
[FEATURE] Versand über E-POST BusinessBox (API)

### ISSUE THREAD

**Issue by LazyGuy21No** [jlawyerorg/j-lawyer-org#1800]
Die DPAG stellt eine Rest-API für die Nutzung des E-Post-Systems bereit. Über diese scheint ein großer Teil des Leistungsspektrums (inkl. Einschreiben) ansprechbar zu sein.

https://api.epost.docuguide.com/faq

Eine Einbindung ähnlich der Fax-Versand-Funktion wäre toll!

**Comment by j-dimension** [comment]
Duplikat von #54 (da sind auch noch andere Anbieter genannt)

**Comment by hackvokat** [comment]
Ich versende auch über EPOST und lade die PDFs auf einen FTP-Server der Post hoch.
Dort kann man verschiedene Versandarten festlegen, z.B. duplex in Farbe und für jede Versandart gibt es einen Ordner in dem FTP-Server-Verzeichnis. D.h. ein einfacher FTP-Upload mit Auswahl der dort vorhandenen Server wäre möglich.

Bei mir sieht das so aus:
![Bildschirm­foto 2022-11-04 um 11 16 53](https://user-images.githubusercontent.com/98764663/199949112-7dd9dd95-6a2c-47cb-9ab5-b135b7230bba.png)

**Comment by LazyGuy21No** [comment]
Nutzt Du die E-Post BusinessBox oder laden Deine MA direkt auf den PostServer hoch?  (E-Post BusinessBox ist IMHO ein bekloppter Name)

**Comment by hackvokat** [comment]
Ohne BusinessBox, ich will alles an extra-Gerätschaften vermeiden.

Ich habe den E-POSt-Server einfach als Laufwerk eingebunden, dann muss man nur die PDF-Datei rüberschieben und fertig. Dauert nicht mal eine Sekunde, ist wirklich super. Briefe sind meistens am nächsten Tag schon zugestellt.

**Comment by LazyGuy21No** [comment]
Hey,

Ich danke Dir herzlich für den Tipp und hoffe ich darf Dich jetzt (Fluch der guten Tat) nochmal stören: 

Wir haben die FirmenID und die E-Mail-Adrese, die woher kommst Du den *Benutzernamen für den Mailer*? (Die Post antwortet nicht aus unsere Anfragen).

Liebe Grüße,

Guido

**Comment by hackvokat** [comment]
Hallo,

das ist alles nicht so leicht zu finden. Es gibt eine PDF-Dokumentation, wo alles erklärt ist.

WebDav HTTPS (Port 443) mailer-webdav.epost.de
Benutzer ist benutzer.name@kdFirmenid (z.B. hans.wurst@kd34223413).

Grüße

**Comment by j-dimension** [comment]
Gelöst via #54
