### ISSUE TITLE
PDF öffnen drag and drop aus Dokumentenordner

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-org#1804]
Ich arbeite inzwischen (versuche es) mit rein elektronischer Akte, an einem Bildschirm (geteilte Ansicht, windoof 10).  vielleicht wäre es möglich, einfach die Datei nicht per Doppelklick zu öffnen, sondern einfach per Drag und Drop (hier - Foxitreader) im Moment wird zwar das Dokument und die Hand angezeigt, aber beim Drop öffnet es  sich leider nicht. 

**NOTE: Please search existing tickets to avoid duplicates **
**HINWEIS: Bitte vorab die Ticketsuche verwenden, um Doppeleinträge zu vermeiden **

**Is your feature request related to a problem? Please describe. / Welches Problem soll durch die Erweiterung / Verbesserung gelöst werden?**
Description / Beschreibung

**Describe the solution you'd like / Beschreibe die gewünschte Lösung**
Description / Beschreibung

**Additional context / Sonstiges **
Sonstige Informationen / Screenshots / ...

**Comment by j-dimension** [comment]
Du willst das Dokument wohin genau ziehen?

**Comment by Mucki526** [comment]
Evt. habe ich hier ein Question-Tag übersehen? Sorry...
Ich nehme einDokument pdf aus der Dateiliste und ziehe es(linke Taste an der Maus gedrückt, hält die Datei fest) rüber zum offenen Foxitreader (in dem z.B. bereits ein Dokument offen ist).  Bei Drag and Drop öffnet sich beim loslassen der linken Taste eigentlich die Datei oder wird dorthin kopiert. hier sieht man das Symbol für das Dokument, die Hand, die das Dokument hält und wenn man loslässt, dann passiert - nichts. Daher mein Hinweis.

**Comment by j-dimension** [comment]
Danke, dann ist es ein Duplikat von #1218
