### ISSUE TITLE
PDF-Vorschau bei Fenstergrößenänderung

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-org#1805]
Wenn man das J-lawyer-Fenster verkleinert und dann wieder vergrößert,  bleibt die PDF vorschau horizontal klein.

**NOTE: Please search existing tickets to avoid duplicates **
**HINWEIS: Bitte vorab die Ticketsuche verwenden, um Doppeleinträge zu vermeiden **

**Describe the bug / Fehlerbeschreibung**
(todo: a description of the bug / eine Beschreibung des Fehlers)

**To Reproduce / Schritte zum Nachvollziehen**

1. Go to / Gehe zu '...'
2. Klicke auf / Click on '....'
4. Error message / Fehlermeldung: '...'

**Expected behavior / Erwartetes Verhalten**
Eine Beschreibung des erwarteten Verhaltens.

**Screenshots**
Falls relevant, Screenshot beifügen.

**Environment / verwendete Umgebung:**
 - OS / Betriebssystem:
 - j-lawyer.org Version:

**Additional context / Sonstiges**

**Comment by j-dimension** [comment]
@Mucki526 hier nicht reproduzierbar. Bitte ein Bildschirmvideo liefern oder genauer beschreiben.

**Comment by Mucki526** [comment]
Lieber Jens, kannst Du bitte das Foto hier sofort löschen (ich versuche es selbst, da es versehentlich kundendaten enthält.... Ein Kollege hat mich darauf hingewiesen....

**Comment by Mucki526** [comment]
Oh ich glaube ich habes geschafft es rauszunehmen..... bitte auch in evt. Backups löschen, falls erforderlich (blöd von mir, ich habe nicht daran gedacht, als ich den screenshoot gemacht habe...

**Comment by Dickmaulruessler** [comment]
Lieber @Mucki526 auch ich würde dich gerne auf etwas hinweisen. 
Kannst du #1803  bitte _sofort_ lesen?

**Comment by j-dimension** [comment]
Ich schließe mangels Feedback.
