### ISSUE TITLE
Abspeichern von neuen Dokumenten - Fehler

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-org#1806]
Hängt vielleiht mit dem gemeldetem Login problem zusammen... Ich bin gerade eingeloggt. Dann kommt eine neue Nachricht. Die wird dann durch Aktualisieren runtergeladen und ich kann sogar die Dokumente im Anhang öffnen. Aber wenn ich es dann abspeichern will in der Akte geht es nicht. 

![grafik](https://user-images.githubusercontent.com/37142896/200774824-00442a94-e657-4f99-8b8d-8bdabad63934.png)

Es scheint aber so zu sein, dass die Nachricht doch in die Akte übernommen wird.

Denn wenn ich mich neu einlogge kommt die Nachricht wieder und kann jetzt gespeichert werden, meldet aber, sie existiert bereits in der Akte..

Hoffe das ist hilfreich bei der Fehlersuche...

**NOTE: Please search existing tickets to avoid duplicates **
**HINWEIS: Bitte vorab die Ticketsuche verwenden, um Doppeleinträge zu vermeiden **

**Describe the bug / Fehlerbeschreibung**
(todo: a description of the bug / eine Beschreibung des Fehlers)

**To Reproduce / Schritte zum Nachvollziehen**

1. Go to / Gehe zu '...'
2. Klicke auf / Click on '....'
4. Error message / Fehlermeldung: '...'

**Expected behavior / Erwartetes Verhalten**
Eine Beschreibung des erwarteten Verhaltens.

**Screenshots**
Falls relevant, Screenshot beifügen.

**Environment / verwendete Umgebung:**
 - OS / Betriebssystem:
 - j-lawyer.org Version:

**Additional context / Sonstiges**

**Comment by j-dimension** [comment]
1. welche Speichern-Variante wird genutzt?
2. ich benötige ein Client.log und server.log, direkt nach Auftreten des Fehlers. Danke!

**Comment by j-dimension** [comment]
Kann ohne client.log / server.log nicht helfen. Ich schließe hier und mache das Ticket gern wieder auf, wenn Logs da sind.
