### ISSUE TITLE
[BUG] Dialog Dokumenterstellung zu groß unter Debian+XFCE4

### ISSUE THREAD

**Issue by bmle17** [jlawyerorg/j-lawyer-org#1809]
### 
**Fehlerbeschreibung:**

Der Bildschirm "Dokumente erstellen" ist übergroß, sodass die Beteiligten nicht ausgewählt werden können und Dokumente nicht erstellt werden können, weil der Button außerhalb des angezeigten Fensters liegt. Vollbild oder bildschirmfüllende Einstellung nicht möglich.
(Arbeit mit mehreren Monitoren)

**To Reproduce / Schritte zum Nachvollziehen**

1. Go to / Gehe zur Akte
2. Klicke auf / Click on 'Dokumente' -> Erstellen
3. Fenster übergroß - nicht einstellbar

**Expected behavior / Erwartetes Verhalten**
Fenster in der Größe des verwendeten Bildschirms - oder jedenfalls so in einen anderen Bildschirm zu ziehen, dass die Reiter und die Schaltflächen zur Verfügung stehen.

**Screenshots**
[https://cloud.advobox.com/apps/files_sharing/publicpreview/XQqoi8oEYHR75yP?x=1920&y=551&a=true&file=Problem.jpg&scalingup=0](url)

**Environment / verwendete Umgebung:**
 - Linux Debian BE
 - 
** Sonstiges**
J-lawyer kann wohl weder die Bildschirme noch die angezeigte Bildschirmfläche unterscheiden.
Problem besteht seit immer, wird verstärkt durch neue Monitor-Einstellungen.

**Comment by j-dimension** [comment]
Was ist das für ein Window Manager? 
Wie hoch ist die Displayauflösung?
Lässt sich das Fenster etwas nach unten ziehen und dann in der Größe ändern?

**Comment by j-dimension** [comment]
> Problem besteht seit immer, wird verstärkt durch neue Monitor-Einstellungen.

Was heißt das genau?

**Comment by bmle17** [comment]
Ich benutze xfce4 - in  debian Grundeinstellung und 2 externe Monitore zusätzlich zum Laptop.
Auflösung ist bei allen 1920x1080 (16:9) 60,0Hz, 1x. 

Das Fenster lässt sich nicht immer nach unten ziehen.  Ort und Größe des Fensters sind unterschiedlich und nicht nachvollziehbar. 

Das Problem habe ich seit dem ich jlawyer benutze, es tritt jetzt allerdings wieder gehäuft bei mir auf. 

Aktuell Jlawyer 2.1.0.0.

**Comment by j-dimension** [comment]
Puh, da habe ich nicht mal eine Testumgebung. Ich teste Windows, macOS, Linux+KDE, Linux+GNOME. 

Gibt es bei Euch noch ein alternatives Gerät mit anderem Window Manager? 

Entweder tritt das konsistent auf, wenn XFCE genutzt wird, oder es ist eine spezifische Thematik für dieses Gerät/Konfiguration. Mir ist das zumindest von anderer Seite noch nicht angetragen worden.

**Comment by j-dimension** [comment]
Der Dialog "fragt" das System nach den Dimensionen des Screens, und setzt seine Größe dann auf 85% davon, sofern nicht durch manuelles Ändern der Größe eine Präferenz in den Einstellungen gespeichert wurde.

In $HOME/.j-lawyer-client/clientConfiguration.properties gibt es diese zwei Zeilen:

```
com.jdimension.jlawyer.client.editors.files.AddDocumentFromTemplateDialog.w=1920
com.jdimension.jlawyer.client.editors.files.AddDocumentFromTemplateDialog.h=1034
```
Du kannst dort testweise mal Werte eintragen, die Dir sinnvoll erscheinen. Vor dem Bearbeiten den Client schließen.

**Comment by j-dimension** [comment]
@bmle17 sofern sich neue Erkenntnisse ergeben, das Ticket gern wieder öffnen.

**Comment by j-dimension** [comment]
Bitte einen Screenshot an neuem Ticket - danke.

**Comment by bmle17** [comment]
![Bildschirmfoto_2023-03-06_13-04-55](https://user-images.githubusercontent.com/118005461/223105894-f2843b0b-1574-4fca-ab56-4d8c1fe14b3e.jpg)
