### ISSUE TITLE
[FEATURE] Versionsattribut für Dokumente

### ISSUE THREAD

**Issue by j-dimension** [jlawyerorg/j-lawyer-org#1810]
Als Vorstufe von #862 ein Attribut "Version" an jedem Dokument. Ein Client, der weiß dass er schon eine Version x hat, muss nicht neu vom Server laden, wenn der Server auch noch bei x ist.

**Comment by stm9x9** [comment]
Das wird dann bei jeder Änderung - ob nun am Inhalt oder an Meta-Daten (Datum, Etikett ...) - das Attribut hochgezählt?

**Comment by j-dimension** [comment]
> Das wird dann bei jeder Änderung - ob nun am Inhalt oder an Meta-Daten (Datum, Etikett ...) - das Attribut hochgezählt?

ja
