### ISSUE TITLE
[FEATURE] REST-Endpunkt zum Dokumente erstellen ohne Angabe der Platzhalterwerte

### ISSUE THREAD

**Issue by j-dimension** [jlawyerorg/j-lawyer-org#1811]
/v6/templates/documents/{folder}/{template}/{caseId}/{fileName} benötigt aktuell die Platzhalterwerte auf Clientseite. Service könnte - für "ease of use" - die Platzhalter selbst bereitstellen und die vom Client übertragenen nur zum "Überschreiben" nutzen.

**Comment by j-dimension** [comment]
@iradraconis @LazyGuy21No

**Comment by iradraconis** [comment]
Würde die Erweiterung in Vorlagen die auf dem Server gespeicherten Werte bspw. des Kanzleiprofils automatisch ausfüllen?

**Comment by LazyGuy21No** [comment]
Das ist der Plan

**Comment by j-dimension** [comment]
Muss mir das anschauen, aber das wäre das Ziel, ja. Der Client würde dann nur noch Platzhalterwerte mitgeben, die er manuell überschreiben / setzen will.

**Comment by iradraconis** [comment]
Ich werde das diese Woche noch testen. Bin bisher nicht dazu gekommen.

**Comment by iradraconis** [comment]
So, erste Tests erfolgreich! Das erleichtert die Erstellung von Dokumenten enorm. Werde das die Tage in mein Tool einbauen und dann werden wir es im praktischen Einsatz jeden Tag nutzen. 

1000 Dank, Jens!
