### ISSUE TITLE
[BUG] Fehler bei Speichern vom Faxbericht oder Scaneingängen zur Akte, wenn Dokument keinen Namen hat

### ISSUE THREAD

**Issue by iradraconis** [jlawyerorg/j-lawyer-org#1815]
Meine Mitarbeiterin wollte ein Faxbericht zur Akte hinzufügen. Dann kam die auf dem Bildschirmfoto ersichtliche Fehlermeldung. Sie sagt, dass der Fehler nur in dieser Akte von heute auf morgen aufgetaucht sei. Auch an meinem Client kann ich den Faxbericht nicht speichern. Das LogFile (kommt per Mail) ist vom Client meiner Mitarbeiterin unmittelbar, nachdem ich die Fehlermeldung abfotografiert habe. 

Sie sagt, der Fehler werde auch angezeigt, wenn sie Dateien aus dem Scan Ordner in DIESE Akte hinzufügen möchte.
<img width="714" alt="Bildschirmfoto 2022-11-17 um 09 21 27" src="https://user-images.githubusercontent.com/71747937/202400517-eb92f420-d51e-4417-a54e-51b663ccd6ba.png">

**Comment by j-dimension** [comment]
@iradraconis die NullpointerException ist leider nicht im client.log enthalten. Weißt Du noch, wie Du den Client im Terminal starten kannst? Dann bitte mal so starten und das Fehlerszenari erneut ausführen. Danach sollte im Terminal eine lange Ausschrift stehen, die ich benötige. 

Danke!

**Comment by j-dimension** [comment]
```
Caused by: java.lang.NullPointerException
	at com.jdimension.jlawyer.services.ArchiveFileService.doesDocumentExist(ArchiveFileService.java:3515)

```

**Comment by j-dimension** [comment]
doesDocumentExist-Implementierung: 
`if (doc.getName().equalsIgnoreCase(documentName)) {`

**Comment by j-dimension** [comment]
@iradraconis ich weiß nicht wie Ihr das hinbekommen habt, aber es gibt ein Dokument ohne Namen in dieser Akte. 

Wenn Du Zugriff auf die Datenbank hast, kannst Du das wie folgt verifzieren: 

` select id, name from case_documents where name is null;`

**Comment by iradraconis** [comment]
> @iradraconis ich weiß nicht wie Ihr das hinbekommen habt, aber es gibt ein Dokument ohne Namen in dieser Akte.
> 
> Wenn Du Zugriff auf die Datenbank hast, kannst Du das wie folgt verifzieren:
> 
> ` select id, name from case_documents where name is null;`

Meinst du dieses "Dokument"? :D 
lässt sich nicht löschen..

![Bildschirm­foto 2022-11-17 um 11 20 08](https://user-images.githubusercontent.com/71747937/202420701-5b2a14ed-a0eb-4d99-b8a8-6807cb3252a2.png)

**Comment by j-dimension** [comment]
Geht wahrscheinlich nur über die Datenbank. Bitte erstmal die Abfrage oben ausführen, danach kann ich ein Statement senden, welches den Namen auf einen definierten Wert setzt. 

Ggf. machen wir Fernwartung.

**Comment by iradraconis** [comment]
Alles gut, ich konnte über die Zuordnung in einen Unterordner im Ausschlussverfahren die Datei löschen. Jetzt funktioniert wieder alles

**Comment by j-dimension** [comment]
@iradraconis jetzt wäre es nur noch spannend zu wissen, wie das Dokument entstanden ist. War es ein Dokument das über die API generiert wurde?

**Comment by iradraconis** [comment]
Nein, das kann nicht sein. Es muss über den Scan Eingang gekommen sein.
