### ISSUE TITLE
[BUG] Darstellung der Ordner Liste in eMail Modul => horizontaler Scrollbalken

### ISSUE THREAD

**Issue by iradraconis** [jlawyerorg/j-lawyer-org#1817]
Wenn ich aus E-Mails heraus Dokumente zu Akten zuordnen möchte, muss ich eigentlich fast immer den vertikalen Trennbalken verschieben, sodass ich alle Ordner sehen kann. Siehe Screenshot. Vielleicht ließe sich hier das Verhalten so anpassen, dass automatisch alle Ordner angezeigt werden oder die Position des Balkens gespeichert wird. Vielleicht kein Bug aber "Usabilityerweiterung" :) 

EDIT: ich muss mich korrigieren, der Balken wird gespeichert und soweit ich sehen kann auch nur innerhalb einer Session. Was ich mit dem Ticket eigentlich sagen wollte: die Ordner sollten automatisch immer voll sichtbar sein :)

![Bildschirmfoto-20221118080131-231x909](https://user-images.githubusercontent.com/71747937/202641604-4dbf001e-6ef2-4d55-ac8a-fa74b6e36e71.png)

**Comment by j-dimension** [comment]
@iradraconis die Trennerposition wird eigentlich gespeichert. Passiert das bei Dir nachvollziehbar immer?

**Comment by iradraconis** [comment]
Folgendes beobachtet, da ich erst dachte ich sei bekloppt. Du hast Recht, die Trennerposition wird gespeichert. ABER: mit jedem weiteren Mal, das dieses Fenster aufgeht, rutscht der Trenner weiter nach rechts, so dass es dann irgendwann nicht mehr passt.

**Comment by iradraconis** [comment]
Video per Mail geschickt.

**Comment by j-dimension** [comment]
Danke für das Video, allerdings bekomme ich das immer noch nicht reproduziert. Passiert das auch auf anderen Arbeitsplätzen?

**Comment by iradraconis** [comment]
> Danke für das Video, allerdings bekomme ich das immer noch nicht reproduziert. Passiert das auch auf anderen Arbeitsplätzen?

Ich habe es heute mit dem M1 Client ausprobiert, aber konnte es so nicht reproduzieren. Ich schaue morgen noch mal an einem anderen Arbeitsplatz.
