### ISSUE TITLE
[BUG] [beA] [Mail] Verzögerung beim lokalen Abspeichern 

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#1818]
Nach jedem Neustart von j-l (Win64) fällt folgendes auf:

Wenn ich erstmalig in beA in einer Nachricht auf einem Anhang auf Speichern als lokale Datei gehe, dann friert j-l für bis zu 30 Sekunden ein, bis das Fenster mit dem Dateisystem erscheint. Jedes spätere Aufrufen, auch in anderen Nachrichten läßt dieses Fenster binnen Sekunden erscheinen.

**Comment by j-dimension** [comment]
DAnn wird im Hintergrund noch das Postfach geladen (sollte unten in der Statuszeile angezeigt werden). Der Nachrichtenabruf drängelt sich dann irgendwo "dazwischen", bricht aber kein Hintergrundladen einer Nachricht ab.

**Comment by j-dimension** [comment]
30s erscheint mir aber sehr viel.

**Comment by stm9x9** [comment]
30 sec ist leider korrekt. Eher mehr. Und ich hatte beA jetzt ne halbe Stunde offen bevor ich ein Abspeichern versucht habe. Wieder die Pause. Das liegt IMHO nicht am Postfachladen. Und in Akte speichern öffnet sofort das Fenster.

Wie ich gerade bemerke, das ist nichtmal ein beA-Dingens. Es passiert genauso wenn ich das erste Mal nach Neustart einen Mail-Anhang lokal ablegen will.

Mir scheint, das ist was mit dem lokale-Ordner-Dialog des Frameworks.

**Comment by j-dimension** [comment]
Wieviel RAM nutzt denn der Client? Vielleicht möchte er mehr.

**Comment by stm9x9** [comment]
700 MB. Und über 10 GB frei.
Aber kann denn das Einlesen einer Verzeichnisstruktur derart was brauchen?

**Comment by j-dimension** [comment]
Temporär kann das beA viel RAM benötigen. In der Datei j-lawyer-Client.vmoptions könnte man den Xmx anpassen. Könnte dann so aussehen: 

-Xmx3072m

**Comment by stm9x9** [comment]
wie gesagt, es ist ja doch kein beA-Issue. Es passiert genauso ohne beA im Mailbereich.

**Comment by j-dimension** [comment]
Probier es doch bitte mal, um das als Ursache auszuschließen. Andere Anhaltspunkte habe ich aus der Ferne nicht.

**Comment by stm9x9** [comment]
done. keine Veränderung - wie gesagt, direkt bei einem Mail-Anhang versucht, ganz ohne beA.

**Comment by j-dimension** [comment]
Wie groß ist der Mailanhang und die Mail insgesamt?

**Comment by stm9x9** [comment]
Mail 12kb. Anhang 4 kb. Aber wie gesagt, ab dem zweiten Mal öffnet sich das Fenster binnen Sekunden. Und die ersten 30 sec sind bei absolut jeder Mail / beA-Nachricht.

**Comment by j-dimension** [comment]
Wenn es ein Linux ist, könnte man den Client mal mit 

`strace ./j-lawyer-Client `

starten und die Ausgabe bei dieser Aktion hier posten.

**Comment by stm9x9** [comment]
Win64 :-(

**Comment by j-dimension** [comment]
Du hattest aber auch einen Linux-Client, oder? Tritt das dort auch auf?

**Comment by stm9x9** [comment]
Linux ist nur der Server, sorry

**Comment by j-dimension** [comment]
@stm9x9 ich weiß nicht wie ich hier helfen kann. Vielleicht kannst Du es mit dem Process Explorer noch etwas eingrenzen und dann das Ticket wieder öffnen.

https://learn.microsoft.com/en-us/sysinternals/downloads/process-explorer

**Comment by j-dimension** [comment]
@stm9x9 ich konnte das jetzt auf einem Windows-Arbeitsplatz beobachten. Scheinbar tritt das auf, wenn Netzlaufwerke angebunden sind oder eine Verknüpfung zu einer Netzwerkressource auf dem Desktop liegt. Beim Initialisieren des Datei-öffnen-Dialogs wird für alle Ressourcen das Icon ermittelt, und für Remote-Verzeichnisse dauert das scheinbar (oder wenn Authentifizierung notwendig ist, wird bis zu einem Timeout gewartet). 

Kann das bei Dir eine Rolle spielen?

> https://stackoverflow.com/questions/49792375/jfilechooser-is-very-slow-when-using-windows-look-and-feel

**Comment by stm9x9** [comment]
Ich kann die Beobachtung bestätigen: a) ich habe hier ein Netzlaufwerk eingebunden. b) es ist nur über ein VPN erreichbar. Ist das VPN beim ersten Aufruf der Funktion aus, dann dauert es die 30 sek. Wenn das VPN zufällig an ist, dann öffnet sich das Ordnerfenster auch beim ersten Mal sofort.

**Comment by j-dimension** [comment]
@stm9x9 ich lade den Dialog jetzt beim Clientstart im Hintergrund.
