### ISSUE TITLE
[FEATURE] Usability im Kalender: Scrollen durch Monate, Wochen, Tage mittels Mausrad

### ISSUE THREAD

**Issue by iradraconis** [jlawyerorg/j-lawyer-org#1821]
Siehe Titel.

Das wäre eine tolle Erweiterung, um das Arbeiten mit dem Kalender etwas flüssiger zu gestalten. Die kleinen Pfeile, über die bisher die Navigation erfolgt, sind etwas friemelig.

**Comment by iradraconis** [comment]
Wäre für mich mit #2481 erledigt.

**Comment by iradraconis** [comment]
@j-dimension  Ergänzend kann ich mir vorstellen, analog zum einfachen Scrollen durch die Monate, das scrollen durch Tag- und Wochenansicht bei gedrückter Shift Taste. Sinnvoll? Dann würde ich mich da dran setzen.

**Comment by j-dimension** [comment]
Ich habe bisher keinen Bedarf dafür verspürt, bin aber offen dafür :-)
Unklar ist mir noch, wie ein Nutzer überhaupt bemerken würde, dass diese Art der Bedienung möglich ist.

**Comment by iradraconis** [comment]
Bei uns rufen oft Gerichte an und wollen Termine irgendwann in den kommenden Monaten absprechen. Daher kommt es bei uns häufig vor, dass wir Monate oder ein paar Wochen vorspringen müssen. 

"poweruser feature", das man dann einfach kennen muss...

**Comment by j-dimension** [comment]
Nachtrag via https://github.com/jlawyerorg/j-lawyer-org/pull/2492

**Comment by iradraconis** [comment]
Das Scrollen durch Tag- und Wochenansicht ist ohne Tastatur shortcut implementiert und damit die bessere Lösung. Kann geschlossen werden.
