### ISSUE TITLE
REST Schnittstelle /v1/cases/party/create returned Error 405

### ISSUE THREAD

**Issue by timo0** [jlawyerorg/j-lawyer-org#1822]
Wenn ich per API auf `/v1/cases/party/create` mit folgender Payload sende:

```
{
	"addressId":"09c9409fac1100056049e7eb0d5f0af2",
	"caseId":"adad6493ac16000d11de5fbc3d0b068d",
	"contact":"",
	"custom1":"",
	"custom2":"",
	"custom3":"",
	"id":"",
	"involvementType":"Dritte",
	"reference":""
}
```

Bekomm ich immer Error 405 und bei komplett DEBUG Log finde ich nur einen Eintrag:

```
17:11:16,306 DEBUG [io.undertow.request] (default I/O-8) Matched default handler path /v1/cases/party/create
```
Weder davor, noch danach irgendein Hinweis auf ein Fehler.

Die IDs sind doppelt gecheckt und wenn ich den Beteiligten manuell per UI anlege, kommt der exakt gleiche Eintrag per API zurück (mit ID natürlich)

**Comment by j-dimension** [comment]
Was sagt denn das Server.log?

**Comment by timo0** [comment]
Wie oben geschrieben. Wirklich nur:

```
17:58:20,021 DEBUG [io.undertow.request] (default I/O-2) Matched default handler path /v1/cases/party/create
```

Keine weiteren logs und es ist alles auf DEBUG.

**Comment by timo0** [comment]
Ebenfalls ausgeschlossen hab ich den reverse proxy, auch bei direkter Verbindung, kommt der gleiche Fehler.

**Comment by j-dimension** [comment]
Kann hier kein Problem mit dem Endpunkt nachstellen. Beispiel-Request:

`curl -X PUT "http://admin:a@localhost:8080/j-lawyer-io/rest/v1/cases/party/create" -H  "accept: application/json" -H  "Content-Type: application/json" -d "{  \"addressId\": \"0c6179ec7f00010163d344da529e0abb\",  \"caseId\": \"142bcce07f00010135bbe086674f1b8a\",  \"contact\": \"\",  \"custom1\": \"\",  \"custom2\": \"\",  \"custom3\": \"\",  \"id\": \"\",  \"involvementType\": \"Dritte\",  \"reference\": \"\"}"`

**Comment by j-dimension** [comment]
Einmal durchchecken:

- IDs prüfen (hast Du schon gemacht)
- Gibt es den Beteiligtentyp "Dritte" in der von Dir genutzten Installation?
- wird ein HTTP PUT genutzt (kein GET oder POST)
- ist der Pfad für den Endpunkt korrek? http://localhost:8080/j-lawyer-io/rest/v1/cases/party/create

Wenn das nicht hilft, dann bitte die Ausgabe von 

curl -v ....   (verbose) 

hier posten.

**Comment by timo0** [comment]
mea culpa! Irgendwie hat den Content-Type Header nicht gesetzt gehabt. Danke für deine Hilfe!
