### ISSUE TITLE
Bug: Kennwortgenerierung für Freigabe erstellt nicht mind. 10 Stellen 

### ISSUE THREAD

**Issue by iradraconis** [jlawyerorg/j-lawyer-org#1830]
Siehe Titel. Bei Freigabe wird ein PW generiert, das aber keine 10 Stellen lang ist. Das Programm moniert dann, dass das PW zu kurz sei.

**Comment by j-dimension** [comment]
@iradraconis tatsächlich. Wenn man ein Passwort an der Adresse hinterlegt, wird es 10 Zeichen lang. Das Generieren beim Erstellen der Freigabe nutzt nur 8. Ich passe das an.
