### ISSUE TITLE
Organisation der eingehenden BEA-Anhänge

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-org#1831]
Ich habe die Tage vom Landgericht eine BEA mit Anhängen bekommen - 111 Dateien. Davon sind 2/3 Signaturdateien, Transfervermerke für jede einzelne Anlage...., nur ein Drittel sind verfahrensrelevante Schriftsätze und Anlagen. Da muss man dann höllisch aufpassen nicht eine Datei zu übersehen. ich exportiere aus der BEA Datei immer nur die Dokumente und Anlagen (pdf) und lasse die Original-Bea Transfervermerke, signaturnachweise, etc. mit der original BEA im Dokumentenordner. Es wäre evt. hilfreich, die im "täglichen Betrieb" unnötigen Transferdateien etc. in einer anderen Farbe anzuzeigen, damit man die PDFs schneller erkennt oder die Anhänge der Bea-Nachricht nach Dokumententyp sortieren lassen zu können um einen Export in den Dokumentenordner der Schriftsätze und Anlagen zu erleichtern...

**Comment by Mucki526** [comment]
Oh, also 1289 (doppelt)... Das tut wirklich Not, weil der Entwickler des BEAS offensichtlich nicht mit dem System arbeiten muss....

**Comment by j-dimension** [comment]
Werde mir das via #1225 mit anschauen. Das hier mache ich als Duplikat zu.
