### ISSUE TITLE
[FEATURE] [E-Mail]-Versand: anzeigen. ob für Empfänger Verschlüsselung genutzt werden kann

### ISSUE THREAD

**Issue by iradraconis** [jlawyerorg/j-lawyer-org#1834]
Wenn an der Adresse eines Empfängers ein PW hinterlegt ist, wäre es schön, wenn im E-Mail Fenster der Button „verschlüsseln“ aktiviert wäre. Gegenwärtig ist keine Automatik hinterlegt. Ich weiß leider nicht auswendig, welcher Mandant gern verschlüsselt empfangen möchte. Derzeit behelfen wir uns damit, dass wir einen Unterordner anlegen, der „VERSCHLÜSSELT“ heißt, damit mir das ja nicht entgeht, wenn ich E-Mails versende.

**Comment by j-dimension** [comment]
Das automatische Aktivieren wird einigen nicht gefallen, bspw. weil das Passwort nur für die Nextcloud-Freigaben verwendet wird. Evtl. wäre eine Information / Anzeige, ob Person ein Passwort hat, die bessere Variante.

**Comment by iradraconis** [comment]
Ach so, das habe ich nicht bedacht. Dein Vorschlag wäre tatsächlich eine gute Ergänzung.
