### ISSUE TITLE
[FEATURE] Dokumentenliste - Buttons verschieben / Vorschau vergrößern

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#1836]
Vorschlag: die Buttons da rechts nach links (aber immer noch rechtsbündig neben der Vorschau) verschieben. Links bzw in der Mitte ist Platz und die Vorschau könnte noch einen Ticken größer werden.

![image](https://user-images.githubusercontent.com/29924198/207449262-be385598-26af-43eb-952c-e184d0e63f26.png)

**Comment by j-dimension** [comment]
Kann ich ohne weiteres nicht umsetzen. Das würde nur gehen, wenn sichergestellt ist, dass die Buttons links immer Platz haben. Auf kleineren Bildschirmen ist das nicht der Fall, die Vorschau würde dann nach links aus dem Bildschirm herausgedrängt werden.

**Comment by stm9x9** [comment]
>Auf kleineren Bildschirmen ist das nicht der Fall, die Vorschau würde dann nach links aus dem Bildschirm herausgedrängt werden.

Ist das realistisch? Dann wäre die Ansicht ja so klein, daß in der Dokumentenliste nichts mehr zu lesen wäre, so wenig Zeichen wir dann nur möglich wären?

Ich finde - zu der Größe der Vorschau - auch inhaltlich passender, da ich keinen inhaltlichen Zusammenhang mit der Vorschau sehe. Daß die Buttons aber dadrüber sind, impliziert einen Zusammenhang IMHO.

**Comment by j-dimension** [comment]
> Ist das realistisch?

Ja, sobald auf einem kleineren Display eine Skalierung oder Schriftgrößenanpassung genutzt wird.

**Comment by stm9x9** [comment]
dann sind doch aber auch die Buttons wieder kleiner?

**Comment by j-dimension** [comment]
> dann sind doch aber auch die Buttons wieder kleiner?

Es geht um die "ich hab nen kleines Display und vergrößere die Schrift damit ich was erkennen kann"-Fraktion. Dann werden die Buttons größer, bei wenig Platz.

**Comment by Dickmaulruessler** [comment]
Hintergrund ist ja letztendlich, dass wir die Vorschau toll finden und diese gerne möglichst groß hätten...

Daher mal anders gefragt: Wäre ein (im Einzelfall optional) fliegendes, sich groß machendes Fenster für die Vorschau evtl. eine denkbare Lösung, welche alle Seiten glücklich machen könnte?

**Comment by j-dimension** [comment]
Ich mache an der Stelle erstmal zu, da die hier angefragte Layoutänderung nicht umgesetzt werden sollte, aus genannten Gründen.
