### ISSUE TITLE
[TASK] Warnung bei HTML-Mails abschaltbar machen

### ISSUE THREAD

**Issue by j-dimension** [jlawyerorg/j-lawyer-org#1837]
Ich weiß nicht mehr, welcher das war :( 
ich klicke mich den ganzen Tag durch so viele Akten. Ich habe versucht, hier reinzukommentieren, so schnell es ging, damit ich es nicht vergesse. Wenn ich das Verhalten noch mal sehe, achte ich darauf. Wenn es eine Möglichkeit gäbe, diese Funktion ganz abzuschalten, wäre ich dennoch dankbar.

_Originally posted by @iradraconis in https://github.com/jlawyerorg/j-lawyer-org/issues/1669#issuecomment-1354302122_

**Comment by iradraconis** [comment]
Gibt es irgendwas, was ich in der Zwischenzeit zur Lösung des Problems machen kann? Ich hab das immer häufiger: Mail wird angeklickt, Absender bestätigt. Anderes Dokument/Mail wird geöffnet und dann wieder die vorangegangene Mail. Ich muss wieder bestätigen.

**Comment by j-dimension** [comment]
> Gibt es irgendwas, was ich in der Zwischenzeit zur Lösung des Problems machen kann?

Ohne Codeänderung ist das Verhalten nicht anzupassen.

**Comment by j-dimension** [comment]
@iradraconis ich meine ich konnte #1669 gerade nachvollziehen und habe einen Fix erstellt. Von der Konfigurierbarkeit würde ich erstmal absehen. Okay?
