### ISSUE TITLE
Datumszeile im Scanfenster verschwindet, wenn man eine Datei anklickt für die Vorschau

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-org#1841]
Wenn man in den scanordner / bereich wechselt, dann sieht man in der ersten Zeile das Datum und die Uhrzeit des Scans. Wenn man dann eine Datei auswählt für die Vorschau, verschwindet diese Zeile (lässt sich auch nicht wieder rausziehen). Sie erscheint erst wieder, wenn man manuell eine refresh macht. .

**Comment by j-dimension** [comment]
In dem gewählten Layout ist dann nicht genügend Platz für Datumsspalte und Dateiname. Du kannst entweder den Trenner nach rechts ziehen, sodass beide Spalten ausreichend Platz haben, oder statt auf den Dateinamen auf das Datum in der selben Zeile klicken. Die Tabelle scrollt automatisch zu der Spalte, die geklickt wird. 
Hilft das weiter?

Bei mir kann man aber jederzeit horizontal scrollen, sodass ich den Teil mit dem notwendigen Refresh nicht verstehe. 

Ggf. mal ein Bildschirmvideo posten.

**Comment by Mucki526** [comment]
Oh,der Scrollbalken verschwindet bei mir (immer) unter der Windowszeile (Windows10 prof) (21 Zollbildschirm) sobald j-lawyer im Vollbild ist. Vielleicht kann ich das irgendwie ändern.... Das mit dem Argument, Es passt wegen langer Dateinamen nicht ins Layout, ist aber nicht die Erklärung. Ich habes darum nochmal ausprobiert. Meine Irritation beruht darauf, dass, wenn ich in der "Grundstellung" der Ansicht das  (Zeigefinger linke Taste Maus) Datum einer Datei anklicke, kommt einfach die Vorschau. Klicke ich (Zeigefinger linke Taste Maus) aber in der Leiste mit einer Datei im Focus auf den Dateinamen, dann verschwindet das Datum (verschiebt sich) und ich sehe im Layout nur noch die Dateinamen. Das könnte / sollte m.E. einheitlich sein.

**Comment by Mucki526** [comment]
Ist eine philosophische Frage. Wir haben immer recht viel Scans im Scanordner, ist bei uns die Schnittstelle zwischen den windows Ordnern und der Aktendatenbank... Bei mir wird am Bildschirm so oder so ein Dateiname in jeder Länge angezeigt. Also leben wir den Kompromiss.... :-)
