### ISSUE TITLE
[BUG] Rechnungsnummernkreis läßt sich nicht isoliert zu Jahresbeginn neu setzen

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#1851]
Wenn ich dem Hinweis unter https://www.j-lawyer.org/?p=4698 folgend neue Werte eingebe, dann werden die nicht übernommen solange ich nicht auch gleich eine neue Rechnungsnummer generiere. Man muß also - ggf mit der Neuerung der individuellen Nummernkreise mehrfach - beim Erstellen der jeweils neuen ersten Rechnung daran denken statt es einmal zum Jahresanfang machen zu können. Ein Speichern-Button könnte helfen.

![image](https://user-images.githubusercontent.com/29924198/212192356-52ca9a65-11cd-4205-8c76-0f04d582eef0.png)

Vorschlag nebenbei: den Button da nicht zurücksetzen nennen. Ich denke da immer, ich würde nur auf Null zurücksetzen. Stattdessen wird das ganze Nummernschema zurückgesetzt auf Defaultwerte. 

Im Archivnummergenerator heißt es verständlicher Plugineinstellungen zurücksetzen. Wobei es dort merkwürdigerweise dann aber gerade das Präfix nicht zurücksetzt. (BTW: vorangestellter Präfix ist doppelt gemoppelt :-))  Vielleicht Einstellungen zurücksetzen?

![image](https://user-images.githubusercontent.com/29924198/212192675-449bf508-8753-4f6e-aa11-7b9adf69e645.png)

**Comment by j-dimension** [comment]
Ich werde das Rechnungsnummernplugin nicht mehr anfassen, da hinsichtlich #225 obsolet.
