### ISSUE TITLE
[FEATURE] Rechnungen erstellen / organisieren

### ISSUE THREAD

**Issue by j-dimension** [jlawyerorg/j-lawyer-org#1853]
- [x] Rechnungstypen konfigurierbar machen; Name,  benötigt Rechnungsnummer ja/nein, ...
- [x] Rechnungen: Datenmodell und Services, inkl. Referenz auf Rechnungsempfänger (Adresse)
- [x] Rechnungspositionen: Datenmodell und Services
- [x] Rechnungspositionen als Vorlagen: Datenmodell und Services
- [x] Rechnungspositionen, UI
- [x] Rechnungserstellung, UI: Kopfdaten erfassen, Rechnungsnummernkreisauswahl
- [x] Rechnungsdokument generieren
- [x] Rechnungsdokument in Akte ablegen (noch unklar wo/wie), an der Rechnung anzeigen, Sync zwischen Dokumentliste und Rechnungsliste
- [x] Rechnungen suchen: nach Status, Fälligkeitsdatum
- [x] Adresse: Anzeige der Rechnungen, in welcher die Adresse als Empfänger geführt wird
- [x] Plugins: Übernahme der Positionen in eine Rechnung (Honorar)
- [x] Plugins: Übernahme der Positionen in eine Rechnung (RVG)
- [x] Plugins: Übernahme der Positionen in eine Rechnung (Sozialrecht)
- [x] Plugins: Übernahme der Positionen in eine Rechnung (Strafrecht)
- [x] Rechnungen duplizieren
- [x] Rechnungen in andere Akte kopieren
- [x] Rechnungstyp ändern (bspw. Kostenvoranschlag zu Rechnung - dabei dann auswerten ob neuer Typ eine Rechnungsnummer erfordert und ggf. erstellen)
- [x] Rechnungen löschen
- [x] #1956
- [x] #1957
- [x] Währung als Attribut an der Rechnung, inkl. Platzhalter
- [x] Aktenhistorie bei allen Rechnungsaktionen erweitern
- [x] Belegart "Quitting": Belegart, Uploadmöglichkeit für Dokument (statt Erstellen via Vorlage)
- [x] Statuswerte erweitern: 1. Mahnstufe, 2. Mahnstufe, 3. Mahnstufe (alle als "offen" werten)
- [x] Statuswerte erweitern: "nicht vollstreckbar" (bspw. Schuldner insolvent - als "offen" werten)
- [x] #1955 -  Übergangsvariante: gezahlten Betrag speichern (Man könnte hier auch erstmal die Teilzahlungen in der Beschreibung hinterlegen)
- [x] #1959
- [x] alle Plugins: Faktor/Quote in die Beschreibung der Position aufnehmen

**Comment by Maz111111** [comment]
Ich kann nicht erkennen, ob das oben schon beinhaltet ist.

Es wäre total gut, wenn eine tabellarische Übersicht über alle Rechnungen und deren Status abrufbar wäre.

In der Übersicht sollten (ggf. konfigurierbare) Informationen (u.a. Aktenzeichen, Kurzrubrum, Höhe der Forderung, Status etc.) der Rechnungen ersichtlich sein.

Am Ende der Übersicht sollte ein (konfigurierbare) Kummulation erfolgen (insges abgerechnet, bezahlt, offen, netto offen / abgerechnet, netto bezahlt etc.)

Die systematische Übersicht sollte in zeitlicher Sicht konfigurierbar sein, dass entweder ein bestimmter Monat, ein bestimmtes Jahr oder der gesamte erfasste Zeitraum aufgelistet wird.

**Comment by j-dimension** [comment]
@Maz111111 ja, Auswertungen wird es geben. Zahlungen (dokumentieren) sind hier allerdings nicht Inhalt des Tickets, folgen später.

**Comment by j-dimension** [comment]
Einstellungen:

https://user-images.githubusercontent.com/3729754/234424672-d1807338-c8d3-4db6-baf2-5819149b2733.mp4

**Comment by j-dimension** [comment]
Vorlagen / Platzhalter: 

https://user-images.githubusercontent.com/3729754/234424754-a16b1014-abbe-4919-a6ee-ebb7f397a6d1.mp4

**Comment by j-dimension** [comment]
Erstellen / Editieren von Rechnungspositionen und Kopfdaten:

https://user-images.githubusercontent.com/3729754/234424805-767bdce8-ea22-465a-b475-86a9ca6bc260.mp4

**Comment by j-dimension** [comment]
Rechnung als Dokument erstellen:

https://user-images.githubusercontent.com/3729754/234424892-62e3208a-4138-46c5-8a62-888fa2a07ad4.mp4

**Comment by j-dimension** [comment]
Auswertungen:

https://user-images.githubusercontent.com/3729754/234424932-ddc2e0f0-f879-4ff6-9246-1d7e0fafd6ad.mp4

**Comment by j-dimension** [comment]
alle RVG-Plugins erweitert (Übernahme als Positionen in eine Rechnung)

**Comment by stm9x9** [comment]
kann das Ticket noch das Label Finanzen bekommen?
