### ISSUE TITLE
[FEATURE] [beA] in Akte speichern mit Ordnerauswahl

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#1859]
Wenn man eine beA-Nachricht beim Versenden in eine Akte speichert, dann wird sie im obersten Ordner Dokumente gespeichert und man muß sie immer erst hinterher in den richtigen Unterordner verschieben. Hilfreich wäre es daher, den passenden Ordner direkt auswählen zu können, zb durch ein Dropdown-Menü:

![image](https://user-images.githubusercontent.com/29924198/213014543-4024924e-3266-4593-936a-2241e3bdaac1.png)

**Comment by j-dimension** [comment]
Duplikat von #1221

**Comment by librelegal** [comment]
wenn es ein Duplikat ist, sollte das issue geschlossen werden
