### ISSUE TITLE
[BUG] [beA] Gesendete Nachricht mit vielen Anhängen kann nicht geöffnet werden auf j-lawyer Box 1.13.4

### ISSUE THREAD

**Issue by librelegal** [jlawyerorg/j-lawyer-org#1862]
Der Abruf von Nachrichten per j-lawyer funktioniert allgemein problemlos. Linux-Server mit ausreichend RAM usw., von mehreren Linux und Windows Clients, Abruf per Zertifikat durch RA und Mitarbeiter.  - OS / Betriebssystem: Linux und Win10
 - j-lawyer.org Version: 2.3.0.0. Besonderheit j-lawyer-Box "Firmware:  1.13.4" "Kanzleisoftware: 2.3.0.1", ist also NICHT die normale Version.

Eine einzige durch RA gesendete Nachricht an das Amtsgericht Brandenburg vom 12.1.23 kann jedoch seitdem nicht geöffnet werden. Diese Nachricht wird OBEN angezeigt, mit Betreff (der auch Klammern, Punkte und Schrägstriche enthält), Absender, Aktenzeichen usw.. Die Nachricht hat 27 Anhänge.  Ein Klick auf diese Nachricht bewirkt exakt gar nichts, auch nicht nach 10 Minuten. UNTEN wird nichts angezeigt, auch nicht der Betreff. 

Die Nachricht war von j-lawyer aus  durch MA entworfen und in Entwürfe eingestellt worden. Versand wurde sie aus der beA-Weboberfläche durch RA, die Zustellanwort normal.  In der beA-Weboberfläche kann sie geöffnet werden, beim ersten Öffnen am 12.1. dauerte dies etwas länger.

**Comment by j-dimension** [comment]
Gibt es Einträge im client.log? 
Wie groß sind alle Anlagen zusammen?

**Comment by librelegal** [comment]
Im Client.log mit rund 10500 Zeilen finde ich nichts kann es aber an Dich direkt schicken. Die Nachrichten ID finde ich dort nicht. Die Gesamt-Größe wird mir auch der Weboberfläche nicht angezeigt.

**Comment by j-dimension** [comment]
> Die Gesamt-Größe wird mir auch der Weboberfläche nicht angezeigt.

Du könntest die Nachricht über beA Web exportieren, das ZIP auspacken, Gesamtgröße (entpackt) ermitteln.

**Comment by librelegal** [comment]
Entpackt 244.270.894 Bytes, angezeigt wird 232 MB. Ist wohl zu groß

**Comment by j-dimension** [comment]
Dann ist sie kodiert ca. 340MB groß, ich vermute dass der vom Client benutzte RAM nicht ausreicht. Den kann man in einer Datei konfigurieren, lohnt sich wenn das öfter vorkommt.

**Comment by librelegal** [comment]
Ich bezweifle das. Ein Client hat z.B. noch 7,8 GB RAM frei (von 12 GB), doch öffnet sich - auch nach langer Zeit gar nichts. Ähnlich bei anderen Clients

**Comment by j-dimension** [comment]
Geht nicht um die Hardware, sondern ein konfiguriertes Limit für jeden Client-Prozess. Das steht standardmäßig auf 2GB.

**Comment by librelegal** [comment]
Danke für die Info. Dann würde ich das gerne entsprechend erhöhen, ich muss diese beA-Nachricht ja irgendwie verspeichern.

**Comment by j-dimension** [comment]
Im Installationsverzeichnis des Clients gibt es eine j-lawyer-Client.vmoptions

Dort bitte eine Zeile am Ende einfügen:

`-Xmx4096M`

Client neu starten.

**Comment by librelegal** [comment]
... habe das nun bei 3 clients ausprobiert, doch scheint das nicht die Lösung zu sein

**Comment by j-dimension** [comment]
Dann bitte mal das client.log senden, und die Ausgabe von 

`sysprops`

in der Administratorkonsole.

**Comment by Mucki526** [comment]
Habe das gleiche erlebt Schriftsatz mit vielen Anhängen. Da half schlussendlich tatsächlich nur der Export über die weboberfläche (Zeitintensiv ohne Ende). Da wir alles über BEA abwickeln müssen mit den Gerichten und es immer mehr wird, ist es immer wichtiger, dass das das BEA "flutscht".

**Comment by j-dimension** [comment]
```
2023-01-19 13:19:21,730 INFO  [org.ehcache.impl.internal.resilience.RobustResilienceStrategy] Ehcache key 207199786 recovered from
org.ehcache.spi.resilience.StoreAccessException: The element with key '207199786' is too large to be stored in this offheap store.
	at org.ehcache.impl.internal.store.offheap.AbstractOffHeapStore.computeWithRetry(AbstractOffHeapStore.java:1034) ~[ehcache-3.7.0.jar:3.7.0 46e678e9f3c666500e2b2cd3c5f626fed22f4c97]
	at org.ehcache.impl.internal.store.offheap.AbstractOffHeapStore.put(AbstractOffHeapStore.java:247) ~[ehcache-3.7.0.jar:3.7.0 46e678e9f3c666500e2b2cd3c5f626fed22f4c97]
	at org.ehcache.impl.internal.store.tiering.TieredStore.put(TieredStore.java:108) ~[ehcache-3.7.0.jar:3.7.0 46e678e9f3c666500e2b2cd3c5f626fed22f4c97]
	at org.ehcache.core.Ehcache.doPut(Ehcache.java:94) ~[ehcache-3.7.0.jar:3.7.0 46e678e9f3c666500e2b2cd3c5f626fed22f4c97]
	at org.ehcache.core.EhcacheBase.put(EhcacheBase.java:189) [ehcache-3.7.0.jar:3.7.0 46e678e9f3c666500e2b2cd3c5f626fed22f4c97]
	at com.jdimension.jlawyer.client.bea.BeaAccess.getMessage(BeaAccess.java:1103) [j-lawyer-client.jar:?]
```

**Comment by j-dimension** [comment]
@librelegal um nicht bei jedem Öffnen einer Nachricht im Posteingang vom Server laden zu müssen, habe ich einen plattenbasierten Cache implementiert. In diesem Fall ist er zu klein für die Nachricht. Ich habe das Limit nun angehoben.

**Comment by j-dimension** [comment]
Nicht ohne neues Release meinerseits. Du musst die Nachricht über den Browser exportieren und zur Akte nehmen.

**Comment by librelegal** [comment]
Alles klar, das hatte ich nur nicht verstanden. Dann herzlichen Dank für den Einbau der Lösung, offenbar hat ja auch Kollege Mucki mal ein Problem gehabt.
