### ISSUE TITLE
[adresssen] Mehr Inhalt der Detail-Anzeige bei Beteiligten 

### ISSUE THREAD

**Issue by MarcoWolny** [jlawyerorg/j-lawyer-org#1863]
In der Akte unter "Beteiligte" werden bei "Details" nicht alle eingetragenen Felder angezeigt; wünschenswert wäre auf jeden Fall "Unternehmen" und "Abteilung", wenn möglich aber auch gerne Telefon, E-Mail pp. damit man nicht immer in die Adressdatensätze einsteigen muss, wenn man etwas sucht. 

Begründung:
Wir haben in unserer täglichen Arbeit häufig z.B. das Bezirksamt als Beteiligten, dann aber dort die Wohngeldstelle, die Elterngeldstelle, das Sozialamt pp. - und all das in einer Akte. Wir differenzieren nach Abteilung, was allerdings im Detail und bei Mouse-over nicht angezeigt wird, sodass immer erst einmal der Adressdatensatz aufgerufen werden muss, um sicherzustellen, dass der richtige Beteiligte kontaktiert wird.

**Comment by j-dimension** [comment]
@MarcoWolny in den "Details" eines Beteiligten sind bereits Festnetz / Mobil / E-Mail etc. enthalten - bitte nochmal erläutern wie das gemeint ist, damit wir nicht aneinander vorbeireden :-)

**Comment by j-dimension** [comment]
Die Angaben in gelbe habe ich jetzt hinzugefügt: 

![grafik](https://user-images.githubusercontent.com/3729754/213532157-d6e6f847-e088-4334-b6dd-bedb8da4c856.png)

**Comment by MarcoWolny** [comment]
Hallo Jens,Erst einmal danke fürs schnelle Reagieren. Es würde mir jetzt (als Oldschool-Rechtsanwalt) nur noch die Fax-Nummer fehlen - dafür brauche ich mobil fast nie, wusste also nicht, dass das drin ist. Eilt nicht und ist nicht wichtig! 😉können wir auch drauf verzichten! Mit freundlichem Gruß MARCO WOLNYRechtsanwalt Fachanwalt für Strafrecht(von unterwegs)W O L N YRECHTSANWÄLTEPARTMBB*Bärenallee 12 22041 Hamburg-Wandsbek T: 040 . 650 333 28 F: 040 . 650 333 ***@***.****AG HamburgPR 1328Am 19.01.2023 um 19:46 schrieb Jens Kutschke ***@***.***>:﻿
Closed #1863 as completed via 1b0ad51.

**Comment by j-dimension** [comment]
> Es würde mir jetzt (als Oldschool-Rechtsanwalt) nur noch die Fax-Nummer fehlen

Ist erledigt!

**Comment by MarcoWolny** [comment]
Top, danke nochmal! Mit freundlichem Gruß MARCO WOLNYRechtsanwalt Fachanwalt für Strafrecht(von unterwegs)W O L N YRECHTSANWÄLTEPARTMBB*Bärenallee 12 22041 Hamburg-Wandsbek T: 040 . 650 333 28 F: 040 . 650 333 ***@***.****AG HamburgPR 1328Am 19.01.2023 um 19:58 schrieb Jens Kutschke ***@***.***>:﻿

Es würde mir jetzt (als Oldschool-Rechtsanwalt) nur noch die Fax-Nummer fehlen

Ist erledigt!
