### ISSUE TITLE
[QUESTION] [beA] Wie handhabt ihr die Betreffzeile?

### ISSUE THREAD

**Issue by Dickmaulruessler** [jlawyerorg/j-lawyer-org#1868]
Eine Frage an die Kolleginnen und Kollegen: 

Was tragt ihr im beA in die Betreffzeile ein? Diese wird ja ohnehin ignoriert (VHN2). 
(ich trage dort immer nur "Betreuungsgericht" ein)
Was wäre empfehlenswert?

Zum Nachrichtentext gibt es eine entsprechende [Info auf der Community-Seite](https://www.j-lawyer.org/?p=5036)

Frage an den Chef: Wie wird das hinsichtlich der Betreffzeile - die ignoriert wird und damit soweit ersichtlich unter j-lawyer keinen Sinn macht - zukünftig gehandhabt werden?

**Comment by stm9x9** [comment]
Wird die wirklich ignoriert? Die Gerichte nutzten die jedenfalls in unsere Richtung weiterhin und ausgiebig.

Bei mir kommt das Kurz-Rubrum rein.

**Comment by LazyGuy21No** [comment]
Ich arbeite mit einigen Vorlagen, die dann jeweils einen anderen Betreff mit bringen, z.B.

- AKTE_ZEICHEN: Neues Verfahren zum GERICHT
- AKTE_ZEICHEN: Einreichung zum GERICHT
- EB zurück
- Zustellung im Parteiverkehr

**Comment by Dickmaulruessler** [comment]
(Nur zur Info wie ich darauf komme, unter Betreff die Gerichtsbarkeit einzutragen (dort S.3): [Waschzettel beA-Bedienung.pdf](https://github.com/jlawyerorg/j-lawyer-org/files/10569902/Waschzettel.beA-Bedienung.pdf). Das hatte die RAK Hamburg 2019 versandt. Nein, eingeleuchtet hatte mir das nie. Ja, es ist alt und möglicherweise überholt)

**Comment by LazyGuy21No** [comment]
crazy

**Comment by Dickmaulruessler** [comment]
(Nachtrag: Auch die aktualisierte Version vom ["Waschzettel" (2023)](https://github.com/jlawyerorg/j-lawyer-org/files/10661392/beA-Waschzettel-Hamburg-2023.pdf) enthält gleichlautende Empfehlung).

**Comment by stm9x9** [comment]
Sorry, I didn't get it ... 

![image](https://user-images.githubusercontent.com/29924198/217038410-24c16685-6a5f-416c-90cc-4085b89b10d5.png)

Diese Information ergibt sich aus dem Aktenzeichen. 



![image](https://user-images.githubusercontent.com/29924198/217037847-11dd4fc9-5f4c-4fdd-9645-9ac2a5bc207c.png)

Und "zu b)" das scheint mir auch sehr merkwürdig. Daß das nicht ausgewertet wird, scheint mir ausschließlich für Ausdrucker-Gerichte zuzutreffen. Im Gegentum, der Anzeigename ist in einer elektronischen Akte das Maß aller Dinge.

**Comment by LazyGuy21No** [comment]
Meint ihr, dass es da um eine Hamburger Besonderheit gehen könnte; dass es z.B. für jeden dieser Tätigkeitszweige eine eigene Poststelle gibt?
