### ISSUE TITLE
[FEATURE] [e-mail] Thunderbird-Plugin zum Speichern in Akte

### ISSUE THREAD

**Issue by hackvokat** [jlawyerorg/j-lawyer-org#1869]
Nur mal so als Idee, weil ich mich mit dem j-lawyer E-Mail-Client einfach nicht anfreunden kann.

Besonders vermisse ich eine "Konversations-Ansicht" (threaded view), eine Suche und das Parsen macht immer wieder Probleme (Fehler beim Laden der Nachricht: failed to parse:). Ich weiss aus leidlicher Erfahrung, dass es kein Spaß ist, E-Mail-Clients zu programmieren. Meiner Meinung nach muss j-lawyer auch nicht einen vollständigen E-Mail-Client leisten (aus der Akte Senden würde mir reichen).

Wie wäre es mit einem Thunderbird-Plugin, über das man E-Mails "in die Akten schieben" kann? Dort könnte man dann auch ganze Konversationen bzw. Betreffs (oder ein Kürzel im Betreff) für die automatische Zuordnung nutzen. Ähnlich wie es RA Mirco für Outlook anbietet. Oder man setzt beim Senden einer E-Mail eine Aktenzuordnung, die dann bei allen E-Mails aus dieser Konversation automatisch an j-lawyer samt E-Mail geschickt wird. Da gibt es sicher viele Möglichkeiten, damit alles Wichtige in der Akte landet. Darüber könnten auch nachträglich E-Mails, die man vom Smartphone verschickt hat, automatisch zugeordnet werden.

Die j-lawyer-API gibt das wahrscheinlich schon her, weil ja letztlich nur Dokumente gespeichert werden müssen, sodass man "nur" ein Plugin für Thunderbird programmieren müsste.

Ich nutze bisher Mail unter Mac, aber für so etwas würde ich auch auf Thunderbird umsteigen. Zumindest kommt mir Thunderbird als plattformunabhängiges open-source-Projekt als erstes in den Sinn, mir wäre jeder Client recht.

Dann könnte man sich für alle Mails auf ein Programm konzentrieren und müsste nicht mehr in j-lawyer und einem anderen Client parallel arbeiten.

Was meint ihr dazu?

**Comment by librelegal** [comment]
Thunderbird wird kontinuierlich besser, ich nutze es unter Linux und Windows, offenbar geht es auch gut unter Apple. Es wäre mir sehr recht, wenn Thunderbird genutzt werden könnte.

**Comment by hackvokat** [comment]
Ich nutze es unter Mac und finde gerade die vielen Anpassungsmöglichkeiten super. Auch lassen sich out-of-the-box die Kontakte/Termine aus der j-lawyer-nextcloud über CardDav/CalDav einbinden. Auch iCloud und Exchange lässt sich bewerkstelligen. Auch für den automatischen Upload von Anhängen in nextcloud gibt es ein Plugin.

Vielleicht gibt es ja eine einfache Lösung über ein paar Flags, die man pro Mail setzt, und die dann durch einen Filter an j-lawyer geschickt werden.

**Comment by iradraconis** [comment]
Was sollte denn das Plugin können? Die Mail in einer zugehörigen Akte speichern nebst Anhängen? 

Mit der API sollte das relativ leicht umsetzbar sein. Wie kann das aber mit der Benutzerverwaltung laufen? Für das Speichern in einer Akte von einer externen Anwendung, müssen der Anwendung ja Zugangsdaten für den Server bekannt sein. Wir machen das in vielen Fällen über einen Extra Nutzer (Erfassung), der genutzt wird, um über ein Tool Mandanten- und Aktendaten schnell einzugeben.

**Comment by hackvokat** [comment]
Ziel wäre der Abgleich von Akte und E-Mail-Postfach, damit nichts untergeht.

In dem Plugin müsste man die API-Zugangsdaten hinterlegen. Ob man dort dann einen extra Nutzer oder jeder seinen eigenen nutzt, kann man ja selbst entscheiden.

Ich hätte mir dann ein Kontextmenü beim Klicken auf eine E-Mail vorgestellt mit Optionen wie
- jetzt in Akte speichern (danach Aktenauswahl mit Vorschlag anhand E-Mail / Name oder wenn Gesprächspartner schonmal veraktet wurde, diesen automatisch)
- jede E-Mail von/an diesen Absender automatisch in Akte speichern
- jede E-Mail dieser Konversation automatisch in Akte speichern

Die gleichen Optionen sollte man beim Verfassen einer E-Mail bekommen.

Das löst aber noch nicht das Problem, E-Mails vom Smartphone automatisch in die Akte zu bekommen. Da fällt mir nur ein Kürzel im Betreff ein oder hat jemand noch eine Idee?

**Comment by Dickmaulruessler** [comment]
Wie ich feststelle, liegen jeweils unterschiedliche Motivationen für dieses grundsätzliche Anliegen vor. 

Bei mir ist es so, dass ich auf **Outlook** nicht komplett verzichten möchte. Ich nutze das seit 20 Jahren und möchte das auch weitertun. Besonders wichtig ist mir dort eine sehr gute Suchfunktion, da ich auch über viele Jahre zurück gerne spezielle E-Mails suche. Die bekomme ich unter Outlook über das Plugin Lookeen. (Aber nein: Ich möchte jetzt nicht ein Outlook-Plugin).

Für den Großteil nutze ich die J-Lawyer-E-Mailfunktion schon gerne (den Umweg für die automatische Aktenzuordnung über "Beteiligte" / "E-Mail verfassen" finde ich etwas umständlich - ich würde das unter "Dokumente" logischer finden - aber damit komme ich schon zurecht). 

Für den Versand aus j-lawyer würde ich mir aber wünschen, wenn ich **in j-lawyer eine dauerhafte BCC-Funktion** einrichten könnte (siehe dahzu #1453 ), da ich das manuell einfach zu häufig vergesse oder es mir mit dem manuellen Eintippen einfach zu fehleranfällig ist. Falls das dauerhafte BCC (nur) mit einem Thunderbird-Plugin realisierbar wäre, würde ich diese Variante auch begrüßen. 

Der E-Mail**empfang** aller E-Mails funktioniert bei mir gut. Ich nutze unter Outlook und J-lawyer dasselbe E-Mailkonto, Mails landen daher stets in beiden Programmen und ich kann das gut (theoretisch also "doppelt") weiterbearbeiten. Dafür bedarf es meiner Meinung nach kein gesondertes E-Mail-Plugin in j-lawyer.  

Für Anwalts-Mails, die ich **über Outlook versende** (Gründe: vor allem wegen der dort sehr guten Formatierungsmöglichkeiten) nutze ich ein BCC zu meiner eigenen Adresse (das ist unter Outlook generell einfacher, da es dort auch eine Autocomplete-Funktion gibt). Die Mail landet dann auch wieder im Posteingang von J-lawyer und kann dort dann wiederum manuell der Akte zugeordnet werden.
