### ISSUE TITLE
[FEATURE] Schnellerfassung (Kontakt) um weitere Felder ergänzen

### ISSUE THREAD

**Issue by LazyGuy21No** [jlawyerorg/j-lawyer-org#1877]
<img width="655" alt="image" src="https://user-images.githubusercontent.com/56734761/220263513-17cf1931-ea77-4cbb-b4de-f71531f2dc82.png">

In der Schnellerfassung gibt es Werte, die wir nie eintragen (Homepage); dafür fehlen uns die Rechtsform und die Registerdaten.

Wir würden uns freuen, wenn es eine Möglichkeit gäbe, die Schnellerfassung zu "customizen", um festlegen zu können, welche Felder angezeigt werden und welche nicht.

**Comment by j-dimension** [comment]
> Ob das aber wirklich konfigurierbar sein muss oder ob der großen Masse an Nutzern schon mit 2 oder 3 Feldern mehr gedient wäre, weiß ich nicht...

Schön, dass eine solche Anmerkung aus der Anwenderschaft kommt. Das wäre auch mein Favorit. Ein paar zusätzliche Felder sind in 30-45 Minuten hinzuzufügen. Eine Konfigurierarbeit bedeutet einen Aufwand von 6+ Stunden, und generiert fortlaufenden Aufwand (bei jeder Änderung am Datenmodell der Adressen).

**Comment by j-dimension** [comment]
> Wer hätte denn noch Sonderwünsche für zusätzliche Felder?

Anrede und Grußformel sind sicher auch gute Kandidaten.

**Comment by LazyGuy21No** [comment]
Das ist eigentlich eine gute Idee

**Comment by LazyGuy21No** [comment]
Dann rege ich folgende zusätzliche Felder an:
- Rechtsform
- Registergericht 
- Registernummer
- Geburtsort

Homepage kann mE raus

**Comment by Dickmaulruessler** [comment]
- ein kleines Freitext-Feld ("Notizen")

Kann das auch zwei- oder mehrspaltig werden? Hat es ein Grund, dass das bisher generell nur wenig erfolgt?
Hier wäre es glaube ich besonders sinnvoll.

**Comment by j-dimension** [comment]
![grafik](https://github.com/jlawyerorg/j-lawyer-org/assets/3729754/64022e4c-74b2-41d5-ad90-18a2c06e503f)

**Comment by Dickmaulruessler** [comment]
Ich weiß nicht, wie du dich in #1132 entschieden hast, ich gebe dies hier einfach nur noch einmal zur Kenntnis.
