### ISSUE TITLE
[BUG] Email: TLS wird als SSL tituliert

### ISSUE THREAD

**Issue by papiertiger960ff** [jlawyerorg/j-lawyer-org#1882]
Ausfädelung aus #1881:

Im Konfigurationsdialog für den Mailclient wird TLS fälschlich als SSL tituliert. Sollte geändert werden.

**Comment by j-dimension** [comment]
Geht es um den Versand oder den Empfang?

**Comment by papiertiger960ff** [comment]
Beides. Ist aber eigentlich nur ein kosmetisches Problem.

**Comment by j-dimension** [comment]
In der API von JavaMail heißen die Konfigurationen alle irgendwas mit SSL. Thunderbird nennt das "SSL/TLS".

**Comment by papiertiger960ff** [comment]
Jupp. Aus historischen Gründen. In modernen „SSL-Implementierungen“ wird aber i. d. R. ausschließlich der SSL-Nachfolger TLS unterstützt, während das eigentliche SSL gesperrt ist, weil es hoffnungslos veraltet und unsicher ist. Ist schon seit vielen Jahren so. Ironischerweise gilt das (in der Standardkonfiguration) auch für OpenSSL, das somit eigentlich OpenTLS heißen müsste.
