### ISSUE TITLE
[BUG] [e-mail] Defaultport für Submission sollte 587 sein, nicht 25

### ISSUE THREAD

**Issue by papiertiger960ff** [jlawyerorg/j-lawyer-org#1884]
Ausfädelung aus #1881:
Der Default-Port für SMTP Submission sollte 587 und nicht 25 sein. Port 25 ist sehr streng reglementiert, ich musste für meinen eigenen Mailserver erst kürzlich einen Genehmigungsantrag mit 3fachem Durchschlag schreiben, um den benutzen zu dürfen. Von daher halte ich es für verfehlt, diesen Port für die einfache Einlieferung zu nutzen.

**Comment by j-dimension** [comment]
Bin unsicher. Der Client schlägt den Port 25 ja nicht vor (bei Anlegen eines neuen Postfaches ist der Port leer), es handelt sich um einen Standardwert von JavaMail. Wer 587 nutzen möchte, trägt den einfach ein?

Ich habe hier tatsächlich mehrere Postfächer die ganz normal 25 nutzen (auch wenn 587 gebräuchlicher ist).
