### ISSUE TITLE
[FEATURE] Virtuelles Dateisystem

### ISSUE THREAD

**Issue by papiertiger960ff** [jlawyerorg/j-lawyer-org#1885]
ICh hätte eine Idee.
Wie wäre es, wenn j-Lawyer ein virtuelles Dateisystem hätte, über das man auf den Aktenbestand von j-Lawyer per Dateimanager zugreifen könnte? Als Schnittstelle könnte ich mir WebDAV, FTP, FUSE oder KIO vorstellen.

**Is your feature request related to a problem? Please describe. / Welches Problem soll durch die Erweiterung / Verbesserung gelöst werden?**
Ein Stück weit, ja. Es gibt in der Akte keine Möglichkeit für Drag&Drop und auch das Umbenennen von Dateien mit F2 klappt nicht.
Außerdem könnte man sich in vielen Anwendungsfällen das ständige Hin und Her mit EXport und Import sparen.

**Comment by j-dimension** [comment]
> keine Möglichkeit für Drag&Drop

zur Info: das Ziehen von Dateien in die Dokumentenliste funktioniert, der umgekehrte Weg nicht

**Comment by j-dimension** [comment]
> könnte man sich in vielen Anwendungsfällen das ständige Hin und Her mit EXport und Import sparen.

was sind das für welche?

**Comment by papiertiger960ff** [comment]
> > könnte man sich in vielen Anwendungsfällen das ständige Hin und Her mit EXport und Import sparen.
> 
> was sind das für welche?

qeS und ERV mit externer Software

**Comment by papiertiger960ff** [comment]
Hmmm. ICh hätte schwören können, das Drag&Drop das letzte Mal, als ich es versucht habe, nicht funktioniert hat.

**Comment by stm9x9** [comment]
> > > könnte man sich in vielen Anwendungsfällen das ständige Hin und Her mit EXport und Import sparen.
> > 
> > 
> > was sind das für welche?
> 
> qeS und ERV mit externer Software

ich mache die qeS extern per SecSigner. Im Arobat mit dem Secsigner-Plugin. Geht wunderbar mit der temporären Datei, die jl für Acrobat öffnet. Es gibt nur eine Fehlermeldung zwischendurch, weil Acrobat die Datei sperrt und jl sie aber gerne mal speichern möchte. Macht aber nix.
