### ISSUE TITLE
[BUG] Kontrast / Transparenz Desktop

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#1892]
aktuelle 2.3.0.1

könnte der Grad der Transparenz der Hintergründe der Desktop-Einträge nochmal überdacht werden? Das ist SEHR schwer zu lesen.

![image](https://user-images.githubusercontent.com/29924198/224176925-bb0fa752-e0ef-4db1-ab1f-0abf96c32fbe.png)

**Comment by j-dimension** [comment]
Ich glaube das ist insbesondere auch diesem speziellen Hintergrundbild geschuldet, das im Gegensatz zu den anderen viel helle Flächen hat. 

Ggf. Hintergrundbilder erstmal deaktivieren.

**Comment by stm9x9** [comment]
leider nicht nur bei dem Hintergrundbild

![image](https://user-images.githubusercontent.com/29924198/224181085-df9ef611-ae99-4e0d-9e38-a64c403fd277.png)

Ich meine, bei der letzten Version war die Transparenz einfach nicht so hoch eingestell.t

**Comment by j-dimension** [comment]
Welche "letzte" meinst Du?

**Comment by stm9x9** [comment]
hier ist dann zb zuviel Grün im Bild:

![image](https://user-images.githubusercontent.com/29924198/224181718-d6d88de3-6ae1-4d09-a14c-28d9d60b9fcb.png)

**Comment by stm9x9** [comment]
> Welche "letzte" meinst Du?

die 2.2.x die bis eben hier lief vor dem Update

**Comment by j-dimension** [comment]
Alles gutes Feedback, aber jetzt erstmal zu spät. Bitte wie oben erwähnt verfahren.

**Comment by PBaumfalk** [comment]
Könnten wir ggfs. auf einen weißen Hintergrund mit schwarzer Schrift wechseln? Invertiert finde ich nicht so gut.

**Comment by stm9x9** [comment]
hm ... soooo dolle finde ich den Kontrast ohne Hintergrundbild aber auch nicht. Sowohl das Rot ist zu schwach, die Etiketten verschwinden fast ... und so richtig erkennbar ist das weiß auch nicht :-( 

![image](https://user-images.githubusercontent.com/29924198/225158791-c065a8b5-6840-4401-bff2-419ad9a3e33c.png)
![image](https://user-images.githubusercontent.com/29924198/225158817-2c5e4757-76fb-4ca5-ad33-89c1f477ce2b.png)

**Comment by j-dimension** [comment]
Installer mit höherem Kontrast auf dem Desktop: 
https://cloud.j-dimension.com/index.php/s/wscJLx3KDCKoEWm?path=%2FVorschau%2FClient

**Comment by stm9x9** [comment]
egal ob mit Hintergrundbild oder ohne: DEUTLICH besser lesbar. Danke!
