### ISSUE TITLE
[FEATURE] Adressen: Etiketten vorziehen

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#1893]
Ist für diesen großen leeren Platz rechts schon was geplant? Könnten da vielleicht die Personen-Etiketten hinziehen? Bei Akten und Dateien sind sie immer direkt zu sehen, nur bei Personen nicht. Aber sowohl "inhaftiert" als auch "Problemmandant" :-) sollte man immer sofort sehen!

![image](https://user-images.githubusercontent.com/29924198/224177778-2b0447b2-07a6-422c-81e5-b84782a2d754.png)

**Comment by j-dimension** [comment]
großer Screen:

![grafik](https://user-images.githubusercontent.com/3729754/226478494-a044ab3c-7eca-4130-a6c9-6abacf745478.png)

**Comment by j-dimension** [comment]
kleiner Screen:

![grafik](https://user-images.githubusercontent.com/3729754/226478598-98a1b613-d131-476f-9054-f9dcb759ae82.png)

**Comment by Dickmaulruessler** [comment]
Fein!
