### ISSUE TITLE
[BUG] automatische Dateinamenerweiterung im Zuordnungsdialog - cursorposition

### ISSUE THREAD

**Issue by Maz111111** [jlawyerorg/j-lawyer-org#1896]
Wenn man im Zuordnungsdialog die Datei umbenennt und dabei auch die Erweiterung löscht, springt der Cursor im Rahmen der automatischen Dateinamenerweiterung immer ans Ende des Dateinamens - also hinter die Erweiterung.
Dies macht er bei jeder Zeicheneingabe.

Das führt z.B. zu S.pdfc.pdfh.pdfr.pdfe.pdfi.pdfb.pdfe.pdfn.pdf 

Der Cursor müsste nach Durchführen der automatischen Erweiterung wieder dort stehen, wo er vorher war.

**Comment by Dickmaulruessler** [comment]
![Testakte](https://user-images.githubusercontent.com/46451749/225708053-0ff7c32c-28fb-49ff-b3c5-18d84059371d.jpg)

Hier wurde der obige Dateiname gelöscht und dann versucht, den neuen Dateinamen "Testakte" zu vergeben.
