### ISSUE TITLE
[BUG] Aktensuche: "erstellt" und "archiviert"-Datumsangaben mit falscher Farbe

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-org#1899]
Erst mal ganz herzlichen Dank für das neue Release und die ganze Arbeit. Das sieht alles sehr gut aus und erleichtert sehr unsere Arbeit.
1ter kleiner Bug gesichtet: Das neue Erstelldatum der Akte erscheint invertiert, erst nach dem Anklicken stimmen die Farben.

**Comment by j-dimension** [comment]
Notiz an @j-dimension : es wird für diese Spalten kein QuickArchiveFileSearchCellRenderer verwendet, sondern ein normaler DateRenderer
