### ISSUE TITLE
Volltextsuche geht nicht mehr

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-org#1902]
Nach dem Update geht die Volltextsuche nicht mehr. Man soll den Dienst (Serverdienst?) stoppen und den Index wieder aufbauen. Mehr habe ich das zu nicht gefunden Aber wie baut man den Index neu auf (wo welcher Befehl?) oder geht das dann automatisch? Habe den HP-Microserver laufen zur Erinnerung...

**NOTE: Please search existing tickets to avoid duplicates **
**HINWEIS: Bitte vorab die Ticketsuche verwenden, um Doppeleinträge zu vermeiden **

**Describe the bug / Fehlerbeschreibung**
(todo: a description of the bug / eine Beschreibung des Fehlers)

**To Reproduce / Schritte zum Nachvollziehen**

1. Go to / Gehe zu '...'
2. Klicke auf / Click on '....'
4. Error message / Fehlermeldung: '...'

**Expected behavior / Erwartetes Verhalten**
Eine Beschreibung des erwarteten Verhaltens.

**Screenshots**
Falls relevant, Screenshot beifügen.

**Environment / verwendete Umgebung:**
 - OS / Betriebssystem:
 - j-lawyer.org Version:

**Additional context / Sonstiges**

**Comment by j-dimension** [comment]
Einstellungen - Dokumente - Dokumentensuche
