### ISSUE TITLE
[BUG] Doppelpunkt in Dateinamen führt zu Fehler

### ISSUE THREAD

**Issue by PBaumfalk** [jlawyerorg/j-lawyer-org#1903]
Ich weiß gar nicht, wie ich das gefunden habe, aber uns ist folgender Fehler aufgefallen:

Wenn ein Doppelpunkt im Dateinamen ist, spuckt der J-Lawyer einer Fehlermeldung aus. Man kann wohl Doppelpunkte eingeben, wenn man das Dokument aus Scans übernimmt.

**Comment by PBaumfalk** [comment]
Keine Doppelpunkte im Dateinamen. Er schmeißt doch ansonsten aus, dass es die Datei nicht gibt (bei Windows)...Fehlermeldung hatte mein Mitarbeiter mit Windows-Rechner.

**Comment by stm9x9** [comment]
Das wäre IMHO ein Punkt für die Idee, den "Dateinamen", also das was dem Nutzer angezeigt wird, von dem technischen Dateinamen auf filesystem-Ebene zu trennen. Dann gibt es keine Probleme mit Transferierungen oder so und man kann den Anzeigenamen dennoch leserlicher machen.

**Comment by j-dimension** [comment]
@stm9x9 das ist ja jetzt schon so, schau mal in das Datenverzeichnis. Nur wenn ein Dokument am Client bearbeitet wird, wird wieder der "normale" Dateiname verwendet, sonst hätten die LibreOffice / Word-Fenster völlig nichtssagende Titel.

**Comment by j-dimension** [comment]
@PBaumfalk der vorgeschlagene Dateiname hat diese Zeichen bereits herausgefiltert. Es war noch möglich eine manuelle Eingabe solcher Zeichen zu tätigen - das wird der Dialog nun unterbinden.
