### ISSUE TITLE
[TASK] Felder "Gegenstandswert" und "Schadennummer" verschieben

### ISSUE THREAD

**Issue by j-dimension** [jlawyerorg/j-lawyer-org#1904]
Anwenderfeedback: 

Das Feld „Gegenstandswert“ ist sicherlich vorteilhaft, um schnell in der Akte einen Überblick zu können, was der Gegenstandswert und damit der maßgebliche Faktor der RVG-Berechnung ist. Ich halte es jedoch für sinnvoller, diesen Gegenstandswert unter dem Reiter „Finanzen“ aufzuführen. Denn dort wird der Gegenstandswert tatsächlich relevant. Hier muss auch die Änderung erfolgen, wenn sie notwendig ist.

Das Feld “Schadennummer“ ist hier aus mehrfachen Gründen fehl am Platz. Zum einen ist schon nicht klar, um welche Schadensnummer es sich handeln soll. So kann ich in einer Akte theoretisch mehrere Schädiger haben. Klassischerweise kommt es jedoch beim Verkehrsunfallrecht dazukommen, dass sowohl die gegnerische Haftpflichtversicherung eine Schadennummer vergibt, als auch die eigene Rechtsschutzversicherung. Da führt die „Schadennummer“ mehr zur Verwirrung als zur Aufklärung. Die „Schadennummer“ gehört meines Erachtens zwingend in die aktenspezifischen Adressdaten des Dritten. Unabhängig davon verstehe ich nicht, welchen Mehrwert das bringen soll, die (nicht zugeordnete) Schadennummer auf diesem Reiter unterzubringen.

**Comment by j-dimension** [comment]
@RA-crm

**Comment by Dickmaulruessler** [comment]
Dem kann ich mich nur anschließen: Weder der Gegenstandswert und schon gar nicht die Schadensnummer "verdienen" eine so promiente Stelle ganz am Anfang. Nicht selten gibt es gar keinen Gegenstandswert und eine "Schadensnummer" ist in meinem langen Anwaltsleben (Strafrecht, Betreuungsrecht) noch nicht ein einziges Mal aufgetaucht...
Bei den "Finanzen" wäre es in der Tag gut aufgehoben.

**Comment by j-dimension** [comment]
Für den Moment habe ich beide Felder in den Tab "Finanzen" geschoben.

**Comment by Dickmaulruessler** [comment]
Zur Schadennummer:
Oder vielleicht gar nur im Falldatenblatt? 
Oder wer es unbedingt braucht, kann auch ein eigenes Feld dafür nutzen.

**Comment by RA-crm** [comment]
> @RA-crm wäre die Schadennummer nicht eigentlich identisch mit dem "Zeichen" einer Beteiligten, wenn Beteiligte = Versicherung? Braucht es dieses Feld überhaupt?

meines Erachtens braucht es das nicht. Die Schadensnummer kommt in das Feld "Zeichen" im Aktenbezogenen Adresssatz.
