### ISSUE TITLE
[TASK] Dialog "Akte suchen" bei Drebis überflüssig

### ISSUE THREAD

**Issue by Linkki2021** [jlawyerorg/j-lawyer-org#1906]
Seit dem Update gibt es den neuen Dialog für die verschiedenen Posteingänge.

So sinnvoll ich die Verbesserungen der Etikettierung finde: im Falle von Drebis-Eingängen ist der erste Schritt "Akte suchen" m.E. überflüssig, auch wenn die korrekte Akte immer zuoberst vorgeschlagen wird.

Der Charme der Drebis-Kommunikation ist ja gerade, dass klar ist, wo das Dokument hinmuss, da die Verbindung schon mit Übermittlung hergestellt wurde.

Wenn sich der Step für den Drebis-Dialog deaktivieren ließe wäre das super, wenn aber auch die anderen Eingänge wie z.B. Mail - wo es sinnvoll ist - betrofffen wären, dann lieber nicht.

**Comment by PBaumfalk** [comment]
Nein, das ist falsch.

Wenn die Versicherung keine Schadennummer angibt (und das ist mir bei der Roland häufig passiert), dann verbleibt die Nachricht für immer im Posteingang.
Mit freundlichen Grüßen / Kind regards

Patrick Jan Baumfalk
Rechtsanwalt

BAUMFALK - Rechtsanwaltskanzlei

Telefon: + 49 (0) 2273 40 68 504
Telefax: + 49 (0) 2273 59 03 565
Email: ***@***.*** <mailto: ***@***.***>
web: https://www.kanzlei-baumfalk.de <https://www.kanzlei-baumfalk.de/>
Postanschrift: Postfach 1233, 50141 Kerpen

Hauptkanzlei: Hauptstraße 147, 50169 Kerpen
Zweigstelle Witten: Berliner Str. 4, 58452 Witten
Zweigstelle Köln: Gürzenichstr. 25, 50667 Köln

Telefonische Sprechzeiten:

Mo, Di, Do
10:00 Uhr bis 13:00 Uhr
14:00 Uhr bis 17:00 Uhr
Mi, Fr
10:00 Uhr bis 13:00 Uhr

Persönliche Besprechungstermine bitte nur nach vorheriger Vereinbarung

**Comment by Linkki2021** [comment]
Verstehe ich zwar technisch nicht, denn die Verknüpfung läuft doch nicht über die Schadennummer, aber wenn das so ist, dass Nachrichten ins Leere laufen; i.O., danke für das Feedback!

Wir hatten so einen Fall trotz fleißiger Drebis-Nutzung schlicht noch nicht.

**Comment by j-dimension** [comment]
Dieser Schritt erlaubt auch das Auswählen eines Ordners, der dann für die Dokumente vorselektiert ist. Das ist natürlich nur dann hilfreich, wenn man mit Ordnern arbeitet - weiß nicht ob das für Euch relevant ist, @Linkki2021

**Comment by Linkki2021** [comment]
Wir arbeiten nicht mit Unterordnern, aber natürlich tun das viele. Den Zwischenschritt hatte ich nicht bedacht. Wie wäre es mit der Möglichkeit, einen Standardordner auszuwählen oder eben auch keinen, so dass das Ordner-Auswählen potentiell entfallen kann?
