### ISSUE TITLE
[BUG] - korrektur des Wiedervorlage Grundes 

### ISSUE THREAD

**Issue by RA-crm** [jlawyerorg/j-lawyer-org#1909]
Ich hoffe es ist ein Bug und kein Feature.

Bereits seit der 2.2 hat sich das Verhalten bei der (erstmaligen) Erstellung einer WV geändert. Gibt man etwa als Grund ein:

"Rückmeldnug von Mtd auf Mail vom 15.03."

und möchte die Tippfehler "Rückmeldnug" und "Mtd" korrigieren, wird nach löschen des "u" der nachfolgende Text komplett makiert und mit dem nächsten Zeichen gelöscht.

Besonders hinderlich ist dieses Verhalten bei einer vorgegenbenen WV wie 
"KoNo ... vom ... Zahlung erfolgt?"
denn beim Eintragen der KoNo Nummer wird der nachfolgenden Text gelöscht.

Das passiert nicht, wenn die WV einmal eingetragen ist und dann lediglich "bearbeitet" wird. Dies ist aber m.E. ein unnötiger Umweg.

**Comment by j-dimension** [comment]
Ich habe dort eine Komponente eingebaut, die eine automatische Vervollständigung unterstützt. Ich muss schauen ob ich dort überhaupt selbst etwas am Verhalten ändern kann.

**Comment by RA-crm** [comment]
In der Praxis nervt mich diese Autovervollständigung schon ziemlich. Die Option, als Admin so ein Feature Kanzleiweit einfach ein- und auszuschalten, liegt wohl nicht auf dem Tisch, oder?

**Comment by j-dimension** [comment]
Auto-Vervollständigung für Kalendereintrage entfernt.
