### ISSUE TITLE
Mailclient macht zuviele IMAP-Verbindungen auf einmal auf

### ISSUE THREAD

**Issue by papiertiger960ff** [jlawyerorg/j-lawyer-org#1914]
![connection_excess](https://user-images.githubusercontent.com/85453166/226353615-ff9db50b-e485-4d2f-80c5-4a413aaf942e.png)
Hier die Fehlermeldung. Mein Verdacht ist, dass der Mailclient seine IMAP-Verbindungen nicht ordnungsgemäß schließt und sich dadurch auf dem Server eine größere Anzahl an hängenden Verbindungen ansammelt.

Ich hatte ursprünglich vermutet, dass mein Double NAT an diesem Verhalten mit Schuld sein könnte. Aaaaaber: einer von den beiden Mailservern ist IPv6-only. Damit scheidet die NAT-Situation als Ursache aus. Paketfilter im Router ist ebenfalls deaktiviert.

**Environment / verwendete Umgebung:**
 - OS / Betriebssystem: Debian
 - j-lawyer.org Version: 2.0.1.0

**Comment by j-dimension** [comment]
Das hört sich nach einem Dovecot in Standardkonfiguration an, der nur 10 parallele Verbindungen max zulässt. Das mag für einen Einzelnutzer auf dem Mailserver funktionieren, ist aber allgemein sehr niedrig angesetzt. 

Der j-lawyer Client nutzt einen Verbindungspool, um das ständige Auf- und Abbauen der Verbindungen zu reduzieren. 

Eine Anpassung von mail_max_userip_connections am Mailserver wird das Problem beheben.
