### ISSUE TITLE
[BUG] Speicherfehler Falldatenblätter (forms-internal)

### ISSUE THREAD

**Issue by bmle17** [jlawyerorg/j-lawyer-org#1915]
Die Eingabe bei eingefügten (forms-internal) Falldatenblätter werden die Eingaben nicht übernommen, bis die Akte gespeichert und geschlossen wurde, bevor nicht eine weitere Akte geladen wurde. Bei dem Schließen der Anwendung nach Eingabe von Daten in dem Fallblatt und nach dem Speichervorgang werden die Eingaben nicht übernommen.   

**To Reproduce / Schritte zum Nachvollziehen**

1. Go to / Gehe zu ' Falldatenblätter- EIGENES Falldatenblatt erstellen'
2. Klicke auf / Click on '.Mache EINGABE, klicke speichern, schließe nach "bereit" - Angabe die Anwendung'
4. Error message / Fehlermeldung: ' Eingabe wird nicht übernommen'

**Expected behavior / Erwartetes Verhalten**
Übernehmen der Eingabe nach dem Speichervorgang ohne neues laden einer weiteren Akte.

**Environment / verwendete Umgebung:**
 - OS / Betriebssystem: debian 11
 - j-lawyer.org Version:  2.1.0.0.

**Comment by j-dimension** [comment]
Bitte auf 2.3 updaten, wo dieses Thema adressiert ist: https://github.com/jlawyerorg/j-lawyer-org/issues/1843
