### ISSUE TITLE
[BUG] Historie: Fehlender Nutzer bei manuellem Eintrag

### ISSUE THREAD

**Issue by Utzi81** [jlawyerorg/j-lawyer-org#1918]
In der Historie wird in der Clientversion 2.3.0.1 in Verbindung mit meiner J-Lawyer-Box kein Nutzername mehr bei manuellen Einträgen mehr hinterlegt. Das sieht dann so aus (siehe EInträge von 21:44h und 21:45h):

![image](https://user-images.githubusercontent.com/65081404/226463201-5c0dd15b-f9bd-4e78-82de-6478d5a89cd6.png)

Gerade bei manuellen Einträgen sollte nachvollziehbar sein, wer diese angelegt hat. Daher Danke für entsprechende Korrektur!

LG
Christopher

**Comment by j-dimension** [comment]
Danke, ist im aktuellen Entwicklungsstand nun behoben.

**Comment by Utzi81** [comment]
Wow, das ging ja schnell! Top!

Viele Grüße

Christopher Utz

***@***.***
– von meinem Telefon gesendet

Am 20. März 2023, 22:30 +0100 schrieb Jens Kutschke ***@***.***>:
