### ISSUE TITLE
[Ausrichtung Text] bei Grunddaten in der Adressverwaltung 

### ISSUE THREAD

**Issue by RA-crm** [jlawyerorg/j-lawyer-org#1919]
Bei den Grunddaten in der Adressverwaltung ist die Anordnung der Felder
geboren:
in:
gestorben:

nicht mehr in einer Linie zu den jeweiligen Feldern.

Da meldet sich bei mir mein innerer Monk 
;-) @PBaumfalk 

![grafik](https://user-images.githubusercontent.com/46541381/226657351-10b809f9-b9e1-4b5f-ad4d-431db560dd5c.png)

**Comment by j-dimension** [comment]
sollte via #1894 bereits behoben sein
