### ISSUE TITLE
[BUG] Beteiligte verschwinden aus Akte

### ISSUE THREAD

**Issue by iradraconis** [jlawyerorg/j-lawyer-org#1922]
Bei uns sind in den vergangenen Tagen in einigen Akten Beteiligte "verschwunden", obwohl wir die schon dreimal hinzugefügt hatten.  Von einem Kollegen (andere Kanzlei) habe ich dasselbe gehört. Hat das noch jemand beobachten können? 

Die Adressen sind dabei noch vorhanden, lediglich die Beteiligten verschwinden aus der Akte.

Soweit das gestern aufgefallen ist, war es die Vorschau Client Version 2.3.0.1 und der heute aktuelle Server

**Comment by PBaumfalk** [comment]
Ich hatte auch das gleiche Problem und habe gedacht, ich wäre zu dumm zum speichern...
Mit freundlichen Grüßen / Kind regards

Patrick Jan Baumfalk
Rechtsanwalt

BAUMFALK - Rechtsanwaltskanzlei

Telefon: + 49 (0) 2273 40 68 504
Telefax: + 49 (0) 2273 59 03 565
Email: ***@***.*** <mailto: ***@***.***>
web: https://www.kanzlei-baumfalk.de <https://www.kanzlei-baumfalk.de/>
Postanschrift: Postfach 1233, 50141 Kerpen

Hauptkanzlei: Hauptstraße 147, 50169 Kerpen
Zweigstelle Witten: Berliner Str. 4, 58452 Witten
Zweigstelle Köln: Gürzenichstr. 25, 50667 Köln

Telefonische Sprechzeiten:

Mo, Di, Do
10:00 Uhr bis 13:00 Uhr
14:00 Uhr bis 17:00 Uhr
Mi, Fr
10:00 Uhr bis 13:00 Uhr

Persönliche Besprechungstermine bitte nur nach vorheriger Vereinbarung

**Comment by j-dimension** [comment]
Ich brauche eine Klicksequenz hierfür, da ich es nicht reproduzieren kann.

**Comment by iradraconis** [comment]
Soweit ich es verstanden habe von meiner Mitarbeiterin war so, dass der Beteiligte angelegt war, die Akte gespeichert war, später noch einmal in die Akte hinein gegangen worden ist, und der Beteiligte dann weg war. schwierig, hier eine Klicksequenz wieder zu geben. :-)

**Comment by j-dimension** [comment]
Dann bleibt das Ticket hier erstmal offen stehen. 

Ohne Zuarbeit komme ich da nicht weiter.

**Comment by iradraconis** [comment]
Was hilft denn da eher? Client log oder Server log? Wenn ich es zeitlich eingrenzen kann von gestern, kann ich die log Datei vom Server schicken

**Comment by Dickmaulruessler** [comment]
Macht es nicht vielleicht SINN, das etwas breiter zu beobachten und Jens dann nur eindeutige Vorkommnisse zu schicken?

Ich glaube der Chef braucht auch mal ein paar freie Tage nach dem BRAK-Mist gestern...

**Comment by iradraconis** [comment]
> Macht es nicht vielleicht Sinn, das etwas breiter zu beobachten und Jens dann nur eindeutige Vorkommnisse zu schicken?
> 
> 
> 
> Ich glaube der Chef braucht auch mal ein paar freie Tage nach dem BRAK-Mist gestern... 

Dem Ticket war keine zeitliche Vorgabe beigefügt. Ich erstelle die Tickets, wie ich es nebenbei schaffe. Sonst geht das bei mir unter. Da es keine konkrete Klicksequenz gibt, und ich es selbst nicht reproduzieren kann, konnte das Ticket nur so formuliert werden. Aber trotzdem Danke für den Hinweis.  

Den Grund für das Ticket finde ich schon wichtig. Beteiligte sollten nicht verschwinden. Ich bin sicherlich der letzte, der Jens seinen verdienten Erholungsurlaub/Wochenende absprechen möchte.

**Comment by j-dimension** [comment]
> Was hilft denn da eher? Client log oder Server log? Wenn ich es zeitlich eingrenzen kann von gestern, kann ich die log Datei vom Server schicken

Da ich es nicht eingrenzen kann - beides. Bin da völlig im Unklaren.

**Comment by Dickmaulruessler** [comment]
@iradraconis ja, weiß ich bei dir. (Herz-Emoji) War nicht so gemeint. 

Wenn etwas "verschwindet", wird so aber schnell erheblicher Druck aufgebaut.

Jens, mach mal Wochenende!

**Comment by j-dimension** [comment]
@iradraconis @PBaumfalk bisher habe ich keine weitere Rückmeldung dieser Art von Anwender/-innen erhalten. Habt Ihr das nochmal beobachtet?

**Comment by iradraconis** [comment]
Ich frage noch mal nach...
eine Log-Datei habe ich bisher nicht geschickt, weil nur der Zeitpunkt bekannt war, wann es aufgefallen ist und nicht, wann die Daten bzw. die Beteiligten verschwunden sind.
