### ISSUE TITLE
[TASK] Dateiname für Dokument-Etiketten anklickbar

### ISSUE THREAD

**Issue by Dickmaulruessler** [jlawyerorg/j-lawyer-org#1927]
Bei den Akten-Etiketten auf dem Desktop lässt sich die Akte anklicken. 
Bei den Dokumenten-Etiketten aber nicht das Dokument (im Screenshot: Drei Dokumente derselben Akte).

Die Dokumente sollten nach meinem Dafürhalten anklickbar sein und dass man dann direkt im Reiter Dokument beim Dokument selbst landet. Aktuell kann man nur dreimal ein und diesselbe Akte anklicken. 

![Etiketten](https://user-images.githubusercontent.com/46451749/228248313-f161a0c6-e9e3-489e-9b4f-cf35349df736.jpg)

(Huch, ich finde gar kein bestehendes Ticket dazu. Das muss irgendeinen besonderen Grund haben...)

**Comment by j-dimension** [comment]
Wenn Du auf die Akte klickst, kommst Du direkt zum Dokument.

**Comment by Dickmaulruessler** [comment]
oh ja. 
Für mich ist das so aber nicht logisch. Siehst du das auch so?
Oder geht es nicht anders?

**Comment by Dickmaulruessler** [comment]
Noch nicht zu Ende gedacht - aber ein paar Gedanken:

Meine "Logik" wäre, dass es das Ziel ist, weshalb es auf dem Desktop aufgrund des Etiketts angezeigt wird. 
Also vor allem: Dokument-Etikett sollte zum jeweiligen Dokument führen. Akten-Etikett zur Akte.

Das ist ja gerade bei mehreren Dokument-Etiketten innerhalb einer Akte interessant. So wie an meinem obigen Beispiel (3 neu gescannte Dokumente aus einer Akte). 

Das nah-beieinander-Liegen der Klick-Bereiche fände ich jetzt nicht so problematisch, da man ja nicht "komplett woanders", sondern in der Akte nur einen Reiter weiter landet.

**Comment by j-dimension** [comment]
> Dokument-Etikett sollte (auch beim Dokument selbst) zum jeweiligen Dokument führen. Akten-Etikett zur Akte.

So sollte das bereits sein. Tut es das nicht?

**Comment by Dickmaulruessler** [comment]
Ja, schon, aber eben nur dort wo oben der Aktentitel (klickbar) steht und nicht weiter unten wo der Dateiname (nicht klickbar) steht. 
Ich könnte mir die Lösung so vorstellen, dass das gesamte Feld oder eben beides (Titel und Dateiname) klickbar sind und bei einem Dokument-Etikette beides zum Dokument führt.
