### ISSUE TITLE
urteile-gesetze.de: Gesamtsuche liefert ausschliesslich Gesetze

### ISSUE THREAD

**Issue by j-dimension** [jlawyerorg/j-lawyer-org#193]
Wird der Request mit zwei Kategorien abgesetzt:
`{\"categories\":[\"rechtsprechung\", \"gesetze\"]}`
so enthält das Ergebnis ausschliesslich Gesetze.

**Comment by danbeck** [comment]
Es handelt sich dabei um einen Fehler der externen API von urteile-gesetze. Siehe Issue https://github.com/neo-search/urteile-gesetze-web/issues/6.

 Der Fehler ist behoben und deployt.

**Comment by j-dimension** [comment]
Wow, das nennt man "agil". Danke!
