### ISSUE TITLE
[FEATURE] Dateiname einer Notiz in der Detailansicht aufnehmen

### ISSUE THREAD

**Issue by Dickmaulruessler** [jlawyerorg/j-lawyer-org#1930]
Ich hätte Anregungen zu der Notizfunktion. Ich glaube du nutzt dafür eine fertige Komponente und die Änderungsmöglichkeiten sind sehr begrenzt (so schon [dort](https://github.com/jlawyerorg/j-lawyer-org/issues/1750#issuecomment-1243035024)). Aber ich lege trotzdem einmal los:

In einer Notiz nutze ich nach Möglichkeit den linken Dateinamen-Bereich für sehr kurze Notizen, denn das geht am Schnellsten **und man sieht es sofort inhaltich schon in der Liste der Dokumente** (gerade das finde ich besonders praktisch!). 
Bei (häufigen) kurzen Notizen ist das alles gut und die Sache ist kurz und knapp erledigt. 
Wenn aber der Text länger wird, wird er natürlich an der rechten Seite abgeschnitten und ist nur in der Vollbild-Ansicht überhaupt sichtbar. 

Könnte der linke Text auch im rechten Feld - dort dann in voller Länge - stehen? 
Dort wie ich hier gezeigt habe oder weiter unten **(egal wo **- nur nicht abgeschnitten).**** 
.

![Notiz](https://user-images.githubusercontent.com/46451749/228619117-18f9c123-8f25-4b1d-a70f-761fde8e09b7.jpg)
.
.
.
Das wäre auch unter einem weiteren Gesichtspunkt sinnvoll: Wenn man den rechten Teil im großen Fenster öffnet, ist dieser Text-Bereich (= der HTML-Dateiname) sehr unscheinbar (klein, leicht grau, nicht fett). Klar, er hat da ja auch eine andere Funktion. Man muss das dort oben geradezu suchen. 
Nach meinem Dafürhalten würde es auch nichts schaden, wenn der HTML-Dateiname zusätzlich auch weiter unten im Feld (dort dann tiefschwarz, größer und fett) aufgeführt wird (und dann zweimal genannt wird). 

![Notiz2](https://user-images.githubusercontent.com/46451749/228619766-75618e5b-3924-416a-aea0-c99fd216f4fa.jpg)

Wäre die einfachste Lösung vielleicht: Den HTML-Dateinamen auch im Kasten mit aufführen?

![Notiz3](https://user-images.githubusercontent.com/46451749/228630614-92ab065e-d2a5-4c53-bcb1-fba35c9f643c.jpg)

**Comment by j-dimension** [comment]
Den Dateinamen im rechten Teil mit darzustellen ist kein Problem. 

Die Darstellung des Fenstertitels in LibreOffice kann ich nicht beeinflussen. 

Die Aufnahme des Dateinamens in die Notiz selbst möchte ich nicht, da das dann immer synchron gehalten werden müsste, bspw. muss dann bei Umbenennung die Notiz "bearbeitet" werden.

**Comment by Dickmaulruessler** [comment]
> Den Dateinamen im rechten Teil mit darzustellen ist kein Problem.
> 
Gut!

**Comment by Dickmaulruessler** [comment]
Ich könnte mir vorstellen, dies zu sponsorn. Ich nutze die Notiz-Funktion sehr gerne und das wäre für mich ein erheblicher Mehrwert. Magst du dazu bitte mal etwas sagen?

**Comment by Dickmaulruessler** [comment]
Sehr cool!
Vielen vielen Dank!
