### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-org#1931]
Wenn man einen Scan zuordnen will, wird bei der Namensvergabe fürs Dokument ja .pdf angezeigt. Wenn man dann das Dokument umbenennen will und einfach hinter das .pdf den fokus setzt um alles wegzulöschen und nen neuen Namen zu vergeben (der dann automatisch die Endung Pdf erhält, wie halt in Windoof üblich), geht das nicht. Es werden beim löschen einfach immer mehr Teile aus .pdf (.pd.pd.pd). Es geht nur, wenn man vor dem Punkt vor PDF in den Namen klickt und ändert.

**NOTE: Please search existing tickets to avoid duplicates **
**HINWEIS: Bitte vorab die Ticketsuche verwenden, um Doppeleinträge zu vermeiden **

**Describe the bug / Fehlerbeschreibung**
(todo: a description of the bug / eine Beschreibung des Fehlers)

**To Reproduce / Schritte zum Nachvollziehen**

1. Go to / Gehe zu '...'
2. Klicke auf / Click on '....'
4. Error message / Fehlermeldung: '...'

**Expected behavior / Erwartetes Verhalten**
Eine Beschreibung des erwarteten Verhaltens.

**Screenshots**
Falls relevant, Screenshot beifügen.

**Environment / verwendete Umgebung:**
 - OS / Betriebssystem:
 - j-lawyer.org Version:

**Additional context / Sonstiges**

**Comment by iradraconis** [comment]
Duplikat von #1896
