### ISSUE TITLE
[FEATURE] beA: Einheitliche Handhabung der Etiketten-Markierung

### ISSUE THREAD

**Issue by Dickmaulruessler** [jlawyerorg/j-lawyer-org#1934]
Wenn ich ein Dokument per beA versende, gilt die Etiketten-Markierung **dauerhaft** (bleibt also so beim nächsten Versand bestehen). Es handelt sich um eine Checkbox.

![fdjklösafjl](https://user-images.githubusercontent.com/46451749/229572608-24474673-805e-409c-8486-cbb6600efc2a.jpg)

Wenn ich eine beA-Nachricht empfange und zur Akte speichere, gilt die Etiketten-Markierung nur **einmalig**. Es handelt sich um eine Anklick-Pulldown-Liste.

![fdjklösafjldfsdf](https://user-images.githubusercontent.com/46451749/229573256-d7f8db34-edb9-4ad0-af2a-b93450bea4d5.jpg)
.
.
.

Sollte nicht an beiden Orten beide Varianten (einmalig / dauerhaft) angeboten werden? 

In meiner Praxis hätte ich es sogar gerne eher genau anders herum (bei Versand unterschiedliche Etiketten, beim Empfang jedenfalls immer das Etikett "Neues beA"). 
Nun ich bin sicherlich kein normaler Maßstab. Aber die unterschiedliche Behandlung erschließt sich mir jedenfallls nicht. 
.

Das würde ebenfalls für den Scan-Eingang gelten (wo ich auch generell immer "Neuer Scaneinang" setze).

**Comment by j-dimension** [comment]
Es handelt sich um zwei völlig unterschiedliche Funktionalitäten. Der obere Screenshot zeigt das Aktivieren eines Etiketts, das beim Speichern angebracht werden soll. 
Der untere Screenshot ist eine Suche anhand eines Etikettes (daher auch in der Suchzeile dargestellt). Gespeichert wird dort gar nichts.

**Comment by Dickmaulruessler** [comment]
Ich bin verwirrt und werde das noch einmal in Ruhe testen, (da ich meine, es werde im unteren Beispiel gespeichert.) 

Wie auch immer: Die Möglichkeit einer sofortigen Etikettenvergabe direkt beim ersten Abspeichern der beA wäre sehr sinnvoll (Etikett "neue beA")

**Comment by iradraconis** [comment]
> 
> Wie auch immer: Die Möglichkeit einer sofortigen Etikettenvergabe direkt beim ersten Abspeichern der beA wäre sehr sinnvoll (Etikett "neue beA") 

Aber ist das nicht bereits so? Bei mir ist "To-do Sekretariat" standardmäßig als Etikett vergeben für Bea Post, wenn ich diese speichere.
