### ISSUE TITLE
Dateinamenpräfix variabel

### ISSUE THREAD

**Issue by Thorsten-Nutzer** [jlawyerorg/j-lawyer-org#1937]
Hallo,

lange gesucht, aber bisher noch nichts gefunden.

Ich würde gerne die automatisch generierten Dateinamen in den Speicherdialogen konfigurieren können. 

Beispielsweise nutze ich ein 6-stelliges inverses Datum ohne Bindestriche, kein Aktenzeichen und eine "von/an-Logik". Bei jedem Speichervorgang (und Import von Dateien) muß ich den Dateinamen umfangreich händisch anpassen. Schön wäre es, wenn ich das global festlegen könnte, ähnlich wie bei den Aktenzeichen und den Dokumentenvorlagen. So eine Automatik ist ja im Prinzip eine tolle Sache.

Liebe Grüße!

**Comment by j-dimension** [comment]
Duplikat von #288
