### ISSUE TITLE
[FEATURE] Dokumente - Änderungsdatum

### ISSUE THREAD

**Issue by j-dimension** [jlawyerorg/j-lawyer-org#1938]
Dokumente sollten explizites Änderungsdatum bekommen. 

Sortierung in der Akte standardmäßig nach Änderungsdatum absteigend, nicht mehr nach Erstellungsdatum. 

Anzeige des Änderungsdatums.

Formatierung des Änderungsdatums (und evtl. weiterer Datumsangaben in der Anwendung) in menschenlesbarer Form wie "vor 5 Tagen", "vor 3 Wochen", ... (via JodaTime PeriodFormatter)

**Comment by Dickmaulruessler** [comment]
Dass man optional nach Änderungsdatum sortieren kann, ist OK. Ich persönlich benötige diese Sortierung jedoch nicht. Dass das nun die Standardeinstellung ist, finde ich unglücklich. 

Ich gucke mir die Dokumente an, um einen **chronologischen** Ablauf der Akte zu haben. Daher nutze ich ausschließlich die Sortierung nach Erstellungsdatum. Das muss ich jetzt jedes Mal manuell klicken. Also praktisch in jeder Akte ein zusätzlicher Klick. 
(Wenn ich im Nachhinen den Dateinamen geändert hatte, führt das mit der Sortierung nach Änderungsdatum zu Ergebnissen, die aus meiner Sicht unpraktisch sind). 

Aus welchem Grund wünschten andere Anwender die Sortierung nach Änderungsdatum? Ich verstehe den praktischen Anwendungsfall leider gar nicht...

**Comment by stm9x9** [comment]
Vielleicht wenn man mehr in der Vertragsgestaltung tätig ist und die jeweils zuletzt bearbeiteten Entwürfe sehen will? Ich nutzte das aber auch nicht. Ich sortiere aber überhaupt nicht nach Datum, weil dann zb Gegnerschriftsätze falsch sortiert sind, wenn sie später ins System gelangt sind. Ich habe das Dokumentendatum im Namen und sortiere nach Namen. Wenn es eine eigene Spalte "Dokumentendatum" gäbe, dann könnte ich auf das Datum im Namen verzichten und danach sortieren.
