### ISSUE TITLE
urteile-gesetze.de: Anzahl der gelieferten Treffer erhöhen?

### ISSUE THREAD

**Issue by j-dimension** [jlawyerorg/j-lawyer-org#194]
Lässt sich die Anzahl der Treffer in der Ergebnisliste erhöhen, bspw. auf 50?

**Comment by danbeck** [comment]
Anzahl der zurückgelieferte Treffer in der externe API von urteile-gesetze auf 50 gesetzt. Die Änderung ist deployt.
