### ISSUE TITLE
urteile-gesetze.de: Scrolling der Trefferliste

### ISSUE THREAD

**Issue by danbeck** [jlawyerorg/j-lawyer-org#195]
Scrollen in der Trefferliste (z.B. mit dem Mausrad) funktioniert nicht richtig. Vielleicht hat einer der Dokumentvorschau-Panels den Fokus.

**Comment by danbeck** [comment]
@j-dimension: Die Issue kannst du mir auch gerne zuweisen.

**Comment by j-dimension** [comment]
erfolgreich getestet
