### ISSUE TITLE
Warnung wenn keine WV für Zukunft, wenn nicht alle WV geschlossen

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-org#1950]
Wenn man eine Akte ohne aktive WV verlässt, bekommt man eine Warnung. Gut, wichtig, richtig. Aber gerade merke ich, wenn man vergessen hat, eine vom Datum her abgelaufene WV zu schließen und keine WV angelegt hat für die Zukunft, dann wird man beim Verlassen der Akte nicht davor gewarnt, dass man keine Wiedervorlage für die Zukunft hat.... Gefährlich, sollte nicht passieren. Die Warnung sollte genauso kommen.

**Comment by j-dimension** [comment]
Dann wird die WV, die in der Vergangenheit liegt, aber immer noch auf dem Desktop angezeigt. 

Ich fürchte, mal eben aus "Akte muss eine offene WV haben" ein "Akte muss eine offene WV in der Zukunft haben" zu machen, wird bei vielen zu unglaublich vielen Warnungen bei jeder Akte führen. Ich sehe sehr oft eine riesige Anzahl offener WV in der Vergangenheit.

Bin unsicher und möchte zunächst weitere Meinungen hierzu sammeln.

**Comment by Mucki526** [comment]
Meinen Meinung ist, dass es solche offenen WV in der Vergangenheit garnicht geben darf beim Schließen einer Akte - dann muss man eben eine neue WV vergeben, wenn man es bemerkt... Und mal dumm gefragt - Es doch nur darum, dass dass eine Warnmeldung kommt, wenn eine Akte keine offene WV für die Zukunft hat, wenn sie geschlossen wird. Die Frage nach einer offenen WV ist doch das eine, die andere, viel wichtigere Frage ist die nach einer fehlenden WV für die Zukunft beim Verlassen der Akte. Das wäre doch "nur" ein zusätzlicher Vergleich über das Datum der letzten vorhandenen WV mit dem Kalenderdatum. Im Moment führt eine übersehene offene WV in der Vergangenheit (was per-se schon schlecht ist, aber wohl (zu oft) vorkommt) und Verlassen der Akte ohne Warnmeldung zu einem erhöhten Risiko, dass man das Versäumnis zu klären, wann die Akte wieder "hochkommt" evt. erst viel später bemerkt, statt beim Verlassen der Akte, wo man das Versäumnis sofort korrigieren könnte (und nebenbei noch sieht, dass noch alte WV offen sind)..... Mir als würde es helfen, insoweit diszipliniert zu werden, gerade wenns hektisch ist.

**Comment by stm9x9** [comment]
> Meinen Meinung ist, dass es solche offenen WV in der Vergangenheit garnicht geben darf beim Schließen einer Akte - dann muss man eben eine neue WV vergeben, wenn man es bemerkt... 

Warum sollte es das nicht geben? Das gibt es bei mir ständig. Eine WV ist wie in der Analog-Zeit die Akte, die man mir "wieder vorgelegt" hat auf meinen Schreibtisch / WV-Stapel. Und dieser Stapel ist die Liste auf dem Desktop. Eine WV heißt für mich: In der Akte gibt es aktuell was zu tun. Und zwar ab dem <Datum>. Nicht bis <Datum>. Da liegt dann also zb "gibt es eine Eingangsmeldung?", "we" oder auch "in einer Woche ist Frist für xy". Und bis ich die bearbeitet habe und die WV erledigt markiere, "liegt sie halt weiter auf dem Stapel".

> Die Frage nach einer offenen WV ist doch das eine, die andere, viel wichtigere Frage ist die nach einer fehlenden WV für die Zukunft beim Verlassen der Akte. ... Im Moment führt eine übersehene offene WV in der Vergangenheit (was per-se schon schlecht ist, aber wohl (zu oft) vorkommt) und Verlassen der Akte ohne Warnmeldung zu einem erhöhten Risiko, dass man das Versäumnis zu klären, wann die Akte wieder "hochkommt" 

Solange die WV offen ist, ist sie ja in der Liste der offenen WV/Fristen auf dem Desktop zu sehen. Das reicht IMHO. Die hier genannte Warnfunktion dient IMHO dazu, daß eine Akte nicht "untertauchen" kann, weil sie aktuell und auch nicht später mal in der WV-Liste auftaucht.
