### ISSUE TITLE
[BUG] PDF lassen sich manchmal aus der Akte nicht öffnen

### ISSUE THREAD

**Issue by hackvokat** [jlawyerorg/j-lawyer-org#1952]
Hallo,

ich habe seit Kurzem das Problem, dass sich manche PDFs nicht aus der Akte heraus öffnen lassen.

Ich verbinde mich mit den Clients über den in j-lawyer integrierten SSH-Tunnel mit dem Server.

Die j-lawyer-Vorschau funktioniert problemlos, auch das Verschicken (beA / Fax) und das lokal Speichern klappt. Ab das Öffnen (Kontextmenü und Doppelklick) funktioniert nicht bei allen PDFs. Weder in der client.log noch in der server.log taucht dazu etwas auf. Ich schließe daher nicht aus, dass es auch ein Problem auf meinem Client ist (Mac).

Der Lade-Dialog kommt kurz und dann, wenn das Dokument geöffnet werden sollte, passier nichts. Die Vorschau-App startet zwar noch, aber ohne ein Dokument zu öffnen. Zeitlich taucht das ca. seit dem letzten Update auf, aber da kann auch Zufall sein, falls die Ursache wo anders liegt.

In den Systemlogs von Mac steht auch nichts dazu.

Wie könnte ich dem Problem näher auf die Spur kommen?

**Comment by j-dimension** [comment]
Auf dem MAc mal aus dem Terminal starten und schauen ob dort dann weitere Ausschriften helfen können:

`"/Applications/j-lawyer.org (Client).app/Contents/PlugIns/jre.bundle/Contents/Home/bin/java" -Xmx1024M -Djava.net.preferIPv4Stack=true -jar "/Applications/j-lawyer.org (Client).app/Contents/Resources/app/j-lawyer-client.jar"`

**Comment by stm9x9** [comment]
passiert es immer wieder bei denselben Dokumenten?

**Comment by hackvokat** [comment]
Es ist immer bei denselben Dokumenten, also reproduzierbar. Wenn ich j-lawyer über den shell-Befehl starte, landet folgendes im Terminal:

```
15:05:50,772 DEBUG [invocation] Calling invoke(module = j-lawyer-server/j-lawyer-server-ejb/ArchiveFileService, strong affinity = None, weak affinity = None): 
15:05:50,772 DEBUG [invocation] Calling invoke(module = j-lawyer-server/j-lawyer-server-ejb/ArchiveFileService, strong affinity = None, weak affinity = None): 
15:05:50,828 DEBUG [ScratchFileBuffer] ScratchFileBuffer not closed!
15:05:50,830 DEBUG [PostScriptTable] No PostScript name information is provided for the font DejaVuSans-ExtraLight
15:05:50,832 DEBUG [PostScriptTable] No PostScript name information is provided for the font DejaVuSans-Bold
15:05:50,835 DEBUG [PostScriptTable] No PostScript name information is provided for the font DejaVuSans
15:05:50,977 DEBUG [invocation] Calling invoke(module = j-lawyer-server/j-lawyer-server-ejb/ArchiveFileService, strong affinity = None, weak affinity = None): 
15:05:53,539 DEBUG [invocation] Calling invoke(module = j-lawyer-server/j-lawyer-server-ejb/SingletonService, strong affinity = None, weak affinity = None): 
```

Das Problem tritt bei mehreren Macs im gleichen Netzwerk auf, nicht nur bei einem.

**Comment by j-dimension** [comment]
Ist das eine Terminalausgabe NACH dem Öffnen eines solchen Dokuments?

**Comment by j-dimension** [comment]
Ist in den Einstellungen eine bestimmte Anwendung für PDF konfiguriert?

**Comment by j-dimension** [comment]
Bitte mal einen "Universalstarter" wie hier beschrieben einrichten und probieren ob es dann passt:

> https://www.j-lawyer.org/downloads/documentation/j-lawyer.org-UserGuide-de.html#__RefHeading__429_1146603382

**Comment by hackvokat** [comment]
Es betrifft alle PDFs mit einem Umlaut im Dateinamen! Wurde da kürzlich irgendetwas geändert?

Sobald ich es umbenenne geht es. Bei allen PDFs mit Umlauten tritt dieser Fehler auf.

**Comment by j-dimension** [comment]
Da gab es keine neuerliche Änderung. Wurde ein Update eingespielt oder ein Backup rückgesichert?

**Comment by hackvokat** [comment]
Nur das letzte j-lawyer-Update. Das komische ist ja, dass sonst alles mit diesen Dokumenten funktioniert:
- Preview in j-lawyer
- Versand per beA/Fax
- lokal speichern

Nur das Öffnen nicht.

**Comment by j-dimension** [comment]
Das heißt dass j-lawyer kein Problem mit dem Umlaut hat, aber die "Vorschau"-Anwendung. Warum auch immer. Vielleicht in der Richtung weiter recherchieren.

**Comment by hackvokat** [comment]
> 

Ich habe es mit anderen PDF-Readern versucht, dort ist das Verhalten identisch. J-Lawyer öffnet zwar den Reader, aber kein Dokument geht auf. In den Mac-Logs findet sich dazu nichts, das Problem lässt sich auf 3 Macs reproduzieren (alle Umlaut-PDFs aus den Akten gehen nicht).

Öffne ich die Dokumente dirakt aus dem tmp-documents-Verzeichnis, dann funktioniert es einwandfrei. Irgendwo bei der "Übergabe" direkt an den PDF-Reader auf den Client muss es ein Problem geben.

Kann jemand anderes das unter Mac auch feststellen?

**Comment by LazyGuy21No** [comment]
Hier ist dasselbe Phänomen aufgetreten. Auch Mac mit jüngstem Update

**Comment by j-dimension** [comment]
Es gab seit 2.1 keine diesbezüglichen Änderungen, und ich bekomme es schlicht nicht reproduziert. Ich nutze folgende Einstellungen, um "Vorschau" zu starten:

<img width="643" alt="image" src="https://user-images.githubusercontent.com/3729754/236920082-fa37878c-8793-4375-8ae5-ffed73f47615.png">

Ich nutze zwei Szenarien: 
- Dokument mit Umlaut aus Finder in die Akte ziehen und dann dort per Doppelklick öffnen
- Dokument ohne Umlaute im j-lawyer umbenennen, sodass Umlaute enthalten sind, dann dort per Doppelklick öffnen

Ich benötige eine exakte Bediensequenz, mittels derer ich das Problem nachvollziehen kann.

**Comment by iradraconis** [comment]
Wir und eine befreundete Kanzlei haben das Problem übrigens auch. Wir sind noch nicht dahinter gekommen. Allerdings kann ich feststellen, dass ich die PDF Dateien nach dem Export/Speichern auf dem Laptop dort auch nicht mehr mit der Vorschau App, sondern allenfalls mit QuickView ansehen kann. Sehr schräg! Hängt es vielleicht mit der Konvertierung durch Libreoffice zusammen? Ich muss gestehen, dass ich immer die aktuelleste Version von LibreOffice verwende. Heute noch auf die 5.3.2 aktualisiert. Ich behalte das mal im Auge.

**Comment by j-dimension** [comment]
Vielleicht kann jemand mal ein solches kaputtes Dokument generieren und bereitstellen.

**Comment by hackvokat** [comment]
odt-Datei mit Umlaut über j-lawyer in PDF konvertieren, dann tritt das Problem bei mir auf.

**Comment by j-dimension** [comment]
> odt-Datei mit Umlaut über j-lawyer in PDF konvertieren, dann tritt das Problem bei mir auf.

Hier leider nicht. Daher die Bitte nach einer Beispieldatei. So könnte man erstmal eingrenzen (bspw. verifizieren, dass es an der Datei liegt, nicht am Code).

**Comment by j-dimension** [comment]
> Heute noch auf die 5.3.2 aktualisiert.

Hab ich eben installiert, ohne weitere Erkenntnisse. Hier Intel-Mac.

**Comment by PBaumfalk** [comment]
Einer von meinen Jungs hat den Mac geupdated. Er hat das Problem. Alle ohne Update noch nicht.

Es gibt jetzt ein Verbot für Umlaute.

**Comment by hackvokat** [comment]
Sobald ich so eine PDF-Datei bei github hochlade oder in eine Mail einfüge, scheint der Charset "repariert" zu werden, sodass die Datei wieder funktioinert.

Hier alles unter ARM.

Ich glaube nicht, dass es an j-lawyer liegt, sondern Mac OS irgendwas komisches bei den Umlauten geändert hat, was man umschiffen muss.

**Comment by j-dimension** [comment]
@hackvokat hast Du mal die volle Versionsbezeichnis des MacOS?

**Comment by j-dimension** [comment]
> https://communities.apple.com/de/thread/254794086

"Ich hatte Kontakt mit dem Support von Apple und sie sagen, das Problem liegt am letzten Update von macOS, es ist bekannt und es wird daran gearbeitet. Beim nächsten Update sollte es behoben sein."

**Comment by iradraconis** [comment]
Zwischenlösung: problematische PDF Datei mit Firefox öffnen. Firefox ist inzwischen ein recht guter PdF Viewer. Allerdings ohne die Möglichkeit, Lesezeichen zu setzen.

**Comment by hackvokat** [comment]
mac OS 13.3.1 (a) (22E772610a)

**Comment by PBaumfalk** [comment]
Lösung: Umlaute im J-Lawyer ersetzen funktioniert.
