### ISSUE TITLE
Vorlagenplatzhalter Geburtsdatum

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-org#1954]
Der Vorlagenplatzhalter für das Geburtsdatum _Gebdatum übernimmt das eingepflegte Geburtsdatum nicht. Geburtsort funktoniert

**Comment by j-dimension** [comment]
Einen solchen Platzhalter gibt es nicht. Den korrekten Platzhalter für das Geburtsdatum bitte der Doku entnehmen - danke!
