### ISSUE TITLE
Aktenkonto

### ISSUE THREAD

**Issue by j-dimension** [jlawyerorg/j-lawyer-org#1955]
Erfasst werden tatsächliche Geldzu- und -abflüsse, d.h. eine Rechnung wird bei Rechnungsstellung nicht im Aktenkonto dargestellt. Jedoch können (Teil-)Zahlungen im Aktenkonto mit dem Beleg verknüpft werden - so wird im "Belege"-Tab ein Überblick über offene (Teil-)Beträge möglich.

Gebühren = Honorar = Rechnungen, in der Regel gestellte Rechnungen
Fremdgeld = durchlaufende Posten, müssen zwangsweise auf 0 stehen, wenn Akte abgelegt wird
Auslagen = Auslagen für den Mandanten

- [x] neuer Sub-Tab "Aktenkonto" im Tab "Finanzen
- [x] tabellarische Darstellung, Spalten: Datum, Zahlung von/an, Gebühren/Honorar Einnahmen, , Gebühren/Honorar Ausgaben, fremdes Geld Einnahmen, fremdes Geld Ausgaben, Auslagen Einnahmen, Auslagen Ausgaben, Kommentar, Bezug zu Beleg
- [x] Darstellung kumulierter Wert pro Spalte
- [x] Darstellung kumulierter Wert pro Kategorie (Gebühren, Fremdgeld, Auslagen)
- [x] neue Buchung: editierbar sind immer alle Spalten
- [x] neue Buchung: Verknüpfung mit Kontakt
- [x] neue Buchung: Verknüpfung mit Beleg
- [x] Buchung bearbeiten
- [x] Buchung löschen
- [x] Belege-Tab: zusätzliche Information (neben "total"): bereits gezahlter Betrag, als kumulierter Betrag aller Zahlungen
- [x] Rechnungsdialog: Detailinformationen (nur lesend) aus dem Aktenkonto: Darstellung aller Zahlungen
- [x] Prüfung bei Aktenablage: Fremdgeldsaldo=0? (Schließen verhindern)
- [x] Prüfung bei Aktenablage: Auslagen ausgeglichen? (Option, die Differenz zu ignorieren)
- [x] Export in Tabellenkalkulation
- [x] #2236

Fragen:
- Erfassen von (Teil-)Zahlungen: über die Rechnung, und dann Übernahme ins Aktenkonto? Oder übers Aktenkonto und dann Anzeige an Rechnung? Tendiere zu Eingabe über das Aktenkonto.
- Werden Spalten / Angaben zu Umsatzsteuer benötigt?

**Comment by stm9x9** [comment]
kurze off-topic Frage:

> @j-dimension
[version up for docker. issue](https://github.com/jlawyerorg/j-lawyer-org/commit/6ade6a8211801a6204f113ce2ce04128c84d2242) https://github.com/jlawyerorg/j-lawyer-org/issues/1955

gibt es jl als Docker-Version? Das wäre obercool.

**Comment by j-dimension** [comment]
Das gibt es seit Jahren 🙂

Nur empfehle ich das nicht für den produktiven Einsatz.

**Comment by j-dimension** [comment]
Aktenkonto - Ansicht in derAkte:

![grafik](https://github.com/jlawyerorg/j-lawyer-org/assets/3729754/81c9b218-2cbe-4cd2-86b5-3157c452b320)

**Comment by j-dimension** [comment]
neue Buchung: 

![grafik](https://github.com/jlawyerorg/j-lawyer-org/assets/3729754/0c23911f-51de-447a-b8ea-0700b677d9f4)

**Comment by j-dimension** [comment]
Buchung bearbeiten:

![grafik](https://github.com/jlawyerorg/j-lawyer-org/assets/3729754/cb9c79e3-6933-4bcc-90b0-ee531d8ba838)

**Comment by j-dimension** [comment]
Zahlungen an einer Rechnung: ein/aus pro Zahlung werden kumuliert und Betrag entsprechend dargestellt.

![grafik](https://github.com/jlawyerorg/j-lawyer-org/assets/3729754/73181f12-a313-4d8c-8410-1c2a8bcc1eb1)

**Comment by j-dimension** [comment]
Belegübersicht in der Akte:

![grafik](https://github.com/jlawyerorg/j-lawyer-org/assets/3729754/9120e6a7-327a-4061-a1cc-e42347c921d6)
