### ISSUE TITLE
[BUG] Bezeichnung im Kontextmenü für PDF-Speichern

### ISSUE THREAD

**Issue by Dickmaulruessler** [jlawyerorg/j-lawyer-org#1958]
So, ich komme hier mal wieder mit so ´nem pingeligen Ding...

Im beA heißt es beim Speichern für mich sehr gut nachvollziehbar
![Speichern-beA](https://github.com/jlawyerorg/j-lawyer-org/assets/46451749/d3fa0b3b-299f-42e5-be4c-9471d256a71b)

Im Dokumenten-Reiter in der Akte taucht das Wort "Akte" oben nicht auf, sondern dort steht "ablegen" (beim "**in andere Akte** kopieren" dann aber plötzlich doch wieder mit dem Wort "Akte"). 

Das Wort "Ablegen" ist nicht ganz eindeutig - und eben auch nicht einheitlich. 

Ich würde daher dafür plädieren, es im Dokumenten-Ordner auch **"in Akte speichern als PDF"** zu nennen.

![Dokumente-Kontextmenü](https://github.com/jlawyerorg/j-lawyer-org/assets/46451749/500d56a2-9cc3-4f47-a550-52c58dba665c)

(Zum mir [überladen wirkenden Kontextmenü](https://github.com/jlawyerorg/j-lawyer-org/issues/1422) hatte ich schon einmal etwas geschrieben. Das findet aber wohl keine weiteren Unterstützer/innen...)

**Comment by stm9x9** [comment]
Also meine Unterstützung hattest du da :-)

Hier in der Sache: das geht in Richtung #1505 Mit Ablegen habe ich auch meine gedanklichen Probleme. Aber in #1505 wird ja auf weitere Vorschläge gewartet :-) In Akte speichern wäre IMHO eine Alternative.

**Comment by Dickmaulruessler** [comment]
Danke @j-dimension !
Das wurde mit der 3.0 übernommen und ich schließe.
