### ISSUE TITLE
urteile-gesetze.de: Trefferlisten-Highlighting

### ISSUE THREAD

**Issue by danbeck** [jlawyerorg/j-lawyer-org#196]
Aktuell wird eine Vorschau jedes Dokuments in der Trefferliste angezeigt. 

Stattdessen soll die Trefferliste so angepasst werden, dass ein Text-Snippet zurückgegeben wird, der das gesuchte Wort enthält (ähnlich der Google-Suche).

**Comment by j-dimension** [comment]
erfolgreich getestet
