### ISSUE TITLE
[FEATURE] Integration von Tesseract/OCRmyPDF

### ISSUE THREAD

**Issue by LazyGuy21No** [jlawyerorg/j-lawyer-org#1961]
Tesseract ist eine äußerst präzise OCR-Engine, die für Englisch und Deutsch (und viele Andere Sprachen) sehr gute Ergebnisse liefert. OCRmyPDF ist darauf spezialisiert Tesseract auf PDF anzuwenden (und die Qualität der Vorlagen wenn möglich zu optimieren). OCRmyPDF braucht Linux/MacOS als Umgebung.

Es wäre schön, wenn sich **Tesseract/OCRmyPDF** optional als Erweiterung einbinden ließe (den Pfad zu tesseract auf dem Server angeben; Sprachen-Optionen angeben, PDF Optionen wählen).

Ist die Einbindung aktiviert könnte eine OCR-Option über das **Kontextmenü** im Reiter Dateien verfügbar sein.

Siehe auch: #1074

**Comment by j-dimension** [comment]
Duplikat von #74
