### ISSUE TITLE
[FEATURE] Anbindung an OpenAI's Whisper

### ISSUE THREAD

**Issue by LazyGuy21No** [jlawyerorg/j-lawyer-org#1962]
**Whisper** (https://openai.com/research/whisper) ist eine seht gute Spracherkennung, die für Englisch und Deutsch (und viele Andere Sprachen) sehr gute Ergebnisse liefert. 

![image](https://github.com/jlawyerorg/j-lawyer-org/assets/56734761/29afd6e2-e97d-473e-8393-285aaf6ee3c9)

Quelle: https://www.assemblyai.com/blog/how-to-run-openais-whisper-speech-recognition-model/

Das System kann vollständig local auf dem Server betrieben werden. 

Es wäre schön, wenn sich Whisper zunächst optional als Erweiterung einbinden ließe (den Pfad zu Whisper auf dem Server angeben; Sprachen-Optionen angeben, Ausgabenvorlage wählen).

Ist die Einbindung aktiviert könnte eine Option "Spracherkennung ausführen" über das Kontextmenü im Reiter Dateien verfügbar sein, wenn eine Audio-Datei ausgewählt ist.

Siehe auch: 
https://github.com/jlawyerorg/j-lawyer-org/issues/1074
https://github.com/jlawyerorg/j-lawyer-org/issues/1961

**Comment by iradraconis** [comment]
sehr guter Vorschlag!

**Comment by Dickmaulruessler** [comment]
OpenAI mit Sitz in den USA haut mich nicht so vom Hocker - schon gar nicht bei Spracherkennung.

**Comment by LazyGuy21No** [comment]
Whisper läuft komplett lokal auf Deinem Rechner und ist OpenSource

**Comment by j-dimension** [comment]
via #2395
