### ISSUE TITLE
[FEATURE] Integration einer Spracherkennung mit OpenAI's Whisper 

### ISSUE THREAD

**Issue by LazyGuy21No** [jlawyerorg/j-lawyer-org#1963]
**Whisper von OpenAI** ist eine sehr gute Spracherkennung.

Neben der Anbindung (#1962) wäre eine Integration m.E. wünschenswert. In einer Akte kann ein neues Diktat gestartet (oder ein gespeichertes Diktat hochgeladen) werden. Der Client nimmt dann entweder das Diktat auf oder verarbeitet eine Audiodatei (möglichst auf dem Server).

Auch denkbar wäre m.E. ein "Diktierfenster", in dem eine **Live-Erkennung** angezeigt wird. Ist der Text fertig diktiert, wählt man eine Vorlage aus, in die der Text eingefügt werden soll. Der Erkannte Text wandert dann in einen dort hinterlegten **Platzhalter {{WHISPER}}** im Textkörper.

Nachteile: Eine Live-Erkennung nutzt die Rechenleistung des Clients. Auf Windows scheint der Betrieb von Whisper etwas komplizierter einzurichten zu sein.

Bei der **Stapelverarbeitung** könnte man analog die Sprachdatei auswählen (bitte mit Vorschau zum Kontrollieren) und die Ziel-Textvorlage angeben. Der Server arbeitet dann alles nacheinander ab und sagt bescheid, wenn das Dokument fertig ist (ähnlich Faxfunktion).

Siehe auch: #1961

**Comment by iradraconis** [comment]
sehr guter Vorschlag!

**Comment by j-dimension** [comment]
via #2395
