### ISSUE TITLE
[Question] create E-Mail from file

### ISSUE THREAD

**Issue by kvogelsa** [jlawyerorg/j-lawyer-org#1965]
Hi!
I#ve just installed j-lawyer.

Server, ver 2.3.0.22, is installed on a Debian 11 behind an nginx reverse proxy.
Client, ver 2.3.0.1, ist installed in Win10.

It is running, esp. #1042 was quite useful. Thanks.

Now i am testing, whether j-lawyer suits to us. In the moment, I am looking for an opportunity to send E-Mails directly out of a file, without attaching anything. I've read that it is possible from outfolding the involved person; but it is not. I find the email-adress, but it is normal text. I cannot find the feature for creating the email.

Has anyone a clou for me?

Thanks in advance.

**Comment by j-dimension** [comment]
Thanks for reaching out (we may communicate in german as well). 

I am not sure I understand the question. If you want to send e-mail to a person that is involved in a case, you may open the "Beteiligte" tab and there you find a dropdown that allows sending an e-mail that has no attachments.

![grafik](https://github.com/jlawyerorg/j-lawyer-org/assets/3729754/9b74f833-5b69-49c9-afe0-0c291934e7f4)

Does this answer the question?

**Comment by kvogelsa** [comment]
Danke!
Genau das habe ich gesucht. Manchmal hilft kucken... Ich hielt "Details" für das dropdown.

Gern schreibe ich auch auf deutsch. (War auf github ein Reflex)

Wo wir gerade dabei sind, noch zwei kurze Fragen:

1. Kann man mehrere Akten nebeneinander offen haben? (Ist wahrscheinlich Feature-Request)
2. Wie kann ich zur zuletzt geöffneten Akte gehen? Beispiel: Ich bearbeite eine Akte. Ich gehe in den E-Mail-Eingang, um eine E-Mail der Akte zuzuordnen. Wie kann ich direkt zurück in die vorher bearbeitete Akte?
3. Wie schnell aktualisieren sich Stammdaten? Beispiel: Ich lege eine natürliche Person an. Ich gehe in den E-Mail-Eingang und klicke eine empfangene E-Mail dieser Person an. Es wird mir vorgeschlagen, eine neue Person anzulegen. Nach neuem login^wird die Person jedoch erkannt.
4. Erachtet ihr den Betrieb des Servers im Netz als sicher? Die Verbindung ist, über den reverseproxy, mit ssl verschlüsselt. Der Server selbst ist nach menschlichem Ermessen sicher.

An dieser Stelle erstmal ein großes Kompliment für j-lawyer. Es ist ungewohnt, ich mag kein Java und es ist nicht von mir. Abgesehen davon ist es ein tolles Programm :)

**Comment by j-dimension** [comment]
> 2\. Wie kann ich zur zuletzt geöffneten Akte gehen? Beispiel: Ich bearbeite eine Akte. Ich gehe in den E-Mail-Eingang, um eine E-Mail der Akte zuzuordnen. Wie kann ich direkt zurück in die vorher bearbeitete Akte?

Es gibt in Akte und Adresse oben links "zurück"-Navigationsbuttons. Die würden aber eher den entgegengesetzten Fall unterstützen: man befindet sich gerade irgendwo (bspw. E-Mail / beA / Scan / ...), springt von dort in eine Akte und will dann zurück.

Ansonsten gibt es auf dem Desktop immer die Möglichkeit, schnell zu den zuletzt geänderten Akten zu springen. Der Desktop ist mit Shift+F1 immer direkt erreichbar.

**Comment by kvogelsa** [comment]
Danke!
Ich versuche es zu rekonstruieren. 

Noch eine weitere Frage: Kann ich einer juristische Person Mitarbeiter hinzufügen? Und kann ich bei der Beteiligung in der Akte den Mitarbeiter als Ansprechpartner auswählen?

Ich habe das Feld Ansprechpartner gefunden, aber das scheint keine Funktion zu haben beim Erstellen eines Briefs.

lgk
