### ISSUE TITLE
Meldungen frieren den Client ein

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-org#1966]
Beim versehentlichen zweiten Öffnen eines bereits geöffneten dokuments friert uns regelmäßig der Client ein. Das passiert mehrmals am Tag, man hat ein Dokument offen, bearbeitet ein anderes oder macht ein Telefonat. dann öffent man das geöffnete Dokument später nochmals um weiter zu arbeiten (weil man übersieht, dass es schon offen ist) und dann friert alles ein, es bleibt einem nur noch den Client-task abzuschießen mit dem drei-Finger-Griff. Es wäre schön, wenn das geändert wird (ich finde dazu keine Doublette, habe echt gesucht).

**Comment by iradraconis** [comment]
Schön das wir jetzt Namen, Aktenzeichen und Gericht kennen.

**Comment by Mucki526** [comment]
Ah, danke, da habe ich nicht darauf geachtet.... schon weg....
