### ISSUE TITLE
[FEATURE] Sachbearbeiter auf Desktop anzeigen

### ISSUE THREAD

**Issue by Linkki2021** [jlawyerorg/j-lawyer-org#1967]
Bei der Anzeige "Zuletzt geändert" und "Nach Etikett" wäre die Anzeige des Sachbearbeiters unterhalb des Rechtsanwalts hilfreich.

Begründung siehe #1951

**Comment by j-dimension** [comment]
![Image](https://github.com/jlawyerorg/j-lawyer-org/assets/3729754/9144e899-a9b2-4362-8174-9fdc47bd348d)
