### ISSUE TITLE
[FEATURE] Namens Kollisionen vermeiden beim Upload von Dokumenten per API 

### ISSUE THREAD

**Issue by timo0** [jlawyerorg/j-lawyer-org#1968]
Aktuell laufen wir (hin und wieder) in folgende Exception beim Upload von Dokumente per API:

```
12:02:12,626 ERROR [org.jlawyer.io.rest.v1.CasesEndpointV1] (default task-168) can not create new document Dokument.pdf: java.lang.Exception: Dokument.pdf existiert bereits in der Akte oder deren Papierkorb - bitte einen anderen Namen wählen!
	at com.jdimension.jlawyer.services.ArchiveFileService.addDocument(ArchiveFileService.java:1671)
	at sun.reflect.GeneratedMethodAccessor292.invoke(Unknown Source)
```

Meine aktuelle Vermeidungsstrategie ist mir vor dem Upload alle Dokumente zu holen und zu checken ob Kollisionen entstehen würden und füge der Datei dann einen Präfix an um den Namen eindeutig zu machen. 

Aber über den Endpoint `/v1/cases/{id}/documents` bekomme ich die Dokumente aus dem Papierkorb nicht. Deshalb passiert dann evtl. doch ein Fehler.

Aus meiner Sicht wären folgende Lösungen für das Problem schön:
1. Endpoint schaffen der checkt ob der Name für die Akte funktioniert. Z.b. `/vX/cases/{id}/documents/check-name` der dann `true` oder `false` liefert. 
2. Möglichkeit schaffen auch die Dokumente (mind. Namen) aus dem Papierkorb auch bereitstellen. 
3. Der Service schafft einfach einen konfliktfreien Dateinamen mit (2) oä am Ende

Ich persönlich tendiere zu 1, kann aber auch verstehen, wenn das etwas zu spezifisch ist.

**Comment by j-dimension** [comment]
![Image](https://github.com/jlawyerorg/j-lawyer-org/assets/3729754/3bb8d05a-2fdf-481f-9c9a-d4a721f58741)

**Comment by j-dimension** [comment]
Bei Variante (1) ist der Ergebnis-Payload am kleinsten, das ist sehr charmant. Habe das eingebaut.
