### ISSUE TITLE
[BUG] [beA] [e-mail] Doppelpunkt : im Namen führt zu Fehler beim Speichern  (bei direktem lokalen Speichern aus dem Posteingang)

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#1969]
Ich habe heute ein Dokument vom Gericht bekommen, mit vorbildlicher Nutzung des Anzeigenamens:

Ladung_Terminmitteilung zum 27.07.2023 um 11:00 Uhr

Daraus wird dann beim Speichern auf der Festplatte der zusammengesetzte Dateinamen:

(Ladung_Terminmitteilung zum 27.07.2023 um 11:00 Uhr) S_xxx_AS_xxxx_18_LADUNG_TERMINMITTEILUNG_A54333xxxxxx224834E1.pdf

Und zumindest unter Windows ist der : wohl nicht so dolle in Dateinamen :-) und es wird eine leere Datei mit dem Namen bis zu : abgelegt: "(Ladung_Terminmitteilung zum 27.07.2023 um 11"

mögliche Abhilfe: entweder im Speicherdialog warnen, daß ein unzulässiges Zeichen (mit Nennung des konkreten Zeichens) enthalten ist oder selbstständig in ein zulässiges Zeichen umwandeln. Favorit: Variante 1.

**Comment by j-dimension** [comment]
Muss nachfragen: das Speichern in die Akte hat funktioniert, die Vorschau für das PDF funktioniert, aber das Öffnen per Doppelklick scheitert auf einem Windows-Arbeitsplatz?

**Comment by j-dimension** [comment]
prüfen, ob bereits via #1903 gelöst
