### ISSUE TITLE
[FEATURE] API Endpunkt für Setzen der Berechtigungen einer Akte

### ISSUE THREAD

**Issue by iradraconis** [jlawyerorg/j-lawyer-org#1970]
@j-dimension 2024-07-29:

- alle verfügbaren Gruppen auflisten: /v6/security/groups/list
- alle berechtigten Gruppen einer Akte auflisten: /v7/cases/{id}/groups (GET)
- berechtigte Gruppen einer Akte ändern: /v7/cases/{id}/groups (PUT)

**Comment by j-dimension** [comment]
@iradraconis wie meinst Du das genau?

- Nutzer in eine Grupe aufnehmen
- Gruppen an einer Akte setzen
- alle Nutzer einer Gruppe mit einer bestimmten Berechtigung ausstatten?

**Comment by iradraconis** [comment]
Entschuldigung. Ich meinte "Gruppen an einer Akte setzen unter dem Reiter "allgemeine Daten" bei den Gruppeneinstellungen unter "Berechtigte".

**Comment by PBaumfalk** [comment]
Ich würde darum bitten, dass dieses Ticket in die kommende Version aufgenommen wird.
