### ISSUE TITLE
[TASK] Desktop besser / automatisch aktualisieren

### ISSUE THREAD

**Issue by j-dimension** [jlawyerorg/j-lawyer-org#1973]
Bspw. bei Navigation zum Desktop, oder bei Änderung des Datenbestandes (im selben Client).

"Fällig":
- [x] Bearbeiten von Kalendereinträgen
- [x] Hinzufügen von Kalendereinträgen
- [x] Schliessen von Kalendereinträgen
- [x] Löschen von Kalendereinträgen

"Zuletzt geändert":
- [x] Bearbeiten von Akten
- [x] Hinzufügen von Akten
- [x] Archivieren von Akten
- [x] Löschen von Akten

"Nach Etikett"

- [ ] Etikettänderungen (erstmal nicht)

**Comment by stm9x9** [comment]
ich würde die "Etikettänderungen" nochmal anregen wollen. Alternativ: Wenigstens wenn man auf den Desktop neu geht, daß zu diesem Zeitpunkt alle Bereiche einmal aktualisiert werden.

**Comment by j-dimension** [comment]
Neues Ticket erstellt.
