### ISSUE TITLE
[FEATURE] UI/UX Dokumente auswählen mit Pfeiltasten+Shift+Space

### ISSUE THREAD

**Issue by LazyGuy21No** [jlawyerorg/j-lawyer-org#1975]
Ein UI-Ding, das mich stört: Die Klageschrift mit Anlagen liegen nicht untereinander. Ich würde gern mit Shift+Pfeiltasten (+ Space) die Dokumente auswählen können.

**Comment by j-dimension** [comment]
Shift + Mausklick sowie Strg + Mausklick sollten bereits das ermöglichen, falls auch die Maus genutzt werden darf.
