### ISSUE TITLE
stapelweise Übernahme von Ordner- und Etikettenvorgaben unabhängig von Anzahl der Dokumente

### ISSUE THREAD

**Issue by Dickmaulruessler** [jlawyerorg/j-lawyer-org#1976]
Sorry, sorry, für Mini-Mini-Bug-Meldung:

Die Aktiv-Iconfarbe ist nicht einheitlich und das Grau im Scaneingang eher verwirrend. 

Ich plädiere "aktiv" auch im Scaneingang auf grün zu setzen. 
Gleiches gilt für das darunterstehende Icon für Dokumente (blau).

![etikett](https://github.com/jlawyerorg/j-lawyer-org/assets/46451749/e3d4513f-de8a-42fe-8e8b-f5a330c71046)

![etikett2](https://github.com/jlawyerorg/j-lawyer-org/assets/46451749/0f353269-caa1-470e-9fc3-f6b8a2d05b38)

**Comment by j-dimension** [comment]
Grau ist das Icon nur dann wenn der Button inaktiv ist. Im unteren Screenshot ist nur ein Dokument in der Liste, daher sind die Massenübernahme-Buttons inaktiv und somit grau. 

Grün bedeutet bei den Etiketten: "es ist mindestens eines ausgewählt"
Weiß bedeutet: "es ist keines ausgewählt".
Diese Farbkodierungen sind konsistent mit der Etikettenselektion auf dem Desktop. 

Bei den Ordner kann man niemals gar nichts auswählen, daher habe ich dort das Icon so genutzt, wie es auch in der Akte dargestellt ist - der Wiedererkennungswert ist so am größten.

**Comment by Dickmaulruessler** [comment]
> Grau ist das Icon nur dann wenn der Button inaktiv ist. Im unteren Screenshot ist nur ein Dokument in der Liste, daher sind die Massenübernahme-Buttons inaktiv und somit grau.
> 

Ich bewundere, bis in welcher Tiefe du dir immer vorab Gedanken gemacht hast!

Dennoch eine kurze Replik:

Ist die Information "Massenübernahme" oder Auswirkung auf nur ein Dokument relevant und notwendig? Mich verwirrt es eher. 
Mich interessiert, ob eine Kennzeichnung erfolgt. Auf wieviele sich das tatsächlich auswirkt, muss ich eigentlich nicht wissen.

**Comment by j-dimension** [comment]
Hallo @Dickmaulruessler! Ich fürchte ich verstehe die Frage nicht ganz. Die Massenübernahme wirkt auf alle aktuell selektieren Dokumente, sobald man hinten auf die Übernahmebuttons klickt. 

Du kannst so mal eben alle PDFs selektieren, per Massenübernahme ein Etikett "Posteingang" anbringen, dann PDF deselektieren und alle XMLs etc. auswählen und dort ein Etikett "beA-Schrott" anbringen. Dann speichern. 

Oder war das Deinerseits ein Plädoyer, die Buttons immer aktiv zu lassen, unabhängig davon wieviele Dokumente davon betroffen sind?

**Comment by Dickmaulruessler** [comment]
> 
> Oder war das Deinerseits ein Plädoyer, die Buttons immer aktiv zu lassen, unabhängig davon wieviele Dokumente davon betroffen sind?

Ja, genau.

**Comment by stm9x9** [comment]
Das kann ich nur unterstützen. Ist unschön, wenn man sein gewohntes Handling umstellen muß, nur weil es mal nur ein Dokument ist.
