### ISSUE TITLE
bei auszuhändigenden Unterlagen warnen

### ISSUE THREAD

**Issue by FlorianPaintner** [jlawyerorg/j-lawyer-org#1979]
Aus meiner Sicht wäre es Wünschenswert in der Aktenansicht "allgemeine Daten" vermerken zu können, dass der Akte Papierdokumente -- typischerweise vollstreckbare Urkunden -- zugeordnet sind. Beim Archivieren einer Akte sollte dann eine Warnung erscheinen, wie dies auch schon bei noch offenen Wiedervorlagen der Fall ist. So können die Urkunden zunächst noch an den Mandanten ausgekehrt werden bevor die Akte wirklich archiviert wird.

**Comment by j-dimension** [comment]
Hier könnte man sich mit Notiz oder einem Etikett direkt helfen. Allerdings ohne Warnung. Alternativ: eine Wiedervorlage dafür erstellen, dass noch Urkunden auszuhändigen sind, und die WV weit in die Zukunft legen. Dann erscheint bei Archivierung auch eine Warnung.
