### ISSUE TITLE
[BUG] .msg-Nachrichten werden nicht in Vorschau angezeigt

### ISSUE THREAD

**Issue by Linkki2021** [jlawyerorg/j-lawyer-org#1986]
.eml funktioniert, bei .msg bleibt die Vorschau leer.

Können wir das irgendwie umgehen?

**Comment by j-dimension** [comment]
Ich müsste einen Parser und Viewer dafür bauen. DAs sollte nicht sonderlich schwer / aufwändig sein. Es gibt Bibliotheken die den Parsing-Teil übernehmen. 

Einziger Punkt der mich umtreibt: ich habe die Wahrnehmung, dass Microsoft selbst stärker auf  .eml setzt, zumindest speichert mein Outlook auf'm Mac und auch die Office 365 Web UI standardmäßig als .eml.

**Comment by Linkki2021** [comment]
Ich persönlich habe da keine Präferenz. Wenn ich auf Windows eine Nachricht aus Outlook auf den Desktop speichere setzt er automatisch .msg. .eml kann ich nicht mal auswählen bei "Speichern unter". Welches Dateiformat setzt er, wenn ich eine Nachricht aus dem Posteingang in j-lawyer zur Akte speichere? Das hängt gerade bei mir, kann es daher nicht testen.

**Comment by Dickmaulruessler** [comment]
Bei mir (Win 10, Outlook 2019) gibt es unten stehende Optionen, wobei standardmäßig immer das blau hinterlegte (.msg) angeboten wird. 

![jkfldsöjaf](https://github.com/jlawyerorg/j-lawyer-org/assets/46451749/af6e5656-56da-40e8-8e43-7e6c7a6e8f6b)

**Comment by j-dimension** [comment]
implementiert:
- Anzeige .msg-Dateien
- Forward
- Reply
- Reply All
- Anhänge
