### ISSUE TITLE
[FEATURE] Zeiterfassung: Zeitdauer eingeben statt Stoppuhr-Nutzung

### ISSUE THREAD

**Issue by j-dimension** [jlawyerorg/j-lawyer-org#1988]
Im "Zeit buchen"-Dialog eine Möglichkeit schaffen, statt mittels Stoppuhr durch manuelle Zeitdauereingabe zu buchen. 
Sollte möglichst schnell gehen, evtl. als Dezimalzahl in Stunden? Oder etwas wie 
30m
2h
2h30m
?

In Zeiterfassungstabelle (in Dokumenten) ggf. nur Startdatum ausgeben, keine Zeiten.

**Comment by Dickmaulruessler** [comment]
Ich würde die Stoppuhr niemals nutzen (da sehr häufig ohne PC bei auswärtigen Terminen in Krankenhäusern und Pflegeheimen unterwegs) sondern ausschließlich die - nachträgliche - manuelle Eingabe. Da rechne ich in 5-Minuten-Takten ab. 30 Minuten-Takte würden bei meinen Abrechnungen nicht akzeptiert werden. 

Ich würde eine Option in der ich die Minuten (auch dreistellig! Ohne dass man das selbst in Stunden und Minuten unterteilen muss) eingeben kann, benötigen. 

Für viele Anwendungen anderer Nutzer sind deine pauschalen, schneller zu klickenden Optionen aber sicherlich sinnvoll, wobei mir 30-Minuten Schritte auch dort zu groß erscheinen (15 Min?)

**Comment by LazyGuy21No** [comment]
Ich meine mich an diverse Rechtsprechung erinnern zu können, die sagt, dass nur die Minutengenaue Abrechnung akzeptabel ist. Ist m.E. nachvollziehbar, obwohl meine IT-Verwandtschaft immer in vollen Tagessätzen zu 850 € abrechnet und damit durch kommt.

**Comment by j-dimension** [comment]
Habe das jetzt als alternative Eingabe ganzzahliger Minuten gestaltet:

![grafik](https://github.com/jlawyerorg/j-lawyer-org/assets/3729754/3e4a9067-5def-457f-98b0-0785b3290f63)

**Comment by Dickmaulruessler** [comment]
Freue mich sehr auf dieses neue Feature! Danke dir dafür!
