### ISSUE TITLE
[FEATURE] Mahnverfahren

### ISSUE THREAD

**Issue by frerpilot** [jlawyerorg/j-lawyer-org#1989]
Ich suche nach einer Möglichkeit aus den Daten einer Akte einen Antrag auf Erlass eines Mahnbescheides zu generieren, um diesen dann per beA an das Mahngericht zu senden. Ich gehe davon aus, dass hierzu ein EDA-Datensatz erstellt werden muss. Dann könnten aus diesen Daten auch die folgenden Anträge auf Erlass eines Vollstreckungsbescheides und ggf. auch der Zwangsvollstreckungsauftrag generiert werden.

**Comment by LazyGuy21No** [comment]
Evtl. zusammen mit der Forderungsbuchhaltung (#527) integrieren: "EDA aus Forderungen erstellen…"

**Comment by j-dimension** [comment]
Das Ticket ist sehr wahrscheinlich bereits über #338 und #525 erfasst. Ich schliesse dieses hier als Duplikat. Inhaltliche Verfeinerung gern über die bestehenden Tickets.
