### ISSUE TITLE
Dokument bereits eröffnet

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-org#199]
Wenn ein Dokument bereits geöffnet ist, gibt es beim erneuten Versuch eine Fehlermeldung. Je nachdem, wieviel Dokumente man gerade offen hat kann die Suche danach dann Dauern. Vielleicht könnte in so einem Fall statt Fehlermeldung eine Meldung erfordern und auf Knopfdruck das entsprechende Fenster ganz nach vorne geholt werden....

**Comment by j-dimension** [comment]
Das ist mit der gewählten Architektur leider sehr, sehr, sehr aufwändig. Da ein Programm nicht ohne weiteres ein externes Programm "steuern" kann, müsste man auf Funktionen des Betriebssystems zugreifen. Es wären daher Speziallösungen für Windows (wahrscheinlich unterschiedliche Lösungen für unterschiedliche Versionen), macOS (dito), Linux (hier für unterschiedliche Window Manager) zu entwickeln. 

Möglich wohl, aber das Aufwand / Nutzen - Verhältnis ist suboptimal. Ich bitte um Verständnis :-(
