### ISSUE TITLE
[BUG] Beteiligtendaten können nicht geöffnet werden nach Zuweisung eines Belegs mit bestimmten Status

### ISSUE THREAD

**Issue by nronk** [jlawyerorg/j-lawyer-org#1991]
Wenn ich bei den Berechnungen einen anderen Punkt als "offen", "bezahlt" oder "storniert" angebe und dann die Adressdaten des zugehörigen Kontaktes öffnen möchte, bekomme ich eine "null" Fehlermeldung und kann die Adressdaten nicht mehr öffnen.

Eine Kopie der Adressdaten erstellen, funktioniert und diese kann ich wiederum öffnen.

Sobald bei dem betreffenen Beleg der Status wieder auf eine der drei oben genannten (offen, bezahlt oder storniert) geändert wurde, können auch die Adressdaten des Kontaktes wieder geöffnet werden.

Also:
1. Beleg erstellen und einem Beteiligten zuordnen
2. Status des Beleg ändern auf anderen als "offen", "bezahlt" oder "storniert"
3. Versuch den Kontakt aufzurufen (zB Adressen suchen oder Auswahl in der Akte) scheitert mit einem Fehler(-fenster) "null"
4. Ändern des Status auf einen der o.g.: Kontaktdaten können wieder aufgerufen werden.

Auch wenn ein Belegstatus wie 1. Mahnstuffe keine Auswirkung auf die Umsatzanzeige in der Kontaktübersicht haben müsste, sollte der Kontakt aufgerufen werden können.

Client (2.4.0.0) und Server (2.4.0.10) laufen auf demselben Ubuntu 23.04.-Rechner

**Comment by j-dimension** [comment]
https://github.com/jlawyerorg/j-lawyer-org/assets/3729754/e5c6cb76-82cf-4931-8771-36b25f29f012

**Comment by j-dimension** [comment]
@nronk  das bekomme ich nicht nachgestellt. Gehe ich im Video richtig vor?

**Comment by LazyGuy21No** [comment]
Genau so eigentlich. Schicke Dir privat ein Video

**Comment by nronk** [comment]
Kann es damit zusammenhängen, dass in deinem Video als Belegart "Angebot" ausgewählt wurde? Bei mir ist es "Rechnung". Ich hab es auch erst bemerkt, als in der Kontakt-/Umsatzübersicht kein Wert angezeigt wurde.

**Comment by j-dimension** [comment]
Ich meine das gefunden zu haben, melde mich in der Mailingliste, sobald es neue Installer gibt.
