### ISSUE TITLE
[FEATURE] "Chat" in einer Akte…

### ISSUE THREAD

**Issue by LazyGuy21No** [jlawyerorg/j-lawyer-org#1994]
Wir kommunizieren sowohl per Messenger als auch über die Etiketten zu Akte/Dokument, wenn es um eine Akte geht. Die besondere Herausforderung ist, dass es hier Menschen gibt, die während der Sommermonate aus gesundheitlichen Gründen nur nachts arbeiten: also an einer Live-Kommunikation nicht wirklich teilnehmen. 

Außerdem ist es schwer, die Kommunikation nachzuvollziehen, die zu einem deutlich zurückliegenden Zeitpunkt erfolgt ist.

Für die ungleichzeitige Kollaboration wäre es daher toll, wenn wir eine Art Akten-Chat hätte, der auch die Aktenhistorie integrieren könnte, zum Beispiel also Vorgänge, Nachrichten und Arbeitsanweisungen enthalten könnte (statt eines etwas antiquierten Verfügungssystems)

**Chat (Radost Miller):**

-- vor 2 Tagen --
**@ Thomas Müller** `fügt hinzu: Klageschrift.odt`
**@ Thomas Müller** `markiert @Alexa Kaminski zum Dokument (Klageschrift.odt) und sagt: "Bitte finalisieren, Sachverhalt in Abschnitt II. mit Mdt. besprechen; Achtung Zuständigkeit ist korrekt: Gerichtsstandsvereinbarung!"`
**📅** **@ Thomas Müller** `setzt eine Frist zu (Klageschrift.odt) für 17.07.2023 `
**@ Alexa Kaminski** `bearbeitet 'Klageschrift.odt'`

-- gestern --
**@ Alexa Kaminski**: `@ Radost Miller ich habe den Sachverhalt mit Mdt. schon besprochen und eingepflegt. @Thomas Müller`

-- heute --
**@ Radost Miller** `bearbeitet (Klageschrift.odt)`
**@ Radost Miller** `markiert (Klageschrift.odt) mit (per Fax verschicken)`
**@ Radost Miller** `löscht Markierung (per Fax verschicken) zu (Klageschrift.odt)`
**@ Radost Miller** `ändert (09314419495_Kaufvertrag_Mueller.pdf) zu (Anlage 1 Kaufvertrag.pdf)`
**@ Radost Miller** `markiert Klageschrift.odt (und 1 weitere) als (verschicken!)`
**@ Radost Miller** `ist fertig! 😅`
**@ Radost Miller** `markiert @Abrechnung (Gruppe) und sagt: Endlich abrechnen!!! Beachtet: wir haben GK-vorgeschossen: anfordern bei RSV. Bitte denk daran, auch an die anderen OP zu erinnern.`
**@ Thomas Müller** `erstellt (Klageschrift.pdf)`
**✉️ @ Thomas Müller** `verschickt (Klageschrift.pdf) und 1 weitere per beA an Landgericht Wuppertal` 
**📅 @ Thomas Müller** `ändert eine Frist zu (Klageschrift.odt) für 17.07.2023  zu: erledigt!`
**📅 @ Thomas Müller** `setzt eine WV zu Akte für 24.07.2023: Zugestellung? und markiert:  @ Thomas Müller @ Radost Miller` 
**📅 @ Thomas Müller** `hat dich soeben markiert (@ Radost Miller)`

**Comment by j-dimension** [comment]
Referenz zu #1179

**Comment by j-dimension** [comment]
Ich schliesse das hier. Bitte mal das neue Instant Messaging anschauen und dann spezifische Änderungs- / Erweiterungswünsche stellen.
