### ISSUE TITLE
[FEATURE] Volltextsuche beschränken auf eine Akte oder eine Gruppe von Akten

### ISSUE THREAD

**Issue by LazyGuy21No** [jlawyerorg/j-lawyer-org#2000]
Ein Volltext in einer Akte wäre toll. Noch toller wäre es, wenn man die Volltextsuche über mehrere Akten (nach Kriterien) aus  

Zum Beispiel: alle Akten 

… mit Anlagedatum zwischen … und …

… an denen eine bestimmte Person beteiligt ist.

… mit Bearbeiter X

**Comment by LazyGuy21No** [comment]
<img width="355" alt="image" src="https://github.com/jlawyerorg/j-lawyer-org/assets/56734761/ac24b0cd-e950-4f82-8f40-8424c83f108c">
 Sorry: vieles davon geht eigentlich, ist aber etwas nerdig zu bedienen.

**Comment by j-dimension** [comment]
Bitte die #333 oder #1926 inhaltlich schärfen, dieses Ticket hier schließe ich als Duplikat.
