### ISSUE TITLE
[BUG] Akten werden archiviert - Beteiligte dabei manchmal gelöscht

### ISSUE THREAD

**Issue by MarcoWolny** [jlawyerorg/j-lawyer-org#2001]
Ohne ersichtlichen Grund und ohne eigenes Zutun werden Akten archiviert. Teilweise (aber nicht immer) werden sämtliche Aktenbeteiligte gelöscht. Der Bug lässt sich derzeit nicht reproduzieren, kommt immer mal wieder - derzeit ca. 1x die Woche (auch mit unterschiedlichen Akten) vor. 

 - OS / Betriebssystem: Ventura 13.4.1
 - j-lawyer.org Version: 2.3.0.1

Ist das Problem bekannt?

**Comment by stm9x9** [comment]
hier nicht - das klingt ja katastrophal! Was ist denn in der Aktenhistorie zu sehen?

**Comment by j-dimension** [comment]
Mir ebenfalls nicht bekannt. Insbesondere die Archivierung wird ja nur getriggert, wenn der Haken gesetzt wird. Hier wäre ich auch an Details interessiert.

**Comment by MarcoWolny** [comment]
Ja, in der Historie heißt es dann:

"... [Timestamp] Akte abgelegt / archiviert"
"... [identischer Timestamp] Akte geändert"

Tatsächlich hat niemand den Haken gesetzt. Es trifft zu, dass in der Akte gearbeitet wurde, allerdings wurde diese nicht archiviert. Gleichwohl hat das System dies daraus gemacht. 

Ich kann ausschließen, dass der Haken gesetzt wurde und dass Beteiligte bewusst gelöscht wurden.

**Comment by stm9x9** [comment]
Welcher Nutzer wird dort angegeben?

**Comment by LazyGuy21No** [comment]
Kann es sein, dass nicht die Beteiligten sondern nur ihre Beteiligung an der Akte gelöscht wird. Das Problem haben wir gelegentlich hier auch. Es scheint damit zu tun zu haben, dass die Akte von mehreren Bearbeiterinnen gleichzeitig bearbeitet wird.

**Comment by MarcoWolny** [comment]
Es werden die Beteiligten gelöscht - der Reiter "Beteiligte" ist dann komplett leer.

Als Nutzer wird derjenige angegeben, der auch in der Akte gearbeitet hat (aber diese nicht archiviert hat). Heute einmal unsere Sekretärin in Akte A und meine Frau in Akte B - zeitlich ca. 1 Stunde versetzt.

**Comment by j-dimension** [comment]
Bitte mal den Ordner mit den client.log's bereitstellen - danke!

**Comment by MarcoWolny** [comment]
Wenn du mir sagst wo ich den finde... Die Suche ergibt nichts brauchbares...

**Comment by Dickmaulruessler** [comment]
https://www.j-lawyer.org/downloads/documentation/j-lawyer.org-UserGuide-de.html#__RefHeading___Toc12649_1781334919

**Comment by MarcoWolny** [comment]
Danke dafür  - kommt per E-Mail

**Comment by MarcoWolny** [comment]
[Screenshot.pdf](https://github.com/jlawyerorg/j-lawyer-org/files/12111572/Screenshot.pdf)

Reicht das so?

**Comment by j-dimension** [comment]
Danke, da sehen wir 9:40 Archivierung von Nutzer(in) "Höfer". Sind die mir vorliegenden Client-Logs vom Höferschen Arbeitsplatz? Wenn nicht, dann brauche ich die noch.

**Comment by MarcoWolny** [comment]
Alles klar - bin jetzt unterwegs, mache ich morgen fertig - sind nicht vom Platz Höfer.

**Comment by j-dimension** [comment]
Ich finde auch in den neuen Logs leider weder einen Fehler noch einen Anhaltspunkt. Mir ist unklar, wie ich hier helfen kann, wenn ich es nicht reproduziert bekomme.

**Comment by MarcoWolny** [comment]
Ja, ich weiß, es tritt ja bei uns auch gefühlt random auf - ist ja auch nur lästig nicht schlimm. Ich beobachte mal weiter und wenn es wieder auftritt oder eine Reproduzierbarkeit gegeben ist, melde ich das mal wieder….

**Comment by iradraconis** [comment]
Uns ist es auch schon zwei bis dreimal passiert, aber reproduzieren konnten wir es auch nicht. Schwierig, dann das Szenario nachzustellen.

**Comment by j-dimension** [comment]
> Uns ist es auch schon zwei bis dreimal passiert, aber reproduzieren konnten wir es auch nicht. Schwierig, dann das Szenario nachzustellen.

Mit den Beteiligten (dafür habe ich eine Erklärung) oder eine Archivierung (da habe ich keinerlei Ansatz)?

**Comment by iradraconis** [comment]
> > Uns ist es auch schon zwei bis dreimal passiert, aber reproduzieren konnten wir es auch nicht. Schwierig, dann das Szenario nachzustellen.
> 
> 
> 
> Mit den Beteiligten (dafür habe ich eine Erklärung) oder eine Archivierung (da habe ich keinerlei Ansatz)?

Das mit den Beteiligten meinte ich. 

Das mit dem Archivieren hatten wir auch schon, aber ich vermute da hat sich jemand bei uns "verklickt". Vielleicht könnte man den Button verlegen oder eine Nachfrage einbauen, um unbeabsichtigtes Archivieren zu vermeiden.

**Comment by j-dimension** [comment]
> Vielleicht könnte man den Button verlegen oder eine Nachfrage einbauen, um unbeabsichtigtes Archivieren zu vermeiden.

Eine solche Abfrage gibt es, wenn noch offene Kalendereinträge existieren (was bei einem aktiven Mandat der Fall sein sollte).

**Comment by iradraconis** [comment]
Okay, stimmt. Dann reihe ich mich ein in die Anwender, die unbeabsichtigt archivierte Akten haben.

**Comment by j-dimension** [comment]
Ich kann das nach wie vor nicht nachvollziehen. Bitte mit der kommenden 2.6 nochmal testen, dort ist das Archivieren mit einer detaillierteren Prüfung versehen.

**Comment by MarcoWolny** [comment]
Das Problem tritt in der aktuellen Version nach wie vor regelmäßig (2-3 Mal in der Woche) auf. In der Hälfte der Fälle sind dann auch weiterhin alle Aktenbeteiligten gelöscht.
Möglicherweise müsste/könnte man dort auch eine Sicherheitssperre einrichten, dass das System beim Löschen von Beteiligten ebenfalls nach einer Bestätigung verlangt!?

Ach und in dem Zuge (weil es ja mit dem neunen Release nicht stressig genug ist): könnte man Aktenbeteiligte „ablegen“? Es kommt ja häufig vor, dass z.B. Behörden in der Zuständigkeit wechseln, die Polizei die Akte an die Staatsanwaltschaft abgibt usw. - für diesen Fall wäre es schön und übersichtlich, wenn man Beteiligte „archivieren“ könnte. Das könnte entweder ganz einfach mit einem Hashtag #alt vor dem Beteiligten gelöst werden, hilfsweise aber auch wie bei der Archivierung der Akten (mit Archiv-Suche in den Beteiligten). Alternative (und vielleicht einfachere) Idee: Könnten wir für die Beteiligten Etiketten bekommen, die wir (wie die Aktenetiketten) selbst wählen können? Dann könnte man dort ein Etikett „alt“ und eines „aktuell“ etc. setzen. Wäre vielleicht auch nützlich, wenn besondere Kommunikationswege genutzt werden sollen, z.B. „kein Kontakt per E-Mail“ etc.

Ist sicherlich ein größeres Projekt - soll ich dafür mal ein Ticket erstellen?

Mit freundlichem Gruß 


MARCO WOLNY 
Rechtsanwalt 
Fachanwalt für Strafrecht

**Comment by stm9x9** [comment]
> Ach und in dem Zuge (weil es ja mit dem neunen Release nicht stressig genug ist): könnte man Aktenbeteiligte „ablegen“? Es kommt ja häufig vor, dass z.B. Behörden in der Zuständigkeit wechseln, die Polizei die Akte an die Staatsanwaltschaft abgibt usw. - für diesen Fall wäre es schön und übersichtlich, wenn man Beteiligte „archivieren“ könnte.

Welche Lösung ich präferieren würde, weiß ich noch nicht, aber die Problemstellung kann ich bestätigen :-D

**Comment by Dickmaulruessler** [comment]
> 
> Welche Lösung ich präferieren würde, weiß ich noch nicht, aber die Problemstellung kann ich bestätigen :-D

Das sehe ich genauso, insbesondere auch mit den von @MarcoWolny genannten Beispielen im Strafrecht. 

Es braucht dafür aber wohl ein gesondertes / neues Ticket, oder @j-dimension  ?

**Comment by j-dimension** [comment]
> Es braucht dafür aber wohl ein gesondertes / neues Ticket, oder @j-dimension ?

Ich habe wirklich keine Ahnung in welche Richtung das gehen könnte, aber dieses Ticket hier ist zu und wird inhaltlich nicht erweitert werden. Es müsste also ein neues erstellt werden.
