### ISSUE TITLE
[FEATURE] eEB aus "Dokumente" abgeben

### ISSUE THREAD

**Issue by MarcoWolny** [jlawyerorg/j-lawyer-org#2002]
Derzeit kann das eEB nur aus dem BeA-Eingang abgegeben werden. Bei uns kümmert sich das Sekretariat um die eingehenden Nachrichten und markiert diese - nachdem sie in die entsprechende Akte verschoben wurden - mit Tags "To Do Anwalt x" und "eEB abgeben". Dazu muss der Anwalt dann immer aus der Akte wieder "raus" in den BeA-Bereich, dort in den Bereich "In Akte importiert" und dort das eEB abgeben.

Ist es möglich, die Abgabe an die Nachricht zu knüpfen, sodass in der jeweiligen Akte aus dem Bereich" Dokumente" das eEB abgegeben werden kann?

**Comment by j-dimension** [comment]
Duplikat von #1948
