### ISSUE TITLE
[FEATURE] WV / Frist / Termin aus "Chronologisch" oder Desktop erstellen

### ISSUE THREAD

**Issue by MarcoWolny** [jlawyerorg/j-lawyer-org#2003]
Derzeit ist es nur möglich, Wiedervorlagen Fristen oder Termine aus der Akte selbst unter "Kalender" oder bei Erstellung eines Dokumentes / Email / BeA zu erstellen. 

Es wäre wünschenswert, wenn man - z.B. unter "Kalender" - "Chronologisch" eine neue Wiedervorlage / Frist / Termin erstellen könnte, um dann in der Maske die Akte auszuwählen, in die dieser Eintrag gespeichert werden soll. Dann müsste man nicht immer die komplette Akte laden, nur um z.B eine 2-Wochen-WV einzupflegen.

**Comment by j-dimension** [comment]
Ihr könnt unter "chronologisch" im Tab "Kalenderblatt" in den gewünschten Tag klicken und einen Eintrag erstellen - entspricht das der Vorstellung?

**Comment by MarcoWolny** [comment]
Ah, okay - das hatte ich nicht gewusst. 
Passt, danke - kann geschlossen werden! 
;)
