### ISSUE TITLE
[BUG] Rechnungsposten an Adresse können nicht gescrollt werden - UI

### ISSUE THREAD

**Issue by iradraconis** [jlawyerorg/j-lawyer-org#2007]
... und werde abgeschnitten.

<img width="779" alt="Bildschirmfoto 2023-07-20 um 10 05 09" src="https://github.com/jlawyerorg/j-lawyer-org/assets/71747937/69157e91-6197-4ff7-a589-b2800f7c9ed6">

**Comment by j-dimension** [comment]
Bis 1200 Pixel vertikal sollte nichts abgeschnitten werden. Was ist das denn für ein Screen?

**Comment by iradraconis** [comment]
MacBook Pro 16 Zoll. Allerdings mit Schriftgrößen Anpassung beziehungsweise Scaling in den Einstellungen des Clients.

**Comment by j-dimension** [comment]
Ziemlich wahrscheinlich gibt es dann auch in anderen Dialogen bereits Einschränkungen. 1200 ist das Limit das ich versuche einzuhalten, weil es viele Screens gibt, die vertikal nur 1280 auflösen.

**Comment by iradraconis** [comment]
Ich habe die Schriftgröße auf 2 gesetzt. Und der Bereicht der Etiketten ist hier bspw. auch scrollbar. Ist für mich jetzt kein riesen Problem, war mir aber aufgefallen. 

<img width="1540" alt="Bildschirmfoto 2023-07-23 um 07 10 29" src="https://github.com/jlawyerorg/j-lawyer-org/assets/71747937/b4289dbd-3d37-4314-a7cc-98be3a65e224">
<img width="587" alt="Bildschirmfoto 2023-07-23 um 07 12 17" src="https://github.com/jlawyerorg/j-lawyer-org/assets/71747937/45129e65-0c0b-4407-a118-99fc538aad80">

**Comment by j-dimension** [comment]
Würde das gern schließen. Bei üblicher Skalierung passt alles auf den Screen, wenn nicht, dann wird die Grafik skaliert. Die Legende kann ich nicht sinnvoll skalieren, ist aber auch nicht zwingend notwendig, die die einzelnen Pie Chart-Elemente einen Tooltip haben, der die Legende unnötig macht. 

Okay?

**Comment by stm9x9** [comment]
Ich bin etwas verwirrt, was hat denn skalieren oder nicht skalieren mit scrollen können zu tun?
