### ISSUE TITLE
[BUG] Ändern der Beschreibung des Belegs  nach ändern des Nummern Kreises  oder des Typs; Aktualisierung im Reiter Dokumente 

### ISSUE THREAD

**Issue by iradraconis** [jlawyerorg/j-lawyer-org#2009]
Ich weiß nicht, ob das so gewünscht ist, aber mir ist Folgendes aufgefallen : 

meine Mitarbeiterin erstellt einen Beleg und hat nur Zugriff auf den Nummernkreis  "Entwürfe".  Im nächsten Schritt gehe ich dann in die  Belegerstellung und ändere den Nummernkreis auf den Standard Nummernkreis und klicke auf den Haken.  Die Bezeichnung  des Belegs ändert sich dann allerdings nicht, sodass nicht die neue  bzw. dann richtige Rechnungsnummer eingetragen ist sondern noch die zuletzt gespeicherte Bezeichnung einschließlich der Nummer aus dem Belegkreis. Die neue Rechnungsnummer wird oben links im Belegerstellungsfenster angezeigt und im Fenster Titel.  

Es wäre schön, wenn die Bezeichnung für den erstellten Beleg sich selbst aktualisieren würde, damit die neue Rechnungsnummer etc. per copy and paste übernommen werden kann.

Nachdem ich  die Belegbeschreibung geändert habe, wird die neue Bezeichnung  unter dem Reiter Dokumente erst dann angezeigt, wenn ich die Akte einmal verlasse und dann wieder hinein gehe.

**Comment by j-dimension** [comment]
Ich werde die Bezeichnung auf einen neutralen Wert setzen, der dann nicht angepasst / aktualisiert werden muss.

**Comment by stm9x9** [comment]
Ich bin mir nicht sicher, ob ich die Lösung richtig verstehe bzw das Problem. Soweit ich es verstehe, ist es immer noch vorhanden:

Nach der Umstellung vom Entwurfsnummernkreis auf den Standardkreis ist in der Dokumentenliste immer noch der alte Nummernkreis genannt und nicht die neue, echte Rechnungsnummer:

![image](https://github.com/user-attachments/assets/807db233-0851-440e-ace7-e3ebe7c236ed)

Erst nach einem Sprung auf den Desktop und wieder in die Akte wird die korrekte angezeigt.
