### ISSUE TITLE
[BUG] Urteile und Gesetze gibt Fehlermeldung aus, ist aber ohnehin "tot"

### ISSUE THREAD

**Issue by iradraconis** [jlawyerorg/j-lawyer-org#2011]
![grafik](https://github.com/jlawyerorg/j-lawyer-org/assets/71747937/694e9fc2-8be8-4469-a459-829d6ce68b17)

Die Seite ist seit Jahren nicht gepflegt. Für einen juristischen Suchdienst ein K.O. Kriterium. Braucht es noch die Integration in jLawyer?

**Comment by Dickmaulruessler** [comment]
#1601 #250
