### ISSUE TITLE
[FEATURE] Suche/Filterung Wiedervorlagen, Fristen und Termine

### ISSUE THREAD

**Issue by Linkki2021** [jlawyerorg/j-lawyer-org#2013]
In Kalender/suchen wären erweiterte Suchmöglichkeiten toll.

Als Filter wäre "Anwalt" und "verantwortlich" spannend.

Viel interessanter wäre aber noch, wenn man die Liste nach Freitext in Grund oder Beschreibung filtern könnte, ggf. auch Kurzrubrum

Derzeit läuft das bei uns bei Bedarf via Export und dann Suche in Excel/Libre.

**Comment by j-dimension** [comment]
Könnte mir eine Volltextsuche in der Liste unter "chronologisch" gut vorstellen - was meint Ihr dazu?

**Comment by Linkki2021** [comment]
Bin ich persönlich offen, würde für uns funktionieren. Aber machst Du so nicht eine zweite Suchlogik auf?

Es gibt ja schon "suchen", wo man in "nach Aktenzeichen" auch nach Text sucht.

**Comment by j-dimension** [comment]
Aktenzeichensuche zur Volltextsuche erweitert, durchsucht die meisten Felder.

![grafik](https://github.com/jlawyerorg/j-lawyer-org/assets/3729754/d6260feb-eda1-4be3-aa3f-706f4789d1f5)
