### ISSUE TITLE
[BUG] Aktenvorschlag in Drebis nicht korrekt

### ISSUE THREAD

**Issue by Linkki2021** [jlawyerorg/j-lawyer-org#2015]
Die Akte, wo es hingehört wird korrekt erkannt. Der Vorschlag-Dialog kann das dann aber nicht auflösen, so dass man nochmal suchen muss.

<img width="132" alt="image" src="https://github.com/jlawyerorg/j-lawyer-org/assets/77149788/0e2fa521-79b5-454b-a7f9-44cb1ad50871">

Das Problem ist wiederkehrend, habe jetzt aber mal an ein Ticket gedacht.

Siehe auch #1906

**Comment by j-dimension** [comment]
@Linkki2021 ich benötige dazu das verwendete Aktenzeichenschema (am besten direkt einen Screenshot des Aktenzeichenschema-Einstellungsdialogs)  - danke!

**Comment by Linkki2021** [comment]
![Image](https://github.com/jlawyerorg/j-lawyer-org/assets/77149788/4e9dc4b8-b239-4d4e-8ac4-3efecf46dddf)

**Comment by j-dimension** [comment]
Akte nun im Suchdialog vorausgewählt zwecks Ordnerauswahl. Im Normalfall ist dort also nur zu bestätigen.
