### ISSUE TITLE
[FEATURE] Nachrichtencenter für externe Anwendungen schaffen

### ISSUE THREAD

**Issue by Linkki2021** [jlawyerorg/j-lawyer-org#2018]
Wir haben eine Web-Anwendung mit j-lawyer verknüpft, in der Nutzer Kommentare hinterlassen können. Derzeit werden wir darüber via Mail benachrichtigt. Dann ziehen wir die Mail in die Akte etc.

Es wäre eine super Sache, wenn es analog Drebis, bea etc. ein  Nachrichtencenter gäbe, in dem externe Nachrichten verarbeitet und einer Akte zugeordnet bzw. per API gesendet und in jlawyer weiterverarbeitet werden können.

Dies könnte auch von anderen Web-Anwendungen als unserer genutzt werden.

Eine weitere Ausbaustufe, ggf. ist das aber auch ein separates Thema, es könnten auch Nachrichten aus einer Akte via API an die verknüpfte Web-Anwendung gesendet werden.

--------------- @j-dimension 2023-09-11 ----------------------------

- [x] Datenmodell: Nachricht: Autor, (plain) Text, empfangen Zeitstempel, Aktenkontext (optional)
- [x] Datenmodell: Erwähnung (Nachricht kann Erwähnungen von 0..n User Accounts enthalten, die dann auch separat als erledigt markiert werden sollten: user id, erledigt markiert (Zeitstempel)
- [x] UI: Oberflächenelement für Nachrichtendarstellung entwickeln - es gibt kein fertiges Callout oder ähnliches
- [x] UI: Oberflächenelement für Verfassen von Nachrichten entwickeln: Darstellung, @-Erwähnungen mit auto complete, Nutzer-Icon, ...
- [x] UI: zentraler Nachrichtenüberblick - muss noch detailliert werden, Ideen: Darstellung über alle Akten hinweg, Volltextsuche
- [x] UI: Darstellung der aktenbezogenen Nachrichten direkt auf dem ersten Tab der Akte - muss noch detailliert werden
- [x] UI: Aktion auf Dokumentenkontext muss anders behandelt werden, je nachdem ob man im Nachrichtencenter oder in der Akte ist
- [x] UI: Tab "Erwähnungen" im Nachrichtencenter, wo man nur Nachrichten sieht, in denen man selbst erwähnt wurde
- [x] UI: im Nachrichtencenter die Tabs der Akten nach links sortieren, die neue Nachrichten haben
- [x] Server / UI: Mentions brauchen Änderungsdatum, Mentions anhand des Änderungsdatum pollen und Status im Client updaten über InstantMessageMentionChangedEvent
- [x] UI: Pop Out-Fenster für Nachrichten
- [x] UI: Aktion Nachricht erstellen und senden
- [x] UI: Aktion Nachricht in Akte erstellen und senden
- [x] UI: Aktion Nachricht für ein oder mehrere Dokumente erstellen und senden
- [x] UI: Aktion Nachricht beantworten
- [x] UI: Aktion Nachricht (Erwähnung) erledigt markieren
- [x] UI: Nachrichtendarstellung sollte für andere Nutzer anzeigen, ob die Erwähnung als erledigt markiert wurde
- [x] UI: Nachrichtenindikator auf Desktop
- [x] Server: Servicelayer und Geschäftslogik
- [x] Server: aus neuer Nachricht die @ - mentions extrahieren und Mentions erstellen
- [x] #2120
- [x] API: Nachricht erstellen
- [x] API: Nachrichten einer Akte listen
- [x] API: Nachricht löschen
- [x] ~~API: Nachricht aktualisieren (evtl. nicht notwendig)~~
- [x] Web Hook: neue Nachricht (externe Anwendung könnte sich so über neue Nachrichten informieren lassen und selbst entscheiden, ob eine Nachricht für die Anwendung relevant ist)
- [x] Web Hook: neue Nachricht, mit vollem Payload
- [x] ~~Web Hook optional: Erwähnung wurde als gelesen / erledigt markiert~~
- [ ] Tests

zu klären:
- Das Feature hat das Potential, soetwas wie "moderne Verfügungen" abbildbar zu machen. Abgrenzung zu Wiedervorlagen klären.
- Wird eine Referenz zu einem bestimmten Dokument benötigt? Wahrscheinlich schon...

**Comment by j-dimension** [comment]
Backend und REST API erledigt und wird mit 2.4 geliefert. UI mache ich direkt, aber evtl. in separatem Release.

**Comment by j-dimension** [comment]
erster Prototyp für Nachrichtendarstellung und -versand. Ein externes System würde dann einen eigenen Account bekommen, sich für den Web Hook registrieren und hat eine einfache Möglichkeit zu erkennen, ob die Nachricht sich an den eigenen Account richtet (durch Erwähnung). 

UI-Features Nachrichtendarstellung:
- unterschiedliche Farben für eigene (gesendete) und empfangene Nachrichten
- Darstellung eines Nutzerkürzels 
- Nutzernamen werden gehighlighted
- eigener Nutzername gesondert hervorgehoben
- Indikator der anzeigt, ob man eine Nachricht, in welcher man erwähnt wurde, zur Kenntnis genommen hat
- Klick auf Indikator setzt den Status

UI-Features Nachrichtenversand
- Auto complete für Erwähnungen mittels "@"-Zeichen

**Comment by j-dimension** [comment]
https://github.com/jlawyerorg/j-lawyer-org/assets/3729754/d6dc57db-0045-43b4-9152-3951b8648c02

**Comment by iradraconis** [comment]
Mega Feature !! Das brauchen wir! 😍

**Comment by j-dimension** [comment]
https://github.com/jlawyerorg/j-lawyer-org/assets/3729754/e25a7070-e6b8-4d16-892c-c0008b7e2aed

**Comment by j-dimension** [comment]
Beispiel mit Client-to-Client mit unterschiedlichen Nutzern, Anzeige und Navigation Aktenkontext / Dokumentenkontext, Tabs pro Akte, Hashtagfilter:


https://github.com/jlawyerorg/j-lawyer-org/assets/3729754/c592d3b0-e0c5-4970-8fd2-2cc04920cbfb
