### ISSUE TITLE
[BUG]  Leistungszeitraum - Aktenanlage anstatt Tag der Rechnungserstellung

### ISSUE THREAD

**Issue by iradraconis** [jlawyerorg/j-lawyer-org#2019]
Siehe Screenshot.  Wäre es nicht sinnvoll, der Dialog würde bei Angabe des Zeitraums das Datum der Aktenerstellung auslesen und direkt eintragen? 

![Bildschirmfoto vom 2023-07-31 07-45-04](https://github.com/jlawyerorg/j-lawyer-org/assets/71747937/4d1669f1-7377-4cc8-a168-e159a3c0d0aa)

**Comment by j-dimension** [comment]
Das wird nicht immer passen, bspw. wenn erfasste Zeiten monatlich abgerechnet werden o.ä. 
Als Voreinstellung aber wahrscheinlich besser geeignet.
