### ISSUE TITLE
[BUG] unnötiger Doppelpunkt bei Übernahme von Positionen aus Rechnungsplugin

### ISSUE THREAD

**Issue by iradraconis** [jlawyerorg/j-lawyer-org#2020]
Der Doppelpunkt ist m.E. überflüssig.

![Bildschirmfoto vom 2023-07-31 10-07-21](https://github.com/jlawyerorg/j-lawyer-org/assets/71747937/8998de6a-9f23-46fa-aa60-1399e9b6465f)

**Comment by j-dimension** [comment]
Bereits behoben via https://github.com/jlawyerorg/j-lawyer-org/commit/9db614d187845375ed59695413519caa4dd8d736

Installer gibt es hier: https://cloud.j-dimension.com/index.php/s/wscJLx3KDCKoEWm?path=%2FVorschau%2F2023-07-26_2.4.0

**Comment by iradraconis** [comment]
Hallo Jens, ich habe diese Version installiert. Der Doppelpunkt ist aber dennoch vorhanden.
