### ISSUE TITLE
[BUG] Belegfenster: Zuvor ausgewählter Rechnungsempfänger wird bei Ändern des Rechnungskreises abgewählt

### ISSUE THREAD

**Issue by iradraconis** [jlawyerorg/j-lawyer-org#2023]
siehe Titel. Vielleicht ist das so gewollt. Es war mir nur aufgefallen.

**Comment by j-dimension** [comment]
Ich bekomme das nicht reproduziert, allerdings gab es noch einige Änderungen bzgl. der Belege. Ich schließe. In Kürze werde ich nochmal eine Version bereitstellen - dann gern nochmal testen.
