### ISSUE TITLE
[FEATURE] Nachfrage, wenn kein Rechnungsempfänger ausgewählt

### ISSUE THREAD

**Issue by iradraconis** [jlawyerorg/j-lawyer-org#2024]
Mir passiert es recht häufig, dass ich "vergesse" einen Rechnungsempfänger auszuwählen. Vielleicht könnte für den Fall, dass keiner ausgewählt wird, vor dem Verlassen des Dialogs oder Speichern eine Warnung kommen, dass kein RE ausgewählt wurde. Oder wenn man durch solche wegzuklickenden Dialoge schnell genervt ist, könnte auch das Empfängerfeld rot oder dezenter hinterlegt sein. 

Der Button ist so unscheinbar, dass das hier (auch bei anderen Nutzern) häufig übersehen wird.

**Comment by j-dimension** [comment]
![grafik](https://github.com/jlawyerorg/j-lawyer-org/assets/3729754/55153612-fe1f-4b0b-8517-dfe4bfc977ab)
