### ISSUE TITLE
[beA] [bug] Reihenfolge beA EEB-Abgabe - Hauptdokument 

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-org#2035]
Das EEB wird im BEA zuerst angeklickt und landet dann im Dokumentenordner. Dann speichert man das Hauptdokument ab, das landet dann aber hinter dem abgegebenen EEB... Umgekehrt wäre logischer

**NOTE: Please search existing tickets to avoid duplicates **
**HINWEIS: Bitte vorab die Ticketsuche verwenden, um Doppeleinträge zu vermeiden **

**Describe the bug / Fehlerbeschreibung**
(todo: a description of the bug / eine Beschreibung des Fehlers)

**To Reproduce / Schritte zum Nachvollziehen**

1. Go to / Gehe zu '...'
2. Klicke auf / Click on '....'
4. Error message / Fehlermeldung: '...'

**Expected behavior / Erwartetes Verhalten**
Eine Beschreibung des erwarteten Verhaltens.

**Screenshots**
Falls relevant, Screenshot beifügen.

**Environment / verwendete Umgebung:**
 - OS / Betriebssystem:
 - j-lawyer.org Version:

**Additional context / Sonstiges**

**Comment by j-dimension** [comment]
Werde hier vorerst nicht anpassen. Bei den beA-Nachrichten und Mails wird das Empfangsdatum als Dokumentdatum verwendet, was mir logisch erscheint.
