### ISSUE TITLE
[FEATURE] Markdown Vorschau und Editor für Dokumente - umschaltbar per Button

### ISSUE THREAD

**Issue by iradraconis** [jlawyerorg/j-lawyer-org#2037]
Toll wäre eine Vorschau für Markdown Dateien, die auch die Formatierung berücksichtigt. Ein Button könnte zwischen Edit/Lesemodus umschalten. 

Md - Dateien können zwar aktuell bearbeitet aber noch nicht erstellt werden. Die Vorschau macht aktuell keine Zeilenumbrüche. Man kann die Änderungen in der Vorschau auch aktuell nicht speichern. Aktuell ist es nur sinnvoll, die MD Datei mit Libreoffice oder sonst einem Programm zu öffnen.

**Comment by j-dimension** [comment]
Ein Editor ist es noch nicht, aber einen Viewer habe ich eben hinzugefügt:

![grafik](https://github.com/user-attachments/assets/541a1511-4703-4c37-acb5-506f3e704131)

**Comment by j-dimension** [comment]
Ein Editor ist es noch nicht, aber einen Viewer habe ich eben hinzugefügt:

![grafik](https://github.com/user-attachments/assets/50009aaa-0c06-43d2-b620-c5072fdf388d)

**Comment by iradraconis** [comment]
Mega!!
