### ISSUE TITLE
fehlerhafte Namenssuche bei Eintrag in Beteiligte 

### ISSUE THREAD

**Issue by RobertT01** [jlawyerorg/j-lawyer-org#2043]
Wenn ich einen Beteiligten in eine Akte eintragen will und dabei mich bei dem ersten Eintrag verschrieben habe, funktioniert die Suche nur richtig, wenn man mehrere Buchstaben ändert.

Beispiel:

Ich suche als erstes den Nachnamen Schmidt, es werden alle Einträge mit Schmidt angezeigt
Ich ändere den Eintrag auf Schmit. Es kommt keine Änderung.   
Ich ändere auf Schmid. Es kommt keine Änderung.

Ich komme auch auf keine logische Regel dem das System folgt.

**Comment by RobertT01** [comment]
Danke, kannst Du mir das fürn Client zum testen schicken?

**Comment by j-dimension** [comment]
Muss noch etwas warten, da ich gerade noch ein beA-Upgrade umsetze :-(
