### ISSUE TITLE
[kalender] Verknüpfung von sachbearbeitenden RA und "seinen" Farben im Kalender

### ISSUE THREAD

**Issue by RobertT01** [jlawyerorg/j-lawyer-org#2046]
Es wird ja bei jeder Akte ein Anwalt hinterlegt. 
Im Kalender hat jeder Anwalt für VW, Fristen und Terminen jeweils eine Farbe. 
Kann man den Anwalt/die Anwältin der Akte automatisch mit "seine/ihren Farben verknüpfen? 
D.h. wenn ich eine Akte anlege oder einen Anwalt der Akte zuordne oder ggfls wechsle, dass dann bei den WV, Terminen und Fristen automatisch immer dessen Kalenderfarbe genommen wird und man das grundsätzlich händisch ändern muss, wenn es ein anderer Sachbearbeiter machen soll.

**Comment by hackvokat** [comment]
Das halte ich für sehr sinnvoll.

Wir haben ständig das Problem, dass eine WV eingetragen wird und dann der falsche WV-Kalender ausgewählt ist. Wenn man den bei jedem Eintrag nicht manuell auswählt, gibt es ein Durcheinander.

Wenn jeder Nutzer fix mit seine Kalendern verbunden ist, sollte das Problem nicht mehr auftreten. Dann müsste man nur noch manuell etwas auswählen, wenn man eine Abweichung vom Standard will.

**Comment by j-dimension** [comment]
Bitte schaut Euch #2238 an, das ist ein anderes Regelwerk, das die Problematik jedoch wesentlich entschärfen sollte.
