### ISSUE TITLE
[beA] Strukturdatensatz

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-org#2049]
Es ist ein guter Ansatz, dass die PDF in der Dokumentenansicht (Vorschau) im ReiterAnhänge erscheinen, andere Dateien unter weitere. Ich halte es für sinnvoll, dass der Xjustiz-Strukturdatensatz .xml auch unter weitere erscheint. Ein Schritt zur Übersichtlichkeit, was man da alles vom Gericht geschickt bekommt.

**Comment by j-dimension** [comment]
Verglichen mit den anderen technischen Anhängen, ist der XJustiz-Datensatz schon eher wichtig. Mich würden weitere Meinungen interessieren, bspw. von @stm9x9

**Comment by Dickmaulruessler** [comment]
Ich wäre auch für "weitere"

**Comment by stm9x9** [comment]
soweit ich das sehe, werden alle Infos aus der xjustiz schon anderweitig dargestellt? Die Anzeigenamen in () und die Aktenzeichen im Header. Und sie ist auch rechts über Strukturdatensatz anzeigen zu öffnen? Dann wäre ich auch für weitere.

**Comment by Dickmaulruessler** [comment]
Wie sieht es beim beA-Empfang mit dem Versandprotokoll...[...]....html aus?

Könnte das nicht auch in "weitere"?
