### ISSUE TITLE
Anpassen von {{BEL_TABELLE}}

### ISSUE THREAD

**Issue by alexhell** [jlawyerorg/j-lawyer-org#2051]
- [x] Die Spalte "Einzel" ist bei mir viel größer als "Gesamt", obwohl bei "Gesamt" generell die größeren Summen stehen werden. 
- [x] Bei Beträgen über > 10k EUR wird das "EUR" auch umgebrochen. (Schriftgröße 12 roboto).
- [x] Es fehlt mir bei den Zeilen der Einzelpositionen das Währungszeichen am Ende (bei  Umsatzsteuer/Zahlbetrag ist es vorhanden).
- [x] Kann man Umsatzsteuer in USt. umbenennen?
- [x] Der Tausenderpunkt oder das besagte geschützte Leerzeichen fehlt mir.

**Comment by j-dimension** [comment]
Zwei der Punkte habe ich umgesetzt, der Rest muss etwas warten. Ich kann das Release nicht mehr länger liegen lassen / warten lassen.

**Comment by LazyGuy21No** [comment]
Wir würden die Funktion gerne Nutzen, aber dass MA jedes Mal die Tabellenbreite manuell anpassen müssen ist ein Downer. Bitte priorisiert fixen

**Comment by j-dimension** [comment]
> Wir würden die Funktion gerne Nutzen, aber dass MA jedes Mal die Tabellenbreite manuell anpassen müssen ist ein Downer. Bitte priorisiert fixen

Es liegt nicht an fehlender Priorisierung, sondern an fehlenden Möglichkeiten :-(

**Comment by LazyGuy21No** [comment]
Alternativ: Keine Tabelle sondern Tabulatoren als Fix? Andere Programme verwenden ausschließlich Tabulatoren im Rechnungskörper. Das wirkt zwar auf den ersten Blick ungewöhnlich klappt m.E. total gut.

**Comment by j-dimension** [comment]
Ich habe jetzt folgenden funktionierenden Ansatz: 
- in der Vorlage wird die Tabelle mit der korrekten Anzahl an Spalten aufgenommen
- die Spalten werden in die gewünschte Breite gebracht
- der Platzhalter kann sich in einer beliebigen Zelle befinden - beliebig, da es keinen Sinn ergibt, einen langen Platzhalternamen in eine ganz schmale Spalte aufnehmen zu müssen
- es darf innerhalb der Tabelle weitere Zeilen und Inhalte geben, primär um die Vorlage verständlicher zu machen. Einfach leere Zellen zu sehen, ist schwer zu erschließen

Möglich sind also bspw. 

![grafik](https://github.com/jlawyerorg/j-lawyer-org/assets/3729754/4eaa83bc-824e-4477-a977-22c8c866e5a2)

und

![grafik](https://github.com/jlawyerorg/j-lawyer-org/assets/3729754/e6b68155-0144-438d-bb7a-5037b50cf621)

oder auch

![grafik](https://github.com/jlawyerorg/j-lawyer-org/assets/3729754/95a4383c-43ee-414b-83f9-7afb3b14c536)


Bei Erstellung eines Dokuments aus der Vorlage, bleiben die Spaltenbreiten erhalten.

**Comment by j-dimension** [comment]
Erfolgreich getestet mit LibreOffice und Microsoft Office.

Das "automatische Breite"-Feature ist bei Nutzung über die APIs schlicht kaputt.

**Comment by LazyGuy21No** [comment]
Funktioniert aktuell schon, oder mit der kommenden Version?

**Comment by j-dimension** [comment]
@LazyGuy21No in der kommenden. Evtl. wird die etwas kleiner vom Scope, damit das schneller veröffentlicht werden kann.

**Comment by j-dimension** [comment]
Doku erweitert
