### ISSUE TITLE
[FEATURE] Api Endpunkt zur Abfrage der am Server hinterlegten Dokumenten-Etiketten

### ISSUE THREAD

**Issue by iradraconis** [jlawyerorg/j-lawyer-org#2054]

**Comment by j-dimension** [comment]
![grafik](https://github.com/jlawyerorg/j-lawyer-org/assets/3729754/3d4662fc-44c2-4f3a-9795-ae6ad595419e)

**Comment by j-dimension** [comment]
![grafik](https://github.com/jlawyerorg/j-lawyer-org/assets/3729754/356278f3-a7f6-453f-b8a3-04be87248b00)

**Comment by j-dimension** [comment]
@iradraconis für das Plugin werden nur die Dokumentetiketten benötigt, da reicht also ein direkter Aufruf des zweiten Endpunkts mit der optiongroup "document.tags".
