### ISSUE TITLE
[FEATURE] API - Erweiterung: Email Vorlagen per API abrufbar machen

### ISSUE THREAD

**Issue by iradraconis** [jlawyerorg/j-lawyer-org#2055]
Zweck: Zugriff auf eMail-Vorlagen von externem Mail Programm

**Comment by j-dimension** [comment]
Muss ich aufgrund des Aufwandes ggf in die 2.5 schieben.

**Comment by j-dimension** [comment]
@iradraconis hier würde es um das reine Abrufen der Vorlagen gehen, oder auch um ein "ausfüllen lassen"?

**Comment by iradraconis** [comment]
Am besten analog den allgemeinen Vorlagen. Also mit Platzhalter Funktion.

**Comment by iradraconis** [comment]
Ist das ein größeres Ding? 
Wenn es das in die 2.7 schaffen würde, könnte ich die Erweiterung für Thunderbird bis zum nächsten j-Lawyer Release vorantreiben.

**Comment by iradraconis** [comment]
bump
