### ISSUE TITLE
[BUG] Thunderbird als externes Programm für Emails

### ISSUE THREAD

**Issue by iradraconis** [jlawyerorg/j-lawyer-org#2056]
ich möchte Thunderbird (macOs) zum Öffnen von eml Dateien verwenden. Meine Konfiguration funktioniert nicht. Es öffnet sich der Standard Viewer von j-Lawyer. Ich habe auch den Aufruf über Applications/Thunderbird/contents.... etc. probiert. Dasselbe Ergebnis. Was mache ich falsch? 

<img width="635" alt="Bildschirmfoto 2023-08-29 um 13 44 04" src="https://github.com/jlawyerorg/j-lawyer-org/assets/71747937/1e8dce9d-3590-48f3-bb4c-06ffebea0882">

**Comment by j-dimension** [comment]
Die Variante per Rechtsklick ist Dir bekannt, oder?

**Comment by iradraconis** [comment]
Ja ist mir bekannt. Ich wollte den Standard ändern.

**Comment by librelegal** [comment]
Auch ich würde Thunderbird gerne dafür nutzen, auch wegen der sehr intensiver Nutzung von Verschlüsselung  (das sollten auch andere so handhaben: https://www.heise.de/news/Bremer-Datenschutzbehoerde-fordert-Ende-zu-Ende-Verschluesselung-bei-Anwaelten-9287570.html).
Mit dem workflow ließe sich das vielleicht so kombinieren, dass jede e-mail automatisch im BCC (als weiteren Empfänger) das Sekretariat hat. Dieses kann dann die dort eingehende E-Mail als durch die RAin versandte E-Mail speichern.

**Comment by Dickmaulruessler** [comment]
> Mit dem workflow ließe sich das vielleicht so kombinieren, dass jede e-mail automatisch im BCC (als weiteren Empfänger) das Sekretariat hat. 

siehe #1453 
dort kann man noch "[auf den Zug aufspringen](https://github.com/jlawyerorg/j-lawyer-org/issues/1453#issuecomment-966577676)" :-)

**Comment by librelegal** [comment]
Danke, aber ich habe die E-Mail-Funktion in j-lawyer noch nicht genutzt, gerade weil ich lieber Thunderbird nutzen will.
#1453 will ja offenbar in der j-lawyer-E-Mail-Funktion eine Änderung erreichen

**Comment by Dickmaulruessler** [comment]
> #1453 will ja offenbar in der j-lawyer-E-Mail-Funktion eine Änderung erreichen

Ja, aber letztendlich mit dem Hintergedanken zukünftig **standardmäßig** vielleicht doch die **j-lawyer-**E-Mail-Funktion zu verwenden, die Komfort-E-Mailfunktionen (bei mir vor allem die Suchfunktion) und "einfach **alle** E-Mails in **einem** Programm" durch die BCC-Weiterleitung an Thunderbird und Outlook aber dennoch nutzen zu können.

**Comment by iradraconis** [comment]
Es wird bald eine j-Lawyer-Extension für Thunderbird geben, die ein Speichern von E-Mails in Akten ermöglicht. Das dürfte für diejenigen interessant sein, die ihre Mails gern in Thunderbird schreiben und sichergehen wollen, dass die Mails (Eingang und Ausgang) in der passenden Akte landen. Siehe auch #1869 

Die Extension ist vor allem auch deshalb nützlich, weil man "von unterwegs" per VPN eingehende Mails direkt an den Server und in die Akte schicken kann, ohne dafür den Client öffnen zu müssen.

**Comment by librelegal** [comment]
Ich versuche gerade thunderbird unter Linux als externe Anwendung zu starten, finde aber keine Dokumentation dazu. Was muss man denn da eingeben?

**Comment by iradraconis** [comment]
Siehe oben :) da ist doch ein Screenshot.

**Comment by librelegal** [comment]
Das sind ja Einstellungen für MacOS ich bin aber unter Linux (debian) unterwegs, da ist vermutlich etwas anders bei der ausführbaren Datei. Habe aber alles sonst so eingeben. Aber /usr/bin/thunderbird als Pfad. Klicke ich dann auf Testen geht ein Fenster auf, was mir die Auswahl eines .eml erlaubt. Das klappt eben nicht

**Comment by iradraconis** [comment]
So sieht es bei mir unter Fedora aus. Thunderbird ist bei mir dort im Pfad als Flatpak installiert. Du solltest mal mit dem Finder (welcher auch immer) nach Thunderbird suchen. Wenn du irgendwo den Ordner findest, in dem, die ausführbare Datei liegt, dann die natürlich auswählen. 

![grafik](https://github.com/jlawyerorg/j-lawyer-org/assets/71747937/f1925017-a095-414d-8e1d-7baa014847ff)

**Comment by librelegal** [comment]
gelingt mir nicht

**Comment by j-dimension** [comment]
unter /usr/bin befinden sich oft Links zu den installierten Anwendungen. 

Hier: /usr/bin/thunderbird
(Kubuntu)

**Comment by librelegal** [comment]
![image](https://github.com/jlawyerorg/j-lawyer-org/assets/37673969/8cf24b74-865e-410f-aa94-69fa77cb06ac)

**Comment by librelegal** [comment]
![image](https://github.com/jlawyerorg/j-lawyer-org/assets/37673969/00223347-b5ca-4489-b7ae-05ea6415812d)

**Comment by librelegal** [comment]
![image](https://github.com/jlawyerorg/j-lawyer-org/assets/37673969/5db0614a-2b36-4b80-a7a2-6c73ad75327a)

**Comment by librelegal** [comment]
gehen alle nicht

**Comment by j-dimension** [comment]
Bitte genauer beschreiben. Was heißt "geht nicht"? Passiert nichts? Kommt ein Fehler?

**Comment by librelegal** [comment]
Folgende Pfade führen nicht zu einem Start des Programms thunderbird:
/usr/lib/thunderbird/thunderbird-bin (sichtbar nach Speichern der Einstellungen ist nur ohne slash "usr/lib/thunderbird/thunderbird-bin")

/usr/lib/thunderbird/thunderbird (sichtbar nach Speichern der Einstellungen ist nur ohne slash "usr/lib/thunderbird/thunderbird")

/home/xxx/.local/share/applications /thunderbird (wobei anstelle von xxx der username steht)
 
Bei Klick auf Verbindungstest, öffnet sich ein Ordner und wird nach einer eml gesucht, was ich mit Abbruch quittiere. Nach Speichern der Einstellungen wird bei Klick auf eine E-Mail-Adresse eines Kontakts, um eine E-Mail zu schreiben, die j-lawyer eigene E-Mail-Anwendung anstele von thunderbird gestartet.

**Comment by librelegal** [comment]
Auf der Kommandozeile meines Laptops kann ich im Ordner /home/xxx/.local/share/applications/ (wobei anstelle von xxx der username steht) durch Eingabe thunderbird eben dieses externe Programm öffnen. Das geht in j-lawyer in der Administrator-Konsole nicht, was ich für nachvollziehbar halte, weder sollte der Administrator das Öffnen können noch liegt der Server auf dem Laptop, vielmehr im Netzwerk 

Beachtlich ist noch, dass eine in einer  Akte gespeicherte eml-Datei sich mit Doppelklick gar nicht öffnen läßt. Bei Rechtsklick kann ich diese mit LibreOffice öffnen, nicht aber mit dem ebenfalls angebotenen thunderbird, auch nicht, wenn das Programm bereits geöffnet ist.

Angeboten wird bei Rechtsklick weiter unten auch das Öffnen mit externem Mail-Programm, doch funktioniert das nicht.

**Comment by j-dimension** [comment]
Wie erwähnt: /usr/bin/thunderbird ist die ausführbare Datei (bzw. ein symbolischer Link zur ausführbaren Datei, welchen der Client nach Bestätigung dann auch auflöst). Die Einstellungen sollten so aussehen: 

![grafik](https://github.com/jlawyerorg/j-lawyer-org/assets/3729754/9fee0f74-23df-4656-bb6c-83472906ac21)

**Comment by j-dimension** [comment]
Zum Tragen kommt das nur in der Dokumentenliste, nicht am Beteilligten oder in der Adresse. Daher auch der Einstellungsdialog unterhalb "Dokumente".

**Comment by librelegal** [comment]
Bei mir klappt es mit diesen Einstellungen nicht. Auch nach Neustart kann ich nicht eine .eml-Datei mit thunderbird öffnen.

**Comment by j-dimension** [comment]
Dann bitte nach einem Doppelklick auf eine .eml direkt einen Systemreport generieren und per E-Mail an mich senden.

**Comment by j-dimension** [comment]
Da kommt ein 

`java.io.IOException: Cannot run program "/usr/lib/thunderbird/thunderbird.sh": error=2, Datei oder Verzeichnis nicht gefunden`

Ist evtl. der symbolische Link kaputt? Was gibt

`ls -l /usr/lib/thunderbird/thunderbird.sh`

**Comment by librelegal** [comment]
ls: Zugriff auf '/usr/lib/thunderbird/thunderbird.sh' nicht möglich: Datei oder Verzeichnis nicht gefunden

![image](https://github.com/jlawyerorg/j-lawyer-org/assets/37673969/840657cc-f4cb-453f-9ffa-a2ceafcfe024)

gebe ich im Terminal hier ein Enter /usr/lib/thunderbird$ thunderbird  öffnet sich das Programm

**Comment by j-dimension** [comment]
Dann ist der symbolische Link auf Deinem System kaputt. Was gibt

`whereis thunderbird`

**Comment by librelegal** [comment]
thunderbird: /usr/bin/thunderbird /usr/lib/thunderbird /etc/thunderbird /usr/share/thunderbird /usr/share/man/man1/thunderbird.1.gz

**Comment by j-dimension** [comment]
Das ergibt keinen Sinn. Irgendetwas ist an der Installation kaputt.  Was sagt

`flatpak list`

**Comment by librelegal** [comment]
bash: flatpak: Kommando nicht gefunden.

Handelt es sich überhaupt um eine flatpak Installation, es ist 115.3.1 (64-Bit)

**Comment by j-dimension** [comment]
Keine Ahnung. Ohne Fernwartung ist für mich hier das Ende der Fahnenstange erreicht.

**Comment by librelegal** [comment]
Dann Danke
