### ISSUE TITLE
[TASK] Zeiterfassung bitte dokumentieren

### ISSUE THREAD

**Issue by Dickmaulruessler** [jlawyerorg/j-lawyer-org#2058]
Danke für dieses vom Prinzip her sehr tolle Tool!

Ich finde es bedarf aber einer Dokumentation. Ich bekomme es noch nicht hin. 
Ein kleines Video - vor allem zu dem manuellen Nachtragen von Zeiten - wäre auch toll.

**Comment by j-dimension** [comment]
Der Task zur Zeiterfassung steht noch im Status "Documenting", da er noch dokumentiert werden muss: 
https://github.com/jlawyerorg/j-lawyer-org/issues/58

Ich schliesse also hier :-)
