### ISSUE TITLE
[BUG] beA: Text zu 0800-Meldung korrigieren

### ISSUE THREAD

**Issue by Dickmaulruessler** [jlawyerorg/j-lawyer-org#2059]
Lässt sich dieser Fehler unten korrigieren? 
Ich finde gerade dort ist es ein sehr unglücklicher Ort für diesen kleinen Bug.

![jfdklöjdaslköfda](https://github.com/jlawyerorg/j-lawyer-org/assets/46451749/49583847-b45d-4df2-b118-9dee81ebe09c)

**Comment by j-dimension** [comment]
Bitte mal mit der kommenden 2.4 prüfen. Wahrscheinlich Duplikat von #1003 .
