### ISSUE TITLE
[FEATURE] Speichern ob ein Briefkopf bei bestimmten Vorlagen genutzt werden soll oder nicht

### ISSUE THREAD

**Issue by clvnsch** [jlawyerorg/j-lawyer-org#2069]
Bei dem neuen Feature, dass Briefköpfe und der Inhalt getrennt sind [#1552] wird ja bereits gespeichert, welcher Briefkopf zuletzt genutzt wird. 

Jetzt ist es so, dass ich teilweise Vorlagen nutze, wo kein Briefkopf benötigt wird. 
Vielleicht könnte man hier, ähnlich wie bei der optionalen Erstellung der zusätzlichen PDF [#1739], speichern ob eine Vorlage einen Briefkopf erhalten soll oder eben nicht

**Comment by j-dimension** [comment]
related to #1552
