### ISSUE TITLE
[BUG] Installation unverständlich bei Komponentenauswahl

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#2070]
um ganz ehrlich zu sein, ich versteh es nicht.

Zum einen schon mal, warum einmal X und einmal 1 und 2? Warum ist hinter dem X hinten ein [*1]? Und wenn die Vorauswahl [2,3] ist, wird dann der Server installiert? Ich nehme es an, aber ich verstehe es nicht.

Und was soll ich eingeben, wenn ich eine Beschreibung zb vom Backupmanager haben möchte?

![image](https://github.com/jlawyerorg/j-lawyer-org/assets/29924198/c7ccba3f-8481-4e4b-b0a6-7ce00e4ce530)

PS: Kann man auch nachinstallieren? Wenn ja, wäre hier ein Hinweis darauf hilfreich. Im gegenteiligen Fall aber auch.

**Comment by j-dimension** [comment]
X wird immer installiert, der Rest optional. Wenn es ein [*...] dahinter gibt, kann man sich die Beschreibung anzeigen lassen. Vorauswahl 2,3 bedeutet, dass alle optionalen Komponenten (zusätzlich zu den nicht abwählbaren) installiert werden. 

Ich kann in diesem Screen literally *nichts* anpassen, da es vom Installer-Framework (install4j) vorgegeben wird. Ich kann Komponenten definieren und ob sie optional sind, mehr nicht.
