### ISSUE TITLE
[BUG] UI / GUI Fehler bei manchen Akten - Teil des Layouts verschwindet aus dem Hauptfenster

### ISSUE THREAD

**Issue by iradraconis** [jlawyerorg/j-lawyer-org#2071]
Nicht eindeutig reproduzierbar, aber es scheint bei umfangreichen Akten (viele Beteiligte oder viele Dokumente) vermehrt aufzutauchen.

![Bildschirmfoto vom 2023-09-12 15-23-15](https://github.com/jlawyerorg/j-lawyer-org/assets/71747937/83c8f420-8745-455a-b645-10746e692c96)

**Comment by j-dimension** [comment]
Was ist das für eine Auflösung und welcher Skalierungsfaktor wird genutzt?

**Comment by j-dimension** [comment]
https://github.com/jlawyerorg/j-lawyer-org/assets/3729754/5ecface2-d430-4c96-a61d-b03f7578ce47

Viele Beteiligte, viele Dokumente, viele Ordner... ich krieg das nicht nachgestellt... :-(

**Comment by iradraconis** [comment]
Das sind noch nicht viele Dokumente bei dir ;) 
Übrigens: es ging bei uns das erste Mal in einer Akte los, die sowohl viele Beteiligte als auch viele Dokumente hatte. Aber es passiert auch in unserem Beleg-Ordner, und da sind keine Beteiligte. Es könnte also eher an den vielen Dokumenten liegen.

Der Fehler war schon, bevor man den Client skalieren konnte. Damals konnten nur die Schriftgrößen geändert werden. Passiert auf allen Clients hier. Laptops, Desktops, Linux, Mac. 

![Bildschirmfoto vom 2023-09-13 07-47-15](https://github.com/jlawyerorg/j-lawyer-org/assets/71747937/eab286ac-9cda-41f9-81d4-479e78a59a77)

![Bildschirmfoto vom 2023-09-13 07-47-34](https://github.com/jlawyerorg/j-lawyer-org/assets/71747937/8a730172-aacd-4549-9bda-e33e00be6a61)

**Comment by j-dimension** [comment]
@iradraconis es sind da jetzt 458 Dokumente drin - ist das viel? Ich kriege das nicht nach nachgestellt :-(

**Comment by iradraconis** [comment]
Das ist ja frustrierend... ich kann es nicht genauer eingrenzen..

**Comment by j-dimension** [comment]
@iradraconis magst Du nochmal in der Mailingliste nachfragen? In der Facebook-Gruppe gab es keine Rückmeldung, die zu exakt diesem Problem passt.

**Comment by j-dimension** [comment]
Liegt scheinbar an den Beteiligten. Warum ist mir noch nicht klar.

**Comment by iradraconis** [comment]
Teilweise wird der Betreff bei den Beteiligten geleert, oder Beteiligte verschwinden ganz aus der Akte. Wenn der Betreff geleert ist, kann ich die Betreffzeile nicht mehr vollständig nutzen.

**Comment by iradraconis** [comment]
Der Fehler ist behoben!!! Danke Jens!
