### ISSUE TITLE
[FEATURE] Login-Screen: nach Fokus per Tastatur auf Benutzerfeld den Login-Namen komplett markieren

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#2072]
**Is your feature request related to a problem? Please describe. / Welches Problem soll durch die Erweiterung / Verbesserung gelöst werden?**

Wenn ich mich mit einem anderen User einloggen will, dann gehe ich via shift-tab in das User-Feld. (alter Tastatur-Junkie :-)) Dann ist der Cursor dort am Anfang oder Ende des eingetragenen Nutzernamens. Um einen neuen Namen einzutragen muß ich erst den Namen komplett Buchstaben für Buchstaben löschen.

**Describe the solution you'd like / Beschreibe die gewünschte Lösung**
Description / Beschreibung

Wenn nach dem Fokus auf eines der Eingabenfelder (mittels Tastatur) gewechselt wird, wird der dort stehende Eintrag gleich komplett markiert. Dann kann man direkt mit dem neuen Namen lostippen. Will man wirklich nur einen Buchstaben korrigieren oder so, genügt jetzt aber ein Pfeil-rechts oder -links.

**Comment by j-dimension** [comment]
getestet
