### ISSUE TITLE
[FEATURE] Nutzerkürzel als Platzhalter verfügbar machen

### ISSUE THREAD

**Issue by Linkki2021** [jlawyerorg/j-lawyer-org#2078]
Für Nutzerkürzel_Autor und Nutzerkürzel_Aktensachbearbeiter

**Comment by j-dimension** [comment]
neue Platzhalter für Kürzel:

- {{AKTE_SACHBEARBEITER_KRZ}} (Kürzel des verantwortlichen Sachbearbeiters)
- {{AKTE_ANWALT_KRZ}} (Kürzel des verantwortlichen Anwalts)
- {{AUTOR_KRZ}} (Kürzel des Autors des Dokuments / der Nachricht)
