### ISSUE TITLE
Eingabe Stunden und Minuten in Beleg

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-org#2085]
Wenn man einen Beleg manuell anlegt in Finanzen 

und z.B. 10 h 55 min eingibt a´250 €, (10,55) dann rechnet das Programm nicht in 55/60 Minuten sondern in 55/100 was die Minuten angeht und die Abrechnung wird falsch.

**Comment by j-dimension** [comment]
@Mucki526 das müsstest Du bitte einmal erläutern. In einem Beleg können doch gar keine Zeiten eingegeben werden - die Positionen eines Belegs kennen nur Menge, Einzelpreis, Steuersatz.

**Comment by Mucki526** [comment]
Also, wenn ich einen Stundensatz habe und dann die Menge eingebe, dann ist das Regelmäßig 1 h und 45 min und nicht Menge 1,75. Wenn ich dann die Menge ändern will, muss ich zb. 1 h 37 min in Dezimalstellen umrechnen. Wären dann 1,6166... und ich kann ja im Beleg manuell editieren.... oder nicht? (hab da noch kein Gefühl dafür, was vielleicht nicht schlau oder falsch ist...).

**Comment by Mucki526** [comment]
oder anders rum gedacht... wenn ich mit dem Plugin arbeite, fragt es mich, nach Stunden, Minuten und Stundensatz. Im Reiter Finanzen einen Beleg anelegt mit meinem Stundensatz und dann könnte man ja einfach das Plugin umgehen über den Beleg, aber der will nicht Minuten, der will Dezimal nach dem Komma....

**Comment by j-dimension** [comment]
Das gehört aber nicht in eine Rechnung - woher soll die Rechnung wissen, ob Basis 60 oder 100, ob eine Taktung von 1, 2, 5 Minuten etc.? 

Du kannst dann die Zeiten über das Plugin reinbringen, oder Du legst ein Zeiterfassungsprojekt in der Akte an, buchst dort die Zeiten, und rechnest dann ab (im Beleg gibt es einen Import für erfasste Zeiten).

**Comment by Mucki526** [comment]
Verstehe ich. Manchmal, oft, mache ich nur eine Beratung. Haben dann nen Zettel 1 h 40 min. Buche das rein, Kostennote per e-mail. Da wäre es am einfachsten einfach in den Beleg zu buchen und ne Rechnung draus zu machen. Da brauchtes keinen Umweg über Plugin oder Zeiterfassungsprojekt (Mit Kanonen auf Spatzen schießen).. Verstehe aber den Einwand und werden dann wohl grundsätzlich über das Plugin gehen müssen....
