### ISSUE TITLE
[TASK] Client für Linux ARM

### ISSUE THREAD

**Issue by iradraconis** [jlawyerorg/j-lawyer-org#2086]
für das 2.4 Release gibt es noch keinen Installer für ARM Linux

**Comment by j-dimension** [comment]
Findet man hier: https://cloud.j-dimension.com/index.php/s/wscJLx3KDCKoEWm?path=%2F2.4.0%2FExperimentell

Gehört aber nicht zu den offiziell supporteten Installern.
