### ISSUE TITLE
[BUG] Mail - Inhalt und Anlagen werden nicht angezeigt

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#2088]
Ich habe hier eine ganz merkwürdige Mail mit einem ganz merkwürdigen Verhalten von jl:

Mail sieht an sich normal aus, Betreff ohne Umlaute, Anhang mit dem Namen "Anhang 1.pdf".

Ich klicke in der Mailliste auf eine andere Mail, es werden in der Vorschau unten Metadaten, Text und Anhänge angezeigt. Ich klicke nun auf die fragliche Mail:

- Metadaten werden geladen.
- Der Inhalt bleibt der Inhalt der letzten Mail
- Anhänge werden keine mehr angezeigt.

Auch wenn ich die Mail komplett zur Akte speichere (es werden auch korrekt ca 7MB gespeichert), dann kann ich sie zwar mit Doppelklick in neuem Fenster öffnen, aber es werden keine Anhänge angezeigt. 

BTW ein Öffnen der Mail in neuem Fenster mit Doppelklick in der Mailliste geht nicht. Es kommt zwar kurz das popup mit ... 7 MB wird geladen ... aber dann passiert nix weiter.

BTW2: Ich habe noch weitere Mails (anderer Absender) gefunden, die zb mit einem 20 MB-Anhang sich nicht per Doppelklick in der Liste öffnen lassen. Hier wird die Anlage aber sauber angezeigt.

**Comment by j-dimension** [comment]
Hier wären Eml-Dateien notwendig, die das nachvollziehbar machen.

**Comment by stm9x9** [comment]
Der Inhalt der Mail und der Anhang unterliegt leider der anwaltlichen Verschwiegenheit. Ich muß sehen, ob ich den Mandanten überzeugen kann.
