### ISSUE TITLE
Rechnungsnummer  wenn man einen Entwurf weglöscht.[FEATURE]

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-org#2092]
Wenn ich einen Entwurf einer Kostennote mache und den dann direkt wieder weglösche, dann wird nicht die vergebene Rechnungsnummer zurückgesetzt. Dann muss man umständlich in die Einstellungen und den Startpunkt für die Rechnungsnummer neu setzen nach dem Löschen des Entwurfs. Ist natürlich blöd, wenn man einen Entwurf macht und danach drei Rechnungen schreibt, dann gibts da eine Lücke oder es würden sich alle folgenden Rechnungen verschieben.

Wieso muss ein Rechnungsentwurf überhaupt eine Rechnungsnummer haben. Die könnte er bekommen, wenn man die Rechnung von Entwurf auf offen setzt.

**Comment by j-dimension** [comment]
Du machst einen eigenen Nummernkreis für die Entwürfe, dort kannst Du dann Nummern verbrennen wie Du magst. Wird daraus eine echte Rechnung, passt Du den Nummernkreis auf den "echten" an.

**Comment by Mucki526** [comment]
O.K.... Nummernkreis für Entwürfe. Ay Ay Sir... Danke!

**Comment by Mucki526** [comment]
Hilft doch nicht weiter.... wenn ich einen Rechnungsnummernkreis für Entwürfe mache, dann hat der Entwurf eine Rechnungsnummer von diesem Kreis. Wenn ich den Entwurf zur normalen Rechnung machen will, muss ich ihn gerade nochmal als Rechnung schreiben.....  Oder sehe ich das falsch?

**Comment by j-dimension** [comment]
Musst Du nicht. Du drückst auf den Stift hinter der Belegart und kannst den Nummernkreis anpassen.
