### ISSUE TITLE
Belegerstellung - Fehler

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-org#2093]
Wenn ich einen Beleg erstelle als Entwurf und auf speichern Klicke und es dann später wieder aufrufe, sind die Belegdaten nicht mehr da (Rechnungsempfänger). Wenn ich dann den Beleg auf offen stelle und abspeichere, dann habe ich in der Belegübersicht 2 identische Belege, einen als Entwurf und einen als offen, scheinbar mit dem gleichen Inhalt. Wenn ich jetzt den Entwurf weglösche, ist der zweite Beleg nicht mehr aufrufbar und nicht weglöschbar. Und wenn ich dann notgedrungen den Beleg neu anlegen will, dann bekomme ich einen Java Fehler : Fehler beim Speichern der Rechnung Java.ang.NullPointerExeption.

Und dann bekomme ich das nur weg, wenn ich den Belegnummerkreis lösche und neu anlege...

**Describe the bug / Fehlerbeschreibung**
(todo: a description of the bug / eine Beschreibung des Fehlers)

**To Reproduce / Schritte zum Nachvollziehen**

1. Go to / Gehe zu '...'
2. Klicke auf / Click on '....'
4. Error message / Fehlermeldung: '...'

**Expected behavior / Erwartetes Verhalten**
Eine Beschreibung des erwarteten Verhaltens.

**Screenshots**
Falls relevant, Screenshot beifügen.

**Environment / verwendete Umgebung:**
 - OS / Betriebssystem:
 - j-lawyer.org Version:

**Additional context / Sonstiges**

**Comment by Mucki526** [comment]
![grafik](https://github.com/jlawyerorg/j-lawyer-org/assets/37142896/43de263a-a7eb-4e92-8f61-82742e3cdac0)

**Comment by Mucki526** [comment]
![grafik](https://github.com/jlawyerorg/j-lawyer-org/assets/37142896/0ce767f3-51de-45a2-b344-f7675503a0b4)

**Comment by j-dimension** [comment]
Davon brauche ich entweder eine exakte Beschreibung der Bediensequenz oder ein Video. Ich bekomme das nicht reproduziert:


https://github.com/jlawyerorg/j-lawyer-org/assets/3729754/24b88577-f2fb-46d6-b380-ea381cba0c12

**Comment by Mucki526** [comment]
Verstehe ich, ich muss da mal genau meinen Workflow analysieren, welchen Schlenker ich da unbewußt mache.... Was mir dabei gerade aufgefallen ist -, wenn ich den Belegkreis ändere von Entwurf auf Kostennote, dann wird die Änderung beim Speichern (unten button im Beleg) nur übernommen, wenn ich zuvor den Editiermodus des Belegkreises (Stift neben Belegkreis) verlassen habe und wieder alles ausgegraut ist. Wenn ich im aktivierten Belegeditiermodus speichere und rausgehe, werden die Änderungen des Belegkreises nicht übernommen....

**Comment by j-dimension** [comment]
Ja, die Änderung des Nummernkreises muss explizit bestätigt werden, wäre sonst etwas riskant. Hier könnte die Nutzerführung noch verbessert werden.

**Comment by j-dimension** [comment]
Ich schliesse mangels Feedback.
