### ISSUE TITLE
Aktennummern in der Übersicht, nicht nur Rechnungsnummern

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-org#2095]
Bei der Übersicht über die Rechnungen fehlt mir eine Spalte mit der Aktennummer, insbesondere auch aber nicht nur, weil man nicht direkt zur Rechnung in die Akte springen kann....

**Comment by j-dimension** [comment]
Meinst Du die Auswertungen? Dort haben alle drei rechnungsrelevanten Auswertungen diese Akteninformationen.
