### ISSUE TITLE
Backups feingranularer einstellbar machen

### ISSUE THREAD

**Issue by bjk00** [jlawyerorg/j-lawyer-org#210]
Möglichkeit Backups mehrmals am Tag zu starten, z.B. jede Stunde
Option einer Benachrichtigung per Email nur bei fehlgeschlagenem Update

**Comment by j-dimension** [comment]
Hinweis: das "Senden der Mail nur bei Problemen" bedeutet mehr Verantwortung für die Anwender - wenn bspw. der Mailserver / Mailaccount ein Problem hat, bekommt man nicht mit, wenn die Backups fehlschlagen.

**Comment by j-dimension** [comment]
Werde hier erstmal nichts ändern. Die Benachrichtigung ist mittlerweile wie gefordert konfigurierbar, eine höhere Frequenz für die Backups lässt sich skripten (curl - Aufruf ist verfügbar, der ein Backup startet). Eine höhere Frequenz ist von den meisten nicht benötigt, oder gar kontraproduktiv (bspw. dauert die anschließende Synchronisation sehr oft mehr als 1h)
