### ISSUE TITLE
[e-mail] aus Thunderbird in j-lawyer drag ´n drop - problem

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-org#2100]
Ich benutze oft die Drag an drop funktion um e-mails aus Thunderbird in den Dokumentenordner einer Akte zu schieben.

Wenn man aus Versehen aber nicht den Dokumentenordner trifft oder dieser nicht offen ist und die "festgehaltene" e-mail, weil der Dokumentenordner nicht im Fokus ist, auf die Oberfläche des Clients fallen lässt, um den Dokumentenordner zu öffnen, dann stürzt j-lawyer ab (hängt sich auf), dann hilft nur der Dreifinger-Griff. Wenn man das Dokument neben j-lawyer loslässt, passiert nichts. Vorschlag - das Dokument landet auch im Dokumentenordner eine Akte, wenn man über den Reiter Dokumentenordner fährt (oder der öffnet sich) oder es gibt eine Warnmeldung ("Bitte Dokumentenordner vorher öffnen") in jedem Fall kein Absturz des Clients....

**Comment by iradraconis** [comment]
Oder unsere neue Extension installieren zum Speichern von Emails und/oder Anhängen :)

**Comment by Mucki526** [comment]
bin zu blöde... woher? wo?, wie... :-)?

**Comment by iradraconis** [comment]
https://github.com/jlawyerorg/j-lawyer-tbaddon/releases/download/v0.9.7.4/j-Lawyer_Thunderbird_0.9.7.4.xpi

https://github.com/jlawyerorg/j-lawyer-tbaddon/blob/main/README.md

**Comment by Mucki526** [comment]
Das löst das Absturzproblem leider nicht - aber die Idee per se ist super, (Das Tool verbindet sich wohl mit dem Server, findet aber unsere Akten nicht...)

**Comment by Mucki526** [comment]
In der Anleitung steht htts://(IP des Servers) im Beispiel. im Toll mit Port :8080. Beides verbindet sich wohl, aber findet keine Akte, die ich eingebe....

**Comment by iradraconis** [comment]
Serverdaten richtig eingeben, dann in der Oberfläche der Erweiterung 2 x auf den Reload Button klicken, dann sollte sich die Tabelle mit den am Server gespeicherten Etiketten füllen. Und dann sollte die Erweiterung normal arbeiten.

**Comment by iradraconis** [comment]
Die Aktensuche mal auf Namen geprüft ?

**Comment by Mucki526** [comment]
Habe extra eine Akte Test angelegt 01663/2023 Test  und ein paar Etiketten angeklickt. Geht nicht. Der Rahmen mit den Etiketten bleibt gelb (gelb ist schlecht, grün ist vermutlich gut....) und er findet keine Akte. (Grübel....) Der Port 8080 sollte ja offen sein, weil auch der Client auf den Server darüber zugreift, meine ich....

![grafik](https://github.com/jlawyerorg/j-lawyer-org/assets/37142896/621f056e-2602-40b2-90db-e25a01fb33d8)

**Comment by Mucki526** [comment]
Es hat geklappt  - Mühsam nährt sich das Eichhörnchen bei der Suche nach der Nuss im tiefen Laub.... Ich habe versucht, einen einzelnen Buchstaben als Akte einzugeben, auf einmal gings los.... Keine Ahnung wo der "Pups" quergestanden ist.... jetzt geht es ganz normal. Vorher hatte ich versucht manuell den Port 8080 in der Fritzbox freizuschalten, brachte nix und die Freigabe dann wieder gelöscht... danach ging´s wie gerade beschrieben (vielleicht Zufall)...

**Comment by Mucki526** [comment]
Noch anders gesagt, man darf garnicht nach der Aktennumer suchen, außer sieh steht im Namen.. Merke: Haselnuss nicht Walnuss (Eichhörnchen) und (Aktennummer nicht gleich Name (Anwalt).....  Manchmal hat man die Aktennummer als Zahl im Kopf, vor allem wenn der Name Xrhplyclis oder Wryczlwazehl ...  oder so ähnlich ist. , wäre vielleicht eine Erweiterung für Vers. 1.0 - ansonsten genial... :-) Danke!

**Comment by j-dimension** [comment]
Mich würde noch ein Systembericht unmittelbar nach einem solchen Absturz interessieren. Kann man unter "Administration" erzeugen. Danke!

**Comment by j-dimension** [comment]
Ich schließe mangels Feedback.
