### ISSUE TITLE
[FEATURE] in andere Akte kopieren: nicht einzeln umbenennen

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#2109]
wenn ich mehrere Dateien in eine andere Akte kopieren will, dann werde ich aktuell x-mal nach einem neuen Dateinamen gefragt.

Vorschlag: Übernahme des "in Akte importieren"-Dialogs aus dem beA-Massenimport.

**Comment by j-dimension** [comment]
Duplikat von (detaillierterem) #2491
