### ISSUE TITLE
[BUG] Adressen: Bereich Rechnungsbeträge abgeschnitten

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#2110]
Wenn der Screen zu klein ist (hier 1680x1050), dann wird nicht alles bei den Rechnungsbeträgen angezeigt. Scrollbar machen?

![image](https://github.com/jlawyerorg/j-lawyer-org/assets/29924198/5bfc28bd-7d9d-49f6-8b87-ea91c243def7)

**Comment by j-dimension** [comment]
Dup von #2007
