### ISSUE TITLE
[BUG] Adresse: Etikett per beA erreichbar nicht da

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#2115]
diverse Adressen haben das Etikett "per beA erreichbar". Aber ich kann es nicht manuell vergeben, da fehlt es einfach in der Liste!?

![image](https://github.com/jlawyerorg/j-lawyer-org/assets/29924198/1c84f5c5-a05e-4b81-b6fd-c0ae67a8acfd)

trotz:

![image](https://github.com/jlawyerorg/j-lawyer-org/assets/29924198/11c0331e-cf76-487b-9ef8-b12a0e7c31bc)

**Comment by j-dimension** [comment]
Dieses Etikett wird bei Import aus dem beA angebracht. Wenn Du es anderweitig nutzen willst, einfach anlegen.

**Comment by stm9x9** [comment]
und das ist dann "dasselbe" Etikett oder doppelt sich dann was?

**Comment by j-dimension** [comment]
Dann hast Du es überall zur Auswahl.
