### ISSUE TITLE
[TASK] Adressen: beA durch ERV ersetzen

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#2116]
Im Kontakt-Reiter steht unten das Feld "beA (Anwaltspostfach):

![image](https://github.com/jlawyerorg/j-lawyer-org/assets/29924198/e27c3ad2-9781-45d8-95e4-32dcd7666a50)

mittels der SAFE-ID sind ja aber auch Gerichte (also EVGP-Postfächer) und beBPos oder Bürgerpostfächer etc erreichbar.

Ich weiß nur noch nicht, was eine bessere Betitelung wäre.

**Comment by steinwedel** [comment]
Wenn man eine Überschrift sucht, wäre vielleicht "Elektronischer Rechtsverkehr" passend.

**Comment by librelegal** [comment]
Ich würde es so lassen, denn die SAFE-ID ist hier die Grundlage für einen der Kommunikationswege im ERV, aber nicht der ERV selbst.  Die SAFE-ID ist laut BRAK "persönliche Adresse für Ihr beA Postfach", nämlich der  Eintrag im "Bundesweiten Amtliches Anwaltsverzeichnis" (https://portal.beasupport.de/fragen-antworten/kategorie/allgemeine-fragen/was-ist-die-safe-id-und-wo-finde-ich-diese, das letztlich auf https://bravsearch.bea-brak.de/bravsearch/index.brak führt). Hintergrund: "SAFE-Konzept	gibt	vor,	dass	jeder	Identität,	die	in	einem	SAFE-konformen	
Identitätsmanagement	–System	gespeichert	ist,	eine	eineindeutige	ID,	die	sogenannte	SAFEID,	zugeordnet	wird" (https://egvp.justiz.de/Drittprodukte/SAFE_Abbildungsvorschrift_SAFE_ID_V2.pdf)

**Comment by steinwedel** [comment]
Soweit ich verstanden habe, geht es nicht um die Bezeichnung Safe-ID. Diese ist zutreffend. Vielmehr ist die Überschrift "beA (Anwaltspostfach)". Diese Bezeichnung ist zu eng, da nicht nur beA-Nutzer eine Safe-ID haben, sondern beispielsweise auch Gerichte, die statt beA EGVP nutzen.

**Comment by librelegal** [comment]
Ja, das ist wohl richtig. Die "Überschrift" sollte wohl weg und einfach Safe-ID stehen bleiben. Die Safe-ID wird festgelegt von der deutschen "Projektbüro der BLK-AG IT-Standards" (https://justiz.de/laender-bund-europa/elektronische_kommunikation/grob-und-feinkonzept/index.php) und findet Niederschlag in § 11 Abs. 2 RAPV (https://www.gesetze-im-internet.de/ravpv/__11.html). Die bei dem Projektbüro genannte "D.I.M. ( Distributed Identity Management)" gibt es offenbar nicht, das wäre ein großer Fortschritt.

**Comment by j-dimension** [comment]
![grafik](https://github.com/jlawyerorg/j-lawyer-org/assets/3729754/8d0ec8fb-1d87-4284-8181-e715a231ba68)

**Comment by librelegal** [comment]
Schick. Sollte man nicht gleich "beA / EGVP / beBPo / eBO / beN / beSt / MJP" daraus machen? Oft ist noch unklar, ob man dann per KSW-Schnittstelle des beA oder per beA-Weboberfläche damit auch kommunizieren kann, aber die Information kann man dennoch in den Adressen-Bestand aufnehmen. Bei beN geht das meines Wissens jdf. nicht, vgl. #1730 

beN https://egvp.justiz.de/beh_allgemeine_info/index.php 
beSt https://steuerberaterplattform-bstbk.de/ 
MJP https://mein-justizpostfach.bund.de/(Pilotbetrieb seit 12.10.23, https://egvp.justiz.de/buerger_organisationen/index.php)

"beA / EGVP / beBPo / eBO / beN / beSt / MJP"

**Comment by j-dimension** [comment]
@librelegal merci, hab ich so übernommen.

**Comment by stm9x9** [comment]
> Sollte man nicht gleich "beA / EGVP / beBPo / eBO / beN / beSt / MJP" daraus machen?

wäre da nicht "Elektronischer Rechtsverkehr" doch generischer?
