### ISSUE TITLE
[BUG] geänderte Logindaten werden gespeichert ohne Speichern zu klicken

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#2121]
**Describe the bug / Fehlerbeschreibung**
(todo: a description of the bug / eine Beschreibung des Fehlers)

**To Reproduce / Schritte zum Nachvollziehen**

ich habe (mehrere) Login-Profile
ich gehe in Profile und ändere den Server (ich mußte mich testweise auf einen neuen Server einloggen, wollte aber das noch nicht dauerhaft mit einem eigenen Profil machen)
ich drücke NICHT Speichern
ich gehe auf Login, gebe mein Paßwort ein und verbinde
ich schließe den client
ich starte den client neu
das Profil enthält nun den geänderten Server

**Expected behavior / Erwartetes Verhalten**
Eine Beschreibung des erwarteten Verhaltens.

Da ich nicht gespeichert hatte, sollte das Profil in der alten gespeicherten Form mit dem alten Server weiter erhalten sein.

funfact: wenn ich mich nach dem Ändern des Servers nicht einlogge oder das Einloggen nicht geklappt hat, dann wird der veränderte Server nicht gespeichert.

ähnlich: 
ich ändere den Login-Namen und logge mich ein. Bei einem neuen Start von jl ist der neue Name vorgegeben (aber nur, wenn der Login auch geklappt hat).

**Environment / verwendete Umgebung:**
Client: Windows 10

**Comment by j-dimension** [comment]
Feature, kein Bug.

**Comment by stm9x9** [comment]
Huch?

Warum ist dieses, ich nenn es mal automatische Abspeichern ein Feature, wenn es doch gerade dafür den Speicher-Button gibt? Was ist denn der Benefit dahinter?

Wie gesagt, ich fände es ganz nützlich, eine Einstellung auch mal nur temporär ändern zu können, ohne mir Gedanken machen zu müssen, das hinterher wieder korrigieren zu müssen.

**Comment by j-dimension** [comment]
> Wie gesagt, ich fände es ganz nützlich, eine Einstellung auch mal nur temporär ändern zu können, ohne mir Gedanken machen zu müssen, das hinterher wieder korrigieren zu müssen.

Dann einfach zwei Profile anlegen.
