### ISSUE TITLE
[FEATURE] Login-Name optional als Teil des Profiles

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#2122]
Ich würde gerne den Login-Namen auch im Profil hinterlegen können

das scheint mir hilfreich, wenn zb mehrere an einem Rechner arbeiten (Rechner am frontdesk mit wechselnden Refas) oder auch um schnell mittels Maus zwischen meinem Account und dem Admin-Account beim Login zu wechseln, ohne daß man den Login-Namen eingeben muß. Stattdessen alt mit drop-down aus den Profilen auswählbar.

**Comment by j-dimension** [comment]
Der Loginname ist bereits Teil des Profils.

**Comment by stm9x9** [comment]
ah, ok. Dann hängt das wohl mit #2121 zusammen, daß das Eingeben eines anderen Login-Namen das Profil einfach überraschend überschreibt :-/

**Comment by j-dimension** [comment]
Das Profil wird mit dem zuletzt erfolgreich authentifizierten Nutzer gespeichert. Das hält niemanden davon ab, mehrere Profile für unterschiedliche Nutzer zu haben und per Dropdown zu switchen.

Ich schließe hier.
