### ISSUE TITLE
[FEATURE] Stirling PDF Integration per API?

### ISSUE THREAD

**Issue by iradraconis** [jlawyerorg/j-lawyer-org#2128]
Ich möchte auf ein tolles Tool aufmerksam machen. Stirling PDF läuft auf dem Server in einem Docker Container und ist damit leicht einzurichten. Eine Anbindung an jlawyer würde gerade unter dem Gesichtspunkt der digitalen Aktenführung den Werkzeugkasten für PDF Dateien enorm vergrößern und damit den Entwicklungsaufwand für Jens in diesem Bereich minimieren.

Es lassen sich Dokumente komprimieren, bearbeiten, beschneiden, Seitenzahlen einfügen, Wasserzeichen einfügen, Texterkennung einfügen usw. Von Vorteil ist auch, dass mehrere Dateien parallel bearbeitet werden können.

Wenn es zukünftig möglich wäre, Dokumente unmittelbar an den Stirling PDF Server zu schicken, wäre das eine spannende Erweiterung. Falls das jetzt schon gehen sollte, hab ich es nur noch nicht geschafft :-)

Vielleicht lässt sich auch schon ein einfaches Skript einbinden, dass die Weitergabe von Dokumenten übernimmt. 

https://github.com/Frooodle/Stirling-PDF

EDIT: 
Hier die SwaggerUI
https://app.swaggerhub.com/apis-docs/Frooodle/Stirling-PDF/0.14.1

**Comment by stm9x9** [comment]
digitale Aktenstörung? :-D

**Comment by iradraconis** [comment]
Ach ja, ein wichtiges Feature hat Stirling PDF: Es kann Akten automatisch schwärzen.

![grafik](https://github.com/jlawyerorg/j-lawyer-org/assets/71747937/ca7f24a4-4f36-4b34-be46-a134aef3fe0b)

**Comment by librelegal** [comment]
sieht seht gut aus, wäre toll, wenn sich das einbauen ließe

**Comment by librelegal** [comment]
Jedenfalls der lokale Einsatz setzt wohl die Installation von Java 17 voraus (#2099, https://github.com/Frooodle/Stirling-PDF/blob/main/LocalRunGuide.md).

**Comment by librelegal** [comment]
Die Einbindung würde vermutlich auch #74 (PDF automatisch OCR scannen) erledigen.

**Comment by iradraconis** [comment]
Mit dem Aufteilen im ScanEingang und nun auch in der Akte, dem Zusammenführen von PDF Dateien, der OCR Funktionalität im Scaneingang, dem selektiven Entfernen von Seiten aus einer PDF, dem Verkleinern von PDF meine ich, kann das Ticket hier geschlossen werden. Die PDF Features sind ziemlich rund inzwischen. Da das mein Ticket ist, würde ich mal schließen.
