### ISSUE TITLE
[BUG] Änderung der Rechnungsnummer nicht aktuell in Dokumentenliste

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#2129]
**Describe the bug / Fehlerbeschreibung**
(todo: a description of the bug / eine Beschreibung des Fehlers)

**To Reproduce / Schritte zum Nachvollziehen**

Ich erstelle einen neuen Rechnungsbeleg mit noch einer Testrechnungsnummer.
ich erstelle dazu ein Dokument
ich finalisiere den Beleg und erstelle eine endgültige Rechnungsnummer

in der Dokumentenliste steht die alte Testnummer

erst wenn ich die Akte komplett verlasse und neu reingehe, steht die neue Nummer da

**Expected behavior / Erwartetes Verhalten**
Eine Beschreibung des erwarteten Verhaltens.

eine neue Nummer wird sofort in der Liste angezeigt, spätestens nach erneutem Aufruf des Dokumentenreiters

**Screenshots**
Falls relevant, Screenshot beifügen.

![image](https://github.com/jlawyerorg/j-lawyer-org/assets/29924198/fe00d625-3c40-42b7-bb13-1f06886b6bc0)

**Comment by j-dimension** [comment]
Duplikat von #2012
