### ISSUE TITLE
Abbruch des Speicherns einer Email bei zu langem Dokumentennamen

### ISSUE THREAD

**Issue by bjk00** [jlawyerorg/j-lawyer-org#213]
Wird eine Email mit mehreren Anhängen aus der Akte versendet und ist die Option zur Speicherung als Dokument in der Akte aktiv, kann der vorgeschlagene Dateiname zu lang werden. 
Nach der Fehlermeldung bricht der Speichervorgang ab, ohne das ein kürzerer Name für das Dokument angegeben werden kann. Die Email wird nicht in der Akte gespeichert aber trotzdem versendet.
Bei einer Fehlermeldung sollte eine Korrektur des Dokumentennamens möglich sein.

Anmerkung:
Als Dokumentenname wäre die Betreffzeile vielleicht sinnvoller als die Aneinanderkettung aller angehängter Dokumentennamen. Zumal so lange Namen unter "Dokumente" in der Akte auch dazu führen, das Diktatzeichen und Größe nur noch mit horizontalem Scrollen sichtbar sind.

Vorschlag für die automatische Dokumentenbezeichnung bei Emailversand:
Datum_Uhrzeit_Betreff_Anzahl der angehängten Dokumente

oder den Namen des ersten angehängten Dokuments mit einem Hinweis, falls mehrere Dokumente angehängt wurden:
Datum_Uhrzeit_Betreff_NameErsterAnhang_" und weitere Dokumente"

**Comment by j-dimension** [comment]
Ist das tatsächlich mit 1.9.1 aufgetreten? In 1.9.1 gab es hierzu einen Bugfix, der Dokumentname wird automatisch eingekürzt.

**Comment by bjk00** [comment]
Ja, definitiv 1.9.1 und reproduzierbar.
Schritte: 
1. mehrere Dokumente markieren
2. Rechtsklick auf die makierten Dokumente und senden wählen
3. Email schreiben und absenden (mit Option in Akte speichern)
4. Dialog zum Umbenennen des Dateinamens erscheint. Mit ok bestätigen.
5. Fehlermeldung das Dateiname zu lang ist erscheint. Kann nur mit ok bestätigt werden.

Email wird dann schon versendet, wobei die Maske zum Email schreiben weiterhin sichtbar ist. Nochmal senden will ich sie ja nicht, also bleibt mir nur, sie zu schließen ohne das sie gespeichert wird.

**Comment by j-dimension** [comment]
Hab's gefunden - vielen Dank für das Ticket!
