### ISSUE TITLE
Dateinamen in den Ausdruck von Notizen aufnehmen

### ISSUE THREAD

**Issue by Dickmaulruessler** [jlawyerorg/j-lawyer-org#2130]
Es war bisher noch nie mein Wunsch, dies zu tun. Aber heute dann eben doch einmal: Ein paar Notizen auf Papier auszudrucken. 

Dabei wird nur der unten grün gekennzeichnete Bereich gedruckt, nicht jedoch der rote, also nicht der Dateiname (bei mir steht - nur - da der eigentliche kurze Inhalt)

Falls sich der Bug mit wenigen Klicks beheben ließe, wäre das gut, andernfalls wäre das sicherlich nicht wichtig. Aber grundsätzlich finde ich, dass ein physischer Ausdruck schon möglich sein sollte. 

![jfkldöjfaklöds](https://github.com/jlawyerorg/j-lawyer-org/assets/46451749/c51db1e7-0281-4e68-a84e-ea8015b22916)

**Comment by stm9x9** [comment]
da wäre ich eher in die Richtung mit dem Anzeigenamen statt Dateinamen in der Dokumentenliste. Dann kann auch eine Notiz halt "Tel mit Mdt - Beleg angefordert".
