### ISSUE TITLE
Teilzahlungen verbuchen[FEATURE]

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-org#2135]
Eine Teilzahlung auf eine Kostennote verbuchen habe ich jetzt als "negative" Position zur Akte gebucht und als Teilzahlung bezeichnet. Das Datum der Teilzahlung konnte ich aber nur als Notiz ergänzen. Ferner musste ich den Nettobetrag händisch ausrechnen. Es wäre eine Erweiterung sinnvoll, mit der eine Teilzahlung enfach zur Rechnung gebucht wird (brutto / netto als Auswahl mit Datum). 

**NOTE: Please search existing tickets to avoid duplicates **
**HINWEIS: Bitte vorab die Ticketsuche verwenden, um Doppeleinträge zu vermeiden **

**Is your feature request related to a problem? Please describe. / Welches Problem soll durch die Erweiterung / Verbesserung gelöst werden?**
Description / Beschreibung

**Describe the solution you'd like / Beschreibe die gewünschte Lösung**
Description / Beschreibung

**Additional context / Sonstiges **
Sonstige Informationen / Screenshots / ...

**Comment by j-dimension** [comment]
Duplikat von #1955
