### ISSUE TITLE
weitere Funktion im Messenger - individuelle Nachricht

### ISSUE THREAD

**Issue by RobertT01** [jlawyerorg/j-lawyer-org#2147]
Bitte den Nachrichtendienst um die Funktion der persönlichen Nachrichten erweitern
Wenn ich einem bestimmten Nutzer eine Nachricht schicke, sollte die auch NUR von dem Nutzer lesbar sein, sonst schicke ich die Nachricht bei "alle" und schreiben konkret rein für wen die Nachricht ist oder sie ist dann für alle

**Comment by j-dimension** [comment]
Muss noch etwas darüber nachdenken, bspw. was passiert wenn man eine Nachricht mit einer Aufgabe in einer Akte an eine Kollegin sendet, die dann krank wird. Dann hat niemand anderes die Möglichkeit, die Nachricht einzusehen.

**Comment by RobertT01** [comment]
Einfach eine Abwesenheitsfunktion einbauen /afk oder so. Wir müssen ja nicht das Fahrrad nochmal erfinden. Außerdem macht es die Sache selbsterklärend. Hilft das weiter?Von meinem/meiner Galaxy gesendet
-------- Ursprüngliche Nachricht --------Von: Jens Kutschke ***@***.***> Datum: 06.11.23  01:14  (GMT+01:00) An: jlawyerorg/j-lawyer-org ***@***.***> Cc: RA Robert Thees ***@***.***>, Author ***@***.***> Betreff: Re: [jlawyerorg/j-lawyer-org] weitere Funktion im Messenger -
  individuelle Nachricht (Issue #2147) 
Muss noch etwas darüber nachdenken, bspw. was passiert wenn man eine Nachricht mit einer Aufgabe in einer Akte an eine Kollegin sendet, die dann krank wird. Dann hat niemand anderes die Möglichkeit, die Nachricht einzusehen.

**Comment by j-dimension** [comment]
Ich habe jetzt folgende Regeln implementiert:

- wird eine Nachricht mit einem Aktenbezug gesendet, ist sie "öffentlich" - zu Dokumentationszwecken
- ist ein User der Absender, sieht er / sie die Nachricht
- wurde der angemeldete User erwähnt, sieht er / sie die Nachricht
- ist die Nachricht ohne Aktenbezug und es gibt keine Erwähnungen, sieht er / sie die Nachricht

Das bedeutet: Nachrichten ohne Aktenbezug von Person A an Person B können nicht von C eingesehen werden.
