### ISSUE TITLE
Datum von Mahnungen und Zahlungen

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-org#2150]
Ich habe gerade Zahlungseingänge geprüft. Dabei habe ich gemerkt, dass man in Finanzen die Rechnungen auf bezahlt stellen kann - aber nicht das Datum der Zahlung erfassen kann. Das wäre aber wichtig wenn man in ein paar Wochen, Monaten, Jahren nachvollziehen will, wann was bezahlt wurde.  (das gleiche gilt für Mahnungen - Datum der Mahnung und ggf. neues letztes Zahlungsziel)

**NOTE: Please search existing tickets to avoid duplicates **
**HINWEIS: Bitte vorab die Ticketsuche verwenden, um Doppeleinträge zu vermeiden **

**Is your feature request related to a problem? Please describe. / Welches Problem soll durch die Erweiterung / Verbesserung gelöst werden?**
Description / Beschreibung

**Describe the solution you'd like / Beschreibe die gewünschte Lösung**
Description / Beschreibung

**Additional context / Sonstiges **
Sonstige Informationen / Screenshots / ...

**Comment by j-dimension** [comment]
Mit Aktenkonto erledigt.
