### ISSUE TITLE
[BUG] Doppelter Eintrag in Finanzen bei Umstellung von Entwurf auf offen 

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-org#2152]
Wenn man in Finanzen einen Eintrag erzeugt und ein Dokument, steht der bei mir auf Entwurf (obwohl ich mir sicher bin, das auf offen gestellt zu haben). Wenn man dann die Rechnung von Entwurf auf Offen stellt (Rechnungsnummer ist bereits vergeben...), erscheint der Eintrag unter dem Reiter Belege auf einmal zweimal - einmal als Entwurf, einmal als offen. Wenn man dann die Akte verläßt und wieder in die Akte geht, verschwindet der erste (falsche) Eintrag Entwurf.

**Comment by j-dimension** [comment]
Das bekomme ich nicht reproduziert. Die genaue Klicksequenz wird aber aus der Beschreibung auch nicht deutlich, sodass ich wahrscheinlich anders vorgehe. Am besten ein kurzes Bildschirmvideo bereitstellen.

**Comment by j-dimension** [comment]
Gern kommentieren wenn neue Informationen bereitstehen, dann mache ich das Ticket wieder auf.
