### ISSUE TITLE
[BUG] Befehlsmenü zeigt Services unter Linux nicht

### ISSUE THREAD

**Issue by librelegal** [jlawyerorg/j-lawyer-org#2155]
Das Befehlsmenü (Datei, Ansicht, Einstellungen ...) ist in der aktuellen Version sichtbar, bei einem mouse-over werden die dahinterliegenden Befehle angezeigt. Das ist bei "Services" nicht der Fall, auch nicht nach Neustart des Programms. Unter Windows geht es.

Debian Linux 11, KDE 64bit
Server: 2.5.0.4, Client: 2.5.0.0, beA-Integration: 3.16.0.3

![image](https://github.com/jlawyerorg/j-lawyer-org/assets/37673969/6d8be231-f843-4e94-ac96-39f9bcfe4395)

![image](https://github.com/jlawyerorg/j-lawyer-org/assets/37673969/fab7396e-77d3-4c00-95a6-44592a6063fe)

**Comment by j-dimension** [comment]
Die Einträge in diesem Menü werden dynamisch erstellt, dazu ruft der Client eine Datei von j-lawyer.org (der Website) ab. Scheint als dürfte oder kann er das bei diesem Client nicht.
