### ISSUE TITLE
[BUG] Kalender öffnet sich bei mehreren Monitoren u.U. auf anderem Monitor

### ISSUE THREAD

**Issue by librelegal** [jlawyerorg/j-lawyer-org#2158]
Ausgangssituation:
Beim Klick auf den Kalender öffnet sich dieser immer auf Monitor 1, z.B. so: 

![image](https://github.com/jlawyerorg/j-lawyer-org/assets/37673969/063ed9fe-ad0a-4928-8688-efd575dc9c6d)

aber auch bei der Neuanlage einer Adresse:

![image](https://github.com/jlawyerorg/j-lawyer-org/assets/37673969/d4eb187c-3fe6-416c-ba71-b52bf1dc0a82)

Hat der Nutzer mehr als einen Bildschirm / Monitor (hier: 3), kann ein Problem auftreten. Das Programm startet nämlich immer auf Monitor 1 und muss zum Arbeiten auf Monitor 3 verschoben werden. Beim Klick auf den Kalender öffnet sich dieser immer auf Monitor 1 von drei Monitoren, auch wenn j-lawyer gerade auf Monitor 3 geöffnet ist. Danach kann in j-lawyer nicht mehr gearbeitet werden, bis das neu aufgegangene Fenster geschlossen wird. 

**Environment / verwendete Umgebung:**
- Debian Linux 11, KDE 64bit
- Server: 2.5.0.4, Client: 2.5.0.0, beA-Integration: 3.16.0.3

**Comment by j-dimension** [comment]
Dup von #1044
