### ISSUE TITLE
[FEATURE] Wechsel zwischen Akten beschleunigen

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-org#2160]
Ich habe gerade einen Fall, da gibt es wegen 1 Kindes und zweier Eltern über 10 laufende Akten. Diese sind natürlich nach und nach angefallen und haben unterschiedliche Nummern. Das Ordnersystem der Dokumenten reicht da nicht wirklich, das würde viel zu unübersichtlich, wollte man in einer Akte mehrere Prozesse verwalten. Also verschiedene Akten.... Aber es wäre hilfreich, wenn beim Aufruf der Akte zeitgleich eine Liste der anderen Akten erscheinen würde, so dass man zwischen den Akten springen könnte ohne jedesmal zu suchen oder das Aktenzeichen im Kopf haben zu müssen. Also wie ein Merker "verknüpft mit" der Gesetzt wird oder /und  eine Anbindung an den Beteiligten "Mandant".

**Comment by iradraconis** [comment]
Über die Beteiligten kann schon in verknüpfte Akten gesprungen werden, da deren Beteiligungen im letzten Reiter dargestellt werden. Manchmal ist es auch praktisch, 2 Fenster des Clients geöffnet zu haben.

**Comment by Mucki526** [comment]
Ja, aber dazu muss ich - aus dokumenten raus, in die Beteiligten rein, in den konkreten Beteiligten, Rein, dann auf den Button Akten und dann auswählen - Thema workflow, ich arbeite in einem Dokument im Dokumentenordner und brauche das Dokument aus der anderen Akte:  - Dann wäre es hilfreichen den Reiter Akten im Dokumentenordner zu haben mit allen Akten des Mandante (oder auswählbar für welche Beteiligte). Ein zweiter Client ist nett, aber davon bin ich abgekommen, weil man irgendwann mit zwei oder drei clients in der gleichen Akte arbeitet, eine Instanz irgendann übersieht, weil es keine "Du hast unter Deinen Browertabs noch zwei Clients offen- Liste gibt".

**Comment by librelegal** [comment]
Duplicate von https://github.com/jlawyerorg/j-lawyer-org/issues/2161 und https://github.com/jlawyerorg/j-lawyer-org/issues/2162?
