### ISSUE TITLE
[FEATURE] elektronische Rechnung als XML nach Richtlinie 2014/55/EU

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#2165]
Das ist zwar noch Zukunfstmusik, aber damit wir es auf dem Schirm haben:

> Das geplante Wachstumschancengesetz verpflichtet Rechtsanwälte, ab dem 1.1.25 gegenüber inländischen Unternehmern elektronische Rechnungen zu stellen und zu verarbeiten (vgl. Gesetzentwurf vom 30.8.23 unter [iww.de/s8772](https://iww.de/s8772) ). Die elektronische Rechnung soll der europäischen Norm für die elektronische Rechnungsstellung nach Richtlinie 2014/55/EU entsprechen. Diese Norm ist auch die Grundlage des Formats XRechnung, das bereits seit November 2022 gegenüber öffentlichen Auftraggebern verwendet werden muss. Die Richtlinie sieht die Übermittlung der Rechnungsdaten in dem rein maschinenlesbaren Format XML vor. Nicht zulässig sind Rechnungen im Textformat als PDF oder E-Mail

Quelle: https://www.iww.de/rvgprof/praxisfaelle/elektronischer-rechtsverkehr-wachstumschancengesetz-elektronische-rechnung-soll-fuer-rechtsanwaelte-ab-2025-pflicht-werden-f156217

---------------- @j-dimension 2024-08-15 -----------------------

Muss:
- [x] Zugferd Java API integrieren: 0,75h
- [x] Mapping Datenmodelle: j-lawyer Rechnung zu Zugferd-Rechnung: 1,25h
- [x] bei Generieren eines PDFs zu einem Rechnungsdokument: Rechnung als Zugferd-Objektmodell erstellen: 1,25
- [x] bei Generieren eines PDFs zu einem Rechnungsdokument: Zugferd-Objektmodell in XML konvertieren und in PDF einbetten 0,5h https://www.mustangproject.org/invoice-class/
- [x] XRechnung-XML generieren (Rechnungslegung an öffentliche Auftraggeber)
- [x] ~Schalter für "als elektronische Rechnung: ja/nein" - nicht überall wird das benötigt werden - bspw. bei Rechnungslegung ins Ausland - optional (evtl. schadet es nicht, die XML-Daten immer einzubetten)~

Die Daten des Verkäufers sind aktuell entweder fest in der Rechnungsvorlage oder werden bspw. aus dem Kanzleiprofil übernommen. Das ist dann nicht mehr praktikabel - sie müssten entweder vom angemeldeten Nutzer, oder besser über eine Auswahl definiert werden können (bspw. stellt Sekretariat Rechnungen mal für RAin1 oder RA2). Bedingt: 

- [x] Datenmodellerweiterung in Nutzerverwaltung um Kontodaten, Anschrift, Unternehmensname, Steuerinformationen, ... (fast alles, was auch an einer Adresse steht): 1,75h
- [x] zusätzliche Services zum Verändern dieser Daten: 1h
- [x] Oberfläche zum Pflegen der Daten: 2,5h
- [x] bei Belegerstellung den Rechnungssender auswählbar machen: 1,25h
- [ ] Test und Dokumentation: 2h
- [x] Beleg ohne E-Rechnung, wenn nicht umsatzrelevant (bspw. Dokument wird für Angebot o.ä. erstellt)

optional:
- [x] ~Generieren der LibreOffice / MS Office-Rechnung und Erstellen des PDFs können zeitlich auseinanderliegen, und es gab inzwischen evtl. Änderungen an der Rechnung. Evtl. ist der Workflow so anzupassen, dass das PDF immer direkt mit generiert werden MUSS, um die Konsistenz zu wahren: 2,25h~
- [x] ~bei Erhalt einer Rechnung: auf eingebette XML-Daten prüfen, Darstellung mit separatem Icon in der Dokumenteliste der Akte, Import als Beleg ermöglichen: 3,25h~

ohne optionale Punkte: 12,25h
komplett: 17,75h

ungeplant:

- [x] zusätzliche Daten am User per Platzhalter bereitstellen
- [x] zusätzliche Platzhalter für den Sender einer Rechnung (wie User-Platzhalter, nur eben nicht vom angemeldeten User sondern jenem, der als Rechnungsssender angegeben wurde)
- [ ] neue User- und Beleg-Platzhalter dokumentieren, Vorlage aktualisieren
- [x] bei Änderung der Nutzerdaten muss Nutzer im Cache des Clients aktualisiert werden
- [x] Viewer für ZUGFeRD-Rechnungen
- [x] Viewer für XRechnung
- [ ] Import von XML-Rechnungen als Beleg(?)
- [x] REST API erweitern (zusätzliche Attribute am User)
- [x] Rechnungssender in Auswertungen (verschiedene) aufnehmen
- [x] Girocode nicht mehr mit Daten aus Kanzleiprofil, sondern aus den Daten des rechnungslegenden Nutzers
- [x] unterschiedliche Zahlungsarten unterstützen
- [x] Lastschriftmandat - Erweiterung der Adressverwaltung inkl. Platzhalter und REST-API - siehe #1707
- [x] Darstellung Dokumentmetadaten im "Dokumente"-Tab eines Belegs, oder zumindest eine visuelle Bestätigung nach Dokumenterstellung
- [x] #2611

**Comment by j-dimension** [comment]
https://konik.io/docs/index.html

**Comment by j-dimension** [comment]
Muss:
- [ ] Zugferd Java API integrieren
- [ ] Mapping Datenmodelle: j-lawyer Rechnung zu Zugferd-Rechnung
- [ ] bei Generieren eines PDFs zu einem Rechnungsdokument: Rechnung als Zugferd-Objektmodell erstellen
- [ ] bei Generieren eines PDFs zu einem Rechnungsdokument: Zugferd-Objektmodell in XML konvertieren und in PDF einbetten
- [ ] Schalter für "als elektronische Rechnung: ja/nein" - nicht überall wird das benötigt werden - bspw. bei Rechnungslegung ins Ausland
- [ ] Die Daten des Verkäufers sind aktuell entweder fest in der Rechnungsvorlage oder werden bspw. aus dem Kanzleiprofil übernommen. Das ist dann nicht mehr praktikabel - sie müssten entweder vom angemeldeten Nutzer, oder besser über eine Auswahl definiert werden können (bspw. stellt Sekretariat Rechnungen mal für RAin1 oder RA2).
- [ ] Test und Dokumentation

optional:
- [ ] Generieren der LibreOffice / MS Office-Rechnung und Erstellen des PDFs können zeitlich auseinanderliegen, und es gab inzwischen evtl. Änderungen an der Rechnung. Evtl. ist der Workflow so anzupassen, dass das PDF immer direkt mit generiert werden MUSS, um die Konsistenz zu wahren.
- [ ] bei Erhalt einer Rechnung: auf eingebette XML-Daten prüfen, Import als Beleg ermöglichen

**Comment by RobertT01** [comment]
- noch ein paar weitere Info
- https://www.frankfurt-main.ihk.de/recht/uebersicht-alle-rechtsthemen/steuerrecht/umsatzsteuer-national/e-rechnungspflicht-ab-2025-6055774
- e-rechnung ist nicht relevant gegenüber Verbrauchern
- mal sehn was mit der Abrechnung gegenüber der RS wird, man könnte es so machen wie gegenüber der Allianz, Abrechnung an den Mdt adressiert und der RS geschickt
- sollte wir hier ein finanziertes Projekt drausmachen? der Kostenaufwand schein bei der veranschlagten Zeit überschaubar

**Comment by j-dimension** [comment]
https://github.com/ZUGFeRD

**Comment by j-dimension** [comment]
Breaking Change ohne Rückwärtskompatibilität: da sehr viele neue Platzhalter für den angemeldeten Nutzer entstehen, soll ein einheitlicher Präfix gefunden werden. Daher wird es einige Platzhalter geben (bspw. Anwaltskürzel, Autor), die ab 2.7 nicht mehr unterstützt werden.

**--> Doku und Release Notes**

**Comment by j-dimension** [comment]
Nutzerverwaltung mit den Daten, die nun an jedem Nutzer hinterlegt werden können. So sind verschiedene Rechnungssender mit eigenen Bankverbindungen etc. möglich.

![grafik](https://github.com/user-attachments/assets/58ec06f5-8ba7-4e4c-a319-6e81c4533485)

**Comment by stm9x9** [comment]
ist damit abbildbar, daß Rechnungen nicht unbedingt vom jeweiligen Anwalt(snutzer) geschrieben werden, sondern zb von einer Refa (für mehrere Anwälte)? 

Oder andersrum gefragt: kommt es wirklich vor, daß man je Rechnungssender verschiedene Daten hat? Es geht doch alles an die Kanzlei? Allenfalls wenn in einer Bürogemeinschaft eine jl-Instanz verwendet wird, fiele mir als Anwendungsfall ein.

**Comment by j-dimension** [comment]
neue Platzhalter:

```
{{USER_AN}}
{{USER_EMAIL}}
{{USER_KRZ}}
{{USER_VORNAME}}
{{USER_NAME}}
{{USER_UNTERNEHMEN}}
{{USER_FKT}}
{{USER_STRASSE}}
{{USER_ZUSATZ}}
{{USER_PLZ}}
{{USER_ORT}}
{{USER_LAND}}
{{USER_TEL}}
{{USER_FAX}}
{{USER_MOBIL}}
{{USER_WWW}}
{{USER_BANK}}
{{USER_BIC}}
{{USER_IBAN}}
{{USER_STEUERNR}}
{{USER_USTIDNR}}

```

entfernte Platzhalter:

```
{{AUTOR_AN}}
{{AUTOR_KRZ}}
{{AUTOR_EMAIL}}
```

**Comment by j-dimension** [comment]
PDF-Konvertierungen, bei denen das eingehende Dokument auf Link zu einer Rechnung überprüft und ggf. eine elektronische Rechnung in das PDF eingebettet werden muss:

![grafik](https://github.com/user-attachments/assets/60028b46-39f8-4765-9ad1-df854ac96744)
