### ISSUE TITLE
[FEATURE] E-Mail-Posteingang: Aktenzeichen in Betreff / Nachrichteninhalt erkennen

### ISSUE THREAD

**Issue by j-dimension** [jlawyerorg/j-lawyer-org#2167]
eigene Aktenzeichen im Betreff oder Nachrichtentext erkennen, dann diese Akte als allererste zwecks Zuordnung vorschlagen

**Comment by librelegal** [comment]
Bitte Kommentar zur code Änderung überprüfen.

**Comment by j-dimension** [comment]
search & replace - Problem. Wird korrigiert.

**Comment by stm9x9** [comment]
kann der neue Code auch für #1256  Verwendung finden?

**Comment by j-dimension** [comment]
Da die AZ beim beA strukturiert vorliegen, sollte das dort auch anders gehandhabt werden.

**Comment by stm9x9** [comment]
ich meinte auch weniger den "Extraktionsteil" und mehr den Code, der dann die Aktenvorschläge erstellt und sortiert
