### ISSUE TITLE
Fehlermeldung auf allen Rechnern bei Versendungen an ein Gericht

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-org#2171]
![grafik](https://github.com/jlawyerorg/j-lawyer-org/assets/37142896/92d0ba5a-9554-41a1-b1a1-d8b7b0766b73)

Bei Versendung eine BEA an ein Gericht (Hier Amtsgericht Konstanz) kommt nach dem 2.5 Update nur die Fehlermeldung.

Versendungen an einen anderen Anwalt funktionieren aber....

Was tun?

**Comment by j-dimension** [comment]
Hier nicht nachvollziehbar. Kann auch sein, dass der Intermediär des Gerichts schlicht nicht antwortet / zu lange benötigt. 

Bitte bei beA-Sendefehlern **IMMER** zunächst die Störmeldungen prüfen. 

Heute bspw.:

Hinweis: Alle Gerichte einschl. Staatsanwaltschaften, Grundbuchämter sowie am ERV angeschlossenen Behörden in BW
Umfangreiche Wartungsarbeiten am Intermediär -TERMINÄNDERUNG

Betroffenes Land: Baden-Württemberg
Beginn: 27.10.2023 18:00
Voraussichtliches Ende: 30.10.2023 11:00
Status: aktuell

Aufgrund von notwendigen Wartungsarbeiten an der ERV Infrastruktur in Baden-Württemberg ist der Empfang von elektronischen Nachrichten bei allen Gerichten in Baden-Württemberg einschließlich Grundbuch und Staatsanwaltschaften nicht möglich.
Der elektronische Versand an Gerichte, Staatsanwaltschaften, Grundbuchämter und dem ERV angeschlossen Behörden in Baden-Württemberg (z.B. Landratsämter, Gemeinden und Städte, Jobcenter etc.) ist im genannten Zeitraum nicht möglich.

In eilbedürftigen Angelegenheiten wählen Sie während der Dauer der Wartungsarbeiten bitte andere Kommunikationskanäle.

**Comment by j-dimension** [comment]
In welchem Bundesland befindet sich das Gericht?

**Comment by Mucki526** [comment]
Baden-Württemberg - dann ist das wohl das Problem. Ich gestehe, ich habe noch nie von dieser Webseite gehört, bis ich danach aufgrund Deines Hinweises gesucht habe. Gibts ne Möglichkeit solche Störungsmeldungen direkt im BEA einzublenden oder oder das eine unmögliche Idee?
