### ISSUE TITLE
[BUG] Messaging Tool: Schließen-Button ohne Funktion?

### ISSUE THREAD

**Issue by LazyGuy21No** [jlawyerorg/j-lawyer-org#2172]
Messaging Tool: Schließen-Button ohne Funktion?
<img width="856" alt="image" src="https://github.com/jlawyerorg/j-lawyer-org/assets/56734761/6bd9126b-40b1-4f6d-a2d5-7d408a284873">

**Comment by LazyGuy21No** [comment]
Habe verstanden, dass es zu den Hashtags gehört. Verwirrend, wenn es keine Hashtags gibt!

**Comment by j-dimension** [comment]
Tooltip hinzugefügt.
