### ISSUE TITLE
[FEATURE] Signatur unter Antwort aber oberhalb der zitierten Nachricht bei Antwort auf Mail

### ISSUE THREAD

**Issue by iradraconis** [jlawyerorg/j-lawyer-org#2173]
zumindest als Option wäre das schön

**Comment by hackvokat** [comment]
Unbedingt! Das ist aktuell das einzige, was uns davon abhält auch E-Mails in j-lawyer zu beantworten.

Derzeit schicken wir über j-lawyer E-Mails nur aus der Akte, beantworten aber über andere E-Mail-Clients.

**Comment by steboe1** [comment]
Sehe ich genauso, ist für mich auch aktuell noch der Grund nicht den ganzen Mailverkehr über jl laufen zu lassen.

**Comment by iradraconis** [comment]
@j-dimension  Wie würdest du das beurteilen? Wäre es sinnvoll, dass insgesamt, also nicht nur optional, zu ändern? Option wäre ggfs. vermeidbarer Mehraufwand.

**Comment by iradraconis** [comment]
Ich habe dafür ein PR gemacht. Ich muss sagen, dass es im Test schon eine Wohltat ist, die Signatur oberhalb des Zitats zu sehen, :) kein manuelles Copy-and-paste mehr nötig. Das Verfassen einer Antwort wird deutlich übersichtlicher.
