### ISSUE TITLE
Rechnungsfehler 15Abs3 RVG  Deckelung[BUG] 

### ISSUE THREAD

**Issue by SaschaKarcher01** [jlawyerorg/j-lawyer-org#2182]
**Describe the bug / Fehlerbeschreibung**
(todo: a description of the bug / eine Beschreibung des Fehlers)

Bei Rechnungserstellung wird bei Deckelung die Deckelung addiert statt subtrahiert
**To Reproduce / Schritte zum Nachvollziehen**

1. Go to / Gehe zu '...'
2. Klicke auf / Click on '....'
4. Error message / Fehlermeldung: '...'

**Expected behavior / Erwartetes Verhalten**
Eine Beschreibung des erwarteten Verhaltens.

**Screenshots**
Falls relevant, Screenshot beifügen.

**Environment / verwendete Umgebung:**
 - OS / Betriebssystem:
 - j-lawyer.org Version:

**Additional context / Sonstiges**

**Comment by j-dimension** [comment]
Ein toller Fund, vielen Dank für's Melden! Ich habe das soeben für Versionen

- 2.4.0.2
- 2.5.0.0

behoben. Ein Neustart des Clients sollte ausreichen. 

@SaschaKarcher01 kannst Du das eben kurz prüfen? Vielen Dank!

**Comment by SaschaKarcher01** [comment]
Vorzeichen passt jetzt, danke dir, schönen Abend
