### ISSUE TITLE
[BUG] [beA] Posteingang abspeichern - Etiketten / Speicherort vergeben geht nicht

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#2188]
Vielleicht verstehe ich das Procedere auch falsch, aber wenn ich oben das Etikett A-01 angewählt habe und dann rechts auf den Doppelpfeil nach unten klicke, sollte es dann nicht für alle (hier vom Typ beA) übernommen werden? Es passiert aber nichts.

![image](https://github.com/jlawyerorg/j-lawyer-org/assets/29924198/c584d45d-67fb-428d-bf1a-1297c0d350e4)

Einen anderen Speicherort übertragen geht auch nicht.

**Comment by j-dimension** [comment]
Die "für alle" Buttons sind ausgegraut, also inaktiv, weil es nur ein Dokument gibt.

**Comment by Dickmaulruessler** [comment]
Duplikat 
https://github.com/jlawyerorg/j-lawyer-org/issues/1976#issuecomment-1608079886
