### ISSUE TITLE
[FEATURE] [adresssen] UI  "Versicherungsunternehmen" als Link zur Person (statt als Textfeld)  

### ISSUE THREAD

**Issue by LazyGuy21No** [jlawyerorg/j-lawyer-org#2193]
… so braucht man nicht die Namen ändern, wenn der Versicherer seinen ändert. Außerdem ließe sich dadurch die manuelle Aktenanlage verbessern: 

Für die Person "Jona Mustermensch" sind Versichererdaten (Pfefferminzia VVaG) hinterlegt. Soll der Versicherer auch hinzugefügt werden?

( ) ja, mit Rolle "RSV"
( ) ja, mit Rolle "Haftpflichtversicherer"
(*) nein, nicht automatisch hinzufügen

**Comment by j-dimension** [comment]
Duplikat von #120
