### ISSUE TITLE
[BUG] [adressen] UI Grunddaten: Felder einheitlich ausrichten

### ISSUE THREAD

**Issue by LazyGuy21No** [jlawyerorg/j-lawyer-org#2194]
<img width="569" alt="image" src="https://github.com/jlawyerorg/j-lawyer-org/assets/56734761/1a018192-b19a-44af-885a-e00134a65da2">

**Comment by iradraconis** [comment]
![Eingefügtes Bild](https://github.com/user-attachments/assets/29951adc-9569-4a20-afc2-6fdd3629af3f)
