### ISSUE TITLE
[BUG] [adressen] UI Kontakt: Felder einheitlich ausrichten

### ISSUE THREAD

**Issue by LazyGuy21No** [jlawyerorg/j-lawyer-org#2196]
<img width="574" alt="image" src="https://github.com/jlawyerorg/j-lawyer-org/assets/56734761/48915875-4778-4cf1-9a0a-73f5eaa52d24">

**Comment by j-dimension** [comment]
Das würde nur gehen, wenn die Gruppierungen aufgelöst werden. Es gibt keine identische Ausrichtung, die über Gruppen hinweg angewandt werden kann.

**Comment by j-dimension** [comment]
Ich finde hier keine Möglichkeit, die ohne die Auflösung der Gruppen umsetzbar wäre.
