### ISSUE TITLE
Fehler mit neuem Softwarezertifikat

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-org#2209]
Mein neues Softwarezertifikat lässt sich installieren und verbindet sich auch mit dem Postfach. Aber die Anschreiben lassen sich mit j-lawyer nicht lesen. Über den Browser funktioniert alles ganz normal, mit dem alten Softwarezertifikat funktioniert alles ganz normal (auch im J-Lawyer). 
![grafik](https://github.com/jlawyerorg/j-lawyer-org/assets/37142896/e969583d-12fd-4ea6-8a2c-c79519bab5db)

**Comment by j-dimension** [comment]
Ist das neue Zertifikat (1) im Postfach importiert und (2) dort freigeschalten (ist eine separate Aktion)?

**Comment by Mucki526** [comment]
Es wird vermutlich an der Freischaltung liegen. Ich probiers, sobald die Störung beim Intermediär BW seit 11.45 Uhr beseitigt ist, bzw. ich es schaffe auf die BEA-Karte zuzugreifen. Es macht, selbst wenn man IT mag nicht wirklich Spaß.... Ich poste hier, wenn ich es geschafft habe (oder eben nicht)....
