### ISSUE TITLE
Softwarezertifikat kann keine Umlaute 

### ISSUE THREAD

**Issue by Thorsten-Nutzer** [jlawyerorg/j-lawyer-org#2212]
Hallo,

auf Anstoß der Bundesnotarkammer habe ich mein altes Softwarezertifikat für den beA-Zugang gegen ein neues getauscht. Das war alles sehr frikelig, aber so ist das beim beA. Das  Zertifikat funktioniert bei der Anmeldung im Browser einwandfrei.

Wenn ich das neue Zertifikat im j-Lawyer hinterlege, gibt es aber Probleme. Das Passwort des Zertifikats enthält ein "ü". Das ist offensichtlich kein ASCII Zeichen. Deshalb kommt immer die Fehlermeldung, daß das Zertifikat deshalb nicht glesen werden kann.

Jetzt habe ich schon die Empfehlung genutzt aus Posting #4049 (Stefan Bührer) im Forum, mit Firefox das Passwort des Zertifikats abzuändern - auf "ue" statt "ü". Damit kann dann tatsächlich j-lawyer das Zertifikat lesen.

Aber: Beim Versuch auf das beA zuzugreifen kommt jetzt die Fehlermeldung "...NullPointerException...", also wie hier bei den Tickets unter #2209. Die Meldung kommt jetzt aber auch bei meinem alten Zertifikat.

Im beA kann ich mein neues Zertifikat nicht freischalten, weil es wohl schon freigeschaltet ist (ein Tauschzertifikat). Die Option zum Freischalten wird daher nicht mehr angezeigt. Und über die Browseranmeldung funktioniert es ja auch.

Also, am Besten könnte j-Lawyer die Passwörter genauso lesen, wie das beA und nicht nur eine Teilmenge davon. Es wäre sicher sinnvoll, das mal zu richten.

Liebe Grüße,
Carsten

**Comment by j-dimension** [comment]
#2209 war eine fehlende Freischaltung. 

Ggf. mal einen Systemreport für die NullpointerException bereitstellen.

Das alte Zertifikat sollte weiter wie gewohnt funktionieren - hier scheint mir grundsätzlich etwas nicht zu stimmen.

**Comment by j-dimension** [comment]
Ich würde dann hier mal schließen. Umlaute würde ich in den PINs grundsätzlich vermeiden. Und es gibt ja den Ausweg mittels Firefox.

**Comment by Dickmaulruessler** [comment]
Ich habe es nicht alles verstanden, vor allem nicht, wie groß die Wahrscheinlichkeit für Probleme ist. 
Und in die Firefox-Lösung müsste ich mich im Fall der Fälle jetzt auch noch erst einmal einlesen. 
Ich kann schon verstehen, dass man da Stress bekommt, wenn das beA nicht läuft (und eine Frist an jenem Tag möglicherweise endet). 

Wäre das möglicherweise etwas, was von dir Jens wegen grundsätzlicher Bedeutung auf der Mailingliste kurz erläutert werden sollte?

**Comment by j-dimension** [comment]
Der Firefox-Workaround ist bereits seit Längerem in der Doku erwähnt. Und da jede(r) Postfachinhaber(in) eine Karte besitzen muss, sehe ich hier keine Gefahr.

**Comment by Thorsten-Nutzer** [comment]
Hallo,
ja, stimmt alles. Habe eben noch einmal die Anleitung zu j-Lawyer gelesen. Mein Problem war allerdings nicht, daß die Clientsecurity das Passwort nicht lesen konnte - viele Kollegen kommen ja mit der Karte und dem Webzugang zurecht - sondern daß j-Lawyer das Problem mit den Umlauten hatte. Außerdem will man ja mit j-lawyer gerade nicht mit dem Cardreader usw. rumhandtieren müssen.

Deswegen wäre ein kurzer Hinweis in der Anleitung hilfreich, daß bei der Erstellung eines neuen Zertifikates bzw. dem Zertifikatstausch - wie er jetzt aktuell vielfach ansteht - darauf geachtet wird, nur simple ASCII-Zeichen zu nutzen, keine deutschen Sonderzeichen. 

Eigentlich finde ich es immer besonders schlau, deutsche Sonderzeichen zu nutzen, weil die von der internationalen Hackerklientel schwieriger nachzuvollziehen sind. Aber das gilt wohl auch für die "normale" Software. Die Idee ist also nur mäßig schlau.

**Comment by stm9x9** [comment]
> Außerdem will man ja mit j-lawyer gerade nicht mit dem Cardreader usw. rumhandtieren müssen.

geht das denn überhaupt?

**Comment by j-dimension** [comment]
Falls jemand motiviert ist: Die Doku findet man hier: 

https://github.com/jlawyerorg/j-lawyer-documentation/blob/master/src/j-lawyer.org-UserGuide-de.fodt

Dort gibt es einen Download-Button. Die FODT-Datei lässt sich mit LibreOffice bearbeiten. Dann gern mich zurück, wenn man sich den Workflow in GitHub sparen möchte.
