### ISSUE TITLE
Reporte (Spalten) sortierbar machen

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-org#2216]
Während die Auswertung offene Rechnungen alle Rechnungen nach einem Refresh auflistet, ist dies bei der Auswertung alle Rechnungen nicht der Fall, selbst wenn man als Endtag einen Tag in der Zukunft nimmt. Sie erscheinen einfach nicht.

**NOTE: Please search existing tickets to avoid duplicates **
**HINWEIS: Bitte vorab die Ticketsuche verwenden, um Doppeleinträge zu vermeiden **

**Describe the bug / Fehlerbeschreibung**
(todo: a description of the bug / eine Beschreibung des Fehlers)

**To Reproduce / Schritte zum Nachvollziehen**

1. Go to / Gehe zu '...'
2. Klicke auf / Click on '....'
4. Error message / Fehlermeldung: '...'

**Expected behavior / Erwartetes Verhalten**
Eine Beschreibung des erwarteten Verhaltens.

**Screenshots**
Falls relevant, Screenshot beifügen.

**Environment / verwendete Umgebung:**
 - OS / Betriebssystem:
 - j-lawyer.org Version:

**Additional context / Sonstiges**

**Comment by j-dimension** [comment]
Nicht nachvollziehbar - bitte Screenshot oder Video bereitstellen.
