### ISSUE TITLE
Aktenarchivierung soll auf offene Belege und Zeiterfassungsprojekte prüfen

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-org#2220]
Solange eine Kostennote in irgendeiner Form offen ist, sollte es nicht möglich sein, die Akte zu archivieren oder zumindest ein Warnhinweis kommen, wie bei offenen Wiedervorlagen.

**NOTE: Please search existing tickets to avoid duplicates **
**HINWEIS: Bitte vorab die Ticketsuche verwenden, um Doppeleinträge zu vermeiden **

**Is your feature request related to a problem? Please describe. / Welches Problem soll durch die Erweiterung / Verbesserung gelöst werden?**
Description / Beschreibung

**Describe the solution you'd like / Beschreibe die gewünschte Lösung**
Description / Beschreibung

**Additional context / Sonstiges **
Sonstige Informationen / Screenshots / ...

**Comment by j-dimension** [comment]
![grafik](https://github.com/jlawyerorg/j-lawyer-org/assets/3729754/4ee778cf-56f6-4456-aa20-9324a7639f70)
