### ISSUE TITLE
Volltext-Suche gibt Fehlermeldung "Fehler bei der Suche: Search Index is not initialized: null"

### ISSUE THREAD

**Issue by MarcoWolny** [jlawyerorg/j-lawyer-org#2228]
Bei Ausführen der Volltextsuche erscheint o.g. Fehler

Der Fehler ist reproduzierbar.

**Screenshots**
Fehlermeldung beigefügt

**Environment / verwendete Umgebung:**
 - OS / Betriebssystem: MacOS Sonoma 14.1.2 (23B92)
 - j-lawyer.org Version: current

![Bildschirmfoto 2023-12-12 um 13 09 26](https://github.com/jlawyerorg/j-lawyer-org/assets/74820386/0d2bca2f-e711-4a1e-a20f-9582adc9c563)

**Comment by j-dimension** [comment]
Einmal in Einstellungen - Dokumente - Dokumentensuche und dort den Index neu erfassen lassen. 

VG!

**Comment by j-dimension** [comment]
Das kann eine Weile in Anspruch nehmen, am besten über Nacht laufen lassen.

**Comment by Dickmaulruessler** [comment]
> Einmal in Einstellungen - Dokumente - Dokumentensuche und dort den Index neu erfassen lassen.
> 
Nur aus Neugierde hatte ich mich dort einmal hingeklickt. 

Ich hatte eine kleine zweistellige Differenz an indexierten und nicht-indexierten Dokumenten. 

Ist das möglicherweise etwas, was standardmäßig mit niedriger Priorität (einmal monatlich?) im Hintergrund laufen sollte? Oder ein Hinweis **direkt** in der Volltextsuche auf die Differenz und **dort** eine sofortige Aktualisierungsmöglichkeit? 
Es ist schon unglücklich, wenn man sucht, nichts findet, tatsächlich aber doch etwas da ist...

**Comment by MarcoWolny** [comment]
Sorry dass ich noch einmal nerve, aber das funzt nicht.

Rufe ich die Einstellungen/Dokumente/Dokumentensuche auf, erscheint der "Fehler Ermitteln der Dokumentenabzahl: java.lang.NullPointerException“, den ich mit OK bestätigen kann. Dann erscheint das Fenster Dokumente insgesamt 0, Dokumente im Suchindex 0, „Suchindex neu erfassen“

Klicke ich dann da drauf, erscheint eine Meldung: „Erfassung läuft auf dem Server im Hintergrund, Dialog wird geschlossen“.

Das habe ich jetzt mehrmals über Nacht probiert, immer mit dem Ergebnis, dass ich wieder bei Aufruf der Dokumentensuche den o.g. Fehler bekomme - ich drehe mich also im Kreis…
 
Mit freundlichem Gruß 


MARCO WOLNY
Rechtsanwalt 
Fachanwalt für Strafrecht
______________________________
W O L N Y
RECHTSANWÄLTE
PARTMBB*
______________________________
Bärenallee 12 | 22041 Hamburg-Wandsbek 
T: 040 . 650 333 28 | F: 040 . 650 333 29 
www.wolny-rechtsanwaelte.de
* AG Hamburg - PR 1328
______________________________
