### ISSUE TITLE
[FEATURE] Teilzahlungen erfassen

### ISSUE THREAD

**Issue by iradraconis** [jlawyerorg/j-lawyer-org#2233]
Bitte unbedingt die Möglichkeit hinzufügen, Teilzahlungen zu erfassen. Ich meine, dass Jens irgendwann mal gemeint hat, das würde dann mit dem Akten onto kommen. Vielleicht gibt es ja aktuell eine einfache Lösung, die in der Zwischenzeit weiterhilft.

Oftmals verbleibt bei uns ein offener Restbetrag, oder aber es werden Ratenzahlungen vorgenommen. Aktuell lässt sich dies mit den Optionen für offen, bezahlt, nicht vollstreckbar, etc. nicht darstellen. wenn also von einer 1000 € Rechnung 800 € gezahlt werden, kann nirgends vermerkt werden, dass noch 200 € fehlen. Außer natürlich, es wird eine gesonderte Notiz irgendwo in der Akte gefertigt. Das macht es aber extrem unübersichtlich, weil die Zahlungen dann an unterschiedlichen Orten "gebucht" werden. Der Mehraufwand ist nicht zu unterschätzen. Und wenn dann beispielsweise 900 von 1000 € gezahlt wurden und der Beleg auf bezahlt gesetzt wird, geht der Sachbearbeiter davon aus, dass 1000 € gezahlt wurden. Auch an der Adresse werden ja Zahlungen gespeichert. Dort steht dann zwangsläufig ein falscher Betrag.

**Comment by j-dimension** [comment]
Duplikat von #1955
