### ISSUE TITLE
[TASK] Vorauswahl Kalender

### ISSUE THREAD

**Issue by j-dimension** [jlawyerorg/j-lawyer-org#2238]
Ist: zuletzt genutzer Kalender wird vorselektiert

Soll:
Akte "merkt sich", in welchen Kalender *innerhalb dieser Akte* zuletzt eingetragen wurde, und dieser Kalender wird automatisch vorselektiert, sofern der Nutzer / die Nutzerin Zugriff auf diesen Kalender hat

**Comment by hackvokat** [comment]
Den Sinn dahinter verstehe ich nicht. Bei uns entsteht dadruch regelmäßig Durcheinander. Wir arbeiten teilweise zu dritt an Akten (Sekretariat + 2 Anwälte). Wenn ich bei dem Kalendereintrag unten den Benutzer auswähle, für den der Eintrag ist. Welchen Anwendungsfall gibt es, dass der Eintrag für diesen Benutzer im Kalender eines anderen Nutzers erscheint?

Bei den Kalendern kann man ja für jeden Nutzer einen WV-Kalender, einen Termin-Kalender und einen Fristen-Kalender anlegen. D.h. diese Kalender sind nutzergebunden. Da wäre es für mich nur logisch, dass jeder Benutzer mit seinen Kalendern verknüpft ist.

Wenn sich die Akte nun merkt, dass die letzte Kalendernutzung für das Sekretariat war, weil dort etwas erledigt werden soll und das Sekretariat danach einen Termin für mich als Anwalt eintragen will, dann wäre demnach der Kalender des Sekretariats vorausgewählt, obwohl der Termin für meinen Nutzer bestimmt ist.

Also nochmal in kurz: Warum sollte Kalender und Nutzer überhaupt auseinanderfallen?

**Comment by j-dimension** [comment]
> Wenn ich bei dem Kalendereintrag unten den Benutzer auswähle, für den der Eintrag ist. Welchen Anwendungsfall gibt es, dass der Eintrag für diesen Benutzer im Kalender eines anderen Nutzers erscheint?

Diese Zuordnung ist schlicht nicht eindeutig, und nicht immer sinnvoll. Der ausgewählte Nutzer kann mehrere Kalender haben - bspw. einen Terminkalender für private Dinge, einen für die eigenen beruflichen Termine, und einen für allgemeine Kanzleiorganisation. Es gibt keine 1:1-Zuordnung eines Nutzers zu einem Kalender.

> Da wäre es für mich nur logisch, dass jeder Benutzer mit seinen Kalendern verknüpft ist.

Wie erwähnt, diese Eindeutigkeit gibt es nicht.

> Also nochmal in kurz: Warum sollte Kalender und Nutzer überhaupt auseinanderfallen?

Weil nicht eindeutig.



Die Arbeitsweisen sind hier schlicht sehr vielschichtig - das sieht man ja selbst hier bei der Diskussion:
- A wünscht sich, dass die Kalender anhand der Verantwortlichkeiten (nicht des Termins, sondern der Akte! - erster Tab) voreingestellt werden
- B wünscht sich, dass der für den Kalendereintrag Verantwortliche maßgeblich ist
- C wünscht sich, dass der zuletzt für die Akte genutzte verwendet wird

Es gibt hier keine goldene Lösung, weil es bspw. abhängig davon ist, ob Sekretariat für verschiedene Anwälte einträgt (das geht dann mit diesem Ticket besser), ob innerhalb der Akte mehrere Personen zusammenarbeiten, und wie feinteilig die eigenen Kalender aufgesetzt sind.
