### ISSUE TITLE
Platzierung des Hinweises keine Kostennote / Offene Kostennote bzw. Grafikkreis Kosten [FEATURE]

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-org#2240]
Ich würde vorschlagen, die Hinweise zu offenen Kostennote, keine Kostennoten, Grafik Kostenrechnung der der Akte beim Einstieg (auch) anzuzeigen. Oft ruft ein Mandant an und man steigt dann ja in den Akte ein und sieht dann sinnvollerweise, dass eine Kostennote überfällig ist und man das ggf. thematisieren muss

**Comment by j-dimension** [comment]
Duplikat von #1990
