### ISSUE TITLE
[FEATURE] automatischen Focus auf Buttons in Dialogfenstern

### ISSUE THREAD

**Issue by iradraconis** [jlawyerorg/j-lawyer-org#2242]
Es wäre schön wenn in Dialogfenstern wie diesen der Fokus automatisch auf "ok" oder "unverändert speichern" liegen würde, so dass mit einem Tastendruck auf Enter das Fenster geschlossen werden kann. Das vereinfacht das Handling.

![Bildschirmfoto 2023-12-20 um 13 53 49](https://github.com/jlawyerorg/j-lawyer-org/assets/71747937/f26189d0-97c6-4646-a1d2-837742549dbd)
![Bildschirmfoto 2023-12-20 um 13 53 27](https://github.com/jlawyerorg/j-lawyer-org/assets/71747937/eb10e054-e5b0-4042-8cad-5127c353ca3e)

**Comment by j-dimension** [comment]
erfolgreich getestet
