### ISSUE TITLE
[FEATURE] Vorauswahl Dokumentbenennung

### ISSUE THREAD

**Issue by Linkki2021** [jlawyerorg/j-lawyer-org#2246]
Wir haben unsere Dokumentbenennung stark standardisiert. In unterschiedlichen Akten gibt es immer wieder immer wieder gleich benannte Dokumente.

Uns würde helfen, wenn man eine Vorauswahl treffen könnte, zB dort wo das X ist. Von der Logik her ähnlich wie anzuwählende Etiketten, Ordner oder Wiedervorlagegründe. Bei uns vor allem in den Drebis-Dialogen beim Eingang analog dem beigefügten Bild und Versand (abschließend, wenn man das Dokument in die Akte übernimmt).

Natürlich müsste man das als Liste irgendwo pflegen können.
![image](https://github.com/jlawyerorg/j-lawyer-org/assets/77149788/21c9cce2-ed4c-4120-b21d-f1212d6002c2)

**Comment by j-dimension** [comment]
@Linkki2021 würden für diese Dokumente dann auch die Präfixe (Datum) Anwendung finden, oder wäre bei Auswahl eines vordefinierten Dokumentnamens dann kein Präfix gewünscht?

**Comment by Dickmaulruessler** [comment]
Die Idee finde ich vom Prinzip auch sehr gut und praktisch, da man dann evtl. ganz ohne Tastatur arbeiten könnte. 
Zu Bedenken geben möchte ich, dass es aber auch übersichtlich (max 5 Auswahlmöglichkeiten) bleiben sollte und man dafür möglicherweise einen ganzen Hierarchiebaum zur Auswahl benötigen würde - oder dies jedenfalls später gewünscht werden würde. 
Die Dokumentenbenennung ist schon jetzt recht komplex. 
Das Datum davor finde ich stets wichtig.

**Comment by Linkki2021** [comment]
@j-dimension Eine gute Frage, das hatte ich bei Erstellung gar nicht auf dem Schirm. Habe mal in der Praxis geprüft, wie wir heute benamen. Tatsächlich gemischt...

Mir würde eine flexible Lösung vorschweben, wo das Schema anpassbar ist - sofern darstellbar. Quasi eine Art Mischung aus den Logiken Aktenzeichen-Schema, Etiketten, Dokumenterstellung aus Vorlage. So würde es glaube ich auch für viele nutzbar.

Also z.B., kursiv=flexibel, normal=feststehend
Schema 1: Schreiben des Gegners__Platzhalter Datum Heute_
Schema 2: Mail von__Rolle Beteiligter_
Schema 3: Reparaturrechnung__Platzhalter Kennzeichen aus Verkehrsunfalldaten_

@Dickmaulruessler Zur Vielzahl der Auswahlmöglichkeiten: das sollte analog Etiketten oder WVL-Gründe jeder selbst bestimmen können.

Wo die Möglichkeit noch schön wäre: im Umbenennen-Dialog in Dokumente, z.B. wenn man etwas per Drag-and-Drop reingezogen hat.

**Comment by j-dimension** [comment]
Einstellungsdialog für Dateinamens(bildungs)vorschriften:

![image](https://github.com/user-attachments/assets/dc50367b-38f6-4c67-9a67-fe5e0bad1b72)

![image](https://github.com/user-attachments/assets/0b1bbfba-04e3-413c-a2c2-df0308561ed8)

**Comment by j-dimension** [comment]
https://github.com/user-attachments/assets/7a9b5b25-33f8-4c78-bbe1-61146502981c

**Comment by j-dimension** [comment]
Beteiligtenplatzhalter werden hier erstmal nicht unterstützt, das würde nur funktionieren wenn der Zuordnen-Dialog auch eine Auswahl für die Beteiligten hätte (es kann ja mehrere Mandanten geben).
