### ISSUE TITLE
Filter fehlende Wiedervorlagen - einzelne Anwälte bzw. Akten ohne Anwälte auswählen / ausblenden

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-org#2247]
Es wäre schön, wenn man bei der Auflistung von Akten einzelne Anwälte einblenden bzw. andere Bereiche damit ausblenden könnte (z.B. Akten ohne Anwälte (z.B. bei uns Buchhaltung, allg.) bzw. nur die eigenen Wiedervorlagen auflisten könnte und danach noch nach Nummern sortieren.... Erleichert die Überwachung der eigenen Fehlbarkeit bei der WV-Vergabe.

**Comment by j-dimension** [comment]
Mir ist nicht ganz klar um was es hier geht. Der Titel meint "fehlende Wiedervorlagen" - das wäre die separate Ansicht unter "Kalender" - "fehlende"?

**Comment by j-dimension** [comment]
Schließe mangels Feedback.
