### ISSUE TITLE
[BUG] Berechnungsfehler bei Belegerstellung und Nutzung des Plugins

### ISSUE THREAD

**Issue by iradraconis** [jlawyerorg/j-lawyer-org#2248]
Es scheint hier einen Fehler im Berechnungsplugin zu geben bzw. in der Belegerstellung. Einmal ist die Tabelle mit dem "alten" Plugin eingefügt und einmal mit dem Belegerstellungstool. 

![Bildschirm­foto 2023-12-22 um 16 13 18](https://github.com/jlawyerorg/j-lawyer-org/assets/71747937/cfada275-5fec-4e05-a2d2-99b97a7ca550)

**Comment by j-dimension** [comment]
@iradraconis links ist über Zwischenablage übernommen, rechts über den Beleg?

**Comment by j-dimension** [comment]
Sollte via https://github.com/jlawyerorg/j-lawyer-calculations/commit/ccbf4e7f4f84220e31d59b4f2f3da8657da1e6eb gelöst sein.
