### ISSUE TITLE
Konfigurierbare Rechnungsnummernkreise

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-org#225]
Über eine automatische aufsteigende Rechnungsnummer (wie Aktennummer als Variable im Vordruck nutzbar) wurde m.E. irgendwann nachgedacht. Diese sollte benutzerabhängig steuerbar sein, wenn jeder Anwalt eigene Rechnungsnummern vergibt.

----------------------------------- @j-dimension 2023-01-11

- [x] Admin-Dialog
- [x] mehrere Nummernkreise
- [x] Schemadefinition analog zu AZ / Rechnungsnummernplugin
- [x] Attribut: Kleinunternehmerregelung
- [x] Attribut: manuell anpassbar bei Rechnungserstellung
- [x] Nutzerverwaltung: Berechtigungen für Rechnungsnummernkreise

**Comment by j-dimension** [comment]
Ähnlich Aktenzeichenschemata - mit Platzhalter für neue Rechnungsnr.

Duplikat: #279

**Comment by librelegal** [comment]
Einzelne Akten werden meist von einem Bearbeiter bearbeitet. Das Plugin Rechnungsnummern sollte die Aktennummer anbieten und darin hochzählen können. Man darf solche Nummernkreise bilden (https://de.wikipedia.org/wiki/Nummernkreis, es gibt auch ein BMF-Schreiben dazu)

**Comment by j-dimension** [comment]
Ich werde in einem ersten Schritt erstmal die Funktionalität des bestehenden Rechnungsnummernplugins in die feste Codebasis übernehmen und über Platzhalter zur Verfügung stellen, sodass bei Erstellung einer Rechnung eine neue Rechnungsnummer automatisch generiert und ins Dokument übernommen werden kann.

**Comment by Dickmaulruessler** [comment]
> 
> 
> Ich werde in einem ersten Schritt erstmal die Funktionalität des bestehenden Rechnungsnummernplugins in die feste Codebasis übernehmen und über Platzhalter zur Verfügung stellen, sodass bei Erstellung einer Rechnung eine neue Rechnungsnummer automatisch generiert und ins Dokument übernommen werden kann.

ja, das wäre eine schöne Sache!

Ich weiß nicht wie aufwändig dein Vorschlag ist. Falls es dieser nicht mehr in die 1.14 schaffen sollte, vielleicht sind diese Überlegungen noch von Interesse: 

Ich nutze den Rechnungsnummern-Generator nicht, sondern führe meine Rechnungsnummern parallel auf dem Papier. Einfach weil ich irgendwo eine Liste über die vergebenen Rechnungsnummern und der dazugehörigen Akte haben möchte. Ich finde diese nachträgliche Rekonstruierbarkeit der Rechnungsnummern unverzichtbar. Zum einen für mich und für das Finanzamt. 

Also: Falls man im Rechnungsnummern-Genererator neben der Rechnungsnummer ein Feld für das (notfalls manuelle) Eintragen des Aktenzeichens hätte, wäre da schon sehr viel gewonnen. 

Die von dir oben vorgeschlagene Lösung wäre aber natürlich sehr viel besser.

**Comment by Mucki526** [comment]
Ist eine wünschenswerte Sache, es sollte aber jeder Benutzer die Möglichkeit haben, eine eigene Rechnungsnummernliste ohne Lücke zu führen. Meine Frau und ich führen jeder eigene Rechnungsnummernliste in Excell. Zulässig ist die Einführung eines Identifikators (Siehe BMF-Schreiben oben). Dann kommt hinter die Rechnungsnummer z.b. das Kürzel des Anwalts der angemeldet ist.

**Comment by LazyGuy21No** [comment]
Bitte auch ermöglichen: **Rechnungsnummer mit zufälligen Buchstaben/Zahlen** (wie Aktenzeichen) und Rechnungsnummern mit Platzhaltern für Quartal (römisch I bis IV) mit der Option: neu beginnen nach Quartal/Jahr. 

Das Gesetz sagt nicht, dass die Nummern fortlaufend sein müssen. Sie müssen nur eindeutig sein.

**Comment by librelegal** [comment]
Die Rechnungsnummern müssen fortlaufend sein, es können aber (wie in 
Österreich) Nummernkreise gebildet werden, je Mandant, je Akte, je Akte 
des Mandanten etc.

Es gibt ein BFH-Schreiben aus ca. 2012 dazu ...

Frohe Grüße
Mike

Am 08.05.22 um 06:35 schrieb LazyGuy21No:

**Comment by LazyGuy21No** [comment]
Es stimmt, dass es dazu ein Schreiben gibt, aber es kann - das stimmt auch - jederzeit ein separierter Nummernkreis gebildet werden, solange es nicht der Eindeutigkeit entgegen steht "I 0703-M – 003896 – 22" ist ein zulässige Rechnungsnummer; ABCDEF1 bis ABCDEF4 auch.

Schwarz/Widmann/Radeisen, UStG § 14:

Rz. 96
Es ist zulässig, eine oder mehrere Zahlen- oder Buchstabenreihen zu verwenden; dabei ist auch eine Kombination von Ziffern und Buchstaben erlaubt, wie es z. B. der Verwaltung bei der Umsatzsteuer-Identifikationsnummer gem. § 27a UStG vorgeschrieben ist. Die Zahlen können römisch oder arabisch sein; die Buchstaben brauchen nicht dem lateinischen Alphabet zu entstammen. Aus der Formulierung "fortlaufend" kann nicht geschlossen werden, dass die Rechnungen mit aufeinander folgenden Zahlen zu nummerieren sind, also 1, 2, 3, 4 usw. Vielmehr können auch nur gerade oder ungerade Zahlen oder z. B. Primzahlen oder Zehner- oder Hunderterzahlen verwendet werden. Entscheidend ist die Einmaligkeit der Rechnungsnummer. S. Abschn. 14.5 Abs. 10 UStAE.

 
Rz. 97
Der Unternehmer kann lt. Abschn. 14.5 Abs. 11 UStAE beliebig viele separate Nummernkreise schaffen, in denen die Rechnungsnummern jeweils aber nur einmal vergeben werden dürfen. Die Nummern können sich z. B. auf zeitlich, räumlich oder organisatorisch abgrenzbare Bereiche beziehen, also z. B. nach Tagen, Wochen, Monaten, Jahren, Kunden, Filialen, Betriebsstätten, Organgesellschaften, Vermietungsobjekten u. Ä. aufgeteilt werden.

**Comment by LazyGuy21No** [comment]
Ich möchte noch kurz ergänzen:
Die letzten beiden von mir bei der Zentrale Zahlstelle Justiz gekauften eKostenmarken hatten die Rechnungsnummern
- RNRJC5M0F573GB1 
- RNRKQ1GGB063202
"Fortlaufend" sind die ja eher nicht

**Comment by j-dimension** [comment]
![grafik](https://user-images.githubusercontent.com/3729754/211940823-3892d1b0-f5be-41cf-b25e-89a6a36ba6bd.png)

**Comment by j-dimension** [comment]
![grafik](https://user-images.githubusercontent.com/3729754/211940921-4eed46a1-70dc-431d-bb86-6897cf87e919.png)

**Comment by j-dimension** [comment]
https://user-images.githubusercontent.com/3729754/212190756-a87ff0b4-253c-4854-b249-67b5e8ddaae2.mp4

**Comment by j-dimension** [comment]
Doku: manuelles Rücksetzen des Startwertes, aktuellen Wertes bei Geschäftsjahreswechsel)
