### ISSUE TITLE
[TASK] Terminologie RVG-Plugins: "Streitwert" --> "Gegenstandswert"

### ISSUE THREAD

**Issue by j-dimension** [jlawyerorg/j-lawyer-org#2251]
Der korrektere Begriff wäre „Gegenstandswert“ anstatt „Streitwert“, da man erst innerhalb des gerichtlichen Prozesses von Streitwert spricht.

**Comment by Maz111111** [comment]
Hier bitte auch die Möglichkeit geben, "Verfahrenswert" verwenden zu können.
Im Familienrecht ist dies die korrekte Bezeichnung.
Danke

**Comment by j-dimension** [comment]
> Hier bitte auch die Möglichkeit geben, "Verfahrenswert" verwenden zu können. Im Familienrecht ist dies die korrekte Bezeichnung. Danke

Dafür bitte ein separates Ticket erstellen. Einen festen Wert durch einen anderen festen Wert zu ersetzen kostet 5min Aufwand, eine Konfigurierbarkeit >1,5h, muss separat priorisiert werden.

**Comment by Maz111111** [comment]
So wichtig ist es nicht - scheine ja der einzige mit dem Bedarf zu sein.

**Comment by j-dimension** [comment]
@EmiliaKolev wäre dann im Plugin "RVG Wertgebühren" der "Streitwert" durch "Gegenstandswert" zu ersetzen im 
- oberen Bereich (Basisdaten)
- Vorverfahren

nicht aber in 
- 1. Instanz
- 2. Instanz
?

Vielen Dank!

**Comment by Maz111111** [comment]
Es gibt - soweit ich das überschaue - drei Bergrifflichkeiten.

Das GerichtsKostenGesetz spricht vom Streitwert (§ 34 GKG). Das FamGKG spricht vom Verfahrenswert (§ 28 FamGKG). Das RVG spricht vom Gegenstandswert (§ 13 RVG).

Das Gericht setzt also den Streitwert oder - in Familienverfahren - den Verfahrenswert fest.

Der Anwalt rechnet aber nach dem RVG ab. 

Dabei entgelten die Gebühren, soweit dieses Gesetz (RVG) nichts anderes bestimmt, die gesamte Tätigkeit des Rechtsanwalts vom Auftrag bis zur Erledigung der Angelegenheit (§ 15 Abs. 1 RVG).

Da bzw. wenn der RA nach RVG abrechnet - was bei Nutzung des Plugins "RVG Wertgebühren" der Fall ist - dürfte die Terminologie des RVG jedenfalls nicht verkehrt und wohl die bessere Wahl sein.

Unabhängig von (vor-) prozessualem Stadium und Instanz dürfte man daher mit dem Begriff "Gegenstandswert" auf der sicheren Seite sein, womit sich dann auch mein Wunsch nach Editierbarkeit vollständig erledigt hat.
