### ISSUE TITLE
[FEATURE] Quelle eines Scans hinzufügen

### ISSUE THREAD

**Issue by Linkki2021** [jlawyerorg/j-lawyer-org#2253]
Je nach Organisation des Arbeitsablaufs wären zur Übersichtlichkeit ein bis zwei Ergänzungen in der Scan-Ansicht sinnvoll:

1) Eine weitere Spalte "Quelle" neben geändert/Dateiname. Dort könnte dann zB stehen Server oder der Name des Nutzers aus dessen lokalen Eingangsordner das Dokument kam.
2) Eine Checkbox "Nur meine anzeigen" analog z.B. den Wiedervorlagen auf dem Desktop

**Comment by LazyGuy21No** [comment]
nice!

**Comment by j-dimension** [comment]
- geht das Dokument direkt am Server ein, wird als Quelle "zentraler Scanordner" angegeben
- wird es von einem Client hochgeladen, stehen dort Nutzer(in) und Name des Gerätes, welches den Scan bereitgestellt hat

Ich hoffe, dass niemand im HomeOffice mit Geräten arbeitet, die "Darknet Host" o.ä. heißen - das könnte für Belustigung sorgen. 

Den Filter "nur meine anzeigen" habe vorerst weggelassen - man kommt mit der Sortierung nach Nutzer(in) wahrscheinlich schon recht weit.

![grafik](https://github.com/jlawyerorg/j-lawyer-org/assets/3729754/b3b52ed5-82e9-4041-baea-363ccd84e292)
