### ISSUE TITLE
[BUG] Fenstergröße und -position merken

### ISSUE THREAD

**Issue by Maz111111** [jlawyerorg/j-lawyer-org#2257]
Ich muss auf allen meinen (windows) Rechnern nach jedem Start des Client das Fenster von Hand maximieren.

JL merkt sich das jedoch nicht und beim nächsten Start muss man erneut maximieren.

Es wäre gut, wenn sich die Software die Fenstergröße und -position beim Schließen merkt und beim nächsten Start automatisch wieder herstellt.

**Comment by j-dimension** [comment]
Duplikat von #1480. Es gibt keine plattformübergreifende Lösung, die ID o.ä. des Bildschirms zu erkennen. Das wäre aber notwendig, um dieses Feature umzusetzen. Ansonsten kommen Situationen zustande, wenn man zwischen verschiedenen Monitoren wechselt, in denen das Fenster im nicht sichtbaren Bereich dargestellt wird.

**Comment by j-dimension** [comment]
Workaround: Fenstergröße ändern statt maximieren - die Größe sollte wiederhergestellt werden.
