### ISSUE TITLE
[BUG] Belegtabelle im Dokument weist USt aus (nicht im Gesamt, aber als Information), auch wenn Rechnung ohne USt erstellt wird

### ISSUE THREAD

**Issue by Maz111111** [jlawyerorg/j-lawyer-org#2263]
Ich habe eine Belegposition "Erstberatung" erstellt. 

Einzelpreis 190,00 EUR
Menge: 1,0
Steuersatz: 19,00

Bei der Übernahme im Rahemn der Belegerstellung wird nur der Nettobetrag übernommen. Obwohl ein Steuersatz angegeben wurde, erscheint auf der rechten Seite lediglich die Position Beratungsgebühr (lt. meiner Bezeichnung und Beschreibung) - Menge: 1,00 - Einzelpreis: 190,00

In der untersten Zeile erscheint bei USt 0,00

Wenn man das Dokument mit {{BEL_TABELLE}} erstellt, gibt es zwar die Zeile USt, die als Wert auch die korrekten 36,10 EUR in der rechten Spalte auswirft. 

Allerdings wird als Zahlbetrag 190,00 EUR ausgewiesen - also die Zurechnung der USt unterlassen.

Habe ich hier falsche Erwartungen? Muss ich noch irgendwas machen?

**Comment by j-dimension** [comment]
Die Rechnung selbst hat noch eine Einstellung, ob USt ausgewiesen werden soll. Ist die aktiviert?

**Comment by Maz111111** [comment]
Alles klar, das war der Fehler. 

Aber wie soll der Anwender darauf kommen? Und wie soll meine Mitarbeiterin sich das merken.

Die Logik dahinter erschließt sich mir nicht. Ich gebe in der Vorlage einen USt-Satz an und muss dann händisch für eine von mir selbst als umsatzsteuerpflichtig erstellte Position doch nochmal entscheiden, dass USt ausgewiesen und berechnet werden soll.

Gleichwohl - das Ergebnis in der Tabelle ist auch unerwartet. Es wird eine Zeile USt ausgegeben und ein Wert ausgewiesen aber der Nettobetrag als Gesamtbetrag.

**Comment by j-dimension** [comment]
Bei jeder Neuanlage eines Belegs ist diese Option voreingestellt aktiviert. Es muss ein manuelles Deaktivieren stattgefunden haben.

Du kannst in den Positionsvorlagen einen sinnhaftigen USt-Satz angeben. Wenn Du dann eine Rechnung erstellst, wo Du dem Rechnungsempfänger keine USt berechnen möchtest, dann kannst Du den Haken rausnehmen. 

Die Alternative wäre gewesen, jede Positionsvorlage doppelt vorhalten zu müssen - einmal mit Steuer und einmal ohne.

**Comment by j-dimension** [comment]
> Gleichwohl - das Ergebnis in der Tabelle ist auch unerwartet. Es wird eine Zeile USt ausgegeben und ein Wert ausgewiesen aber der Nettobetrag als Gesamtbetrag.

Das ist nicht sinnvoll und ich werde es über dieses Ticket korrigieren.

**Comment by Maz111111** [comment]
> Bei jeder Neuanlage eines Belegs ist diese Option voreingestellt aktiviert. 

Nein, ist es nicht. Es hat noch andere Abhängigkeiten, die der Nutzer alle wissen muss  -> siehe unten

> Es muss ein manuelles Deaktivieren stattgefunden haben.

Hat es nicht. 

Ich habe den von Dir vorgegebenen Testnummernkreis genutzt, da ich eigentlich nur eine neu erstellte Dokumentenvorlage (Abrechnung Erstberatung) testen wollte. Das mit der USt kann man beim Nummernkreis auch noch mal festlegen. Beim Testnummernkreis ist es ausgeschaltet. Das weiß der Anwender nicht.

Man kann und muss also an drei Stellen entscheiden, ob die USt ausgewiesen und berechnet werden soll.

Jetzt, wo ich es weiß...kann ich das natürlich beherrschen.

Aber die Frage wirst Du noch öfter bekommen. Und ich weiß auch nicht, ob drei Mal wirklich nötig sind, zumal man es im allerletzten, finalen Schritt im Zweifel ja doch wieder ausschalten kann.

Konstruktiv:
Ich habe eine Belegvorlage erstellt, der ich standardmäßig eine Umsatzsteuer zuordnen wollte. Diese habe ich dann mit einem Nummernkreis genutzt, dem standardmäßig keine USt zugewiesen ist. Die KSW weißt mich auf diesen Konflikt nicht hin und entscheidet eigenständig, dass die Vorgabe im Nummernkreis priorität hat.

Vielleicht wäre es eine Lösung, wenn die KSW einen Hinweis auf den Widerspruch gibt. 

Es dürfte in der Regel ein Anwendungsfehler oder eine Ausnahme sein, wenn man einen Belegnummernkreis erstellt, für den man grundsätzlich keine USt will und diesen dann aber mit einer Vorlage verwendet, für die man grundsätzlich die USt eingestellt hat.

Wie gesagt, wenn man es weiß, ist das selbstverständlich beherrschbar.

**Comment by j-dimension** [comment]
Habe gerade gemerkt dass die Option in der Rechnung nicht neu gesetzt wird, wenn man von einem Nummernkreis ohne USt zu einem mit USt-Ausweis wechselt. Das werde ich anpassen. 

Grundsätzlich sollte - wie auch bei Rechnungseingang - bei Rechnungserstellung nicht blind vorgegangen, sondern auf Sinnhaftigkeit kontrolliert werden.

**Comment by Maz111111** [comment]
> Grundsätzlich sollte - wie auch bei Rechnungseingang - bei Rechnungserstellung nicht blind vorgegangen, sondern auf Sinnhaftigkeit kontrolliert werden.

Das ist anmaßend.

Ich habe kontrolliert, sonst hätte ich die Ungereimtheit gar nicht bemerkt und es wäre nie zu dem Ticket gekommen.

**Comment by j-dimension** [comment]
Boah... ich verstehe die schlechten Vibes hier überhaupt nicht. Das war gar nicht auf Deinen konkreten Fall bezogen, sondern auf die Aussage "Aber die Frage wirst Du noch öfter bekommen.", die impliziert dass das ein grundsätzliches und großes Problem ist. 

Du hast ein Ticket gemeldet, ich habe Anpassungen in Aussicht gestellt, versuche zu verstehen und zu hinterfragen. Warum Du das in den falschen Hals bekommst, verstehe ich nicht. Macht keinen Spaß.

**Comment by Maz111111** [comment]
Na das kriegen wir jetzt vermutlich nicht mehr gelöst.

Aus meiner Reaktion solltest Du schon merken, dass Deine Formulierungen bei mir nahe legten, dass ich . obwohl ich es hätte besser wissen können - die SW falsch bedient habe, ohne mein Vorgehen auf Sinnhaftigkeit zu überprüfen.

Das löst bei mir schlechte Vibes aus und macht auch mir keinen Spaß.

Ich habe aber verstanden, dass das nicht so von Dir gemeint war.
 
Also nichts für Ungut. Es tut der Sache ja keinen Abbruch, dass ich Dein Programm total gut finde und nutze und dementsprechend auch dankbar dafür bin, dass Du das alles in Deiner Freizeit machst. 

Mein Anliegen ist nur, die SW zu verbessern, wenn ich Ecken und Kanten in der Nutzung bemerke.

in diesem Sinne - alles gut von meiner Seite
