### ISSUE TITLE
[FEATURE] Abbrechen bei Belegerstellung bricht nicht wirklich ab

### ISSUE THREAD

**Issue by Maz111111** [jlawyerorg/j-lawyer-org#2264]
Vielleicht ist das auch ein Bug...

Wenn ich einen Beleg erstmalig erstelle und ohne diesen zu Speichern (aber nachdem ich auf den Haken bei "Typ und Nummernkreis bearbeiten" geklkickt habe) auf Abbrechen klicke, wird der Beleg trotzdem erstellt und die Belegnummer verbraucht.

Abbrechen sollte den Vorgang auch abbrechen und solange nicht vorher gespeichert war keinen Beleg erstellen und keine Belegnummer verbrauchen.

Zumindest für mich war das unerwartet, dass der Vorgang faktisch trotz des Klicks auf Abbrechen beendet wurde.

(als Hinweis - ich habe vor Submit jetzt nochmal schnell gestestet, ob das Problem tatsächlich, so wie oben dargestellt, auftritt,  und vergessen den Belegnummernkreis auf Test zu stellen. Nun ist eine Nummer aus meinem Standardnummernkreis weg und ich kann nichts machen. Das Problem mit dem Beleglöschen und den vebrauchten Nummern ist m.E. akut)

**Comment by j-dimension** [comment]
Sobald eine Rechnungsnummer generiert wurde, muss zwingend gespeichert werden. Erstellen zwei Nutzer quasi-parallel Rechnungen, kann es sonst zu Nummernkollisionen kommen. Beim Abbrechen werden geänderte Kopfdaten oder Positionen nicht gespeichert.

**Comment by j-dimension** [comment]
> Nun ist eine Nummer aus meinem Standardnummernkreis weg und ich kann nichts machen.

Du kannst den Zähler zurücksetzen und den Start auf den gewünschten Wert setzen.
Oder nichts machen und die Rechnung auf storniert setzen.
