### ISSUE TITLE
Platzhalter und Dokumentation der Platzhalter

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-org#227]
Es ist es ja jetzt möglich, Aktenbezogene Zeichen zu vergeben "Dritter_Akte_Zeichen" etc.

Aber mir erschließt es sich auch nach lesen der Dokumentation und einigen Versuchen nicht, welches Kürzel
nun für welches Zeichen unter Details welches Kürzel steht und welches Kürzel für das Zeichen direkt neben dem Beteiligten....

**Comment by j-dimension** [comment]
Die Dokumentation (https://www.j-lawyer.org/downloads/documentation/j-lawyer.org-UserGuide-de.html#__RefHeading__273_1146603382) meint:
```
{{MANDANT_AKTE_KONTAKT}}	Ansprechpartner des Mandanten innerhalb einer Akte
 {{MANDANT_AKTE_ZEICHEN}}	AZ1/Referenz des Mandanten innerhalb einer Akte
 {{MANDANT_AKTE_EIGENE1}}	Eigenes Feld 1 des Mandanten innerhalb einer Akte
{{MANDANT_AKTE_EIGENE2}}	Eigenes Feld 2 des Mandanten innerhalb einer Akte
{{MANDANT_AKTE_EIGENE3}}	Eigenes Feld 3 des Mandanten innerhalb einer Akte
```
Gleiches für GEGNER_ und DRITTE_

Beantwortet das die Frage?

**Comment by Mucki526** [comment]
Nicht wirklich :-(
Ich habe seit der aktenbezogenen Erweiterung unter jedem Beteiligten das Feld Details
Neben dem Beteiligtennamen steht: "Zeichen"
Unter Details steht: "Az:"
darunter steht: "Ihr Zeichen:" 
wie spreche ich die drei im Einzelnen konkret an???
Das bekomme ich nicht unter die von Dir genannte Liste in der Doku.....

**Comment by j-dimension** [comment]
Dann hast Du die Felder unter "Details" bereits umbenannt. Schau mal in den Einstellungen. 

Im "Normalzustand" stehen dort Zeichen (rechts neben Beteiligtem), Ansprechpartner, Eigene 1, Eigene 2, Eigene 3. Da ist der Zusammenhang mit den Platzhaltern klar. 

Du kannst die Felder in der Oberfläche umbenennen, damit die Nutzer genau wissen welche Eingabe dort erwartet wird. Die Namen der Platzhalter ändern sich dadurch nicht - das muss demjenigen klar sein, der die Vorlagen bearbeitet / erstellt.

**Comment by Mucki526** [comment]
Der Groschen ist mit lautem Scheppern gerade gefallen - ich habe die eigene Leitung auf der ich stand verlassen.... DER Bezug hat mir gefehlt. Alles klar und - genial, dann kann ich die Platzhalter unter Details so benennen, wie ich das gerne möchte :-). Danke für Deine Geduld...

**Comment by Mucki526** [comment]
so benenne wie ich möchte..., soll heißen wie sie in der Maske angezeigt werden. In der Vorlage muss aber weiter als Platzhalter "Eigene 1" etc. stehen...
