### ISSUE TITLE
[FEATURE] Suchfunktion in den Auswertungen

### ISSUE THREAD

**Issue by Maz111111** [jlawyerorg/j-lawyer-org#2270]
Es kommt sehr oft vor, dass nicht der Mandant selbst, sondern irgendein Verwandter oder die Lebensgefährtin zahlt. Bei Zahlungen der Staatskasse erfolgen i.d.R. keinerlei Angaben außer dem gerichtlichen AZ.

Mandanten vergessen ebenso regelmäßig AZ oder RE Nr anzugeben. Oder sie verwechseln beides und geben dann auch noch nur ein Kriterium an (z.B. die Rechnungsnummer mit dre Zahl des AZ). Das geschieht fast immer, wenn nicht der Mandant selbst zahlt.

Oftmals hat man dann nur den Betrag als Suchkriterium. 

Ohne Suchfunktion lässt sich die Zahlung nur aufwendig zuordnen.

**Comment by j-dimension** [comment]
Man kann die Tabellen in der Tabellenkalkulation öffnen und dort suchen.

**Comment by Maz111111** [comment]
> Man kann die Tabellen in der Tabellenkalkulation öffnen und dort suchen.

Vielen Dank.

Ich habe das direkt mal versucht. 
Bei der Tabelle, die bei mir erstellt wird, stehen die Kommastellen des Rechnungsbetrages in der Spalte "Waehrung" und der ganze Rest verschiebt sich dann um eine Spalte nach rechts, so das EUR in er Spalte "erstellt" steht usw.

Wenn ich vor Erstellen der Tabelle doppelt in das Feld "Rechnungsbetrag" klicke und dann irgendwo anders in der Zeile klicke, wird der Betrag (inkl. Kommastellen) danach linksbündig in dem Feld dargestellt und die Tabelle wird hinsichtlich dieser Zeile ordnungsgemäß ohne den beschriebenen Fehler erstellt.

**Comment by j-dimension** [comment]
Wenn Du LibreOffice nutzt, sollte direkt bei Export ein Importdialog aufgehen. Dort bitte als Trennzeichen ausschließlich Tabulator angeben, keine weiteren Zeichen wie Komma oder Semikolon. Im selben Dialog gibt es unten eine Vorschau.
