### ISSUE TITLE
[FEATURE] Auswertung für Teilzahlungen

### ISSUE THREAD

**Issue by Maz111111** [jlawyerorg/j-lawyer-org#2271]
Oftmals bitten Mandanten (auch noch nach Erhalt der Rechnung) um Einräumung einer Ratenzahlung oder zahlen eigenmächtig nur Raten oder (auch nur versehentlich) Teilbeträge.

Im Belegdialog gibt es nur "offen" und "bezahlt".

Hier sollte es auch die Möglichkeit "bezahlt in Höhe von" geben, wobei dann der gezahlte (Teil-) Bruttobetrag eingegeben werden sollte.

Dies müsste dann auch in der Auswertung der offenen Rechnungen sichtbar gemacht werden.

Z.B mit den Spalten:
"Rechnungsbetrag" "Zahlungseingang" "noch offen"

Aktuell sehe ich da kein anderes workaraound, als parallel eine eigene Rechnungsübersicht zu unterhalten, in der man dann Teilzahlungen bis zur vollständigen Bezahlung überwacht.

**Comment by j-dimension** [comment]
Teilzahlungen: Duplikat von #2233 und #2135 sowie #1955, über welches das bereits umgesetzt ist.
Man kann das bereits auch im Live-System ausprobieren. 

Für die Übersicht / die Auswertung passe ich den Titel des Tickets an.

**Comment by iradraconis** [comment]
> Im Belegdialog gibt es nur "offen" und "bezahlt".
> 
> Hier sollte es auch die Möglichkeit "bezahlt in Höhe von" geben, wobei dann der gezahlte (Teil-) Bruttobetrag eingegeben werden sollte.

Das fehlt m.E. in der Vorschau der 2.6 im Belegfenster noch und wäre wichtig, damit der Belegstatus auch passend gesetzt werden kann. Bsp. "teilweise bezahlt" o.ä. .
