### ISSUE TITLE
[BUG] Anzeige brutto/netto in Belege-Tab

### ISSUE THREAD

**Issue by j-dimension** [jlawyerorg/j-lawyer-org#2272]
User: "In dieser Akte sind zwei Zahlungen "verbucht". Wenn ich in die Akte hinein gehe, wird der Betrag der Rechnungssumme in netto angezeigt, gehe ich dann in das Belegfenster und schließe dieses wieder, aktualisiert sich der Betrag auf den Bruttobetrag."

**Comment by iradraconis** [comment]
Ergänzend: die Eingaben im Aktenkonto werden nicht unmittelbar im Bereich der Belegübersicht dargestellt. Die Eingabgen werden erst nach Verlassen und wieder Öffnen der Akte angezeigt.
