### ISSUE TITLE
[BUG] Größe Metaspace zu gering

### ISSUE THREAD

**Issue by iradraconis** [jlawyerorg/j-lawyer-org#2273]
ich erhalte seit dem Update auf 2.6 in einigen Vorlagen - nicht immer auch wenn es dieselbe Vorlage - ist  folgenden Fehler 
![Bildschirmfoto vom 2024-01-11 07-36-30](https://github.com/jlawyerorg/j-lawyer-org/assets/71747937/e39d34a8-f1c4-4d7f-82fd-740784723d14)

**Comment by j-dimension** [comment]
@iradraconis Du müsstest bitte mal die Datei 

wildfly/bin/standalone.conf

bearbeiten und aus

`JBOSS_JAVA_SIZING="-Xms256m -Xmx2048m -XX:MetaspaceSize=96M -XX:MaxMetaspaceSize=256m"`

das hier machen:

`JBOSS_JAVA_SIZING="-Xms256m -Xmx2048m -XX:MetaspaceSize=96M -XX:MaxMetaspaceSize=384m"`

Danach den Dienst neu starten. Zeitnah wäre hier sinnvoll, weil Dein Server zu wenig RAM nutzen darf.

**Comment by j-dimension** [comment]
Wenn der Server RAM-mäßig gut ausgestattet ist, dann auch gern diese Variante:

`JBOSS_JAVA_SIZING="-Xms512m -Xmx4096m -XX:MetaspaceSize=96M -XX:MaxMetaspaceSize=384m"`

**Comment by iradraconis** [comment]
Der Server hat 32 gb ram. Ich passe das  mal an. Danke.

**Comment by j-dimension** [comment]
Standardkonfiguration für Installer angepasst.
