### ISSUE TITLE
[FEATURE] offenen Betrag in der Belegübersicht anzeigen

### ISSUE THREAD

**Issue by iradraconis** [jlawyerorg/j-lawyer-org#2274]
An dieser Stelle wäre es gut, auch den "noch offenen" Betrag zu sehen, ohne selbst rechnen zu müssen :) Übrigens fehlt die Währung bei Zahlungseingang.

![grafik](https://github.com/jlawyerorg/j-lawyer-org/assets/71747937/fdad00a1-799a-45d9-b00a-56d19e8a8bf5)

**Comment by j-dimension** [comment]
erledigt, zusammen mit #2269
