### ISSUE TITLE
Scaneingang sehr langsam / träge

### ISSUE THREAD

**Issue by iradraconis** [jlawyerorg/j-lawyer-org#2275]
Bei uns ist der Scan Eingang, also das Anklicken, die Darstellung und das Zuordnen von  Scans in die jeweiligen Akten sehr träge und ich meine wirklich sehr träge.  

Der Server ist per LAN Kabel mit dem Router verbunden und die Clients greifen per WLAN, mE mit guter Verbindung auf den Server zu. Gibt es etwas, das wir tun können, um hier eine bessere Performance zu erzielen?

**Comment by j-dimension** [comment]
Kannst Du sagen was genau langsam ist? Ich hantiere hier idR mit PDFs <10 Seiten, da benötigt der Client <1s zum Laden und Darstellen. Und wie groß sind die PDFs so?

**Comment by iradraconis** [comment]
Selsbt das Zuordnen von nur 1-2 seitigen PDFs ist mehr als träge. Das Laden der Vorschau dauert schon mehrere Sekunden. Unsere Scans sind dabei aber nicht sonderlich groß (Dateigröße). Nach dem Laden der Vorschau springt auch manchmal die Auswahl der Datei zurück, so dass diese erneut angeklickt werden muss um dann eine Zuordnung vornehmen zu können. Es ist schon auffällig langsam. 

Ich versuche die Tage mal ein Video zu machen.

**Comment by j-dimension** [comment]
MariaDB Buffer Pool zu klein

**Comment by iradraconis** [comment]
Das Problem ist jetzt gelöst, es lässt sich wieder arbeiten mit dem Scaneingang!! Danke Jens!
