### ISSUE TITLE
[FEATURE] Kalendereinträge im Kalenderblatt auf "erledigt" setzen können (Haken setzen) per Kontextmenü

### ISSUE THREAD

**Issue by iradraconis** [jlawyerorg/j-lawyer-org#2279]
bisher muss der Nutzer die Akte öffnen.

**Comment by iradraconis** [comment]
@j-dimension Jens, ich stehe auf dem Schlauch, ich bekomme das eigentliche Ereignis in der Akte nicht auf "erledigt" gesetzt. Eintrag im Menü ist drin und das Event wird gelöscht, könntest du mir einen Tipp geben?

**Comment by j-dimension** [comment]
@iradraconis der Code in feature/calendar-mark-events-as-done manipuliert nur die GUI-Komponente. @iradraconis der Code in feature/calendar-mark-events-as-done manipuliert nur die GUI-Komponente. Es muss noch einen Request an den Server gehen, um den Eintrag in der Datenbank zu aktualisieren. 

Jedoch: der Kalendereintrag im Tabellenblatt in der GUI kennt bisher nicht die ID des Kalendereintrages, nur die Akte. Daher musste ich etwas tiefer reingreifen. Schau Dir mal den letzten Commit an, wenn es Dich interessiert. 

Ich habe direkt in den Feature Branch gepusht, ihn aber offen gelassen - weiß nicht ob Du noch weitere Änderungen geplant hast. 

Hinweis: ich habe eine Server-Methode hinzugefügt, wenn Du meine Änderungen lokal hast, musst Du auch den Server neu bauen und deployen.

**Comment by iradraconis** [comment]
Ja genau, ich hatte gesehen, dass nur das Kalender Event gelöscht wurde. War nur halbfertig. 

Schaue mir das gleich mal an. Tausend Dank!
