### ISSUE TITLE
e-mail Akte zuordnen bug

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-org#228]
Wenn man im e-mail Fenster rechts über den drei Button auf "Akte zuordnen" klick gibts ne Fehlermeldung wegen fehlender Akten ID - Fehler beim Laden der Akte..... Der linke Button drunter zum speichern funktioniert, aber man muss die Akte suchen...

**Comment by j-dimension** [comment]
Die Beschriftung "Akte zuordnen" sollte in der Tag gar nicht klickbar sein --> Bug

Akte suchen musst Du nur, wenn die Absendermailadresse nicht in der Adressverwaltung bekannt ist. Wird zur Absenderadresse ein Kontakt gefunden, der als Beteiligter in einer Akte vorhanden ist, dann bekommst Du weiter unten in der Seitenleiste direkt die Zuordungsmöglichkeiten und die Suche entfällt.
