### ISSUE TITLE
[FEATURE] Drebis: Datum des Schadens aus Falldaten übergeben

### ISSUE THREAD

**Issue by Linkki2021** [jlawyerorg/j-lawyer-org#2281]
Ich weiß nicht, ob Du darauf Einfluss hast Jens. Wenn man eine Kfz-Schadenmeldung macht und dann via Link direkt ins Drebis-Portal wechselt (im Übrigen auch ein Schritt, den ich mir gerne sparen würde) werden bestimmte vorhandene Daten nicht übertragen.

Er hinterlegt das Aktenzeichen und den Namen des Mandanten (hier aus Datenschutzgründen geschwärzt), nicht aber das Kfz-Kennzeichen oder das Unfalldatum sowie den Schadenhergang. Damit pflege ich die Daten doppelt.

Hat das damit zu tun, dass das Programm nicht weiß, aus welchem Falldatenblatt etwas gezogen werden soll? Falls ja könnte das irgendwie eingebaut werden, dass sich die Daten aus dem FDB Verkehrsunfalldaten gezogen werden (oder eine Auswahlmöglichkeit, falls es mehrere gibt, wobei zumindest wir dieses Szenario nicht haben)?

![Bild1](https://github.com/jlawyerorg/j-lawyer-org/assets/77149788/1a6cf882-10ed-45ee-9064-7bd29de56052)

**Comment by j-dimension** [comment]
Habe gerade versucht das nachzuvollziehen. Das Kennzeichen - sofern im Wizard eingegeben, ist dann bei mir auch im Portal bereits eingetragen. Das kann man über die Schnittstelle mitgeben. Das wird jedoch im Wizard nicht vorbelegt mit dem Wert aus einem Falldatenblatt. Könnte man machen. 

Ansonsten ist die Übergabe fachlicher Daten (abgesehen von Versicherungsinformationen und Personen) an Drebis nur für folgende Attribute möglich:

```
	<xsd:complexType name="KfzSchadenDatenType">
		<xsd:sequence>
			<xsd:element name="KfzKennzeichen" minOccurs="0"
				maxOccurs="1">
				<xsd:annotation>
					<xsd:documentation>Das KFZ-Kennzeichen des schädigen-den KFZs
					</xsd:documentation>
				</xsd:annotation>
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:minLength value="1"></xsd:minLength>
						<xsd:maxLength value="15"></xsd:maxLength>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
			<xsd:element name="Schadentag" minOccurs="0" maxOccurs="1">
				<xsd:annotation>
					<xsd:documentation>Tag, an dem der Schaden entstanden ist
					</xsd:documentation>
				</xsd:annotation>
				<xsd:simpleType>
					<xsd:restriction base="xsd:date">
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
			<xsd:element name="Schadensparte" minOccurs="1"
				maxOccurs="1">
				<xsd:annotation>
					<xsd:documentation>Angabe, um welche Schadensparte es sich bei dem
						KFZ-Schaden handelt. Gültige Werte sind:
						Kraftfahrthaftpflichtversicherung
						Fahrzeugvollversicherung
						Fahrzeugteilversicherung
					</xsd:documentation>
				</xsd:annotation>
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:minLength value="1"></xsd:minLength>
						<xsd:maxLength value="20"></xsd:maxLength>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
			<xsd:element name="Schadenort" minOccurs="1" maxOccurs="1">
				<xsd:annotation>
					<xsd:documentation>Ort, an dem der Schaden entstanden ist
					</xsd:documentation>
				</xsd:annotation>
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:minLength value="1"></xsd:minLength>
						<xsd:maxLength value="72"></xsd:maxLength>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
			<xsd:element name="PolizeilichAufgenommen" minOccurs="1"
				maxOccurs="1">
				<xsd:annotation>
					<xsd:documentation>Wurde der Schaden von der Polizei aufgenommen?
					</xsd:documentation>
				</xsd:annotation>
				<xsd:simpleType>
					<xsd:restriction base="xsd:boolean">
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
			<xsd:element name="AktenzeichenGericht" minOccurs="0"
				maxOccurs="1">
				<xsd:annotation>
					<xsd:documentation>Das Aktenzeichen des Gerichts
					</xsd:documentation>
				</xsd:annotation>
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:minLength value="1"></xsd:minLength>
						<xsd:maxLength value="30"></xsd:maxLength>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
```

Für genannte Attribute könnte an den Wizard entsprechend vorbelegen, allerdings bekomt man den Unfallhergang gar nicht transferiert.

**Comment by Linkki2021** [comment]
Unscharf von mir formuliert: nicht im Portal vorhanden ist das Kennzeichen des Mandanten/Geschädigten. Das ist gem. Schnittstelle offenbar leider auch nicht vorgesehen. 

Im Wizard ist das Kennzeichen des Schädigers aufgeführt, das sich aus dem FDB geholt wird, das wird dann auch ins Portal übertragen.

**Comment by j-dimension** [comment]
> Was aber möglich sein müsste im Screenshot oben: Das Datum des Schadens übergeben. Im Wizard gibt es auch den Schadentag.

Beobachtung hier: 
- Unfalltag im FDB erfasst
- Drebis-Schadenmeldung-Wizard geöffnet, Datum steht dort voreingetragen drin
- Anfrage an Drebis senden
- im Browser vervollständigen - Schadentag wurde übernommen

@Linkki2021 habt Ihr einen anderen Workflow oder irgendwelche Informationen, die beim Reproduzieren hilfreich sein könnten?

**Comment by Linkki2021** [comment]
Gerade live nochmal einen Übertrag begleitet: Feld "Wann trat der Schaden ein?" im Browser nicht befüllt, im Wizard zuvor schon. Gegnerische Versicherung in dem Fall: HUK (ich glaube, die Maske unterscheidet sich je nach empfangender Versicherung)

**Comment by j-dimension** [comment]
https://github.com/jlawyerorg/j-lawyer-org/assets/3729754/9fb8a86f-33b8-4d55-b37b-ddd207b0709d

**Comment by j-dimension** [comment]
@Linkki2021 hier mal ein Video (Übertragung an Drebis Testumgebung). Aus meiner Sicht wird alles übertragen, was die Schnittstelle erlaubt. 

Ist Eure Bediensequenz die gleiche?

**Comment by j-dimension** [comment]
Nein, die Masken sind immer die selben. Mir scheint dass es eine größere Abweichung zwischen Drebis produktiv und Test gibt. Ich werde den Support kontaktieren.

**Comment by j-dimension** [comment]
"Blocked" aufgrund der Unterschiede zwischen Test und Produktion.  Unklar, wie hier weiter verfahren werden könnte.

**Comment by j-dimension** [comment]
Ich schließe dieses Ticket. Totes Pferd :-(
