### ISSUE TITLE
[FEATURE] Sortierung der Auswertungstabellen

### ISSUE THREAD

**Issue by Maz111111** [jlawyerorg/j-lawyer-org#2285]
Ich hoffe, es liegt kein Bedienfehler vor.

Es ist mir jedenfalls nicht möglich, in den Auswertungsansichten durch Klick auf den jeweiligen Spaltennamen eine Sortierung nach diesem Spaltennamen zu erreichen.

Ein Klick löst nichts aus.

Es wäre gut, wenn man durch entsprechenden Klick auf den Spaltennamen, nach RE Nr oder Status etc. sortieren könnte.

Aktuell wird bei mir in der Reihenfolge der Rechnungen 4,5,6,1,2,3 angezeigt und ich kann es irgendwie nicht ändern.

**Comment by j-dimension** [comment]
Duplikat von #2216, und bereits erledigt.
