### ISSUE TITLE
[FEATURE] Auswertung pro Anwalt - Zahl der Fälle, Einnahmen aus diesen Fällen 

### ISSUE THREAD

**Issue by iradraconis** [jlawyerorg/j-lawyer-org#2286]

**Comment by iradraconis** [comment]
Die Auswertung pro Anwalt ist aus meiner Sicht übrigens viel sinnvoller als die pro Kunde/Mandant. Gerade in Kanzleien mit mehreren Berufträgern ist eine konkrete Auswertung der erwirtschafteten Umsätze pro Berufsträger von großem Interesse.

**Comment by iradraconis** [comment]
Chance für die 2.6? 🫣🫣🫣

**Comment by j-dimension** [comment]
Eher nicht, ich muss irgendwann den Sack zu machen. Ich könnte eine 2.6.1 bauen, wenn etwas weiteres Feedback gekommen ist - die könnte Bug Fixes und dieses Ticket enthalten.

**Comment by j-dimension** [comment]
Bräuchte dann allerdings auch mehr Details zu den gewünschten Inhalten und Datenquellen (bspw. können Einnahmen aus erstellten Rechnungen oder aus dem Aktenkonto ermittelt werden).

**Comment by iradraconis** [comment]
Die aktenübergreifend realisierten Einnahmen der Anwälte wären interessant, also vordergründig die im Aktenkonto verbuchten Einnahmen. 

Eine Auswertung zusätzlich nach erstellten Belegen (Rechnungen) der Anwälte wäre auch interessant.

**Comment by Dickmaulruessler** [comment]
Ich, Einzelanwalt, brauche das freilich nicht; 
kann mir aber gut vorstellen, dass dies eine sehr wertvolle Info in Sozietäten sein dürfte.

**Comment by iradraconis** [comment]
> Eine Auswertung zusätzlich nach erstellten Belegen (Rechnungen) der Anwälte wäre auch interessant. 

Dieser Punkt wäre schon erledigt, wenn man in die Auswertung der offenen Rechnungen noch den Sachbearbeiter aufnehmen könnte. Die Auswertung gibt es bereits. 

Die Auswertung nach vereinnahmten Geldern ist natürlich unterm Strich wichtiger :-)

**Comment by iradraconis** [comment]
Ich würde das hier gern sponsorn, damit es das Feature in die nächste Version schafft.

**Comment by j-dimension** [comment]
Anwalt und Sachbearbeiter aufgenommen in die Reporte:
- Alle Rechnungen / Belege
- Offene Rechnungen
- Fällige Rechnungen
- Akten mit nicht ausgeglichenem Fremdgeld
- Ergebnis pro Akte
- Buchungen

**Comment by j-dimension** [comment]
Neuer Tabellen-Tab im Report "Akten pro Monat", der eine Pivottabelle für die Anwälte / Anwältinnen und deren Fallaufkommen enthält:

![grafik](https://github.com/jlawyerorg/j-lawyer-org/assets/3729754/6bbe0f4f-9fd4-4c3d-8387-a869572c082e)

**Comment by j-dimension** [comment]
im Report "Aktenkonto - Buchungen" gibt es in der bisherigen Tabelle nun die Spalten "Anwalt" und "Sachbearbeiter". Zusätzlich gibt es weitere Tabellen, die die Buchungen nach dem Anwalt der Akte gruppiert darstellen (also alle Buchungen der Akten von Anwalt x in einem Tab):

![grafik](https://github.com/jlawyerorg/j-lawyer-org/assets/3729754/49550246-0672-4625-b024-96915e35b35a)

Reicht das evtl. bereits? Oder werden kumulierte Werte benötigt? (die könnte man auch einfach über einen Export in die Tabellenkalkulation bekommen).

**Comment by iradraconis** [comment]
Das sieht schon gut aus. Ein Export in die Tabellenkalkulation würde mich jetzt nicht stören, auch wenn ein direktes Ablesen der Einnahmen pro Anwalt/Sachbearbeiter in der Auswertung toll wäre.

**Comment by j-dimension** [comment]
Nur "Einnahmen", ja? Oder jeweils die Summe über "Einnahmen-Ausgaben" in einer Spalte?

**Comment by j-dimension** [comment]
weiteres Tabellenblatt mit den kumulierten Werten im Report "Aktenkonto - Buchungen":

![grafik](https://github.com/jlawyerorg/j-lawyer-org/assets/3729754/08ba218f-5cdf-468e-8349-a1b4303257a3)

**Comment by iradraconis** [comment]
super!!
