### ISSUE TITLE
[FEATURE] neuer optionaler Parameter für Datumsformat bei Fristen-Funktionen

### ISSUE THREAD

**Issue by LazyGuy21No** [jlawyerorg/j-lawyer-org#2290]
Ich möchte die Rückgabe von Fristen-Funktionen in einem anderen Format erreichen. Also z.B.

Als Frist habe ich mir den [[SCRIPT:FRISTBANKTAG(KURZDATUM,"14");]] notiert.

—> Als Frist habe ich mir den 2023-02-23 notiert.

oder:

Als Frist habe ich mir [[SCRIPT:FRISTBANKTAG(KURZDATUM,"14");]] notiert.

—> Als Frist habe ich mir Freitag, den 23. Februar 2024 notiert.

Die Funktion DATUMZEIT(Format) kann das aktuell ja mit einem Formatierungsparameter (z.B. **"EEEEE, dd. MMMMM yyyy“**)

---------------------

@j-dimension schrieb dazu:

`[[SCRIPT:new java.text.SimpleDateFormat("yyyy-MM-dd").format(new java.text.SimpleDateFormat("dd.MM.yyyy").parse(FRISTBANKTAG(KURZDATUM,"14")));]]
`

**Comment by j-dimension** [comment]
Ich sehe gerade dass das bereits via #827 umgesetzt und auch dokumentiert wurde - ist also direkt nutzbar.
