### ISSUE TITLE
alternativer VoIP-Anbieter: Placetel

### ISSUE THREAD

**Issue by j-dimension** [jlawyerorg/j-lawyer-org#230]
siehe https://www.j-lawyer.org/?topic=placetel-statt-sipgate-moeglich

API existiert: https://www.placetel.de/hilfe/telefonanlage/api

**Comment by ForCase** [comment]
Sie finden ebenfalls eine Beschreibung der API unter https://api.placetel.de/v2/docs/

**Comment by j-dimension** [comment]
Über die nun verfügbare Softphone-Anbindung bereits machbar.
