### ISSUE TITLE
[FEATURE] erweiterte Tastaturunterstützung bei Eingabe von Zahlungen, Belegen etc.

### ISSUE THREAD

**Issue by iradraconis** [jlawyerorg/j-lawyer-org#2304]
Ich wünsche mir eine etwas umfangreichere Tastatur Unterstützung abgesehen von der Tabulatortaste. Gerade das Eingeben von mehreren Zahlungsvorgängen in ein Aktenkonto könnte effizienter sein. Nachdem wir nun das neue Aktenkonto haben, habe ich aus zahlreichen Akten die dort verbuchten Zahlungen in das neue System überführt. Die Mauswege und die Zahl der Klicks bei Bearbeitung eines Aktenkontos sind momentan eine kleine Herausforderung.

Das Aktenkonto an sich ist eines der besten Features der neuen Version, weil es so wichtig ist. Das Ticket hier dient nur dem Feinschliff :)

**Comment by j-dimension** [comment]
Eintragen mehrerer Buchungen sollte nun vollständig ohne Maus möglich sein. 

- Wechsel zwischen den Elementen mittels Enter (Ausnahme ist das Beschreibungsfeld, da dort ja mehrzeiliger Text eingegeben werden kann - dort Tab nutzen)
- Auswahl Beteiligte(r) über Enter
- Bei Fokus auf ein Feld mit Geldbetrag wird der Feldinhalt selektiert, sodass direkt losgetippt werden kann
- am Ende des Dialogs wird "Speichern" fokussiert

**Comment by iradraconis** [comment]
Danke! Großartig!

**Comment by j-dimension** [comment]
Kann jetzt auch in der Online-Demo ausprobiert werden.
