### ISSUE TITLE
[FEATURE] [Akte] Dokumentenfenster mitscrollen lassen

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#2308]
Wenn ich in der Dokumentenliste mit Pfeil hoch/runter die Dokumente durchgehe, wäre es schön, wenn der "Cursor" nicht einfach oben bzw unten verschwindet, wenn ich dort weiterdurchklicke, sondern stattdessen die Liste mitscrollt. So wie zb im Windows-Datei-Explorer.

**Comment by Dickmaulruessler** [comment]
siehe #2025
