### ISSUE TITLE
[FEATURE] [Akte] Idee für Tastensteuerung

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#2309]
In der Dokumentenliste kann ich mit Pfeil hoch/runter die Dokumente durchgehen. Zur schnellen Durchsicht einer Akte wäre es toll, wenn ich zusätzlich bei mehrseitigen Dokumenten mit Pfeil rechts/links das jeweils aktuelle Dokument seitenweise durchblättern könnte. Dann wäre alles per Tastatur möglich. Also Pfeil runter = nächstes Dokument / Pfeil rechts nächste Seite.

Ggf könnte man mit Pfeil rechts auf der letzten Seite auch den Sprung zum nächsten Dokument auslösen. Analog für links auf der ersten Seite und vorheriges Dokument.

**Comment by Dickmaulruessler** [comment]
siehe dort: #2299
