### ISSUE TITLE
[BUG] Abbruch bei versehentlicher Löschung Beleg - Finanzen

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-org#2314]
Ich habe in einem Beleg versehentlich Belegpositionen weggelöscht, die schon zu einer Kostennote gehörte. Da es keine Widerherstellung gab, habe ich das Fenster über Abbruch verlassen ohne zu speichern, aber die Belegpositionen ware und blieben gelöscht. Eigentlich sollte das nicht so sein. Wenn ich den Beleg versehentlich weglösche sollte bei Abbrechen der vorherige Zustand gerettet sein. Leider nicht... Alternativ bräuchte man eine Wiederherstellungoption, Schritt rückgängig machen.

**Comment by j-dimension** [comment]
In 2.6 gibt es eine Rückfrage, bevor Positionen gelöscht werden. Das sollte die Problematik entschärfen.
