### ISSUE TITLE
Kostennote aus Belegpositionen neu erstellen

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-org#2315]
Stand 2.5 kann man über das RVG Plugin eine RVG Rechnung erstellen und die Berechnung als Belegpotionen in die Finanzen übernehmen. Aber es gibt keine Möglichkeit, wenn man eine Belegposition vergessen hat, aus den Belegpositionen neu die RVG Rechnung zu erstellen. Im Moment kann man nur alles neu erstellen (Höchststrafe bei großen Rechnungen mit viel Reisekosten) oder die fehlende Position als extra RVG-Berechnung als weitere Tabelle in die Kostennote mit reinkopieren und händisch den neuen Zahlbetrag errechnen.

**Comment by iradraconis** [comment]
> Stand 2.5 kann man über das RVG Plugin eine RVG Rechnung erstellen und die Berechnung als Belegpotionen in die Finanzen übernehmen. Aber es gibt keine Möglichkeit, wenn man eine Belegposition vergessen hat, aus den Belegpositionen neu die RVG Rechnung zu erstellen. Im Moment kann man nur alles neu erstellen (Höchststrafe bei großen Rechnungen mit viel Reisekosten) oder die fehlende Position als extra RVG-Berechnung als weitere Tabelle in die Kostennote mit reinkopieren und händisch den neuen Zahlbetrag errechnen. 

Also soweit ich das beurteilen kann, können einzelne Positionen durchaus hinzugefügt werden. Im Belegfenster eine neue Berechnung aufmachen, dann beispielsweise nur die Auslagen wie Fahrtkosten etc. aufnehmen und dann unten auf "als Rechnung" anklicken. Dann werden diese Positionen hinzugefügt. Habe ich schon oft gemacht.

**Comment by iradraconis** [comment]
> Die von Iradraconis angeführte Lösung praktivziere ich dann schon, aber die Rechnung enthält dann wenigstens zwei Tabellen mit jedesmal eigener Umsatzsteuer. Muss entweder händisch geändert werden und von Hand die Summe, Umsatzsteuer und Zahlbetrag neu ermittelt werden (auch händisch). Alle Zeit- und Automatisierungsvorteile des Computers schmelzen dahin)... Und dann ruft der verunsicherte Mandant an und fragt, was das mit den zweimal Umsatzsteuer und zwei Tabellen soll. Das gleiche fragt mich dann säuerlich mein Buchhalter und weist darauf hin, dass in einer Rechnung sinnvollerweise, nur einmal die Umsatzsteuer mit ihrem Satz am Ende erscheinen darf.... Die Not-Lösung ist also doppelt suboptimal. Und dabei stehen doch alle ergänzten Positionen sauber im Beleg in Finanzen - nur nutzen kann man das dann nicht zu einer (korrigierten) Rechnungserstellung.

Das verstehe ich nicht, oder du praktizierst nicht meine angeführte Lösung :) 
Beispiel: über das Belegfenster wird das Rechnungsplugin geöffnet, eine Berechnung vorgenommen und "als Rechnung" hinzugefügt. dann befinden sich die Rechnungspositionen alle im Belegfenster. Soweit so gut. Hast du nun Auslagen wie beispielsweise Fahrtkosten vergessen, öffnest du ein neues Berechnungsplugin, gibst nur die Fahrtkosten ein, klickst unten auf "als rechnung"  und diese Position wird den Positionen, die  vorher im Belegfenster vorhandenen wren, hinzugefügt. Im Anschluss erstellst du einfach ein neues Rechnungsdokument und hast darin auch nur eine Tabelle. Die Tabelle weist dann alle die Positionen aus, die vorher im Belegfenster standen. 

Ist doch eine gute Lösung oder verstehe ich deine Problemstellung falsch?

**Comment by Mucki526** [comment]
Dann verstehe ich das nicht. Wie mache ich aus den Belegpositonen  im Belein Finanzen eine Rechnungstabelle für die Kostennote, bzw. welches Kürzel in der Vorlage muss das haben?? Das ist das was ich eigentlich suche. Ich kann aus dem Plugin heraus mit <Tabelle1> eine Tabelle in der Kostennote erzeugen, aber nicht aus den Belegpositionen in Finanzen (oder ich kenne das Kürzel dafür nicht???).

**Comment by j-dimension** [comment]
https://www.j-lawyer.org/downloads/documentation/j-lawyer.org-UserGuide-de.html#__RefHeading__273_1146603382

**Comment by Mucki526** [comment]
Lange Frage.... und hier die Antwort --- und diese Kürzel habe ich nicht gesehen (weil ich auch nicht wusste, wonach ich suchen soll). Super... Danke für die Geduld und Mühe, dann kann man das hier schließen... Das habe ich vorgeschlagen, ist aber schon mehr als umgesetzt.... 👍.
