### ISSUE TITLE
[BUG] Farbmarkierungen schief

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#2318]
Keine Ahnung, hab ich einen Knick in der Optik? Oder ist das eine optische Täuschung?

![image](https://github.com/jlawyerorg/j-lawyer-org/assets/29924198/8d5539bc-a45f-40a1-b284-a3a80c54c27d)

Mir scheinen die Farbquadrate nicht einheitlich zu sein. Mal runder, mal eckiger, nicht alle (links) auf einer Linie ausgerichtet ...?

**Comment by j-dimension** [comment]
Wahrscheinlich optische Täuschung durch den alternierenden Hintergrund.

Werde hier keine Zeit investieren.
