### ISSUE TITLE
[BUG]  Plugin: Rechner RVG Wertgebühren 3.2.2

### ISSUE THREAD

**Issue by alexhell** [jlawyerorg/j-lawyer-org#2319]
Der Rechner scheint bei hohen Gegenstandswerten nicht die richtige Gebühr zu berechnen.

**To Reproduce / Schritte zum Nachvollziehen**
Gegenstandswert von > 3 Mio EUR eingeben, dann erscheint bei mir eine Gebühr von 15 EUR

**Comment by an-mus** [comment]
Dazu müssen die Listen in RvgTablesRangeList2021.groovy und RvgTablesRangeList.groovy fortgeschrieben werden. Ich hatte das vor langer Zeit schon mal bis 3 mio gemacht, aber nur für das neue RVG ab 2021. 
Man könnte jetzt natürlich einfach ein kleines script machen, dass die Liste bis xx mio einfach fortschreibt. Über kurz oder lang wird aber wer drüber stolpern, dass die Liste irgendwann endet. Außerdem wird dann die Ausgabe des Plugins RVG-Tabelle immer länger. 
Ab einem Streitwert von 500 000€ erhöht sich das ganze linear: "für jeden angefangenen Betrag von weiteren 50 000 Euro um 165 Euro". (§ 13 RVG)
Ich fände ja es wäre die sauberere Lösung, das in Software zu gießen, statt eine Tabelle zu hinterlegen. Das übersteigt aber aktuell meine Programmierfähigkeiten ;-)
@j-dimension: sag doch mal ob ich kurzfristig nochmal die Tabelle verlängern soll oder ob du dich an eine gerechnete Lösung machen willst.

**Comment by an-mus** [comment]
Hi, ich bin an einem patch dran, der für Gegenstandswerte größer als 500 000€ den Rückgabewert rechnet, statt ihn aus der Tabelle zu übernehmen. Ich versuche mal, den bis heute Abend fertig zu bekommen. Schöne Grüße.

**Comment by j-dimension** [comment]
@an-mus sorry für die späte Reaktion, ich bin gerade mit Hochdruck daran, die 2.6 fertig zu bekommen. Ich kann das Thema auch übernehmen, aber wohl erst nächste Woche. :-(

**Comment by an-mus** [comment]
Alles gut, ich wollte nur nicht, dass wir gleichzeitig dran sind. Die Lösung war auch doch nicht so kompliziert :-)  
b7c72915c5e98da1ab18f6a496f3332c879ea245

**Comment by an-mus** [comment]
close

**Comment by an-mus** [comment]
Der Bug ist erledigt. Ich kann ihn aber nicht schließen, er liegt im falschen Repository.

**Comment by j-dimension** [comment]
Besten Dank, @an-mus !
