### ISSUE TITLE
Änderungen in LibreOffice Dokumenten werden manchmal nicht gespeichert

### ISSUE THREAD

**Issue by bjk00** [jlawyerorg/j-lawyer-org#232]
Ich habe sporadisch das Problem, dass Änderungen die in vorhandenen LibreOffice-Textdokumenten gemacht werden, nicht gespeichert werden. Also nach dem Öffnen einer vorhandenen odt-Datei aus einer Akte werden Änderungen vorgenommen und danach auf Speichern geklickt. Das Dokument wird ohne Fehlermeldung geschlossen, wenn man es wieder öffnet, sind die gemachten Änderungen jedoch nicht vorhanden.

Der Fehler tritt sehr oft nach dem zweiten Speichern eines offenen odt-Files auf. Die Schritte zum Fehler:
1. odt-Datei aus der Akte/Dokumente heraus öffnen.
2. Änderungen vornehmen
3. Auf speichern klicken
4. weiter Änderungen vornehmen
5. auf Speichern klicken
…
usw.
xx. Dokument schließen und die Abfrage ob gespeichert werden soll bestätigen

Alle Änderungen ab Punkt 3 werden zwar in der temporären Datei unter C:\Users\Nutzername\AppData\Local\Temp gespeichert aber nach dem Schließen nicht mehr von j-lawyer übernommen. Die temporäre Datei bleibt jedoch scheinbar erhalten, sodass die gemachten Änderungen nicht verloren sind. 

Ich hatte jedoch auch schon den Fall, dass alle Änderungen seit dem Öffnen des Dokumentes nicht übernommen wurden.

Konfiguation: 
Client Windows 10, j-lawyer 1.9.1, LO 6.0.7.3
Server Linux Mint 18.1

Das Problem trat sporadisch und relativ selten auch schon früher auf, mit LO5 und j-lawyer < 1.9.1, Windows 7. Die Serverkonfiguration war identisch zur oben genannten.

**Comment by j-dimension** [comment]
Dazugehöriger Foreneintrag:
https://www.j-lawyer.org/?topic=aenderungen-in-libreoffice-dokumenten-werden-manchmal-nicht-gespeichert/

**Comment by Mucki526** [comment]
Das hatte ich auch schon. Heißt ggf. alles noch mal, wenn die Änderungen nicht mehr verfügbar sind.  Mir hat schon geholfen, den Ausdruck mit Paperport (OCR-Schrifterkennung zu scannen und den Text neu einzulesen). Es passiert auch, wenn man einen weiteren Client aufmacht, den ersten vergisst oder zumacht und die Verbindung zur Akte damit verloren geht (ggf. weil man übersieht, dass die Datei noch offen aber ungespeichert ist und die Warnung, es sind noch Dokumente offen ignoriert (sollte man natürlich nicht).

**Comment by j-dimension** [comment]
Workaround für temporäres Verschwinden der LibreOffice-Locks entwickelt und getestet (testen lassen - Danke @bjk00 ). Test auf Seiteneffekte unter Linux und macOS noch offen.
