### ISSUE TITLE
[FEATURE] [Finanzen] Belegliste hat zwei gleiche Icons

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#2320]
Bei den Belegen in der Akte gibt es zwei Buttons mit demselben Icon.

![image](https://github.com/jlawyerorg/j-lawyer-org/assets/29924198/345a49d6-0006-4ad8-b37b-87b8d19239a8)

Einmal duplizieren in der Akte und einmal kopieren in eine andere Akte. Was was ist, sieht man erst beim tooltip.

Könnte dem ersten Icon unten rechts ein + und dem zweiten ein Pfeil spendiert werden?

**Comment by iradraconis** [comment]
![Eingefügtes Bild 1](https://github.com/user-attachments/assets/9f0537bf-ad3c-48e4-8ccb-0188091376ac)

**Comment by j-dimension** [comment]
getestet
