### ISSUE TITLE
[TASK] ePost - Rückmeldung über Status?

### ISSUE THREAD

**Issue by iradraconis** [jlawyerorg/j-lawyer-org#2323]
Ich habe gestern ein Schreiben an die ePost übergeben und dann heute morgen gesehen, dass der Status anders aussieht als bei den übrigen Schreiben. Ich dachte "ok, dann nochmal". Das selbe Ergebnis. Es tut sich dort nichts. Also es steht auch nicht "Verarbeitung im Druckzentrum" im Status. Den Versand habe ich auf die gleiche Weise angestoßen wie bei den übrigen Schreiben. 

Der Nutzer müsste irgendwie eine Info bekommen, was mit den Schreiben passiert. Ich kann natürlich bei der Gegenseite anrufen und fragen, ob der Brief nun angekommen oder sogar 2 mal angekommen ist.. 

![Bildschirmfoto vom 2024-02-23 07-53-41](https://github.com/jlawyerorg/j-lawyer-org/assets/71747937/3eb0c5fa-4a3e-463c-aeaf-3e626a5cfbac)

**Comment by j-dimension** [comment]
Hier wäre ein Systemreport hilfreich.

**Comment by iradraconis** [comment]
per Mail verschickt

**Comment by iradraconis** [comment]
Der Status ist jetzt normal, wie bei den anderen Dokumenten.. Vielleicht ist es gar nix.. nur eine verspätete Antwort der ePost API?

**Comment by j-dimension** [comment]
Tritt auf wenn die E-POST-Server den API-Zugang "drosseln". Logik angepasst.
