### ISSUE TITLE
Vertauschtes Zeichen punkt, komma bei Zahlbetrag[BUG] 

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-org#2331]
Wenn man den Zahlbetrag per kürzel aus den Belegpositionen in die Rechnung übernimmt, dann wird aus dem "tausender-Punkt" ein Komma und aus dem Dezimalzeichen "Komma" ein Punkt.... (Also statt richtig (in Deutschland) 1.000,00 falsch 1,000.00

**Describe the bug / Fehlerbeschreibung**
(todo: a description of the bug / eine Beschreibung des Fehlers)

**To Reproduce / Schritte zum Nachvollziehen**

1. Go to / Gehe zu '...'
2. Klicke auf / Click on '....'
4. Error message / Fehlermeldung: '...'

**Expected behavior / Erwartetes Verhalten**
Eine Beschreibung des erwarteten Verhaltens.

**Screenshots**
Falls relevant, Screenshot beifügen.

**Environment / verwendete Umgebung:**
 - OS / Betriebssystem:
 - j-lawyer.org Version:

**Additional context / Sonstiges**

**Comment by j-dimension** [comment]
Duplikat von #2250
