### ISSUE TITLE
Fehler bei Neuerstellung Kostennote ohne Umsatzsteuer

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-org#2332]
Ich habe versehentlich eine Kostennote mit Umsatzsteuer erstellt. (Schweiz). Dann habe ich das gemerkt, in den Belegen links das Feld Umsatzsteuer ausgeschaltet und die Kostennote neu erstellt. Das funktioniert nicht. die Umsatzsteuer wird weiter in der Kostennote erstellt in der Tabelle und angezeigt....

**NOTE: Please search existing tickets to avoid duplicates **
**HINWEIS: Bitte vorab die Ticketsuche verwenden, um Doppeleinträge zu vermeiden **

**Describe the bug / Fehlerbeschreibung**
(todo: a description of the bug / eine Beschreibung des Fehlers)

**To Reproduce / Schritte zum Nachvollziehen**

1. Go to / Gehe zu '...'
2. Klicke auf / Click on '....'
4. Error message / Fehlermeldung: '...'

**Expected behavior / Erwartetes Verhalten**
Eine Beschreibung des erwarteten Verhaltens.

**Screenshots**
Falls relevant, Screenshot beifügen.

**Environment / verwendete Umgebung:**
 - OS / Betriebssystem:
 - j-lawyer.org Version:

**Additional context / Sonstiges**

**Comment by j-dimension** [comment]
in 2.6 bereits behoben
