### ISSUE TITLE
[FEATURE] UI: Nachrichten-Counter zählt nur Nachrichten an den aktuellen Benutzer

### ISSUE THREAD

**Issue by LazyGuy21No** [jlawyerorg/j-lawyer-org#2334]
Aktuell werden alle Nachrichten angezeigt, die sich Nutzer:innen geschrieben haben.

<img width="176" alt="image" src="https://github.com/jlawyerorg/j-lawyer-org/assets/56734761/b1b21398-9220-4b8d-98b8-67464fcad58b">

Schöner wäre, wenn nur solche gezählt würden, die mich als aktuellen Nutzer betreffen.

**Comment by j-dimension** [comment]
Es wird dort die Anzahl aller Nachrichten angezeigt, die eine nicht bestätigte Erwähnung für den angemeldeten Nutzer beinhalten.
