### ISSUE TITLE
Inhalt vom Scanordner wird nicht mehr angezeigt 2.6[BUG] 

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-org#2338]
Erst mal herzlichen Dank für die 2.6 und die ganze Arbeit und Herzblut, die da drinsteckt. Ich habe es gestern installiert. 

Nur - leider  - wird uns jetzt im scanordner (im Client) kein Scan mehr angezeigt.

Soll heißen: Der Scanordner existiert (man sieht ihn und alle Scans und neuen Scans im Explorer). Scanne funktioniert vom Drucker aus, wie gehabt. J-Lawyer zeigt auch am Zähler die Anzahl der vorhandenen scans an. 

Aber die Scans selbst werden im Abschnitt scans nicht mehr angezeigt... man sie die neue Oberfläche mit ("OCR"), aber keine Dateien...

Neustart des Clients hat nichts gebracht.... Bin ratlos. Wir machen jetzt einen Workaround über den Explorer und Drag und Drop,

Aber weil der Ordner bei uns sehr zentral genutzt wird, wäre ne schnelle Idee hilfreich...

![grafik](https://github.com/jlawyerorg/j-lawyer-org/assets/37142896/87a756e6-4e65-46f2-b4c1-f9d4d4431346)

**NOTE: Please search existing tickets to avoid duplicates **
**HINWEIS: Bitte vorab die Ticketsuche verwenden, um Doppeleinträge zu vermeiden **

**Describe the bug / Fehlerbeschreibung**
(todo: a description of the bug / eine Beschreibung des Fehlers)

**To Reproduce / Schritte zum Nachvollziehen**

1. Go to / Gehe zu '...'
2. Klicke auf / Click on '....'
4. Error message / Fehlermeldung: '...'

**Expected behavior / Erwartetes Verhalten**
Eine Beschreibung des erwarteten Verhaltens.

**Screenshots**
Falls relevant, Screenshot beifügen.

**Environment / verwendete Umgebung:**
 - OS / Betriebssystem:
 - j-lawyer.org Version:

**Additional context / Sonstiges**

**Comment by Mucki526** [comment]
Den Ordner etwas leeren und aktualisieren hat nix gebracht....

**Comment by j-dimension** [comment]
Welche Versionen zeigt Menü "?" - "Über"?

**Comment by j-dimension** [comment]
Dann muss noch ein Update auf der Box eingespielt werden. Der Server muss Version 2.6.0.17 sein.

**Comment by Mucki526** [comment]
Update läuft, aber jetzt bewegt sich nix mehr oder es ist noch in Arbeit und dauert sehr lange?
Außerdem gabs eine Warnung:

![grafik](https://github.com/jlawyerorg/j-lawyer-org/assets/37142896/0198ec07-72e1-4376-aba2-a2c27426cd00)
und jetzt scheint es hier zu "stehen". Oder ich bin zu ungeduldig (wie lange sollte das hier dauern, oder muss ich manuell den server neu starten??)

![grafik](https://github.com/jlawyerorg/j-lawyer-org/assets/37142896/cd84a7f5-4ae7-4a19-b91b-cdafda78d424)

**Comment by j-dimension** [comment]
Dort hat ein Download nicht funktioniert. Das Update nochmal anstoßen.

**Comment by Mucki526** [comment]
Hat geklappt (Schwitz..... :-)). Danke für den superfast support....Kann man hier schließen...
