### ISSUE TITLE
scans - werden gelistet, haben jetzt aber alle falsche Endung...

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-org#2340]
![grafik](https://github.com/jlawyerorg/j-lawyer-org/assets/37142896/f7fb3d04-7588-4e1a-bdc2-ac90274fca91)

**NOTE: Please search existing tickets to avoid duplicates **
**HINWEIS: Bitte vorab die Ticketsuche verwenden, um Doppeleinträge zu vermeiden **

**Describe the bug / Fehlerbeschreibung**
(todo: a description of the bug / eine Beschreibung des Fehlers)

**To Reproduce / Schritte zum Nachvollziehen**

1. Go to / Gehe zu '...'
2. Klicke auf / Click on '....'
4. Error message / Fehlermeldung: '...'

**Expected behavior / Erwartetes Verhalten**
Eine Beschreibung des erwarteten Verhaltens.

**Screenshots**
Falls relevant, Screenshot beifügen.

**Environment / verwendete Umgebung:**
 - OS / Betriebssystem:
 - j-lawyer.org Version:

**Additional context / Sonstiges**

**Comment by j-dimension** [comment]
.uploading erscheint, während ein Arbeitsplatz aus einem lokalen Scanordner die Dateien hochlädt. Verbleiben die Dokumente länger, dann funktioniert der Upload nicht und es wären die Logs zu prüfen.

**Comment by Mucki526** [comment]
Die Funktion hatte ich aus Verzweiflung vor dem update auf meinem Arbeitsplatz eingeschaltet und den zentralen scan-Ordner als zu überwachenden eingetragen. Nur - wie bekommt man das wieder abgewählt, abgeschaltet? Ich kann am Zahnrad im Scanordner den zu überwachenden Ordner auswählen, aber ich sehe nix um die Funktion wieder abzuschalten. Bzw. auf welchen Ordner muss ich es umleiten, damit nix mehr passiert und die Dateinamen wieder stimmen. (also kein Eintrag)?

**Comment by j-dimension** [comment]
Dialog öffnen, Feld "Ordnername" leeren, "Auswählen". (ggf. danach abbrechen)
