### ISSUE TITLE
[FEATURE] Sortierung Dokumente in Akte: konfigurierbar bzw. speichern

### ISSUE THREAD

**Issue by j-dimension** [jlawyerorg/j-lawyer-org#2347]
Optionen:

1. Standardsortierung konfigurieren
2. zuletzt gewählte Sortierung speichern und bei erneutem Öffnen einer Akte wiederherstellen

**Comment by Dickmaulruessler** [comment]
3x thumbs up und Danke dafür!
Die neue Sortierung nach Änderungsdatum stört mich sehr.

Wird es beide von dir eingangs erwähnte Optionen geben?
Optionen 1 gilt dauerhaft für alle Akten?
Welche Standard-Sortieroption wird es geben: 
Erstellungsdatum? 
Änderungsdatum? 
Name? (siehe da)

**Comment by j-dimension** [comment]
Es wird die zuletzt genutzte Sortierung gespeichert, am Nutzer.
