### ISSUE TITLE
[BUG] Keine Aktualisierung der Anzeige nach Belegeingabe

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-org#2352]
Wenn ich einen Beleg eingebe (eine Zahlung des Mandanten), dann wird die Statusanzeige rechts bzgl. des Aktenkontos erst aktualisiert, wenn ich die Akte verlasse und wieder reingehe. Irritierend....

**NOTE: Please search existing tickets to avoid duplicates **
**HINWEIS: Bitte vorab die Ticketsuche verwenden, um Doppeleinträge zu vermeiden **

**Describe the bug / Fehlerbeschreibung**
(todo: a description of the bug / eine Beschreibung des Fehlers)

**To Reproduce / Schritte zum Nachvollziehen**

1. Go to / Gehe zu '...'
2. Klicke auf / Click on '....'
4. Error message / Fehlermeldung: '...'

**Expected behavior / Erwartetes Verhalten**
Eine Beschreibung des erwarteten Verhaltens.

**Screenshots**
Falls relevant, Screenshot beifügen.

**Environment / verwendete Umgebung:**
 - OS / Betriebssystem:
 - j-lawyer.org Version:

**Additional context / Sonstiges**

**Comment by j-dimension** [comment]
Duplikat von #2278
