### ISSUE TITLE
[BUG] Eingabe von Auslagen, Fokus springt automatisch weiter

### ISSUE THREAD

**Issue by iradraconis** [jlawyerorg/j-lawyer-org#2356]
Wenn ich beispielsweise 12 Euro an Auslagen eingebe, springt der Fokus direkt auf das Speichern Feld, ohne dass ich vorher TAB gedrückt habe. Die Eingabe muss sehr schnell erfolgen, sonst kann sie gar nicht erfolgen, da der Fokus sofort weiter springt.

![grafik](https://github.com/jlawyerorg/j-lawyer-org/assets/71747937/8ffddc47-7d38-4406-892c-fe97a7cede63)

**Comment by j-dimension** [comment]
Es gibt hier einen Hotfix der diesen Fehler behebt:
https://cloud.j-dimension.com/index.php/s/wscJLx3KDCKoEWm?path=%2FVorschau%2FClient%2F2024-03-05_Sortierung_Akte

Ich warte erst noch ein wenig, es wird bei kritischer Masse eine 2.6.1 geben.

**Comment by j-dimension** [comment]
https://github.com/jlawyerorg/j-lawyer-org/commit/e28444051a4dd01fa63f48a6eec94cfbce5eea3c
