### ISSUE TITLE
[BUG] Dringend: Öffnen einer Notiz aktualisiert ihr Änderungsdatum auch ohne Änderungen

### ISSUE THREAD

**Issue by LazyGuy21No** [jlawyerorg/j-lawyer-org#2358]
... obwohl nichts gespeichert werden sollte.

<img width="483" alt="image" src="https://github.com/jlawyerorg/j-lawyer-org/assets/56734761/2bcf3542-8557-4905-aadb-535254c33d91">

**Comment by iradraconis** [comment]
Das führt bei uns auch zu Verwirrungen, da wir schon oft den Fall hatten (in der Vergangenheit), dass Änderungen nicht gespeichert wurden.

**Comment by j-dimension** [comment]
Das hat u.U. gar noch größere Auswirkungen: bearbeitet man die Notiz extern (mit LibreOffice), werden die Änderungen bei "Verlassen" überschrieben.
