### ISSUE TITLE
[FEATURE] E-POST: Attribute zur Sendungsverfolgung bereitstellen

### ISSUE THREAD

**Issue by j-dimension** [jlawyerorg/j-lawyer-org#2361]
Support: 

Sie finden das Attribut innerhalb des LetterStatus Schema

![grafik](https://github.com/jlawyerorg/j-lawyer-org/assets/3729754/df3c5c5c-f75c-4c74-9a68-de48cf2ca718)

![grafik](https://github.com/jlawyerorg/j-lawyer-org/assets/3729754/bc8c7246-8087-4024-a677-988b34fa5aa9)

**Comment by Dickmaulruessler** [comment]
Ich weiß nicht, ob das hierher gehört: 

Der Sendestatus muss man etwas suchen... (ich habe bisher nur einen normalen Brief getestet).

Könnte der **Dateiname** des Berichtes (aktuell: "E-POST-Bericht_Sendung-[Datum, Uhrzeit, Sendungsnummer].txt)
den man dann im Reiter "Dokumente" sieht um **"Fehler" bzw. "Erfolg"** ergänzt werden oder alternativ im Bericht selbst die Zeile **"letzter Status"** anders platziert (nicht genau mittendrin, also vielleicht zweite Zeile) oder hervorgehoben werden (*** davor und danach ***)?
