### ISSUE TITLE
EPOST-API nicht Post-Standard-konform: Länderbezeichnungen werden nur auf Deutsch akzeptiert

### ISSUE THREAD

**Issue by LazyGuy21No** [jlawyerorg/j-lawyer-org#2366]
Weltpostsprache ist Französisch. Die API scheint aber Länderbezeichnungen nur auf Deutsch zu akzeptieren. 

Das ist standardwidrig, denn nach den Vorgaben des Union Postale Universelle (Weltpostverein) _müssen_ die Vertragsstaaten Länder-Bezeichnung auch in der französischen Bezeichnung (Pays-Bas statt Niederlande) und auch die offiziellen Namen, wie bei der UNO hinterlegt ("Royaume de Belgique" statt "Belgique") akzeptieren. Ebenso müssen Städte-Namen auf Französisch akzeptiert werden, wenn es einen französischen Namen gibt (z.B. Francfort-sur-le-Main für Frankfurt am Main). Das gilt auch für Inlandssendungen! 

Also ist…

`Oberlandesgericht Frankfurt`
`Gerichtsstraße 2`
`60313 FRANCFORT-SUR-LE-MAIN`
`ALLEMAGNE`

… eine **in der innerdeutschen Beförderung** korrekte Adressierung. 

Deshalb haben auch alle Zusteller:innen eine sog. "Termpost"-Liste (auf der App) in der sich die französischen Begriffen und diverse Arbeitshilfen finden.

Die **EPOST-Business-Box** verhält sich diesbezüglich auch korrekt (und rechnet auch korrekt ab).

Das kann man - obwohl der Unwille zwischen den Zeilen durchscheint - auch in der Handreichung auf der Seite der Post finden (https://www.uni-konstanz.de/facility-management/aktuelles-vom-facility-management/aktuelles-detailseite/anschrift-und-kennzeichnung-von-auslandspost/#:~:text=Briefe%20beschriften%20ins%20Ausland%20–%20So,letzten%20Zeile%20unterhalb%20der%20Ortsangabe.).

Vielleicht kann jemand das mal an die DPAG weiterleiten, verbunden mit dem Hinweis, dass es jemanden gibt, der das in seinem Sommerurlaub noch mal testen wird, und sich dann ggf. auch gern die Zeit nehmen wird, bei der UPU eine Beschwerde wegen Nichteinhaltung der Vertragsbedingungen einzureichen. ;-)

**Comment by j-dimension** [comment]
j-lawyer.org ist hier lediglich Nutzer einer API der DPAG, das Thema sollte dort vorgetragen werden. Ich kann das über den Supportkanal einbringen, bin aber nicht im drivers seat für das Anliegen.
