### ISSUE TITLE
Überprüfung eines bereits vorhandenen Adresseintrags bei "Neueintrag"

### ISSUE THREAD

**Issue by RobertT01** [jlawyerorg/j-lawyer-org#2368]
Bitte eine Prüfungsroutine implementieren, dass der Nutzer gewarnt wird, wenn er eine Person/Unternehmen speichern will, dessen Name und/oder Adresse und/oder Tel NUmmer und/oder E-Mail bereits vorhanden ist

Bitte nur warnen, dass dazu ein Eintrag vorhanden ist und man den gegebenenfalls ändern sollte aber auch als weiteren Eintrag zulassen

**Comment by j-dimension** [comment]
Notiz: auch bei Nutzung des Aktenanlage-Assistenten

**Comment by j-dimension** [comment]
Umsetzung in Verbindung mit #2440

**Comment by j-dimension** [comment]
Umsetzung: Berechnung einer durchschnittlichen Jaro Winkler-Distanz über 
- Name
- Vorname
- Strasse
- Hausnummer
- PLZ
- Ort
