### ISSUE TITLE
Emailzitat: Datum und Uhrzeit in Trennzeile

### ISSUE THREAD

**Issue by j-dimension** [jlawyerorg/j-lawyer-org#237]
https://www.j-lawyer.org/?topic=informationsgehalt-zwischen-beim-beantworten-einer-e-mail

Ist:
*** „Name, Vorname“ <name@firma.de> schrieb: ***

Soll:
Am 05.02.2019 um 15:18 schrieb Name, Vorname:

**Comment by Stimpi72** [comment]
Datums-/Zeitangabe immer aus Metadaten der zu beantwortenden E-Mail entnehmen.
