### ISSUE TITLE
Null bei  Aktendatenblatt [BUG] 

### ISSUE THREAD

**Issue by Cadzand1969** [jlawyerorg/j-lawyer-org#2370]
Seit dem letzten Update passier dieser Fehler.

**Comment by iradraconis** [comment]
Hoffentlich sind das keine echten Mandantendaten.

**Comment by j-dimension** [comment]
Im Beispiel enthalten (schematisch):

**Mandant 1:**
Otto Müller null

**Comment by j-dimension** [comment]
Dokument entfernt

**Comment by Cadzand1969** [comment]
Hallo Herr Kutschke, kann mit den unten angegeben Hilfen nichts anfangen. Benötige Ihre Hilfe.

 

Von: Jens Kutschke ***@***.***> 
Gesendet: Montag, 29. April 2024 23:36
An: jlawyerorg/j-lawyer-org ***@***.***>
Cc: Cadzand1969 ***@***.***>; Author ***@***.***>
Betreff: Re: [jlawyerorg/j-lawyer-org] Null bei Aktendatenblatt [BUG] (Issue #2370)

 

Closed #2370 <https://github.com/jlawyerorg/j-lawyer-org/issues/2370>  as completed via  <https://github.com/jlawyerorg/j-lawyer-org/commit/4f8c691cf32f99313a4521158ef716bb10d2c301> 4f8c691.

**Comment by j-dimension** [comment]
@Cadzand1969 die Änderungen am Ticket bedeuten dass es bearbeitet wurde und die Änderungen mit der kommenden Version bereitgestellt werden.

**Comment by Cadzand1969** [comment]
Vielen Dank!!!

 

Von: Jens Kutschke ***@***.***> 
Gesendet: Donnerstag, 2. Mai 2024 11:57
An: jlawyerorg/j-lawyer-org ***@***.***>
Cc: Cadzand1969 ***@***.***>; Mention ***@***.***>
Betreff: Re: [jlawyerorg/j-lawyer-org] Null bei Aktendatenblatt [BUG] (Issue #2370)

 

@Cadzand1969 <https://github.com/Cadzand1969>  die Änderungen am Ticket bedeuten dass es bearbeitet wurde und die Änderungen mit der kommenden Version bereitgestellt werden.
