### ISSUE TITLE
[TASK] Akten-Reihenfolge bei Person/Adresse

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#2372]
Nach welcher Regel werden eigentlich die Akten in der Übersicht bei einer Person sortiert?

![image](https://github.com/jlawyerorg/j-lawyer-org/assets/29924198/911c05b1-25e7-44fc-a66f-c4ac206cff05)

Aktenzeichen ist es nicht, Aktenbetreff ist es nicht, ...

Und könnte man das wahlweise nach Wahl sortierbar machen oder fest nach Aktenzeichen?

**Comment by j-dimension** [comment]
alt: sortierung nach rolle, aufsteigend
neu: sortierung nach erstellungsdatum der akte, absteigend
