### ISSUE TITLE
[BUG] bea: Nachricht ungelesen geht nicht mehr

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#2375]
Ich kann auf einmal nicht mehr eine Nachricht im beA-System auf ungelesen setzen!? Der Menüpunkt ist einfach weg.

![image](https://github.com/jlawyerorg/j-lawyer-org/assets/29924198/da92407c-effc-4fdf-b363-e2a7e473fa89)

**Comment by j-dimension** [comment]
Es gab einen solchen Menüpunkt nie, was daran liegt dass es die Schnittstelle bei der BRAK dafür gar nicht gibt. Du verwechselst das mit den Mails?

**Comment by stm9x9** [comment]
hm .. entweder das. Oder ich verwechsel das mit der neuen beA-App von der BRAK. Da geht das nämlich. Ich nehme mal naiv an, die App (wie auch die Drittanbieter-Apps?) greift per API aufs beA zu? Dann müßte das doch inzwischen gehen. Oder haben die sich da wieder was exklusives spendiert?

**Comment by j-dimension** [comment]
Das Toolkit für die Hersteller hat einen 

SetMessageReadByUserRequest

der aber kein Attribut true / false hat. Man kann damit nur als gelesen markieren. Einen

SetMessageUnreadByUserRequest

o.ä. gibt es nicht.

Was die App nutzt kann ich nicht sagen, scheinbar nicht die API, die auch von den Integratoren verwendet wird.
