### ISSUE TITLE
[FEATURE] Skripte: Durch Skripte entstandene Leerzeilen "löschen"

### ISSUE THREAD

**Issue by Linkki2021** [jlawyerorg/j-lawyer-org#2376]
Wenn ein Scriptausdruck kein / ein leeres Ergebnis generiert soll keine Leerzeile verbleiben.

Derzeit verbleibt eine Leerzeile. Was dazu führt, dass man zwar inhaltlich nicht ans Dokument ran muss, aber dafür formatierend.

Ggf. ist das ähnlich der "Intelligenz" der Platzhalter lösbar, die ein Leerzeichen einfügt, wenn zwei Platzhalter direkt zusammengeschrieben werden, nur andersherum. {{MANDANT_ANREDE}}{{MANDANT_NAME}} ergibt ja dann z.B. auch Herr Müller und nicht HerrMüller.

**Comment by j-dimension** [comment]
LibreOffice: 
umgesetzt für alle Fälle, wo der Scriptplatzhalter auf eigenem Absatz steht (Zeilenumbruch per Enter), nicht jedoch für Fälle die nur einen Zeilenumbruch enthalten (Strg+Enter)
