### ISSUE TITLE
[BUG] Wiedervorlage ohne Grund

### ISSUE THREAD

**Issue by papiertiger960ff** [jlawyerorg/j-lawyer-org#2380]
J-Lawyer verweigert bei mir die Erstellung von WIedervorlagen, wenn das Feld „Grund/Beschreibung“ nicht befüllt ist. Wenn ich auf „Hinzufügen“ klicke, verschwinden links einfach die Eingaben zur WVL, aber auf der rechten Seite erscheint keine WVL. Das passiert auch, wenn ich nur Leerzeichen eingebe.

ZUr Umgehung des Problems muss ich bei jeder WVL als Grund „Wiedervorlage“ eingeben, was ziemlich nervt, weil Wiedervorlagen bei mir nicht begründet werden.

**Comment by j-dimension** [comment]
Man kann in den Einstellungen eine Liste von WV-Gründen hinterlegen, sodass nichts getippt werden muss.

**Comment by j-dimension** [comment]
Ich plane nicht, WV ohne Grund zuzulassen.
