### ISSUE TITLE
[FEATURE] automatische Veraktung eingehender E-Mails

### ISSUE THREAD

**Issue by j-dimension** [jlawyerorg/j-lawyer-org#2385]
Umfang: 

- [x] Server überwacht Postfach
- [x] für jede Nachricht: Suche nach Aktenzeichen, Auswertung Absenderadresse
- [x] Anhangstypen / Dateitypen blacklisten
- [x] bei Eindeutigkeit: Mail zur Akte zuordnen
- [x] bei Eindeutigkeit: Etikett anbringen
- [x] bei Eindeutigkeit: aus Postfach löschen
- [x] bei mehreren relevanten Akten: prüfen ob nur eine davon nicht abgelegt ist, dann diese verwenden
- [x] bei fehlender Eindeutigkeit: keine Aktion, Mail verbleibt im Postfach
- [x] prüfen / optional: aktenübergreifende Ansicht als neuer Dialog: alle Dokumente mit bestimmtem Etikett, sortiert nach Erstellungsdatum; Aktionsmöglichkeiten: Aktenzuordnung ändern, Etikettvergabe - via #2170
- [x] Intervall: erster Start 3min nach Serverstart

Konfiguration:

- [x] zu überwachendes Postfach
- [x] bei Veraktung Etikett anbringen ja/nein, welches
- [x] Blacklist für nicht gewünschte Dateitypen

neue Aktionen in der Akte:

- [x] Dokument in andere Akte verschieben (dabei Dokumentetiketten beibehalten) - falls der Automatismus mal falsch liegt

**Comment by Linkki2021** [comment]
Gefällt mir. Nur der Punkt bei fehlender Eindeutigkeit: lässt man es dann nicht lieber im Postfach? Aber natürlich kann ich mir auch einfach eine Posteingangs-Dummy-Akte anlegen.

**Comment by j-dimension** [comment]
> Gefällt mir. Nur der Punkt bei fehlender Eindeutigkeit: lässt man es dann nicht lieber im Postfach? Aber natürlich kann ich mir auch einfach eine Posteingangs-Dummy-Akte anlegen.

In der Regel wird man ja dann ein Postfach anbinden, das Weiterleitungen - ggf. sogar aus mehereren Postfächern - empfängt und somit evtl. gar nicht im Client eingebunden ist. 

Vielleicht ermöglicht man beide Varianten.

**Comment by j-dimension** [comment]
![grafik](https://github.com/jlawyerorg/j-lawyer-org/assets/3729754/28b29ac7-a1f9-425c-add8-2591c89f7a76)
