### ISSUE TITLE
Unklare Aufforderung während Linux-Installation

### ISSUE THREAD

**Issue by MC-1984** [jlawyerorg/j-lawyer-org#2386]
`Welche Komponenten sollen installiert werden?
X: j-lawyer.org Server [*1]
2: j-lawyer.org Vorlagenpaket
3: j-lawyer.org Backupmanager
(Um die Beschreibungen einer Komponenten anzuzeigen, geben sie eines von *1 ein)
Bitte geben sie eine durch Kommas separierte Liste der ausgewählten Werte an oder drücken Sie [Eingabe] um die Vorauswahl zu akzeptieren:
[2,3]`

Ich finde die Beschreibung hier missverständlich. Wenn ich es richtig verstehe, wird der Server ohnehin installiert und mit 2,3 können nur das Vorlagenpaket und der Backupmanager installiert werden. Wäre dann nicht 1,2 leichter nachvollziehbar? Auch habe ich es nicht geschafft mir die Beschreibung anzeigen zu lassen. Vielleicht liegt das aber auch an mir und alle anderen verstehen es sofort...

Viele Grüße

Markus

**Comment by j-dimension** [comment]
Mit Stern gekennzeichnete Komponenten müssen installiert werden, weitere sind optional. die Voreinstellung [2,3] sorgt dafür, dass alle optionalen mit installiert werden.
