### ISSUE TITLE
Sortierung und der Fokus in der Dateiliste unter Scans ändert sich

### ISSUE THREAD

**Issue by bjk00** [jlawyerorg/j-lawyer-org#239]
Die Sortierungsreihenfolge im Scannerordner wird durch eine Aktualisierung auf "Älteste zuerst" zurückgesetzt.
Dies passiert sowohl bei einer manuellen Aktualisierung über den "Aktualisieren"-Button als auch nach einer automatischen Aktualisierung nach Zuordnung eines Dokuments zu einer Akte.

1. Sortierung im Scannordner auf "Neuste zuerst" stellen (klick auf "geändert" Spaltenfeld, Pfeil zeigt nach unten)
2. Klick auf den Aktualisieren-Button setzt die Sortierreihenfolge zurück auf "Älteste zuerst"

und 

1. Sortierung im Scannordner auf "Neuste zuerst" stellen 
2. gewünschte Datei mit Klick markieren
3. "Datei der Akte zuordnen" auswählen und Dateinamen bestätigen.
   -> zugeordnete Datei verschwindet aus der Dateiliste und die Markierung in der Dateiliste springt zum ersten Eintrag
4. ca 15s warten, dann stellt sich die Sortierreihenfolge zurück auf "Älteste zuerst" 

Das die Markierung in der Dateiliste nach jeder Zuordnung wieder auf den Anfang der Liste springt, ist bei einer langen Dateiliste auch sehr nervig, da man immer wieder zur alten Position zurück scrollen muss.
Intuitiver wäre es die Markierung auf die nach Sortierreihenfolge nächste Datei zu setzen. Oft hat man noch die Scannreihenfolge im Kopf und will an diesem Punkt weiter machen.
Die Markierung springt auch auf den Anfang zurück, wenn der Dialog "Datei umbenennen" in Punkt 3 nicht bestätigt sondern abgebrochen wird.
Auch dann muss man wieder zurück zur alten Position scrollen.

**Comment by j-dimension** [comment]
In 1.10 sind die Tickets #163 und #170 umgesetzt, bitte nach Release nochmals testen - ich schliesse dieses hier als Duplikat.
