### ISSUE TITLE
[BUG] Parsefehler in Finanzen

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-org#2393]
![grafik](https://github.com/jlawyerorg/j-lawyer-org/assets/37142896/3a6d871f-da29-4ecd-863a-33cd3b992fd6)

Meine Frau hat sich verschrieben, dann die Position löschen wollen und jetzt ist die Fehlermeldung da, die sich nicht abstellen lässt.

**Comment by Mucki526** [comment]
Wenn man auf Fehlerfenster schließen klickt, ändert sich die Anzeige darunter zwischen Menge = 10 und Menge = 0 und umgekehrt. Mehr passiert nicht mehr...

**Comment by Mucki526** [comment]
![grafik](https://github.com/jlawyerorg/j-lawyer-org/assets/37142896/0c9316d9-0f16-4edd-91d0-9a15601e970c)
nach dem Klick....

**Comment by Mucki526** [comment]
[access_log.log](https://github.com/jlawyerorg/j-lawyer-org/files/14882982/access_log.log)
hier das server log dazu,

**Comment by j-dimension** [comment]
Bitte einen Systemreport per Mail.
