### ISSUE TITLE
[FEATURE] "Assistent Ingo"

### ISSUE THREAD

**Issue by j-dimension** [jlawyerorg/j-lawyer-org#2395]
**Generelle Anforderungen**

- muss auf anderem Gerät laufen und somit remote genutzt werden können
- muss eine höhere Updatedynamik erlauben, oder gar Modelle per einfacher Konfiguration austauschbar machen
- muss multithreading-fähig sein
- muss "offline" funktioneren (also keinerlei Daten an weitere Server durchreichen)

**Anwendungsszenarien (nach Priorität, absteigend)**
- Transkription
- Übersetzungen
- zusammenfassen
- Antwort auf Nachricht / Schriftsatz entwerfen
- frei formulierbarer Prompt
- mit eigenem Dokument "chatten"

**Backend für Assistent Ingo**

- [x] RESTful API
- [x] Security (falls auf öffentlichem Server gehostet)
- [x] Requeststruktur "neue Anfrage": 
1 Prompt (optional)
1..n Kontext-/Eingangsdaten beliebiger Länge, plain text oder Base64-kodierte Binärdaten samt Dateiname (verpflichtend)
1 Anfragetyp (bspw. "summarize", "transcribe", ...) (verpflichtend)
1 Modellart (optional)
- [x] Responsestruktur "neue Anfrage": 
1 Request-ID
1 Status (Fehler, Erfolg) (Erfolg=Anfrage erfolgreich angenommen)
- [x] Requeststruktur "Anfrageergebnis": 
1 Request-ID
- [x] Responsestruktur "Anfrageergebnis": 
1 effektiv genutzter Prompt (optional)
1 Anfragetyp (bspw. "summarize", "transcribe", ...) (verpflichtend)
1 genutzte Modellart (verpflichtend)
1 Metriken (Ausführungszeit, ...)
1 Status (Fehler, Erfolg / abgeschlossen, in Arbeit)
1 Abarbeitung in % (optional, ggf. nicht immer verfügbar)
1 Statusnachricht (zur Anzeige in GUI)
1..n Ergebnisse: plain text oder Base64-kodierte Daten mit Dateinamen
- [x] muss technologieagnostisch sein - es sollten sich beliebige Skripts und Binaries rufen lassen
- [x] Konfiguration: für jede Kombination von "Anfragetyp + Modellart" (Modellart optional) muss es eine Konfiguration geben:
Kommandozeile (samt Platzhalter für die Eingangsdaten)
- [x] XML-Konfiguration für Ausführung von Requests
- [x] Exekutoren / Prozessoren für die Ausführung von Requests

**Integration im j-lawyer.org Client**

"Assistent-Ingo"-Buttons an verschiedenen Stellen im Client
- [x] generische Filterung der Assistenten-Funktionen, je nachdem was der Client in einem gewissen Kontext benötigt
- [x] E-Mail-Versand
- [x] Soundplayer
- [x] Diktierdialog
- [x] ~~E-Mail-Posteingang, Kontextmenü auf Nachricht~~
- [x] E-Mail-Posteingang, Nachrichtenansicht
- [ ] Akte, Dokumentenvorschau
- [x] Akte, Kontextmenü auf Dokumente
- [ ] Auswahl alternativer Prompts bei E-Mail-Beantwortung (Prompt sehr abhängig vom Charakter der zu beantwortenden Mail)

Prompting:

- [x] Unterstützung für eigene Prompts
- [x] Unterstützung von Platzhalter für dynamische Befüllung von Prompts

Ausführung der Assistenten-Aufrufe
- [x] Konfiguration des Assistenten-Backends (REST-Endpunkt, Nutzer, Passwort)
- [x] Assistentendialog, Requests an das Assistenten-Backend (siehe Eingangsparameter für "neue Anfrage"), Folgeaktion
- [x] Folgeaktion implementieren: neue E-Mail mit Ergebnisdaten
- [x] Folgeaktion implementieren: Dokumente zur Akte speichern
- [x] Folgeaktion implementieren: Chatfenster
- [x] Folgeaktion implementieren: Ergebnis anzeigen
- [ ] Folgeaktion implementieren: keine (bspw. für langlaufende Aktionen)

evtl. zentrale Ansicht von Anfragen und deren Status (bspw. für langlaufende Aktionen)
- [ ] (noch zu definieren)

**Modelle**

- [x] Modelle für die genannten Anwendungsszenarien evaluieren
- [x] Aufrufe dokumentieren
- [ ] Limitationen dokumentieren

**"Assistent Ingo"-Installation**

- [x] ~Dokumentation~
- [x] ~ggf. Installer~

**Comment by LazyGuy21No** [comment]
so f*cking love it!

**Comment by Dickmaulruessler** [comment]
Es klingt cool!
Aber, sorry, ich verstehe es noch nicht, kannst du die Anwendungsfälle bitte noch einmal anders beschreiben?

**Comment by LazyGuy21No** [comment]
Einige Überlegungen:

1. KI könnte wie virtuelle:r Benutzer:in daher kommen.  
2. es sollte möglich sein, KI auf einer anderen Machine zu betreiben (Beefy Server an einem anderen Standort); rechtlich, scheint mir auch ein Einsatz einer KI eines kommerziellen Anbieters mit Verarbeitungsvertrag innerhalb der EU denkbar (bietet aktuell OpenAI+Microsoft-Cloud). Das berührt zwar ethische Fragen, ab in einigen Monaten machen es sowieso alle.
3. Persistenz zu Akte, Kanzlei und Mandant:in: Die KI sollte ein persistentes Priming (via prompt shaping?) haben. 
4. Scheduling: KI arbeitet Aktionen ohne Priorität selbständig ab,  _wenn_
 a. die Arbeits-Last gering ist (nachts? UX) oder
 b. massenhaft Solarstrom zur Verfügung steht (tags!), oder
 c. wenn wir sowieso heizen müssen (tagsüber im Winter). 
Steuerung über HomeAssistent wäre ein Knaller ("eigentlich wäre die Arbeit jetzt zu erledigen, aber in 40 Minuten ist die Sonneneinstrahlung absehbar so intensiv, dass wir ohnehin Überschuss ins Netz speisen würden, also warten wir noch ein wenig mit der Arbeit).

5. KI kann mit dem Mandanten chatten und fragen zum Verfahrensstand beantworten oder Termine vereinbaren.
6. KI braucht einen anderen Namen

Usecases: 
Termine eintragen und bei Terminskollisionen eine Verlegungsbitte an das Gericht vorbereiten, wäre für mich schon ein killer USP.

**Comment by RobertT01** [comment]
Klingt genial. 
Könnte man die KI auch mit der Bibliothek verknüpfen, so dass sie Verschläge für Rechtssprechung für den Inhalt bestimmter Schriftsätz macht? Wie eine Art Abgleich

**Comment by RobertT01** [comment]
Falls die die KI Schriftsätze die man schreibt, metlesen könnte, könnte diese bei Einfügen einer Anlage gleich dazu nachfragen und die Anlage entsprechend beschriften.

Beispiel: Ich schreibe für einen Vortrag

Beweis: Schriftsatz vom ..... Anlage K1 

und die KI fragt mich, ob ich den Schriftsatz gleich als PDF mit der Kezeichnung  "Anlage K1" im Dateinamen und auf der Anlage selbst im Aktenbestand hinterlegen will. D.h. die KI sucht den entsprechenden Schriftsatz anhand meiner Angaben raus und wenn ich diesen als richtige Anlage bestätige, schriftet die KI den Schriftsatz und legt ihn als pdf und als Anlage ab.

**Comment by j-dimension** [comment]
[v](https://github.com/jlawyerorg/j-lawyer-ai)

**Comment by j-dimension** [comment]
Platzhaltersupport für Prompts umgesetzt, bspw. 

`Du bist {{USER_AN}}. Antworte freundlich auf diese E-Mail und und erfrage einen Terminvorschlag für die kommende Woche. Bleibe beim förmlichen "Sie". Biete für Abstimmungen ein Telefonat an und nenne die Telefonnummer {{USER_TELNR}}. Bitte bei Rückfragen um Angabe des Aktenzeichens {{AKTE_ZEICHEN}}. Unterschreibe Deine Nachricht mit {{USER_AN}}, {{USER_FKT}}:

`

**Comment by j-dimension** [comment]
neuer Platzhalter für Übernahme eines Ingo-Textes in eine Vorlage: 

`{{INGO_TEXT}}`

**Comment by j-dimension** [comment]
Auch wenn hier noch einiges zu tun ist, schließe ich dieses Ticket. Für die iterative Weiterentwicklung sollte es spezifische und "kleinteiligere" Tickets geben.
