### ISSUE TITLE
Alte Dokumenten Ettikette löschen

### ISSUE THREAD

**Issue by mmellenthin** [jlawyerorg/j-lawyer-org#2404]
Auf dem Desktop werden gelöschte Dokumenten-Ettikette bei der Sortierauswahl FEld unten links  2. Zettel recht neben "Meine Ettiketten" noch in der Liste angezeigt, obwohl gelöscht und kein Dokument mit diesem Ettikett (makiert)  mehr existiert.

**Comment by j-dimension** [comment]
Auch nachdem der Aktualisieren-Knopf genutzt wurde?

Welche Version ist im Einsatz?

**Comment by mmellenthin** [comment]
Ja natürlich, auch nach aktualisieren.

server 2.6.0.17
Client 2.6.0.2

**Comment by j-dimension** [comment]
Das kann ich nicht reproduzieren.
Und bei Klick auf das Dokumentetikett? Zeigt das Dokument dann das Etikett noch an?

**Comment by mmellenthin** [comment]
Bitte Emailadresse dann sende ich Bilder.

**Comment by j-dimension** [comment]
gern direkt an die Impressumsadresse

**Comment by j-dimension** [comment]
Solange mindestens ein Dokument existiert, das ein solches Etikett hat, ist das Etikett auf dem Desktop als Filter auswählbar. Das schließt auch Dokumente in abgelegten Akten ein.

**Comment by mmellenthin** [comment]
Wie findet man abgelegte unerledigte Ettiketten?

**Comment by j-dimension** [comment]
Aktivierte Etiketten in abgelegten Akten findet man über die Aktensuche, gefolgt von einer dortigen Suche nach Etikett im Tab "Dokumente".
