### ISSUE TITLE
Nach Ratenzahlung durch Mdt - Saldo - 0 € (kleiner bug)

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-org#2417]
Die Rechnung wurde in zwei Raten bezahlt vom Mdt. Das sieht so aus im Belegbereich

![grafik](https://github.com/jlawyerorg/j-lawyer-org/assets/37142896/2f4f1721-1c05-4eaf-a805-ec82c92b3b56)

Das -0 passt nicht....

**Comment by j-dimension** [comment]
Duplikat von #2322
