### ISSUE TITLE
[FEATURE] Platzhhalter für Hausnummer

### ISSUE THREAD

**Issue by RobinDev03** [jlawyerorg/j-lawyer-org#2418]
Derzeit fehlt ein Platzhalter bei Mandat & Gegner für die Hausnummer der Adresse

**Comment by clvnsch** [comment]
Der Platzhalter für die Hausnummer ist: _HAUSNR
also z.B.
{{MANDANT_HAUSNR}} oder {{GEGNER_HAUSNR}}

**Comment by j-dimension** [comment]
So ist es. Danke @clvnsch !
