### ISSUE TITLE
[FEATURE] Rechnungsausgleich + Aktenkontobuchung vereinfachen

### ISSUE THREAD

**Issue by j-dimension** [jlawyerorg/j-lawyer-org#2424]
- Button in Belegübersicht: "als bezahlt markieren", bei Klick:
- Rechnung als bezahlt markieren
- Aktenkontobuchungsdialog öffnen: Rechnung, Kontakt, Zahlungseingang sind bereits voreingetragen
- ist schon eine Teilzahlung erfolgt: Differenz berechnen, automatisch eintragen
- bestätigen

**Comment by stm9x9** [comment]
ich kenne da von easybill noch eine ähnliche Funktion, die sehr praktisch ist:

Da kann man einen Betrag kleiner des Rechnungsbetrags eingeben und angeben, daß dies keine Teilzahlung ist, sondern als Abschlußzahlung akzeptiert wird und der Rest "abgeschrieben" wird.

![image](https://github.com/jlawyerorg/j-lawyer-org/assets/29924198/7b0e0aad-da73-41f5-a7d3-363e3c357326)

Das kann bei einem abweichenden Kostenfestsetzungsbescheid sein, den man aktzeptiert, oder wie hier bezeichnet, ein Skonto.
