### ISSUE TITLE
Duplex+Zusatzleistung mit EPOST geht nicht (2.6.1.)

### ISSUE THREAD

**Issue by LazyGuy21No** [jlawyerorg/j-lawyer-org#2430]
In 2.6.1. lässt sich **Duplex** nicht kombinieren mit **irgendwelchen Zusatzleistungen** (Einschreiben). Über die EPOST BusinessBox  geht das Problemlos.

**Comment by j-dimension** [comment]
Ich kann hier nur den Support kontaktieren, das Verhalten der API des Anbieters kann ich nicht beeinflussen.

**Comment by j-dimension** [comment]
Support kontaktiert

**Comment by j-dimension** [comment]
Support: 

"dies sind produktive Vorgaben/Limitierungen des Druckzentrums zu Einschreiben für den Hybriden Briefversand, näheres kann ich dazu aktuell nicht sagen."

**Comment by Dickmaulruessler** [comment]
Dass das eine mit dem anderen in Kombination nicht möglich ist, ist ja nichts worauf man so kommen kann - da ziemlich unlogisch (oder versteht das wer?)
Man sucht sich bei der Fehlersuche tot - wenn man nicht diesen Eintrag hier liest...

Daher Vorschlag:
Evtl. konkrete Fehlermeldung innerhalb von j-lawyer wenn o.g. Kombi geklickt wird?
Oder irgendein anderer Fehlerhinweis?

**Comment by j-dimension** [comment]
> Evtl. konkrete Fehlermeldung innerhalb von j-lawyer wenn o.g. Kombi geklickt wird?

Da bin ich kein Fan von, weil ich dann die Logik, die es in den Servern der DP gibt, doppeln würde. Unterstützt die Post das irgendwann, würde der j-lawyer das immer noch verhindern.

**Comment by Dickmaulruessler** [comment]
Dann aber wenigstens das Ticket mit milesston "roadmap" offen lassen bis hier jemand meldet, dass es funktioniert?

**Comment by LazyGuy21No** [comment]
Macht mich immernoch irre: die epost Box Business macht die Kombination völlig problemlos; die wird da wohl auch nur an das Druckzentrum schicken

**Comment by j-dimension** [comment]
Gern ebenfalls an den Support wenden, ich werde das nicht im Monatsrhythmus tun.

**Comment by LazyGuy21No** [comment]
Kannst Du mir einen Kontakt von denen per E-Mail schicken?

**Comment by j-dimension** [comment]
Den direkten Kontakt für Entwickler darf(?) ich nicht rausgeben. Ich würde einfach das produktspezifische Kontaktformulare nutzen: https://www.deutschepost.de/de/e/epost/geschaeftskunden/partner/business-api/kontakt.html
