### ISSUE TITLE
[BUG] Gesamtzahl der Seiten des PDFs in 2.6.1.

### ISSUE THREAD

**Issue by LazyGuy21No** [jlawyerorg/j-lawyer-org#2432]
Die Anzeige ist optisch unglücklich (und es brauch m.E. auch "gesamten x" nicht, weil 1/2 aussagekräftig genug ist.)
<img width="261" alt="image" src="https://github.com/jlawyerorg/j-lawyer-org/assets/56734761/5b825f24-688e-41f9-80f1-b7a4b3ab2037">

**Comment by j-dimension** [comment]
Die "gesamt"-Angabe wird für #2432 benötigt. Das Durchscrollen bedingt dass aus dem PDF Grafiken extrahiert und skaliert werden müssen. Das wird bei einem 500 Seiten-PDF und schwacher Hardware nicht funktionieren, deshalb gibt es eine Deckelung bei 20. Dort wäre die Ausgabe dann bspw. 

"3/20  gesamt: 500"
