### ISSUE TITLE
[BUG] Langsame Darstellung bei Änderung des Zoomsfaktors bei der PDF-Vorschau

### ISSUE THREAD

**Issue by socram70** [jlawyerorg/j-lawyer-org#2433]
**Describe the bug / Fehlerbeschreibung**
Langsame Darstellung bei Änderung des Zoomsfaktors bei der PDF-Vorschau

**To Reproduce / Schritte zum Nachvollziehen**
Beim Verwenden des Zoomreglers oben rechts bei der Vorschau bei PDF-Dokumenten im Reiter "Dokumente" ist die Reaktion sehr stark verzögert (drei Sekunden). Gleiches gilt für den Button "auf Seitenhöhe einpassen". Hier muss mehrere Sekunden auf eine Reaktion gewartet werden. Die Dokumentengröße des Testdokuments sind lediglich 150 KB.

**Expected behavior / Erwartetes Verhalten**
Es sollte eine schnellere Reaktion erfolgen.

**Screenshots**
![grafik](https://github.com/jlawyerorg/j-lawyer-org/assets/60073801/37009359-e224-4098-9225-74b41047359c)

**Environment / verwendete Umgebung:**
 - OS / Betriebssystem: Windows 11 (10.0.22631.3527)
 - j-lawyer.org Version: Client: 2.6.1.0 - Server: 2.6.1.6 (Ubuntu 24.04)

**Comment by socram70** [comment]
Das Dokument hat zwei Seiten. Der Client ist ein AMD Ryzen 5 3600, also nicht sonderlich langsam. Testweise habe ich die Software auf einem MacBook Pro M2 installiert. Hier ist es eine Ecke schneller, das Neuskalieren dauert aber auch etwa eine Sekunde.

**Comment by j-dimension** [comment]
Ich habe jetzt sowohl die initiale Darstellung als auch das Zoomen nochmal überarbeitet

- 200 DPI statt 300 DPI (bringt tatsächliche Beschleunigung)
- Multithreading (bringt gefühlte Beschleunigung, da die erste(n) Seite(n) bereits dargestellt wird/werden, während der Rest noch gerendert wird)

Ein Ändern des Zooms ist aber erst möglich, nachdem alle Seiten initial dargestellt wurden.

**Comment by j-dimension** [comment]
So schaut das jetzt auf einem Intel Core i7 aus 2017 aus:

https://github.com/jlawyerorg/j-lawyer-org/assets/3729754/83391cd6-37a0-43a0-9ef2-5b2f958c08ab
