### ISSUE TITLE
[BUG] MacOS System-Applikationen als externe Programme auswählen

### ISSUE THREAD

**Issue by LazyGuy21No** [jlawyerorg/j-lawyer-org#2436]
System-Applikationen (/System/Applications/Preview.app) lässt sich nicht als "externe App" zur Dateiöffnung auswählen (der Öffnen-Dialog zu "ausführbare Dateien" betritt den App-Folder, statt den Pfad zu übernehmen)
<img width="543" alt="image" src="https://github.com/jlawyerorg/j-lawyer-org/assets/56734761/920c0221-b21f-4f21-a2d8-e6ece1ef7ae0">

**Comment by j-dimension** [comment]
Die Doku hat einen Abschnitt dazu. Bitte mal schauen, bin gerade unterwegs.

**Comment by iradraconis** [comment]
Ich habe mal das aus der Doku genommen: 
<img width="593" alt="Bildschirmfoto 2024-05-07 um 20 04 51" src="https://github.com/jlawyerorg/j-lawyer-org/assets/71747937/6255ae2e-edac-4f22-b2f1-08ac56a6ce5b">

**Comment by j-dimension** [comment]
Danke @iradraconis

**Comment by j-dimension** [comment]
nach dem -a folgt der englischsprachige Name der Anwendung
