### ISSUE TITLE
[BUG]  Vorschau: 2.6.1 => PDF Vorschau - das gesamte Dokument ist nicht verfügbar

### ISSUE THREAD

**Issue by iradraconis** [jlawyerorg/j-lawyer-org#2438]
Weiter als Seite 20 kann ich nicht blättern oder scrollen. 

![grafik](https://github.com/jlawyerorg/j-lawyer-org/assets/71747937/e51cd9d1-1682-47f9-b715-38e9e20909ff)

Ich nutze die gestern bereitgestellte Vorschauversion. 
Systembericht kommt per Mail

**Comment by j-dimension** [comment]
Das ist bewusst so implementiert:
https://github.com/jlawyerorg/j-lawyer-org/issues/2412#issuecomment-2067808860

Größere Dokumente müssen in einem externen Viewer geöffnet werden.

**Comment by iradraconis** [comment]
Achso

**Comment by j-dimension** [comment]
Man könnte irgendeine Art Konfiguration einbauen, dann kann gute Hardware mehr darstellen. Ich meine dass mit 20 Seiten sehr viele Fälle abgedeckt sind.

**Comment by j-dimension** [comment]
Alternativ könnte man - abhängig von der Scrollposition - entladen und neu laden. Dann würde ich aber einen ausgewachsenen PDF-Viewer bauen und es stellt sich die Frage nach Aufwand / Nutzen.

**Comment by iradraconis** [comment]
Nein, alles gut, ich hatte mit dem Verhalten nur nicht gerechnet. Es macht schon Sinn, den Standard Viewer zu öffnen, schon wg. der Bearbeitungsmöglichkeiten. Du hast recht, die meisten Fälle einfacher Schreiben dürften mit 20 Seiten abgedeckt sein. Und die Möglichkeit nun scrollen zu können ist spitze! Kannst gern schließen hier.

**Comment by stm9x9** [comment]
Könnte vielleicht eine letzte Seite "Vorschau endet hier ... bitte extern öffnen" angefügt werden in der Vorschau?

**Comment by j-dimension** [comment]
Habe Icon + Tooltip hinzugefügt, wenn eine solche Situation eintritt.
