### ISSUE TITLE
Funktion "zusätzlich als PDF ablegen" überdenken

### ISSUE THREAD

**Issue by Dickmaulruessler** [jlawyerorg/j-lawyer-org#2439]
Die Funktion "zusätzlich als PDF ablegen" erstellt - sofort nach dem ersten Öffnen - eine (dann praktisch nur aus der Dokumentvorlage bestehende, also eine nahezu **leere**) PDF. 

Sorry, aber ich verstehe den Sinn nicht. 
Meiner Meinung nach wäre es sinnvoll, wenn es das fertige .odt-Dokument ganz am Ende als PDF ablegen würde. Wie das aber technisch realierbar sein soll, weiß ich nicht. 

Was steckt dahinter? Ist das ein Bug (so meine Wahrnehmung)?

Unabhängig davon: Würde das nicht eher weiter rechts zu "Erstellen und Öffnen" gehören? Ich finde es gehört eher nicht zum Dateinamen.

![kfkdaösdfdsfsdf](https://github.com/jlawyerorg/j-lawyer-org/assets/46451749/f28df3ae-42f9-4130-9db3-5aae0d530cf1)

Ganz unabhängig von Allem: 
Schönen Vatertag @j-dimension !

**Comment by clvnsch** [comment]
Naja, das ist (glaube ich) eher für den Fall von Vorlagen, welche keine weitere Bearbeitung benötigen. Zum Beispiel sowas wie eine Vollmacht wo nur die Daten des Mandanten eingetragen werden, sodass diese direkt nach der Erstellung auch als PDF vorliegt.

**Comment by j-dimension** [comment]
Mit Formularen hat das nichts zu tun. Die Funktion kann überall dort genutzt werden, wo eine Nachbearbeitung nicht notwendig ist. Nutzt mal die Skriptfunktionen in Vorlagen, kann man viele Fälle so weit automatisieren, dass eine Bearbeitung des entstehenden Dokuments für Standardfälle nicht notwendig ist.

**Comment by j-dimension** [comment]
Ich find's eigenltich beim Dateinamen gut aufgehoben. Rechts sind ja alles fachliche Daten, links durchaus technische.

**Comment by stm9x9** [comment]
ich finde irgendwie auch, daß es mehr zu den Speicher-Buttons gehört, geht ja ums zusätzliche Speichern als pdf
