### ISSUE TITLE
Sprachmemo-Funktionalität mit macOS Sonoma

### ISSUE THREAD

**Issue by j-dimension** [jlawyerorg/j-lawyer-org#2441]
Sprachmemo-Funktionalität mit macOS Sonoma - scheitert wg. fehlender Berechtigungen (Berechtigung wird nicht beim Betriebssystem angefragt)

_Originally posted by @j-dimension in https://github.com/jlawyerorg/j-lawyer-org/issues/2416#issuecomment-2105180979_

**Comment by j-dimension** [comment]
https://stackoverflow.com/questions/78427142/java-application-not-recording-from-microphone-when-packaged-using-install4j/78428362#78428362

**Comment by j-dimension** [comment]
Info.plist braucht einen Eintrag, der erklärt WARUM die App Mikrofon-Zugriff benötigt: 

<key>NSMicrophoneUsageDescription</key>
<string>This app requires access to the microphone for recording audio.</string>

install4j, "Launchers", Einstellungen des Launchers öffnen, "macOS options", "customize plist file" und dort die obigen Zeilen einfügen.

**Comment by j-dimension** [comment]
@iradraconis ich habe mal einen neuen und signierten Installer für Apple Silicon im Vorschaubereich hochgeladen, in der Hoffnung dass das Mikro dann genutzt werden kann. Könntest Du das bei Gelegenheit mal testen und Rückmeldung geben?

Auf meinem Testgerät hat die Installer-Anpassung geholfen.

Danke!

**Comment by iradraconis** [comment]
An drei Geräten ausprobiert, funktioniert.

**Comment by j-dimension** [comment]
Sehr gut! Das wär eine harte Nuss.
