### ISSUE TITLE
Verlorene Dokumentspeicherung

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-org#245]
Mit dem Update wg. der Libre-Office Speicherautomatik ist die Gefahr eines Verlustes eines Dokuments trotz Speicherung m.E. nicht völlig ausgeschlossen. Wenn man in einer Akte ist und einen Schriftsatz bearbeitet, dann - während das Dokument geöffnet ist in eine andere Akte wechselt - z.B. weil ein Mandant anruft - und dann zurückwechselt in die ursprüngliche Akte werden weitere Speicherungen von Änderungen des geöffneten Dokuments nicht mehr übernommen. Ich habe heute ein (zum Glück ausgedrucktes Dokument) aus der Zeit vor dem Update bzgl. des Speicherfehlers neu abtippen müssen - 8 Seiten... zum Glück habe ich dabei eine Sicherung (bak) jeder Speicherung zusätzlich gesondert abgespeichert ("Speichern unter") und konnte es wiederherstellen, nachdem nach dem beschriebenem Wechsel der Akte und Rückkehr in die Akte des bearbeiteten Dokuments -trotz workaround-update - Änderungen nicht übernommen wurden. Akte wechseln bei geöffnetem Dokument ist somit nicht ratsam, außer man liebt Sysiphos-Arbeiten. Aber man muss oft wegen z.B. Anruf- Mandant in anderer Sache kurz die Akte wechseln um z.B. eine Telefonnotiz zu machen und kehrt dann zur Akte zurück, die man bearbeitet. Kurz - Die Verbindung des geöffneten Dokuments zur gerade nicht aktiven Akte darf nicht abreißen solange das Dokument geöffnet ist und beim Schließen / Speichern des Dokuments muss der letzte Stand in die richtige, wenn auch gerade nicht aktive Akte gespeichert werden.**

**Comment by j-dimension** [comment]
Nein, das kann ich so nicht bestätigen. Die Überwachung der Dokumente läuft im Hintergrund, die Navigation innerhalb der Anwendung hat keinen Einfluss darauf.

Was nicht gemacht werden sollte ist besagtes "Speichern unter...". Das ist aber unabhängig von j-lawyer.org: hat man ein Dokument_A.odt auf Platte und bearbeitet und speichert, so wird Dokument_A.odt gespeichert / geändert. Sobald man "Speichern unter" nutzt, entsteht ein neues, von Dokument_A.odt völlig unabhängiges Dokument_B.odt.

Daumenregel daher: Speichern, nicht Speichern unter.

Wenn man testweise sichergehen will, ob eine Speicherung in der Akte angekommen ist, so kann man entweder (a) den Dokumentmonitor nutzen (Menü "?") oder (b) die Dokumentvorschau in der Akte verwenden (ggf. kurz ein anderes Dokument anklicken und zurückwechseln, damit die Vorschau neu geladen wird.).

Oder habe ich das Szenario falsch verstanden? Ich lasse das Ticket solange offen.

**Comment by Mucki526** [comment]
Danke Dir - ich verstehe das nur teilweise, weil von mir der Mechanismus Temporäre Datei von Libreoffice und speichern /übertragen derselben in J-Lawyer noch nicht wirklich verstanden / durchdacht wurde). Soll das heißen, dass sobald ich "speichern unter" (B.odt erzeugen) mache, ich danach beim "Speichern" von A.odt alle weiteren Änderungen nicht mehr in den J-Lawyer Dokumentenordner bekomme?  D.h. ich müsste die Datei jedesmal danach schließen und aus dem J-Layer Dokumentenordner neu öffnen oder neu importieren. Es fehlt ja IMHO die Möglichkeit, direkt auf den J-lawyer Dokumentenordner der Akte zuzugreifen. Der Ordner ist ja im Windows-Explorer nicht direkt ansprechbar, weil die Dateien in der SQL-Datenbank liegen (liegen die da, ja wo liegen die Dateien eigentlich...??). Wenns speichern mal nicht geklappt hat und man es merkt, bleibt im Moment ja nur, die a.odt als b.odt abzupeichern und neu nach j-lawyer zu importieren...

Und zum Tipp Dokumentenmonitor oder Dokumentenvorschau (meist fehlt ja nicht der Anfang des Dokuments sondern es ist schon mehr als eine Seite geschrieben, hilft also nicht wirklich - warum erfolgt eigentlich nicht überall (z.B. auch e-mail, scanordner) automatisch beim Öffnen ein Refresh der Ansicht - gibt´s da schon ein Ticket für die Zukunft?). 

Ich werde jetzt mal gezielt die Szenarien durchspielen was wann wie speichert und wann nicht, denke ich...

**Comment by j-dimension** [comment]
> Soll das heißen, dass sobald ich "speichern unter" (B.odt erzeugen) mache, ich danach beim "Speichern" von A.odt alle weiteren Änderungen nicht mehr in den J-Lawyer Dokumentenordner bekomme?

Sobald Du "speichern unter" (B.odt erzeugen) machst, wird ja A.odt geschlossen. Insofern landen alle Deine Änderungen in B.odt, nicht aber in A.odt. 
Du kannst natürlich dann Deine B.odt per Drag&Drop wieder in die Akte ziehen. Oder A.odt erneut aus der Akte öffnen und dort weiterarbeiten.

> Und zum Tipp Dokumentenmonitor oder Dokumentenvorschau (meist fehlt ja nicht der Anfang des Dokuments sondern es ist schon mehr als eine Seite geschrieben, hilft also nicht wirklich

Im Dokumentenmonitor siehst Du ob das Dokument in der Überwachung / geöffnet ist, und auch wann das Dokument zuletzt an den Server übertragen / gespeichert wurde. Die Dokumentvorschau wird mit jedem Speichern auf dem Server neu generiert, sollte also auch neu geschriebenen Text bereits anzeigen, wenn das Dokument noch offen und in Bearbeitung ist. D.h. nach einem Klick auf "Speichern" landen die Änderungen ein paar Sekunden später auf dem Server und die Dokumentvorschau wird nach erneutem Anklicken die neu geschriebenen Inhalte anzeigen.

> warum erfolgt eigentlich nicht überall (z.B. auch e-mail, scanordner) automatisch beim Öffnen ein Refresh der Ansicht - gibt´s da schon ein Ticket für die Zukunft?).

Der Scanordner aktualisiert sich zyklisch, sofern Änderungen anliegen. Wenn es bestimmte Refresh-Wünsche gibt: gern ein Ticket erstellen. An vielen Stellen geschieht es automatisch, an anderen Stellen nicht.

**Comment by Mucki526** [comment]
o.k. also ist "speichern unter" keine wirkliche Option.... Man merks, wenn man bei speichern unter einen anderen Namen vergibt.... dann gibt es keinen (direkten) Weg zurück.... kann hier erst einmal geschlossen werden . Vielen Dank für die ausführliche Auskunft

**Comment by j-dimension** [comment]
> also ist "speichern unter" keine wirkliche Option

Genau, es sei denn Du willst das Dokument dann nochmal in die Akte laden. Wir können das auch gern mal am Telefon durchspielen, wenn es hilft :-)
