### ISSUE TITLE
[FEATURE] Aktenzeichenschema: Logik für laufende Nummern erweitern

### ISSUE THREAD

**Issue by j-dimension** [jlawyerorg/j-lawyer-org#2450]
- N benötigt mindestens 5 Stellen, soll auf 4 Stellen "aufgeweicht" werden (NNNN - max. 10K Akten)
- Möglichkeit, die laufende Nummer statt um 1 um beliebige Werte zu inkrementieren (bpsw. 2)

**Comment by j-dimension** [comment]
ja, man hat dann nur 4 Stellen. Bei laufender Nummer 319 wäre es trotzdem 0319.

**Comment by j-dimension** [comment]
![dahag-aktenzeichen](https://github.com/jlawyerorg/j-lawyer-org/assets/3729754/c6379f07-407e-4d83-ac6d-51576736b73c)

**Comment by stm9x9** [comment]
wozu kann man dieses Feature in der Praxis einsetzen?
