### ISSUE TITLE
Anzeige Übersicht Adressdaten falsch (Zeigt Telefonnummer der letzten aufgerufenen Adresse)

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-org#2453]
Ich habe gerade Herrn A. anrufen wollen und seine Adresse aufgerufen. Dann bin ich in die Akte des Herrn B. und wollte den anrufen. angezeigt wird mir dann aber in der Übersicht weiter der Name und die Telefonnummer von A. . Wenn ich dann kurz auf Person gehe und dann zurück zu Übersicht, dann korrigiert sich das. Wenns blöd läuft und man nicht genau hinschaut ruft man also beim Adressaufruf den/die falsche an.

**Comment by j-dimension** [comment]
Bereits bearbeitet: https://github.com/jlawyerorg/j-lawyer-org/issues/2442
