### ISSUE TITLE
[BUG] Navigation durch PDFs

### ISSUE THREAD

**Issue by socram70** [jlawyerorg/j-lawyer-org#2456]
Beim Durchklicken der Vorschau werden beim Erreichen der letzten Seite nicht die beiden rechten Buttons ausgegraut. Der Fokus springt bei erneutem Klick auf einen der Buttons anschließend auf den Zoom-Slider. Beim Navigieren nach links tritt das Problem nicht auf und die beiden linken Buttons werden beim Erreichen der ersten Seite ausgegraut.
![grafik](https://github.com/jlawyerorg/j-lawyer-org/assets/60073801/dddc0a73-3bac-4583-86f7-c40a955cf954)

**Expected behavior / Erwartetes Verhalten**
Die beiden rechten Icons sollten beim Erreichen der letzten Seite ausgegraut werden. Der Fokus sollte nicht auf den Zoom-Slider wechseln.

**Environment / verwendete Umgebung:**
 - OS / Betriebssystem: Windows 11 
 - j-lawyer.org Version: 2.6.1.6 / 2.6.1.0 (Client)

**Comment by j-dimension** [comment]
Ich bekomme das im aktuellen Entwicklungsstand nicht reproduziert, evtl. habe ich es "versehentlich" im Rahmen von  #2409 behoben.
