### ISSUE TITLE
[FEATURE] Button zum Aktualisieren im Dokumenten-Reiter

### ISSUE THREAD

**Issue by socram70** [jlawyerorg/j-lawyer-org#2457]
Ein Button im Dokumenten-Reiter der Akte zum Aktualisieren wäre sehr hilfreich. 

Beim Arbeiten mit einer (offenen) Akte kommt es hin und wieder vor, dass ich z. B. über das Thunderbird-Plugin neue E-Mails oder Dokumente zur Akte hinzufüge. Diese Dokumente tauchen dann erst auf, nachdem man die Akte ein Mal geschlossen hat und neu geöffnet hat. Die Dokumente werden auch nicht angezeigt, wenn man nach dem Hinzufügen einer E-Mail ein neues Dokument über den j-lawyer Client hinzugefügt hat. Hier würde es sich ggf. auch anbieten, die Ansicht zu aktualisieren um parallel hinzugefügte Dokumente aufzulisten.

**Comment by j-dimension** [comment]
Duplikat von #2081
