### ISSUE TITLE
[BUG] Navigation durch pdf - Pfeile grauen nicht aus

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#2459]
ähnlich wie #2456 

wenn ich bei zweiseitigen pdf auf den Pfeilbutton nach rechts klicke, dann wird die zweite Seite angezeigt, aber es grauen die Schaltflächen nicht aus (und dafür dann die zurück-Buttons entgrauen). Nur wenn ich ein ein zweites Mal draufklicke, dann springt die Anzeige um.

![image](https://github.com/jlawyerorg/j-lawyer-org/assets/29924198/74512dff-c283-4f6f-9234-d574304c620b)

Win 10 64bit, jl 2.6.1.0

**Comment by j-dimension** [comment]
Bitte erstmal keine weiteren Tickets bzgl. des PDF-Viewers, da er für die 2.7 in großen Teilen neu geschrieben wurde. Es wäre hilfreich, wenn es eine breitere Beteiligung im Rahmen der Pilottests geben würde um die überarbeitete PDF-Anzeige zu testen.
