### ISSUE TITLE
[BUG] CPU im Servermonitoring immer auf 100% (Windows)

### ISSUE THREAD

**Issue by Dickmaulruessler** [jlawyerorg/j-lawyer-org#2467]
Ich hatte häufiger RAM-Warnungen. Nun habe ich meinen Arbeitsspeicher einmal auf 32 GB aufgerüstet. Das tut gut und alles läuft bestens!

Bei der Gelegenheit habe ich mir das Servermonitoring und "Administration" noch einmal angeguckt. 
Für meine CPU wird in j-lawyer durchgängig 100% Auslastung und ein roter Balken angezeigt. Das war schon immer so. Deshalb hatte ich die Überwachung für die CPU schon vor einer Ewigkeit deaktiviert. 

Im (Windows 10) Taskmanager ist meine CPU (Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz)
niemals zu 100% ausgelastet. In Hochphasen so um die 30-40%, sonst deutlich darunter.
Die CPU-Überwachungswerte werden unter j-lawyer aber konstant mit 100% angegeben.

Ich persönlich habe kein Problem, alles läuft wunderbar.
Meine Frage wäre nur, ob mit dem j-lawyer-Servermonitorin irgendetwas vieilleicht nicht stimmt, ob das wichtig ist oder ob das vielleicht einfach so bleiben kann...

Die anderen drei Werte (RAM, JAVA VM, DISK) werden korrekt angezeigt.

**Comment by j-dimension** [comment]
Die CPU-Werte im j-lawyer aktualisieren sich nur alle paar Minuten. Ist der Wert auch nach längerem Arbeiten im Client permanent auf 100%? Und laufen Server und Client überhaupt auf dem selben Gerät?

**Comment by Dickmaulruessler** [comment]
Ja, Server und Client befinden sich auf dem selben Gerät. 

Ich habe jetzt mehrere Stunden getetestet. Und ja, es gibt tatsächlich Veränderungen und die 10-Min-Durchschittswerte können jetzt durchaus stimmen (20-23%). Nichtsdestotrotz hatte ich auch wieder Werte die absolut nicht stimmen können (100%, 0%). Möglicherweise werden diese "komischen" Werte nur angezeigt, wenn man unter Einstellungen den Haken bei Überwachung der Schwellwerte entfernt. 
Ich werde das mal auf längere Sicht im Blick behalten und schlage vor, das erst einmal zu schließen - vielleicht bin auch nur ich hier "überlastet" ;-)
