### ISSUE TITLE
[FEATURE] Name des Beteiligten in Popup Ort: eMail/Bea Versandfenster -> Beteiligtenmatrix

### ISSUE THREAD

**Issue by iradraconis** [jlawyerorg/j-lawyer-org#2475]
Wir haben sehr viele Beteiligten-Typen und mir bereitet es immer wieder Schwierigkeiten bei Versand einer E-Mail  den richtigen Beteiligten auszuwählen. Wenn ich mit der Maus über die auf der linken Seite der Matrix befindlichen drei Punkte klicke, sehe ich nur das Zeichen des jeweiligen Beteiligten, aber weiß dann immer noch nicht, welcher Beteiligte das ist. Ich muss also das Fenster immer vergrößern, bis alle Beteiligten zu sehen sind. Eine Erweiterung des Pop-Ups um den Namen des Beteiligten würde hier sehr helfen.

![Bildschirmfoto vom 2024-07-03 08-10-27](https://github.com/jlawyerorg/j-lawyer-org/assets/71747937/fc5a6bd5-b604-424a-8ba8-867d1ed54462)

**Comment by j-dimension** [comment]
Warum auch immer bekomme ich unter Linux gerade **gar keinen** Tooltip... muss das nochmal an einer anderen Maschine testen.

**Comment by iradraconis** [comment]
Man sieht meinen Mauszeiger nicht.. aber ich gehe da mit der Maus auf die Drei Punkte. Linux Fedora 39 - ARM

[Bildschirmaufzeichnung vom 2024-07-08, 16-03-17.webm](https://github.com/jlawyerorg/j-lawyer-org/assets/71747937/0c8f8cbf-6195-4945-b27f-abf8c945e8a2)

**Comment by iradraconis** [comment]
> Warum auch immer bekomme ich unter Linux gerade **gar keinen** Tooltip... muss das nochmal an einer anderen Maschine testen.

Funktioniert?

**Comment by j-dimension** [comment]
Unter Ubuntu mit KDE kein Tooltip. Stört mich aber erstmal nicht und hat auch nichts mit Deinen Codeänderungen zu tun. Ich schaue mir das bei Gelegenheit noch unter macOS und Windows an.

**Comment by iradraconis** [comment]
Tooltip ist leer, wenn kein Zeichen beim Beteiligten notiert ist. Der Name sollte wenigstens im Tooltip stehen. Ich liefere nach

**Comment by j-dimension** [comment]
Stimmt, so stand's im Code :-)
