### ISSUE TITLE
Clientupdate - start nach download

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-org#2476]
Wenn der Client in einer alten Version vorliegt (2.6.02, bei mir auf länger ruhendem Rechner), dann erkennt bekommt man die Meldung dass eine neue Version vorliegt und diese wird heruntergeladen. 

Man weiss nicht wohin, man kann sie nicht starten, sie startet nicht automatisch. Wenn man den Client neu startet wird der download nicht erkannt und die Prozedur beginnt von neuem. Bis man sich von der Webseite den Client nochmals runterlädt und installiert um Voranzukommen. Vorschlag - nach download des updates angebot der (automatischen) Installation, schließen des Clients, installation der neuen Version, (Auto) Neustart des Clients. Dann wäre es rund....

**NOTE: Please search existing tickets to avoid duplicates **
**HINWEIS: Bitte vorab die Ticketsuche verwenden, um Doppeleinträge zu vermeiden **

**Is your feature request related to a problem? Please describe. / Welches Problem soll durch die Erweiterung / Verbesserung gelöst werden?**
Description / Beschreibung

**Describe the solution you'd like / Beschreibe die gewünschte Lösung**
Description / Beschreibung

**Additional context / Sonstiges **
Sonstige Informationen / Screenshots / ...

**Comment by j-dimension** [comment]
Nach Download erscheint ein Popup mit dem Ordner, ist das nicht der Fall?

**Comment by Linkki2021** [comment]
Ich weiß nicht, ob es hierauf auf anderem Wege eine Antwort gab, ich hatte das gestern zufällig.

Das Ganze wird so angezeigt, ein Popup gibt es nicht, die Installationsdatei liegt im Download-Ordner
![image](https://github.com/user-attachments/assets/906cf877-d120-49af-a4d2-e7f1432718bc)

**Comment by j-dimension** [comment]
siehe #2655
