### ISSUE TITLE
[FEATURE] Fehlende Wiedervorlagen/Fristen

### ISSUE THREAD

**Issue by Linkki2021** [jlawyerorg/j-lawyer-org#2478]
Ich mag die Funktion. Kann man sie noch kleinteiliger aufbauen? 

Derzeit findet man nur Akten, in den keine Fristen "und" keine Wiedervorlagen vorhanden sind. Wir hatten zuletzt mit neuen Mitarbeitern häufiger, dass entweder das eine oder das andere vergessen wurde. Diese Akten findet man dann aber nicht, weil ein Typ jeweils gepflegt wurde. Dass beides vergessen wurde gibt es natürlich auch, aber deutlich seltener.

**Comment by j-dimension** [comment]
Ansicht hat nun drei Tabs: 
- Akten ohne irgendeinen Kalendereintrag
- Akten ohne WV
- Akten ohne Frist

Die drei Tabs erlauben alle eine Navigation zum jeweiligen Fall und können auch alle exportiert werden.

**Comment by j-dimension** [comment]
![grafik](https://github.com/user-attachments/assets/fe050eb3-3679-44a4-b7a3-04c98496359c)

**Comment by j-dimension** [comment]
Es gibt nun auch einen Zahlenindikator in der Hauptnavigation, damit man nicht "auf Verdacht" reinschauen muss, sondern angezeigt bekommt, ob Akten gerade "vergessen" werden könnten: 

![grafik](https://github.com/user-attachments/assets/4bf8dcc5-95e5-457a-9055-2a9f7cb7982f)
