### ISSUE TITLE
[BUG] Dokumentenliste - Farbmarkierung grün ist ungünstig

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#2479]
Das Grün der Markierungsbox und das Grün des ausgewählten Dokuments sind leider nicht zu unterscheiden. Wäre schön, wenn das Grün (was ich als grundlegende Farbe durchaus richtig finde) ein erkennbar anderes Grün als das andere wäre.

![image](https://github.com/jlawyerorg/j-lawyer-org/assets/29924198/c8a19b69-3c11-4129-b302-94c22a43eae3)

**Comment by iradraconis** [comment]
Kann geschlossen werden, da erledigt

**Comment by stm9x9** [comment]
ein kleines Folgeproblem:

alte gesetzte Farbmarkierungen in dem alten Grün bleiben in dem alten Grün.

![Image](https://github.com/user-attachments/assets/5b31f365-b132-4a8b-b71d-4403e26d0130)
