### ISSUE TITLE
[BUG] Orderreihenfolge inkonsistent

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#2480]
Die alphabetische Reihenfolge der Ordner ist in der einen Liste anders als in der anderen, was immer ein wenig irritiert. Offenbar liegt hier eine unterschiedliche Behandlung von groß/kleinschreibung vor. IMHO sollte groß/kleinschreibung ignoriert werden.

![image](https://github.com/jlawyerorg/j-lawyer-org/assets/29924198/4bc3686c-c7db-448b-b1b6-94fc0d939460)

Die Reihenfolge der Dateien bei Sortierung nach Ordnern ist wie in der Seitenleiste.

![image](https://github.com/jlawyerorg/j-lawyer-org/assets/29924198/2018ebab-5118-4618-bea2-70592d7e44c0)

**Comment by j-dimension** [comment]
getestet
