### ISSUE TITLE
[FEATURE] Messaging: Filter Nachrichtenempfänger

### ISSUE THREAD

**Issue by Linkki2021** [jlawyerorg/j-lawyer-org#2484]
Im Grunde ein weiterer Baustein zu #2435:

Wenn ich weiß, dass jemand im Urlaub ist zB, wäre es schön, wenn ich die Nachrichten nur an diesen Nutzer filtern könnte, um sie dann ggf. abzuhaken und zu bearbeiten. Analog des Desktops mit den Wiedervorlagen beispielsweise.

Bei vielen Messages wird es ansonsten arg unübersichtlich.

**Comment by j-dimension** [comment]
@Linkki2021 zur Info:


https://github.com/user-attachments/assets/cffcbfa6-10cb-4306-8ab4-81cacfa70cd8
