### ISSUE TITLE
[FEATURE] Auswahl zwischen OpenStreetMap und Google Maps für Adresse und Route

### ISSUE THREAD

**Issue by iradraconis** [jlawyerorg/j-lawyer-org#2489]
Mit dem Feature #902 ist es nun möglich, die Route und die Adresse zu einem Beteiligten über Open Street Map anzeigen zu lassen. 

Manche möchten aber vielleicht stattdessen lieber Google Maps nutzen, da über Google Maps noch andere Features wie Synchronisation von Routen, viele Informationen zur Zieladresse etc. verfügbar sind. 

Es könnte in den Einstellungen eine Option angeboten werden, welcher Service genutzt werden soll. Oder ist das schon deshalb raus weil Google proprietär ist?

Wenn Google Maps trotz closed source (wird ja auch nur ein Link verwendet und keine API) in Betracht kommt, wäre interessant, hier weitere Meinungen zu haben.

**Comment by j-dimension** [comment]
Ich meine dass das sicher einen Mehrwert hätte. Die Route mal eben aufs Telefon synchronisieren zu können ist schon schick. 
Evtl. kann man statt einer Option in den Einstellungen einfach ein Sub-Menü machen

--> Route --> Open Streetmap
--> Route --> Google Maps

**Comment by iradraconis** [comment]
kann geschlossen werden, weil erledigt
