### ISSUE TITLE
[FEATURE] Kalender: Klick auf "heute" öffnet Tagesansicht 

### ISSUE THREAD

**Issue by iradraconis** [jlawyerorg/j-lawyer-org#2507]
Auf Wunsch eines Kollegen.

@j-dimension darf ich das umsetzen oder anders ausgedrückt, ist das aus deiner Sicht auch sinnvoll? 

Wenn heute in der Monatsansicht geklickt wird, ist das nicht so wirklich sinnvoll. Anders in der Wochenansicht. Aber heute, sollte vielleicht wirklich auch den "heutigen" Tag zeigen.

**Comment by j-dimension** [comment]
@iradraconis ich persönlich fände das nicht so nett. Ich nutze fast ausschließlich die Wochenansicht und bei Terminvergabe springe ich in den Wochen nach vorn, finde nix, springe zurück um es irgendwo reinzuquetschen. 

Zusätzlichen Button einfügen?

**Comment by iradraconis** [comment]
Sehe das ganz genauso, ich nutze die Tagesansicht tatsächlich auch nie. Und dafür ist vielleicht auch dann die tägliche Agenda gut, wenn sie fertig ist.

Für einen Button wäre noch genug Platz. :-)

**Comment by iradraconis** [comment]
Ich habe das jetzt implementiert, meine aber, dass es kein großer Mehrwert ist. Es wird ja nur ein Klick gespart, aber dafür ein Button mehr... Durch klick auf heute und dann Tag hat der Nutzer dasselbe Ergebnis. 
@j-dimension ich tendiere zu lieber weglassen..

**Comment by iradraconis** [comment]
Ich pushe den Commit mal in den branch… Du kannst ja mal schauen

**Comment by j-dimension** [comment]
> @j-dimension ich tendiere zu lieber weglassen..

@iradraconis ich hab's mir angeschaut und teile Deine Meinung...
