### ISSUE TITLE
[BUG] Messages: Trotz 365 Tage - Ansicht werden nicht alle Nachrichten angezeigt. 

### ISSUE THREAD

**Issue by iradraconis** [jlawyerorg/j-lawyer-org#2509]
Message von vor 9 Wochen bspw. noch als ungelesen, wird nicht angezeigt.

**Comment by j-dimension** [comment]
Das ist mehr Bug als Feature. Es gibt eine harte Limitierung auf 500 Nachrichten in https://github.com/jlawyerorg/j-lawyer-org/blob/50c2a8d0bf159078cd71a9625793bc36ae6b5b2c/j-lawyer-server/j-lawyer-server-ejb/src/java/com/jdimension/jlawyer/services/MessagingService.java#L842

Die Frage ist, wie man die gesamte Datenbank in einem Screen als User handhaben möchte.

**Comment by iradraconis** [comment]
Achso.. dann nehm ich das zurück :) war hier nur aufgefallen. Ticket kann geschlossen werden.

**Comment by j-dimension** [comment]
Nein nein, das Anliegen ist ja valide :-)

Man müsste eben nur eine andere sinnvolle Logik definieren. Bspw. unbestätigte Nachrichten immer mit zu laden, auch wenn dadurch das Limit überschritten würde.

**Comment by j-dimension** [comment]
Sollte via #2516 gelöst sein
