### ISSUE TITLE
[BUG] Navigationsbutton wird am Ende des Dokuments bei der Vorschau nicht ausgegraut

### ISSUE THREAD

**Issue by socram70** [jlawyerorg/j-lawyer-org#2513]
**Describe the bug / Fehlerbeschreibung**
Der Klick auf den Navigationsbutton bei der Vorschau von PDFs führt dazu, dass zwar zur nächsten Seite gesprungen wird, der Button allerdings nicht ausgegraut wird, obwohl man am Ende des Dokuments angelangt ist. Hier ist ein erneuter Klick auf den Button notwendig, damit er ausgegraut wird. Ein Zurücknavigieren ist nicht möglich, da der Button hierfür ausgegraut ist. Das ist insbesondere bei Dokumenten mit zwei Seiten relevant, da man erst durch einen weiteren Klick auf den Vorwärtsbutton den Zurückbutton aktivieren kann.

**To Reproduce / Schritte zum Nachvollziehen**
Ein PDF mit zwei Seiten in der Vorschau öffnen -> Zur zweiten Seite navigieren.

**Expected behavior / Erwartetes Verhalten**
Der Button für's Vorwärtsnavigieren sollte ausgegraut werden, sobald man am Ende des Dokuments angelangt ist. Gleichzeitig  sollte der Buttonfür die Rückwärtsnavigation wieder aktiviert werden.

**Screenshots**
![grafik](https://github.com/user-attachments/assets/d9ee9c71-ea7c-43cc-a22d-152ef53e236b)

**Environment / verwendete Umgebung:**
 - OS / Betriebssystem: Windows 11
 - j-lawyer.org Version: 2.6.1.6 / 2.6.1.0 (Client / Server)

**Additional context / Sonstiges**

**Comment by stm9x9** [comment]
ggf Duplikat von #2459 ?

**Comment by socram70** [comment]
Ja, danke, hatte ich nicht gefunden. Kann dann wohl geschlossen werden.
