### ISSUE TITLE
[FEATURE] Sicherheitswarnung bei emails dauerhaft abschalten können

### ISSUE THREAD

**Issue by iradraconis** [jlawyerorg/j-lawyer-org#2517]
Wir wünschen uns die Möglichkeit, diese Warnung, dass der Empfänger unbekannt ist, dauerhaft ausgeschaltet werden kann.

**Comment by iradraconis** [comment]
Bitte bitte in die 2.7

**Comment by j-dimension** [comment]
Kann sich nun jeder User selber im Profil einstellen: 

![grafik](https://github.com/user-attachments/assets/9eb9d015-bc16-4a28-b632-6920711223bd)

**Comment by j-dimension** [comment]
Als erstes Feedback kommt bestimmt: "ich möchte aber nicht, dass sich das meine Mitarbeiter selbst abschalten können"

Verlass Dich drauf! :-)

**Comment by iradraconis** [comment]
Wir sind sehr dankbar für diese Option! :)
