### ISSUE TITLE
[FEATURE] Zeiterfassung: Stundensätze pro Projekt

### ISSUE THREAD

**Issue by iradraconis** [jlawyerorg/j-lawyer-org#2520]
Ich habe wenige Akten, bei denen ich auf Zeitbasis abrechnen kann.  Meine Belegpositionen bzw. Vorlagen habe ich mit einem konkreten Stundensatz versehen. Allerdings ist der Stundensatz bei manchen Projekten abweichend.  Ich muss den nun händisch ändern, wenn ich die Belegvorlagen benutze.

Featurewunsch: Ist es sinnvoll oder möglich, den Stundensatz per Projekt einzustellen und einstellen zu können?  Falls ja, würden wir uns das wünschen. 

@j-dimension 2024-08-02 -----------------------------------------

- [x] Stundensätze pro Projekt ermöglichen
- [x] Beschreibung des Projektes in Zeiterfassungsdialog anzeigen
- [x] Beschreibung des Projektes mit in der Übersicht in der Akte anzeigen

**Comment by steboe1** [comment]
Daran wäre ich auch sehr interessiert. Ich habe andauernd abweichende Stundensätze und habe daher keinen Stundensatz in der Zeiterfassung hinterlegt sondern muss das jedes Mal manuell erledigen.

**Comment by j-dimension** [comment]
> muss das jedes Mal manuell erledigen

Du kannst einen abweichenden Stundensatz in den Einstellungen hinterlegen und er steht dann zur Auswahl. So müsstest Du nicht bei jeder Buchung Hand anlegen.

**Comment by j-dimension** [comment]
Die Stundensätze werden weiterhin zentral und aktenübergreifend konfiguriert. Pro Projekt lässt sich dann jedoch auf eine Teilmenge einschränken.
