### ISSUE TITLE
[FEATURE] Emails aus der Akte heraus öffnen => soll zentriert sein wie alle anderen Fenster und nicht oben links

### ISSUE THREAD

**Issue by iradraconis** [jlawyerorg/j-lawyer-org#2524]

**Comment by iradraconis** [comment]
@j-dimension hast du einen Tipp, wo ich die passende Codestelle finde?

**Comment by j-dimension** [comment]
@iradraconis 

Der Dialog, der eine Mail anzeigt, ist ViewEmailDialog. In deren Konstruktur wird die Fenstergröße bereits per `ComponentUtils.restoreDialogSize(this);` auf die zuletzt vom User genutzte Größe skaliert:

```
    public ViewEmailDialog(java.awt.Window parent, ArchiveFileBean contextArchiveFile, CaseFolder contextFolder, ObservedDocument odoc) {
        super(parent);
        initComponents();
        this.contextArchiveFile = contextArchiveFile;
        this.contextFolder = contextFolder;
        this.odoc = odoc;

        ComponentUtils.restoreDialogSize(this);

    }
```

Man könnte im selben Konstruktor, direkt nach dem Wiederherstellen der Fenstergröße, ein Zentrieren umsetzen via `FrameUtils.centerDialogOnParentMonitor`
Dazu würdest Du in der Dialogklasse über die Properties das Event `componentShown` behandeln und wie folgt füllen:

```
private void formComponentShown(java.awt.event.ComponentEvent evt) {                                    
        FrameUtils.centerDialogOnParentMonitor(this, this.getOwner().getLocation());
    }
```
