### ISSUE TITLE
[TASK] Zeilenhöhe für WV / Fristen im Reiter Kalender erhöhen

### ISSUE THREAD

**Issue by Dickmaulruessler** [jlawyerorg/j-lawyer-org#2528]
Die Zeilenhöhe für die Wiedervorlagen / Fristen im Reiter "Kalender" finde ich zu niedrig. 

- **Das richtige "Treffen"** mit der Maus ist unntöig umständlich (da Fläche zu klein)
- Falls man einen längeren **Beschreibungstext** hat, wird dieser aktuell nicht umgebrochen, sondern man muss horizontal scrollen. 

Ich rege an, die Zeilenhöhe im Reiter "Kalender" dort entsprechend der Zeilenhöhe auf dem Desktop anzupassen und damit auch dem Beschreibungstext mehr Platz zu geben. Es ist viel Platz vorhanden.

------------------------------------------------- @j-dimension 2024-08-14 --------------------

- [ ] Test Windows Normalskalierung
- [ ] Test Linux Normalskalierung
- [ ] Test macOS Normalskalierung
- [ ] Test Windows 150%
- [ ] Test Linux 150%
- [ ] Test macOS 150%

**Comment by iradraconis** [comment]
vorher: 
![Bildschirmfoto vom 2024-08-07 21-49-15](https://github.com/user-attachments/assets/28d58338-e5d1-4b3e-bc0d-7f51c14b3c7c)

nachher:
![Bildschirmfoto vom 2024-08-07 21-48-42](https://github.com/user-attachments/assets/9c160a15-9784-4250-afca-601bb7c4bc70)

**Comment by iradraconis** [comment]
Ich finde das Ticket gut. Daher mein Vorschlag dazu... :) @j-dimension was meinst du dazu?

**Comment by iradraconis** [comment]
Ein Umbruch der Beschreibung wäre damit noch nicht verbunden

**Comment by Dickmaulruessler** [comment]
Ich meinte - richtig - hoch, so wie auf dem Desktop (und auch mit der gleichzeitigen Möglichkeit das für die Beschreibung neu anzuordnen und hierfür mehr Platz zu schaffen. Ich selbst nutze die Beschreibung allerdings nie und schon gar nicht mit langem Text)

Aber für eine schnelle Lösung ist das hier schon einmal gut! Danke dir dafür!

**Comment by Dickmaulruessler** [comment]
> vorher: ![Bildschirmfoto vom 2024-08-07 21-49-15](https://private-user-images.githubusercontent.com/71747937/355964658-28d58338-e5d1-4b3e-bc0d-7f51c14b3c7c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwNjA2NDcsIm5iZiI6MTcyMzA2MDM0NywicGF0aCI6Ii83MTc0NzkzNy8zNTU5NjQ2NTgtMjhkNTgzMzgtZTVkMS00YjNlLWJjMGQtN2Y1MWMxNGIzYzdjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA3VDE5NTIyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJhMGE3ZWM0NTVjZDI0OGRlM2ZjNmM5ZWM3NDUyNmM2OGQxNWM4Zjg1YjVhNGIzMWMxMjY0NDQ1N2E2MjBiYmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dFWnj-z1zw7sjCThMHpDg5HPhfbmIHMT-iPVjbu6TxM)
> 
> nachher: ![Bildschirmfoto vom 2024-08-07 21-48-42](https://private-user-images.githubusercontent.com/71747937/355964641-9c160a15-9784-4250-afca-601bb7c4bc70.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwNjA2NDcsIm5iZiI6MTcyMzA2MDM0NywicGF0aCI6Ii83MTc0NzkzNy8zNTU5NjQ2NDEtOWMxNjBhMTUtOTc4NC00MjUwLWFmY2EtNjAxYmI3YzRiYzcwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA3VDE5NTIyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThhOGU1ODhiZGI5NzM4Mjk5OTY2YmU5Y2Q5NWVhODNkZmY0YTE5NWM2NzE0MDI1NTY0OWU2OGZkOTVlMDBmY2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6QIdx3n-32sntC9VV53RiklYag9sfiNrvNTUqMC8woc)

(man hat doch nie so viele offene WV/Fristen, oder?)

**Comment by j-dimension** [comment]
> Ich finde das Ticket gut. Daher mein Vorschlag dazu... :) @j-dimension was meinst du dazu?

Ich finde das optisch super angenehm! 

Man müsste schauen ob man das anwendungsweit so macht. Das könnte ein Einzeler sein. Bin mir gerade nicht sicher, aber es könnte reichen in FlatIntelliJLaf.properties den Wert für Table.cellMargins zu setzen (vgl. https://www.formdev.com/flatlaf/components/table/). Wäre auf ungewollte Seiteneffekte zu prüfen.

**Comment by iradraconis** [comment]
> > vorher: ![Bildschirmfoto vom 2024-08-07 21-49-15](https://private-user-images.githubusercontent.com/71747937/355964658-28d58338-e5d1-4b3e-bc0d-7f51c14b3c7c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwNjA2NDcsIm5iZiI6MTcyMzA2MDM0NywicGF0aCI6Ii83MTc0NzkzNy8zNTU5NjQ2NTgtMjhkNTgzMzgtZTVkMS00YjNlLWJjMGQtN2Y1MWMxNGIzYzdjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA3VDE5NTIyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJhMGE3ZWM0NTVjZDI0OGRlM2ZjNmM5ZWM3NDUyNmM2OGQxNWM4Zjg1YjVhNGIzMWMxMjY0NDQ1N2E2MjBiYmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dFWnj-z1zw7sjCThMHpDg5HPhfbmIHMT-iPVjbu6TxM)
> > nachher: ![Bildschirmfoto vom 2024-08-07 21-48-42](https://private-user-images.githubusercontent.com/71747937/355964641-9c160a15-9784-4250-afca-601bb7c4bc70.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwNjA2NDcsIm5iZiI6MTcyMzA2MDM0NywicGF0aCI6Ii83MTc0NzkzNy8zNTU5NjQ2NDEtOWMxNjBhMTUtOTc4NC00MjUwLWFmY2EtNjAxYmI3YzRiYzcwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA3VDE5NTIyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThhOGU1ODhiZGI5NzM4Mjk5OTY2YmU5Y2Q5NWVhODNkZmY0YTE5NWM2NzE0MDI1NTY0OWU2OGZkOTVlMDBmY2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6QIdx3n-32sntC9VV53RiklYag9sfiNrvNTUqMC8woc)
> 
> (man hat doch nie so viele offene WV/Fristen/Termine, oder? Sprich: Die Liste ist normalerweise nicht so lang)

die Länge der Liste ändert sich doch nicht, wenn Fristen oder WVen offen oder erledigt sind. Dann wird doch nur ein Haken gesetzt. Oder verstehe ich dich falsch?

**Comment by Dickmaulruessler** [comment]
Ja genau.
Was ich sagen wollte: Die erledigten muss man nicht auf den ersten Blick sehen. Und recht viel Platz ist, könnte das - jedenfalls hier - sogar ruhig noch großzügig sein. Freilich nicht falls es eine anwendungsweite Lösung geben soll.

**Comment by iradraconis** [comment]
> Table.cellMargins

@j-dimension  mit Table.rowHeight = 25 funktioniert es. Finde ich persönlich richtig gut! :) Gerade im Aktenkonto sehr angenehm.

**Comment by j-dimension** [comment]
> > Table.cellMargins
> 
> @j-dimension mit Table.rowHeight = 25 funktioniert es. Finde ich persönlich richtig gut! :) Gerade im Aktenkonto sehr angenehm.

Ist das die Lösung in der properties-Datei? Hast Du mal einen Screenshot? 
Bei absoluten Angaben bin ich immer etwas unsicher, man müsste das auf alle Fälle mit anderen Skalierungen (Menü "Ansicht" - "Schriftgrössen" - oberer Slider testen.

**Comment by j-dimension** [comment]
Die cellMargins wären hingegen wahrscheinlich bei jeder Skalierung eine sichere Lösung, da das die Abstäne zwischen Zellrand und Schrift sind. Wie groß die Schrift dann ist, ist egal.

**Comment by iradraconis** [comment]
mit cellMargins hat sich bei mir gar nix geändert... ich teste das die Tage mal mit unterschiedlichen 
Skalierungen.

**Comment by j-dimension** [comment]
Ein Augenschmeichler, ich liebe es, @iradraconis ! Und das mit einer Zeile Code :-)
