### ISSUE TITLE
[BUG] Reaktivierung der Akte trotz Ablehnung

### ISSUE THREAD

**Issue by ms00st** [jlawyerorg/j-lawyer-org#2532]
Beim Hinzufügen eines Scans zu einer archivierten Akte werde ich standardmäßig gefragt, ob ich diese reaktivieren möchten. 
Auch bei Ablehnung wird die Akte reaktiviert.

**Comment by j-dimension** [comment]
@ms00st danke für das Ticket. 

Bei Ablehnung bekomme ich das nicht reproduziert. Jedoch, wenn man statt "ja" oder "nein" zu antworten einfach das kleine Rückfragefenster schließt, findet eine Reaktivierung statt. 

Könnte das das Anwendungsszenario sein?
