### ISSUE TITLE
[FEATURE] Umgang mit extern bearbeiteten Dokument-Dateien verbessern

### ISSUE THREAD

**Issue by Dickmaulruessler** [jlawyerorg/j-lawyer-org#2537]
Wenn ich eine PDF in einem externen Programm bearbeiten will - die alte Datei aber behalten will - erfolgt die Abspeicherung der neuen (bearbeiteten) Datei in einem komplizierten Unterordner von ...\.j-lawyer-client\tmp-documents.

Könnte dieser Unterordner **für das Hinzufügen** dieser neuen bearbeiteten Datei unter J-lawyer einfach auffindbar (ein entsprechender Button?) gemacht werden? 
Oder gibt es einen anderen Weg, wie man diese Datei der Akte unkompliziert hinzufügen kann? 

Derzeit speichere ich die extern bearbeitete Datei zunächst lokal und bringe sie über den Hinzufügen-Button dann wieder in die Akte. 
Das finde ich recht umstänlich.

**Comment by j-dimension** [comment]
Du könntest die Datei per Rechtsklich in der Akte duplizieren und das Duplikat dann öffnen und bearbeiten.

**Comment by Dickmaulruessler** [comment]
Ah ja, gute Idee! Danke!

Macht es nicht trotzdem Sinn, dass man an diesen Ordner unkompliziert "rankommen" kann?

**Comment by j-dimension** [comment]
Ich wüsste nicht wofür. Dann werden dort Sachen gespeichert und User fragen sich warum das nicht in der Akte erscheint, "es ist ja das Aktenverzeichnis". 

Hast Du eine Idee wofür man das brauchen könnte?

**Comment by Dickmaulruessler** [comment]
> Ich wüsste nicht wofür. Dann werden dort Sachen gespeichert und User fragen sich warum das nicht in der Akte erscheint, "es ist ja das Aktenverzeichnis".
> 

OK. 
Dann kann das meinerseits hier geschlossen werden.

**Comment by Mucki526** [comment]
Ich kämpfe seit Jahren mit dem gleichen Problem und es wird dadurch noch dringlicher, dass man nur noch mit elektronischen Akten arbeitet. Wenn man eine Bearbeitung mit libreoffice macht, dann kann man die Datei öffnen und beim Speichern landet die Datei im Temporärordner von libre office, im backupordner - und erscheint im J-lawyer. Wenn ich aber (was wöchtenlich mehrfach der Fall ist, vom Mandanten Dateien bekomme oder Akteneinsicht vom Gericht (ein Stapel) und Dokumente extrahieren will oder Erzeugen (von Mandanten oft aus gedrehten jpgs, oder 30 Einzelpdf, zum Teil auf dem Kopf), dann kann ich icht einfach die Dateien z.B. in PDF24PDF laden und bearbeiten und wieder abspeichern, die externen Programme finden den Dokumentenordner nicht. Es müsste doch einen Weg geben, den aktiven Ordner als Virtuellen Ordner im Windows anzuzeigen, in den dann solche Bearbeitungen stattfinden und die Arbeitsergebnisse landen dann darin und direkt im J-lawyer Ordner, wie bei libreoffice.

**Comment by Dickmaulruessler** [comment]
> Du könntest die Datei per Rechtsklich in der Akte duplizieren und das Duplikat dann öffnen und bearbeiten.

Ich werde mit obigem Weg gut klar kommen. 
Du nicht auch @Mucki526   ?
