### ISSUE TITLE
[BUG] Rechnungdatum wird auf aktuelles Datum zurückgesetzt bei Öffnen einer noch offenen Rechnung

### ISSUE THREAD

**Issue by SoWhy** [jlawyerorg/j-lawyer-org#2538]
**Describe the bug / Fehlerbeschreibung**
Wenn man eine Rechnung nochmals öffnet, merkt das Programm sich zwar den Zeitraum, setzt aber das Datum zurück auf das aktuelle Datum

**To Reproduce / Schritte zum Nachvollziehen**
1. Rechnung unter Akte => Finanzen => Belege hinzufügen und speichern
2. Lupe klicken um wieder zu öffnen 

**Expected behavior / Erwartetes Verhalten**
Das gewählte Datum sollte gespeichert werden

**Screenshots**
Speichern mit richtigem Datum:
![2024-08-10 19_41_04-Rechnung RG240003](https://github.com/user-attachments/assets/5790038d-874a-4a30-b06a-4b19354429de)
Richtige Anzeige in Liste:
![2024-08-10 19_42_55-j-lawyer org Client 2 6 1 0  admin@192 168 1 56_8080-standard](https://github.com/user-attachments/assets/9a4d0c7e-1c5f-4f2f-9036-60c9a6453282)
Falsches Datum nach Wiederöffnen (aber Fälligkeit bleibt richtig!)
![2024-08-10 19_43_44-Rechnung RG240003](https://github.com/user-attachments/assets/afa624a0-9cea-4491-8f7b-0d88213f34c8)

**Environment / verwendete Umgebung:**
 - OS / Betriebssystem: Windows 11 Pro
 - j-lawyer.org Version: 2.6.1.6 / 2.6.1.0

**Additional context / Sonstiges**
Die Akte wurde erst heute angelegt, aber die Rechnung ist bereits älter, weil vor Nutzung von j-lawyer erstellt. Das sollte aber das Programm können

**Comment by j-dimension** [comment]
@SoWhy vielen Dank für das detaillierte Ticket - das ist sehr hilfreich!
