### ISSUE TITLE
[TASK] {{ZE_TABELLE}} bei mir leer trotz ZE Projekt und gebuchter Zeiten

### ISSUE THREAD

**Issue by iradraconis** [jlawyerorg/j-lawyer-org#2541]
Der Platzhalter bleibt bei mir leider leer, sodass ich keine Tabelle eingefügt bekomme. Ich habe auch die vorinstallierte Vorlage ausprobiert. Ohne Erfolg, es wird nur ein leeres Tabellenfeld dargestellt. Ich habe ein Projekt in der Akte und gebuchte Zeiten in dem Projekt. Zu welchem Zeitpunkt wird der Platzhalter gefüllt?

**Comment by j-dimension** [comment]
Wurden die zu berechnenden Positionen in den Beleg importiert?

**Comment by iradraconis** [comment]
Ich habe einen Vorschuss von zehn Stunden berechnet und habe dazu einen Beleg. Da hatte ich noch keine gebuchten Zeiten. Sollte ich für die Zeitaufstellung nun einen neuen Beleg erstellen? Mir ist der richtige Ablauf noch nicht ganz klar.

**Comment by j-dimension** [comment]
So wie Du bei Abrechnung nach RVG den Beleg aus den Plugins befüllst, kannst Du im Beleg auch Positionen aus einem Zeiterfassungsprojekt importieren. Im Tab "Positionen" hast Du dafür einen Stoppuhr-Button.

**Comment by iradraconis** [comment]
Also sinnvollerweise nach Ableistung der ersten zehn Stunden eine neue Rechnung  erstellen bzw. einen neuen Beleg und dann die Positionen einfügen, die bereits gezahlte Summe abziehen und die Rechnung an den Mandanten verschicken. ok.. kapiert

**Comment by j-dimension** [comment]
Den Vorschuss hast Du ja in Rechnung gestellt, oder? Das wäre Beleg 1. 

Dann, wenn Du abrechnest, wäre eh ein neuer Beleg fällig. Dort würde ich dann die Zeiten aus der Zeiterfassung importieren und anschließend eine manuelle Position einfügen, welche den Vorschussbetrag abzieht.

Ergibt das Sinn?

**Comment by iradraconis** [comment]
Ja, so gerade ausprobiert. Habe dafür eine neue Vorlage (mit Zeiterfassung) erstellt.  Mir war das Handling noch nicht klar, denn das youtube Video fehlt noch 🤪

So ist es super! Danke! kann geschlossen werden.
