### ISSUE TITLE
Falldatenblatt Flugrecht und Flug Musterschreiben

### ISSUE THREAD

**Issue by Dickmaulruessler** [jlawyerorg/j-lawyer-org#2546]
Falldatenblätter werden aufgelistet, obwohl weder vorhanden noch unter "Falldatenblätter verwalten" verfügbar.

![Falldaten-Flugrecht](https://github.com/user-attachments/assets/56073c8c-a0b4-43f6-9824-f3ddd3a63562)

**Comment by j-dimension** [comment]
Es gibt kein offizielles FDB zum Thema Flugrecht, wahrscheinlich hast Du mal das Training zur FDB-Entwicklung mitgemacht und Deine lokale Installation für die Entwicklung vorbereitet. Das müsstet Du wieder zurückbauen, wenn es stört.

**Comment by Dickmaulruessler** [comment]
> wahrscheinlich hast Du mal das Training zur FDB-Entwicklung mitgemacht 

Ja. 

> Das müsstet Du wieder zurückbauen, wenn es stört.

"stören" ist relativ. Wenn es ansonsten dauerhaft dort bleibt, hätte ich es gerne weg. 
Wie könnte ich das tun?

**Comment by j-dimension** [comment]
Im verlinkten Material gibt es Folien zur "Vorbereitung", das müsstest Du rückgängig machen:

https://www.j-lawyer.org/?p=3601

**Comment by Dickmaulruessler** [comment]
![formadfjasdölfjasdfsd](https://github.com/user-attachments/assets/46d32b53-2d60-4c9d-a0fc-275d34112067)

Diese vier Dateien löschen? 
Dann fertig?

**Comment by j-dimension** [comment]
oder einfach den ganzen Ordner Forms-internal löschen.

**Comment by Dickmaulruessler** [comment]
Mit dem Löschen des o.g. Ordners war es noch nicht weg. 

Ich bin unsicher und frage lieber, bevor ich etwas komplett falsches mache. Daher: 

Dort ist das auch in jedem Unterordner vorhanden.
![fkdsjfaklösjdfklöas](https://github.com/user-attachments/assets/78f4a01c-cfe5-47e6-b301-0ddb01aae137)

Reicht es, wenn ich die vier Dateien in dem Ordner 2.6.1.0 lösche? Oder muss ich in den anderen Unterordnern noch etwas tun? 

![dfdfdasdddddd](https://github.com/user-attachments/assets/0e0b1a39-91f3-4148-97c6-d3310a27d754)

Hab´ ich es dann komplett geschafft?

**Comment by j-dimension** [comment]
Schickst Du mal ein Bild aus den Falldatenblatt-Einstellungen? (da wo man die installieren und deinstallieren kann)

**Comment by Dickmaulruessler** [comment]
Fluggast ist - und war auch zuvor - nicht dabei. 

![fdfdfdfdddddd](https://github.com/user-attachments/assets/b4727eab-32a2-42f2-b659-ab861fe515df)
![fdafdsafdsfdsffsdd](https://github.com/user-attachments/assets/0e1df685-1a8b-44ea-ad4d-e6fd483369a3)
![dfssfdasdfasdffsdsdaf](https://github.com/user-attachments/assets/1747ec28-ee7a-4724-aefd-76ae83493030)

**Comment by j-dimension** [comment]
Hier müsste ich mal per Fernwartung draufschauen.

**Comment by socram70** [comment]
Ich habe das Problem auch und würde gerne beim Einpflegen unterstützen. Weil es eher in das andere Repo gehört, hatte ich [hier](https://github.com/jlawyerorg/j-lawyer-forms/issues/5#issuecomment-4275923003) etwas dazu geposted.

**Comment by socram70** [comment]
@Dickmaulruessler das Problem liegt nicht auf deinem Client, sondern daran, dass in einer alten j-lawyer Serverversion diese Templates über die Datenbank mit ausgeliefert wurden. Sie werden bei jedem Neustart des Clients neu vom Server geholt, sodass das Löschen nicht hilft. Neben dem Löschen musst du Folgendes machen:

```
DELETE FROM form_types_artefacts WHERE formtype = 'flug01';
DELETE FROM form_types_artefacts WHERE formtype = 'flug02';
DELETE FROM form_types WHERE id = 'flug01';
DELETE FROM form_types WHERE id = 'flug02';
```

Wenn du eine Fehlermeldung bekommst, liegt das daran, dass die Formulare noch in einer Akte verwendet werden. Dann kannst du mit `SELECT * FROM case_forms WHERE formtype IN ('flug01', 'flug02');` gucken, welche Akten das sind und entweder manuell die Falldatenblätter entfernen oder über 
```
DELETE FROM case_forms WHERE formtype IN ('flug01', 'flug02');
DELETE FROM form_types_artefacts WHERE formtype IN ('flug01', 'flug02');
DELETE FROM form_types WHERE id IN ('flug01', 'flug02');
```

Vielleicht betrifft das ja noch den ein oder anderen User hier, der schon lange dabei ist und diese Altlasten noch in der Datenbank hat.

@j-dimension Da das ja ursprünglich nur mal als [Test gedacht war](https://github.com/jlawyerorg/j-lawyer-forms/issues/5#issuecomment-4276894921), wäre vielleicht ein Skript in einem der nächsten Updates gut, das die Einträge entfernt.
