### ISSUE TITLE
[BUG] Dokumentenetiketten nicht richtig sortiert beim Anlegen einer Notiz

### ISSUE THREAD

**Issue by iradraconis** [jlawyerorg/j-lawyer-org#2555]
![Bildschirmfoto 2024-08-28 um 15 48 48](https://github.com/user-attachments/assets/262038e0-1d99-48b9-9f3b-60fae01edbc0)

**Comment by iradraconis** [comment]
Oder ist die Sortierung nach Groß- und Kleinschreibung so gewollt?

**Comment by j-dimension** [comment]
Nee, das ergibt keinen Sinn, die Sortierung sollte unabhängig von Groß-/Kleinschreibung sein. 

Man kann hier einfach in https://github.com/jlawyerorg/j-lawyer-org/blob/42d8f2a8bb4d027e5f6af2c3a49e71d45c30fc07/j-lawyer-client/src/com/jdimension/jlawyer/client/editors/files/AddNoteDialog.java#L771 die Zeile

`Collections.sort(allTags2);`

ersetzen durch

`StringUtils.sortIgnoreCase(allTags2);`

Betrifft auch die Aktenetiketten im selben Dialog.
