### ISSUE TITLE
[FEATURE] dateibasierte Export- und Importmöglichkeit für Einstellungen

### ISSUE THREAD

**Issue by j-dimension** [jlawyerorg/j-lawyer-org#2561]
Ähnlich zu #130 bzgl. fachlicher Daten, soll ein Import von Einstellungen ermöglicht werden:

- [x] Service zum Laden / Ausgeben eines leeren (oder vorausgefüllten) Sheets
- [x] Service zum Importieren
- [x] Dialog für Import und zur Anzeige der Ergebnisse
- [x] Unterstützung für "Dry Run" / Validierung

importrelevante Objekte:

- [x] Etiketten Dokument
- [x] Etiketten Akte
- [x] Etiketten Adresse
- [x] Beteiligtentypen
- [x] Eigene Felder Akte
- [x] Eigene Felder Adresse
- [x] Eigene Felder Beteiligte
- [ ] Installationsstatus Falldatenblätter
- [x] WV-/Frist-/Termingründe

Der Import soll "ergänzend" funktionieren, vorhandene Einstellungen bleiben erhalten.

**Comment by j-dimension** [comment]
Testlauf:


https://github.com/user-attachments/assets/2fd811e8-452d-4a9f-8d9f-d34765f9bc7f

**Comment by Linkki2021** [comment]
@j-dimension 
1. Ja, bitte auch Falldatenblattinstallation via Server
2. Export vorhandener Einstellungen wäre prima.
