### ISSUE TITLE
[TASK] Frage zur Zeiterfassung 

### ISSUE THREAD

**Issue by iradraconis** [jlawyerorg/j-lawyer-org#2562]
Ich habe mal eine Frage zur Zeiterfassung. Ich möchte gern die Tabelle, welche die  jeweiligen Zeiten aufhört, in mehrere Dokumente einbeziehen. Wenn ich diese aber einmal abgerechnet  habe, kann ich das nicht mehr, weil sie in der Belegerfassung als schon abgerechnet erscheinen.  Ich kann die Zeiten dann auch gar nicht mehr editieren. 

Ich habe  vorgehabt, die bereits geleisteten Stunden einer zweiten Vorschussrechnung beizufügen und die dann dort eingefügt. Demgemäß war aber ein Teil nur als Vorschuss zu berechnen und eben noch nicht als abgerechnet. Komme ich noch mal an die Zeiten ran? 

Über Auswertungen erhalte ich zwar auch eine Tabelle aber diese ist umständlicher zu formatieren und enthält Infos, die ich nicht benötige und dafür gibt es auch keinen Platzhalter. Ich möchte einfach nur die bisher gebuchten Zeiten in einer Tabelle haben.

**Comment by j-dimension** [comment]
Ich fürchte ich verstehe das Vorgehen noch nicht. In einer Vorschussrechnung würde man sich doch nicht auf bestimmte geleistete Zeiten beziehen, oder? Wäre das dann nicht eine ordentliche Rechnung?

**Comment by iradraconis** [comment]
In der 1. Vorschussrechnung würde ich bspw. 10 Stunden berechnen. Wenn die 10 Stunden erledigt sind, möchte ich eine 2. Vorschussrechnung erstellen und in der Vorlage des Rechnungsdokuments die bisher geleisteten Stunden abbilden. Es soll nur der aktuelle Stand abgebildet werden. Dass die gebuchten Zeiten nach Import in einen Beleg nicht mehr "verfügbar" sind, hat mich überrascht. Ggfs. wollte ich die Notizen oder die Beschreibung einer einzelnen Position noch einmal ergänzen etc.; 

Du hast schon Recht, dass die Zeiten in eine ordentliche Rechnung gehören, ich finde es nur unhandlich, wenn die Zeiten dann im Programm nicht mehr "verfügbar" sind, im Sinne von importfähig oder editierbar etc.

Ist das zwingend so?

**Comment by j-dimension** [comment]
Vielleicht wäre das ein Thema für die Mailingliste. Mir erscheint es seltsam, eine abgerechnete Zeit im Nachhinein inhaltlich zu verändern. 

Im Beispiel oben:
In der 1. Vorschussrechnung würdest Du ja keine Positionen importieren. In der 2. Vorschussrechnung würdest Du importieren. Möchtest Du dann 
(a) nach dem Import, aber vor Erstellung des Rechnungsdokuments oder
(b) nach dem Erstellen des Rechnungsdokuments 
editieren?

**Comment by iradraconis** [comment]
Was soll daran "seltsam" sein? Ich will ja nicht die Zeiten ändern, sondern ggfs. die Beschreibung ausführlicher und nachvollziehbarer machen, damit es nicht zu Nachfragen kommt. Ich möchte vielleicht den Stundensatz für eineulne Positionen anpassen, um dem Mdten entgegenzukommen. Und: die Positionen eines normalen Rechnungsbelegs kann ich ja auch jederzeit ändern. 

Und was ist mit folgender Konstellation: 
1. VR über 10 Stunden ohne Zeiten
2. VR über wieder 10 Stunden, jetzt mit Zeiten dabei, aber es sind schon 12 Stunden geleistet... Wie bilde ich das ab in dem Rechnungs- und Zeiterfassungstool?

Ich verstehe wirklich nicht, warum mein Anliegen "seltsam" sein soll :-)

**Comment by j-dimension** [comment]
Nee, nicht grundlegend seltsam :-)   Daher meine Frage nach dem Zeitpunkt des Editierens. Findet das vor der Dokumenterstellung statt ist das nachvollziehbar, findet es danach statt, finde ich es seltsam. Eine erstellte Rechnung ändert man ja auch nicht, nachdem das Rechnungsdokument erstellt wurde.

Die Frage ist: wenn das Editieren der abzurechnenden Zeiten einfach vor dem Impotieren in die Rechnung stattfindet, ist das Problem doch gelöst oder? Alternativ könnte man das Bearbeiten von Namen und Beschreibung IMMER erlauben. Das Ändern von Beträgen und Zeiten würde aber die kumulierten Zeiten in der Rechnung ungültig machen.

**Comment by iradraconis** [comment]
> Nee, nicht grundlegend seltsam :-) Daher meine Frage nach dem Zeitpunkt des Editierens. Findet das vor der Dokumenterstellung statt ist das nachvollziehbar, findet es danach statt, finde ich es seltsam. Eine erstellte Rechnung ändert man ja auch nicht, nachdem das Rechnungsdokument erstellt wurde.
> 

Da kommt es aber auf das Dokument an, das erstellt werden soll. Eine Rechnung? Eine Berechnung? Eine Aufstellung? Eine aktuelle Übersicht für die interne Dokumentation?

**Comment by Mucki526** [comment]
Es ist nicht seltsam, eine Zeiterfassung nachträglich zu korrigieren, sie ist nicht die Rechnung, nur eine Information für den Mandanten. Seltsam ist eher, eine Vorschussrechnung mit einer Zeiterfassung zu versehen. Die Abrechnung von erbrachten Zeiten ist kein Vorschuss, sondern die Abrechnung erbrachter Zeiten zujm vereinbarten Stundensatz. Meist vereinbare ich dazu in der Honorarvereinbarung, "xxx €/Stunde, mindestens die gesetzlichen Gebühren"), dann kommt es darauf an, womit ich besser fahre (gesetzliche Gebühren oder aufgewendete Zeit). )Vor Gericht ist es ja gesetzlich verboten, weniger abzurechnen als die gesetzlichen Gebühren nach dem RVG. Wenn ich die abgerechnete Zeit korrigieren oder ergänzen muss, teile ich das konkret dem Mandanten mit und stelle eine korrigierte Abrechnung über den Zeitraum unter Berücksichtigung der erbrachten Zahlungen mit korrigierter  /ergänzter Zeitabredch. Also Stornorechnung und Neuabrechnung. Wenn ich dann irgendwann eine Gesamtabrechnung mache, sind da diese Korrekturen an der Gesamtzeitabrechnungen drinnen. 
(Kommt aber bei mir so gut wie nie vor, da ich nach Abschnitten (Monate) abrechne.
Aber die Zeitaufstellung sollte tatsächlich immer editierbar sein und auch mehrfach in eine Rechnung kopierbar. Ich komme persönlich mit der im J-Lawyer implementierten Projektabrechnung noch überhaupt nicht zurecht. Wenn ich eine Akte habe ist das ein Projekt. Wenn ich unterschiedliche Tarife habe, weil z.B. der Stundensatz im Folgejahr (Akte über mehrere Jahre) ändert, hinterlege ich das bzw. rechne entsprechend ab. Meistens bleibt es bei dem Projekt (Mandat) aber bei dem alten Stundensatz, aber nicht immer, wenn es z.B. ein Dauermandat ist, passe ich das mit dem Mandanten zusammen irgendwann an. Wenn ich etwas in die Zeiterfassung eintragen will, dann möchte ich in der Akte an den Rand klicken, eine Tabelle geht auf und ich trage das ein mit Kommentar und schließen und fertig. Mehrere Projekte in einer Akte kommen bei mir einfach nicht vor. Wäre nur denkbar, wenn ich bzgl. einer einzelnen Tätigkeit eine gesonderte Vereinbarung treffe (anderer Stundensatz, Pauschale). Aber das ist dann oft eine neue Akte. Im Moment erledigt die Zeiterfassung immer noch meine Exeltabelle, die ich über den gelben Stern am Rand schnell erreiche, dann kann ich auch leicht Sachen nachtragen (Dauer des Telefonats, Nachbearbeitung). Vielleicht geht das ja mit dem jetzigen Projektmanagement, nur ich bin dazu noch nicht schlau genug bzw. habe die Funktionalität der Projektzeiterfassung noch nicht geistig durchdrungen.

**Comment by Dickmaulruessler** [comment]
Zeiterfassung - optional - einfacher gestalten
#2068

**Comment by iradraconis** [comment]
> Seltsam ist eher, eine Vorschussrechnung mit einer Zeiterfassung zu versehen.

War so gemeint: Vorschuss über 10 Stunden.. 11 Stunden sind schon erledigt, 2. Vorschussrechnung wird geschickt und zur INFORMATION, was alles schon so passiert ist, wird die Übersicht der abgerechneten Stunden "mitgeschickt"..

**Comment by stm9x9** [comment]
> ie Abrechnung von erbrachten Zeiten ist kein Vorschuss, sondern die Abrechnung erbrachter Zeiten zujm vereinbarten Stundensatz.

Ist nicht jede Geldanforderung vor Fälligkeit, also vor Ende der Angelegenheit, ein Vorschuß?

**Comment by j-dimension** [comment]
FYI, via #2472 werde ich Namen und Beschreibung immer editierbar lassen.

**Comment by j-dimension** [comment]
Man kann nun jederzeit einen Leistungsnachweis generieren - als normales Dokument, das nicht mit dem Beleg verknüpft ist: 

![grafik](https://github.com/user-attachments/assets/4be82fb3-1516-4e8e-b08f-7e86d48d00e3)
