### ISSUE TITLE
[FEATURE] E-Post / PRIO-Sendungen

### ISSUE THREAD

**Issue by Dickmaulruessler** [jlawyerorg/j-lawyer-org#2567]
Man kann keine [PRIO-Sendungen](https://www.deutschepost.de/de/p/prio.html) versenden. 

Liegt das an der Deutschen Post - API oder könnte das in j-Lawyer ergänzt werden? Falls Letzeres, würde ich mir das hier wünschen. Die Post dauert regelär manchmal wirklich schon sehr lange und die PRIO-Sendungen sind wirklich schneller.

**Comment by Dickmaulruessler** [comment]
Würde es auch hier Sinn machen, das (neben "Einschreiben") bei der Post anzuregen? 

Da die Postlaufzeiten immer länger werden, wird PRIO glaube ich immer wichtiger werden... 

https://www.deutschepost.de/de/e/epost/geschaeftskunden/partner/business-api/kontakt.html

**Comment by j-dimension** [comment]
> Würde es auch hier Sinn machen, das (neben "Einschreiben") bei der Post anzuregen?

Kann man probieren.

**Comment by Dickmaulruessler** [comment]
Hier die Antwort der Deutschen Post:

Die Auskunft Ihres Softwareherstellers bezüglich der Briefzusatzleistung PRIO und der E-POSTBUSINESS API ist richtig. Die sogenannten E-POST Zugangsprodukte, zu denen die API auch gehört, durchlaufen einen anderen Prozess als Briefe, die analog bei uns eingereicht werden. Bei PRIO-Brief haben Sie eine höhere Wahrscheinlichkeit, dass die Schreiben am nächsten Tag nach Einlieferung bei Empfänger sind. Das nennt sich bei uns E+1 und setzt voraus, dass der Brief in einer Filiale oder einem Briefzentrum eingeliefert wird. Eine Briefverfolgung kann online erfolgen, wenn Ihnen ein entsprechender Beleg mit der erforderlichen ID vorliegt.

Bei den E-POST Zugangsprodukten sieht der Prozess grundsätzlich anders aus. Wir erhalten das Schreiben digital und produzieren zunächst den Brief in unseren Druckzentren. Im Anschluss werden die Schreiben direkt in die Zustellzentren abgeleitet und gehen in die Zustellung, was in der Regel bedeutet, dass der Brief nach Einlieferung auch zwei Tage bis zum Empfänger benötigen kann, also E+2. Wenn Ihr Softwarehersteller es entsprechend implementiert hat, können Sie dafür den Status des Briefes automatisch aus Ihrer Anwendung heraus bis zum Zustellbriefzentrum nachverfolgen, ohne Beleg oder Suche in der Online-Sendungsverfolgung. Gilt übrigens auch für Einschreiben, wenn das für Sie relevant sein sollte.

Zusammenfassend wäre also der Sachverhalt so, dass Sendungen, die mit PRIO, jedoch nicht in der Filiale oder einem Briefzentrum eingeliefert werden, nicht zwingend einen Tag nach Einlieferung beim Empfänger sein müssen. Da Briefe, die über E-POST eingeliefert werden nach der Produktion direkt in die Zustellung abgeleitet werden, ist in der Regel auch hier gewährleistet, dass die Sendung genauso schnell beim Empfänger ist, jedoch mit weniger Aufwand und günstigeren Preisen.

**Comment by Dickmaulruessler** [comment]
Zum endgültigen Abschluss dieses Themas:

Die Deutsche Post stellt "PRIO" zum Jahresende komplett ein. 

Dann gibt es nur noch Einschreiben, welche neben dem Zustellnachweis gleichzeitig auch schneller befördert werden.

Mit E-POST haben wir in j-lawyer aber ein tolles Produkt mit schneller Zustellung (siehe oben Antwort der Deutschen Post)
