### ISSUE TITLE
[BUG] Aufruf und Anzeige von PDFs im ScanEingang mit 2.7 sehr langsam geworden

### ISSUE THREAD

**Issue by iradraconis** [jlawyerorg/j-lawyer-org#2570]

**Comment by j-dimension** [comment]
Nur im Scaneingang, nicht in der Akte?

**Comment by iradraconis** [comment]
soweit getestet sehr auffällig im Scan Eingang. In der Akte öffnen die Dokumente normal, sagt meine MAin.

**Comment by iradraconis** [comment]
Sobald der Hintergrund des neuen Viewers geladen ist, aber das Dokument noch nicht,  ist auffällig, dass sobald man die Maus in das Fenster führt, das Dokument sofort erscheint.

**Comment by j-dimension** [comment]
Okay, dann ist es ein reines Oberflächenaktualisierungsproblem. Kann man verifizieren, indem man den Trenner mal mit der Maus etwas verschiebt. Ich fixe das, aber das könnt Ihr erstmal als Workaround nutzen.

**Comment by iradraconis** [comment]
Es dauert aber auch überdurchschnittlich lang, bis der "viewer" geladen wird...

**Comment by iradraconis** [comment]
hm, kann ich noch nicht sagen.. das scheint sich gar nicht genau eingrenzen zu lassen. Mal dauert es lange, mal geht es fix. OCR ist aber dann schon immer erledigt.

**Comment by j-dimension** [comment]
Ich schließe hier und öffne ggf. wieder, wenn die Pilot-User ähnliches Feedback geben.

**Comment by Dickmaulruessler** [comment]
> Ich schließe hier und öffne ggf. wieder, wenn die Pilot-User ähnliches Feedback geben.

jepp. Kann ich auch bestätigen (im Reiter Dokumente / Scan noch nicht getestet).

**Comment by j-dimension** [comment]
Was genau ist denn langsam oder sehr langsam? 

Mehr Funktionalität / Komfort und Geschwindigkeit sind leider konträre Ziele. Das Scrollen bedingt, dass Seiten "vorgeladen" werden, die höhere Auflösung bedeutet längere Zeiten für Skalierungen etc.

**Comment by Dickmaulruessler** [comment]
> Was genau ist denn langsam oder sehr langsam?

Schon das Laden der ersten PDF-Seite ist langsam und bei umfangreichen PDF-Dokumenten ist das Laden der ersten PDF-Seite sehr langsam. An der von @iradraconis beschriebenen Beobachtung mit dem Mauszeiger ins Feld ziehen, ist wohl etwas dran, aber ganz sicher bin ich mir nicht. 

Ich beziehe mich nicht auf den ScanEingang, sondern auf den Dokumentenreiter (vermute aber, dass es wohl dasselbe Problem ist, daher schreibe ich hier. Bitte ggf. korrigieren).

**Comment by Dickmaulruessler** [comment]
danke dir! Nach einem ersten Test scheint das Problem behoben zu sein. 

Ein Caching der allerersten PDF-Seite findet aber wohl nicht statt. Das wäre beim schnellen Wandern durch die Akte hilfreich. Man wartet zwar nicht lange, aber die erste Seite ist eben nicht sofort da. 
Ginge das? Gesondertes Ticket?
