### ISSUE TITLE
[BUG] 2.7: Dateinamen vorlagen Fehler bei Eingabe von "n". N hingegen ist möglich.

### ISSUE THREAD

**Issue by iradraconis** [jlawyerorg/j-lawyer-org#2573]
![Bildschirmfoto 2024-09-20 um 09 47 43](https://github.com/user-attachments/assets/cc1f76c6-fc44-4dfb-98c4-1730152fb8d1)

**Comment by iradraconis** [comment]
![Bildschirmfoto 2024-09-24 um 21 07 31](https://github.com/user-attachments/assets/1956bcab-2d49-401f-a13f-376033d37036)

**Comment by iradraconis** [comment]
Scheint mit der Länge des Dateinamens zusammenzuhängen

**Comment by j-dimension** [comment]
Nee, das "m" ist einfach ein Platzhalter für den Monat... mal sehen ob ich das irgendwie lösen kann.

**Comment by iradraconis** [comment]
Problem besteht auch für andere Buchstaben. "d" zum Beispiel

**Comment by j-dimension** [comment]
Muss das überarbeiten. Danach werden eckige Klammern um die Platzhalter m, d, y notwendig sein.

**Comment by clvnsch** [comment]
Wenn man ein neues Schema anlegen will, ist der Standardtext nicht mit den eckigen Klammern:

![Image](https://github.com/user-attachments/assets/fff5437f-74d0-4d21-bdc8-a35b1013dc6d)

Es wird also als Standard "yyyy-mm-dd_DATEINAME" eingefügt statt "[yyyy]-[mm]-[dd]_DATEINAME".

**Comment by j-dimension** [comment]
@clvnsch danke für den Hinweis! Korrigiere ich mit der nächsten Vorschauversion.
