### ISSUE TITLE
[FEATURE] Umgang mit beA "schneller" machen

### ISSUE THREAD

**Issue by iradraconis** [jlawyerorg/j-lawyer-org#2574]
Ich weiß, das ist wieder Jammern auf hohem Niveau, daher möchte ich das nur als Frage in den Raum stellen. 

Ist es vielleicht möglich, den Umgang mit beA-Nachrichten zügiger zu gestalten?  Gerade beim Versenden von Nachrichten schaut man oft für mehrere Sekunden auf den Text "Nachricht verschickt". 

Ich weiß natürlich nicht, was im Hintergrund alles an Prozessen und requests abläuft und ob die Server-Antwort so lange dauert.  

Jedenfalls fällt es auf, dass beim Verschicken von Nachrichten das System immer so lange gesperrt ist, bis die Nachricht raus ist. Kein Vergleich zu postalischem Versand! Ist mir alles klar... war mir nur aufgefallen :)

**Comment by j-dimension** [comment]
Duplikat von #566.

Das Versenden dauert schlicht wirklich so lange. Technisch ließe sich das in den Hintergrund verlagern, dazu müsste aber
- jede Nachricht vor Versand in der Datenbank gespeichert werden
- ein Postausgangs-Dialog mit einer Vielzahl an Aktionen erstellt werden

Das hat Projektcharakter.

**Comment by j-dimension** [comment]
#566 bleibt offen, daher schließe ich dieses hier. Ist also keine Ablehnung des Themas an sich.

**Comment by iradraconis** [comment]
> Duplikat von #566.
> 
> 
> 
> Das Versenden dauert schlicht wirklich so lange. Technisch ließe sich das in den Hintergrund verlagern, dazu müsste aber
> 
> - jede Nachricht vor Versand in der Datenbank gespeichert werden
> 
> - ein Postausgangs-Dialog mit einer Vielzahl an Aktionen erstellt werden
> 
> 
> 
> Das hat Projektcharakter. 

Oha... Das steht wohl in keinem angemessenen Verhältnis
