### ISSUE TITLE
[FEATURE] Ingo: Eigene Prompts "sortierbar" machen.... Abbildung dieser Sortierung auch im Kontextmenü

### ISSUE THREAD

**Issue by iradraconis** [jlawyerorg/j-lawyer-org#2578]
Im Dialog für Erstellen eigener Prompts wäre es gut, wenn sich die Prompts in eine beliebige Reihenfolge bringen liessen. Durch eine eigene Sortierung lassen sich Kategorien abbilden. Meint aber nicht Art des Prompts, sondern Kategorien je nach Anwendungsfall und Kanzleibedürfnissen.

RIchtig top wäre es dann noch, wenn im Kontextmenü Kategorien mit Trenner optischj unterteilt werden.

**Comment by j-dimension** [comment]
Wird wahrscheinlich nicht mehr in die 2.7 passen.

**Comment by iradraconis** [comment]
Dann wenigstens vielleicht eine alphabetische Sortierung im Kontext Menü? Kann es mir gern angucken.

**Comment by j-dimension** [comment]
Ich erläutere kurz wie das aktuell funktioniert:

Grundsätzlich ist es so, dass nicht jede Ingo-Aktion in jedem Kontext sinnvoll ist. Beispielsweise kann man in Mail sehr viel ausführen und über den Button für die Erstellung neuer Dokumente eher weniger (bspw. nur Chat oder Generate, weil es keine Eingangsdaten gibt). Daher wird folgendes getan:

- Ermitteln aller Ingo-Fertigkeiten der angebundenen Ingoserver
- Filtern nach deren Aktionstyp (bspw. "Chat" oder "Chat" und "Generate")
- Aufnahme der gefilterten Liste in Popup-Menüs oder Kontextmenüs o.ä.

Ein Beispiel für das Filtern auf sehr viele Aktionstypen findet man hier: 
https://github.com/jlawyerorg/j-lawyer-org/blob/17761d8634709464e64c4606c92f68359143e02e/j-lawyer-client/src/com/jdimension/jlawyer/client/mail/MailContentUI.java#L2019

Kontextmenüs werden schrittweise pro Typ aufgebaut, also erst alle Aktionen "generate", dann "translate" usw. Es gibt also eine Art Sortierung der Menüs nach Kategorie. Bei vielen eigenen Prompts sind es viele Aktionen innerhalb einer Kateogorie, aber innerhalb der selben Kategorie gibt es keine definierte Sortierung. 

Codetechnisch gibt es zwei Alternativen:

(1) Eine Sortierung herstellen, nur innerhalb der Kategorie: dazu wäre die Methode filterCapabilities der Klasse AssistantAccess anzupassen. Dort wird ein gefilterte Liste rausgereicht, die könnte man noch nach dem Namen sortieren. Hier wäre nur an einer einzigen Stelle - eben jener Methode - Hand anzulegen, die Auswirkungen wären überall sichtbar.

(2) Eine Sortierung herstellen, die über alle Kategorien reicht: dazu wäre eine neue oder alternative Methode filterCapabilities zu entwickeln, die eine Liste von Capabilities bekommt und eine gefilterte und sortierte Liste zurückgibt, die Capabilities mehrerer Aktionstypen enthält.

Hört sich evtl. verwirrend an, aber es ist bzgl. Ingo eben nichts hartkodiert, damit man mittels Umkonfiguration des Ingo auf einmal zusätzliche Kontextmenüeinträge hat, ohne dass der Client aktualisiert werden muss.

**Comment by iradraconis** [comment]
Der erster Ansatz würde meines Erachtens erfordern, dass man die Kategorien im Menü dann durch einen Trenner sichtbar macht. Sonst führt die Darstellung nur zu Verwirrung. 

Die zweite Variante halte ich für gut, insbesondere weil es durch die alphabetische Darstellung auch für den Nutzer möglich ist, im Dialog für das Erstellen der eigenen Prompts eine Art Kategorisierung durch Namensgebung herzustellen. Die "Art" des Prompts summarize, chat, translate etc.) ist für die Darstellung gar nicht so wichtig, finde ich. Und wie gesagt, über die Namensgebung der Prompts könnte die Darstellung übersichtlich gemacht werden. Eine Unterscheidung in mitgelieferte und eigene Prompts wäre auch irgendwo noch sinnvoll... aber das dann vielleicht später :)

**Comment by iradraconis** [comment]
Ich merke gerade, dass die erste Methode viel einfacher ist :) Der Trenner liesse sich ja einfach bei der Generierung des PopupMenüs einbauen. Ich probiere mal

**Comment by iradraconis** [comment]
![Bildschirmfoto 2024-09-26 um 09 42 35](https://github.com/user-attachments/assets/9f854f94-1cd7-4b75-8867-c5a615e51d1e)

**Comment by iradraconis** [comment]
so zum Beispiel

**Comment by iradraconis** [comment]
ich bau das mal an den entsprechenden Stellen ein, mache einen Commit für den FeatureBranch und dann könntest du mal schauen. Ich finde es übersichtlicher. Die Zahl der Prompts wird je nach Kanzlei sicherlich deutlich größer sein.
