### ISSUE TITLE
[FEATURE] PDF zusammenführen - Inhaltsverzeichnis und Vorblatt optional machen

### ISSUE THREAD

**Issue by iradraconis** [jlawyerorg/j-lawyer-org#2579]
![2024-09-24 21 44 47](https://github.com/user-attachments/assets/e1a3f558-4f0b-483f-b89a-c540fa38b214)

**Comment by iradraconis** [comment]
Die Bedeutung dieses Tickets möchte ich noch einmal erläutern. Viele Mandanten bekommen es nicht hin, ihre Unterlagen als PDF-Dateien an die Kanzlei zu übermitteln. Was dann regelmäßig  kommt, sind mehrere Fotos, manchmal auch 20 Stück oder mehr. Diese können wir ja nun in PDF  konvertieren und in eine PDF-Datei zusammenführen. Nun benötigen wir in diesen Dokumenten kein  Deckblatt und kein Inhaltsverzeichnis. Diese Dokumente werden oft auch weitergeleitet an Gericht oder Staatsanwaltschaft oder sonst wen... Dann müsste die PDF also wieder mit einem externen Tool angefasst werden, welches das Entfernen von Seiten ermöglicht.

**Comment by j-dimension** [comment]
Für die 2.7 muss der Fokus jetzt erstmal auf dem Testen liegen, sonst ist das Oktober-Release in Gefahr (und beA hört auf zu funktionieren).

**Comment by iradraconis** [comment]
Für mich durch #2586 nicht mehr wichtig.

**Comment by clvnsch** [comment]
Stimmt, man kann die Seiten entfernen, entweder nun durch #2586 oder extern. Sind dann aber nicht die Seitenzahlen irreführend, oder starten diese erst ab der 3. Seite bei 1?

**Comment by iradraconis** [comment]
Wenn ich aus einer PDF Datei Seiten entferne, darf ich mich natürlich nicht mehr auf ein Inhaltsverzeichnis verlassen.
