### ISSUE TITLE
pdf drag und drop

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-org#2583]
Man kann Dokumente per drag und drop in den Dokumentenordner ziehen.  Man kann aus dem Dokumentenordner kein Dokument per drag und drop rausziehen. Im Scanordner geht beides nicht, weder rein noch raus. Ich arbeite mit pdf24pdf Icreator) wenn ich PDFs bearbeite oder einzelne Dokumente aus scans herausziehe. Dort soll man die Dokumente einfach per drag und drop hinziehen. Da das nicht geht, muss ich umständlich über den explorer auf den scanordner zugreifen und im Dokumentenordner gehts garnicht mit dem export per drag und drop...

**Comment by j-dimension** [comment]
Siehe #35 und #1218
