### ISSUE TITLE
[BUG] Mail Dialog: Beteiligte werden nicht angezeigt

### ISSUE THREAD

**Issue by iradraconis** [jlawyerorg/j-lawyer-org#2584]
Wenn ich in einer Akte eine E-Mail öffne und dann in dieser E-Mail auf Antworten klicke,  geht der Aktenbezug verloren. Ich kann die Vorlagen nicht nutzen,  weil keine Beteiligten in der Matrix verfügbar sind. Getestet mit Version 2.7.

**Comment by j-dimension** [comment]
Duplikat von #2326
