### ISSUE TITLE
[FEATURE] Im PDF Viewer einzelne Seiten löschen können

### ISSUE THREAD

**Issue by iradraconis** [jlawyerorg/j-lawyer-org#2586]
![Bildschirmfoto 2024-09-28 um 19 56 35](https://github.com/user-attachments/assets/7d5da84c-2ed3-42b1-a92b-aeedcff29b9b)

**Comment by Dickmaulruessler** [comment]
Wenn man verpeilt ist und sich aus Versehen verklickt: Kann man dann noch etwas retten?
Ihr habt wohl eine Sicherheitsabfrage eingeplant... Sehe ich das richtig? Das würde glaube ich auch ausreichen.

**Comment by iradraconis** [comment]
Eine Abfrage ist eingebaut
