### ISSUE TITLE
[BUG] Transkription erscheint unterhalb der Signatur. Soll oberhalb der Signatur eingefügt werden

### ISSUE THREAD

**Issue by iradraconis** [jlawyerorg/j-lawyer-org#2590]
Wenn aus dem Beteiligtenfenster heraus eine Mail versandt werden soll, landet die Transkription unterhalb der Signatur.

**Comment by iradraconis** [comment]
ja das ist auch super, und ich nutze das auch so schon intensiv. Das macht das Diktat sehr intuitiv. Aber beim Öffnen des Mail Dialogs müsste der cursor automatisch oberhalb der Signatur gesetzt werden. Das passiert noch nicht überall..

**Comment by j-dimension** [comment]
Nutzt Du eine Mailvorlage? Da gibt es einen {{CURSOR}}-Platzhalter.

**Comment by iradraconis** [comment]
ja. Beim Antworten muss der Cursor dann manuell gesetzt werden. Wir probieren mal weiter rum.

**Comment by iradraconis** [comment]
Das Problem tritt vor allem da auf, wo aus dem E-Mail Dialog heraus über Ingo auf "antworten" geklickt wird. Dann wird eine Antwort generiert, und per "übernehmen" eine neue Mail erstellt. Diese enthält die Mail, auf die geantwortet werden soll und darüber die Signatur. Der Ingo Text wird nun genau dazwischen eingefügt. Da hier noch keine Vorlage ausgewählt ist, kann ich über den Platzhalter CURSOR das Problem nicht lösen.

**Comment by iradraconis** [comment]
Fehler besteht noch in der 3.0.0.1 
Kriegen wir das noch gelöst vor dem Release? Nur bei gravierenden Bugs oder? 

Es geht vor allem um das hier: 

> Das Problem tritt vor allem da auf, wo aus dem E-Mail Dialog heraus über Ingo auf "antworten" geklickt wird. Dann wird eine Antwort generiert, und per "übernehmen" eine neue Mail erstellt. Diese enthält die Mail, auf die geantwortet werden soll und darüber die Signatur. Der Ingo Text wird nun genau dazwischen eingefügt. Da hier noch keine Vorlage ausgewählt ist, kann ich über den Platzhalter CURSOR das Problem nicht lösen.


=> die Funktion "Auf Email antworten" durch Ingo ist damit nur kompliziert zu nutzen, da der Text an einer Stelle landet, an der er nicht landen soll...

**Comment by j-dimension** [comment]
Nee, das wird nix mehr mit 3.0.0.1. Wir können ein Bug Fix-Release nachschieben, da wird sicher noch mehr entdeckt werden. 

Muss mich jetzt aber an die Doku setzen und habe keine Zeit mehr für Codeänderungen und das Installerbauen :-(

**Comment by j-dimension** [comment]
@iradraconis hier könnte ich ein zweites Paar Augen beim Testen benötigen, da ich selbst nicht mit Signaturen arbeite. Hoffe ich habe alle Szenarien erwischt.

**Comment by iradraconis** [comment]
Super! Klappt jetzt, wie es soll, zumindest in meinem Use Case.

Es werden zwar noch Zeilenumbrüche eingefügt, die in der Antwort von Ingo nicht mehr sein sollten, aber die können manuell entfernt werden.. Oder neues Ticket für später.
