### ISSUE TITLE
[FEATURE] Ingo: Sprachaufnahme analog zum E-Mail-Fenster auch in Aktennotiz

### ISSUE THREAD

**Issue by iradraconis** [jlawyerorg/j-lawyer-org#2595]
Das iterative Diktieren und Transkribieren wäre in der Aktennotiz eine große Hilfe. Der Unterschied zu einer Sprachmemo liegt darin, dass das Ergebnis visuell verfolgt werden kann und deshalb nicht so viel kognitiven Aufwand erfordert :) Einen Schriftsatz komplett runter zu diktieren braucht viel Übung. So könnte das Diktat kleinschrittiger erfolgen oder in einer Besprechung könnten einfacher Abschnitte generiert werden. 

Mandant sitzt vor einem und man möchte eben Teile des Sachverhalts aufnehmen. Das ginge auch über die Sprachmemo und dann Pausenfunktion aber dort lässt sich nichts rauslöschen.

**Comment by j-dimension** [comment]
@iradraconis ich habe noch ein paar minimale Anpassungen vorgenommen und hoffe das ist okay für Dich :-)

**Comment by iradraconis** [comment]
@j-dimension ja klar. ich war froh, dass es überhaupt lief :)
