### ISSUE TITLE
[BUG] Messaging: Zeilenumbruch lässt sich nicht in einer Zeile sondern nur am Ende einfügen

### ISSUE THREAD

**Issue by iradraconis** [jlawyerorg/j-lawyer-org#2596]
Beispiel: ich diktiere eine lämgere Nachricht und habe den kompletten Text in einer Zeile. Wenn ich jetzt  die Zeile umbrechen möchte, innerhalb des Textes, damit es für mich noch einmal übersichtlicher wird, den Text zu korrigieren, wird zwar ein Zeilenumbruch eingefügt, aber der Text bricht nicht um. Ich kann nur einen Zeileneinbruch einfügen und dann weiterschreiben. Ich hoffe, das ist verständlich ausgedrückt

Am besten wäre es, wenn der Text automatisch am Ende des Fensters umbricht

**Comment by iradraconis** [comment]
https://github.com/user-attachments/assets/73684f12-f03e-4342-ae10-8a1a86891708

**Comment by j-dimension** [comment]
Ah! Ich dachte es geht um Ingo-Themen und konnte mit "Aktenchat" nichts anfangen. Danke!

**Comment by iradraconis** [comment]
Sorry 😬 war etwas unscharf formuliert..
