### ISSUE TITLE
[BUG] Dokumenten-Tab: Pfeiltasten-Navigation setzt aus, wenn neuer PDF-Editor geöffnet wird

### ISSUE THREAD

**Issue by Dickmaulruessler** [jlawyerorg/j-lawyer-org#2597]
Wenn man mit der oben/unten Pfeiltaste wandert, hängt sich diese Funktion aus mir nicht nachvollziehbaren Gründen an verschiedenen Stellen auf. Wenn man dann auf die Pfeiltasten klickt, tut sich gar nichts mehr. 

(noch nicht ausreichend getestet, daher erst einmal nur am Rande: ´habe den Eindruck dass PDF-Seiten jetzt langsamer laden; auch PDF Dokumente, die man vor einer Minute schon betrachtet und dann wieder verlassen hatte, laden beim erneuten Betrachten recht lange. Ich beobachte das noch weiter und erstelle ggf. ein gesondertes Ticket). 

Dieser Bug bezieht sich auf die Version 2.7.0.0
Vorher trat dieser Fehler nicht auf.

**Comment by iradraconis** [comment]
> (noch nicht ausreichend getestet, daher erst einmal nur am Rande: ´habe den Eindruck dass PDF-Seiten jetzt langsamer laden; auch PDF Dokumente, die man vor einer Minute schon betrachtet und dann wieder verlassen hatte, laden beim erneuten Betrachten recht lange. Ich beobachte das noch weiter und erstelle ggf. ein gesondertes Ticket).
> 
> Dieser Bug bezieht sich auf die Version 2.7.0.0 Vorher trat dieser Fehler nicht auf.

#2570

**Comment by j-dimension** [comment]
> Wenn man mit der oben/unten Pfeiltaste wandert, hängt sich diese Funktion aus mir nicht nachvollziehbaren Gründen an verschiedenen Stellen auf. Wenn man dann auf die Pfeiltasten klickt, tut sich gar nichts mehr.

Hier scheint einfach der Fokus auf einem anderen Oberflächenelement zu landen, sodass die Pfeiltastenanschläge nicht mehr in der Dokumentenliste landen.
