### ISSUE TITLE
[BUG] WV-Reihenfolge ändern: Unerledigte WV immer vorne (egal welch Datum)

### ISSUE THREAD

**Issue by Dickmaulruessler** [jlawyerorg/j-lawyer-org#2603]
Wiedervorlage-Reihenfolge: Unerledigte immer vor erledigten - unabhängig vom Datum.
Siehe Beispiel dort (vom 7.10.): 
Die noch nicht erledigte Wiedervorlage vom 3.10, sollte **_vor_** der (vorzeitig) erledigten vom 16.10. stehen. 

![jdfklösjlköfjas](https://github.com/user-attachments/assets/3c3a4af0-1564-4fd9-bb7a-195cedde4cfe)

**Comment by iradraconis** [comment]
ich glaube nicht, dass das ein Bug ist. Es wird nach Datum sortiert in deinem Beispiel. Sortiere mal durch Klick auf "erledigt", dann sollte das passen.

**Comment by Dickmaulruessler** [comment]
hmmmm..... 
die Sortierung wird aber nicht gespeichert.... Weder in dieser einen Akte, noch im System (was ich favorisieren würde). 

Wenn es eine Standard-Sortierung gibt, sollte diese glaube ich die unerledigten vorne haben. 
@iradraconis Ticket doch wieder öffnen?

**Comment by iradraconis** [comment]
Kommt es oft vor, dass die Einträge unübersichtlich sind, weil eine erledigte über einer unerledigten WV steht? 
Schließlich handelt es sich ja um ein "Kalenderblatt". Ein Kalender ist ja per definition immer "chronologisch". Und wer im Einzelfall konkret anders sortieren muss, kann das ja tun.

**Comment by Dickmaulruessler** [comment]
Ich sehe es eher als eine To-do-Liste, daher die Priorität auf das "erledigt". 

Dort stehen bei mir dann auch einmal sehr langfristige WV drin (z.B. Jahresbericht in einer Betreuungssache) und zwischendurch gibt es immer kleine WV. Daher diese Reihenfolge, die bei mir häufiger so ist. 

Warum eine erledigte Sache, die man ja nur noch als "Historie" betrachten kann, jemals vor einer unerledigten stehen sollte, erschließt sich mir nicht. Nun ja, ich könnte sie natürlich immer manuell löschen (dann macht der "erledigt" Button aber keinen Sinn). 

Aber das ist wohl Geschmackssache. 
Ich lasse das geschlossen, es sei denn andere Personen sehen das wie ich.

**Comment by iradraconis** [comment]
> Ich sehe es eher als eine To-do-Liste, daher die Priorität auf das "erledigt".

Aber der Reiter auf dem Tab heißt doch Kalender und nicht To-dos :)

Gegenbeispiel: es werden Termine mit dem Gericht abgestimmt. Die Termine erledigen sich, es wird ein neuer Termin VORHER vereinbart. Dann steht im Kalenderblatt der erledigte auch oberhalb des nicht erledigten Termins. Gerade da ist die Chronologie ja auch, wie bei einem Kalender zu erwarten, abgebildet. Ich verstehe deinen Wunsch. 

Das wäre dann also ein Featurewunsch, dass jedenfalls die Sortierung in der Akte (am Nutzer) gespeichert wird?

**Comment by j-dimension** [comment]
Ich persönlich benötige die chronologische Darstellung. Insbesondere mit der Möglichkeit, bei Erstellung eines Eintrages einen verbundenen zweiten Eintrag zu erstellen, hilft die chronologisch Darstellung, den Überblick zu behalten.

**Comment by Dickmaulruessler** [comment]
> 
> Aber der Reiter auf dem Tab heißt doch Kalender und nicht To-dos :)
> 

Das überzeugt mich! (ich nutze die Termin-Funktion nicht). Dann ist das chronologisch natürlich schon richtig. 

Ich werde mir glaube ich angewöhnen, erledigte WV-Einträge zu löschen. 

Bleibt allenfalls die Frage, ob die letzte Sortierung am Client gespeichert werden sollte oder ob erledigte WV und Fristen in einem schwachen Grau erscheinen sollten. 
Ich belasse es erst einmal hierbei und eröffne selbst dafür kein neues Ticket, würde mich aber ein ein Ticket eines weiteren Nutzers dranhängen.

**Comment by stm9x9** [comment]
Das mit dem verbundenen Eintrag muß ich mir erstmal noch angucken. Aber grundsätzlich wäre ich auch für die Standardeinstellung primäres Sortierkriterium: nicht erledigt / erledigt und sekundäres Kriterium: Datum. Oder untechnisch gesprochen: erst alle offenen Fristen chronologisch und dahinter alle erledigten chronologisch.

Bei mir kommt es jedenfalls sehr oft vor, daß weiter in die Zukunft liegende Fristen schon erledigt sind (entweder weil ich fleißig war :-D) oder aber eher weil ich in einer Akte mehrere Verfahren (Klage & Eilverfahren zB. und dann noch der Beratungshilfeantrag etc) habe und dann in in dem einen schon Sachen erledigt sind, während weiter früher gesetzte Fristen noch offen sind.
