### ISSUE TITLE
[BUG] Beim Diktieren in Mails werdenZeilenumbrüche eingefügt, die nicht sein sollten.

### ISSUE THREAD

**Issue by iradraconis** [jlawyerorg/j-lawyer-org#2604]

**Comment by j-dimension** [comment]
Das liefert whisper so. Ich kann den stringreplace-processor im Ingo anpassen, sodass Zeilenumbrüche entfernt werden. Wären dann aber ALLE Umbrüche.

**Comment by iradraconis** [comment]
wenn der String replace-processor dann "neue Zeile" als Zeilenumbruch versteht, wäre das Problem sehr elegang gelöst. Geht das? Momentan ist es halt eine aufwendige Korrektur von Mails, um die Umbrüche zu entfernen. Tritt das bei dir nicht auf?

**Comment by j-dimension** [comment]
In der kommenden Ingo-Version habe ich eine dedizierte Transkriptions-Capabilty, die nur für die Diktate verwendet wird. Dort habe ich jetzt das Entfernen der Zeilenumbrüche aufgenommen. Jedoch läuft danach noch ein Modell, welches sinnvolle Formatierungen selbständig vornehmen soll. 

Prompt:

`Du bist Rechtsanwalt. Korrigiere die Rechtschreibung in folgendem Text. Wenn Du eine Anrede oder eine Grußformel erkennst, so gib diese in einem separaten Absatz aus. Gib ausschließlich den angepassten Text aus. Lasse Erläuterungen und Hinweise weg. Hier der Text:`

Das müssen wir mal mit ein paar echten Diktaten ausprobieren und ggf. anpassen, oder den separaten Modell-Aufruf nach der Transkription wieder entfernen.

**Comment by iradraconis** [comment]
Führt der separate Modellaufruf nicht zu einer erheblichen Verzögerung bei der Ausgabe? Ich bin mir nicht sicher, ob man nicht auch Whisper so konfigurieren kann, dass diese Zeilenumbrüche nicht eingefügt werden. Ich habe dieses Verhalten  jedenfalls bei keiner anderen Diktiersoftware festgestellt, die Whisper nutzt. Vor allem: der hat den gesamten Textblock so raus. Wenn lediglich nach einzelnen (sprachlich sinnvollen) Abschnitten ein Zeilenumbruch erfolgen würde, hätte ich noch Verständnis dafür, was Whisper dort macht... Das kann aber jedenfalls von Whisper so nicht gewollt sein. Möglicherweise lässt sich das noch programmatisch im Client lösen ohne weiteres Modell?

**Comment by j-dimension** [comment]
> Führt der separate Modellaufruf nicht zu einer erheblichen Verzögerung bei der Ausgabe?

Das müssen wir mal testen, wenn der neue Ingo auf den produktiven Server ausgerollt ist. Wenn es zu lange dauert, kann man das ja konfigurativ wieder entfernen. 



> Ich bin mir nicht sicher, ob man nicht auch Whisper so konfigurieren kann, dass diese Zeilenumbrüche nicht eingefügt werden.

Ich habe keine Möglichkeit gefunden, aber offene Tickets, die das selbe Problem schildern.

Die Zeilenumbrüche können ja mit dem stringreplaceprocessor entfernt werden. Es wäre eben nur toll, wenn Anrede und Grussformel eben separat stehen würden. Sonst muss man immer nachformatieren.



> Möglicherweise lässt sich das noch programmatisch im Client lösen ohne weiteres Modell?

Eher im Ingo selbst, per Konfiguration. Wie erwähnt.
