### ISSUE TITLE
[FEATURE] Zwischenspeicherung und Wiederherstellung von E-Mail-Text bei versehentlichem Löschen

### ISSUE THREAD

**Issue by ms00st** [jlawyerorg/j-lawyer-org#2605]
Beim Schreiben einer E-Mail sollte der Text automatisch zwischengespeichert werden. Falls der Nutzer versehentlich den Text löscht, beispielsweise durch das Drücken einer falschen Tastenkombination (wie es bei mir beim Kopieren der E-Mail passiert ist), sollte der Text durch die übliche Rückgängig-Funktion (z.B. bei Apple: Command + Z) wiederhergestellt werden können.

**Comment by iradraconis** [comment]
Das betrifft auch den Fall, dass man eine andere Vorlage für die E-Mail auswählt, dann ist auch der vorher geschriebene Text komplett weg.

**Comment by j-dimension** [comment]
Ich bin hier ein wenig lost. Ich weiß nicht genau wie die Thunderbird-Integration die Endpunkte orchestrieren würde - mir erscheint Folgendes sinnvoll:

- Auflisten aller Vorlagen (eigentlich nur Namen der Vorlagen interessant)
- Nutzer wählt eine aus
- Vorlage wird "ausgefüllt" angefordert

Die Änderungen hier bewirken, dass beim Auflisten der Vorlagen bereits alle Vorlagen ausgefüllt werden, das kann eine ziemliche Datenbankabfragemenge in kürzester Zeit generieren. 

Das Ersetzen der Platzhalter ist Code der bereits vorhanden ist, lass uns den nachnutzen. 

@iradraconis darf ich Hand anlegen?
