### ISSUE TITLE
eeB-Speicherung

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-org#2619]
Wenn man das angeforderte EEB abgibt bei Bea und dann versehentlich das Abspeichern des EEB abbricht - ist es weg (zumindest finde ich es nicht mehr und erneut abgeben geht (zu Rech) nicht, gibt (im Moment) eine Fehlermeldung. Das EEB sollte aber m.E. nach der Abgabe zumindest im Papierkorb noch erhalten bleiben, um den Fehler korrigieren zu können.

**Comment by j-dimension** [comment]
@Mucki526 wieso im Papierkorb? Nach Versand ist es in den gesendeten Elementen des beA-Postfaches.

**Comment by Mucki526** [comment]
Cool :-) - habe ich noch nie gebraucht. Danke. Peinlich. Hier schließen....
