### ISSUE TITLE
[e-mail] Mehrere Scans auf einmal

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-org#262]
Mehrere scans auf einmal in eine Akte verschieben - fehlt, ggf. mit Namensvergabe je Datei bei gleichzeitiger Vorschau. Beispiel, Gegner schickt 20 Dateien zur Erfüllung einer Auskunft. Alle gehören in eine Akte. Könnte auch über BEA so passieren...

**Comment by j-dimension** [comment]
@RA-crm

**Comment by j-dimension** [comment]
Ebenfalls für E-Mail-Posteingang

**Comment by RA-crm** [comment]
Bie Stapelverabeitung der scans, mails oder anhänge sollte gleicher Präfix vergeben werden können.

**Comment by Dickmaulruessler** [comment]
Supi! Danke!
