### ISSUE TITLE
Verschieben von gesendeten Nachrichten in Bea in Akte funktioniert nicht.

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-org#2620]
![grafik](https://github.com/user-attachments/assets/660f7ac6-76c7-41e5-86d0-86f07e3157c0)

**Comment by Mucki526** [comment]
Oder mache ich wieder was falsch...?

**Comment by j-dimension** [comment]
Das ist eine Beschränkung des beA. Du solltest die Nachricht aus den gesendeten Elementen aber zur Akte speichern können.
