### ISSUE TITLE
Rechnungserstellung, wenn am Nutzer keine Bankdaten gepflegt

### ISSUE THREAD

**Issue by SteRoe** [jlawyerorg/j-lawyer-org#2625]
**Describe the tasks / Aufgabenbeschreibung**
(todo: a description of the task / eine Beschreibung der Aufgabe)
Ab Version 2.7 / 3.0 hängen die Bankdaten für Rechnungen / QR-Codes an den Benutzerkonten. Diese müssen für jeden Benutzer, der das nutzt, eingetragen sein. Anderenfalls funktioniert {{BEL_TABELLE}} und {{BEL_GIROCODE}} nicht. Es kommt dort auch keine Hinweis. Einfach nichts. Nachdem ich die Benutzerkonten mit Information befüllt habe, können wieder Rechnungen erzeugt werden.

Ein kurzer Hinweis in den Release Notes kann andere Anwender vor der Sucherei bewahren.

**Comment by j-dimension** [comment]
Beim Erstellen des Rechnungsdokuments erhalte ich eine Fehlermeldung, dass BIC oder IBAN leer ist, es gibt also eine Rückmeldung an den User. 

Bitte nochmal die konkrete Bediensequenz erläutern, damit ich es nachvollziehen kann. Danke!

**Comment by SteRoe** [comment]
Es gibt ein Template mit {{BELTABELLE}} und {{BEL_GIROCODE}}, welches bis Version 2.6 funktioniert hat. Dieses funktionierte bei 2.7 und 3.0 nicht mehr. Es kam auch keine Fehlermeldung (Windows 10/LibreOffice). Nachdem alles im Benutzer eingetragen ist, funktioniert es wieder.

**Comment by j-dimension** [comment]
Falls es einen Weg gibt, das Verhalten zu reproduzieren, habe ich großes Interesse. 

Wenn ich alle Bankinformationen entferne, bekomme ich besagte Fehlermeldung, die darauf hinweist, dass die Daten fehlen.

**Comment by SteRoe** [comment]
Ich habe es soeben nochmal ohne Bankverbindung im Benutzer probiert und erhalte nun auch: "Girocode kann nicht erstellt werden - BIC des Absenders ist leer". Was vorher passiert war - ???

**Comment by j-dimension** [comment]
So sollte es sein. Ich habe diese Meldung gestern noch um die Information erweitert, wo man die Daten pflegen kann.

Mache hier erstmal zu.
