### ISSUE TITLE
[BUG] Hinweistext PDF-Seiten splitten

### ISSUE THREAD

**Issue by Dickmaulruessler** [jlawyerorg/j-lawyer-org#2631]
Sehr cool, das neue Feature zum Splitten von bereits vorhandenen PDF-Seiten im Dokumentenreiter!
Danke an @iradraconis !

Mini-Anmerkung:
Hinweistext vielleicht ändern zu "Splitten **nach**... (Seitenzahlen eingeben, kommagetrennt)". 

Aus der bisherigen Erklärung weiß man nicht, wie sich die Eingabe auswirkt, also wo gesplittet wird.
Gut, ich habe es jetzt ausprobiert - war begeistert - und weiß es nun. Aber vielleicht ist der Hinweis sinnnvoll.

**Comment by iradraconis** [comment]
Da lässt sich was machen :)
