### ISSUE TITLE
PDF-Export: Inhaltsverzeichnis, Deckblatt, Seitenzahlen optional

### ISSUE THREAD

**Issue by clvnsch** [jlawyerorg/j-lawyer-org#2638]
#104 könnte erweitert werden

Ich würde es bevorzugen wenn man hier das Deckblatt mit den Akteninformationen, das Inhaltsverzeichnis und die Seitenzahlen abwählen, also optional machen könnte.

Dann kann diese Funktion auch genutzt werden um Anschreiben mit Anlagen zu erstellen. Hier benötigt man weder das Inhaltsverzeichnis noch das Deckblatt. Wenn man dann hier auch keine "neuen" Seitenzahlen hat, sind diese auch nicht über dem Text der eigenen Schreiben oder der Anlagen ist. 

Hier z.B.: zwei Beispiele, ich denk dies könnte den ein oder anderen Empfänger (im Sinne der Dokumentenerstellung mit Anlagen) verwirren:

![Bildschirmfoto 2024-11-01 um 12 47 01](https://github.com/user-attachments/assets/1dd27d36-f23f-499c-9b81-ad5ef8073dfc)
![Bildschirmfoto 2024-11-01 um 12 46 30](https://github.com/user-attachments/assets/d312e915-c35d-4203-b3cf-7d9667bd3ca7)

Wenn zumindest die Seitenzahlen optional machen könnte, die ersten beiden Seiten dann löscht, dies kann die Software mit der Vers. 3 ja nun, könnte man die Funktion auch zur Erstellung von Dokumenten mit Anlagen erstellen.

Oft muss man die Dateien erst aus der Akte exportieren, alle Dokumente zusammenfügen und wieder in die Akte speichern. Dies würde hiermit entfallen und ist sicher für viele eine sinnvolle Erweiterung.

**Comment by j-dimension** [comment]
@iradraconis super! Vielen Dank!
