### ISSUE TITLE
[BUG] PDF-Vorschau verschwommen

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#2643]
weil ich das gerade in der Präsentation höre: Bei mir ist seit Jahr und Tag die pdf-Vorschau doch recht erheblich verschwommen :-( 

![image](https://github.com/user-attachments/assets/3c9403de-1197-4efc-815a-9b38a10d53a2)

Windows 10
2560x1440
benutzerdefinierte Skalierung 120%

Oberflächenskalierung im Programm 100%

**Comment by Dickmaulruessler** [comment]
#2630
