### ISSUE TITLE
J-Lawyer 3.0 BEA Anmeldung mit Softwarezertifikat geht nicht mehr....

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-org#2645]
![grafik](https://github.com/user-attachments/assets/6b06b772-4346-410d-bb92-cb2c0713b75e)

**NOTE: Please search existing tickets to avoid duplicates **
**HINWEIS: Bitte vorab die Ticketsuche verwenden, um Doppeleinträge zu vermeiden **

**Describe the bug / Fehlerbeschreibung**
(todo: a description of the bug / eine Beschreibung des Fehlers)

**To Reproduce / Schritte zum Nachvollziehen**

1. Go to / Gehe zu '...'
2. Klicke auf / Click on '....'
4. Error message / Fehlermeldung: '...'

**Expected behavior / Erwartetes Verhalten**
Eine Beschreibung des erwarteten Verhaltens.

**Screenshots**
Falls relevant, Screenshot beifügen.

**Environment / verwendete Umgebung:**
 - OS / Betriebssystem:
 - j-lawyer.org Version:

**Additional context / Sonstiges**

**Comment by j-dimension** [comment]
> Systemneustart, Serverneustart oder Neuanmeldung des Zertifikats im Client hilft nicht....

weil es eine Störung bei der BRAK gibt. Bitte **IMMER** vorab die Störungsmeldungen prüfen.
