### ISSUE TITLE
[BUG] Fehler beim Drehen der PDF-Ansicht

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-org#2646]
Beim Versuch die AGB einer Bank, übersandt als PDF, zu drehen in der Ansicht gab es folgende Fehlermeldung:

![grafik](https://github.com/user-attachments/assets/6e657ed2-360b-4168-8285-dece7e9b1275)

**NOTE: Please search existing tickets to avoid duplicates **
**HINWEIS: Bitte vorab die Ticketsuche verwenden, um Doppeleinträge zu vermeiden **

**Describe the bug / Fehlerbeschreibung**
(todo: a description of the bug / eine Beschreibung des Fehlers)

**To Reproduce / Schritte zum Nachvollziehen**

1. Go to / Gehe zu '...'
2. Klicke auf / Click on '....'
4. Error message / Fehlermeldung: '...'

**Expected behavior / Erwartetes Verhalten**
Eine Beschreibung des erwarteten Verhaltens.

**Screenshots**
Falls relevant, Screenshot beifügen.

**Environment / verwendete Umgebung:**
 - OS / Betriebssystem:
 - j-lawyer.org Version:

**Additional context / Sonstiges**

**Comment by j-dimension** [comment]
@Mucki526 Hier bräuchte ich mal das PDF - das scheint in irgendeiner Form "geschützt" zu sein.

**Comment by j-dimension** [comment]
Es handelt sich um ein verschlüsseltes oder signiertes und geschütztes PDF. Änderungen an solchen Dokumenten sind nur nach Aufheben des Schutzes (idR mittels Passwort) möglich. 

Ohne ein Beispiel-PDF komme ich hier nicht weiter.
