### ISSUE TITLE
Rechnung erstellen aus Position

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-org#2651]
Bisher (V2.61) konnte ich unter Finanzen - Reiter dokumente eine Vorlage auswählen, um eine Kostennote für meinen Mandanten zu erstellen aus mit Belegnummer etc. Jetzt kann man noch Rechnungen erstellen, aber muss auswählen "an Unternehmer" oder "an öffentliche Auftraggeber". Aber den Button, einfach eine Kostennote für meinen Mandanten (Verbraucher) zu erstellen, finde ich nicht mehr? 

**NOTE: Please search existing tickets to avoid duplicates **
**HINWEIS: Bitte vorab die Ticketsuche verwenden, um Doppeleinträge zu vermeiden **

**Describe the bug / Fehlerbeschreibung**
(todo: a description of the bug / eine Beschreibung des Fehlers)

**To Reproduce / Schritte zum Nachvollziehen**

1. Go to / Gehe zu '...'
2. Klicke auf / Click on '....'
4. Error message / Fehlermeldung: '...'

**Expected behavior / Erwartetes Verhalten**
Eine Beschreibung des erwarteten Verhaltens.

**Screenshots**
Falls relevant, Screenshot beifügen.

**Environment / verwendete Umgebung:**
 - OS / Betriebssystem:
 - j-lawyer.org Version:

**Additional context / Sonstiges**

**Comment by j-dimension** [comment]
Du kannst an Verbraucher ebenfalls eine B2B-E-Rechnung senden. Das Steuerbüro wird sich darüber freuen, da dann Deine Rechnungen automatisch verbucht werden können.
