### ISSUE TITLE
[BUG] Nicht ausgewählte "Deckblätter" bei PDF-Verknüpfung

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-org#2652]
Bei der neuen Verknüpfung von Dokumenten zu PDF wird in die neue Datei ein Deckblatt mit Aktennummer eingebunden und eine weitere Seite mit Daten, welche Dokumente verknüpft wurden. Dies sollte nicht passieren, da ich mit der Funktion Dokumente generiere, die ich versenden will, die diese Information nicht benötigen oder erst garnicht haben sollen.

Beispiel Mandant schickt 10 PDF mit Kontoauszügen per mail für VKH-Unterlagen als "Anlage Kontoauszüge", die ich verknüpfen und als Anlage zum Antrag versenden will. 

Vorschlag die Deckblältter sollten abschaltbar sein oder zumindest gesondert zum neuen Dokument gespeichert werden.

**NOTE: Please search existing tickets to avoid duplicates **
**HINWEIS: Bitte vorab die Ticketsuche verwenden, um Doppeleinträge zu vermeiden **

**Describe the bug / Fehlerbeschreibung**
(todo: a description of the bug / eine Beschreibung des Fehlers)

**To Reproduce / Schritte zum Nachvollziehen**

1. Go to / Gehe zu '...'
2. Klicke auf / Click on '....'
4. Error message / Fehlermeldung: '...'

**Expected behavior / Erwartetes Verhalten**
Eine Beschreibung des erwarteten Verhaltens.

**Screenshots**
Falls relevant, Screenshot beifügen.

**Environment / verwendete Umgebung:**
 - OS / Betriebssystem:
 - j-lawyer.org Version:

**Additional context / Sonstiges**

**Comment by Dickmaulruessler** [comment]
Dazu gibt es schon ein Ticket. 
#2638 

Schließt du das Ticket bitte von selbst wieder?
