### ISSUE TITLE
[FEATURE] Teilung von PDF im Scaneingang

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-org#2653]
Ich wollte gerade ein PDF teilen im Scanordner, da wird mir angeboten nach Seite 1, 3, 5, 10, aber eine andere Teilung ist nicht möglich (ich wollte das Formular von den Anlagen nach Seite 4 trennen). Die Seitenzahl zur Trennung sollte frei wählbar sein.

**Comment by j-dimension** [comment]
Unklar, wie sich das von #2654 abgrenzt.

**Comment by j-dimension** [comment]
Duplikat von #2654
