### ISSUE TITLE
Möglichkeit auf Löschung falscher Einträge in der Aktenhistorie durch Admin

### ISSUE THREAD

**Issue by Goodadvicer** [jlawyerorg/j-lawyer-org#266]
Möglichkeit auf Löschung falscher Einträge in der Aktenhistorie durch Admin.

**Comment by j-dimension** [comment]
Gilt das nur für manuell erstellte Historieneinträge?

**Comment by Goodadvicer** [comment]
Vorschlag gilt ebenfalls für die automatischen Einträge.

**Comment by j-dimension** [comment]
Danke. In diesem Fall muss ich nachfragen: was wäre denn dann ein "falscher" Eintrag? Das System schreibt ja nur Aktionen in die Historie, die vom Nutzer so ausgeführt wurden.

Was wäre ein praktisches Beispiel?

**Comment by Goodadvicer** [comment]
Als Beispiel wenn aus Versehen, ein Dokument erstellt oder hinzugefügt wird, welches aber nicht zur entsprechenden Akte gehört. Der Admin sollte umfassende Systempflege-Berechtigungen erhalten.

**Comment by stm9x9** [comment]
Ich plädiere dann aber statt Löschen für ein Ausblenden / Maskieren des Eintrags. Wenn wir hier Löschungen zulassen, dann schmälert das den Beweiswert zb hinsichtlich Aktionen mit Fristen?
