### ISSUE TITLE
[FEATURE] Zeitstempel Etiketten auf Desktop

### ISSUE THREAD

**Issue by Linkki2021** [jlawyerorg/j-lawyer-org#2663]
Auf dem Desktop gibt es die Ansicht "Nach Etikett". Bei großen Datenmengen wäre es hier hilfreich, wenn man wüsste, wann ein Etikett gesetzt wurde, zB entweder hinter dem Etikett in Klammern oder als Tooltip.

Tüpfelchen auf dem i wäre eine Sortierfunktion von alt nach neu oder andersherum. Oder zumindest ein Default nach zeitlicher Reihenfolge. Derzeit bin ich mir gar nicht sicher, in welcher Reihenfolge die Dinge dort angezeigt werden.

-------------------- @j-dimension 2024-11-26 ----------------------------------

- [x] Erweiterung Datenbank und Persistenzlogik für Aktenetiketten
- [x] Erweiterung Datenbank und Persistenzlogik für Dokumentetiketten
- [x] Upgradescript für bestehende Etiketten (Aktivierungsdatum auf aktuelles Datum setzen)
- [x] erweiterter Tooltip für Etikettenbuttons an Akte und Dokument
- [x] erweiterte Tooltips für "nach Etikett" auf dem Desktop

**Comment by j-dimension** [comment]
Anzeige auf Desktop: 

![grafik](https://github.com/user-attachments/assets/6f6702d6-995a-4a57-956e-039d42db41e2)

**Comment by j-dimension** [comment]
Anzeige an jeden Akten- und Dokumentetikett, als Tooltip: 

![grafik](https://github.com/user-attachments/assets/268b77f2-f5c7-481d-9e3e-a936975a4afa)

**Comment by Dickmaulruessler** [comment]
Nicht genau zum Thema, aber betreffend "Etiketten" und "große Datenmengen"
https://github.com/jlawyerorg/j-lawyer-org/issues/1983

**Comment by Linkki2021** [comment]
An mehrere Etiketten für ein Dokument hatte ich nicht gedacht. Dann würde ich die aktive Sortierung mal außen vor lassen und erstmal mit den Tooltips starten.

Wie wäre als automatisches Default ein A-Z oder Z-A gemessen an der "ältesten" Aktivierung? Oder ist das bereits die heutige Praxis?

**Comment by j-dimension** [comment]
Ich habe nun eine Sortierung wie folgt hinzugefügt:

- etikettierte Akten, zeitlich absteigend
- etikettierte Dokumente, zeitlich absteigend nach dem zuletzt gesetzten Etikett (wenn es mehrere gibt)

**Comment by Dickmaulruessler** [comment]
> Ich habe nun eine Sortierung wie folgt hinzugefügt:
> 
>     * etikettierte Akten, zeitlich absteigend
> 
 
Worauf bezieht sich das "zeitlich"?

**Comment by j-dimension** [comment]
> Worauf bezieht sich das "zeitlich"?

im Fall der Akten auf das Änderungsdatum

**Comment by j-dimension** [comment]
Referenz zu #2985
