### ISSUE TITLE
[BUG] Aktenkonto - Buchungen zusätzlicher "Anwalt" als unbekannt

### ISSUE THREAD

**Issue by iradraconis** [jlawyerorg/j-lawyer-org#2664]
In unserer Kanzlei sind 2 Anwälte tätig. In der Nutzerverwaltung sind auch nur 2 Personen mit dem Haken bei "ist Anwalt" versehen. In der Auswertung "Aktenkonto - Buchungen erscheinen die beiden Berufsträger mit ihren Buchungen in ihrer Spalte und in einer weiteren Spalte "unbekannt" sind "0,00" Euro angegeben. Haben wir irgendwo etwas falsch konfiguriert oder ist das ein Fehler?

**Comment by j-dimension** [comment]
Die Ausgabe ist okay so. Ausgegeben werden dort ja die Angaben "Anwalt" an der jeweiligen Akte. Und da es Installationen gibt, wo Anwalt / Sachbearbeiter nicht durchgehend gepflegt werden, muss es eine Art Sammelpott geben für alle Akten, deren Verantwortlichkeit unklar ist. Wenn bei Euch dort 0 steht, heißt das dass Ihr alles sauber aufgesetzt habt.
