### ISSUE TITLE
[BUG] Datensicherung löscht andere Ordner im Sicherungsverzeichnis

### ISSUE THREAD

**Issue by Dickmaulruessler** [jlawyerorg/j-lawyer-org#2673]
Ich nutze die Datensicherung unter "Administration" / "Datensicherung" / "Jetzt sichern" . 
Gesichert wird bei mir auf einen USB-Stick an den unter "Synchronisation" angegebenen Ort (bei mir file://Z:\ )

Nach Durchführung der Datensicherung werden nicht zu j-lawyer dazugehörige Daten auf dem Stick gelöscht. In meinem Fall wollte ich den USB-Stick an einem anderen Ort lagern (ich habe mehrere USB-Sticks die ich wechselnd verwende) und wollte auch ein Backup von meinem Outlook-Ordner dazu packen. Dieser Outlook-Ordner wurde von j-lawyer gelöscht. 

Ist das so beabsichtigt? Ich hätte dieses Verhalten nicht erwartet.

**Comment by j-dimension** [comment]
Das ist so beabsichtigt. Die Angabe von Z:\ (oder was auch immer) gibt an, dieses Verzeichnis als Ziel der Synchro zu verwenden. Da beim Löschen von Akten die Verzeichnisse auch aus der Sicherung verschwinden, müssen beim Synchronisieren in der Senke diejenigen Verzeichnisse gelöscht werden, die lokal nicht mehr existieren. 

Bei Nutzung eines Sticks, der nicht ausschließlich für die Backups verwendet wird, sollte ein Unterverzeichnis angegeben werden.
