### ISSUE TITLE
[FEATURE] Sanduhr für Ingo

### ISSUE THREAD

**Issue by SteRoe** [jlawyerorg/j-lawyer-org#2674]
**Welches Problem soll durch die Erweiterung / Verbesserung gelöst werden?**
Wenn Ingo "nachdenkt" (z.B. beim Diktieren), ist das nicht sichtbar.

**Beschreibe die gewünschte Lösung**
 Es wäre gut, wenn ein Aktivitätsanzeiger (Sanduhr etc.) eingeblendet wird, damit klar ist, da kommt noch etwas...

**Comment by j-dimension** [comment]
Wo genau? Nach dem Stoppen des Diktats stoppt die Zeit und es erscheint eine Sanduhr.

**Comment by SteRoe** [comment]
Sorry, das Ticket kann wieder weg. Hier ist auch eine Sanduhr auf Ubuntu. Windows teste ich gelegentlich nochmals. Von dort kam der Bericht. Asche auf mein Haupt.

**Comment by j-dimension** [comment]
👍
