### ISSUE TITLE
Verschlüsselte PDF

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-org#268]
Mir fehlte heute die Möglichkeit eine Datei als verschlüsseltes PDF in der Akte abzulegen. Man muss es erst verschlüsseln, dann munter wieder importieren....

**Comment by j-dimension** [comment]
Was wäre hier der Anwendungsfall? Bei Versand kann man es verschlüsseln. 

Zu welchem Zweck würde man ein Dokument sowohl im Original als auch verschlüsselt in der Akte haben wollen?

**Comment by j-dimension** [comment]
Schließe wg. fehlender Rückmeldung.

**Comment by stm9x9** [comment]
es könnte zb bei der Strafverteidigung von KiPo notwendig / sinnvoll sein. Da darf dann wirklich nur der sachbearbeitende Anwalt auf Beweismitteldateien zugreifen können.

**Comment by Dickmaulruessler** [comment]
Wäre das nicht besser über das Rechtesystem steuerbar?

**Comment by stm9x9** [comment]
jein. Ich weiß gerade nicht, wie granular das Rechtesystem ist. Auf Dateiebene haben wir da nichts, oder?
