### ISSUE TITLE
[FEATURE] PDFs schwärzen

### ISSUE THREAD

**Issue by Linkki2021** [jlawyerorg/j-lawyer-org#2682]
Die neuen PDF-Features sind super. 

Ergänzend, wenn es die verwendete PDF-Bibliothek hergibt: es wäre toll, wenn man als User bestimmte Stellen einer PDF direkt in j-lawyer schwärzen könnte, um dann diese geschwärzte Variante als neues Dokument in die Akte abzulegen.

------------------ @j-dimension 2024-11-29 -----------------------------

- [x] PDF-Anmerkungen entfernen
- [x] PDF-Metadaten leeren
- [x] PDF-Inhalte anonymisieren: nutzerdefinierte Texte ersetzen
- [x] Oberfläche, welche Optionen umgesetzt werden sollen
- [x] als neues Dokument zur Akte speichern

**Comment by j-dimension** [comment]
ggf. später über Ingo eine Vorschlagsliste erzeugen lassen, welche Terme geschwärzt werden sollten:

Prompt:
Extrahiere Vornamen, Namen, Firmennamen, IBANs, Telefonnummern, E-Mails aus einem Text. Gib die Ergebnisse in einer Zeile, separiert durch Kommata aus. Es soll exakt eine Zeile entstehen, ohne Hinweise ob es sich um Vornamen, Namen, Firmennamen, IBANs, Telefonnummern oder E-Mails handelt. Hier der Text:

**Comment by j-dimension** [comment]
Anmerkungen löschen:

```
        // annotations
//            File inputFile = new File("input.pdf");
//        File outputFile = new File("output.pdf");
//
//        try (PDDocument document = PDDocument.load(inputFile)) {
//            document.getPages().forEach(page -> page.setAnnotations(null)); // Remove annotations
//            document.save(outputFile);
//        }
```

**Comment by j-dimension** [comment]
das eigentliche Schwärzen per itext - komplex, je nach Dokumentstruktur

**Comment by j-dimension** [comment]
Anonymisierung - nutzerdefinierte Terme werden entfernt, sowie Metadaten und Anmerkungen:


https://github.com/user-attachments/assets/31d973f3-1b47-4adf-bb72-3be13a6e0d72

**Comment by j-dimension** [comment]
Anonymisierung - Assistent Ingo extrahiert Namen, Vorname, Strassennamen, Ortsnamen, Telefonnummern, IBANs und Mailadressen und schlägt sie zur Anonymisierung vor:


https://github.com/user-attachments/assets/7cbabc02-3320-499c-8806-5a2ef9937c73
