### ISSUE TITLE
[BUG] Datum auf Desktop aktualisiert nicht

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#2685]
Ich bin mir zwar zu 100% sicher, das ich das schon mal geschrieben hatte, aber ich finde es nicht mehr:

![image](https://github.com/user-attachments/assets/f45fdc40-7e96-491a-9efd-67989ed8340d)

Das Bild ist vom Mittwoch, dem 20.11. Das Datum aktualisiert nicht, auch nicht, wenn ich in eine Akte und zurück wechsle.

PS: Falls es da schon ein Ticket für gibt: Wie wurde das gefunden? Ich habe es mit Datum UND Desktop versucht und mit beiden Begriffen einzeln ...

**Comment by j-dimension** [comment]
Wird alle 30min aktualisiert.

**Comment by stm9x9** [comment]
könnte man das nicht zum Tageswechsel also Mitternacht zusätzlich machen?
