### ISSUE TITLE
[TASK] Layout Nutzerverwaltung, Dokumenterstellung auf kleinen Displays

### ISSUE THREAD

**Issue by steboe1** [jlawyerorg/j-lawyer-org#2689]
Inhalte werden bei Anzeige in Fenstern nicht vollständig angezeigt scrollen nicht möglich. 
Es ist nicht erkennbar das z.B. noch Schaltflächen vorhanden sind die aber nur sichtbar sind wenn das Fenster nach unten gezogen wird.

**Welches Problem soll durch die Erweiterung / Verbesserung gelöst werden?**
Einfügen einer Bildlaufleiste horizontal und vertikal wenn Bereiche bei kleinen Fenstern nicht sichtbar sind

**Beschreibe die gewünschte Lösung**
Konsequente Umsetzung von Bildlaufleiste horizontal und vertikal wenn etwas verdeckt wird in allen Programmfenstern und Aktenoberflächen

Screenshots
**Fenster klein**
![image](https://github.com/user-attachments/assets/3328e662-93dc-4ca5-9632-981548513b49)

**Fenster groß**
![image](https://github.com/user-attachments/assets/1d7597fb-cde1-408f-8f21-70a2849107eb)

Die Umsetzung würde mir sehr helfen da ich unterwegs (Notebook 14 Zoll Full-HD Auflösung) nur umständlich arbeiten kann.

**Comment by j-dimension** [comment]
Das Hinzufügen von Scrollbalken halte ich nicht für die Lösung, das wird schlicht unbenutzbar, wenn man routinemäßig viel Scrollen muss. 
Auch ist der Inhalt des Tickets zu unspezifisch - darf ich ihn umformulieren und auf die Nutzerverwaltung fokussieren? Wenn es weitere Dialog gibt, bitte benennen - danke!

**Comment by steboe1** [comment]
Ich habe zwei Screenshots beigefügt die das Problem darstellen das betrifft so ziemlich jedes Fenster der Anwendung. Das ist nicht nur ein Problem in der Nutzerverwaltung. Wenn die Höhe eines Fensters verringert wird verschwinden die Schaltflächen. Das es welche gibt ist dann nicht mehr erkennbar.Ebenfalls habe ich das Problem das eine lange Benennung bei „wegen“ die Buttons rechts oben weg schiebt da wäre eine Bildlaufleiste die bei verdeckten Elementen sichtbar wird aus meiner Sicht eine Hilfe.Ich denke nicht das der Ansatz sein sollte das es nur mit 17“ Notebook mit UHD Auflösung richtig nutzbar ist.Wenn Sie andere Lösungen für das Problem sehen würde ich mich darüber freuen.Mit freundlichen GrüßenStefan BöckDiese E-Mail enthält vertrauliche und/oder rechtlich geschützte Informationen. Wenn Sie nicht der richtige Adressat sind oder diese E-Mail irrtümlich erhalten haben, informieren Sie bitte sofort den Absender und vernichten Sie diese E-Mail. Das unerlaubte Kopieren sowie die unbefugte Weitergabe dieser Mail sind nicht gestattet.Wir danken Ihnen für Ihre Unterstützung. This e-mail may contain confidential and/or privileged information.If you are not the intended recipient ore have received this e-mail in error please notify the sender immediately and destroy this e-mail.Any unauthorised copying, disclosure or distribution of the material in this e-mail is strictly forbidden.We thank you for your support.Am 22.11.2024 um 09:49 schrieb Jens Kutschke ***@***.***>:﻿
Das Hinzufügen von Scrollbalken halte ich nicht für die Lösung, das wird schlicht unbenutzbar, wenn man routinemäßig viel Scrollen muss.
Auch ist der Inhalt des Tickets zu unspezifisch - darf ich ihn umformulieren und auf die Nutzerverwaltung fokussieren? Wenn es weitere Dialog gibt, bitte benennen - danke!

**Comment by j-dimension** [comment]
Die Screenshots sind beide aus der Nutzerverwaltung. 

Ich arbeite hier selbst mit einem 15" Full HD. Die Größe des Displays spielt keine Rolle, die Auflösung sehr wohl, und ob eine Skalierung eingestellt wird (125% oder mehr). 

Gerne weitere Screenshots bereitstellen.

**Comment by j-dimension** [comment]
@steboe1 ich kann das Problem in der Nutzerverwaltung hier nicht nachvollziehen. Die Buttons sollten nur "runterrutschen", wenn der Inhalt auf einem der Tabs in der Vertikalen sehr viel Platz braucht. Ist das der Fall? Dann bitte mal davon einen Screenshot.

**Comment by j-dimension** [comment]
Nutzerverwaltung, Extrembeispiel, hier mit horizontal 1270 Pixeln. Platzhalter in separaten Tab verschoben.

![grafik](https://github.com/user-attachments/assets/aa22c1f6-510d-40d2-bcf9-b5d8928a2d0d)

**Comment by j-dimension** [comment]
Nutzerverwaltung, nur geringe Anpassungen, passt auf 1000 x 780:

![grafik](https://github.com/user-attachments/assets/48e5b234-8ed8-476d-822e-34d36cd048e9)
