### ISSUE TITLE
[BUG] Rundungsfehler bei Zeiterfassung

### ISSUE THREAD

**Issue by DenisLug** [jlawyerorg/j-lawyer-org#2705]
**Fehlerbeschreibung**
Bei der Zeiterfassung kommt es scheinbar zu einem Rundungsfehler des Gesamtbetrags. Im Screenshot unten sieht man ein Beispiel:

![Zeiterfassung fehlerhaft](https://github.com/user-attachments/assets/f89e9eb8-5909-4b0e-a6e8-b0dbca9985cf)

280 * 0,17 = **46,6** (J-Lawyer 46,67)
280 * 12,33 = **3452,4** (J-Lawyer 3453,32)
280 * 0,83 = **232,4** (J-Lawyer 233,33)

**verwendete Umgebung:**
 - Betriebssystem: Mac OS
 - j-lawyer.org Version: 3.0.0.1

**Comment by j-dimension** [comment]
Die Darstellung ist ja aus einer Rechnung, nicht aus einer Zeiterfassung. 
Vermutlich werden die kumulierten Zeiten hier mit 2 Nachkommastellen dargestellt, es wird aber intern mit allen verfügbaren Nachkommastellen gerechnet. 

Wie verhält es sich, wenn daraus eine Rechnung erstellt wird?

**Comment by DenisLug** [comment]
Richtig, das stammt aus der Rechnungsansicht. Auch in der erstellten Rechnung werden die Rundungsfehler übernommen.

**Comment by j-dimension** [comment]
Könnte ich für "Verhandlung 280EUR/h" mal die exakten erfassten Zeiten bekommen?
