### ISSUE TITLE
[BUG] Akte aus Email erstellen, wenn Aktenzeichen mit Gruppenkürzel angegeben wird

### ISSUE THREAD

**Issue by SaschaKarcher** [jlawyerorg/j-lawyer-org#2710]
Ich habe seit neuestem bei den Aktenzeichen diese mit einem Gruppenkürzel erweitert. Hierbei ist mir aufgefallen, dass wenn ich nunmehr aus einer Email heraus eine Akte erstelle, diese dann anscheinend nicht abgespeichert wird.

**Comment by j-dimension** [comment]
Das wäre ein Duplikat von #2477
