### ISSUE TITLE
[BUG] Finanzen: Begleichen einer Rechnung via Aufrechnung mit Fremdgeld ergibt Zahlungseingang NULL

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#2714]
Ich bekomme in einer Akte Geld vom Gegner für den Mandanten. Sein Geld und Kostenersatz. Ich buche das ins Fremdgeld.

Dann rechne ich meine Rechnung anteilig mit dem Fremdgeld auf.

Ich klicke auf den bezahlt-Button

![image](https://github.com/user-attachments/assets/efcd5bba-f1ec-4f0f-b4b2-b5ca7dd19c8b)

Dort gebe ich zb "476 € Einnahmen ein und 476 Fremdgeld aus" ein. 

![image](https://github.com/user-attachments/assets/241d6e5a-6858-4bad-8ea1-6bc6c4851e2c)

Der Status wechselt auf bezahlt und es steht 476 Zahlungseingang und 0 offen

![image](https://github.com/user-attachments/assets/e3085bcf-6e98-402c-8a8a-ee26c2772fdc)

In den Zahlungen steht aber 0,00 

![image](https://github.com/user-attachments/assets/28f512d5-4461-49af-8b04-8ada0febf24f)

und wenn ich die Akte neu öffne, dann ist 0 bezahlt und wieder 476 offen

![image](https://github.com/user-attachments/assets/a1acbd5a-4337-4d38-b04c-462bb97036b3)

**Comment by j-dimension** [comment]
@stm9x9 glücklicherweise nur ein Anzeigefehler, die Buchungen in der Datenbank sind korrekt. Ich möchte Dich bitten, das im Rahmen der kommenden Testphase (wird wahrscheinlich noch im Dezember) einmal durchzuchecken. Danke!
