### ISSUE TITLE
Navigationsleiste in 3.1 skaliert nicht auf Fensterhöhe 

### ISSUE THREAD

**Issue by iradraconis** [jlawyerorg/j-lawyer-org#2730]
Ich weiß nicht, ob es Absicht ist. Es ist mir nur aufgefallen. 

![2024-12-10 20 46 24](https://github.com/user-attachments/assets/1c9c494c-ac0d-4179-863d-816540311bcb)

**Comment by j-dimension** [comment]
Das ist soweit erstmal Absicht. Ich würde mich aber über Rückmeldung freuen, welche Variante besser ist :-)

**Comment by Dickmaulruessler** [comment]
> Ich würde mich aber über Rückmeldung freuen, welche Variante besser ist :-)

Mein Feedback: So ist weniger Abstand, man muss die Maus genauer postionieren und unten ungenutzter Platz. Ich kann darin keinen praktischen Vorteil erkennen und optisch ist es nicht "so schön"...

**Comment by j-dimension** [comment]
Die Mauswege werden aber idR kürzer.

**Comment by iradraconis** [comment]
also ich hab mir ein paar Tage damit gegeben und muss sagen, dass es mir vorher besser gefallen hat, bzw. ich das Handling angenehmer fand.
