### ISSUE TITLE
[BUG] Langer Titel im Ingo Fenster gibt Breite des Inhalts des Dialogs vor, Dialog muss dann manuell vergrößert werden

### ISSUE THREAD

**Issue by iradraconis** [jlawyerorg/j-lawyer-org#2731]
Das hat vor allem auch Effekt auf die unten rechts angeordneten Buttons Übernehmen und Kopieren

![2024-12-10 21 13 44](https://github.com/user-attachments/assets/6d332c1b-cb68-43dd-a579-8e522337a592)

Mögliche Lösung: Dialogbreite passt sich automatisch dem Titel an? (wäre nicht so schön, weil nicht durchgängig oder vorhersehbar)

Besser: Dialoggröße wird gespeichert und das Label im Titel wird bei Erreichen der Fensterbreite abgekürzt mit "..."

**Comment by j-dimension** [comment]
Ich habe jetzt kurzerhand die Beschreibung der Ingo-Aktion angepasst / eingekürzt.
