### ISSUE TITLE
[FEATURE] pdf-Vorschau: An Breite anpassen Button

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#2732]
In der pdf-Vorschau haben wir den Button an-Seite-anpassen

![image](https://github.com/user-attachments/assets/bbe01c70-6b2f-4447-9fab-081d39c280cc)

In anderen pdf-Viewern hat dieser Button im Wechsel eine doppelte Funktion, an Seite(nhöhe) anpassen und auch noch an Seitenbreite anpassen, womit er halt breiter darstellt, so daß man je nach Layoutaufteilung und Fenstergröße zwar nicht mehr alles in der Länge einer Seite sieht, dafür aber in maximaler Breite.

![image](https://github.com/user-attachments/assets/1b799d15-727a-4fe6-b977-8fb911ba330d)

**Comment by Dickmaulruessler** [comment]
#2553
