### ISSUE TITLE
[BUG] Dunkles Design wechselt nach mouse-over wieder zu hell

### ISSUE THREAD

**Issue by Dickmaulruessler** [jlawyerorg/j-lawyer-org#2734]
Dunkles Design wird nach Mouse-over wieder hell. 
Nach Client-Neustart ist wieder standard-Heller-Modus eingestellt. 
Win 10, 
JL: 3.1.0.0

Off-Topic PS: Das Update hat problemlos funktioniert.

![dfdsfdsafdsafdsafdsafs](https://github.com/user-attachments/assets/d898f0b7-bbaa-46f1-b55b-0b010a07b828)

**Comment by j-dimension** [comment]
?!

Sorry, wo stellst Du das ein? Es gibt keinen offiziellen Dark Mode.

**Comment by j-dimension** [comment]
Da sollte noch gar nicht rein, ist Vorbereitung für #1581
