### ISSUE TITLE
[BUG] Inhalt des Posteingangs wird unter Windows nicht angezeigt

### ISSUE THREAD

**Issue by SteRoe** [jlawyerorg/j-lawyer-org#2741]
**Fehlerbeschreibung**
Client Version 3.1: Unter Windows wird der Inhalt des Posteingangs nicht angezeigt, obwohl der Versand der Testnachricht funktioniert. Unter Linux funktioniert alles.
Server ist auch Version 3.1

**Schritte zum Nachvollziehen**
0. Mit Client 3.1 (Windows 10/11)
1. Gehe zu 'E-Mail'
2. Klicke auf 'Posteingang'
4. Fehlermeldung: 'Die Übersicht der Nachrichten bleibt leer.'

**Erwartetes Verhalten**
Es sollten die eingegangenen Nachrichten angezeigt werden.

**verwendete Umgebung:**
 - Betriebssystem: Windows 10/11
 - j-lawyer.org Version: 3.1

**Sonstiges**
Client auf Ubuntu 24.04 funktioniert

**Comment by SteRoe** [comment]
Nach Downgrade auf Version 3.0.0.1 (Server und Client) kann ich mich nicht mehr anmelden. Nun ist guter Rat gefragt.
Wieder hoch auf 3.1: Anmelden funktioinert wieder, unsichtbare Email bleibt.

**Comment by j-dimension** [comment]
3.1 ist noch nicht offiziell released.

Ist es ein Office 365 - Postfach?

**Comment by SteRoe** [comment]
Irgendwer muss ja testen (-:
Nein, das ist ein IMAP Server bei Ionos.

**Comment by j-dimension** [comment]
Das ist lobenswert! 🙂

Welches Abruflimit im Posteingang oben rechts hast du eingestellt?

**Comment by SteRoe** [comment]
Das kann ich gerade nicht sagen. Die Windows Clients stehen im Büro. Aber: die Testnachricht in den Einstellungen geht zu versenden und kommt auch an (mit Thunderbird geprüft). Wenn ich im Windows-Client auf aktualisieren ("Kringel-Pfeil" oben links) klicke, kommt "authentication failed".

Abruflimit bekomme ich heraus (es steht unverändert auf Standard-Einstellung).

**Comment by SteRoe** [comment]
Ich bin jetzt im Büro: Abruflimit auf 20 bringt keine Veränderung. Die Fehlermeldung beim Aktualisieren heißt: "Keine Verbindung zum Mailserver: authentication failed".

**Comment by j-dimension** [comment]
Ist es ein Office 365 - Postfach?

**Comment by SteRoe** [comment]
Nein.

**Comment by SteRoe** [comment]
Jetzt wird es interessant: Als admin angemeldet funktioniert es. Als normaler Nutzer weiterhin  "Keine Verbindung zum Mailserver: authentication failed" nach Klick auf "Aktualisieren". Abruflimit 20: Die Nachrichten werden nun angezeigt. Alles nur unter Windows.

**Comment by j-dimension** [comment]
Dann werden wahrscheinlich unterschiedliche Postfacheindtellungen genutzt?

**Comment by SteRoe** [comment]
Abruflimit auf 20 war eine gute Idee. Damit wird zumindest etwas angezeigt.
Wenn ich auf Aktualisieren klicke kommt als normaler Benutzer:  "Keine Verbindung zum Mailserver: authentication failed". Als Admin funktioniert es ohne Fehlermeldung. Postfacheinstellungen sind sehr sicher identisch für normalen Benutzer und Admin.

Das ist eine Rechte-Sache: Als Admin kann ich das IMAP-Postfach abrufen, als normaler Benutzer nicht. Wenn die Nachricht einmal vom IMAP Server abgeholt ist, wird sie auch beim normalen Benutzer angezeigt.

Nochmal Revision: das Verhalten ist entgegen ursprünglicher Annahme identisch unter Linux und Windows.

**Comment by SteRoe** [comment]
Noch eine Beobachtung: Wenn ich lange genug warte, kommen neue Nachrichten auch als normaler Benutzer an. Klick auf "Aktualisieren" produziert ohne Admin reproduzierbar:  "Keine Verbindung zum Mailserver: authentication failed".

**Comment by SteRoe** [comment]
Noch etwas Anderes: J-Lawyer merkt sich die Spalteneinstellungen (Betreff, Absender, Empfängder, Gesendet) in der Mail-Übersicht nicht.

**Comment by j-dimension** [comment]
> Noch eine Beobachtung: Wenn ich lange genug warte, kommen neue Nachrichten auch als normaler Benutzer an. Klick auf "Aktualisieren" produziert ohne Admin reproduzierbar:  "Keine Verbindung zum Mailserver: authentication failed".

Dann muss es Unterschiede in den Einstellungen geben.

**Comment by SteRoe** [comment]
Tatsächlich: Es war eine zweite email-Adresse mit falschem Passwort beim Benutzer hinterlegt. Version 3.0 hat sich daran nicht gestört. 3.1 schon.
Danke, nun funktioinert es.

**Comment by SteRoe** [comment]
Verbesserungsvorschlag: wenn bei "Keine Verbindung zum Mailserver: authentication failed" das Mail-Konto, welches das Problem verursacht, genannt würde, wäre die Fehlersuche einfacher.
