### ISSUE TITLE
Containerization

### ISSUE THREAD

**Issue by j-dimension** [jlawyerorg/j-lawyer-org#275]
Docker? LXC/LXD with https://github.com/adaptivescale/lxdui?

**Comment by j-dimension** [comment]
https://lxc-webpanel.github.io/

**Comment by j-dimension** [comment]
https://www.linuxjournal.com/content/everything-you-need-know-about-linux-containers-part-ii-working-linux-containers-lxc

**Comment by malteos** [comment]
Any news on this?

**Comment by j-dimension** [comment]
> Any news on this?

Meantime I am running LXC containers for some customers. No Docker however. If you have a specific requirement, I can add it to the planning for 1.13 - just let me know.

**Comment by malteos** [comment]
A `docker-compose` file to manage all the server applications would be really useful. Let me know if I can help you out somehow.

**Comment by j-dimension** [comment]
So, you're looking at building the image yourself vs. getting a built image from e.g. Docker Hub?

**Comment by j-dimension** [comment]
- [ ] Dockerfiles and compose YAML
- [ ] build integration
- [ ] figure out how to have the wildfly container wait until the database schema has been fully set up

**Comment by malteos** [comment]
You can add health checks to let services wait for each other. See https://stackoverflow.com/questions/31746182/docker-compose-wait-for-container-x-before-starting-y

**Comment by j-dimension** [comment]
Thanks @malteos but that does not / no longer seem to do the trick. 

Before docker-compose in v3 you could do something like:

```
depends_on:
      db:
        condition: service_healthy
```

and the container depending on the other would wait until the health check of this container was executed successfully. The condition directive is no longer supported :-(

**Comment by j-dimension** [comment]
@malteos would you have time and mood to serve as a guinea pig? The images are now on Docker Hub. 

How to, pending an official README.md:

```
wget https://raw.githubusercontent.com/jlawyerorg/j-lawyer-org/master/docker/docker-compose.yaml
docker-compose up
```

The container(s) expose a port 8000, first checks would be
- http://localhost:8000/ for the Wildfly status page
- http://localhost:8000/j-lawyer-io/swagger-ui/ for Swagger UI (frontend to try out the REST API)
- then install the client from the official download page and connect to "localhost" and ports 8000

I have not tested on macOS yet.

**Comment by j-dimension** [comment]
added readme: https://github.com/jlawyerorg/j-lawyer-org/tree/master/docker

**Comment by malteos** [comment]
Cool! If I find time in the next week, I'll give it a try.
