### ISSUE TITLE
[FEATURE] Volltextsuche auch auf Aktenebene

### ISSUE THREAD

**Issue by SteRoe** [jlawyerorg/j-lawyer-org#2757]
Es gibt eine wunderschön funktionierende Volltextsuche, die über alle textbasierten Dokumente in allen Akten sucht.

Es wäre hilfreich, wenn es das auch auf Aktenebene gibt, so dass nur in den Dokumenten der aktuellen Akte gesucht wird,

**Comment by j-dimension** [comment]
Duplikat von #333
