### ISSUE TITLE
Seitenleiste beA / E-Mail: "nur Anhang speichern"

### ISSUE THREAD

**Issue by j-dimension** [jlawyerorg/j-lawyer-org#286]
@RA-crm

**Comment by j-dimension** [comment]
als separaten Button / 4. Möglichkeit

**Comment by Maz111111** [comment]
Empfinde ich als dringend!
Beim beA ist die Nachricht in der Regel ausschließlich und bei Mails in über 50%:
"anliegendes Schreiben zur Kenntnisnahme.
MfkG
……….
-Rechtsanwalt-"
Interessant ist ausschließlich der Anhang

**Comment by j-dimension** [comment]
Stimmt, aber ohne Speichern der Nachricht hast Du auch kein Journal.

**Comment by Maz111111** [comment]
Da hast Du Recht - das korrespondiert mit der Frage der Exportfunktion. Wobei es hier ja nur um empfangene Nachrichten geht.
Soweit ich das jetzt verstehe, ist das Journal dafür da, um verschiedene Zeitpunkte (hier den Zugangszeitpunkt) zu dokumentieren. 
Es wäre zwar gut, wenn auch der Empfänger einen Nachweis für den Zeitpunkt des Zugangs hätte, aber der eigentliche Nachweis des Zugangszeitpunkts obliegt in der Regel dem Versender.
Schwierig, zu entscheiden. 
Aber das oben dargestellte "Anschreiben" des Versenders macht die Akte nur unübersichtlich und wird eigentlich im Übrigen nicht gebraucht.
Ich verstehe aber, was Du meinst.

**Comment by j-dimension** [comment]
Kein Problem, ich liefere das - der Anwender möge entscheiden welche Variante er bevorzugt :-)

**Comment by stm9x9** [comment]
@Maz111111 die beA-Nachricht als solche brauchst du spätestens, wenn der Absender sagt, aber da waren doch zwei Anlagen drin und du dich fragst: welche ZWEI Anlagen? Gar nicht erst, um dem Absender das Gegenteil beweisen zu können, sondern bereits um dich selbst zu vergewissern, daß da nur ein Anhang neben dem Anschreiben bei war.

**Comment by Maz111111** [comment]
Das ist ein verdammtes "Für und Wider"
Auch hier würde ich sagen: Lieber Absender, stimmt nicht! Beweis mir das und sende mir die Anlagen erneut. Im Termin natürlich zu spät und unangenehm.
Vielleicht könnte man es so machen, dass die reine Nachricht nebst Journal zwar abgespeichert - aber nicht unter dem Dokumentenreiter angezeigt wird, sondern einen eigenen Reiter oder sogar nur einen eigenen Menüpunkt erhält - aber auf Initiative des Anwenders doch in den Doks gespeichert werden kann. Damit kann man entscheiden, welche Nachrichten zwingend "in der Papierakte abgeheftet" würden - also unter den Doks zu finden sein müssen und hat trotzdem die notwendige Überprüfungshoheit.

**Comment by j-dimension** [comment]
> Vielleicht könnte man es so machen, dass die reine Nachricht nebst Journal zwar abgespeichert - aber nicht unter dem Dokumentenreiter angezeigt wird

Oder Unterordner in den Dokumenten haben, und alle beA-Nachrichten in einen eigenen Ordner?

**Comment by Maz111111** [comment]
Ja, auch so würde es natürlich auch gehen. Die Ordnerstruktur war ja ohnehin angedacht.
Es wäre dann schön, wenn man bereits im Rahmen der Zuordnung die Möglichkeit hätte, die Nachricht in einen Unterordner zu verbannen und den Anhang in eine andere Ordnerebene.

Off-Topic:
Ich finde das mit den Ordnern nur begrenzt ausreichend. Aber da hat jeder seine eigenen Vorlieben.

Manche Kanzleien ordnen (in der Papierakte) tatsächlich auch so getrennt nach verschiedenen Kriterien ab und haben dann Trenneinleger in der Akte. Andere Kollegen verwenden unterschiedlich farbiges Papier (SS Gericht = rot; SS Mandant = gelb etc).

Das kann man digital über eine Ordnerstruktur abbilden, über farbliche Markierungen der Dokumentennamen oder über eine entsprechende Verschlagwortung (MandantenDoks bekommen vor das Datum ein M; GerichtsDoks ein G etc) und darauf folgender Sortierung nach Namen.

Aber letztlich entscheidest Du das. Man könnte dem Anwender alle Möglichkeiten eröffnen (das wär natürlich toll) oder es auch so lassen, wie es ist.
Eine Verschlagwortung wäre ja möglich - wenn auch mit Aufwand.
