### ISSUE TITLE
Notiz erstellen: Möglichkeit einen Tag zu aktivieren

### ISSUE THREAD

**Issue by j-dimension** [jlawyerorg/j-lawyer-org#287]
@RA-crm

**Comment by RA-crm** [comment]
Möglichkeit für Tag Zielakte und Tag (Ziel)dokument = Notiz

So wäre es etwa möglich, die Akte dem Bearbeiter vorzulegen (Tag Zielakte) und zugleich konkret eine Aufgabe zum Dokument zu erstellen (Tag Dokument)
