### ISSUE TITLE
Konfigurierbarer Präfix für Dokumente

### ISSUE THREAD

**Issue by j-dimension** [jlawyerorg/j-lawyer-org#288]
Aktuell wird Datum verwendet. Sollte konfigurierbar sein (Datumsformat, AZ, von, an, ...)

**Comment by j-dimension** [comment]
@RA-crm

**Comment by RA-crm** [comment]
Genau, zB
Az_YYYYMMDD_
als Präfix

von / an / mit erfolgt dann individuell

es sei den, bei der Erstellung des Dokuments oder der Aufnahme des Scans, der Mail oder dem Anhang zur Akte erfolgt ein Dialog zur Bestimmung des Typs

etwa
Schreiben ans Landgericht 
Az_YYYYMMDD_aLG_"individueller Text".odt
oder Mail vom GegnerRA
Az_YYYYMMDD_vRA "xx"_"individueller Text".eml

**Comment by j-dimension** [comment]
Ticket vorerst fokussieren auf konfigurierbares Datumsformat, bspw. um statt

2022-05-04_12-31_usw Text Beispiel.eml

etwas kürzer

220504_1231_usw Text Beispiel.eml

nutzen zu können.

Ggf. Option zum Ersetzen von Leerzeichen durch Unterstriche.

**Comment by Dickmaulruessler** [comment]
Cool!

**Comment by Dickmaulruessler** [comment]
> 
> etwas kürzer
> 

Oder evtl. gar mit der Option nur 
Erstes Dokument: [Datum]
Zweites Dokument: [Datum]-2
Drittes Dokument: [Datum]-3

Die Uhrzeit ist in der Regel nicht von Interesse und kann häufig komplett entfallen. Ich jedenfalls benötige sie im Dateinamen nie. Wichtig ist aber die streng chronologische Sortierung.
