### ISSUE TITLE
Editierbarer Name des RA > bug?

### ISSUE THREAD

**Issue by RA-crm** [jlawyerorg/j-lawyer-org#291]
Bei der Aktenanlage ist es möglich, den Anwalt auszuwählen UND dann den Namen anzupassen. Das sollte nicht sein. Bug?

**Comment by j-dimension** [comment]
Das ist tatsächlich gewollt - es gibt Anwender / Kanzleien, wo ausschließlich das Sekretariat die Kanzleisoftware bedient, und die Dokumente dann den Anwälten vorlegt.

Klingt verrückt, ist aber so :-)
