### ISSUE TITLE
[adressen] Trennung Adressfelder in natürliche Person und Unternehmen / Institution

### ISSUE THREAD

**Issue by RA-crm** [jlawyerorg/j-lawyer-org#296]
Dadurch übersichtliches Adressfeld 
Anrede/Name/Nachname bei nat. Personen
Unternehmensbezeichnung HRB/HRA Nummer, Insolvenzvermerk

bei beiden Zuordnung eines Vertreters
zB Geschäftsführer, Eltern, Betreuer

**Comment by librelegal** [comment]
Ein Vorteil wäre, dass die Einhaltung datenschutzrechtlicher Vorgaben leichter wäre. So kann in anderen Programmen eine automatische Löschung bei Erreichen der Löschpflicht erfolgen. Hier dazu das Beispiel des Anwaltsprogramms a-jur (http://www.a-jur.de/dsgvo.htm)

**Comment by librelegal** [comment]
Die Bezeichnung dieses issues sollte vereinheitlicht werden. Es geht um Adressen, deshalb "Adressen:" voranstellen. Optimierung zur Verständlichkeit 
Insgesamt wie nachstehend:
Adressen: Trennung Felder in natürliche Person und Unternehmen / Institution

**Comment by j-dimension** [comment]
Wie sieht so ein Insolvenzvermerk aus? @RA-crm

**Comment by j-dimension** [comment]
"vertreten durch" erst via #120

**Comment by j-dimension** [comment]
Wie sieht so ein Insolvenzvermerk aus? @RA-crm

**Comment by RA-crm** [comment]
Als Insolvenzvermerk verstehe ich zum einen die Ergänzung der Unternehmesbezeichnung/Firma um die Insolvenz. Etwa:
Ab-in-die-Pleite GmbH i.I.; wobei i.I. für in Insolvenz steht.
Ähnlich ist es bei der Liquidation. Dort heißt es dann i.L. für in Liquidation.
Hinzu kommt, dass sich bei der Insolvenz die "Vertretung" ändert. Mit der Insolvenz übernimmt der Insolvenzverwalter die Verwaltung des Vermögens des Insolvenzschuldners. Insoweit "vertritt" er die Vermögensmasse des Schuldners. Die gesellschftsrechtliche Vertretung durch den Geschäftsführer bliebt allerdings bestehen, sodass dieser nicht einfach durch den Insolvenzverwalter ersetzt werden kann.
Wahrscheinlich kann man dies aber über die Beteiligtenregelung lösen, wenn man einen Insolvenzverwalter anlegt.
