### ISSUE TITLE
Capi  / Bea

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-org#300]
Ich benutze im Moment den Kartenleser Reiner SCT, Firmwarevers. 2.2.0 für Proficash (Banking FinTS/Networld-Card) und auch mit der BEA Basiskarte. Die Erkennung der Karten scheitert jedesmal bei einem Wechsel auf die jeweils andere Karte, weil die Capi-Schnittstelle als belegt gemeldet wird (von der Karte vorher). Der Rechner muss immer runtergefahren und neu gestartet werden bei einem Kartenwechsel. Oder der Leser muss an eine andere USB-Schnittstelle. Vielleicht lässt sich das bei der Neuimplementierung des BEA in J-Lawyer gleich vermeiden....?

**Comment by j-dimension** [comment]
Das lässt sich in j-lawyer nicht kontrollieren, da es Sache des Gerätetreibers ist. Die Empfehlung wird wahrscheinlich auch sein, in j-lawyer in der Regel mit einem Softwarezertifikat zu arbeiten. Damit entfällt diese Thematik komplett. 

Kartenleser dann nur nutzen wenn es tatsächlich sein muss (z.B. wenn QES vorgeschrieben ist).

Ich schliesse daher das Ticket.
