### ISSUE TITLE
EGVP-Laufzettel-Handling

### ISSUE THREAD

**Issue by j-dimension** [jlawyerorg/j-lawyer-org#305]
Siehe #202 !

Eigentlich müssten die Nachrichten an ein EGVP beim Senden IMMER in die Akte gespeichert werden, denn ein späteres Abrufen des Laufzettels ist nicht mehr möglich. 

Oder: ist ein beA-Fehler - evtl. neue KSW-Toolkit-Version mit Fix verfügbar?

**Comment by j-dimension** [comment]
@stm9x9 ich komme endlich an die Laufzettel ran. 
Im Großen und Ganzen bestehen die aus einer Liste von von <Code, Statustext>, bpsw. 

![grafik](https://user-images.githubusercontent.com/3729754/77367317-31e81900-6d5a-11ea-8a5d-c47d686618be.png)

Außerdem wird die OSCI-Nachricht mit in die im Client abgespeicherte .bea-Datei aufgenommen. 

Siehst Du einen Bedarf, die OSCI-Nachricht in Rohform dem Nutzer zugänglich zu machen?

**Comment by stm9x9** [comment]
Was heißt denn, sie wird in die .bea-Datei aufgenommen, genau? Ich sehe da jetzt halt nur den Code. 

Und wenn die OSCI-Nachricht die ist, die ich hoffe, dann würde ich die unbedingt in Rohform haben wollen, denn damit wäre der Zugangsnachweis führbar. Aber dazu müßte ich sie mal sehen.

**Comment by j-dimension** [comment]
Du klickst die .bea - Datei in der Akte an und hast dann unter "EGVP-Laufzettel" die Laufzetteleinträge. 0800 heißt "erfolgreich verschickt".

Wenn Du die OSCI-Nachricht sehen willst, speichere die .bea mal lokal, nenne sie in .xml um und mache sie mit dem Browser auf.

**Comment by stm9x9** [comment]
```
<processCard messageId="29978879">
<processCardEntry code="3707">
<entryText>Certificate is selfsigned.</entryText>
</processCardEntry>
<processCardEntry code="0800">
<entryText>Request executed, dialog closed</entryText>
</processCardEntry>
<osciMessage>xxxx

```
Eine ProcessCard! Eine ProcessCard!!!!!!1111 :-D :-D :-D

Genau das dürfte es sein, was den sicheren kryptographischen Nachweis des Posteingangs beweisen kann. Von daher würde ich das wirklich gerne in Rohform zur Ansicht und zum Download/Abspeichern aus einer bea-Nachricht haben wollen.

**Comment by Mucki526** [comment]
Hört sich für mich so an, dass mit diesem Codeschnippsel zweifelsfrei der Zugang bei Gericht bewiesen werden kann, was bisher wohl nicht möglich war? Dann wäre es m.E. sinnvoll wenn beim Abruf des codes dieser gedruckt werden könnte und eine Kommentierung erfolgt Code... "Die Nachricht (Nr. der Nachricht) ist am (Datum) ( Uhrzeit) erfolgreich bei Gericht eingegangen bzw. Fehler - die Nachricht ist nicht bei Gericht eingegangen....

**Comment by Mucki526** [comment]
Das versteht dann auch sogar ein Richter wenn man ihm den Ausdruck vorlegen kann + Nachricht und man muss dann den Nachweis führe können, welche Nachricht zu diesem Nachweis konkret gehört...

**Comment by stm9x9** [comment]
Das da oben sind ca 5% des Laufzettels. Und - man mag Richter damit überrtölpeln können - ein Ausdruck - gerade dazu noch von einer Drittfirma-Software statt wenigstens aus beA-Web - beweist halt gar nichts. So einen Ausdruck kann jeder ja selber in Word produzieren.

Beweisen tut alleine die digitale Datei etwas. Die muß man im Streitfalle dem Gericht und dem Gegner digital zukommen lassen. 

Man müßte mal herausbekommen, ob die oder einige Gerichte schon so ausgerüstet sind, einen digitalten Laufzettel mit seinen Signaturen lesen und prüfen zu können.

**Comment by stm9x9** [comment]
Wenn man was als Ausdruck machen will, dann würde ich sowas hier machen:

![image](https://user-images.githubusercontent.com/29924198/80104468-793f1080-8577-11ea-828d-4c962a1dad25.png)

**Comment by stm9x9** [comment]
oder sich komplett an dem orientieren, was bea-web in der export.html macht - es sieht jedenfalls "überzeugend" aus. Und das dann als pdf zum Speichern, verschicken oder drucken.

![image](https://user-images.githubusercontent.com/29924198/80107380-47c84400-857b-11ea-8ac3-eac19447fd69.png)

**Comment by j-dimension** [comment]
Die Bereitstellung der Daten mache ich noch in 1.12. 

@stm9x9 und @Mucki526, das Erzeugen eines Berichts bitte als separates Ticket anfordern.

**Comment by stm9x9** [comment]
> das Erzeugen eines Berichts bitte als separates Ticket anfordern

da hier kein entsprechendes Ticket querverlinkt ist und ich auch bei der Suche kein passendes, offenes Ticket fand, mach ich das dann mal.
