### ISSUE TITLE
Ändern der Tags auf Dokumenten- bzw Aktenebene

### ISSUE THREAD

**Issue by RA-crm** [jlawyerorg/j-lawyer-org#309]
Bisher: auf Akteneben und zukünftig auf Dokumentenebene können Tags gesetzt werden
Einstellungen > Akten/Dokumente > Tags 
Es kann jedoch nur angelegt (neu) und gelöscht werden.
Für bestimmte Anwendungsfälle (zB personenbezogene Tags oder Konkretisierung des Inhalts wäre die Möglichkeit "Ändern" sinnvoll, da andernfalls nur ein neuer Tag erstellt werden kann und alle alten Tags umgetragen werden müssen.

**Comment by j-dimension** [comment]
- Umbenennen von Tags implementiert
- bei Umbenennung wird rückgefragt, ob die Tags auch an vorhandenen Akten / Adressen / Dokumenten geändert werden sollen
