### ISSUE TITLE
Übertragung von Aktennummer - Name - Telefonnummer in Fritzbox

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-org#31]
Wir geben vestärkt die Aktennummer Anrufername und Telefonnummer in das Telefonbuch der Fritzbox ein. Dann sehen wir sofort, wer anruft. Es wäre eine Idee, dass dies automatisch geschieht, indem man bei Anlage  der Akte bzw. des Beteiligten festlegt, dass dieser mit Aktennummer Name und Telefonnummer gleich ins Telefonbuch der Fritzbox eingetragen wird.....

**Comment by Maz111111** [comment]
Coole Idee - Aber! Datenschutz?

**Comment by PBaumfalk** [comment]
Wieso denn Datenschutzrechtliche Probleme? Auf das Telefonbuch der Fritzbox greift doch nur die Kanzlei zu. Oder sehe ich das falsch?

**Comment by Maz111111** [comment]
Hast völlig recht. Ist mir auch gerade eingefallen und ich wollte meinen Post löschen.
Es ging mir um die Angreifbarkeit der FB. Oder der Verlust des Smartphones auf dem die FB Software installiert ist.
Aber alles in allem muss das ja jeder für sich selbst entscheiden. 
Also doch eine coole Sache das.

**Comment by PBaumfalk** [comment]
Ich habe Mandanten, die mehrere Akten haben. Dann wäre die Funktion Unfug.

**Comment by j-dimension** [comment]
Ich gebe @PBaumfalk recht. Wirklich sinnvoll wäre es, wenn die Anwendung eingehende Anrufe "mitbekäme", die anrufende Nummer in der Adressverwaltung sucht und direkt ein kleines Popup anzeigt mit den Mandaten die dazu zu finden sind. Dazu gibt es bereits ein Ticket.
