### ISSUE TITLE
Anderkonto im Kanzleiprofil

### ISSUE THREAD

**Issue by RA-crm** [jlawyerorg/j-lawyer-org#310]
Im Kanzleiprofil fehlt die Möglichkeit für ein oder mehrere weitere Konten. Ein Anwalt hat regelmäßig auch ein Anderkonto. Daher bedarf es eine Felder (IBAN /KontoNr und BIC/BLZ sowie Bank) für mindestens ein weiteres Konto.

**Comment by j-dimension** [comment]
@RA-crm soll ich das direkt als "Anderkonto" bezeichnen in der Oberfläche und den Platzhaltern?

**Comment by RA-crm** [comment]
mE ja. Typischer Weise verfügt eine Rechtsanwaltskanzlei über ein Anderkonto für das Fremdgeld. Daher macht es sinn, auch den Nutzern von j-lawyer das Feld so anzubieten, damit klar ist, welche Bankverbindung hier hinterlegt wird.
