### ISSUE TITLE
Feld für USt-ID Nr. im Kanzleiprofil 

### ISSUE THREAD

**Issue by RA-crm** [jlawyerorg/j-lawyer-org#311]
Im Kanzleiprofil fehlt ein Feld zur USt-ID Nr. die bei grenzüberschreitender Zahlung innerhalb der EU anzugeben ist. Sie kann auf Rechnungen die Steuer-Nr. auch ersetzen. Daher ist ein Feld mit USt-ID Nr. mit entsprechendem Platzhalter notwendig.

**Comment by j-dimension** [comment]
Erledigt.
