### ISSUE TITLE
Integration von Softphones

### ISSUE THREAD

**Issue by Maz111111** [jlawyerorg/j-lawyer-org#319]
Zusätzlich zu sipgate oder sonstigen derartigen Anbietern, sollte die Möglichkeit geschaffen werden, die jeweils hinterlegte Telefonnummer mit einem Softphone zu wählen. 
Neben der Einstellung der Nutzung von sipgate, könnte in den Einstellungen die weitere Möglichkeit gegeben werden, den Pfad zur SoftphoneAnwendung (unter Windows käme Phoner in Betracht) nebst der entsprechenden Befehlszeilenkommandos anzugeben und dieses dann (ggf. minimiert) mit der entsprechenden Nummer über den "anrufen" Button zu starten.

- [x] neuer Einstellungsdialog - gespeichert in den Arbeitsplatzeinstellungen (da der Nutzer an verschiedenen Geräten mit verschiedenen Betriebssystemen und Softphones arbeiten kann)
- [x] Einstellungsvariante 1: per Binary und konfigurierbaren Kommandozeilenparametern
- [x] Einstellungsvariante 2: per Protocol handler (bspw. macOS "open tel:123445" oder Windows "start tel:123545")
- [x] ClientSettings: default auf "Protokollhandler" setzen, damit es direkt funktionert ohne dass man etwas konfigurieren muss
- [x] Implementierung Wählvorgang: Kommandozeilenaufruf
- [x] Implementierung Wählvorgang: Protocol Handler-Aufruf
- [x] Adressverwaltung: Telefoniebutton mit Popup: Sipgate, Softphone
- [x] Akte/Beteiligte: Aktionsmenü um zusätzliche Einträge erweitern: mobil (Softphone), Festnetz (Softphone)
- [x] Recherche Kommandozeilenparameter / Protocol Handler für verschiedene Softphones
- [ ] Doku für Einstellungen der gängigsten Softphones: Phoner (Windows), Telephone (macOS), Twinkle (Linux)
- [x] Menü / Popup möglichst vermeiden: wenn am Nutzer Sipgate aktiviert, dann keine Softphone-Integration in der UI, und andersherum

Tests:

- [ ] Windows Protocol Handler
- [ ] Windows Executable
- [ ] macOS Protocol Handler
- [ ] macOS Executable
- [x] Linux Protocol Handler
- [x] Linux Executable

**Comment by j-dimension** [comment]
Hast Du einen Beispiel-Kommandozeilenaufruf für Phoner?

**Comment by Maz111111** [comment]
phoner.exe CONNECT 0123456789 
Mit obigem Beispiel würde Phoner gestartet werden, und automatisch eine Verbindung mit der (fiktiven) Rufnummer 0123456789 herstellen. 
Auflegen wäre dann Phoner.exe DISCONNECT 
Das könnte als zweiter Button oder als Kommando für den zweiten Klick auf den ersten Button belegt werden.
Das habe ich so zumindest bei Google gefunden.
Irgendwo hatte ich auch gelesen, wie man es schafft, dass phoner nur minimiert startet und den Ruf aufbaut, wenn man sowas haben will. Sieht dann vielleicht eleganter aus.
Wenn du dem Anwender aber die Möglichkeit gibst, den Button neben der Tel,-Nr eben (auch) selbst zu belegen, wäre das ohnehin immer Sache des Users.

**Comment by j-dimension** [comment]
Lösung beschränkt auf ausgehende Anrufe. Bei eingehenden geht das Softphone eh auf.

**Comment by j-dimension** [comment]
Protocol Handler:

- Windows: start callto://1234567 oder start tel://1234567 (non-blocking)
- macOS: open "tel://1234567"
- Linux: xdg-open callto://1234567 oder xdg-open tel://1234567 (non-blocking)

**Comment by j-dimension** [comment]
Kommandozeile:


- Windows: phoner.exe CONNECT 0123456789
- macOS: 
- Linux: twinkle --call 01723654916 (KDE) oder /opt/linphone/bin/linphone "call sip-address=$number" (GNOME)

**Comment by j-dimension** [comment]
Einstellungsdialog:

![grafik](https://user-images.githubusercontent.com/3729754/108640145-51bb1c00-7498-11eb-9678-1f36d6d6b47d.png)

**Comment by j-dimension** [comment]
PhonerLite unter Windows erfolgreich getestet
