### ISSUE TITLE
Platzhalter und Tabulatoren

### ISSUE THREAD

**Issue by Maz111111** [jlawyerorg/j-lawyer-org#323]
Unter Windows akzeptieren die Platzhalter eine mit einem oder mehreren Tabulator(en) vorgegebene Stelle im Dokument nur, wenn in der Zeile gleichzeitig auch mindestens ein anderes Zeichen (leider kein Leerzeichen) vor dem Tab gesetzt ist. 
Eine Lösung über eine Tabelle ist möglich. Es sollte aber auch mit Tabs gehen.

**Comment by j-dimension** [comment]
Ich habe das jetzt umgesetzt, bin aber fast sicher dass das bei einigen Anwendern auf wenig Liebe stoßen wird. 

Ein Beispiel: Adresse in einem Schriftsatz, der Empfänger (d.h. die Platzhalter) sind über Tabs eingerückt. Es gibt auch einen FIRMA-Platzhalter. Wird nun an eine Privatperson verschickt, so ist Firma leer und die gesamte Zeile würde entfernt werden. 
In der neuen Variante werden Tabs nicht entfernt, wenn der Platzhalter leer ist. Es entsteht dann eine Leerzeile.

**Comment by Maz111111** [comment]
Das ist jetzt genau die Kehrseite.
Gibt es keine Möglichkeit zu programmieren, dass für den Fall, dass eben nur Tabs in der Zeile sind und der Platzhalter an sich aber eigentlich leer ist, die Zeile doch zu entfernen ist.
Wahrscheinlich nicht, sonst hättest Du es bestimmt implementiert.
Aber man kann ja mal fragen... :-)

**Comment by j-dimension** [comment]
Das hatte ich versucht, es ist aber nicht trivial aufgrund der Elementtypen in einem ODT-Dokument. Mir fehlt es schlicht an einer vollständigen Liste. Mal schauen...
