### ISSUE TITLE
Vorgabe der Dateinamen

### ISSUE THREAD

**Issue by Maz111111** [jlawyerorg/j-lawyer-org#324]
Das Programm sollte keine Namen (z.B. zum Speichern von gesendeten Mails in der Akte) vorgeben, die es nicht akzeptiert.
Bsp. 
Es wird eine Mail mit 10 verschlüsselten Anlagen versendet. Das Programm schlägt dementsprechend einen Namen für die zu speichernde Datei vor, um dann im Speichervorgang zu melden, dass der Dateiname zu lang ist. Der Speichervorgang wird dann abgebrochen.
Die Software sollte nur Dateinamen vorschlagen/vorgeben, die auch wirklich möglich sind.

**Comment by Maz111111** [comment]
Das entspricht #213. Dort wurde allerdings zugemacht. Der Fehler besteht immer noch. Ob das nur bei Mails ist, kann ich nicht beurteilen. 
Es geht vor allem darum, dass das Programm von sich aus keinen zu langen Dateinamen vorschlagen sollte.

**Comment by j-dimension** [comment]
Ja, #213 behebt diesen Fehler und ist bereits umgesetzt, wird aber erst mit der 1.10 ausgeliefert. Ich schliesse daher dieses Ticket als Duplikat.
