### ISSUE TITLE
Sortierung der Dateien innerhalb der Akte im Reiter Dokumente

### ISSUE THREAD

**Issue by Maz111111** [jlawyerorg/j-lawyer-org#325]
Innerhalb einer Akte sollten die Dokumente (auch) nach dem letzten Änderungszeitpunkt sortiert werden können.
Problem:
Sekretärin erstellt Dokument. Dieses erhält automatisch als Dateinamen, das aktuelle Datum. Am nächsten Tag kommt neue Post, die ebenfalls mit Datum eingescannt und der Akte zugeordnet wird. RA bearbeitet den Schriftsatz der Sekretärin am (über)nächsten Tag und berücksichtigt in diesem dann gleich den neuen Posteingang (vom vorigen Tag).
Wenn nur nach Erstellungsdatum und Dateinamen sortiert werden kann, ist die Reihenfolge dann falsch.

**Comment by j-dimension** [comment]
Verwandt mit #134.

**Comment by j-dimension** [comment]
Hier wäre zu klären welche Angaben wirklich gebraucht werden, sonst haben wir schon drei Datumsangaben: 

- erstellt
- eingegangen
- geändert

**Comment by Maz111111** [comment]
Also ich hab da aktuell nur die Möglichkeit nach Datum und Namen zu sortieren. Und das Datum im Namen entspricht eigentlich immer der Angabe in der Spalte Datum.
Wenn ich das Erstellungsdatum (von Haus aus vorgegeben aber ggf. abänderbar) im Namen der Datei habe, bräuchte ich nur noch das Datum der letzten Änderung als zusätzliche Sortiermöglichkeit.
Das Erstellungsdatum entspricht im Zeitpunkt der Erstellung ohnehin immer dem Datum, welches in der Spalte der letzten Änderung angegeben wird.

**Comment by Maz111111** [comment]
Da das Erstellungsdatum ja ohnehin vom Programm als möglicher Teil des Dateinamens vorgeschlagen wird, wäre ja jeder User selbst verantwortlich, wenn er dies abändert. Insofern würde das Datum der letzten Änderung und des Posteingangs ausreichen. Wobei ich meine, dass Posteingangsdaten ja in der Regel nur für Dokumente benötigt würde, welche nicht selbst erstellt und bearbeitet werden. Dann dürfte das Posteingangsdatum in der Regel aber identisch mit dem Erstellungsdatum und damit auch mit dem Datum der letzten Änderung sein.
Im Einzelnen halte ich in meiner täglichen Arbeit immer vier Daten fest:
- Posteingang (aktuell händisch auf dem Dokument)
- Postausgang (aktuell händisch auf dem Dokument)
- Datum der letzten Änderung (bis zum Einsatz von jlawyer digital aus der Windows Ordner Ansicht - jetzt leider nicht mehr)
- Erstellungsdatum (immer im Dateinamen)

Auf dem Weg zur papierlosen Kanzlei müssen diese vier Daten irgendwie und irgendwo "vergriesgnaddelt" werden :D
Postausgang könnte bei beA und eMail möglicherweise ohnehin ersichtlich sein. Jedenfalls meine ich, dass es dafür **keine Sortiermöglichkeit** braucht. Auch für den Posteingang braucht es keine **Sortiermöglichkeit**. Die beiden Daten müssen im Streitfall nur irgendwie nachvollzogen werden können.
Um innerhalb der Akte schnell den Verlauf der Dokumentenbearbeitung und- einpflege nachvollziehen zu können, denke ich, dass eine Sortierung nach Datum der letzten Änderung die richtige Wahl wäre. 
Ich denke, dass dies auch genau die Reihenfolge sein müsste, in der die gesamten Dokumente einer Akte exportiert werden sollten für die Mitnahme zum Termin auf dem Tablet etc.

Und vielleicht nochmal zur Begrifflichkeit. Für mich ist das Erstellungsdatum ja eigentlich eher das Datum der Fertigstellung eines Schriftsatzes (manchmal brauchts eben ein paar Tage Feinschliff) und das ist das Datum der letzten Änderung.

**Comment by j-dimension** [comment]
Danke, das ist eine in sich schlüssige Argumentation die sich umsetzen lässt!

**Comment by Maz111111** [comment]
Im Ergebnis ist das jetzt auch irgendwie verwandt mit #405 und #370

**Comment by j-dimension** [comment]
Sortierung nach Änderung bereits möglich.
