### ISSUE TITLE
Ablagedatum als explizites Attribut

### ISSUE THREAD

**Issue by j-dimension** [jlawyerorg/j-lawyer-org#332]
Aktuell ist das Ablagedatum das höchste Datum in der Historie. Das ist nicht gewünscht, bspw. wenn man zu einer abgelegten Akte nur noch mal ein Dokument hinzufügt. 

--> als eigenes Attribut, das man ggf. auch selbst bearbeiten kann

**Comment by stm9x9** [comment]
Beispiel für so einen Fall: Nach 3 Jahren meldet sich das Gericht wegen einer PKH-Überprüfungsanfrage *seufz*

**Comment by j-dimension** [comment]
Muss zusammen mit #44 bearbeitet werden.
