### ISSUE TITLE
Lage und Größe des ClientFensters auf dem Desktop - Anordnung der Trennbalken im Clientfenster

### ISSUE THREAD

**Issue by Maz111111** [jlawyerorg/j-lawyer-org#335]
Wenn das Clientfernster maximiert (also desktopfüllend) geschlossen wurde, sollte es auch maximiert beim nächsten Mal wieder gestartet werden. 
Alle anderen Größen werden bis zu einer bestimmten Maximalgröße abgespeichert - aber eben nicht die desktopausfüllende. Die Lage des Fensters ist bis zu einer bestimmten Größe immer mittig auf dem Desktop - wird also auch nicht gespeichert. Wenn das Fenster maximiert geschlossen wurde, startet es nicht mittig auf dem Desktop.

Die Trennbalken im Clientfenster sollten ebenfalls abgespeichert werden. Zum Beispiel beim Scanvorschau-Fenster ist ggf. nur die halbe Seite zu sehen, aber es gibt ungenutzten Platz am unteren Bildschirmrand. Dementsprechend wird das Vorschaufenster nach unten vergrößert. Beim nächsten Start ist wieder alles wie vorher.

Fenstergröße und Lage sowie Anordnung der Trennbalken sollte daher clientseitig und/oder Nutzerabhängig abgespeichert werden.

**Comment by j-dimension** [comment]
@bjk00

**Comment by bjk00** [comment]
In der Desktopansicht springt die Teilung zwischen "zuletzt geändert" / "nach Etikett" auch bei geöffnetem Client auf den Wert 50/50 zurück und zwar 
1. automatisch, ca. alle 30s
2. nach Klick auf den Aktualisierungs-Button links neben "nach Ettikett"

**Comment by PBaumfalk** [comment]
Gibt es eigentlich die Möglichkeit, dass das Fenster immer in der „letzten“ Position öffnet? Bei 2550 x 1440 muss ich immer das Fenster händisch verkleinern. Das ist viel zu groß.


Mit freundlichen Grüßen / Kindly Regards

Patrick Baumfalk
Rechtsanwalt / Lawyer


Mobil:    +49 1525 53 04 194
E-Mail:   patrick.baumfalk@kanzlei-baumfalk.de


Baumfalk - Rechtsanwaltskanzlei
Hauptstr. 195
50169 Kerpen

Tel.: +49 2273 40 68 504
Fax: +49 2273 59 03 565

E-Mail: info@kanzlei-baumfalk.de
Web: www.kanzlei-baumfalk.de

**Comment by bjk00** [comment]
> 
> 
> In der Desktopansicht springt die Teilung zwischen "zuletzt geändert" / "nach Etikett" auch bei geöffnetem Client auf den Wert 50/50 zurück und zwar
> 
>     1. automatisch, ca. alle 30s

Das automatische Zurücksetzten der Teilung scheint nur aufzutreten, wenn keine Etiketten zur Anzeige ausgewählt wurden.

Die Teilung zwischen "zuletzt geändert" / "Fällig" wird durch den Klick auf aktualisieren ebenfalls auf 50/50 zurückgesetzt.

**Comment by RA-crm** [comment]
Ist das Hacktoberfest schon vorbei?

Ergänzend zu den vorangegangenen Beiträgen. Der Dialog "Dokument hinzufügen" wird bei meinen Mitarbeitern und mir (Client 1.12.0.9 unter Linux Mint, verschiedene Versionen) sehr unvorteilhaft aufgeteilt angezeigt. Die beiden linken Spalten bekommen nur 1/5 des Raums. Man kann kauf etwas lesen. Auch die Box oben rechts ist sehr klein. Man muss jedesmal händisch die Trennbalken verschieben.

Auch hier bitte die Ansicht so konfigurieren, dass die ausgewählte Darstellung in einem Client bis auf weiteres übernommen wird.

**Comment by j-dimension** [comment]
Für Desktop, Scaneingang und Dokumenterstellung werden die Trennerpositionen jetzt gespeichert und wiederhergestellt. 

Wenn es weitere wichtige Dialoge gibt die das brauchen, bitte spezifisch benennen in neuem Ticket. Ich werde das nicht querbeet überall machen (können).

**Comment by j-dimension** [comment]
Wird mit der finalen 1.13 bereitgestellt.
