### ISSUE TITLE
Formatierenung / Darstellung der Dokumentenvorschau

### ISSUE THREAD

**Issue by Maz111111** [jlawyerorg/j-lawyer-org#336]
Wenn Libre Office Dokumente in der Vorschau angezeigt werden, werden Zeilenumbrüche nicht angezeigt.

Der Text eines Absatzes läuft also nach rechts aus dem Fenster und man muss den unteren Scrollbalken verwenden.

Hier wäre es besser, wenn die Darstellung der Seite so erfolgt wie im Office Fenster. 
Gerade wenn man nur kurz die gesetzte Frist suchen will oder die Aufzählung der Anlagen prüfen möchte, ist beides (Murphy's law) natürlich immer ganz rechts und man beginnt umständlich zu suchen. Meistens ist das Öffnen in Libre Office dann doch schneller.

**Comment by j-dimension** [comment]
Duplikat von #103
