### ISSUE TITLE
beA-Sendefenster zu klein und ohne Scrollbalken

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#345]
wenn ich eine beA-Nachricht erstelle, dann kommt ein Fenster, bei dem ich nur durch Zufall darauf kam, daß da unten noch mehr ist und ich das Fenster vergrößern muß, um alles zu sehen. Sollte ein Scrollbalken da sein. Und das Nachrichtenfenster - was man eh nicht so nutzen soll - ist auch zu groß. Wenn es kleiner wäre, dann würde die Anhang-Liste weiter oben sein. Und muß auch nicht so klein sein.

**Comment by stm9x9** [comment]
![image](https://user-images.githubusercontent.com/29924198/65392898-6d3d6700-dd7a-11e9-9d61-59abebc5e4b0.png)

ggf auch lieber die Anhangliste über das Nachrichtenfenster packen.

**Comment by stm9x9** [comment]
es fehlt IMHO immer noch ein Scrollbalken für das was unten rechts abgeschnitten wird

**Comment by j-dimension** [comment]
Nochmal einen Screenshot bitte, sehe ich nicht unter Linux / Windows 10.
