### ISSUE TITLE
[bea] Nachrichtentyp auswählen

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#347]
IMHO sollten wir auch mit j-l die drei verschiedenen Nachrichtentypen einstellen können:

![image](https://user-images.githubusercontent.com/29924198/65393203-1f2a6280-dd7e-11e9-8ba6-c4fcbeceb123.png)

Allgemeine Nachricht, Mahn-Antrag und Testnachricht.

**Comment by j-dimension** [comment]
Das ergibt nur Sinn, wenn sich die Auswahl auf irgendeine Art und Weise auf die Nachricht auswirkt. Ich sehe in der Schnittstellenbeschreibung der BRAK keine solche Typisierung.

**Comment by stm9x9** [comment]
Ich weiß nur, daß man eben für die Übermittlung einer EDA-Mahndatei eben diesen Typ auswählen soll. siehe https://www.brak.de/zur-rechtspolitik/newsletter/bea-newsletter/2017/ausgabe-18-2017-v-04052017.news.html#hl137497

**Comment by stm9x9** [comment]
Was meinst du mit, du findest keine Typisierung? 

Mir wurde nur gesagt, daß anhand dieses Datenfeldes bei Gerichten die erste Zuordnung zur richtigen Untereinheit vorgenommen wird. Also eben Mahnanträge zur Mahnabteilung. Es soll noch andere Auswahlmöglichkeiten für das Feld geben, die aber zb webBea nicht unterstützt und die möglicherweise für Gericht2Gericht da sind.

**Comment by j-dimension** [comment]
Die beA-Schnittstelle kennt kein Konzept von Nachrichtentypen. Daher weiss ich jetzt nicht, wie sich eine solche vom Nutzer getroffene Auswahl auf die Nutzung der Schnittstelle auswirken würde bzw. was von mir anzupassen wäre.

**Comment by stm9x9** [comment]
Es müßte einfach ein Datenfeld geben, wo das drinsteht, was der Typ ist. So wie ein Datenfeld für Aktenzeichen Sender etc. Es ändert sich je nach Nachrichtentyp wohl nichts an der Datenstruktur oder so.

**Comment by stm9x9** [comment]
ich finde auf die Schnelle nur:

![image](https://user-images.githubusercontent.com/29924198/65835215-f822e200-e2e3-11e9-9303-1cdfd2fc359f.png)

aus https://egvp.justiz.de/Drittprodukte/EGVP_Infrastruktur_Anforderungen_Teilnahme_von_Drittanwendungen.pdf

**Comment by j-dimension** [comment]
Hmm... finde da nix. Werde es mit einem "befreundeten" KSW-Hersteller besprechen.

**Comment by j-dimension** [comment]
Ich vermute dass dieses Ticket erst dann Relevanz hat, wenn ich die Mahnanträge implementiere. Ich schiebe daher, und beantrage Unterstützung für das gesamte Mahnantragsthema :-)

**Comment by stm9x9** [comment]
Mahnanträge kann man übrigens auch extern erzeugen und es wäre schön, die dann mit j-l verschicken zu können.

**Comment by j-dimension** [comment]
> Mahnanträge kann man übrigens auch extern erzeugen und es wäre schön, die dann mit j-l verschicken zu können.

Ja, irgendwie muss das über Schnittstelle zu setzen sein (Nachrichtentyp). Da sich die Rückmeldungen von Anwendern häufen (Mahngericht moniert Nachrichtentyp), zieh ich das Thema nochmal vor.

**Comment by j-dimension** [comment]
Hab evtl. eine API gefunden: messageDTO.setOsciSubject(MessageDTO.OSCISubjectTypeDTO.*);

OSCISubjectTypeDTO hat folgende Werte:

- allgemeine_nachricht
- hr_beteiligter
- hr_gericht
- mahn_abgabe
- mahn_antrag
- mahn_nachricht
- test_nachricht
- ubest_mahn

@stm9x9 kannst Du damit etwas anfangen? welcher der Mahntypen wäre der "richtige"? mahn_antrag?

**Comment by stm9x9** [comment]
das sieht mir jedenfalls richtig aus - allgemeine Nachricht ist ja zb das was wir sonst nehmen. Und test_nachricht gibt es in beA-web auch.

**Comment by stm9x9** [comment]
Laut https://www.brak.de/zur-rechtspolitik/newsletter/bea-newsletter/2017/ausgabe-18-2017-v-04052017.news.html#hl137497 sollen wir in beA-web "Mahn-Antrag" nehmen. Das wird vermutlich mit mahn_antrag korrespondieren.

**Comment by j-dimension** [comment]
Das Attribut / Feature ist in der Doku der BRAK nicht beschrieben, aber ein Versand und anschließender Export zeigt, dass die Nachrichten dann unterschiedlich aussehen. Ich kann das hier nicht testen und bräuchte vor dem Release der 1.13 dann Hilfe.

![image](https://user-images.githubusercontent.com/3729754/88979831-b9263a00-d2c2-11ea-9646-2cbe24cd8b00.png)

**Comment by stm9x9** [comment]
Ich würde rein optisch hinter das Auswahlfeld nicht das - damit nichts zutunhabende - signieren platzieren. Besser vor oder hintendran: Nachrichtentyp

**Comment by j-dimension** [comment]
Ich hab dort schlicht zu wenig Platz, andere Optionen würden den Dialog noch in der Vertikalen weiter aufblähen.

**Comment by stm9x9** [comment]
Wieso hast du denn da zu wenig Platz!?

![image](https://user-images.githubusercontent.com/29924198/89080205-821a5c00-d388-11ea-9069-fd2a0ff7af05.png)


IMHO könnte man da grundsätzlich eine zweite Spalte aufmachen. zb auch "gegen EB" nach rechts.

Die Elemente da drunter fordern ja eh eine gewisse Breite des Fenster.

Im ürbigen, fällt mir gerade auf, oben Empfänger und Betreff müssen eigentlich nicht über die ganze Breite gehen, da reicht es über dem Nachrichtenfenster IMHO aus.

**Comment by j-dimension** [comment]
Ja gut, in Deinem Screenshot ist der Slider / Trenner nach links gezogen. Jetzt denke Dir mal eine volle Anlagenliste hin, es ist kaum Platz um die Anlagennamen darzustellen!

Und es gibt etliche Anwender mit 1200 / 1300 Auflösung horizontal.
