### ISSUE TITLE
beA: Verstärkte Nutzung des xml-Anzeigenamens

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#349]
Ich glaube, es gibt ein Ticket hinsichtlich einer automatischen Benennung / Nummerierung von beA-Anhängen. Als Ergänzung:

Laut Aussagen der Zuständigen auf Gerichtsseite sind Dateinamen Schall und Rauch (außer wohl angeblich für die Reihenfolge beim Ausdrucken bei noch-nicht-elektronischen Gerichten - dafür dann auch diese Nummerierung oben). In dem Fachverfahren Eureka-fach wird stattdessen immer der Anzeigenamen im System angezeigt. Umgekehrt sollen auch die Anwalts-Fachsoftwaren nicht im Posteingang mit den Dateinamen arbeiten (da bekomme ich Sachen wie ITDZ_PROD_CL_156xxxxxxxxx7716763478395S 53 AS xxx_18.PDF - damit kann keiner was anfangen) sondern mit den im xjustiz.xml hinterlegten Anzeigenamen. Das wäre in dem Beispiel dann "Schriftsatz vom 11.07.2019". Das macht sich in unserer Dokumentenliste (aber auch schon in der Übersicht im beA-Viewer/Vorschau) wesentlich besser.

Das heißt beispielsweise auch, daß j-l immer eine xjustiz erzeugen sollte, auch ohne EB-Anforderung.

**Comment by j-dimension** [comment]
Referenz zu #248

**Comment by j-dimension** [comment]
Ich habe die Thematik mit den Aliasnamen / XJustiz-Dateibezeichungen in #248 aufgenommen und schliesse dieses Ticket als Duplikat.

**Comment by stm9x9** [comment]
Ich bin mir nicht sicher, ob das andere Ticket das richtig umfaßt. Hier geht es mir insbesondere auch darum, daß j-l bei aus- wie eingehenden Dokumenten eher den Anzeigenamen anzeigt als einen klassischen Dateinamen. Und für eingehende diesen zb aus der xjustiz extrahiert und abspeichert und anzeigt.

**Comment by j-dimension** [comment]
Ich setzt das jetzt erstmal für den Postausgang um. Für den Eingang sind Änderungen am Dokumentenmanagement notwendig, das ist eine andere Hausnummer. (und würde ein separates Ticket bedingen)
