### ISSUE TITLE
beA-Login asynchron

### ISSUE THREAD

**Issue by j-dimension** [jlawyerorg/j-lawyer-org#350]
bei automatischer Anmeldung

**Comment by stm9x9** [comment]
es geht das hier:

![image](https://user-images.githubusercontent.com/29924198/65394988-f5c90100-dd94-11e9-917b-644c0bb2970a.png)


Das dauert bei mir bis zu zwei Minuten. Und weil es zudem nicht "nach hinten klickbar" ist, sperrt das zusätzlich für Minuten den Bildschirm.

**Comment by j-dimension** [comment]
Wie (via Facebook) gesagt, das Laden im Vordergrund habe ich schon abgeändert. Zwei Minuten ist aber sehr extrem. Die Schulungsumgebung braucht gerne mal 20 Sekunden, aber nicht mehr.

**Comment by j-dimension** [comment]
Authentifizierung, Laden der Ordnerstruktur und Laden des Posteingangs nun vollständig asynchron, wenn automatische Anmeldung aktiviert ist.
