### ISSUE TITLE
beA: Aktenzeichen Empfänger erzeugen

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#351]
Ich habe in einer Akte einen Beteiligten mit beA/ERV-Postfach. Der hat in j-l ein Aktenzeichen. Ich erzeuge aus dieser Akte heraus:

a) aus der Beteiligtenliste mit bea Nachricht versenden
b) aus der Dokumentenliste mit bea senden

an diesen eine beA-Nachricht.

In allen Fällen wird das Aktenzeichen des Beteiligten nicht bei Akz Empfänger in der beA-Nachricht hinterlegt.

![image](https://user-images.githubusercontent.com/29924198/65393504-9c0b0b80-dd81-11e9-997e-51dea226f480.png)

**Comment by an-mus** [comment]
Es wäre gut, wenn das Empfänger Aktenzeichen auch editierbar wäre. Es kommt (bei mir) doch sehr häufig vor, dass ich in einer Akte mehrere Verfahren mit dem gleichen Gericht habe (z.B. Eilverfahren/Hauptsacheverfahren)

**Comment by j-dimension** [comment]
> Es wäre gut, wenn das Empfänger Aktenzeichen auch editierbar wäre.

Geht in Ordnung, @an-mus

**Comment by stm9x9** [comment]
ich bin ja immer für editierbar :-) aber dafür ist das nicht nötig bzw man sollte das eh anders angehen: Wenn ein Gericht zweimal vorhanden ist, sollte man es auch zweimal in den Beteiligten haben, eben um da unterschiedliche Aktenzeichen zu hinterlegen.
