### ISSUE TITLE
beA, Email: Elemente (Anhänge, Empfänger) löschen können

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#353]
Es wäre hilfreich, wenn man angehangene Dokumente und ausgewählte Empfänger im Entwurfsfenster wieder löschen könnte.

**Comment by Maz111111** [comment]
...und auch öffnen könnte, damit man noch mal kontrollieren kann.
Ich hatte in einer Mail mal das Problem, dass zwar alle Anhänge den richtigen Namen hatten, der Inhalt aber immer gleich war. 
Es war alles mit jL in pdf umgewandelt und ich weiß nicht, was da schief gelaufen ist. Seitdem kontrolliere ich die Anhänge aber ganz gern immer noch mal vor dem Versenden.

**Comment by j-dimension** [comment]
- [ ] Email: Empfänger löschen - geht manuell
- [ ] Email: Anhang löschen
- [ ] Email: Anhang öffnen - geht per Doppelklick
- [ ] beA: Empfänger löschen
- [ ] beA: Anhang löschen
- [ ] beA: Anhang öffnen
