### ISSUE TITLE
Adressfeld Kanzlei (und beA)

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#357]
Es gibt in beA einen neuen Suchparamenter bzw ein neues Datenfeld: "Kanzlei"

Sollte in der beA-Suche möglich sein und auch in der internen Adressdatenbank eingebbar sein. ggf (ich kenne da die interne Struktur nicht) in "Firma"?

**Comment by j-dimension** [comment]
Keine Ahnung. Muss schauen ob mit der letzten beA-Version das Datenmodell ggf. erweitert wurde.

**Comment by j-dimension** [comment]
@stm9x9 , ich finde im Datenmodell der BRAK die Attribute "Office Name" und "Organization". In der Testumgebung des beA finde ich keine Teilnehmer mit einem Kanzleinamen. Ich habe die Implementierung unter der Annahme erweitert, dass der "Kanzleiname" in der Weboberfläche dem Attribut "Office Name" entspricht.

**Comment by stm9x9** [comment]
Infos gibt es jedenfalls hier: https://www.brak.de/zur-rechtspolitik/newsletter/bea-newsletter/2017/ausgabe-50-2017-v-14122017.news.html#hl151307

**Comment by stm9x9** [comment]
es scheint so zu funktionieren. Ich kenne einen Kollegen mit Eintrag in dem Feld, der wird jetzt mit j-l so gefunden/angezeigt und in Firma im Adressbuch übernommen.

**Comment by stm9x9** [comment]
Aber die Suche danach funktioniert nicht richtig. Ich habe mal oBdA Müller in Berlin gesucht. Ich finde an Anwälten tatsächlich nur welche mit Müller in der Kanzlei aber ich finde auch lauter Gerichte etc.

![image](https://user-images.githubusercontent.com/29924198/65559483-159a2980-df3b-11e9-8dd4-42d90fb393b8.png)

PS: Kann man eigentlich per API die Suche auf den Typ xy einschränken? Also Justiz oder Rechtsanwalt zb?

**Comment by stm9x9** [comment]
Wenn ich aus dem obigen Beispiel mal nach Wrede suche dann finde ich keinen einzigen Anwalt. Geht die Suche immer nur vom Namensanfang her? Aber stattdessen 100x Justiz-Einträge, die alle Wrede überhaupt nicht enthalten.

**Comment by j-dimension** [comment]
Ich glaube da ist gerade grundsätzlich etwas kaputt bei der BRAK. Zur Sicherheit öffne ich das Ticket wieder und teste morgen / übermorgen erneut.

**Comment by j-dimension** [comment]
> PS: Kann man eigentlich per API die Suche auf den Typ xy einschränken? Also Justiz oder Rechtsanwalt zb?

Nein, diese Funktionalität ist nicht vorhanden.
