### ISSUE TITLE
beA: eEB angefordert Icon obwohl nicht angefordert

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#358]
Ich habe etliche Eingänge mit dem grünen eEB Icon, aber da wird keines gefordert:

![image](https://user-images.githubusercontent.com/29924198/65395033-b949d500-dd95-11e9-97f3-4929afbd4c4a.png)

**Comment by j-dimension** [comment]
Die Information "ist ein eEB angefordert ja/nein" wird von der Schnittstelle geliefert, ich reiche das nur durch. 
Schaue ich mir aber gern nochmal an.

**Comment by j-dimension** [comment]
Behoben in BeaWrapper. Benötigte erweiterte Prüfung Nachrichten-Metadaten.

**Comment by stm9x9** [comment]
> Benötigte erweiterte Prüfung Nachrichten-Metadaten.

Was genau brauchst du noch?

**Comment by j-dimension** [comment]
Konntest Du es mit der letzten Version nochmal testen?

**Comment by stm9x9** [comment]
weiterhin: Test an mich gesendet. In der Liste mit grünem Icon. In der Nachricht ohne.

![image](https://user-images.githubusercontent.com/29924198/65840211-61bbe400-e316-11e9-8b3b-34be4d1c4898.png)

**Comment by stm9x9** [comment]
weiterhin. An mich gesendet ohne eEB. In der Liste mit grünem Icon. In der Nachricht korrekt ohne.

![image](https://user-images.githubusercontent.com/29924198/65840221-8a43de00-e316-11e9-8fd5-6c8897f434c0.png)

**Comment by j-dimension** [comment]
Toll. Die neueste Schnittstellenversion liefert das Attribut nicht mehr. 

Hintergrund: es gibt zwei Dienste 

(1) Nachrichtenüberblick holen: man bekommt eine Liste von Metadaten zu allen Nachrichten in einem Ordner. Dort ist die Struktur, die mal das eEB-Flag lieferte, nun leer. 

(2) Nachricht holen: man bekommt alle Daten zu einer Nachricht. Dort ist das Attribut korrekt gesetzt.

Muss die Spalte wohl eliminiert werden... nur: ich finde dass das auch für das beA Web sinnvoll wäre, Nachrichten mit angefordertem eEB schneller erkennen zu können.

**Comment by stm9x9** [comment]
> Muss die Spalte wohl eliminiert werden... nur: ich finde dass das auch für das beA Web sinnvoll wäre, Nachrichten mit angefordertem eEB schneller erkennen zu können.

Die Möglichkeit gibt es sogar und wird auch aktiv beworben. Aber nicht über eine Spalte, sondern so:  https://www.brak.de/zur-rechtspolitik/newsletter/bea-newsletter/2019/ausgabe-23-2019-v-2162019/

Auch wenn das erst funktioniert, wenn eine Nachricht gelesen wurde, weil die ungelesen-Farbe Vorrang hat. Aber man kann auch eine virtuelle Sicht definieren, die nur Nachrichten mit EB anzeigt. Jedenfalls muß man nicht in die Nachricht rein.

**Comment by stm9x9** [comment]
> (1) Nachrichtenüberblick holen: man bekommt eine Liste von Metadaten zu allen Nachrichten in einem Ordner. Dort ist die Struktur, die mal das eEB-Flag lieferte, nun leer.

offtopic: Ist das der Grund, warum man in der Liste nur den komischen beA-Namen zu Gesicht bekommt bei Anwälten VornameNachmameBuchstabensalat bzw die ID bei Gerichten und in der Nachrichtenanzeige dann den richtigen "Vorname Nachname"?

**Comment by j-dimension** [comment]
> st das der Grund, warum man in der Liste nur den komischen beA-Namen zu Gesicht bekommt bei Anwälten VornameNachmameBuchstabensalat bzw die ID bei Gerichten und in der Nachrichtenanzeige dann den richtigen "Vorname Nachname"?

Ja, in den Headern habe ich nur den "User Name", in der vollen Nachricht dann den "Sender Name". Mal von der unklaren Terminologie abgesehen ist das der Grund für die abweichenden Darstellungen. Ich möchte in jedem Fall vermeiden, für die Darstellung der Nachrichtenübersicht alle Nachrichten voll laden zu müssen.

**Comment by stm9x9** [comment]
> Ich möchte in jedem Fall vermeiden, für die Darstellung der Nachrichtenübersicht alle Nachrichten voll laden zu müssen.

Das ist verständlich. Und bei Gerichten ist der User Name nur die Govello-ID? Weil da ist es schon nervig, nicht gleich zu sehen, von wem es kommt. Ob da nun VornameNachmameBuchstabensalat oder Vorname Nachname steht, ist hingegen eher egal.
