### ISSUE TITLE
beA: erstellte eEBs nicht in Ordnung

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#359]
eEBs aus j-l sind nicht lesbar für den Empfänger - mir scheint, es fehlt der Inhalt in tns:fremde_Nachrichten_ID

**Comment by stm9x9** [comment]
einmal mit j-l erzeugt, einmal in beA-web

[eEB-j-l.xml.txt](https://github.com/jlawyerorg/j-lawyer-org/files/3640221/eEB-j-l.xml.txt)
[eEB-web.xml.txt](https://github.com/jlawyerorg/j-lawyer-org/files/3640222/eEB-web.xml.txt)

**Comment by stm9x9** [comment]
und es muß die Möglichkeit geben, das Datum des EBs manuell zu setzen. Ist gesetzlich vorgeschrieben.

**Comment by j-dimension** [comment]
Schaue ich mir an. 

Datumseingabe in separates Tickets gesplittet.

**Comment by j-dimension** [comment]
> eEBs aus j-l sind nicht lesbar für den Empfänger

Wie äußert sich das?

**Comment by j-dimension** [comment]
Der XJustiz-Standard ist mir an der Stelle zu unkonkret: 

> fremde_Nachrichten_ID
> (Kommentar: Referenz zum anfordernden übermittelten Schriftgutobjekt)

Mir ist nicht ganz klar ob damit die ID der Nachricht gemeint ist, mit welcher ein eEB angefordert wird, oder ob es sich um die ID des eingehenden eEB handelt. 
Ich vermute zweites, zumindest passt das von der Syntax her mit der von Dir zur Verfügung gestellten xjustiz-nachricht. Dort haben die IDs mehrere Komponenten, die mit Bindestrich getrennt sind. Die beA-Nachrichten-IDs sind hingegen nur numerische Werte.

**Comment by j-dimension** [comment]
Korrigiert und erfolgreich getestet wie folgt:
- beA Web: Nachricht mit 1 Anhang und eEB-Anforderung versendet
- j-lawyer.org: eEB abgegeben
- beA Web: empfangene eEB-Abgabe visualisiert

Scheint zu passen.

**Comment by stm9x9** [comment]
kann ich dann auch im live-Betrieb testen, wenn es wieder eine neue Test-Version gibt.

**Comment by j-dimension** [comment]
Da möchte ich auf keinen Fall bremsen :-) 

Die neuen Installer eines offiziellen Clients 1.10.0.11 werden gerade in die Cloud geladen, und zwar der ursprüngliche Link für alle Pilotanwender, nicht der wo ich nur Dir die .jars zur Verfügung gestellt habe. 
In ein paar Minuten sollte alles hochgeladen sein.

**Comment by stm9x9** [comment]
Sieht grundsätzlich iO aus. Einzig: Der EB-abgebende wird nicht angezeigt:

![image](https://user-images.githubusercontent.com/29924198/65840264-253cb800-e317-11e9-90de-54fe76841794.png)

so sieht es im web aus

![image](https://user-images.githubusercontent.com/29924198/65840275-443b4a00-e317-11e9-9f56-f28939c108f4.png)

Wenn es irgendwie auflösbar ist, wäre es schön, wenn man da hinter die ID noch den beA-Namen packt.

**Comment by stm9x9** [comment]
äh, ach so, der Inhalt fehlt bei j-l auch!

**Comment by j-dimension** [comment]
> 
> 
> äh, ach so, der Inhalt fehlt bei j-l auch!

Da brauch nich nochmal mehr Kontext: Das ist ein eEB das über Web erstellt und in j-lawyer.org angezeigt wird?

**Comment by stm9x9** [comment]
ich habe jetzt aus j-l ein eEB abgegeben. In meinem gesendet-Order ist die eEB-Nachricht. Wenn ich da auf eEB anzeigen klicke kommt:

**Comment by stm9x9** [comment]
![image](https://user-images.githubusercontent.com/29924198/65885899-b190be80-e39b-11e9-9354-833be3edfde4.png)

**Comment by stm9x9** [comment]
dasselbe passiert, wenn ich das eEB im Web erstelle und an mich schicke. Ist also ein Darstellungsfehler und kein Fehler bei der Erstellung der xml

**Comment by j-dimension** [comment]
> dasselbe passiert, wenn ich das eEB im Web erstelle und an mich schicke. Ist also ein Darstellungsfehler und kein Fehler bei der Erstellung der xml

Also ist das Ticket erstmal abschliessbar?

**Comment by stm9x9** [comment]
ich habe es nochmal hoffentlich verständlicher markiert. Ich habe ein eEB mit beA-Web abgegeben. Das sieht in j-l so aus:

![image](https://user-images.githubusercontent.com/29924198/66007498-f9eed000-e4b2-11e9-9dfe-35aac81a6502.png)

es sollte aber (wie im Web) so aussehen:

![image](https://user-images.githubusercontent.com/29924198/66007510-02dfa180-e4b3-11e9-88f9-fcd97be6c98c.png)

**Comment by stm9x9** [comment]
ganz merkwürdig: Wenn ich mir in j-l die Nachricht des Gericht ansehe, wo das eEB gefordert wurde, und dort das abzugebende eEB angucke:

![image](https://user-images.githubusercontent.com/29924198/66007627-784b7200-e4b3-11e9-8dd5-35686763d564.png)

alles da!

**Comment by j-dimension** [comment]
Sehr merkwürdig. Die XMLs werden mittels einer Transformation als HTML dargestellt, und dazu nutzen sowohl beA als auch j-lawyer die offiziellen Stylesheets des jeweiligen XJustiz-Versionsstandes...

**Comment by j-dimension** [comment]
@stm9x9 nochmal in Kurzfassung: das Problem betrifft die Visualisierung selbst abgegebener eEB, korrekt?

**Comment by stm9x9** [comment]
Nein nicht unbedingt. Das letzte betrifft eBs, die von irgendwem abgegeben wurden und an mich gesendet wurden und die ich mir dann in j-l angucke. Ich speichere die xml auf dem PC und gucke mir die Datei so an: alle Daten sind vorhanden. nur j-l zeigt sie nicht an.

**Comment by j-dimension** [comment]
@stm9x9 kannst Du mir so ein "Problem-XML" zur Verfügung stellen (die xjustiz_nachricht.xml). Oder noch besser: eine exportierte .bea - Datei?
