### ISSUE TITLE
Eintragen einer Frist

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-org#36]
Es wäre eine gute option, wenn man zu einer Frist automatisch eine Wiedervorlage z.B. 3 Tage vorher eintragen könnte, also grundsätzlich. Ich lege mir die Akten vor Ablauf einer Frist immer 3 Tage vorher vor, um sie nicht zu verpennen, bzw. einen schlafenden Mandanten, der mit Informationen nicht in "die Puschen" gekommen ist, nochmals zu erinnern, dass die Frist abläuft.

**Comment by Maz111111** [comment]
In meinem schönen Soldan Terminkalender ist das über eine Spalte "Vorfrist" gelöst.
Nutze ich auch regelmäßig.
Also einfach zu Wiedervorlage und Frist noch den Auswahlknopf Vorfrist dazu.

**Comment by stm9x9** [comment]
Die genauen Tage könnte man ja in den allgemeinen Einstellungen hinterlegen.

**Comment by j-dimension** [comment]
> Die genauen Tage könnte man ja in den allgemeinen Einstellungen hinterlegen.

Du meinst zu einer Frist xyz eine Vorfrist samt Namen und "Vorlauftagen" konfigurieren?

**Comment by stm9x9** [comment]
Ich meine:

in den Einstellungen sowas wie:
Vorfrist soviele Tage vorher eintragen: X

Und dann einfach einen Zusatzhaken bei der Erstellung einer Frist: [ ] Vorfrist eintragen.

Dann müßte es auch einen weiteren Typ: Vorfrist geben. Aber IIRC gab es dazu eh schon ein Ticket?

**Comment by stm9x9** [comment]
eines müßte man da noch überlegen - ich weiß nicht wie die übrigen Anwälte das hier handhaben:

Vorfristen sind bei mir immer eine Woche. Aber es gibt Ausnahmen!
Beratungshilfeanträge brauchen regelmäßig mehr Vorlauf, um Mandantenunterlagen noch anfordern zu können, da mache ich 2 Wochen.

Und Betreibensaufforderungen bekommen bei mir sogar 4 Wochen.

Entweder muß man das hinterher händisch korrigieren oder:

[ ] Vorfrist eintragen für [Datumsfeld mit einer Woche vorbelegt aber änderbar]

**Comment by Dickmaulruessler** [comment]
#1145 Das würde - auf anderem Wege - dasselbe erreichen.

**Comment by j-dimension** [comment]
https://github.com/user-attachments/assets/6c00e9fb-fe18-4ba5-8984-545e7b50e24f

**Comment by j-dimension** [comment]
Es können nun n Tage Vorlauf / Nachlauf für einen Kalendereintrag konfiguriert werden. Für den "zweiten" Kalendereintrag können Name und Beschreibung vordefiniert werden, bspw. für den Haupteintrag "Vollmacht anfordern" kann für +5 Tage ein Eintrag "Vollmacht erhalten?" definiert werden.
Der Nutzer bekommt dann ein Popup für den zweiten Kalendereintrag und kann dort nochmal nachschärfen, sofern notwendig.

**Comment by Dickmaulruessler** [comment]
Cool!
Das werden viele glaube ich lieben! ♥
