### ISSUE TITLE
Es muß die Möglichkeit geben, das Datum des eEBs manuell zu setzen.

### ISSUE THREAD

**Issue by j-dimension** [jlawyerorg/j-lawyer-org#360]
und es muß die Möglichkeit geben, das Datum des EBs manuell zu setzen. Ist gesetzlich vorgeschrieben.

_Originally posted by @stm9x9 in https://github.com/jlawyerorg/j-lawyer-org/issues/359#issuecomment-533923186_

**Comment by j-dimension** [comment]
@stm9x9

**Comment by stm9x9** [comment]
![image](https://user-images.githubusercontent.com/29924198/65840285-751b7f00-e317-11e9-8e1a-7f0c28d9b2fe.png)

Da ein EB nicht für die Zukunft abgegeben werden kann, würde ich die Zukunft nicht einblenden. Da man auch nicht beliebig spät abgeben soll, würde ich meinen, es reicht der aktuelle Monat und der letzte.

**Comment by j-dimension** [comment]
> Da ein EB nicht für die Zukunft abgegeben werden kann, würde ich die Zukunft nicht einblenden. Da man auch nicht beliebig spät abgeben soll, würde ich meinen, es reicht der aktuelle Monat und der letzte.

Habe ich als neues Ticket #381 für 1.11 erfasst.
