### ISSUE TITLE
Kennzeichnen der Dokumententags

### ISSUE THREAD

**Issue by Maz111111** [jlawyerorg/j-lawyer-org#362]
Es sollte möglich sein, einem Dokument mehrere Tags zuzuorden (das geht) und dies aber auch auf den ersten Blick sichtbar zu machen.
Dies könnte über Farben und Schriftarten / Attribute gehen.
Bsp:
Ein Dokument erhält den Tag Schriftverkehr mit Gericht - diesem würde ich eine Farbe zuordnen, die auch dauerhaft eingeschaltet bleibt. Also immer wenn ich den Doku-Reiter anwähle, werden alle Doks mit diesem Tag rot dargestellt.
Nun gab es neuen Posteingang, den meine Mitarbeiterin eingescannt und der Akte zugeordnet hat. Diesen Doks und den Akten, zu denen sie gehören, würde der Tag "unbearbeiteter PE" zugeordnet - hier würde ich auf Dok Ebene das Attribut Fettdruck wählen.
So würde ich (ich sitze im Homeoffice und betreue mein krankes Kind oder sitze im Urlaub am Strand) sofort erkennen können, dass es neuen Posteingang in einer Akte (das geht ohnehin schon) vom Gericht gibt.
Müsste doch machbar sein.

**Comment by Maz111111** [comment]
Letzten Endes sollte das darauf hinaus laufen, dass man die Dokumente auch nach den Tags sortieren kann.

**Comment by j-dimension** [comment]
Duplikat von #69. 

Die Formatierung der Dokumentnamen an sich halte ich nicht für zielführend, da die Anzahl der Kombinationen beschränkt ist. Ich würde dann lieber die Tags an sich spezifisch darstellen. 

Weitere Kommentare gern an #69. Ich "hänge" Dich dort mit dran.
