### ISSUE TITLE
XJUSTIZ 2.4?

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#364]
Ist das schon berücksichtigt, daß mit https://bea-abc.de/blog/quo-vadis-bea/ xjustiz 2.4 je nach Empfänger - betrifft ggf nur die Gerichte? - ein anderes "Subset" (würde ich mal so nennen) der Definition des xml-Strukturdatensatzes ausgewählt und angewandt werden muß? im web erfolgt dies über eine (automatisierte) Auswahl aus einem pulldown.

**Comment by j-dimension** [comment]
XJustiz 2.4 erwartet eine sogenannte "Instanzbehörde". j-lawyer.org fragt die ja auch ab, wenn man Versand gegen eEB wählt. Die dortige Liste der auswählbaren Gerichte definierte auch direkt der XJustiz-Standard. 

Eine andere XML-Struktur je nach Auswahl gibt es m.E. nicht.

**Comment by stm9x9** [comment]
Mir wurde es nur so erklärt, daß da irgendwas empfängerspezisch sein soll.

> . j-lawyer.org fragt die ja auch ab, wenn man Versand gegen eEB wählt.

genau dann ist es aber nicht der richtige Zeitpunkt. Grund: gegen eEB kann (soll/darf?) man nicht an Gerichte senden. Jedenfalls ist das in web-bea nicht möglich und das Gesetz sieht auch keine Zustellung an Gerichte gegen EB vor. Nur andersrum oder Anwalt2Anwalt oder Notar oder so.

ein xjustiz.xml soll aber gerade gegenüber Gerichten verwendet werden - da würde ich dann entweder vorschlagen, es eh immer zu erzeugen oder aber (weil man zb aus Gründen ein selbstgefertigtes xml nutzen will) wie in web-bea den Strukturdatensatz anschaltbar zu machen.

**Comment by j-dimension** [comment]
Die Auswahl bedeutet ja nicht, dass man an dieses Gericht dann sendet. Es ist einzig eine notwendige Angabe innerhalb des Strukturdatensatzes.

**Comment by stm9x9** [comment]
Vielleicht mißverständlich formuliert:

a) wenn ich an einen Anwalt per eEB sende, dann soll und muß ich in beA-Web keinen dieser Instanzbehörden auswählen. Da steht dann unbekannt und wird angenommen:

![image](https://user-images.githubusercontent.com/29924198/65840429-5e762780-e319-11e9-8fb8-0a07e8491ce0.png)


b) wenn ich an ein Gericht sende dann soll ich einen Strukturdatensatz erzeugen. Aber das geht aktuell bei j-l nur (außer durch manuelles externes erzeugen und hochladen), wenn ich eEB anklicke. Aber ein eEB kann/soll ich nicht von Gerichten fordern.

Und wenn ich eine xml ans Gericht erzeuge, dann wäre es schön, wenn - wie im bea-Web - die Instanzbehörde bereits vorausgewählt ist:

![image](https://user-images.githubusercontent.com/29924198/65840474-f70ca780-e319-11e9-9445-04d6e0402c43.png)

**Comment by j-dimension** [comment]
D.h.
- zwei Optionen: "gegen Empfangsbekenntnis" und "nur Strukurdatensatz".
- Auswahl Justizbehörde nur wenn an ein Gerichtspostfach versendet wird
- Vorauswahl Justizbehörde: weiss noch nicht wie ich das am besten hinbekomme. 

Korrekt?

**Comment by stm9x9** [comment]
für ein Versenden an einen Anwalt aus dem Web kommt bei mir folgendes in die xml:

```
<tns:verfahrensdaten>
<tns:instanzdaten_erweitert>
<tns:instanzdaten>
<tns:instanznummer>1</tns:instanznummer>
<tns:sachgebiet listURI="urn:xoev-de:xjustiz:codeliste:gds.sachgebiet" listVersionID="2.1">
<code>039</code>
</tns:sachgebiet>
<tns:instanzbehoerde>
<tns:gericht listVersionID="2.6">
<code>9A0000</code>
</tns:gericht>
</tns:instanzbehoerde>
<tns:aktenzeichen/>
</tns:instanzdaten>
</tns:instanzdaten_erweitert>
</tns:verfahrensdaten>
```

**Comment by stm9x9** [comment]
> D.h.
> 
> * zwei Optionen: "gegen Empfangsbekenntnis" und "nur Strukurdatensatz".

Kann man mit "nur Strukturdatensatz" machen oder wie im Web einfach nur "Strukturdatensatz". Dabei wird Strukturdatensatz aber erzwungen, wenn man EB anwählt.


> * Vorauswahl Justizbehörde: weiss noch nicht wie ich das am besten hinbekomme.

einfach den EGVP-Namen des Empfängers in das Suchfeld einspielen?

![image](https://user-images.githubusercontent.com/29924198/65881559-e3058c00-e393-11e9-8aa8-c080dd2da868.png)

> * Auswahl Justizbehörde nur wenn an ein Gerichtspostfach versendet wird

Auswahl Justizbehörde würde ich nicht auf Gerichte einschränken. Die Liste enthält ja noch andere.

![image](https://user-images.githubusercontent.com/29924198/65881413-a8035880-e393-11e9-81f3-30a3c094a58e.png)

oder ganz anders:

**Comment by j-dimension** [comment]
Hab ich so ungefähr umgesetzt. Der Anwaltsname wird im Auswahldialog nicht eingetragen, aber es wird das zuletzt ausgewählte vorausgewählt.

Der "unbekannt"-Button ist eine gute Idee, habe ich so umgesetzt.

Die Optionen im Sende-Dialog sind nun überarbeitet. Es wird nun also IMMER ein Strukturdatensatz mitgeschickt. 

Die beA-Weboberfläche hat keine Möglichkeit, den Strukturdatensatz anzuzeigen, wenn nicht gleichzeitig ein eEB angefordert wird. Klingt komisch, ist aber so.

**Comment by stm9x9** [comment]
> Hab ich so ungefähr umgesetzt. Der Anwaltsname wird im Auswahldialog nicht eingetragen, aber es wird das zuletzt ausgewählte vorausgewählt.

Wenn man an ein Gericht schickt, dann kann das Gericht auch nicht voreingetragen werden?

Dann würde ich eher gar nichts eintragen, das mit dem letzten Eintrag irritiert, IMHO.


> Die Optionen im Sende-Dialog sind nun überarbeitet. Es wird nun also IMMER ein Strukturdatensatz mitgeschickt.

Was passiert, wenn man einen eigenen Strukturdatensatz hochgeladen hat?

> Die beA-Weboberfläche hat keine Möglichkeit, den Strukturdatensatz anzuzeigen, wenn nicht gleichzeitig ein eEB angefordert wird. Klingt komisch, ist aber so.

beA IST komisch! Aber man kann es als Fachsoftware ja besser machen :-)

**Comment by j-dimension** [comment]
> Was passiert, wenn man einen eigenen Strukturdatensatz hochgeladen hat?

Wer würde sowas in welchem Anwendungsszenario tun?

**Comment by stm9x9** [comment]
also nach Rückfrage scheint es besser zu sein, eine xml immer zu erzeugen.
