### ISSUE TITLE
beA: gesendet-Ordner ohne Sendedatum

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#365]
betrifft sowohl früher per web versendete als auch jetzt per j-l versendete Nachrichten:

die Spalte gesendet ist leer. Sollte da nicht Datum/Zeit stehen?

![image](https://user-images.githubusercontent.com/29924198/65559717-049de800-df3c-11e9-9727-79d81baf241e.png)

beim Eingang ist das nicht so

**Comment by stm9x9** [comment]
ist in der letzten beta noch nicht gelöst bei mir

**Comment by j-dimension** [comment]
Das kann ich nicht nachvollziehen - kannst Du nochmal mit den letzten .jar - Dateien probieren? (siehe Cloud-Freigabe wo die Installer liegen, unter "jars").
