### ISSUE TITLE
beA: ellenlanges Journal mit Abholen_der_Nachricht_KSW

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#366]
ich habe hier etliche Nachrichten mit immer länger werdendem Journal. Ständig wird ein Abholen der Nachricht dokumentiert:

![image](https://user-images.githubusercontent.com/29924198/65559989-2e0b4380-df3d-11e9-899f-c29556041f18.png)

**Comment by j-dimension** [comment]
Ja, das Journal wird automatisch beA-seitig erweitert, wenn eine Nachricht per Kanzleisoftware abgeholt wird.

**Comment by j-dimension** [comment]
Betrifft das alle Nachrichten? Nur die im Posteingang? Wie schaut es bei den anderen Ordnern aus?

**Comment by stm9x9** [comment]
offenbar jedes(!) in Posteingang und zwar jedes mal ein weiterer Eintrag, wenn ich es nach einem j-l-Neustart neu aufrufe.

Posteingang - Unterorder Test: hier passiert zb nix derart. gesendet auch nicht.

**Comment by j-dimension** [comment]
Dachte ich mir. Die BRAK hat sich entschieden, Abrufe über die Schnittstelle im Journal aufzunehmen.

Und ich habe mich entschieden, nach Login im beA automatisch im Hintergrund die Nachrichtenköpfe im Posteingang (und zwar nur in diesem Ordner) im Hintergrund "vorzuladen", damit dort keine langen Wartezeiten entstehen. 

Daher dort die Journaleinträge.

**Comment by j-dimension** [comment]
Ich möchte das Journal nicht selbst "manipulieren", würde den Punkt daher vorerst schliessen. Bis auf die Menge der Einträge gibt es auch keine negativen Auswirkungen.
