### ISSUE TITLE
Dokument duplizieren

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-org#367]
Wenn man ein Dokument duplizieren will und dann die Sache abbrechen will (und daher keinen anderen Namen vergibt) wird trotz klicken auf das Abbruchkreuzchen rechts oben im Fenster mit der Aufforderung zur Namensvergabe eine Dublette des Textes angelegt.

**Comment by Mucki526** [comment]
Korrektur. Die Dublette wird angelegt, wenn man den Namen verändert hat und dann abbrechen will. Dann erscheint trotzdem die Dublette. Wenn man den Namen nicht verändert klappt das Abbrechen.

**Comment by j-dimension** [comment]
Erledigt.
