### ISSUE TITLE
beA: Aktenzeichen im Nachrichtenformular

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#368]
Es sollte im neue-beA-Nachricht-Formular nicht nur der Betreff setzbar sein sondern auch das Aktenzeichen (wenn aus einer Akte heraus aufgerufen, natürlich vorbelegt nach den dort hinterlegten Aktenzeichen).

Grund: 

1) Wenn man - sei mangels Akte oder anderem Grund - eine beA schreibt, sollte man ein Aktenzeichen angeben können.

2) auch wenn man aus einer Akte heraus sendet und ein Aktenzeichen vorbelegt ist, kommt es in der Praxis vor, daß man das Aktenzeichen leicht anpaßt. zb bei einer Einstweiligen Anordnung ein ER ans Ende des Aktenzeichens. Daher sollte es auch hier anpaßbar sein.

**Comment by j-dimension** [comment]
Okay. Packe ich aber erstmal in die 1.11.

**Comment by stm9x9** [comment]
vielleicht paßt es hierzu, ansonsten bitte ausgliedern:

Unabhängig davon, daß nach meinem Vorschlag das Aktenzeichen im Nachrichtenformular angezeigt und editierbar sein sollte: das Aktenzeichen des Empfängers wird aktuell gar nicht in die Nachricht übernommen, das Feld ist immer leer nach dem Senden.

**Comment by j-dimension** [comment]
Ist das gesamte Aktenzeichenhandling im beA nicht völlig unlogisch und kaputt? Ich kann mehrere Empfänger für eine Nachricht auswählen, aber alle erhalten das gleiche AZ? Warum gibt es nicht ein Empfänger-AZ pro Empfänger?

**Comment by stm9x9** [comment]
Mehrere Empfänger für eine Nachricht mag irgendwie gehen, aber zumindestens im web-beA ist das mit etlichen Problemen behaftet. Letztlich würde ich meinen, EGVP ist eigentlich als 1:1 zu betrachten.
