### ISSUE TITLE
Dezernat als Bestandteil von Aktenzeichenschemata

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#369]
In vielen Kanzleien mit mehr als einem Anwalt werden die Aktenzeichen um den bearbeitenden Anwalt ergänzt.

zb 305-NN-19 für RA Nomen nescio und 306-MM-19 für RAin Marta Mustermann.

Dazu bräuchte es in der Nutzerverwaltung das zusätzliche Feld Initialen oder so und deren Einbindungsmöglichkeit in das Aktenschema.

(wobei wir auch wieder bei der Änderung eines Aktenzeichen wären, wenn mal die Akten den Anwalt wechselt)

Das Bearbeiterkürzel eines Nicht-Anwalts wird oft auch als Anhang an das Aktenzeichen in Schriftsätzen gepackt, wenn das kein Anwalt verfaßt hat. zb: 305-NN-19 mf oben in der Aktenzeichen/Datum-Zeile für ein Schreiben der Reno Musterfrau.

**Comment by stm9x9** [comment]
Ergänzung: Ich kenne eine befreundete Kanzlei, die hat mehr als einen Standort. Da wird dann auch der Standort im Akz codiert:

MP-305-NN-19 für RA NN am Münsterplatz und SW-306-MM-19 für RAin Mustermann im Seeburger Weg. 

Entweder müßte man in diesem Fall beide Standorte getrennt mit j-l versorgen (dann müßte man aber wenigstens im Aktenschema noch "Konstanten" reinschreiben können. (kann man grundsätzlich auch, aber nicht, wenn diese eine der Variablenbezeichnungen wie N oder M oder Y ... enthalten). Oder - wenn man j-l zentral für alle betreibt, dann müßte man das irgendwie ähnlich wie die Initialen machen. Aber ich weiß ehrlich gesagt nicht wie. Und das oben mit den Namen an einem Standort / einer Kanzlei halte ich für das weitaus öfter vorkommende Szenario und daher dringlicher.

**Comment by stm9x9** [comment]
Wie gehört eigentlich das Diktatzeichen in diesen Kontext?

**Comment by j-dimension** [comment]
Beim Diktatzeichen geht es um Verantwortlichkeiten bezogen auf das Dokument. 
https://www.sekretaria.de/bueroorganisation/korrespondenz/din-5008/diktatzeichen/

Ich glaube allerdings dass diese Angabe irgendwie überflüssig geworden ist. Ich kenne wenige Anwender die das in der Kanzlei so praktizieren / nutzen.

**Comment by stm9x9** [comment]
Wenn ich das richtig verstehe dann müßte man ja in j-l für jede mögliche Kombination aus Anwalt und Sekratariat einen Eintrag hinterlegen: a-x, a-y, a-z, b-x, b-y ...   8-o

**Comment by j-dimension** [comment]
Ja, vielleicht nicht für jede, in etlichen Büros scheint es so zu sein dass Sekretariats-MA1 für RA1 tätig ist, und Sekretariats-MA2 für RA2 und RA3. 

Wie gesagt - es liegt letztlich am Anwender das zu nutzen / zu konfigurieren oder nicht.

**Comment by j-dimension** [comment]
Nutzerverwaltung:

- Nutzer bekommt ein zusätzliches Attribut "Dezernat". Dort können im einfachen Fall die Initialen aufgenommen werden, oder beliebige andere Attribute "kodiert" werden, bspw. für Otto Müller am Standort Hamburg ein OM-HH.
- Mehrere Nutzer können den selben Dezernat-Wert haben.
- Das Dezernat ist case-sensitiv zu behandeln. Ein Dezernat aB ist ein anderes als Ab.
- Im Aktenzeichenschema muss es zusätzliche "Platzhalter" für das Dezernat geben, an beliebiger Stelle im Aktenzeichen.
- Im Einstellungsdialog für die Schemata sollten einige zusätzliche auswählbare Schemata aufgenommen werden, welche das Dezernat am Anfang / Ende des AZ beinhalten.
- Ist ein Schema mit Dezernat gewählt, MUSS bei Anlage einer Akte das Vorhandensein eines Dezernat-Wertes am anlegenden Nutzer geprüft werden. Ist das nicht der Fall, so wird das Anlegen der Akte mit einer Fehlermeldung abgelehnt.
- Die laufenden Nummern / zufälligen Nummern innerhalb des Schemas sind vom Dezernat unabhängig, d.h. bspw. bei laufender Nummer und drei unterschiedlichen Dezernaten bleibt die laufende Nummer über alle Dezernate hinweg eindeutig.

**Comment by j-dimension** [comment]
Ich tendiere momentan dazu, den Anwender das Derzernat bestätigen zu lassen, wenn es im AZ-Schema enthalten ist. Alles andere wäre zu starr. Es wird sicher auch Fälle geben, wo ein Anwalt X für einen Anwalt Y eine Akte anlegt, weil der gerade in Urlaub ist.

Die Frage könnte aber mit einem Dezernat vorbelegt sein, entweder direkt jenes am Nutzer oder am für die Akte angegebenen Anwalt.

**Comment by j-dimension** [comment]
@stm9x9 : Man könnte dann auch für Admins ein extra Listing anbieten, wo man nach Dezernat oder Anwalt filtern kann und dann mehrere Akten markieren kann, um sie dann einem anderen Anwalt und Dezernat zuzuordnen. Bei Umänderung des Aktenzeichens. Und ein Ettikett setzen "neuer Anwalt", damit man gleich bei diesen Akten eine Änderungsmitteilung zb ans Gericht schickt.

**Comment by j-dimension** [comment]
@RA-crm wünscht sich eigenen Aktenkreis pro Dezernat: https://github.com/jlawyerorg/j-lawyer-org/issues/241

**Comment by j-dimension** [comment]
plus: Kürzel des Nutzers als Schemabestandteil unterstützen

**Comment by j-dimension** [comment]
> Im Aktenzeichenschema muss es zusätzliche "Platzhalter" für das Dezernat geben, an beliebiger Stelle im Aktenzeichen.

Das ist leider sehr aufwändig. Mögliche Lösung: zweites Attribut "AZ-Erweiterung" und dann Berechnung des AZ zur Laufzeit. Erweiterung könnten 

- feste Bestandteile sein (vom Nutzer angegeben)
- Nutzerkürzel
- Guppenkürzel

Die Erweiterung würde dann aber immer am Ende des AZ stehen.

**Comment by RA-crm** [comment]
Ich könnte mit einer solchen Lösung gut leben.

meine Aktenzeichen bestehen ggw aus einer reinen fortlaufenden
Nummerierung und einem freigewählten Zusatz, damit mehr, als nur eine
Ziffernfolge da steht.

Wenn die Lösung zukünftig als aussieht

113/20-RA Mü-III für
Akte 113 aus 2020 - Rechtsanwalt Müller - Gruppe III

stell ich mir etwa:

00113-RA Mü (bei normalen Akten)
00114-RA Mü-KOrg (für Kanzleiorganisationsakten)
00115-RA Mü-Pers (für Personalakten) etc.
vor.

Beste Grüße
Christoph


Am 13.04.20 um 00:22 schrieb Jens Kutschke:

**Comment by j-dimension** [comment]
dokumentieren:
- setrefno setzt nur Basis-AZ

testen:
- setrefno
