### ISSUE TITLE
PDF-Formulare als Vorlage nutzen

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-org#37]
Habe mir die PDF-Formulare der Zwangsvollstreckung in den Vorlagenordner gelegt. Wenn man aber PDF-Formulare dann mit dem Adobe DC Reader öffnet und bearbeitet aus Dokumente heraus, Kann man die Datei nicht direkt in Dokumente von J-lawyer speichern, sondern muss sie erst auf der Festplatte des PC ablegen und importieren.... Abspeichern wie ein Dokument direkt in J-lawyer wäre sinnvoller

---------- @j-dimension 2024-10-10 ------------------

- Unterstützung für die Verwendung von PDF-Dateien mit Formularen als Vorlage
- Platzhalter können wie folgt in ein PDF eingebracht werden: (a) als Wert eines Formularfeldes (b) als Name eines Formularfeldes
- unterstützt werden alle Textfelder, keine booleschen Felder (bspw. ankreuzbare Checkboxen)
- Scripte werden nicht unterstützt
- Platzhalter aus Falldatenblättern werden unterstützt

**Comment by an-mus** [comment]
Ich mache das mittlerweile wie folgt: ich zerlege die PDF Formulare in einzelne Seiten. Dann in Libreoffice die unter 'Einfügen -> Bild' die Seiten einzeln in ein .odt Dokument einfügen und vergrößern. Darüber kann man dann über 'Einfügen -> Textfeld' eigene Textfelder legen, die dann die jeweiligen j-lawyer Platzhalter enthalten.
Das löst streng genommen nicht das technische Problem in diesem issue, ist aber vielleicht die weitergehende Lösung. Es ist zwar etwas mehr Arbeit, die einzelnen Formulare in .odt Dateien umzuwandeln und die Bearbeitung ist nicht so komfortabel wie in einem PDF Reader, die automatische Datenübernahme ist aber einfach super.
Ich nutze das bei PKH Formularen, um alle Daten, die ich in j-lawyer gespeichert habe zu übernehmen. Den Rest fülle ich eh nach dem ausdrucken per Hand aus.
Leider dürfen zumindest die PKH Formulare nicht einfach so weiter veröffentlicht werden (https://justiz.de/rechtliche_hinweise/index.php). Vielleicht bekommt man ja von denen einfach eine Genehmigung... 
@j-dimension: falls du bei denen mal nachfrage willst schicke ich dir gerne mal ein PKH-Formular Bastelmuster.
Wenn die das nicht genehmigen könnte man aber zumindest eine Anleitung in die Dokumentation stellen.

**Comment by an-mus** [comment]
Noch besser klappt es übrigens, wenn man das PDF in Libreoffice als Wasserzeichen einfügt (Format -> Seite -> Hintergrund -> Bild) und die Textfelder anschließend vor dem verschieben schützt (Rechtsklick auf das Feld -> Position und Größe -> Schützen Position

**Comment by j-dimension** [comment]
@an-mus , könntest Du mir die von Dir angesprochene PKH-Vorlage senden? Ich werde das nicht veröffentlichen, möchte es mir nur mal anschauen. 

Besten Dank!

**Comment by Mucki526** [comment]
Das funktioniert mit dem Wasserzeichen, aber wirklich sinnvoll wird das, wenn auch die Gebührentatbestände automatisch aus der RVG-Berechnung eingetragen würden. Richtig "scharf" ist das Formular dann nicht, aber "who cares"... Es geistern da sowieso von Bundesland zu Bundesland modifizierte Formulare herum, mehr oder weniger fehlerbehaftet. Wir benutzen das NRW - Formular, weil das Formular von der Justiz B-W Seite HKR 168 keine IBAN drin hat, sondern immer noch Kontonummer und Bankleitzahl.....

**Comment by j-dimension** [comment]
Siehe auch Email von @an-mus vom 06.05.

**Comment by an-mus** [comment]
Auch eine Möglichkeit wäre, den Formularserver der NRW Justiz zu nutzen: https://www.fms.nrw.de/justiz/form/display.do?%24context=EF97413A2E14201A223D
Da kann man die Formulardaten per xml importieren und bekommt ein ausgefülltes Formular als PDF. Es wäre prinzipiell möglich, dem RVG-Plugin beizubrigen, so eine xml Datei zu erzeugen. Wäre aber einiges Arbeit und gebastel. Änderungen, die die NRW Justiz an den Formularen macht müsste man einpflegen.

**Comment by j-dimension** [comment]
@an-mus ich schaue mir das mal an - danke!

**Comment by stm9x9** [comment]
> Leider dürfen zumindest die PKH Formulare nicht einfach so weiter veröffentlicht werden (https://justiz.de/rechtliche_hinweise/index.php).

Ich bezweifle eher, daß die amtlichen Formulare dem Urheberrecht unterliegen. Und auch daß das damit auf dieser allgemeinen Seite gemeint ist.

**Comment by j-dimension** [comment]
Füllen bspw. mit

​http://www.adobe.com/devnet/acrobat/fdftoolkit.html []
​http://pdfbox.apache.org/index.html []

​http://www.bmj.de/DE/Service/Formulare/_node.html []
