### ISSUE TITLE
Dokumentation: AKTE_BEZEICHNUNG

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#372]
Der Platzhalter heißt jetzt wohl AKTE_KURZRUBRUM steht aber in der (html) Dokumentation noch mit AKTE_BEZEICHNUNG.

Jedenfalls löst AKTE_BEZEICHNUNG nicht mehr auf.

**Comment by j-dimension** [comment]
Korrigiert.
