### ISSUE TITLE
Datei umbenennen ohne Dateiendung

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#373]
![image](https://user-images.githubusercontent.com/29924198/65808217-3957ac80-e193-11e9-831a-da317eae8631.png)

Da beim Umbenennen ja der Dateityp nicht verändert wird, scheint es mir fehlerresistenter, hier gar nicht den .xxx Teil hinten anzuzeigen und veränderbar zu machen.

**Comment by j-dimension** [comment]
Die Endung wird angezeigt, ja. Wenn man sie allerdings entfernt, wird das erkannt und entsprechend behandelt. Man hat beim Umbenennen keine Möglichkeit, die Endung zu entfernen oder zu ändern. 

Oder habe ich ein Szenario übersehen?

**Comment by stm9x9** [comment]
Das ist mir noch gar nicht aufgefallen. Persönlich fände ich es dann aber besser, nur anzuzeigen im Umbenennen-Dialog, was auch umbenennbar ist.

Wenn - wie ich es nach längerer Rücksprache mit Verantwortlichen für XJustiz für sehr sinnvoll halte - in Zukunft der Anzeigename (der dann ja keine Dateiendung hat) mehr im Vordergrund steht, dann ist das aber auch egal.

**Comment by Dickmaulruessler** [comment]
#1733
