### ISSUE TITLE
beA: Anhang-Import-Fenster vergrößern

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#376]
![image](https://user-images.githubusercontent.com/29924198/65840332-14d90d00-e318-11e9-8ef8-7d15061bd214.png)

Das Fenster ist ein wenig klein und gibt wenig Übersicht über die eigene Dateistruktur. Wäre schön, wenn man das Fenster vergrößern könnte. Idealerweise auch bildschirmfüllend per Doppelklick auf die Fensterleiste.

**Comment by j-dimension** [comment]
Der Dialog ist ein "Standarddialog" an den ich programmatisch nicht rankomme. :-(

**Comment by stm9x9** [comment]
:-(
Da gibt es keine alternativen Dateidialoge oder so? Das ist nämlich wirklich äußerst mickrig und schwer nutzbar.

**Comment by j-dimension** [comment]
Ich könnte entweder selber einen bauen oder auf eine andere UI-Bibliothek setzen. Alternativ vielleicht einfach an der Stelle Drag & Drop ermöglichen?

**Comment by stm9x9** [comment]
da das eines der Hauptkritikpunkte an webBea ist, daß man immer übers deren Dateibrowser navigieren muß, wäre drag&drop wohl das beste! Ein Auswahlfenster wäre hingegen noch hilfreich, das die Dateien der Akte anzeigt, falls man noch eines nachher hinzufügen will.
