### ISSUE TITLE
[bea] Etiketten?

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#377]
Sind die Etiketten aus der beA-Weboberfläche eigentlich per API abrufbar? Wenn ja, wäre das Darstellen und Bearbeiten in j-l hilfreich.

**Comment by j-dimension** [comment]
Ich meine das mal in der API der BRAK gesehen zu haben, ja.

**Comment by j-dimension** [comment]
Nach wie vor nicht Teil der API.
