### ISSUE TITLE
beA: Massenverschieben

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#378]
Man kann in einem beA-Ordner mehrere Nachrichten markieren.

Es wäre schön, wenn man diese dann auch gesammelt per drag&drop in einen anderen Ordner verschieben könnte.

**Comment by j-dimension** [comment]
Das funktioniert in der Tat schon. Bitte ggf. nochmal genauer spezifizieren / nachfragen.

**Comment by stm9x9** [comment]
> Das funktioniert in der Tat schon. Bitte ggf. nochmal genauer spezifizieren / nachfragen.

hm. bei mir nicht.

Ich klicke eine Nachricht an. Dann mit strg eine weitere. Zwei sind markiert. Wenn ich jetzt diese beiden per drag&drop nehmen will, dann ist nur noch eine von beiden markiert und ich kann nur eine verschieben.

**Comment by j-dimension** [comment]
Ja, das Markierverhalten ist nicht ideal. 

Du kannst eine Nachricht markieren. Dann mit Strg oder Shift zusätzliche Nachrichten. Taste gedrückt halten  und direkt den Drag & Drop-Vorgang starten.

**Comment by stm9x9** [comment]
Das tut mir jetzt mehr weh als Dir :-D Ne!

Konkret: es geht tatsächlich bei Shift, also wenn ich von bis markieren will. Da verändert sich dann der Cursor und ich kann ziehen. Bei strg geht es bei mir (Win7) nicht.
