### ISSUE TITLE
beA: importierte Nachrichten verschieben oder markieren

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#379]
Gibt es aktuell eine Möglichkeit zu erkennen, daß man eine Nachricht bereits importiert hat? 

Wenn nein: 

a) automatisch oder auswählbar in einen anderen Unterordner verschieben (zb j-l bearbeitet)
b) Etikett "exportiert" setzen

**Comment by j-dimension** [comment]
Erstmal mit Verschieben in Unterordner behelfen. Werde ich mit 1.10 nicht mehr liefern.

**Comment by j-dimension** [comment]
Die Etiketten sind über die Schnittstelle weder abfrag- noch manipulierbar. Es verleibt die Möglichkeit, die Nachrichten in einen Unterordner zu schieben.

**Comment by j-dimension** [comment]
Bei Verbindungsaufbau wird ggf. ein neuer Standardordner "in Akte importiert" mit j-lawyer.org-Logo erstellt. Bea-Inbox hat ein neue Option (rechts neben den Tagging-Schaltern) "in importiert verschieben"

**Comment by stm9x9** [comment]
> Die Etiketten sind über die Schnittstelle weder abfrag- noch manipulierbar. 

your are kidding!?

**Comment by j-dimension** [comment]
Not kidding at all, my friend. :-(
