### ISSUE TITLE
Timeline Refresh

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-org#382]
Timeline macht beim Aufruf keinen automatischen Refresh.

**Comment by j-dimension** [comment]
Knopf oben links nutzen?

**Comment by Mucki526** [comment]
Natürlich kann ich den Knopf oben links nutzen (den sehe ich als Notlösung, wenns nicht anders geht) - aber warum kann die Abfrage bei Öffnen nicht automatisch erfolgen. Die Sache mit dem Knopf ist die "Linux-typische-Denke", gibt´s ja auch bei manchem Editor, dass man manuell einen Refresh machen muss für die aktuelle Ansicht, empfand ich immer als sinnfrei. Die aus der "Klicki-Bunti-Fraktion" (Windows) stehen in sinnvollem Rahmen auf Automatismen :-), Warum muss ich mich beim Öffnen eines Fensters manuell um einen Refresh kümmern müssen? Ich habe beim Blick in die Timeline andere Sorgen. Ich meine, beim Scanfenster wird beim Öffnen ja auch automatisch ein Refresh gemacht, obwohl es den Button gibt, den man eigentlich nur dann braucht, wenn man bei offenem Scanfenster von außen eine Datei in den Ordner reinkopiert. Aber selbst da erscheinen in anderen Programmen dann die Dateien im Verzeichnis automatisch.

**Comment by j-dimension** [comment]
Beim Scaneingang ist der Knopf "statuslos". Er hat einfach zu aktualisieren. 

Bei der Timeline gibt es Eingangsparameter: die selektierte Zeitauswahl. Beim Laden der Ansicht weiss ich nicht, ob der Anwender bereits ein Suchergebnis hatte, dann mal eben in eine Akte gesprungen ist um etwas zu schauen, und dann zur Timeline zurückkehrt um weiterzusuchen. Hat er dann bereits innerhalb der Ergebnisliste an eine bestimmte Position gescrollt, möchte ich diese Ansicht dem Anwender nicht durch ein automatisches Neuladen kaputt machen.

**Comment by Mucki526** [comment]
Verstehe das Problem (oder denke ich verstehe es :-)). Ist es nicht unterscheidbar ob ich aus der Auswahl (z.B. Klick auf Aktenzeichen aus der Timeline heraus in die Akte springe) oder von anderer Stelle dorthin gelange und wieder zurück. Oder ist es einfach die Idee, dass derjenige, der sucht, egal wie er wieder in die Timeline / Historie einsteigt, zur letzten Suche zurückkommt . Man könnte es vielleicht dann so unterscheiden: Wer über den Button Historie oder Timeline links einsteigt, bekommt eine aktuelle Ansicht, also den automatischen Refresh, wer aus der Suche in der Historie einsteigt und dorthin zurück will nimmt den Zurückbutton der Aktenansicht (wie bei nem Browser den Zurückbutton)? Oder denke ich da jetzt zu kompliziert?

**Comment by j-dimension** [comment]
Ich erlaube mir das Ticket zu schliessen. Im Vergleich zur Menge der anderen Tickets und deren "Mehrwert" werde ich voraussichtlich nie zur Arbeit an diesem Ticket kommen.
