### ISSUE TITLE
beA: eEB - Anzeige in der gesendeten Nachricht

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#384]
![image](https://user-images.githubusercontent.com/29924198/65878901-653f8180-e38f-11e9-9462-7169fae35ec3.png)

a) In der gesendeten Nachricht sollte die Möglichkeit zur eEB-Abgabe nicht gegeben werden. Das sollte nur der Empfänger können.

b) Die (html-)Darstellung des eEB sollte nicht den Zustellungsempfänger anzeigen. 1) weil der ja noch kein eEB abgegeben hat und b) ja auch ein anderer berechtigter Anwalt das wird abgegeben können

Zum Vergleich wie es in beA-Web aussieht:

... äh Mist, das sieht da genauso murks aus.

Dann bitte wenigstens das "Das Empfangsbekenntnis wird nicht abgegeben, da" in Rot wie im Web.

Und - falls das zulässig ist - vielleicht oben in der Überschrift ein "Entwurf" oder "Vorlage" hinterfügen?

**Comment by j-dimension** [comment]
> a) In der gesendeten Nachricht sollte die Möglichkeit zur eEB-Abgabe nicht gegeben werden. Das sollte nur der Empfänger können.

Wie wurde die Nachricht geöffnet - aus einer Akte heraus oder über den Gesendet-Ordner des beA-Posteingangs?

**Comment by j-dimension** [comment]
> b) Die (html-)Darstellung des eEB sollte nicht den Zustellungsempfänger anzeigen. 1) weil der ja noch kein eEB abgegeben hat und b) ja auch ein anderer berechtigter Anwalt das wird abgegeben können
> 
> Zum Vergleich wie es in beA-Web aussieht:
> 
> ... äh Mist, das sieht da genauso murks aus.
> 
> Dann bitte wenigstens das "Das Empfangsbekenntnis wird nicht abgegeben, da" in Rot wie im Web.
> 
> Und - falls das zulässig ist - vielleicht oben in der Überschrift ein "Entwurf" oder "Vorlage" hinterfügen?

Ich verwende die offiziellen Stylesheets für die Darstellung und möchte die eigentlich nicht anfassen. Schaue mir das im Rahmen der 1.11 aber nochmal an, insbesondere bzgl. der Ausgabe "Das Empfangsbekenntnis wird nicht abgegeben, da"

**Comment by stm9x9** [comment]
> > a) In der gesendeten Nachricht sollte die Möglichkeit zur eEB-Abgabe nicht gegeben werden. Das sollte nur der Empfänger können.
> 
> Wie wurde die Nachricht geöffnet - aus einer Akte heraus oder über den Gesendet-Ordner des beA-Posteingangs?

beA-Posteingang

**Comment by j-dimension** [comment]
> 
> 
> > > a) In der gesendeten Nachricht sollte die Möglichkeit zur eEB-Abgabe nicht gegeben werden. Das sollte nur der Empfänger können.
> > 
> > 
> > Wie wurde die Nachricht geöffnet - aus einer Akte heraus oder über den Gesendet-Ordner des beA-Posteingangs?
> 
> beA-Posteingang

Aber über den Gesendet-Ordner?

**Comment by stm9x9** [comment]
äh, ja klar. beA-Gesendet-Ordner. Ging ja an einen anderen Anwalt.

**Comment by j-dimension** [comment]
@stm9x9 es gibt hier ganz interessante Konstellationen. 

Bsp.:
- ich bin angemeldet und sehe mehrere Postfächer: A, B und C
- für eine Nachricht von A an jemanden sollte ich in der Regel kein eEB abgeben können - ich bin ja der Versender.
- was ist aber mit Nachrichten von A an C - hier könnte ich ein eEB im Namen von C an A zurücksenden.

**Comment by stm9x9** [comment]
> * was ist aber mit Nachrichten von A an C - hier könnte ich ein eEB im Namen von C an A zurücksenden.

warum sollten sich zwei Anwälte, die beide so eng verbunden sind, daß ich als dritter Anwalt in deren beide beAs darf, gegenseitig was per EB schicken? Oder versteh ich das Szenario nicht?

**Comment by j-dimension** [comment]
Ich weiss dass das ein eher unwahrscheinliches Szenario ist, aber es ist technisch möglich das so aufzusetzen :-)

**Comment by stm9x9** [comment]
Und ist das dann ein Problem?

Ich habe Zugriff auf das Konto eines Kollegen (also ganz ordnungsgemäß mit Tokenfreigabe) und kann ihm gerne mal von mir was gegen EB schicken und das dann selber in seinem Konto das EB abgeben. Alles in bea-Web, falls Dich da irgendwie interessiert, wie sich web-beA da verhält?

**Comment by j-dimension** [comment]
Steck da keinen Aufwand rein.
