### ISSUE TITLE
beA: Dokumententyp codieren

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#385]
in der xml für die Anhänge, kommt da wirklich Freitext rein?

```
<tns:datei>
<tns:dateiname>para.jpg</tns:dateiname>
<tns:dateiformat listURI="urn:xoev-de:xdomea:codeliste:dateiformat" listVersionID="2.0">
<code>PDF</code>
</tns:dateiformat>
```

In meinen web-erzeugten xmls seht da immer eine dreistellige Codezahl statt wie hier PDF

**Comment by stm9x9** [comment]
so hier für pdf zb

```
<tns:datei>
<tns:dateiname>Paragraph.pdf</tns:dateiname>
<tns:dateiformat listURI="urn:xoev-de:xdomea:codeliste:dateiformat" listVersionID="">
<code>018</code>
</tns:dateiformat>
```

**Comment by j-dimension** [comment]
Stichwort xdomea-Datentypen. Ich schaue heute abend.

**Comment by j-dimension** [comment]
Am 22.08. stellte die BRAK Beispielstrukturdatensätze in XJustiz 2.4 zur Verfügung. Dort war die Struktur / Wertbelegung wie aktuell umgesetzt und wurde von mir eingearbeitet.

Am 29.08. schickte die BRAK eine Korrektur der eben jene Dokumenttypen betraf, den ich noch nicht eingearbeitet habe / hatte...

**Comment by stm9x9** [comment]
Einmal mit Profis ... m(
