### ISSUE TITLE
beA: eEB geht an den falschen

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#387]
A sendet an B eine Nachricht mit eEB-Anforderung.

B sendet eEB. Dabei geht das an B statt an A.

Das heißt in gesendet findet sich eine neue Nachricht B an B und es kommt zudem die Nachricht nochmal in den Posteingang. A bekommt nichts.

**Comment by j-dimension** [comment]
?!

**Comment by stm9x9** [comment]
Na, das eEB geht an den falschen, nämlich den eEB-Sendenden zurück statt an den, der die Ursprungsnachricht mit der eEB-Anforderung geschickt hat.

**Comment by j-dimension** [comment]
Hab ich schon verstanden, nur erscheint mir der Fehler so gravierend, dass ich mich frage was hier schiefgelaufen ist... Ich hatte das ja auch getestet...

Schaue mir das nochmal an.

**Comment by j-dimension** [comment]
Ich krieg das Ding nie fertig... :-(
