### ISSUE TITLE
Vorlagen  für Schriftsätze

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-org#388]
Ich bin gerade dabei, für Schriftsätze (Klagen) als Vorlagen zu entwickeln (Z.B. Ehescheidung - Antragsteller Mann, Eheleute haben minderjährige Kinder etc.). Das klappt ganz gut. Aber ich habe ein Problem. Ich kann bei den Beteiligten ja unterscheiden zwischen Mandant, Gegner und Dritter. Wenn ich nun das zuständige Gericht erfasse, dann als "Dritter". Und den Anwalt der Gegenseite ist dann auch ein "Dritter" oder "Gegner". Ich kann zwar auswählen, wer der Dritte für die Vorlage sein soll, aber dann habe ich als Anschrift z.B. das Gericht und auch als gegnerischer Anwalt die Adresse des Gerichts.  Das gleiche Problem, wenn ich im Rubrum den Gegner und dessen Anwalt jeweils als Gegner bezeichnet habe.
Man bräuchte evt. für sowas noch den Beteiligten "Prozessgericht" oder / und "Gegnerischer Anwalt".

**Comment by j-dimension** [comment]
Ja, das ist über die #117 bereits eingeplant :-)
