### ISSUE TITLE
beA: Adressen übernehmen mit SAFE-ID

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#393]
Wenn ein bislang unbekannter Kollege (oder Gericht oder Behörde) mir via beA schreibt, dann habe ich die SAFE-ID. Es wird mir in der Nachricht auch gleich angeboten den Absender ins Adressbuch zu übernehmen.

Da landen aber erstmal nur der Displayname und die SAFE-ID.
Aber ich kann ja mit dem Button "i" die Infos aus dem beA/SAFE-ID-Verzeichnis holen. Praktisch wäre es, wenn man diese gleich mit einem Knopfdruck ins Adressbuch übernehmen könnte:

![image](https://user-images.githubusercontent.com/29924198/66009543-2870a900-e4bb-11e9-83bd-8106039bfaca.png)

**Comment by j-dimension** [comment]
Es wird nun alles aus dem beA auf Knopfdrück übernommen.
