### ISSUE TITLE
bea: aus dem Papierkorb wiederherstellen

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#396]
Offenbar geht Verschieben aus dem Papierkorb nicht so einfach wie in beA-web:

![image](https://user-images.githubusercontent.com/29924198/66171243-bf6a6c00-e647-11e9-9789-651d614c432c.png)

**Comment by j-dimension** [comment]
Interessant. Da scheint es eine eigene Schnittstellenfunktion für zu geben. 

Ich weiß nicht warum, aber dann baue ich das ein.

**Comment by j-dimension** [comment]
Die API sagt einem nicht, in welchen Ordner restored wurde.
