### ISSUE TITLE
beA: Papierkorb - Spalte für "endgültig gelöscht"

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#397]
Im Papierkorb wäre es hilfreich wie in beA-web das Datum zu sehen, wann eine Nachricht endgültig gelöscht wird:

![image](https://user-images.githubusercontent.com/29924198/66171284-ef197400-e647-11e9-80a7-aedb18399a82.png)

**Comment by j-dimension** [comment]
Ich schaue mal ob die Schnittstelle dieses Attribut liefert.

**Comment by j-dimension** [comment]
Attribut vorhanden als "permanent deletion"
