### ISSUE TITLE
rechtsschutzversicherung als "Beteiligten"

### ISSUE THREAD

**Issue by Maz111111** [jlawyerorg/j-lawyer-org#398]
Es wäre gut, wenn man in der Akte die RSV auch von Hand (mit Anschrift und allem Drumherum) erfassen könnte und es auch die entsprechenden Platzhalter dafür gäbe, wenn man drebis nicht nutzen kann oder will.
Einige RSV sind nicht bei drebis dann würde ich gern mit einer Vorlage arbeiten können. Dazu muss die RSV irgendwo in der Akte mit Adresse angegeben werden können und aber auch einen Platzhalter für Adresse und Versicherungsnummer und Schadensnummer erhalten.
Bis auf die Anschrift wird das ja ohnehin schon erfasst. Es müssten eben noch Platzhalter für Vorlagen geschaffen werden.

**Comment by j-dimension** [comment]
Du könntest die Versicherung als Dritte führen und die vorhandenen Platzhalter verwenden. Für Versicherungsnr. / Schadennr. könnte man die "Eigenen" Felder in den Details der Beteiligten verwenden. 

So könntest Du Dir zumindest mit dem jetzt verfügbaren Stand helfen.

**Comment by Maz111111** [comment]
Stimmt! Danke!

**Comment by stm9x9** [comment]
Was mir bei der Lösung mit Dritten nicht so gefällt, daß man damit keine Lager-Zugehörigkeit abbilden kann. RSVs oder Anwälte oder gesetzliche Vertreter etc sind in meinem anwaltlichen Verständnis keine Dritten:

![image](https://user-images.githubusercontent.com/29924198/66246369-01f97a80-e714-11e9-9755-16e50558476d.png)

**Comment by stm9x9** [comment]
Was mir bei der Lösung mit Dritten nicht so gefällt, daß man damit keine Lager-Zugehörigkeit abbilden kann. RSVs oder Anwälte oder gesetzliche Vertreter etc sind in meinem anwaltlichen Verständnis keine Dritten:

![image](https://user-images.githubusercontent.com/29924198/66246423-2a817480-e714-11e9-8529-b65a4aca6fdf.png)

**Comment by Maz111111** [comment]
Das sehe ich ähnlich. 
Aber da muss Jens vielleicht mal seine Beweggründe nennen.
Soweit ich das sehe, war das in früheren Versionen zumindest für das Gericht mal anders. (glaube ich irgendwo gelesen zu haben) Da gab es eine eigene Beteiligtenkategorie für das Gericht.

Insbesondere wenn man mit Platzhaltern und Vorlagen arbeiten möchte, lässt sich mit dem aktuellen Bestand kein voll automatisiertes Klagerubrum erstellen, bei dem der GG anwaltlich vertreten ist. 
Gericht und Gegenanwalt sind beide als Dritte erfasst und es gibt aber jeweils nur einen Platzhalter für die Kategorie Dritte. Also wird entweder das Gericht automatisch eingetragen oder der Gegenanwalt.
