### ISSUE TITLE
Intelligente Eingabefelder

### ISSUE THREAD

**Issue by Maz111111** [jlawyerorg/j-lawyer-org#399]
Es wäre toll, wenn man beim Eingeben z.B. nach den ersten drei Zeichen sofort Vorschläge erhält.
Z.B. bei der Beteiligtensuche könnten alle in Betracht kommenden Suchergebnisse nach der Eingabe von drei Zeichen angezeigt werden. Je mehr Zeichen man angibt, um so eingegrenzter sollten die Vorschläge sein und sobald nur noch einer in Betracht kommt, sollte diese Möglichkeit automatisch im Eingabefeld erscheinen und entweder mit Enter gewählt oder - falls man etwas neues anlegen will - überschrieben werden können.
Dies sollte eigentlich bei jedem Eingabefeld möglich sein. Auch in der Aktensuche oder der Beteiligtensuche beim Anlegen einer neuen Akte. Auch bei den Textbausteinen in der Beteiligtenerfassung.
Bei den Wiedervorlagegründen könnte man so ggf. auch die individuelle Liste erstellen, ohne das man das Menu aufrufen muss. Sobald man einen neuen Grund eingegeben hat, sollte der in die Liste übernommen werden und dann automatisch angezeigt werden.
Als Anwender ist man so ein Verhalten der Software aktuell von Google und Co und eigentlich in der gesamten Windowsoberfläche eben gewohnt und es würde den Workflow beschleunigen.
Ob das bei Linux und iOS auch so ist weiß ich nicht. Beim iPhone war es - glaube ich - so.

**Comment by j-dimension** [comment]
Ich habe jetzt via #1626 für verschiedene Eingabefelder - primär in Akte und Adresse - eine Auto-Vervollständigung hinzugefügt. Kannst man auch bereits in der Onlinedemo sehen.

Du nennst hier explizit noch weitere Fälle, insbesondere auch die Suchen. Da bin ich nicht ganz dabei. Die Vervollständigung ergibt primär dort Sinn, wo die "Quelle" klar ist und man den Beginn des Wertes tippt. Also bspw. einen Titel, Anrede etc. 

Bei der Suche ist es oftmal sinnvoll, irgendeinen Teil in der "Mitte" zu tippen. Bspw. 
/22 in der Aktenzeichensuche
ller wenn man nicht weiß ob man Müller oder Mueller erfasst hat
etc.
Und die Suchen haben sehr viele Felder als Eingangsdatum.

> Bei den Wiedervorlagegründen könnte man so ggf. auch die individuelle Liste erstellen, ohne das man das Menu aufrufen muss. Sobald man einen neuen Grund eingegeben hat, sollte der in die Liste übernommen werden und dann automatisch angezeigt werden.

Das passt hier thematisch nicht so richtig rein. Bitte ggf. ein separates Ticket machen. Das benötigt auch noch etwas mehr Definition. Das schlichte automatische Hinzufügen ist m.E. nicht zielführend. Dann hat man in kurzer Zeit Einträge wie "Telefonat Hr. Müller" und "Telefonat Fr. Meier" in der Liste, die sich nicht als allgemein sinnvolle Einträge qualifizieren.
Man könnte da aber versuchen einen "intelligenten" Ansatz zu finden.

**Comment by Maz111111** [comment]
Das mit den WV Gründen hat sich glaube ich erledigt. Da gibt es jetzt checkboxen, die es damals noch nicht gab.
