### ISSUE TITLE
Aktenunterordner - Vorlagen nach Sachgebiet

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#400]
Schonmal im Vorgriff auf die Ordner in einer Akte :-)

Hilfreich in meinem alten Programm ist es, daß ich je nach Sachgebiet beim Einrichten einer Akte eine Vorauswahl an Ordnern automatisch eingerichtet bekomme.

zb im Sozialrecht:

![image](https://user-images.githubusercontent.com/29924198/66245872-bee9d800-e710-11e9-8408-bcee03db2085.png)

**Comment by j-dimension** [comment]
Link zu #122

**Comment by Mucki526** [comment]
Kann ja durchaus mit Tags kombinierbar sein. Die eine Welt schließt die andere nicht aus....

**Comment by j-dimension** [comment]
Nun in #122 enthalten
