### ISSUE TITLE
Beteiligten-Beispiel aus der Praxis

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#401]
Nicht direkt ein Featurewunsch, Bug oder so. Einfach mal ein Beispiel, wie ein durchaus typisches Beteiligten-Tableau aussieht und was ich mir hoffe, auch zukünftig in j-l abbilden zu können:

![image](https://user-images.githubusercontent.com/29924198/66246446-674d6b80-e714-11e9-86e7-95eddffe9ee7.png)

**Comment by j-dimension** [comment]
Link zu #121

**Comment by j-dimension** [comment]
Das ist doch aber ziemlich das was man jetzt schon abbilden kann? Geht es nur um die Terminologie "Dritte" vs. "unparteiisch"?

**Comment by stm9x9** [comment]
Wie kann ich denn aktuell den Anwalt des Gegners einordnen? Gegner ist er ja nicht. (nehmen wir mal den durchaus nicht völlig aus der Luft gegriffenen Fall, ich verklage für meinen Mandanten seinen alten Anwalt. Dem wird in der Regel von seiner Haftpflicht ein spezialisierter Anwalt zur Seite gestellt. Dann stünde da unter Gegner zweimal ein Anwalt - ich kann also nichtmal sagen: naja der Anwalt wird der Anwalt sein und der Nicht-Anwalt der eigentliche Gegner)

Oder wie bilde ich den gesetzlichen Vertreter ab? Den brauch ich aber zb wegen Anschreiben oder Vollmachtserzeugung.

Übersehe ich da was bei j-l?

**Comment by j-dimension** [comment]
Wie würdest Du es denn in den Kategorien Mandant/Gegner/unparteiisch abbilden?

**Comment by stm9x9** [comment]
Letztlich braucht man IMHO ein Unterscheidung in Lager und Rolle.

**Comment by RA-crm** [comment]
stm9x9 hat Recht. Man muss den Beteiligten auf Aktenebene Rollen zuweisen.

Bei einer hinreichend genauen Rollenverteilung bekommt man schnell viele der typischen Kostellationen in den Griff. Hier ein Beispiel anhand einer  GmbH & Co KG:

Bei-Spiel GmbH & Co KG (Mandant oder Gegner oder Dritter)
diese vertreten durch die Bei-Spiel-Verwaltungs GmbH (gesetzlicher Vertreter 1)
diese vertreten durch den Geschäftsführer Martin Muster (gesetzlicher Vertreter 2)
Ansprechpartner: Herr Siegfried Richter (Kontaktperson 1)

Oder bei einem jugendlichen Mandanten

Johan Jung (Mandant)
Vertreten durch Johana und Jürgen Jung (gesetzliche Vertreter)

**Comment by j-dimension** [comment]
Gelöst in #117
