### ISSUE TITLE
beA: AZ Gegner, Empfänger Klarname, Speicherung des Sendeberichtes in der Akte, Speicherung der Sortierung

### ISSUE THREAD

**Issue by Maz111111** [jlawyerorg/j-lawyer-org#403]
Frage oder Verbesserung:

1 .Beim Versenden einer beA Nachricht kann ich das AZ des Empfängers nicht angeben.
Wie erfolgt die Zuordnung beim Empfänger? Zieht jL es automatisch aus der Akte? Habe ich etwas übersehen?
Das AZ muss irgendwie angegeben werden können, wenn es nicht automatisch aus der Akte gezogen wird (falls letzteres muss es im Versandfenster angezeigt und korrigiert werden können)

2 .Bei der Auswahl des Empfängers steht "Unbekannter beA-Teilnehmer (govello-xxxx...)"
Insofern muss ich mich darauf verlassen, dass ich bei der Auswahl den richtigen Empfänger angeklickt habe. Ein Doppelcheck ist nicht möglich. Nachrichten dürfen aber unter keinen Umständen beim falschen Empfänger landen.
Hier muss (ggf. zusätzlich) im Empfängerfeld der Klarname des Empfängers angezeigt werden.

3. Kann man den Sendebericht aus dem Export speichern? Soweit ich das sehe - nicht.
Ich verlinke mal:
[https://www.brak.de/zur-rechtspolitik/newsletter/bea-newsletter/2019/ausgabe-27-2019-v-882019/](url)
Die Files die hier als gerichts- und nachweisrelevant genannt werden, sollten automatisch in der Akte gespeichert werden, damit sie ausgedruckt werden können. Im Zweifel einfach das gesamte ZipFile speichern (so mache ich das aktuell bei wichtigen Sendungen).

4. Die Sortierung springt immer wieder auf "AZ Absender". Wenn man es schon nicht dauerhaft ändern kann, sollte das Datum des Versandes als Sortierung gewählt sein. Besser wäre natürlich, wenn die KSW die Wahl des Anwenders speichern würde.

**Comment by Maz111111** [comment]
Und noch etwas:
5 .Der Posteingang sollte an oberster Stelle stehen und nicht "gesendet"

**Comment by j-dimension** [comment]
Eine Bitte vorab: getrennt abarbeitbare Themen auch als separate Tickets machen. Ich bearbeite nicht alle Inhalte von "Sammeltickets" gleichzeitig, sodass ich dann immer manuell Tickets splitten muss. Danke!

**Comment by j-dimension** [comment]
> 5 .Der Posteingang sollte an oberster Stelle stehen und nicht "gesendet"

Die Struktur samt Sortierung entnehme ich 1:1 einem Schnittstellenservice der BRAK. Ich würde ungern manuell umsortieren. Mal sehen...

**Comment by j-dimension** [comment]
> 1 .Beim Versenden einer beA Nachricht kann ich das AZ des Empfängers nicht angeben.
> Wie erfolgt die Zuordnung beim Empfänger? Zieht jL es automatisch aus der Akte? Habe ich etwas übersehen?
> Das AZ muss irgendwie angegeben werden können, wenn es nicht automatisch aus der Akte gezogen wird (falls letzteres muss es im Versandfenster angezeigt und korrigiert werden können)

Bitte vor Erstellung von beA-Tickets die geplanten Inhalte der 1.11 anschauen: https://github.com/jlawyerorg/j-lawyer-org/milestone/7
Die 1.10 liefert keine "fertige" beA-Integration, es gibt noch eine ganze Reihe weiterer Erweiterungen. Die Aktenzeichenthematik gehört dazu.

**Comment by j-dimension** [comment]
> .Bei der Auswahl des Empfängers steht "Unbekannter beA-Teilnehmer (govello-xxxx...)"

Die govello-Adressen sind "keine vollwertigen" beA-Teilnehmer. Die Schnittstelle der BRAK liefert daher keine Informationen zu diesen Adressen. Siehe Diskussion an Ticket #352

**Comment by j-dimension** [comment]
>     1. Kann man den Sendebericht aus dem Export speichern? Soweit ich das sehe - nicht.

Die Schnittstelle der BRAK ermöglicht aktuell keine mit dem ZIP-Export vergleichbare Exportfunktionalität. Diese Funktionalität war ursprünglich für Mitte 2019 versprochen, ist aber noch nicht geliefert.

**Comment by j-dimension** [comment]
>     2\. Die Sortierung springt immer wieder auf "AZ Absender". Wenn man es schon nicht dauerhaft ändern kann, sollte das Datum des Versandes als Sortierung gewählt sein. Besser wäre natürlich, wenn die KSW die Wahl des Anwenders speichern würde.

Schaue ich mir an.

**Comment by Maz111111** [comment]
> Eine Bitte vorab: getrennt abarbeitbare Themen auch als separate Tickets machen. Ich bearbeite nicht alle Inhalte von "Sammeltickets" gleichzeitig, sodass ich dann immer manuell Tickets splitten muss. Danke!

Sorry... ich war voller Tatendrang und hab mir jetzt selbst ein Ei gelegt, weil ich nun auch nicht getrennt antworten kann....Mist! :)

> Die Struktur samt Sortierung entnehme ich 1:1 einem Schnittstellenservice der BRAK. Ich würde ungern manuell umsortieren. Mal sehen...

Ich kam nur drauf, weil es in der WebOberfläche des beA anders sortiert ist.

> Die govello-Adressen sind "keine vollwertigen" beA-Teilnehmer. Die Schnittstelle der BRAK liefert daher keine Informationen zu diesen Adressen. Siehe Diskussion an Ticket

Könnte man da im Zweifel nicht zusätzlich den selbstvergebenen Namen aus der eigenen Beteiligtenliste mit anzeigen? Btw es handelt sich hier um die Adresse meines Heimatgerichtes, die nicht angezeigt wird.

> Die Schnittstelle der BRAK ermöglicht aktuell keine mit dem ZIP-Export vergleichbare Exportfunktionalität. Diese Funktionalität war ursprünglich für Mitte 2019 versprochen, ist aber noch nicht geliefert.

Unschön...aber dann eben nicht zu ändern. Da das beA von selbst alte Nachrichten löscht und man ja nie weiß, wann man es braucht, bleibt wohl nichts anderes übrig, als - zumindest bei wichtigen, insbesondere fristgebundenen, Nachrichten - nach dem Versand von Hand den Export zu machen. Die Gerichte scheinen etwas anderes zum Nachweis ja nicht zu akzeptieren.

> 2\. Die Sortierung springt immer wieder auf "AZ Absender"...
Schaue ich mir an.

Dankeschön! Das geht so in eine Richtung, wie das Abspeichern der Fenstergröße. Nicht zwingend zum Arbeiten nötig, aber irgendwie wärs dann doch schöner...

**Comment by j-dimension** [comment]
> Könnte man da im Zweifel nicht zusätzlich den selbstvergebenen Namen aus der eigenen Beteiligtenliste mit anzeigen? Btw es handelt sich hier um die Adresse meines Heimatgerichtes, die nicht angezeigt wird.

Welches ist es genau?



> bleibt wohl nichts anderes übrig, als - zumindest bei wichtigen, insbesondere fristgebundenen, Nachrichten - nach dem Versand von Hand den Export zu machen.

oder sie wieder in einen anderen Ordner zu verschieben, bspw einen selbst angelegten Archivordner :-)  Das geht beliebig oft.

**Comment by Maz111111** [comment]
Es ist das Amtsgericht Halle (Saale)

Das mit dem Ordner verstehe ich nicht. Auf dem Schlauch steh...

**Comment by j-dimension** [comment]
Eine govello-Adresse ist eine, die vor dem 1.1.2016 erstellt wurde. Alle danach erstellten SafeIDs folgen dem Muster De.Justiz....   (https://egvp.justiz.de/Drittprodukte/SAFE_Abbildungsvorschrift_SAFE_ID_V2.pdf)
Für Govello kann ich im beA keine Kontaktinformationen abrufen. 
Der Wunsch nach Anzeige des Namens, wenn der Kontakt in der eigenen Datenbank erfasst ist, ist super. Werde ich so umsetzen.

Ordnerthematik: nach x Tagen werden Nachrichten im beA in den Papierkorb verschoben, nach weiteren y Tagen dann gelöscht. Verschiebt man eine Nachricht aus dem Papierkorb in einen anderen Ordner, so beginnt die Frist der x Tage erneut von vorn. Das kann man beliebig oft wiederholen.

**Comment by stm9x9** [comment]
> bleibt wohl nichts anderes übrig, als - zumindest bei wichtigen, insbesondere fristgebundenen, Nachrichten - nach dem Versand von Hand den Export zu machen

Gute Idee. Leider nicht umsetzbar.
https://www.heise.de/newsticker/meldung/Wieder-eine-beA-Panne-Archive-ohne-Signatur-4491965.html

> Für Govello kann ich im beA keine Kontaktinformationen abrufen.

für neuere (nicht-beA) Adressen aber schon? Ich dachte, aktuell gehen wirklich nur Anwälte als Namen an der Stelle?

hier geht es jedenfalls nicht: 

![image](https://user-images.githubusercontent.com/29924198/66348358-a66aff00-e956-11e9-983b-1d06d4065141.png)

Advoware schafft es bei demselben Gericht aber irgendwie:

![image](https://user-images.githubusercontent.com/29924198/66348381-b4208480-e956-11e9-85e7-db8596987d25.png)

**Comment by Maz111111** [comment]
> Gute Idee. Leider nicht umsetzbar.
https://www.heise.de/newsticker/meldung/Wieder-eine-beA-Panne-Archive-ohne-Signatur-4491965.html

Ok - das bedeutet aber in letzter Konsequenz, dass man fristgebundene Schriftsätze oder andere wichtige Sachen derzeit überhaupt nicht über das beA versenden DARF. Nicht sehr schön!

> `Ordnerthematik: nach x Tagen werden Nachrichten im beA in den Papierkorb verschoben, nach weiteren y Tagen dann gelöscht. Verschiebt man eine Nachricht aus dem Papierkorb in einen anderen Ordner, so beginnt die Frist der x Tage erneut von vorn. Das kann man beliebig oft wiederholen.

Bis die BRAK das merkt und diesem "Missbrauch" des BRAK-eigenen Speicherplatzes ein Ende bereitet :D
