### ISSUE TITLE
Abspeichern von Anlagen aus E-Mail oder Umbenennen erzeugt lange Dateinamen

### ISSUE THREAD

**Issue by nronk** [jlawyerorg/j-lawyer-org#404]
Moin.
Wenn ich versuche in der Dokumentenansicht eine Datei umzubenennen oder einen E-Mail Anhang abzuspeichern werden Dateinamen mit zusätzlichen Unterstrichen erzeugt.

Zum Beispiel: aus "Schriftsatz 153a.pdf" wird "S_c_h_r_i_f_t_s_a_t_z_ _1_5_3_a_._p_d_f"

Ich nutze den Linux Client und einen entfernten Linux Server.
Ich nehme nich an, dass es sich um ein Feature handelt.

Mit allerbesten Grüßen

**Comment by j-dimension** [comment]
@nronk es werden eigentlich nur in Dateinamen unzulässige Zeichen ersetzt. Der Fall oben ist definitiv kein Feature. Kann mir nur vorstellen dass da irgendwelche Steuerzeichen enthalten sind.

Ist das bei Dir bei allen Dokumenten so?

**Comment by nronk** [comment]
Mein erster Gedanke war auch, dass Sonder- bzw. Leerzeichen ersetzt werden sollten. Allerdings werden selbst vor und hinter Leerzeichen die Unterstriche eingefügt.

Es tritt auf, wenn ich Dateien aus E-Mails oder dem beA-Modul abspeichern will. Ferner wenn ein Dokument umbenannt werden soll. Es tritt nicht auf, wenn in der Akte ein neues Dokument erstellt wird oder eine Datei in der Akte über den "Hinzufügen" Dialog zur Akte genommen wird.

**Comment by j-dimension** [comment]
Fehler gefunden und korrigiert. Gern mal mit der neuen 1.10.0.13 probieren: https://www.j-lawyer.org/?p=3093

**Comment by nronk** [comment]
Sorry, aber ich hab es mit der 1.10.0.13 ausprobiert und der Fehler tritt weiter auf. Bei Umbenennung und Abspeichern aus E-Mails ausprobiert.
Tut mir leid.

**Comment by j-dimension** [comment]
Ich habe eben in kurzem Abstand zwei Uploads der 1.10.0.13 gemacht. Evtl. hast Du den ersten erwischt? Dort war die Korrektur noch nicht drin. 

Nochmal probieren?

**Comment by nronk** [comment]
Ja, das wird es gewesen sein. Jetzt funktionierts. Vielen Dank für die unglaubliche Arbeit! :-)
