### ISSUE TITLE
Anleitung / Hinweis für update für Benutzer von 2 j-lawyerboxen für Replikation

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-org#408]
Update auf 1.10.013 hat geklappt. BEA läuft. Aber was ich nicht in der Anleitung gefunden habe - Ich habe ja eine zweite Box als Replikation laufen. Wird die vollständig automatisch auf Vers. 1.8 gesetzt und das update geht munter weiter oder muss manuell eingegriffen werden (und wie...?).  Und -- vielen Dank für die ganze Arbeit und die tolle Software.

**Comment by j-dimension** [comment]
Hallo @Mucki526, Du solltest in der Dokumentation fündig werden:
https://www.j-lawyer.org/downloads/documentation/j-lawyer.org-UserGuide-de.html#__RefHeading___Toc3120_1951799897

> Hinweis: Bei Installation von Updates der j-lawyer.BOX Management Console oder der j-lawyer.org Kanzleisoftware, sind in jedem Fall beide Boxen zu aktualisieren!

Die Replikation transferiert ausschließlich Daten, keine Softwareinstallationen. D.h. nach dem Einspielen von Updates kurz auf die Management Console der zweiten Box und einmal aufs Knöpfchen drücken.
In diesem konkreten Fall sollte die zweite Box das Update der Kanzleisoftware auf Version 1.10 anbieten, dort kommt dann automatische auch die neueste Management Console in Version 1.9 mit.

Gern melden wenn es noch Fragen gibt :-)

**Comment by Mucki526** [comment]
Ja, ich kann die 2 Box anpingen, aber komme nicht drauf. Muss ich dazu evt. die alte Clientversion benutzen (nochmal installieren) oder soll ich einfach mal am Replikanten "den Stecker ziehen"?.

**Comment by Mucki526** [comment]
Zum Verständnis - ich habe bisher die Hauptbox aktualisiert und an den Rechnern den neuen Client 1.10.013 installiert und das Bea zum laufen gebracht... J

**Comment by j-dimension** [comment]
Ah, ich habe eine Ahnung was passiert sein könnte. Melde mich später dazu.

**Comment by j-dimension** [comment]
todo:

- Update Dokumentation
- Hinweise in Updateseite der j-lawyer.BOX Management Console

**Comment by j-dimension** [comment]
Website und Doku angepasst.

**Comment by j-dimension** [comment]
Neue j-lawyer.BOX Management Console ausgerollt.
