### ISSUE TITLE
BEA Papierkorb

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-org#409]
Löschen einer Datei im BEA Papierkorb funktioniert nicht. Man muss die Datei erst über die WEB-Oberfläche löschen, dann erscheint sie aber immer noch als Datei im J-lawyer, dann kann man aber den Eintrag weglöschen....

**Comment by j-dimension** [comment]
> Löschen einer Datei im BEA Papierkorb funktioniert nicht.

Was passiert genau - kommt eine Fehlermeldung?

**Comment by Mucki526** [comment]
Nein, aus dem J-lawyer heraus passiert garnichts wenn man eine Datei im Papierkorb auswählt und den Löschbutton drückt. Es wird nicht gelöscht. Wenn man dann in die Weboberfläche geht und löscht, dann kann man die Datei, die dort unverändert besteht, löschen, wobei vorher gefragt wird, ob man die Datei wirklich löschen will. Wenn man sie dann löscht und zurück ins j-lawyer-Bea geht, dann ist der Dateieintrag der gelöschten Datei dort weiter vorhanden (die Datei ist ja aber gerade von mir gelöscht worden) und wenn man jetzt den Eintrag auswählt und auf löschen klickt, dann verschwindet er.
