### ISSUE TITLE
Bea

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-org#410]
Haber gerade den ersten Schriftsatz ans Amtsgericht geschickt mit BEA. Das war nicht ganz einfach. Um die Adresse auszuwählen bietet das BEA an aus dem bestehendem Adressverzeichnis oder aus dem Gesamtverzeichnis die Adresse zu suchen. Aus dem bestehendem eigenen Adressverzeichnis geht nicht, weil dann die J-Lawyer-Adressen kommen, nicht die BEA-Adressen. Aus dem Gesamtverzeichnis geht, aber wenn man das auswählt kommt unbekannter Nutzer und dann wird man bei der Versendung aufgefordert nochmal aus dem unsortiertem Gesamtverzeichnis (nehme ich an, das Amtsgericht Konstanz rauszusuchen. Erst dann klappt das Versenden. Das ist noch nicht optimal.

**Comment by j-dimension** [comment]
Ich bringe etwas Licht ins Dunkel.

> Aus dem bestehendem eigenen Adressverzeichnis geht nicht, weil dann die J-Lawyer-Adressen kommen, nicht die BEA-Adressen.

Daher empfiehlt es sich, das Gericht als Adresse in der lokalen Datenbasis zu erfassen. Entweder über Adresse - Neu - dann dort ganz unten im beA-Verzeichnis suchen und die Daten übernehmen und als Adresse speichern. 
Oder: Über Menü Datei - Import alle Gerichte in einem Rutsch importieren. 

Vorteil: dann hast Du das Gericht samt SafeID in der Datenbank und musst nicht jedes mal die langsame beA-Suche bemühen.

> dann wird man bei der Versendung aufgefordert nochmal aus dem unsortiertem Gesamtverzeichnis (nehme ich an, das Amtsgericht Konstanz rauszusuchen

Das ist seit Anfang September so, mit dem Wechsel auf XJustiz 2.4 muss ein Instanzgericht angegeben werden, auch in der beA-Weboberfläche.

**Comment by Mucki526** [comment]
- Das erste habe ich verstanden, d.h. ich muss alle Gerichte aus der bisherigen j-lawyer-Datenbank rauswerfen die stören und durch BEA-Gerichte ersetzen. Na ja, ist nicht zuviel, ich muss es nur meiner Frau erklären (Herausforderung) :-).
- Das letztere in 2.4 ist doch wohl "Banane". Ich suche das Amtsgericht im Verzeichns mit der Suchfunktion und muss dann nochmal das Amtsgericht aus einer unsortierten Liste ohne Suchfunktion raussuchen? Welche "Logo"-Programmierer haben das zu verantworten...

**Comment by j-dimension** [comment]
>     * d.h. ich muss alle Gerichte aus der bisherigen j-lawyer-Datenbank rauswerfen die stören und durch BEA-Gerichte ersetzen

Oder nur die Safe-ID an die vorhandenen Gerichte dranpacken. 

>  nochmal das Amtsgericht aus einer unsortierten Liste ohne Suchfunktion raussuchen?

im j-lawyer gibt es zumindest die Suchfunktion. Und es wird aktuell das zuletzt genutzte Gericht vorausgewählt. Eine intelligentere Behandlung ist für die 1.11 geplant via Ticket #394


Aus meiner Sicht bleibt das hier für dieses Ticket nichts übrig, da die Inhalte bereits in anderen Tickets reflektiert sind. Ich schliesse es als Duplikat. Du kannst natürlich noch Rückfragen stellen, die auch beantwortet werden.
