### ISSUE TITLE
[bea] Nachricht exportieren über offizielle API der BRAK, sobald verfügbar

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-org#412]
Das BEA Sendejournal lässt sich nicht einsehen wenn man es anklickt....

**Comment by j-dimension** [comment]
Brauche mehr Informationen.

- Geht es um das Nachrichtenjournal oder die Laufzettel?
- Wo geht das nicht? In einer exportierten beA-Nachricht in der Akte? Im Gesendet-Ordner des beA?

**Comment by Mucki526** [comment]
Wenn ich im Dokumentenordner wo die BEA-Nachricht und Daten u.s.w. abgelegt werden auf den Reiter Journal gehe. Dann sieht man in meinem Fall 5 verschiedene Message Zeit, Message Daten, kann das aber nicht einsehen oder drucken. Strukturdatensatz unter Reiter Nachricht Anhänge lässt sich ansehen, aber nicht drucken oder speichern.... (wenn man es dann irgendwann mal bräuchte als Nachweis).

**Comment by Maz111111** [comment]
Soll man das öffnen können?
Wenn ja, muss ich auf #403 Bezug nehmen. Dort wollte ich ja den Sendebericht irgendwie einsehen / drucken / abspeichern können.
War das ein Missverständnis und der Bericht liegt im Journal und lässt sich - was ich vor meinem Beitrag versucht hatte - ungewollt einfach nur nicht öffnen?

**Comment by Mucki526** [comment]
Wenn man es nicht öffnen kann, was soll es dann wert sein? Ich denke das ist so ein Ding, was man irgendwann braucht morgen oder in 10 Jahren und dann kann man nicht drucken oder exportieren und versenden und hat Stress.

**Comment by j-dimension** [comment]
Ich schiebe das mal. Die BRAK hatte für "Mitte 2019" eine Exportfunktion für die Kanzleisoftwarehersteller angekündigt, die einen ZIP-Export identisch zur Weboberfläche umsetzen soll. 

Hoffe das es dieses Jahr noch kommt...

**Comment by j-dimension** [comment]
Duplikat von #1299
