### ISSUE TITLE
Speichern einer neuen Akte leert alle Eingabefelder

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-org#414]
Wenn ich aus der Beteiligtenseite einer Akte eine Adresse anlegen lande ich danach nicht wieder in der Beteiligtenseite der Akte, sondern muss wieder neu einsteigen. Wieder zurück daher woher ich komme wäre ökonomischer...

**Comment by Mucki526** [comment]
Ah, es passiert mir bei Neuanlage einer Akte. Ich lege sie an, lege den Beteiligten an, speichere sie und lande in neue Akte anlegen statt in der neu angelegten Akte. Das ist so gewollt?

**Comment by j-dimension** [comment]
Ich glaube Du machst es Dir zu kompliziert. Gehst Du denn zum Neuanlegen der Beteiligten in Addresse - Neu? Das muss man nicht - siehe meinen Kommentar oben. D.h. Du bleibst eigentlich immer in der Akte.

**Comment by Mucki526** [comment]
Meine Frau meint auch manchmal, dass ich zu kompliziert bin... aber hier eigentlich nicht: 1.)  ich gehe auf Akte neu, nenne sie z.B. Test. 2.) Dann soll Frau Test angelegt werden also gehe ich in der Akte auf Beteiligte und drücke dort + lege Frau test an, übernehme sie. 3.) Wen ich dann auf speichern gehe (Programm mecker, weil keine Widervorlage, trotzdem speicher - yes)..., lande ich in der Maske für eine neue Akte, aber nicht in der Akte, die ich gerade angelegt habe. Hat meine Frau recht, oder ich :-).

**Comment by j-dimension** [comment]
Verstehe :-)

Frage: warum speicherst Du denn, wenn Du eh noch in der Akte bleiben und etwas machen willst? Dann kannst Du doch auch später speichern, oder?

Das was Dir hier in die Quere kommt ist das "mehrere Akten in einem Rutsch anlegen". Wenn Du mehrere Akten anlegen willst - bspw. weil Du gerade vorbildlicherweise zu j-lawyer migriert bist - dann kannst Du Aktendaten (ein Minimum) eingeben, speichern --> Maske ist leer und Du kannst direkt die nächste Akte anlegen usw. usf. 

Optionen für Dich: 

- Speichern, wenn Du mit der Akte "fertig" bist
- statt explizitem Speichern einfach kurz auf den Dokumente-Reiter wechseln, dann findet ein Speichern statt und Du verbleibst innerhalb der Akte



> Hat meine Frau recht, oder ich

PS: Das Leben lehrt uns: Frauen haben in einer Beziehung zum Zwecke der Harmonieförderung immer recht. :-)

**Comment by Mucki526** [comment]
Danke! Wechsel auf Dokumentenreiter passt. Und natürlich hat meine Frau und haben meine Töchter immer recht.... Harmonie, Harmonie....

**Comment by stm9x9** [comment]
hm, bin hierher gelotst worden: so ganz dolle finde ich das nicht und der Workaround ist auch nur das, ein Workaround. Akten im Akkord anlegen sollte doch nicht so oft vorkommen, daß das das Standardverhalten von j-l dominieren sollte. Da kann man IMHO auch nach Speichern noch mal kurz auf Akte neu klicken ...

**Comment by stm9x9** [comment]
Mir ist es jedenfalls schon mehrfach passiert, daß ich die neue Akte speichere, dann ohne hinzugucken auf den Reiter Beteiligte gehe, dort die eintrage, wieder speichere und huch? Ich hab jetzt zwei neue Akten!

**Comment by j-dimension** [comment]
@stm9x9 dann mach das andere Ticket wieder auf.
