### ISSUE TITLE
BEA - Versendung fehlgeschlagen

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-org#417]
![grafik](https://user-images.githubusercontent.com/37142896/66494829-923f1300-eab8-11e9-8532-ab4e3af50d31.png)

Der Versuch eine Anlage ans Amtsgericht zu schicken (Adresse aus importiertem Verzeichnis) endete mit der vorgenannten Fehlermeldung.

**Comment by Mucki526** [comment]
Versendung klappt, wenn man die Gerichtsadresse nicht aus den importierten Daten nimmt sondern aus dem BEA-Gesamtverzeichnis.

**Comment by j-dimension** [comment]
Kannst Du bitte schauen ob die Safe ID aus der importierten Adresse mit der Safe ID aus der beA-Verzeichnissuche übereinstimmt?

Der Fehler oben kann genauso auch kommen, wenn das beA eine temporäre Störung hat. Unter Umständen hängt es also nicht daran woher man die Empfängerdaten bezieht.

**Comment by j-dimension** [comment]
Ich schliesse. Gern wieder öffenen wenn der Fehler noch auftritt.
