### ISSUE TITLE
Integration Foxit nach Anleitung

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-org#419]
Die Integration von Foxit für PDFs über j-lawyer hat funktioniert. Wenn ich aber ein PDF aufrufe kommt immer die Warnmeldung das foxit von j-lawyer ohne eine gültige Signatur geöffnet wurde. Man kann anklicken, Auswahl für diese Anwendung speichern, aber die Meldung kommt bei jeder Öffnung eines PDF´s wieder. Ist das ein j-lawyer Problem oder ein Windows Sicherheitsrichtlinienproblem (Windows 10 prof 1903)? Und wie bekomme ich das weg, ohne mein System mit einem Sicherheitsloch zu versehen.....

**Comment by j-dimension** [comment]
Kann ich so erstmal nicht reproduzieren. 

Kannst Du mal den Foxit über das Startmenü öffnen, dann in Foxit Datei - Einstellungen - Trust Manager und dort schauen ob der j-lawyer Client als vertrauenswürdige Anwendung gelistet ist?

**Comment by Mucki526** [comment]
Das war das Problem. Ich habe diese Einstellung nicht im mir unbekannten Foxit vermutet, sondern in den Sicherheitseinstellungen von Windows. Habe j-Lawyer als vertrauenswürdige app an der von Dir empfohlenen Stelle in Foxit aufgenommen. Jetzt gehts. Danke!
