### ISSUE TITLE
Sipgate: mehrere Faxe auf einmal bestätigen

### ISSUE THREAD

**Issue by j-dimension** [jlawyerorg/j-lawyer-org#425]

**Comment by fortrieb** [comment]
Hi,
ich wuerde mich gern an diesem Ticket versuchen. Dazu braeuchte ich noch etwas Hilfestellungen. In der [Anwenderdoku](http://www.j-lawyer.org/downloads/documentation/j-lawyer.org-UserGuide-de.html#__RefHeading__118_1146603382) gibt es leider nur einen Hinweis zu Sipgate. Dort aber keinen Erlaeuterung zur Aktivierung von Sipgate.
Nun zu meinen Fragen:

- Wie aktiviert man Sipgate in J-Lawyer?
- Wie generiere ich passende Testdaten fuer diesen Use-case?
- Welche Teile betrifft die mehrfache Bestaetigung von Faxen? Nur den j-lawyer-client, j-lawyer-fax oder auch j-lawyer-server?

Danke

**Comment by j-dimension** [comment]
Hallo @fortrieb ,

die Sipgate-Anbindung lässt sich über den Client in "Einstellungen" - "Voice over IP" aktivieren. In dem Dialog trägst Du Nutzername und Passwort ein und stellst die Integration auf "an". Mehr ist nicht notwendig.

Testdaten generieren geht leider nur über einen echten Account, über welchen man ein oder mehrere Faxe absetzt. in j-lawyer-fax gibt es zwar ein paar Unit Tests, aber nur solche die keine Kosten verursachen. Das Senden eines Faxes findest Du als Codebeispiel in 
https://github.com/jlawyerorg/j-lawyer-org/blob/master/j-lawyer-fax/src/com/jdimension/jlawyer/fax/FaxClient.java
Oder Du sendest über den Client direkt (Rechtsklick auf ein Dokument in einer Akte, dort kannst Du faxen). 

Die mehrfache Bestätigung würde tatsächlich nur den Client betreffen. Aktuell ist die "einzelne" Bestätigung zu finden in https://github.com/jlawyerorg/j-lawyer-org/blob/master/j-lawyer-client/src/com/jdimension/jlawyer/client/voip/FaxStatusPanel.java

```
    private void cmdSaveReportActionPerformed(java.awt.event.ActionEvent evt) {                                              
        ClientSettings settings = ClientSettings.getInstance();
        try {
            JLawyerServiceLocator locator = JLawyerServiceLocator.getInstance(settings.getLookupProperties());
            
            locator.lookupVoipServiceRemote().saveFaxReport(lblSession.getText());
            this.clearDetails();
        } catch (Exception ex) {
            log.error(ex);
            ThreadUtils.showErrorDialog(this, "Fehler beim Erstellen des Reports: " + ex.getMessage(), "Fehler");
        }
    }     
```

Dort wird die #saveFaxReport des Servers gerufen, und die ID des aktuell selektierten Faxes reingereicht. An dieser Stelle müsste über die selektieren Tabelleneinträge iteriert werden, und die #saveFaxReport mehrfach gerufen werden.

Gern melden wenn ich helfen kann.

**Comment by fortrieb** [comment]
Danke soweit fuer die Hinweise.

Noch zu den Testdaten: Die Faxe welche bestaetigt werden sollen, liegen doch sicher in der Datenbank. Laesst sich damit ein SQL-Insert absetzen, damit diese im Client angezeigt werden?
Vlt. sogar die Aufrufe an die Sipgate-API mocken?

**Comment by j-dimension** [comment]
> Laesst sich damit ein SQL-Insert absetzen, damit diese im Client angezeigt werden?

Das geht natürlich:

```
insert into communication_fax (sessionId, archiveFileKey, localUri, remoteUri, remoteName, pdfName, pdfQueueFile, sentDate, lastStatusDate, lastStatus, sentBy) values 
(LEFT(UUID(), 8), (SELECT id FROM cases LIMIT 1), '+4942', '+491337', 'Dr. Drosten', 'covid19-cure.pdf', 'dummy.pdf', '2020-05-06 13:37', '2020-05-06 13:39', 'sent', 'admin');
```

Das SQL kannst Du auch mehrfach ausführen und hast dann mehrere Einträge. 

Ein Bestätigen wäre dann auch möglich, da ist die Sipgate API gar nicht mehr involviert. Einen Mock habe ich dafür noch nicht geschrieben.

**Comment by j-dimension** [comment]
Obiges SQL-Statement setzt voraus dass mindestens eine Akte im System erfasst wurde.

**Comment by fortrieb** [comment]
Klasse, damit lassen sich Faxe generieren die angezeigt werden.

**Mein Idee:**
Die einfachste Loesung waere einen weiteren Knopf einzufuegen, in etwa `Alle Berichte generieren`.

Was fuer den Nutzer sicher hilfreiche waere, eine Multiselect ueber die Eintraege in der Tabelle. Dort dann eine Knopf mit 'Alle Auswaehlen' und die anderen Methoden entsprechen auf das Multiselect aktualisieren.

Nur scheint die verwendete Tabelle kein Multiselect zu unterstuetzen. Korrekt?

**Comment by fortrieb** [comment]
Ist der Code in [FaxStatusPanel](https://github.com/jlawyerorg/j-lawyer-org/blob/master/j-lawyer-client/src/com/jdimension/jlawyer/client/voip/FaxStatusPanel.java#L1140) von einem Generator erstellt worden? Dort sind einige Kommentare wie `` // Variables declaration - do not modify//GEN-BEGIN:variables``.

**Comment by j-dimension** [comment]
> Nur scheint die verwendete Tabelle kein Multiselect zu unterstuetzen. Korrekt?

In der jetzigen Umsetzung nicht. Dazu müsste man aber nur diese Zeile entfernen: 

`tblQueue.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);`

Besser gesagt: nicht per Hand entfernen, sondern im GUI-Builder diesen Wert auf seinen Standardwert zurücksetzen:

![grafik](https://user-images.githubusercontent.com/3729754/81217195-7bc05200-8fdc-11ea-94c2-05fa219aab7a.png)

**Comment by j-dimension** [comment]
> Ist der Code in [FaxStatusPanel](https://github.com/jlawyerorg/j-lawyer-org/blob/master/j-lawyer-client/src/com/jdimension/jlawyer/client/voip/FaxStatusPanel.java#L1140) von einem Generator erstellt worden?

Ja, am effizientesten wird es sein wenn Du Netbeans als IDE verwendest. Ich nutze den dort eingebauten GUI-Builder. Und für praktische alle Komponenten von j-lawyer.org gibt es Projektdateien, die Du direkt in Netbeans öffnen kannst und nichts von Hand konfigurieren musst.

**Comment by j-dimension** [comment]
Liste der Contributors erweitert: https://github.com/jlawyerorg/j-lawyer-org/edit/master/README.md
