### ISSUE TITLE
Bea-Status gelesen/ungelesen

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-org#428]
Ich habe die BEA Nachricht gelesen und gespeichert, sie wird aber im BEA-Fenster weiter als ungelesen angezeigt (fett).

**Comment by Mucki526** [comment]
Manuell kann man die Nachricht als gelesen markieren. Es wäre m.E. sinnvoller, wenn sie beim Öffnen automatisch als gelesen markiert wird und manuell nur auf "ungelesen" zurückgesetzt werden kann.

**Comment by Mucki526** [comment]
Wenn man nach einer Weile nochmals ins BEA schaut wird die Nachricht einfach wieder als ungelesen angezeigt, die man vorher manuell auf gelesen gesetzt hatte. Da stimmt was nicht.

**Comment by j-dimension** [comment]
Das beA wertet offensichtlich den Abruf einer Nachricht über die Schnittstelle nicht als Lesevorgang. Nur das Öffnen der Nachricht in der Weboberfläche setzt den "Gelesen"-Status. 

Mal schauen ob ich eine Notlösung drumherum basteln kann.

**Comment by j-dimension** [comment]
BRAK KSW-Support angefragt.

**Comment by j-dimension** [comment]
Antwort der BRAK: "Es gibt derzeit keine Möglichkeit, über die KSW-Schnittstelle eine Nachricht als "gelesen" zu markieren."
