### ISSUE TITLE
Versendung BEA Nachricht

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-org#430]
Bei Versendung einer BEA Nachricht mit Speicherung in der Akte verschwindet (zumindest bei mir) die box für die Vergabe des Namens der Nachricht in der Akte hinter dem Statusbalken der Versendung. Man denkt zunächst, die Versendung hängt, dabei wartet der Statusbalken nur darauf, den Namen des Akteneintrags mit OK zu bestätigen.....

**Comment by j-dimension** [comment]
Duplikat von #348 , und in der aktuellen Entwicklungsversion bereits behoben.
