### ISSUE TITLE
Wo finde ich den BeaWrapper

### ISSUE THREAD

**Issue by eikebartels** [jlawyerorg/j-lawyer-org#436]
Ich würde mir gerne mal den org.jlawyer.bea.BeaWrapper anschauen jedoch finde ich nur die Verlinkung aber nicht das Package direkt. Wo finde ich das?

**Comment by j-dimension** [comment]
Der beA-Wrapper ist closed source, aufgrund vertraglicher Regelungen für die Kanzleisoftwarehersteller.
