### ISSUE TITLE
Parsing fehler bei Mails mit Grafik als Signatur

### ISSUE THREAD

**Issue by Maz111111** [jlawyerorg/j-lawyer-org#439]
Die KSW gibt einen Fehler aus 
"Fehler beim Öffnen der Nachricht: failed to parse:"
wenn man versucht, eine eMail mit einer Grafik als Signatur zu öffnen bzw. anzuzeigen.

Habe mir die Mail der gegnerischen Kollegen selbst weitergeleitet und dabei die Signaturgrafik entfernt. Dann konnte jL die Mail öffnen bzw. anzeigen.

Es dürfte wohl nicht so unüblich sein, dass Kanzleien eine Grafik (ihr Logo) als Signatur verwenden.

**Comment by Maz111111** [comment]
Nachtrag:
Habe gerade auf die Mail aus Thunderbird heraus geantwortet und mir die Antwortmail, in der auch noch die Grafik des GG drin war, per Drag and Drop in die Akte gezogen.
Beim Anzeigen dieser Antwortmail kommt der Fehler nicht mehr. die Grafik wird nur als Rahmen angezeigt. Im Rahmen steht offenbar der Name der Grafikdatei und ein graues Piktogram (ein zerbrochenes Bild)

**Comment by j-dimension** [comment]
Wäre es möglich, die Email, welche den Fehler zeigt, als Export / .eml zur Verfügung zu stellen?

**Comment by Maz111111** [comment]
Hab Dir eine Mail an info@j-lawyer.org gesendet.
Hab nur den Header im Betreff geändert - wegen Geheimnispflicht und so

**Comment by j-dimension** [comment]
Offensichtlich Fehler in JavaMail: https://stackoverflow.com/questions/28813571/issue-loading-e-mail-with-image-attachment

**Comment by j-dimension** [comment]
https://stackoverflow.com/questions/50954561/strange-exception-in-mimebodypart-getcontent?rq=1

**Comment by j-dimension** [comment]
Dieser Fehler ist außerhalb meines "Einflussbereichs". Ich packe daher eine Referenz an #190 und werde das dort dann erneut testen. 
Dieses Ticket hier schliesse ich, da keine Möglichkeit besteht das ohne #190 zu beheben.
