### ISSUE TITLE
beA: Sendedialog zeigt nicht alle Beteiligten

### ISSUE THREAD

**Issue by j-dimension** [jlawyerorg/j-lawyer-org#443]
Hat ein Beteiligter keine SafeID, so sollte er nicht als Empfänger auswählbar sein (ist bereits so), aber er sollte trotzdem als Beteiligter für das Vorlagensystem auswählbar sein.

**Comment by stm9x9** [comment]
ich würde grundsätzlich nicht unbedingt Energie in alles rund um das beA-Nachrichtentextfeld stecken. Mir wurde gesagt, die Gerichte wollen da eh nichts drin haben und mittelfristig soll das Feld wohl eher abgeschafft werden
