### ISSUE TITLE
Umschalten auf Notfallbox Boxversion 1.11

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-org#447]
Super das die Umsetzung der Reaktivierung als Notfallbox so schnell erfolgt ist. Aber bevor ich es testweise probiere: Die Aktivierung der Notfallbox als aktive Box erfolgt durch Auswahl beim Einloggen. Aber wo und wie stelle ich sie wieder von Aktiv auf Notfallbox (Kurze Anleitung?). Danke!

**Comment by j-dimension** [comment]
Direkt in der Browseroberfläche. War die Box mal "Ziel" einer Replikation, wurde dann aber aktiviert, so erscheint ein entsprechender Button.
