### ISSUE TITLE
Adressen: PLZ-Import mit Bundesland?

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#448]
![image](https://user-images.githubusercontent.com/29924198/68088746-5eaa9b00-fe62-11e9-91d6-1ebeaf6fa0b8.png)

Wenn ich über die PLZ-Suchmaske aus dem importieren Verzeichnis den Ort suche, dann wird der Ort mit (Bundesland) dahinter in die Adresse übernommen. Ist zwar nett die Information, aber postkonforme Adressen erzeugt man damit nicht, oder?

**Comment by j-dimension** [comment]
Was meinst du mit "postkonform" - gibt es einen Standard oder eine Situation wo das Probleme verursacht?

**Comment by stm9x9** [comment]
Ich weiß nicht ob 

Name
Straße
12345 Stadt (Bundesland) 

den Anforderungen an eine Zustell-Adresse genügt. 

Jedenfalls die Vorgaben der Post für maschinenlesbare Adressierung sagen:

`Postleitzahl und Bestimmungsort in
einer Zeile (in postalischer Schreibweise und ohne Länderkennzeichen
oder ISO-Kennung)`

Da steht nichts von (Bundesland)

**Comment by stm9x9** [comment]
Ich würde dann eher ein Feld Bundesland hinzufügen und mit der Suche ausfüllen. Dann kann jeder nach eigenem Wunsch dieses einbauen, wo er es will.

**Comment by j-dimension** [comment]
Ich würde ungern Zeit in Etwas investieren das evtl gar kein Problem darstellt.

Für mich erstmal eine rein optische Sache.

Schau ich ggf mit an wenn ich die Impotquelle aktualisiere.

**Comment by j-dimension** [comment]
Duplikat von #609
