### ISSUE TITLE
PLZ-Import: Aktionstasten

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#449]
![image](https://user-images.githubusercontent.com/29924198/68088782-adf0cb80-fe62-11e9-9ed5-ebed2bbf3c2b.png)

Irgendwie irritiert der Button Importieren, wenn man gerade importiert hat. Es ist nicht so intuitiv, daß man danach dann Schließen klicken muß, insbesondere weil da das rote Abbruch-Kreuz vor ist. Geht es nach dem Einlesen die Buttons zu verändern? In "Fertig" oder so?

**Comment by j-dimension** [comment]
Für Banken und PLZ-Import angepasst.
