### ISSUE TITLE
Fehler beim Öffnen eines odt

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#452]
Wenn ich ein mit j-l erstelltes odt öffne, dann wird beim Starten von LO dieser Fehler hier geschmissen:

![image](https://user-images.githubusercontent.com/29924198/68089392-a59b8f00-fe68-11e9-8e89-ec16ba704a47.png)

**Comment by j-dimension** [comment]
Java Version 12?!?! Damit funktioniert es definitiv nicht. 

Vermutlich hat Dein System ein JAVA_HOME falsch gesetzt oder ein Java 12 im "PATH" - dadurch wird das von j-lawyer.org mitgelieferte Java "ausgehebelt".

**Comment by stm9x9** [comment]
Wenn ich die Datei extern / lokal ablege und dann öffne, kommt der Fehler auch.

**Comment by stm9x9** [comment]
gestartet wird LO mit dem Dokument dann aber doch - sowohl von lokal als auch aus j-l heraus.

**Comment by j-dimension** [comment]
Sicher. Du kannst mir das Dokument gerne mal schicken, aber thematisch wäre das eher etwas für das LO-Forum. Warum hast / brauchst Du Java 12? Und noch dazu von Oracle direkt?

**Comment by j-dimension** [comment]
Sieht aus als hättest Du ein AddOn installiert, das das Problem verursacht.
https://languagetool.org/issues

**Comment by stm9x9** [comment]
ich habe jetzt in LO auf die 8/231 zurückgestellt. Der Fehler ist weg.

> Warum hast / brauchst Du Java 12? Und noch dazu von Oracle direkt?

Muß ich überlegen ... irgendwas wollte nur noch damit ... ah MediathekView

**Comment by j-dimension** [comment]
Passt.

Du kannst in LO irgendwo einstellen welche Javaversion verwendet wird. Da bin ich aber nicht so firm.
