### ISSUE TITLE
Vorlagen mit variablen Platzhaltern

### ISSUE THREAD

**Issue by Maz111111** [jlawyerorg/j-lawyer-org#455]
Was für irgendwann in der Zukunft:

In verschiedenen Vorlagen gibt es manchmal variable Werte für die jL keine Platzhalter zur Verfügung stellt (stellen kann).
Bsp.:
Übersendung eines Scheidungsbeschlusses von einem bestimmten Datum (Variable) zu Erteilung der Rechtskraftvermerks.
Der Text ist immer gleich:
überreiche ich den Beschluss vom XXXXXXXX im Original mit der Bitte um Erteilung der Rechtskraftvermerkes und darauf folgender Rücksendung an mich.

Hier wäre es großartig, wenn jL beim Erstellen der Vorlage bereits variable Platzhalter zur Verfügung stellen könnte, die dann beim eigentlichen Erstellen des Dokumentes abgefragt werden, wobei die Abfragesyntax vom Anwender - vielleicht ja sogar dokumentengebunden -  frei beschrieben werden kann.
In meinem Fall also eine Variable und im Erstellvorgang die Abfrage "Datum Beschluss?"

Hier könnten zum Beispiel 10 freie Platzhalter zur Verfügung gestellt werden.

Vielleicht wär das ja mal was für später.

Man kann das natürlich über eigene Felder in der Akte realisieren. Ich find die beschriebene Vorgehensweise aber intuitiver...

**Comment by j-dimension** [comment]
Sowas hatte ich neulich mit einem Anwalt aus NRW besprochen. Das hat eine Menge Potential!

**Comment by stm9x9** [comment]
Gibt es nicht bei in LO die Möglichkeit, Felder zu definieren, die beim ersten Öffnen einer Vorlage genau sowas abfragt?

**Comment by Maz111111** [comment]
Jetzt habe ich doch tatsächlich angefangen zu suchen und auch noch was gefunden.
Ja das geht über die Definition von Eingabefeldern.
Ist aber ja gerade nicht das, was ich wollte....
Ich will das Dokument gar nicht mehr öffnen müssen. Bereits beim Erstellen aus der Vorlage, soll es vollständig sein, so dass es direkt finalisiert und ausgedruckt oder per beA versandt werden kann.
Wenn man es erst öffnen muss und dann alle Daten - ggf. in Abfragefelder - eingeben kann, kann man die Daten auch gleich an die richtige Stelle ins Dokument schreiben.

**Comment by j-dimension** [comment]
Das sollte m.E. mit der neuen "Falldatenblätter"-Funktionalität umgesetzt werden. Bitte ein Ticket erstellen, mit den Daten die benötigt werden.
