### ISSUE TITLE
Startaktenzeichen auch für das frei einstellbare AZ Schema

### ISSUE THREAD

**Issue by Maz111111** [jlawyerorg/j-lawyer-org#460]
Ich pack es jetzt doch mal rein:
Es wäre gut, wenn man ein beliebiges AZ Schema verwenden könnte und diesem auch ein StartAZ zuweisen könnte.
Also z.B.: 
Schema:
dreistellige fortlaufende Zahl/aktuelles Jahr (zweistellig), beginnt jedes Jahr automatisch neu und startet immer mit 101 als erstes AZ pro Jahr.

**Comment by j-dimension** [comment]
Ich schaue mir als erstes den Aufwand an. Wahrscheinlich noch nicht in 1.11, es sei denn es ist eine triviale Änderung.

**Comment by j-dimension** [comment]
nnn/YY kann jetzt mit Start-Index genutzt werden.
