### ISSUE TITLE
Dokument mehrfach als pdf ablegen

### ISSUE THREAD

**Issue by Maz111111** [jlawyerorg/j-lawyer-org#461]
Wenn ein Dokument in einer Akte ein zweites Mal als pdf abgelegt werden soll, kommt die Meldung:
"Fehler beim Duplizieren des Dokuments...existiert bereits - bitte einen anderen Namen wählen.
"ok"
Es wird dann aber nicht die Möglichkeit geboten, einen anderen Namen zu wählen. Der Vorgang wird einfach abgebrochen.
Entweder benennt man das Ausgangsdokument um oder löscht das bereits vorhandene pdf bzw. benennt es um.
Der Anwendungsfall ist minimal (wenn man z.B. ein Dokument als pdf mit unterschiedlichen Stempeln versehen will oder sowas).
Aber wenn schon die Aufforderung kommt, einen anderen Namen zu wählen, sollte dann auch die Möglichkeit der Namenswahl gegeben werden. Oder die KSW sollte automatisch (1) hinter den eigentlichen Namen generieren.

**Comment by j-dimension** [comment]
Nacharbeiten: falsche Endung wird angeboten
