### ISSUE TITLE
Rendern von PDF/A dauert lange

### ISSUE THREAD

**Issue by Maz111111** [jlawyerorg/j-lawyer-org#462]
Es dauert (gefühlt) immer unheimlich lang, die Vorschau eines pdf zu öffnen.
Bestünde die Möglichkeit, dass sofort nach dem Öffnen der Akte, alle Dokumente in einen Cache geladen werden, um sie somit direkt und ohne Wartezeit zumindest in die Vorschau  - vielleicht ja sogar auch in das Bearbeitungsprogramm - öffnen zu können (Klick und sofort da).
Das Cachen sollte allerdings im Hintergrund ausgeführt werden, so dass man sofort in der Akte arbeiten kann.
IT technisch hab ich da zu wenig Ahnung - aber ich meine, dass es wohl gut wäre, dazu ausschließlich den Speicher des jeweiligen ClientRechners zu verwenden, um bei Verwendung der Box, diese nicht zu überlasten und außerdem insgesamt auch den Flaschenhals des Netzwerkes zu umgehen.
Wahrscheinlich wäre es dann auch das Günstigste, wenn man keinen Festplatten Cache verwendet, sondern tatsächlich irgendwie den RAM verwenden könnte und nur im Notfall auf die HD zurückgreift.

**Comment by j-dimension** [comment]
Das sollte eigentlich nur bei wirklich grossen PDFs der Fall sein - dauert die Anzeige auch lange bei kleineren PDFs?

**Comment by j-dimension** [comment]
Und ja, das Netzwerk spielt hier natürlich eine entscheidende Rolle, mit der Hardware der Box hat das nichts zu tun, da die Anzeige am Arbeitsplatz aufbereitet wird.

**Comment by Maz111111** [comment]
Also ich habe eben mal schnell LAN Speed Test installiert und die Verbindungsgeschwindigkeit zu meinem Scan Ordner auf der Box getestet. Upload: 35,05 Mbps Download 48,14 Mbps
Insofern sollten sich (theoretisch) ja erst spürbare Wartezeiten bei Files ergeben, die größer als 35 Mb sind.
Aber ich habe gerade festgestellt, dass die Wartezeiten hauptsächlich bei den von mir generierten pdf (pdf / A und durchsuchbar) entstehen. Egal welche Größe.
Aber auch bei den anderen pdf ist es nicht das Klick und da Gefühl.
Der Ladebalken kommt eigentlich immer. Und immer auch so lang, dass es spürbar ist.

**Comment by j-dimension** [comment]
48Mbps sind 48 MegaBIT pro Sekunde, also 6 MegaBYTE pro Sekunde. 

Im Vergleich dazu ist man bei einem üblichen kabelgebundenen Netzwerk bei 125 MegaBYTE pro Sekunde. Das ist schon gravierend.

Besteht die Möglichkeit so ei PDF/A zu bekommen, das lange lädt?

**Comment by Maz111111** [comment]
klaro schicke ich per mail

**Comment by j-dimension** [comment]
Ich kann bestätigen dass das Darstellen des gesendeten PDF/A länger als bei anderen PDFs dauert. Ein PDF mit sehr vielen Seiten (>100) ist bei mir in nullkommanix offen, Dein einseitiges Testdokument "lädt" deutlich länger. Mit "Laden" meine ich hier tatsächlich nur die Darstellung.

An dieser Stelle wird ein Cache keine Vorteile bringen. Letztlich muss ich hier die Ursache ermitteln. Ich verwende eine externe Bibliothek zur Darstellung von PDFs. Werde als erstes versuchen auf die neueste Version zu wechseln.

Ticketnamen passe ich entsprechend an.

**Comment by stm9x9** [comment]
Wie lange ist denn lange?

Bei mir braucht es auch ca 1-2sec, auf e jeden Fall ist der Ladebalken deutlich wahrnehmbar.

**Comment by j-dimension** [comment]
Ja, bei mir auch 1-2s, auch wenn das PDF/A nur 1 Seite hat.

**Comment by Maz111111** [comment]
Ok.
Supi! Danke!@stm9x9 
lange ist natürlich relativ. Man merkt es eben.

**Comment by Maz111111** [comment]
Wenn das pdf am Client Rechner aufbereitet wird, hängt es ja auch noch von der Leistung dieses Rechners ab(?).
Falls das so ist:
Wäre es dann eventuell nicht doch erwägenswert, dann eben die Aufbereitung der pdf Dateien beim Öffnen der Akte schon im Hintergrund zu starten und zu "cachen".
Wenn man mit Tablet oder Minicomputer im Termin sitzt, wäre das bestimmt angenehm, wenn die Dinger sofort in einem großen Vorschaubild (#469) aufpoppen.
Aber das ist alles nix, was drückt.

**Comment by j-dimension** [comment]
@Maz111111 ist das noch ein Problem? Ich vernehme zumindest von anderen Anwendern keine vergleichbaren Rückmeldungen.

**Comment by Maz111111** [comment]
Der Ladebalken kommt nach wie vor.
Aber egal. Mach hier zu. Wenn ich es in Zeit ausdrücke, sind es in der Tat nur 1-2 Sekunden.

Das muss dann eben so.
