### ISSUE TITLE
Auswahlfenster Vorlagen: Größe änderbar

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-org#463]
Wir haben inzwischen einige Ordner Vorlagen angelegt (Themensortiert). Wenn man eine Vorlage (Dokument erstellen) auswählen will, ist das Auswahlfenster für die Vorlagenordner bzw. Vorlagen recht klein, man muss scrollen obwohl genug Platz am Bildschirm da wäre. Man kann den Gesamtframe der sich geöffnet hat dann zwar auch vertikal größer ziehen, aber nicht das in ihm enthaltene Auswahlfenster mit den Ordnern / Vorlagen vertikal vergrößern. Es wäre sinnvoll, wenn beides variabel wäre, also auch die vertikale Vergrößerung des Auswahlfensters für Vorlagen möglich wäre.

**Comment by Maz111111** [comment]
Wie schon bei #335 und auch bei #464 
Letztlich trifft das alles den selben Bereich.
