### ISSUE TITLE
Größe Auswahlfenster beim nächsten Öffnen gespeichert

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-org#464]
Man kann im Ordner beim Vorgang Dokument - erstellen das Auswahlfenster horizontal größer ziehen (und vielleicht ja zukünftig auch vertikal), aber die Veränderung ist beim nächsten Öffnen nicht gespeichert. Wäre aber arbeitserleichternd, wenn die eingestellte Größe / Aufteilung gleich bliebe.

**Comment by Maz111111** [comment]
das betrifft letztlich auch #335

**Comment by j-dimension** [comment]
Dieses Fenster wird nun immer maximiert geöffnet.
