### ISSUE TITLE
Version 1.10 - Mailversand web.de funktioniert nicht

### ISSUE THREAD

**Issue by RoVoBo** [jlawyerorg/j-lawyer-org#465]
Es gibt in Version 1.10 einen Fehler beim Email-Versand über web.de, vermutlich weil dort der smtp-Port auf 587 gewechselt wurde.

Einstellungen im Nutzerprofil:

     Server: smtp.web.de
     Verschlüsselung: StartTLS AN, SSL AUS

Ich erhalte die Fehlermeldung: could not connect to smtp-host: smtp.web.de, port: 25

Im besten Falle sollte die Eingabemaske vorsehen, dass der Port manuell eingetragen werden kann.

Forumbeitrag unter:

https://www.j-lawyer.org/?topic=fehlermeldung-mailversand

**Comment by j-dimension** [comment]
Kommt wahrscheinlich gleich noch in die kommende Version. Danke für das Ticket.

**Comment by j-dimension** [comment]
@RoVoBo ich sitze gerade an der Thematik und stelle fest: der Versand geht wieder! Evtl. hat web.de wieder auf den Standardport gewechselt?

**Comment by j-dimension** [comment]
Nichtsdestotrotz werde ich den Port jetzt konfigurierbar machen.

**Comment by RoVoBo** [comment]
danke fürs Kümmern und die Nachricht, ich werde das auch mal testen und berichten.


Mit freundlichen Grüßen

Ronald Voigt
——————————————
Holzstr. 32
44869 Bochum

**Comment by RoVoBo** [comment]
Ich habe es gerade nochmal mit dem web.de-Accont getestet: Weder mit TLS, SSL, noch beiden Häkchen geht die Email raus.

Gruß

RoVoBo

**Comment by j-dimension** [comment]
Das ist verwunderlich... danke jedoch fürs Testen!

Dann wirst Du wohl oder übel auf die 1.11 warten müssen.
