### ISSUE TITLE
Tastatursteuerung in Dokumentenliste - Enter zum Öffnen

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#468]
man kann ja in der Dokumentenliste eine Akte mit den Pfeiltasten navigieren. Sehr angenehm durch Durchblättern einer Akte.

Allerdings kommt man nicht nur mit Pfeilrunter sondern auch mit Enter zu nächsten Datei. Bei Enter wäre es schöner, wenn das Dokument wir bei Doppelklick geöffnet werden würde. Dann bräuchte man da nicht extra zur Maus greifen.

**Comment by stm9x9** [comment]
Da paßt auch: 

man kann ja mehrere Dateien markieren. Wenn man die dann auch mit Enter alle öffnen könnte ...

**Comment by Maz111111** [comment]
Möglicherweise könnte man überhaupt die gängigen Tastaturkommandos implementieren.
Es passiert mir zum Beispiel auch andauernd, dass ich "Entf" drücke, um zu löschen und dann eben doch zur Maus greife...
Backspace könnte Seite zurück sein etc.

**Comment by j-dimension** [comment]
Tastenkombinationen: wenn, dann maximal solche die auf macOS, Windows und Linux identisch sind. An allen stellen plattformspezifisches Verhalten in der Oberfläche einzubringen, halte ich schlicht nicht durch.

**Comment by Maz111111** [comment]
Das ist absolut verständlich und macht auch absolut  Sinn.
Dann braucht ein Anwender bei einem eventuellen Systemwechsel sich auch nicht jedes mal umzugewöhnen.
Es wäre ja auch möglich, immer nur ein par Tastenkürzel pro Update zu implementieren.

**Comment by stm9x9** [comment]
paßt vielleicht auch hier rein:

![image](https://user-images.githubusercontent.com/29924198/69283227-584f4980-0bec-11ea-8573-17ef5ae8a925.png)

Bei solchen Dialogen die Standard-Aktion (hier also speichern) mit Enter/Return nutzen.
