### ISSUE TITLE
Vorschaufenster vergrößern - Tags  verkleinern

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#469]
könnte man den Platz untern anders verteilen? Statt so viel (zu viel?) Platz für die Tags zu verwenden

![image](https://user-images.githubusercontent.com/29924198/68552433-49f87500-0417-11ea-8ae8-abad69271681.png)

das Vorschaufenster (die Seiten sind als A4 ja halt meisten hoch statt breit) nach untern vergößern?

![image](https://user-images.githubusercontent.com/29924198/68552480-cab77100-0417-11ea-9313-1102b19afe5a.png)

**Comment by stm9x9** [comment]
Dies würde das Durchblättern und sich in der Akte orientieren deutlich erleichtern.

**Comment by Maz111111** [comment]
Wäre es eine Option, dass die Größe des angezeigten Dokuments nicht feststehend ist, sondern immer so groß ist, wie das Anzeigefenster und quasi mit dem Anzeigefenster wächst, wenn der Anwender es größer macht, wobei dem Anwender dann auch die Möglichkeit gegeben werden sollte, das Fenster - wie in den Beispielbildern oben - eben auch in den unteren Bereich, wo jetzt die Etiketten stehen, (größer) zu ziehen.

**Comment by Maz111111** [comment]
Es sollte jedenfalls unabhängig vom verwendeten Bildschirm möglich sein, immer eine komplette Seite des Dokuments anzuzeigen und das - jetzt natürlich abhängig vom verwendeten Monitor - so groß, wie der Anwender es möchte.

**Comment by j-dimension** [comment]
Was haltet ihr davon das Dokument mit einem Klick in einem Popupdialog öffnen zu können, das dann gern auch Fullscreen sein kann?

**Comment by Maz111111** [comment]
grundsätzlich nicht schlecht. 
Meine Intention ist aber immer die Mandatsbesprechung oder die Verhandlung.
Wenn das PopUp dann so funktionieren würde, dass es offen bleibt und man mit den Cursortasten (hoch/Runter) das nächste/vorherige Dokument öffnet und mit den Cursortasten (links/rechts) im Dokument blättern kann, wäre das eine gute Lösung.
Die Dokumentenliste sollte aber sichtbar bleiben oder sichtbar gemacht werden können.

**Comment by j-dimension** [comment]
Okay, also so eine Art Dokumentrecherchemodus. Könnte ich mir gut vorstellen in Verbindung mit einer Volltextsuche im gleichen Dialog.
