### ISSUE TITLE
geschlossene Dokumente werden als noch geöffnet gewarnt

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#470]
alle drei Dokumente sind geschlossen. Konkret ist hier kein einziges pdf mehr geöffnet auf dem Rechner.

![image](https://user-images.githubusercontent.com/29924198/68552529-44e7f580-0418-11ea-8c6d-19ddf75e1f27.png)

BTW, wo ist das Problem, wenn ein Dokument noch geöffnet ist, das schreibgeschützt geöffnet wurde?

**Comment by j-dimension** [comment]
Keine Warnung mehr bei schreibgeschützt offenen Dokumenten.
