### ISSUE TITLE
Beteiligte / Rollenvergabe / Vorlage für Rubrum mit allen regelmäßig möglichen Beteiligten etc.

### ISSUE THREAD

**Issue by Maz111111** [jlawyerorg/j-lawyer-org#471]
Es gibt diverse Issues die diese Thema irgendwie diskutieren. Und ich könnte mich jetzt an jedes dranhängen.
Wenn das hier zu viel ist - bitte einfach zumachen.

Die Frage der Beteiligten und deren Rollenverteilung ist ein spannendes Thema und beeinflusst imo den Arbeitsablauf mit der KSW so sehr, dass 2.0 (so zum Bsp in #401, #121, geplant) fast ein wenig spät ist...

Der Anwendungsfall ist ja bei jedem Klagerubrum präsent und damit im Schnitt mindestens einmal pro Woche.
Der Schriftsatz mit dem Rubrum geht an den Dritten (Gericht). Im Rubrum werden dann zusätzlich mindestens die Beteiligten MANDANT, GEGNER und 2. DRITTE (Anwalt des GEGNERS) aufgeführt.
In der Vorlage kennt jL aber nur einen Platzhalter für einen DRITTEN.
Wenn jetzt noch gesetzliche Vertreter dazukommen ist der Vorteil, den die Nutzung von Vorlagen bringt, schon fast marginal, weil man dann doch wieder soviel von Hand einfügen muss.
Also Ziel sollte es sein, eine Vorlage erstellen zu können, in der zumindest "die üblichen Verdächtigen" automatisch eingefügt werden können. (oder geht das schon und hab's nur nicht geblickt?)

Die Frage, ob man die Anzahl und die Bestimmung / Benennung der Rollenverteilung der "Verdächtigen" dem Anwender überlässt oder diesem ein festes Korsett vorgibt (z.B. "automatisiert kann die KSW eben nur Gerichte für 3 Instanzen, maximal zwei Gegenanwälte und 3 Gegner sowie 5 eigene Mandanten über eine Vorlage abbilden") würde ich mal zur Diskussion stellen oder aber der Entscheidung von Jens überlassen.

**Comment by j-dimension** [comment]
Ich verstehe die Thematik, und es gibt Tickets dafür. 

Jedoch

> Die Frage, ob man die Anzahl und die Bestimmung / Benennung der Rollenverteilung der "Verdächtigen" dem Anwender überlässt oder diesem ein festes Korsett vorgibt (z.B. "automatisiert kann die KSW eben nur Gerichte für 3 Instanzen, maximal zwei Gegenanwälte und 3 Gegner sowie 5 eigene Mandanten über eine Vorlage abbilden") würde ich mal zur Diskussion stellen oder aber der Entscheidung von Jens überlassen.

gerade diese Fragestellung wäre für mich interessant. Hier bin ich an Anwendermeinungen interessiert.

**Comment by Maz111111** [comment]
Das ist schwierig und ich bin da nicht das Maß der Dinge. Am einfachsten wäre dann aber wohl eine feste Vorgabe, die zumindest die häufigsten Anwendungsfälle abdeckt.
Wenn man es variabel gestalten will, dürfte es einen erheblichen Arbeitsaufwand auf Seiten der Programmierung hinsichtlich der Platzhalter geben.
Insofern hat man regelmäßig (es gibt Ausnahmen) mit einem Gericht pro Instanz zu tun. Regelmäßig wird es max 3 Instanzen geben. Also müsste Platz für drei Gerichte da sein - sowohl bei der Beteiligtenerfassung als auch bei den Platzhaltern. Es müsste auch den Beteiligten "Gericht" geben.
Regelmäßig wird man max 3 Gegenparteien (im VKU: Fahrer, Halter, Versicherung) haben, die sich - das ist schon eher die Ausnahme - auch von drei unterschiedlichen RAs vertreten lassen.
Ergo sollten Platzhalter für 3 GG da sein, denen bei der Erfassung und mit den Platzhaltern jeweils ein RA zugeordnet werden kann. Also muss es den Beteiligten Typ Gegnervertreter geben.
Bei den eigenen Mandanten denke ich an sozialrechtliche Konstellationen und die Vertretung einer Großfamilie. Hier dürften 5 eigene Mandanten-Platzhalter den Regelfall abdecken.
Dann fällt mir im Familienrecht noch der gesetzliche Vertreter ein, der beim Beteiligten "Mandant" (mit vollständigen Beteiligtendaten: Anschrift, Tel, eMail etc) aufgenommen werden könnte und eigene Platzhalter erhält. Hier ist zu berücksichtigen, dass der eigentliche Ansprechpartner immer diese Person sein wird (ließe sich aber evtl. auch über Ansprechpartner lösen- wäre aber gefühlt eher ein Workaround, da die Anschrift nicht aufgenommen werden kann und es dafür dann auch keine Platzhalter gäbe).
Von allem gibt es Ausnahmen, wenn ich die 50 köpfige Erbengemeinschaft oder WEG vertrete sind da nach oben keine Grenzen. Aber das sind doch eher Ausnahmen.
Wenn man auf jede von mir benannte Zahl noch 2 oder 3 als Puffer aufschlägt, sollte die KSW für den Regelfall ganz gut aufgestellt sein.

**Comment by j-dimension** [comment]
Danke @Maz111111. Evtl. haben die fleissigen Ticketschreiber @stm9x9 / @Mucki526 / @RA-crm noch etwas zu ergänzen / entgegnen :-)

**Comment by RA-crm** [comment]
Hallo in die Runde!

Ich versuche die sich mir stellenden Probleme und meine Lösungsansätze kurz zu skizzieren.

mE sollten wir unterscheiden zwischen den Gruppen "Mandant, Gegner und Dritte" sowie Personen/Adresssätze, welche in den jeweiligen Gruppen Rollen übernehmen:

einfaches Beispiel:
V gegen K auf Kaufpreisforderung
Mandant = V (Rolle: Mandant)
Gegner = K (Rolle:Gegner); RA R (Rolle: Gegnervertreter)
Dritte = Gericht 1 (Mahngericht) Gericht 2 (Gericht 1. Instanz) Gericht 3 (Gericht 2. Instanz)

wenn es komplizierter wird sähe es schon so aus:
Mandant = V GmbH & Co KG (Rolle: Mandant); Vertreter: VVerw GmbH (Rolle: gesetzlicher vertreter; T (Rolle: Geschäftsführer); Herr U (Rolle Kontaktperson)
Gegner = K AG (Rolle:Gegner); E (Rolle: Vorstand), RA R (Rolle: Gegnervertreter)
Dritte = Detektei XY (Rolle: Detektiv); Behörde Stadt S (Einwohnermeldeamt) Gericht 1 (Mahngericht) Gericht 2 (Gericht 1. Instanz) Gericht 3 (Gericht 2. Instanz)

Bei einem Verkehrsunfall:
Mandant = V GmbH & Co KG (Rolle: Mandant; Halter); Vertreter: VVerw GmbH (Rolle: gesetzlicher vertreter; T (Rolle: Geschäftsführer); Herr U (Rolle Kontaktperson); Frau L (Rolle Fahrerin)
Gegner = K AG (Rolle: Gegner; Halter); E (Rolle: Vorstand), RA R1 (Rolle: Gegnervertreter Halter); Herr C (Rolle Fahrer); RA R2 (Rolle: Gegnervertreter Fahrer); KJ VersGesellschaft AG (Rolle HPV), G (Rolle: Vorstand HPV), RA R3 (Rolle: Gegnervertreter HPV)
Dritte = Autohaus A (Rolle Autohaus); Polizei W (Rolle Ermittlungsbehörde/Polizei); Staatsanwaltschaft R (Rolle Ermittlungsbehörde/StA)

Daraus folgt auch, dass die Schreiben nicht mehr durch die Gruppen "Mandant, Gegner und Dritte" bestimmt werden, sondern aus der Rolle heraus. So kann dann auch dem jeweiligen Adressaten die jeweilige Kontaktperson zugeordnet werden. 

Was meint ihr?

**Comment by Maz111111** [comment]
Möglicherweise sind zuerst mal die Ansätze zu klären.
Geht es um eine möglichst uneingeschränkte Abbildbarkeit innerhalb der KSW oder geht es um die Möglichkeit, möglichst automatisierte Prozesse über Vorlagen zu schaffen.
Während ersteres absolut mit dem Rollenszenario von @RA-crm möglich wäre (und zwar vermutlich besser als mit meinem Beispiel, weil ich es ja begrenzt habe), denke ich, dass die Platzhalterproblematik bei dem Vorschlag von @RA-crm , schier nicht zu bewältigen sein könnte.

**Comment by RA-crm** [comment]
Ich habe keine Kenntnis, wie wir die Rollen und Adressdaten sinnvoll abbilden können. 

Ich habe allerdings Erfahrungen mit einer anderen KSW, die ich in meiner zweiten Kanzlei nutze. Dort wird so ein Rollmodell genutzt. Daher kommt auch mein Überlegungsansatz.

Ich vermute, dass die Lösung darin liegt, die Platzhalter nicht mehr nach den Gruppen zu benennen, sondern über die Rollen zu kommen.

**Comment by Maz111111** [comment]
Hier müsste sich Jens mal äußern.
Soweit ich das sehe, bräuchte man ja dann die Möglichkeit, unendlich viele, sich selbst generierende Platzhalter zu programmieren, da ja niemand vorhersagen kann, wie viele Beteiligte es in einer Akte mal geben kann - gleichwohl für den Anwender aber die Möglichkeit geschaffen werden soll, eine unbegrenzte Anzahl an Beteiligten (egal welche Rolle sie innerhalb der Akte spielen) pro Akte zu generieren.
Ich glaube, dass es mit den zur Verfügung stehenden Ressourcen möglicherweise nur für eine begrenzte Anzahl machbar ist, die Beteiligten auch mit Platzhaltern für die Vorlagen zu versorgen.
Es geht darum, dass es dann in einer Akte durchaus auch mal 2 Beteiligte Dritte mit der Rolle RA des Beteiligten Gegners geben kann. Es kann aber auch mal 5 Beteiligte Dritte mit dieser Rolle geben. 
Wenn es - worum es mir geht - für jeden Beteiligten innerhalb der Akte einen Platzhalter geben soll, müssen die sich entweder in Abhängigkeit von den Eingaben des Anwenders selbst generieren oder aber begrenzt werden. 
Eine Begrenzung mag ja nicht daran hindern, so viele Beteiligte aufzunehmen und entsprechenden Rollen zuzuweisen, wie man will. Es muss dann eben nur klar sein, dass es nur für eine bestimmte Anzahl an jeweiligen Rollen und möglicherweise auch nur für bestimmte Rollen Platzhalter gibt und alles andere dann eben von Hand eingetragen werden muss.
Ob man nun eine Struktur Oberbegriff Beteiligter und Unterkategorie Rollenvergabe oder nur statische Beteiligte vorgibt, ist Geschmacksache. Das Rollenmodel dürfte mehr Flexibilität bieten, wenn man die Rollen selbst definieren und benennen könnte.

**Comment by stm9x9** [comment]
Also aus dem Sozialrecht kann ich nur sagen, daß 5 Mandanten die untere Grenze einer möglichen Begrenzung darstellen. Mehr als 5 sind auch nicht unüblich.

Gerichte können en masse auftauchen:

Einstweiliger Rechtsschutz über zwei Instanzen
dann das UK-Gericht, weil der Widerspruch in der Hauptsache nicht entschieden wird
dann die normalen Instanzen1-3
und zwischendurch, weil die alte einstweilige abgelaufen ist, nochmal das Spiel mit dem einstweiligne Rechtsschutz ...  Und eine Kollegin hat es gerade geschafft in einer Untätigkeitsklage in die Berufung zu gehen ... :-D

Dazu dann als Gegner das Jobcenter, der Inkasso-Service (hier übrigens dann auch noch eine weitere ER-Instanz), de Inkasso-Service für den zweiten Mandanten ...

**Comment by stm9x9** [comment]
Bei a-jur wird das zb semi-automatisch geregelt:

man kann in den Einstellungen eine Liste von Rollen anlegen (und dazu auch noch Verfahrensrollen wie Widerspruchsgegner, Beklagter ... die man nacheinander einer Partei zuweist. Aber IMHO braucht es das nicht unbedingt. Eher noch Beklagter oder Beklagte irgendwie mit passenden grammatikalischen Varianten in der Klageerzeugung)

Aber ich kann jedenfalls die Rollen in dieser Liste anlegen und im laufenden Betrieb kann sich das Programm daran langhangeln und man muß nicht im laufenden Betrieb bei jeder Dokumentenerzeugung für eine individuelle nicht vorhersehbare Menge von ad hoc erzeugbaren Rollen vorsorgen.

**Comment by Maz111111** [comment]
> Gerichte können en masse auftauchen:

Hmmm…
EA und HS dürfte immer das selbe Gericht sein. Was sich unterscheidet ist das AZ. Bei mir laufen EA Sachen aber immer unter einem eigenen KanzleiAZ - kann man ja auch einzeln abrechnen - und ggf. gibt es danach gar keine HS mehr, weil alles per Einigung erledigt.
Also bei den Gerichten halte ich daran fest, dass es pro Akte wohl ausreichen dürfte, drei unterschiedliche Gerichte mit unterschiedlichen AZ anlegen und in den Vorlagen einsetzen zu können.
Also ich kann mir gerade kein Szenario vorstellen, bei dem ich innerhalb einer Akte unterschiedliche Gerichte innerhalb einer Instanz gleichzeitig oder auch nacheinander in einer Vorlage per Platzhalter einsetzen können muss.

**Comment by stm9x9** [comment]
wie gesagt, siehe mein Kommentar oben. Und selbst wenn man die EA-Sache in eine eigene Akte packt, kommt mit UK, Abwehr vom Jobcenter-Inkasso etc schon einiges zusammen.

**Comment by j-dimension** [comment]
Gelöst in #117
