### ISSUE TITLE
Erweiterungen nur auf Wunsch einblenden

### ISSUE THREAD

**Issue by Maz111111** [jlawyerorg/j-lawyer-org#472]
Es wäre für die Übersichtlichkeit in den Dokumenten ganz gut, wenn die Erweiterungen ausgeblendet würden (und nur auf Wunsch einblendbar wären).
Die Piktogramme dürften im Regelfall ausreichen, um den Dateityp erkennen zu können.
Auch bei der Namensvergabe oder dem Umbenennen von Dokumenten könnten die Erweiterungen ausgeblendet bleiben. Auch wenn sie in diesen  Fällen automatisch angefügt werden, achtet man doch irgendwie immer darauf, die Erweiterung nicht zu überschreiben.

**Comment by j-dimension** [comment]
Ich erlaube mir das Ticket zu schliessen. Im Vergleich zur Menge der anderen Tickets und deren "Mehrwert" werde ich voraussichtlich nie zur Arbeit an diesem Ticket kommen.
