### ISSUE TITLE
Meldung Dokument ist bereits geöffnet

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-org#473]
Im Moment kommt beim Versuch ein geöffnetes Dokument zu öffnen die Fehlermeldung Dokument ist bereits geöffnet. Sinnvoller wäre es doch, wenn in diesem Fall einfach in das geöffnete Dokument gesprungen würde und man direkt weiterarbeiten kann.

**Comment by j-dimension** [comment]
Das ist nicht möglich ohne Funktionalitäten des darunter liegenden Betriebssystems, d.h. ich müsste das drei mal implementieren (macOS, Windows, Linux)... und potentiell noch für verschiedene Windowsvariante. :-(
