### ISSUE TITLE
Erstelldatum der Wiedervorlage / Frist

### ISSUE THREAD

**Issue by Maz111111** [jlawyerorg/j-lawyer-org#475]
Es wäre schön, wenn in der Wiedervorlage/Frist - Liste auch das Datum angezeigt würde, an dem der Eintrag erstellt wurde.
Damit kann man dann nachvollziehen, ob nach Erstellen der Wiedervorlage noch Posteingang in der Akte war, der die Wiedervorlage faktisch "überholt" hat.

**Comment by j-dimension** [comment]
Die Aktenhistorie zeigt Dir, wann eine WV erstellt oder auch verschoben wurde. Reicht das?

**Comment by librelegal** [comment]
Es könnte sich um ein Duplikat von #519 handeln

**Comment by j-dimension** [comment]
In der Tat stark verwandt. Ich schliesse dieses hier, da #519 einen größeren "Scope" hat.
