### ISSUE TITLE
Plugins auf neues Tabellenformat migrieren

### ISSUE THREAD

**Issue by j-dimension** [jlawyerorg/j-lawyer-org#478]
- [x] rvg: exemplarisch gemacht, braucht noch letzten Check ob in der 1.9.1er-Version Änderungen gemacht wurden die im 1.11er noch nicht enthalten sind
- [x] rvgtables: sollte nicht relevant sein
- [x] pkhtables: sollte nicht relevant sein
- [x] sozialrecht
- [x] gkgtables: sollte nicht relevant sein
- [x] strafrecht
- [x] pflichtverteidiger
- [x] honorar
- [x] rechnungsnr: sollte nicht relevant sein
- [x] strafrecht_owig

**Comment by j-dimension** [comment]
siehe #188

**Comment by j-dimension** [comment]
Sobald Installer für 1.11 verfügbar, --> @an-mus zur Verfügung stellen.

**Comment by an-mus** [comment]
Alle Plugins sind auf das neue Tabellenformat migriert. Ich habe auch die Tabellen und den Rechnungsnummerngenerator in den 1.11.0.0 Ordner kopiert, damit ab dem Versionssprung nur noch die Dateien aus dem Ordner bearbeitet werden müssen. Ich hoffe das ist in deinem Sinne. 
Wenn ich den Installer habe, kann ich mich ans testen machen.

**Comment by j-dimension** [comment]
@an-mus Du bist schlicht unglaublich - vielen Dank!

Bzgl. des Installers: wäre das bei Dir eine reine Testinstallation (als Neuinstallation) oder würdest Du direkt Deine produktiv genutzte Installation updaten?

**Comment by PBaumfalk** [comment]
Auf MacOS kopiert der die Berechnungen nicht mehr in die Zwischenablage. Bei anderen Betriebssystemen muss ich das noch ausprobieren.
