### ISSUE TITLE
leeren beA-Betreff unterbinden

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#480]
Ich kann das aktuell nicht verifizieren, fand das aber gerade bei Facebook:

![image](https://user-images.githubusercontent.com/29924198/69289939-7d4cb800-0bfe-11ea-8035-c7ba48a0a67a.png)

**Comment by j-dimension** [comment]
Diese Änderung habe ich bereits umgesetzt, das Ticket ist aber nur in einem Closed Source-Modul sichtbar.

Hintergrund: die BRAK informierte gestern, dass über die Schnittstelle Nachrichten ohne Betreff angenommen und zugestellt werden, dann aber nicht geöffnet werden können. Es fehlt schlicht eine Validierung innerhalb der BRAK-Schnittstelle.

Mit j-lawyer.org 1.11 wird daher der j-lawyer.org-eigene Bea-Wrapper eine solche Prüfung durchführen und ggf. einen Fehler werfen. 

Ich schließe daher das Ticket.
