### ISSUE TITLE
BEA "Refresh"

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-org#481]
Obwohl mein PC die Nacht oft durchläuft - wenn man BEA am nächsten Tag aufruft ist die Session invalid und man kann nichts versenden. Man muss erst den Client neu starten. Wie ich gelesen haben wird mit einem "Ich bin noch da" -Signal alle 29 min die Sitzung zum BEA offengehalten. Aber offensichtlich klappt das nicht über Nacht, vielleicht weil der Provider eine Zwangstrennung nachts vornimmt (Neue IP). Vielleicht wäre es eine Abhilfe, wenn grundsätzlich beim Aufruf des BEA im J-lawyer, egal ob direkt das Bestehen der Verbindung kurz geprüft und ggf. neu aufgebaut wird (falls möglich und erforderlich).

**Comment by j-dimension** [comment]
Ja, wenn die eigene IP sich ändert ist definitiv Schluss.

Hast Du mal oben im beA-Posteingang das Logout und dann Refresh probiert? Dann solltest Du einen neuen Login ohne Neustart des Clients hinbekommen.

**Comment by Mucki526** [comment]
Danke, ich probiers mal beim nächsten Mal, aber schöner wäre natürlich grundsätzlich mal die morgendliche Meldung "works fine - have a nice day" und nicht "error!!!- logout, refresh und - don´t forgert - login everyday again after error-message" :-).

**Comment by j-dimension** [comment]
Bitte mal die exakte Fehlermeldung und das client.log kurz nach Auftreten des Fehlers zur Verfügung stellen - danke!
