### ISSUE TITLE
[adressen] Ortsteil in der Adresse

### ISSUE THREAD

**Issue by Maz111111** [jlawyerorg/j-lawyer-org#487]
Das von der Post vorgegebene Format für die Angabe von Ortsteilen laut der Webseite der Post lautet:
"Eine Ortsteilbezeichnung ist zwischen Name und Straßenbezeichnung anzugeben."
Also benötigt man eine Extrazeile für den Ortsteil im Adressfeld.
Das kann ich aktuell nur abbilden, wenn ich die Ortseingabe beim Land mache und entsprechend alles andere auch verschiebe. 
In der Adressverwaltung sollte also eine Eingabe und ein Platzhalter für den Ortsteil eingefügt werden.

**Comment by librelegal** [comment]
Zur Vereinheitlichung sollte dieses issue mit einem tag zu Adressen versehen werden.
Bitte "[Adressen]" voranstellen.
