### ISSUE TITLE
Aktenzeichenbereich

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-org#490]
Es wäre ein Button bei Anlage neuer Akte hilfreich, mit dem man (Dropdown-Menue) einen Aktenbereich auswählen könnte. Also Button "Akte in speziellem Aktenbereich anlegen).  Die Bereiche könnten individuell hinterlegt werden (3000...., 4000 .... 5000) je nach Bedarf (Natürlich entsprechend dem verwendeten Aktennummernformat). Im Moment ist es für mich immer ein Gefrikkel (rein in die Einstellungen Aktenbereich verändern, neue Akte anlegen, wieder zurückspringen, alten Zähler wieder einstellen.  Geht schon irgendwie, wäre aber mit der Auswahlmöglichkeit hübscher und schneller. Nach der Aktenanlage mit der neuen Auswahl springt der Zähler für die nächste Aktennummer dann einfach wieder in die Standardposition..

**Comment by j-dimension** [comment]
Duplikat von #241 :-)
