### ISSUE TITLE
Platzhalter für Mandatsbeginn

### ISSUE THREAD

**Issue by Maz111111** [jlawyerorg/j-lawyer-org#493]
Es wäre schön wenn man einen Platzhalter für den Mandatsbeginn hätte.
Dieses Datum benötigt man bei jeder Abrechnung. 
Es könnte das (vom Anwender veränderbare) Datum des Tags sein, an dem die Akte im jL angelegt wurde.
Dies wird nicht immer (exakt) stimmen. Aber vielfach ausreichen.
Kumulativ sollte im Erfassungsbogen die Möglichkeit gegeben werden, das Datum der Vollmacht einzutragen, welches dann für den Wert des Mandatsbeginns maßgeblich wäre.

**Comment by librelegal** [comment]
Steuerlich genügt für die Rechnung der Leistungsmonat, es muss nicht der konkrete Tag sein (§ 14 Abs. 4 Satz 1 Nr. 6 UStG i.V.m. § 31 Abs. 4 UStDV).

**Comment by stm9x9** [comment]
zb für die Abrechnung von Beratungshilfe soll es aber taggenau sein.

**Comment by stm9x9** [comment]
Steuerlich wäre - insbesondere zb für die Frage, welcher USt-Satz in den nächsten Monaten gilt - das Datum des Endes des Mandats bzw der abrechnungstechnischen Angelegenheit (kann davon ja mehrere in einem Mandat / Akte geben) hilfreicher IMHO.

Auch für die Abrechnung von BerH wäre es sinnvoll, da dort der Vertretungszeitraum eingetragen werden soll

**Comment by j-dimension** [comment]
"Mandatsbeginn" werde ich via Ticket #920 in Form einer Angabe "Anlagedatum", welche dann auch editierbar sein wird, umsetzen. 

Beratungshilfe / Vollmacht etc. klingt für mich so als würde man es nicht immer brauchen, somit eher Kandidaten für Falldatenblätter. Meinungen dazu?

**Comment by librelegal** [comment]
das meine ich aus

**Comment by j-dimension** [comment]
Doku: 
- Platzhalter AKTE_ERSTELLT in Doku aufnehmen
- Demo-Vorlage(n) anpassen
