### ISSUE TITLE
[1.11] Schriftgröße Seitenleiste links

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#494]
Irgendwie ist die Größer der Schrift in der linken Seitenleiste nicht so recht stimmig zum Rest des Fensters.

![image](https://user-images.githubusercontent.com/29924198/70478806-41f62880-1adc-11ea-9e3f-18390b6d5cbb.png)

**Comment by j-dimension** [comment]
Wenn ich das größer mache gibt es

- weniger Bildschirmfläche zum Arbeiten
- definitiv eine Notwendigkeit zu Scrollen, um alle Module navigieren zu können

Ich gehe auch davon aus, daß man nach einer Einarbeitung tatsächlich nicht mehr auf das Lesen der Modulbezeichnung angewiesen sein wird.

**Comment by stm9x9** [comment]
> Ich gehe auch davon aus, daß man nach einer Einarbeitung tatsächlich nicht mehr auf das Lesen der Modulbezeichnung angewiesen sein wird.

Das würde ich nicht wetten. Alleine schon weil da die Symbole bis zu dreimal verwendet werden. (Mail beA drebis, die Fristen ...)

**Comment by stm9x9** [comment]
> * weniger Bildschirmfläche zum Arbeiten
> * definitiv eine Notwendigkeit zu Scrollen, um alle Module navigieren zu können

Ja? Ich meine da recht viel Freifläche gerade links zu sehen.

Vielleicht reicht auch schon eine Idee größer und dick dafür?

**Comment by j-dimension** [comment]
Die Freifläche gibt es nur, weil Du scheinbar kein E-Mail-Postfach angebunden oder ein Scanverzeichnis eingebunden hast. In diesen Fällen gibt es hinter der Modulbezeichnung noch einen Indikator, meist eine Zahl. Siehe bspw.
https://www.j-lawyer.org/wp-content/uploads/j-lawyer-1-11-desktop.png

**Comment by j-dimension** [comment]
Ist es okay für Dich wenn wir das erstmal bei ein paar Anwender "einsickern" lassen? Bei Bedarf kann ich das in 1.12 dann nachschärfen.
