### ISSUE TITLE
[1.11] beA: Neue Nachricht wird ohne Empfänger-Aktenzeichen verschickt, wenn Dropdown kein FocusLost bekommt

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#496]
Direkt in bea rein, ohne Akte. Ich erstelle eine neue Nachricht, wähle einen Empfänger aus, gebe ein Sender-Akz und ein Empfänger-Az ein. (vorher war das ja leer): Das Empfänger-Akz wird verschluckt und kommt weder beim Empfänger noch in gesendet an. Feld ist leer.

Wenn ich aus einer Akte heraus an einen Beteiligen eine Nachricht erstelle, dann wird das Akz immer erhalten. Auch wenn der Empfänger kein Akz hinterlegt hat und ich selber eines ins leere Feld eingebe: Es bleibt in der Nachricht erhalten. Nur halt nicht, wenn ich das ganze vom beA-Reiter aus direkt starte.

**Comment by j-dimension** [comment]
Schaue ich mir an.

**Comment by j-dimension** [comment]
@stm9x9 Sorry, das kriege ich nicht reproduziert. Kannst Du bitte einen Screenshot von den Sendeoptionen zur Verfügung stellen? Die verschiedenen Einstellungen spielen da eine Rolle.

Danke!

**Comment by stm9x9** [comment]
![image](https://user-images.githubusercontent.com/29924198/70580021-aaafd480-1bb2-11ea-9abe-6ff2a73a1686.png)

![image](https://user-images.githubusercontent.com/29924198/70580118-fa8e9b80-1bb2-11ea-9ab6-368c564870a3.png)

dann noch Justizbehörde unbekannt und:

![image](https://user-images.githubusercontent.com/29924198/70580188-2873e000-1bb3-11ea-8afd-73eb9a8d8d1d.png)

sowohl in Gesendet als auch im Posteingang ohne "receiver"

**Comment by j-dimension** [comment]
Bekomme ich leider nicht reproduziert. Ich lasse das Ticket in "Testing" stehen. Evtl. kannst Du den nächsten Release Candidate nochmal testen.
