### ISSUE TITLE
Interessenkollision: Liste der Akten

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#498]
Es wäre praktisch, bei der Warnung auch eine Liste (Akz, Rubrum, wegen) zu bekommen:

![image](https://user-images.githubusercontent.com/29924198/70579668-9e774780-1bb1-11ea-8c0d-b5c689b9e065.png)

**Comment by j-dimension** [comment]
Okay. Zwischenzeitlich kann man zum Beteiligten navigieren und sieht dort im letzten Tab alle Akten.

**Comment by librelegal** [comment]
Aus meiner Sicht kann eine Interessenkollision nur sicher gelöst werden, wenn die Adressen in der Adressverwaltung optimal mit allen notwendigen und zur Zeit teilweise fehlenden Feldern eingeben wurden. Eine fuzzy logic könnte im Moment helfen. 

Ich meine, dass auch dies ein Adress-Thema ist, deren technischer Abgleich erfolgt. Zur Vereinheitlichung sollte dieses issue mit einem tag zu Adressen versehen werden.
Bitte "[Adressen]" voranstellen.

**Comment by j-dimension** [comment]
Ich merke gerade dass dieses Ticket mit der 1.12 erledigt wurde - man bekommt eine Liste von Akten und der Rolle der Person angezeigt.
