### ISSUE TITLE
[1.11] Starten dauert wieder länger

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#500]
Mit der neuen Version dauert es teils bis zu 10sec bis das Anmeldefenster(sic!) erscheint.

**Comment by j-dimension** [comment]
- An welcher Stelle? Was steht im Fortschrittsbalken?
- Welches Betriebssystem?
- Welche Ausstattung (CPU? SSD?)
- Welche Module sind an? (beA mit automatischer Anmeldung? E-Mail? Sipgate? Drebis?)

**Comment by stm9x9** [comment]
Windows 10, 64 bit
Das 10sec-Warten kommen gleich nach dem Klicken auf das Programm-Icon. Bis überhaupt der Anmeldebildschirm kommt, also kein Fortschrittsbalken oder so bis dahin zu sehen. Bei 1.10 habe ich sowas nicht bemerkt.

**Comment by j-dimension** [comment]
Hmm.. an der Stelle wird noch gar keine Programmlogik ausgeführt, außer dem Laden der Anwendung in den Hauptspeicher. Zu wieviel % ist der ausgelastet, wenn der Anmeldebildschirm da ist?

**Comment by stm9x9** [comment]
Das im Kreis dürfte die RAM-Mehrbenutzung im Augenblick des Anmeldebildschirms sein:

![image](https://user-images.githubusercontent.com/29924198/70637390-703c4b00-1c37-11ea-8fe5-9576448d499a.png)

**Comment by j-dimension** [comment]
Das ist nicht auffällig. Und ich nehme an dass eine SSD verbaut ist?

**Comment by j-dimension** [comment]
Habe jetzt die Anzeige des Splashscreens vorgezogen, so erhält der Anwender zumindest ein Feedback dass die Anwendung startet. Wird in der finalen 1.11 enthalten sein.
