### ISSUE TITLE
Mail-Verschlüsselung ausschalten?

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#506]
Wenn ich die Mailverschlüsselung einmal angeschaltet habe, bekomme ich sie nicht mehr aus? Ei  Klick auf das Symbol öffnet wieder das Paßwortfenster und dann ist wieder verschlüsselt.

![image](https://user-images.githubusercontent.com/29924198/70631352-585fc980-1c2d-11ea-9ce1-37446b81b639.png)

**Comment by j-dimension** [comment]
Passwort rauslöschen, Okay, fertig.
