### ISSUE TITLE
Anlagen aus e-mail nachträglich abspeichern - Anzeige

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-org#509]
Wenn man eine e-mail mit Anlagen in eine Akte speichert und dann die Anlagen aus der in der Vorschau angezeigten e-mail gesondert nachträglich in die Akte kopieren will, geht dies (jede Anlage einzeln, Akte suchen, speichern) aber angezeigt werden die erfolgreich kopierent Anlagen erst, wenn man aus dem Dokumentenfenster aussteigt und wieder einsteigt / aus der Akte aussteigt und wieder einsteigt.

**Comment by j-dimension** [comment]
Erledigt für das Speichern von Anhängen aus E-Mails und beA-Nachrichten.
