### ISSUE TITLE
[e-mail] E-Mail in Akte übernehmen

### ISSUE THREAD

**Issue by Maz111111** [jlawyerorg/j-lawyer-org#511]
#509 und #510
Wenn man eine Mail und Anhang über den Button getrennt/einzeln in die Akte übernimmt, finde ich es übertrieben, wenn die übernommene Mail die Anhänge behält. Dann hat man sie doppelt.
Einmal an der Mail und dann auch noch extra übernommen.
Da ich immer wieder jpg Dateien von Mandanten erhalte, die gigantisch groß sind, ist das Platzverschwendung.

**Comment by j-dimension** [comment]
Da bin ich nicht ganz an Bord. Ein Weiterleiten würde so erschwert werden.

**Comment by Maz111111** [comment]
Das stimmt nicht ganz.
Beim Einpflegen der Mail hat man ja gerade auch die Option, die gesamte Mail einzupflegen.
Wenn ich mich bewusst dafür entscheide, dass ich Mail und Anhang separiert in der Akte haben will, bin ich bei meiner Argumentation von oben.
Die Option habe ich nicht so verstanden, dass man die Anhänge zusätzlich  - also doppelt  - in die Akte schiebt, sondern beides eben separat.

**Comment by j-dimension** [comment]
Dann würde ich fast dazu tendieren, das Feature umzubenennen und das Verhalten so zu lassen. Ich möchte im Normalfalls die Anhänge leicht zugänglich direkt in der Akte haben, aber die Option es weiterleiten zu können. 

Der Speicherplatz ist zumindest mir eigentlich (relativ) egal.

**Comment by Maz111111** [comment]
Wäre Platz für einen 5. Knopf? :-D
Du bist Bestimmer :-D

**Comment by Maz111111** [comment]
bloß mal so nebenbei. Die Option, die Du haben willst, hast Du doch, wenn Du die Mail vollständig übernimmst.
Falls man die Anhänge dann doch noch separat (doppelt) in der Akte haben will, ließe sich das ja über meinen Vorschlag aus #510 relativ komfortabel lösen.
Also...öhm...nö...ich will Bestimmer sein :-D

**Comment by j-dimension** [comment]
Ich bin aber klickfaul :-)

Ich denke das wäre ein gutes Thema für die Mailingliste, das ich aber erst aufmachen werde wenn ich beginne daran zu arbeiten. Bin kopfmäßig erstmal noch bei der Fertigstellung der 1.11.
