### ISSUE TITLE
[1.11] [beA] Anhang nach Versenden nicht zu öffnen

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#513]
![image](https://user-images.githubusercontent.com/29924198/70837788-8d267900-1e05-11ea-9b5f-80cdcb6c3b0f.png)

Ich habe eine bea-Nachricht mit Anhang aus der Akte versendet und diese dann in der Akte gespeichert. Ich konnte im Anschluß in der importierten beA-Nachricht den Anhang nicht öffnen: Er sei schon geöffnet.

a) er war nicht geöffnet
b) wenn das bei einem Dokument in der Dokumentenliste passiert, dann fragt mich j-l, ob ich die Datei trotzdem (nochmal) öffnen will

**Comment by j-dimension** [comment]
Hast Du für PDF eine externe Anwendung eingerichtet?

**Comment by stm9x9** [comment]
ja acrobat.exe mit jeweils dem Parameter DATEINAME
