### ISSUE TITLE
[e-mail] Löschen von E-Mails

### ISSUE THREAD

**Issue by Maz111111** [jlawyerorg/j-lawyer-org#514]
Wenn ich eingegangene Mails löschen will, kann ich so viele Mails auswählen, wie ich will. Es werden immer nur drei gelöscht.

Es sollten alle markierten Dateien gelöscht werden. Sonst wird man - gerade nach einem Wochenende - nie fertig. ;-)

**Comment by j-dimension** [comment]
Das kenne ich nicht, muss ich mir anschauen (wird erst morgen Abend).

**Comment by Maz111111** [comment]
Hmmm...hab es gerade noch mal versucht, jetzt ging es … eventuell doch falscher Alarm...

**Comment by Maz111111** [comment]
Ich muss das nochmal öffnen.
Eben hatte ich die Möglichkeit ausgiebig zu testen, da jL mir über Nacht wieder etliche Warnmails gesendet hat (Fehler limit)
Ich habe 7 Mails markiert - gelöscht wurden drei.
Dann habe ich die übrigen 4 markiert - gelöscht wurden 2.
Dann habe ich die 2 markiert und gelöscht wurde eine.
Sieht irgendwie nach einem System aus.
Bitte doch nochmal kontrollieren.

**Comment by j-dimension** [comment]
Ich werde versuchen das zu reproduzieren. Jegliche weitere Information würde dabei helfen, bspw.

- standen die Mails alle oben im Posteingang?
- War die Selektion ein zusammenhängender Bereich oder mehrere Einzelselektionen?
- ...

**Comment by Maz111111** [comment]
Alle sieben Mails waren im Posteingang. Es gab keine anderen Mails im Posteingang. Es wurden alle Mails im Posteingang zusammenhängend markiert.

**Comment by Maz111111** [comment]
Das muss reproduzierbar sein.
Ich habe es mit den zwischendurch eingetroffenen Mails gerade nochmals probiert.
-den gesamten Posteingang mit shift und Pfeil nach unten markiert (waren wieder sieben Mails)
-dann auf den Papierkorb geklickt 
Diesmal war es dann so dass nach dem ersten Löschen drei übrig blieben, dann zwei und dann null

**Comment by j-dimension** [comment]
Krieg ich schlicht nicht reproduziert und schiebe daher nach 1.13.
