### ISSUE TITLE
[adressen] Minderjährigkeit feststellen, darstellen und als Variable exportieren

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#515]
Mir fiel gerade wieder beim Bearbeiten einer Akte auf, daß es sehr hilfreich wäre, auf einen Blick auf die Beteiligten zu sehen, wer minderjährig ist. Wenn j-l das aus dem Geburtsdatum rausrechnen würde und dann zb so anzeigen würde mit einem U18! vorne oder hinten.

![image](https://user-images.githubusercontent.com/29924198/71025092-a893cb80-2106-11ea-80d1-05fa63882788.png)

Außerdem wäre es toll, wenn man das auch als Variable für LO/Word bekommen könnte, damit man zb beim Rubrum automatisch schreibt: Nomen Nescio, minderjährig, Musterstraße ...

**Comment by librelegal** [comment]
ur Vereinheitlichung sollte dieses issue mit einem tag zu Adressen versehen werden.
Bitte "[Adressen]" voranstellen.

**Comment by j-dimension** [comment]
![grafik](https://user-images.githubusercontent.com/3729754/86849639-41dcfc00-c0b0-11ea-9e2c-df5290aa2942.png)
