### ISSUE TITLE
Fristen und Wiedervorlagen getrennt auf Desktop anzeigen

### ISSUE THREAD

**Issue by Maz111111** [jlawyerorg/j-lawyer-org#517]
Zur Übersichtlichkeit und zur Sicherheit wäre es ganz gut, wenn man den Desktop auf der rechten Seite auch horizontal teilt und einen Teil für die Wiedervorlagen nutzt und den anderen für Fristen.
Besser sogar drei Teile damit die neu zu schaffende Vorfrist auch gesondert angezeigt werden kann.

**Comment by j-dimension** [comment]
Ich weiß nicht. Das könnte potentiell zu unübersichtlich werden, und das Teilen kostet auch wieder Fläche. 
Die Fristen haben ja schon ein rotes Icon für das Erkennen auf den ersten Blick. 

Oder ist das Problem dass durch die Menge der WV die Fristen untergehen, weil am jeweiligen Tag immer sehr viele Einträge in der Liste stehen?

Ich könnte mir vorstellen im Kopfbereich noch ein paar Angaben anzuzeigen wie bspw. 

4 Fristen und 17 Wiedervorlagen heute fällig.

**Comment by Maz111111** [comment]
Also ich habe immer diverse Wiedervorlagen am Tag und hin und wieder mal eine Frist oder auch mal zwei.
Ich weiß nicht wie das bei anderen aussieht. In der Regel überwiegen die WVs aber deutlich. In meinem Papier-Fristenkalender sind WVs, Vorfristen und tatsächliche Fristen in jeweils einer Spalte deutlich voneinander abgegrenzt. Man sieht es eben auf Anhieb. 
Sicher sind im jL die Fristen rot und man kann alles erkennen.
Es war nur eine Idee. Vielleicht wäre es auch gut Fristen im selben Fenster aber separat ganz oben und insgesamt präsenter (größere Schriftart) darzustellen.
Wenn man das WV Fenster am Abend abarbeitet und dann erst sieht, dass sich unter den 15 WVs eine mickrige Frist versteckt hat, ist das echt ärgerlich.
Ein eigenes Fenster hätte man früh gleich gesehen. 
Sicher ginge es auch mit der von Dir vorgeschlagenen Lösung eines permanenten extra Markers im Kopfbereich (Heute noch 2 Fristen zu erledigen - Mit Warnhinweis beim Schließen der KSW).

**Comment by stm9x9** [comment]
Ich denke auch, daß Fristen immer oben sein sollten. Und unter denen dann - sobald das implementiert ist - die Notfristen besonders farbig markiert.

**Comment by RA-crm** [comment]
Aus meiner Sicht reicht es aus, wenn WV und Fristenauf dem Desktop jeweils gruppiert werden (Fristen vor WV). Es müssen keine gesonderten Felder eingeführt werden. 

Viel wichtiger wäre mir, die WV/Fristen nach bestimmten Kriterien zu sortieren; etwa:
Aktenzeichen
Datum (bei überfälligen WV(n). Überfällige Fristen dürfte es nicht geben ;-)
Adressat
Alphanummerische Abfolge. 

So ist es möglich, Gruppen zu bilden; zB: 
alle WV zur Akte xy
alle WV mit dem Betreff "Akte ablegen" etc.

Notfristen werden bei mir mit einem großgeschriebnen FRIST zu Beginn des Betreffs hervorgehoben.

**Comment by Dickmaulruessler** [comment]
Auch zum Thema: https://github.com/jlawyerorg/j-lawyer-org/issues/1145
