### ISSUE TITLE
[beA] Etikett nach hinten schieben im Sendedialog

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#523]
Ich schlage vor die Etikett-Auswahl hinter Dokument speichern zu schieben:

![image](https://user-images.githubusercontent.com/29924198/71314715-cedea180-244d-11ea-95d3-415575e2b454.png)

Das mit dem Etikett macht ja nur Sinn. wenn man sich vorher entschieden hat, die Nachricht als Dokument in eine Akte zu speichern. oder? Das sollte sich dann auch optisch / im Workflow wiederfinden.

**Comment by stm9x9** [comment]
ich würde immer noch das als Dokument Speichern nach vorne bzw jetzt dadrüber ziehen und Etikett da drunter. Einfach von der logischen Reihenfolge her.

![image](https://user-images.githubusercontent.com/29924198/74761465-614bc780-527c-11ea-8691-954c11542eb9.png)

**Comment by stm9x9** [comment]
und ggf den Text aussagekräftiger machen? "Als Dokument in Akte speichern"?

**Comment by j-dimension** [comment]
> Dokument Speichern nach vorne bzw jetzt dadrüber ziehen

erledigt

**Comment by j-dimension** [comment]
> Text aussagekräftiger machen? "Als Dokument in Akte speichern"?

Zu lang. Aber längeren deskriptiven Text als Tooltip aufgenommen.

**Comment by stm9x9** [comment]
zu lang? Ist doch immer noch kürzer als "Etikett mit Auswahlfeld"?
