### ISSUE TITLE
Dokument erstellen im übergroßen fullscreen

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#524]
Eine Nebenwirkung des fullscreen-beim-Start? Wenn ich ein neues Dokument erstellen will dann ist das Vorlagenfenster immer im übergroß, so daß Speichern unten nicht mehr im Bildschirm sind:

![image](https://user-images.githubusercontent.com/29924198/71328094-7ec91300-2511-11ea-869d-fc7a797a23b7.png)

**Comment by j-dimension** [comment]
Bitte nochmal den eben hochgeladenen Client-Installer laufen lassen und damit erneut prüfen. Danke!

**Comment by stm9x9** [comment]
gelöst
