### ISSUE TITLE
Fristen und Wiedervorlagepläne anlegen

### ISSUE THREAD

**Issue by PBaumfalk** [jlawyerorg/j-lawyer-org#526]
Könnte man nicht auch einen Fristenplan einfügen? Dann kann man insbesondere beim Forderungsmanagement die Fristen direkt automatisiert einfügen.

**Comment by j-dimension** [comment]
Kannst Du irgendwie genauer beschreiben, was hier gefordert wäre?

**Comment by PBaumfalk** [comment]
Die Idee hat sich in meiner täglichen Arbeit mit der Eintreibung von Rechnungen herauskristallisiert:

Mandant beauftragt mich mit der Beitreibung der Forderung --> Anwaltliches Aufforderungsschreiben - Zahlungsfrist=10 Tage (also erste Wiedervorlage lege ich händisch an, 11 Tage ab Versendung des Schreibens).

Automatisch müsste ab dann folgendes kommen: Wiedervorlage -> Mahnverfahren einleiten 11. Tag --> Nach vier Wochen dann "Klage einreichen".

Das ganze lässt sich auf einige andere Fragestellungen auch übertragen, z.B. Akteneinsicht beantragen --> WV 2 Wochen --> Erinnerung --> Klage

oder:

Frist: Berufungsbegründung (hier müsste das Programm dann Rückwärts eine Vorfrist eintragen).

Also letztlich, ob man eine Folge von Wiedervorlagen bzw. Fristen einfügen kann.

**Comment by j-dimension** [comment]
Hört sich schwer nach #84  an.

**Comment by PBaumfalk** [comment]
Das ist #84 

Habe nicht gesehen, dass das schon jemand vorgeschlagen hatte. Ich sende dir mal eine Liste mit allen Fristen zu. Setze ich dann in #84 ein. Meine Refa habe ich sowieso gezwungen, diese Liste auswendig zu lernen ;)

**Comment by j-dimension** [comment]
Duplikat von #84
