### ISSUE TITLE
Anzeigenamen als Attribut am Nutzer aufnehmen und als Platzhalter bereitstellen

### ISSUE THREAD

**Issue by PBaumfalk** [jlawyerorg/j-lawyer-org#528]
Zur Verwendung in Dokumenten würde ich gerne den Namen des Sachbearbeiters als Alias einbinden. Mein Benutzername ist eine Buchstaben und Zahlenkombination und das kann ich nicht in die Dokumente setzen. Gibt es eine Möglichkeit?

**Comment by j-dimension** [comment]
Ja, es gibt einen Platzhalter dafür:

https://www.j-lawyer.org/downloads/documentation/j-lawyer.org-UserGuide-de.html#__RefHeading__273_1146603382

**Comment by PBaumfalk** [comment]
Ich glaube, dass das bisher noch nicht richtig angekommen ist, daher erlaube ich mir nochmals dieses Thema zu öffnen:

Die Benutzernamen in meinem j-lawyer heißen bspw. Patrick.Baumfalk

Wenn ich nunmehr den Nutzernamen in das Dokument eintrage, dann erscheint dort Patrick.Baumfalk

Ich würde allerdings gerne einen anderen Namen dort eintragen z.B. Baumfalk, oder auch Patrick Baumfalk.

Das bedeutet, dass ich im Feld außer den Nutzernamen noch ein weiteres Feld für den Nutzer bräuchte, nämlich "Name" oder "Anzeigename".

Gerne zeige ich das Problem auch nochmal im anydesk....

Geht das?

**Comment by PBaumfalk** [comment]
Wichtig ist hier, dass meine Benutzernamen eben keine Leerzeichen aufweisen oder gar ganz andere zahlen oder zifferkombinationen sind.

**Comment by j-dimension** [comment]
Das ist nachvollziehbar und benötigt keine Erläuterung via AnyDesk :-).  Ich öffne das Ticket wieder und benenne es entsprechend um, damit klar wird was hier gemeint ist.

**Comment by j-dimension** [comment]
Nutzerverwaltung hat nun an jedem Nutzer ein Attribut "Anzeigename".

Es gibt folgende neue Platzhalter:
- AKTE_ANWALT_AN: Anzeigename des Anwalts
- AKTE_SACHBEARBEITER_AN: Anzeigename des Sachbearbeiters
- AUTOR_AN: Anzeigename des aktuell angemeldeten Nutzers (also der Person, welche das Dokument oder die Nachricht erstellt)

**Comment by j-dimension** [comment]
offen: Platzhalter in Dokumentation aufnehmen

**Comment by j-dimension** [comment]
![grafik](https://user-images.githubusercontent.com/3729754/105612815-a480b580-5dbe-11eb-9241-943e3cce612a.png)

**Comment by Linkki2021** [comment]
Da ich glaube, dass es zu dem Thema am besten passt und ich anderweitig bislang nicht fündig geworden bin: gibt es einen Platzhalter, um den Anzeigenamen des Nutzers und nicht des Sachbearbeiters in Dokumente zu bekommen? 
Also die Akte "gehört" eigentlich Sachbearbeiter 1. Sachbearbeiter 2 erstellt nun aber ein Schriftstück, wegen Vertretung oder weil bestimmte Aufgaben von bestimmten Spezialisten erledigt werden. Gibt es einen Platzhalter, der dafür sorgt, dass irgendwo im Dokument "Sachbearbeiter 2" steht?

**Comment by j-dimension** [comment]
@Linkki2021 das sollte

`{{AUTOR_AN}}`

sein.

Grüße!

**Comment by j-dimension** [comment]
(Der Anzeigename des Autors des Dokuments)

**Comment by Linkki2021** [comment]
Danke! Und Pardon, ich hatte das in der Dokumentation trotz mehrmaliger Sichtung tatsächlich übersehen.
