### ISSUE TITLE
Icons in Seitenleiste ausdifferenzieren

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#529]
Ich fände es schön, wenn man schon mit einem Blick ohne Lesen am Icon erkennt, was der Button macht. Klar, beim ersten Mal wird man lesen müssen, aber wenn man eingeübt ist, dann könnte das das Arbeiten schneller und intuitiver machen.

![image](https://user-images.githubusercontent.com/29924198/71454078-39197e00-278f-11ea-958f-01c1635d39c9.png)

Im wesentlichen habe ich als Vorschlag den bestehenden Icons Ergänzungen hinzugefügt: ein + für "neu erstellen", ein @ für Mail, eine Lupe bei allem mit suchen, bei Wissen ein Symbol, welche Suche dahinter steht: in Dokumenten, in §§ für Gesetzte und Urteile .... Bei den Adressen würde man wohl den Kopf wegnehmen müssen, aber IMHO steht das Karteikarten-Symbol schon für sich.

Ach ja, bei drebis dann den Schriftzug rein und bei den fälligen Fristen könnte ein ! (ggf rot?) rein als Achtung-Symbol.

**Comment by j-dimension** [comment]
Das kann gern jemand übernehmen, mir ist es gerade zu viel Aufwand, bzw. zu schlechtes Aufwand/Nutzen-Verhältnis.

Icons erstellen ist einfach zeitraubend. Ich hänge hier mal ein Beispiel an. Die Anforderungen sind:

- Hintergrund transparent
- PNG-Format
- jeweils in Farben RBG 222,49,59 / 151,191,13 / 14,114,181 / 14,114,181
- jede Farbvariante in Auflösungen 128px / 32px / 20px / 16px 

Also pro Icon 16 Varianten.

![encrypted](https://user-images.githubusercontent.com/3729754/71489549-62d1b400-2826-11ea-880f-6614ad5c6b47.png)

**Comment by PBaumfalk** [comment]
Würde ich machen. Kannst du mir die Icons als Zip per Mail senden?

**Comment by j-dimension** [comment]
@PBaumfalk 

[material.zip](https://github.com/jlawyerorg/j-lawyer-org/files/4006194/material.zip)

Anbei die Modul-Icons in 32px-Auflösung. Die 128px-Auflösung könnte man erstmal weglassen.

**Comment by PBaumfalk** [comment]
Erledigt. Als Preview mal die blaue Farbvariante. Anhang ist im nächsten Post. Übrigens: In deinem Post sind zwei RGB-Farben gleich: jeweils in Farben RBG 222,49,59 / 151,191,13 / **14,114,181 / 14,114,181**

![Icons-01](https://user-images.githubusercontent.com/50404378/71543201-25c60880-2971-11ea-9d6b-f17ffdb20f20.png)
![Icons-02](https://user-images.githubusercontent.com/50404378/71543202-25c60880-2971-11ea-9a15-26edbe0e210c.png)
![Icons-03](https://user-images.githubusercontent.com/50404378/71543203-265e9f00-2971-11ea-8445-a75693a8194a.png)
![Icons-04](https://user-images.githubusercontent.com/50404378/71543204-265e9f00-2971-11ea-82e7-a70c4186e892.png)
![Icons-05](https://user-images.githubusercontent.com/50404378/71543205-265e9f00-2971-11ea-8741-fa7668e0c22c.png)
![Icons-06](https://user-images.githubusercontent.com/50404378/71543206-265e9f00-2971-11ea-9a92-6182231f330c.png)
![Icons-07](https://user-images.githubusercontent.com/50404378/71543207-265e9f00-2971-11ea-801f-cd953ade1f45.png)
![Icons-08](https://user-images.githubusercontent.com/50404378/71543208-26f73580-2971-11ea-83bc-b10266e9e38b.png)
![Icons-09](https://user-images.githubusercontent.com/50404378/71543209-26f73580-2971-11ea-8055-88ec04632f55.png)
![Icons-10](https://user-images.githubusercontent.com/50404378/71543210-26f73580-2971-11ea-8d15-95b4136119ce.png)
![Icons-11](https://user-images.githubusercontent.com/50404378/71543211-26f73580-2971-11ea-9210-7d8ec7006fbe.png)
![Icons-12](https://user-images.githubusercontent.com/50404378/71543212-26f73580-2971-11ea-8973-83363297101e.png)
![Icons-13](https://user-images.githubusercontent.com/50404378/71543214-278fcc00-2971-11ea-87c5-6dd5538acfdb.png)
![Icons-14](https://user-images.githubusercontent.com/50404378/71543215-278fcc00-2971-11ea-8c7a-e8d5f72a56ad.png)
![Icons-15](https://user-images.githubusercontent.com/50404378/71543216-278fcc00-2971-11ea-8824-7ac5fb36054c.png)
![Icons-16](https://user-images.githubusercontent.com/50404378/71543217-278fcc00-2971-11ea-9e9a-d32246e1693b.png)
![Icons-17](https://user-images.githubusercontent.com/50404378/71543218-278fcc00-2971-11ea-86b5-0169e52d1606.png)
![Icons-18](https://user-images.githubusercontent.com/50404378/71543219-28286280-2971-11ea-839d-c2cd58d1c6a7.png)
![Icons-19](https://user-images.githubusercontent.com/50404378/71543220-28286280-2971-11ea-9769-d483f29e52ef.png)
![Icons-20](https://user-images.githubusercontent.com/50404378/71543221-28286280-2971-11ea-9d31-a4ce08ffe01c.png)
![Icons-21](https://user-images.githubusercontent.com/50404378/71543222-28286280-2971-11ea-9863-3db7b343f34e.png)
![Icons-22](https://user-images.githubusercontent.com/50404378/71543223-28286280-2971-11ea-92ef-58970dadd42d.png)
![Icons-23](https://user-images.githubusercontent.com/50404378/71543225-28c0f900-2971-11ea-80e8-84acac66f811.png)
![Icons-24](https://user-images.githubusercontent.com/50404378/71543226-28c0f900-2971-11ea-8e03-b5f482f6699d.png)
![Icons-25](https://user-images.githubusercontent.com/50404378/71543227-29598f80-2971-11ea-83f0-af2aae5fe4f4.png)
![Icons-26](https://user-images.githubusercontent.com/50404378/71543228-29598f80-2971-11ea-9550-96c03f9c215c.png)
![Icons-27](https://user-images.githubusercontent.com/50404378/71543229-29598f80-2971-11ea-9138-60665fb86271.png)
![Icons-28](https://user-images.githubusercontent.com/50404378/71543230-29598f80-2971-11ea-9082-a128e7a109cb.png)
![Icons-29](https://user-images.githubusercontent.com/50404378/71543231-29f22600-2971-11ea-886b-9a17d6893199.png)
![Icons-30](https://user-images.githubusercontent.com/50404378/71543232-29f22600-2971-11ea-973a-9b9e341e915c.png)

**Comment by PBaumfalk** [comment]
@j-dimension 

Alle Farbvarianten und alle Größen + Illustrator Datei
[material.zip](https://github.com/jlawyerorg/j-lawyer-org/files/4006993/material.zip)

**Comment by stm9x9** [comment]
Super!

Kannst du dir nochmal Fristen suchen und UG angucken?

Fristen suchen: Das Lupenglas zentrieren statt die ganze Lupe. Aktuell wirkt es zu sehr linksfokusiert.
UG: UG finde ich etwas wenig-sagend. Kannst Du es nochmal mit zwei §§ versuchen?

Ach und Fristen: ohne - das X ist in der Strichstärke wesentlich stärker als das ! im Kreis und die Lupe.

**Comment by j-dimension** [comment]
@PBaumfalk  hab vielen Dank, das schaut gut aus!

> In deinem Post sind zwei RGB-Farben gleich: jeweils in Farben RBG 222,49,59 / 151,191,13 / **14,114,181 / 14,114,181**

Stimmt, das ist ein Copy&Paste-Fehler. Die letzte Farbe ist weiß (für die Fälle wo Icons auf dunklem Hintergrund dargestellt werden müssen)

**Comment by PBaumfalk** [comment]
Ich habe die Icons überarbeitet anbei die überarbeite Variante. Im nächsten Post dann auch die Material.zip (diesmal ist auch weiß dabei):
![Icons2-01](https://user-images.githubusercontent.com/50404378/71558622-c130a980-2a55-11ea-89cf-f5a6b68a34c2.png)
![Icons2-02](https://user-images.githubusercontent.com/50404378/71558624-c1c94000-2a55-11ea-8b39-c600f31a5838.png)
![Icons2-03](https://user-images.githubusercontent.com/50404378/71558625-c1c94000-2a55-11ea-98aa-35675eab66d3.png)
![Icons2-04](https://user-images.githubusercontent.com/50404378/71558626-c1c94000-2a55-11ea-94e7-7e40288d8269.png)
![Icons2-05](https://user-images.githubusercontent.com/50404378/71558627-c1c94000-2a55-11ea-912c-ed809b5b5a32.png)
![Icons2-06](https://user-images.githubusercontent.com/50404378/71558628-c1c94000-2a55-11ea-9d6c-63a08de34e73.png)
![Icons2-07](https://user-images.githubusercontent.com/50404378/71558629-c261d680-2a55-11ea-91a1-4b8c1fcf3937.png)
![Icons2-08](https://user-images.githubusercontent.com/50404378/71558630-c261d680-2a55-11ea-8fa9-71d46dc7b7fd.png)
![Icons2-09](https://user-images.githubusercontent.com/50404378/71558631-c261d680-2a55-11ea-8603-176ae27834f1.png)
![Icons2-10](https://user-images.githubusercontent.com/50404378/71558632-c261d680-2a55-11ea-8a5a-d28e28e1235b.png)
![Icons2-11](https://user-images.githubusercontent.com/50404378/71558633-c261d680-2a55-11ea-84da-cd2761af27bc.png)
![Icons2-12](https://user-images.githubusercontent.com/50404378/71558634-c2fa6d00-2a55-11ea-8b1d-d4a963bb82b6.png)
![Icons2-13](https://user-images.githubusercontent.com/50404378/71558635-c2fa6d00-2a55-11ea-9148-9bc963b70f1d.png)
![Icons2-14](https://user-images.githubusercontent.com/50404378/71558636-c2fa6d00-2a55-11ea-91f4-9ad02f85e47d.png)
![Icons2-15](https://user-images.githubusercontent.com/50404378/71558637-c2fa6d00-2a55-11ea-8d2b-be7a4ea478fc.png)
![Icons2-16](https://user-images.githubusercontent.com/50404378/71558638-c3930380-2a55-11ea-8992-762f8864f3a3.png)
![Icons2-17](https://user-images.githubusercontent.com/50404378/71558639-c3930380-2a55-11ea-82af-10c0d842d96c.png)
![Icons2-18](https://user-images.githubusercontent.com/50404378/71558640-c3930380-2a55-11ea-9c7b-67da62b18f7e.png)
![Icons2-19](https://user-images.githubusercontent.com/50404378/71558641-c3930380-2a55-11ea-8d7f-57bff1e7f68a.png)
![Icons2-20](https://user-images.githubusercontent.com/50404378/71558642-c3930380-2a55-11ea-8e01-a27986d36185.png)
![Icons2-21](https://user-images.githubusercontent.com/50404378/71558643-c42b9a00-2a55-11ea-90f7-e7e6f448f9b3.png)
![Icons2-22](https://user-images.githubusercontent.com/50404378/71558644-c42b9a00-2a55-11ea-89df-fc72627dd349.png)
![Icons2-23](https://user-images.githubusercontent.com/50404378/71558645-c42b9a00-2a55-11ea-9f4d-f7fd7b0ab085.png)
![Icons2-24](https://user-images.githubusercontent.com/50404378/71558646-c42b9a00-2a55-11ea-9b6f-719508ae1822.png)
![Icons2-25](https://user-images.githubusercontent.com/50404378/71558647-c42b9a00-2a55-11ea-8b4a-e3ddd502390e.png)
![Icons2-26](https://user-images.githubusercontent.com/50404378/71558648-c4c43080-2a55-11ea-8023-bc7ad6992c1b.png)
![Icons2-27](https://user-images.githubusercontent.com/50404378/71558649-c4c43080-2a55-11ea-9c6f-cffa34807122.png)
![Icons2-28](https://user-images.githubusercontent.com/50404378/71558650-c4c43080-2a55-11ea-9615-8512e68873d7.png)
![Icons2-29](https://user-images.githubusercontent.com/50404378/71558651-c55cc700-2a55-11ea-9f32-4f7faff1f5b8.png)
![Icons2-30](https://user-images.githubusercontent.com/50404378/71558652-c55cc700-2a55-11ea-9227-c1098183b18f.png)

**Comment by PBaumfalk** [comment]
[Material2.zip](https://github.com/jlawyerorg/j-lawyer-org/files/4008194/Material2.zip)

**Comment by j-dimension** [comment]
Große Klasse, @PBaumfalk !

Eingebaut: 

![grafik](https://user-images.githubusercontent.com/3729754/71562846-70857480-2a86-11ea-90cc-44e11dc353c0.png)

**Comment by librelegal** [comment]
Super, das gefällt mir. Danke.
