### ISSUE TITLE
Nutzer ausblenden oder deaktivieren

### ISSUE THREAD

**Issue by j-dimension** [jlawyerorg/j-lawyer-org#53]
Moin,
im Programm werden einem unter "Anwalt" und "Sachbearbeiter" immer alle angelegten Nutzer angeboten.
Ist es möglich, in der Nutzerverwaltung die Option einzurichten, das Nutzer im Programmbetrieb ausgeblendet werden?
Das hätte den Vorteil, dass man sie nicht löschen muss und etwa auf die Nutzer angelegte Akten / Wiedervorlagen / Fristen etc archivieren kann, wenn der Nutzer mal ausscheidet.

- [x] ClientSettings stellen mehrere Nutzerlisten bereit: alle und alle mit Loginrecht
- [x] Aktenansicht: Dropdowns für Anwalt / Sachbearbeiter / Verantwortliche einer WV / weitere werden nur mit den Nutzern befüllt, die ein Loginrecht haben
- [x] bei Laden einer Akte prüfen, ob noch Nutzer ohne Loginrecht verwendet werden und diese ggf. in die Dropdowns aufnehmen. populateOptions wird diese dann beim nächsten Aktenladen wieder rauswerfen, falls nicht benötigt.

**Comment by j-dimension** [comment]
Nutzer ohne Loginrecht nicht in Dropdowns aufnehmen. Vorhandene Daten mit diesem Nutzer sollen nicht angepasst werden und müssen auch noch den inaktiven Nutzer darstellen.

**Comment by j-dimension** [comment]
@RA-crm

**Comment by RA-crm** [comment]
Ich hatte gehofft, dass das schon mit der 1.12 erledigt wird. Warte nun auf die 1.13 
;-)
