### ISSUE TITLE
e-mail - pdf aus Akte anhängen und nochmals ansehen vor Versendung

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-org#533]
Erst einmal einen herzlichen Dank von für die neue Version und die viele Arbeite bis dahin. Erleichtert an mancher Stelle den Workflow. Aber nach dem Update ist vor dem update:.... Super, man kann jetzt Dateien aus der aktiven Akte nachträglich an eine e-mail anhängen. Aber die angehängten Dateien werden unterschiedlich behandelt. Das soll heißen. Wenn ich eine Datei zur e-mal-Versendung anhänge kann ich sie im E-mailfenster nochmals öffnen und auf den Inhalt kontrollieren. Aber wenn ich z.B. ein PDF nachträglich anhängen will, geht das zwar, aber man kann das PDF dann nicht zur Kontrolle öffnen

**Comment by j-dimension** [comment]
Kann ich nicht reproduzieren. Bitte erneut Ausführen und anschließend das client.log senden.

**Comment by Mucki526** [comment]
Hallo, ich habe es jetzt mal ein paar Dateien umgewandelt und dann selbst aktiv versucht, den Fehler zu reproduzieren. Er ist so nicht wieder aufgetaucht. Ich beobachte das mal weiter, aber vielleicht saß da nur etwas "quer" in meinem Rechner, dass dieses Fehlverhalten provoziert hat....

**Comment by j-dimension** [comment]
Danke für die Rückmeldung!
