### ISSUE TITLE
Fehlermeldung beim Arbeiten mit Dateien (bereits geöffnet)

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-org#534]
Seit dem Update meldet j-lawyer nach dem Schließen einer bearbeiteten odt - Datei (andere Dateien habe ich noch nicht gestestet), bei einem Neuöffnen des Dokuments, es sei bereits geöffnet. Wenn man es dann trotzdem öffnet, dauert das sehr lange. Dann kann man das Dokument bearbeiten und die Änderungen werden wohl richtig abgespeichert, die Fehlermeldung bleibt beim nächsten Öffnen aber...

**Comment by librelegal** [comment]
Habe das auf einem Ubuntu 18.04 j-lawyer Server und einem debian 10 (buster) client probiert und kann bestätigen, dass die odt-Datei nach dem Schließen bei Wiederöffnen als bereits geöffnet bezeichnet wird und man eine Warnung erhält. Beim Klicken auf Öffnen, hat das aber nicht lange gedauert. Etwas länger hat es (nach Schließen von LibreOffice Version: 6.1.5.2,  Build-ID: 1:6.1.5-3+deb10u5) beim zweiten Öffnen gedauert, immer noch nicht lang. Es scheint nach mehreren Tests nicht darauf anzukommen, ob man nur das Dokument schließt oder auch LibreOfice selbst.

Nehme ich eine txt-Datei, die automatisch ebenfalls mit LibreOffice geöffnet wird, passiert dasselbe

**Comment by j-dimension** [comment]
Der relevante Code wurde zuletzt am 20.07. geändert, also vor dem Release der 1.10 - im Rahmen der 1.11 gab es keine Anpassungen. 

Die MAXIMALE Dauer die man warten muss, bevor ein gerade geschlossenes Dokument wieder geöffnet werden kann, beträgt 5s plus etwas Overhead für das Schliessen von LibreOffice. 

Sollte es ein grundsätzliches Problem geben, dann bitte nochmal aufmachen und client.log zur Verfügung stellen.
