### ISSUE TITLE
openjur.de einbinden

### ISSUE THREAD

**Issue by PBaumfalk** [jlawyerorg/j-lawyer-org#536]
www.openjur.de

Es ist wohl eine API vorhanden und es handelt sich um eine Rechtsprechungsdatenbank mit über 450.000 Datensätzen.

**Comment by librelegal** [comment]
Gute Idee, finde aber die API nicht bei openjur.de dokumentiert

**Comment by PBaumfalk** [comment]
Habe den Jungs eine eMail geschrieben. Vielleicht meldet sich jemand.

**Comment by j-dimension** [comment]
@PBaumfalk und @librelegal , ich mache mir da wenig Hoffnung. Ich hatte in Vergangenheit wiederholt versucht, die Datenbank einzubinden, und hatte auch Kontakt zum Gründer des Projektes. Es ist letzlich an der Unterstützung gescheitert. Ob es eine API wirklich gibt, weiß ich nicht.

Ich lasse das Ticket offen, in der j-lawyer.org 1.12. Wenn es bis zum Ende dieser Version keinen Fortschritt gibt, schliesse ich es.

**Comment by j-dimension** [comment]
Sollte es eine Rückmeldung gegeben haben, das Ticket gern wieder aufmachen.
