### ISSUE TITLE
Farbe des Focus bei Dateiliste

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-org#537]
Wenn man das erste Mal in den Dokumentenordner einsteigt ist die markierte Zeile (typischerweise die oberste) Hellgrau mit weißer Schrift (Schlecht zu lesen). Wenn man dann in den Zeilen mit dem Focus rauf und runter geht, ist er blau mit weißer Schrift, auch in der vormals grauen Zeile. blau mit weißer Schrift - gut zu lesen. Wenn man dann aus dem Ordner raus und wieder reingeht, ist die erste Zeile wieder grau. Das sollte IMHO einheitlich blau sein...

**Comment by j-dimension** [comment]
https://github.com/JFormDesigner/FlatLaf/blob/master/flatlaf-core/src/main/java/com/formdev/flatlaf/ui/FlatTableUI.java
