### ISSUE TITLE
Schriftgröße seitliche Leiste

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-org#538]
Die Schriftgröße der seitzlichen Leiste ist für meine alten Augen trotz Brille zu klein - das läßt sich aber über die Schriftgrößeneinstellungen nicht veränderrn :-(.

**Comment by j-dimension** [comment]
Bin mir nicht sicher was ich hier tun sollte. 

Schrift vergrößern --> Seitenleiste braucht zu viel Platz
Schrift unterhalb des Icons --> Seitenleiste müsste gescrollt werden, weil sie vertikal zu viel Platz braucht

Ich lasse das Ticket für die 1.12 offen, evtl. hat noch jemand eine Idee.

**Comment by PBaumfalk** [comment]
Hallo zusammen,

Die Einstellungen ganz unten oben in die Reiter packen (so oft braucht man da jetzt keinen Zugriff drauf) und die Kategorien vorher benennen und dann nur die einzelne Funktion in die Seitenleiste. Tooltipp natürlich komplett. Sieht dann so aus:

![Vorschlag](https://user-images.githubusercontent.com/50404378/71545343-4e0e3100-298a-11ea-84d1-927fc860d8ef.jpg)

**Comment by Mucki526** [comment]
Um die Buchstaben ist noch genug Platz für 2 pt groessere Schrift. Wer nen groessere Bildschirm hat de stört doch auch eine 5 mm groessere Seitenleiste nicht.... Von meinem Huawei-Telefon gesendet-------- Ursprüngliche Nachricht --------Betreff: Re: [jlawyerorg/j-lawyer-org] Schriftgröße seitliche Leiste (#538)Von: Jens Kutschke An: jlawyerorg/j-lawyer-org Cc: Mucki526 ,Author Bin mir nicht sicher was ich hier tun sollte.

Schrift vergrößern --> Seitenleiste braucht zu viel Platz

Schrift unterhalb des Icons --> Seitenleiste müsste gescrollt werden, weil sie vertikal zu viel Platz braucht

Ich lasse das Ticket für die 1.12 offen, evtl. hat noch jemand eine Idee.
