### ISSUE TITLE
update putty 0.70 --> 0.73 

### ISSUE THREAD

**Issue by librelegal** [jlawyerorg/j-lawyer-org#539]
Im Ordner j-lawyer-box\j-lawyer-share\j-lawyer-client findet sich nach Neuinstallation von j-lawyer 1.11.02 eine putty.exe mit der Version 0.70. Aktuell ist aber 0.73, released on 2019-09-29, vgl. https://www.chiark.greenend.org.uk/~sgtatham/putty/latest.html

**Comment by j-dimension** [comment]
Da es ein j-lawyer.BOX-Thema ist, transferiere ich in ein anderes Repo.
