### ISSUE TITLE
Anbindung e-POST

### ISSUE THREAD

**Issue by j-dimension** [jlawyerorg/j-lawyer-org#54]
​https://www.deutschepost.de/de/e/e-post/gk/partner/business-api.html
https://api.epost.docuguide.com/faq

- [x] API: SMS request
- [x] API: Passwort setzen / neu setzen
- [x] API: Login
- [x] API: Health Check
- [x] API: Sendungsvalidierung (Format Briefkopf)
- [x] API: Sendungsabfrage 
- [x] API: Abfrage Testsendung
- [x] API: Statusabfrage
- [x] API: Einliefern einer herkömmlichen Sendung
- [x] API: Einliefern eines Einschreiben
- [x] Server: Services für jeden API-Endpunkt
- [x] Server: VendorID anders speichern (aktuell VoipService)
- [x] Server: Datenmodellerweiterung - ePost-Zugang an jedem Nutzer
- [x] Server: Datenmodellerweiterung - Queue-Eintrag für eingelieferte Schreiben
- [x] Server: Thread der Queue-Statusinformationen zyklisch aktualisiert
- [x] UI: Registrierung API-Nutzer
- [x] UI: Preprocessing (PDFs mergen etc.)
- [x] UI: Einstellungen Vendor ID, Kundennummer
- [x] UI: Statusanzeige analog Sipgate-Fax
- [x] UI: Aktionen in Statusanzeige: bestätigen, löschen, Dokumentanzeige etc. - inkl. enablen / disablen je nach Typ
- [x] UI: Dokument als Brief senden (inkl. Varianten wie Einschreiben etc.)
- [x] UI: Wizard - Versand als separaten letzten Schritt
- [x] UI: Detailinfos in der Statusliste je nach Typ (Sipgate, E-POST)
- [x] UI: gesendetes Dokument zur Akte speichern
- [x] UI: Dokument validieren lassen, Ergebnis anzeigen
- [x] UI: Vorlage validieren lassen, Ergebnis anzeigen
- [x] UI: Briefkopf validieren lassen, Ergebnis anzeigen
- [x] UI: für Briefe den Empfänger im Statuspanel anzeigen

Vorerst nicht:

Terminieren des Versands, Abbrechen oder Vorziehen terminierter Sendungen

**Comment by stm9x9** [comment]
andere Kandidaten wären noch 

https://www.letterxpress.de/briefe-uebertragen/api
https://www.onlinebrief24.de/leistungen/sftp-schnittstelle/

**Comment by j-dimension** [comment]
@stm9x9 sehr cool! Onlinebrief wäre praktisch mit Aufwand von 1h anzubinden. Leider teurer als Letterexpress.

**Comment by stm9x9** [comment]
Allerdings nicht wesentlich teurer und noch günstiger als ePOST. Allerdings habe ich mich bislang nicht damit befaßt, weil deren Client schlecht ist und das Anfügen von Anlagen sehr unkomfortabel ist. Aber vermutlich geht das mit einer API eh einfacher.

Letterexpress hat doch aber auch eine API`?

**Comment by stm9x9** [comment]
Letterexpress hat aus meiner Sicht jetzt leider einen entscheidenden Nachteil, der es für viele Anwälte unnutzbar macht:

Man kann Anlagen an den Brief nur anfügen, wenn sie EXAKT DIN A4 sind. Bei meinem Scanner bin ich mir nicht ganz sicher, der scheint bei ungünstiger Vorlage auch mal ein pdf mit leicht abweichenden mm zu erzeugen. Wirklich schlimm sind in dieser Hinsicht aber Gerichte oder Behörden. Ich bekomme ja vom Gericht die Schreiben der Gegenseite, zumeist noch eingescannt. Die sind alles, nur kein sauberes A4. Also kann ich sie so nicht an letterexpress anhängen. Bei der API wird das wohl genau so sein.

Daher gibt es aus meiner Sicht für letterxpress nur eine Chance, wenn j-l vor dem Anhängen jeden Anhang in ein sauberes A4 pdf konvertiert. Wobei, das könnte vielleicht sogar gar nicht so schwer sein?

Ansonsten bleibt nur Onlinebrief, die auch nicht sooo viel teurer sind. Und wenn der Aufwand da nur 1h wäre :-D ...

**Comment by stm9x9** [comment]
Ich würde das gerne nochmal aus der Versenkung holen :-)

Ich habe da eine Idee wie man vielleicht mit diversen Anbietern mit unterschiedlichen APIs oder Hochladeoptionen umgehen könnte. Und es würde ein einheitliches Handling ermöglichen:

man nutzt - auch wenn vorhanden - nicht die Möglichkeiten des Anbieters, Brief und Anhänge getrennt zu übergeben und vom Anbieter nötige leere (Rück)Seiten zu generieren, wenn man doppelseitig wählt. j-l müßte das im Vorfeld selber machen. 

also:

# Zusammenstellung

Man wählt das Hauptschreiben in der Akte aus und im Kontextmenü: ePost

Dann gibt es ein Auswahlfenster (wie zb bei der beA-Dateiauswahl), wo man aus der Akte, vom Rechner (und ggf sogar aus anderer Akte?)) weitere Dokumente hinzufügt.

Dann hat meine eine Liste der Anhänge (nicht das Briefdokument) und kann die in der Reihenfolge ändern.

# Briefeinstellungen

Dann wählt man einseitig oder doppelseitig. Und ob kleine Dokumente auf A4 vergrößert werden sollen. Und ob bei doppelseitigem Versand jeder Anhang auf einem neuen Blatt beginnen soll. Und ob ein C4-Umschlag genutzt werden soll.

und auch welchen Anbieter man nutzen will (nur die in den Einstellungen mit Daten hinterlegten hier anzeigen!)

Der Clou wäre dann noch, wenn j-l (unverbindlich!) ausrechnen würde, was das jeweils doppelseitig, neues Blatt ja/nein etc kosten würde. Da würde ich mir die Preisgestaltung auch mal angucken und Kostenalgorithmen erstellen.

# pdf-Erzeugung

So oder so, j-l packt jetzt alle Dokumente in ein pdf zusammen und sorgt dabei dafür, daß es immer saubere A4-Seiten sind. Immer. Alle. Notfalls verkleinern, ggf auch vergrößern. Das behebt alle Probleme mit letterxpress.

Wenn doppelseitig gewählt wurde, dann erhält jedes Dokument mit ungerader Seitenanzahl eine Leerseite ans Ende, damit neue Anhänge auf neuer Seite anfangen. **wenn gewünscht**

Das fertige Gesamtdokument wird dann mit der entsprechenden Einstellung doppelseitig/einseitig über die Schnittstelle übergeben. Voila! :-)

**Comment by j-dimension** [comment]
#83 nennt noch postbode.nu oder confidencepost.de

**Comment by hackvokat** [comment]
Ich versende auch über EPOST und lade die PDFs auf einen FTP-Server der Post hoch.
Dort kann man verschiedene Versandarten festlegen, z.B. duplex in Farbe und für jede Versandart gibt es einen Ordner in dem FTP-Server-Verzeichnis. D.h. ein einfacher FTP-Upload mit Auswahl der dort vorhandenen Server wäre möglich.

EPost würde ich schon wegen des Preises den anderen Anbietern vorziehen.

Bei mir sieht das so aus:![Bildschirm­foto 2022-11-04 um 11 16 53](https://user-images.githubusercontent.com/98764663/199949295-767847a0-b34c-4223-87ae-b2c27912ae73.png)

**Comment by stm9x9** [comment]
Ist EPost wirklich günstig? Als ich mich letztlich für confidencepost.de entschieden hatte, waren die erkennbar günstiger. Und - wie ist das bei EPost? - aus deren Preisen kann man USt ziehen.

**Comment by hackvokat** [comment]
Bei EPost für Geschäftskunden wird alles inkl. 19% MwSt. berechnet. 

https://www.deutschepost.de/de/e/epost/geschaeftskunden/preise.html

Ich habe den Tarif Basis (ohne Grundgebühr): https://www.deutschepost.de/content/dam/dpag/images/E_e/epost/downloads/gk/epostmailer/dp-epost-preisliste-mailer-basis-012022.pdf

Da zahlt man z.B. für einen einseitigen Brief 67cent netto (also inkl. Porto und Druck) und für jede weitere Seite in diesem Brief 4ct netto.

Bei confidencepost kostet das gleiche 80ct.

**Comment by stm9x9** [comment]
Ui. Haben die derart die Preise gesenkt? Ich hatte damals eine Tabelle mit diversen Anbietern gemacht und da steht für ePost zb 99 cent für den Standardbrief mit einer Seite drin 8-o Da muß ich dann mir den EPost Mailer mal anschauen.

Was genau nutzt du denn da? Du schreibst: 

> Ich versende auch über EPOST und lade die PDFs auf einen FTP-Server der Post hoch. 

ist das die Postbox? Oder der EPOST Mailer? Es gibt ja auch eine API die j-l einbauen könnte, aber da muß man sich wohl dauerhaft kostenpflichtig registrieren?

**Comment by hackvokat** [comment]
Ich kann mir irgendwie nicht vorstellen, dass gerade die Post Preise senken würde ;-)

Ich habe einen Account bei dem E-Post Mailer und dort über WebDav (sorry, doch nicht FTP) ein Laufwerk, wo ich die PDFs einfach reinschiebe. 1x pro Stunde holt die Post die dort ab und man bekommt noch eine Mail, ob das PDF ok oder nicht ok ist.

Also ohne zusätzliche Hardware / Software, einfach mit irgendeinem FTP-Programm, das WebDav kann oder mit Boardmitteln als Laufwerk einbinden.

**Comment by stm9x9** [comment]
> Ich kann mir irgendwie nicht vorstellen, dass gerade die Post Preise senken würde ;-)

Kaum vorzustellen - scheint aber so :-D Ich finde "meine" Preise da zwar nicht, aber teurer war es trotzdem: https://web.archive.org/web/20201201184628/https://www.deutschepost.de/content/dam/dpag/images/E_e/epost/downloads/gk/epostmailer/dp-epost-preisliste-mailer-ab-01012020.pdf

>
> Ich habe einen Account bei dem E-Post Mailer und dort über WebDav (sorry, doch nicht FTP) ein Laufwerk, wo ich die PDFs einfach reinschiebe. 1x pro Stunde holt die Post die dort ab und man bekommt noch eine Mail, ob das PDF ok oder nicht ok ist.
> 
> Also ohne zusätzliche Hardware / Software, einfach mit irgendeinem FTP-Programm, das WebDav kann oder mit Boardmitteln als Laufwerk einbinden.

Was genau müßte j-l denn dann für eine Integration tun? So ganz blicke ich noch nicht durch: Der E-post Mailer ist doch ein virtueller Drucker, oder? Wer oder wo bekommt man dann den WebDav-Platz, um dort was abzulegen? Und wie spielt der Mailer da rein?

**Comment by hackvokat** [comment]
Es gibt verschiedene Varianten, wie man den Mailer nutzen kann. z.B. mit Druckertreiber oder eben über einen Upload auf den Server. Im Mailer legt man die "Drucker" an, die auf die verschiedenen Wege angesprochen werden können. Der Webdav-Server kommt von der Post, nachdem man die Drucker dort angelegt hat. "Mailer" heisst einfach nur das Produkt bei der Post.

j-lawyer müsste also einfach nur einen Upload per Webdav integrieren. Davor müsste man die Server-Zugangsdaten hinterlegen können.

**Comment by papiertiger960ff** [comment]
Es gibt bei der E-Post der DPAG insgesamt 4 verschiedene ZUgänge.
1. Webbrowser
2. ZUschlagpflichtige API
3. WebDAV-Upload (bisher nur IPv4)
4. Netzwerkdrucker per IPP (bisher nur IPv4)
Der fehlende IPv6-Support ist IMO ein größeres Manko.

**Comment by j-dimension** [comment]
2023-09-05 Zugang zur E-POSTBUSINESS API angefragt.

**Comment by papiertiger960ff** [comment]
Update: Die Dpag hat wider Erwarten dazu gelernt und IPv6 nachgerüstet. Alle 4 der nachstehenden Horsts verfügen nun über AAAA-Records:
◦ mailer.epost.de
◦ mailer-ws.epost.de
◦ mailer-printer.epost.de
◦ mailer-webdav.epost.de
Was die Schnittstelle angeht, würde ich persönlich eher für WebDAV plädieren. Für den API-ZUgang braucht man eine ZUlassung der DPAG, die teuer, umständlich und eigentümlich ist.

**Comment by j-dimension** [comment]
erste Informationen erhalten:
- REST API mit JWT
- ziemlich umfangreich, inklusive Terminierung des Versands etc.
- Zugang zur API kostet: 250 EUR einmalig, 50 EUR pro Monat

**Comment by j-dimension** [comment]
Warte auf Zugangsdaten / Vertrag

**Comment by j-dimension** [comment]
Vertrag für API-Zugang erhalten, bearbeitet, zurückgeschickt.

**Comment by j-dimension** [comment]
- inkl. einseitig / beidseitig als Option
- bei Versand mehrerer PDFs: Option des "Merges" ja/nein - Auswirkungen bei beiseitigem Druck, bpsw. bei Handhabung von Anlagen oder bei mitgesendeten Formularen, die zurückgeschickt werden sollen

**Comment by j-dimension** [comment]
API-Zugang in Betrieb genommen, Login via API erfolgreich.

**Comment by j-dimension** [comment]
Um Nutzungrechte für die E-POST - Logos gebeten, zwecks Nutzung in der GUI.

**Comment by j-dimension** [comment]
Validieren des Layout von Vorlagen hinsichtlich Eignung für E-POST-Versand:


https://github.com/jlawyerorg/j-lawyer-org/assets/3729754/41a2246e-379a-45dc-adbf-327b96d63605

**Comment by j-dimension** [comment]
Vorbereiten des Versands via E-POST:

- Dokumente auswählen
- PDF-Konvertierung
- PDFs in Reihenfolge bringen
- PDFs zu einem Dokument zusammenführen
- Gesamt-PDF kontrollieren
- Versand


https://github.com/jlawyerorg/j-lawyer-org/assets/3729754/7d8865ab-8b49-40fc-9f61-6111f5ec9e0a

**Comment by Dickmaulruessler** [comment]
Cool!
Was wird der einzelne Nutzer gegenuber der Deutschen Post tun müssen, damit man diese Funktion (ich persönlich: sehr selten, dann aber sehr gerne) nutzen kann?

**Comment by j-dimension** [comment]
Einen Account öffnen und ihn mit der Anwendung verknüpfen. Ziemlich easy.

**Comment by Dickmaulruessler** [comment]
Registrierung
https://www.deutschepost.de/de/e/epost/geschaeftskunden/partner/business-api.html

FAQ: 
https://www.deutschepost.de/de/e/epost/geschaeftskunden/faq-api-geschaeftskunden.html
- "Keine Einrichtungskosten"
- "Eine monatliche Pauschale fällt nicht an, lediglich ein Preis pro Sendung."
- "Der Kundenservice der Deutschen Post ist von Montag bis Freitag 08:00-18:00 Uhr (außer an bundeseinheitlichen Feiertagen) unter der Telefonnummer 0228 4333112 erreichbar. Die E-Mail-Adresse lautet e-post@deutschepost.de."

**Comment by j-dimension** [comment]
Danke für's Verlinken. Auf dieser Seite (https://www.deutschepost.de/de/e/epost/geschaeftskunden/partner/business-api.html) ist nur der obere Link für Endkunden interessant ("Registrierung für den Versand von Hybridpost über die E-POSTBUSINESS API"), der untere ist für Softwarehersteller. 

Monatliche Kosten fallen nur für Softwarehersteller an.

**Comment by Dickmaulruessler** [comment]
> 
> Monatliche Kosten fallen nur für Softwarehersteller an.

Danke dir für diesen tollen Service!

**Comment by stm9x9** [comment]
> Monatliche Kosten fallen nur für Softwarehersteller an.

bääh. Das heißt, Du mußt jetzt dafür zahlen?

**Comment by j-dimension** [comment]
> bääh. Das heißt, Du mußt jetzt dafür zahlen?

ja

**Comment by Dickmaulruessler** [comment]
Geil! Danke!

**Comment by j-dimension** [comment]
Fertig. 13 000 Zeilen Code.

https://github.com/jlawyerorg/j-lawyer-org/pull/2166/files

**Comment by j-dimension** [comment]
Schreiben an mich selbst erhalten. Wieder ein Meilenstein erreicht :-)
