### ISSUE TITLE
[beA] Justizbehörde wird (wieder) falsch vorbelegt

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#540]
ist das schonmal gefixt gewesen oder verwechsel ich inzwischen alles?

![image](https://user-images.githubusercontent.com/29924198/71528958-b7d30000-28e2-11ea-8bf3-7d275d6bb306.png)

Ich habe an ein in beA existierendes AG Neukölln verschickt und bekomme als Vorauswahl die Eingabe vom letzten Mal statt den Ort des Gerichts.

**Comment by j-dimension** [comment]
Eher eine Erweiterung als ein Bugfix. 

Duplikat von #394. Eine Frage an die BRAK blieb unbeantwortet. 

Am 17. November von mir daher in die 1.12 geschoben.
