### ISSUE TITLE
Sperren von Dokumenten

### ISSUE THREAD

**Issue by j-dimension** [jlawyerorg/j-lawyer-org#541]
ggf. auch Akten, wenn anderweitig geöffnet. 

Bei Sperrung: Ausgabe einer Warnung, aber Nutzer kann wahlweise fortfahren.

dokumentieren: automatisches Sperren von Dokumenten über Nutzerverwaltung an- und ausschaltbar

**Comment by j-dimension** [comment]
@RA-crm

**Comment by librelegal** [comment]
Dokumente sperren macht Sinn. Das Dokument könnte nach Warnung dann schreibgeschützt geöffnet werden. Akten würde ich nicht sperren, da der/die ReNo andere Arbeiten ausführen kann (z.B. Anlagen zur Klage zusammenstellen), während RA / RAIn an der Klage arbeitet.

**Comment by Linkki2021** [comment]
Ich halte hier auch Akten für sinnvoll. Wenn man eine Warnung erhält kann man ja immer noch entscheiden, ob man fortfährt, weil man abgestimmt etwas parallel macht oder eben nicht, weil es einem nicht klar war, dass noch jemand in der Akte arbeitet.

**Comment by j-dimension** [comment]
Switch-Widget für Sperrung: https://github.com/JFormDesigner/FlatLaf/issues/135

**Comment by j-dimension** [comment]
User: "Der Server sperrt viele Dokumente, obwohl ich längst aus der Akte raus bin. Im Dokumentenmonitor stehen manchmal Dokumente, die vor Stunden bearbeitet wurden. Mit der neuen Warnung für gesperrte Dokumente fällt das umso mehr auf."

**Comment by j-dimension** [comment]
@iradraconis bin unsicher ob ich hier im Rahmen der 2.6 noch Verbesserungen erreichen kann. In der Nutzerverwaltung kann man das Sperren deaktivieren.

Welche Dokumente werden bei Euch nicht ordentlich als geschlossen erkannt? (Dateityp, mit welcher Anwendung geöffnet)

**Comment by iradraconis** [comment]
Odt Libreoffice Dokumente und pdf Dokumente, bspw. Mit Preview geöffnet (macOS). Der Dokumenten Inspektor (heißt das so?) hat aber schon lange Zeit immer mal Schwierigkeiten, Dokumente ordentlich zu schließen, so dass nach 1- 2 Stunden Nutzung dort zig Dokumente stehen, die schon längst geschlossen sind.

**Comment by j-dimension** [comment]
Preview kann ich nachvollziehen, aber LibreOffice nicht. Ist das als "externes Programm" konfiguriert? Das sollte definitiv nicht passieren.

**Comment by j-dimension** [comment]
@iradraconis habt Ihr das Feature deaktiviert, oder ist es grundsätzlich so nutzbar?

**Comment by iradraconis** [comment]
Wir haben das Feature nicht deaktiviert. Ich vermute, es ist grundsätzlich so nutzbar, wir sind nicht auf größere Schwierigkeiten gestoßen.

**Comment by j-dimension** [comment]
server_settings: jlawyer.server.documents.lock.filetypes
default: doc,docx,xls,xlsx,fodp,fodt,odp,ods,odt,ppt,pptx
