### ISSUE TITLE
Anzeige Datum mit Wochentag

### ISSUE THREAD

**Issue by librelegal** [jlawyerorg/j-lawyer-org#544]
Datumsangaben "Wiedervorlage und Fristen") werden im Format DD.MM.YYYY angezeigt (also z.B. 01.01.2020). Optimal wäre es, wenn dann auch gleich der Wochentag mit dabei steht, zumindest optional. So läßt sich der zeitliche Ablauf in der Akte besser steuern.

**Comment by PBaumfalk** [comment]
#507
