### ISSUE TITLE
Dialog lokal speichern

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#547]
Wenn ich eine Datei lokal speichere, dann sieht der Dialog für den Speicherordner so aus:

![image](https://user-images.githubusercontent.com/29924198/71565034-5d849b80-2aaa-11ea-901c-09a0e4e73b94.png)

Da paßt unten "öffnen" IMHO nicht. Vielleicht "hier speichern"? Ebenso oben im Titel.

Und auch oben: "suchen in"?

Dateityp könnte bei einer Ordnerauswahl weg - wenn das geht.

Und es wäre schön, ein "maximize" Button oben neben dem X zu haben.

**Comment by j-dimension** [comment]
Maximieren-Button gibt die API nicht her.

**Comment by j-dimension** [comment]
File Type Filter verstecken gibt die API nicht her.

**Comment by j-dimension** [comment]
Titel und Button-Beschriftung angepasst (verschiedene Stellen)
