### ISSUE TITLE
Farbgebung

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-org#548]
Nach zwei Tage Arbeit im neuen Design sind meine Frau und ich uns dahingehend einig, dass das alte Design ein entspannteres Arbeiten ermöglichte. Das liegt insbesondere an den im alten Design höheren Kontrasten. Das ist nun nicht direkt ein Mangel, andere mögen dies anders empfinden, aber es wäre hilfreich, die Farbpalette des Designs anpassen zu können durch vorgegebene Muster oder individuell abspeicherbare Muster - ähnlich wie man das aus älteren Windowsversionen kennt.

**Comment by PBaumfalk** [comment]
Also ich finde das neue Design sehr ansprechend. Eine änderbar Farbgebung wäre mit einem enormen Mehraufwand was die Erstellung von Icons angeht, verbunden.

**Comment by j-dimension** [comment]
Ich lasse mal noch ein paar Tage im neuen Jahr ins Land ziehen, dann werden sicher etliche Anwender auf die 1.11 wechseln.

Gegen Mitte Januar dann am besten mal auf der Mailingliste eine breitere Debatte dazu initiieren.

Grundsätzlich gilt: Flexibilität kostet, und zwar sehr viel Zeit. Daher sind mir konkrete Änderungsvorschläge sehr viel lieber, wie bspw. dieser hier:
https://github.com/jlawyerorg/j-lawyer-org/issues/537
den ich schon umgesetzt habe und in Kürze als Release liefern werde.

**Comment by j-dimension** [comment]
Bitte die 1.11.0.4 ausprobieren.
