### ISSUE TITLE
[BUG] Bericht generieren Fax - MacOS 10.15 Catalina

### ISSUE THREAD

**Issue by PBaumfalk** [jlawyerorg/j-lawyer-org#549]
Wenn ich einen Bericht für das Fax generieren möchte, dann erscheint folgende Fehlermeldung auf dem Mac:

![image](https://user-images.githubusercontent.com/50404378/71580153-cea26e00-2aff-11ea-80fd-643c85bfb324.png)

**Comment by j-dimension** [comment]
Kannst Du ein client.log per Mail schicken?

**Comment by j-dimension** [comment]
Wie "alt" ist das relevante Fax?

**Comment by PBaumfalk** [comment]
Das relevante Fax war nur wenige Tage alt. Ich werde den Fehler nochmals reproduzieren.

**Comment by j-dimension** [comment]
Okay, verstehe. Fakt ist dass Sipgate meint, das Fax würde nicht (mehr) existieren. Ich könnte das abfangen und dem Anwender eine bessere Fehlermeldung präsentieren, und den Eintrag aus der Liste entfernen. 

Deal?

**Comment by PBaumfalk** [comment]
Passt.

**Comment by j-dimension** [comment]
Serverseitige Änderung, daher erst in 1.12 zu beheben.
