### ISSUE TITLE
Customization Schriftgröße

### ISSUE THREAD

**Issue by j-dimension** [jlawyerorg/j-lawyer-org#556]
mit FlatLaf erneut testen / fixen oder ausbauen

**Comment by j-dimension** [comment]
@bjk00

**Comment by bjk00** [comment]
Was mir in Version 1.11.0.3 aufgefallen ist:

- Menüleiste links: die Schriftgröße der Mengenindikatoren wird nicht skaliert

- Akte/Beteiligte: die Namen der Beteiligten werden nicht skaliert
- Akte/Beteiligte: die Feldbreite der Dropdown-Auswahl zum Typ der Beteiligten (Mandant, Gegener, Dritte) wird nicht skaliert und ist bei großer Schriftgröße zu klein
- Akte: das Aktenzeichen und das Kurzrubrum über der Tab-Leiste wird nicht skaliert
- Akte/Drucken: die Symbole werden nicht skaliert

- Desktop: die Überschriften über den Listen ("zuletzt geändert", "Nach Etikett" und "Fällig") werden nicht skaliert
- Desktop: der Profilname oben rechts wird nicht skaliert
- Desktop: die Statusanzeige oben links wird nicht skaliert

- Adresse bearbeiten: Der Name oben links über den Tabs wird nicht skaliert
- Adresse bearbeiten: der Status "Verschlüsselt/nicht verschlüsselt" oben rechts wird nicht skaliert

- Fax: die Anzeige des Guthabens oben links wird nicht skaliert

- Volltext/Dokumentensuche: die Ergebniseinträge in der Dokumentensuche werden nicht skaliert

- Meine Timeline/alle Änderungen: die Zeitraumanzeige/Auswahlschieber oberhalb der Ergebnisanzeige ist zu breit und wird rechts vom Fensterrand abgeschnitten

- U&G: die Ergebnisliste wird nicht skaliert

- Einstellungen (Button linke Menüleiste): die Unterpunkte werden nicht skaliert

- Kalenderauswahl: die Schriftgröße in der Kalenderauswahl (egal von wo aufgerufen) wird nicht skaliert

- in allen Listen (Akte/Dokumente, Akte/Wiedervorlagen und Fristen, Akte/Historie, Email/Posteingang, Scans, usw.): die Höhe der Zeilen ist für die größte Schriftgrößeneinstellung zu klein bzw. wird nicht skaliert, der Text wird dadurch an der Unterkante leicht abgeschnitten

**Comment by j-dimension** [comment]
Skalierung anders implementiert, sodass sie sich auf die gesamte Oberfläche auswirkt. Einstellungsdialog angepasst:

![grafik](https://user-images.githubusercontent.com/3729754/162639637-cb01eb6a-8e41-4aca-a998-63d3c5511c0e.png)

**Comment by Dickmaulruessler** [comment]
Sehr wertvoll für manche! 
Merci!

**Comment by j-dimension** [comment]
MacOS skaliert wie es will (Einstellungen Betriebssystem, was okay sein könnte)
JVM unter Linux hat nen Bug: https://bugs.java.com/bugdatabase/view_bug.do?bug_id=JDK-8238077
Windows geht
