### ISSUE TITLE
Shortcuts reloaded / Tastenkürzel überarbeiten

### ISSUE THREAD

**Issue by RA-crm** [jlawyerorg/j-lawyer-org#557]
Ich arbeite sehr gerne mit shortcuts. Insbesondere mit F2 für umbenennen. Mit der neuen Version ist F2 = Akte suchen. Das ist schade. Denn die Funktion Dokument umbenennen als shortcut fehlt und F2 läge so nahe.
Kann man das noch ändern?
Gibt es eine Möglichkeit einen Shortcut für Umbenennen zu implementieren? zB F2+Strg?

@j-dimension:

- [x] Test Windows
- [ ] Test macOS
- [x] Test Linux

**Comment by stm9x9** [comment]
yep, ich mache auch immer den Fehler.  F2 ist schlicht Umbenennen in Windows.

**Comment by Maz111111** [comment]
das gehört zu #468.
Dort hatte ich im Zusammenhang damit vorgeschlagen, auch gleich das Löschen auf "Entf" zu legen?

**Comment by RA-crm** [comment]
Kann man die F2 Taste manuell  stumm legen.

Als es noch kein F-Funktionalität gab, passierte bei meiner Umbenennungsroutine schlicht nichts. Jetzt haue ich mich selbst immer aus der Akte und lande bei "Neue Akte anlegen", wenn ich aus der Jahrzehnte alten Routine das Dokument mal wieder mit F2 umbennen will.

**Comment by j-dimension** [comment]
Ich werde die Shortcuts auf  AltGr+Fx abändern.

**Comment by j-dimension** [comment]
Ach Moment, @PBaumfalk hat eine Apple-Tastatur überhaupt ein AltGr?

**Comment by PBaumfalk** [comment]
Nein. Hier ein Bild einer Apple Tastatur:



Mit freundlichen Grüßen / Kindly Regards

Patrick Baumfalk
Rechtsanwalt / Lawyer


Mobil:    +49 1525 53 04 194
E-Mail:   patrick.baumfalk@kanzlei-baumfalk.de


Baumfalk - Rechtsanwaltskanzlei
Hauptstr. 195
50169 Kerpen

Tel.: +49 2273 40 68 504
Fax: +49 2273 59 03 565

E-Mail: info@kanzlei-baumfalk.de
Web: www.kanzlei-baumfalk.de

Sent by Mobile

**Comment by j-dimension** [comment]
Ich find schon was. Hab nur Bedenken dass die Tastatur von meinem 2012er macBook nicht mehr "state of the art" ist :-D

**Comment by PBaumfalk** [comment]
Das funktioniert wohl nicht über die Mail:

Magic Keyboard:
![image](https://user-images.githubusercontent.com/50404378/72597271-b0b17780-390d-11ea-832e-e2a55787e4d0.png)

**Comment by RA-crm** [comment]
argh. Ich sehe gerade, dass die F2-Tastenbelegung erst in der 2.1 angepasst werden soll. Dann ist es mE zu spät. F2 muss Dateiname-Ändern sein. Wenn jetzt mit F2 gleich "neue Akte anlegen" gearbeitet wird, bekommt man die User davon nicht mehr weg. Und ich brauche F2 wirklich dringend zum Umbenennen. Jedenfalls darf die Taste keine andere Funktion haben, sodass ich jedesmal wo anders lande.

**Comment by j-dimension** [comment]
Ich kann die F-Tasten wieder rausnehmen (nur F2 rausnehmen wäre m.E. inkonsistent). Das Umbenennen über F2 mache ich aber in 1.12 nicht mehr. Ich muss dort jetzt mal den Sack zu machen.

Im Mai werde ich wesentlich weniger Zeit investieren können, daher muss die 1.12 jetzt fertig werden.

**Comment by RA-crm** [comment]
damit kann ich leben ;-) 
Das verhindert immerhin die falsche Gewöhung der Nutzung der F2 Taste.
Vielen Dank

**Comment by j-dimension** [comment]
auskommentiert in Klasse ModuleBar

```
            ModuleButton b = new ModuleButton(m);
            buttonPane.add(b);
            if (m.getHotKey() != null) {
                this.hotKeyActions.put(m.getHotKey(), new AbstractAction(m.getEditorClass()) {
                    @Override
                    public void actionPerformed(ActionEvent e) {
                        b.actionPerformed();
                    }
                });
            }
```

**Comment by j-dimension** [comment]
Und schon bekomme ich verbale Prügel von zwei Anwendern, die die Shortcuts zurück haben wollen. Seufz.

**Comment by j-dimension** [comment]
Akten- / Adresssuche-Shortcut sollte auch den Fokus in das Suchfenster setzen

**Comment by RA-crm** [comment]
was soll
> sollte auch den Fokus in das Suchfenster setzen
heißen?

**Comment by j-dimension** [comment]
@RA-crm "Suchfeld" wäre passender. 

Ziel: Tastenkombination drücken und dann ohne Griff zur Maus direkt die Suche eintippen, Enter. Dazu muss der Cursor auch im Suchfeld sein.

**Comment by stm9x9** [comment]
> Und schon bekomme ich verbale Prügel von zwei Anwendern, die die Shortcuts zurück haben wollen. Seufz.

kein Wunder, die sind ja auch noch im Hover-Text bei dem Seitenmenü genannt die Kürzel :-D

**Comment by j-dimension** [comment]
Shice   8-(

**Comment by Dickmaulruessler** [comment]
Es gab ja mal Shortcuts, die dann [wieder entfernt](https://github.com/jlawyerorg/j-lawyer-org/issues/700) wurden. 

Wenn diese später wieder eingeführt werden, was ich sehr begrüßen würde, wofür wird es die denn dann geben?
Ich vermisse es eigentlich vor allem für **"Akte neu"** und **"Akte suchen".**

Und soll das hier ein recht spezieller Titel "Umbenennen von Dokumenten ..." bleiben oder kann man hier allgemein zu Shortcuts schreiben? 
Relevant zu diesem allgemeinen Thema ist auch noch #468

**Comment by stm9x9** [comment]
Zumindest Akte neu kommt doch jetzt nicht sooo oft vor im Vergleich zu anderen Aktionen?

**Comment by Dickmaulruessler** [comment]
@j-dimension ob es sinnvoll wäre, dass du die von dir beabsichtigten Kürzel hier jetzt schon einmal vollständig zur Diskussion stellst und jeder seinen Senf dazugeben kann, damit die Kürzel dann langfristig bestehen bleiben können?

**Comment by Dickmaulruessler** [comment]
Macht es Sinn, die Kürzel jetzt schon einmal festzulegen, damit evtl. "Einwände" frühzeitig erhoben werden können?

**Comment by j-dimension** [comment]
> Macht es Sinn, die Kürzel jetzt schon einmal festzulegen, damit evtl. "Einwände" frühzeitig erhoben werden können?

Ich werde in den nächsten drei / vier Wochen noch nicht zu diesem Ticket kommen, aber wenn Du bereits eine Abstimmung hier zu initiieren möchtest, ist das natürlich sehr willkommen.

**Comment by Dickmaulruessler** [comment]
"Einwände" wurden nur gegen F2 erhoben. 
Ich mache einfach einmal den Vorschlag **dann die F3 ff. zu belegen.** 
Am Wichtigsten wäre mir das für "Akte suchen", freue mich natürlich auch über weitere...

**Liebe Kolleginnen und Kollegen, bitte gerne breit kommentieren und ggf. Gegenvorschläge unterbreiten!**
Falls F3 ff. nicht auf Zustimmung stoßen sollte, würde ich es begrüßen, wenn wir dann alternativ eine andere einzelne Taste und nicht eine Tastenkombination finden könnten.

**Comment by stm9x9** [comment]
vor allem brauche ich ja F2 :-)

ansonsten wäre zb F5 für Reload zb in bea oder Mails

**Comment by stm9x9** [comment]
aber vielleicht mal in der Mailingsliste fragen?

**Comment by stm9x9** [comment]
> Shice 8-(

BTW die Shortcuts sind im Hover-Text bei dem Seitenmenü immer noch genannt :-D

**Comment by j-dimension** [comment]
@Bentipa falls Du Dir das anschaust, hier wäre ein Tastenkombination zu definieren, 
- die nicht mit vorhandenen kollidiert (also fallen einfache F-Tasten wohl raus, und man müsste eine Tastenkombination nehmen)
- die für Windows, Linux und macOS funktioniert (ggf. plattformspezifisch umsetzen)

Für die Definition der Hot Keys gibt es in der Klasse "Module" bereits Members. Die Module selbst werden in dieser Klasse initialisiert: https://github.com/jlawyerorg/j-lawyer-org/blob/master/j-lawyer-client/src/com/jdimension/jlawyer/client/Main.java

Um die Tastenkombinationen anwendungsweit zu aktivieren, sollte bereits (ggf. auskommentiert) etwas im Code zu finden sein. Im Code mal nach "Toolkit" oder "KeyDispatcher" suchen.

**Comment by j-dimension** [comment]
An alle Mitlesenden: die Tastenkombinationen werden zukünftig Shift+Fx nutzen.

**Comment by j-dimension** [comment]
Auf macOS nicht funktionsfähig - reopen.

**Comment by Dickmaulruessler** [comment]
> > Shice 8-(
> 
> BTW die Shortcuts sind im Hover-Text bei dem Seitenmenü immer noch genannt :-D

Besteht fort.

**Comment by j-dimension** [comment]
> > > Shice 8-(
> > 
> > 
> > BTW die Shortcuts sind im Hover-Text bei dem Seitenmenü immer noch genannt :-D
> 
> Besteht auch in 2.2. fort.

Sollen Sie ja, und auch funktionieren :-)

**Comment by Dickmaulruessler** [comment]
Ey! Sorry, wie cool!
Danke!

**Comment by stm9x9** [comment]
sollte F2 zum Umbenennen jetzt eigentlich funktionieren in der aktuellen 2.3 oder noch nicht? Weil hier (Windows 10) geht es nicht.

**Comment by j-dimension** [comment]
https://github.com/jlawyerorg/j-lawyer-org/issues/1908
