### ISSUE TITLE
noch mehr Icons für die Mitarbeiter

### ISSUE THREAD

**Issue by RA-crm** [jlawyerorg/j-lawyer-org#559]
Die Mitatbeiter sollen anhand des Icons unterscheidbar sein. Meinen Mitarbeitern ist die Auswahl zu gering und die Motive tendenziell zu unprofessionell. Vielleicht kann man den blauen Kopf einfach in unterschiedlichen Farben bereit stellen.

**Comment by PBaumfalk** [comment]
Hallo zusammen,

auch ich mag die Mitarbeiter-Icons nicht. Ich mache welche, die zum Design passen und professionell sind. Wie viele Icons brauchen wir für die Mitarbeiter und Anwälte? 50 Stück?

**Comment by RA-crm** [comment]
50 wäre extraklasse. 
Für meinen Bedarf würden absehbar 10 bis 12 reichen.

**Comment by j-dimension** [comment]
Ihr Humorlosen! :-)

@PBaumfalk - 50 ist eine Menge! Letztlich überlasse ich das Dir - jedes zusätzliche Icon hilft. Ich schreibe heute Abend noch was genau gebraucht wird. Bei den Nutzer-Icons sollten es nur zwei Varianten sein: einmal groß, einmal klein.

**Comment by PBaumfalk** [comment]
> Ihr Humorlosen! :-)
> 
> @PBaumfalk - 50 ist eine Menge! Letztlich überlasse ich das Dir - jedes zusätzliche Icon hilft. Ich schreibe heute Abend noch was genau gebraucht wird. Bei den Nutzer-Icons sollten es nur zwei Varianten sein: einmal groß, einmal klein.

Die Größe ist mir egal. Das macht die Stapelverarbeitung hier von Photoshop. Die Icons selbst sind die Arbeit ;)

**Comment by j-dimension** [comment]
Ah, von unterwegs gefunden. Gebraucht werden je zwei Varianten:
- 16x16, mindestens 1 Pixel Rand umlaufend
- 32x32, mindestens 1, besser 2 Pixel Rand umlaufend

Gebraucht werden wieder PNGs mit transparentem Hintergrund.

Die Logofarben (falls das eine Rolle spielt - die hinteren Zahlen sind die RGB-Werte): 

```
    public static Color COLOR_LOGO_RED=new Color(222, 49, 59);
    public static Color COLOR_LOGO_GREEN=new Color(151, 191, 13);
    public static Color COLOR_LOGO_BLUE=new Color(14, 114, 181);
    public static Color COLOR_DARK_GREY=new Color(102, 102, 102);
```

**Comment by j-dimension** [comment]
Aktuell genutzte Avatare:
https://github.com/jlawyerorg/j-lawyer-org/tree/master/j-lawyer-client/src/avatar16
https://github.com/jlawyerorg/j-lawyer-org/tree/master/j-lawyer-client/src/avatar32

**Comment by PBaumfalk** [comment]
Die Icons werde ich so bauen:

1x Anwalt Männlich (10 unterschiedliche Farben)
1x Anwalt Weiblich (10 unterschiedliche Farben)
1x Mitarbeiter Männlich (10 unterschiedliche Farben)
1x Mitarbeiter Weiblich (10 unterschiedliche Farben)
10 Sonstige Icons in J-Lawyer Farben

+ J-Lawyer-Classic Icons ;)

Dann dürften doch genug dabei sein oder?

**Comment by j-dimension** [comment]
Solange Du keine Paragraphenzeichen, Richterhämmer oder Justitias machst ist mir alles recht.

**Comment by PBaumfalk** [comment]
![Mitarbeiter-Icons-16](https://user-images.githubusercontent.com/50404378/71736033-5bc32b00-2e50-11ea-8f6b-60c6df8d06fd.png)
![Mitarbeiter-Icons-17](https://user-images.githubusercontent.com/50404378/71736034-5c5bc180-2e50-11ea-9b78-309f9c34daf7.png)
![Mitarbeiter-Icons-18](https://user-images.githubusercontent.com/50404378/71736035-5c5bc180-2e50-11ea-9ff2-4658a530c8ce.png)
![Mitarbeiter-Icons-19](https://user-images.githubusercontent.com/50404378/71736036-5c5bc180-2e50-11ea-9e0d-4b8523d3bb16.png)
![Mitarbeiter-Icons-20](https://user-images.githubusercontent.com/50404378/71736037-5cf45800-2e50-11ea-9e71-e5aa2a14d1a5.png)
![Mitarbeiter-Icons-21](https://user-images.githubusercontent.com/50404378/71736039-5cf45800-2e50-11ea-9523-c90443babc47.png)
![Mitarbeiter-Icons-22](https://user-images.githubusercontent.com/50404378/71736040-5cf45800-2e50-11ea-8fd1-1423ed0d113f.png)
![Mitarbeiter-Icons-23](https://user-images.githubusercontent.com/50404378/71736041-5cf45800-2e50-11ea-8bac-ee04440f4237.png)
![Mitarbeiter-Icons-24](https://user-images.githubusercontent.com/50404378/71736042-5cf45800-2e50-11ea-91ab-5d6c6cd914ea.png)
![Mitarbeiter-Icons-25](https://user-images.githubusercontent.com/50404378/71736043-5d8cee80-2e50-11ea-9c80-1bd3cf60280f.png)
![Mitarbeiter-Icons-01](https://user-images.githubusercontent.com/50404378/71736045-5d8cee80-2e50-11ea-8b60-f5201e7d4e27.png)
![Mitarbeiter-Icons-02](https://user-images.githubusercontent.com/50404378/71736046-5d8cee80-2e50-11ea-9c86-d74f8d19c05e.png)
![Mitarbeiter-Icons-03](https://user-images.githubusercontent.com/50404378/71736047-5e258500-2e50-11ea-949d-e1baca08ff58.png)
![Mitarbeiter-Icons-04](https://user-images.githubusercontent.com/50404378/71736048-5e258500-2e50-11ea-82f2-ec192d7cbc28.png)
![Mitarbeiter-Icons-05](https://user-images.githubusercontent.com/50404378/71736050-5e258500-2e50-11ea-8cfd-cf7bc201145b.png)
![Mitarbeiter-Icons-06](https://user-images.githubusercontent.com/50404378/71736052-5e258500-2e50-11ea-9dd8-97c3f9bf9f6a.png)
![Mitarbeiter-Icons-07](https://user-images.githubusercontent.com/50404378/71736053-5ebe1b80-2e50-11ea-9207-1bb1bd8a9591.png)
![Mitarbeiter-Icons-08](https://user-images.githubusercontent.com/50404378/71736054-5ebe1b80-2e50-11ea-9c25-9eb3b0b26e80.png)
![Mitarbeiter-Icons-09](https://user-images.githubusercontent.com/50404378/71736055-5ebe1b80-2e50-11ea-84a0-fe34ee527933.png)
![Mitarbeiter-Icons-10](https://user-images.githubusercontent.com/50404378/71736056-5ebe1b80-2e50-11ea-9c6d-2fedcce91d24.png)
![Mitarbeiter-Icons-11](https://user-images.githubusercontent.com/50404378/71736057-5f56b200-2e50-11ea-8c70-10168d244697.png)
![Mitarbeiter-Icons-12](https://user-images.githubusercontent.com/50404378/71736058-5f56b200-2e50-11ea-953c-591691ee95b1.png)
![Mitarbeiter-Icons-13](https://user-images.githubusercontent.com/50404378/71736059-5f56b200-2e50-11ea-8a43-c9dadf49fa5a.png)
![Mitarbeiter-Icons-14](https://user-images.githubusercontent.com/50404378/71736060-5f56b200-2e50-11ea-9a64-3194c572860a.png)
![Mitarbeiter-Icons-15](https://user-images.githubusercontent.com/50404378/71736061-5fef4880-2e50-11ea-85d3-66f4fc75b426.png)

**Comment by PBaumfalk** [comment]
25 Stück müssten doch erstmal reichen oder?

**Comment by PBaumfalk** [comment]
[Mitarbeiter.zip](https://github.com/jlawyerorg/j-lawyer-org/files/4019962/Mitarbeiter.zip)

**Comment by j-dimension** [comment]
Super, @PBaumfalk !

Ich habe das gerade eingebaut. 

Hast Du eigentlich schonmal ein j-lawyer.org-Goodie von mir erhalten?

**Comment by PBaumfalk** [comment]
> Super, @PBaumfalk !
> 
> Ich habe das gerade eingebaut.
> 
> Hast Du eigentlich schonmal ein j-lawyer.org-Goodie von mir erhalten?

Bisher noch kein Goodie. ;-)

**Comment by j-dimension** [comment]
@PBaumfalk , okay, ich ändere das.

**Comment by stm9x9** [comment]
kann man - für 2.0 oder so - auch selbsthochgeladene Avatare in Betracht ziehen?

**Comment by j-dimension** [comment]
@stm9x9 wäre ein eigenes Ticket.
