### ISSUE TITLE
Löschen von Dokumenten und Einstellungen

### ISSUE THREAD

**Issue by RA-crm** [jlawyerorg/j-lawyer-org#560]
Wenn Dokumente, oder auch auf Einstellungsebene (zB Etiketten/Tags), gelöscht werden sollen, funktioniert das über das Kontextmenue (rechte Maustaste > löschen). Dabei ist die Auswahl Löschen immer oben. Wenn man etwas unsauber klickt, löscht man den Eintrag "gleich" beim ersten Klick.
Lösungsvorschlag:
Auswahl "löschen" an das Ende des Kontextmenue platzieren, um das Löschen tatsächlich willentlich vorzunehmen.

**Comment by Maz111111** [comment]
siehe #356
Da ging es zwar um Beteiligte
Aber auch da hatte ich schon vorgeschlagen, "Löschen" an eine andere Stelle zu verschieben.
Halte ich nach wie vor für sicherer - gerade beim Löschen von Dokumenten.

**Comment by j-dimension** [comment]
Ich habe die Kontextmenüeinträge jetzt an die Ende der jeweiligen Gruppe geschoben. Das ist meistens das Ende des Menüs. Bei Dokumenten hat das Popup mehrere Gruppen, dort ist es dann irgendwo mittig zu finden.
