### ISSUE TITLE
Sicherheitsabfragen

### ISSUE THREAD

**Issue by Maz111111** [jlawyerorg/j-lawyer-org#564]
Normalerweise bin ich ja eher ein safety first Typ.
Aber beim Schließen der KSW (nur durch ein eindeutiges Kommando und fast nicht per Zufall möglich) kommt bei geöffneten Doks ein großes - nicht zu übersehendes - Fenster, in welchem auf die (vermeintlich) ungespeicherten noch offenen Dokumente hingewiesen wird. Man klickt auf "Schließen" und bekommt dann eine zweite Abfrage mit dem gleichen Inhalt, die auch per Klick bedient werden muss.
Dazu kann man stehen wie man will.
Ich brabbele bei solchen Doppelabfragen (bei jeder Software) immer in Richtung Monitor "Ich habe bereits zweimal gesagt, das ich die Software schließen will. Meine Meinung dazu hat sich in den letzten Sekunden nicht geändert. Und ja, ich habe den Warnhinweis gesehen und bewusst weggeklickt. Aber ich sag es gern auch ein Drittes Mal" :-)
Ich denke ein Hinweis in Form eines nicht zu übersehenden Fensters genügt. Zumal die KSW ja gar nicht zu prüfen scheint, ob wirklich abgespeichert wurde oder nicht, sondern grundsätzlich jedes geöffnete Dokument als unabgespeichert behandelt.
Das gilt auch für die Abfrage beim Speichern einer Akte ohne Wiedervorlage. 
Wenn denn hier überhaupt ein Hinweis nötig ist, dürfte ein Klick ausreichen.

**Comment by Maz111111** [comment]
Also bevor das jemand in den falschen Hals kriegt. Ich mein das nur als Verbesserungsvorschlag und

>  "Ich habe bereits zweimal gesagt, das ich die Software schließen will. Meine Meinung dazu hat sich in den letzten Sekunden nicht geändert. Und ja, ich habe den Warnhinweis gesehen und bewusst weggeklickt. Aber ich sag es gern auch ein Drittes Mal" :-)

zaubert dem Leser hoffentlich ein verschmitztes Lächeln ins Gesicht.
Wie gesagt normalerweise habe ich auch lieber eine Abfrage mehr als eine zu wenig.
Aber die beiden beschriebenen Abläufe haben sich in meiner Zeit der Nutzung der KSW als sehr auffällig erwiesen - gerade wenn man Feierabend machen will oder den Mandanten im Raum sitzen hat.
also bitte nicht falsch verstehen - nur als Vorschlag gedacht...

**Comment by j-dimension** [comment]
Kein Mensch flucht so explizit konstruktiv. Genau mein Humor :-)

**Comment by ReRo-G** [comment]
Rückfrage zu diesem Thema:
Ich bekomme gar keine Warnmeldung und so kommt es leider gelegentlich vor, dass ich jl schließe, obwohl noch Dokumente offen sind. (MacOS).
Ist die Funktion inzwischen deaktivert?

**Comment by j-dimension** [comment]
Die Funktion gibt es noch. Gibt es ein reproduzierbares Szenario? Dann bitte ein separates Bugticket. Danke!
