### ISSUE TITLE
[BEA] Pfeiltasten funktionieren nicht im Nachrichtenfenster - MacOS 10.15

### ISSUE THREAD

**Issue by PBaumfalk** [jlawyerorg/j-lawyer-org#568]
Die Cursortasten(Pfeiltasten) auf meiner Tastaur funktionieren nicht im Nachrichtenfenster. 

Also wenn ich zweimal Enter drücke und dann mit dem Cursor in die Zeile darüber möchte, kann ich das nicht machen.

**Comment by j-dimension** [comment]
Meinst Du im Nachrichtentext? 

Sehr verwunderlich...

**Comment by PBaumfalk** [comment]
Ja, auf MacOS ist das so. Zeige ich dir auch gerne.

**Comment by j-dimension** [comment]
Kannst Du das mal in die Mailingliste und/oder die Facebook-Gruppe reinrufen?

**Comment by PBaumfalk** [comment]
Mit den Pfeiltasten "scrolle" ich nach unten oder oben. Der Cursor bewegt sich nicht.  Ich habe auch nochmal in der Windowsversion geguckt: Der Fehler tritt bei mir nur in MacOS auf.

**Comment by PBaumfalk** [comment]
Das Problem tritt auch im E-Mail-Fenster auf.

**Comment by j-dimension** [comment]
Gerät mit macOS 10.15 beschafft. Cursortasten links/rechts funktionieren, hoch/runter funktioniert nicht. Ist das bei Dir genaus, @PBaumfalk ?

**Comment by j-dimension** [comment]
Gefunden. Die Scrollleisten stehlen unter macOS die Tastenereignisse.

**Comment by PBaumfalk** [comment]
Ja genau so ist das!

Mit freundlichen Grüßen / Kindly Regards

Patrick Baumfalk
Rechtsanwalt / Lawyer


Mobil:    +49 1525 53 04 194
E-Mail:   patrick.baumfalk@kanzlei-baumfalk.de


Baumfalk - Rechtsanwaltskanzlei
Hauptstr. 195
50169 Kerpen

Tel.: +49 2273 40 68 504
Fax: +49 2273 59 03 565

E-Mail: info@kanzlei-baumfalk.de
Web: www.kanzlei-baumfalk.de

Sent by Mobile
