### ISSUE TITLE
Desktop: Icons auf Desktop passen nicht zum Design

### ISSUE THREAD

**Issue by PBaumfalk** [jlawyerorg/j-lawyer-org#571]
![image](https://user-images.githubusercontent.com/50404378/71762553-b69c6700-2ed0-11ea-98d8-465622b5768e.png)

Das sieht doch irgendwie seltsam aus. Ich mache da fix zwei zum Design passende Logos.

**Comment by PBaumfalk** [comment]
@j-dimension Kannst du mir für die beiden linken Icons mal die Datei-Maße geben? Ich finde die irgendwie nicht im "Code"...

**Comment by j-dimension** [comment]
@PBaumfalk meinst Du die beiden rechts? Drebis und beA?

**Comment by PBaumfalk** [comment]
@j-dimension Si.

**Comment by j-dimension** [comment]
https://github.com/jlawyerorg/j-lawyer-org/blob/master/j-lawyer-client/src/icons16/drebis16.png

**Comment by j-dimension** [comment]
https://github.com/jlawyerorg/j-lawyer-org/blob/master/j-lawyer-client/src/icons16/bea16.png

**Comment by PBaumfalk** [comment]
![Icons-Desktop-01](https://user-images.githubusercontent.com/50404378/71763664-ac816500-2ede-11ea-8543-6ee98a424dd8.png)
![Uploading Icons-Desktop-02.png…]()

**Comment by PBaumfalk** [comment]
![Icons-Desktop-01](https://user-images.githubusercontent.com/50404378/71763669-b3a87300-2ede-11ea-995e-42d04da6c828.png)
![Icons-Desktop-02](https://user-images.githubusercontent.com/50404378/71763670-b3a87300-2ede-11ea-99e7-bd57872524a4.png)

**Comment by PBaumfalk** [comment]
[Desktop-Icons.zip](https://github.com/jlawyerorg/j-lawyer-org/files/4021734/Desktop-Icons.zip)
