### ISSUE TITLE
[BUG] Tooltip bei Favorit fehlt

### ISSUE THREAD

**Issue by PBaumfalk** [jlawyerorg/j-lawyer-org#572]
![image](https://user-images.githubusercontent.com/50404378/71762737-97530900-2ed3-11ea-8ea6-5c077342e16d.png)

Hier kommt kein Tooltip.

**Comment by bjk00** [comment]
Ich schreibe es mal hier rein:
Der Tooltip "Klicken um Dokument in die Favoriten aufzunehmen" in der Dokumentenliste wird über die gesamte Breite des Eintrags angezeigt. Das Aktivieren/Deaktivieren als Favorit per Klicken funktioniert aber nur auf dem Favoritensymbol.
