### ISSUE TITLE
[FRAGE] Roter Stern?

### ISSUE THREAD

**Issue by PBaumfalk** [jlawyerorg/j-lawyer-org#573]
![image](https://user-images.githubusercontent.com/50404378/71762742-a3d76180-2ed3-11ea-9255-4228e9f01dd8.png)

Ich habe nichts gegen den roten Stern, wirkt imho aber etwas komisch. Der Stern müsste gelb sein. Oder halt j-lawyer-blau auf grauem Hintergrund.

**Comment by j-dimension** [comment]
Ich habe das kommunistische Symbol rekoloriert.

**Comment by PBaumfalk** [comment]
Danke, Genosse!

Mit freundlichen Grüßen / Kindly Regards

Patrick Baumfalk
Rechtsanwalt / Lawyer


Mobil:    +49 1525 53 04 194
E-Mail:   patrick.baumfalk@kanzlei-baumfalk.de


Baumfalk - Rechtsanwaltskanzlei
Hauptstr. 195
50169 Kerpen

Tel.: +49 2273 40 68 504
Fax: +49 2273 59 03 565

E-Mail: info@kanzlei-baumfalk.de
Web: www.kanzlei-baumfalk.de

Sent by Mobile
