### ISSUE TITLE
Akte bearbeiten ohne Anwalts-Icon

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#575]
![image](https://user-images.githubusercontent.com/29924198/71771162-4f65cd80-2f37-11ea-9883-ce54eb73d83b.png)

da rechts ist bei Anwalt kein Icon zu sehen

**Comment by j-dimension** [comment]
Das ist mehr Feature als Bug. Es gibt Kanzleien, da nutzt nur das Sekretariat die Software. Die wollen dann dort frei reinschreiben, wer Anwalt für die Akte ist. Für editierbare Dropdowns kann ich keine Icons reinrendern.

**Comment by stm9x9** [comment]
Ah! Äh, weiß das jemand, daß das editierbar ist? :-D Ich wäre nicht drauf gekommen. :)
