### ISSUE TITLE
Akte bearbeiten - was macht der gelbe Stern da rechts?

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#576]
![image](https://user-images.githubusercontent.com/29924198/71771178-77553100-2f37-11ea-9357-374af8ad5ef9.png)

Ich kann den Stern anklicken, aber es passiert nichts.

**Comment by bjk00** [comment]
Ein Klick darauf zeigt die Dokumenten-Favoriten. Solange allerdings keine Favoriten makiert sind, wird auch nichts angezeigt. 
Man kann unter Akte/Dokumente einzelne Dokumente als Favoriten markieren. Einfach auf den gelben Stern in der jeweiligen Dokumentenzeile klicken.

**Comment by j-dimension** [comment]
Danke, @bjk00  :-)

**Comment by stm9x9** [comment]
Aha.könnte

**Comment by j-dimension** [comment]
Erledigt. Ohne Ticket. Und dann erst mit 1.12 verfügbar.
