### ISSUE TITLE
Zeiterfassung

### ISSUE THREAD

**Issue by j-dimension** [jlawyerorg/j-lawyer-org#58]
**Kategorie 1 (Grundlagen)**

- [x] Akte: neuer Tab für Zeiterfassung: Tab, neues Icon erstellen - **0,25h**
- [x] Akte: neuer Tab für Zeiterfassung: Darstellung Projekte im Tab - **0,75h**
- [x] Akte: neuer Tab für Zeiterfassung: Bearbeitung Projekte - **1h**
- [x] Konfiguration: Taktung  _(1min, 5min, 10min, 15min, 30min). Es wird grundsätzlich aufgerundet._: neuer Einstellungsdialog für Zeiterfassung, Parameter "Taktung", Voreinstellung, lesen / speichern. - **0,75h**

- [x] Akte: Erstellen / Bearbeiten / Löschen von Positionen - **2h**
- [x] Akte: Anzeige aller erfassten Positionen und der Summe für jedes Projekt - **1h**
- [x] Akte: Projekt als CSV exportieren (gesamt oder selektierte Positionen - bspw. wenn für einen vergangenen Monat abgerechnet werden soll, aber bereits Einträge für den neuen / laufenden Monat getätigt wurden). _Export enthält alle Attribute der erfassten Einträge sowie Metadaten des Projektes und der Akte._ - **1,25h**
- [x] Akte: Taktung / Rundung anwenden
- [x] Akte: alle Projekte als CSV exportieren - **0,5h**
- [x] _Start-Button in Akte: Darstellung im Aktenkopf, bspw. oben rechts neben App-Sync-Button_ - **0,25h**
- [x] Start-Button in Akte: Auswahl der Zeiterfassungsposition (letzt genutzte jeweils automatisch anbieten), bspw. "Literaturrecherche 200 EUR/h". _Die Attribute der möglichen Vorauswahlen können vom Anwender angepasst werden._  - **0,75h**
- [x] Start-Button in Akte: Zeiterfassung beginnen - **0,25h**
- [x] Start-Button in Akte: prüfen, ob noch eine Erfassung für den angemeldeten Nutzer für eine andere Akte läuft, Option anbieten, diese Erfassung zu stoppen, dazu Dialog anzeigen. - **0,75h**
- [x] Ende-Button in Akte: aktuell für den Nutzer laufende Erfassung/Position speichern - Nutzer optional nochmal nachjustieren lassen: Start, Ende, Rundung entsprechend Taktung. _Jeder Eintrag enthält Projekt, Kurzbeschreibung, Kommentar, Stundensatz, Betrag, Steuersatz._ - **1h**
- [x] Client beenden: prüfen, ob noch eine Erfassung läuft, Erfassung stoppen lassen - **0,25h**
- [x] Clientstart: prüfen, ob noch eine Erfassung läuft, Erfassung stoppen lassen (bspw. nach einem Absturz des PCs o.ä., wenn Erfassung nicht ordnungemäß beendet werden konnte) - **0,25h**
- [x] aktenübergreifende Auswertung erfasster Zeiten, inklusive CSV-Export - **0,5h**
- [x] Test: Mac, Windows, Linux - **5h**
- [ ] Doku - **1h**

Kategorie 1 total = 17,5h

**Kategorie 2 (Grundlagen erweitert)**

- [x] Konfiguration: Einstellungsdialog für "Zeiterfassungspositionen" mit Name, Beschreibung, Stundensatz, Steuersatz. Das könnten dann auch allgemeine Auslagen sein, die unabhängig von einem zeitlichen Aufwand sind. Diese sind dann bei Zeiterfassung in der Akte auswählbar. - **2,5h**
- [x] Akte: Erstellen / Bearbeiten / Löschen eines neuen Zeiterfassungsprojektes / -pools. _Für ein Projekt kann auch ein bestellter Betrag erfasst werden. Die Anzeige eines Projektes in der Akte stellt bestellten und geleisteten Betrag gegenüber._ Benötigt Dialog "neues Projekt" (Name, Kontingent, Taktung aus Einstellungen auslesen, überschreibbar machen) - **1,75h**
- [x] Akte: Übernahme ausgewählter Positionen in eine Rechnung, Erstellen einer Verknüpfung zwischen Position und Rechnung - **2h**
- [x] Zeiterfassungspositionen als Tabelle in Dokument übernehmen

Kategorie 2 total = 6,25h

**Optionales**

- [x] #1977
- [x] Anzeige einer laufenden Erfassung in der Fußzeile der Anwendung - **1h**
- [x] Pausieren / Beenden einer laufenden Erfassung in der Fußzeile der Anwendung - **0,5h**

Optionales total = 3h

**Unklar**

- [x] _Klärungsbedarf: Zeiterfassungseinträge "fortführen" - genaue Ausgestaltung unklar, da ein Eintrag in der Regel Startdatum/-zeit und Enddatum/-zeit haben sollte. Wie soll bei einer Fortführung eines Eintrages die "Lücke" gehandhabt werden?_

Die Eingabe von bezahlten Kostenvorschüssen muss auch im Aktenkonto abgebildet werden - wird später implementiert, siehe https://github.com/jlawyerorg/j-lawyer-org/wiki/Finanzen

**Comment by j-dimension** [comment]
Telefonat mit Anwender, siehe 8836/20:


- mandanten selektieren
- mandat / akte selektieren
- erfassung von n items: datum, kürzel, leistung (kann über kürzel schnell erfasst werden - sind einstellbar), anzahl, einheit (zeit), preis (einzel), total, initialen (bestimmen den nutzer der geleistet hat)
- stundensätze konfigurierbar - je mandat und nutzer
- minutengenaue abrechung
- stundensätze je nach “rolle” - jeder nutzer der kanzleisoftware hat eine rolle (berater, associate, …) - in einem mandat werden die stundensätze für jede rolle eingegeben / überschrieben (standardstundensätze gibt es in globalen einstellungen).
-  anzeige aktuelle summe und aktuell geleistete zeit
- liste der positionen wird teils automatisch gepflegt - telefonate, dokumenterstellung, …
- positionen sind alle netto
- 

rechnung:
- auswahl: vorschussrechnung, teilrechnung, rechnung
- anzeige einzelpositionen mit beschreibung, sachbearbeiter
- PLUS: aggregation pro sachbearbeiter mit stundensatz - wird rein rechtlich benötigt und ist internationaler standard
- eine oder mehrere positionen selektieren
- bei rechnungserstellung bekommt die position einen haken, die bereits abgerechnet wurde
- bei rechnungerstellung kann mwst ja/nein (besser: satz?) ausgewählt werden


- rechnungsnummernkreise? - erstmal nicht benötigt

- akte hat: mandatsführer, akquisiteur, sachbearbeiter

- zeitraumsangabe: soll aus frühester und spätester position ermittelt werden


- wie wird festgehalten was schon abgerechnet ist?

- beispielabrechnung? —> senden lassen

**- in einer rechnung können verschiedene mandate abgerechnet werden!!! es wird ein mandatsübergreifender / aktenübergreifender blick auf die offenen zeiten benötigt**


bei anlage akte kann man sprache auswählen
—> dann wird bei rechnungsstellung eine entsprechende vorlage verwendet
—> beeinflusst NICHT die texte der leistungsbeschreibungen



übersicht: datum, empfänger, mandat, ausstand / summe, tage seit versand

wenn rechnung bezahlt wird: “ausbuchen” o.ä. klicken

**Comment by j-dimension** [comment]
von @stm9x9
Die Kanzleien, die mit Zeithonoraren arbeiten, haben oft je nach Mitarbeiterstatus unterschiedliche Stundensätze. Die könnte man beim Mitarbeiter hinterlegen, um die Rechnungsstellung zu vereinfachen.

Anschauungsbeispiel: https://www.a-jur.de/zeiterfassung.htm#Stufe

**Comment by j-dimension** [comment]
oder auch https://timebuzzer.com/de/

**Comment by iradraconis** [comment]
Nur so als Gedanke: ließe sich nicht die bisherige Kalender Integration erweitern für eine Zeiterfassung? Die Kalender erlauben ja schon eine sehr flexible Nutzung und einen nutzerbezogenen Aktenbezug. Bspw. gäbe es dann einen "Kalender Zeiterfassung Nutzer A". Die Akten, in denen die Zeiterfassung aktiviert ist, könnten dann automatisch oder manuell zu bestätigen einen Eintrag in diesen Kalender machen. Der Kalender ließe sich ggfs. aktenbezogen auslesen. 

Ich habe mir einige Zeiterfassungstools angesehen. Es wäre wirklich schön, sowas in j-Lawyer zu haben. Das ist vielleicht auch schneller zu realisieren als der gesamte Komplex "Finanzen".

**Comment by j-dimension** [comment]
Einstellungen: Intervalle

![grafik](https://github.com/jlawyerorg/j-lawyer-org/assets/3729754/e06fff6c-c6a7-4a8b-a37b-feff5d09e9b7)

**Comment by j-dimension** [comment]
![grafik](https://github.com/jlawyerorg/j-lawyer-org/assets/3729754/9c9f1f11-ca25-4c2b-8e45-6e58cdf0c8bf)

**Comment by j-dimension** [comment]
Demovideo für die Zeiterfassungsmaske: ein per Tastenkombination zu öffnender Dialog zeigt im linken Bereich alle Akten mit mindestens einem Zeiterfassungsprojekt. Der rechte Teil zeigt laufende Zeiterfassungen / Aktivitäten, und per Klick kann eine neue Aktivität gestartet werden.


https://github.com/jlawyerorg/j-lawyer-org/assets/3729754/5c5bff77-5b36-42d1-9665-b4eb17cbae27

**Comment by j-dimension** [comment]
Video, Einstellungen:


https://github.com/jlawyerorg/j-lawyer-org/assets/3729754/a9fe3b66-4111-4cd4-9a17-8476dd822b4a

**Comment by j-dimension** [comment]
Video, Projekterstellung und Zeiterfassung:

https://github.com/jlawyerorg/j-lawyer-org/assets/3729754/6ce769dc-fd4e-4a60-937b-5b9deaf3bc78

**Comment by j-dimension** [comment]
Video, Auswertung und Export:


https://github.com/jlawyerorg/j-lawyer-org/assets/3729754/452d17a9-ea16-4787-804a-82fefc92a486

**Comment by j-dimension** [comment]
Video, Abrechnung erfasster Zeiten:
- Akte mit drei Zeiterfassungsprojekten
- Erstellen einer Rechnung
- Importieren erfasster Zeiten - auch aus mehreren Projekten - in die Rechnung
- bei Import werden gleiche Positionen (identische Beschreibung, Steuersatz, Stundensatz) zusammengefasst - das macht die Rechnungen kompakter.
- zusätzlich zur Rechnungstabelle kann über einen Platzhalter die vollständige Zeitentabelle übernommen werden
- abgerechnete Zeiten "wissen" dass sie abgerechnet sind und werden nicht erneut für den Import in eine Rechnung angeboten
- (Vorlage sieht nicht sonderlich hübsch und strukturiert aus, ist nur zum Testen)


https://github.com/jlawyerorg/j-lawyer-org/assets/3729754/a09cec84-88d1-4d2e-85c6-fce8478e9671
