### ISSUE TITLE
Schriftgröße ändern - Tabellenformatierung

### ISSUE THREAD

**Issue by PBaumfalk** [jlawyerorg/j-lawyer-org#584]
Hallo zusammen,

super wäre noch, wenn man bei der Tabellenformatierung die Schriftgröße ändern könnte. Ich bin ein großer Freund von Arial 10 ;)

**Comment by PBaumfalk** [comment]
Ich habe das nochmal in ein ganz neues Dokument gemacht. Also komplett leer. Tabelle mit Platzhalter rein und die Schriftgröße ist immernoch 12. Die Schriftart stimmt aber.

**Comment by an-mus** [comment]
Unter Linux klappt das übrigens auch nicht ...

**Comment by j-dimension** [comment]
Hmm... dann muss ich wohl nochmal ran.

**Comment by j-dimension** [comment]
Dann müsste also 

[ ] StyledCalculationTable erweitert werden
[ ] LibreOfficeAccess erweitert werden
[ ] Das Tabellenformatierungs-Plugin erweitert werden
[ ] die Plugins selbst erweitert werden (Schrift setzen)

**Comment by PBaumfalk** [comment]
Oder man einigt sich darauf, dass man die Lieblingsschriftgröße und Schriftart der Gerichte und Staatsanwaltschaften benutzt: Arial 11. Wäre für die Erstellung der Temples an sich auch nicht schlecht, hier einen Standard zu definieren.

Aber: Ich mag auch Individualität. :-)

**Comment by PBaumfalk** [comment]
Also noch ein Hinweis:

Wenn ich "Kopieren" anklicke und dann in das Dokument einfüge, ist die Schriftgröße automatisch Arial 10...

**Comment by an-mus** [comment]
HI Jens, 
sehe ich dass richtig, dass bei der ToDo Liste vom 05.01. die Reihenfolge wichtig ist. Dass heißt du würdest mit einer kommenden Version die beiden ersten Punkte abarbeiten und ich übernehme dann die beiden letzten Punkte?

**Comment by j-dimension** [comment]
@an-mus genau, das wäre perfekt! Wenn ich die oberen beiden Punkte erledigt habe, erstelle ich ein separates Ticket für die unteren zwei im Repo j-lawyer-calculations

**Comment by iradraconis** [comment]
Bei mir kommt auch unabhängig von der im Dokument vorgegebenem Formatierung immer eine Tabelle mit Arial 12 raus. Ich hatte das als Ticket bei den rvg Plugins erstellt, aber dann gesehen, dass es das Ticket hier schon gab. Wird wahrscheinlich nix in 1.13 oder? :)

**Comment by j-dimension** [comment]
@iradraconis nein in 1.13 nicht mehr. Ich muss hier den Sack erstmal zu machen, sonst wird die Version immer größer und nie fertig.

**Comment by j-dimension** [comment]
@an-mus @iradraconis @PBaumfalk ich habe das im Ticket #120 fertig prototypisiert, da kann man sich auch ein Video anschauen. Schließe dieses Ticket hier als Duplikat.
