### ISSUE TITLE
Programmname im System

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#585]
Soll das Programm im Windows-Taskmanager so heißen wie die Webadresse (mit http sogar!)

![image](https://user-images.githubusercontent.com/29924198/71788963-a6e36680-3027-11ea-81ff-60914fc83d94.png)

**Comment by j-dimension** [comment]
Hmm... nö. Muss irgend so ein Windows-Ding sein :-)

Ich schaue mal.

**Comment by j-dimension** [comment]
Changed Windows manifest information. Not relevant for other platforms.
