### ISSUE TITLE
[BUG] Standarddrucker druckt OCR-Daten mit

### ISSUE THREAD

**Issue by PBaumfalk** [jlawyerorg/j-lawyer-org#586]
Hallo,

wenn ich Drucken (Standarddrucker) mit Linux anklicke, dann druckt der die OCR-Daten in PDF-Dateien mit. Sehr unschön, sieht aus als wäre ich betrunken. Ist kein Treiber-Problem, da der Drucker ansonsten, also wenn ich die PDF doppelt anklicke und dann drucke, sauber ausdruckt.

**Comment by j-dimension** [comment]
Wenn du WAS von WO druckst?

**Comment by PBaumfalk** [comment]
Eine PDF-Datei direkt aus der Akte zu meinem Drucker.

Mit freundlichen Grüßen / Kindly Regards

Patrick Baumfalk
Rechtsanwalt / Lawyer


Mobil:    +49 1525 53 04 194
E-Mail:   patrick.baumfalk@kanzlei-baumfalk.de


Baumfalk - Rechtsanwaltskanzlei
Hauptstr. 195
50169 Kerpen

Tel.: +49 2273 40 68 504
Fax: +49 2273 59 03 565

E-Mail: info@kanzlei-baumfalk.de
Web: www.kanzlei-baumfalk.de

**Comment by j-dimension** [comment]
Auf welchem Betriebssystem?

**Comment by PBaumfalk** [comment]
Linux.

Mit freundlichen Grüßen / Kindly Regards

Patrick Baumfalk
Rechtsanwalt / Lawyer


Mobil:    +49 1525 53 04 194
E-Mail:   patrick.baumfalk@kanzlei-baumfalk.de


Baumfalk - Rechtsanwaltskanzlei
Hauptstr. 195
50169 Kerpen

Tel.: +49 2273 40 68 504
Fax: +49 2273 59 03 565

E-Mail: info@kanzlei-baumfalk.de
Web: www.kanzlei-baumfalk.de

**Comment by j-dimension** [comment]
Hmm... da müsstest Du mir mal das Dokument zur Verfügung stellen, sofern machbar.

**Comment by PBaumfalk** [comment]
> Hmm... da müsstest Du mir mal das Dokument zur Verfügung stellen, sofern machbar.

Ich bereite dir eine unverfängliche Version vor.

**Comment by j-dimension** [comment]
Danke für die Dateien. Ich kann aktuell nicht sagen woran es liegt. An der Stelle gibt es tatsächlich kaum Programmcode - ich übergebe das praktisch nur zum Drucken. 

Wie verhält es sich mit dem **selben** Dokument auf macOS oder Windows?

**Comment by PBaumfalk** [comment]
Wird ganz normal gedruckt. Vielleicht macht Linux ja mit der PDF-Datei irgendwas. Auf jeden Fall wird beim Öffnen des PDF-Programms und anschließendem Drucken kein Doppler-Effekt ausgelöst.

Mit freundlichen Grüßen / Kindly Regards

Patrick Baumfalk
Rechtsanwalt / Lawyer


Mobil:    +49 1525 53 04 194
E-Mail:   patrick.baumfalk@kanzlei-baumfalk.de


Baumfalk - Rechtsanwaltskanzlei
Hauptstr. 195
50169 Kerpen

Tel.: +49 2273 40 68 504
Fax: +49 2273 59 03 565

E-Mail: info@kanzlei-baumfalk.de
Web: www.kanzlei-baumfalk.de

**Comment by Maz111111** [comment]
Also ich habe unter Win10 dieselbe Erscheinung. pdf mit ocr drucke ich nur aus dem pdf Programm (bei mir Abbyy) direkt. Also vorher öffnen.
Ich dachte, dass das am Scanner liegt (nutze brother).

**Comment by j-dimension** [comment]
Der Direktdruck ist via LibreOffice implementiert, und da scheint es wohl Probleme mit bestimmten PDFs zu geben: https://ask.libreoffice.org/en/question/74934/how-do-i-open-exisiting-pdf-without-ocr-interpretation/

**Comment by j-dimension** [comment]
Alternative: PDFBox zum Drucken von PDFs: https://stackoverflow.com/questions/16293859/print-a-pdf-file-using-printerjob-in-java

**Comment by PBaumfalk** [comment]
Dann wäre doch, wenn PDFBox keine Probleme macht, dieses Programm besser geeignet. Oder?

Ferner:
PDFBox kann stempeln (Overlay). Ich kann dir dafür DINA4-Vorlagen geben. Habe ich hier.

**Comment by j-dimension** [comment]
Ja, PDFBox ist bereits als Abhängigkeit im Client drin, zwecks Darstellung von PDFs. 
Das Drucken müsste ich allerdings entsprechend entwickeln / umsetzen und auf allen drei Plattform (macOS, Linux, Windows) testen. 

Ticket ist ja schon in der 1.12 :-)

**Comment by PBaumfalk** [comment]
Beim Testen unterstütze ich auf allen drei Betriebssystemen!

Mit freundlichen Grüßen / Kindly Regards

Patrick Baumfalk
Rechtsanwalt / Lawyer


Mobil:    +49 1525 53 04 194
E-Mail:   patrick.baumfalk@kanzlei-baumfalk.de


Baumfalk - Rechtsanwaltskanzlei
Hauptstr. 195
50169 Kerpen

Tel.: +49 2273 40 68 504
Fax: +49 2273 59 03 565

E-Mail: info@kanzlei-baumfalk.de
Web: www.kanzlei-baumfalk.de

Sent by Mobile

**Comment by j-dimension** [comment]
@PBaumfalk gibt es mit der neuesten LibreOffice-Version diese Probleme immer noch?

**Comment by Mucki526** [comment]
Ich habe das gleiche Problem mit Windows 10 64 bit. Der direkte PDF-Druck macht "Doppebilder und merkwürdige Zeichen", aber nicht bei allen PDF, beim Öffnen des Dokuments z.B. mit Foxitreader und dann drucken ist alles gut. Libre Office 7.052 ist aktuell installiert. Dachte erst der Drucker ist kaputt, dann der Treiber.
