### ISSUE TITLE
Kontextmenü aufräumen

### ISSUE THREAD

**Issue by Maz111111** [jlawyerorg/j-lawyer-org#587]
Nachdem man die Favoritenfunktion über einen einfachen Mausklick ein- und ausschalten kann (Superfunktion - vielen Dank), bedarf es des Menüpunktes bei der rechten Maustaste nicht mehr.
Damit könnte das Kontextmenü ein wenig aufgeräumt werden.

Nach Wikipedia sind in solchem Kontextmenüs wohl nur die jeweiligen Funktionen beinhaltet, die für das gewählte Objekt aktuell sinnvoll und machbar sind.
Da es zum einen für Drebis ein separates Button gibt und diese Funktion zum anderen wohl nicht den eben benannten Voraussetzungen entspricht (sie ist nicht objektabhängig), wäre es aus meiner Sicht auch gut, die Drebisfunktionen aus dem Menü zu entfernen, um es übersichtlich zu halten.

Ferner könnte man prüfen, dass nur die Funktionen eingeblendet werden (oder ausgegraut werden) die tatsächlich auch möglich sind - Fax nur, wenn auch Faxfunktion vom Anwender definiert wurde; bea nur, wenn Anwender Sendeberechtigung hat; Mail nur, wenn auch Mail eingerichtet ist etc.

Alles nur Kosmetik

**Comment by j-dimension** [comment]
> Nach Wikipedia sind in solchem Kontextmenüs wohl nur die jeweiligen Funktionen beinhaltet, die für das gewählte Objekt aktuell sinnvoll und machbar sind.
> Da es zum einen für Drebis ein separates Button gibt und diese Funktion zum anderen wohl nicht den eben benannten Voraussetzungen entspricht (sie ist nicht objektabhängig)

Wenn man die Drebisaktionen über das Kontextmenü startet, dann werden die selektierten Dokumente mit der Drebisanfrage versendet.

**Comment by j-dimension** [comment]
> bea nur, wenn Anwender Sendeberechtigung hat

Eine solche Berechtigung gibt es nicht. Und da die Anwendung nicht weiß, ob der User mit Kartenanmeldung arbeitet, wäre es praktisch immer möglich, per beA zu versenden.

**Comment by j-dimension** [comment]
> Nachdem man die Favoritenfunktion über einen einfachen Mausklick ein- und ausschalten kann (Superfunktion - vielen Dank), bedarf es des Menüpunktes bei der rechten Maustaste nicht mehr.

Das würde ich gern drinlassen. Der Kontextmenüeintrag funktioniert auch für Mehrfachselektionen.

**Comment by j-dimension** [comment]
> Fax nur, wenn auch Faxfunktion vom Anwender definiert wurde; Mail nur, wenn auch Mail eingerichtet ist etc.

Das kann man machen.

**Comment by Maz111111** [comment]
Wegen der einen Sache ist das nicht nötig.
Ich schlag dann vor, hier zu zu machen .-)
