### ISSUE TITLE
Spezifischere Fehlermeldung bei beA-Blacklisting der Version

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-org#588]
Meine Frau war heute konsterniert,weil das BEA Im J-lawyer meldete, nicht funktionieren zu dürfen (falsche Clientversion). Herauszufinden, woran das liegt, damit war meine Frau als IT-Phobes-Wesen nachvollziehbar überfordert. Sinnvoll wäre daher, dass bei einer Neuversion im Client beim Starten ein entsprechender Hinweis eingeblendet und z.B. gleich der Download und Installation angeboten wird. Wäre hilfreich. Bei vielen Rechnern im Netz verliert man dann auch nicht den Überblick, wo das Update schon erfolgt ist.

**Comment by j-dimension** [comment]
Die Anwendung prüft beim Start und zeigt dann mit einem Symbol in der Statusleiste unten sowie im Infobereich ganz oben am Desktop an, dass es ein Update gibt. 

Es poppt nichts auf, ja. Wenn ich aber sehe wie konservativ manche Anwender updaten, dann würde ein Popup wohl wieder nicht gut ankommen...

Ich denke mal drüber nach.

**Comment by PBaumfalk** [comment]
Bitte kein Popup. Lieber ein dezenter Hinweis auf Twitter oder in einem Newsletter und unten in der Statusleiste.

Mit freundlichen Grüßen / Kindly Regards

Patrick Baumfalk
Rechtsanwalt / Lawyer


Mobil:    +49 1525 53 04 194
E-Mail:   patrick.baumfalk@kanzlei-baumfalk.de


Baumfalk - Rechtsanwaltskanzlei
Hauptstr. 195
50169 Kerpen

Tel.: +49 2273 40 68 504
Fax: +49 2273 59 03 565

E-Mail: info@kanzlei-baumfalk.de
Web: www.kanzlei-baumfalk.de

**Comment by Mucki526** [comment]
Der Durchschnittsuser (auch wenig liebevoll "DAU" genannt"),  startet die Anwendung, wenn er nicht den Rechner die ganze Woche sowieo durchlaufen lässt, und sieht den dezenten Hinweis in der Statusleiste nie - weil er oft auch garnicht weiss, was eine Statusleiste ist. Wenn schon sollte der Hinweis Grün und rot blinken...  Eine Kette ist immer nur so stark wie ihr schwächstes Glied - und das schwächste Glied sitzt erfahrungsgemäß in vielen Fällen halt regelmäßig 45 cm hinter der Tastatur in der Person des Anwenders... Fettes Hinweisschild "keine Panik, Kaffee trinken, Updatemachen ja / nein, aber dann kein BEA / eingeschränkte Funktion",  schützt die Daten, den User und den Programmierer der Software (nervlich, d.h. vor Verwünschungen, e-mails und anderen Hilferufen). Der erfahrene User, der meint, dass er keinen Warnung braucht, weil ihm der Dauerhinweis in der Statuszeile reicht, kann den Wink mit dem Zaunpfahl ja dann z.B.evt. temporär für Zwischenupdates in den Einstellungen abschalten. Meine Meinung...

**Comment by stm9x9** [comment]
kann man ein popup nicht so einrichten, daß es auf Wunsch nicht wieder kommt, bis es eine neue neue Version gibt?

**Comment by j-dimension** [comment]
Kann man alles machen, ist ja nur Software.

Aber wie bei einigen anderen Tickets frage ich mich: hat das gegenüber den anderen eine solche Priorität? Letztlich wären das auch 45min Aufwand, die ich eigentlich lieber in neue Funktionalität stecken würde.

**Comment by stm9x9** [comment]
Das müssen andere beantworten, ich wollte nur einen Mittelweg aufzeigen wegen der Nerv-Faktor-Frage.

Aber vielleicht reicht ja auch was ganz anderes:

beim beA-Fehler "falsche Clientversion" den Text erweitern:

Bitte prüfen Sie unter xLinkx ob eine neue Version des j-l-Clients vorhanden ist oder unter xLinkx ob es aktuelle Meldungen zu j-l gibt!

**Comment by j-dimension** [comment]
I love it! Gute und schnelle Lösung.
