### ISSUE TITLE
Gruppenbasierte Zugriffsbeschränkung für Akten

### ISSUE THREAD

**Issue by j-dimension** [jlawyerorg/j-lawyer-org#59]
auf Aktenlevel, bearbeitbar für Anwalt und Sachbearbeiter der Akte

**Comment by j-dimension** [comment]
siehe https://www.j-lawyer.org/?topic=begrenzte-einsichtsrechte-fuer-sachbearbeiter-moeglich

**Comment by RA-crm** [comment]
Ich verstehe das als Aktenkreise, sodass zB ein Kreis alle normalen Akten sind; ein andere umfasst die Absrechnungen (wenn man diese von den normalen Akten trennt), ein weiterer umfasst die Kanzleiorga (Verträge mit Zulieferen, Vermieter, Leasinggeber) und noch ein Aktenkreis umfasst das Personal (Mitarbeiterakten, Bewerbungen)

**Comment by j-dimension** [comment]
- Neuer Einstellungsdialog: Gruppenverwaltung. Dort werden erstmal nur die Gruppen definiert. Beim Löschen von Gruppen muss eine Prüfung stattfinden, ob die Gruppe noch als berechtigte Entität an einer Akte dranhängt. Das Anlegen einer Gruppe prüft lediglich auf Eindeutigkeit. Das Bearbeiten einer Gruppe prüft lediglich auf Eindeutigkeit.
- Die Gruppenverwaltung ist nur für Administratoren verfügbar.
- In der Nutzerverwaltung muss es einen neuen Tab "Gruppenmitgliedschaften" geben. Ein Nutzer kann dort 0..n Gruppen zugeordnet werden.
- In der Nutzerverwaltung gibt es ein **optionales** Attribut für "Standardgruppe für neue Akten" (0..n Gruppen). Ist es leer, so werden neu angelegte Akten nicht durch Gruppenberechtigungen geschützt. Ist es gesetzt, so erhalten von DIESEM Nutzer angelegte Akten automatisch die angegebenen Einschränkungen auf Gruppen.
- Lediglich der Zugriff auf Akten mit allen dazugehörigen Elementen (Wiedervorlagen, Dokumente) ist durch Gruppenmitgliedschaften restriktiert. 
- Eine Gruppe restriktiert den Zugriff auf Akten. Das Recht zum Schreiben / Lesen ... bleibt vorerst ein globales Recht. Man hat also auf Basis der Gruppenmitgliedschaften entweder KEINEN Zugriff auf eine Akte, oder man hat Zugriff und darf exakt das ausführen, was in der Nutzerverwaltung als (gruppenunspezifische) Berechtigung hinterlegt ist. 
- Adressen, Vorlagen etc. sind gruppenunabhängig allein auf Basis der bereits vorhandenen Berechtigungen in der Nutzerverwaltung nutz- und veränderbar.

**Comment by RA-crm** [comment]
Für mich wäre wichtig, dass die Akten aus den jeweiligen andere Az haben, damit jeweils klar ist, wo die Akte hingehört. Idee: Gruppenkürzel an das Aktenzeichen und jede Gruppe zählt selbständig seine Akten durch

Mit Blick auf den Umstand, dass "das Recht zum Schreiben / Lesen [...] vorerst ein globales Recht" bleibt, stellt sich die Frage, wie mit eingehenden Mails und Dokumenten etc umgegangen werden soll. Im Zweifel muss der Scann oder die Mail mit einem Attribut getagged (etikettiert) werden, der dem Admin oder dem anderen Gruppenverantwortlichen zu Zuordnung zur Akte als ToDo zuweist.

Wenn Adressen auch nur auf Gruppenbasis nutzbar sind, kann man Adressen mehreren Gruppen zuordnen?

Möglich wären also Gruppen wie: -intern -organisation -kanzleiverträge -personal -buchhaltung?

**Comment by j-dimension** [comment]
> Für mich wäre wichtig, dass die Akten aus den jeweiligen andere Az haben, damit jeweils klar ist, wo die Akte hingehört. Idee: Gruppenkürzel an das Aktenzeichen und jede Gruppe zählt selbständig seine Akten durch

Dazu habe ich gestern auch ein Grobkonzept gemacht: #369 
Allerdings plane ich dort mit globalen laufenden Nummern etc. 

> Wenn Adressen auch nur auf Gruppenbasis nutzbar sind, kann man Adressen mehreren Gruppen zuordnen?

Nein, die Adresse plane ich nicht explizit zu "schützen". Das Gruppen-Feature wird erstmal nur auf Akten mit allem was dazugehört angewandt.
 
> Möglich wären also Gruppen wie: -intern -organisation -kanzleiverträge -personal -buchhaltung?

Ja.

**Comment by PBaumfalk** [comment]
Kanzleiinterne Altenzeichen fände ich auch gut.

Mit freundlichen Grüßen / Kindly Regards

Patrick Baumfalk
Rechtsanwalt / Lawyer


Mobil:    +49 1525 53 04 194
E-Mail:   patrick.baumfalk@kanzlei-baumfalk.de


Baumfalk - Rechtsanwaltskanzlei
Hauptstr. 195
50169 Kerpen

Tel.: +49 2273 40 68 504
Fax: +49 2273 59 03 565

E-Mail: info@kanzlei-baumfalk.de
Web: www.kanzlei-baumfalk.de

Sent by Mobile

**Comment by j-dimension** [comment]
Testen: Referenzen und kaskadierendes Löschen

**Comment by j-dimension** [comment]
Dokumentation:

- Eigentümergruppe nur von Nutzern bearbeitbar, die in der aktuellen Eigentümergruppe sind
- berechtigte Gruppen nur von Nutzern bearbeitbar, die in der Eigentümergruppe sind
- Eigentümergruppe nur auf eine Gruppe änderbar, in der man selbst Mitglied ist
