### ISSUE TITLE
beA: Anhangstyp

### ISSUE THREAD

**Issue by Maz111111** [jlawyerorg/j-lawyer-org#591]
Ich hoffe, ich hab es nicht übersehen und es gibt das nicht schon...
Ich habe beim beA Versand als Anhangstyp "Schriftsatz" angeklickt. Die Bezeichnung im Alias ändert sich auch prompt.
Im beaWeb wird trotzdem für alles (auch für den Schriftsatz) als Anhangstyp "Anlage" angezeigt.

Hier würde ich jetzt einen Screenshot einfügen. Ich weiß aber nicht, wie :-(

Ich weiß nicht inwiefern dies tatsächlich rechtlich problematisch wird. Aber man sollte es wohl zur Sicherheit zeitnah fixen.

**Comment by j-dimension** [comment]
Ticketthema: schaue ich mir an.

Screenshots einfügen: einfach kopieren und dann per Strg+V einfügen? :-)

**Comment by stm9x9** [comment]
Rechtlich problematisch wohl überhaupt nicht, weil diese Information nach allen mir bekannten Quellen beA nie verläßt. Ich bin mir nichtmal sicher, ob es innerhalb von beA an einen anderen Anwalt weitergegeben wird.

in beAweb ist das nur, damit beAweb warnen / verhindern kann, daß jemand anderes als der Postfachinhaber (also zb ein Reno) ein nicht-signiertes Dokument verschickt, daß als Schriftsatz bezeichnet wurde. Da beAweb an dieser Stelle inline signierte pdfs nicht erkennt sondern nur mit externen p7s-Datei, würde er bei mir immer meckern, weil ich oft im Postfach eines Kollegen versende. Daher ist bei mir alles "Anhang". Das hat noch kein Gericht gestört. Und wie gesagt, AFAIK ist das in dem Strukturdatensatz gar nicht enthalten diese Info.

**Comment by Maz111111** [comment]
Gut zu wissen. Danke.

**Comment by j-dimension** [comment]
Bevor ich schliesse, werde ich nochmal das Verhalten i. Zshg. mit dem Strukturdatensatz prüfen.

**Comment by Maz111111** [comment]
Ich denke nicht, dass die Problematik so gelassen werden sollte. Also bitte nicht schließen, sondern nach Möglichkeit korrigieren.
Es mag zwar auf den ersten Blick rechtlich nicht dramatisch sein. Das kann aber keiner mit Sicherheit sagen.
Ich bin hier eindeutig dafür, den Schriftsatz auch als Schriftsatz im Sinne des beA zu Kennzeichnen. Man kann einfach nicht vorhersehen, ob bei irgendeiner Entscheidung des BGH dann nicht doch genau dieses Problem zur Falle wird.
Letztlich werden - wenn man es als Empfänger / Richter so sehen will - eben nur Anlagen an das Gericht gesendet.
Ich würde dieses Risiko als Anwalt nicht eingehen.

**Comment by stm9x9** [comment]
Wie schon gesagt, wenn diese Information nicht im Strukturdatensatz stehen sollte (wie von mir postuliert), dann kann es keine rechtliche Relevanz haben, weil rein praktisch das Gericht diese Information niemals zu Gesicht bekommt.

Das hier ist der Strukturdatensatz einer Nachricht via beAweb an ein Testgericht. Ein Anhang ist Anlage, einer Schriftsatz. Ich sehe keinen Unterschied. Außer daß es einmal png und einmal pdf ist.

 

>   <tns:dokument>
>         <tns:identifikation>
>             <tns:id>91dcd8fb-341d-4304-9756-7cf885ec8880</tns:id>
>         </tns:identifikation>
>         <tns:dokumententyp listVersionID="2.1">
>             <code>001</code>
>         </tns:dokumententyp>
>         <tns:anzeigename>ss</tns:anzeigename>
>         <tns:akteneinsicht>true</tns:akteneinsicht>
>         <tns:datei>
>             <tns:dateiname>Paragraph.pdf</tns:dateiname>
>             <tns:dateiformat listURI="urn:xoev-de:xdomea:codeliste:dateiformat" listVersionID="">
>                 <code>018</code>
>             </tns:dateiformat>
>             <tns:bestandteil listVersionID="2.1">
>                 <code>001</code>
>             </tns:bestandteil>
>         </tns:datei>
>         <tns:ruecksendung_EEB_erforderlich>false</tns:ruecksendung_EEB_erforderlich>
>     </tns:dokument>
>     <tns:dokument>
>         <tns:identifikation>
>             <tns:id>7cae57be-721f-442c-8d0a-66fc88eb3507</tns:id>
>         </tns:identifikation>
>         <tns:dokumententyp listVersionID="2.1">
>             <code>001</code>
>         </tns:dokumententyp>
>         <tns:anzeigename>aaanlage</tns:anzeigename>
>         <tns:akteneinsicht>true</tns:akteneinsicht>
>         <tns:datei>
>             <tns:dateiname>Paragraph.png</tns:dateiname>
>             <tns:dateiformat listURI="urn:xoev-de:xdomea:codeliste:dateiformat" listVersionID="">
>                 <code>019</code>
>             </tns:dateiformat>
>             <tns:bestandteil listVersionID="2.1">
>                 <code>001</code>
>             </tns:bestandteil>
>         </tns:datei>
>         <tns:ruecksendung_EEB_erforderlich>false</tns:ruecksendung_EEB_erforderlich>
>     </tns:dokument>

**Comment by Maz111111** [comment]
Es mag sein, dass das bei Gerichten so ist. Aber auch da wäre ein Richter, der mir das Leben schwer machen will, nicht auf der Rechnung.
Außerdem nutzte ich beA ja auch, um an Kollegen zu senden. Mir ist der Strukturdatensatz beim Empfang völlig egal. Und dann kommt der neunmalkluge Kollege.
Wenn ich an einen Kollegen etwas sende, um mit dem Zugang des Schreibens einen Stichtag (Zahlung des Unterhalts ab dem ersten des Zugangsmonats) herbeizuführen und beim Kollegen kommen nur Anlagen an, wird mir der besagte neunmalkluge Kollege irgendwann in den nächsten Monaten schreiben, dass meiner beA Nachricht leider kein Schriftsatz beilag und er die Anlagen daher gar nicht erst geöffnet hat.
Das will ich nicht erst mit dem eigenen Mandanten und dann ggf. auch noch mit ungewissem Ausgang vor Gericht diskutieren müssen.
Safety first!
