### ISSUE TITLE
[bea] Nachricht und Journal drucken

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-org#592]
Es fehlt mir 10 Mal am Tag die Möglichkeit, die BEA Nachricht und das Journal der Versendung, am besten auf einem Blatt ausdrucken zu können....

**Comment by stm9x9** [comment]
Was konkret wollen Sie mit dem Journal? Das zeigt den Eingang beim Empfänger AFAIK nicht an.

**Comment by Mucki526** [comment]
Zum Einen - wenn ich direkt eine Nachricht ins Nachrichtenfenster bei BEA schreibe, kann ich den Inhalt der Nachricht nicht ausdrucken für die Akte. Ich muss jedesmal einen Screenshot machen. Ich nutze das aber inzwischen wie e-mail und mache nicht erst einen Schriftsatz den ich dann anhänge. Bei e-mail kann ich wenigstens einen Ausdruck mit dem externen Mailprogramm machen. Hier sehe ich meine Nachricht im Reiter neben dem Journal, kann aber nicht drucken.

Mit dem Journal selbst kann ich nach meinem Verständnis den Nachweis führen, dass die Versendung erfolgreich gewesen ist. Das ist doch IMHO zumindest so, wenn nicht besser, wie das Sendejournal Fax, d.h. im Zweifel ein Widereinsetzungsgrund, wenn eine erfolgreiche Übermittlung bescheinigt wird. Ich halte das für ziemlich wichtig, z.B. bei Notfristenwahrung. Wozu brauche ich sonst das Journal??? 

Bietet das BEA denn keine Möglichkeit für den Nachweis zu führen, dass die Nachricht beim Gericht eingegangen ist????

**Comment by j-dimension** [comment]
Ein sicherer Nachweis ist aktuell nur mit dem aus der Webanwendung exportierbaren ZIP zu führen. 

Die Schnittstelle der BRAK bietet einen solchen Export aber nicht - es ist schlicht nicht im Funktionsumfang der Schnittstelle. War für "Mitte 2019" versprochen, wurde aber bisher nicht geliefert.

Gleiche Diskussion übrigens in https://github.com/jlawyerorg/j-lawyer-org/issues/412

**Comment by stm9x9** [comment]
Meines Wissens nach ist auch mit dem zip kein Nachweis möglich, weil die Signaturdatei kaputt ist.

**Comment by j-dimension** [comment]
> Meines Wissens nach ist auch mit dem zip kein Nachweis möglich, weil die Signaturdatei kaputt ist.

Ich kenne die Thematik. Die BRAK hat sich m.W. dazu nicht geäußert. Und selbst wenn es der Fall wäre: es würde die KSW dann nicht tangieren, da die Implementierung dann allgemeint kaputt ist :-)
