### ISSUE TITLE
Authentifizierung und Autorisierung: Cache wird nicht invalidiert

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#594]
Wenn ich als Admin das Paßwort eines Mitarbeiters (auch admin selber) ändere, dann kann man sich mit dem alten Paßwort so lange noch und wiederholt einloggen, bis das erste Mal das neue Paßwort verwendet wird.

**Comment by j-dimension** [comment]
?! Überraschend!

Muss ich mir anschauen.

**Comment by j-dimension** [comment]
cache-type einer security-domain?
https://docs.wildfly.org/16/Admin_Guide.html#Security

Evtl. Auswirkung auf Performance (jeder Request würde authentifiziert) - lieber explizites Flush?

**Comment by j-dimension** [comment]
https://developer.jboss.org/thread/263210

**Comment by j-dimension** [comment]
Cache type infinispan mit Parametrisierung für Invalidierung testen

**Comment by j-dimension** [comment]
neben Passwort- auch Rollenänderung betroffen
