### ISSUE TITLE
Reiter - Nachweis des Zugangs der Nachricht mit Anlagen bei Gerichts und Ausdrucksmöglichkeit

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-org#595]
"Das beA verarbeitet und protokolliert jeweils den Versand- und Empfangszeitpunkt einer Nachricht. Durch interne Signaturen wird zudem die Authentizität und Integrität einer Nachricht sichergestellt. Ob eine beA-Nachricht beim Empfänger zugegangen ist, lässt sich daher ganz einfach prüfen und auch in elektronischer Form nachweisen.

Und so geht’s:

1. Klicken Sie in dem jeweiligen Postfach (1) auf den Ordner „Gesendet“ (2). In der Nachrichtenübersicht sehen Sie in den Spalten „Gesendet“ und „Zugegangen“ (3) das jeweilige Datum. In der Spalte „Übermittlungsstatus“ (4) ist dann „Erfolgreich“ vermerkt." 

Sowas fehlt mir also im J-Lawyer, ich dachte bisher, das wäre das "Journal"

**Comment by j-dimension** [comment]
Die im beA an dieser Stelle angezeigten Informationen sollten aus dem Journal stammen und somit auch in j-lawyer.org verwertbar sein. 

Jedoch: es macht einen Unterschied, ob von beA an beA (also zwischen Anwälten) kommuniziert wird, oder von beA an EGVP (Gerichtspostfach). Im zweiten Fall benötigt man die sogenannten Laufzettel. 

Die Schnittstelle der BRAK hat an dieser Stelle einen Fehler: https://github.com/jlawyerorg/j-lawyer-org/issues/305

Und bitte nicht so viele Tickets zum gleichen Thema, jetzt haben wir schon #412, #592 und #595.

**Comment by stm9x9** [comment]
Zumindestens in beAweb ist es so, daß die Tatsache, daß die Nachricht in gesendet liegt, schon hinreichender Nachweis des Zugangs (nicht des Zeitpunkts) ist, weil Nachrichten mit Problemen in Postausgang hängen bleiben (und dort steht dann nicht "erfolgreich" sondern ein Fehler.

Ist das bei der API ggf auch so? Alles was es in gesendet geschafft hat, hatte keine Fehler?

**Comment by j-dimension** [comment]
Nach meinem Verständnis ja. Der beA-API-Client (also die Kanzleisoftware) verschiebt nach dem Senden nicht selbst in "Gesendet" (wie es bspw. bei E-Mail im Falle von IMAP ist).
