### ISSUE TITLE
Vorlage mit Doppelklick öffnen

### ISSUE THREAD

**Issue by Maz111111** [jlawyerorg/j-lawyer-org#598]
Wäre es möglich, dass man die Vorlage im "Erstellen" Dialog mit Doppelklick erstellt und die befüllte Vorlage dann auch gleich geöffnet wird?

**Comment by j-dimension** [comment]
Du meinst im Dokument erstellen-Dialog? (nicht Vorlage)

**Comment by Maz111111** [comment]
Ja, wenn in der Akte ein Dokument aus einer Vorlage erstellt wird.

**Comment by j-dimension** [comment]
Das könnte ich als Option / Checkbox einbauen im Dialog. Das Doppelklick spart tatsächlich keinen Klick, aber das direkte Öffnen fänd ich auch cool.

**Comment by Maz111111** [comment]
Der Doppelklick mag zahlenmäßig keinen Klick sparen (Komma Aber) die Maus liegt einmal auf der zu öffnenden Datei. Dann ist der Doppelklick einfach schneller. Aktuell nutze ich (meist nach erfolglosem Versuch des Doppelklicks - irgendwie ist das in meinem Finger drin) die Entertaste, weil das immer noch schneller ist, als wenn ich mit der Maus das Button "Erstellen" suche und ansteuere.
Das liegt vermutlich daran, dass das "normale" Öffnen der Dokumente im DokReiter eben mit Doppelklick geht.
Wenn ich schon mit Klickzählen nicht weiterkomme :-) dann vielleicht mit Intuition der KSW und Konsistenz.

**Comment by j-dimension** [comment]
D.h. Du lässt Dateiname und Auswahl Beteiligter immer bei den Voreinstellungen und machst keine weiteren Eingaben (WV, ...)?

**Comment by Maz111111** [comment]
in der Regel mache ich da nichts weiter. Die Vorlagen haben aussagekräftige Namen. Der Sinn, mit der Erstellung eines Dokuments direkt eine WV einzutragen, hat sich mir bisher nicht erschlossen.
Es gibt Vorlagen, bei denen ich den Namen ändere. Das sind die Vorlagen, die ein leeres aktenbezogenes Dokument erstellen.
Über die Möglichkeit auch die Namen automatisch einfügen zu lassen ist das alles ziemlich einfach.
Bsp.: Schreiben an GEGNER (Gegner) leer aktenbezogen - hier würde ich eingreifen
Schreiben an DRITTE (Gegnervertreter) per beA - hier nicht
Schreiben an MANDANT (Mandant) per Mail - Übersendung VA Auskünfte GEGNER - hier auch nicht

**Comment by stm9x9** [comment]
Klassischer Fall für eine WV: Schreiben an Mandat wegen Nachfragen des Gerichts: WV "Rücklauf Mdt?"

**Comment by j-dimension** [comment]
Ich meine dass der Button "Erstellen und Öffnen" hier schon einen besseren Arbeitsfluss ermöglicht und schließe an der Stelle.
