### ISSUE TITLE
j-lawyer.org mobile App

### ISSUE THREAD

**Issue by j-dimension** [jlawyerorg/j-lawyer-org#60]
**Iteration 1:**

Querschnittsaspekte:
- [ ] responsive (Smartphone vs. Tablet)
- [ ] iOS und Android
- [ ] Viewer - vorerst keine Aktenbearbeitung
- [ ] Querschnittsaspekt: Authentifizierung über http basic (im Header, nicht als Teil der URL)
- [ ] Querschnittsaspekt: Unterstützung mehrerer j-lawyer.org-Versionen (zumindest aktuelle und Vorgänger) - dazu müsste eine App die Version der REST-API auslesen (dazu gibt es bereits einen API-Call) und ihr eigenes Verhalten anpassen

Funktionalität:
- [ ] Funktionalität: sichere Offline-Speicherung der Daten
- [ ] Funktionalität: automatische (in Intervallen) und manuelle Synchronisation der Offline-Daten
- [ ] Funktionalität: nur solche Daten synchronisieren, die zur Synchronisation im Rich Client markiert worden sind. Der Ablauf wäre: Nutzer aktiviert innerhalb der Akte die Synchronisation für sich oder einen anderen Nutzer. Bei Nutzung der App (oder intervallbasiert im Hintergrund) wird eine API gerufen, welche Akten synchronisiert werden sollen, Synchronisation wird durchgeführt.
- [ ] Funktionalität: Öffnen von Dokumenten einer Akte. Da es eine Vielzahl an Dateiformaten gibt, werden die verfügbaren Apps zu einem Dateityp ermittelt und genutzt. Keine Implementierung in der App selbst.
- [ ] Funktionalität: Beteiligten anrufen
- [ ] Funktionalität: innerhalb der App eine Akte aus der "Synchronisationsliste" entfernen (wie handhaben, wenn Server nicht erreichbar?)
- [ ] Funktionalität: "Teilen" von Dokumenten, um sie bspw. in einer anderen App zu nutzen (per Mail-App versenden o.ä.)

User Interface:
- [ ] Hauptscreen: Liste mit Akten, Filterung / Suche möglich, Sortierung absteigend nach letzter Änderung
- [ ] Detailscreen(s): (fast) alle Daten der Akte zugänglich machen. Ausnahmen: Falldatenblätter, Historie(?), Handakte

Einstellungen:
- [ ] API-Endpunkt, Nutzer, Passwort (sichere Ablage im Gerät, oder bei Start der App immer abfragen)
- [ ] ggf. Synchronisationsintervall

unterstützende Arbeiten (@j-dimension) im j-lawyer.org Hauptprojekt, die noch ohne Ticket sind:

- [ ] Aktivieren der Aktensynchronisation für einen Nutzer
- [ ] REST API für Ermittlung der zu synchronisierenden Akten des anfragenden Nutzers
- [ ] REST API für das Ändern des Synchronisationsflags einer Akte für den anfragenden Nutzer
- [ ] GitHub-Repository
- [ ] Continuous Integration Pipeline (GitHub Actions) für Android, iOS

---------------------------------------------------------

**Iteration 2: (vorerst nicht im Detail geplant)**

Kommentare / Notizen erstellen und auf Backend zurückspeichern
WV / Fristen / Termine mobil erfassen und auf Backend zurückspeichern

**Comment by stm9x9** [comment]
Wenn sich da nicht noch eine andere Lösung finden lassen sollte - ich bevorzuge immer noch eine Anbindung /Export an google, ms, sonstwas-Kalender - dann wäre ein Einsatzzweck für Handygröße die Auflistung / kalendermäßige der Fristen.

**Comment by Maz111111** [comment]
Es wäre auch eine App für Windows Tablets (Surface - Lenovo) schön.
Die App sollte die Dokumente einer Akte auf Anforderung laden, aufbereiten und anzeigen können.
Es wäre schön, wenn man in der App so blättern könnte, wie in einer Papierakte und auch Notizen wie in der Papierakte machen könnte.
Soweit im "großen Client" Ordnerstrukturen in einer Akte verfügbar sind (#122) und auch angelegt wurden, sollten diese auch in der App nutzbar sein.
Vielleicht ginge eine PenUnterstützung auf Tablets, die so etwas haben. Dann könnte die Terminsmitschrift in Schreibschrift wie gewohnt erfolgen.
Anbindung an GoogleKalender - wie in Thunderbird - wäre auch gut, damit mit dem Gericht Termine abgestimmt werden können.
Die Änderung von Mandantenanschriften o.Ä. wäre nicht zwingend - aber wohl auch nicht schlecht.

**Comment by Dickmaulruessler** [comment]
Bitte haltet eure Wünsche doch in einem realistischen Rahmen. Unser Chef (Jens) macht das alles in seiner Freizeit <3

**Comment by Maz111111** [comment]
> Ticket dient der Anforderungssammlung - was muss eine solche App können?

Genau dies sollte mein comment darstellen

Jens wird entscheiden, was er umsetzt bzw. was umsetzbar ist.

**Comment by Dickmaulruessler** [comment]
mir würde ein bloßer Viewer und eine manuelle "Mitnahme"-möglichkeit von der jeweiligen Akte zum Termin genügen.

**Comment by Maz111111** [comment]
Also PenUnterstützung ist sicher Traumzauberei. ;)
Aber ein bloßer Viewer wäre IMO den Aufwand nicht wert.
Das kann man doch eigentlich jetzt mit dem Export schon machen. 
Akte exportieren - auf das Tablet laden - dort im entsprechenden Viewer ansehen.

**Comment by stm9x9** [comment]
Fristenübersicht und Dokumente lesen können, wäre mir am Handy(!) am wichtigsten

**Comment by jannis2200** [comment]
Eine Idee, die ich aus eigenen Anwendungszwecken vorerst hilfreich fände, bis eine offizielle App besteht: Export in WebDav! Damit könnte man einfach den Kalender in Nextcloud Syncen und dann mit dem iPhone oder Android-Telefon oder Online abrufen. Und man hätte eine Integration direkt in die Systemkalender und CarPlay.

**Comment by jannis2200** [comment]
> Eine Idee, die ich aus eigenen Anwendungszwecken vorerst hilfreich fände, bis eine offizielle App besteht: Export in WebDav! Damit könnte man einfach den Kalender in Nextcloud Syncen und dann mit dem iPhone oder Android-Telefon oder Online abrufen. Und man hätte eine Integration direkt in die Systemkalender und CarPlay.

Werde mich heute mal in den SourceCode einarbeiten. Mit welcher IDE wurde hier hauptsächlich gecoded?

**Comment by j-dimension** [comment]
@jannis2200 primäre IDE ist Netbeans. Hier gibt es eine Anleitung für die ersten Schritte: (wenn man wirklich Server und Client komplett lokal bauen will). https://github.com/jlawyerorg/j-lawyer-developer-quickstart

Ich helfe auch gern für eine Schnellbesohlung.

**Comment by j-dimension** [comment]
Ticket in separates Repo transferiert, wird hier geschlossen.

**Comment by stm9x9** [comment]
> Ticket in separates Repo transferiert, wird hier geschlossen.

kannst Du das Repo bitte noch verlinken?

**Comment by j-dimension** [comment]
> kannst Du das Repo bitte noch verlinken?

Nein, es handelt sich um ein privates Repo.
