### ISSUE TITLE
Enhanced REST API (write access)

### ISSUE THREAD

**Issue by j-dimension** [jlawyerorg/j-lawyer-org#601]
Remaining:

- [x] case tags: toggle 0,5h
- [x] document tags: list
- [x] document tags: toggle

- [x] contacts: get cases 0,75h
- [x] contact tags: list 0,25h
- [x] contact tags: toggle 0,5h

out of scope: 
reviews: update
reviews: create

**Comment by iradraconis** [comment]
kommen diese Ergänzungen vielleicht noch irgendwann in die REST API?

**Comment by j-dimension** [comment]
Benötigst Du einen bestimmten Service aus der Liste oben?

**Comment by iradraconis** [comment]
Diejenigen, die contact und case betreffen, finde ich spannend und machen die bestehenden Endpunkte der API "rund"

**Comment by j-dimension** [comment]
> gibt es in der aktuellen Vorschauversion der 2.1 eine Möglichkeit, die im System konfigurierten Tags für Cases und Contacts abzurufen so wie bei den Beteiligtentypen?

@iradraconis das ist an der Stelle nicht notwendig. Die Etiketten werden angelegt, auch wenn sie nicht als Konfiguration hinterlegt sind. (Also kann ein Aufrufer ein Etikett "vorgeben")

**Comment by iradraconis** [comment]
das ist top! Danke!
