### ISSUE TITLE
Mehrere WV Gründe auswählen können

### ISSUE THREAD

**Issue by Maz111111** [jlawyerorg/j-lawyer-org#606]
Beim Erstellen einer WV / Frist kommt es oft vor, dass mehrere der vordefinierten Gründe die WV / Frist veranlassen.
Aktuell kann nur immer ein Grund ausgewählt und der weitere muss dann doch per Hand eingetragen werden.
Vielleicht könnte man mit Checkboxen arbeiten.

**Comment by j-dimension** [comment]
Wäre es dann evtl. sauberer und flexibler, tatsächlich mehrere WV einzutragen? Dann kann man die auch einzeln als erledigt markieren. Mehrere Gründe mit einem einzigen Fälligkeitsdatum würden das "Erledigen" einzelner Gründe verhindern. 

Vorschlag: Bei der Eingabe wird für die Gründe statt eines Dropdowns eine Liste mit Checkboxen dargestellt, sowie EIN Fälligkeitsdatum. Wählt der Nutzer mehrere Gründe aus, wird für jeden eine separate WV angelegt. 
Somit ließen sich eine Menge Klicks sparen, und man behält volle Flexibilität.

**Comment by Maz111111** [comment]
Ich kann Deine Argumentation nachvollziehen.
Aktuell habe ich einen SS an das Gericht gesendet und eine Vorschussrechnung an den M.
Die Akte wandert am Tag X wieder auf meinen Tisch weil ich checken will, ob es Posteingang gab und ob der M gezahlt hat.
Ich würde da ungern zwei WV abhaken müssen. Im Handkalender habe ich auch nur einen Eintrag.
Ich glaube aber, dass Du hier zu kompliziert denkst.
Die Möglichkeit zwei einzelne WVs (mit jeweils unterschiedlichen Gründen) auf einen Tag zu legen bietet die KSW ja ohnehin schon. Dafür braucht es keine (neue) Checkbox.
Was fehlt, ist die Möglichkeit, zwei Gründe in eine WV zu packen.
Dein Vorschlag dürfte im Ergebnis auch zu mehr Klicks führen. 
Ich hätte heute in der Liste zwei Haken gesetzt. am Tag X die WV bestätigt (=ja ich habe geprüft, ob PE und/oder Zahlung eingegangen ist) und eine ggf. notwendige neue WV erstellt (entweder nochmal dieselbe oder eine mit nur Zahlung oder nur PE).

**Comment by j-dimension** [comment]
> Dein Vorschlag dürfte im Ergebnis auch zu mehr Klicks führen.

Beispiel mit drei Gründen:

- jetzt: Dropdown aufklappen, Eintrag auswählen, Hinzufügen = 9 Klicks
- mit Vorschlag oben: drei Gründe anklicken, Hinzufügen = 4 Klicks
- mit Deinem Vorschlag: ebenso 4 Klicks

> und eine ggf. notwendige neue WV erstellt (entweder nochmal dieselbe oder eine mit nur Zahlung oder nur PE).

Mit einzelnen WV könnte man dann einfach das Datum der einen WV anpassen.


Für mich hätten die mehreren WV auch Darstellungsvorteile. Bei mehreren Gründen wird es dazu kommen, dass die Gründe bspw. auf dem Desktop abgeschnitten dargestellt werden oder man scrollen muss.

**Comment by Maz111111** [comment]
Ich verstehe Deinen Vorschlag. Allerdings halte ich objektiv weder meinen noch Deinen für besser oder schlechter.
Man müsste jetzt wissen, wie die Praxis der anderen Anwender aussieht.
Ich hab noch nie (absichtlich) zwei WV für eine Akte am selben Tag im Kalender notiert.
Vermutlich würde ich das auch digital so halten, selbst wenn die Funktion, so wie Du sie beschreibst, implementiert würde, und dann weiter händisch mehrere Gründe eintragen.
Ich will da einfach auch soweit es eben möglich ist, einen Gleichlauf zwischen meinem geschriebenen und dem elektronischen Kalender.

**Comment by stm9x9** [comment]
> Die Akte wandert am Tag X wieder auf meinen Tisch weil ich checken will, ob es Posteingang gab und ob der M gezahlt hat.
> Ich würde da ungern zwei WV abhaken müssen. Im Handkalender habe ich auch nur einen Eintrag.

Echt? Zwei Gründe sind bei mir zwei Fristen/WV. Vielleicht kann ich das eine schon gleich checken, das andere aber doch noch nicht. Vielleicht will ich eine der beiden WVs auch verschieben ...

**Comment by stm9x9** [comment]
> Aktuell habe ich einen SS an das Gericht gesendet und eine Vorschussrechnung an den M.

und mein Workflow sieht auch im Digitalen dann so aus, daß ich nach dem SS die WV dafür setze und nach der Rechnung die WV für die Kosten.

**Comment by an-mus** [comment]
Ich würde auch dazu neigen, aus zwei Gründe zwei Wiedervorlagen zu machen. Ich benutze Wiedervorlagen auch mehr Richtung Aufgabenplanung und schreibe oft noch ein paar zusätzliche Stichworte in den Wiedervorlagegrund mit rein. 
Es kommt doch auch regelmäßig vor, dass die beiden Gründe nicht gleichzeitig abgearbeitet werden und eine Frist noch mal verschoben wird. Auch das bildet mit zwei Fristen den Arbeitsablauf besser ab.

**Comment by RA-crm** [comment]
Ich bin auch ein Anhänger von eine WV für jeden Grund. Zum Beispiel lege ich nach Versand eines Vertragsentwurfs an mehrere Beteiligte für die Frage "Rückmeldung auf Entwurf von ..." diese WV für jeden Beteiligte an und arbeite sie auch so ab.

Die Idee die bestehenden Templets anklickbar zu gestalten wäre super, gerade aber, weil ich das Templet anpassen können muss (wer soll hier was machen), ist ein Auswahlmenue vllt nicht die richtige Lösung.

**Comment by Maz111111** [comment]
Also ich akzeptiere ja Demokratie... :-)
Aber gerade eben:
Ich erzeuge eine WV "Posteingang?". Dazu hätte ich jetzt gerne meinen WV Grund "Sachstand" (mein Hinweis dafür, dass, falls kein PE, eine Anfrage gestellt werden soll) gepackt.
Geht nicht per Klick, sondern nur per Hand.
Bei dem nun angedachten Modell hätte ich zwei WVs. 
Das würde meine Intention nicht korrekt abbilden.

**Comment by stm9x9** [comment]
Was ist mit einem Template "Posteingang? Sachstand!"?
