### ISSUE TITLE
Schutz vor zu schnellem Umwandeln in pdf

### ISSUE THREAD

**Issue by Maz111111** [jlawyerorg/j-lawyer-org#607]
Mir ist gerade (weiderholt) aufgefallen, dass es zu Folgendem unschönen Vorfall kommen kann:

Wenn man ein Dok als odt abspeichert und dann schnell genug (ich arbeite mit zwei Bildschirmen - rechts LO und links jL) auf "ablegen als pdf" klickt, wird nicht die aktuell abgespeicherte Version umgewandelt, sondern die vor dem letzten Abspeichern.

Das fällt dem Anwender in der Regel aber nicht zwingend auf, weil man auf die Korrektheit der Umwandlung vertraut, so dass es sein kann, dass eine alte Version umgewandelt und dann in der Folge auch versendet wird.

Kann hier ein Sicherheitsmechanismus in die KSW eingebaut werden?

Betrifft Aktionen auf einzelne Dokumente: Nutzer zum Schliessen auffordern und auf Schliessen warten

- [x] duplizieren
- [x] ablegen als PDF
- [x] ablegen als ...
- [x] in andere Akte kopieren
- [x] Fax senden

Betrifft Aktionen auf mehrere Dokumente: nur Hinweis an Nutzer mit Frage "fortfahren ja/nein"

- [x] lokal speichern
- [x] senden (E-Mail)
- [x] senden als PDF (E-Mail)
- [x] senden (beA)
- [x] senden als PDF (beA)
- [x] obsolet (siehe Kommentar unten): 3x Drebis

**Comment by j-dimension** [comment]
benötigt NIO WatchService

**Comment by j-dimension** [comment]
@Maz111111 ich bin mir gerade unsicher welche Aktionen man mit geöffnetem / noch in Speicherung befindlichem Dokument unterbinden sollte und welche nicht. 

Wäre das aus Deiner Sicht auf alle anzuwenden, also

- lokal speichern
- duplizieren
- ablegen als PDF
- ablegen als ...
- in andere Akte kopieren
- senden (E-Mail)
- senden als PDF (E-Mail)
- senden (beA)
- senden als PDF (beA)
- Fax senden
- 3x Drebis

?

**Comment by Maz111111** [comment]
Ich würde es bei allen unterbinden.
Das einzige, bei dem es vielleicht nicht so tragisch wäre, scheint lokal speichern zu sein.
Aber auch da weiß man nicht, was der User vor hat und ob er das Dok vor seinem Vorhaben nochmal prüft.
Im Grunde erwartet man bei jeder Aktion, dass die zuletzt abgespeicherte Version bearbeitet wird.
Also für alle.
Bleib gesund!

**Comment by j-dimension** [comment]
Drebis-Aktionen lasse ich erstmal, bis man den Assistent abgearbeitet hat, ist das Dokument gespeichert.
