### ISSUE TITLE
Wegfall des Bundeslandes bei Übernahme aus PLZ-Suche

### ISSUE THREAD

**Issue by jphaag** [jlawyerorg/j-lawyer-org#609]
Adressen:
Liebe Mitanwender,
ich benutze gerne und häufig die Ortsübernahme bei Eingabe der PLZ bei der Adressaufnahme. Hierbei wird immer das Bundesland in Klammern hinzugefügt. Nur meckert drebis dann immer, weil die Ortsangabe regelmäßig 30 Zeichen überschreitet. Ist grundsätzlich nicht problematisch, die Adresse wird dann von Hand "bereinigt". Ich fände es aber wünschenswert, wenn das Bundesland gar nicht erst hinzugefügt würde. Was meint Ihr?

**Comment by j-dimension** [comment]
Vielen Dank und herzlich willkommen bei GitHub! Ticket eingeplant für 1.12.

**Comment by Maz111111** [comment]
Auch von hier herzlich willkommen.
Die Sache könnte dann mit #448 verbunden werden.

**Comment by PBaumfalk** [comment]
Ohne Bundesländer wäre so imba

**Comment by j-dimension** [comment]
erneuter Import der PLZ durch den Anwender notwendig, damit Änderung aktiv wird
