### ISSUE TITLE
flexible Falldatenblätter als Plugins

### ISSUE THREAD

**Issue by j-dimension** [jlawyerorg/j-lawyer-org#610]
Grobkonzept:
- [x] neuer Tab "Falldaten" in Akte
- [x] Falldaten sind Groovy-Plugins, die ein Formular bereitstellen
- [ ] FormsAPI für Zugriff auf Beteiligte, Aktendaten, etc.
- [ ] generische API für Aufrufen von Pluginfunktionalität (bspw. dem Plugin signalisieren, dass ein Beteiligter hinzugefügt wurde)
- [x] Plugins zur Laufzeit aktualisierbar und installierbar, aber durch Client gemanaged, mit Speicherung auf Server. Entweder aus zentralem Repo runterladen oder manuell von Platte hinzufügen (falls jemand etwas sehr spezifisches erfassen will). 
- [x] Plugins müssen alle Daten per Platzhalter zur Verfügung stellen, Platzhalter werden bei Änderung im Plugin als Key-Value abgespeichert. Platzhalterschlüssel sind als Information im Plugin selbst anzeigbar. Platzhalterpräfix kann vom Anwender selbst angepasst werden, damit man das gleiche Datenblatt mehrfach in der selben Akte führen kann.
- [x] Löschen von Plugin verhindern, wenn in Akten genutzt
- [x] Löschen von Plugintyp verhindern, wenn in Akten genutzt
- [x] Integration in Vorlagensystem

Persistenz:
- [x] form_types: id, name, version, default-placeholder-prefix
- [x] form_types_artefacts: id, filename, content
- [x] case_forms: id, formtype-id, description, placeholder-prefix, creationDate
- [x] case_forms_entries: key, value, placeholder

GUI:
- [x] neuer Tab "Falldaten" in Akte
- [x] Einstellungsdialog zum Managen von Forms-Plugins
- [x] in Akte: bei Hinzufügen von Fallldatenblatt: Description, Platzhalterpräfix etc. abfragen
- [x] beim Hochfahren die Forms aus der Datenbank laden

Server:
- [x] Services

REST-API:
- [x] neue Services implementieren
- [x] alte Services testen (wg. lazy load neuer Relationen)

**Comment by stm9x9** [comment]
Ich versteh zwar kein Wort und weiß nicht, was groovy Plugins sind aber wenn zb beim Eintrag "PKH bewilligt von Gericht x" automatisch ein Schreiben an den Mandanten gefertigt wird "hey PKH ist da!", dann wäre das cool!

Muß aber dann gerichtsbezogen sein, weil man in einer Akte mehrfach je Instanz PKH bekommen kann.
