### ISSUE TITLE
Beim Versand von Mail und bea Dritten anhand des Empfängers automatisch bestimmen

### ISSUE THREAD

**Issue by Maz111111** [jlawyerorg/j-lawyer-org#613]
Wenn man bei Mail oder beA einen Empfänger auswählt und eine Vorlage nutzt, muss in dem Fenster für die Vorlage zwingend das passende Pendant ausgewählt werden, damit die Vorlage richtig befüllt wird.
Gibt es von einem Beteiligten mehrere (z.B. zwei oder drei dritte) darf man da nicht schludern, sonst stimmen Anrede AZ oder was auch immer man in der Vorlage nutzt, nicht.
Es wäre schön, wenn die KSW einem diese Kontrollarbeit abnehmen könnte und automatisch Empfänger und Vorlage abgleicht (wird ein Dritter als Empfänger gewählt, wird automatisch dieser Dritte in der Vorlage genutzt und auch dessen AZ im beA eingestellt).

**Comment by j-dimension** [comment]
> Es wäre schön, wenn die KSW einem diese Kontrollarbeit abnehmen könnte und automatisch Empfänger und Vorlage abgleicht (wird ein Dritter als Empfänger gewählt, wird automatisch dieser Dritte in der Vorlage genutzt 

Ist das nicht der Fall? Was genau geht schief?

> und auch dessen AZ im beA eingestellt).

Das ist sinnvoll, ja.

**Comment by Maz111111** [comment]
`>Ist das nicht der Fall? Was genau geht schief?`
Ich habe eine beA Nachricht versendet. Als Dritte in der Akte gibt es eine Gegenanwältin und eine Notarin.
In meiner Vorlage ist die Anredeformel für Dritte hinterlegt.
Aus irgendeinem Grund war im Vorlagefenster die Notarin als Dritte ausgewählt (obwohl diese erst viel später in der Akte erfasst wurde).
die Nachricht im beA Fenster lautete dann "sehr geehrte "Name der Notarin"" anstatt "sehr geehrte "Name der RAin"" obwohl als Empfänger die RAin ausgewählt war. Das habe ich nicht geprüft - halt vergessen. außerdem ist der Cursor ohnehin immer am Ende der Vorlage, so dass ich die Anredeformel nicht im Fenster sehe.
Bei Mail habe ich nicht noch mal getestet - ging aber davon aus, dass Du da denselben Ablauf programmiert hast. Wenn es bei Mail nicht so ist - Asche auf mein Haupt. 
Bei beA müsste es dann noch nachgereicht werden.

**Comment by j-dimension** [comment]
Habe die Beteiligtenauswahl in den Sendedialogen komplett überarbeitet, Fehler kann ich damit nicht mehr reproduzieren.
