### ISSUE TITLE
Erfassung Beratungshilfe "einbauen"

### ISSUE THREAD

**Issue by Maz111111** [jlawyerorg/j-lawyer-org#615]
Wäre es eine mögliche Verbesserung, wenn man bei "allgemeine Daten" eine Checkbox einbauen würde "Beratungshilfe (BHS) bewilligt?"
Für den Fall, dass der Anwender diese Box anhakt, wäre es toll, wenn dann die Möglichkeit gegeben würde, in einem PopUp, wie beim Passwort für die Verschlüsselung, AZ des Beratungshilfescheins und Anschrift des bewilligenden Gerichtes einzugeben und für beides dann auch einen Platzhalter hätte um die BHS Abrechnung weiter automatisieren zu können.

**Comment by j-dimension** [comment]
Ich plane aktuell ein Feature zur Erfassung fallspezifischer Daten: #610 
Dabei geht es darum, ähnlich der Berechnungsplugins, eines oder mehrere "Datenblätter" mit fallspezifischen Daten in einer Akte hinterlegen zu können. Damit wäre dann auch diese Anforderung von Dir umsetzbar. 

Ich würde das gern bereits in der 1.12 umsetzen, aber wie immer: kein Versprechen.

**Comment by stm9x9** [comment]
Sollte das Amtsgericht nicht in den Beteiligten eingepflegt werden? Weit vor dem erhaltenen Schein? Zumindestens bei der nachträglichen Beantragung muß man das ja schon für das Anschreiben nutzen, für das Vor-Ausfüllen des Antrags, ggf für weitere Korrespondenz, wenn der Rechtspflegel mal wieder was zu meck... monieren hat.

Will sagen, bislang ist das bei mir in meinem bisherigen Programm schlicht ein weiterer "Dritter". Mit Aktenzeichen und Pipapo

**Comment by stm9x9** [comment]
Eine Checkbox wäre dann aber trotzdem eine interessante Idee. Die würde ich dann aber bei jedem Gericht haben wollen. Dann kann man nämlich bei jedem involvierten Gericht (und auch bei ggf mehrfach involvierten, Stichwort Hauptsache und Eilverfahren) PKH ankreuzen.

**Comment by PBaumfalk** [comment]
Nicht Sio viel Zeit verschwenden in die Beratungshilfe, die Gerichte machen das immer noch in Papierform. Da reicht eigentlich eine automatisierte Rechnungsvorlage. Beweis dafür, dass die Gerichte das gerne händisch machen:

![image](https://user-images.githubusercontent.com/50404378/72622506-a0b48a80-3943-11ea-83e5-a2fb8d0c8b7a.png)

**Comment by stm9x9** [comment]
Es gibt aber noch mehr AGs als das eine :-) Und ich kenne einige Kollegen, die das rein per beA machen können.

Aber eigentlich verstand ich das Ticket und seine Erweiterungen gar nicht so, daß es auf einen beA-Versand ankommt, sondern es wäre eine Hilfe auch bei einer Papier-Erstellung.

**Comment by Maz111111** [comment]
Exakt!
Es geht darum eine Vorlage basteln zu können, in der sofort das richtige Gericht mit dem richtigen AZ eingetragen ist. Dann müsste ich drei Vorlagen basteln und meine Mitarbeiterin müsste sie nur noch erstellen.

Das Gericht als Beteiligten zu erfassen - kann man machen - ist aber unter Umständen unübersichtlich, da das eigentlich mit dem Fall zu betrauende Gericht und das BH Gericht auseinanderfallen können. Im FamR fast immer, da Mandant und Kind sehr häufig in unterschiedlichen Gerichtsbezirken leben.

Dieses BH Gericht soll einen eigenen Platzhalter bekommen, der dann auch für die Korrespondenz herhalten soll. Btw nachträgliche BH gibt es in meiner Kanzlei nicht. Die Leute kommen mit Schein oder es ist ihnen offenbar nicht wichtig genug.

Ob die Abrechnung bei mir per beA geht, bleibt auszutesten. Sobald ich mal wieder ein Mandat abrechne, bei dem es nur um die 40 EUR Beratung geht, werde ich es mal versuchen.

Bisher will das Gericht eigentlich immer den BHS im Original. Da aber bei Gericht ein AZ für den Schein existieren muss, zu dem man vermerken könnte, dass und in welcher Höhe bezahlt ist, verstehe ich das noch nicht ganz.
Da könnte ich ggf. mal Energie investieren.

**Comment by stm9x9** [comment]
> da das eigentlich mit dem Fall zu betrauende Gericht und das BH Gericht auseinanderfallen können.

Man kann ja mehr als ein Gericht in j-l eintragen. Und wenn ich das richtig verstehe und gerade am Beteiligtensystem heftig rumgeschraubt wurde, dann könnte es sein, daß an dem Gericht dann auch Rollen vergeben kann (I. Instanz, BerH-Gericht, ...)

> Da aber bei Gericht ein AZ für den Schein existieren muss, zu dem man vermerken könnte, dass und in welcher Höhe bezahlt ist, verstehe ich das noch nicht ganz.

es ist - gerüchteweise! - die Sorge, wir Anwälte würden auf gefälschte / kopierte BHS reinfallen und dann würden zwei RAs abrechnen wollen. Und wenns fürs Gericht blöd läuft, der mit der Fälschung zuerst.

**Comment by PBaumfalk** [comment]
> Exakt!
> Es geht darum eine Vorlage basteln zu können, in der sofort das richtige Gericht mit dem richtigen AZ eingetragen ist. Dann müsste ich drei Vorlagen basteln und meine Mitarbeiterin müsste sie nur noch erstellen.
> 
> Das Gericht als Beteiligten zu erfassen - kann man machen - ist aber unter Umständen unübersichtlich, da das eigentlich mit dem Fall zu betrauende Gericht und das BH Gericht auseinanderfallen können. Im FamR fast immer, da Mandant und Kind sehr häufig in unterschiedlichen Gerichtsbezirken leben.
> 
> Dieses BH Gericht soll einen eigenen Platzhalter bekommen, der dann auch für die Korrespondenz herhalten soll. Btw nachträgliche BH gibt es in meiner Kanzlei nicht. Die Leute kommen mit Schein oder es ist ihnen offenbar nicht wichtig genug.
> 
> Ob die Abrechnung bei mir per beA geht, bleibt auszutesten. Sobald ich mal wieder ein Mandat abrechne, bei dem es nur um die 40 EUR Beratung geht, werde ich es mal versuchen.
> 
> Bisher will das Gericht eigentlich immer den BHS im Original. Da aber bei Gericht ein AZ für den Schein existieren muss, zu dem man vermerken könnte, dass und in welcher Höhe bezahlt ist, verstehe ich das noch nicht ganz.
> Da könnte ich ggf. mal Energie investieren.

Ich habe bereits das ganze Ding für die Abrechnung gebastelt. Steht im Repo für die Templates:

[DRITTE-Liquidation-BerHG-MANDANT-VORABFAX-SW.odt.zip](https://github.com/jlawyerorg/j-lawyer-org/files/4089657/DRITTE-Liquidation-BerHG-MANDANT-VORABFAX-SW.odt.zip)

**Comment by j-dimension** [comment]
Es ist gut dass hier verschiedene Möglichkeiten diskutiert werden. Einen klaren Erweiterungswunsch kann ich momentan noch nicht ableiten. 

Vorschlag: ich schiebe in die 1.13, Ihr schaut Euch die Umsetzung des neuen Beteiligtensystems sowie die Falldatenblätter an, und dann konkretisieren wir dieses Ticket.

**Comment by Maz111111** [comment]
Mit dem neuen Beteiligtensystem kann ich alles umsetzen, worum es hier für mich ging.

Hier kann aus meiner Sicht zugemacht werden. Das mach ich jetzt aber mal nicht selbst, falls doch noch einer was dazu sagen will.

**Comment by Maz111111** [comment]
Na das ist jetzt kein großer Budenzauber.
Ich lege eine Beteiligten Gericht BH an. Bei den Adressen wird das Gericht kopiert und unter Abteilung "Beratungshilfestelle / -Abteilung eingetragen.
Dann hab ich eine Vorlage erstellt (ich nutze nicht den amtlichen Vordruck, sondern eine selbst erstellte Abrechnungsvorlage)
[Abr BH Vordruck.pdf](https://github.com/jlawyerorg/j-lawyer-org/files/4763353/Abr.BH.Vordruck.pdf)
Das einzige was ich von Hand eintragen muss, sind Re-Nr (was ja eigentlich falsch ist, da es ein Antrag ist und keine Rechnung - ich mach es dennoch) und das Datum der Vollmacht als Mandatsbeginn (dafür habe ich hier schon ein Issue eröffnet, damit dafür ein Platzhalter geschaffen wird).
Die 20 bei der Re.-Nr. ist über einen Feldbefehl "Datum" automatisiert.
That's it.
Viele Grüße
Martin

**Comment by Maz111111** [comment]
Ach so, beim Aktenzeichen des Beteiligten "Gericht BH" wird in der jeweiligen Akte das AZ des Beratungshilfescheins eingetragen

**Comment by stm9x9** [comment]
> Bei den Adressen wird das Gericht kopiert und unter Abteilung "Beratungshilfestelle / -Abteilung eingetragen.

Verstehe ich das richtig? Das Gericht ist dann doppelt in der Adressdatenbank? Welchen Vorteil hat das? Kann man diesen Text nicht fest im Adressbereich der Vorlage reinschreiben?

**Comment by Maz111111** [comment]
Das kann man sicher so machen.
Geschmacksache.
Allerdings habe ich auch Faxvorlagen und die einzelnen Abteilungen haben unterschiedliche Faxnummern.
Das war der Grund, warum ich für jede Abteilung (Familiengericht; BH_Abteilung etc.) jeweils einen Adresseintrag angelegt habe. Bei den paar Gerichten, mit denen ich so intensiv verkehre, war das kein Aufwand und auch kein großer Mehrbestand an Daten.

**Comment by stm9x9** [comment]
> Allerdings habe ich auch Faxvorlagen und die einzelnen Abteilungen haben unterschiedliche Faxnummern.
> Das war der Grund, warum ich für jede Abteilung (Familiengericht; BH_Abteilung etc.) jeweils einen Adresseintrag angelegt habe.

Das wäre vielleicht auch mal eine Sache für ein eigenes Ticket? Es kommt ja durchaus öfter vor und die einzelnen Abteilungen haben ja auch individuelle Telefon-Durchwahlen. a-jur zb geht da einen - vermutlich aufwändigen - Weg und läßt aktenbezogen zusätzliche Kontaktinformationen zu einem Beteiligten einpflegen.

**Comment by GuidoBo** [comment]
Ich möchte das Thema nochmal öffnen; es bedarf m.E. einer Regelung:

Ich schlage vor:

**Lösung über Falldatenblatt ("Kostenhilfen")**
Im Falldatenblatt die erforderlichen Felder des PDF-BerH-Antrags bereithalten:
https://justiz.de/service/formular/dateien/agI1.pdf

Es braucht m.E. mindestens die Dokumentenvorlagen: 
`"Erklärung über die wirtschaftlichen Verhältnisse.pdf"` und `"BerH-Abrechnung.pdf"`
für beide ist die Pflicht vorgesehen, das (amtliche?) Formular zu verwenden (jedenfalls sehen das die AGs so).

Die Felder im PDF sollte JL aus dem Falldatenblatt vorbefüllen können.
