### ISSUE TITLE
ablegen als - Abbruch - Fehler

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#621]
Wenn ich in einer Dokumentenliste "ablegen als" wähle, kommt ein Auswahlfeld für das Format. Wenn ich da auf das Abbruch-X oben rechts klicke kommt eine Fehlermeldung statt einfach abzubrechen:

![image](https://user-images.githubusercontent.com/29924198/72690564-c6958700-3b1d-11ea-95d1-770d6e68f568.png)

Vermutlich wird der Abbruch nicht abgefangen sondern einfach nur ein "leeres" Zielformat an die nächste Subroutine weitergegeben.

**Comment by j-dimension** [comment]
Jo, das wird wohl genau so sein wie Du das einschätzt. Wird behoben.
