### ISSUE TITLE
[beA] Betreff bei beA-Versand aus Akte leer

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#622]
Wenn ich aus einer Akte eine beA-Nachricht erzeuge, wird zwar mein Akz übernommen und die der anderen als dropdown für Empfänger angeboten. Aber Betreff wird nicht mit dem Kurzrubrum vorbelegt.

**Comment by j-dimension** [comment]
Du kannst Dir eine Vorlage erstellen und so das Rubrum automatisch in den Betreff übernehmen. Funktioniert dann auch gleich für E-Mails.

**Comment by stm9x9** [comment]
Ich dachte, die sind mehr für das Nachrichtentextfeld? Gibt es denn einen Grund, warum man das nicht automatisch immer übernommen haben wollen könnte?

**Comment by j-dimension** [comment]
Die Vorlagen für E-Mail und beA umfassen sowohl den Nachrichtentext als auch den Betreff. 

Automatik: Der eine will nur AZ, der nächste AZ und Rubrum, der übernächste AZ und Rubrum und irgendeine Schadennummer oder sonstwas. Daher: Vorlage. Die ist mit einem Klick ausgewählt und enthält dann genau das, was man sich wünscht.
