### ISSUE TITLE
Beteiligte hinzufügen - Abteilung anzeigen

### ISSUE THREAD

**Issue by PBaumfalk** [jlawyerorg/j-lawyer-org#624]
Hallo zusammen,

in "Beteiligte hinzufügen" muss noch die Abteilung angezeigt werden.

Gerade bei großen Behörden oder Städten finde ich sonst die richtige Adresse nicht schnell. Wir haben das in der Vergangenheit mit Name oder Vorname gemacht. Ist aber Scheisse. ;)

Beispiel:
![image](https://user-images.githubusercontent.com/50404378/72704743-e9de2780-3b59-11ea-9106-5768cb2a5283.png)

**Comment by j-dimension** [comment]
Endlich mal was mit 10min Aufwand :-)
