### ISSUE TITLE
SMS-Vorlage für Passwortversand neutral gestalten

### ISSUE THREAD

**Issue by PBaumfalk** [jlawyerorg/j-lawyer-org#627]
EDIT:

Bitte die SMS Vorlage neutral gestalten.
Passwort zum Entsperren empfangener Dokumente: (PASSWORT)

---
Hallo zusammen,

ich finde die Möglichkeit nicht mehr, die SMS-Vorlage zu ändern.

Thread kann direkt geschlossen werden, wenn ich weiß, wo man das ändern kann.

**Comment by j-dimension** [comment]
Was meinst Du genau? Für welche SMS? Geht es um die Verschlüsselungspasswörter?

**Comment by PBaumfalk** [comment]
Ja!

Mit freundlichen Grüßen / Kindly Regards

Patrick Baumfalk
Rechtsanwalt / Lawyer


Mobil:    +49 1525 53 04 194
E-Mail:   patrick.baumfalk@kanzlei-baumfalk.de


Baumfalk - Rechtsanwaltskanzlei
Hauptstr. 195
50169 Kerpen

Tel.: +49 2273 40 68 504
Fax: +49 2273 59 03 565

E-Mail: info@kanzlei-baumfalk.de
Web: www.kanzlei-baumfalk.de

**Comment by j-dimension** [comment]
Die ist aktuell nicht konfigurierbar. Was für einen Bedarf hast Du?

**Comment by PBaumfalk** [comment]
Ach, das ist nicht konfigurierbar :(

Passwort zum Entsperren empfangener Dokumente: XXXXXXXXi - Mit frdl. Gruessen, Ihre BAUMFALK

Liest sich irgendwie komisch.
Also das Ende müsste einfach nur weg. Kann man das in der SQL Tabelle verändern?

Mit freundlichen Grüßen / Kindly Regards

Patrick Baumfalk
Rechtsanwalt / Lawyer


Mobil:    +49 1525 53 04 194
E-Mail:   patrick.baumfalk@kanzlei-baumfalk.de


Baumfalk - Rechtsanwaltskanzlei
Hauptstr. 195
50169 Kerpen

Tel.: +49 2273 40 68 504
Fax: +49 2273 59 03 565

E-Mail: info@kanzlei-baumfalk.de
Web: www.kanzlei-baumfalk.de

**Comment by j-dimension** [comment]
Kann man leider nicht. 

Aktuell wird hinten das Attribut "Firma" aus dem Kanzleiprofil angefügt. 

D.h. durch Änderung könntest Du erstmal Abhilfe schaffen. Und ggf. diese Ticket umformulieren hinsichtlich einer Konfigurierbarkeit (oder einfach nur einen neutralen Text nutzen - was sehr schnell gehen würde).

**Comment by PBaumfalk** [comment]
> Kann man leider nicht.
> 
> Aktuell wird hinten das Attribut "Firma" aus dem Kanzleiprofil angefügt.
> 
> D.h. durch Änderung könntest Du erstmal Abhilfe schaffen. Und ggf. diese Ticket umformulieren hinsichtlich einer Konfigurierbarkeit (oder einfach nur einen neutralen Text nutzen - was sehr schnell gehen würde).

Habe die Fragestellung editiert.
