### ISSUE TITLE
Vorbelegung Textbausteine

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-org#629]
Ich weis schon garnicht mehr, wie oft ich am Tag bei Neuanlage der Akten Mit freundlichen Grüßen bzw. Sehr geehrter Herr ... einpflegen muss. Eine Standardvorbelegung mit alternativem Dropdownmenü um anders einzutragen (Standard Mit freundlichen Grüßen, alternativ z.B. Mit besten Grüßen etc.) wäre segensreich.

**Comment by j-dimension** [comment]
??? 

Reiter "Textbausteine" in der Adresse nutzen. Die Werte in den Dropdowns lassen sich konfigurieren, sodass man das nie tippen muss.

**Comment by PBaumfalk** [comment]
> ???
> 
> Reiter "Textbausteine" in der Adresse nutzen. Die Werte in den Dropdowns lassen sich konfigurieren, sodass man das nie tippen muss.

Ich glaube was Mucki meint ist, dass man ggf. noch ein weiteres Datenfeld mit "Schlussformel" einfügt. Das wäre auch ein neues Ticket. Mit kollegialen Grüßen, Hochachtungsvoll, Mit kollegialer Hochachtung, Mit vorzüglicher Hochachtung etc...

**Comment by PBaumfalk** [comment]
Idee: Eine Combobox, die automatisch fertig schreibt. Mit vordefinierten Feldern. Gebe ich Frau ein, kommt „Sehr geehrte Frau“, bei Herr auch usw.

**Comment by j-dimension** [comment]
Ich verstehe immer noch nicht so richtig die Motivation. Braucht man eine Anrede / Grussformel für die Schriftsätze, die andere in E-Mail o.ä.?

**Comment by PBaumfalk** [comment]
Für Briefe bei Kollegen grüßt man anders als bei Gericht

Mit freundlichen Grüßen / Kindly Regards

Patrick Baumfalk
Rechtsanwalt / Lawyer


Mobil:    +49 1525 53 04 194
E-Mail:   patrick.baumfalk@kanzlei-baumfalk.de


Baumfalk - Rechtsanwaltskanzlei
Hauptstr. 195
50169 Kerpen

Tel.: +49 2273 40 68 504
Fax: +49 2273 59 03 565

E-Mail: info@kanzlei-baumfalk.de
Web: www.kanzlei-baumfalk.de

Sent by Mobile

**Comment by j-dimension** [comment]
> Für Briefe bei Kollegen grüßt man anders als bei Gericht

Ja, das ist mir klar, und genau deswegen gibt es ja die Textbausteine an der Adresse. Dort kannst Du für ein Gericht etwas anderes hinterlegen als für einen Kollegen.

**Comment by PBaumfalk** [comment]
> > Für Briefe bei Kollegen grüßt man anders als bei Gericht
> 
> Ja, das ist mir klar, und genau deswegen gibt es ja die Textbausteine an der Adresse. Dort kannst Du für ein Gericht etwas anderes hinterlegen als für einen Kollegen.

Ich glaube @Mucki526 muss die gleichen Sachen jeden Tag hunderte Male erneut eintippen und hätte gerne eine Vorbelegung.

**Comment by j-dimension** [comment]
Raff ich immer noch nicht. Die Inhalte der Dropdowns sind doch frei konfigurierbar?

**Comment by j-dimension** [comment]
Die einzige "Lücke" die ich sehe ist dass man in Schriftsätzen "Sehr geehrter" haben will, aber wenn man den gleichen Kontakt eine E-Mail schreibt, dann innerhalb der E-Mail "Hallo" "Moin" o.ä. haben will. 

Das lese ich aus der ursprünglichen Anfrage nicht heraus. 

Vielleicht kann uns @Mucki526 erleuchten.

**Comment by Mucki526** [comment]
Oh je, da habe ich aber eine Lawine losgetreten. Nennen wir es Aktivierung neuer Ideen.... Die Wahrheit ist dazwischen.... 1.) Wahrheit, ich habe einfach hinten rechts den Reiter für die Vorbelegungen übersehen, bzw. inzwischen vergessen. (Asche auf mein Haupt). Aber: 2.) Es wäre gut, wenn man eine Standardvorbelegung bei Adressanlage drin hätte. z.B. Sehr geehrter Herr / Mit freundlichen Grüßen - 

Aber ich sehe - schon beginnt das Problem, wenn ich Sehr geehrter Herr voreingestellt habe und dann eine Frau oder was dazwischen.... eintragen will :-).

**Comment by j-dimension** [comment]
Okay, dann schliesse ich hier, und lasse die #631 offen und konkretisiere dort.
