### ISSUE TITLE
[adressen] alternative Grussformel / Anrede

### ISSUE THREAD

**Issue by PBaumfalk** [jlawyerorg/j-lawyer-org#631]
Eigentlich das selbe, wie bei der Grußformel und Anrede, nur als Schlussformel. Also einmal "Copy & Paste" der Grußformel-Funktion.

Das ist verwandt mit #629

**Comment by j-dimension** [comment]
Also zwei verschiedene Anreden und zwei verschiedene Grussformeln, sehe ich das richtig?

**Comment by j-dimension** [comment]
@Mucki526

**Comment by PBaumfalk** [comment]
> Also zwei verschiedene Anreden und zwei verschiedene Grussformeln, sehe ich das richtig?

Si.

**Comment by PBaumfalk** [comment]
Und du hast die beleidigende Schlussformel vergessen:

"Mit vorzüglicher Hochachtung"...das heißt unter Anwälten sowas wie "Fick dich"

**Comment by j-dimension** [comment]
:-)   https://twitter.com/jlawyerorg/status/1219944904652095488

**Comment by j-dimension** [comment]
Inhalt dieses Tickets: alternative Anrede / Grussformel, um bspw. in Schriftsätzen eine förmlichere / abweichende Anrede zu verwenden als in E-Mails.

**Comment by RA-crm** [comment]
Man könnte unterscheiden zwischen 
Anrede > Herr/Frau
Briefanrede > Sehr geehrter Herr, Sehr geehrte Frau  
Briefanrede fömrlich > Sehr geehrter Herr Kollege, Sehr geehrte Frau Kollegin

Mein Problem: wie erstelle ich einen Textbaustein er lautet:
... zeigen wir an, mit der Wahrnehmung und Durchsetzung der Interessen von Herrn Mustermann bauftragt zu sein.

Für Herrn Mustermann kommt bei {{ANREDE_MANDANT}} {{NAME_MANDANT}} eben "Herr Mustermann" raus und nicht "HerrN Mustermann".

any Ideas, ohne dass ich wie bisher auf die {{ANREDE_MANDANT}} verzichte und statt dessen einfach zwei Alternativen (Herrn/Frau) nutze.

**Comment by librelegal** [comment]
Die Bezeichnung dieses issues sollte vereinheitlicht werden. Es geht um Adressen, deshalb "Adressen:" voranstellen. Außerdem war ein Tippfehler im Betreff.
Insgesamt wie nachstehend:
Adressen: alternative Grussformel / Anrede

**Comment by j-dimension** [comment]
Erledigt via #800
