### ISSUE TITLE
Ergänzung beim Tab Drucken (Details der Beteiligten)

### ISSUE THREAD

**Issue by christophstoeber** [jlawyerorg/j-lawyer-org#633]
Beim Tab Drucken fehlen der Ansprechpartner sowie die drei eigenen Felder unter Beteiligte. Es wäre gut, wenn diese Infos auch angezeigt werden könnten.

**Comment by j-dimension** [comment]
Ansprechpartner hinzugefügt, die "Eigene"n erstmal nicht.
