### ISSUE TITLE
Anlagen in beA "stempeln"

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#637]
Es gibt wohl Gerichte die, mangels eigener Fachsoftware, wegen des Ausdruckens einen Anhang-Stempel einfordern.
 
![image](https://user-images.githubusercontent.com/29924198/73034668-decf1400-3e45-11ea-8c14-d20d2271e685.png)

Ich weiß nicht, ob ich das nutzen würde, aber als Angebot wäre es vielleicht sinnvoll:

Die als Anlage markierten Dateien (wenn es pdfs sind) an fest definierte Stelle mit dem Anzeigenamen stempeln vor dem Versenden. Dauert sicher eine Weile länger dann beim Versand, aber falls es hilfreich ist für die Steinzeit-Gerichte ...

**Comment by PBaumfalk** [comment]
#542 

Ist schon hier im Git
