### ISSUE TITLE
[beA] Erfolgsmeldung beA-Versand

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#638]
ich las auf Facebook, folgendes:

> Ich nutze Advoware und bekomme nach dem Versenden in einer Datei folgende Meldung:
> 
> Empfänger
> Übermittlungscode
> Meldungstext
> OSCI-Nachrichten-ID
> Zugegangen
> Übermittlungsstatus
> 
> Landgericht Kiel (24114 Kiel)
> 0800
> Auftrag ausgeführt, Dialog beendet
> DataportMsgPrefix15797861903708018749019104896360
> 23.01.2020 14:29
> Erfolgreich

Was kann das sein? der Laufzettel? Ist das irgendwas rechts-sicheres?

**Comment by PBaumfalk** [comment]
Eine kurze Erfolgsmeldung fände ich auch gut.

**Comment by j-dimension** [comment]
Die Informationen kommen aus der OSCI-Datei, welche nur verfügbar ist wenn man an Gerichte verschickt. 

@PBaumfalk @stm9x9 ist es sinnvoll die Erfolgsmeldung auch nur dann anzuzeigen, wenn die Nachricht an EGVP / an ein Gericht geht?

**Comment by PBaumfalk** [comment]
Gerade da, weil man (wie mein damaliger Ausbilder im Ref mal sagte) auf eine anwaltlich gesetzte Frist auch mal „scheißen“ kann.

Bei Gerichten immer sinnvoll, wegen Fristversäumnissen.

Mit freundlichen Grüßen / Kindly Regards

Patrick Baumfalk
Rechtsanwalt / Lawyer


Mobil:    +49 1525 53 04 194
E-Mail:   patrick.baumfalk@kanzlei-baumfalk.de


Baumfalk - Rechtsanwaltskanzlei
Hauptstr. 195
50169 Kerpen

Tel.: +49 2273 40 68 504
Fax: +49 2273 59 03 565

E-Mail: info@kanzlei-baumfalk.de
Web: www.kanzlei-baumfalk.de

Sent by Mobile

**Comment by Maz111111** [comment]
Es wäre gut, wenn die Nachricht in Zusammenhang mit dem Dialog zum Abspeichern in der Akte angezeigt würde - also im selben Fenster, damit man nur einmal einen Dialog mit ok bestätigen muss.
Ich hatte erst darüber nachgedacht, ob ein PopUp ohne ok reichen könnte. Da man aber meistens parallel noch was anderes macht, kann es dann oft vorkommen, dass man die Meldung nicht wahrnimmt. Dann könnte man es aber auch gleich lassen.

**Comment by j-dimension** [comment]
Kurze Anzeige des erfolgreichen Versands - ohne explizite Bestätigung durch Nutzer. 

Bei Nachricht an Gericht: Prüfen des Laufzettels. Bei Fehlen des Laufzettels oder bei fehlendem Eintrag 0800 - Fehler anzeigen und vom Nutzer quittieren lassen.
