### ISSUE TITLE
Rückgängigmachung von Aktenlöschung oder Dokumentenlöschung

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-org#64]
Habe gerade eine neu angelegte Akte versehentlich gelöscht. War nichts drin, Glück gehabt. Hilfreich wäre eine Rückgängigtaste zumindest der letzten 5 Aktionen...

**Comment by j-dimension** [comment]
@RA-crm

**Comment by j-dimension** [comment]
Duplikat von #722

**Comment by LazyGuy21No** [comment]
Kann mir jemand sagen, wie der Stand zu gelöschten "Akten" ist? Dazu finde ich nichts.

**Comment by j-dimension** [comment]
Für Akten derzeit kein Papierkorb.
