### ISSUE TITLE
Falldatenblatt für Verkehrsrecht

### ISSUE THREAD

**Issue by j-dimension** [jlawyerorg/j-lawyer-org#643]
- [x] Falldatenblatt entwickeln
- [x] Drebis-Integration

**Comment by PBaumfalk** [comment]
Hallo Jens,

wie funktioniert das mit der Entwicklung?

**Comment by j-dimension** [comment]
Wenn ich die Basis fertig habe, wird das sehr vergleichbar zu den RVG-Plugins sein, nur dass sich das nicht komplett alles selbst installiert, sondern dass man in einer Art App Store die gewünschten Falldatenblätter installiert. 

Die Entwicklung findet in einem eigenen Repo statt: https://github.com/jlawyerorg/j-lawyer-forms

Hast Du einen bestimmten Grund für die Frage? :-)

**Comment by PBaumfalk** [comment]
Wenn das nur Tabellen sind, wo ich Sachen eintragen muss, dann kann ich für das Arbeitsrecht auch so Falldatenblätter entwickeln…
Ich würde gerne lernen, wie das geht :)

Mit freundlichen Grüßen / Kindly Regards

Patrick Baumfalk
Rechtsanwalt / Lawyer


Mobil:    +49 1525 53 04 194
E-Mail:   patrick.baumfalk@kanzlei-baumfalk.de


Baumfalk - Rechtsanwaltskanzlei
Hauptstr. 195
50169 Kerpen

Tel.: +49 2273 40 68 504
Fax: +49 2273 59 03 565

E-Mail: info@kanzlei-baumfalk.de
Web: www.kanzlei-baumfalk.de

**Comment by j-dimension** [comment]
Es ist etwas technischer :-)

Letztlich braucht man die Möglichkeit, so Szenarien abzubilden wie 

- wenn Option / Checkbox X angeklickt, dann blende diese Oberflächenelemente aus
- Oberflächenelement A, B und C sollen sich verändern, wenn einem Dropdown D etwas ausgewählt wird
- ...

Das Falldatenblatt für die Erfassung von Unfallinformationen sieht bspw. so aus:
https://github.com/jlawyerorg/j-lawyer-forms/blob/master/src/1.12.0.0/verkehr01_ui.groovy
(runter scrollen, der Lizenztext ist länger als der Code :-)  )

Man findet dort Layoutelemente (tr= Tabellenzeile, td = Tabellenzelle, panel = Gruppierung von Elementen), Oberflächenelemente wie Textfelder, Checkboxen, Radio Buttons, ...

Das ist kein Hexenwerk, aber man braucht wahrscheinlich ein wenig Starthilfe.

Evtl. wäre es sinnvoll wenn ich mal ein 1h-Onlineseminar anbiete? Der @an-mus hat sich total schnell zu einem hypereffizienten Projektmitstreiter entwickelt. Die RVG-Plugins funktionieren sehr ähnlich.

**Comment by PBaumfalk** [comment]
Ja bitte.

Mit freundlichen Grüßen / Kindly Regards

Patrick Baumfalk
Rechtsanwalt / Lawyer


Mobil:    +49 1525 53 04 194
E-Mail:   patrick.baumfalk@kanzlei-baumfalk.de


Baumfalk - Rechtsanwaltskanzlei
Hauptstr. 195
50169 Kerpen

Tel.: +49 2273 40 68 504
Fax: +49 2273 59 03 565

E-Mail: info@kanzlei-baumfalk.de
Web: www.kanzlei-baumfalk.de

**Comment by stm9x9** [comment]
Also wenn das nur annähernd das ist, was ich mir vorstelle, dann könnte ich eventuell was im Bereich Sozialrecht und Strafrecht beitragen. Würde also auch gerne so eine Stunde investieren ...

**Comment by j-dimension** [comment]
Wenn ich es fertig bekomme, mache ich diese Woche noch einen Blogeintrag zum Feature an sich. 

Onlinetraining plane ich ein, wird aber noch etwas dauern.

**Comment by an-mus** [comment]
Das sieht alles sehr interessant aus und bietet das Potential, so ganz unterschiedliche Workflows abzubilden (wobei ich bei mir nicht so richtig viele Anwendungsfälle hab, ich arbeite wenig standadisiert).
Ich kann mir aber gut vorstellen, bei der Umsetzung einzelner Falldatenblätter mitzumachen. Aus meiner Erfahrung mit den RVG Plugins finde ich am schwierigsten sich zu überlegen, wie die Oberfläche konzipiert werden soll. Wenn also konkrete Wünsche und ein konkreten Entwurf für ein Falldatenblatt hat kann ich mich gerne um die Umsetzung kümmern. 
Um den Code zu verstehen hat es mir am Anfang im übrigen sehr geholfen, mir den Code mit einem guten Code-Editor mit Syntaxhervorhebung anzuschauen. Ich mache das mit Visual Studio Code von Microsoft. Ist Opensource und läuft auf allen Plattformen. Für die Programmiersprache Groovy gibt es ein Plugin.
@j-dimension: hattest du auch die Idee über die Falldatenblätter sowas wie die Aktenbuchhaltung oder andere Features zu realisieren?

**Comment by j-dimension** [comment]
> @j-dimension: hattest du auch die Idee über die Falldatenblätter sowas wie die Aktenbuchhaltung oder andere Features zu realisieren?

Wahrscheinlich eher nicht. Die Falldatenblätter sind sehr gut für Sachen geeignet, die (a) nicht von jedem benötigt werden und (b) einer gewissen Dynamik / Flexibilität unterliegen. Das ist mit der Buchhaltung nicht unbedingt der Fall - daher werde ich das eher auf herkömmlichem Weg umsetzen.
