### ISSUE TITLE
CRM-System anbinden, bspw. VTiger

### ISSUE THREAD

**Issue by Goodadvicer** [jlawyerorg/j-lawyer-org#644]

**Comment by j-dimension** [comment]
Für was würde das Ticketsystem genutzt werden? Geht es um Help Desk? Oder beliebige Kundenanfragen?

**Comment by Goodadvicer** [comment]
Hauptsächlich geht es darum, telefonische Anfragen aller Art zu bearbeiten, für die es keine Akte gibt, z.B. für Interessenten.

Aber auch um interne Aufgaben bestmöglich zu verwalten.

**Comment by RA-crm** [comment]
Ist da eine Akte (zB Allgemeine Mandantsanfragen) mit Etikettierung der Mail oder der Telefonnotiz sowie mit WV und Fristen nicht ausreichend?

**Comment by j-dimension** [comment]
Angesichts des Aufwands und der geringen Nachfrage mache ich hier zu. Konkrete Einzelanforderungen werde ich aber gern umsetzen, das hier ist aber zu unscharf und "groß".
