### ISSUE TITLE
Möglichkeit Projektmanagement, Projektverwaltung

### ISSUE THREAD

**Issue by Goodadvicer** [jlawyerorg/j-lawyer-org#649]

**Comment by j-dimension** [comment]
Geht es um soetwas wie #41 

Oder eher in Richtung reines Projektmanagement mit Aufgaben, ggf. Kanban-Boards etc.?

**Comment by Goodadvicer** [comment]
Ja vom Grundsatz her wie #41. 
In der Hauptakte sollte es die Möglichkeit geben, weitere zusammengehörende Unterakten anzulegen.

**Comment by j-dimension** [comment]
Okay, dann lassen wir #41 offen und machen dieses hier zu.
