### ISSUE TITLE
[bea] Fehlermeldung bei nicht zugestellten Nachrichten?

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#651]
ich las im BRAK-Newsletter (auch wenn das laut Gericht nicht reichen soll):

> Seine Kanzleisoftware verschiebe die Nachrichten erst dann in einen „Versendet-Korb“, wenn eine Eingangsbestätigung des Gerichts eingegangen sei. Ansonsten würde ein Fehlercode erzeugt und es gebe auch Fehlermeldungen beim Herunterfahren des PC.

Das wäre denke ich eine Idee auch für j-l. Wenn eine Nachricht x min im Postausgang verschimmelt => Fehlermeldung. Wenn man j-l schließt und es ist noch was im Postausgang => Meldung (wie jetzt schon für noch offene Dateien)

**Comment by stm9x9** [comment]
Verständnisfrage dazu: Die Eingangsbestätigung des Empfängers, wie hier zu sehen https://www.brak.de/zur-rechtspolitik/newsletter/bea-newsletter/2019/ausgabe-31-2019-v-17102019/#nl3120192 gibt es ja nachwievor nicht über die API, oder?

Aber trifft es zu, daß nicht j-l sondern der beA-Server die Nachricht aus dem Postausgangsordner in den gesendet-Ordner verschiebt? Und trifft es zu, daß er das erst macht, wenn der Server die Eingangsbestätigung erhalten hat?

**Comment by j-dimension** [comment]
> Aber trifft es zu, daß nicht j-l sondern der beA-Server die Nachricht aus dem Postausgangsordner in den gesendet-Ordner verschiebt? Und trifft es zu, daß er das erst macht, wenn der Server die Eingangsbestätigung erhalten hat?

Ja, das Verschieben übernimmt das beA. 

Was der "Trigger" für das Verschieben ist weiß ich nicht genau. Meines Wissens passiert das Verschieben wenn die Nachricht an das EGVP übergeben wurde (nicht: erfolgreich zugestellt wurde). Letztlich muss hier immer der Laufzettel geprüft werden, der über die API nicht zuverlässig abgerufen werden kann.

**Comment by j-dimension** [comment]
siehe auch #689
