### ISSUE TITLE
Mehrere Server im Anmeldebildschirm hinterlegen

### ISSUE THREAD

**Issue by PBaumfalk** [jlawyerorg/j-lawyer-org#656]
Hallo zusammen,

war lange nicht mehr ganz aktiv hier (sorry, viel zu tun).
Es wäre super, wenn man bei der Serverauswahl eine Combo-Box hätte, wo man mehrere Server abspeichern oder hinterlegen könnte. Hintergrund: Ich tue mich mit einem anderen Anwalt nur für das Inkassogeschäft zusammen, da wollen wir auch J-Lawyer nutzen.

Viele Grüße aus Kerpen

**Comment by j-dimension** [comment]
@PBaumfalk da könnt Ihr Euch auch jetzt schon helfen:
http://www.j-lawyer.org/downloads/documentation/j-lawyer.org-UserGuide-de.html#__RefHeading___Toc2289_656293559

Das angefragte Feature setze ich trotzdem um.

**Comment by stm9x9** [comment]
könnte man diese Auswahl auf den ersten Reiter verschieben? ggf indem man im Reiter Verbindung noch ein Feld "Server oder Kanzlei Name" macht und dann diesen Namen im ersten Reiter als Auswahl anbietet. ggf auch nur solche Server, die einen Eintrag bei Name haben und damit als "will ich öfter nutzen" gekennzeichet sind.

**Comment by j-dimension** [comment]
Könnte man. Braucht aber ein neues Ticket.
