### ISSUE TITLE
[bea] Visitenkarte 

### ISSUE THREAD

**Issue by PBaumfalk** [jlawyerorg/j-lawyer-org#659]
Wenn ich eine Nachricht über das beA versende wird die Visitenkarte nicht mitgesendet. Nur die Safe-ID. Das Mahngericht in Uelzen hat sich beschwert und die Rechtsanwaltskammer hat herausgefunden, dass es wohl an der Kanzleisoftware liegt.

**Comment by j-dimension** [comment]
Hmm... mir ist nicht bekannt dass die Visitenkarte gesendet werden MUSS. 

Kannst Du mal eine Nachricht in die Mailingliste schreiben, ob das bei anderen schonmal angemeckert wurde und ob eine Rechtsgrundlage bekannt ist?

**Comment by PBaumfalk** [comment]
[2020-02-11_Schreiben-AGUelzen.pdf](https://github.com/jlawyerorg/j-lawyer-org/files/4204802/2020-02-11_Schreiben-AGUelzen.pdf)

[Visitenkarte-Screenshot.pdf](https://github.com/jlawyerorg/j-lawyer-org/files/4204803/Visitenkarte-Screenshot.pdf)

**Comment by PBaumfalk** [comment]
Es gibt keine Rechtsgrundlage. Die Gerichte finden das nur "geil"...

**Comment by j-dimension** [comment]
Okay. Dann machen wir den Friedrich Liechtenstein und bauen das ein. Muss aber erst analysieren wie das und ob das geht über die Schnittstelle.

**Comment by stm9x9** [comment]
"um dem Gericht die Prüfung der wirksamen eRV- Übertragung zukünftig zu erleichtern" wie meinen!? Was wollen die damit prüfen?

**Comment by PBaumfalk** [comment]
Die prüfen nicht die Safe-ID sondern die Visitenkarte. Halte ich für falsch, aber was soll’s.

**Comment by stm9x9** [comment]
Ja, aber worauf prüfen die? Meinen die wegen § 130a IV ZPO? Dafür gibt es doch im Prüfvermerk das Merkmal vertrauenswürdiger Herkunftsnachweis: VHN?

**Comment by j-dimension** [comment]
@stm9x9 @PBaumfalk jetzt bei anderen Anwendern verstärkte Beschwerden vom AG Balingen. Wortlaut in Etwa "in unserem System ist das Feld "absendende Person" leer. Ein Anwender hat sich an den beA-Support gewandt und die Rückmeldung war: BusinessCard.html muss mitgeschickt werden. 
Ganz offensichtlich wird eine HTML-Datei zum Füllen der Systeme der Justiz verwendet. Für mich ist das fast unglaublich, ich kann dort ja alles möglich reinschreiben und über die Schnittstelle einreichen. 

Ich weiß dass die Justizsysteme in BW "speziell" sind, aber dass nun vom beA-Support die Aussage kommt, überrascht mich.

**Comment by PBaumfalk** [comment]
Und wie wird das Problem gelöst? Man will ja keine Probleme mit dem Gericht haben. Wenn denen das zu viel Arbeit ist, sollte man die html mitschicken...

**Comment by j-dimension** [comment]
Der Versand mit Visitenkarte ist nirgends dokumentiert. Ich habe eine API gefunden, über welche ich die Daten zur Verfügung stellen kann, sie kommen aber nicht im beA an. 
--> Support aktiviert

**Comment by j-dimension** [comment]
Support: 

"Die von uns aufgesetzte KSW Testsuite enthält keine extra Beschreibung der Visitenkarten und dennoch werden Sie in der beA webUI nach dem Versandt angezeigt. Im Moment gehe ich stark davon aus, dass diese automatisch generiert wird, aus den Metadaten, die an die SAFE-Identität gebunden sind, von der aus die Nachricht versendet wird."

Katze -> Schwanz

**Comment by j-dimension** [comment]
Information von einem der sich mit den IT-Systemen der Justiz hervorragend auskennt: 

"Visitenkarte ist Blödsinn, wird nicht genutzt und es gibt keine rechtliche Grundlage"

**Comment by j-dimension** [comment]
neues Feedback vom beA-KSW-Support. IdentityDTOConverter prüfen / erweitern.

**Comment by j-dimension** [comment]
beA wrapper ticket 31
