### ISSUE TITLE
Reihenfolge im Dokumenten-Kontext-Menü

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#661]
![image](https://user-images.githubusercontent.com/29924198/74694095-04560000-51ef-11ea-8f89-e8ca0b7684d9.png)

Ich würde - weils IMHO öfter genutzt wird / werden wird - die beA-Senden-Einträge vorziehen vor die Mail-Einträge

Verschlüsselte pdf ablegen - paßt das nicht besser zu ablegen als pdf statt so isoliert?

**Comment by j-dimension** [comment]
> Ich würde - weils IMHO öfter genutzt wird / werden wird - die beA-Senden-Einträge vorziehen vor die Mail-Einträge
> 

Das würde ich erstmal nicht machen, da die Nutzungsintensität Mail immer noch höher als die von beA ist.

> Verschlüsselte pdf ablegen - paßt das nicht besser zu ablegen als pdf statt so isoliert?

Mach ich.

**Comment by j-dimension** [comment]
> > Verschlüsselte pdf ablegen - paßt das nicht besser zu ablegen als pdf statt so isoliert?
> 
> Mach ich.

Ich ändere meine Meinung. Mir ist die Nutzungsfrequenz für das Exportieren verschlüsselter PDFs zu gering, um es so prominent nach oben zu positionieren.
