### ISSUE TITLE
Icons und Farben im Dokument-Kontext-Menü

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#662]
![image](https://user-images.githubusercontent.com/29924198/74694213-86debf80-51ef-11ea-823d-7e6fdf103f64.png)

Kann das Mail-Versenden statt dem Sende-Pfeil das Mail-Symbol aus der linken Seitenleiste bekommen? 

Und Datum anpassen eine Zahl in das Kalenderblatt?

Und zu guter Letzt: in vielen Anwendungen ist der Löschen-Eintrag rot gefärbt. Einerseits als Warnfarbe, andererseits zu schneller finden.

**Comment by PBaumfalk** [comment]
Ich würde die Anpassungen erstellen. Allerdings erst nach Karneval aus Gründen!

Bitte mich assignen.

Mit freundlichen Grüßen / Kindly Regards

Patrick Baumfalk
Rechtsanwalt / Lawyer


Mobil:    +49 1525 53 04 194
E-Mail:   patrick.baumfalk@kanzlei-baumfalk.de


Baumfalk - Rechtsanwaltskanzlei
Hauptstr. 195
50169 Kerpen

Tel.: +49 2273 40 68 504
Fax: +49 2273 59 03 565

E-Mail: info@kanzlei-baumfalk.de
Web: www.kanzlei-baumfalk.de

Sent by Mobile

**Comment by j-dimension** [comment]
Ich verlinke heute Abend die aktuellen Icons, damit die Auflösung etc. ablesbar ist. Dann weise ich das Ticket @PBaumfalk  zu.

Danke!

**Comment by j-dimension** [comment]
Ich verlinke hier jeweils die größeren Varianten. Benötigt werden dann wieder die verschiedenen Auflösungsvarianten, da es große, mittlere und kleine Lösch-Buttons etc. gibt. 

Es ist für die Qualität des Icons immer sinnvoll, alle Bearbeitungen am am größten aufgelösten Icon vorzunehmen und dann nach unten zu skalieren. 

Papierkorb: https://github.com/jlawyerorg/j-lawyer-org/blob/master/j-lawyer-client/src/icons32/agt_stop1.png

Mail: https://github.com/jlawyerorg/j-lawyer-org/blob/master/j-lawyer-client/src/icons32/material/Icons2-30-blue.png

Kalender: evtl. das hier als Grundlage nehmen: https://github.com/jlawyerorg/j-lawyer-org/blob/master/j-lawyer-client/src/icons32/material/Icons2-14-blue.png

Bei der Rotfärbung bitte die j-lawyer.org-Farbpalette nutzen:
public static Color COLOR_LOGO_RED=new Color(222, 49, 59);

Für das Kontextmenü werden die Icons in 20x20 benötigt, und sollten wieder 1px oder 2px Rand haben. Hintergrund transparent. 

Icons einfach hier dranhängen und das Ticket an mich assignen. 

Danke!

**Comment by PBaumfalk** [comment]
Mache ich nach Karneval! Ist auf der ToDo.

Mit freundlichen Grüßen / Kindly Regards

Patrick Baumfalk
Rechtsanwalt / Lawyer


Mobil:    +49 1525 53 04 194
E-Mail:   patrick.baumfalk@kanzlei-baumfalk.de


Baumfalk - Rechtsanwaltskanzlei
Hauptstr. 195
50169 Kerpen

Tel.: +49 2273 40 68 504
Fax: +49 2273 59 03 565

E-Mail: info@kanzlei-baumfalk.de
Web: www.kanzlei-baumfalk.de

Sent by Mobile

**Comment by PBaumfalk** [comment]
> Ich verlinke hier jeweils die größeren Varianten. Benötigt werden dann wieder die verschiedenen Auflösungsvarianten, da es große, mittlere und kleine Lösch-Buttons etc. gibt.
> 
> Es ist für die Qualität des Icons immer sinnvoll, alle Bearbeitungen am am größten aufgelösten Icon vorzunehmen und dann nach unten zu skalieren.
> 
> Papierkorb: https://github.com/jlawyerorg/j-lawyer-org/blob/master/j-lawyer-client/src/icons32/agt_stop1.png
> 
> Mail: https://github.com/jlawyerorg/j-lawyer-org/blob/master/j-lawyer-client/src/icons32/material/Icons2-30-blue.png
> 
> Kalender: evtl. das hier als Grundlage nehmen: https://github.com/jlawyerorg/j-lawyer-org/blob/master/j-lawyer-client/src/icons32/material/Icons2-14-blue.png
> 
> Bei der Rotfärbung bitte die j-lawyer.org-Farbpalette nutzen:
> public static Color COLOR_LOGO_RED=new Color(222, 49, 59);
> 
> Für das Kontextmenü werden die Icons in 20x20 benötigt, und sollten wieder 1px oder 2px Rand haben. Hintergrund transparent.
> 
> Icons einfach hier dranhängen und das Ticket an mich assignen.
> 
> Danke!

Sorry wenn ich doof frage: In welchen Auflösungen werden die Icons benötigt? Nur 20x20? "Große, kleine und mittlere" sind ja leider keine Maße :(

Beste Grüße

**Comment by j-dimension** [comment]
> Sorry wenn ich doof frage: In welchen Auflösungen werden die Icons benötigt? Nur 20x20? "Große, kleine und mittlere" sind ja leider keine Maße :(

Die gleichen wie beim letzten mal :-)
https://github.com/jlawyerorg/j-lawyer-org/issues/529#issuecomment-569128405

Allerdings kann jetzt die 128px-Variante entfallen.

**Comment by j-dimension** [comment]
Ich schiebe das erstmal in die 1.13. Sollte vorher noch etwas verfübar sein, ziehe ich es wieder in die 1.12.

**Comment by PBaumfalk** [comment]
Sorry, dass das so lange dauert...habe gerade echt viel hier an der Brause...:(

**Comment by j-dimension** [comment]
Ich mache das im Sinne der Tickethygiene erstmal zu.

**Comment by stm9x9** [comment]
> > Darf ich nochmal an die Idee eines roten Löschen-Eintrags hinweisen?
> 
> An wen geht die Frage?

wenn neben dem Text "löschen" auch der Papierkorb rot werden sollte, dann an @PBaumfalk. Ansonsten nur Dich :-)
