### ISSUE TITLE
XJustiz-Viewer integrieren

### ISSUE THREAD

**Issue by j-dimension** [jlawyerorg/j-lawyer-org#667]
http://ervjustiz.de/neue-version-des-xjustiz-aktenviewers#more-1326

Windows-only, aber immerhin :-)

**Comment by j-dimension** [comment]
UM hat heute Schnittstelle bereitgestellt.

**Comment by j-dimension** [comment]
Xjustiz (von j-lawyer.org generiert) mit abweichender Struktur i.Vgl. zur Testakte UM.

Die von j-lawyer.org erstellten XMLs haben die Dokument-Knoten direkt unter der Wurzel, UM Testakte hat eine Struktur Wurzel > akte > inhalt > dokument. Vermutlich ist die Struktur Ihrer Testakte jene, die von Gerichten generiert wird - ist diese Annahme korrekt? Oder wäre es sinnvoll, wenn j-lawyer.org die gleiche Struktur erzeugt?

**Comment by j-dimension** [comment]
Token ist im Wrapper unterzubringen

**Comment by stm9x9** [comment]
> Vermutlich ist die Struktur Ihrer Testakte jene, die von Gerichten generiert wird - ist diese Annahme korrekt? Oder wäre es sinnvoll, wenn j-lawyer.org die gleiche Struktur erzeugt?

Die Strukturdatensatz-xmls? Da sollte sich j-l IMHO an das halten, was beA-web auch produziert. Beispieldateien wenn nötig auf Anfrage.

**Comment by j-dimension** [comment]
> Da sollte sich j-l IMHO an das halten, was beA-web auch produziert.

Ja genau. Es scheint einen Unterschied zu geben zwischen Akten die man zur Einsicht zur Verfügung gestellt bekommt, und den Strukturdatensätzen die man für den Versand von Dokumenten verwendet.

Bin da gerade an der Klärung.

**Comment by librelegal** [comment]
In der pre-release der 1.12 wird auch bei Linux Clients ein download gestartet. Ein Hinweis darauf, dass diese Modul - leider - nur unter Windows und nicht auch unter Linux zur Verfügung steht, erscheint sinnvoller. Habe die .exe aber auch nicht mit wine getestet und wäre neugierig, ob das Sinn machte. xjustiz stellt eine Brücke zur Justiz dar, als solches ein Fortschritt.

**Comment by j-dimension** [comment]
Ich habe sowohl Wine als auch Mono probiert, geht beides nicht, aufgrund verwendeter Drittbibliotheken.
