### ISSUE TITLE
Variablen für automatische Dokumentenbenennung

### ISSUE THREAD

**Issue by Maz111111** [jlawyerorg/j-lawyer-org#668]
Derzeit kann man ein Dokument automatisch mit der Variablen DRITTE benennen lassen bzw. diese in den Namen einbauen.
Sieht bei mir z.B so aus:
"Schreiben an DRITTE (Gegnervertreter) per beA.odt"
Das generiert dann - wenn man den gegnerischen Kollegen mit Namen und Firma aufgenommen hat (wie es oftmals notwendig ist, da Kanzleiname und Anwaltsname nicht identisch sind) - sehr lange Dateinamen, da DRITTE die Firmenbezeichnung gefolgt von Zu- und Vornamen generiert.

Wäre es möglich, hier zwei andere Spielarten zu programmieren? 
Also FADRITTE und NAMEDRITTE, wobei ersteres dann nur den Firmennamen in die Benennung übernimmt und letzteres den Zu- und Vornamen des Dritten.
Dasselbe dann bitte auch für MANDANT.

**Comment by j-dimension** [comment]
Das ist m.E. nicht zielführend, weil man dann unterschiedliche Vorlagen braucht, je nachdem ob es sich um eine Firma handelt oder eine Privatperson. Das wollte ich mit der aktuellen Automatik gerade vermeiden.

Wie wäre eine Logik a la: 
wenn Firmenname + Name zu lang (bspw. 30 Zeichen), dann nimm nur Name
?

**Comment by Maz111111** [comment]
Hmm…ich hoffte man könne sich darauf einlassen, dass der Anwender selbst entscheidet, welche Namensgebung er bevorzugt (deswegen fragte ich nach zwei zusätzlichen Möglichkeiten).
Ich würde für meinen Teil bei Vorlagen in denen der Dritte, der gegnerische RA ist, den Namen des RA in der Dokumentenbezeichnung bevorzugen und wenn der Dritte das Gericht ist, die Fa. 
Für beide habe ich ohnehin unterschiedliche Vorlagen.
Aktuell kommt es zu Namensgebungen wie folgt:
"Schreiben an Rechtsanwalt Thomas Meier Meier Thomas (Gegnervertreter) per beA.odt"
Da würde eine Abkürzungslogik nichts verbessern.
Und bevor man darüber nachdenkt, warum bei einer Einzelkanzlei, in der Firmenname und Inhaber gleich sind, dann beides aufgenommen wird.
Die Fa nehme ich auf, weil meine (nach Möglichkeit allgemeingültigen) Vorlagen im Adressfenster auf der Fa. basieren. Anderenfalls müsste ich eine eigene Vorlage für eine Anwaltssozietät auf der Gegenseite basteln. Den Namen nehme ich auf, damit der Kollege in der Vorlage automatisch angesprochen werden kann.

**Comment by j-dimension** [comment]
> Aktuell kommt es zu Namensgebungen wie folgt:
> "Schreiben an Rechtsanwalt Thomas Meier Meier Thomas (Gegnervertreter) per beA.odt"
> Da würde eine Abkürzungslogik nichts verbessern.

Warum nicht, mit einer Abkürzungslogik hättest Du dann bei Überschreiben einer Zeichenanzahl vollautomatisch nur noch
"Schreiben an Meier Thomas (Gegnervertreter) per beA.odt"

**Comment by Maz111111** [comment]
Das stimmt, ich hatte irgendwie die Vorstellung, dass nach 30 Zeichen wahllos gekappt wird. Aber so hattest Du es nicht beschrieben.
Deine Lösung finde ich trotzdem nur semi.
Erstens könnte man es nicht beeinflussen, ob gekürzt wird oder nicht, da die Namen der Dritten eben so lang sind, wie sie sind und zweitens kommt es dann zu ungleichförmigen Benennungen der Schriftsätze in verschiedenen Akten - je nach Länge des Namens des Dritten.
Das wird dann auch nur irritieren, wenn man beim Durchsehen des Akteninhaltes jedes mal umdenken muss.
Ich würde es dann eher so lassen, wie es ist.

**Comment by j-dimension** [comment]
Magst Du es in der Mailingliste ansprechen? (und diese Diskussion hier verlinken)

Wenn andere auch dieses Mehr an Kontrolle (und Vorlagen) haben möchten: technisch alles machbar!

Ich lasse das Ticket solange offen.

**Comment by j-dimension** [comment]
anderer Anwender:

>> Praktisch wäre es auch, wenn alle Variablen in den Dateinamen genutzt
>> werden könnten. Dies scheint mir derzeit auf ...NAME begrenzt zu sein. 

> Welche Variablen würden benötigt? Wenn sich eine geschlossene Liste
> einiger Variablen definieren ließe, würde sich der Aufwand deutlich
> reduzieren. 

Varible "Kurzrubrum" wäre m.E. sinnvoll, "Dritter" (hier nur Name und Zeichen), bzw. bei mir gibt es auch die Variablen für "Gericht" (Name und Zeichen) und Akte_Wegen

**Comment by stm9x9** [comment]
Initialien wäre noch ganz praktisch für die, die es gerne kurz haben

**Comment by GuidoBo** [comment]
Wir verwenden Beteiligungsaten GERICHT (respektive Gericht2 für die 2. Instanz) und GEGNERVT (Gegnervertreter). 

Könnte man die [Dateinamen-Automatik](http://www.j-lawyer.org/downloads/documentation/j-lawyer.org-UserGuide-de.html#__RefHeading___Toc1982_186327974) dahingehend erweitern, dass nicht nur die Variablen MANDANT, GEGNER und DRITTER sondern alle Beteiligtenrollen aufgelöst werden?

**Comment by iradraconis** [comment]
Also ich nutze das bereits so. Das funktioniert, wenn ich beispielsweise die Vorlage so benenne "KFA an GERICHT1.odt", so wird das Gericht I. Instanz direkt eingefügt und der Dateiname entsprechend angelegt.

**Comment by GuidoBo** [comment]
Habe mein Posting gerade auch schon editiert. My bad!

**Comment by j-dimension** [comment]
Ich habe die Dokumentation diesbezüglich etwas"geschärft".
