### ISSUE TITLE
[beA] "eEB angefordert" nicht aus den beA-Schnittstelleninformationen beziehen, sondern aus XJustiz-SDS

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#669]
Ich bin mir gerade nicht sicher, ob das schon funktionieren sollte:

![image](https://user-images.githubusercontent.com/29924198/75466350-57b41500-598a-11ea-8dc5-500e25fd6905.png)

hier wird ein eEB gefordert (im web geprüft), aber hier ist es ausgegraut und nicht abgebbar.

**Comment by j-dimension** [comment]
Einmal client.log und Zeitpunkt, bitte.

**Comment by j-dimension** [comment]
Ob ein eEB angefordert ist oder nicht, steckt direkt in den Metadaten aus der Schnittstelle. j-lawyer.org wendet keine weitere Logik auf dieses Flag an.

**Comment by stm9x9** [comment]
Steckt die Info nicht auch in der xustiz_nachricht.xml? Weil mir scheint die Schnittstelle hat mal wieder ein Problem:

Ich habe in der Zwischenzeit die Nachricht im Web geöffnet, um das eEB abzugeben. JETZT wird mir auch in j-l das eEB zum Abgeben angeboten.

**Comment by stm9x9** [comment]
Ich habe noch eine ungelesene Nachricht mit eEB gefunden: wieder ausgegraut.

im client.log ist vorher nur das zigfache

[org.jlawyer.bea.BeaWrapper] Is EGVP? xxxx

und beim Öffnen der Nachricht kommt nichts.

**Comment by j-dimension** [comment]
Das deutet tatsächlich auf einen Fehler der Schnittstelle hin. 

Weißt Du ob der Versender mit beA Web arbeitet oder einer Kanzleisoftware?

Meine Vermutung: beA hat die eEB-Informationen redundant - einmal im Datenmodell der Nachricht, und einmal in der XJustiz-Nachricht. Vermutlich kann man über XJustiz-Datensatz ein eEB anfordern, wenn aber eine KSW vergisst, das Attribut zusätzlich in der Nachricht zu setzen, dann kommt es zu beschriebenem Fehler.

**Comment by stm9x9** [comment]
> Weißt Du ob der Versender mit beA Web arbeitet oder einer Kanzleisoftware?

ist ein Gericht, also Fachsoftware

> Meine Vermutung: beA hat die eEB-Informationen redundant - einmal im Datenmodell der Nachricht, und einmal in der XJustiz-Nachricht. Vermutlich kann man über XJustiz-Datensatz ein eEB anfordern, wenn aber eine KSW vergisst, das Attribut zusätzlich in der Nachricht zu setzen, dann kommt es zu beschriebenem Fehler.

AFAIK wird im EGVP-System das eEB ausschließlich über den entsprechenden Flag im XJustiz-Datensatz angefordert. Erst beA wird das da auslesen und dann zusätzlich über die Schnittstelle bekanntgeben.

Wie ja bekannt, werden bei web-ungelesenen Nachrichten zb die Absender anders angezeigt über die Schnittstelle. Und wir hatten ja auch schon, daß andere Infos erst nach dem web-lesen über die API in der Nachrichtenübersicht übermittelt wurden. Meine Vermutung: bea-API liefert die Info schlicht nicht, bevor nicht die Nachricht im web gelesen und entschlüsselt wurde.

Abhilfe wäre dann nur, nicht auf die API-Info vertrauen sondern selber in der xml gucken. Denn da ist die originäre Quelle der Information.

**Comment by j-dimension** [comment]
> Abhilfe wäre dann nur, nicht auf die API-Info vertrauen sondern selber in der xml gucken. Denn da ist die originäre Quelle der Information.

Ja, wird wohl so gemacht werden müssen. Im Posteingang (tabellarische Darstellung) kann ich's dann allerdings nicht anzeigen, nur in den Detailansichten.

**Comment by j-dimension** [comment]
Heute eine weitere Meldung hierzu von @RasimT erhalten.

**Comment by j-dimension** [comment]
BRAK: "das ist normal" :-D

**Comment by RasimT** [comment]
was machen wir jetzt!

Dem Gericht mitteilen, dass unsere Schnittstelle nicht tut!?!? :))))))))

 

Von: Jens Kutschke [mailto:notifications@github.com] 
Gesendet: Mittwoch, 11. März 2020 22:19
An: jlawyerorg/j-lawyer-org <j-lawyer-org@noreply.github.com>
Cc: Rechtsanwalt Tosun <tosun@kanzlei-albstadt.de>; Mention <mention@noreply.github.com>
Betreff: Re: [jlawyerorg/j-lawyer-org] [beA] "eEB angefordert" nicht aus den beA-Schnittstelleninformationen beziehen, sondern aus XJustiz-SDS (#669)

 

BRAK: "das ist normal" :-D

**Comment by j-dimension** [comment]
Workaround verfügbar: https://www.j-lawyer.org/?p=3481

**Comment by RasimT** [comment]
Wow! Super! Werde mal die Datei austauschen!

Vielen Dank!

 

 

Von: Jens Kutschke [mailto:notifications@github.com] 
Gesendet: Sonntag, 15. März 2020 20:41
An: jlawyerorg/j-lawyer-org <j-lawyer-org@noreply.github.com>
Cc: RasimT <tosun@kanzlei-albstadt.de>; Mention <mention@noreply.github.com>
Betreff: Re: [jlawyerorg/j-lawyer-org] [beA] "eEB angefordert" nicht aus den beA-Schnittstelleninformationen beziehen, sondern aus XJustiz-SDS (#669)

 

Closed #669 <https://github.com/jlawyerorg/j-lawyer-org/issues/669> .

**Comment by RasimT** [comment]
die Beschreibung, welche Datei wo ersetzt werden muss, ist leider nicht ganz nachvollziehbar für mich

lib habe ich nicht gefunden

liegt aber an mir

 

Von: Jens Kutschke [mailto:notifications@github.com] 
Gesendet: Sonntag, 15. März 2020 20:41
An: jlawyerorg/j-lawyer-org <j-lawyer-org@noreply.github.com>
Cc: RasimT <tosun@kanzlei-albstadt.de>; Mention <mention@noreply.github.com>
Betreff: Re: [jlawyerorg/j-lawyer-org] [beA] "eEB angefordert" nicht aus den beA-Schnittstelleninformationen beziehen, sondern aus XJustiz-SDS (#669)

 

Closed #669 <https://github.com/jlawyerorg/j-lawyer-org/issues/669> .

**Comment by RasimT** [comment]
mein Fehler habe den Pfad in der box gesucht

habe es gefunden

 

 

Von: Jens Kutschke [mailto:notifications@github.com] 
Gesendet: Sonntag, 15. März 2020 20:41
An: jlawyerorg/j-lawyer-org <j-lawyer-org@noreply.github.com>
Cc: RasimT <tosun@kanzlei-albstadt.de>; Mention <mention@noreply.github.com>
Betreff: Re: [jlawyerorg/j-lawyer-org] [beA] "eEB angefordert" nicht aus den beA-Schnittstelleninformationen beziehen, sondern aus XJustiz-SDS (#669)

 

Workaround verfügbar: https://www.j-lawyer.org/?p=3481

**Comment by RasimT** [comment]
zur Info

habe die Datei ersetzt, 

eine Nachricht vom Gericht wiederhergestellt

eb angefordert Feld gelb aber keine Abgabe möglich???

 

 

 

Von: Jens Kutschke [mailto:notifications@github.com] 
Gesendet: Sonntag, 15. März 2020 20:41
An: jlawyerorg/j-lawyer-org <j-lawyer-org@noreply.github.com>
Cc: RasimT <tosun@kanzlei-albstadt.de>; Mention <mention@noreply.github.com>
Betreff: Re: [jlawyerorg/j-lawyer-org] [beA] "eEB angefordert" nicht aus den beA-Schnittstelleninformationen beziehen, sondern aus XJustiz-SDS (#669)

 

Workaround verfügbar: https://www.j-lawyer.org/?p=3481

**Comment by j-dimension** [comment]
Bitte mal den Anhang xjustiz_nachricht.xml dieser beA-Nachricht lokal speichern und per E-Mail senden.

**Comment by RasimT** [comment]
Von: Jens Kutschke [mailto:notifications@github.com] 
Gesendet: Sonntag, 15. März 2020 22:56
An: jlawyerorg/j-lawyer-org <j-lawyer-org@noreply.github.com>
Cc: RasimT <tosun@kanzlei-albstadt.de>; Mention <mention@noreply.github.com>
Betreff: Re: [jlawyerorg/j-lawyer-org] [beA] "eEB angefordert" nicht aus den beA-Schnittstelleninformationen beziehen, sondern aus XJustiz-SDS (#669)

 

Bitte mal den Anhang xjustiz_nachricht.xml dieser beA-Nachricht lokal speichern und per E-Mail senden.
