### ISSUE TITLE
Warnmeldung beim schließen des Clients

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-org#67]
Die Warnmeldung beim Schließen des Clients sollte auch kommen, wenn kein Dokument über jlawyer geöffnet ist, sondern wenn man versehentlich das Kreuzchen rechts oben betätigt, z.B. weil man ein anderes Programm schließen will. Ich mache mir immer wieder mal versehentlich den Client zu, weil ich zu schnell klicke. "Meldung - Wirklich schließen" ist sinnvoll. Evt. als auswählbare Option in einem Einstellungsmenü zum Abwählen für die, denen das natürlich nie passiert :-)

**Comment by j-dimension** [comment]
Ich erlaube mir das Ticket zu schliessen. Im Vergleich zur Menge der anderen Tickets und deren "Mehrwert" werde ich voraussichtlich nie zur Arbeit an diesem Ticket kommen.
