### ISSUE TITLE
Dokument erstellen: Fehler bei AZ-Übernahme bei zwei identischen Beteiligten in gleicher Rolle

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#671]
Ich habe ein Gericht zweimal in einer Akte A1 und A2 und ein weiteres einmal B. A1 und A2 mit unterschiedlichen Aktenzeichen.

Ich habe eine (alte) Vorlage u.a. mit DRITTE_FIRMA, DRITTE_STRASSE, DRITTE_ORT, DRITTE_PLZ und DRITTE_AKTE_ZEICHEN.

Wenn ich B als Dritter in den Beteiligten einstelle, wird in alle fünf Variablen was übernommen.
Wenn ich B als (neu eingerichtet) Gericht einstelle und dann im Dokumentendialog bei B unter Dritte ein Kreuz mache, dann wird FIRMA, ORT PLZ und STRASSE gesetzt, AKTE_ZEICHEN bleibt aber leer.

Wenn ich A1 als Dritter in den Beteiligten einstelle und A2 als Gericht, dann wird - egal ob ich bei A1 oder A2 das Kreuz unter Dritter mache - immer das Aktenzeichen von A1 übernommen. Wenn ich beide als Gericht einstelle, dann wird wie bei B gar kein Aktenzeichen übernommen.

**Comment by stm9x9** [comment]
Wenn ich A1 und A2 als Dritter einstelle, dann wird - auch egal ob ich bei A1 oder A2 das Kreuz unter Dritter mache - immer das Aktenzeichen von A1 übernommen. A1 dominiert also immer über A2.

Nur wenn ich A2 als Dritter einstelle, aber A1 als Gericht, dann wird die Aktenzeichen von A2 genommen. Bei beiden.

Mir scheint also: Aktenzeichen wird nur übernommen, wenn als "Dritte" bei den Beteiligten eingestellt wird, sonst wird gar keins übernommen. Und wenn, dann wird immer nur das Aktenzeichen vom ersten namentlich gleichen Dritten übernommen.

**Comment by j-dimension** [comment]
Test offen
