### ISSUE TITLE
Fehler beim Speichern von beA Files in der Akte bei zu langem Namen

### ISSUE THREAD

**Issue by Maz111111** [jlawyerorg/j-lawyer-org#672]
Ich habe eine beA Nachricht an das Gericht mit 9 Anhängen versendet. Beim Abspeichern in der Akte kam obiger Fehler.
Das Problem gab es auch schon bei zu langen MailNamen.
Die Nachricht wurde aber vollständig und erfolgreich versendet. Es klappt nur das Speichern in der Akte nicht.

**Comment by Maz111111** [comment]
Ergänzung es liegt nicht an den Anhängen sondern an der Betreffzeile.
Hab ein SO verfahren mit 5 Kindern, die all namentlich im Betreff aufgeführt werden.
Betreff die elterliche Sorge für Name, Geburtsdatum, Name Geburtsdatum etc.
Also muss hier gekappt werden.
Ggf. auch gleich noch mal bei den Mails prüfen
dankeschön

**Comment by j-dimension** [comment]
Hast Du noch einen Screenshot oder kannst das client.log per E-Mail senden?

**Comment by j-dimension** [comment]
```
2020-03-05 18:34:05,048 INFO  [org.jlawyer.bea.BeaWrapper] resolved
govello-1307448530392-000289545 to Amtsgericht Halle (Saale) (06112
Halle (Saale))
2020-03-05 18:36:31,317 INFO
[de.governikus.bea.kswtoolkit.socketactions.impl.DecryptSessionKey]
alias: c3faaa4652a68d04550aa89359598c25df6e0872
2020-03-05 18:36:39,199 ERROR
[com.jdimension.jlawyer.client.bea.SendBeaMessageAction] Could not save
message to archive file
java.io.FileNotFoundException:
/usr/local/j-lawyer-server/j-lawyer-data/archivefiles/81188d7bc0a8b3241886d5bf65a5a814/2020-03-05_18-36_145_20_XXXXXXXXXXXXXXXXXXXXX
geboren am XXXXXXXXXX  XXXXXX XXX XXXXXX  geboren  am XXXXXXXXXX XXXXX
XXXXXXXX XXXXXX  geboren am XXXXXXXXXX  XXXX XXXXXXXXX XXXXXX  geboren 
am XXXXXXXXXX_Müller  Otto (06110 Halle (Saale))--Amtsgericht Halle
(Saale) (06112 Halle (Saale)).bea (File name too long)
    at java.io.FileOutputStream.open0(Native Method)
```
