### ISSUE TITLE
Upgrade auf beA-Schnittstelle 2.3.5

### ISSUE THREAD

**Issue by j-dimension** [jlawyerorg/j-lawyer-org#676]
E-Mail BRAK 17.03.

**Comment by Maz111111** [comment]
wird von dieser Version die Export-Funktion endlich unterstützt?

**Comment by j-dimension** [comment]
> wird von dieser Version die Export-Funktion endlich unterstützt?

Nein, es handelt sich um ein reines Fehlerbeseitigungsrelease.
