### ISSUE TITLE
Sonderzeichen werden im Client nicht korrekt angezeigt

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-org#682]
Sonderzeichen (hier ungarische) lassen sich zwar aus der Sonderzeichentabelle aufrufen und mit copy paste einfügen in die Adressfelder, aber beim Wiederaufruf steht da nur ein Fragezeichen drinnen. Angesichts der zunehmenden Interantionalisierung der Mandantschaft sollten die Sonderzeichen korrekt widergegeben werden im Text.

**Comment by Mucki526** [comment]
konkret wird aber wohl nicht jedes Zeichen falsch ausgegeben, Das kleine Ö mit doppel akut gibt ein ?, das a mit akut wird richtig angezeigt...

**Comment by Mucki526** [comment]
Und interessanterweise ändert eine Änderung in den Textbausteinen auch das Sonderzeichen in der Anzeige der Beteiligten, der Namenseintrag aber nicht....

**Comment by Mucki526** [comment]
Ist offensichtlich aber nur eine Frage der Anzeige im J-Lawyer, denn der Name wird mit Sonderzeichen in den Text übernommen (Trotz Fragezeichen in der Anzeige)

**Comment by j-dimension** [comment]
Windows am Arbeitsplatz, Linux am Server, korrekt?

**Comment by Mucki526** [comment]
Ja, windoof 10 prof am Arbeitsplatz und dann der Microserver von Dir mit Linux... Wenn ich in meinem Leben mal am Tag 37 Stunden Zeit habe werde ich mir Linux aufsetzen... Aber wie gesagt, da fehlen mir im Moment 13 Stunden am Tag.... bleib gesund....

**Comment by j-dimension** [comment]
Danke, dann schließe ich das als Duplikat von #682.
