### ISSUE TITLE
[bea] Abbruch-Knopf bei Versand ausblenden

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-org#683]
Ich habe versucht eine BEA-Versendung abzubrechen. Abbruchtaste hat nicht reagiert - Stecker ziehen hat geholfen, ist aber unpraktisch...

**Comment by j-dimension** [comment]
Ja, das liegt schlicht daran, dass ich an der Stelle nichts abbrechen kann, weil es die Schnittstelle der BRAK nicht unterstützt. Einmal gestartet kann man sich nur gedulden und der Dinge harren, die da kommen mögen :-)

Ich kann aber den Abbruchknopf ausblenden.

**Comment by Mucki526** [comment]
Unfassbar - was hat dieses prähistorische Stück Beta-Software gekostet? 3,5 Mio € ?.... Das einzige was ich nicht verstehe - warum sind die auch noch stolz darauf. ... Ausblenden macht Sinn, aber dann bekommst Du mails, dass ein Abbruchknopf fehlt, Fehlermeldung wäre sinnvoller (Abbruch geht wegen fehlender Schnittstellenfunktione leider nicht - bitte Stecker ziehen...) Ich würde den Abbruchknopf sowieso eher wie folgt belegen: Bei jedem Drücken des Abbruchknopfes erhält die BRAK folgende BEA-Nachricht "Bitte vor dem 01.01.2021 eine funktonierende Schnittstellenfunktion für den Abbruch von  Nachrichtenversendungen ins BEA einbauen - ich hätte diese Nachricht an Sie gerne abgebrochen, aber leider fehlt da die Abbruchroutine... ;-) . Bleib gesund.....
