### ISSUE TITLE
Rechtemanagement /Freigeben und Sperren von Akten bei vers. Nutzern 

### ISSUE THREAD

**Issue by mal02LE** [jlawyerorg/j-lawyer-org#692]
Nicht alle Mitarbeiter oder Kanzleipartner sollen immer vollen Zugriff auf die gesamte Datenbank und alle Akten eines Falls haben. Insb. bei dem Einarbeiten von neuen Mitarbeitern o. sinnvolle einbinden von Praktikanten und Referendaren ist ein Rechtemanagement sinnvoll, dass die Akten und die darin vorhandenen Dokumente pro Nutzer freischaltet o. sperren kann.

**Comment by j-dimension** [comment]
@mal02LE das ist bereits umgesetzt und wird mit der kommenden 1.12 geliefert: https://github.com/jlawyerorg/j-lawyer-org/issues/59

Ich schliesse dieses Ticket hier als Duplikat.
