### ISSUE TITLE
[beA] Laaaanges Einfrieren von j-l nach Versand mit in-Akte-Speichern

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#694]
Ich habe eben  - was ich normalerweise nicht tue - per beA versandt mit Abspeichern der Nachricht. Nach dem Versenden (also Sendebalken war weg) war j-l für ca 10min einfroren! Nichts reagierte mehr und nach einem Fenstergröße-Verändern war der Fensterinhalt schwarz.

Erst nach 10 min ging es plötzlich weiter.

Vorher habe ich schon was versendet, ohne Speichern, da ging alles schnell weiter.

Logfile kommt per Mail.

**Comment by j-dimension** [comment]
Das kann ich nicht reproduzieren. Bitte in exakt dieser Konstellation nochmal ausführen und beobachten. 

Das gesendet client.log hat keine relevanten Informationen, und auch keine 10min-"Löcher" anhand der Zeistempel.

**Comment by j-dimension** [comment]
Hast Du noch ein paar Randbedingungen? Hast Du unmittelbar nach
Anmeldung verschickt, oder verging da schon etwas Zeit dazwischen?

Hingen große Dokumente dran?

Was hat der Fortschrittsbalken beim Versenden zuletzt gezeigt, bevor die
Anwendung "hing"?

**Comment by j-dimension** [comment]
Ggf. neu aufmachen.
