### ISSUE TITLE
bea-Nachricht in Akte - Vorschau defekt

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#695]
Wenn ich auf eine bea-Datei klicke, dann sehe ich weiterhin die Vorschau der letzten angeschauten (pdf-)Datei. Oben die Tabs sind erst die der alten Datei (Pfeile und Seitenzahlen). Erst wenn ich mit der Maus darüber fahre und klicke, kommen bruchstückenhaft die korrekten Tabs.

![image](https://user-images.githubusercontent.com/29924198/79371953-7c257a00-7f55-11ea-998c-c725860f8115.png)

Ich nutze die aktuelles Vorschau 1.12.0.2

**Comment by j-dimension** [comment]
Sieht aus als wäre beim Laden der Ansicht ein Fehler aufgetreten. Ich benötige client.log und ungefähren Zeitstempel.

**Comment by stm9x9** [comment]
ich kann es aktuell nicht reproduzieren

**Comment by j-dimension** [comment]
Dann machen wir es erstmal zu.
