### ISSUE TITLE
[adressen] Grussformel vorinstalliert und automatisiert

### ISSUE THREAD

**Issue by librelegal** [jlawyerorg/j-lawyer-org#702]
Beim Anlegen von Beteiligten sollten Vorschlagstexte für Grussformel zur Verfügung stehen, aber auch eine besondere Grussformel eingegeben werden können, die dann zum Vorschlagstext für den nächsten Beteiligten wird. So genutzt beihttp://www.a-jur.de/adressen.htm

Folgende Grussformel-Texte wünsche ich mir, jedenfalls bereits mit dem vollen Text in der Voransicht der Adresse:
Liebe Grüße
Lieber Gruß
Mit freundlichen Grüßen
Mit freundlichen kollegialen Grüßen
Mit liebem Gruß
Kind regards,
Yours sincerely, 

Im Englischen mit Komma am Ende, im Gegensatz zum Deutschen (https://bewerbung.com)/grussformel-fehler/)

Die entstehende Angabe wird für die Grussformel in Dokumentvorlagen genutzt, also bei Mandant ( {{MANDANT_NACHTEXT}}, Grusswort des Mandanten), bei Dritten {{DRITTE_NACHTEXT}}    Grusswort des Drittbeteiligten).

**Comment by j-dimension** [comment]
> aber auch eine besondere Grussformel eingegeben werden können, die dann zum Vorschlagstext für den nächsten Beteiligten wird

@librelegal kannst Du das näher beschreiben? Soll der manuell eingetragene Wert automatisch in die Einstellungen aufgenommen werden? Oder soll er als neue "Voreinstellung" bei Erstellung einer neuen Adresse werden?

**Comment by librelegal** [comment]
Der neu eingegebene Wert soll als Auswahl für künftige Grussformeln zur Verfügung stehen.
