### ISSUE TITLE
[beA] verändertes Absender-Aktenzeichen wird nicht übernommen

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#704]
Ich gehe in eine Akte, nehme ein oder mehrere Dokumente und erstelle damit eine bea-Nachricht.
ich wähle einen Empfänger.
das Absender-Aktenzeichen ist vorbelegt aus der Akte
Ich verändere das Absender-Aktenzeichen. und wähle eines für den Empfänger aus.
ich mache den Haken bei: in Akte speichern.

Absenden. (egal ob bei Justizbehörde was wähle oder nicht)

In der gesendeten und empfangenen und der gespeicherten Nachricht steht wieder das vorbelegte Absender-Aktenzeichen statt dem manuell veränderten.

Wenn ich nicht "in Akte speichern" mache, dann wird das veränderte Absender-Aktenzeichen übertragen.

Testsystem: 1.12.0.2

**Comment by j-dimension** [comment]
Ganz klar ein Fehler. Nur: ich hatte dieses Szenario bei meinen Tests gar nicht auf dem Schirm. Warum würde man soetwas tun wollen?

**Comment by stm9x9** [comment]
Bin ein Spielekind! :-D

Im Ernst: Manche ergänzen das eigene Akz je nach Verfahrensstand im Außenverkehr.

zb: MM-00017/19 wird im ER-Verfahren zu MM-00017/19 ER, in der Klage zu MM-00017/19 K
