### ISSUE TITLE
[bea] Druck des Journals ermöglichen

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-org#708]
Aus Beweisgründen bräuchte man eine lesbare Version über den Nachweis der Versendung einer Nachricht über BEA und den Beweis für den Zugang bei der Gegenseite, vor allem beim Gericht, welches man a.) ausdrucken kann und b.) bei der ein IT-Phobes Gericht im Idealfall im Klartext lesen kann Dass die Nachricht mit folgenden Anlagen am x.x.xxxx um x Uhr beim AG x eingegangen ist (Falls sowas geht)...

**Comment by stm9x9** [comment]
ideal würde es sein, sich an dem  zu orientieren, was bea-Web in der export.html  macht - es sieht jedenfalls "überzeugend" aus. Und das dann als pdf zum Speichern, verschicken oder drucken.

![image](https://user-images.githubusercontent.com/29924198/80107380-47c84400-857b-11ea-8ac3-eac19447fd69.png)

**Comment by Mucki526** [comment]
Sieht gut aus...

**Comment by j-dimension** [comment]
Siehe letzte Kommentare an #760

**Comment by j-dimension** [comment]
Duplikat von #592

**Comment by stm9x9** [comment]
ich bin mir gerade nicht ganz sicher, ob/wo/wie das schon umgesetzt ist. Oder ob das ganze in einem anderen Ticket weitergeht. Gebraucht war ja etwas, was man wenigstens als Beweis des ersten Anschein dem Gericht ausdrucken kann.

Jedenfalls ist jetzt noch was neues hinzugekommen, was wir Anwälte beachten müssen: Wir sind jetzt auch gehalten, die qeS von ausgegangenen Schriftsätzen zu überprüfen. http://ervjustiz.de/olg-braunschweig-wiedereinsetzung-nur-mit-vollstaendiger-postausgangskontrolle

Da würde es sich anbieten, so einen Test nach / beim Abspeichern der beA-Nachricht bzw. bei Erhalt des Zustellnachweises / processcard die Signaturen zu prüfen und das auch gleich in diesem Ausdruck mit anzuzeigen: wenn eine Signatur (inline oder extern) da ist und ob sie korrekt ist.
