### ISSUE TITLE
Platzhalter in Auto-Texten

### ISSUE THREAD

**Issue by AvoBayern** [jlawyerorg/j-lawyer-org#717]
Platzhalter können in Dokumentvorlagen verwendet werden. Es wäre sehr nützlich, Platzhalter auch in Auto-Texten verwenden zu können.

Beispiel: Die Dokumentvorlage „Brief an Gegner“ ist so mit Platzhaltern ausgestattet, dass automatisch die Anschriftsdaten, das Aktenzeichen, der Betreff und die Anrede des Gegners sowie die eigenen Akten- und Diktatzeichen und das aktuelle Datum eingefüllt werden. Es wäre schön, wenn man in eine solche Dokumentvorlage über die Auto-Text-Funktion Textbausteine einfügen könnte, die ihrerseits Platzhalter enthalten, bspw. „Es wird die anwaltliche Vertretung von {{DRITTE_TITEL}} {{DRITTE_VORNAME}} {{DRITTE_NAME}} {{DRITTE_STRASSE}} {{DRITTE_PLZ}}{{DRITTE_ORT}} angezeigt.“ 

siehe hierzu Forum-Thema „Platzhalter in Textbausteinen“

**Comment by j-dimension** [comment]
@AvoBayern herzlich willkommen und vielen Dank für das erste Ticket!

**Comment by iradraconis** [comment]
+ + +

**Comment by j-dimension** [comment]
Thema wird in #1319 weitergeführt.
