### ISSUE TITLE
Anhang an E-mail aus Vorlagenordner 

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-org#718]
Wenn ich in der Akte bin und dem Mandanten ein Formular schicken will, kann ich nicht auf den Vorlagenordner zugreifen und das Formular als Anhang nehmen, es geht nur Akte (Dokumente) und "normale" Ordner in windows.

**Comment by j-dimension** [comment]
Hänge ich an #712 mit an und schliesse dieses hier.
