### ISSUE TITLE
Ungelesen / gelesen Funktion für beA-Posteingang

### ISSUE THREAD

**Issue by Dickmaulruessler** [jlawyerorg/j-lawyer-org#719]
(ja, man sollte einen Posteingang im beA wohl sofort in eine Akte importieren...)

Falls man das aus irgendwelchen Gründen aber nicht tut, gibt es derzeit keine Möglichkeit, eine Nachricht wieder auf "ungelesen" zu setzen und das birgt die Gefahr, dass eine möglicherweise wichtige Nachricht in Vergessenheit geraten könnte. 

Eine entsprechende Funktion als Icon oder im Kontextmenü wäre gut. Danke!

**Comment by j-dimension** [comment]
Hallo @Dickmaulruessler , ja, das hätte ich auch gerne :-)

Es gab dazu bereits Ticket #428. Leider unterstützt die Schnittstelle der BRAK diese Funktionalität gar nicht.

Antwort der BRAK: "Es gibt derzeit keine Möglichkeit, über die KSW-Schnittstelle eine Nachricht als "(un-)gelesen" zu markieren."

**Comment by stm9x9** [comment]
Das bedeutet aber umgekehrt auch, daß die Sorge umsonst ist: wenn man eine beA-Nachricht in j-l anguckt, dann wird sie nämlich auch nicht auf gelesen gesetzt :-)

Im Ernst: Das Problem läßt sich umgehen, in dem man beim in Akte speichern die Option wahrnimmt, die Nachricht in einen anderen Ordner zu verschieben. Was dann nicht abgespeichert wurde, liegt immer präsent im Eingangspostfach.

**Comment by Dickmaulruessler** [comment]
bedeutet das auch dass es für jede Nachricht immer die Meldung "Aufbewahrungsfrist für Nachrichten läuft ab" gibt?
