### ISSUE TITLE
BUG - Beteiligtendaten, Wiedervorlagen und alles andere verschwindet bei Öffnung der nächsten Akte nach Archivierung

### ISSUE THREAD

**Issue by PBaumfalk** [jlawyerorg/j-lawyer-org#720]
Hallo,

folgendes Problem:

Wenn ich eine Akte archiviere wird die darauf folgende Akte dergestalt geändert, dass die Wiedervorlagen gelöscht werden, die Beteiligtendaten, Anwalt, Sachbearbeiter. 

Glücklicherweise konnte ich in den Akten, wo das jetzt passiert ist noch alles nachvollziehen, aber wir archivieren erstmal nichts mehr.

**Comment by PBaumfalk** [comment]
Außerdem ändert sich das "wegen" in das "wegen" der archivierten Akte.

**Comment by j-dimension** [comment]
Was bedeutet "darauf folgende Akte" genau?

**Comment by j-dimension** [comment]
das kriege ich nicht reproduziert. Kannst Du bitte

- genaue Abfolge der Schritte beschreiben? Archivierst Du eine Akte, 
speicherst, öffnest dann eine andere Akte, und dort fehlen Daten?
- client.log samt Zeitpunkt liefern
- server.log liefern

Passiert das konsistent immer, oder gibt es Randbedingungen?

**Comment by PBaumfalk** [comment]
Ich archiviere Akte 1 und öffne daraufhin eine weitere Akte. Die folgend geöffnete Alte ist dann verbuggt.

Mit freundlichen Grüßen / Kindly Regards

Patrick Baumfalk
Rechtsanwalt / Lawyer


Mobil:    +49 1525 53 04 194
E-Mail:   patrick.baumfalk@kanzlei-baumfalk.de


Baumfalk - Rechtsanwaltskanzlei
Hauptstr. 195
50169 Kerpen

Tel.: +49 2273 40 68 504
Fax: +49 2273 59 03 565

E-Mail: info@kanzlei-baumfalk.de
Web: www.kanzlei-baumfalk.de

Sent by Mobile

**Comment by PBaumfalk** [comment]
Ich schicke dir das alles gleich.

Mit freundlichen Grüßen / Kindly Regards

Patrick Baumfalk
Rechtsanwalt / Lawyer


Mobil:    +49 1525 53 04 194
E-Mail:   patrick.baumfalk@kanzlei-baumfalk.de


Baumfalk - Rechtsanwaltskanzlei
Hauptstr. 195
50169 Kerpen

Tel.: +49 2273 40 68 504
Fax: +49 2273 59 03 565

E-Mail: info@kanzlei-baumfalk.de
Web: www.kanzlei-baumfalk.de

Sent by Mobile

**Comment by PBaumfalk** [comment]
Also folgendes: Ich habe jetzt zwei Testakten angelegt und der Fehler passiert immer noch.

Testakte 1:

![image](https://user-images.githubusercontent.com/50404378/81146955-99a89b00-8f79-11ea-88ea-dff4ca582257.png)
![image](https://user-images.githubusercontent.com/50404378/81147000-a9c07a80-8f79-11ea-8abe-b38a591a2b48.png)

Testakte 2:
![image](https://user-images.githubusercontent.com/50404378/81147095-df656380-8f79-11ea-9006-4d92ea295708.png)
![image](https://user-images.githubusercontent.com/50404378/81147105-e55b4480-8f79-11ea-9545-f14b2fd38886.png)


- ich schließe alle Wiedervorlagen
- ich klicke auf archivieren
- speichern
- in der danach zu öffnenden Testakte verschwinden die Wiedervorlagen, Anwalt, Wegen wird geändert in das Wegen der vorigen Testakte. Hier bei Testakte 2.

Screenshot:
![image](https://user-images.githubusercontent.com/50404378/81147166-0754c700-8f7a-11ea-9b5f-f7a1c5ffacb1.png)
![image](https://user-images.githubusercontent.com/50404378/81147189-15a2e300-8f7a-11ea-82b0-a07ebd7636ad.png)

Das Client.log und die Server.log habe ich dir geschickt.

**Comment by PBaumfalk** [comment]
Sachgebiet ist dann auch weg. Das passiert nur, nach der Archivierung der Akte.

**Comment by j-dimension** [comment]
Von wo wird die Folgeakte geöffnet? Dem Desktop oder der Suche?

**Comment by PBaumfalk** [comment]
Der Fehler passiert sowohl bei Öffnung der Akte aus dem Desktop heraus, als auch aus der Suche heraus.
Habe ich gerade auch ausprobiert.

Mit freundlichen Grüßen / Kindly Regards

Patrick Baumfalk
Rechtsanwalt / Lawyer


Mobil:    +49 1525 53 04 194
E-Mail:   patrick.baumfalk@kanzlei-baumfalk.de


Baumfalk - Rechtsanwaltskanzlei
Hauptstr. 195
50169 Kerpen

Tel.: +49 2273 40 68 504
Fax: +49 2273 59 03 565

E-Mail: info@kanzlei-baumfalk.de
Web: www.kanzlei-baumfalk.de
