### ISSUE TITLE
Papierkorbfunktion

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-org#722]
Wenn man im J-Lawyer eine Datei löscht und es war ein Versehen fehlt mir eine Papierkorbfunktion wie z.B. in Windows wo man die Datei noch retten bzw. wiederherstellen kann.

- [x] entity enhancements
- [x] all finders to use deleted=0
- [x] change: removedocument to set deleted metadata and do an update instead of a delete
- [x] add: restoreFromBin - reset deleted metadata and create index request
- [x] add: removeFromBin - needs to delete from file system (see former removeDocument)
- [x] check any occurence of ArchiveFileDocumentsBean
- [x] adjust REST API
- [x] UI in case
- [x] UI for admins (managed deleted docs across all cases)
- [x] rephrase case history entries ("gelöscht" - "in den Papierkorb verschoben")
- [x] setting for retention time
- [x] auto deletion based on retention time
- [x] name conflict - messages need to indicate that conflicts may occur with documents in bin
- [x] special cases: deletion of folder that seems empty but has documents in bin, ...?
- [x] where is getDocumentsUnrestricted used? --> proper parameter value for "deleted"
- [x] upon moving to bin, need to clear folder; restore will only take place into the root folder
- [x] Ordner löschen überarbeiten, ggf. neue Transaktion für das Löschen der Dokumente bei Ordner löschen

**Comment by Mucki526** [comment]
Um Speicherplatz zu sparen (falls man das in der heutigen Zeit noch muss könnte die Lebensdauer des Inhalt des Papierkorbs begrenzbar sein (z.B. 1 Woche oder 1 Monat).

**Comment by PBaumfalk** [comment]
Oh ja!!!

Mit freundlichen Grüßen / Kindly Regards

Patrick Baumfalk
Rechtsanwalt / Lawyer


Mobil:    +49 1525 53 04 194
E-Mail:   patrick.baumfalk@kanzlei-baumfalk.de


Baumfalk - Rechtsanwaltskanzlei
Hauptstr. 195
50169 Kerpen

Tel.: +49 2273 40 68 504
Fax: +49 2273 59 03 565

E-Mail: info@kanzlei-baumfalk.de
Web: www.kanzlei-baumfalk.de

Sent by Mobile

**Comment by Maz111111** [comment]
Von mir auch ein dickes 
JA!
Ist mir in der bisherigen Nutzungszeit einfach schon zu oft passiert - also kein versehentliches Löschen, sondern eher ein zu schnelles / unbedachtes Löschen. 
Da beißt man in die Tischkante...

**Comment by j-dimension** [comment]
Auch für den Scaneingang gefordert.

**Comment by Maz111111** [comment]
Ich bitte darum, diese Funktion vorzuziehen.

Es gibt jetzt die Möglichkeit über die Markierung des Kästchens mehrere Dokumente zu markieren.

Das Kästchen wird aber auch automatisch aktiviert, wenn man nur irgendwo in die Zeile des jeweiligen Dokumentes klickt.

ich wähle ein Dokument aus und sehe es mir in der Vorschau an oder ordne es einem Ordner zu.

Ich scrolle herunter und will zwei Dokumente zeitgleich löschen. Dementsprechend markiere ich beide Dokumente direkt in dem Kästchen. Das vorher bereits markierte Dokument ist durch das Scrollen nicht mehr im Bild - aber gleichwohl immer noch markiert.

Ich lösche...Keine Chance, das versehentlich gelöschte Dokument wieder zu bekommen. Das Original ist vor Wochen geschreddert und eine Sicherheitsfunktion (Papierkorb oder Schritt zurück) gibt es (noch) nicht.

Bisher konnte ich die Angelegenheit immer noch dadurch gerade biegen, dass ich in der E-Akte irgendwo noch eine Mail oder eine BeA Nachricht hatte, an der dieses Dok hing und so konnte ich das Dok umständlich wieder herstellen (bei Mail ist es meist verschlüsselt und muss xMal neu gespeichert werden, bis es in unverschlüsselter Form wieder in die Akte genommen werden kann). Das Datum geht dann meist verloren, weil ich selber nicht mehr weiß welche Datumsangaben in der Akte für dieses Dok hinterlegt waren.

Exakt so ist mir das jetzt bestimmt schon 10 Mal passiert.

Da nutzt auch kein daran denken - wenn man das Dok nicht mehr sieht, denkt man auch nicht mehr daran.

Wenn man es vor der nächsten Datensicherung merkt, kann man es noch unklompliziert aus dem Export retten (vorausgesetzt man hat ihn eingeschaltet)

Darum bitte vorziehen - das ist m.E. echt wichtig.

Viele Grüße
Martin

**Comment by j-dimension** [comment]
Eine sehr schnelle Lösung könnte eine Warnung mit Auflistung der zu löschenden Dokumente sein.

**Comment by Maz111111** [comment]
Das wäre sicher erst mal besser als nichts - (ein Papierkorb muss m.E. in jedem Fall sein)

Danke für die schnelle Antwort

**Comment by Dickmaulruessler** [comment]
Nur eine allgemeine Anmerkung: Ich glaube, wir können unserem Chef Jens so sehr vertrauen, dass er anhand einer Problemschilderung die Priorität selbst einstufen kann. Wir solltem ihm da bitte keine Vorgaben machen oder Wünsche äußern, etwas vorzuziehen. Und: Schon gar nicht mehrfach. 

Auch Labels wie "enhancement" möchte Jens auch glaube ich ausschließlich alleine setzen dürfen. 
Oder liege ich da falsch @j-dimension ?

**Comment by j-dimension** [comment]
@Dickmaulruessler die Label sind tatsächlich unter meiner Kontrolle, Anwender die nicht explizit die Berechtigung haben (wie bspw. @librelegal), können diese nicht verändern. 

Viele der Anwenderwünsche sind nicht mal eben an einem Abend umgesetzt, so auch die Papierkorbfunktion. Ich verstehe das Risiko, das @Maz111111 hier beschreibt und habe eine schnelle und pragmatische Lösung angeboten, ohne die umfassende Lösung abzulehnen. Auf eine schnelle Lieferung hat man auch bei Open Source keinen Anspruch, es sei denn es ist ein Auftrag.

**Comment by j-dimension** [comment]
Löschen-Rückfrage listet nun die Dokumente auf: 

![grafik](https://user-images.githubusercontent.com/3729754/105764874-d9744000-5f57-11eb-808d-224b319f7ffc.png)

**Comment by j-dimension** [comment]
Beispiel mit einem selektiertem Dokument im sichtbaren Bereich und weiteren Dokumenten außerhalb des sichtbaren Srollbereiches:

![grafik](https://user-images.githubusercontent.com/3729754/105765048-16d8cd80-5f58-11eb-994a-7a6788cdcb5f.png)

**Comment by stm9x9** [comment]
> Ich verstehe das Risiko, das @Maz111111 hier beschreibt und habe eine schnelle und pragmatische Lösung angeboten, ohne die umfassende Lösung abzulehnen.

Danke dafür. Damit diese schnelle Umsetzung aber auch genutzt werden kann: wann kommt denn eine neue Version mit dieser Änderung? :-D

**Comment by j-dimension** [comment]
> wann kommt denn eine neue Version mit dieser Änderung?

Wenn ich neben dem Unterrichten zweier Drittklässler und einem 9-to-5-Job, der sich auf 12-21 Uhr verlagert, gefolgt von j-lawyer - Community-Support noch dazu komme die verbleibenden 34 Tickets der 1.14 abzuarbeiten.

Im Ernst, ich kann dazu nichts Verlässliches sagen.

**Comment by Dickmaulruessler** [comment]
Lieber Jens, 

ein ganz herzliches DANKESCHÖN an dich!
Es ist wirklich toll: 
Du bist JEDEN Tag an unserem Projekt dran, schreibst hier etwas und verbesserst das Programm JEDEN Tag!

An die Ungeduldigen hier: Auch wenn das die private und berufliche Belastung von Jens überhaupt nicht verbessert, aber werft vielleicht dennoch gerne auch einmal einen Blick [hierauf](https://www.amazon.de/registry/wishlist/3NQIW4354H68X). 

:-)

**Comment by j-dimension** [comment]
Video zum Wochenausklang:


https://user-images.githubusercontent.com/3729754/107093599-cee26200-6805-11eb-84e8-d2bc22d58848.mp4

**Comment by Dickmaulruessler** [comment]
Cool!

**Comment by Maz111111** [comment]
html,body{background-color:#fff;color:#333;line-height:1.4;font-family:sans-serif,Arial,Verdana,Trebuchet MS;}Dude, you rock!

Jens Kutschke schrieb am 05.02.2021 22:59 (GMT +01:00):

Video zum Wochenausklang:
https://user-images.githubusercontent.com/3729754/107093599-cee26200-6805-11eb-84e8-d2bc22d58848.mp4

**Comment by stm9x9** [comment]
Ich spiel doch so gerne den advocatus diaboli :-D

Die wiederhergestellten Dateien haben ja ihr Ordner-Attribut verloren!!!!!1einself

**Comment by j-dimension** [comment]
> Die wiederhergestellten Dateien haben ja ihr Ordner-Attribut verloren!!!!!1einself

Muss so, sonst gibt es zu viele Sonderfälle, die alle separat ausimplementiert werden müssten. Bspw. Löschen von leeren Ordnern würde fehlschlagen, wenn es noch Dokumente gibt, die im Papierkorb liegen aber zu diesem Ordner gehörten.

**Comment by stm9x9** [comment]
hm ... muß das passieren? Kann der leere Ordner nicht gelöscht werden und wenn eine Datei aus diesem Ordner wiederhergestellt wird, dann wird der Ordner einfach neu erstellt?

**Comment by j-dimension** [comment]
> Kann der leere Ordner nicht gelöscht werden und wenn eine Datei aus diesem Ordner wiederhergestellt wird, dann wird der Ordner einfach neu erstellt?

Nein, da der Ordner weitere Attribute hat. Ich müsste dann alle Ordnerattribute noch separat speichern, wenn er gelöscht wird. Oder einen weiteren Papierkorb für Ordner erstellen. 
Mach ich aber nicht. Aufwand/Nutzen.
