### ISSUE TITLE
[kalender] Warnhinweis auf WV beim Archivieren

### ISSUE THREAD

**Issue by Maz111111** [jlawyerorg/j-lawyer-org#723]
Beim Archivieren einer Akte kommt ein Warnhinweis bei noch offenen WVs.
Das ist auch gut so!
Manchmal führt aber gerade eine WV zum Archivieren (Bsp.: WV: Hat Mandant Unterlagen abgeholt? - JA! -> es wird archiviert). Das habe ich sogar recht oft.
Könnte man den Warndialog so anpassen:
"Noch offene WV / Frist (en) für xx.xx.xxxx! Trotzdem archivieren? (Bei "ja" werden alle WVs und Frist(en) auf erledigt gesetzt!"
Mal wieder nur Kosmetik und für den Workflow - aber vielleicht ja schnell umzusetzen.
Grüße
Martin

**Comment by Mucki526** [comment]
Also wenn ich archiviere mache ich eine letzte Widervorlage "Ablage" und erledige diese. Dann kann ich an der WV-Historie nachvollziehen, wann ich die Akte archiviert habe. Manchmal muss man das Fass nochmal aufmachen und neu archivieren. Ist dann dokumentiert.  Der jetzige Warnhinweis reicht doch eigentlich völlig. Ansonsten "putzt" der "eilige eifrige Archivierer" mit einem Knopfdruck evt. eine wichtige evt. vergessene WV weg.

**Comment by stm9x9** [comment]
Nehmen wir mal die "WV: Hat Mandant Unterlagen abgeholt?"

Was können denn dann da zb noch an späteren Fristen eingetragen sein?

**Comment by Maz111111** [comment]
Keine späteren, sondern die WV an diesem Tag.
Diese müsste ich erst als erledigt markieren - dann kann ich archivieren. I.d.R. ist es aber so, dass ich die Akte über den Desktop öffne und dann in der Papierakte nach meinem Aushändigungsbeleg suche. Sobald ich den gefunden habe, will ich archivieren und klicke dies sofort an. Das Datum der Archivierung vermerke ich händisch auf dem letzten Blatt der Akte.
Außerdem kann es auch sein, dass der Mandant sein Zeug vor der WV abholt und ich übereifrig die Sache dann gleich klar machen will. Dann gibt es auch eine spätere WV.
Aber das macht jetzt auch schon wieder viel zu viel Aufwand - wenn es auf so viel Gegenwind stößt, dann sollte es am besten so bleiben, wie es ist - es funktioniert ja.

**Comment by j-dimension** [comment]
Man könnte bei Archivierung, wenn noch WV offen sind, einfach einen Dialog anzeigen mit den noch offenen WV und deren Fälligkeit, und zwei Buttons zum Abbrechen oder "auf erledigt setzen und archivieren".

Was meint Ihr?

**Comment by stm9x9** [comment]
Klingt gut

**Comment by Mucki526** [comment]
Das Datum der Archivierung vermerke ich als letzte Widervorlage "Ablage". Manchmal muss ich den "Sack" nochmals aufschnüren (VKH-Rückfrage Gericht, späteres Anschreiben in der Sache nach Ablage, Dann wird die Akte geöffnet, der neue Vorgang hinzugefügt und erneut abgelegt (erneut abgelegt)..... Ich schaue immer rein, ob noch was offen ist. Einfach alles auf "erledigt" setzen kann auch heißen - alle Warnlampen auf grün schalten (wird schon gut gehen - famous last words).

**Comment by Mucki526** [comment]
o.k. wenn die offenen noch angezeigt werden, dann geht das, dann kann man entscheiden abzubrechen und erst mal die noch offenen WV zu bearbeiten, soweit erforderlich...
