### ISSUE TITLE
Client-Version schon im Logindialog anzeigen

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#724]
Es wäre schön, wenn man die Client-Version schon beim Startbildschirm und Login-Fenster sehen würde. 

![image](https://user-images.githubusercontent.com/29924198/81196192-06925400-8fbf-11ea-84fd-4dc072ad0e3f.png)
![image](https://user-images.githubusercontent.com/29924198/81196294-2590e600-8fbf-11ea-8fed-1509cba759c3.png)

So oben rechts, wie nach dem Login

![image](https://user-images.githubusercontent.com/29924198/81196336-33df0200-8fbf-11ea-85d7-19f8bd14bbe3.png)

**Comment by j-dimension** [comment]
Das geht leider nicht - in dem ersten Screen werden im Hintergrund die Bibliotheken geladen. Der Client ist ja mittlerweile auch ganz schön groß. Innerhalb dieses Prozesses habe ich keinen Einfluss auf das angezeigte im Sinne einer Logik - ich kann nur angeben dass eine Grafik angezeigt werden soll, oder gar nichts. Habe mich für die Grafik entschieden :-)  - sieht der Nutzer zumindest dass etwas passiert.

Gut, ich könnte jetzt mit jedem Release eine neue Grafik generieren, da ist mir aber Kosten / Nutzen-Relation zu gering.

**Comment by j-dimension** [comment]
Loginfenster würde gehen. Aber man erlaube mir die Frage: wozu?

**Comment by stm9x9** [comment]
> Aber man erlaube mir die Frage: wozu?

gerne. Ich brauche mich dann nicht erst anzumelden, um zu sehen, daß ich auf dem Rechner den Client doch noch hätte vorher updaten müssen :-)

**Comment by fortrieb** [comment]
Ich wuerde das Ticket uebernehmen, falls hier noch keiner dran arbeitet.

**Comment by j-dimension** [comment]
@fortrieb das wäre Klasse! Die Versioninformation des Clients (der Server ist separat verioniert, soll hier nicht angezeigt werden) findet man in https://github.com/jlawyerorg/j-lawyer-org/blob/master/j-lawyer-client/src/com/jdimension/jlawyer/client/utils/VersionUtils.java
Es gibt dort eine Methode getFullClientVersion.

Ich würde die Version dann einfach im Fenstertitel mit anzeigen, ähnlich wie es im Client aktuell gemacht ist. Aber andere Ideen sind natürlich herzlich willkommen.
