### ISSUE TITLE
Logo in Kanzleiprofil laden

### ISSUE THREAD

**Issue by PBaumfalk** [jlawyerorg/j-lawyer-org#726]
Es wäre cool, wenn man eine Datei in das Kanzleiprofil hochladen könnte und diese dann als Platzhalter verwendet werden kann.

**Comment by j-dimension** [comment]
Wäre das für das Kanzleilogo? Wäre das dann nicht besser im Kanzleiprofil aufgehoben?

**Comment by PBaumfalk** [comment]
Edit.

**Comment by PBaumfalk** [comment]
> Wäre das für das Kanzleilogo? Wäre das dann nicht besser im Kanzleiprofil aufgehoben?

Ja, das ins Kanzleiprofil.
Alternative für Templates: Kanzleiname noch als gesonderten Platzhalter.

**Comment by j-dimension** [comment]
Ich schließe hier mit Verweis auf #1552
