### ISSUE TITLE
Upgrade to FlatLaf 0.44 or later

### ISSUE THREAD

**Issue by j-dimension** [jlawyerorg/j-lawyer-org#732]
https://github.com/JFormDesigner/FlatLaf/releases/tag/0.34

Drop shadows and reworked menu items for even more awesomeness :-)

**Comment by j-dimension** [comment]
Requires setting some properties to enable those features.

**Comment by librelegal** [comment]
Die Bearbeitung dieses issues erledigt vielleicht zugleich #620

**Comment by j-dimension** [comment]
@librelegal nein, leider nicht.

**Comment by j-dimension** [comment]
Error / Warning outline für Komponenten in 0.35: https://github.com/JFormDesigner/FlatLaf/releases/tag/0.35

**Comment by j-dimension** [comment]
Seems to depend on https://github.com/JFormDesigner/FlatLaf/issues/219
