### ISSUE TITLE
Sortierung der Beteiligten konfigurierbar machen 

### ISSUE THREAD

**Issue by RobertT01** [jlawyerorg/j-lawyer-org#740]
Bei der Clientversion 1.12.07 und Servervesion 1.12.09 werden bei den Beteiligten immer erst die Dritten dann die Gegner und dann der/die Mandanten angezeigt. Dies ist also genau umgekehrt zu allen vorhergehenden Versionen. Bitte wieder umkehren

**Comment by j-dimension** [comment]
Das ist nicht ganz so einfach wie es scheint. Bis dato gab es nur diese drei Beteiligtentypen. Jetzt kann man sich eigene konfigurieren - Gericht, Mieter, wasauchimmer. Da ist es nicht trivial eine "bestmöglich bedienbare" Reihenfolge zu definieren. 

Lässt sich praktisch nur lösen, wenn an den Beteiligtentypen auch Reihenfolge / Sortierkriterien konfiguriert werden könnten.

**Comment by Maz111111** [comment]
Ich häng mich mal dran.
Eine Reihenfolge zu konfigurieren wäre super! Dies könnte zum Beispiel im Dialog, in welchem man die Beteiligten erstellen kann, erfolgen.
Die Reihenfolge sollte dann konsequent auch beim Dialog zum Hinzufügen der Beteiligten in einer Akte in dem Auswahldialog (also dieses Aufklappfenster, in welchem man aussucht, als was man die Person oder das Gericht hinzufügt) eingehalten werden.

**Comment by j-dimension** [comment]
> Dies könnte zum Beispiel im Dialog, in welchem man die Beteiligten erstellen kann, erfolgen.

Du meinst wo man die Beteiligten**typen** (=Einstellungsdialog) erstellen kann, korrekt?

**Comment by RobertT01** [comment]
Ja, es sind die "Beteiligtentypen", d.h. dort wo ich derzeit auswähle ob
die natürliche oder juristische Person,

-     Mandant
-    Gegner oder
-     Dritter ist.

Vielleicht wäre es möglich, dass man die Beteiligten frei verschiebbar
macht. Alternativ müsste das System automatisch erkennen, wie viel
Personen in der Akte vorhanden sind und ihnen dann einen entsprechende
Positionen zuweist, die man dann händisch ändern kann. Also Mdt1 bekommt
die Nummer 1, Mdt 2 die Nummer 2, Gegner 1 die Nummer 3 usw.

Was jetzt richtig unschön ist, dass das Aktendatenblatt mit Dritten
anfängt, dann die Gegner kommen und dann erst der Mandant. Letztere
Daten braucht man beim Blick in die Akte jedoch meines Erachtens als
Erstes.

Am 13.05.2020 um 19:45 schrieb Jens Kutschke:

**Comment by Maz111111** [comment]
> Du meinst wo man die Beteiligtentypen (=Einstellungsdialog) erstellen kann, korrekt?

Ich meine: Einstellungen -> Modul 'Adressen' -> Beteiligtentypen

Wenn man dort solche Auf- und Abwärtspfeile hätte, wie bei den Anhängen im beA könnte man dort die Reihenfolge einstellen, in der die Beteiligten dann auch in der Akte unter dem Reiter "Beteiligte" erscheinen und in dem Aufklappfenster, wenn man den Beteiligten einer Akte zuordnet.

> Vielleicht wäre es möglich, dass man die Beteiligten frei verschiebbar
macht.

Wäre schon geil - aber irgendwie auch spielig im gesamten Design der KSW. Würde irgendwie nicht zum bisherigen sehr nüchternen Stil passen. Ist aber Geschmacksache...

> Alternativ müsste das System automatisch erkennen, wie viel
Personen in der Akte vorhanden sind und ihnen dann einen entsprechende
Positionen zuweist, die man dann händisch ändern kann. Also Mdt1 bekommt
die Nummer 1, Mdt 2 die Nummer 2, Gegner 1 die Nummer 3 usw.

Wenn das ginge, würde es helfen - allerdings würde das ja zwingend ohnehin sowieso so zu programmieren sein. Interessanter wäre es, ob man die von der KSW vorgegebene Reihenfolge eigenhändig wieder ändern kann und so seinen Lieblingsmandanten auf Nummer 1 bekommt. Die Sozialrechtler hätten bestimmt den Vertreter der gesamten Bedarfsgemeinschaft gern immer ganz oben an erster Stelle und dann erst den Rest der BG.

**Comment by RA-crm** [comment]
Ich fände es super, wenn man in drei Gruppen teilt, die in festen Blöcken abgebiltet werden, innerhalb derer man ggf. scrollen kann, wobei die Zuordnung der einzelnen Beteiligtentypen zu den Gruppen bei der Aktenanlage konfigurierbar ist. 
Mandant (=eigentlicher Mandant, Ansprechpartner, Vertreter)
Gegenseite (= Gegner, Ansprechpartner, Vertreter, gegnerischer Rechtsanwalt)
Dritte (=Gericht, Versicherung, Sachverständige, Behörden, Zeugen. Gerichtsvollzieher)

**Comment by stm9x9** [comment]
> Ich fände es super, wenn man in drei Gruppen teilt, die in festen Blöcken abgebiltet werden, innerhalb derer man ggf. scrollen kann,

oder auf- und zuklappen

> wobei die Zuordnung der einzelnen Beteiligtentypen zu den Gruppen bei der Aktenanlage konfigurierbar ist.

das hört sich eher nach einer kanzleiweiten Konfiguration an, oder?

**Comment by j-dimension** [comment]
betrifft auch Beteiligtenauswahl im "Beteiligte hinzufügen"-Dialog

**Comment by j-dimension** [comment]
Ich habe nun die Lösung mit den Auf- / Ab-Pfeilen umgesetzt. Sie wirkt sich einmal quer über die Anwendung aus: Akte, Handaktenbogen, ...

![grafik](https://user-images.githubusercontent.com/3729754/211106612-998d80b6-4a2d-4d43-8a4e-ece6daae193d.png)

**Comment by Dickmaulruessler** [comment]
Super!

**Comment by RobertT01** [comment]
Vielen Dank. Machst Du dafür ein Update?Von meinem/meiner Galaxy gesendet
-------- Ursprüngliche Nachricht --------Von: Jens Kutschke ***@***.***> Datum: 06.01.23  22:58  (GMT+01:00) An: jlawyerorg/j-lawyer-org ***@***.***> Cc: RA Robert Thees ***@***.***>, Author ***@***.***> Betreff: Re: [jlawyerorg/j-lawyer-org] Sortierung der Beteiligten
  konfigurierbar machen  (#740) 
Closed #740 as completed via fe2ad65.

**Comment by j-dimension** [comment]
Kommt mit dem nächsten regulären Update (2.3). Das Timing ist abhängig von der BRAK. Habe bereits eine neue bea-Schnittstelle implementiert und muss nun warten bis die in der produktiven beA-Umgebung verfügbar ist.
