### ISSUE TITLE
[beA] Versand löscht Dateien auf Festplatte!

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#741]
folgendes Szenario:

einloggen in beA
eine neue Nachricht in der beA-Ansicht erstellen
eine lokale Datei per drag&drop in die Anhänge ziehen (da steht schon "Verschieben" am Cursor)
bea-Nachricht versenden
j-l schließen.

In dem Moment wird die lokale Datei lokal gelöscht. Nicht nach dem Senden, erst beim Schließen von j-l.

Server: Linux
Client: Windows 64bit

**Comment by j-dimension** [comment]
Puh...
