### ISSUE TITLE
[bea] Versand-Fehler bei "&" Zeichen (z.B. GmbH & Co. KG)

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-org#743]
![Veehler](https://user-images.githubusercontent.com/37142896/82076319-f9234b00-96dd-11ea-8fc5-b9ec0f84c577.jpg)

Fehler bei Versendung eines PDF an einen Kollegen... Fehler tritt vermutlich beim Abspeichern auf...

**Comment by Mucki526** [comment]
Fehler wird durch das &-Zeichen erzeugt im Aktennamen / Beteiligtennamen GmbH & Co.KG.....

**Comment by j-dimension** [comment]
Das bekomme ich nicht reproduziert, ich muss genau wissen ob 

- ein Dokumentname
- der Name des Empfängers

ein & enthielt, und ob eine Vorlage für den Nachrichtentext verwendet wurde, mit welchem Namen.

Am allerliebsten wäre mir ein client.log, kurz nachdem das aufgetreten ist.

**Comment by j-dimension** [comment]
Ticket gern wieder aufmachen, wenn noch relevant.

**Comment by j-dimension** [comment]
Anderer Anwender hat berichtet. Ursächlich ist das & in einem Nachrichtenbetreff. Bug wird wieder aufgemacht.

**Comment by j-dimension** [comment]
Auf Ebene beA Wrapper umsetzen?

**Comment by j-dimension** [comment]
Behoben mit beA Wrapper #34
