### ISSUE TITLE
Drebis findet die Aktenzeichen beim Speichern und bestätigen nicht

### ISSUE THREAD

**Issue by PBaumfalk** [jlawyerorg/j-lawyer-org#747]
Aktenzeichen hat Anwalts- und Gruppenkürzel. Das Aktenzeichen wird von Drebis nicht gefunden...

**Comment by j-dimension** [comment]
Da brauch ich mehr Info. Du hast eine eingehende Drebis-Nachricht. Hast Du den Drebis-Vorgang gestartet BEVOR Du das erweiterte Aktenzeichen aktiviert hast?

**Comment by PBaumfalk** [comment]
Die Akte wurde vor Einführung der erweiterten Aktenzeichen angelegt. Das Gruppen- und Anwaltskürzel nachträglich angehangen. Nunmehr findet das DREBIS-Modul das ursprüngliche Aktenzeichen nicht mehr.

**Comment by j-dimension** [comment]
Dann hat sich das Aktenzeichen ja geändert. 

1. Vorgang wird begonnen mit 0815/20
2. Aktenzeichen ändert sich auf 0815/20-PB
3. Drebis-Antwort trifft ein, bezieht sich auf 0815/20
--> Zuordnung nicht möglich

Wird der Vorgang bereits mit 0815/20-PB gestartet, so kann auch eine Zuordnung stattfinden. 

Wenn ein Aktenzeichenwechsel mitten in einem Vorgang stattfindet, wirst Du die Antworten aus Drebis manuell in die Akte transferieren müssen.

**Comment by PBaumfalk** [comment]
Ok. Thread closed.

Mit freundlichen Grüßen / Kindly Regards

Patrick Baumfalk
Rechtsanwalt / Lawyer


Mobil:    +49 1525 53 04 194
E-Mail:   patrick.baumfalk@kanzlei-baumfalk.de


Baumfalk - Rechtsanwaltskanzlei
Hauptstr. 195
50169 Kerpen

Tel.: +49 2273 40 68 504
Fax: +49 2273 59 03 565

E-Mail: info@kanzlei-baumfalk.de
Web: www.kanzlei-baumfalk.de

**Comment by PBaumfalk** [comment]
Muss nochmal geöffnet werden. Das Aden findet das Aktenzeichen nicht bei einer Akte, die ich nach der Einführung der Gruppen- und Anwaltskürzel angelegt habe.

**Comment by j-dimension** [comment]
@PBaumfalk welches Aktenzeichen bekommst Du in der Rückmeldung von Drebis (unter "Nachrichtendetails")?

**Comment by j-dimension** [comment]
Okay, habe eine Idee was passieren könnte, brauche aber mal ein Beispiel-Aktenzeichen in Deiner aktuellen Konfiguration @PBaumfalk . 

Danke!

**Comment by PBaumfalk** [comment]
![image](https://user-images.githubusercontent.com/50404378/82416075-c4b2e480-9a79-11ea-9e65-aca7a989d8c2.png)

**Comment by j-dimension** [comment]
@PBaumfalk ich plane zwar eine "kleine" 1.13, aber u.U. ist das Drebis-Problem dringender für Dich. Benötigst Du eine Vorab-/Zwischenversion?

**Comment by PBaumfalk** [comment]
Wir können damit noch warten. Danke!

Mit freundlichen Grüßen / Kindly Regards

Patrick Baumfalk
Rechtsanwalt / Lawyer


Mobil:    +49 1525 53 04 194
E-Mail:   patrick.baumfalk@kanzlei-baumfalk.de


Baumfalk - Rechtsanwaltskanzlei
Hauptstr. 195
50169 Kerpen

Tel.: +49 2273 40 68 504
Fax: +49 2273 59 03 565

E-Mail: info@kanzlei-baumfalk.de
Web: www.kanzlei-baumfalk.de
