### ISSUE TITLE
Vorlagen Anschreiben BEA

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-org#748]
Die Vorlagen für das BEA sollten nicht die gleichen wie für e-mail sein... Ich habe gerade versehentlich mit dem Anschreiben für meinen Mandante einen Schriftsatz ans Gericht per BEA verschickt. Nicht schlimm, aber blöd....

**Comment by j-dimension** [comment]
Das verstehe ich nicht. Du kannst die doch einfach eindeutig benennen. Oder einen eigenen Beteiligtentyp "Gericht" anlegen, dann hat der andere Platzhalter. 

Und würde das nicht auffallen, wenn man vor dem Absenden nochmal über den Text liest?

**Comment by Maz111111** [comment]
eine strikte Trennung beA und Mail Vorlagen fänd ich auch nicht schlecht.

Aktuell habe ich unterschiedliche Vorlagen für RA beA und RA Mail, da ich bei Mail das gegnerische AZ per Platzhalter in den Betreff packe und im beA genau dieses nicht nötig und sogar überflüssig wäre, da das gegnerische AZ dort ja direkt ausgewählt werden kann.

Dann muss ich schon immer aufpassen, welche Vorlage ich aussuche. Kein Beinbruch und geht schon...aber ist keine schlechte Idee...

**Comment by j-dimension** [comment]
Ich möchte ganz offen sein: Es ist unwahrscheinlich, dass ich daran arbeite - aus dem einfachen Grund, dass ich - das möge mein Unvermögen sein :-) - den Nutzen als nicht so hoch bewerte und weiterhin die BRAK in der Planung hat, die Eingabemöglichkeit für Nachrichtentext komplett zu entfernen. Das beA würde somit zum reinen "Dokumentübermittler", und jede Minute in eine Typisierung der Nachrichtenvorlagen investierte Zeit wäre eine Minute für die Tonne.

**Comment by Mucki526** [comment]
Also wenn die Brak die Eingabemöglichkeit für Nachrichtentexte komplett entfernt, schickt man eh nur noch Schreiben und Anlagen. Dann ist´s eh wurscht und Du hast Recht. Da gibt es wichtigeres. Das mit dem nochmal drüberlesen - da hast Du auch Recht, aber wenn´s schnell gehen soll, das Telefon klingelt, Ruckzuck ist danebengeklickt und abgeschickt und ein Fehler passiert. Menschen machen halt Fehler, gerüchteweise sollen auch manche Anwälte zu der Spezies gehören... :-)
