### ISSUE TITLE
Makro der Beteiligtenlisten

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-org#751]
Ich hatte mir das Makro für Libreoffice mit den Kürzellisten der (bisherigen) Beteiligten angelegt. Wurde hier mal diskutiert. Schade ist, dass die neuen Beteiligten nicht automatisch da übernommen werden. Wäre vielleicht eine Idee, wenn die neuen Beteiligten automatisch in die Makroliste geschrieben werden. Die ist hilfreich bei der Erstellung neuer Vorlagen.

**Comment by j-dimension** [comment]
Lt. @PBaumfalk ist nun mit LibreOffice 6 auch auf dem macOS die Installation einer Extension möglich, was für den Anwender sehr viel einfach ist. Habe daher dieses Ticket kommentiert und schliesse dieses hier.
