### ISSUE TITLE
Client update

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-org#752]
Ich bin gerade dabei, auf meinen Rechnern (Laptops, PC) die Clients up to daten. Könnten die Clients nicht beim Einloggen automatisch die vorhandene Serverversion prüfen und sich dann automatisch mit einem freundlichen Hinweis an den geneigten User auf die aktuelle Version bringen? Mit der alten Version der Clients sollte man eh nicht mehr starten.

**Comment by j-dimension** [comment]
Duplikat von #133
