### ISSUE TITLE
Replikation 2. Box - Warnmail

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-org#753]
Wenn eine erfolgreiche Datensicherung gemacht wurde, bekomme ich eine e-mail. Wenn die Replikation nicht funktioniert, merkt man das nur, wenn man sich an der Replikationsbox nicht anmelden kann bzw. wenn es klappt, aber dann die Gesamtakten /Dateienzahl nicht stimmt. Habe beim Update gemerkt gestern, dass die Repibox "hing".
Wenn die Replikation nicht stattfindet, wäre eine Warnmail schick. könnte ja vom Hauptgerät kommen, wenn die Replikationsbox die falschen / keine Werte zurückmeldet nach der Replikation oder die Replikation garnicht startet.

**Comment by j-dimension** [comment]
Der Code der j-lawyer.BOX wird in einem anderen Repository gepflegt. Ich habe das Ticket dorthin transferiert und schliesse dieses hier.
