### ISSUE TITLE
initiales Konzept für Buchhaltung und Konten ins Wiki bringen

### ISSUE THREAD

**Issue by RA-crm** [jlawyerorg/j-lawyer-org#756]
Eine der nächsten großen Schritte für j-l wird eine sinnvolle Buchhaltung und Kontoführung sein. Jens plant ein schrittweises Vorgehen. Außerdem wurde schon mehrfach diskutiert, dass einzelne Asprekte nicht eigenständig entwickelt werden müssen. Dazu habe ich ein paar Gedanken:

1.
Man muss zwischen der Kanzleibuchhaltung, Aktenkonten und Forderungskonten unterscheiden.

1.1
Die Kanzleibuchhaltung dient der Buchführung für die gesamte wirtschafltiche Einheit. Bei Einzelanwälten oder Personengesellschaftern reicht eine EÜR. Es bedarf keiner Bilanzierung.
In der Kanzleibuchhaltung werden sowohl die Kostennoten und darauf erfolgten Zahlungseingänge, aber auch die sonstigen Einnahmen (zB aus Vorträgen) und Ausgaben (Mieten, Personalkosten) verbucht.

1.2
Das Aktenkonto dient zu Erfassung der Einnahmen und Ausgaben in der jeweiligen Akten. Zu unterscheiden sind Honoraransprüche auf Grund von Kostennoten, Auslage bzw. deren Erstattung und der Ein- und Ausgang von Fremdgeld zur jeweiligen Akten. Nur wenn die Spalten Honorer, Auslagen und Fremdgeld am Schluss "0" ist, sollte es möglich sein, die Akte abzulegen.

1.3
Das Forderungskonto hat mit der Buchhaltung im engeren Sinne nichts zu tun. Hier werden die Forderungen des Mandanten gegen den Gegner erfasst und berechnet. Dabei sind neben der Hauptforderungen auch die Nebenforderungen (Rechtsanwaltskosten, Vollstreckungskosten, Auslagen und Zinsen) zu berücksichtigen. Dabei muss jedenfalls der Basiszinssatz der letzten 10 Jahre und der aktuelle Berücksichtigung finden. Auch sind die gesetzlichen Zinssätze zu berücksichtigen. Außerdem muss es einstellbare Vorgaben für die nicht bestimmte Zahlungen auf die Forderung geben.

2.
Als Lösung bietet sich m.E. ein Forderungskoto in Form des entwickelten Konzepts des "Falldatenblattes" an, welches aber dynamisch ein tagesaktuelles Ergebnis produziert und zur Akte gespeichert werden kann. Sinnvoller weise kommt dieses "Falldatenblatt" dann aber in den Reiter Berechnungen.

Die Kanzleibuchhaltung kann über eine Drittlösung integriert werden. Dabei muss aber sicher gestellt werden: 
a) die Kanzleibuchhaltung ist opensource
b) sie läuft auch allen unterstützten OS (am besten basiert sie auf java)
c) es gibt eine Schnittstelle, sodass die bestehenden Daten aus j-l verarbeitet werden kann und eine Buchung in der Kanzleisoftware direkt im Aktenkonto erfasst wird

Das Aktenkonto selbst wäre bei dieser Lösung lediglich ein Auszug aus der Kanzleibuchhaltung um den Umsatz in der Akte auf Ebene der Aktenbearbeitung im j-l nachvollziehen zu können.

**Comment by j-dimension** [comment]
Telefonat JW 02.07.2020:

- vollständige Lösung wäre "interessant", aber nicht zwingend. Datev-Schnittstelle?
- Forderungskonto / Aktenkonto / Fremdgeld als Mindestanforderungen
- verschiedene Rechnungsnummernpools benötigt, um Bürogemeinschaften abbilden zu können
- Nutzer können unterschiedliche Rechnungsnummernpools verwenden (bspw. Sekretariat erstellt Rechnungen für verschiedene eigenständig agierenden Anwälte)
- Rechnungserstellung per Rechtsklick auf Positionen im Aktenkonto
- Positionskategorien / Positionen - konfigurierbar machen - welche können das sein? 
- Aktenablage: Prüfung und Warnung (siehe Kommentar RA-crm oben)  - Nutzer entscheidet ob ablegen oder nicht
- Nachvollziehbarkeit: Rechnungsstatus, bspw. Entwurf / verschickt / bezahlt / überfällig / gestundet
- optional: Auswertung - aktenübergreifend
- Fremdgeld: separater Korb 
- Buchhaltungssoftware: Kandidaten für eine Anbindung?

**Comment by Maz111111** [comment]
Ich beschreibe mal einen Teil, wie ich die Rechnungsverwaltung aktuell ohne SW löse (wahrscheinlich so wie viele andere auch).
Ich habe eine Tabelle, in der die - von mir per Hand erstellten - Re-Nr (bei mir 100/20 - open end) drin stehen.
Wenn eine Re erstellt wird, öffne ich die Tabelle und sehe, welches die nächste Re-Nr ist, so dass ich diese in die RE eintragen kann. In der Tabellenzeile dieser Nr erfasse ich:
Re-Datum, Fälligkeit, AZ, Kurzrubrum, Bruttobetrag, Zahlungseingangsbetrag (Eintrag erfolgt von Hand, wöchentlich,  wenn ich die Buchhaltung für meinen Buchhalter vorbereite) und am Ende ein Feld, in das ich das Wort "erledigt" schreibe, wenn die Re vollständig beglichen ist.
Im Falle einer vereinbarten Ratenzahlung löse ich das derzeit sehr inkonsequent so, dass ich anstatt des Fälligkeitsdatums einfach "Rate" reinschreibe (hilft nichts, wenn man die Fälligkeit der Raten wissen will - da muss ich dann in die Akte und die Vereinbarung sehen).
Vielleicht ist das ja erstmal ein Ansatz.
Das Buchen macht aktuell ein Steuerbüro. Früher habe ich Lexware Buchhalter verwendet.
Allerdings klingt das alles sehr sehr umfangreich, was hier schon angedacht ist.
Vielleicht doch eher was für die 1.14 oder nur Teile...
Viele Grüße
Martin

**Comment by j-dimension** [comment]
Rohnotizen aus Telefon vom 30.11.: 

rechnung schreiben
- bereich kostenberechnungen: durchführen einer berechnung --> worddokument zum zweck einer preisauskunft / honorarauskunft --> eher nicht wichtig; man dann daraus eine rechnung erstellen
- bereich rechnungen
- bereich kostenanträge: anträge an gericht auf kostenerstattung der eigenen kosten (ohne rechnungsnummer) - scheint aber auch ganz normal über rechnungen zu gehen - also eher nicht wichtig --> als frage in die anwenderschaft
- bereich rechnungen:
-- mwst wählen, rvg-gesetz wählen, rechnungsvorlage (rechnung, ...) - "finde ich quatsch"; rechnungskreis - eigenes rechnungsnummersdchema bswp. für bürogemeinschaften (müssen auch unterschiedliche schemata sein); empfänger wählen; streitwert wählen; bezeichnung für dokumentenliste wählen; option "rechnung ist vorschussrechnung" (evtl. nicht so wichtig)
-- dann kann RVG-positionen zusammengeklickt werden
-- "zu berücksichtigende vorschussrechnungen auswählen"
-- übersicht der berechnung wird angezeigt
-- forderungskonto auswählen
-- mahnstufe
-- rechnungsdatum
-- frist wird eingetragen für bezahlung
-- bearbeitungsstatus: entwurf / gebucht
-- alle sumgsetzt als wizard
-- bestätigen, dokument wird generiert und geöffnet
-- leistungszeitraum muss enthalten sein
-- zahlungsziel
- bereich mit übersicht finanzen für die gesamte akte
- 


forderungskonto
- 


zeiterfassung
- honoravereinbarungen machen
- zeit automatisch erfassen -- kann im hintergrund gestartet werden
- tätigkeiten mit stundensatz
- "bei abrechnung ignorieren"
- dann: zeit abrechnen - rechnungsdialog erscheint, es sind positionen an- und abklickbar, es können noch neue gebühren hinzugefügt werden (acuh RVG), 

strafrecht nach rvg



buchhaltung über excel-sheet von pierre tunger

**Comment by RA-crm** [comment]
Wenn es oben heißt:

_forderungskonto_

zeiterfassung

    honoravereinbarungen machen
    zeit automatisch erfassen -- kann im hintergrund gestartet werden
    tätigkeiten mit stundensatz
    "bei abrechnung ignorieren"
    dann: zeit abrechnen - rechnungsdialog erscheint, es sind positionen an- und abklickbar, es können noch neue gebühren hinzugefügt werden (acuh RVG),

Dann möchte ich noch mal klarstellen, dass ein Forderungskonto die Forderungen des Mandanten gegen den Gegner oder einen Dritten beinhalten. Das hat mit der Buchhaltung nichts zu tun.

Das was unter Forderungskonto mit Honorarvereinbarung und Zeiterfassung beschrieben wird, kommt in das Aktenkonto. Denn Dort wird das Honorar, die Auslagen und das Fremdgeld erfasst.

**Comment by stm9x9** [comment]
> * bereich kostenanträge: anträge an gericht auf kostenerstattung der eigenen kosten (ohne rechnungsnummer) - scheint aber auch ganz normal über rechnungen zu gehen - also eher nicht wichtig --> als frage in die anwenderschaft

In der Tat sind das - genau so wie Kostenaufstellungen an unterlegene Gegner - keine umsatzsteuerlichen Rechnungen, weil das Gegenüber nicht der Leistungsempfänger ist. Man kann es aber auch als "Rechnung" machen, also zb mit Rechnungsnummer. Es darf halt nur nicht der Eindruck erweckt werden, der Empfänger könnte Vorsteuer draus ziehen. Damit sind dann die "echten" USt-Rechnungen nicht mehr mit lückenloser Rechnungsnummer versehen, weil ja immer wieder welche für diese "Pseudo-Rechnungen" verwendet werden. Das ist aber unschädlich: https://www.nwb-experten-blog.de/keine-pflicht-zur-vergabe-lueckenlos-fortlaufender-rechnungsnummern/

**Comment by stm9x9** [comment]
> * -- mwst wählen, rvg-gesetz wählen, rechnungsvorlage (rechnung, ...) - "finde ich quatsch";

Was genau, warum? zb Rechnungsvorlage wählen kann für die Unterscheidung echte Rechtnung Mdt / Kostenforderung an Ggn / PKH sinnvoll sein

> * -- "zu berücksichtigende vorschussrechnungen auswählen"

müßte man nicht eher oder auch die tatsächlichen Vorschußzahlungen auswählen?
