### ISSUE TITLE
[beA] Nachricht erfolgreich verschickt als eigenes Fenster

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#759]
Wenn eine beA-Nachricht verschickt wurde kommt im Forschrittsbalkenfenster die Meldung

Nachricht erfolgreich verschickt 

Dann schließt sich das recht schnell.

Solange wir eh keine beA-Versendung asynchron haben, wäre es schön, wenn Nachricht erfolgreich verschickt als eigenes Fenster aufploppt und erst nach einem OK verschwindet.

**Comment by j-dimension** [comment]
Im Fehlerfall okay (ist jetzt schon der Fall), aber im Erfolgsfall?

Könnte mir vorstellen dass das eine Kontroverse gibt. Mal in der Mailingliste ansprechen?

**Comment by Maz111111** [comment]
Hab es bereits in der Mailingliste geschrieben:
Vorschlag zur Güte:
Die Erfolgsmeldung in den Dialog zum Abspeichern des Journals einfügen.
Dann muss sie mit einem Klick bestätigt werden und man hat aber keinen Klick zusätzlich.
Viele Grüße

**Comment by j-dimension** [comment]
Die Logik ist so, dass

- im Fehlerfall in jedem Fall eine zu quittierende Fehlermeldung dargestellt wird, unabhängig davon ob man das Speichern in die Akte an- oder abgewählt hat
- beim Schreiben einer Nachricht an ein EGVP eine Fehlermeldung angezeigt wird, wenn vom beA kein Laufzettel geliefert wird
- beim Schreiben einer Nachricht an ein EGVP eine Fehlermeldung angezeigt wird, wenn vom beA zwar ein Laufzettel geliefert wird, der Laufzettel aber aussagt dass der Versand nicht erfolgreich war

Insofern hat aus meiner Sicht eine "Positivmeldung" keinen Mehrwert. Im Gegenteil - Je nach Kritikalität der versendeten Nachricht würde ich als Entwickler Euch evtl. in einer falschen Sicherheit wiegen, wenn ich Erfolg so explizit signalisiere und dann doch etwas schief gegangen ist. Das muss ja nicht mal in meinem Hoheitsbereich liegen, sondern im beA selbst.

**Comment by Maz111111** [comment]
Naja...wegen mir braucht es die Bestätigung nicht.
Bei den wichtigen Nachrichten kopiere ich mir eh den Export händisch in die Akte - kontrolliere also händisch nochmal, ob alles glatt gelaufen ist. Sollte eigentlich jeder Anwender aktuell so handhaben.
Irgendwann wird's auch mit der Schnittstelle automatisch gehen, so dass dann auch über das Abspeichern des Exports in die Akte eine Kontrolle da ist.

**Comment by j-dimension** [comment]
@stm9x9 dann würde ich an der Stelle erstmal keinen Aufwand investieren. Okay?
