### ISSUE TITLE
[beA] Laufzettel Rohdaten abspeichern können

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#760]
![image](https://user-images.githubusercontent.com/29924198/82377160-90acd480-9a23-11ea-83b1-89d7316d81dc.png)

Danke!

Toll wäre es, wenn man das nun auch noch auf der Festplatte abspeichern könnte, um das weiterleiten zu können.

**Comment by j-dimension** [comment]
Strg+C, Strg+V ?

**Comment by stm9x9** [comment]
Möglich aber nicht gerade bequem. Und für nicht-Technik-affine Mitarbeiter eine Hürde.

**Comment by j-dimension** [comment]
Puh... ehrlich? Nicht technik-affine Mitarbeiter werden die Funktion nicht nutzen, oder? Die fühlen schlicht keinen Bedarf für diese Informationen.

**Comment by Mucki526** [comment]
Das einzige was man braucht beim BEA als Anwalt ist die Möglichkeit den erfolgreichen Zugang der Versendung beim Gegner - Gericht mit Nachweis, welche Anlagen mitgeschickt wurden, nachzuweisen und für analoge Richter verständlich und schlüssig dargestellt (gerichtsfest) ausdrucken zu können...

**Comment by j-dimension** [comment]
Das Drucken ist ja bereits in #708 erfasst.

Im Übrigen benötigt man für einen echten Nachweis eigentlich den offiziellen Export der BRAK, der aber nicht über die Schnittstelle verfügbar ist: https://github.com/jlawyerorg/j-lawyer-org/issues/412#issuecomment-542388081

Insofern würde ich hier gern zumachen. Die Laufzettel wären dann mit im Ergebnis von #708 enthalten. Bis das umgesetzt ist, kann man sich über die Zwischenablage (s.o.) helfen.

**Comment by stm9x9** [comment]
> Im Übrigen benötigt man für einen echten Nachweis eigentlich den offiziellen Export der BRAK, der aber nicht über die Schnittstelle verfügbar ist: [#412 (comment)](https://github.com/jlawyerorg/j-lawyer-org/issues/412#issuecomment-542388081)

Das sehe ich eigentlich nicht so. Der Laufzettel, die processcard.osci ist die laut Gesetz vorgesehene und mit den notwendigen kryptographischen Empfangssignaturen versehene Eingangsbestätigung. Diese haben wir ja dankenswerterweise(!) nun endlich zur Verfügung. DAS ist der echte Nachweis.

**Comment by j-dimension** [comment]
> processcard.osci ist die laut Gesetz vorgesehene und mit den notwendigen kryptographischen Empfangssignaturen versehene Eingangsbestätigung

Ist das tatsächlich so? Auf welche Quelle könnte man sich dabei beziehen?

**Comment by stm9x9** [comment]
zum einen: 
![image](https://user-images.githubusercontent.com/29924198/83912851-d4674400-a76e-11ea-986a-cd76a27837d3.png)

**Comment by j-dimension** [comment]
Danke, @stm9x9 !

**Comment by stm9x9** [comment]
ggf noch ein ganz anderer Ansatz:

Als Beweis des ersten Anscheins (siehe http://ervjustiz.de/vgh-kassel-egvp-eingangsbestaetigung-ist-anscheinsbeweis-fuer-fristwahrung?fbclid=IwAR3ENrwDsOnkOnN4F-VekIzQ2dYO2flwJg5z0Zl77lvDpLCDRg0kXCzl-0Q) den Ausdruck, wie er in #708 skizziert wurde und dann, falls man es abgeben muß beim Gericht, ein zip mit der oscicontentdata.osci(?) und der processcard.osci oder was immer man noch brauchen würde. Den Inhalt dieses zips könnte man zb in Absprache mit H. Müller oder U. Möller gestalten.
