### ISSUE TITLE
[beA] Speichern von Dateien - Dateinname

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#762]
Wenn die Datei einen Alias/Anzeigenamen hat, dann wird sie so abgespeichert im Dateisystem:

Dateiname (Anzeigename)
200519-SG Erledigung.pdf (01_Anlage_200519-SG Erledigung.pdf)

sinnvollerweise sollte aber der Dateityp am Ende stehen mit einem . davor.

Vorschlag:

Vom Dateinamen die Endung abschneiden und hinter dem ) anfügen:

200519-SG Erledigung (01_Anlage_200519-SG Erledigung.pdf).pdf

oder 

S_114_AS_xxxx_18_URTEIL_00000026163720 (Urteil vom 11.1.20).pdf
statt
S_114_AS_xxxx_18_URTEIL_00000026163720.pdf (Urteil vom 11.1.20)

**Comment by stm9x9** [comment]
oder 
xjustiz_nachricht.xml (Signatur).p7s
statt
xjustiz_nachricht.xml.p7s (Signatur)

**Comment by stm9x9** [comment]
Das gleiche Problem ist beim speichern in die Akte:

![image](https://user-images.githubusercontent.com/29924198/101228373-ba65da00-369b-11eb-9221-d80dd6731513.png)


hinterher kann man solche Dateien nicht mehr in j-l öffnen, weil der Dateityp ja nicht am Ende steht.

**Comment by j-dimension** [comment]
via https://github.com/j-dimension/j-lawyer-bea-wrapper/issues/37

**Comment by stm9x9** [comment]
> via [j-dimension/j-lawyer-bea-wrapper#37](https://github.com/j-dimension/j-lawyer-bea-wrapper/issues/37)

der Link gibt ein 404er

**Comment by j-dimension** [comment]
@stm9x9 weil das ein privates Repository ist.
