### ISSUE TITLE
[adressen] weitere Felder für die Beteiligten

### ISSUE THREAD

**Issue by RA-crm** [jlawyerorg/j-lawyer-org#763]
Ich vermisse folgende Felder für den Adresssatz:

bei natürlichen Personen:
Staatsangehörigkeit
Gebutrsname
Verstorben am

USt-ID
Steuer-ID

bei juristischen Personen:
Register-Nr.
Register-Gericht

**Comment by PBaumfalk** [comment]
Bei juristischen Personen wäre, damit man die EDA dann auch noch erstellen kann wichtig: 

Rechtsform
vertreten durch

**Comment by stm9x9** [comment]
"vertreten durch" mit der generischen Angabe "den Vorstand" etc oder mit den konkreten Personen in dem Feld? Letzteres würde ich eher über einen eigenen Kontakt machen und einer entsprechenden selbstdefinierten Rolle "gesetzlicher Vertreter" oder "Vorstand".

**Comment by RA-crm** [comment]
Ich teile die Ansicht von @stm9x9. Soweit eine Vertretung vorliegt (jur. Personen, Minderjährige, Betreute) ist es praktikabel, die konkrete Person als eigenen Kontakt und der selbstdifinierten Rolle aufzunehmen.

@PBaumfalk: wie muss bei EDA des Rechtsform angegeben werden; als einzelnes Feld? Gibt es da einen nc bzgl. der Auswahl?

**Comment by j-dimension** [comment]
Ich setze hier erstmal alles um, mit Ausnahme von "vertreten durch" - das mach ich via Ticket #120, da es ein Verweis auf einen anderen Adresseneintrag sein sollte.
