### ISSUE TITLE
Autobennenung der Dokumente mit den neuen Beteiligtentypen

### ISSUE THREAD

**Issue by Maz111111** [jlawyerorg/j-lawyer-org#764]
Ich habe den Beteiligtentyp Anwalt Gegner erstellt und die KSW generierte automatisch den Platzhalter ANWALTGEGNER.
In den Vorlagen selber funktionierte dies - soweit bisher ersichtlich - alles einwandfrei.
Allerdinges nicht bei der automatischen Dokumenten Benennung.
Bsp. 
Gegner als "Horst Müller" benannt.
Dok-Vorlage heißt "Schreiben an ANWALTGEGNER"
Dann machte die KSW daraus "Schreiben an ANWALTMüller Horst".

Nachdem ich den Platzhalter für Anwalt Gegner händisch in ANWALTGEG geändert habe, funktioniert alles, wie es soll.
Leider muss ich alle Vorlagen nochmal nachbearbeiten :(

Hier sollte der Platzhalter von vornherein kompatibel (Auto-) benannt werden also die Kombination eines Platzhalters mit einem bereits bestehenden verhindert werden.

Viele Grüße

**Comment by j-dimension** [comment]
Werde ich korrigieren.

Unabhängig davon: ich persönlich finde ANWALTGEGNER zu lang als Platzhalterpräfix. Das macht wahrscheinlich auch das Layouting der Vorlagen schon etwas schwieriger.
