### ISSUE TITLE
[beA] Justizbehörde automatisch befüllen

### ISSUE THREAD

**Issue by Maz111111** [jlawyerorg/j-lawyer-org#770]
Wäre es eventuell möglich, dass die Justizbehörde von der KSW anhand des Empfängers automatisch bestimmt und derart vorgeschlagen wird, dass man nur noch auf "übernehmen" klicken kann (nicht muss).
Dies könnte über einen Abgleich mit dem Eintrag unter Firma geschehen. Soweit ich das sehe, ist der dortige Eintrag - wenn man es über die beA Suche automatisch befüllen lässt - identisch mit dem Namen der dann zu wählenden Justizbehörde.
Findet die KSW keine Übereinstimmung, bleibt das Textfeld einfach leer und der Anwender kann von Hand wählen bzw. (zunächst nur) Unbekannt klicken, weil es entweder korrekt ist, dass keine Übereinstimmung gefunden wurde, da der Empfänger keine Justizbehörde ist oder der Anwender den Eintrag unter Firma von Hand abgeändert hat.
Hier wäre es dann auch schön, wenn bei RA und allen anderen Empfängern, für die unbekannt gewählt werden sollte, das Textfeld automatisch leer würde und nur noch" unbekannt" und "Abbruch" anklickbar wären.
Ich stelle mir folgende Logik vor:
Steht im Textfeld keine zulässige Justizbehörde oder nichts, ist der Button "Übernehmen" (ich meine den ganz rechten Button - kann gerade nicht prüfen, ob der tatsächlich "Übernehmen" heißt) grau und nicht klickbar.
Sollte die KSW anhand des gewählten Empfängers keine Justizbehörde ermitteln können, könnte das Textfeld automatisch leer bleiben, mit der Folge, dass zunächst nur "Unbekannt" oder "Abbruch" auswählbar ist oder der Anwender von Hand eine zulässige Justizbehörde in der in #749 benannten Form eintragen kann.
Vielleicht ist das ja umsetzbar
Gruß
Martin

**Comment by j-dimension** [comment]
Ist nicht so trivial. Schau Dir mal #394 an. 

Ich schliesse das hier als Duplikat.
