### ISSUE TITLE
[beA] Ordner bei Fehlern optional neu laden mit Nutzerbestätigung (war: gesendete Nachricht verschwunden)

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#772]
Ich habe gestern zwei Nachrichten an dasselbe Gericht geschickt. Eine der beiden ist über die Schnittstelle nicht mehr auffindbar.

Beide sind in beA-web im Gesendet-Ordner mit Übermittlungsstatus Erfolgreich. In j-l in Gesendet ist nur eine der beiden Nachrichten. Sie ist auch nicht mehr in Postausgang oder Entwürfe.

**Comment by j-dimension** [comment]
Das hört sich nach einem Schnittstellenfehler an. Kannst Du das client.log senden?

**Comment by j-dimension** [comment]
Wird die Nachricht auch nach einem Neustart des Clients nicht angezeigt?

**Comment by stm9x9** [comment]
bis heute nicht zu sehen die Nachricht

**Comment by j-dimension** [comment]
Dann brauche ich nochmal Hilfe: 

- Client schliessen
- client.log löschen
- Client öffnen
- Zeit A notieren (und später per E-Mail an mich)
- unmittelbar danach am beA anmelden
- ca. 2 Minuten warten (damit ich die Vorgänge zeitlich eindeutig trennen kann)
- Zeit B notieren
- unmittelbar danach den Ordner abrufen, in welchem die Nachricht fehlt

--> Zeiten A und B sowie das client.log an mich senden. 

Danke!

**Comment by stm9x9** [comment]
ich habe bevor ich das oben las leider schon folgendes gemacht:

ich habe beide Nachrichten in einen Unterordner von gesendet per web verschoben. Dort findet sie j-l auch.

Ich habe sie dann zurückgeschoben per web.

Jetzt bekomme ich beim Öffnen von gesendet in j-l das hier:

![image](https://user-images.githubusercontent.com/29924198/83979125-5c368500-a90c-11ea-8e0a-4b576dd8b526.png)

und der Ordner bleibt komplett leer

**Comment by stm9x9** [comment]
Zeit A 22:23
Zeit A2 (bea vollständig geladen, Nachrichten im Eingang zu sehen): 22:26
Zeit B: 22:33

Ich habe jetzt die Nachrichten wieder in einen Unterordner verschoben:

A: 22:38
A2: 22:41
B: 22:44

jetzt kann ich den Hauptordner wieder öffnen, es liegt offenbar an einer , mußtmaßlich der bislang unsichtbaren, der beiden Nachrichten.

**Comment by j-dimension** [comment]
> Zeit A 22:23
> Zeit A2 (bea vollständig geladen, Nachrichten im Eingang zu sehen): 22:26
> Zeit B: 22:33
> 
> Ich habe jetzt die Nachrichten wieder in einen Unterordner verschoben:
> 
> A: 22:38
> A2: 22:41
> B: 22:44
> 
> jetzt kann ich den Hauptordner wieder öffnen, es liegt offenbar an einer , mußtmaßlich der bislang unsichtbaren, der beiden Nachrichten.
> Und den Unterordner kann ich auch öffnen und sehe wieder beide: 22:46

Kann ich dazu noch das client.log haben?

**Comment by j-dimension** [comment]
Nevermind, hab ich gerade gefunden.

**Comment by stm9x9** [comment]
und es fehlen wieder zwei gesendete Nachrichten von heute. Erst dachte ich, es könnte was mit den aufgelösten SAFE-ID-Adressen zu tun haben, da wurde vor einiger Zeit einiges geändert und ich habe die Empfänger aus dem internen Adressbuch genommen. Aber dem ist nicht so: es gingen zwei Nachrichten an dasselbe Sozialgericht und das war auch nicht von den Änderungen betroffen.

log kommt wieder per Mail.

**Comment by j-dimension** [comment]
Tritt der Fehler unabhängig davon auf, ob Nachrichten per beA Web verschoben werden? Oder ist das evtl. ein Trigger für den 9999?

**Comment by stm9x9** [comment]
> Tritt der Fehler unabhängig davon auf, ob Nachrichten per beA Web verschoben werden? 

ja. Es fängt ja immer so an, daß ich in j-l verschicke und sie dann gleich in gesendet nicht zu sehen sind. Bevor ich dann überhaupt was in beA-Web gemacht hatte.

> Oder ist das evtl. ein Trigger für den 9999?

Ich weiß es nicht - eben zb hatte ich wieder nach dem Einloggen im Ordner Gesendet diesen 9999er. zwei, dreimal. Dann auf einmal wurde der Inhalt aufgelistet. (ohne die oben genannten fehlenden Nachrichten).

**Comment by j-dimension** [comment]
@stm9x9 Die Logs von Dir zeigen eigentlich nur zwei Fehlerarten: 

1. Irgendwelche Identitäten können beim Laden der Ordnerübersicht nicht aufgelöst werden. Das kann in der Tat passieren und wird daher vom beA Wrapper ordentlich abgefangen und behandelt. Praktisch steckt in der Ordnerübersicht nur die Information, zwischen welchen Safe IDs Nachrichten ausgetauscht wurden. Um da eine sinnvolle Anzeige draus zu bauen, löst der Client die Safe IDs zu Anzeigenamen auf. Und das geht bspw. bei Änderung von Safe IDs schief - bspw. weil sich die ID eines Teilnehmers geändert hat oder der Teilnehmer keiner mehr ist. Gar nicht so unüblich, daher behandelt / abgefangen - in diesem Fall wird dann eben nur die Safe ID angezeigt.

2. Der 

`de.brak.bea.application.dto.soap.types5.BeaFault: 9999 - General error processing request.`

 Tritt ebenfalls beim Laden des Ordners auf und bringt die Anfrage in diesem Fall zum Erliegen. Das ist schlicht die Anfrage an die BRAK-Server "Gib mir mal die Nachrichtenliste für Ordner x" - wird dort vom Server ein Fehler geworfen, gibt es nichts mehr zu behandeln, da ich gar keine Antwort habe die ich noch irgendwie sinnvoll darstellen könnte. 
Nur: diesen Fehler bekomme ich weder reproduziert, noch habe ich als "Hersteller" irgendeine Einflussmöglichkeit. Bei der Anfrage gibt es praktisch nichts falsch zu machen. 

Hier würde nur die Möglichkeit bleiben, das zusammen an Hand Deines Postfaches mal durchzuspielen, alle Daten zu sammeln die sinnvoll sind, und das als Ticket an die BRAK zu geben.

Gib mir bescheid wenn wir das tun wollen.

**Comment by stm9x9** [comment]
Könnte man softwareseitig als Abhilfe eine Art "Wahlwiederholung" anbieten? Momentan muß ich händisch in einen anderen Ordner gehen und wieder zurück. Und das so 2-3 mal, bis ich den Ordner voll bekomme (was natürlich nichts am Problem der einzelnen fehlenden Nachricht ändert).

**Comment by j-dimension** [comment]
Technisch sehr einfach machbar, sollte aber nur getan werden wenn es tatsächlich etwas bringt. Heißt das, dass nach dem Fehler ein Ordner neu geladen werden kann und das läuft dann ohne Fehler durch?

**Comment by stm9x9** [comment]
wie beschrieben, nach dem 3. oder 4. Mal wird der Ordner dann ohne Probleme geladen (also außer dem Problem, daß manche Nachrichten halt nicht dabei sind, was der ursprüngliche Inhalt des Tickets war). Das wäre also eine große Erleichterung, ideal wäre sowas:

error blabla 9999

Beim Öffnen dieses Ordners ist was schief gelaufen. Wollen Sie es erneut versuchen?

[Sofort neu versuchen] [automatische Wiederholung (5 Versuche)] [Abbruch]

und die 5 Versuche dann alle 5-10sec oder so.

**Comment by j-dimension** [comment]
- wrapper versucht getFolderOverview jetzt bis zu drei mal
- wenn Nutzer den Aktualisieren-Knopf nutzt, wird die Ordnerstruktur komplett neu geladen (jetzt wird nur auf eine gültige Verbindung geprüft und ggf. neu eingeloggt)
