### ISSUE TITLE
ändern der Daten eines Beteiligten sofort übernehmen

### ISSUE THREAD

**Issue by Maz111111** [jlawyerorg/j-lawyer-org#777]
Wenn man in einer Akte zu den Beteiligten wechselt und dort die Daten des Beteiligten aufruft und ergänzt bzw. ändert, dann abspeichert und wieder zurück in die Akte geht, sind die geänderten Daten nicht für Vorlagen da. Erst wenn man die Akte einmal verlassen und wieder neu geöffnet hat.
Bsp.
Ich bin in der Akte und möchte eine Fax aus einer Vorlage an das Gericht erstellen. Ich stelle fest, dass die Faxnummer noch nicht für das Gericht in dessen Adressdaten hinterlegt ist. Ich gehe über den Reiter "Beteiligte" zu den Adressdaten des Gerichtes und trage die Faxnummer nach. Dann speichere ich die Adressdaten und gehe über den "Pfeil zurück" wieder in die Akte zu "Dokumente" und versuche erneut, die Vorlage zu verwenden. Die eben eingetragene Faxnummer ist nicht übernommen. Dann muss ich die Akte verlassen und neu öffnen. Dann ist die Faxnummer für die Vorlage da.

Kann hier Abhilfe geschaffen werden, so dass die Änderungen ohne Verlassen der Akte sofort da sind.

Grüße
Martin

**Comment by j-dimension** [comment]
Die geänderte Adresse ist zwar innerhalb der Akte aktualisiert, die Änderung aber nicht für das Vorlagensystem sichtbar. Korrigiert.
