### ISSUE TITLE
Installation: Hinweis auf root passwort

### ISSUE THREAD

**Issue by Dickmaulruessler** [jlawyerorg/j-lawyer-org#780]
Im Rahmen des Installationsprozesses die Wichtigkeit des **root passwortes** noch deutlicher hervorheben: 

- Rote Hervorhebung?

- Option "Ausdrucken" anbieten?

Ggf. auch Erläuterung: 

_"Das Root Passwort wird später u.a. für jedes Server-Update benötigt."_

**Comment by librelegal** [comment]
Und ein Hinweis auf die Möglichkeit der Änderung scheint mir auch sinnvoll, zumal das Standard Passwort geändert werden sollte ...

**Comment by j-dimension** [comment]
> Und ein Hinweis auf die Möglichkeit der Änderung scheint mir auch sinnvoll, zumal das Standard Passwort geändert werden sollte ...

@librelegal es handelt sich nicht um ein Standardpasswort. Der Installer erzeugt ein individuelles MySQL-root-Passwort für jede Installation.

**Comment by stm9x9** [comment]
pro Ausdrucken! (kann man ja dann auch als pdf drucken)

**Comment by stm9x9** [comment]
könnte man gleich ein Komplettpaket machen. Passwörter, ggf Pfade oder so. Alles was man für einen Zugriff oder Umzug braucht.

**Comment by j-dimension** [comment]
Ich bin ganz offen: ausdrucken werde ich nicht implementieren. Die Installation muss anwenderfreundlich sein, aber der Anwender verbringt nur einmalig mit der Installation, dann viel Zeit mit der Nutzung. Ich muss die Zeit an der "richtigen" Stelle investieren.

**Comment by Dickmaulruessler** [comment]
Das machst du so vollkommen richtig! Danke dir!

**Comment by j-dimension** [comment]
Dialog überarbeitet.

**Comment by Dickmaulruessler** [comment]
Ich würde dies noch einmal zur Diskussion stellen... auch mit der Möglichkeit, sich das Datenbank-Passwort später im Programm noch einmal gesondert anzeigen lassen zu können.

Das Ausdrucken fände ich nachwievor sinnvoll. Wenn man das Passwort abschreibt, bestehen immer Fehlermöglichkeiten. Und ein "offizieller" J-lawyer-Ausdruck wird bei den Nutzern einfach mehr wertgeschätzt, als ein eigenes handschriftliches Gekrakel. Ich glaube die Mühe lohnt sich....

**Comment by j-dimension** [comment]
Man kann die Information, die der Installer anzeigt, einfach in die Zwischenablage übernehmen.
