### ISSUE TITLE
Adress-Daten: Geschlecht eingeben können

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#785]
Für automatisierte Erstellung von Texten (zb in Falldatenblättern wie Flugrecht) könnte damit auf den Wert Geschlecht zurückgegriffen werden, um "mein Mandant hat" oder "meine Mandantin hat" zu erstellen.

offene Frage: auch divers dazunehmen?

**Comment by stm9x9** [comment]
ggf auch "Firma" oder "Gesellschaft"

**Comment by j-dimension** [comment]
ja, inklusive divers und Gesellschaft

**Comment by stm9x9** [comment]
oder "juristische Person"

**Comment by j-dimension** [comment]
> oder "juristische Person"

Das finde ich tatsächlich am passendsten.

**Comment by j-dimension** [comment]
da ich bei Hinzufügen des Feldes irgendeinen Standardwert für die vorhandenen Daten setzen muss, nehme ich noch "sonstige" in die Liste auf

**Comment by stm9x9** [comment]
> da ich bei Hinzufügen des Feldes irgendeinen Standardwert für die vorhandenen Daten setzen muss, nehme ich noch "sonstige" in die Liste auf

wenn dieser Wert insbesondere für alte Datensätze sein soll, vielleicht eher "nicht definiert"?

**Comment by j-dimension** [comment]
> wenn dieser Wert insbesondere für alte Datensätze sein soll, vielleicht eher "nicht definiert"?

ja
