### ISSUE TITLE
Falldatenblätter: Text-Generierung verschluckt Zeichen

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#788]
![image](https://user-images.githubusercontent.com/29924198/85083646-a227fe80-b1d2-11ea-877c-fc1a6ec33d82.png)

Das jeweils zuletzt eingegeben Zeichen (hier die 6 im Datum) wird im erzeugten Schriftsatz nicht angezeigt. Erst wenn ich zb in Flugnummer eine 7 hinter die 3 eingebe, wird die 6 im Datum geschrieben, dafür aber die 7 noch nicht. Alternativ hilft auch ein Klick auf einen Radio-Button

**Comment by j-dimension** [comment]
@stm9x9 am bestroffenen Element statt 

`keyPressed`

einfach 

`keyReleased` 

verwenden.

**Comment by j-dimension** [comment]
PS: das habe ich in sgguk bereits angepasst und stelle es gleich zur Verfügung
