### ISSUE TITLE
"Drucken" überdenken

### ISSUE THREAD

**Issue by Dickmaulruessler** [jlawyerorg/j-lawyer-org#789]
Das Sachgebiet könnte auf dem Handaktenvorblatt auftauchen.

Es gibt einen "**Drucken"-Reiter**. 

- Dieser beinhaltet wohl das, was zum Ausdruck für die Handakte gedacht ist. So könnte man es dann auch bezeichnen. Die Bezeichnung "Drucken" finde ich jedenfalls irreführend. 

- Kann man das, was dort auf den 2 Seiten auftaucht auch definieren? 
Die "Aktendaten" mit Beteiligten, Wiedervorlagen, Fristen und Terminen machen wohl für alle Sinn.
Das Kostenvorblatt allerdings benötigen Zivilrechtler freilich ständig, Anwälte aus anderen Rechtsgebieten aber möglicherweise nie. 

- möglicherweise möchte jemand dort auch ein individuelles Dokument hinzufügen können?

Oben links gibt es noch einen **Drucken-Icon**. 

- Dieser druckt immer (nur) den o.g. Reiter aus. Ich würde es logischer finden, wenn immer das gerade aktive Fenster gedruckt werden würde (ich weiß nicht, ob man das wirklich braucht, logisch wäre es aber).

- Was ich mir gut vorstellen kann, ist, dass häufiger einmal Bedarf besteht, das Falldatenblatt ausdrucken zu wollen.

![drucken](https://user-images.githubusercontent.com/46451749/85143783-7cd6d700-b24a-11ea-838c-0ce96cf7fa5f.jpg)

**Comment by Dickmaulruessler** [comment]
möchten ein paar Kollegen zu dem Reiter noch sagen, was sie da meinen ?

**Comment by stm9x9** [comment]
ich bin über den Ausdruck (Wortspiel intended! :-D) "Drucken" auch immer gestolpert. Die neue Benamsung finde ich gut.

Den allgemeinen Druckbutton finde ich dann auch komisch, sollte dann weg.

btw, was ist JasperPrint-Report?

Und BTW: das Speichern-Symbol in dem Handaktending

![image](https://user-images.githubusercontent.com/29924198/85189419-4c755400-b2af-11ea-9acf-6517f4a614df.png)

da kann man zwar zb pdf auswählen, aber da wird kein pdf gespeichert.

**Comment by stm9x9** [comment]
BTW: Das Sachgebiet könnte auf dem Handaktenvorblatt auftauchen.

**Comment by j-dimension** [comment]
> Den allgemeinen Druckbutton finde ich dann auch komisch, sollte dann weg.

Werde ich drinlassen, aber mit einem besseren Tooltip versehen.

**Comment by j-dimension** [comment]
> da kann man zwar zb pdf auswählen, aber da wird kein pdf gespeichert.

https://github.com/jlawyerorg/j-lawyer-org/issues/794

**Comment by j-dimension** [comment]
Ich würde hierüber erstmal die Anpassung bzgl. der Bezeichnung der Oberflächenelemente umsetzen. Für die selbst definierbaren Handaktenbögen und das Drucken der Falldatenblätter bitte ggf. neue Tickets machen, da sie unabhängig voneinander priorisiert und bearbeitet werden können. Danke!
