### ISSUE TITLE
Zeiterfassung und Abrechnung

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#790]
Eine Anregung (also ggf nur ein fernes todo-Ziel) aus dem aktuellen Anwaltstag - Vortrag Marktübersicht KSW:

![image](https://user-images.githubusercontent.com/29924198/85188322-036cd200-b2a6-11ea-9917-40fc84d20fe6.png)

Zeiterfassung einbauen und dabei mit Abrechnung gegenchecken: Ist schon länger nicht abgerechnet worden? Sind Budgets / Vorauszahlungen erschöpft? (wohl hauptsächlich bei Zeithonorar)

**Comment by j-dimension** [comment]
Duplikat von #58
