### ISSUE TITLE
Schnittstelle für Adressen zu anderen Kontaktdatenbanken

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#792]
Eine Anregung (also ggf nur ein fernes todo-Ziel) aus dem aktuellen Anwaltstag - Vortrag Marktübersicht KSW:

Export (und Import?) insbesondere von Mandantenkontakten zu Outlook, google contacts, Thunderbird, owncloud, damit man u.a. die Daten auch auf dem Handy hat.

![image](https://user-images.githubusercontent.com/29924198/85188440-bf2e0180-b2a6-11ea-8770-772b3143629b.png)

**Comment by j-dimension** [comment]
Teil von #330 und #107
