### ISSUE TITLE
Termine / Fristen / synchronisieren mit anderen Kalendern

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#793]
Eine Anregung (also ggf nur ein fernes todo-Ziel) aus dem aktuellen Anwaltstag - Vortrag Marktübersicht KSW:

![image](https://user-images.githubusercontent.com/29924198/85188476-18963080-b2a7-11ea-9376-8a5abed11369.png)

**Comment by j-dimension** [comment]
Duplikat von #108
