### ISSUE TITLE
BEA Versendung

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-org#796]
Ich habe es jetzt zum zweiten Mal. Wenn mein Rechner morgens nicht neu hochgefahren wird und BEA (untechnisch) gesagt, den Rechner ausgeloggt hat, dann führt der Versuch der Versendung zu einem Fehler. Wenn man sich dann einloggt und nochmals versendet hat man eine doppelte Versendung und es wird sogar in der Akte gespeichert (Das habe ich daran gemerkt, dass gemeldet wird, dass der Dokumentennamen schon vergeben ist. Die Gretchenfrage - liegt es jetzt auch zweimal bei Gericht???

**Comment by j-dimension** [comment]
Da brauche ich mehr Informationen. 

Wird der j-lawyer.org Client dann auch über Nacht laufen gelassen?

"Versuch der Versendung führt zu einem Fehler" - was für einem?

**Comment by Mucki526** [comment]
Ja, absolut unökologisch kommt es bei mir oft vor, dass der Rechner einfach über Nacht weiterläuft. Morgens läuft alles weiter, aber es gibt eine Fehlermeldung (beim nächsten Mal mache ich geistesgegenwärtig einen Screenshoot...) beim Versuch der BEA Versendung. Ich konzentriere mich beim nächsten Mal auch auf den Ablauf (was der doofe User (also ich) da eigentlich bei der Fehlermeldung in welcher Reihenfolge macht)

**Comment by j-dimension** [comment]
Bei neuen Erkenntnissen gern das Ticket wieder öffnen.
