### ISSUE TITLE
Desktop-Oberflächenverbesserungen

### ISSUE THREAD

**Issue by j-dimension** [jlawyerorg/j-lawyer-org#798]
- [x] Transparenz
- [x] größere Icons im Header
- [x] Exo2 im Header
- [x] Divider Location der Splitpanes nicht immer neu setzen
- [x] dynamisch ladende Hintergrundbilder?

**Comment by j-dimension** [comment]
neuer Standarddesktop: 

![grafik](https://user-images.githubusercontent.com/3729754/85903881-b63db280-b807-11ea-9083-8ab31b48afca.png)

**Comment by j-dimension** [comment]
mit zufälligem Hintergrundbild:

![j-lawyer-desktop](https://user-images.githubusercontent.com/3729754/85904225-70cdb500-b808-11ea-8e60-326a0ae15dd2.png)

**Comment by Dickmaulruessler** [comment]
Hintergrundbild finde ich recht verspielt.... Bleibt das optional?

**Comment by j-dimension** [comment]
> Hintergrundbild finde ich recht verspielt.... Bleibt das optional?

Ja, dazu gibt es neue Menü "Ansicht" - dort kann man das an- und ausschalten. Prinzpiell haben bereits alle Ansichten ein Hintergrundbild, nur eben ein abstraktes. Und der Desktop ist in 1.12 noch nicht semi-transparent.
