### ISSUE TITLE
Übernahme von BEA-Daten bei Schnellerfassung

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-org#804]
Lege gerade eine Akte mit "neuem" Anwalt auf der Gegenseite an. Wenn ich die Adressdaten des Kollegen eingebe, wird es kompliziert. Ich kann nicht einfach seine Daten aus dem BEA übernehmen. Wäre "schick" -> Taste Daten aus BEA übernehmen (im Fenster Adress-Schnellerfassung)

**Comment by j-dimension** [comment]
Nur Namen eintrage, dann hast Du ihn in der Akte, kannst draufklicken und dort die Übernahme aus dem beA starten?

**Comment by Maz111111** [comment]
Ich hatte auch mal drüber nachgedacht, um diese Erweiterung zu bitten.
Hab dann aber festgestellt, dass ich in der Schnellerfassung die Anrede und Grußformel nicht einstellen könnte und dann ohnehin in die richtige Beteiligtenanlage wechseln müsste.
Die Erweiterung würde also vermutlich keine Vorteile bringen
