### ISSUE TITLE
[Adressen] Alter anzeigen und U18-Warnung

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#814]
![image](https://user-images.githubusercontent.com/29924198/86416324-e256a900-bcc9-11ea-8112-274445a2a8b9.png)

Da rechts ist noch so viel ungenutzter Platz :-)

Da wäre es praktisch, das jeweils aktuelle Alter ausgerechnet zu bekommen (und das auch als Platzhalter zu haben) und eine Warnung, wenn ein Mandant minderjährig ist. (wg Vollmachten zb).

Dabei das Alter bei verstorbenen Kontakten nach dem Tod nicht weiterzählen sondern mit einem (+) dahinter das Sterbealter anzeigen.

**Comment by j-dimension** [comment]
Bei der Altersanzeige gehe ich mit, bei der Volljährigkeit bin ich unsicher. Das ist länderabhängig - ich habe bspw. eine mir bekannte Installation in Edinburgh, bei denen würde das nicht passen.

Und jetzt bitte nicht mit "dann möchte ich die Jahre zur Volljährigkeit in Abhängigkeit des gewählten Landes einstellen können" antworten :-)

**Comment by stm9x9** [comment]
> Bei der Altersanzeige gehe ich mit, bei der Volljährigkeit bin ich unsicher. Das ist länderabhängig - ich habe bspw. eine mir bekannte Installation in Edinburgh, bei denen würde das nicht passen.

Hab ich mir ehrlich gesagt, noch nie Gedanken drüber gemacht: Ist j-l mehrsprachig?

> Und jetzt bitte nicht mit "dann möchte ich die Jahre zur Volljährigkeit in Abhängigkeit des gewählten Landes einstellen können" antworten :-)

Hm ... Letztlich liefe es aber darauf hinaus. Weil ich die Info als solche für den Anwalt wirklich wichtig finde und sie eben auch in der Vorlagenerstellung eine Bedeutung bekommen kann.

Aber ich will mal nicht so sein: dann möchte ich die Jahre zur Volljährigkeit in Abhängigkeit des gewählten Landes der Installation UND als optionale zweite Angabe "minderjährig nach Heimatrecht!" über die eingestellte Staatsangehörigkeit einstellen können Das wird die Familienrechtler oder Erbrechtler freuen, wo es auch auf die Volljährigkeit nach dem Heimatland ankommen kann! :-P

**Comment by j-dimension** [comment]
> Ist j-l mehrsprachig?

Auf englischen Systemen startet es mit englischer Oberfläche. Zumindest zum Großteil, die Übersetzung ist nicht 100%ig vollständig. Ist aber auch nicht der Anspruch - ich mache zwar regelmäßig Installationen außerhalb Deutschlands, das sind dann aber i.d.R. deutsprachige Anwälte.

**Comment by stm9x9** [comment]
> Dabei das Alter bei verstorbenen Kontakten nach dem Tod nicht weiterzählen sondern mit einem (+) dahinter das Sterbealter anzeigen.

Ich hab den neuen Code eben nur kurz überflogen: Ist das mit drin? Das weitergezählte, hypothetische Alter des Toten ist eher nicht interessant, IMHO.

**Comment by j-dimension** [comment]
Aktuell steht in dem Fall nur "verstorben" im rechten oberen Bereich.
