### ISSUE TITLE
Speichern von Anlagen als Datei

### ISSUE THREAD

**Issue by Maz111111** [jlawyerorg/j-lawyer-org#816]
Ich habe gerade aus dem Mail Client mehrere Anhänge einer Mail als Datei (nicht in der Akte) speichern wollen. Das Verhalten ist aber immer gleich. Egal ob Mail oder beA Anhang und egal ob aus der Akte heraus oder direkt aus dem Client.
Ich habe alle mit STRG markiert und dann das Speichern als Datei über Rechtsklick eingeleitet.

1. Es sollte dann nicht mehr für jede Datei einzeln der Speicherort abgefragt werden, sondern alle gewählten Dateien in den einmal gewählten Ort gespeichert werden - zumindest habe ich dieses Verhalten der KSW erwartet

2. Wenn schon jedes mal gefragt wird, sollte der gewählte Speicherpfad erhalten bleiben - so zumindest meine Erwartung.

Ich habe leider nicht mitbekommen (da unerwartet), dass der Speicherpfad jedes mal zurückgesetzt wird und immer fleißig ok geklickt . ;)

**Comment by j-dimension** [comment]
Das Nachfragen lasse ich drin - es bietet gleich die Möglichkeit, die Dateien umzubenennen. 

Ich passe es aber so an, dass der zuerst gewählte Ordner automatisch vorselektiert ist.
