### ISSUE TITLE
Wiedervorlagen / Frist: angelegt am anzeigen

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#819]
![image](https://user-images.githubusercontent.com/29924198/86931474-6f6d8800-c138-11ea-853d-3232993c4918.png)

Um eine Frist inhaltlich einordnen zu können beim Angucken, ist es ab und an hilfreich, zu wissen, wann sie angelegt wurde (zb vor oder nach einer bestimmten Reaktion des Gerichts ...) Möglich entweder besser als eigene Spalte hinten oder notfalls auch als Tooltip.

**Comment by j-dimension** [comment]
wenn wirklich "ab und an", dann Aktenhistorie konsultieren.

**Comment by stm9x9** [comment]
naja, ab und an ist relativ. Eher öfter.

**Comment by Maz111111** [comment]
Das hat was mit #519 und auch mit #475 zu tun. #519 dürfte faktisch fast das gleiche sein.

**Comment by j-dimension** [comment]
In der Tat. Duplikat von #519 .
