### ISSUE TITLE
Aktenhistorie - suchen

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#820]
![image](https://user-images.githubusercontent.com/29924198/86931738-bbb8c800-c138-11ea-9db3-40b80f394fea.png)

Wenn man zb nachschauen muß, wer oder wann eine bestimmte Etikette erstellt oder eine Frist erledigt hat, dann ist es sehr hilfreich, wenn man in der Historie suchen kann und dann nur noch die passenden angezeigt bekommt. zb "Info an Mdt, erledigt" oder so.

**Comment by j-dimension** [comment]
Duplikat von #75
