### ISSUE TITLE
Dateiüberwachung temporärer Dokumente, wenn Prozessüberwachung nicht möglich (war: pdf-Bearbeitung wird nicht übernommen)

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#821]
Ich habe eine pdf-Datei in j-l. Doppelklick, geöffnet im Acrobat. Ich habe dann da ein paar Veränderungen im Dokument gemacht. Und abgespeichert, dann geschlossen.

Das Dokument in j-l wurde aber nicht verändert - die geänderte, temporäre lokale Datei nicht zurückübernommen.

im client.log steht nix

es gibt noch das Ticket https://github.com/jlawyerorg/j-lawyer-org/issues/652 - dieser Fehler kommt aktuell auch nicht mehr - dafür wird aber die signierte Datei auch nicht mehr in j-l übernommen :-(

**Comment by j-dimension** [comment]
Ist der Acrobat als "externe Anwendung" konfiguriert?

**Comment by stm9x9** [comment]
![image](https://user-images.githubusercontent.com/29924198/86978466-4a503800-c17f-11ea-8fba-c997d0c98228.png)

Was genau sollte da bei "Testen" passieren? Bei mir öffnet sich ein Datei-öffnen-Dialog.

**Comment by j-dimension** [comment]
Du kannst dort ein PDF auswählen und schauen ob die Anwendung korrekt startet.
http://www.j-lawyer.org/downloads/documentation/j-lawyer.org-UserGuide-de.html#__RefHeading__429_1146603382

**Comment by stm9x9** [comment]
ok. Das funktioniert. Aber es werden halt keine Änderungen mehr übernommen. zb Bearbeitungen, Kommentierungen von Ermittlungsakten oder aber qeS-Signaturen.

**Comment by j-dimension** [comment]
Müsstest mal schauen wie sich der Acrobat verhält. Du kannst unter "?" einen Dokumentmonitor öffnen. Solange das PDF offen ist, sollte dort ein Eintrag existieren. Verschwindet er direkt, funktioniert die Überwachung des Prozesses nicht. Passiert bspw. bei Anwendungen die nur einen Prozess starten und den immer "nachnutzen".

**Comment by stm9x9** [comment]
Da liegt offenbar des Pudels Kern:

Wenn ich Acrobat nicht offen habe und ein pdf aus j-l starte, dann erscheint und bleibt das in der Dokumentenliste. Änderungen im pdf werden übernommen. Beim Schließen verschwindet es nach etwa 4 Sekunden aus der Liste. 

Dafür ist hier auch das Signierungsproblem wieder da.

Wenn ich aber nur das Dokument schließe und den Acrobat offen lasse, dann bleibt es so lange in der Liste, bis ich auch das Programm Acrobat selber schließe.

Wenn ich hingegen Acrobat nicht schließe und stattdessen ein weiteres Dokument aus j-l öffne, dann wird mir auch dieses zusätzlich im Monitor angezeigt. Dafür verschwinden die angeblich noch offenen Dateien gar nicht mehr aus der Liste, auch wenn ich Acrobat selber schließe. Hier werden Änderungen übernommen.

Wenn ich aber erst ein lokales Dokument öffne und dann zusätzlich eines aus j-l,. dann verschwindet das gleich wieder aus dem Dokumenten-Monitor und Änderungen werden nicht übernommen.

**Comment by j-dimension** [comment]
externe Anwendungen / "Default" Launcher: lokales Verzeichnis nutzen, ohne Prozessüberwachung

**Comment by j-dimension** [comment]
Schliessen des Clients dürfte für diese Dokumente dann auch keine "noch offen" - Warnung generieren

**Comment by j-dimension** [comment]
Tests:
- [ ] Windows Native Launcher
- [ ] Windows Custom Launcher
- [ ] Linux Native Launcher
- [ ] Linux Custom Launcher
- [ ] macOS Native Launcher
- [ ] macOS Custom Launcher
