### ISSUE TITLE
Zeiterfassung

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-org#823]
Ich habe öfters Akten mit vereinbartem Zeithonorar - Jedem Vorgang liegt somit eine Zeit bei, die in das Formular Zeiterfassung eingetragen wird. Jedesmal muss man dran denken, das Formular öffnen und schließen. E-mail kommt - Formular suchen, Antwort versendet, Formular suchen, Anruf von Mdt. Zeitformular öffnen.... 

Einfacher wäre doch wenn im Hintergrund die Zeiterfassung wenn aktiviert mitlaufen würde und ich zu jedem Dokument einen Vermerk mit ggf. Beginn und Dauer hinterlegen könnte z.B Rechtsklick "Zeiterfassung". Und wenn ich einen Vorgang hätte, der nicht mit einer Datei einhergeht, könnte es bei aktivierter Zeiterfassung einen Button geben (z.B. neben dem Notizbutton), der in die Zeiterfassung einen Vermerk einträgt, was gearbeitet wurde und wie lange (und ggf. einen Eintrag als Zeitvermerk in der Akte erzeugt. Bei Bedarf drückt man auf einen weiteren Knopf und die Zeiterfassung ist fertig. ..

**Comment by j-dimension** [comment]
Duplikat von #58
