### ISSUE TITLE
Datumsformat individualisieren - ggf. neue Variablen

### ISSUE THREAD

**Issue by ReRo-G** [jlawyerorg/j-lawyer-org#827]
Das Thema betrifft das Datumsformat. Mit heutigem Stand (jl 1.12.0.9) exisiteren die variablen:

1. {{KURZDATUM}}, TT.MM.JJJ
2. {{LANGDATUM}}, Wochentag, TT.MM.JJJ

Zwecks besserer Lesbarkeit wäre eine individualisierung denkbar, vergleichbar evtl. mit jener, welche in Excel zur Verfügung steht. Dort führt "T. MMMM JJJJ" zum Ergebnis 14. Juli 2020. Ebenso führte dieses aber auch zum Ergebnis 4. Juli 2020, da der erste Zahl erst ab zehn erweitert wird, zuvor also keine Null vorangestellt wird (dafür wäre TT erforderlich).

Durch Einfürhung weiterer Variablen wären hier statische Ergebnisse möglich. Alternativ könnte die Datumsvariable auf lediglich eine reduziert und in den zentralen Einstellungen eine Möglichkeit zur Individualsierung implementiert werden (so wird es z.B. in anderen Softwares umgesetzt). Damit wären dann auch individulle Varianten möglich, z.B. TT-MM-JJ oder TT. MMM JJJJ (der Monat würde hier stets auf drei Buchstaben gekürzt).

Herzliche Grüße!
ReRo

**Comment by j-dimension** [comment]
Habe ich nun über das neu verfügbare Scripting umgesetzt, so hat der Nutzende volle Flexibilität:

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<html>
<head>
	
	<title></title>
	<meta name="generator" content="LibreOffice 6.4.7.2 (Linux)"/>
	<style type="text/css">
		@page { size: 21cm 29.7cm; margin: 2cm }
		td p { background: transparent }
		td p.western { font-family: "Liberation Sans", sans-serif }
		td p.cjk { font-size: 10pt }
		p { margin-bottom: 0.21cm; background: transparent; page-break-before: auto }
		p.western { font-family: "Liberation Sans", sans-serif; so-language: de-DE }
		p.cjk { font-size: 10pt }
		a:visited { color: #800000; so-language: zxx; text-decoration: underline }
		a:link { color: #000080; so-language: zxx; text-decoration: underline }
	</style>
</head>
<body lang="en-GB" link="#000080" vlink="#800000" dir="ltr"><p class="western" align="justify" style="margin-bottom: 0.5cm"><a name="__DdeLink__9434_1508882021"></a>
<font face="Verdana, sans-serif"><span lang="de-DE"><b>Datum / Zeit</b></span></font><font face="Verdana, sans-serif"><span lang="de-DE"><b>:
</b></span></font><font face="Verdana, sans-serif"><span lang="de-DE"><b>F</b></span></font><font face="Verdana, sans-serif"><span lang="de-DE"><b>unktion
</b></span></font><font face="Verdana, sans-serif"><span lang="de-DE"><b>DATUMZEIT</b></span></font></p>
<p class="western" align="justify" style="margin-bottom: 0.5cm; page-break-before: auto">
<font face="Verdana, sans-serif"><span lang="de-DE"><span style="font-weight: normal">Gibt
das aktuelle Datum und / oder die aktuelle Zeit im gewünschten
Format aus.</span></span></font></p>


Signatur | DATUMZEIT(Format)
-- | --
Parameter: Format | Format, 			in welchem Datum / Zeit ausgegeben werden sollen | "EEEEE, dd. MMMMM yyyy"
Rückgabewert: | Datum 			/ Zeit im angegebenen Format | Freitag, 11. Februar 2022


<p lang="de-DE" class="western" align="justify" style="margin-bottom: 0.5cm; page-break-before: auto">
<br/>
<br/>

</p>
<p lang="de-DE" class="western" align="justify" style="margin-bottom: 0.5cm; page-break-before: auto">
<font face="Verdana, sans-serif">Folgende Buchstaben können im
Format verwendet werden:</font></p>
<p lang="de-DE" class="western" align="justify" style="margin-bottom: 0cm; page-break-before: auto">
<font face="Verdana, sans-serif">y 	Jahr</font></p>
<p lang="de-DE" class="western" align="justify" style="margin-bottom: 0cm; page-break-before: auto">
<font face="Verdana, sans-serif">M 	Monat im Jahr</font></p>
<p lang="de-DE" class="western" align="justify" style="margin-bottom: 0cm; page-break-before: auto">
<font face="Verdana, sans-serif">w 	Woche im Jahr</font></p>
<p lang="de-DE" class="western" align="justify" style="margin-bottom: 0cm; page-break-before: auto">
<font face="Verdana, sans-serif">W 	Woche im Monat</font></p>
<p lang="de-DE" class="western" align="justify" style="margin-bottom: 0cm; page-break-before: auto">
<font face="Verdana, sans-serif">D 	Tag im Jahr</font></p>
<p lang="de-DE" class="western" align="justify" style="margin-bottom: 0cm; page-break-before: auto">
<font face="Verdana, sans-serif">d 	Tag im Monat</font></p>
<p lang="de-DE" class="western" align="justify" style="margin-bottom: 0cm; page-break-before: auto">
<font face="Verdana, sans-serif">E 	Name des Wochentages</font></p>
<p lang="de-DE" class="western" align="justify" style="margin-bottom: 0cm; page-break-before: auto">
<font face="Verdana, sans-serif">a 	am/pm</font></p>
<p lang="de-DE" class="western" align="justify" style="margin-bottom: 0cm; page-break-before: auto">
<font face="Verdana, sans-serif">H 	Stunde (0-23)</font></p>
<p lang="de-DE" class="western" align="justify" style="margin-bottom: 0cm; page-break-before: auto">
<font face="Verdana, sans-serif">k 	Stunde (1-24)</font></p>
<p lang="de-DE" class="western" align="justify" style="margin-bottom: 0cm; page-break-before: auto">
<font face="Verdana, sans-serif">K 	Stunde in am/pm (0-11)</font></p>
<p lang="de-DE" class="western" align="justify" style="margin-bottom: 0cm; page-break-before: auto">
<font face="Verdana, sans-serif">h 	Stunde in am/pm (0-12)</font></p>
<p lang="de-DE" class="western" align="justify" style="margin-bottom: 0cm; page-break-before: auto">
<font face="Verdana, sans-serif">m 	Minute</font></p>
<p lang="de-DE" class="western" align="justify" style="margin-bottom: 0cm; page-break-before: auto">
<font face="Verdana, sans-serif">s 	Sekunde</font></p>
<p lang="de-DE" class="western" align="justify" style="margin-bottom: 0cm; page-break-before: auto">
<font face="Verdana, sans-serif">z 	Zeitzone</font></p>
<p lang="de-DE" class="western" align="justify" style="margin-bottom: 0cm; page-break-before: auto">
<font face="Verdana, sans-serif">Z 	Zeitzone</font></p>
<p lang="de-DE" class="western" align="justify" style="margin-bottom: 0cm; page-break-before: auto">
<font face="Verdana, sans-serif">X 	Zeitzone</font></p>
<p lang="de-DE" class="western" align="justify" style="margin-bottom: 0.5cm; page-break-before: auto">
<br/>
<br/>

</p>
<p lang="de-DE" class="western" align="justify" style="margin-bottom: 0.5cm; page-break-before: auto">
<font face="Verdana, sans-serif">Beispiel: 14 Tage nach aktuellem
Datum</font></p>
<p lang="de-DE" class="western" align="justify" style="margin-bottom: 0.5cm; page-break-before: auto">
<font face="Verdana, sans-serif"><font size="2" style="font-size: 9pt">Als
Frist habe ich mir den [[SCRIPT:FRIST(KURZDATUM,&quot;14&quot;);]]
notiert.</font></font></p>
<p lang="de-DE" class="western" align="justify" style="margin-bottom: 0.5cm; page-break-before: auto">
<font face="Verdana, sans-serif">Beispiel: 10 Tage nach fixem Datum</font></p>
<p lang="de-DE" class="western" align="justify" style="margin-bottom: 0.5cm; page-break-before: auto">
<font face="Verdana, sans-serif"><font size="2" style="font-size: 9pt">Als
Frist habe ich mir den [[SCRIPT:FRIST(&quot;01.01.2022&quot;,&quot;10&quot;);]]
notiert.</font></font></p>
<p class="western" style="margin-bottom: 0cm; page-break-before: auto">
<font face="Verdana, sans-serif"><font size="3" style="font-size: 12pt"><span lang="de-DE"><span style="font-style: normal"><span style="font-weight: normal">Beispiel</span></span></span></font></font><font face="Verdana, sans-serif"><font size="3" style="font-size: 12pt"><span lang="de-DE"><span style="font-style: normal"><span style="font-weight: normal">:
Fr., 11.02.2022</span></span></span></font></font></p>
<p class="western" style="margin-bottom: 0cm; page-break-before: auto">
<br/>

</p>
<p lang="de-DE" class="western" style="margin-bottom: 0cm; page-break-before: auto">
<font face="Verdana, sans-serif"><font size="2" style="font-size: 9pt"><span style="font-style: normal"><span style="font-weight: normal">[[SCRIPT:DATUMZEIT(&quot;EEE,
dd.MM.yyyy&quot;);]]</span></span></font></font></p>
<p class="western" style="margin-bottom: 0cm; page-break-before: auto">
<br/>

</p>
<p class="western" style="margin-bottom: 0cm; page-break-before: auto">
<font size="3" style="font-size: 12pt"><font face="Verdana, sans-serif"><span lang="de-DE"><span style="font-style: normal"><span style="font-weight: normal">Beispiel</span></span></span></font><font face="Verdana, sans-serif"><span lang="de-DE"><span style="font-style: normal"><span style="font-weight: normal">:
</span></span></span></font><font face="Verdana, sans-serif"><span lang="de-DE"><span style="font-style: normal"><span style="font-weight: normal">Fr.,
11. Februar 2022 15:30</span></span></span></font></font></p>
<p class="western" style="margin-bottom: 0cm; page-break-before: auto">
<br/>

</p>
<p lang="de-DE" class="western" style="margin-bottom: 0cm; font-style: normal; font-weight: normal; page-break-before: auto">
<font face="Verdana, sans-serif"><font size="2" style="font-size: 9pt">[[SCRIPT:DATUMZEIT(&quot;EEE,
dd. MMMMM yyyy HH:mm&quot;);]]</font></font></p>
<p class="western" style="margin-bottom: 0cm; page-break-before: auto">
<br/>

</p>
<p class="western" style="margin-bottom: 0cm; page-break-before: auto">
<font size="3" style="font-size: 12pt"><font face="Verdana, sans-serif"><span lang="de-DE"><span style="font-style: normal"><span style="font-weight: normal">Beispiel</span></span></span></font><font face="Verdana, sans-serif"><span lang="de-DE"><span style="font-style: normal"><span style="font-weight: normal">:
</span></span></span></font><font face="Verdana, sans-serif"><span lang="de-DE"><span style="font-style: normal"><span style="font-weight: normal">Freitag,
11. Februar 2022</span></span></span></font></font></p>
<p class="western" style="margin-bottom: 0cm; page-break-before: auto">
<br/>

</p>
<p lang="de-DE" class="western" align="justify" style="margin-bottom: 0.5cm; font-style: normal; font-weight: normal; page-break-before: auto">
<font face="Verdana, sans-serif"><font size="2" style="font-size: 9pt">[[SCRIPT:DATUMZEIT(&quot;EEEEE,
dd. MMMMM yyyy&quot;);]]</font></font></p>
</body>
</html>

**Comment by ReRo-G** [comment]
Hallo Jens,

meine Vorfreude ist riesig!
Würde der 4. Februar so auch ohne vorstehende Null (04. Februar) ausgewiesen werden?

Dank und Gruß

Timm

**Comment by j-dimension** [comment]
@ReRo-G ja, ganz wie man mag. 

"EEEEE, dd. MMMMM yyyy" 
das "dd" führt dazu, dass führende Nullen dargestellt werden.
--> Freitag, 11. Februar 2022 sowie Freitag, 04. Februar 2022

"EEEEE, d. MMMMM yyyy"
das einfache "d" führt dazu, dass führende Nullen weggelassen werden. 
--> Freitag, 11. Februar 2022 sowie Freitag, 4. Februar 2022

**Comment by ReRo-G** [comment]
Traumhaft!

Schreib mir bitte wie ursprünglich besprochen eine Rechnung.

Gruß
Timm
