### ISSUE TITLE
Server-Auswahl merkt sich nicht unterschiedliche Ports und SSL ja/nein

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#832]
![image](https://user-images.githubusercontent.com/29924198/87585039-bc280480-c6de-11ea-84a3-338a3d671291.png)

Beschreibung: Wenn man an mehreren Servern arbeitet und dann die Liste der zuletzt genutzten hat, dann wird da nur der Name des Servers individuell gespeichert, nicht aber die anderen Angaben.

Problem: Nutzer nutzt für Kanzlei A den Server a.example mit den Ports 8080 und für Kanzlei B den Server b.example, wo aber aus Gründen des dortigen Netzwerks 8081 genutzt wird. Oder ein Server macht SSL ein andere nicht.

Lösung: für jeden Server in der Liste werden auch getrennt/individuell die Ports und SSL gespeichert und abgerufen bei der Auswahl des Servers.

**Comment by j-dimension** [comment]
Sinnvoll. 

Zwischenzeitlicher Workaround: http://www.j-lawyer.org/downloads/documentation/j-lawyer.org-UserGuide-de.html#__RefHeading___Toc2289_656293559

**Comment by j-dimension** [comment]
Umgesetzt via #1325
