### ISSUE TITLE
pdfs in der Größe "normalisieren"

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#834]
Aus gegebenem Anlaß - weil wieder ein Gericht eine übergroße Datei nicht (automatisiert) drucken konnte:

j-l braucht eine Funktion, um pdfs auf DIN A4 zu bringen. Also je nach dem proportional verkleinern oder vergrößern. Auch wenn beA / ERV wohl keine solche Formvorschrift kennen dürfte, sind offenbar etliche Gerichte, die noch ausdrucken, nicht in der Lage, übergroße pdfs auf einen A4-Drucker verkleinert auszudrucken. Solche Dateien werden einfach übergangen. Und solche Dateien ergeben sich leider im Kanzlei-Alltag immer wieder. zb wenn der Scanner die Seite nicht auf den mm genau als A4 erkennt oder wenn man Bilder / mit dem Handy gescannte Unterlagen des Mandanten in pdf umgewandelt hat.

Daher entweder als Funktion im Kontextmenü im Dateien-Reiter zum Ablegen einer normalisierten Version oder/und als Option beim Versenden via beA.

Dies hilft dann auch weiter zb bei einer möglichen Einbindung von letterxpress als Postversender. Denn der nimmt auch nur auf den mm korrekte A4s an. #54

**Comment by j-dimension** [comment]
Verstehe nicht ganz. Ein PDF hat ein Format (bspw. A4, US Letter, ...), eine Ausrichtung (Quer, Hoch), und Ränder.

Um was geht es hier?

Und kannst Du ein "schlechtes" und das selbe in einer "guten" A4-Variante anhängen?

Danke

**Comment by stm9x9** [comment]
Um die Größe, also 210 mm x 297 mm. 

Ich bekomme vom Gericht eingescannte Schreiben der Gegenseite, die vielleicht 210 mm x 300 mm groß sind. Oder 210 x 291.

Oder ich mache halt aus Fotos des Mandanten über die Acrobat-Funktion ein pdf. Das ist dann auf einmal 1'066,8 mm x 1'422,4 mm.

Ich muß mal gucken, ob ich was passendes aber unverfängliches finde.
