### ISSUE TITLE
SSH-Tunnel integrieren für angenehmere Remote Server Nutzung

### ISSUE THREAD

**Issue by PrinzTu** [jlawyerorg/j-lawyer-org#836]
Ein SSH Tunnel im Anmeldefenster, würde Putty oder ein Terminalfenster in macOS/ Linux  bei einer remote Installation sparen. Soweit ich weiß, geht das mit einem jcraft Package (BSD License) & Java recht einfach und zuverlässig.

vgl. auch hier https://www.digitalocean.com/community/questions/ssh-tunnel-using-java-client

**Comment by j-dimension** [comment]
Interessant! Habe jcraft sowieso schon eingebunden für Zugriff auf die j-lawyer.BOX. Schaue ich mir an.

**Comment by PrinzTu** [comment]
die Bibliothek wird auch in den JetBrains Produkten wie z.b. Datagrip oder IntelliJ genutzt.

**Comment by j-dimension** [comment]
https://www.ayoub.io/2016/06/29/using-jsch-for-ssh-port-forwarding-java.html

**Comment by j-dimension** [comment]
Ich konnte das gerade prototypisch in den j-lawyer.org Client einbauen und es funktioniert. 

Fragen:

- nutzt Du für das Aufbauen des Tunnels ein Passwort oder ein Schlüsselpaar?
- beide Informationen sind sehr vertraulich (privater Schlüssel als auch das Passwort). Müsste man entweder lokal speichern oder immer von Hand eingeben. Eine Möglichkeit wäre, das Passwort für den SSH-Tunnel mit dem Passwort des j-lawyer.org-Nutzers zu symmetrisch zu verschlüsseln und dann verschlüsselt am Arbeitsplatz abzulegen. Dann wäre das einzige Problem, dass bei Änderung des Passwortes erneut vom Nutzer eingegriffen werden müsste.

**Comment by PrinzTu** [comment]
Derzeit nutze ich ssh mit Passwort, wobei ein RSA Schlüssel wohl bessere wäre.
Für den Zugriff lege ich die Client-Benutzer auf dem Server ohne Bash Zugriff wie folgt an:

`sudo adduser -r -s /bin/nologin username` oder  `adduser subversion --shell=/bin/false --no-create-home`

Ich habe mal die Eingabemaske für den SSH Tunnel aus Jetbrain Datagrip beigefügt.
<img width="716" alt="Bildschirmfoto 2020-08-03 um 09 26 02" src="https://user-images.githubusercontent.com/20815927/89156691-63c08600-d56b-11ea-900a-4bd77e97c2f5.png">

**Comment by j-dimension** [comment]
Dann werde ich mich erstmal auf die passwortbasierte Variante konzentrieren.

**Comment by j-dimension** [comment]
![grafik](https://user-images.githubusercontent.com/3729754/91909877-4be53a80-ecae-11ea-96a3-8b083f845d80.png)

**Comment by stm9x9** [comment]
@PrinzTu gibt es da irgendwie eine Anleitung, was ich auf Serverseite machen muß?

**Comment by j-dimension** [comment]
@stm9x9 es wird lediglich ein SSH-Zugang mit Nutzername und Passwort benötigt. Das ist ausreichend um sich verschlüsselt zum j-lawyer.org-Server zu verbinden.

Sinvoll ist es allerdings, im Anschluss den Server noch an localhost zu binden, sodass er für andere gar nicht im Netz "sichtbar" ist.
