### ISSUE TITLE
AutoVorschlag für Dateinamen im Scan Eingang oder beim Anhänge speichern aus Mail

### ISSUE THREAD

**Issue by Maz111111** [jlawyerorg/j-lawyer-org#838]
Wäre es denkbar, dass man in der KSW als Anwender ein Namensschema hinterlegt - vielleicht sogar als Vorrat - welches beim Abspeichern von Dokumenten zu einer Akte in der Abfrage für den neuen Namen von der KSW vorgeschlagen wird.

Ich stelle mir vor, dass ein Hauptvorschlag vom User vorgegeben werden kann, der immer erstmal in dem Textfeld steht, dieser dann aber entweder von Hand oder durch aufklappen mit anderen - nachrangigen - Vorgaben ersetzt werden kann.

Mein Fall:
Mein Scanner gibt nur fest voreingestellte Namen für den Scan - z.B. 20200722_PE_001392.pdf.

Bei der Verschlagwortung beim Speichern zur Akte muss ich dies aber immer in die "j-lawyer Form" umändern - 2020-07-22_PE Schreiben vom 

Es wäre einfacher wenn es hier ein gewisses Maß an Automatisierung geben würde.

**Comment by j-dimension** [comment]
Würde es in einem ersten Schritt schon helfen, wenn das übliche Datumspräfix vorangestellt wird? Das wäre mit sehr wenig Aufwand verbunden.

**Comment by PBaumfalk** [comment]
Ja, bitte. Das Datumpräfix wäre super!

Mit freundlichen Grüßen / Kindly Regards

Patrick Baumfalk
Rechtsanwalt / Lawyer


Mobil:    +49 1525 53 04 194
E-Mail:   patrick.baumfalk@kanzlei-baumfalk.de


Baumfalk - Rechtsanwaltskanzlei
Hauptstr. 195
50169 Kerpen

Tel.: +49 2273 40 68 504
Fax: +49 2273 59 03 565

E-Mail: info@kanzlei-baumfalk.de
Web: www.kanzlei-baumfalk.de

**Comment by Maz111111** [comment]
Ja, dass würde selbstverständlich reichen. 

Wobei so ein kleiner Vorrat (z.B. Datum_PE Protokoll v. oder Datum_PE Beschluss v. etc.) die Sache noch weiter vereinfachen wird.

Aber fürs erste wäre das übliche Datumspräfix schon sehr sehr hilfreich.

Dankeschön

**Comment by stm9x9** [comment]
Wobei ich die Dateien aus einer beA-Nachricht eher nicht verändert würde. Dafür lieber dann doch - gibt ein Ticket dafür - mehr auf den EGVP/justix.xml-Anzeigenamen setzen und mittelfristig auch in j-l einen (unwichtiger werdenden) Dateinamen und einen sprechenden Anzeigenamen verwenden. Die meisten "meiner" Gerichte schreiben da inzwischen auch sinnvolle Sachen rein wie "PKH Beschluss vom 1.1.20" oder so.

**Comment by j-dimension** [comment]
@Maz111111 beim Speichern von Anhängen aus E-Mail wird bereits ein Präfix vorgeschlagen. Habe ich ein Szenario übersehen? Wenn ja, kannst Du es hier noch kurz beschreiben?

**Comment by Maz111111** [comment]
Nein da hast Du nix übersehen. Bei Mail ist schon alles schick.
Dankeschön
