### ISSUE TITLE
zu langer Dateiname beim Speichern einer Mail, wenn Verschlüsselung aktiviert

### ISSUE THREAD

**Issue by Maz111111** [jlawyerorg/j-lawyer-org#839]
![screen](https://user-images.githubusercontent.com/53520581/88321100-e8670500-cd1e-11ea-88eb-613c53cfd896.jpg)
Danach war die Mail zwar im gesendet ordner und vermutlich auch gesendet aber sie war nicht in der Akte gespeichert.

**Comment by j-dimension** [comment]
Es gibt an dieser Stelle eigentlich bereits einen Längencheck. Hast Du ein passendes client.log?

**Comment by j-dimension** [comment]
Danke für das Log. Konnte den Fehler nachvollziehen, wenn Verschlüsselung genutzt wird. Behebe ich umgehend.
