### ISSUE TITLE
automatisches Anlegen von Fristen

### ISSUE THREAD

**Issue by j-dimension** [jlawyerorg/j-lawyer-org#84]
welche Fristen sind das im Allgemeinen? (Bezeichnung, wieviele Tage/Wochen? in der Zukunft) 

    wann sollen die Fristen automatisch angelegt werden - bei Anlage der Akte?
    welche Werte (Bezeichnung, Zeit in der Zukunft) sollen individuell einstellbar sein?
    gibt es unterschiedliche "Standardfristen" zwischen Sachgebieten oder aufgrund eines anderen Unterscheidungskriteriums?

**Comment by stm9x9** [comment]
Ich finde den Begriff Wiedervorlagepläne gut. Weil ich denke, daß j-l da nicht sowas fest vorgeben sollte, sondern dem Anwender erlauben sollte, eigene Pläne zu erstellen und die dann über ein Auswahlfeld anzuwenden. Natürlich kann man "Standard"-Pläne als Hilfe und Anschauungsmaterial mit j-l mitbringen. Aber die sollten dann änderbar oder löschbar sein. Ich denke, diese Fristenpläne sind sehr anwalts-individuell.

Und ja die sollten vor- wie rückwärts Fristen anlegen können. Also ich mache die Wiederspruchsfrist und automatisch wird dann eine Woche vorher die Vorfrist eingetragen.

**Comment by RA-crm** [comment]
Ich bin von "festen" WVen nicht überzeugt. Ich arbeite mit WV Mustern und verfüge ggf extra. Bis auf die gerichtlichen Fristen habe ich in der Praxis häufig unterschiedliche Fristbeginne und -enden. Da ist es einfacher, das Datum und den Gegenstand der WV händisch zu notieren.
In soweit bin ich deutlich näher an stm9x9 dran.

Frage in die Runde: notiert ihr Vorfristen (VF) als Fristen oder WV?

**Comment by librelegal** [comment]
Ich notiere die als Vorfrist, damit die verschoben werden kann, falls sich ein Fristablauf ändert. Das wäre bei einer Wiedervorlage nicht der Fall, die auch andere Gründe haben kann

**Comment by stm9x9** [comment]
Dann wäre ein Typ Vorfrist, der automatisch in Abhängigkeit von einer Hauptfrist gesetzt und ggf sogar umgesetzt wirde, eine gute Idee?

**Comment by librelegal** [comment]
Ja. Solange es möglich ist, weitere eigene Fristen zu setzen

**Comment by j-dimension** [comment]
Für die Berechnung einer Monatsfrist siehe https://www.ra-kotz.de/monatsfrist.htm

**Comment by j-dimension** [comment]
Umsetzung via #36
