### ISSUE TITLE
Dokumentensuche mit Filter

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#840]
Word/LO-Dokumente sind ja meist im finalen Stadium in ein pdf umgewandelt - wenn man nun zb nur nach fertigen Dokumenten sucht, dann wäre ein Filter nach Dokumententyp ganz hilfreich. Filter nach Etiketten wäre auch ganz nett. zb könnte man ausgewählte Schriftsätze als "Musterbeispiel" etikettieren und wenn man dann wieder was zu Thema XY hat, dann sucht man XY mit Etikett "Musterbeispiel" und schon findet man einen Schriftsatz, den man für den neuen Fall adaptieren kann.

**Comment by j-dimension** [comment]
Geht es hier um die Suche in der Akte, oder über Volltextsuche?
