### ISSUE TITLE
j-l öffnet sich gleich "dreimal"

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#842]
Eben beim Start von j-l dauerte es erst gefühlt ewig, bis es nach Eingabe des Paßwortes weiterging und dann hatte ich drei Fenster offen. Zwei leere und eines normal. Als ich eines der leeren dann schloß, gingen alle Fenster zu.

client.log ist nicht sehr gesprächig:

> 2020-07-24 16:16:25,177 INFO  [com.jdimension.jlawyer.client.Main] Java: 1.8.0_232
2020-07-24 16:17:24,647 INFO  [com.jdimension.jlawyer.client.SplashThread] client startup in 23364ms
2020-07-24 16:17:24,649 INFO  [com.jdimension.jlawyer.client.SplashThread] client startup in 22121ms
2020-07-24 16:17:24,652 INFO  [com.jdimension.jlawyer.client.SplashThread] client startup in 22496ms

![image](https://user-images.githubusercontent.com/29924198/88401282-d1312180-cdc9-11ea-87cb-864e8389a38c.png)

**Comment by j-dimension** [comment]
Falls das reproduzierbar ist: mal den Client in der Kommandozeile starten

`java -jar j-lawyer-client.jar`

Dann sollten zusätzliche Ausschriften erscheinen.

**Comment by stm9x9** [comment]
Leider passiert das völlig unerwartet so alle zwei, drei Wochen mal :-/

**Comment by an-mus** [comment]
Hallo Jens, 
ich habe das sporadisch auch schon beobachtet (vor allem, wenn man bei etwas schwächeren Rechner, wenn man j-lawyer direkt während/nach dem booten startet). Ich konnte das jetzt reproduzieren, wenn ich den Client starte, während die CPU voll ausgelastet ist. Dann gehen wie beschrieben zwei oder drei Fenster auf. 
Die Ausgabe beim start über die Kommandozeile ist leider auch nicht ergiebiger:

log4j:WARN No appenders could be found for logger (org.jlawyer.bea.BeaWrapper).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
15:40:07,629 INFO  [Main] Java: 1.8.0_265
ERROR StatusLogger No Log4j 2 configuration file found. Using default configuration (logging only errors to the console), or user programmatically provided configurations. Set system property 'log4j2.debug' to show Log4j 2 internal initialization logging. See https://logging.apache.org/log4j/2.x/manual/configuration.html for instructions on how to configure Log4j 2
15:40:51,269 INFO  [SplashThread] client startup in 18826ms
15:40:51,322 INFO  [SplashThread] client startup in 19805ms
15:40:51,331 INFO  [SplashThread] client startup in 19292ms

**Comment by j-dimension** [comment]
> 15:40:51,269 INFO [SplashThread] client startup in 18826ms
> 15:40:51,322 INFO [SplashThread] client startup in 19805ms
> 15:40:51,331 INFO [SplashThread] client startup in 19292ms

Ist es möglich dass in diesen Fällen der Loginbutton mehrfach geklickt wurde? @stm9x9 @an-mus

**Comment by stm9x9** [comment]
Mehrfache Klicks würde ich eher verneinen. Ich tippe eigentlich immer mein Paßwort und dann Enter hinterher. Und das eigentlich nur einmal.

**Comment by stm9x9** [comment]
Allerdings merke ich gerade, das problematische Verhalten läßt sich in der Tat durch mehrfaches Klicken(!) auf den Button provozieren. Aber wie gesagt, ich glaube nicht, daß das bisher der Auslöser war.
