### ISSUE TITLE
"Akte suchen"-Dialoge mit den zuletzt geänderten Akten vorbelegen

### ISSUE THREAD

**Issue by PrinzTu** [jlawyerorg/j-lawyer-org#844]
neben der zunächst leeren Aktenansicht unter  `Akten -> suchen`

begegnet das gleiche Problem unnötiger Klicks bei der Zuordnung von E-Mails oder beA Nachrichten, dass zunächst eine leere Akte angezeigt wird.
Das verursacht beim Arbeiten viele unnötigen Klicks und suboptimalem UX.

Bei den E-Mails könnte man auch von der Suchfunktion von IMAP gebrauch machen und die E-Mail automatisch zuordnen (oder eine Zuordnung vorschlagen), wenn ein Aktenzeichen gefunden wurde. Das gleiche gilt für beA Nachrichten.

**Comment by j-dimension** [comment]
> bei der Zuordnung von E-Mails oder beA Nachrichten, dass zunächst eine leere Akte angezeigt wird.

Kannst du das näher ausführen - wo wird eine leere Akte angezeigt?

Im Allgemeinen gilt: ist die Absenderadresse / SafeID in der Adressverwaltung erfasst, so erhält man in der Seitenleiste des Posteingangs direkt die Akten angezeigt, in denen der Absender als Beteilgte(r) geführt wird. So kann man direkt zuordnen.



> von der Suchfunktion von IMAP gebrauch machen und die E-Mail automatisch zuordnen

Wie meinst Du das genau? Nach was soll im Postfach gesucht werden? Die E-Mail selbst hat ja kein Attribut für ein Aktenzeichen. Und alle Mails des Postfachs (zumindest im Posteingang) nach allen erfassten Aktenzeichen zu durchsuchen wird zu lange dauern.


Brauche mehr Input :-)

Danke

**Comment by PrinzTu** [comment]
Vielen Dank für den Hinweis mit den Absenderadressen.+

z.B. an der Stelle wird eine leere Maske angezeigt, anstatt die Akten mit den letzten Änderungen anzuzeigen. <img width="718" alt="Bildschirmfoto 2020-07-29 um 17 19 55" src="https://user-images.githubusercontent.com/20815927/88819035-babb0980-d1bf-11ea-8c1a-7a3c0571f17f.png">


Neben der Absenderadresse könnte man auch nach dem Kurzrubrum oder eigenen und fremden Az. für die Aktenvorschläge suchen.

**Comment by j-dimension** [comment]
Das Vorfüllen der Tabelle mach ich. 

Suche nach AZ oder Rubrum ist nicht so trivial wie es scheint - erstens ist das AZ / Rubrum dann sicher nur "Teil" des Betreffs / Textes, und zweitens können sich Anwender das AZ-Schema selbst konfigurieren. Ich müsste also das Schema nehmen, es in einen regulären Ausdruck umwandeln und dann suchen. Oder man müsste eine irgendwie geartete linguistische Aufbereitung machen, und etwas Statistik oder eine Mustererkennung dranpacken.

**Comment by PrinzTu** [comment]
Daran habe ich in der Tat nicht gedacht. Vllt. könnte man die letzten 500 Akten mit ID, Az eigen, Az. fremd & Kurzrubrum in ein Array laden, und dann im Betreff die Begriffe als Substring suchen. Ist zwar nicht die saubere Lösung, aber von der Performance dürfte man es kaum spüren. Klingt aber tatsächlich nicht nach drei Zeilen Code :(

**Comment by stm9x9** [comment]
kann man nicht einfach - wenn ich den Vorschlag überhaupt richtig verstehe - ein weiteres Suchfeld "Akz" hinplatzieren?

**Comment by Dickmaulruessler** [comment]
Das ist schon erledigt? 
Wirklich?

Ich finde unter "Akte suchen" keine Angabe oder Sortiermöglichkeit von "zuletzt geändert" bzw. "Änderungsdatum".

![klfösdäkadfä](https://user-images.githubusercontent.com/46451749/110247179-3ad1fa80-7f6b-11eb-9660-d6341540f72b.jpg)

Ja, das findet man natürlich auf dem Desktop. Aber das wäre sicherlich auch unter "Akte suchen" ein sehr sinnvolles Kriterium.

**Comment by j-dimension** [comment]
@Dickmaulruessler darum geht es in diesem Ticket nicht. Es geht um die Popups, bspw. bei Zuordnen eines Dokuments, siehe Screenshot von PrinzTu. 
Diese Dialoge zeigen nun automatisch die zuletzt geänderten Akten.

**Comment by Dickmaulruessler** [comment]
neues Ticket für für mein Anliegen?

**Comment by j-dimension** [comment]
Wäre wohl #921
