### ISSUE TITLE
neues Modul Reporting

### ISSUE THREAD

**Issue by j-dimension** [jlawyerorg/j-lawyer-org#85]
http://www.javabeat.net/2012/05/using-javafx-chart-api-to-add-charts-to-swing-applications/

​http://stackoverflow.com/questions/8374365/integrating-javafx-2-0-webview-into-a-swing-java-se-6-application

Mandanten

    Mandanten über die Zeit (monatlich, line)
    top mandanten, top 10 plus "sonstige" (pie)
    top mandanen trend 

Akten

    akten gesamt (monatlich, line)
    neue akten (monatlich, bar)
    offene akten (monatlich, bar)
    gesamt nach anwalt (pie)
    offen nach anwalt (pie)
    nach sachgebiet (pie) 

ControlsFX anschauen!

Styling ähnlich Nimbus: ​http://aquafx-project.com/documentation.html

**Comment by Dickmaulruessler** [comment]
Was genau ist mit dem Reporting-Modul gemeint? Was würde es leisten? Wie sehe es aus?
Ich kann mir das anhand obiger Angaben leider nicht konkret vorstellen...

**Comment by j-dimension** [comment]
Letztlich bspw. sowas wie oben in der Ticketbeschreibung genannt. Grafische und tabellarische Auswertungen, die bei der betriebswirtschaftlichen Führung des Unternehmens helfen. (pie=Tortendiagramm, bar=Balkendiagramm, line=Liniendiagramm)

**Comment by Dickmaulruessler** [comment]
Ah, Diagramme! Ja, cool!

Für mich und mein Tätigkeitsgebiet wäre das aber eher "Spielkram" - an dem ich aber **dennoch Spaß** hätte!

Für manche andere (insbesondere bei hohe Fallzahlen...) mag das auch wirklich sehr hilfreich sein. 

Nur eben nicht ständig sichtbar auf dem Desktop...

**Comment by Linkki2021** [comment]
Ist für mich persönlich eine Spielerei - wenn auch eine sehr schöne :)

Meines Erachtens ist der jeweilige Auswertungsbedarf sehr spezifisch, d.h. um einen breiten Nutzen für möglichst viele Nutzer zu erzielen muss so ein Ding sehr flexibel kombinierbare Auswertungen anbieten, was vermutlich wiederum relativ aufwendig ist. 

Ich persönlich bevorzuge zielgerichtete Datenbankabfragen, die ich in einem eigenen Modell auf meinen Bedarf hin weiterverarbeite.

**Comment by ReRo-G** [comment]
Gerade wollte ich ein Ticket erstellen um "basic-statistics" zu bewerben und habe dieses Ticket dabei gefunden.
Wir stehen immer wieder vor der Frage, wie viele Mandate in einem bestimmten Zeitraum angenommen wurden und können diese nur sehr umständlich beantworten.
Diagramme etc. halte ich auch für Spielerei, den Auswurf einer Tabelle oder auch nur eines Textdokuments hingegen zunächst für ausreichend.

Meinerseits wäre das auch ein Feature, welches ein gewisses Sponsoring erfahren könnte.

**Comment by j-dimension** [comment]
Erster Prototyp:

https://user-images.githubusercontent.com/3729754/214724723-c2631cd6-4376-4b9f-a6b8-d46155ae6062.mp4
