### ISSUE TITLE
[beA] Übersicht über angeschaute Nachrichten

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-org#851]
Es besteht ja wohl immer noch das Problem, dass die BEA-Schnittstelle für Drittprogramme nicht "durchmeldet", wenn eine Nachricht bereits angeschaut worden ist, weil eine entsprechende Funktion nicht in der API implementiert wurde. Aber solange das so ist, wäre es hilfreich, die betrachteten Dateien nach dem Öffnen andersfarbig zu unterlegen in J-Lawyer, bzw. die Möglichkeit zu schaffen, die Nachricht, die zwar schon betrachtet, aber als solche nicht als betrachtet angezeigt wird, farbig manuell zu hinterlegen - ähnlich wie bei einem TAG (so als workarround)...

**Comment by j-dimension** [comment]
Man könnte sie in einen anderen Ordner verschieben.

**Comment by Mucki526** [comment]
Das macht Sinn, wenn der Zähler im J-Lawyer dann auch korrigiert wird. Ich will sehen, ob seit meinem letzten Zugriff eine neue Nachricht kam. Im Moment scheucht mich nur eine Pushmail des BEA an mich....

**Comment by j-dimension** [comment]
Ich werde hier warten bis die BRAK die Schnittstellen erweitert hat, alles andere wäre nur halbgar. Die Nachrichten im Posteingang liegen datentechnisch nicht in der j-lawyer.org-Datenbank, somit kann dort kein Attribut hinterlegen, das anzeigt ob bereits gelesen wurde. Mit dem Neustart des Clients wäre also alles wieder ungelesen. 

Eine zweite Datenhalde für diese Attribute zu etablieren generiert die Notwendigkeit einer Synchronisation, was mir für dieses Feature zu viel Aufwand ist.
