### ISSUE TITLE
[beA] Anhänge speichern überschreibt ungefragt

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#855]
Wenn ich den Anhang einer beA-Nachricht als Datei speichere, überschreibt er bestehende Dateien gleichen Namens ungefragt.

**Comment by j-dimension** [comment]
Das bekomme ich nicht reproduziert, ich erhalte eine Fehlermeldung, dass bereits ein Dokument mit gleichem Namen existiert. 

Hast Du eine genaue Abfolge von Schritten für mich?

**Comment by j-dimension** [comment]
Gern wieder aufmachen, wenn reproduzierbar.

**Comment by stm9x9** [comment]
ich gehe in eine abgespeicherte bea-Datei (geht aber auch direkt im bea-Posteingang) und wähle für einen Anhang als Datei speichern.

![image](https://user-images.githubusercontent.com/29924198/96296676-eea01100-0fef-11eb-8e70-9b4c2b71715f.png)

![image](https://user-images.githubusercontent.com/29924198/96296719-04153b00-0ff0-11eb-9b8f-1bf34b622b7e.png)

Danach habe ich die Datei geöffnet und den Inhalt(!) durch "test" ersetzt.

Dann wieder als Datei speichern mit gleichem Namen. Es wird nicht abgefragt und die Datei wird überschrieben, es steht wieder der xml-Inhalt drin und nicht mehr "test".
