### ISSUE TITLE
[e-mail]-Versand z.T. ohne Speicherung in Akte

### ISSUE THREAD

**Issue by Stimpi72** [jlawyerorg/j-lawyer-org#856]
Ausgehende E-Mails können unter einem "Namen" in der jeweiligen Akte gespeichert werden.
Beim Versand öffnet sich hierzu ein Dialog mit einem Vorschlag für besagten "Namen" (Datum+Uhrzeit+Betreff).
Der Vorschlag kann dabei händisch überschrieben werden.
Wird nun versehentlich ein bereits in der Akte verwendeter "Name" eingesetzt, erfolgt eine Fehlermeldung.
Gleichzeitig wird die E-Mail NICHT in der Akte GESPEICHERT.
Allerdings wird die E-Mail ABER im Hintergrund VERSENDET, so dass man keine Kontrolle über das Geschehen hat.
 
Hier müsste wohl die Fehlermeldung nicht nur zum Abbruch des Vorgangs führen, sondern auch die Möglichkeit einer erneuten Änderung des "Namens" eröffnen (und zwar so lange, bis ein passender "Name" eingegeben wurde).

**Comment by j-dimension** [comment]
> Allerdings wird die E-Mail ABER im Hintergrund VERSENDET, so dass man keine Kontrolle über das Geschehen hat.

@Stimpi72  Die Mail ist dann im "Gesendet"-Ordner und kann von dort in die Akte kopiert werden, d.h. man hat weiterhin die Kontrolle.

Verbessern kann man das natürlich trotzdem.
