### ISSUE TITLE
lange Wartezeit beim erstellen neuer Dokumente aus .docx Vorlage

### ISSUE THREAD

**Issue by ms00st** [jlawyerorg/j-lawyer-org#857]
Guten Tag,

ich habe mir eine Dokumentenvorlage mit docx angelegt. Wenn ich innerhalb einer Akte eine ein Dokument aus dieser Vorlage erstellen möchte, hängt sich das gesamte Programm ca. 20 - 30 Sekunden auf. Ich glaube das liegt am laden der Platzhalter aus dem Dokument. Wenn ich innerhalb der Dokumentenübersicht zwischen den .odt und dem .docx Vorlagen wechsel, laden die .odt Vorlagen sehr schnell. Beim auswählen der .docx Vorlage hängt es sich jedes mal auf.

Testweise habe ich eine .docx Vorlage ohne Platzhalter erstellt. Diese läd Problemlos.

Vielen Dank für die Arbeit!

**Comment by ms00st** [comment]
Zudem ist mir noch aufgefallen, dass Platzhalter aus einer .doc Vorlage (Word 97-2003) überhaupt nicht erkannt werden.

**Comment by j-dimension** [comment]
Hallo @ms00st , auf diese Thematik wird in der Dokumentation hingewiesen:

http://www.j-lawyer.org/downloads/documentation/j-lawyer.org-UserGuide-de.html#__RefHeading___Toc5076_1542480051

> HINWEIS: aktuell wird von der Verwendung von Textfeldern in .docx-Vorlagen abgeraten. Verwendung vieler Textfelder führt zu sehr langen Zeiten bei der Ermittlung der in der Vorlage verwendeten Platzhalter sowie deren Ersetzung.

Die Anzahl der Platzhalter in der Vorlage spielt keine Rolle. Reduzieren Sie nach Möglichkeit die Nutzung von Textfeldern, bspw. durch Nutzung von Tabellen 1x1, deren Linien nicht dargestellt werden.

**Comment by j-dimension** [comment]
> Zudem ist mir noch aufgefallen, dass Platzhalter aus einer .doc Vorlage (Word 97-2003) überhaupt nicht erkannt werden.

Es werden nur docx unterstützt.

**Comment by ms00st** [comment]
Danke für die schnelle Antwort

**Comment by j-dimension** [comment]
Das Thema bzgl. der Textfelder ist bereits als Ticket erfasst, ich schliesse dieses daher als Duplikat.

https://github.com/jlawyerorg/j-lawyer-org/issues/737
