### ISSUE TITLE
[beA] Anmeldung schlägt fehl nach update - jlawyer box

### ISSUE THREAD

**Issue by Maz111111** [jlawyerorg/j-lawyer-org#863]
Also wenn ich nach dem update den client starte fängt dieser nicht wie gewohnt an, die beA Nachrichtan abzurufen. Bei Nutzer ist eingestellt automatische Einwahl mit SW Zertifikat.

Über den Browsre kann ich mich normal einwählen (am selben Computer).

JL sagt folgendes, wenn ich beA in der Seitenleiste anwähle und dann auf den Refresh Kreis klicke:

Als erstes kommt die Abfrage, wie ich mich anmelden möchte. Ich wähle sdas hinterlegte und funktionierende SW Zerti und dann kommt das:
![screen](https://user-images.githubusercontent.com/53520581/92330875-aa296900-f072-11ea-953a-8df48cdf717b.jpg)

Ich fahr jetzt erst mal nach hause

Nachfragen kann ich daher erst morgen im Lauf des Tages beantworten.

Viele Grüße
Martin

**Comment by j-dimension** [comment]
Dann bitte mal die Datei "config_schulung.jar" aus dem Unterverzeichnis "lib" des Clients an mich senden (per E-Mail). Danke!
Oder hier als Anhang, sofern GitHub das zulässt.

**Comment by j-dimension** [comment]
Ich  brauche die Datei nicht mehr, bitte den überarbeiteten 1.12.0.10-er Installer laufen lassen und hier Rückmeldung geben. Danke!
