### ISSUE TITLE
Warnmeldung fehlerhafte Versendung

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-org#864]
Auf der Weboberfläche des BEA erscheint ein Hinweis rechts oben nach dem Einloggen, wenn Nachrichten im Postausgang sind, die aufgrund eines Fehlers nicht versendet wurden. Das fehlt völlig in der J-Lawyer-Umgebung. Wäre aber hilfreich.

**Comment by j-dimension** [comment]
Bereits abgedeckt in #651  und #689
