### ISSUE TITLE
Anzeige neue Dokumente - Brainstorming - Nutzung der Anzeige der Weboberfläche

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-org#865]
Mein Verständis bisher ist, dass in der Schnittstelle für Hersteller von Drittsoftware die Funktion vergessen wurde, eine Anzeige für neue Dokumente zu implementieren, bzw. diese als gelesen zu merkieren, dass sie nicht mehr als neue ungelesene dokumente angezeigt werden. Wenn das mit dem aktuellen Update nicht vom Anbieter korrigiert worden ist, gibt es nicht eine Möglichkeit den Zähler aus der Weboberfläche zu nutzen??

**Comment by j-dimension** [comment]
Das ist korrekt, der gelesen/ungelesen Status ist über die Schnittstelle nicht zu ermitteln und auch nicht zu setzen. 

Und es gibt leider auch keine andere Möglichkeit / Notlösung :-(
