### ISSUE TITLE
BEA - Auswahl Instanzengericht

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-org#866]
Wenn man an das Gericht etwas schickt, muss man nochmals das Instanzengericht auswählen. Jetzt ist es so, dass wenn man zuvor z.B. an das Amtsgericht Konstanz etwas geschickt hat, und danach was ans Amtsgericht Singen schicken will, einem in der Auswahl des Instanzengerichts als Vorauswahl das vorher angeschriebene Amtsgericht Konstanz angeboten wird. Sinnvoller wäre es, wenn als Vorauswahl das angeschriebene Gericht erscheinen würde.

**Comment by j-dimension** [comment]
Bitte vor Erstellung eines Tickets immer die Suchfunktion nutzen, um zu prüfen ob es die Anfrage schon gibt. Sonst mache ich zu viel als Duplikat einfach zu und verliere Zeit.

Das Thema gibt es bereits: #394
