### ISSUE TITLE
[beA] kein Speichern in Akte bei fehlerhaftem Versand

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#877]
Ich habe eine Nachricht an ein Gericht versandt. Mit "in Akte speichern". Nach dem Versenden kam lange die Meldung "warten auf Laufzettel" oder so ähnlich.  für ne Minute oder so. Dann brach es ab und ich bekam einmal eine Fehlermeldung, daß da kein Laufzettel war (mit viel "Technik-Slang") und dann eine weitere Meldung "keine Zustellnachricht, bitte im bea-web gucken, ob es wirklich angekommen ist" o.ä.

So weit so gut. Aber dann war Ende und die Nachricht wurde - auch nicht ohne Laufzettel - nicht in die Akte gespeichert! Wenn nun aber die Nachricht versendet werden konnte und es nur beim Laufzettel hakte und ich in bea-web nun sehe, sie ist angekommen, dann würde ich die Nachricht schon gerne in der Akte haben. Eigentlich würde ich sie auf jeden Fall gerne da haben, um zu sehen, wann ich zumindest versucht habe, was zu versenden.

**Comment by j-dimension** [comment]
Muss schauen ob das Sinn ergibt. Für Nachrichten in der Akte kann man immer noch Aktionen ausführen, bspw. das Journal aktualisieren. Das setzt aber voraus dass die Nachricht eine beA-interne ID hat, was dann u.U. nicht geben wäre.

**Comment by j-dimension** [comment]
@stm9x9 hier wäre Feedback sehr willkommen.
