### ISSUE TITLE
[beA] j-l friert bei wiederholtem Versenden ein

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#878]
Ich weiß nicht, woher das kommt, aber ohne jede client oder serverseitige Änderung in letzter Zeit sehe ich gerade folgendes Verhalten:

ich versende was über beA (direkt aus der beA-Ansicht mit dem Umschlag-Button) mit in Akte speichern. Alles geht gut, aber wenn ich dann wieder auf den Umschlag drücke, dann kommt kein neues Versandfenster sondern j-l friert ein. Wenn ich zb das j-l-Fenster verkleinere und wieder vergrößere, dann sind die erweiterten Flächen alle schwarz. Der Button bleibt "gedrückt" leicht gegraut.

![image](https://user-images.githubusercontent.com/29924198/93827924-97b25080-fc6a-11ea-813b-20048f5f16a5.png)

Und schließen kann ich j-l auch nur noch über den Taskmanager. Aber danach will sich j-l nicht mehr an dem Server anmelden. im client.log ist nur:

2020-09-22 00:32:52,044 INFO  [com.jdimension.jlawyer.client.Main] Java: 1.8.0_232

und das Anmeldefenster bleibt stehen. 

Erst ein Neustart des Systems hilft weiter.

**Comment by j-dimension** [comment]
Welche Werte haben CPU-Auslastung und Memory des Clientprozesses, wenn das passiert?

Und passiert das jedes Mal, oder ab und zu?

**Comment by stm9x9** [comment]
Ich muß mich korrigieren:

Es ist wohl kein Client-Problem. Auch nach einem Neustart des Client-Systems blieb es bei dem Fehler und auch auf einem anderen Rechner geht kein Einloggen mehr.

also bin ich auf den Server gegangen.

sudo service j-lawyer-server stop 
[sudo] Passwort für debian:
Failed to stop j-lawyer-server.service: Die Wartezeit für die Verbindung ist abgelaufen
See system logs and 'systemctl status j-lawyer-server.service' for details.
Failed to get load state of j-lawyer-server.service: Die Wartezeit für die Verbindung ist abgelaufen

whoot?

nochmal sudo service j-lawyer-server stop und nun ist er gestoppt. Sofort ist bei beiden Rechnern die Einlog-Maske aufgetaut und zeigte "Anmeldedaten oder Parameter falsch".

sudo service j-lawyer-server start 

und ich sehe ihn in "top" aber beim Login mit dem Client kommt sofort   "Anmeldedaten oder Parameter falsch"!?

Nach ein paar Minuten habe ich nun den Server selber neu gestartet. Nach ca zwei Minuten konnte ich mich wieder einloggen.

> Und passiert das jedes Mal, oder ab und zu?

und es ist jetz 3 mal passiert vor heute noch nie. Es waren auch nur 6 Dateien a 200kb oder so. Und es wurde ja auch sauber zur Akte gespeichert.

**Comment by stm9x9** [comment]
Ich habe jetzt j-l auf zwei Rechnern offen. Auf einem habe ich mir selber was geschickt, mit kleinstem Anhang. Und wieder. Nix geht mehr.

Allerdings reichte diesmal ein stop start des Dienstes. Nach ca. 2 min konnte ich mich wieder einloggen.

jetzt habe ich es nochmal probiert, mit nur 30kb großem Anhang. Es gab keinerlei Probleme. Dafür habe ich jetzt beim nächsten Versuch mit 6MB seit über 5 Minuten "Speichern in Akte ..." vor mir!?

Und auf dem anderen Rechner bin ich auf Desktop gegangen und habe eine Akte angeklickt. Seitdem dort auch alles eingefroren.

Irgendwie scheinen Performance-Probleme auf dem Server voll auf alle angeschlossenen Clients durchzuschlagen?

Falls du irgendwelche Logfiles vom Server haben willst, sag mir bitte auch immer gleich, wo die liegen. Ich kann mir das nie merken.

**Comment by stm9x9** [comment]
jetzt hat es nach sudo service j-lawyer-server stop / start geschlagene 7 Minuten gedauert, bis ich mich wieder einloggen konnte.

Kann es sein, daß da irgendwas durch das Speichern in Akte im System passiert, was über ein stop / start hinaus weiterlebt und den Server immer noch zum stottern bringt?

**Comment by j-dimension** [comment]
Schick mir bitte das Server.log per Mail.

**Comment by j-dimension** [comment]
https://www.j-lawyer.org/?topic=wo-findet-man-die-fehlerprotokolle-des-j-lawyer-org-servers-und-clients

**Comment by j-dimension** [comment]
> jetzt hat es nach sudo service j-lawyer-server stop / start geschlagene 7 Minuten gedauert, bis ich mich wieder einloggen konnte.

Das hört sich sehr stark nach einem Problem Deines Hosters an. Bitte mal die Monitoringinfos prüfen (CPU-Auslastung zu diesem Zeitpunkt, ... ) und das server.log senden. Dann das Ticket gern wieder öffnen.
