### ISSUE TITLE
Versendung an Amtsgericht Hannover (govello-Adresse) scheitert, 

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-org#879]
Beim Versenden meldet das BEA "warten auf EGVP-Zettel". Irgendwann kommt rote Fehlermeldung "Nachricht ohne EGVP-Laufzettel, bitte prüfen.... " Versendung an andere Gerichte vom gleichen Tag hat schon funktioniert vom gleichen Rechner.... Neustart des Rechners hat nichts gebracht.  Die fehlerhafte Nachricht (-en (da mehrere Versuche)) wurde im BEA-Ausgang gespeichert. Die Nachricht konnte aber problemlos über die Funktion weiterleiten in der WEB-Oberfläche des BEA weitergeleitet / versendet werden. Das Problem lag also offensichtlich nicht beim Amtsgericht Hannover.....

**Comment by j-dimension** [comment]
Dann haben wahrscheinlich beA-Schnittstellenserver der BRAK zu lange für eine Antwort benötigt, bzw. der Intermediär für das Amtsgericht Hannover zu lange benötigt, um einen Laufzettel zu generieren. Genaueres kann ich sagen wenn ich das client.log habe.

**Comment by Mucki526** [comment]
Kommt per e-mail, weil upload nicht geht, falscher Typ, will die Dateien nicht umbenennen...

**Comment by j-dimension** [comment]
Ist das noch ein aktuelles Problem?
