### ISSUE TITLE
Akte anlegen, markierte Berechtigte gehen verloren 

### ISSUE THREAD

**Issue by iradraconis** [jlawyerorg/j-lawyer-org#880]
Wenn ich eine Akte anlege in der Reihenfolge: Kurzrubrum, Wegen, Sachgebiet, Anwalt, Sachbearbeiter, Gruppe, Berechtigte markieren, Akten Etikett setzen => dann verschwindet an dieser Stelle der Haken bei "Berechtigte". 

Client MacOs und Windows

**Comment by j-dimension** [comment]
Wird geprüft.

**Comment by j-dimension** [comment]
Behoben.

**Comment by iradraconis** [comment]
Das ging fix! Danke!
