### ISSUE TITLE
Akte anlegen => beim Speichern leert sich Maske

### ISSUE THREAD

**Issue by iradraconis** [jlawyerorg/j-lawyer-org#881]
Wenn ich eine Akte anlege in der Reihenfolge: Kurzrubrum, Wegen, Sachgebiet, und dann oben auf speichern klicke, leert sich die Maske komplett. Die Akte ist zwar gespeichert, aber ich muss sie über den Desktop oder die Aktensuche erneut aufrufen.

Client MacOs und Windows

**Comment by j-dimension** [comment]
Das ist in diesem Fall mehr Feature als Fehler, es dient dem Zweck, schnell und hintereinander mehrere Akten anzulegen.

Wenn man sowieso in der Akte bleiben möchte, warum dann "zwischenspeichern"?

**Comment by iradraconis** [comment]
Ah ok. Dachte speichern ist immer gut. Aber so macht es auch Sinn.

**Comment by stm9x9** [comment]
> Wenn man sowieso in der Akte bleiben möchte, warum dann "zwischenspeichern"?

weil man das IMHO aus Gewohnheit so macht. Man macht in Word auch ein Dokument auf und speichert es erstmal. Man will"die Akte sicher haben".

Das ist IMHO auch ein Duplikat, AFAIR hatte ich das schon mal als Ticket gebracht.
