### ISSUE TITLE
Desktopeinstellungen am Nutzer speichern

### ISSUE THREAD

**Issue by iradraconis** [jlawyerorg/j-lawyer-org#882]
Eventuell verstehe ich das Konzept an der Stelle falsch, aber müsste das "Abo" der Etiketten auf dem Desktop nicht user basiert gespeichert werden anstatt client basiert. Jeder user hat doch eigene Präferenzen. Bin mir gerade nicht sicher, ob das ein bug ist.

**Comment by j-dimension** [comment]
Für Arbeitsplatzwechsler wäre das in der Tat besser.
