### ISSUE TITLE
Warnung dass keine Wiedervorlage notiert, obwohl eine WV notiert ist

### ISSUE THREAD

**Issue by iradraconis** [jlawyerorg/j-lawyer-org#884]
Ich erhalte sporadisch die oben genannte Meldung beim Verlassen aus einer Akte.

**Comment by j-dimension** [comment]
Lässt sich das "sporadisch" noch eingrenzen? Unter welchen Bedingungen?

**Comment by j-dimension** [comment]
alt: Warnung, wenn keine offene WV oder die offene(n) WV in der Vergangenheit lagen
neu: Warnung, wenn keine offene WV, unabhängig von der Fälligkeit
