### ISSUE TITLE
Sortierung Liste der Beteiligten variiert. Sollte alphabetisch sein.

### ISSUE THREAD

**Issue by iradraconis** [jlawyerorg/j-lawyer-org#887]
Bei Erfassung der Beteiligten und Auswahl des Beteiligtentyps im Dropdown sind die jeweiligen Typen alphabetisch sortiert. Wo sie nicht alphabetisch sortiert sind, ist in dem Dialog zur Anlage von Beteiligtentypen und wenn bei dem Dialog "hinzufügen eines Beteiligten" der Beteiligte ausgewählt wird. Das führt dazu, dass man sich ständig verklickt, weil man eine andere Position in der Liste vermutet.

**Comment by j-dimension** [comment]
Erledigt
