### ISSUE TITLE
E-Mail Abruf Imap Konten langsam und immer voreingestellte Anzahl an abgerufenen Mails möglich

### ISSUE THREAD

**Issue by iradraconis** [jlawyerorg/j-lawyer-org#889]
Ich vermute, das ist nicht so trivial. Der Posteingang ruft bei mir immer die letzten 20 oder 50 .. je nach Einstellung .. Nachrichten ab. Das dauert. Kann der Client nicht im Hintergrund die Nachrichten abrufen und die Eingangsliste aktuell halten?

**Comment by j-dimension** [comment]
Duplikat von #136 und eingeplant für 1.14
