### ISSUE TITLE
Instant Messaging / Chat / Messenger / Kommentare

### ISSUE THREAD

**Issue by j-dimension** [jlawyerorg/j-lawyer-org#89]
Funktionalität:

- [ ] analog E-Mail-Postfächern: Signal als Eingangskanal konfigurieren, d.h. jeder Nutzer kann eigene Nummer nutzen, es könnte aber auch eine kanzleiweiter Nummer geben
- [ ] Nutzerverwaltung: Zugang zu Signal-Eingangskanälen
- [ ] Versand aus Akte: über Beteiligten eine Nachricht senden
- [ ] Versand aus Akte: ausgewählte Dokumente senden
- [ ] zentraler Eingang: eingehende Signal-Nachrichten darstellen, bei Eindeutigkeit Absender-Akte direkte / automatische Zuordnung, anderenfalls vom Nutzer zuordnen lassen
- [ ] Darstellung Signal-Konversation direkt an Adresse - aktenübergreifend
- [ ] Versand aus Adresse
- [ ] Popup / andere Notifizierung bei neuer Nachricht

technische Implementierung

- [ ] Messaging-Modul, sodass später weitere Messenger eingebunden werden können
- [ ] Signal-Protokoll implementieren: Registrieren, Session-Aufbau, Versand, Empfang
- [ ] Speichern von Nachrichten in der j-lawyer Datenbank

unklar: 

- Offline-Fähigkeit? Kann die Signal-API auch Nachrichten rückwirkend abrufen?
- Braucht man einen eigenen Signal-Server?

**Comment by Maz111111** [comment]
Kommt das noch in die 1.14? Wäre noch eine sehr tolle Erweiterung...die viele auch nutzen würden

Vorzimmer könnte mitteilen, dass Mandantschaft da ist oder irgend jemand um Rückruf bittet etc.

**Comment by stm9x9** [comment]
die 1.14 ist in der Endproduktion :-)

Aber ich sehe da noch ein paar Probleme für eine Einbindung in j-l.

da j-l aktuell nur je eine Akte offen haben kann, muß man ja als Workaround fürs öfter nötige parallele Arbeiten mindestens eine weitere Instanz offen haben. Dann kommt jede Nachricht doppelt (oder noch mehr) an!?

Ich könnte mir an der Stelle vorstellen, daß man zwar serverseitig das über j-l laufen läßt, für den User aber das nicht in den Client einbaut sondern ausnahmsweise einen weiteren reinen Messenger-Client ausgibt. Den startet man dann nur einmal pro Rechner.

**Comment by Maz111111** [comment]
Ich habe ja gar keine Vorstellung, wie diese Erweiterung im Ergebnis überhaupt geplant ist.

Vielleicht plant Jens das ja genauso, wie Du es beschreibst. Vielleicht meint er auch etwas völlig anderes. Die Beschreibung lässt da viel Spielraum .-)

Allerdings würde ich es für konsequent halten, dass die Message in jedem Client-Fenster erscheint, damit man die Nachricht unabhängig davon, in welchem Fenster man gerade arbeitet, auch sieht.

Ich würde - wenn ich den HellseherFaden mal weiter spinne - davon ausgehen, dass man die Nachricht quasi als ChatFenster einbindet z.B. in der Seitenleiste bei Mail und beA. Und man hat ja auch alle Mails in jedem ClientFenster zur Verfügung (beA nur wegen der Restriktionen beim Anmelden nicht).

Na mal abwarten....

**Comment by j-dimension** [comment]
Signal-Bot mit öffentlichen Servern: https://github.com/aaronetz/signal-bot

**Comment by j-dimension** [comment]
https://blog.0day.rocks/a-look-into-signals-encrypted-profiles-5491908186c1

**Comment by librelegal** [comment]
Teil der Version 2.5 ist nun auch das Instant messaging ("Neues Modul für Instant Messaging", https://www.j-lawyer.org/?p=5682). Wirkt sich das auf diesen issue aus?
