### ISSUE TITLE
Dockerized: Make mysql credentials subject to boot time config

### ISSUE THREAD

**Issue by Wurzelkoch** [jlawyerorg/j-lawyer-org#890]
I am trying to install jlawyer on a server that runs podman services.
On running run-jlawyer.sh, a podman script written to replace docker-compose.yaml, both containers start up, but immediatly after, i get: 
        ERROR 2005 (HY000): Unknown MySQL server host 'db' (2)
        MySQL is unavailable - sleeping.
I tracked down the second line to wildfly/startup.sh and noticed, that mysql host and port are hardcoded here. 
I understand that this is the host and port, jlawyer-srv uses to speak to jlawyer-db. On our system, we would need to reconfigure that, but any configuration gets overridden by the hardcoded values.

**Comment by j-dimension** [comment]
Our dockers mainly serve development and test purposes, and therefore do not provide full flexibility as required for productive setups.

You can find and alter the database host in standalone.xml:

https://github.com/jlawyerorg/j-lawyer-org/tree/master/docker/wildfly

In a running container you'll find it in wildfly /standalone / configuration

**Comment by Wurzelkoch** [comment]
If I reconfigure and rebuild the image to try and have my own production mode: Which branch should I use best? release or fixes/12.0? Or is master stable enough?

**Comment by j-dimension** [comment]
Suggest to use this tag: https://github.com/jlawyerorg/j-lawyer-org/releases/tag/1.12.0.8

**Comment by Wurzelkoch** [comment]
jlawyer-db container builds fine this way, but for server, j-lawyer-server.ear is missing. Do I need to build it first, before I pack it into the container?

**Comment by j-dimension** [comment]
That is indeed created by a build. You could extract it from one of the official docker images in the desired version.

**Comment by Wurzelkoch** [comment]
I got it from http://www.j-lawyer.org/downloads/j-lawyer-developer-quickstart/wildfly.tar.gz, hoping it would work, but getting it from the official docker images seems better.

BTW, after I get my instance of jlawyer to work and fill it with my files, I'd look into working on this issue and try if I can contribute something to the official repository.

**Comment by j-dimension** [comment]
The one from the developer quickstart is likely outdated. 

If you have a place for me to upload the official 1.12 .ear, I can provide it to you. It is too large to be attached here.

**Comment by Wurzelkoch** [comment]
Thanks, you could drop it here: https://cloud.0x90.space/s/obl78UNoo41reP3

**Comment by j-dimension** [comment]
Done

**Comment by j-dimension** [comment]
Feel free to re-open if there is still some relevance to this.
