### ISSUE TITLE
Adress- und Aktensuche: Suchanfrage trimmen

### ISSUE THREAD

**Issue by iradraconis** [jlawyerorg/j-lawyer-org#891]
Möchte ich einer Akte einen Beteiligten hinzufügen, kann ich die Schnellsuche dafür nutzen. Diese scheint aber nur 1 Suchbegriff zu nehmen. Gebe ich Vor- und Nachnamen ein, bleibt das Suchergebnis leer. Macht es schwieriger bei sehr vielen Müllers in einer Datenbank. Gilt auch für die normale Adresssuche. 

Ist zufällig ein Leerzeichen nach dem Eingegebenen Suchbegriff, schlägt die Suche ebenfalls fehl.

**Comment by j-dimension** [comment]
> Ist zufällig ein Leerzeichen nach dem Eingegebenen Suchbegriff, schlägt die Suche ebenfalls fehl.

Das kann ich kurzerhand erledigen, der andere Teil benötigt wesentlich mehr Arbeit. Falls das dringend ist, bitte als neues Ticket einstellen, da es nicht Teil der 1.13 werden wird und separat bearbeitet werden wird.

**Comment by iradraconis** [comment]
ok, habe ein separates Ticket dafür erstellt
