### ISSUE TITLE
klickbarer Bereich Dropdown-Menü bei Auswahl des Anwalts

### ISSUE THREAD

**Issue by iradraconis** [jlawyerorg/j-lawyer-org#893]
Lege ich eine Akte an und möchte "oben rechts" den Anwalt auswählen, ist das Feld für den Anwalt nur im unteren Bereich "klickbar", so dass das Menü zur weiteren Auswahl ausklappt. Die beiden Menüs darunter zeigen dieses Verhalten nicht und sind einfach zu klicken. 

Liegt der Unterschied darin, dass bei "Anwalt" auch eine Eingabe erfolgen kann? Hat die Möglichkeit der manuellen Eingabe den Zweck, dass ein Anwalt eingegeben werden kann, der nicht User ist, der also dem System nicht bekannt ist? Falls dem so ist, ist das jetzige Verhalten wahrscheinlich so gewollt und dieses Ticket mag geschlossen werden :)

**Comment by j-dimension** [comment]
>  Hat die Möglichkeit der manuellen Eingabe den Zweck, dass ein Anwalt eingegeben werden kann, der nicht User ist, der also dem System nicht bekannt ist?

So ist es. Believe it or not, es gibt Anwender / Kanzleien wo nur das Sekretariat mit der Software arbeitet und dem Anwalt / der Anwältin alles vorlegt. Daher ist das Feld ein Freitextfeld.

**Comment by iradraconis** [comment]
Gut, dann zu recht geschlossen..
