### ISSUE TITLE
[e-mail] Fehlermeldung „Fehler beim Öffnen der Nachricht: failed  to parse“

### ISSUE THREAD

**Issue by iradraconis** [jlawyerorg/j-lawyer-org#896]
Ich kann noch nicht festmachen, warum das bei einigen eMails kommt und bei anderen nicht.

**Comment by j-dimension** [comment]
Wenn das wieder passiert, bitte unmittelbar danach das client.log sichern und **per E-Mail** senden. 

https://www.j-lawyer.org/?topic=wo-findet-man-die-fehlerprotokolle-des-j-lawyer-org-servers-und-clients

**Comment by Maz111111** [comment]
dürfte ein Duplikat sein
siehe #680 und #439

**Comment by j-dimension** [comment]
> dürfte ein Duplikat sein

Ja, das wollte ich über das client.log verifizieren. Wenn, dann ist es bereits behoben und wird mit 1.13 bereitgestellt.

**Comment by iradraconis** [comment]
ich bekomme den Fehler mehrfach täglich. Habe soeben einen Screenshot und eine Log Datei per E-Mail übersandt

**Comment by j-dimension** [comment]
#680 wieder aufgemacht
