### ISSUE TITLE
Abonnierte Etiketten werden bei Clientstart mit steigender Etikettenanzahl nur teilweise selektiert

### ISSUE THREAD

**Issue by iradraconis** [jlawyerorg/j-lawyer-org#898]
so seit Tagen am Arbeitsplatz einer Mitarbeiterin. An meinem Arbeitsplatz tritt das nicht auf.

Client Log?

**Comment by j-dimension** [comment]
Welches Betriebssystem?

**Comment by iradraconis** [comment]
Siehe Titel des Tickets: Windows

**Comment by j-dimension** [comment]
Ah, sorry. 

Könnt Ihr bitte mal folgendes Vorgehen prüfen: 

- Etiketten-Abos nach Wunsch setzen
- Die Anwendung dann nicht per Fensterleiste oder über die Windows-Taskbar beenden, sondern ganz bewusst über Men ü "Datei" - "Beenden"
- Anwendung neu starten und Etiketten prüfen

Danke!

**Comment by iradraconis** [comment]
Ausprobiert: dasselbe Problem

**Comment by j-dimension** [comment]
Dann bitte mal händisch prüfen, ob die Einstellung nach dem Beenden des Clients korrekt gespeichert wurde: 

Die Einstellungen liegen in der Datei C:/Benutzer/<nutzer>/.j-lawyer-clienet/clientConfiguration.properties

Dort gibt es zwei Einträge  client.desktop.lastfiltertag und client.desktop.lastfilterdocumenttag

Mal schauen ob die Änderungen dort überhaupt ankommen. Und als Notlösung erstmal manuell eintragen. 

Ich schaue heute Abend nochmal in den Code.

```
client.desktop.lastfiltertag=Angebot 20 beauftragt\#\#\#\#\#Rechnung 00 Entwurf\#\#\#\#\#Rechnung 10 verschickt\#\#\#\#\#Rechnung 30 \u00FCberf\u00E4llig\#\#\#\#\#
client.desktop.lastfilterdocumenttag=todo\#\#\#\#\#
```

**Comment by j-dimension** [comment]
Problem erkannt und behoben. Es spielen hier eine Reihe von Randbedingungen eine Rolle. Der größte Einflussfaktor ist die Anzahl der Etiketten insgesamt und die Anzahl der davon selektierten. Mit steigender Anzahl wächst die Wahrscheinlichkeit, dass dieser Fehler auftritt.
