### ISSUE TITLE
IO Exception beim Mailversand mit Anhängen

### ISSUE THREAD

**Issue by Maz111111** [jlawyerorg/j-lawyer-org#903]
Aktuell sitze ich im HomeOffice und bin per VPN zur JL-Box in der Kanzlei verbunden.

Ich will Mails aus der KSW heraus an die Mandanten schicken.

Ohne Anhang kein Problem.

Mit Anhang dauert es gefühlte 100 Jahre.

Ab einer bestimmten Größe des Anhangs kommt folgende Fehlermeldung:
![ioexception](https://user-images.githubusercontent.com/53520581/95646774-106b3680-0acc-11eb-9b46-b6778ea80348.jpg)

Die kann dann nur mit ok bestätigt werden und dann ist nichts weiter geschehen. Also in der Akte ist nichts gespeichert und im Mailausgang ist auch nichts zu sehen.

Was habe ich bisher versucht:
Client neu gestartet

- per Fernsteuerung über VPN
Serverdienst neu gestartet
Box neu gestartet
Fritzbox in der Kanzlei neu gestartet

Habe die Mail mit dem Anhang (2,2 MB) soeben über den Webmailer meines Mailanbieters (Kasserver) erfolgreich senden können.

Auch wenn im Ergebnis der Fehler ggf. nicht über die KSW verursacht wird bzw. behoben werden kann, wäre dann eine aussagekräftigere Fehlermeldung besser.

Bis vorgestern lief alles unproblematisch.

**Comment by j-dimension** [comment]
Ich brauche das Client.log per Email bitte

**Comment by Maz111111** [comment]
Kann geschlossen werden.

Habe eben - als ich Dir die logs über den Webmailer senden wollte - festgestellt, dass mein upload extrem langsam ist.

Habe dann meine Fritzbox zu hause neu gestartet....und siehe da....es geht auf einmal wieder...ich denke ich muss die Box hier tauschen....

Ich fand es irgendwie abwägig, dass der Mailversand über meine Internetverbindung zu hause läuft, wenn ich per VPN zur Box verbunden bin.
