### ISSUE TITLE
Mails aus der KSW an gmx werden nicht von gmx angenommen

### ISSUE THREAD

**Issue by Maz111111** [jlawyerorg/j-lawyer-org#904]
Wenn ich versuche, aus der ksw mails an gmx empfänger zu senden (bei anderen Empfängern ist es noch nicht aufgefallen) werden diese wegen Sicherheitsbedenken nicht zugestellt.

Über Thunderbird oder den Webmailer geht es problemlos.

Ich erhalte folgenden Delivery report:

Reporting-MTA: dns; XXXXXXX.kasserver.com
X-Postfix-Queue-ID: xxxxxxxxxx
X-Postfix-Sender: XXXX; XXX@XXXX.de
Arrival-Date: Fri,  9 Oct 2020 13:07:26 +0200 (CEST)

Final-Recipient: XXXX; XX.XXX@gmx.net
Original-Recipient: XXXX;XX.XXX@gmx.net
Action: failed
Status: 5.0.0
Remote-MTA: dns; xxx.xxxxx.gmx.net
Diagnostic-Code: smtp; 554-Transaction failed 554-Reject due to policy
    restrictions. 554 For explanation visit
    https://www.gmx.net/mail/senderguidelines?ip=85.13.155.220&c=hi

Die "X"e sind von mir

**Comment by j-dimension** [comment]
Ein generelles Problem kann ich hier nicht ausmachen, an meine eigene GMX-Adresse werden Mails ausgeliefert. 

Ist das ein bleibendes, konsistentes Verhalten bei Dir?

**Comment by Maz111111** [comment]
Hmm...an meine eigene kann ich auch problemlos senden...ich hatte das Problem mit zwei Mandanten-GMX-Adressen.

Die eine ist die von diesem Issue mit der oben gezeigten automatisierten Antwort von GMX.

Kann es an besonderen Einstellungen in den Mail Accounts der Empfänger liegen?

**Comment by j-dimension** [comment]
Das weiß ich nicht. In der Antwort des Mailservers stand ein Link, wo die Situationen aufgeführt sind, in denen der GMX-Mailserver eine Nachricht ablehnen würde. Alle Kriterien wurden von mir geprüft und j-lawyer.org "verletzt" diese Kriterien nicht. 

Also ist entweder die Kriterienliste unvollständig, oder es gibt noch irgendwelche Einstellungen die der GMX-Nutzer machen kann, ggf. nur in deren kostenpflichtigen Angeboten.

**Comment by j-dimension** [comment]
Falls Du ein Postfach hast, mit dem man das reproduzieren kann, bitte nochmal melden. Eine Analysemöglichkeit könnte sein, die gesendete Mail der Akte zu entnehmen (die .eml), dann eine aus Thunderbird zu verschicken, auch diese zu speichern und dann beide zu vergleichen.

Bis dahin schließe ich das Ticket erstmal - ich weiß nicht was ich hier tun könnte.
