### ISSUE TITLE
Sortieren nach Wiedervorlage / Frist auf dem Desktop; Ausblenden einer Kategorie

### ISSUE THREAD

**Issue by iradraconis** [jlawyerorg/j-lawyer-org#909]
Siehe Titel. 

Ich würde mir auch bis zur Implementierung eines "echten" Kalenders sehr eine dritte Kategorie neben der Wiedervorlage und der Frist wünschen, damit Termine separat erfasst werden, und entsprechend eine Sortierung auf dem Desktop erfolgen könnte. Bestenfalls auch mit einer eigenen Farbe. 

Ich weiß, das Thema Termine gab es hier schon oft. Aber es ist eben auch so essenziell.

**Comment by RA-crm** [comment]
Ich hätte die Funktion der Sortierung noch etwas detaillierte gelöst. Etwa: 
Sotiere nach 
Datum, 
Akte,
Art (WV/Frist/Termin)
und - ganz wichtig - Bearbeiter

Das hätte den Charm, dass man sich auch die WV/Fristen/Termine von Mitarbeitern und Kollegen anschauen kann, falls die kruzfristig ausfallen, oder wenn man überlegen muss, wer noch weitere Aufgaben bekommt.

**Comment by j-dimension** [comment]
Ich mache erstmal die einfache Variante wie von @iradraconis beschrieben.

**Comment by j-dimension** [comment]
Schaut jetzt so aus:

![grafik](https://user-images.githubusercontent.com/3729754/120401119-924fee80-c33f-11eb-91b2-c18c3646b997.png)

**Comment by j-dimension** [comment]
(unten Tabs gebildet, ähnlich der Umsetzung bei den Etiketten)

**Comment by Dickmaulruessler** [comment]
> (unten Tabs gebildet, ähnlich der Umsetzung bei den Etiketten)

Super!

**Comment by Dickmaulruessler** [comment]
Hier bei WV / Fristen könnte ich mir die sehr hilfreichen Tabs auch oben vorstellen. 
Unten sind sie nach meinem Geschmack etwas "zu weit vom Geschehen" oben entfernt.
