### ISSUE TITLE
[beA] Nachrichten-Vorschaufenster zeigt Inhalt "alter" Akte

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#911]
Ich gehe in eine Akte, in Dokumente und klicke eines an. Dann wird mir rechts der Inhalt angezeigt. In diesem Fall eine bea-Nachricht aus der Akte NK-187....

Dann gehe ich auf Aktensuche in eine neue Akte, wieder auf Dokumente. Bevor ich ein Dokument anklicke, wird rechts immer noch der Inhalt aus der alten Akte angezeigt. Das kann auch ein pdf etc sein. Das irritiert. Besser wäre es, wenn das Vorschaufenster dann leer wäre.

![image](https://user-images.githubusercontent.com/29924198/96291066-daf0ac80-0fe7-11eb-9e40-98a697827194.png)

**Comment by stm9x9** [comment]
etwas ähnliches passiert beim Löschen einer Datei. Da ist dann zwar "Vorschau nicht verfügbar" aber unten sind noch die Etiketten der gelöschten Datei angezeigt.

![image](https://user-images.githubusercontent.com/29924198/96293695-72a3ca00-0feb-11eb-8e7f-5e69795433cb.png)

**Comment by j-dimension** [comment]
Scheint sich mit der Überarbeitung des ganzen Dokumenthandlings erledigt zu haben.
