### ISSUE TITLE
Anbindung Wordpress an Falldatenblätter

### ISSUE THREAD

**Issue by j-dimension** [jlawyerorg/j-lawyer-org#914]
- Wordpress Formularplugin
- j-lawyer.org-Erweiterung, welche diese API nutzt und die Daten in Falldatenblätter übernehmen kann

- [x] Prototyp
- [x] sichere Ablage API-Keys
- [x] Unterstützung für bis zu 5 Wordpress-Seiten
- [x] "sprechende" Platzhalter über Admin-Label in Gravity Forms
- [x] Unterstützung für Dropdowns
- [x] Dokumenten-Upload unterstützen
- [ ] Listenfelder / dynamische Listen über Platzhalter nutzbar machen: als Tabelle
- [ ] Listenfelder / dynamische Listen über Platzhalter nutzbar machen: im Fließtext
- [x] UI-Verbesserungen
- [ ] Dokumentation
- [x] Datumsangaben: aus drei Feldern in Gravity Forms 1 Feld im Falldatenblatt machen
- [x] Zeitangaben
- [x] Unterstützung für HTML-formatierten Text (vorerst keine Umsetzung, da nur lesender Zugriff / reines Anzeigefeld)
- [x] Unterstützung für Trennlinien
- [x] Löschen erfolgreich importierter Einträge aus Wordpress (vorerst keine Umsetzung)
- [x] zusätzliche / mehr Oberflächenelemente unterstützen

**Comment by j-dimension** [comment]
Einsatzszenarien:

1. Link an Mandanten
2. Mandant füllt aus
3. Kanzlei erhält E-Mail-Benachrichtigung 
4. Kanzlei öffnet Akte mit Falldatenblatt, drückt Datenübernahme --> Daten im Falldatenblatt

**Comment by PBaumfalk** [comment]
Assign me.

**Comment by j-dimension** [comment]
@PBaumfalk das geht erstmal an Dich für ein paar Stichpunkte, was Ihr alles damit machen wollt. Danke!

**Comment by j-dimension** [comment]
https://docassemble.org/
