### ISSUE TITLE
Vorschau.app auf MacOS als PDF Editor

### ISSUE THREAD

**Issue by PBaumfalk** [jlawyerorg/j-lawyer-org#915]
Die Vorschau auf dem Mac ist ein mächtiger OnBoard-PDF Editor. Leider speichert der aber die bearbeitete Datei nicht zurück. Wo werden die PDF Dateien denn auf dem Mac temporär gespeichert? Vielleicht finde ich dann die Lösung.

**Comment by j-dimension** [comment]
Das ist höchstwahrscheinlich über #821 im aktuellen Entwicklungsstand bereits umgesetzt. Werde ich vor Veröffentlichung nochmal explizit mit Preview.app testen.

**Comment by j-dimension** [comment]
Mit Version 1.13 getestet - läuft.

**Comment by PBaumfalk** [comment]
GEIL!

Mit freundlichen Grüßen / Kindly Regards

Patrick Baumfalk
Rechtsanwalt / Lawyer


Mobil:    +49 1525 53 04 194
E-Mail:   patrick.baumfalk@kanzlei-baumfalk.de


Baumfalk - Rechtsanwaltskanzlei
Hauptstr. 195
50169 Kerpen

Tel.: +49 2273 40 68 504
Fax: +49 2273 59 03 565

E-Mail: info@kanzlei-baumfalk.de
Web: www.kanzlei-baumfalk.de

Sent by Mobile
