### ISSUE TITLE
E-mail Versand - filelink für große Anlagen

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-org#918]
Nutze gerade mit thunderbird filelink für eine große pdf an Mandanten, weil es das im e-mail von j-lawyer (noch) nicht gibt. Wäre sinnvoll. Thunderbird bietet es bei großen Anlagen automatisch an...

**Comment by iradraconis** [comment]
Ich glaube das wird mit der Nextcloud Anbindung in den kommenden Updates auch möglich sein.

**Comment by j-dimension** [comment]
In der Tat. Hier das Ticket: https://github.com/jlawyerorg/j-lawyer-org/issues/809
