### ISSUE TITLE
Reiter über Dokumentenordner mit Gebührenrechnern / Gerichtskostenrechnern

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-org#919]
Ich erstelle Kostennoten und gebrauche fleißig den RVG Rechner. Da dieser Rechner - Geldverdienen - ja ein zentrales Element beim Abrechnen ist, könnte er als Reiter "Kostenrechner" neben "Dokument" im Ordner Dokumente sein und - wenn man ihn mit der Maus überfahre automatisch eine Liste der verfügbaren Gebührenrechner - Tabellen zur Auswahl zeigen. Das wäre für mich logischer als im jetzigen Reiter "Berechnungen", der weit weg ist am Rand. Wäre dem workflow m.E. dienlich.

**Comment by j-dimension** [comment]
Den Vorschlag lassen wir mit einfließen in #756, und die Umsetzung folgt dann hoffentlich in 1.14.
