### ISSUE TITLE
Featurewunsch: Anlagedatum der Akte 

### ISSUE THREAD

**Issue by iradraconis** [jlawyerorg/j-lawyer-org#920]
für interne Zwecke und auch um Akten zu finden, ist es enorm praktisch, wenn man die Suche nach "Anlagedatum" filtern könnte. Wenn in der Aktensuche ein weiterer Reiter "angelegt am" verfügbar wäre, liesse sich so schnell eine bestimmte Akte finden. Es müsste also das Anlagedatum irgendwo in der Akte auslesbar sein.

**Comment by iradraconis** [comment]
Kurze Ergänzung: das Anlagedatum ist übrigens auch als Platzhalter interessant, denn das Anlagedatum kann in Rechnungen als Beginn des Leistungszeitraums angegeben werden.

**Comment by Maz111111** [comment]
Bitte mit #493 verbinden und die 493 dann auch auf die Version 1.14 vorziehen

Danke :)

**Comment by GuidoBo** [comment]
Weitere **Felder zum Filtern**:

- **Anlage** (Zeitraum): 
  - "Datum von"
  - "Datum bis"
 - **Archiviert** (Zeitraum): 
  - "Datum von"
  - "Datum bis"
 
- **Angelegt von** (Personenauswahl)

- **Sachbearbeitung** (Personenauswahl)
- **Anwalt** (Personenauswahl)
- **Gruppe** (Gruppenauswahl) 

- mit Beteiligter Person (frei Suche: z.B., Landgericht Kiel)

- **zuletzt geändert** (Zeitraum): 
  - "Datum von"
  - "Datum bis"

und **angezeigte Spalten** ändern können

**Comment by j-dimension** [comment]
Werde versuchen die ursprüngliche Anfrage (hinsichtlich Anlagedatum) im Rahmen der 2.2 umzusetzen.

**Comment by j-dimension** [comment]
![grafik](https://user-images.githubusercontent.com/3729754/213588513-eb82bd8e-6c45-4bab-b814-cb821d97e2a8.png)
