### ISSUE TITLE
Altablage

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-org#926]
Ich weiss nicht, ob und wann das eingeplant ist.... Natürlich werden dem Grunde nach, wenn es richtig läuft, alle Vorgänge (Dokumente, e-mails, bea, Anlagen im Dokumentenordner Chronologisch abgelegt und gesichert. Dann wird die Akte archiviert. Aber mir wäre es wohler und auch leichter handelbar (Akte auf USB-Stick, Akte elektronisch an Kollegen übergeben, wenn man die Akte nach dem Abschluss komplett als PDF oder wenigstens ZIp-File "Rausschreiben" könnte. Vielleicht denke ich aber auch nur in archaischen Strukturen und traue einfach keiner Cloud bzw. Datenbankstruktur....

**Comment by j-dimension** [comment]
Dazu kannst Du den bestehenden HTML-Export nutzen. Oben in der Akte das Büroklammersymbol. Passt das?

**Comment by Mucki526** [comment]
Vielleicht was persönliches, ich kann mit dem HTML-Export nicht wirklich wasi m Zusammenhang mit Altablage abgewinnen. Für mich ist das der letzte Notnagel, wenn die Datenbank / j-lawyer-box versagt, quasi das Notrad am Porsche nach Reifenplatzer.....

Ich (wir) scannen im Moment nach Abschluss der Angelegenheit die gesamte Papierakte, damit auch alle Dokumente, die nicht unbedingt im J-Lawyer gelandet sind auch komplett in der Altablage vorhanden sind. 

Warum landet nicht alles sofort im Dokumentenordner? Das nicht noch alles rund läuft mit der elektronischen Akte und elektronischen Ablage der der Akte am Ende in einer Date liegt (bei uns) daran, dass die e-mail-Anbindung von J-lawyer aktuell (noch) recht rudimentär ist (dafür das wir zu 98 % per e-mail korrespondieren) und wir daher ganz oft mit Thunderbird (mit mehreren e-mail accounts arbeiten). Dann wird aus Zeitgründen nur die wichtigste Korrespondenz sofort in J-lawyer (über den Umweg Scanordner in die Dokumenten importiert, im übrigen nur Ausgedruckt und abgeheftet. Man kann hat blöderweise die e-mail aus Thunderbird nicht direkt in eine Datenbankakte schreiben, immer nur mit Umweg über den Scanordner (kein direkter Zugriff wie auf einen fileordner in windows).
Es liegt z.B. auch daran, dass ich keine direkte BEA-Nachricht, die ich ins Textfenster der BEA-Anwendung geschrieben habe (wie bei e-mail) bisher abspeichern oder direkt drucken kann, ich muss dann einen snapshot des Bildschirms machen. Ich muss Nachweis über die korrekte Versendung und Empfang führen (fristenkritisch, haftungsträchtig und genau da ist "Lücke" in der BEA-Anbindung.  (Aber das ist ja in Arbeit, ich finde das alles übrigens wie es ist super und bin dankbar für J-Lawyer (also meine "Kritikpunkte" nicht falsch verstehen), ich will nur verstanden wissen, wie es bei uns läuft incl. "workarounds". 

Ich möchte dem Grunde nach die Akte am Ende in eine Datei packen (und ggf. weiterleiten auf USB, SSD sichern) und in einem einzigen Viewer ansehen können. mit dem HTML-export brauche ich viele Viewer für Dokumente, für e-mails, für jpg, Zip-container, Tabellen... bei einem einzelnen PDF (durchsuchbares PDF bevorzugt) einen einzigen PDF-Viewer, wie er auf jedem Handy ist. 

Meine Vision für die Zukunft wäre - alles über j-lawyer in den Dokumentenordner incl. aller Nachweise und am Schluss alles auf Knopfdruck in ein PDF (notfalls zip) packen, wegsichern - "fire and forget" und mir Papierscanorgien sparen. Daneben existiert die archivierte Akte in der Datenbank weiter, falls ich sie nochmals aktivieren muss. .. Ist ja auf einem guten Weg.

**Comment by Maz111111** [comment]
Ich will Dir nicht in die Parade fahren...
Aber Mails aus Thunderbird schiebe ich per Drag and Drop in die Dokumente einer Akte in JL

Und die beA Nachrichten werden auch in der Akte unter Dokumente abgespeichert und sind sichtbar.

Wenn man natürlich alles als pdf haben will - was schon schön wäre, um alles in einem Viewer "durchblättern" zu können - wird es schwierig und ist tatsächlich nur über Druck und Scan zu bewerkstelligen.

Da wäre eine Automatisierung nicht schlecht.

**Comment by j-dimension** [comment]
Mails lassen sich - wie @Maz111111 schreibt - auch per Drag 'n Drop aus dem Thunderbird direkt in die Akte ziehen. beA-Nachrichten lassen sich mit der kommenden 1.13 als PDF anzeigen (und somit auch drucken). Und wie immer: ein Export i.S.d. Exports aus der beA-Weboberfläche ist mit der Schnittstelle der BRAK aktuell immer noch nicht realisierbar, d.h. das PDF und Drucken ist eine Komfortfunktion, mehr nicht.

**Comment by j-dimension** [comment]
Im Übrigen ist dieses Ticket in https://github.com/jlawyerorg/j-lawyer-org/issues/77 erfasst, ich schliesse daher an dieser Stelle.

**Comment by stm9x9** [comment]
> Ich muss Nachweis über die korrekte Versendung und Empfang führen (fristenkritisch, haftungsträchtig und genau da ist "Lücke" in der BEA-Anbindung.

JFTR: Seit geraumer Zeit wird beim Abspeichern der versendten bea-Nachricht in der Akte auch der Laufzettel mit dem sicheren Eingangsnachweis bei Gericht/Behörde mitgespeichert.
