### ISSUE TITLE
Falldatenblatt speichert nicht: Failed to read response

### ISSUE THREAD

**Issue by iradraconis** [jlawyerorg/j-lawyer-org#927]
Was tun? Log kommt per Mail.

**Comment by iradraconis** [comment]
Ergänzung: Daten werden in das Falldatenblatt Verkehrsrecht eingetragen, es wird zu Dokumente gewechselt und es soll ein Dokument erstellt werden. Oben genannte Fehlermeldung erscheint.

**Comment by j-dimension** [comment]
Das passiert, wenn Werte gespeichert werden sollen, die die Länge eines Datenbankfeldes übersteigen. Ist für die 1.13 bereits korrigiert.

Bei dringendem Bedarf kann es in einer Version 1.12 über einen Datenbankeingriff vorab korrigiert werden.

**Comment by iradraconis** [comment]
danke. finde ich irgendwo eine Anleitung dazu? Falls nein, warte ich ab. Ich habe bis zum Erscheinen der 1.13 sicherlich noch einige Falldatenblätter auszufüllen :)

**Comment by j-dimension** [comment]
Es müssen einige Kommandos auf der Datenbank ausgeführt werden. Bekommst du das hin? Dann poste ich hier die Befehle. 


Notfalls Fernwartung.

**Comment by iradraconis** [comment]
Ich meine, dass ich das wahrscheinlich hinbekommen würde. Aber deine Zeit ist sicher in der Fertigstellung der 1.13 besser investiert. Dann komme ich solange noch klar :)
