### ISSUE TITLE
e-mails drag n´drop

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-org#928]
Eigentlich praktisch e-mails aus einer anderen Anwendung direkt in den Dokumentenordner zu ziehen..... Problem - Ein e-mail -Verkehr hat bei uns oft den gleichen Betreff, dann müsste man die Datei vor dem Drag n´ Drop umbenennen oder zumindest beim ziehen statt einer Fehlermeldung eine Möglichkeit der Dateinamen - Neuvergabe haben. Ist aber nicht der Fall. Das Datum und die Uhrzeit der mail wird leider nicht ausgelesen bei Drag n´drop (aus Thunderbird in unserem Fall) wäre eine elegante Lösung, dann würden sich die Nachrichten evt. gleich richtig sortieren.....  So hilft es nicht wirklich...

**Comment by j-dimension** [comment]
Das Umbenennen ist mit #714 bereits gelöst. 

Das Extrahieren des Sendedatums, wenn E-Mails gedropped werden, ist in https://github.com/jlawyerorg/j-lawyer-org/issues/134 erfasst. 

Schliesse als Duplikat.

Bitte vorher die Suche bemühen - würde Zeit bei mir sparen, die ich nutzbringend einsetzen kann.
