### ISSUE TITLE
Feature request: Kurzrubrum als Teil des Aktenzeichens erlauben

### ISSUE THREAD

**Issue by Wurzelkoch** [jlawyerorg/j-lawyer-org#929]
Es wäre gut, beim Schema des Aktenzeichens auch einen Platzhalter vergeben zu können, der das Kurzrubrum einträgt.

**Comment by j-dimension** [comment]
Werden das nicht unhandlich lange Aktenzeichen?

**Comment by Wurzelkoch** [comment]
Stimmt, ich hab das "Kurzrubrum" nicht normgerecht verwendet. Aber ich mag es, ins Aktenzeichen noch ein Schlagwort einfügen zu können.

**Comment by j-dimension** [comment]
Kannst Du mir einen Hinweis geben, welche Art Information Du auf diese Art und Weise festhältst? Vielleicht lässt sich dann eine gute Lösung finden, die auch anderen Anwendern hilft.

**Comment by Wurzelkoch** [comment]
Manchmal der Vorwurf, manchmal ein Kurzwort zum angeblichen Tathergang (zB "füttern" bei dem Vorwurf der Mittäterschaft zu Störung öffentlicher Betriebe durch füttern einer angeketteten Persen, oder "tripod", wenn die Nötigung laut Akte durch auf einem Tripod sitzen geschehen sein soll) oder Thema ("castor")
(Ja, das sind alles politische Verfahren…)

**Comment by stm9x9** [comment]
Und das alles im Aktenzeichen? Ist genau dafür nicht das Feld wegen in der Akte? An welcher Stelle willst Du diese Kurzinfo denn gerne sehen?

**Comment by Dickmaulruessler** [comment]
Ich möchte den Kollegen nicht kritisieren, aber dennoch zu bedenken geben, dass ein Aktenzeichen für Außenstehende keinerlei Informationen zum Fall enthalten sollte - erst recht nicht in politischen Verfahren. 

Das Aktenzeichen wird mindestens dem Gericht und dem Finanzamt bekannt und jede inhaltliche Information ist da - auch berufsrechtlich - nicht unbedenklich.

**Comment by Wurzelkoch** [comment]
> Und das alles im Aktenzeichen? Ist genau dafür nicht das Feld wegen in der Akte? An welcher Stelle willst Du diese Kurzinfo denn gerne sehen?
Hm, vielleicht genügt das auch.

**Comment by j-dimension** [comment]
Dann mache ich hier erstmal zu.
