### ISSUE TITLE
Rechteverwaltung: Passwörter durch Nutzer selbst ändern lassen

### ISSUE THREAD

**Issue by Wurzelkoch** [jlawyerorg/j-lawyer-org#930]
Im Moment sind sehr viele Einstellungen nur durch den (einen?) Administrator änderbar. Das umfasst auch das jlawyer-Benutzerpasswort und die Maileinstellungen, was sehr unelegant ist. 
Könnte nicht Nichtadministratoris statt "Sie müssen Administrator sein, um diese Funktion zu nutzen" der Einstellungendialog nur für den eigenen Account angezeigt werden, so wie er dem Administrator für alle Accounts angezeigt wird?

**Comment by j-dimension** [comment]
Für Passwörter definitiv sinnvoll. 

>  durch den (einen?) Administrator

Man kann sich beliebig weitere Administratoren anlegen.

**Comment by Wurzelkoch** [comment]
> Man kann sich beliebig weitere Administratoren anlegen.

Wenn ich einem Account nachträglich Adminrechte gebe, braucht es dann einen Serviceneustart, damit das wirksam wird? Mehrfaches Ab- und wieder anmelden mit dem betreffenden Account hat bei mir nicht gereicht, erst am nächsten Tag hat es funktioniert (lokale Installation mit Rechner runtergefahren über Nacht).

**Comment by j-dimension** [comment]
Welches Betriebssystem?

**Comment by Wurzelkoch** [comment]
Debian 10

**Comment by Dickmaulruessler** [comment]
> 
> 
> [...] was sehr unelegant ist. [...]
> 

Ja, ich bin hier etwas off-topic, aber wiederum auch nicht: 

               Ich finde j-lawyer so was krass von ELEGANT und COOL !!!

Hey Leute, achtete mal auf eure Sprache! Ihr bekommt das hier alles für lau!
Danke Jens!

**Comment by j-dimension** [comment]
Eigenes Passwort ändern nun über die Nutzereinstellungen möglich.
