### ISSUE TITLE
[e-mail] Position der Splitpane speichern, Beteiligtenkategorien nach Auswahl einer Vorlage reduzieren

### ISSUE THREAD

**Issue by iradraconis** [jlawyerorg/j-lawyer-org#931]
siehe Screenshot. Der Teiler des Fensters führt ein Eigenleben. Wenn ich das Fenster verkleinere, Verschiebt sich der Teiler nicht "proportional" zum Rest der Fensterfläche. So wie der Teiler hier standardmäßig erscheint, kann ich die Beteiligten, die ich brauche (Dritte) nicht auswählen, sondern muss immer händisch den Teiler nach links verschieben. 

![screenshot Mail](https://user-images.githubusercontent.com/71747937/98678668-37cd5180-235f-11eb-861b-1ff07dd0eb8f.PNG)

**Comment by j-dimension** [comment]
1. Holy shit! Das sind eine Menge Beteiligtenkategorien.
2. Sobald Du eine Vorlage wählst, sollte die Matrix auf diejenigen Beteiligtenkategorien reduziert werden, die in der Vorlage genutzt sind.

**Comment by j-dimension** [comment]
Mittig positionieren wäre hier nicht sinnvoll, da nicht jeder so viele Kategorien nutzt. Muss anders gelöst werden.

**Comment by iradraconis** [comment]
zu 1: mir würden noch mehr einfallen :) 
zu 2: das funktioniert bei normalen Dokumenten aber nicht bei Emails.

**Comment by PBaumfalk** [comment]
Wie wäre es mit einem Popur-Fenster nach der Dokumentenauswahl?

Mit freundlichen Grüßen / Kindly Regards

Patrick Baumfalk
Rechtsanwalt / Lawyer


Mobil:    +49 1525 53 04 194
E-Mail:   patrick.baumfalk@kanzlei-baumfalk.de


Baumfalk - Rechtsanwaltskanzlei
Hauptstr. 195
50169 Kerpen

Tel.: +49 2273 40 68 504
Fax: +49 2273 59 03 565

E-Mail: info@kanzlei-baumfalk.de
Web: www.kanzlei-baumfalk.de

**Comment by iradraconis** [comment]
Kriegen wir vielleicht das „Splitpane speichern“ Feature noch in die 1.13 nachdem wir das jetzt auch im regulären „Dokument erstellen“-Dialog haben? Das wäre sehr hilfreich!!

**Comment by j-dimension** [comment]
@iradraconis meinst Du bei Versand E-Mail und beA?

**Comment by iradraconis** [comment]
> @iradraconis meinst Du bei Versand E-Mail und beA?

Genau, ich meinte jetzt primär Versand E-Mail. Im beA Versand Dialog hat es zumindest mich nie gestört.
