### ISSUE TITLE
[BUG] [beA] Nachrichten an Jobcenter erzeugen Fehler / vermutlich wegen Strukturdatensatz

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#933]
**Describe the bug / Fehlerbeschreibung**
(todo: a description of the bug / eine Beschreibung des Fehlers)

**To Reproduce / Schritte zum Nachvollziehen**

Ich habe eine Nachricht an ein Jobcenter verfaßt mit einer Datei als Anhang und sie versendet. Sie ist auch beim Intermediär angekommen, ich habe eine 0800er Rückmeldung im Laufzettel.

ca eine Stunde später bekomme ich eine eigenständige ERV-Nachricht vom Jobcenter:

![image](https://user-images.githubusercontent.com/29924198/98749924-071c0500-23bd-11eb-9791-311f7e298c95.png)

Ich habe die Nachricht, so wie sie im gesendet-Ordner liegt, aus beA-web weitergeleitet. Der Fehler kam wieder.
Ich habe dann den von j-l erzeugten Strukturdatensatz beim nächsten Weiterleiten aus beA-web gelöscht. Es kam kein Fehler mehr. Ich habe nochmal in beA-web weitergeleitet, diesmal den Datensatz gelöscht und einen von beA-web erzeugen lassen. Kein Fehler.

Meine Vermutung:

Entweder ist am Datensatz was kaputt oder aber - dahin tendiere ich - es ist nicht gut, daß der Datensatz einen Anzeige/Aliasnamen hat. Und zwar nicht im Strukturdatensatz selber, weil der sich AFAIK nicht selber "erwähnt" sondern direkt in der beA/ERV-Nachricht:

![image](https://user-images.githubusercontent.com/29924198/98750526-8100be00-23be-11eb-98a0-0e63e2fb2da6.png)

Dieselbe Datei mit Strukturdatensatz von j-l erzeugt, aber ans Gericht geschickt, erzeugt keinen Fehler.

 - j-lawyer.org Version: 1.12.0.10

**Comment by j-dimension** [comment]
Kannst Du nachfragen was das Problem ist? Würde ungern auf Verdacht Änderungen vornehmen. Letzlich würde es bedeuten dass die Anwendung NIE einen Alias für SDS senden dürfte.

**Comment by stm9x9** [comment]
> Kannst Du nachfragen was das Problem ist? Würde ungern auf Verdacht Änderungen vornehmen.

Ich weiß leider nicht wen, man kommt bei den Jobcentern ja an niemanden richtig ran :-( Aber ich werde es noch mal versuchen.

> Letzlich würde es bedeuten dass die Anwendung NIE einen Alias für SDS senden dürfte.

Das würde ich weniger als Problem denn als Lösung sehen. Ich habe noch keine Nachricht von einem Gericht bekommen, wo der SDS veraliast wurde.

**Comment by stm9x9** [comment]
ich habe mir noch mal so eine Nachricht vom Gericht angeschaut. Wie gesagt, in der Nachricht kein Alias für den SDS.

Aber auch für die Dateien, die im SDS einen Anzeigenamen bekommen haben, gibt es in der OSCI-Nachricht selber keinen alias.-Eintrag. Mir scheint, der wird von keinem genutzt sondern nur **in** dem SDS. 

![image](https://user-images.githubusercontent.com/29924198/101215937-efafff00-367e-11eb-9459-9658130c1ecb.png)

**Comment by j-dimension** [comment]
@stm9x9 ist das noch ein Thema?

**Comment by stm9x9** [comment]
Scheint erstmal zu funktionieren. Ich melde mich, falls nochmal was passiert.
