### ISSUE TITLE
[FEATURE] unbegrenzte Notizmöglichkeiten im Reiter "allgemein"

### ISSUE THREAD

**Issue by Maz111111** [jlawyerorg/j-lawyer-org#938]
Wie gestern in der Runde erfahren, hat das Notizfenster einer Akte im Reiter "allgemein" eine Begrenzung auf 2500 Zeichen.

Manche Akten dauern über Jahre und ich nutze dieses Fenster für jede Aktennotiz. Insbesondere Telefonnotizen, die ich aus Nachweisgründen nicht löschen kann.
Aber auch Notizen wie Mandant ist dann und dann im Urlaub etc.

Wenn es eine große und lange Akte ist, reichen 2500 Zeichen nicht aus.

**Comment by j-dimension** [comment]
"Unbegrenzt" ist in einer Datenbank nicht möglich, wenn das Feld durchsuchbar sein soll (bspw. wird das Notizfeld bei einer Aktensuche mit durchsucht). 

Ich kann aber das Limit anheben. 

Für mich wäre es interessant, welche fachlichen Informationen in diesem Umfang dort abgelegt werden, da das Feld ursprünglich nicht für solche Masseneingaben geplant war. Vielleicht finden wir hier eine bessere Lösung. Ich stelle mir auch die Bedienung (scrollen etc.) schon etwas unhandlich vor, bei der Datenmenge. Kannst Du das etwas näher ausführen?

Und: wie per Mail erwähnt, passe ich das gern auch spontan in Deiner Installation an. Bei Bedarf melden.

**Comment by Maz111111** [comment]
Also das wichtigste was ich in diesem Feld notieren lasse, sind tatsächlich Telefonnotizen von meiner Sekretärin. Die können mal kurz sein ("Mandant stimmt Vergleich zu") oder auch etwas länger. So habe ich einen Zeugen.

Im Termin notiere ich dort z.B. die Verfahrenswerte.

Also faktisch alles, was man sonst handschriftlich in die PapierAkte schreibt. Auch Urlaubszeiten von Mandanten.
Da hatte ich hier mal den Wunsch geäußert, dass man in jeder Akte irgendwie sowas wie ein Klebchen für die Urlaubsnotizen oder andere nur temporäre Infos anbringen könnte.
Da bekam ich ganz schön Gegenwind.
Also habe ich mir jetzt ein Etikett "ACHTUNG Mandant im Urlaub siehe Notiz" erstellt.

Sowas eben.

Wenn derartige Notizen nicht in das Feld sollen, wüsste ich nicht was sonst. 

Und das kann eben auch mal ganz schön viel werden. Habe ich jetzt nur in einer Akte. Aber da kommt es jetzt nicht darauf an, wieviele Akten das betrifft. Wenn es in einer nicht reicht, steht man eben in dieser einen recht hilflos da.

Schönes WE
Martin

**Comment by PBaumfalk** [comment]
Es müsste die Möglichkeit geben, dass die Notiz im Reiter allgemein als Notiz in der Akte zugespeichert wird. Dann kann man das auch nicht mehr löschen. Oder eine Revisionsfunktion, damit man das nachhalten kann. Quasi als Notizbuch zur Akte.
Das wäre eine Bombenfunktion.

Mit freundlichen Grüßen / Kindly Regards

Patrick Baumfalk
Rechtsanwalt / Lawyer


Mobil:    +49 1525 53 04 194
E-Mail:   patrick.baumfalk@kanzlei-baumfalk.de


Baumfalk - Rechtsanwaltskanzlei
Hauptstr. 195
50169 Kerpen

Tel.: +49 2273 40 68 504
Fax: +49 2273 59 03 565

E-Mail: info@kanzlei-baumfalk.de
Web: www.kanzlei-baumfalk.de

**Comment by j-dimension** [comment]
Ich fürchte ich verstehe es noch nicht so recht. 
 
Könnte man nicht für die beschriebenen Inhalte die vorhandene Notizfunktion nutzen? Die im Dokumente-Tab? Dann hätte man sogar einen zeitlichen Verlauf für jede einzelne Notiz, und könnte außerdem noch Etiketten dranpacken. 
Ggf. in Kombination mit dem kommenden Ordnersystem - alle Notizen in einen Ordner und man hat es schnell im Blick.

Die Notizen direkt auf der Einstiegsseite werden von den meisten Anwendern für Informationen genutzt, die tatsächlich direkt ins Auge fallen sollen, bspw. Abwesenheiten, oder andere Dinge die ein Sachbearbeiter einem möglichen anderen Bearbeiter der Akte direkt hinterlassen will.

**Comment by iradraconis** [comment]
> Ich fürchte ich verstehe es noch nicht so recht.
> 
> Könnte man nicht für die beschriebenen Inhalte die vorhandene Notizfunktion nutzen? Die im Dokumente-Tab? Dann hätte man sogar einen zeitlichen Verlauf für jede einzelne Notiz, und könnte außerdem noch Etiketten dranpacken.
> Ggf. in Kombination mit dem kommenden Ordnersystem - alle Notizen in einen Ordner und man hat es schnell im Blick.

Ich finde das so mehr als flexibel und genauso nutze ich es auch.


> Die Notizen direkt auf der Einstiegsseite werden von den meisten Anwendern für Informationen genutzt, die tatsächlich direkt ins Auge fallen sollen, bspw. Abwesenheiten, oder andere Dinge die ein Sachbearbeiter einem möglichen anderen Bearbeiter der Akte direkt hinterlassen will.

mache ich auch so.

**Comment by Maz111111** [comment]
Dann muss ich für jedes Telefonat mit Inhalten wie "Mandant stimmt Vergleich zu", "Mandant ist von bis im Urlaub" "Mandant wünscht Rückruf" etc. ein neues Dokument anlegen und abspeichern.
Ferner nimmt meine Mitarbeiterin in der Regel die Telefonnotizen auf und aktiviert dann das Aktenetikett "neue Anrufnotiz".
 Das heißt ich müsste jedes mal in die Dokumente gehen und ein Dok öffnen - was ich vorher natürlich erst noch identifizieren müsste (in Ordnerstruktur dann einfacher - allerdings muss ich das erst dem Personal beibiegen). Es funktioniert in der Regel nicht, nur die Vorschaufunktion zu verwenden, da die Notiz dort zu klein oder nur unformatiert dargestellt wird. Dann muss ich zurück in "Allgemein" und das Etikett löschen.
Die Notizfunktion unter Dokumente nutze ich tatsächlich für umfangreiche Gesprächsmitschriften.
Für den kurzen Firlefanz, den ich in der Papierakte per Hand einfach auf das letzte Blatt "klieren" würde, nutze ich das Feld unter allgemein. Jeweils mit Datum und Zeit.
Da man nie weiß, wofür man es nochmal braucht, will ich es auch nicht löschen - würde ich in der Papierakte ja auch nicht machen.
Und das kann dann eben auch mal voll werden.
Also ich werde das weiterhin vorn notieren.
Die Wahrscheinlichkeit, dass 2500 Zeichen nicht reichen, mag gering sein.
Aber aktuell habe ich eine Akte, die schon was länger läuft und in der eben nichts mehr hinzunotiert werden kann.
Dort würde ich jetzt gerne notieren, dass Mandant im KH ist und deshalb Termine erst nächstes Jahr stattfinden sollen. Außerdem hat Mandant über das WE um RR gebeten, was ich auch gern notieren würde.
Es passt aber nix mehr rein. Und das sind z.B. genau zwei solche Notizen, für die ein neues Dokument m.E. völlig überzogen wäre.
Jens hatte angeboten, mir für die eine Akte im laufenden Betrieb das Feld zu vergrößern - wäre erst mal ein Workaround.

Dabei kommt mir der Gedanke, ob man nicht einfach ein kleines Button an das Feld programmieren könnte z.B. "+" was bei jedem Klick 500 Zeichen zusätzlich in dieser Akte für das Feld freigibt.

Das wäre eine ausreichende Lösung.

Viele Grüße
Martin

**Comment by j-dimension** [comment]
Meine Kommentare bitte nicht als Kritik oder "Eingriff" in Eure Arbeitsabläufe verstehen. Ich versuche nur eine Lösung zu finden, die (1) für möglichst viele Anwender passt und (2) langfristig wartbar und betreibbar ist.

> Dann muss ich für jedes Telefonat mit Inhalten wie "Mandant stimmt Vergleich zu", "Mandant ist von bis im Urlaub" "Mandant wünscht Rückruf" etc. ein neues Dokument anlegen und abspeichern.

Das ist richtig, aber kaum mehr Aufwand - Du musst dazu nicht mal auf den Dokumente-Tab wechseln, man kann die Notiz direkt oben rechts anlegen, unabhängig davon in welchem Reiter man sich befindet.

Jedoch: für die genannten Beispiele "Mandant stimmt Vergleich zu", "Mandant ist von bis im Urlaub" würde ich tatsächlich das Notizfeld nutzen. Es geht mir mehr um das Nutzen für Masseninformationen - auch wenn diese über einen längeren Zeitraum und in kleinen "Häppchen" entstehen.



> Ferner nimmt meine Mitarbeiterin in der Regel die Telefonnotizen auf und aktiviert dann das Aktenetikett "neue Anrufnotiz".
> Das heißt ich müsste jedes mal in die Dokumente gehen und ein Dok öffnen - was ich vorher natürlich erst noch identifizieren müsste (in Ordnerstruktur dann einfacher - allerdings muss ich das erst dem Personal beibiegen).

Dazu könnte man auch ein Dokumentetikett an dem Notizdokument nutzen, und dieses Dokumetetikett auf dem Desktop abonnieren. Klickt man dort, landet man direkt in der Dokumentansicht, mit dem Dokument bereits vorselektiert und in der Vorschau dargestellt.



> Es funktioniert in der Regel nicht, nur die Vorschaufunktion zu verwenden, da die Notiz dort zu klein oder nur unformatiert dargestellt wird.

Die Notizendokumente sind extra so gemacht worden, dass man formatieren kann (was man in der Aktennotiz gar nicht kann). Hast Du einen Screenshot, der das "zu klein" oder "umformatiert" zeigt?



> Dann muss ich zurück in "Allgemein" und das Etikett löschen.

Dieser Schritt wäre sehr viel effizienter - nachdem Du über den Desktop direkt zum Dokument (nicht nur zur Akte) gesprungen bist, kannst Du anschließend auch gleich das Etikett an eben jenem Dokument entfernen.



> nutze ich das Feld unter allgemein. Jeweils mit Datum und Zeit.

...wobei Du Datum und Zeit manuell erfassen musst.



> Dort würde ich jetzt gerne notieren, dass Mandant im KH ist und deshalb Termine erst nächstes Jahr stattfinden sollen. Außerdem hat Mandant über das WE um RR gebeten, was ich auch gern notieren würde.
> Es passt aber nix mehr rein. Und das sind z.B. genau zwei solche Notizen, für die ein neues Dokument m.E. völlig überzogen wäre.

Wie gesagt, mir geht es nicht um die einzelnen Eintragungen, mehr um das Ansammeln großer Mengen in diesem Feld.




> Jens hatte angeboten, mir für die eine Akte im laufenden Betrieb das Feld zu vergrößern - wäre erst mal ein Workaround.
> Dabei kommt mir der Gedanke, ob man nicht einfach ein kleines Button an das Feld programmieren könnte z.B. "+" was bei jedem Klick 500 Zeichen zusätzlich in dieser Akte für das Feld freigibt.

Ich kann die Änderung für Deine Installation machen, kein Problem (in dem Fall bitte E-Mail an mich). Jedoch gibt es aus technischer Sicht ein Argument, warum ich es für die Allgemeinheit eher nicht machen möchte: Das Notizfeld wird mit jeder Aktensuche durchsucht. Die Suche wird unter Einbezug großer Freitextfelder langsam werden. Das ist so, als würde man im Windows Explorer eine Volltextsuche über Tausende Dokumente machen und erwarten das Ergebnis instant zu haben. 

Mein Bedenken ist, dass wir für den obigen Ansatz eine Lösung finden (durch Vergrößern des Feldes), und dann in einem Jahr ein Ticket hier landet, wo sich Anwender mit größeren Datenbeständen über eine quälend langsame Aktensuche beschweren. Dann bliebe mir nur: Feld wieder verkleinern (d.h. Funktionalität und Daten entfernen) oder aus der Suche ausschließen (d.h. Funktionalität entfernen) - beides wird auf Unmut stoßen. 


Wie bereits gesagt: es geht mir nicht um Ablehnung, sondern um Aufzeigen von Alternativen und Finden einer - aus allen Perspektiven betrachtet - guten und langfristigen Lösung. 
Im Moment sehe ich eine Lücke in der alternativen Arbeitsweise mit den Notizdokumenten: bei Anlage einer Notiz kann in diesem Dialog nicht direkt ein Dokumentetikett vergeben werden. Das wiederum kann ich sehr gern und mit gutem Gewissen einbauen.

**Comment by Maz111111** [comment]
Also ich verstehe nix als Kritik und nehm hier keinem irgendwas übel. Insofern alles gut und safe. Ich hoffe ja vielmehr, dass ich niemandem und insbesondere Dir nicht zu nahe trete. Freie Software und dann auch noch was fordern - das versuche ich zu vermeiden und es soll nicht mal im Ansatz danach klingen...hoffe ich... :-D

Die Gründe die gegen eine Erweiterung sprechen sind nachvollziehbar.
Insofern close
Kannst Du aber bitte kurz erklären, wie Du das meinst - vom Desktop direkt in die Dokumente springen.

Und nur zur Erklärung - Dokumentenetiketten nutze ich nicht - neue Anrufnotiz ist ein Aktenetikett, weil es eben in der Akte einen neuen Anruf gab.

Dokumentenetiketten wollte ich nutzen, um neue Doks mit Posteingang zu etikettieren. Aber ersten stehen die ohnehin immer ganz oben und zweitens ist es im Ergebnis eben doch die Akte, die das Etikett Posteingang braucht.

Im analogen Alltag wäre der Posteingang eben auf die Akte geheftet.

Insofern habe ich für mich noch keine effektive Verwendung für Dokumentenetiketten finden können.

Aber das war OffTopic.

Hier kann "close"

**Comment by j-dimension** [comment]
> Kannst Du aber bitte kurz erklären, wie Du das meinst - vom Desktop direkt in die Dokumente springen.

@Maz111111  Probier's mal aus - aktiviere mal ein Etikett an einem Dokument und abonniere das Etikett auf dem Desktop. Der Desktop zeigt dann nicht nur die Akte, sondern auch den Dokumentnamen mit dem "passenden" Etikett. Klickst Du dann darauf, landest Du nicht nur in der Akte, sondern wechselst automatisch in den Dokumente-Tab, wo auch bereits das Dokument selektiert und dessen Vorschau sichtbar ist.

**Comment by j-dimension** [comment]
Ich habe jetzt die #287 in die Version 1.14 vorgezogen und schließe hier. 

Und wie gesagt, mache ich auch gern die Datenbankänderung in Deiner Installation.

**Comment by Dickmaulruessler** [comment]
@Maz111111 Könnte es nicht auch ein Weg sein, dass du alles wie bisher machst und wenn das Notizfeld vorne voll ist, archivierst du das als eine große Notiz unter "Dokumente" und machst dir vorne einen entsprechenden Vermerk darüber?

@j-dimension

**Comment by Maz111111** [comment]
das ist ein super Idee und so werde ich es in Zukunft machen

@j-dimension Könnte das nicht automatisiert werden und die Problematik so lösen?
