### ISSUE TITLE
[FEATURE] offene Punkte Ordnerstruktur: Drag&Drop, Zuordnungsdialoge

### ISSUE THREAD

**Issue by j-dimension** [jlawyerorg/j-lawyer-org#939]
- [x] Dokumente per Drag & Drop Ordnern zuordnen
- [x] überall wo Dokumente einer Akte zugeordnet werden können, sollte es optional möglich sein, einen Ordner auszuwählen.

Der zweite Punkt verlängert aber den Arbeitsfluss - in einem ersten Schritt die Auswahl der Akte, dann die Auswahl des Ordners (denn die Struktur ist für jede Akte anders)

**Comment by iradraconis** [comment]
Vielleicht gehört das nicht hierhin: im LiveSystem habe ich gesehen, dass man nicht mehr mehrere Dateien durch Drücken von Shift auswählen kann. Die Auswahl erfolgt ausschließlich über die Häkchen neben den Dokumenten. Das bisherige Verhalten der Mehrfachauswahl ist deutlich effizienter und vermeidet unnötige Klicks, wovon ich ein großer Fan bin. Alles was Zeit spart ist gut. Vielleicht ist dieses Verhalten aber auch dem neuen Ordnersystem geschuldet und nicht anders umsetzbar. Wollte das nur anmerken :)

**Comment by j-dimension** [comment]
@iradraconis ich habe das gerade eingebaut und das Demosystem aktualisiert. Kannst Du mal drüberschauen?

**Comment by j-dimension** [comment]
Unterstützt werden Shift und Ctrl.

**Comment by iradraconis** [comment]
wow!! Genau so meinte ich das!! :)

**Comment by Maz111111** [comment]
Könnte man Zuordnung zur Akte und Zuordnung zu Ordner nicht in einem (größeren) Dialog abfrühstücken.

Datei zuordnen -> es öffnet sich EIN Fenster - oberer Bereich Akte wählen / eingeben - sobald Akte gewählt ist - erscheinen im unteren Bereich die möglichen Ordner, wobei oberste Oberordner standardmäßig vorgewählt ist.

**Comment by stm9x9** [comment]
hier mal eine Liste, wo das mit dem Ordner als Ziel relevant ist:

folgende Stellen fallen mir ein, die das betrifft:

**beA**

Rechtsklick, in Akte speichern
rechts Seitenfenster: Akte suchen und zuordnen bzw über eine der Akten da, vollständige Nachricht, nur Anhänge etc

**Scans**

**Emails**

**Drebis**

**Dokumentenliste einer Akte**

Rechtsklick, in andere Akte kopieren

**Comment by stm9x9** [comment]
Cool!

Kannst du auch schon zeigen, wie das aussieht, wenn man rechts schon vorgeschlagene Akten hat und davon eine nutzt?

**Comment by j-dimension** [comment]
> Kannst du auch schon zeigen, wie das aussieht, wenn man rechts schon vorgeschlagene Akten hat und davon eine nutzt?

Es erscheint dann der selbe Dialog, die Akte ist dann vorausgewählt, die Suchbuttons / Eingabefeld sind inaktiv.

**Comment by j-dimension** [comment]
Dokumente per Drag & Drop in Ordner einsortieren:


https://user-images.githubusercontent.com/3729754/112906039-cadb0e00-90eb-11eb-9296-492796496dcd.mp4

**Comment by j-dimension** [comment]
Dokumente per Drag & Drop aus externer Anwendung in Akte aufnehmen und in Ordner einsortieren:

https://user-images.githubusercontent.com/3729754/112909743-4dff6280-90f2-11eb-87bf-5914177f2cfa.mp4

**Comment by stm9x9** [comment]
ich habe noch zwei Stellen gefunden, wo das "in Ordner speichern" fehlt: Wenn man (Mail oder bea) eine Nachricht verschickt und diese "als Dokument in Akte" speichern läßt. Dann wird man zwar nach einem Namen für die Nachrichtendatei gefragt aber nicht nach dem gewünschten Ordner.
