### ISSUE TITLE
Farbe

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-org#94]
Wenn man einen Suchbefehl eingibt, werden manche Dateien ausgegraut. Wenn man dann diese Datei auswählt, erscheint die dunkelgrau Schrift auf Dunkelgrau. Bei der normalen Auswahl ohne aktivierte Suche ist die Schrift weiß auf blau. Weiß auf blau ist lesbar, Dunkelgrau auf dunkelblau nicht.... Individuelle manuelle Farbeinstellungen im J-Lawyer wäre eine Idee. Schrift hellgrau oder gelb einstellen statt dunkelgrau eine im konkreten Fall andere.

**Comment by j-dimension** [comment]
Mit neuem Design nicht mehr relevant.
