### ISSUE TITLE
[BUG] keine Rückkehr zu Akte aus dem Adressfeld, Fehler "null" - 1.13

### ISSUE THREAD

**Issue by iradraconis** [jlawyerorg/j-lawyer-org#941]
Der Zurückbutton oben links führt zu dieser Fehlermeldung

![Unbenannt](https://user-images.githubusercontent.com/71747937/99359734-cd149c80-28af-11eb-94f2-dcfa00bf4770.PNG)

**Comment by j-dimension** [comment]
Bitte mal das client.log bereitstellen - scheint irgendwie datenabhängig zu sein, da  ich es hier nicht nachgestellt bekomme.

**Comment by j-dimension** [comment]
Behoben.
