### ISSUE TITLE
[BUG] Vorschaufunktion von odt Dateien pixelig 1.13 (Windows Client)

### ISSUE THREAD

**Issue by iradraconis** [jlawyerorg/j-lawyer-org#942]
betrifft nicht PDF Dateien.

![Vorschaufehler](https://user-images.githubusercontent.com/71747937/99362187-74df9980-28b3-11eb-964e-e9d18bd2f142.PNG)

**Comment by j-dimension** [comment]
Ich fürchte das ist eine Wahl zwischen Pest und Cholera. Bisher wurde dort ein Textextrakt ohne Formatierung oder Layout angezeigt. Jetzt ist es eine Vorschau, die aber nur Layout / allgemeinen Dokumentaufbau anzeigt, der Text aber nicht zu erkennen ist. 

Die jetzige Vorschau ist ein automatisch von LibreOffice gespeicherter Preview. Eine "echte" Darstellung würde pro Dokument zu einer Wartezeit von mehreren Sekunden führen :-(

Die Frage ist also, welche der beiden möglichen Varianten einem mehr hilft.

**Comment by iradraconis** [comment]
dann bitte lieber so wie vorher :D so ist die Vorschau jedenfalls nicht zu gebrauchen. Zumindest nicht für mich.

**Comment by j-dimension** [comment]
Kannst Du das mal in der Mailingliste zur Diskussion stellen?

**Comment by j-dimension** [comment]
Ich habe jetzt erstmal eine kombinierte Variante eingebaut:

![grafik](https://user-images.githubusercontent.com/3729754/99441352-05e85c00-2918-11eb-99fa-0f1774ab24b3.png)

**Comment by Dickmaulruessler** [comment]
Einen **Screenshot** finde ich irgendwie "cool" - tatsächlichen Nutzen hat er bei (dort nicht lesbaren) Textdokumenten aber nicht. Ich erkenne die Absatze - mehr nicht. Einen tatächlichen Wert habe ich davon nicht. 
Der Screenshot raubt auch viele Platz zu Lasten des Textextraktes. 

Den unformatierten **Textextrakt** finde ich hingegen sehr sehr sinnvoll, um sich sehr **schnell** durch viele Docs durchzuklicken. Ohne Scrollen zeigt die Vorschau allerdings eigentlich nur den oberen Briefkopf. 
Würde es Sinn machen (und geht das überhaupt?), dass die Vorschau die Seite vom **unteren** Ende her zeigt? Das wäre, jedenfalls bei mir, der Bereich mit dem tatsächlichen Text der ersten Seite.

**Comment by j-dimension** [comment]
Man kann den Textbereich automatisch ans Ende scrollen. Ich bin mir aber unsicher, ob das andere Anwender auch sinnvoll finden. Sobald das Dokument mehrere Seiten hat, ist es wahrscheinlich wenig nützlich.

Evtl. könnte man ganz naiv rangehen - bspw. die ersten zehn Zeilen nach oben rausscrollen, in der Annahme dass dann der Briefkopf im nicht sichtbaren Bereich ist und der eigentliche Text dargestellt wird.

**Comment by Dickmaulruessler** [comment]
> 
> Sobald das Dokument mehrere Seiten hat, ist es wahrscheinlich wenig nützlich.
> 

Ja, das wäre wirklich nicht nützlich (und war von mir so auch nicht gemeint, sondern Beginnen am Ende der 1. Seite)

> Evtl. könnte man ganz naiv rangehen - bspw. die ersten zehn Zeilen nach oben rausscrollen, in der Annahme dass dann der Briefkopf im nicht sichtbaren Bereich ist und der eigentliche Text dargestellt wird.

Jo! Danke!

**Comment by j-dimension** [comment]
> > Evtl. könnte man ganz naiv rangehen - bspw. die ersten zehn Zeilen nach oben rausscrollen, in der Annahme dass dann der Briefkopf im nicht sichtbaren Bereich ist und der eigentliche Text dargestellt wird.
> 
> Jo! Danke!

Dann wäre ein Ticket ".odt-Vorschau: erste x Zeilen automatisch rausscrollen" o.ä. hilfreich. Danke!

**Comment by Dickmaulruessler** [comment]
Ah, supi. Mache ich morgen.
