### ISSUE TITLE
[FEATURE] Rechtsklick und Kontextmenü in Dateienliste

### ISSUE THREAD

**Issue by iradraconis** [jlawyerorg/j-lawyer-org#943]
Besteht Hoffnung, dass der Rechtsklick und das Kontextmenü zurückkehren?

**Comment by j-dimension** [comment]
Schaue mir mal an was das an Aufwand wäre.

**Comment by j-dimension** [comment]
Rechtsklick auf Checkbox, Dateiicon, Dateiname:
- wenn nichts selektiert: selektiere geklicktes Dokument, öffne Kontextmenü
- wenn bereits eine Selektion vorhanden: keine weitere Selektion, öffne Kontextmenü

**Comment by j-dimension** [comment]
Erledigt
