### ISSUE TITLE
[BUG] Fensterinhalt passt plötzlich nicht mehr in Fenster; Mac Client 1.13

### ISSUE THREAD

**Issue by iradraconis** [jlawyerorg/j-lawyer-org#944]
**Fehlerbeschreibung**
siehe Titel

**To Reproduce / Schritte zum Nachvollziehen**

1. Akte öffnen. 
2. Dokumente => Dokument öffnen
4. Wechsel auf Tab Beteiligte
5. Fehler stellt sich so dar: Fensterinhalt vergrößert sich und muss nun nach rechts gescrollt werden, bzw. passt nicht mehr in das Hauptfenster. Neustart des Clients erforderlich.

**Environment / verwendete Umgebung:**
 - OS / Betriebssystem: MacOS Catalina 10.15.7
 - j-lawyer.org Version: 1.13

client kommt wie immer per Mail.

**Comment by j-dimension** [comment]
Screenshot ist angekommen, danke, hilft aber leider nicht weiter. 

Ich brauche die exakte Situation, in welcher die Akte anfängt horizontal zu scrollen - ist es wirklich der Wechsel auf den Beteiligte-Tab?
Das bekomme ich nicht reproduziert. Ich bekomme aber einen solchen Effekt, wenn ich eine beA-Nachricht in der Vorschau anzeigen lassen.

Also idealerweise die konkrete Aktion benennen und dann einen Screenshot des gesamten Screens zur Verfügung stellen. Wenn ich dazu vorab eine Geheimhaltungsvereinbarung senden soll, bitte bescheid geben.

**Comment by iradraconis** [comment]
Auch auf Windows Client.

**Comment by j-dimension** [comment]
Ich meine das letzte Nacht gefunden zu haben, muss das aber heute erstmal noch testen, da die Korrektur an sehr "zentraler" Stelle ansetzt.

**Comment by iradraconis** [comment]
Ließ sich heute einfach auslösen indem man im Tab Dokumente auf das Etikettensymbol neben dem Suchfeld klickt oder nur ein Dokument anwählen löste das Problem aus (Windows) aktuelles Log File kommt per Mail.

**Comment by j-dimension** [comment]
Das lässt sich nur noch mit Einschränkungen für kleine Screens lösen. Bei 13 Zoll ist jetzt Schluss.

**Comment by iradraconis** [comment]
Kleiner wär auch doof :)
