### ISSUE TITLE
[BUG] [bea] j-l friert beim Versenden ein

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#946]
**Describe the bug / Fehlerbeschreibung**
(todo: a description of the bug / eine Beschreibung des Fehlers)

alles friert ein

**To Reproduce / Schritte zum Nachvollziehen**

neue bea-Nachricht
Anhang hochgeladen pdf, 400kb
Empfänger ausgewählt (Gericht, an das ich vor wenigen Minuten schon versendet hatte)
Aktenzeichen etc ausgefüllt.
als Dokument speichern: ja
Senden gedrückt.
Justizbehörden-Dialog, Gericht ausgewählt
alles friert ein

**Environment / verwendete Umgebung:**
 - OS / Betriebssystem: Win 10 Pro 64
 - j-lawyer.org Version: 1.13.0.1

**Additional context / Sonstiges**

logfile:

> 2020-11-18 02:58:13,792 INFO  [org.jlawyer.bea.BeaWrapper] Connecting to beA using endpoint https://ksw.bea-brak.de
> 2020-11-18 02:58:20,094 INFO  [de.governikus.bea.kswtoolkit.socketactions.impl.LoginUser] alias: Importiertes Zertifikat
> 2020-11-18 02:58:22,789 INFO  [de.governikus.bea.kswtoolkit.socketactions.impl.DecryptSessionKey] alias: Importiertes Zertifikat
> 2020-11-18 02:58:23,806 INFO  [org.jlawyer.bea.BeaWrapper] sender information is null - loading entire message
> 2020-11-18 02:58:24,077 INFO  [org.jlawyer.bea.BeaWrapper] sender information is null - loading entire message
> 2020-11-18 02:58:26,005 ERROR [com.jdimension.jlawyer.client.settings.UserSettings] Value is null when setting user properties with key client.desktop.onlymycases
> 2020-11-18 02:58:27,664 INFO  [org.jlawyer.bea.BeaWrapper] sender information is null - loading entire message
> 2020-11-18 02:58:27,770 ERROR [com.jdimension.jlawyer.client.settings.UserSettings] Value is null when setting user properties with key client.desktop.onlymyreviews
> 2020-11-18 02:58:27,858 INFO  [org.jlawyer.bea.BeaWrapper] sender information is null - loading entire message
> 2020-11-18 02:58:28,099 INFO  [org.jlawyer.bea.BeaWrapper] sender information is null - loading entire message
> 2020-11-18 02:58:29,169 INFO  [org.jlawyer.bea.BeaWrapper] sender information is null - loading entire message
> 2020-11-18 02:58:29,354 INFO  [org.jlawyer.bea.BeaWrapper] sender information is null - loading entire message
> 2020-11-18 02:58:29,581 INFO  [org.jlawyer.bea.BeaWrapper] sender information is null - loading entire message
> 2020-11-18 02:58:31,518 ERROR [com.jdimension.jlawyer.client.settings.UserSettings] Value is null when setting user properties with key client.desktop.lastfiltertag
> 2020-11-18 02:58:31,518 ERROR [com.jdimension.jlawyer.client.settings.UserSettings] Value is null when setting user properties with key client.desktop.lastfiltertag
> 2020-11-18 02:58:31,518 ERROR [com.jdimension.jlawyer.client.settings.UserSettings] Value is null when setting user properties with key client.desktop.lastfilterdocumenttag
> 2020-11-18 02:58:31,519 ERROR [com.jdimension.jlawyer.client.settings.UserSettings] Value is null when setting user properties with key client.desktop.lastfilterdocumenttag
> 2020-11-18 02:58:38,964 ERROR [com.jdimension.jlawyer.client.settings.UserSettings] Value is null when setting user properties with key client.desktop.onlymytagged
> 2020-11-18 02:58:39,361 ERROR [com.jdimension.jlawyer.client.settings.UserSettings] Value is null when setting user properties with key client.desktop.onlymycases
> 2020-11-18 02:58:43,695 ERROR [com.jdimension.jlawyer.client.settings.UserSettings] Value is null when setting user properties with key client.desktop.onlymyreviews
> 2020-11-18 02:58:52,803 ERROR [com.jdimension.jlawyer.client.settings.UserSettings] Value is null when setting user properties with key client.desktop.onlymycases
> 2020-11-18 02:58:59,666 ERROR [com.jdimension.jlawyer.client.settings.UserSettings] Value is null when setting user properties with key client.desktop.onlymyreviews
> 2020-11-18 02:59:04,518 ERROR [com.jdimension.jlawyer.client.settings.UserSettings] Value is null when setting user properties with key client.desktop.lastfiltertag
> 2020-11-18 02:59:04,518 ERROR [com.jdimension.jlawyer.client.settings.UserSettings] Value is null when setting user properties with key client.desktop.lastfiltertag
> 2020-11-18 02:59:04,518 ERROR [com.jdimension.jlawyer.client.settings.UserSettings] Value is null when setting user properties with key client.desktop.lastfilterdocumenttag
> 2020-11-18 02:59:04,518 ERROR [com.jdimension.jlawyer.client.settings.UserSettings] Value is null when setting user properties with key client.desktop.lastfilterdocumenttag
> 2020-11-18 02:59:06,195 ERROR [com.jdimension.jlawyer.client.settings.UserSettings] Value is null when setting user properties with key client.desktop.onlymytagged
> 2020-11-18 02:59:14,706 WARN  [org.jlawyer.bea.BeaWrapper] Unable to get identity govello-1260364804747-000194713 - trying via getRecipientData
> de.brak.bea.application.dto.soap.types5.BeaFault: 0207 - There is no data for given Identity, because of the IdentitySourceType!
> 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
> 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
> 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
> 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
> 	at com.sun.xml.internal.ws.fault.SOAPFaultBuilder.createException(SOAPFaultBuilder.java:135)
> 	at com.sun.xml.internal.ws.client.sei.StubHandler.readResponse(StubHandler.java:238)
> 	at com.sun.xml.internal.ws.db.DatabindingImpl.deserializeResponse(DatabindingImpl.java:189)
> 	at com.sun.xml.internal.ws.db.DatabindingImpl.deserializeResponse(DatabindingImpl.java:276)
> 	at com.sun.xml.internal.ws.client.sei.SyncMethodHandler.invoke(SyncMethodHandler.java:104)
> 	at com.sun.xml.internal.ws.client.sei.SyncMethodHandler.invoke(SyncMethodHandler.java:77)
> 	at com.sun.xml.internal.ws.client.sei.SEIStub.invoke(SEIStub.java:147)
> 	at com.sun.proxy.$Proxy65.getIdentityData(Unknown Source)
> 	at org.jlawyer.bea.BeaWrapper.getIdentity(BeaWrapper.java:1146)
> 	at com.jdimension.jlawyer.client.bea.BeaAccess.getIdentity(BeaAccess.java:983)
> 	at com.jdimension.jlawyer.client.bea.AddBeaRecipientSearchDialog.useSelection(AddBeaRecipientSearchDialog.java:861)
> 	at com.jdimension.jlawyer.client.bea.AddBeaRecipientSearchDialog.access$000(AddBeaRecipientSearchDialog.java:693)
> 	at com.jdimension.jlawyer.client.bea.AddBeaRecipientSearchDialog$1.actionPerformed(AddBeaRecipientSearchDialog.java:733)
> 	at javax.swing.SwingUtilities.notifyAction(SwingUtilities.java:1668)
> 	at javax.swing.JComponent.processKeyBinding(JComponent.java:2882)
> 	at javax.swing.JTable.processKeyBinding(JTable.java:5265)
> 	at javax.swing.JComponent.processKeyBindings(JComponent.java:2943)
> 	at javax.swing.JComponent.processKeyEvent(JComponent.java:2845)
> 	at java.awt.Component.processEvent(Component.java:6316)
> 	at java.awt.Container.processEvent(Container.java:2239)
> 	at java.awt.Component.dispatchEventImpl(Component.java:4889)
> 	at java.awt.Container.dispatchEventImpl(Container.java:2297)
> 	at java.awt.Component.dispatchEvent(Component.java:4711)
> 	at java.awt.KeyboardFocusManager.redispatchEvent(KeyboardFocusManager.java:1954)
> 	at java.awt.DefaultKeyboardFocusManager.dispatchKeyEvent(DefaultKeyboardFocusManager.java:834)
> 	at java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(DefaultKeyboardFocusManager.java:1102)
> 	at java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:973)
> 	at java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:799)
> 	at java.awt.Component.dispatchEventImpl(Component.java:4760)
> 	at java.awt.Container.dispatchEventImpl(Container.java:2297)
> 	at java.awt.Window.dispatchEventImpl(Window.java:2746)
> 	at java.awt.Component.dispatchEvent(Component.java:4711)
> 	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
> 	at java.awt.EventQueue.access$500(EventQueue.java:97)
> 	at java.awt.EventQueue$3.run(EventQueue.java:709)
> 	at java.awt.EventQueue$3.run(EventQueue.java:703)
> 	at java.security.AccessController.doPrivileged(Native Method)
> 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
> 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
> 	at java.awt.EventQueue$4.run(EventQueue.java:733)
> 	at java.awt.EventQueue$4.run(EventQueue.java:731)
> 	at java.security.AccessController.doPrivileged(Native Method)
> 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
> 	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
> 	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
> 	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
> 	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:109)
> 	at java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:190)
> 	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:235)
> 	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:233)
> 	at java.security.AccessController.doPrivileged(Native Method)
> 	at java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:233)
> 	at java.awt.Dialog.show(Dialog.java:1084)
> 	at java.awt.Component.show(Component.java:1671)
> 	at java.awt.Component.setVisible(Component.java:1623)
> 	at java.awt.Window.setVisible(Window.java:1014)
> 	at java.awt.Dialog.setVisible(Dialog.java:1005)
> 	at com.jdimension.jlawyer.client.bea.SendBeaMessageDialog.mnuSearchRecipientActionPerformed(SendBeaMessageDialog.java:2068)
> 	at com.jdimension.jlawyer.client.bea.SendBeaMessageDialog.access$200(SendBeaMessageDialog.java:737)
> 	at com.jdimension.jlawyer.client.bea.SendBeaMessageDialog$2.actionPerformed(SendBeaMessageDialog.java:1228)
> 	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
> 	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
> 	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
> 	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
> 	at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
> 	at javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:842)
> 	at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:886)
> 	at java.awt.Component.processMouseEvent(Component.java:6539)
> 	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
> 	at java.awt.Component.processEvent(Component.java:6304)
> 	at java.awt.Container.processEvent(Container.java:2239)
> 	at java.awt.Component.dispatchEventImpl(Component.java:4889)
> 	at java.awt.Container.dispatchEventImpl(Container.java:2297)
> 	at java.awt.Component.dispatchEvent(Component.java:4711)
> 	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
> 	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535)
> 	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
> 	at java.awt.Container.dispatchEventImpl(Container.java:2283)
> 	at java.awt.Window.dispatchEventImpl(Window.java:2746)
> 	at java.awt.Component.dispatchEvent(Component.java:4711)
> 	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
> 	at java.awt.EventQueue.access$500(EventQueue.java:97)
> 	at java.awt.EventQueue$3.run(EventQueue.java:709)
> 	at java.awt.EventQueue$3.run(EventQueue.java:703)
> 	at java.security.AccessController.doPrivileged(Native Method)
> 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
> 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
> 	at java.awt.EventQueue$4.run(EventQueue.java:733)
> 	at java.awt.EventQueue$4.run(EventQueue.java:731)
> 	at java.security.AccessController.doPrivileged(Native Method)
> 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
> 	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
> 	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
> 	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
> 	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
> 	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
> 	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
> 	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
> 2020-11-18 02:59:14,921 INFO  [org.jlawyer.bea.BeaWrapper] resolved govello-1260364804747-000194713 to Sozialgericht Berlin (10557 Berlin)
> 2020-11-18 02:59:21,568 ERROR [com.jdimension.jlawyer.client.settings.UserSettings] Value is null when setting user properties with key client.desktop.onlymycases
> 2020-11-18 02:59:29,640 ERROR [com.jdimension.jlawyer.client.settings.UserSettings] Value is null when setting user properties with key client.desktop.onlymyreviews
> 2020-11-18 02:59:37,518 ERROR [com.jdimension.jlawyer.client.settings.UserSettings] Value is null when setting user properties with key client.desktop.lastfiltertag
> 2020-11-18 02:59:37,518 ERROR [com.jdimension.jlawyer.client.settings.UserSettings] Value is null when setting user properties with key client.desktop.lastfiltertag
> 2020-11-18 02:59:37,518 ERROR [com.jdimension.jlawyer.client.settings.UserSettings] Value is null when setting user properties with key client.desktop.lastfilterdocumenttag
> 2020-11-18 02:59:37,518 ERROR [com.jdimension.jlawyer.client.settings.UserSettings] Value is null when setting user properties with key client.desktop.lastfilterdocumenttag
> 2020-11-18 02:59:37,553 ERROR [com.jdimension.jlawyer.client.settings.UserSettings] Value is null when setting user properties with key client.desktop.onlymytagged
> 2020-11-18 02:59:48,184 INFO  [org.jlawyer.bea.BeaWrapper] sender information is null - loading entire message
> 2020-11-18 02:59:48,392 INFO  [org.jlawyer.bea.BeaWrapper] sender information is null - loading entire message
> 2020-11-18 02:59:50,588 ERROR [com.jdimension.jlawyer.client.settings.UserSettings] Value is null when setting user properties with key client.desktop.onlymycases
> 2020-11-18 02:59:51,184 ERROR [org.jlawyer.bea.BeaWrapper] Error loading message journal
> de.brak.bea.application.dto.soap.types5.BeaFault: 9999 - General error processing request.
> 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
> 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
> 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
> 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
> 	at com.sun.xml.internal.ws.fault.SOAPFaultBuilder.createException(SOAPFaultBuilder.java:135)
> 	at com.sun.xml.internal.ws.client.sei.StubHandler.readResponse(StubHandler.java:238)
> 	at com.sun.xml.internal.ws.db.DatabindingImpl.deserializeResponse(DatabindingImpl.java:189)
> 	at com.sun.xml.internal.ws.db.DatabindingImpl.deserializeResponse(DatabindingImpl.java:276)
> 	at com.sun.xml.internal.ws.client.sei.SyncMethodHandler.invoke(SyncMethodHandler.java:104)
> 	at com.sun.xml.internal.ws.client.sei.SyncMethodHandler.invoke(SyncMethodHandler.java:77)
> 	at com.sun.xml.internal.ws.client.sei.SEIStub.invoke(SEIStub.java:147)
> 	at com.sun.proxy.$Proxy65.getMessageJournal(Unknown Source)
> 	at org.jlawyer.bea.BeaWrapper.getMessageJournal(BeaWrapper.java:3486)
> 	at org.jlawyer.bea.BeaWrapper.isMessageReadByIdentity(BeaWrapper.java:3534)
> 	at org.jlawyer.bea.BeaWrapper.getMessage(BeaWrapper.java:3108)
> 	at org.jlawyer.bea.BeaWrapper.getMessage(BeaWrapper.java:2940)
> 	at com.jdimension.jlawyer.client.bea.BeaAccess.getMessage(BeaAccess.java:1024)
> 	at com.jdimension.jlawyer.client.bea.BeaInboxPanel$4.run(BeaInboxPanel.java:988)
> 	at java.util.TimerThread.mainLoop(Timer.java:555)
> 	at java.util.TimerThread.run(Timer.java:505)
> 2020-11-18 02:59:51,243 ERROR [org.jlawyer.bea.BeaWrapper] Error loading message journal
> de.brak.bea.application.dto.soap.types5.BeaFault: 9999 - General error processing request.
> 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
> 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
> 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
> 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
> 	at com.sun.xml.internal.ws.fault.SOAPFaultBuilder.createException(SOAPFaultBuilder.java:135)
> 	at com.sun.xml.internal.ws.client.sei.StubHandler.readResponse(StubHandler.java:238)
> 	at com.sun.xml.internal.ws.db.DatabindingImpl.deserializeResponse(DatabindingImpl.java:189)
> 	at com.sun.xml.internal.ws.db.DatabindingImpl.deserializeResponse(DatabindingImpl.java:276)
> 	at com.sun.xml.internal.ws.client.sei.SyncMethodHandler.invoke(SyncMethodHandler.java:104)
> 	at com.sun.xml.internal.ws.client.sei.SyncMethodHandler.invoke(SyncMethodHandler.java:77)
> 	at com.sun.xml.internal.ws.client.sei.SEIStub.invoke(SEIStub.java:147)
> 	at com.sun.proxy.$Proxy65.getMessageJournal(Unknown Source)
> 	at org.jlawyer.bea.BeaWrapper.getMessageJournal(BeaWrapper.java:3486)
> 	at org.jlawyer.bea.BeaWrapper.getMessage(BeaWrapper.java:3113)
> 	at org.jlawyer.bea.BeaWrapper.getMessage(BeaWrapper.java:2940)
> 	at com.jdimension.jlawyer.client.bea.BeaAccess.getMessage(BeaAccess.java:1024)
> 	at com.jdimension.jlawyer.client.bea.BeaInboxPanel$4.run(BeaInboxPanel.java:988)
> 	at java.util.TimerThread.mainLoop(Timer.java:555)
> 	at java.util.TimerThread.run(Timer.java:505)
> 2020-11-18 03:00:00,581 ERROR [com.jdimension.jlawyer.client.settings.UserSettings] Value is null when setting user properties with key client.desktop.onlymyreviews
> 2020-11-18 03:00:10,518 ERROR [com.jdimension.jlawyer.client.settings.UserSettings] Value is null when setting user properties with key client.desktop.lastfiltertag
> 2020-11-18 03:00:10,518 ERROR [com.jdimension.jlawyer.client.settings.UserSettings] Value is null when setting user properties with key client.desktop.lastfiltertag
> 2020-11-18 03:00:10,518 ERROR [com.jdimension.jlawyer.client.settings.UserSettings] Value is null when setting user properties with key client.desktop.lastfilterdocumenttag
> 2020-11-18 03:00:10,519 ERROR [com.jdimension.jlawyer.client.settings.UserSettings] Value is null when setting user properties with key client.desktop.lastfilterdocumenttag

**Comment by stm9x9** [comment]
Während ich das hier schrieb, nach etwa 20 min ging es auf einmal weiter, ich konnte eine Akte zum Speichern auswählen. 
 ¯\\_(ツ)_/¯

**Comment by j-dimension** [comment]
Vermutlich hängt hier die Schnittstelle. Ich weiß auch nicht wie man das mit vertretbarem Aufwand ändern könnte - soetwas wie einen Timeout kann ich der Schnittstelle nicht mitgeben (sodass sie bspw. nach max. 30s abbricht), auch einen Abbruch ermöglicht die API der BRAK nicht. 
Es liefe letztlich wieder auf ein asynchrones Abarbeiten heraus, also die Nachricht nur "absetzen" und dann im Hintergrund abarbeiten lassen. Dazu bräuchte man aber umfangreiche Änderungen im Sinne einer Postausgangsansicht und umfangreichem Fehlerhandling, damit der Nutzer mitbekommt, dass ein Versand fehlgeschlagen ist.

**Comment by Mucki526** [comment]
Das hatte ich heute auch mit einem großem PDF. Allerdings griff ich auf den Scanordner der Box über das Internet (VPN) zu. Ich vermutete daher ein Geschwindigkeitsproblem beim Versenden des Anhangs. Vor Ort im Büro ging es dann problemlos am nächsten Tag.
