### ISSUE TITLE
[BUG] [beA] Fehler nach "in Akte speichern" when #getRollbackOnly

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#947]
**Describe the bug / Fehlerbeschreibung**
(todo: a description of the bug / eine Beschreibung des Fehlers)

**To Reproduce / Schritte zum Nachvollziehen**

Folgefehler zu #946 

Als es dann gesendet werden konnte, wurde nach der Anzeige "In Akte speichern" "Nachricht erfolgreich verschickt" angezeigt, aber es poppte ein Fehler auf:

![image](https://user-images.githubusercontent.com/29924198/99475363-aeb1ae00-294e-11eb-89f2-c958d177c900.png)

Nach Bestätigen der Meldung ist das Nachrichten-Erstell-Fenster weiterhin offen gewesen! Und ich konnte die Nachricht erneut(!) versenden.

Ich habe die Nachricht nun einmal mit der späteren Uhrzeit in der Akte, aber zweimal im beA-Gesendet-Ordner, jeweils mit 0800er-Status.

**Environment / verwendete Umgebung:**
 - OS / Betriebssystem: Win 10 Pro 64
 - j-lawyer.org Version: 1.13.0.1

**Comment by j-dimension** [comment]
Dazu benötige ich ein Client.log

**Comment by j-dimension** [comment]
Gern wieder aufmachen, wenn es ein Log dazu gibt.
