### ISSUE TITLE
[FEATURE] Datenbank-Infos in Datensicherungs-Einstellungen nötig?

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#949]
![image](https://user-images.githubusercontent.com/29924198/99476459-e3bf0000-2950-11eb-8012-ee37d9332970.png)

Ist das hier eigentlich nötig das abzufragen? Weiß das System diese Daten nicht eh? Es greift ja schließlich permanent auf die Datenbank zu!? Oder übersehe ich da eine Notwendigkeit?

**Comment by j-dimension** [comment]
Es soll / muss möglich sein, für den Betrieb der Anwendung und das Sichern der Datenbank Nutzer mit unterschiedlichen Berechtigungen zu nutzen.
