### ISSUE TITLE
[FEATURE] vormaliges Feature fehlt: in Ansicht Dokumente unterhalb des Suchfelds waren immer die Dok. Etiketten dargestellt

### ISSUE THREAD

**Issue by iradraconis** [jlawyerorg/j-lawyer-org#951]
siehe Titel. So weiß man bei Öffnen der Akte gar nicht, welche Etiketten vergeben sind.

**Comment by j-dimension** [comment]
@iradraconis die Information ist nicht verloren gegangen. Du findest sie als Mouseover-/Tooltiptext an dem Etiketten-Button hinter dem Suchfeld. Okay so?

**Comment by iradraconis** [comment]
Oh peinlich für mich :) das wusste ich nicht. So ist perfekt!

**Comment by j-dimension** [comment]
Ja, fehlt irgendwie als Kommentar in der Änderungshistorie. Mea culpa!
