### ISSUE TITLE
[FEATURE] [kalender] Wiedervorlage und Fristen um Feld Bemerkung erweitern

### ISSUE THREAD

**Issue by RA-crm** [jlawyerorg/j-lawyer-org#953]
Neben Standard-WV und -Fristen gibt es auch Fälle, in denen eine längere Erläuterung des Gegenstandes sinnvoll ist. Etwa, wenn die Wiedervorlage oder Frist weitere Verfügungen umfassen soll. Momentan behelfen wir uns bei uns in der Kanzlei durch Aktenvermerke die als Notiz angelegt werden und auf die die WV oder Frist verweist. 
Andere KSW bieten neben der WV/Frist auch die Möglichkeit, in einem extra Feld (häufig Bemerkungen genannt) diese Erläuterungen anzufügen. Ich halte das für eine sinnvolle Ergänzung.

**Comment by PBaumfalk** [comment]
Diese Idee wäre super. Dann kann man in der WV auch Bemerkungen zu der WV machen. Man müsste nicht mehr in der Akte suchen.

Mit freundlichen Grüßen / Kindly Regards

Patrick Baumfalk
Rechtsanwalt / Lawyer


Mobil:    +49 1525 53 04 194
E-Mail:   patrick.baumfalk@kanzlei-baumfalk.de


Baumfalk - Rechtsanwaltskanzlei
Hauptstr. 195
50169 Kerpen

Tel.: +49 2273 40 68 504
Fax: +49 2273 59 03 565

E-Mail: info@kanzlei-baumfalk.de
Web: www.kanzlei-baumfalk.de

**Comment by iradraconis** [comment]
👍🏻

**Comment by Maz111111** [comment]
Das wäre ein tolles Feature!

Und ich habe es auch schon mal als Issue angesprochen.  #606.

Ihr könnt Euch die Diskussion ja mal ansehen. 

Das aufgrund meiner Anfrage dann implementierte Feature nutze ich nun leider überhaupt nicht.

Auch kann man derzeit beim Anlegen der WV nur entweder in dem Feld für WV-Grund etwas von Hand eintragen oder einen vordefinierten Wert wählen. Man kann jedoch nicht mehr einen vordefinierten Wert wählen und diesen dann von Hand erweitern (das war früher m.E. möglich - hätte ich damals mal bloß meine Klappe gehalten :-) ).

Ich löse es derzeit dann so, dass ich die WV mit dem vordefinierten Wert - z.B. "Posteingang?" - anlege, dann auf Bearbeiten gehe und dann in dem WV-Grund-Feld das dazu schreiben, was ich gern hätte - z.B. "VA Auskünfte da?".

Im Grunde ist es für mich damit umständlicher geworden. In der alten Version, konnte man beim Anlegen der WV den Grund händisch bearbeiten.

Der einzige Unterschied in diesem Thema hier ist jetzt, dass es ein zweites Feld "Hinweis" geben soll. Aus meiner Sicht würde es aber auch reichen, wenn man das WV Feld einfach händisch bearbeiten und den Hinweis von Hand hinzufügen kann.

Wobei mit einem Hinweisfeld möglicherweise durch die Hintertür dann doch das möglich wäre, was ich damals angedacht hatte, indem man dann auch einen Wertevorrat für die Hinweise selbst definieren und anklicken kann.

Viele Grüße
Martin

**Comment by j-dimension** [comment]
> Im Grunde ist es für mich damit umständlicher geworden. In der alten Version, konnte man beim Anlegen der WV den Grund händisch bearbeiten.

Ich könnte folgende einfache Änderung noch kurzfristig reinnehmen: wenn nur exakt ein Wiedervorlagegrund ausgewählt ist, dann wir er unten in das Freitextfeld übernommen und man kann ihn bearbeiten. Sobald mehrere ausgewählt sind, ist eine Bearbeitung nicht möglich.

Was meinst Du, @Maz111111 ?

**Comment by Maz111111** [comment]
Mir würde das reichen! Vielen Danke!

**Comment by j-dimension** [comment]
Okay, dann als schnelle Zwischenlösung die #956. Dieses Ticket hier bleibt offen, ist losgelöst davon sinnvoll.

**Comment by j-dimension** [comment]
"Beschreibung" gibt es nun als Feld, umgesetzt via #955. Ich mache hier also zu.

**Comment by j-dimension** [comment]
(Da gibt es auch Screenshots)

**Comment by j-dimension** [comment]
Ich habe das innerhalb der WV-Anlage in der Akte hinzugefügt. An anderen Stellen habe ich das neue Bemerkungs-Feld noch nicht hinzugefügt. Es ist platztechnisch auch eine echte Herausforderung, insbesondere in den Versanddialogen beA und Mail. 

So wie @RA-crm es formuliert 
`Neben Standard-WV und -Fristen gibt es auch Fälle, in denen eine längere Erläuterung des Gegenstandes sinnvoll ist. `
hört es sich so an, als wäre es zumutbar (da kein Routinefall), in solchen Fällen die Oberfläche in der Akte zu verwenden.
