### ISSUE TITLE
[FEATURE] erste Iteration Kalenderintegration

### ISSUE THREAD

**Issue by iradraconis** [jlawyerorg/j-lawyer-org#955]
Ich weiß, das Thema steht auf der Agenda. Ich weiß auch, dass das Thema nach den Finanzen kommen soll. Da bis dahin allerdings noch einige Zeit verstreichen kann, das Thema Fristen und Termine aber in einer Kanzlei von enormer Wichtigkeit ist, wäre es da nicht gut eine Art Interimslösung zu haben? Zum einen müsste zunächst die dritte Kategorie für Termine eingeführt werden. Als Zwischenlösung bis zu einer vollständigen Implementation wäre vielleicht eine Art automatisierter CSV zu iCal Export, ggfs. als Skript, mit der Möglichkeit, die Datei dann in einen Kalender zu importieren. Wenn das automatisiert im Hintergrund geschieht, wäre die Aktualität gewährleistet. Nur so als Idee, ohne dass ich wüsste, mit welchem Aufwand das verbunden wäre. Das Termin Management ist momentan bei mir eine Katastrophe. Die Kategorisierung nach Wiedervorlage und Frist macht es so unübersichtlich. Eine Darstellung in einer Wochenansicht o.ä. wäre da sehr hilfreich. 

----

- [x] neu: CalendarService
- [x] neu: CalendarAsyncService für Synchronisation, oder Queue-basiert, oder über TimerTask
- [x] Refactoring: WV / Fristen-Services in CalendarService verlagern
- [x] neue Kategorie "Event" für Termine
- [x] neue Icons für Event, WV, Frist
- [x] Desktop Fälligkeiten erweitern
- [x] alles unter "Kalender" links (fällige, suchen, ...)
- [x] alle Stellen wo eine WV angelegt werden kann: Beschreibung hinzufügen, Enddatum automatisch ermitteln und speichern
- [x] Ansicht in der Akte erweitern
- [x] Datenmodell erweitern: Startzeit, Endzeit, Ort, Beschreibung
- [x] Überarbeitung Eingabe in der Akte: bei WV+Frist wie bisher, bei Termin zusätzliche Felder
- [x] j-lawyer-cloud.jar erweitern für CardDAV
- [x] j-lawyer-cloud.jar erweitern für CalDAV
- [x] Support für NC Install in Subdomain und Unterverzeichnis
- [x] Sync bei Datenänderung
- [x] automatischer oder forcierter Vollsync
- [x] erledigte WV/Fristen aus Kalender löschen, Termine nicht. Achtung: wenn es wieder auf "offen" gesetzt wird ist es zwar ein update, aus Kalendersicht aber ein Create
- [x] wie mit vorhandenen Events umgehen? Wahlweise in Standardkalender syncen lassen?
- [x] Einstellungsdialog: Kalender - Farbe, Name, Zugangsdaten
- [x] Nutzerverwaltung: Zugriff auf bestimmte Kalender (ggf. erst später?)
- [x] Fälligkeiten suchen / nach Fälligkeit anzeigen
- [x] alles prüfen wo ArchiveFileReviewsBean verwendet wird (bspw. HTML-Export etc.)
- [x] REST API
- [x] ??? grafische Wochenansicht
- [x] Druck Handakte
- [x] Tests mit Nextcloud in Unterordner des Webservers
- [x] spalte für kalender-id an die case_events
- [x] vorhandene termine in kalender migrieren
- [x] sync - hartkodierte kalenderdaten raus, dynamisch ermitteln
- [x] bei löschen / bearbeiten von kalendern prüfen und agieren
- [x] UI überall
- [ ] REST API
- [x] standardkalender nehmen, wenn client keinen liefert bei anlage WV? (acuh über rest api) oder exception
- [x] einstellungsdialog: sicherstellen dass immer min. 1 kalender für jede kategorie (wv, fr, t) existiert
- [x] CalendarSelectionButton darf nur Kalender anbieten, für die der Nutzer berechtigt ist

**Comment by RA-crm** [comment]
ich schließe mich dem Begehren und dem Lösungsvorschlag an

**Comment by j-dimension** [comment]
Link zu #108

**Comment by j-dimension** [comment]
Bin unsicher, ob eine "einfache" Lösung akzeptiert wird - es kommen dann sofort Rückmeldungen wie

- warum kann ich dort nicht mehrere Personen als Teilnehmer eintragen?
- warum wird das nicht alles synchronsiert in mein (irgendwas)?
- warum gibt es keine "einladen"-Funktion?
- warum kann das keine Serientermine, samt Ausnahme und allem?
- ...

Hier ließen sich noch zig Punkte nennen. 

Ich bin mir unsicher, ob eine Behelfslösung Akzeptanz finden würde, oder mir beständigen Überzeugungsaufwand generieren würde.

**Comment by iradraconis** [comment]
Mist, ich hätte es nicht Behelfslösung nennen dürfen 😀 ich wollte nur die enorme Wichtigkeit einer aktenbezogenen Terminverwaltung hervorheben. Es gibt im Internet Tools für eine csv zu iCal Konvertierung. Wenn wir wenigstens Termine als dritte Kategorie bekommen könnten, mit Termindauer, liesse sich bestimmt im Einzelfall was machen. Die eigentliche Kalenderlösung folgt dann ja ohnehin, wenn die Zeit reif ist.

**Comment by j-dimension** [comment]
Mal sehen, ich muss die 1.14 eh nochmal feinplanen. Packe es erstmal da rein.

**Comment by Mucki526** [comment]
Wir arbeiten im Moment mit Google Calendar mit verschiedenen Kalendern für die jeweiligen Begehrlichkeiten (zumindest Fristen, Vorfristen, Meine Termine, Deine Termine....., in verschiedenen Farben, klappt super). Ich ertappe mich immer wieder, dass damit das Widervorlagensystem aus j-lawyer "verwaist" und Wiedervorlagen in der Akte selbst nicht immer aktuell bzw. nicht im focus steht, weil man nicht zwei Kalender gleichzeitig führt und träume auch davon, dass die google calender Einträge mit J-lawyer synchron laufen. Ich weiss, mit google Calender ist es wie mit Coca Cola, die einen lieben es, die anderen hassen es....

**Comment by j-dimension** [comment]
WV / Frist:

![grafik](https://user-images.githubusercontent.com/3729754/120119267-187d0100-c197-11eb-9862-060efd7da079.png)

**Comment by j-dimension** [comment]
Termin:

![grafik](https://user-images.githubusercontent.com/3729754/120119343-8b867780-c197-11eb-9a8c-89b05f65e9e0.png)

**Comment by j-dimension** [comment]
Desktop - Gruppierung nach Kategorie:

![grafik](https://user-images.githubusercontent.com/3729754/120401043-67fe3100-c33f-11eb-8eb1-e8d7a890eac1.png)

**Comment by j-dimension** [comment]
https://user-images.githubusercontent.com/3729754/120720863-1be0f700-c4cd-11eb-8922-b1a8be783ced.mp4

**Comment by Dickmaulruessler** [comment]
> 
> 
> Bin unsicher, ob eine "einfache" Lösung akzeptiert wird - es kommen dann sofort Rückmeldungen wie
> 
>     * warum kann ich dort nicht mehrere Personen als Teilnehmer eintragen?
> 
>     * warum wird das nicht alles synchronsiert in mein (irgendwas)?
> 
>     * warum gibt es keine "einladen"-Funktion?
> 
>     * warum kann das keine Serientermine, samt Ausnahme und allem?
> 
>     * ...
> 
> 
> Hier ließen sich noch zig Punkte nennen.
> 
> Ich bin mir unsicher, ob eine Behelfslösung Akzeptanz finden würde, oder mir beständigen Überzeugungsaufwand generieren würde.

Danke dir dafür, dass du diese Variante schon einmal ermöglicht hast! 
Es geht nicht alles auf einmal. Und die weitere Entwicklung des Kalenders ist dann erst einmal nachrangig. 
Entsprechende Anfragen nach weiteren Funktionen darfst du dann glaube ich auch recht kurz mit "momentan haben andere Dinge Priorität beantworten".

**Comment by j-dimension** [comment]
https://user-images.githubusercontent.com/3729754/121260965-57573900-c8b2-11eb-8d04-301e61c091c2.mp4

**Comment by j-dimension** [comment]
@nronk wenn Du erlaubst, würde ich den von Dir bereitgestellten Testzugang in Deiner Nextcloud für Tests der Adressbuch - und Kalendersynchronisation verwenden. Ich habe nach wie vor keine Installation die sich in einem Unterverzeichnis des Webservers befindet. 
Darf ich?

**Comment by nronk** [comment]
Na klar. :)Schau mal, ob die Userdaten wieder funktionieren.Am 14.06.2021 21:25 schrieb Jens Kutschke ***@***.***>:

@nronk wenn Du erlaubst, würde ich den von Dir bereitgestellten Testzugang in Deiner Nextcloud für Tests der Adressbuch - und Kalendersynchronisation verwenden. Ich habe nach wie vor keine Installation die sich in einem Unterverzeichnis des Webservers befindet.

Darf ich?

**Comment by j-dimension** [comment]
Noch ein paar Screenshots der "fertigen" (für die 1.15) Lösung:

![grafik](https://user-images.githubusercontent.com/3729754/124833181-13715580-df7e-11eb-9aaa-19d2ba59928d.png)

**Comment by j-dimension** [comment]
Tagesübersicht: 
![grafik](https://user-images.githubusercontent.com/3729754/124833247-313eba80-df7e-11eb-8dfe-a3b0b576a52f.png)

**Comment by j-dimension** [comment]
Monatsübersicht:
![grafik](https://user-images.githubusercontent.com/3729754/124833317-4e738900-df7e-11eb-87ef-0ac95d7ef155.png)
