### ISSUE TITLE
[FEATURE] Längere Anzeige der Mouseover Anzeigen

### ISSUE THREAD

**Issue by iradraconis** [jlawyerorg/j-lawyer-org#957]
Das Feature ist toll. Bei Adressen kann ich leider so schnell, wie die Einblendung wieder verschwindet, gar nicht die Nummer im Telefon eingeben :)

**Comment by j-dimension** [comment]
@j-dimension 
`ToolTipManager.sharedInstance().setDismissDelay(Integer.MAX_VALUE);`

**Comment by j-dimension** [comment]
auf 30s angehoben

**Comment by stm9x9** [comment]
auf Dauer anzeigen lassen, bis man die Maus wieder bewegt, ginge nicht?
