### ISSUE TITLE
[FEATURE] Adressen: verstorben-Angaben erweitern

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#958]
![image](https://user-images.githubusercontent.com/29924198/99848183-9c678800-2b79-11eb-8edf-6ef46418de21.png)

hier ein paar mehr Infos darstellen:

geboren vor: xxx Jahren (also das was sonst das Alter ist)
verstorben mit: xxx Jahren

und dadrunter jeweils(!) ggf der Minderjährigkeitshinweis bezogen auf das aktuelle bzw das Sterbedatum

**Comment by j-dimension** [comment]
Ich mache nochmal einen Gegenvorschlag. Spielt der Fakt "gestorben, wäre jetzt immer noch minderjährig" eine Rolle?

**Comment by j-dimension** [comment]
![grafik](https://user-images.githubusercontent.com/3729754/99860353-1c4e1c00-2b93-11eb-86ed-0a2b95c94858.png)

**Comment by j-dimension** [comment]
![grafik](https://user-images.githubusercontent.com/3729754/99860389-35ef6380-2b93-11eb-9e6c-7077c6167fa1.png)

**Comment by j-dimension** [comment]
![grafik](https://user-images.githubusercontent.com/3729754/99860587-c168f480-2b93-11eb-87ff-ee1d564fa2e9.png)

**Comment by j-dimension** [comment]
![grafik](https://user-images.githubusercontent.com/3729754/99860617-dc3b6900-2b93-11eb-9cfa-cd7077be44eb.png)

**Comment by stm9x9** [comment]
**bug**

![image](https://user-images.githubusercontent.com/29924198/99863833-4eb24600-2ba0-11eb-8b97-580403194953.png)

mit über 18 verstorben, aber das U18 Symbol ist vorne

**Comment by stm9x9** [comment]
> Ich mache nochmal einen Gegenvorschlag. Spielt der Fakt "gestorben, wäre jetzt immer noch minderjährig" eine Rolle?

auf jeden Fall ist geboren vor: xxx Jahren hilfreich, zb zahlen bestimmte Versicherungen mindestens bis zu einem fiktiven Alter von x Jahren Geld an Hinterbliebene aus. 

Ob die Angabe: wäre jetzt noch minderjährig wichtig sein kann, muß ich nochmal überlegen.

Und auch
