### ISSUE TITLE
[Wiedervorlage] Auswahl der häufigsten WV-Fristen per click - Vorschlag "verantwortlich"

### ISSUE THREAD

**Issue by MarcoWolny** [jlawyerorg/j-lawyer-org#959]
Ich fände es hilfreich, wenn im DropDown "verantwortlich" unter "Wiedervorlage und Fristen" der jeweilige Akten-Sachbearbeiter als Standardauswahl vorgeschlagen werden würde. In der Regel erstellt man die Frist für diesen.

Zusätzlich wäre eine kleine Reihe mit Check-Kästchen unterhalt des Datums oberhalb des "verantwortlich-Dropdows" mit den drei (?) häufigsten Fristen toll, wobei hier eine Abstimmung erfolgen müsste, was denn der durchschnittliche Anwender als häufige Fristen versteht. Ich schlage man "1 Woche", "2 Wochen" und "1 Monat" vor - dann könnte man da die Datums-Auswahl bechleunigen.

**Comment by iradraconis** [comment]
👍🏻

**Comment by j-dimension** [comment]
> Ich fände es hilfreich, wenn im DropDown "verantwortlich" unter "Wiedervorlage und Fristen" der jeweilige Akten-Sachbearbeiter als Standardauswahl vorgeschlagen werden würde. In der Regel erstellt man die Frist für diesen.

Okay.



> "1 Woche", "2 Wochen" und "1 Monat" vor - dann könnte man da die Datums-Auswahl bechleunigen.

Es gab in #84 schonmal eine Diskussion, ob man "Standardfristen" direkt an die Wiedervorlagen hängen könnte. Also nicht nur die Gründe, sondern auch eine Anzahl an Tagen. Dann müsste man im Normalfall tatsächlich nur einmal den Grund selektieren und bestätigen. 
Wurde damals etwas kontrovers diskutiert.

**Comment by MarcoWolny** [comment]
Ah, okay. Das hatte ich nicht gesehen. Ist aber auch etwas anders gelagert gewesen, damals. 

Es ging um die Fragen, welche Standardfristen für welche Wiedervorlagen verwendet werden sollen, wenn ich das richtig verstehe. 
Ich meinte eine Möglichkeit, die 3 häufigsten Fristen (1 Woche; 2 Wochen; 1 Monat) per Checkbox jedem x-beliebigen Wiedervorlagegrund zuzuordnen, ohne den Kalender öffnen zu müssen. Damit müssten eigentlich alle d’accord sein, weil es das Problem der jeweils üblichen Fristen des individuellen Wiedervorlagegrundes umgeht...

**Comment by j-dimension** [comment]
@MarcoWolny so schaut das jetzt aus:
https://user-images.githubusercontent.com/3729754/103314962-82488180-4a24-11eb-9be6-baaf77c3c47d.mp4

**Comment by MarcoWolny** [comment]
Finde ich sehr schön - insbesondere eine und zwei Wochen finde ich wichtig. Allerdings ist die Standard-Frist für Widersprüche pp. nicht 4 Wochen sondern leider 1 Monat (was ja abweichen kann)... 
Wie wäre es sonst mit "1 Wo" "2 Wo" "1 Mo"?

**Comment by j-dimension** [comment]
@MarcoWolny wie berechnet man so eine Monatsfrist?
Bspw. wenn der aktuelle Tag ein 31ter ist, etc

**Comment by MarcoWolny** [comment]
Guck mal hier: https://www.ra-kotz.de/monatsfrist.htm
Der Kollege hat es recht gut und knapp beschrieben... Könnte aber schwierig werden, das zu programmieren, fällt mir gerade auf. Insbesondere wenn Fristbeginn der 30.3. ist, der 30.4. aber ein Samstag ist, sodass Fristende am 02.05. wäre...

**Comment by RA-crm** [comment]
Keine Fristen durch einfaches anklicken bitte. Das Fristende bestimmt sich nach dem Fristbeginn. Es kommt regelmäßig auf dem Zugang an. Das ist - jedenfalls wenn der Bescheid dem Mandanten zugestellt wurde - selten der Tag, an dem das Dokument beim RA eingeht und selbst dann nicht immer der Tag, an dem die Frist notiert wird/werden kann.
Um Fehler hier zu vermeiden, sollte es schon keine Option geben, die Frist automatisch anzulegen.
Das gilt nicht für WV. Die sind frei wählbar.

**Comment by MarcoWolny** [comment]
Stimmt, das ist ein Argument. Ich versuche immer, meine Post tagesaktuell abzuarbeiten, aber das Risiko besteht natürlich. Also so lassen, wie Jens es schon eingangs vorschlug?

**Comment by RA-crm** [comment]
Gibt es schon ein Ticket für einen automatisierten Ausdruck einer Fristenkontrolle (wenn nicht, lege ich eins an). Der BGH steht ja weiterhin auf Papier und hält in Haftungsfragen daran fest. 
Denkbare wäre, bei Erstellung einer (elektronischen) Frist automatisch ein Dokument zu erzeugen, welches Fristbeginn, Fristende und Vorfrist aufführt und dass der zuständige RA dann abzeichnet.
Bisher machen wir das in der Kanzlei manuell.

**Comment by MarcoWolny** [comment]
Oh, das klingt gut. Dann gibt es einen Ausdruck mit Unterschrift als Handlungsanweisung für das Sekretariat, die Frist entsprechend noch im Papierkalender zu notieren...

**Comment by RA-crm** [comment]
siehe #1058 
Bitte ergänzen, wenn man in dem Formular noch mehr benötigt

**Comment by j-dimension** [comment]
Ich werde das nicht wieder zurückbauen, und auch keine komplexere Berechnung der Monatfrist implementieren - das wäre Teil von #84.

Versteht das also (in dieser Iteration) als eine "Schnellauswahl" eines Datums, ohne Intelligenz.
