### ISSUE TITLE
Marker für offene Kostennoten - Liste offene Kostennote

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-org#96]
Es wäre eine hilfreiche Sache - wenn es auch noch keine Buchhaltung in j-lawyer gibt - wenn ein Haken hinter einem Dokument in der Akte, welche eine Kostennote ist, gesetzt werden könnte, der dann (wie Wiedervorlagen) dazu führt, dass die Kostennote in einer Liste "offene Kostennoten" erscheint. Wenn der Marker entfernt wird ist die Rechnung bezahlt und verschwindet aus der Liste "Debitoren".

**Comment by RA-crm** [comment]
https://github.com/jlawyerorg/j-lawyer-org/issues/756

**Comment by j-dimension** [comment]
![image](https://user-images.githubusercontent.com/3729754/216849567-8047e7fb-857c-4ddd-a24f-ed67678b32d9.png)

**Comment by j-dimension** [comment]
![image](https://user-images.githubusercontent.com/3729754/216849596-b0ba0e2e-8033-4f01-895b-0ccbe1d1652f.png)

**Comment by j-dimension** [comment]
![image](https://user-images.githubusercontent.com/3729754/216849626-80121047-41b0-4a79-9acc-1be150539689.png)
