### ISSUE TITLE
[BUG] ESC-Taste bei Dokumentenumbenennung führt zu Fehlermeldung

### ISSUE THREAD

**Issue by ReRo-G** [jlawyerorg/j-lawyer-org#961]
**Describe the bug / Fehlerbeschreibung**
Fehlermeldung bei ESC-Taste im Umbenennen-Dialog.

**To Reproduce / Schritte zum Nachvollziehen**

1. Gehe zu Dokumente -> Rechtsklick -> "umbenennen"
2. Drücke anschließend "ESC"
3. Es erscheint eine Fehlermeldung "Der Dateiname existiert bereits (siehe Anhang)

Hinweis: Die Meldung erscheint nicht bei einem Klick auf "abbrechen" im Umbenennen-Dialog.

**Expected behavior / Erwartetes Verhalten**
Verschwinden des Eingabefensters "umbenennen" ohne weitere Meldung (wie beim Klick auf "abbrechen")

**Screenshots**
![Bildschirmfoto 2020-11-20 um 20 30 35](https://user-images.githubusercontent.com/68281026/99943774-20846000-2d72-11eb-8f1b-1f5ee54863df.png)

**Environment / verwendete Umgebung:**
 - OS / Betriebssystem: MacOS
 - j-lawyer.org Version: 1.13.0.1

**Comment by j-dimension** [comment]
Erledigt
