### ISSUE TITLE
[BUG] Mauszeiger in der Dokumentenansicht

### ISSUE THREAD

**Issue by ReRo-G** [jlawyerorg/j-lawyer-org#963]
**Describe the bug / Fehlerbeschreibung**

Vielleicht ist es kein richtiger "BUG" - ich wusste dennoch nicht, wohin damit.

**To Reproduce / Schritte zum Nachvollziehen**

1. Mouseover Dateiname in der Dokumentenansicht
2. Cursor ändert sich dann auf "Linkhand"

**Expected behavior / Erwartetes Verhalten**

Cursor bleibt bei "Pfeil", da mit einem einfachen Klick auf den Dokumentennamen keine Aktion gestartet wird (jedenfalls keine andere als bei einem Klick auf den "Container" mit dem Cursor. Daher ist hier m.E. kein "Link" vorhanden (und auch nicht nötig), welcher bereits ohne Doppelklick eine Aktion auslöst.

Im Bereich "Beteiligte" wird der Cursor auch zur Linkhand, jedoch wird dann beim (einfachen) Klick auf den Beteiligten direkt dessen Profil aufgerufen.

**Environment / verwendete Umgebung:**

 - OS / Betriebssystem: MacOS
 - j-lawyer.org Version: 1.13.0.4

**Comment by j-dimension** [comment]
Muss ich selber erstmal drüber meditieren :-)

**Comment by ReRo-G** [comment]
:)
Mir fiel gerade noch ein weiterer Punkt in dem Kontext auf: in der Desktop-Ansicht wird auch die "Linkmaus" eingeblendet, es benötigt dementsprechend auch nur einen Klick um zur Akte zu kommen. Das halte ich für richtig.

Zur Dokumentenansicht: nutze den integrierten Dokumentenviewer kaum, aber andere sicher reichlich. Wenn da also bei einem Klick auf den Dokumentenname gleich das Dokument in einem externen Programm geöffnet würde, erschiene mir das nicht sinnvoll. Meinem Gefühl einer guten usability entspräche es da eher, wenn man halt einen Doppelklickt braucht (so wie momentan im Container), jedoch der Mauszeiger entsprechend identisch bliebe.
