### ISSUE TITLE
[FEATURE] Dokumente - Ordner: kompletten Pfad anzeigen

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#967]
![image](https://user-images.githubusercontent.com/29924198/100291482-36ff0700-2f7e-11eb-8873-3560848ad6bd.png)

Die beiden Dokumente sind in verschiedenen Ordnern. Das sieht man aber anhand der Angabe

![image](https://user-images.githubusercontent.com/29924198/100291544-5a29b680-2f7e-11eb-8040-6e339849e80d.png)

nicht.

Hilfreich wäre hier der komplette Pfad mit Ordner::Unterordner bzw Ordner2::Unterordner

**Comment by j-dimension** [comment]
Auf diesem Thema habe ich in der Tat länger rumgekaut, die Idee dann aber verworfen: ich müsste dann eine neue Zeile pro Dokument einfügen (und so den Überblick verschlechtern), da auf 13"-Displays ansonsten nicht der gesamte Ordner, sondern meist nur die oberste Ebene sichtbar wäre.

Man hätte also für etwas, das nur unter bestimmten Bedingungen einen Vorteil bringt, einen permanenten Nachteil.

Ich lasse das Ticket offen, damit ggf. andere sich dazu äußern können.

**Comment by stm9x9** [comment]
> ch müsste dann eine neue Zeile pro Dokument einfügen

Meinst du nicht, daß das an der bisherigen Stelle noch ausreicht? Ich denke mal, mehr als zwei oder max drei Ebenen wird es da nicht geben? Und meist sind die automatisch erzeugten Dateinamen doch auch recht lang, so daß der Platz in der Horizontalen eh da sein muß oder aber eine Scrollbalken.

**Comment by j-dimension** [comment]
> so daß der Platz in der Horizontalen eh da sein muß oder aber eine Scrollbalken

Das stimmt. Es ist aber ein Unterschied ob ich dann in dem sichtbaren Bereich noch den untersten Ordner erkennen kann oder nur die "Wurzel" oder eine Ebene darunter. Das Scrollen hat man bei kleinen Displays immer.

**Comment by stm9x9** [comment]
Ich versteh nur Bahnhof :-) aber laß mich überraschen wie das aussieht
