### ISSUE TITLE
[FEATURE] [Ordner] leere und volle Ordner optisch unterscheiden

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#969]
Es würde die Handhabung vereinfachen, wenn man gleich sehen würde, in welchen Ordnern Dateien drin sind (nur der Ordner selber, nicht Unterordner, da die ja eh immer alle angezeigt werden im Baum links). zb mit einem ausgefüllten Icon:

![image](https://user-images.githubusercontent.com/29924198/100390036-67eb4480-302f-11eb-9c0f-390fab3e9751.png)

Es ist einfach eine schnellere Übersicht, wenn man gleich sieht, ob in "Gericht" schon was drin ist oder bislang nur in "Widerspruch".

**Comment by j-dimension** [comment]
Umsetzung:


https://user-images.githubusercontent.com/3729754/113067039-e6ade500-91bb-11eb-8dbf-51829f00ab47.mp4
