### ISSUE TITLE
[BUG] Ansicht scanordner in 1.13

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-org#971]
**NOTE: Please search existing tickets to avoid duplicates **
**HINWEIS: Bitte vorab die Ticketsuche verwenden, um Doppeleinträge zu vermeiden **
Erst mal herzlichen Dank für die neue Version :-)....

Ich habe gerade die 1.3 installiert. Hat alles geklappt. Ich freue mich auf die neuen features :-) und bin am ausprobieren....

Leider ist die Dokumentation noch auf vers. 1.12, ich bin mir also nicht sicher, ob ich was nicht verstehe oder ein bug vorliegt. Es wird im Scanordner, wenn man ihn wie gewohnt anklickt auf der linken Seite die Anzahl der vorhandenen Dokumente angezeigt, aber die Dokumente erscheinen nicht im neuen Scanfenster. Wo finde ich meine alten Scans? Nach der Anzeige sollten sie vorhanden sein, man sieht sie nicht und hat keinen Zugriff darauf...??

**Comment by j-dimension** [comment]
Die aktuelle Doku findest Du hier: https://www.j-lawyer.org/?page_id=11

Was zeigt Menü "?" - "Über" für Versionen an?

Was passiert beim manuellen Aktualisieren des Scaneingangs?

**Comment by Mucki526** [comment]
Ich bin im Moment mit dem Client in meinem Homenetzwerk 192.168.1.0, das über ein VPN zwischen zwei Fritzboxen mit dem Kanzleinetzwerk verbunden ist und greife auf die dortige "Box" (HP) unter 192.168.178.54 zu. Dann wird  mir zwar die Anzahl der im Scanordner vorhandenen Dokumente angezeigt, das Fenster bleibt leer. Ich habe jetzt über Anydesk auf meinen Kanzleiarbeitsplatz im Netzwerk 192.168.178.0 geschaut, da funktioniert es, dort sehe ich die Scandokumente. EIch installieren jetzt mal den Client auf dem nächsten Rechner daheim und schaue was da passiert. Ein manueller Refresh der Ansicht hat erst mal nix gebracht....

**Comment by j-dimension** [comment]
Was zeigt Menü "?" - "Über" für Versionen an?

**Comment by Mucki526** [comment]
1.13.05 für den Client. 13.0.20 Server, bea 2.356a, passt also. Ich kann mich gut mit dem Server in der Kanzlei verbinden. Hat auch mit dem nächsten Rechner geklappt, das gleiche Bild. Ich habe noch die Idee, dass ich auf dem Rechner keinen Netzwerkordner zur Box eingerichtet habe (neuer Rechner). Vielleicht liegt´s daran....???

**Comment by j-dimension** [comment]
Der Scaneingang im j-lawyer benötigt keine Netzwerkfreigabe. Ich bekomme das hier auch gar nicht reproduziert. 

Bitte mal den Scaneingang manuell aktualisieren und mir direkt im Anschluss das client.log per Email senden.

**Comment by Mucki526** [comment]
Ich hab´s kapiert. Beim Starten ist auf meinem kleinen Laptopbildschirm / Bildschirmen das Scanfenster mit den gescannten Dateien ganz klein. Man sieht oben nur den Eintrag "Dateinamen und eine Auswahl (Pfeile). Da ich das neue Dateifenster so noch nie gesehen habe, habe ich nicht verstanden, dass man es runterziehen kann, dann sieht man die gescannten Dateien.  Am 24" Zollbildschirm in der Kanzlei ist das Fenster mit den gescannten Dateien beim Starten größer gewesen, da sieht man die Namen. Das vergrößerte Fenster bleibt bei einem Neustart vorhanden.  Ist eine Darstellungssache beim ersten Start, mehr nicht...

**Comment by Mucki526** [comment]
Und wenn man dann die erste Datei anklickt, erscheinen auch die Auswahloptionen wie gewohnt (Datei aus scaneingang löschen und die erste Vorschau.......
