### ISSUE TITLE
Scanordner Breite der Spalte Namenseintrag bleibt beim Refresh nicht erhalten

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-org#972]
Man kann sich das Scanfenster jetzt viel besser einteilen und die Einteilung bleibt erhalten - Ausnahme: Beim manuellen Refresh der Liste ändert sich die Breite der Spalte (Datei)Namen (der Dateien) und wird sehr breit - sollte genauso wie der Rest unverändert bleiben, weil man es sich ja auf seinen Bildschirm angepasst hat. Kleiner Bug...

**Comment by j-dimension** [comment]
Wenn ich so betrachte wäre es für den Scaneingang sogar sinnvoll, das Datum nach vorn zu bringen. Dann ist es egal, wenn die Dateinamensspalte groß ist.
