### ISSUE TITLE
[Variable Höhe der Notizfläche

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-org#974]
Der Notizbereich ist offensichtlich vergrößert worden und lässt sich nicht verkleinern. Bei mir am großen Bildschirm sind jetzt meine Etiketten verdeckt, bzw. ich muss scrollen statt einfach zu klicken. Variable Notizflächengröße wäre meine Bitte....

**Is your feature request related to a problem? Please describe. / Welches Problem soll durch die Erweiterung / Verbesserung gelöst werden?**
Description / Beschreibung

**Describe the solution you'd like / Beschreibe die gewünschte Lösung**
Description / Beschreibung

**Additional context / Sonstiges **
Sonstige Informationen / Screenshots / ...

**Comment by j-dimension** [comment]
Verstehe ich nicht ganz - bitte einen Screenshot bereitstellen.

**Comment by Mucki526** [comment]
Verdeckt mir jetzt halt
[J-lawyer Notizfensterproblem.pdf](https://github.com/jlawyerorg/j-lawyer-org/files/5608118/J-lawyer.Notizfensterproblem.pdf)
 meine Etiketten ab der dritten Reihe...

**Comment by iradraconis** [comment]
Wessen „Alte" ist denn da im Schrank gefangen? :O 
Sorry, der musste sein. Was für eine Auflösung auf welchem Monitor benutzt du? Nicht mal auf meinem kleinen 13 Zoll MacBook Pro wird das so gestaucht. Ich habe da bei voller Fenstergröße 3 Zeilen Etiketten.

**Comment by Mucki526** [comment]
Meine Alte hat Freigang Iradraconis.... Es ist nur ein Ausschnitt meines normal auflösenden 27 Zoll Monitors, weil -Datenschutz....

**Comment by Mucki526** [comment]
Tut mich auch leid wegen des kleinen MacBooks Pro mit dem angenagten Apfel auf dem Deckel.... ;-) ....... Das musste sein.

**Comment by iradraconis** [comment]
Muss dir nicht leid tun :) 
Hast du das Fenster skaliert? Bei 27 Zoll sollte da mehr Platz sein. Ich habe immer 3 Zeilen Etiketten, selbst wenn ich das Fenster runterskaliere. Mal sehen was Jens sagt.

**Comment by j-dimension** [comment]
@iradraconis @Mucki526 Ihr seid cool! :-D

**Comment by j-dimension** [comment]
13 Zoll MacBook:

<img width="1140" alt="image" src="https://user-images.githubusercontent.com/3729754/100460211-18585780-30c7-11eb-9675-f3204d462107.png">

**Comment by j-dimension** [comment]
Ich teste bis 13 Zoll runter, auf allen drei Betriebssystemplattformen. So eine Skalierung wie von @Mucki526 habe ich bisher noch nicht gesehen. Vermutlich sind entweder im j-lawyer oder im Betriebssystem die Schriftgrößen nach oben angepasst worden.

**Comment by Mucki526** [comment]
Ich habe halt jetzt ein gigantisches Notizfeld bis zum Horizont, wäre kein Problem, wenn der Trennbalken nach unten verschiebbar wäre. Ist ein ASUS Bildschirm, nix exotisches.... Keine exotischen Einstellungen..... Schriftgrößen Skalierung J-Lawyer ist 3
[j-lawyer-Auflösung Bildschirm.pdf](https://github.com/jlawyerorg/j-lawyer-org/files/5608406/j-lawyer-Auflosung.Bildschirm.pdf)

**Comment by j-dimension** [comment]
> Schriftgrößen Skalierung J-Lawyer ist 3

Dann müsste erstmal wieder auf die Normalskalierung gewechselt werden, da ich - solange keine gravierenden Fehler gemeldet werden - so schnell kein neues Release mache. 

Muss erstmal durchatmen :-)

**Comment by Mucki526** [comment]
Ich ging davon aus, dass ich die j-lawyer Normalskalierung 3 habe, dann gibt es noch die Normalskalierungen 1, 2, 4, 5.. je nach Bedarf... Was ist "normal" (in dem Zusammenhang) :-)???

**Comment by Mucki526** [comment]
Wenn normal = 0 ist, ändert sich an der Skalierung des Notizfensters nix, nur die Etiketten werden Kleiner, dann sehe ich halt eine halbe Reihe mehr (aber dafür Altersbedingt nicht mehr unangstrengt die Buchstaben. Die sehen jetzt aus wie auf einem 13 Zoll Apple ohne Retina Display, also muss ich zurück zur 3er-Skalierung...

**Comment by j-dimension** [comment]
Die Normalskalierung ist die 0:

<img width="298" alt="image" src="https://user-images.githubusercontent.com/3729754/100465437-96b8f780-30cf-11eb-8c13-3bb0aeb946bd.png">

Die Änderung erfordert einen Neustart.

**Comment by j-dimension** [comment]
Trenner / split pane eingebaut.
