### ISSUE TITLE
[FEATURE] Sortiersymbole oberhalb der Dokumentenliste sind etwas groß

### ISSUE THREAD

**Issue by iradraconis** [jlawyerorg/j-lawyer-org#977]
und zwar so groß, dass der Teiler für das Vorschaufenster nicht weiter nach links geschoben werden kann. Auf meinem "kleinen MacBook 13 Zoll" passt die Vorschau einer HTML Notiz meist nicht in der Fenster und muss gescrollt werden. Wenn der Teiler etwas mehr nach links gezogen werden könnte, wäre das wieder passend zu machen.

**Comment by j-dimension** [comment]
Der Trenner lässt sich nur so weit nach links ziehen, wie es die nicht "variable skalierenden" Elemente auf der linken Seite zulassen. Das sind in dem Fall die Sortierbuttons. 

Ich habe jetzt eine Änderung vornimmt, die für die nicht aktiven Sortierbuttons nur noch ein Icon anzeigt. Das reduziert die Minimalgröße von 565 auf 359 Pixel. Das sollte helfen. 

vorher / nachher: 
![grafik](https://user-images.githubusercontent.com/3729754/100524386-099d9d80-31b8-11eb-8c4d-365938a186db.png) 
![grafik](https://user-images.githubusercontent.com/3729754/100524403-2afe8980-31b8-11eb-9e46-2e5bae21adf5.png)
![grafik](https://user-images.githubusercontent.com/3729754/100524408-394ca580-31b8-11eb-9511-f6c36a38b409.png)

**Comment by iradraconis** [comment]
sieht nach einer guten Lösung aus
