### ISSUE TITLE
Liste der Dokumente

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-org#979]
Die Liste der Dokumente streckt sich immer über das gesamte Fenster. Bei meinen großen Bildschirm habe ich bei wenigen Dokumenten riesig breite farbige Streifen. Es wäre IMHO besser, wenn die Streifen sich am oberen Rand orientierten und eine normierte oder dynamische Breite hätten, damit die Liste bei wenigen Dokumenten nicht so "auseinandergerissen" ist...

**Comment by j-dimension** [comment]
Duplikat von #965

**Comment by iradraconis** [comment]
dazu gibt es bereits ein Ticket

> Duplikat von #965

wollt ich grad schreiben, aber wenn der Jens so schnell ist, keine Chance! :)
