### ISSUE TITLE
Anhang entfernen

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-org#98]
Meine Frau will gerade von einer kurz vor der Absendung befindlichen e-mail noch einen Anhang nicht mitsenden, ihn also entfernen. Das geht nicht. Also - ganze e-mail neu, Text kopieren etc. Es sollte möglich sein, einen bereits angehängten Anhang auch vor der Versendung wieder zu entfernen.

**Comment by j-dimension** [comment]
Umgesetzt
