### ISSUE TITLE
[BUG] Installation auf Server - /bin/sh^M: bad interpreter: No such file or directory

### ISSUE THREAD

**Issue by PBaumfalk** [jlawyerorg/j-lawyer-org#980]
Scheint ein Problem bei der Installationsdatei zu sein.

./j-lawyer-server_unix_1_13_0_20.sh: /bin/sh^M: bad interpreter: No such file or directory

**Comment by PBaumfalk** [comment]
Erledigt, der Mac hat die Server-Datei zerschossen beim Upload

**Comment by j-dimension** [comment]
Nasty little thing!
