### ISSUE TITLE
Dokument ausblenden wenn es in ausgeblendeten Ordner verschoben wird

### ISSUE THREAD

**Issue by Maz111111** [jlawyerorg/j-lawyer-org#982]
Vielen Dank für die neue Version!

Ich weiß nicht ob dies ein Bug oder eine Erweiterung ist.

Wenn ich Dokumente in einen Ordner verschiebe, den ich vorher ausgeblendet habe, bleiben diese zunächst sichtbar und verschwinden erst, wenn ich den ausgeblendeten Ordner zunächst wieder einblende und dann erneut ausblende.

Ich glaube, der Anwender erwartet, dass mit dem Verschiebevorgang das Dokument dann auch sofort verschwindet.

**Comment by j-dimension** [comment]
Hatte ich drin gelassen, damit der Nutzer ein Feedback erhält und sehen kann, ober nicht aus versehen eine Zeile weiter oben oder unten erwischt hat und die Dokumente im falschen Ordner sind. 

Kann das aber auch direkt verschwinden lassen. Vielleicht kann noch jemand anderes eine Perspektive dazulegen.

**Comment by Maz111111** [comment]
Na wenn es direkt verschwindet, merkt man ja, ob das falsche noch da ist oder nicht...aber grundsätzlich kann ich Deine Intention nachvollziehen.

Mal sehen, was die anderen sagen.

**Comment by j-dimension** [comment]
> Na wenn es direkt verschwindet, merkt man ja, ob das falsche noch da ist oder nicht...

Mir geht es mehr um den Fall dass man beim Zuordnen den falschen Ordner anklickt. Das würde man dann u.U. nicht mitbekommen, wenn dieser Ordner ausgeblendet ist.

**Comment by stm9x9** [comment]
Ich bin am überlegen, ob es nicht umgekehrt sogar besser wäre, wenn der Zielordner - wenn er ausgeblendet ist - eingeblendet wird, damit man sieht, daß die Datei jetzt am - hoffentlich - gewünschten Ort ist und damit nicht die Irritation von @Maz111111 auftritt: huch, die Datei sollte doch jetzt hier weg sein!?

**Comment by Maz111111** [comment]
Also ich verschiebe zum Beispiel die beA Datei die beim Absenden in der Akte gespeichert wird in einen besonderen Ordner, weil ich sie zwar haben will aber nicht in der normalen Dokumentenstruktur brauche.

Wenn ich die verschiebe, soll sie augenblicklich weg sein und nicht erst nachdem ich den zuvor schon ausgeblendeten beA Ordner erst mit Klick wieder einblende und dann mit weiterem Klick wieder ausblende.

Und das sollte auch bei allen anderen Files so sein. Die Befürchtung die @j-dimension beschrieben hat, haben dann offenbar alle Entwickler von Betriebssystemen nicht gehabt. Ich finde das übertrieben. Die Datei ist ja nicht weg und über das Einblenden aller Ordner sieht man sie dann auch sofort wieder und kann eventuelle Fehler sofort erkennen und korrigieren.

Sollte ich die (falsch) verschobene Datei nicht vermissen, ist es sowieso egal, wo sie liegt.  

So zumindest mein Gedankenstand heute...mal sehen, was ich denke, wenn es das erste Mal passiert ist .-)

**Comment by j-dimension** [comment]
> Die Befürchtung die @j-dimension beschrieben hat, haben - soweit ich das sehe - Entwickler von Betriebssystemen nicht gehabt.

Ist nicht so, dass ich das im bösen Willen tue, und nicht alles was hinkt ist ein Vergleich :-)

Ein Betriebssystem erlaubt auch keinen Einblick in mehrere Ordner gleichzeitig. Verdammt, für dieses Feature wird mir @stm9x9 irgendwann Schmerzensgeld zahlen müssen.

**Comment by stm9x9** [comment]
> Ein Betriebssystem erlaubt auch keinen Einblick in mehrere Ordner gleichzeitig. Verdammt, für dieses Feature wird mir @stm9x9 irgendwann Schmerzensgeld zahlen müssen.

pah! Falsches Betriebssystem!

![image](https://user-images.githubusercontent.com/29924198/101688551-7cd2c980-3a6c-11eb-8b38-c4198fbbae75.png)

**Comment by j-dimension** [comment]
wie folgt:


https://user-images.githubusercontent.com/3729754/113063042-f4ac3780-91b4-11eb-8977-1972cb24ce63.mp4
