### ISSUE TITLE
[FEATURE] Klick auf Symbol in der Desktopansicht am oberen Bildschirmrand oder unten in der Statusleiste löst Wechsel zum jeweiligen Fenster aus

### ISSUE THREAD

**Issue by Maz111111** [jlawyerorg/j-lawyer-org#983]
Wenn ich z.B. einen Scan- und oder Mail- beA- etc-eingang habe, wird dieser auf dem Desktop beim jeweiligen Symbol und unten in der Statuszeile des Fensters mit einer Zahl dargestellt.

Ich hatte es wohl noch nie vorher probiert. Jedenfalls habe ich erwartet, dass mich ein Klick auf das jeweils mit Zahl versehene Symbol z.B. zum Scaneingang bringt.

Wenn ich auf das News Symbol oben oder unten klicke komme ich ja auch zu den News.

Nur Kosmetik.

**Comment by j-dimension** [comment]
Das sind tatsächlich nur Anzeigen. Der Zugriff ist links über das Menü ja jederzeit möglich. 

Die News sind eine Ausnahme, weil sie ja sonst an keiner anderen Stelle verfügbar sind. 

Hier möchte tatsächlich keinen Aufwand investieren. Okay?

**Comment by Maz111111** [comment]
klaro!
