### ISSUE TITLE
Warnung bei Löschen von Ordnern: "enthaltene Dokumente werden gelöscht" o.ä.

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-org#985]
Ich weiß nicht ob das ein Bug ist ....  Wenn ich eine Datei einem Unterordner zuordne und dann diesen Ordner in der Ordnerstruktur wieder entferne, verschwindet die diesem Unterordner zugeordnete Datei ohne Warnung still und leise ins Nirwana. Ich dachte irrig, die Dateien liegen dann einfach weiter im Hauptverzeichnis, weil sich das Konzept der Unterordner für mich gefühlt an "Etiketten / Tags" anlehnt. 

Es hätte auch ein Odner mit 50 Dateien sein können, die weg sind, nur weil ich (versehentlich oder absichtlich) den Unterordner mit einem Klick gelöscht habe. Mein Vorschlag bei der Löschung des Unterordner werden die Dateien, die keine "Heimat" mehr haben automatisch wieder dem (unlöschbaren) Dokumentenordner zugeordnet. Oder es gibt zukünftig eine Papierkorbfunktion oder einen "Letzte Funktion rückgängig - war bullshit" -Button.
Im Moment ist´s brandgefährlich.

**Comment by j-dimension** [comment]
@stm9x9, übernehmen Sie.

**Comment by Maz111111** [comment]
Ich hab es jetzt nicht probiert, zu reproduzieren...aber ich habe bisher auch den Eindruck, dass sich die Ordner stark an der Etikettenvergabe orientieren und wäre erstmal auch davon ausgegangen, dass das Löschen eines "Ordners" keinen Einfluss auf den Verbleib der Datei hätte.
Wäre bei echten Ordner natürlich anders und auch erwartungsgemäß.
Allerdings verhält sich das Ordnersystem in jL irgendwie mehr wie ein Tag. -> Dieses Dok ist eine Mail, wenn Anwender den Tag "Mail" ausblendet, werden Dateien mit diesem Tag nicht mehr angezeigt. Löscht Anwender den Tag "Mail" verlieren die jeweiligen Doks eben den Tag - mehr nicht.
Gut zu wissen, dass es nicht so ist.

**Comment by j-dimension** [comment]
> ich habe bisher auch den Eindruck, dass sich die Ordner stark an der Etikettenvergabe orientieren

Darf ich fragen warum? Weil man mehrere Ordner mit einem mal einsehen kann?

**Comment by Maz111111** [comment]
Hmmm....gute Frage...ALSO:
Unter Windows kann ich eine Datei in einen Ordner entweder verschieben oder kopieren. Wenn ich unter Windows eine Datei in einen Ordner verschiebe, ist sie im alten (Ursprungs-) Ordner für den User schlicht und ergreifend weg.
Bei jL verschiebe ich eine Datei aber sie bleibt "da". Erst ein weiteres Zutun macht sie "weg" und beim nächsten Laden der Akte ist sie wieder im "Dateibaum" da. (Ich verwende bewusst jetzt mal nicht die Worte "sichtbar" und "unsichtbar" bzw. "ein- und ausgeblendet") Das fühlt sich komisch an. Eben so, als ob sie "physisch" gar nicht verschoben wurde, sondern eben nur mit dem Hinweis versehen wurde, "du bist jetzt eine Datei, die zu dem und dem "Ordner" gehört". 
Es drängt sich nicht der Eindruck auf, dass bei Löschen dieses "Hinweises" auch die gesamte Datei gelöscht würde.
Es wäre ein anderes Bewusstsein, wenn sich die Ordnerstruktur so verhalten würde, wie man es von - ich glaube jedem - Betriebssystem gewohnt ist - wobei ich glaube zu wissen, dass der tatsächliche rein physische Verschiebevorgang auf einer HD wohl genauso abläuft - die Datei bekommt nur einen Tag wird aber nicht in einen anderen Cluster verschoben - hier mag ich aber auch falsch liegen.
Vielleicht kann man das nachempfinden

**Comment by Maz111111** [comment]
Das soll aber nicht dazu führen, irgendwas grundlegendes zu ändern.

Aktuell bin ich der Ansicht, dass die Ordnersache in jL schon hervorragend gelöst ist.

**Comment by j-dimension** [comment]
@Maz111111 danke für die Erklärung. Das bestätigt meine Annahme. Letztlich verhält sich die Umsetzung wie Ordner im Betriebssystem - eine Datei kann nur in einem Ordner sein, und das Entfernen eines Ordners löscht alles darin. 

Es war für die Umsetzung eine explizite Anforderung (@stm9x9), mehrere Ordner mit einmal einsehen zu können. 

Daher hatte ich den User auch weiter oben bereits versucht ins Boot zu holen (in diesem Ticket). 

Ich könnte - als einfache Umsetzung - einen Hinweis einbauen, der bei Löschen eines Ordners warnt, dass die Dokumente damit gelöscht werden.

**Comment by Maz111111** [comment]
Eine Sicherheitsabfrage vor dem Löschen eines Ordner würde - falls es eine solche noch nicht gibt - ohnehin nicht schaden. In dieses Abfragefenster sollte der Hinweis auf das Löschen der enthaltenen Dateien dann auch exponiert aufgenommen werden.

Im Betriebssystem ist es doch so dass immer der Hinweis kommt " Achtung! Ordner nicht leer. Trotzdem löschen? Dateien werden damit endgültig gelöscht"

Sowas wär doch dann gut.
