### ISSUE TITLE
Unterstützung für Nextcloud-Installationen in Unterverzeichnis des Webservers

### ISSUE THREAD

**Issue by nronk** [jlawyerorg/j-lawyer-org#987]
Bei der Einrichtung eines Nextcloud Servers wird offenbar ausgeschlossen, dass sich der Nextcloud-Server in einem Unterverzeichnis der Domain befindet.

https://meinnextcloudserver.de - scheint zu funktionieren
https://meinserver.de/nextcloud - funktioniert nicht

**Comment by j-dimension** [comment]
@nronk ich habe keine solche Installation und kann es somit nicht testen - wäre es möglich dass ich einen Testnutzer für eine bestimmte Zeit zur Verfügung gestellt bekomme?

**Comment by nronk** [comment]
Klar, gern. Einen speziellen Wunsch was den Usernamen angeht?Am 30.11.2020 13:51 schrieb Jens Kutschke <notifications@github.com>:

@nronk ich habe keine solche Installation und kann es somit nicht testen - wäre es möglich dass ich einen Testnutzer für eine bestimmte Zeit zur Verfügung gestellt bekomme?

**Comment by j-dimension** [comment]
"homersimpson"

Nein, Quatsch - der Username ist mir egal.

**Comment by j-dimension** [comment]
![grafik](https://user-images.githubusercontent.com/3729754/100672529-5e7d1780-3362-11eb-8ccc-914cb15edffa.png)

**Comment by j-dimension** [comment]
Fertiggestellt. Ich würde den Testuser gern behalten bis zur offiziellen Testphase der 1.14. Vielen Dank vorab.

**Comment by nronk** [comment]
Gern. Sei mein Gast.

**Comment by j-dimension** [comment]
@nronk vielen Dank für die Unterstützung, der Testnutzer kann nun gern entfernt werden.
