### ISSUE TITLE
[FEATURE] der Status eines Ordners sollte für jede Akte gespeichert werden

### ISSUE THREAD

**Issue by Maz111111** [jlawyerorg/j-lawyer-org#988]
Wenn man in einer Akte einen Ordner ausblendet und die Akte schließt, wird der Ordner beim nächsten Laden der Akte wieder eingeblendet.

Die Akte sollte sich merken, welchen Status die jeweiligen Ordner hatten.

Ggf. kann man beim Anlegen der Ordner auch schon festlegen, dass dies ein standardmäßig ausgeblendeter Ordner ist.

**Comment by j-dimension** [comment]
Kann ich machen. Das wird dann aber nicht nutzerspezifisch gespeichert. Einer für alle, alle für einen.

**Comment by stm9x9** [comment]
wenn möglich, würde ich hier für eine akten- und benutzerspezifische Speicherung plädieren. Der Anwalt mag sich um die zweite Instanz kümmern, die Reno aber gerade um die Abrechnung.

**Comment by j-dimension** [comment]
> akten- und benutzerspezifische Speicherung

möchte ich noch nicht zusagen. 10 000 Akten, jeweils 15 Ordner, Kanzlei mit 10 MA --> 1,5 Mio Datensätze für dieses eine Feature.

**Comment by Maz111111** [comment]
Hab nochmal nachgedacht...es müsste akten- und nutzerspezifisch gespeichert werden.

Meine MA braucht andere Ordner als ich. 

Es ginge zwar sicher auch so wie von @j-dimension dargestellt. Ich befürchte aber, dass es dann eine "verschlimmbesserung" wird.

Jedes Mal wenn meine MA die Akte in der Hand hat, muss sie sich Ihre Sichtbarkeitsstruktur zurechtklicken. Entweder stellt sie sie danach wieder auf meine Sichtbarkeitsstruktur zurück oder ich habe die Arbeit, wenn ich die Akte wieder öffne.

Wäre im günstigsten Fall keine Veränderung zum IstZustand und im ungünstigsten Fall eine Verschlechterung wegen mehr Aufwand.

**Comment by stm9x9** [comment]
> > akten- und benutzerspezifische Speicherung
> 
> möchte ich noch nicht zusagen. 10 000 Akten, jeweils 15 Ordner, Kanzlei mit 10 MA --> 1,5 Mio Datensätze für dieses eine Feature.

aber auch nur, wenn jeder der 10 MA jede der 10.000 (whoot?) Akten benutzt!?

Und reicht nicht ein Datensatz pro Akte/Nutzer mit der Sichtbarkeit der 15 Ordner oder muß das für jeden Ordner atomar abgespeichert werden?

**Comment by j-dimension** [comment]
> Und reicht nicht ein Datensatz pro Akte/Nutzer mit der Sichtbarkeit der 15 Ordner oder muß das für jeden Ordner atomar abgespeichert werden?

Es muss für jeden Ordner atomar abgespeichert werden, damit eine Abfragemöglichkeit per SQL gegeben ist.
