### ISSUE TITLE
Umbenennung einer Datei

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-org#989]
Wenn man beim Umbenennen einer Datei nicht die Bezeichnung sondern nur Groß und Kleinschreibung eines Buchstabens in der Bezeichnung ändern will (anklicken, falschen Buchstaben ersetzen), den Namen der Datei aber im übrigen nicht ändert, geht das nicht, (WOrt bleibt WOrt und wird nicht zu Wort). Umbenennung WOrt zu Name und dann Umbenennung Name zu Wort geht aber....

**Comment by RA-crm** [comment]
Verstehe ich das richtig, der BUG wird in der 1.14 gefixt?
