### ISSUE TITLE
[FEATURE] [Oberfläche] Anpassbarkeit der Übersicht der Startseite

### ISSUE THREAD

**Issue by socram70** [jlawyerorg/j-lawyer-org#993]
**NOTE: Please search existing tickets to avoid duplicates **
**HINWEIS: Bitte vorab die Ticketsuche verwenden, um Doppeleinträge zu vermeiden **

Es wäre sehr schön, wenn man die aktuelle Ansicht (Aktenübersicht, Etikettenübersicht, Wiedervorlagen) speichern könnte. Momentan ist es so, dass bei jedem Start die Anischt zurückgesetzt wird und man die Größe der jeweiligen Boxen neu zurechtschieben muss. Auch ein Ausblenden einzelner Boxen (z. B. von Etiketten, die ich nicht nutze) wäre sehr praktisch.

**Is your feature request related to a problem? Please describe. / Welches Problem soll durch die Erweiterung / Verbesserung gelöst werden?**
Description / Beschreibung
Reines Komfortproblem

**Describe the solution you'd like / Beschreibe die gewünschte Lösung**
Description / Beschreibung
Anpassbarkeit der Übersicht der Startseite hinsichtlich Größe der Felder und Speicherung der angepassten Übersicht

**Additional context / Sonstiges **
Sonstige Informationen / Screenshots / ...

**Comment by j-dimension** [comment]
> Momentan ist es so, dass bei jedem Start die Anischt zurückgesetzt wird und man die Größe der jeweiligen Boxen neu zurechtschieben muss.

Das sollte für die 1.13 nicht mehr gelten, dort werden die Trennerpositionen gespeichert. Falls nicht, nochmal bescheid geben.

**Comment by socram70** [comment]
Das hatte ich probiert, bevor ich das Ticket aufgemacht habe. Das stimmt auch weitestgehend. Z. B. merkt er sich die Breite des Fensters für die Akten und Wiedervorlagen. Wenn ich aber z. B. den Teil mit den Etiketten komplett klein mache, merkt er sich das nicht.

**Comment by j-dimension** [comment]
> Wenn ich aber z. B. den Teil mit den Etiketten komplett klein mache, merkt er sich das nicht.

Hmm... das bekomme ich nicht reproduziert. Ist das Version 1.13.0.5? Welches Betriebssystem?

**Comment by socram70** [comment]
Genau, aktuelle Version 1.13.0.5 mit Windows 10 x64. Zwei verschiedene Instanzen. Beide mit dem gleichen Problem.

**Comment by j-dimension** [comment]
Dann mal das client.log per E-Mail senden.
