### ISSUE TITLE
Ordner verschwunden nach import von e-mail

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-org#995]
Ich habe eine e-mail versendet, aber nicht gleich dem Aktenordner des Mandanten zugeordnet. Dann bin ich in den Aktenordner und habe einen Unterordner Kostennoten angelegt. Kostennote reinkopiert. Dann bin ich zurück ins e-mail und importierte die e-mail in die Akte. Bei Rückkehr in die Akte war der Unterordner Kostennoten verschwunden, die Kostennote noch da, zugeordnet jetzt zu Dokument. Ich wollte also einfach nochmals den Ordner Kostennote anlegen (dachte ich hab was falsch gemacht) und die Kostennote zuordnen. Da hieß es, dass der Ordner mit diesem Namen schon existiert! (war aber nicht sichtbar im Verzeichnis). Also habe ich einen anderen Ordner angelegt, die Kostennote reinkopiert und den Ordner umbenannt - auf Kostennoten. Das ging jetzt, warum auch immer. Der kleine Zuordnungsbutton zeigte aber weiter den Namen des Ordners vor der Zuordnung. Einen refresh gab´s erst nach Ausstieg aus der Akte..... Ob das reprodzierbar ist... Ich melde es mal und beobachte das.

**Comment by j-dimension** [comment]
Damit kann ich erstmal wenig anfangen, ich benötige eine nachvollziehbare Abfolge von Bedienaktionen um es zu reproduzieren. 

Ich lasse das Ticket mal noch offen.
