### ISSUE TITLE
[FEATURE] [Ordner] überall die Möglichkeit geben, gleich in einen Ordner speichern zu können

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-org#999]
Wenn ich zb in einer beA-Nachricht eine Datei IN AKTE speichern will, wird sie jetzt im Hauptordner gespeichert und man muß sie dann hinterher in der Akte manuell verschieben. zb in "1. Instanz".

Es sollte nach Auswahl der Akte vor der Namensabfrage noch eine Auflistung der Ordner der Akte geben zum Auswählen.

folgende Stellen fallen mir ein, die das betrifft:

**beA**

Rechtsklick, in Akte speichern
rechts Seitenfenster: Akte suchen und zuordnen bzw über eine der Akten da, vollständige Nachricht, nur Anhänge etc

**Scans**

**Emails**

**Drebis**

Dokumentenliste einer Akte

Rechtsklick, in andere Akte kopieren

**Comment by j-dimension** [comment]
Dup von #939
